### ISSUE TITLE
Should autorotate: true be the default?

### ISSUE THREAD

**Issue by ioquatix** [libvips/libvips#1008]
It's tricky to do this correctly in a generic way.

I used `Vips::Image.new_from_file(..., autorotate: true)` and it works for lots of formats but fails for PDF: `VipsForeignLoadPdfFile: unknown option autorotate`

I feel like `autorotate: true` should just be the default for all formats that support it. It's probably what 99% of people want anyway.

**Comment by jcupitt** [comment]
We could move `autorot` into the base class for load so it was valid for all loaders, but ineffective if not supported. 

It's only supported for TIFF and JPG, so it would be mostly non-functional :(

**Comment by ioquatix** [comment]
What do you think of making it th default?

**Comment by jcupitt** [comment]
I think that would break a lot of stuff :(

**Comment by jcupitt** [comment]
8.8 makes autorot more harmless, so you can do `image.autorot` on anything, hopefully. 

Autorot on load is a bit weird anyway -- if you are shrinking, for example, you'll want to rotate after the shrink, not before. It can have a huge performance impact and you probably need to position it carefully in the pipeline.

I'll close ... let's make a new issue if anyone has a good idea on further improvements.
