### ISSUE TITLE
VipsForeignLoad fails to identify valid pdf

### ISSUE THREAD

**Issue by elated-berty** [libvips/libvips#1010]
new_from_file fails to identify valid pdf:
```
In [9]: f = 'bad_content_type.pdf'

In [10]: pyvips.Image.new_from_file(f, page=0, dpi=300)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-10-ee769458b885> in <module>()
----> 1 pyvips.Image.new_from_file(f, page=0, dpi=300)

/usr/local/lib/python2.7/dist-packages/pyvips/vimage.pyc in new_from_file(vips_filename, **kwargs)
    208         name = vips_lib.vips_foreign_find_load(filename)
    209         if name == ffi.NULL:
--> 210             raise Error('unable to load from file {0}'.format(vips_filename))
    211
    212         return pyvips.Operation.call(_to_string(ffi.string(name)),

Error: unable to load from file bad_content_type.pdf
  VipsForeignLoad: "bad_content_type.pdf" is not a known file format
```

but pdfload works properly if called directly:
```
In [11]: pyvips.Image.pdfload(f, page=0, dpi=300)
Out[11]: <pyvips.Image 2480x3507 uchar, 4 bands, srgb>
```

Unfortunately I can't include the pdf as it contains private information

**Comment by elated-berty** [comment]
I forgot to include that python's `mimetypes.guess_type` correctly recognizes this file.

**Comment by jcupitt** [comment]
Hello @elated-berty, 

My guess would be that your libvips has not been built with PDF support. You should see:

```
$ vips -l pdfload
          VipsForeignLoadPdfFile (pdfload), load PDF with libpoppler (.pdf), priority=0, is_a, get_flags, get_flags_filename, header, load
$ vipsheader nipguide.pdf 
nipguide.pdf: 595x841 uchar, 4 bands, srgb, pdfload
```

You may need to rebuild with poppler-glib or PDFium, depending on what your needs are.

**Comment by jcupitt** [comment]
Ooop, going too quickly, sorry, I just saw the second part of your message. Could you mail me the PDF privately? I'll investigate.

I guess other PDF files work correctly?

**Comment by jcupitt** [comment]
I came across this issue again. 

Looking at the source of `is_a` for pdfload, it just checks that the first four characters are `%PDF`. Perhaps your file has `%pdf`? Or something else? I checked the standard, and it specifies uppercase.

If this is still a problem, please reopen.
