### ISSUE TITLE
Assistance required for my project

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1011]
As a beginner to libvips, looks promising for my project:

I have a large tiff file (1400dpi, 34750 x 28400, 1 bit tiff) and my requirement is to cut a part of it (rectangle box) and do adjustments like shear, expand or shrink / expand  in horiz or vertical or both  by small value only, and replace this  modifed one in the original file. So that large tiff file should include that modified rectangle box, I am comfortable with bash. How this can be done using vips.
Also is it possible to shrink/expand like smaller values like 0.1 / 0.2 mm in one side alone (without aspect ratio), angle rotation by 0.5 degree.

**Comment by jcupitt** [comment]
Hello @vkkindia,

Is the TIFF tiled? That makes it easy to read out a small section without decompressing the whole thing.

**Comment by jcupitt** [comment]
I made you a tiny demo program:

```python
#!/usr/bin/env python

import sys
import pyvips

input_filename = sys.argv[1]
output_filename = sys.argv[2]
left = int(sys.argv[3])
top = int(sys.argv[4])
width = int(sys.argv[5])
height = int(sys.argv[6])

# a 2x2 matrix of the affine transform we apply
transform = [0.5, 0.1, -0.3, -0.5]

# scan the source image and decompress just the rect we want to a memory area
im = pyvips.Image.new_from_file(input_filename, access="sequential")
tile = im.crop(left, top, width, height)
tile = tile.copy_memory()

# add an alpha channel we can use to blend back with the source
tile = tile.bandjoin(255)

# and transform
tile = tile.affine(transform)

# pad the tile up to the size of the original image ... you might want to
# position the tile in some other way
overlay = tile.embed(left, top, im.width, im.height)

# scan the source image a second time ... now we will overlay the transformed
# tile
im = pyvips.Image.new_from_file(input_filename, access="sequential")

# ifthenelse will blend between the overlay and the original image
alpha = overlay[overlay.bands - 1]
pixels = overlay[0 : overlay.bands - 1]
im = alpha.ifthenelse(pixels, im, blend=True)

# and write back.
im.write_to_file(output_filename)
```

It should be reasonable quick, and it'll do any size image. It does keep the area being transformed in memory, but everything else is streamed.

You can run it like this:

```
$ vipsheader ~/pics/x.tif
/home/john/pics/x.tif: 37488x37488 uchar, 1 band, b-w, tiffload
$ time ./affine_box.py ~/pics/x.tif y.tif[compression=ccittfax4,squash] 100 100 10000 10000
real	0m24.680s
user	1m5.358s
sys	0m0.915s
```

And it runs in about 150mb of memory.

**Comment by vkkindia** [comment]
First thanks for the fastest reply, i will check this, how to apply slight
rotation eg 1degree or so.
Iam  good in bash scripts. Demo in bash pls.
Thanks,
Vkk

**Comment by jcupitt** [comment]
Sorry, it'd be very slow in bash. You need to use python/ruby/javascript/php/etc. for libvips to be quick.

**Comment by vkkindia** [comment]
Thanks i tied python script and worked.

When compared with abi and api, there is no difference in completion time,.
How can we improve the performance.

**Comment by jcupitt** [comment]
I'm glad it worked.

To improve performance, you need a benchmark. Exactly what kind of files are you running on, what parameters will you typically use, how much memory does your computer have, how many cores, etc. etc.

**Comment by vkkindia** [comment]
When affine transformation is applied, is there any formula to convert
input from angle to left, top.
 so that angle with respect to coordinates 0,0 angle will be converted to
pixels.

**Comment by jcupitt** [comment]
`similarity` will let you specify the affine transform as scale + rotate:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-similarity

Wikipedia has the formula:

https://en.wikipedia.org/wiki/Affine_transformation#Image_transformation

**Comment by vkkindia** [comment]
Hi,

Can i substitute
Tile = tile.similarity(angle = 10) instead of this

tile = tile.affine(transform)

What else I have to change. My requirements are, crop an area do some tilt
and paste in original same starting point, for padding  I need background
white.

Is there a way in bash for copy image to memory.

**Comment by jcupitt** [comment]
Sure, just swap affine for similarity. Experiment and read the docs, it should be easy.

No, it's not possible to do this in bash. You'd have to use very slow, huge files instead.

**Comment by vkkindia** [comment]
Thanks again, for chaining operations is any order necessary eg: resize and
rotate. which is the  first preference. What are your suggestions.

**Comment by jcupitt** [comment]
Affine will do resize, rotate, translate and skew all in one operation, so I'd just use that.

**Comment by vkkindia** [comment]
The requirement is not all images require all operations, some need reduce,
some enlarge, few needs rotation, then rotations+ ...
how can i define in affine, can I give 1 for resize, rotate 0, like that.
pls in python example.

**Comment by jcupitt** [comment]
You need to read that wikipedia page. A 2 x 2 matrix can do all those operations in one go.

**Comment by vkkindia** [comment]
> I made you a tiny demo program:
> 
> ```python
> #!/usr/bin/env python
> 
> import sys
> import pyvips
> 
> input_filename = sys.argv[1]
> output_filename = sys.argv[2]
> left = int(sys.argv[3])
> top = int(sys.argv[4])
> width = int(sys.argv[5])
> height = int(sys.argv[6])
> 
> # a 2x2 matrix of the affine transform we apply
> transform = [0.5, 0.1, -0.3, -0.5]
> 
> # scan the source image and decompress just the rect we want to a memory area
> im = pyvips.Image.new_from_file(input_filename, access="sequential")
> tile = im.crop(left, top, width, height)
> tile = tile.copy_memory()
> 
> # add an alpha channel we can use to blend back with the source
> tile = tile.bandjoin(255)
> 
> # and transform
> tile = tile.affine(transform)
> 
> # pad the tile up to the size of the original image ... you might want to
> # position the tile in some other way
> overlay = tile.embed(left, top, im.width, im.height)
> 
> # scan the source image a second time ... now we will overlay the transformed
> # tile
> im = pyvips.Image.new_from_file(input_filename, access="sequential")
> 
> # ifthenelse will blend between the overlay and the original image
> alpha = overlay[overlay.bands - 1]
> pixels = overlay[0 : overlay.bands - 1]
> im = alpha.ifthenelse(pixels, im, blend=True)
> 
> # and write back.
> im.write_to_file(output_filename)
> ```
> 
> It should be reasonable quick, and it'll do any size image. It does keep the area being transformed in memory, but everything else is streamed.
> 
> You can run it like this:
> 
> ```
> $ vipsheader ~/pics/x.tif
> /home/john/pics/x.tif: 37488x37488 uchar, 1 band, b-w, tiffload
> $ time ./affine_box.py ~/pics/x.tif y.tif[compression=ccittfax4,squash] 100 100 10000 10000
> real	0m24.680s
> user	1m5.358s
> sys	0m0.915s
> ```
> And it runs in about 150mb of memory.


Hi John,

I am converting code  from python to C, all the code except using ifthenelse is completed. How it can be done in C. 

# ifthenelse will blend between the overlay and the original image
alpha = overlay[overlay.bands - 1]
pixels = overlay[0 : overlay.bands - 1]
im = alpha.ifthenelse(pixels, im, blend=True)



####################
/* compile with:
 * 
 *gcc -g -Wall test.c  `pkg-config vips --cflags --libs ` -lm   -o test
  */
  
#include <stdio.h>
#include <vips/vips.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


static void
my_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
        const gchar *message, gpointer user_data )
{
}


int
main( int argc, char **argv )
{
	g_log_set_handler( "VIPS", G_LOG_LEVEL_WARNING| G_LOG_LEVEL_CRITICAL | G_LOG_FLAG_FATAL|G_LOG_LEVEL_MASK|G_LOG_LEVEL_ERROR, my_log_handler, NULL );
	VipsImage *in;
	VipsImage *tile;
	VipsImage *im;
	VipsImage *im_overlay;
	
	VipsImage *out_filename;
	int left;
	int top;
	int width;
	int height;
	double a_angle;
	double b_angle;
	double c_angle;
	double d_angle;
	
	out_filename =  argv[2];
	
	left = atoi(argv[3]);
	top = atoi(argv[4]);
	width = atoi(argv[5]);
	height = atoi(argv[6]);
	a_angle = 0.5;
	b_angle = 0.1;
	c_angle = -0.3;
	d_angle = -0.5;
	
	
	if( !(in = vips_image_new_from_file( argv[1], "access", VIPS_ACCESS_RANDOM, NULL )) )
    vips_error_exit( NULL );
    int im_width = vips_image_get_width(in);
    int im_height = vips_image_get_height(in);
    
	if(vips_crop(in, &tile, left, top, width, height, NULL))
	vips_error_exit( NULL );
	vips_bandjoin_const1(tile, &tile, 255, NULL);
	vips_affine(tile, &tile, a_angle, b_angle, c_angle, d_angle, NULL);
	vips_embed(tile, &im_overlay, left, top, im_width, im_height, NULL);
	
	if( !(im = vips_image_new_from_file( argv[1], "access", VIPS_ACCESS_RANDOM, NULL )) )
    vips_error_exit( NULL );
    
	//how to convert ifthenelse from python to C
	
	//# ifthenelse will blend between the overlay and the original image
	//alpha = overlay[overlay.bands - 1]
	//pixels = overlay[0 : overlay.bands - 1]
	//im = alpha.ifthenelse(pixels, im, blend=True)
	
	
	//if( vips_image_write_to_file( im, out_filename, NULL ) )
    vips_error_exit( NULL );
  
	return 0;
		
}

**Comment by jcupitt** [comment]
The docs are here:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-ifthenelse

So:

```C
if (vips_ifthenelse(alpha, pixels, im, &out, "blend", TRUE, NULL))
    vips_error_exit (NULL);
```

**Comment by vkkindia** [comment]
Thanks John, I require the equivalent for this also :

alpha = overlay[overlay.bands - 1]
pixels = overlay[0 : overlay.bands - 1]

**Comment by jcupitt** [comment]
That's `vips_extract_band()`:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-extract-band

```C
if (vips_extract_band (overlay, &alpha, overlay->Bands - 1, NULL) ||
    vips_extract_band (overlay, &pixels, 0, "n", overlay->Bands - 1, NULL))
    vips_error_exit (NULL);
```

**Comment by vkkindia** [comment]
Thanks john will try,  how to use without oops.
