### ISSUE TITLE
lcms2 not found when configure but lcms2 has been installed

### ISSUE THREAD

**Issue by shenhaofang** [libvips/libvips#1021]
When i try to configure in vips dir, I got a warning like this:
configure: WARNING: lcms2 not found; disabling ICC profile support
But when I try to yum install lcms2, I found lcms2-2.6-3.el7.x86_64 has been installed yet.

**Comment by jcupitt** [comment]
You need to install the lcms2 development files too. I think Red Hat calls the package `lcms2-devel`.

**Comment by jcupitt** [comment]
You've only installed the library -- to compile software, you need the headers as well. I think Red Hat calls the package `lcms2-devel`.
