### ISSUE TITLE
Add a properties

### ISSUE THREAD

**Issue by j6qup3fu3** [libvips/libvips#1024]
I used the command below to create a pyramid:
sudo vips tiffsave input.tiff output.tiff --compression=none --Q=90 --tile --pyramid

However, the tiff I created doesn't have the openslide.objective-power property.
How can I add the the porperty when I create the tiff file?
Thank you.

**Comment by jcupitt** [comment]
Hello @j6qup3fu3,

TIFF images don't really have an extensible set of properties, so libvips can't add them. If you want extra metadata on a tiff image, you'll probably have to carry the information somewhere else.

Could you explain what you are trying to achieve? Perhaps there's another way. 

I wouldn't use sudo to run vips. It should work without that.

**Comment by j6qup3fu3** [comment]
@jcupitt Thank you for your answer.

The tiff file from Philips and Trestle has the properties, and I thought that the tiff file which I created should have this property, too. 

I use openslide to get the value of openslide.objective-power. If I put the value in header or tag, I can't read them in the code with openslide. 

Is there another way to solve this problem?

**Comment by jcupitt** [comment]
You can't read them from the tiff with libvips (they just don't exist), but you can get them from the original slide. For example, with an SVS file:

```
john@kiwi:~/pics/openslide$ vipsheader -f openslide.objective-power CMU-1.svs
20
```

Are you planning to use the pyramid with iipimage and a web viewer? You could use a deepzoom pyramid instead. The deepzoom pyramid writer outputs some XML with all the properties in:

```
john@kiwi:~/pics/openslide$ vips dzsave CMU-1-Small-Region.svs x --properties
john@kiwi:~/pics/openslide$ ls x_files/
0  1  10  11  12  2  3  4  5  6  7  8  9  vips-properties.xml
john@kiwi:~/pics/openslide$ more x_files/vips-properties.xml 
<?xml version="1.0"?>
<image xmlns="http://www.vips.ecs.soton.ac.uk//dzsave" date="2018-07-02T09:30:26
.984865Z" version="8.7.0">
  <properties>
...
    <property>
      <name>openslide.objective-power</name>
      <value type="VipsRefString">20</value>
    </property>
...
  </properties>
</image>
```

**Comment by j6qup3fu3** [comment]
I mean I need to put the value into the tiff file, so that I can read this tiff file into the code(the code uses openslide to get the openslide.objective-power itself. If there is no openslide.objective-power property in the tiff file, there will be an error). 
Thus, I want to give the tiff file an openslide.objective-power property when I create it. 
Is there any way to do this?

**Comment by jcupitt** [comment]
libvips 8.7 has a new feature which sort-of addresses this.

If you give tiffsave the `properties` argument, it saves all the vips metadata to the `IMAGEDESCRIPTION` tiff tag as XML. You can then parse that XML to get `objective-power`.

For example:

```
$ vips copy CMU-1-Small-Region.svs x.tif[pyramid,tile,compression=jpeg,properties]
$ tiffinfo x.tif | grep -i objective
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
```

**Comment by j6qup3fu3** [comment]
Thanks for your answer. I tried to create the tiff file with the command, but when I used
vips copy CMU-1-Small-Region.svs **x.tif[pyramid,tile,compression=jpeg,properties]
, the command window shows that 
VipsForeignLoad: file "properties" not found
Where is the problem?
Thank you.

**Comment by jcupitt** [comment]
Are you using libvips 8.7? It's quite a new feature.

**Comment by j6qup3fu3** [comment]
@jcupitt 
When I install libvips 8.7, I use
 autoconf
, the command window shows 

configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:158: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:196: error: possibly undefined macro: AC_DEFINE
configure.ac:264: error: possibly undefined macro: AM_WITH_DMALLOC
configure.ac:306: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
configure.ac:349: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:359: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:454: error: possibly undefined macro: AC_CHECK_FUNCS
configure.ac:532: error: possibly undefined macro: AM_WITH_EXPAT
configure.ac:565: error: possibly undefined macro: AC_MSG_WARN
configure.ac:951: error: possibly undefined macro: AC_MSG_NOTICE
configure.ac:1275: error: possibly undefined macro: AM_PYTHON_CHECK_VERSION
configure.ac:1283: error: possibly undefined macro: AM_CHECK_PYTHON_HEADERS
cwlab@cwlab:~/leather/libvips-8.7.0$ ^C
cwlab@cwlab:~/leather/libvips-8.7.0$ m4_pattern_allow.

What is the problem?
Thank you.

**Comment by jcupitt** [comment]
You need to download the tarball, then use `configure`. 

https://github.com/libvips/libvips/releases

The install page has some notes:

https://libvips.github.io/libvips/install.html

**Comment by j6qup3fu3** [comment]
So,
$ vips copy CMU-1-Small-Region.svs x.tif[pyramid,tile,compression=jpeg,properties]
$ tiffinfo x.tif | grep -i objective
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
      <name>openslide.objective-power</name>
this method is convert the svs file into a tiff file with objective-power parameter?
Or I can create a tiff file from png and add the parameter to make it similar with svs file?

**Comment by jcupitt** [comment]
It writes all the metadata that vips knows about from the source image into the tiff.

You could load the PNG, set the `openslide.objective-power` field, then save, and it would be added to the tiff in the same way.

**Comment by j6qup3fu3** [comment]
How can I do this? 
When I use the method you mentioned I only turn the svs into tiff.
And if I use tiffsave load a png with the properties argument, it comes a tiff with no objective-power tag. 
How can I create a tiff with objective-power tag?
Thank you.

**Comment by j6qup3fu3** [comment]
How can I do this? 
When I use the method you mentioned I only turn the svs into tiff.
And if I use tiffsave load a png with the properties argument, it comes a tiff with no objective-power tag. 
How can I create a tiff with objective-power tag?
Thank you.

**Comment by jcupitt** [comment]
Could you explain why you need PNG? It's a very slow format. If you use `.vips` for an intermediate, the metadata will be carried over for you, and your program will be much faster.

If it must be PNG, you can't add the metadata at the command-line, you'd need to use one of the supported languages, so Python / Ruby / Javascript / PHP / C# / etc.

**Comment by j6qup3fu3** [comment]
@jcupitt  
I thing I can use .vips as the intermediate.
So if I turn the PNG file into .vips, I can add metadata to the file, right?
How can I do this?
With command line or Python is both OK for me.
Thank you.

**Comment by jcupitt** [comment]
You need to explain what you are trying to do. Where does this PNG come from? How does it relate to the SVS file?

**Comment by j6qup3fu3** [comment]
@jcupitt 
We have a code which can read svs files and have some progress to the file.
And now we have some png files, we want to use our code to do some progress on them.
Our code need the openslide.objective-power parameter to do the progress, but I can't find a method to turn the png files into tiff files with the parameter.
This is the reason why I need to now how to do it.
Thank you.

**Comment by jcupitt** [comment]
Well, in Python you could write:

```python
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])

x.set_type(pyvips.GValue.gstr_type, "openslide.objective-power", "12")

x.write_to_file(sys.argv[2])
```

Run like this:

```
$ python objective.py ~/pics/k2.png x.tif[pyramid,tile,compression=jpeg,properties]
```

Then the tiff has the extra metadata:

```
$ tiffinfo x.tif | grep objective
      <name>openslide.objective-power</name>
```
