### ISSUE TITLE
crop should start from top

### ISSUE THREAD

**Issue by bydbest** [libvips/libvips#1037]
Hello my image is more in height than width so when i use smartcrop , crop or all possible ways it gets resize from center and most of the part are cut. this is my sample image and i want to resize to 240x145 px but whatever i do it never does from top. i dont want to touch width but only cut 145 px from top and crop it.

![277out9](https://user-images.githubusercontent.com/771353/42897350-668fbcaa-8add-11e8-9e9f-6bf145483efb.jpg)

can u plz tell with vipthumbnails command it is possible or not.

**Comment by way2enjoy** [comment]
i dont have full sized image. i want any images to be cut from top instead of doing centering from middle of photos. i ttried smartcrop attention, none, entropy and centre options, trid crop option also but that did not help. i think there is no option in vipthumbnails to tell that plz start from top and crop 145 px and leave the bottom part. our interest is only top part . i am not intereted in smartcrop. i am just interested in cutting images top part. is it possible ??

**Comment by way2enjoy** [comment]
here it is .but i want crop from top irrespective of image .is is possible with vipthumbnails ?
![277](https://user-images.githubusercontent.com/21138551/42929886-0086f14a-8b59-11e8-9a9a-bc9fb79585a2.jpg)

**Comment by jcupitt** [comment]
It's seeing all the edges in the dress and thinks that must be what you want.

You'll have to crop yourself, for example:

```
$ vipsthumbnail dress.jpg -s 240x -o t1.v
$ vips crop t1.v thumb.jpg 0 0 240 145
```

Makes:

![thumb](https://user-images.githubusercontent.com/580843/42931302-48ec5172-8b37-11e8-9e1e-b132471db204.jpg)

**Comment by way2enjoy** [comment]
exactly what i wanted thanks. from top right 0,0 we are starting to move 240 horizontally and 145 vertically beautiful

**Comment by way2enjoy** [comment]
what if we wanted to move from bottom. wanted to cut bottom part starting from eight bottom or left bottom and go 145 up and 240 width.  sorry but want to clear everything

**Comment by jcupitt** [comment]
It depends on your platform. On linux, you could do:

```
vipsthumbnail $1 -s 240x -o t1.v
height=$(vipsheader -f height t1.v)
vips crop t1.v thumb.jpg 0 $((height - 145)) 240 145
```

Or in Python:

```python
thumb = pyvips.Image.thumbnail("dress.jpg", 240)
thumb = thumb.crop(0, thumb.height - 145, 240, 145)
thumb.write_to_file("thumb.jpg")
```

**Comment by jcupitt** [comment]
libvips 8.8 has a new feature for this -- you can now set `low` and `high` as well as `centre`. Low means position the crop at the low coordinate (top and left), high means at the high coordinate (right and bottom).

For example:

```
$ vipsthumbnail dress.jpg --smartcrop low --size 240x14
```

Makes:

![tn_dress](https://user-images.githubusercontent.com/580843/46571621-09a30980-c970-11e8-904e-1a6aa894e889.jpg)
