### ISSUE TITLE
VipsOperation: class "icc_import" not found 

### ISSUE THREAD

**Issue by korys** [libvips/libvips#1044]
Hi,
I'm using thumbnail function to resize images with PHP. It works in most cases but sometimes I get error:
`VipsOperation: class "icc_import" not found`
I suspect it's because I'm missing lcms library but is is really necessary? Can make thumbail function to ignore images' icc profile?

Docs say that this lib functions should be used only if available:

> lcms2, lcms
>If present, vips_icc_import(), vips_icc_export() and vips_icc_transform() are available for transforming images with ICC profiles. If lcms2 is available it is used in preference to lcms, since it is faster.

**Comment by jcupitt** [comment]
Hello, yes, it sounds like your libvips has been built without lcms2 support.

Yes, it should be able to thumbnail without looking at ICC profile, I think. Do you have an example image and command where it fails?

**Comment by korys** [comment]
Example image: 
https://cdn.51015kids.eu/product_picture/full_size/76c28d5dedbfdf71016b780bbfef47c7.jpg

Code:
`$sBuffer = file_get_contents('https://cdn.51015kids.eu/product_picture/full_size/76c28d5dedbfdf71016b780bbfef47c7.jpg');
$aOptions = array('size' => \Jcupitt\Vips\Size::DOWN);

	if (!is_null($this->__iNewHeight)) {
	    $aOptions['height'] = $this->__iNewHeight;
	}
	return \Jcupitt\Vips\Image::thumbnail_buffer($sBuffer, 1000, $aOptions)->copyMemory();`

**Comment by jcupitt** [comment]
That's a CMYK image and it has a 500kb ICC profile embedded in it. If you thumbnail it, the thumbnail will also have the 500kb profile and will be huge.

```
john@yingna ~/pics $ ls -l sample.jpg 
-rw-rw-r-- 1 john john 821904 Jul 24 14:42 sample.jpg
john@yingna ~/pics $ vipsthumbnail sample.jpg 
john@yingna ~/pics $ ls -l tn_sample.jpg 
-rw-r--r-- 1 john john 578712 Jul 24 14:43 tn_sample.jpg
```

So even though the image is now just 128 x 128 pixels, it's only a little smaller. Really, you need to transform to something like sRGB, and you'll need lcms for that.

**Comment by jcupitt** [comment]
I tried this test program:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$sBuffer = file_get_contents('https://cdn.51015kids.eu/product_picture/full_size/76c28d5dedbfdf71016b780bbfef47c7.jpg');

$aOptions = array('size' => 'down');
$out = Vips\Image::thumbnail_buffer($sBuffer, 1000, $aOptions)->copyMemory();
```

and it works for me with no errors.

```
john@yingna ~/pics $ ~/try/x.php 
john@yingna ~/pics $ 
```

**Comment by flesh404** [comment]
I have the same problem. I installed liblcms2-dev, but the error still occurs. Do I have to reinstall libvips again?
