### ISSUE TITLE
bandrank for z-depth image

### ISSUE THREAD

**Issue by zoranpopovic** [libvips/libvips#1046]
I'm wondering what is the easiest way to take a set on N images, and run a bandrank operation (e.g. get the max intensity), but instead of storing the intensities in the output image, to store the index (0 to N-1) of the image with the max value for each pixel.  

i can see running first bandrank and then comparing the output with each of the N images, and using the ifthenelse to assign the index value.  I wonder if there's a more elegant/efficient solution?

**Comment by jcupitt** [comment]
If your source images are 8 or 16 bit, you could store the image index in the bottom few bits.

For example, for an 8-bit image, left shift 8 bits to make a 16 bit image, OR the index into the bottom 8 bits, bandrank, AND out just the bottom 8 bits, you have an index.

**Comment by jcupitt** [comment]
(a bit of an ugly hack)

**Comment by zoranpopovic** [comment]
would it work to add another band for each image that just stores a constant index for each image, or can bandrank deal with just 1 band?

**Comment by jcupitt** [comment]
Each output band has the max (or min etc.) of the corresponding input bands, so no, I don't think that would work. 

I would store the index in the bottom few bots of the input. It should be quick and easy to implement. are you using Ruby? It would be (untested, plus I've spent the evening in the pub, oh dear):

```ruby
input_images = [im1, im2, im3]
input_with_index = input_images.each_with_index.map {|x, i| (x.cast("ushort") << 8) | i}
max_image = Vips::Image.bandrank(input_with_index, input_images.length - 1)
indexes = max_image & 0xff
```

Now each band of `indexes` has the index of the image with the maximum value in that band.

**Comment by zoranpopovic** [comment]
the python version of your suggestion worked.  Thanks.  I'm assuming that if we have more than 256 images in a stack, i'd have to cast to uint and keep the index map in the ushort image?

**Comment by jcupitt** [comment]
I'm glad it worked. 

Yes, use uint and hide the image id in the bottom few bits. You can use any number of bits, it doesn't need to be 8.
