### ISSUE TITLE
background for Deep Zoom format --layout dz 

### ISSUE THREAD

**Issue by JulesDoe** [libvips/libvips#1047]
In 'vips-dev-w64-all-8.7.0' (win 10) seems the background option broken for the dz layout.
'vips.exe dzsave world.200411.3x21600x10800.png world7 --depth onetile --layout dz --background 255'
yields no background fill.

'vips.exe dzsave world.200411.3x21600x10800.png world6 --depth onetile --layout google --background 255'
works fine.

Or maybe i am misinterpreting the documentation?
[https://github.com/jcupitt/libvips/blob/master/doc/Making-image-pyramids.md](https://github.com/jcupitt/libvips/blob/master/doc/Making-image-pyramids.md)

Thank you for the work on this great tool.

**Comment by jcupitt** [comment]
Hey, thanks for testing, I'll have a look.

I expect you know -- 8.7.0 is a pre-release, you should use 8.6.5 for production.

**Comment by jcupitt** [comment]
Yes, `background` is only used in google mode. 

Google layout has a minimum size of one tile, and does not allow half tiles, so if your source image is not exactly square, it must be padded out. The `background` parameter sets the colour that `dzsave` uses to pad out your image.

If you have a PNG with transparent elements and you want to save tiles as (for example) JPG with no transparency and a background colour, you need to give the background colour to the tile write option. 

For example:

```
$ vips dzsave PNG_transparency_demonstration_1.png x --suffix ".jpg[background=255 0 0]"
```

will flatten the PNGs to JPGs with a red background.

**Comment by JulesDoe** [comment]
Thank you very much for your incredibly fast answer.
So trying to add a padding around tiles is just something I should not do for Deep Zoom format?

**Comment by jcupitt** [comment]
DeepZoom images aren't padded -- they can be an exact size. 

If you want to add padding, you can put a border around the image before running dzsave. Something like:

```
vips gravity k2.jpg x.dz centre 10000 10000 --background "255 0 0"
```

Would centre the image in a 10k x 10k pixel red square, then make a deepzoom pyramid.

**Comment by JulesDoe** [comment]
Ah okay interesting, i will do it that way
thank you :)
