### ISSUE TITLE
Bandrank with numpy stack of images

### ISSUE THREAD

**Issue by soniaionescu** [libvips/libvips#1048]
Hello, I am attempting to use bandrank or ifthenelse to create a minimum intensity projection. My images are stored as a 3-dimensional numpy array, which I am turning into a vips image, performing either bandrank or using ifthenelse, and then turning back into a numpy array so that I can use scipy.misc imsave to save it as a tiff. I am not sure if I am misunderstanding these functions or how to call them. I rather than receiving a minimum or maximum intensity projection, as I expect, the output of my function is the correct dimension (2174 by 3504), but is a tiling of a lower resolution version of my image - it says that the number of bands of my vips image is 1, although I would expect it to be the number of 2d arrays in my 3d numpy array. I suspect that this - the conversion between 2d arrays to bands, and back - is where I am going wrong.

My code is as follows, where inputArray is a 3d numpy array and inputArray.shape (11L, 2174L, 3504L), (so there are 11 arrays which have height 2174 and width 3504) returns:

```
def useBandrank(inputArray):

    ## make 3d numpy array to pyvip image

    dtype_to_format = {

        'uint8': 'uchar',

        'int8': 'char',

        'uint16': 'ushort',

        'int16': 'short',

        'uint32': 'uint',

        'int32': 'int',

        'float32': 'float',

        'float64': 'double',

        'complex64': 'complex',

        'complex128': 'dpcomplex',

    }

    bands, height, width = inputArray.shape

    print inputArray.shape

    linear = inputArray.reshape(width * height * bands)

    print linear[1]

    pyVipImage = pyvips.Image.new_from_memory(linear.data, width, height, bands,

                                    dtype_to_format[str(inputArray.dtype)])

    ## use bandrank

    mipAsPyVip = pyvips.Operation.call('bandrank', pyVipImage, index = bands - 1)

    ## use ifthenElse

    #mipAsPyVip = reduce(lambda a, b: (a < b).ifthenelse(a, b), pyVipImage)

    ## back to numpy array

    format_to_dtype = {

        'uchar': np.uint8,

        'char': np.int8,

        'ushort': np.uint16,

        'short': np.int16,

        'uint': np.uint32,

        'int': np.int32,

        'float': np.float32,

        'double': np.float64,

        'complex': np.complex64,

        'dpcomplex': np.complex128,

    }

    mip = np.ndarray(buffer=mipAsPyVip.write_to_memory(),

                   dtype=format_to_dtype[mipAsPyVip.format],

                  shape=[mipAsPyVip.height, mipAsPyVip.width, mipAsPyVip.bands])

    ## return the numpy array

    mip = mip[:,:,0]

    imsave("bandRank.tiff", mip)

    return mip
```

Both the use of bandrank and the commented out us of ifthenelse create the same result, illustrated in the attached image.

In addition, how do I make sure it is a minimum rather than maximum projection? In [vips_bandrank](http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-bandrank) there is the int n argument, is there something similar in python?

I apologize for the lengthy question, just don't want to leave anything out!

Thanks,
Sonia

![bandrank](https://user-images.githubusercontent.com/16094886/43490577-21246686-94d6-11e8-982d-b6a692f3345c.jpg)

**Comment by jcupitt** [comment]
Hello, I made you a test program:

```python
#!/usr/bin/python

import sys
import time

import pyvips
from PIL import Image
import numpy as np
from scipy.misc import imsave

# map vips formats to np dtypes
format_to_dtype = {
    'uchar': np.uint8,
    'char': np.int8,
    'ushort': np.uint16,
    'short': np.int16,
    'uint': np.uint32,
    'int': np.int32,
    'float': np.float32,
    'double': np.float64,
    'complex': np.complex64,
    'dpcomplex': np.complex128,
}

# map np dtypes to vips
# oh dear str lookup ... is there a better way?
dtype_to_format = {
    'uint8': 'uchar',
    'int8': 'char',
    'uint16': 'ushort',
    'int16': 'short',
    'uint32': 'uint',
    'int32': 'int',
    'float32': 'float',
    'float64': 'double',
    'complex64': 'complex',
    'complex128': 'dpcomplex',
}

# numpy array to vips image
def numpy2vips(a):
    height, width, bands = a.shape
    linear = a.reshape(width * height * bands)
    vi = pyvips.Image.new_from_memory(linear.data, width, height, bands,
                                      dtype_to_format[str(a.dtype)])
    return vi

# vips image to numpy array
def vips2numpy(vi):
    return np.ndarray(buffer=vi.write_to_memory(),
                      dtype=format_to_dtype[vi.format],
                      shape=[vi.height, vi.width, vi.bands])

if len(sys.argv) < 3:
    print 'usage: {0} output-filename input1 input2 ...'.format(sys.argv[0])
    sys.exit(-1)

# load images as a set of 2D numpy arrays
arrays = [np.asarray(Image.open(name)) for name in sys.argv[2:]]

# make a set of vips images from the numpy arrays
images = [numpy2vips(x) for x in arrays]

# bandrank ... for each pixel, find the minimum 
mn = images[0].bandrank(images[1:], index=0)

# back to numpy and save
a = vips2numpy(mn)

print 'writing', sys.argv[1], '...'
imsave(sys.argv[1], a)
```

You can run it like this:

```
$ ../try270.py x.tif *.jpg
writing x.tif ...
```

And it'll load all the jpg images with PIL, for each pixel find the minimum with pyvips, and save the result as `x.tif` using scipy.

You can save from vips as well, of course, and skip the final conversion. Just use:

```python
mn.write_to_file("somefilename.tif")
```

**Comment by soniaionescu** [comment]
Hello,
Thank you so much - this was hugely helpful! 
Thanks again for the quick reply.
Best,
Sonia
