### ISSUE TITLE
vips_affine rotation 270 degrees on an odd sized image produces a pixel shift/movement right

### ISSUE THREAD

**Issue by angelmixu** [libvips/libvips#1051]
Hi!

I was just doing some stuff and didn't get to know why there was an image shifted to the right, so after digging and testing, looks like vips_affine when rotating leaves the image with a little displacement.

The final test was this one on the commandline on macOS, using homebrew, version 8.6.3:

`~/code/homebrew/bin/vips affine TesterRGB.tif tester_270.tif "0 -1 1 0"`

And these are the files.
[testerRGB_affine.zip](https://github.com/jcupitt/libvips/files/2256893/testerRGB_affine.zip)

If you open tester_270.tif, you will see that left column pixels are black (if you use a white background they would be white), and on the right column pixels is not the last one, there's a black column missing.

I've taken a look at vips_affine code, but I don't get what's wrong :(

Thanks!

**Comment by jcupitt** [comment]
Hi @angelmixu, I think it's corner vs. centre convention for affine. It's corner by default, set it to centre and the displacement should go.

**Comment by angelmixu** [comment]
Hi John!
I can't see any place for setting the cornering.
In the documentation there isn't any mention ( http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-affine ) nor on the command line, and on vips_affine_build (from affine.c on master branch ) I can't see anything related.

**Comment by jcupitt** [comment]
You set the input offset, so this is corner:

```
vips affine k2.jpg x.jpg "0 -1 1 0"
```

This is centre:

```
vips affine k2.jpg x2.jpg "0 -1 1 0" --idx 0.5 --idy 0.5
```

ie. displace input sampling by 0.5 pixels.

**Comment by angelmixu** [comment]
Oh, ok!

I've tested it and in this case it blurs the image, when it's an straightforward (squared?) rotation.

After adding nearest interpolator looks as it is the same image, but...
`$ ~/code/homebrew/bin/vips affine TesterRGB.tif tester_270_displaced.tif "0 -1 1 0" --background "255 255 255" --idx 0.5 --idy 0.5 --interpolate nearest`

I can see a white line on top of the image, and the bottom line is missing :/

Here's the image:
[tester_270_displaced_nearest.tif.zip](https://github.com/jcupitt/libvips/files/2257238/tester_270_displaced_nearest.tif.zip)

If I changed a little the displacement as follow:
`$ ~/code/homebrew/bin/vips affine TesterRGB.tif tester_270_displaced.tif "0 -1 1 0" --background "255 255 255" --idx -0.5 --idy 0.5 --interpolate nearest`

the result image looks like it's the correct one.

But if I invert the rotation:
`$ ~/code/homebrew/bin/vips affine TesterRGB.tif tester_270_displaced.tif "0 1 -1 0" --background "255 255 255" --idx -0.5 --idy 0.5 --interpolate nearest`

There appears a white column on the left, and a white line on the top, without the bottom and right ones.

[tester_270_displaced_nearest_inverted_rotation.tif.zip](https://github.com/jcupitt/libvips/files/2257251/tester_270_displaced_nearest_inverted_rotation.tif.zip)

What would be a generic solution? :/

**Comment by jcupitt** [comment]
8.10 includes a complete fix for this problem (hopefully). There's a test release here:

https://github.com/libvips/libvips/releases/tag/v8.10.0-beta2

I'll close.
