### ISSUE TITLE
Delete file after using vips_image_new_from_file 

### ISSUE THREAD

**Issue by abenchaaben** [libvips/libvips#1058]
Hi,

I'm loading a tiff file from disk with vips_image_new_from_file. After that i use the vips image to create a pyramids using vips_tiffsave. i want to delete the original tiff file after that but it seems that it vips_image_new_from_file continue to use it even after doing unrfon the vips image.

What did i missed?

thatnk you in advancec.

**Comment by jcupitt** [comment]
Hello, give access mode sequential when you open the tiff. 

If you don't, libvips will assume you need random access. It will decode the whole image, and keep the decoded image in a cache in case you need it again. 

With sequential mode, libvips will open the tiff for streaming. Once the tiffsave has executed, it'll finish the stream and you'll be able to close.

**Comment by abenchaaben** [comment]
Thank you jcupitt,
But, it didn't worked for me. Here what i did : 

VipsImage *image = vips_image_new_from_file(image_input_path.c_str(), "access", VIPS_ACCESS_SEQUENTIAL, NULL);
	vips_tiffsave(image, image_out_name.c_str(), "compression", VIPS_FOREIGN_TIFF_COMPRESSION_JPEG, "Q", 80, "tile", TRUE, "tile_width", 512, "tile_height", 512, "pyramid", TRUE, "bigtiff", TRUE, NULL);


	g_object_unref(image);
std::remove(image_input_path.c_str());

**Comment by jcupitt** [comment]
Huh strange. Sorry, I'm on holiday this week and don't have a Windows machine for testing. I'll have a look next week.

**Comment by kleisauke** [comment]
Are you testing it on Windows? If so, https://github.com/kleisauke/net-vips/issues/12 might be relevant here (on Linux it's fine).

**Comment by jcupitt** [comment]
I think you are right Klies. This is fixed in libvips 8.7 which should be out soon. There's a test build here:

https://github.com/jcupitt/libvips/releases/tag/v8.7.0-rc3

I would try that.

**Comment by jcupitt** [comment]
This should be fixed now. If this is still an issue in 8.7, please open a new issue.
