### ISSUE TITLE
Memory usage when VIPS claims everything is okay

### ISSUE THREAD

**Issue by Fingolfin1196** [libvips/libvips#1064]
Here I am again with another problem; I have defined the following operation (among other ones that work as intended):
```
#pragma once
#include <vips/vips8>

struct SimpleLeakOperation {
    VipsOperation parent_instance;

    VipsImage* in;
    VipsImage* out;

    double sigma_start;
    double sigma_end;
    double min_amplitude;
    unsigned segments;
};

typedef VipsOperationClass SimpleLeakOperationClass;

G_DEFINE_TYPE(SimpleLeakOperation, simple_leak, VIPS_TYPE_OPERATION);

static int simple_leak_build(VipsObject* object) {
    auto* bilateral = (SimpleLeakOperation*) object;

    if (VIPS_OBJECT_CLASS(simple_leak_parent_class)->build(object)) return -1;
    g_object_set(object, "out", vips_image_new(), nullptr);

    auto* input = bilateral->in;
    const auto sigma_start = bilateral->sigma_start;
    const auto sigma_end = bilateral->sigma_end;
    const auto min_amplitude = bilateral->min_amplitude;
    const auto segments = bilateral->segments;
    
    const auto sigma_step = (sigma_end - sigma_start) / segments;

    VipsImage* image{};
    if (vips_linear1(input, &image, 0.0, 0.0, nullptr)) return -1;
    VipsImage* image_copy{};

    for (unsigned i{0}; i <= segments; i++) {
        const auto sigma_low = sigma_start + i * sigma_step;
        
        VipsImage* blurred{};
        if (vips_gaussblur(input, &blurred, sigma_low, "min_ampl", min_amplitude, nullptr)) return -1;
        
        if (image_copy) g_object_unref(image_copy);
        image_copy = vips_image_new();
        if (vips_image_write(image, image_copy)) return -1;
        g_object_unref(image);

        if (vips_add(image_copy, blurred, &image, nullptr)) return -1;
        g_object_unref(blurred);
    }

    if (image_copy) g_object_unref(image_copy);
    if (vips_image_write(image, bilateral->out)) return -1;
    g_object_unref(image);

    return 0;
}

static void simple_leak_class_init(SimpleLeakOperationClass* bilateral_class) {
    typedef std::numeric_limits<double> limits;

    auto* g_object_class = G_OBJECT_CLASS(bilateral_class);
    auto* object_class = (VipsObjectClass*) bilateral_class;
    auto* operation_class = VIPS_OPERATION_CLASS(bilateral_class);

    g_object_class->set_property = vips_object_set_property;
    g_object_class->get_property = vips_object_get_property;

    object_class->nickname = "simple_leak";
    object_class->description = "Simple per-channel bilateral filter";
    object_class->build = simple_leak_build;

    operation_class->flags = VIPS_OPERATION_SEQUENTIAL;

    VIPS_ARG_IMAGE(bilateral_class, "in", 1, "Input", "Input image", VIPS_ARGUMENT_REQUIRED_INPUT, G_STRUCT_OFFSET(SimpleLeakOperation, in));
    VIPS_ARG_IMAGE(bilateral_class, "out", 2, "Output", "Output image", VIPS_ARGUMENT_REQUIRED_OUTPUT, G_STRUCT_OFFSET(SimpleLeakOperation, out));
    VIPS_ARG_DOUBLE(bilateral_class, "sigma_start", 3, "Sigma Start", "Sigma Start", VIPS_ARGUMENT_REQUIRED_INPUT, G_STRUCT_OFFSET(SimpleLeakOperation, sigma_start), 0.01, 1000, 1.5);
    VIPS_ARG_DOUBLE(bilateral_class, "sigma_end", 4, "Sigma End", "Sigma End", VIPS_ARGUMENT_REQUIRED_INPUT, G_STRUCT_OFFSET(SimpleLeakOperation, sigma_end), 0.01, 1000, 1.5);
    VIPS_ARG_DOUBLE(bilateral_class, "min_amplitude", 5, "Minimum amplitude", "Minimum amplitude", VIPS_ARGUMENT_REQUIRED_INPUT, G_STRUCT_OFFSET(SimpleLeakOperation, min_amplitude), 0.001, 1.0, 0.2);
    VIPS_ARG_INT(bilateral_class, "segments", 6, "Segments", "Segments", VIPS_ARGUMENT_REQUIRED_INPUT, G_STRUCT_OFFSET(SimpleLeakOperation, segments), 1, 1000, 8);
}

static void simple_leak_init(SimpleLeakOperation*) {
}

inline int vipsSimpleLeak(VipsImage* in, VipsImage** out, double sigma_start, double sigma_end, double min_amplitude, unsigned segments, bool get_type = true) {
    if (get_type) simple_leak_get_type();
    return vips_call("simple_leak", in, out, sigma_start, sigma_end, min_amplitude, segments, nullptr);
}

inline vips::VImage vipsSimpleLeak(const vips::VImage& in, double sigma_start, double sigma_end, double min_amplitude, unsigned segments) {
    VipsImage* output;
    const auto success = vipsSimpleLeak(in.get_image(), &output, sigma_start, sigma_end, min_amplitude, segments);
    if (success == 0) return vips::VImage(output); else return vips::VImage();
}
```
Basically, the image is blurred and then added onto the output image (which is handled with a separate copy, so that I am able to unref all intermediate steps). This is not supposed to be very useful, but a smaller version of another filter that exhibits the issues as well.
The ``main.cpp`` file I tested this in is as follows:
```
#include <chrono>
#include <thread>
#include <vips/vips8>
#include "SimpleLeakOperation.h"

using vips::VImage;
using std::chrono_literals::operator ""s;

#define PRINT_MEMORY(prefix) printf(#prefix ": %lu, %i, %i\n", vips_tracked_get_mem(), vips_tracked_get_allocs(), vips_tracked_get_files());

int main() {
    if (VIPS_INIT ("Test")) vips_error_exit(nullptr);
    vips_leak_set(true);
    vips_cache_set_max(0);
    const auto size = 1u << 10;
    for (unsigned i{0}; i < 6; i++) {
        std::this_thread::sleep_for(1s);
        PRINT_MEMORY(01)
        auto image = VImage::gaussnoise(size, size);
        PRINT_MEMORY(02)
        auto converted = vipsSimpleLeak(image, 4, 16, 0.05, 256);
        PRINT_MEMORY(03)
        if (!converted.data()) printf("No data!\n");
        PRINT_MEMORY(04)
    }
    std::this_thread::sleep_for(1s);
    PRINT_MEMORY(05)
    return 0;
}
```
The output is as follows:
```
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
01: 0, 0, 0
02: 0, 0, 0
03: 838336, 2056, 0
04: 5032656, 2057, 0
05: 0, 0, 0
memory: high-water mark 5.32 GB
```
So far, everything is as expected. This changes when the graph of the actual RAM usage of the system is considered (here as a screenshot from KSysGuard):
![memory](https://user-images.githubusercontent.com/16902662/44163279-3bf85f00-a0c3-11e8-885c-dd4d23f51181.png)
This is quite peculiar, since it looks like some kind of caching, which has been disabled; additionally, with some changed parameters, the dips can become more pronounced (increased size, e.g. ``size = 1u << 12``) or disappear entirely (more segments, e.g. ``converted = vipsSimpleLeak(image, 4, 16, 0.05, 800)`` with reduced size), and in the latter case, the memory usage can grow in successive bulges, which does not quite fit my “hidden cache” hypothesis.
I am quite baffled by this behaviour, but since the help I got last time was quick and effective, I hope for some explanation and would be very thankful for it.

**Comment by jcupitt** [comment]
Memory use drops right down if you limit the number of threads:

```
$ VIPS_CONCURRENCY=1 time ./a.out
01: 0, 0, 0
02: 0, 0, 0
03: 834944, 2048, 0
...
memory: high-water mark 440.90 MB
```

But of course it's slower too. 

As the pipeline evaluates (driven by your call to `.data()`), for each thread it'll have to repeatedly generate large areas of the gaussnoise image as input to the large radius blurs. This will need a lot of memory :(

**Comment by jcupitt** [comment]
I tried a python version of your code:

```python
import pyvips
    
def filter(im, sigma_start, sigma_end, min_amplitude, segments):
    step = (sigma_end - sigma_start) / (segments - 1)
    
    blurred = [im.gaussblur(sigma_start + i * step, min_ampl=min_amplitude)
               for i in range(0, segments + 1)]
    sums = sum(blurred)
    
    return sums

pyvips.leak_set(True)
pyvips.cache_set_max(0)
size = 1 << 10

for i in range(0, 6):
    image = pyvips.Image.gaussnoise(size, size)
    image = filter(image, 4, 16, 0.05, 256)
    print(image.avg())  
```

I see:

```
john@yingna ~/try $ time python3 fing.py 
32894.809413947165
32894.83548862301
32894.70023133047
32890.934275338426
32894.80602109991
32893.41500362381
memory: high-water mark 3.42 GB
```

The same runtime and memory use as for your code.

**Comment by Fingolfin1196** [comment]
I'm not sure if I made my main problem clear here; it is not about the amount of memory used, but rather about the memory that is not cleared after the image is removed (those plateaus between the “bulges”); mostly, these don't impact the height of subsequent bulges, but in extreme cases, they do (see the case where the dips disappear entirely). If I made that clear already, I'm not sure how your comments relate to that.

**Comment by Fingolfin1196** [comment]
Your interpretation of the filter is correct – I didn't use vips_object_local_array since I prefer seeing my unrefs when I debug.

**Comment by jcupitt** [comment]
Ah OK. Do you know what metric ksysguard is using? Usually the best is RES: the resident set size. That should go up and down as memory is freed, but heap fragmentation can prevent it. brk/sbrk/malloc and the virtual memory subsystems can interact in complex ways. 

Usually as long as the memory high water mark is not creeping up, there's no leak.

**Comment by Fingolfin1196** [comment]
The data that is plotted there is just called “Application Memory”, and I couldn't find any more precise documentation. If you know any better tool to track more specific data, I'd be happy to try it.
I know that it should, and the present behaviour is quite odd. I can plot an example where the memory usage grows visibly from one application of the filter to the next, if that would help to illustrate the problem.
KSysGuard is also able to create detailed memory usage tables for specific points in time, where the allocated parts of memory are listed, together with their source – except for the heap, where such an attribution is not possible; I have tried interpreting the heap data, but without any information apart from the amount of memory in the allocated segments, I failed. If that data might be of any help, I can share it as well.
Several tools (including the log from the first plot, valgrind's memcheck and the Google Leak Sanitizer) seem to agree that there are no leaks, but that doesn't change that some memory is being held after it should be freed, which strains the RAM unnecessarily and is quite problematic within my project.

**Comment by jcupitt** [comment]
I think it's just heap fragmentation. Memory pages are being kept if there's even a small active alloc somewhere in there.

I had a go using `ps` and RES and I got a fairly similar result to ksysguard when running the Python version:

![mem](https://user-images.githubusercontent.com/580843/44273427-60754800-a237-11e8-9660-45b36430698b.png)

Time in seconds horizontally, memuse vertically. Purple is peak RES, blue is RES.

**Comment by Fingolfin1196** [comment]
Am I to understand that this behaviour is normal, and there's nothing that can be done about it? This is certainly an issue in my project, which is quite memory-sensitive, and when an image is to be removed from memory, it should leave no traces.

**Comment by jcupitt** [comment]
Sorry, I think you are seeing heap fragmentation. 

Memory pages are 4kb, and the whole page must be kept in memory if the running program has any active allocations in that page. Imagine a program which allocated 10,000 3.9kb and 0.1kb pairs, then freed all the 3.9kb areas. Even though it now only has 1mb of memory allocated, it must keep 40mb of memory paged in (and visible to RES). This is just a general problem with any C or C++ library -- I don't think there's much that can be done. 

I've not tried to implement a bilateral filter myself. Perhaps the algorithm could be tuned in some way to get memory use down?

**Comment by Fingolfin1196** [comment]
Okay, well, if that's the case, I guess I'll see what I can do. This version of the bilateral filter is quite easy to implement, but apparently ill-suited to VIPS's system in its current form (since it is programmed to progressively add the iteration for the result).
I don't know if it might help to make the output a memory image, so that the iterations don't need to be performed after the fact; otherwise, the only thing that I could do would be to create the images for the separate steps and then perform a per-pixel filter, where each pixel chooses the relevant intermediate images and only queries those pixels (since each output pixel there is a blend of at most two intermediate images), though I'm not quite sure how best to approach that within VIPS's pipeline system. If you could perhaps advise me which of these approaches seems more reasonable to you, I think I can experiment myself (given the time).

**Comment by Fingolfin1196** [comment]
Thanks a lot for the hint! I tried both of these memory allocators, but at least in this (narrow) test, they don't seem to help much and mostly make things worse (unless I did something wrong, but hopefully and probably I haven't):
First test: `size = 1u << 8`, `converted = vipsSimpleLeak(image, 4, 6, 0.05, 256)`
![first](https://user-images.githubusercontent.com/16902662/44298698-ff597d00-a2e7-11e8-9fca-d9d9ddeccbf6.png)
Second test: `size = 1u << 11`, `converted = vipsSimpleLeak(image, 0.5, 1, 0.05, 64)`
![second](https://user-images.githubusercontent.com/16902662/44298705-0f715c80-a2e8-11e8-9963-6c6d4303aba8.png)
Third test: `size = 1u << 10`, `converted = vipsSimpleLeak(image, 1, 2, 0.05, 64)`
![third](https://user-images.githubusercontent.com/16902662/44298708-287a0d80-a2e8-11e8-81ae-f9617df5bea2.png)
Fourth test: `size = 1u << 10`, `converted = vipsSimpleLeak(image, 1, 4, 0.05, 64)`
![fourth](https://user-images.githubusercontent.com/16902662/44298773-76dbdc00-a2e9-11e8-8ba4-d6fad22a265c.png)
(In each graphic, the first part is the GNU default compiler, the second is `jemalloc`, the last `tcmalloc`.)
As can be seen, the behaviour of `tcmalloc` is markedly worse than the default, and `jemalloc` produces mixed results. I have also tried [Hoard](http://hoard.org/), but it seems to produce significantly worse results overall.

**Comment by jcupitt** [comment]
This might be relevant: https://github.com/libvips/libvips/pull/1240

@jtorresfabra found that threadpools were not releasing memory when they finished, but when the image they were defined on was freed. This meant that if you used the same image as the source many times, you could see memory use creep up.

git master libvips has a thing to free threadpool memory much more aggressively, it might make a small difference here.

**Comment by jcupitt** [comment]
This should be a little better in current libvips. Please open a new issue if there is still a problem.
