### ISSUE TITLE
binding for Crystal

### ISSUE THREAD

**Issue by proyb6** [libvips/libvips#1076]
I realise there was a small group of discussion on VIPS but hasn't made any progress. You could port from Ruby to Crystal with a few syntax change and we will have a good reason to choose Crystal and VIPS.

**Comment by jcupitt** [comment]
I had a quick look at Crystal. It seems very nice, but I think ruby-vips would need a bit of work to be ported across.

Ruby-vips uses run-time introspection to create method calls, and that won't work in Crystal. It would need to implemented more like the C++ or C# binding, where the available methods are enumerated in advance. 

I'll leave this issue open as an enhancement in case anyone fancies a go.

**Comment by proyb6** [comment]
@jcupitt I have came across libgen which seems to be useful for generate large API binding for Crystal quickly, I have no experience with this tool yet but may be useful for you.

https://github.com/olbat/libgen

**Comment by jcupitt** [comment]
The python binding used to be made with a tool a little like this (swig), but it was a bit unsatisfactory. The bindings you get are large and usually rather ugly.

I think the simplest solution would just be to make a small Ruby script to generate the Crystal binding from ruby-vips. You could copy most of ruby-vips over, then generate a little wrapper for each operator. 

For example, the C++ binding has this file:

https://github.com/jcupitt/libvips/blob/master/cplusplus/vips-operators.cpp

Generated by this bit of Python:

https://github.com/jcupitt/libvips/blob/master/cplusplus/gen-operators.py

**Comment by jcupitt** [comment]
Another example -- ruby-vips has `Vips::Yard.generate` to make the yard docs for the dynamically bound methods:

https://github.com/libvips/ruby-vips/blob/master/lib/vips/image.rb#L1433

It makes stuff like this:

https://github.com/libvips/ruby-vips/blob/master/lib/vips/methods.rb

You'd need to make something similar that generated the code for the dynamic methods at compile time.

**Comment by proyb6** [comment]
Thanks, I'm no longer using Crystal but Go language.

**Comment by jcupitt** [comment]
@naqvis has made a crystal binding here:

https://github.com/naqvis/crystal-vips
