### ISSUE TITLE
look at libnsgif

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1084]
It seems libnsgif is quite a bit better than giflib:

https://www.netsurf-browser.org/projects/libnsgif/

We should look into swapping our gif load library.

**Comment by jcupitt** [comment]
libnsgif uses the NetSurf build system and is awkward to make in isolation. Here's a fork of libnsgif with an autotools build system ready for adding to the libvips stack.

https://github.com/jcupitt/libnsgif

**Comment by jcupitt** [comment]
libvips branch for working on libnsgif support

https://github.com/jcupitt/libvips/tree/add-libnsgif-support

**Comment by kleisauke** [comment]
It seems that giflib recently removed the Autotools build system in favour of a hand-written Makefile. This will cause problems for cross-compilation.

GEGL (used by GIMP) seems to have moved to libnsgif (by [copying it to the libs folder](https://github.com/GNOME/gegl/tree/a07cbdf3c9fb5e78ce709d8950ab086e54ca2997/libs/libnsgif)). GDK-PixBuf is also considering switching to libnsgif: https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues/46.

**Comment by jcupitt** [comment]
Argh! How annoying.

I posted a begging note:

https://sourceforge.net/p/giflib/feature-requests/6/

Though I doubt if it'll help. I'll fix up the half-done libnsgif loader.

**Comment by jcupitt** [comment]
Branch with a half-done gif loader using libnsgif

https://github.com/libvips/libvips/tree/add-libnsgif

**Comment by lovell** [comment]
I'd be very happy to help test a libnsgif-based loader when it's ready to do so.

Recently I've experienced not only build system changes to giflib patch releases but also API/ABI breakages. Homebrew is pinned to giflib v5.1.4 due to these and the binaries provided by sharp are locked likewise.

https://sourceforge.net/p/giflib/bugs/132/
https://sourceforge.net/p/giflib/bugs/133/

**Comment by jcupitt** [comment]
And at least that second problem is because esr abandoned autotools, sigh.

I'll add fixing up that libnsgif loader to the to-do list. Unless anyone else fancies a go?

**Comment by jcupitt** [comment]
This branch now has a working GIF loader based on libnsgif:

https://github.com/libvips/libvips/tree/add-libnsgif

Decode speed is about the same, but the loader is MUCH simpler. The giflib one was 1600 lines of C (!!!!!) but this one is only 700. It should be more robust as well. The libnsgif API is very nice and well-designed.

Missing features:

- early close (should be simple to add)
- libnsgif does not support GIF comments (who cares)
- I think GIFs which use several GIF frames to update a single display frame will probably not work (needs a little more testing) 
- it always outputs RGBA images as libnsgif makes it hard to detect greyscale GIFs

Any testing welcome!

**Comment by jcupitt** [comment]
Oh, you must use libnsgif as installed by this:

https://github.com/jcupitt/libnsgif

Check in configure output for:

```
...
  (requires libimagequant)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with libnsgif:	yes
file import/export with giflib:		no (using libnsgif)
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			yes
...
```

Perhaps we should just copy the sources in. It would be simpler, and libnsgif seems very stable.

**Comment by lovell** [comment]
I've tried this branch against the sharp test suite and any failures relate to the output always being 4 channel RGBA where giflib was producing anywhere from 1-4 channels based on the input. Otherwise it all looks good :+1:

**Comment by jcupitt** [comment]
Great!

Yes, libnsgif makes it hard to check for mono vs. colour output, so I think it'll have to be RGBA always.

I've found some problems relating to frame vs. rect matchups. I think GIFs which use several zero-delay rects to update one display frame will not work, unfortunately.

I don't suppose anyone has an example GIF that does this?

**Comment by lovell** [comment]
https://en.wikipedia.org/wiki/GIF#/media/File:SmallFullColourGIF.gif

**Comment by jcupitt** [comment]
This gif fails with libnsgif, unfortunately:

![bird](https://user-images.githubusercontent.com/580843/86457777-18bd1400-bd1c-11ea-923a-adeed2eba031.gif)

It looks like dispose previous is not handled correctly. libvips master handles this one correctly (though didn't in 8.9).

Kleis suggested [gifdec](https://github.com/lecram/gifdec). I'll have a look.

**Comment by jcupitt** [comment]
Oh haha sigh gifdec reads the GIF file using 1,000s of read() and lseek() calls. It would need to be reworked to use (I suppose) VipsSource instead.

**Comment by jcupitt** [comment]
gifdec displays the bird correctly, but crashes with a segv for GIFs containing out of bounds image frames. I think it would need a bit of work to be useful to us.

**Comment by jcupitt** [comment]
Mail to the netsurf-dev list re. this possible dispose_previous bug:

https://listmaster.pepperfish.net/hyperkitty/list/netsurf-dev@netsurf-browser.org/thread/WSZO3YZOYBXBPSJNJWT6FNISIRF532HB/

**Comment by jcupitt** [comment]
I think I found the libnsgif bug: they don't handle restore + combine correctly. I offered a patch.

**Comment by jcupitt** [comment]
- libnsgif have fixed the bug.
- I've updated https://github.com/jcupitt/libnsgif with the fix.
- I've updated the libnsgif loader in this dev branch of libvips to the latest source API.

This is probably too late for 8.10. Let's look at merging this for 8.11.

**Comment by jcupitt** [comment]
There's a PR ready for merge with this change. I'll close.
