### ISSUE TITLE
Pdf to 1 bit tiff

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1087]
Good morning,
Using ghostscript for pdf to 1bit cmyk tiff.
How can I do with libvips, also the resultant TIFF file should be user controlled, for eg. convert a whole pdf with 50% dots and the requirement is like instead of 50% dot in tiff it should be 54%.
How can this calibration done in vips.
There should be a lookup table for c,m,y,k and different dot % like 5,10,20,30,40,50,60,70,80,90,95.
So the resultant tiff should carry this values.

**Comment by jcupitt** [comment]
Hello, 

Sorry, `pdfload` does not expose that kind of detail. I think you'll need to stick to ghostscript.
