### ISSUE TITLE
vips_gifload problem

### ISSUE THREAD

**Issue by wbtlb** [libvips/libvips#1088]
hi:
   i want read a gif file and format to webp ,when i use `vips_gifload` to load a gif file, i get a problem `VipsOperation: class "gifload" not found`.
    i am sure, i have install giflib and libvips libraries correctly. My giflib version is 4.x.
    
    #include <vips/vips.h>
    #include <vips/foreign.h>
    int main( int argc, char **argv )
    {
        VipsImage *in;
        VipsImage *out;
        if( VIPS_INIT(argv[0]))
            vips_error_exit(NULL); 
        if(argc != 3)
            vips_error_exit("usage: %s infile outfile", argv[0]); 
        if (!(in = vips_image_new_from_file( argv[1], NULL)))
            vips_error_exit(NULL);
        if (vips_gifload(argv[1], &out, NULL))
            vips_error_exit(NULL);
        if (vips_image_write_to_file(out, argv[2], NULL))
            vips_error_exit(NULL);
        return( 0 );
    }

any idea?

**Comment by jcupitt** [comment]
Hello @wbtlb,

i would guess your libvips is too old (gifload was added in 8.3), or it was built without gif support. 

If you built libvips yourself, check the output of configure. You'll need the giflib headers as well as the library.

**Comment by wbtlb** [comment]
hi：
     thanks for you reply. my libvips version is 8.6.5, and i built libvips by autogen.sh script.

**Comment by jcupitt** [comment]
Then you are missing the giflib headers. Check the output of configure (what you see `autogen` print as it runs).

**Comment by jcupitt** [comment]
It should find giflib automatically, you just need to install the headers.

**Comment by jcupitt** [comment]
Then perhaps you have two libvips installed?

After `make install`, verify that you are picking up the correct one.

```
john@katamata:~/GIT/build-osx/8.6$ which vips
/Users/john/vips/bin/vips
john@katamata:~/GIT/build-osx/8.6$ vips --version
vips-8.7.0-Wed Jun 13 20:06:37 UTC 2018
john@katamata:~/GIT/build-osx/8.6$ vips -l | grep -i gif
        VipsForeignLoadGif (gifload_base), load GIF with giflib, priority=0
          VipsForeignLoadGifFile (gifload), load GIF with giflib (.gif), priority=0, is_a, get_flags, get_flags_filename, header
          VipsForeignLoadGifBuffer (gifload_buffer), load GIF with giflib, priority=0, is_a_buffer, get_flags, get_flags_filename, header
```

**Comment by jcupitt** [comment]
You don't need to `#include <vips/foreign.h>`, by the way, the base vips include will pull everything in.

**Comment by wbtlb** [comment]
hmm, after run `vips -l |grep -i gif`, i got nothing. gifload wont be build in libvips by default?

**Comment by jcupitt** [comment]
Yes, it will be built. Try the `which vips` line and verify that it is executing the vips you built.

**Comment by wbtlb** [comment]
hi:
    i run `autogen` again, and after run `vips -l |grep -i gif`, it show 

    VipsForeignLoadGif (gifload_base), load GIF with giflib, priority=0
    VipsForeignLoadGifFile (gifload), load GIF with giflib (.gif), priority=0, is_a, get_flags, 
    get_flags_filename, header
    VipsForeignLoadGifBuffer (gifload_buffer), load GIF with giflib, priority=0, is_a_buffer, get_flags, 
    get_flags_filename, header


my code

    #include <vips/vips.h>
    int main( int argc, char **argv )
    {
        VipsImage *out;
        if( VIPS_INIT(argv[0]))
            vips_error_exit(NULL); 
        if(argc != 3)
            vips_error_exit("usage: %s infile outfile", argv[0]); 
        if (vips_gifload(argv[1], &out, NULL))
            vips_error_exit(NULL);
        return( 0 );
    }

run  `./a.out  test.gif test.webp`
it still show 

    VipsOperation: class "gifload" not found

**Comment by wbtlb** [comment]
`/usr/local/bin/vips`

**Comment by jcupitt** [comment]
So you have two libvips installed, one with gifload and one without. 

I would remove the one without gifload (perhaps installed by your package manager?), it'll be less confusing.

If you really need two libvips installed, you need to set your environment variables so that the right one is picked up by the compiler and run-time linker.

**Comment by wbtlb** [comment]
i uninstall othere one， and i use `pkg-config vips --cflags --libs` point to correctly libvips path.

**Comment by jcupitt** [comment]
If your C program is still not working, you must have another libvips on your system somewhere.

`ldd` will show you which shared library your executable is picking up.

**Comment by wbtlb** [comment]
ok, i will check it

**Comment by wbtlb** [comment]
another question, can i convert gif to dynamic webp by this library?

**Comment by jcupitt** [comment]
No, the webp writer only supports single page images.

**Comment by wbtlb** [comment]
hmmm... if i want to convert gif to dynamic webp, any idea?

**Comment by jcupitt** [comment]
Very recent imagemagick, perhaps?

**Comment by wbtlb** [comment]
ok， i will try. Thanks for you reply and patient. Thank you very much. Please close this issue.:-)
