### ISSUE TITLE
vips_thumbnail crop seems incomplete

### ISSUE THREAD

**Issue by triptec** [libvips/libvips#1089]
I'm missing gravity in VipsInteresting. It has 'centre' but the rest (north-west, north, north-east etc..)would be good to have as well i think or have I misunderstood something?

**Comment by triptec** [comment]
ah, ok but left and right would then also make sense?

**Comment by jcupitt** [comment]
It's only ever on one axis, you can't position on both, so low/centre/high would mean both left-right and up-down, depending on the aspect ratios.

**Comment by triptec** [comment]
You’re right, seems I didn’t think about this too much. Thanks

**Comment by jcupitt** [comment]
OK, there's a PR to add low/high options. I'll close this issue.
