### ISSUE TITLE
svs format problem: OpenJPEG error: tcd_decode: incomplete bistream

### ISSUE THREAD

**Issue by owenustc** [libvips/libvips#1091]
Hi,  I used vips to open svs format file.  But I had met the problem as list：
(vips:40956): VIPS-WARNING **: error in tile 81600 x 34560
openslide2vips: reading region: OpenJPEG error: tcd_decode: incomplete bistream
 Could someone help me?

My openslide is 3.4.1 ,news version?

**Comment by jcupitt** [comment]
Sorry, I don't know. I would ask on the openslide issue tracker:

https://github.com/openslide/openslide/issues
