### ISSUE TITLE
wbuffer_write: write failed problem

### ISSUE THREAD

**Issue by owenustc** [libvips/libvips#1093]
Hi , I use vips to conver svs format as follow:  
     vips dzsave  xx.svs  xx.zip --background 0 --centre --layout google
  But I had met the problem as list:
    dzsave: too many files in zip
   dzsave: too many files in zip
   dzsave: too many files in zip
   wbuffer_write: write failed
   unix error: Unknown error -1
It means my svs file is too big?  Could someone help me?

**Comment by jcupitt** [comment]
Oh, interesting, I've never seen that message. It looks like you are using an old version of libgsf that does not support zip64. Plain zip can't store more than 65536 files.

The best solution would be to update to a more recent version of libgsf -- you need 1.14.31 or later, and you'll need to rebuild libvips against this newer version.

As a workaround, you could just make your tiles bigger. You could still run into the 4gb limit on plain zip though.

**Comment by jcupitt** [comment]
Please reopen if this is still an issue.
