### ISSUE TITLE
Can VIPS use memory for temp files instead of /tmp ?

### ISSUE THREAD

**Issue by Algae666** [libvips/libvips#1096]
We have lots of RAM to spare, but disk I/O is precious. Is there any way to keep temporary buffers in memory instead of writing as files to disk?

**Comment by jcupitt** [comment]
Hello @Algae666, 

Sure, you can control the switch from memory to disc with `VIPS_DISC_THRESHOLD`:

http://jcupitt.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-file

has the details.

**Comment by hervenivon** [comment]
> Hello @Algae666,
> 
> Sure, you can control the switch from memory to disc with `VIPS_DISC_THRESHOLD`:
> 
> http://jcupitt.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-file
> 
> has the details.

updated link for those stumbling upon that comment: https://www.libvips.org/API/current/VipsImage.html#vips-image-new-from-file
