### ISSUE TITLE
Issue downloading prebaked tarball

### ISSUE THREAD

**Issue by richardnias** [libvips/libvips#1100]
Hiya,

Previously (within the last few days if I'm not mistaken) I was able to download a release via this URL:
https://github.com/jcupitt/libvips/releases/download/v8.6.4/vips-8.6.4.tar.gz

This URL is now 404ing. When I try and download from https://github.com/jcupitt/libvips/releases, the tarballs require running `autogen.sh` to work, rather than just letting me run `./configure` etc.

Is this a GitHub bug? Or has some repo configuration changed?

**Comment by jcupitt** [comment]
Hello @richardnias,

You should be able to download from here:

https://github.com/libvips/libvips/releases

libvips has moved to it's own organisation now, rather than being my personal project:

https://github.com/libvips

I'll see if I can do anything to make old download links work.

**Comment by jcupitt** [comment]
Looks like https://libvips.github.io/libvips/ still has some old jcupitt links in, I'll try to fix it.

**Comment by richardnias** [comment]
ah great, thanks. I'm sure that I could have worked that out for myself but my brain is working a little slowly this morning!

**Comment by jcupitt** [comment]
Links updated in: 

https://github.com/libvips/libvips/pull/1101

Thanks for reporting!
