### ISSUE TITLE
vips_image_new_from_memory from RGB Buffer

### ISSUE THREAD

**Issue by abenchaaben** [libvips/libvips#1105]
Hi, 

I'm trying to create a vips image from a opencv Mat buffer, but the program crash. Her is the code : 

big_image is a RGB opencv Mat image.

size_t length = big_image.rows * big_image.cols;
VipsImage *out;
out = vips_image_new_from_memory(big_image.data, length, big_image.cols, big_image.rows, 3, VIPS_FORMAT_UCHAR);

I think that the problem is the VIPS_FORMAT but i dont know what to choose and i try all of them

Thank's in advanced

**Comment by kmartinez** [comment]
if the image you are using is a simple byte array like rgbrgb... then specifying VIPS_FORMAT_UCHAR just lets libvips know the size of each element. So it looks OK to me. What is the actual error you are getting?

**Comment by jcupitt** [comment]
Hello, I made you a demo program;

```c++
/* compile with
 *
 *      g++ -g -Wall try277.cc `pkg-config opencv vips-cpp --cflags --libs`
 *
 */

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <vips/vips8>

int
main (int argc, char **argv)
{
        cv::Mat img = cv::imread (argv[1]);
        if (img.empty ())
                return -1;

        int width = img.cols;
        int height = img.rows;
        size_t length = 3 * width * height;
        void *data = img.data;

        if (VIPS_INIT (argv[0]))
                return -1;

        vips::VImage out = vips::VImage::new_from_memory (data, length,
                width, height, 3, VIPS_FORMAT_UCHAR);

        /* opencv is BGR, libvips is RGB, we must swap the first and last
         * channels.
         */
        std::vector<vips::VImage> bands = out.bandsplit();
        vips::VImage t = bands[0];
        bands[0] = bands[2];
        bands[2] = t;
        out = vips::VImage::bandjoin (bands);

        out.write_to_file (argv[2]);

        return 0;
}
```

It seems to work for me with a JPG source. You'll need to check the pixel type of the opencv image -- it won't always be uchar.

**Comment by abenchaaben** [comment]
Thank you all,

Her what i did 

```
size_t length = big_image.rows * big_image.cols * 3;
cout << big_image.depth() << endl;
cout << big_image.channels() << endl;
void *data = big_image.data;
VipsImage *out;
out = vips_image_new_from_memory(data, length, big_image.cols, big_image.rows, 3, VIPS_FORMAT_UCHAR);
vips_tiffsave(out, image_name.c_str(), "compression", VIPS_FOREIGN_TIFF_COMPRESSION_JPEG, "Q", 80, "tile", TRUE, "tile_width", 512, "tile_height", 512, "pyramid", TRUE, "bigtiff", TRUE, NULL);
g_object_unref(out);
```
i checked the depth of the opencv Mat and it's 8-bit unsigned integer (uchar)
i checked the number of channels and it's 3

Her what i get 

![capture](https://user-images.githubusercontent.com/39028333/45950588-c0ae9500-c000-11e8-8f85-eb8f6c55fac0.JPG)

Her the opencv image : 

![capture](https://user-images.githubusercontent.com/39028333/45950703-3155b180-c001-11e8-97ae-04cfef6066c3.JPG)


Thak you in advanced

**Comment by jcupitt** [comment]
Sorry, no idea, though it looks like you have rows and columns wrong, since the images are different heights. 

Post a complete program I can run, a sample image and the output you get.

**Comment by abenchaaben** [comment]
The 2 images are screenshot just as example of the output. So it's not exactly the same images.

**Comment by abenchaaben** [comment]
Her is the data and the code 

cv::Mat big_image = imread("input.tiff");
size_t length = big_image.rows * big_image.cols * 3;
cout << big_image.depth() << endl;
cout << big_image.channels() << endl;
void *data = big_image.data;
VipsImage *out;
out = vips_image_new_from_memory(data, length, big_image.cols, big_image.rows, 3, VIPS_FORMAT_UCHAR);
vips_tiffsave(out, image_name.c_str(), "compression", VIPS_FOREIGN_TIFF_COMPRESSION_JPEG, "Q", 80, "tile", TRUE, "tile_width", 512, "tile_height", 512, "pyramid", TRUE, "bigtiff", TRUE, NULL);
g_object_unref(out);



[data.zip](https://github.com/libvips/libvips/files/2410810/data.zip)

**Comment by jcupitt** [comment]
That's not a complete program I can run!

I tried modifying the program I posted instead:

```c++
/* compile with
 *
 *      g++ -g -Wall try278.cc `pkg-config opencv vips-cpp --cflags --libs`
 *
 */

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <vips/vips8>

int
main (int argc, char **argv)
{
        cv::Mat img = cv::imread (argv[1]);
        if (img.empty ())
                return -1;

        int width = img.cols;
        int height = img.rows;
        size_t length = 3 * width * height;
        void *data = img.data;

        if (VIPS_INIT (argv[0]))
                return -1;

        vips::VImage out = vips::VImage::new_from_memory (data, length,
                width, height, 3, VIPS_FORMAT_UCHAR);

        /* opencv is BGR, libvips is RGB, we must swap the first and last
         * channels.
         */
        std::vector<vips::VImage> bands = out.bandsplit();
        vips::VImage t = bands[0];
        bands[0] = bands[2];
        bands[2] = t;
        out = vips::VImage::bandjoin (bands);

        out.tiffsave (argv[2], vips::VImage::option()
                ->set( "compression", "jpeg" )
                ->set( "Q", 80 )
                ->set( "tile", TRUE )
                ->set( "tile-width", 512 )
                ->set( "tile-height", 512 )
                ->set( "pyramid", TRUE )
                ->set( "bigtiff", TRUE ));

        return 0;
}
```

and it works for me on your test image.

I think you must have an error somewhere else in your code.

**Comment by abenchaaben** [comment]
i think so. It seems when i passe an RGB opencv image it does not work. But when i tried an BGR image it work. I will check why. 

Thank you for your help

**Comment by abenchaaben** [comment]
I forget to ask you another question. If i want to save svs file with vips, can i use the tiffsave  function and passe the imageDescription of an svs file?

Thank's a lot

**Comment by jcupitt** [comment]
Sorry, no, SVS is a read-only format.

**Comment by jcupitt** [comment]
Please reopen if this is still an issue.

**Comment by ihuale** [comment]
I have the same problem, but I found a solution.
we can't use cv::Mat::data directly  in some case, because of the storage mechanism of opencv, there may be blank cells between rows and rows. 
For blank cells, opencv uses padding to fill in an integer multiple of 4. You can use isContinuous() to check if the image is continuous.
For non-contiguous images, it is best to use cv::Mat::ptr<> to access by row
