### ISSUE TITLE
Why does write_to_memory() buffer after multiplication increase in size?

### ISSUE THREAD

**Issue by kaas3000** [libvips/libvips#1106]
Hello,

I try to import a Vips image into a Cairo ImageSurface.
Pycairo expects the input channels to be premultiplied with the alpha channel.
When I try to do this with PyVips the image in the cairo imagesurface looks to be broken. This has propably to do with the fact that the memoryview returned from the `write_to_memory()` method has doubled in size somehow.

Please check the code for an example of what I mean.
PIL does the premultiply operation while keeping the buffer the same size, but Vips returns a bigger buffer.

How does this happen and what can I do to prevent the memoryview from increasing in size (or decrease the memoryview)?

Thanks in advance,
Kees

## Python PIL vs Vips example

```python3
import cairo
from PIL import Image as pilImage
from cairo import ImageSurface
from pyvips import Image as vipsImage

if __name__ == '__main__':
    filename = 'example.png'
    vips_img = vipsImage.new_from_file(filename)
    pil_img = pilImage.open(filename)

    # Print initial memory contents
    print(pil_img.tobytes())
    print(bytes(vips_img.write_to_memory()), end='\n\n')

    pil_img.putalpha(128)
    vips_img = vips_img.bandjoin(128)

    # (Change rgba to bgra) and premultiply alpha in Vips
    # r, g, b, a = vimg.bandsplit()
    # vips_img = b.bandjoin(g).bandjoin(r).bandjoin(a)
    vips_img = vips_img.premultiply()

    # (Change rgba to bgra) and premultiply alpha in Pillow
    # pil_img_bytes = bytearray(pimg.convert('RGBa').tobytes('raw', 'BGRa'))
    pil_img_bytes = bytearray(pil_img.convert('RGBa').tobytes('raw'))
    vips_img_bytes = bytearray(vips_img.write_to_memory())

    # Print changed memory contents
    print(pil_img_bytes, end='\n\n')
    print(vips_img_bytes, end='\n\n')

    print(len(pil_img_bytes))
    print(len(vips_img_bytes))

    ImageSurface.create_for_data(pil_img_bytes, cairo.FORMAT_ARGB32, vips_img.width, vips_img.height).write_to_png('out-pil.png')
    ImageSurface.create_for_data(vips_img_bytes, cairo.FORMAT_ARGB32, vips_img.width, vips_img.height).write_to_png('out-vips.png')
```

## Image used
![image](https://user-images.githubusercontent.com/2116782/45951386-8eeafd80-c003-11e8-9994-a0821164bdf9.png)

**Comment by jcupitt** [comment]
Hello @kaas3000,

libvips multiply expands the format to keep all the values, so uchar * uchar gives ushort. If you want to go back to uchar, you'll need to shift and cast. 

There's a `premultiply` operation which will do this for you:

http://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-premultiply

It makes a float image, so you'll need to cast back to uchar after. In Python:

```python
image = image.premultiply().cast('uchar')
```

You might find you need to swap B and R as well, I forget.

**Comment by kaas3000** [comment]
So PIL loses some information where vips uses some more memory automatically to keep all the information?
Thats neat!

Thank you very much for your answer!

**Comment by jcupitt** [comment]
That's right, you have to explicitly throw bits away in libvips (usually).

It doesn't actually use more memory. These operations are all virtual, so images never really exist during computation, as long as you cast down again before the end.

**Comment by jcupitt** [comment]
Oh, I guess that should really be:

```python
image = image.premultiply().cast(image.format)
```

ie. cast back to the start format. That should mean it works for 16-bit images too.
