### ISSUE TITLE
vips convert  xx.ndpi to jpg  error

### ISSUE THREAD

**Issue by owenustc** [libvips/libvips#1108]
Hi， I used vips tools to convert xx.ndpi to jpg as follow:
        vips dzsave  $1 $1\.zip  --background 0 --centre --layout google.
 But I found that the number of jpg of the result of vips is not match the size of image of openside.
 I used python-openside to open the file with ndpi format, which size is 146816 x 90624. But the result of vips shows the number of images of max level of google map is only 51264.  Every image of google map could display 256x256 or 512x512  pixels.  So the number of images should more than 203196, but not 51264.
I wrote a file named check_file.py to check the result of vips.  
 python check_file.py test/xx.ndpi
((146816, 90624), 573.5, 354.0)
('9', 'xx.ndpi')
( 'error 51264 x jpg') 
Could you help me?

**Comment by jcupitt** [comment]
Hello @owenustc,

The dzsave google writer won't write blank tiles, so if a tile is plain white, it'll skip it. Could this be what is happening? Google map viewers are supposed to display `blank.png` if a tile is missing. 

It could also be autocrop. By default, dzsave will only output the parts of the slide which contain real pixel data, and will skip empty parts of the field of view. I don't know how python-openslide handles this. 

I would load your image into a tile viewer and check it looks OK.

**Comment by owenustc** [comment]
Hello @jcupitt ,
    This problem is the error of my check tool.  Here, max level of google map of this file  is 10, but not 9.  I have check the number of jpg of level 10 as follow:
python check_file.py xx.ndpi/10/
(203196, ' x jpg')
It is right!!!, 203196 x jpg.   I want to say thank you very much!!, and also want to say sorry for wasting your time.

**Comment by jcupitt** [comment]
Ah OK, glad it's working!

I usually check the number of files with something like:

```
john@yingna ~/pics $ vips dzsave k2.jpg x
john@yingna ~/pics $ ls x_files
0  1  10  11  2  3  4  5  6  7  8  9
john@yingna ~/pics $ ls x_files/11 | wc
     54      54     486
```

Or for all tiles:

```
john@yingna ~/pics $ find x_files -name "*.jpeg" | wc
     85      85    1684
```

**Comment by owenustc** [comment]
Hi @jcupitt ， I could ask another problem about tif format convert. The detail operation information as follow:
unzip xx.tif.zip
ls xx.tif/
0  1  10  2  3  4  5  6  7  8  9  blank.png
python check_file.py xx.tif/10/
(91804, ' x jpg')
The number of img of vips result is not match the size of python-openslide, which is 96651 x 197226.
And It should have 291438x jpg, but not 91804.

**Comment by jcupitt** [comment]
As I said, it could be blank tiles, or perhaps autocrop. You could make your check program look for missing tiles, then verify that those tiles are indeed all blank. If you use `--centre`, dzsave will add quite a few tiles around the edge of the largest layer as well.

I would be very surprised it it's not working correctly. dzsave is used by most (all?) of the online virtual slide libraries and it's well tested. If you can send me a sample image where you think it's failing, I can have a look.

**Comment by owenustc** [comment]
Hi, @jcupitt ,
    I would send my tif file  to you email jcupitt@gmail.com tomorrow.  
                Thank you very much.

**Comment by jcupitt** [comment]
I had a go with an ndpi image here:

```
$ vipsheader bild.ndpi 
bild.ndpi: 126976x98304 uchar, 4 bands, rgb, openslideload
$ vips dzsave bild.ndpi x --layout google
$ ls x
0  1  2  3  4  5  6  7  8  9  blank.png
$ ls x/9 | wc
    384     384    1426
$ ls x/9/1 | wc
    496     496    3858
```

So it's 384 tiles down, each tile is 256 x 256, so the highest-res layer must be 98304 pixels. 496 tiles across is 126976.

```
$ find x/9 -name "*.jpg" | wc
 190464  190464 2950624
```

Which is exactly 384 * 496. I guess there are no blank tiles in this one.

**Comment by jcupitt** [comment]
Oh, could you have an old libgsf? If you are making zip files, you need a libgsf with support for zip64 to process really large images. 

Did you build libvips yourself? What version of libgsf is it using?

**Comment by owenustc** [comment]
test.tif.tgz
<https://drive.google.com/file/d/1w-J7uVIZOGn51nD4nW9bJTuFXD7P3xdG/view?usp=drive_web>
Hi, John Cupitt ,
The file named test.tif.tgz is my test sample for vips.  For google map,
every image should display 256x256 pixels. And the image size of this file
with tif format is 96651 x 197226. So the number of images  should be more
than
377.54296875 x 770.4140625 after converting google map,  maybe 378 x 771 or
379x 771  .  But the number of  images with vips tool generating is
only 91804 for the max level 10 of google map.   And I guess that there is
a bug for tif conversion in vips.
And the version of my libgsf  is libgsf-1 1.14.36, which is achieved your
requirement, 1.14.31 or later.
                                                    Thank you very much.


John Cupitt <notifications@github.com> 于2018年9月25日周二 下午10:07写道：

**Comment by jcupitt** [comment]
Could you post the exact command you are running? Are you making a zip for output, or writing to the filesystem?

I'll try your file here.

**Comment by jcupitt** [comment]
It seems to work for me, I see:

```
john@kiwi:~/pics/x$ vips dzsave test.tif x --layout google
john@kiwi:~/pics/x$ cd x
john@kiwi:~/pics/x/x$ ls
0  1  10  2  3  4  5  6  7  8  9  blank.png
john@kiwi:~/pics/x/x$ ls 10 | wc
    771     771    2974
john@kiwi:~/pics/x/x$ ls 10/1/ | wc
    378     378    2914
john@kiwi:~/pics/x$ find x/10 -name "*.jpg" | wc
 291101  291101 4822465
```

Perhaps something went wrong when you built libvips? If you are making ZIP output, try checking `config.h` for the line:

```
/* define if your libgsf supports zip64. */
#define HAVE_GSF_ZIP64 1
```

I checked your image in nip2 and it has a lot of missing (black) tiles, I guess you know.

**Comment by owenustc** [comment]
Hi, @John Cupitt,
   It is not working, because the file named test.tif has 96651 x 197226
pixels, which should has more than 377.54296875 x 770.4140625  images in
google map.
Every image of google map should display  256x256 pixels.  And I have
follow your command,  " vips dzsave test.tif x --layout google", to get the
data of google map layout.
Then, I display the result of vips in google map, but there are many miss
images as the file attached file named 15381900099249.png show.

John Cupitt <notifications@github.com> 于2018年9月26日周三 下午5:10写道：

**Comment by jcupitt** [comment]
Yes, I see 378 x 771 tiles, so it is working, for me anyway. Your attachment did not come through, could you upload again? If it shows black areas, they are in your original `.tif` file.

As I said, you need to show how you are running dzsave. Are you making a `.zip` file? Did you compile libvips yourself? Could you check `config.h` to show that zip64 was enabled correctly?
