### ISSUE TITLE
jcupitt

### ISSUE THREAD

**Issue by vvelagal** [libvips/libvips#1109]
I am trying to run pyvips in the command window.

 I am getting an error that it can not find the module libvips.

I am running it on Windows 7.

Can you tell me how to find the libvips binaries for windows? I am attaching the image here.

Thank you

![libvips](https://user-images.githubusercontent.com/43582373/46029425-3a4d8e00-c0a8-11e8-8eb6-7e207d3d97ea.PNG)

**Comment by jcupitt** [comment]
Hello, you need to set your PATH to include the libvips DLL, and you must use a 64-bit Python. 

Try `echo %PATH%` and see if you have the libvips bin area there.

**Comment by jcupitt** [comment]
Oh, Windows binary here, in case you didn't find it:

https://github.com/libvips/libvips/releases

**Comment by vvelagal** [comment]
I added the path but I am getting an error Entry Point not Found.[2](https://user-images.githubusercontent.com/43582373/46032629-0b87e580-c0b1-11e8-9aa1-f71f4080cd86.PNG)
![3](https://user-images.githubusercontent.com/43582373/46032630-0b87e580-c0b1-11e8-98f4-0f21b2d5fdd7.PNG)

**Comment by jcupitt** [comment]
You probably have a conflicting set of libraries on your path, with a cairo that's missing that function.

Search your system for `libcairo-2.dll` and see if you have one on your path that shouldn't be there.

**Comment by vvelagal** [comment]
Thank you.. I figured it out. 

I have an svs file with three levels. How can I convert it to a tiled image with a tiff format?

**Comment by jcupitt** [comment]
At the command-line:

```
vips copy something.svs banana.tif[tile]
```

Or:

```
vips tiffsave something.svs banana.tif --tile
```

To see all the options:

```
vips tiffsave
```

Do you need a pyramidal tiff?

**Comment by jcupitt** [comment]
http://libvips.github.io/libvips/API/current/using-cli.html

explains how to use the vips CLI.

**Comment by vvelagal** [comment]
I am looking for a pyramidal tiff...

Actually I have hundreds of svs files in a directory numbered from one . Each svs file has a memory over 4gb.

Instead of typing every time in command window,I am thinking of writing a program in python which automatically  can convert them to tiffs and process them.

Is there a way to convert them using pyvips ,instead of typing in the command window every time?

I am really thankful for your immediate response

**Comment by jcupitt** [comment]
I would do:

```
vips tiffsave huge.svs something.tif[tile,pyramid,compression=jpeg,bigtiff]
```

Yes, you can make a Python program, or just a little shell script. In bash:

```
for file in *.svs; do
  vips tiffsave $file $file.tif[tile,pyramid,compression=jpeg,bigtiff]
done
```

Or Python:

```
import pyvips

for file in sys.argv[1:]:
    image = pyvips.Image.new_from_file(file, access='sequential')
    image.tiffsave(file + '.tif', tile=True, pyramid=True, compression='jpeg', bigtiff=True)
```

**Comment by vvelagal** [comment]
Thank you..
I converted to pyramidal tiff but its taking a long time to open.So I converted the pyramidal tiff to deep zoom pyramids using dzsave().It generates a directory with series of tiles.Is there a way I get a single high resolution image which contains all the tiles and that  can be zoomed from a svs file ?

**Comment by jcupitt** [comment]
nip2 can display tiled pyramidal tiffs fairly quickly.

https://github.com/libvips/nip2/releases

**Comment by jcupitt** [comment]
There's the `nip2-cli.exe` program in the nip2 area. You can run that from Python like any other program.

`image.crop(x, y, w, h)` and `image.rotate(angle)`, see the documentation:

https://libvips.github.io/pyvips/

**Comment by vvelagal** [comment]
Thank you.. I have used the below code.And the nip2 window gets popped up but the image is not getting opened.
May b 

import subprocess
p = subprocess.Popen([r'C:\Users\Owner\AppData\Local\VIPS\nip2-8.7.0\bin\nip2.exe', r'E:\Downloads\15489b.tiff'])
But it does not open...
I am doing it in spyder... I think python converts the image file to bmp and nip2 can not  open the bmp files...

**Comment by jcupitt** [comment]
On Windows you need `nip2-cli.exe`, or your program won't block. 

Sorry, no idea! It should work.

**Comment by vvelagal** [comment]
I am trying on Ubuntu as it is much faster. But, I am getting this error.

 image.tiffsave( r'/home/vijay/Downloads/15489'+ '.tif', tile=True, pyramid=True, compression='jpeg', bigtiff=True)

  File "/home/vijay/anaconda3/lib/python3.6/site-packages/pyvips/vimage.py", line 799, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)

  File "/home/vijay/anaconda3/lib/python3.6/site-packages/pyvips/voperation.py", line 189, in call
    raise Error('unable to call {0}'.format(operation_name))

Error: unable to call tiffsave
  /home/vijay/Downloads/15489.svs: Compression scheme 33005 tile decoding is not implemented
/home/vijay/Downloads/15489.svs: Compression scheme 33005 tile decoding is not implemented
/home/vijay/Downloads/15489.svs: Compression scheme 33005 tile decoding is not implemented
/home/vijay/Downloads/15489.svs: Compression scheme 33005 tile decoding is not implemented

**Comment by jcupitt** [comment]
It looks like your libvips has been built without openslide support. 

You ought to see:

```
$ vips openslideload
load file with OpenSlide
usage:
   openslideload filename out
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   flags        - Flags for this file, output VipsForeignFlags
...
```

Is this using the Ubuntu libvips? If not, which Ubuntu are you using?

**Comment by vvelagal** [comment]
I am built the libvips from git.I am using the bionic version(18.04 LTS)

I installed the openslide after building vips.

Do I have to uninstall vips now?

**Comment by jcupitt** [comment]
The libvips that comes with Ubuntu is probably fine. I would just use that, unless you need a recent feature. 

If you want to build your own, you must install openslide first. Check the output of libvips configure and make sure openslide has been detected. 

You don't need to uninstall libvips, just reinstall over the top.

**Comment by vvelagal** [comment]
When I am configuring,I am getting these options.How do I have to make the libvips detect the openslide?

* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable vips7 C++ API: 			no (default)
enable vips7 Python binding:		no (default)
enable vips8 Python overrides:		no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			none
Magick API version: 			none
load with libMagick: 			no
save with libMagick: 			no
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	yes
  (requires libwebp-0.1.3 or later)
support webp metadata:			yes
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2: 		yes
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with giflib:		yes (found by search)
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no

**Comment by jcupitt** [comment]
You need to install the `-dev` versions of packages.

If you install `libopenslide0`, you just get the library binary you need to run stuff. You need to install `libopenslide-dev` to get the headers you need to build stuff that links to that library.

**Comment by vvelagal** [comment]
file import with OpenSlide:		yes

Its now detecting but still I am getting the same error

**Comment by jcupitt** [comment]
Perhaps you have installed two libvipses and you are still running the old one? 

I would not build your own libvips unless you are certain you need a recent feature. Ubuntu 18.04 comes with libvips 8.4, which ought to work fine.
