### ISSUE TITLE
question about color profile conversion from cymk to srgb

### ISSUE THREAD

**Issue by beaudet** [libvips/libvips#1110]
By and large, the following two step approach seems to work well to convert an image from one icc profile to another. (I left out the --embedded and --input-profile from this example because I have ruled those out as contributing to the problem already but I'm also using those).

> /usr/local/bin/vips icc_transform inputfile.tif transformedinput.tif[compression=none,strip] sRGBProfile.icc
> /usr/local/bin/vips tiffsave transformed_input.tif transformed_embedded_output.tif --compression none --profile /usr/local/nga/etc/sRGBProfile.icc

This works fine for conversions from rgb and gray profiles, but when converting from cmyk into rgb, the resulting colors are noticeably lighter than what I believe to be the corresponding operations in imagemagick:

> convert inputfile.tif inputfile.icc
> convert inputfile.tif  +profile '*' -profile inputfile.icc -profile sRGBProfile.icc transformed_embedded_output.tif

I've inspected the options of icc_transform just and I am reminded of the option --intent.  Sure enough, setting that to "perceptual" now seems to align the output with that of ImageMagick and produces a much better match to the original image.  Can you clue me in as to why I would only notice this going from cmyk to rgb?  Does it have just as much to do with the original profile as it does with the original color space?

**Comment by jcupitt** [comment]
Hello Dave,

Yes, CMYK->RGB is a tricky one. IM defaults to perceptual (I think), but libvips defaults to relative. For most RGB profiles (but not all!), they are the same, but CMYK is often very different for perceptual intent. 

It depends on the exact profiles you are using, both direct and embedded.

**Comment by beaudet** [comment]
Thanks John!  I'll go with perceptual for now since that's consistent with our image processing preferences to date although it's interesting that a one size fits all approach might not work in all cases.  I imagine if we encounter an unacceptably bad case, we can just edit the original and republish it.
