### ISSUE TITLE
Best input format [question]

### ISSUE THREAD

**Issue by tart-ufo** [libvips/libvips#1111]
i have 2 (995x1015) images, one with alpha, both only with two colors.
so i tried to edit them with gimp, but i'm not sure about what to do
i tried also to convert the images to .vips but i suspect that i can do more with gimp
the images will be used overlapping them with a third image .tiff rgb (the first is the background, the second goes above).
the middle photo should be resized but without interpolation, is it possible?

thanks.

**Comment by jcupitt** [comment]
Hello, yes, you can layer and resize images with libvips. nip2, the vips gui has menu items for this. 

But I wonder if gimp might be simpler. Just load the images into three layers and resize and move them around.

**Comment by tart-ufo** [comment]
thanks for the reply, I realized now that I did not include some basic details to understand the question!
I have to process these photos using the C ++ library

currently what it does is:
- read the background and the overlap
-are available to read the middle image
- resize this photo from 315x339 to 945x1015 (3x) *
-with .compose to put the background and the overlap
-create a text image to decorate the photo
- again with compose add the text
- write the new photo on disk

the operation is repeated for a minimum of 24 images (up to over 700) and requires 2.2 seconds with an i7 2630qm (4.18.9-arch1-1-ARCH)
since the operation is used to create an ondemand web service, I thought it was possible to speed things up by using faster input images

[https://photos.app.goo.gl/HtimoPCVZeDgG66f9]
* I would like the photo not to be resampled, but only stretched for the size of the background

thank you very much for your availability

**Comment by jcupitt** [comment]
Ah I understand. Post your code and some sample images and I'll check it for speedups. There's often something simple you can do.

For text overlays, I would:

- make the text image
- crop out a bit of the background of the same size at the right position
- make a constant image of that size with the text colour you want in
- use ifthenelse in blend mode to blend the text over the background
- insert the new image over the background

Also:

- make sure you are using sequential mode when you can
- don't use PNG -- use uncompressed TIF for speed, or perhaps vips format

**Comment by tart-ufo** [comment]
https://github.com/tart-ufo/MappeIRPI-CNR
here you can find souce code, background, overlay, the marker and an example frame

the text is okay at the top left as it is now, the problem is that the marker should be positioned at the exact coordinates (expressed in xy pixels), and I have not quite understood how I can do
the overlay is in png because with gimp I have indexed it to b / w 1bit, and I can not save a tif indexed with alpha channel
the background is instead tif because it has no alpha channel (this is also indexed to the least possible number of colors)
then I converted the images into .vips
thank you so much you are very kind

**Comment by jcupitt** [comment]
I've not been able to compile your program :( It seems to be using something more recent than Ubuntu 18.04. 

I swapped `<filesystem>` for `<experimental/filesystem>` so it can build with g++7, but I still get:

```
main.cpp: In function ‘void to3857(double*, double*)’:
main.cpp:52:25: error: aggregate ‘OGRSpatialReference sourceSRS’ has incomplete type and cannot be defined
     OGRSpatialReference sourceSRS, targetSRS;
                         ^~~~~~~~~
```

I guess my gdal is too old. Could you make a version of your code that builds against gdal 2.2? It would save me having to update chunks of my PC.

You could make your CMakeLists.txt a little simpler. You should only need:

```
find_package(PkgConfig REQUIRED)
pkg_check_modules(VIPS REQUIRED vips-cpp)
...
target_link_libraries(MappeIrpi ${VIPS_LIBRARIES})
target_include_directories(MappeIrpi PUBLIC ${VIPS_INCLUDE_DIRS})
```

You don't need to add glib, vips-cpp should do that for you.

**Comment by tart-ufo** [comment]
currently you can also delete this function because it serves to convert the coordinates taken from a database, which is still in process and not used
same for <filesystem>, which created folders to organize the outputs (currently it does not, but I did not remove the library)

**Comment by jcupitt** [comment]
OK, it's building now. What would be typical arguments to use for the executable?

**Comment by jcupitt** [comment]
Sorry, accidental close.

It's failing now with:

```
$ ./a.out 20180902_13 20180903_13
ERROR 4: ./20180902_14/cf_psm.tif: No such file or directory
ERROR 1: No source dataset specified.
```

I can tune the vips part for you, but I need a benchmark to optimise. 

Can you make me a complete program I can run (with sample data) which does roughly what you need?

**Comment by tart-ufo** [comment]
the program works in fact the sample frame I got it from that code (except the marker I added with gimp, because I could not specify with vips a precise location where to put it), I put a drive link where you can find the data that I used as input, without those it can not work
in order to run the program you must correct the path at the beginning of the code (lines 21, 24-27)
I appreciate the fact that you started to run my code, it's not for everyone

**Comment by jcupitt** [comment]
But there are no folders for each day in the github repo :( 

https://github.com/tart-ufo/MappeIRPI-CNR

Do they need to be added? The drive link just has `background.vips` in, which is in the repo already.

**Comment by tart-ufo** [comment]
![image](https://user-images.githubusercontent.com/39013921/46105153-982bc400-c1d5-11e8-80dc-b4989e77727d.png)

![image](https://user-images.githubusercontent.com/39013921/46104926-f73d0900-c1d4-11e8-873e-dd0ad583b617.png)
i see this, but if you want I can upload the folder also on github

**Comment by jcupitt** [comment]
I made a version of your code that seems to work:

https://github.com/jcupitt/MappeIRPI-CNR/tree/hacking/composite

It makes maps like this:

![x](https://user-images.githubusercontent.com/580843/46151895-b6da9b00-c267-11e8-955d-fb3652f82079.jpg)

There's a tiny benchmark script: on this laptop, it generates 100 maps in about 14s.

I'll try to speed it up a bit next.

**Comment by jcupitt** [comment]
Here's a faster version:

https://github.com/jcupitt/MappeIRPI-CNR/tree/hacking/composite2

About 8.2s for 100 images.

**Comment by tart-ufo** [comment]
wow, thank you, it's great.
do you have any tips on how to optimize input files? I did my best working with gimp (indexing colors and removing information) and converting them to .vips
is it possible to resize the image without interpolation in libvips?

do you have Paypal? I would like to offer you a beer

**Comment by jcupitt** [comment]
I think the input files are fine as they are, there’s nothing more to do
there that would have an effect on runtime.

That’s kind of you! I’m jcupitt@gmail.com

**Comment by tart-ufo** [comment]
perfect ... but then there is no way to resize the simple image "making the pixels bigger" to cover the entire background? do we have to use an interpolation algorithm?

**Comment by tart-ufo** [comment]
![sample](https://user-images.githubusercontent.com/39013921/46166822-69285780-c294-11e8-90fd-c762a36174e1.png)
 you can notice the difference
 the part on the right is made using the imageMagick .zoom method

**Comment by jcupitt** [comment]
Ah OK. That's nearest-neighbour interpolation. Change it to `VIPS_KERNEL_NEAREST`.

**Comment by jcupitt** [comment]
That's for the eur. 5, by the way, I bought a cheap bottle of wine! Cheers!
