### ISSUE TITLE
Backwards compatibility for jcupitt.github.io/libvips?

### ISSUE THREAD

**Issue by janko-m** [libvips/libvips#1112]
With the move to the `libvips` GH organization, `jcupitt.github.io/libvips` is now returning a 404. I think that will render a lot of existing links invalid. To remedy that, would it possible somehow to make `jcupitt.github.io/libvips` redirect to `libvips.github.io/libvips`?

**Comment by jcupitt** [comment]
There was supposed to be a shadow copy of the docs to do the forwarding, but it looks like I accidentally deleted it a couple of days ago, doh!

I've put it back now, thanks!
