### ISSUE TITLE
Renaming the repo broke source installs

### ISSUE THREAD

**Issue by ioquatix** [libvips/libvips#1116]
I'm not sure if you are aware of this, but any build tool which was automatically fetching releases broke because you renamed the organisation.

**Comment by ioquatix** [comment]
Also, your documentation is now wrong, e.g. README.md refers to the old org.

**Comment by jcupitt** [comment]
Hello @ioquatix, yes, sorry, the move will cause some breaks :( 

Hopefully the README is OK now, we're trying to rename things as we find them.

**Comment by jcupitt** [comment]
The background to this change is me having less free time (I now have a full-time job), and libvips slowly getting wider adoption. The libvips organisation is supposed to open up development and spread the load a bit. 

Would you be interested in joining? It'd be great to have someone who knew more about Ruby overseeing ruby-vips.
