### ISSUE TITLE
Changing color of background on vips_text

### ISSUE THREAD

**Issue by hirthanan** [libvips/libvips#1119]
Hey again John,

I was wondering how I could change the background color of the image file generated from black to another RGB color?

![banner_background](https://user-images.githubusercontent.com/9982835/46323905-87989680-c5a5-11e8-8fef-c7bee32734d9.png)

Currently I'm running this:
`vips text banner_background.png "how can I make this have an orange background" --width 100 --height 100 --align centre`

**Comment by jcupitt** [comment]
Hello @hirthanan,

`vips_text()` just makes a one-band mask image. It has no support for colour.

For coloured text, you need to combine it with other operations. For example, in Python:

```python
import sys
import pyvips

mask = pyvips.Image.text("an orange background", dpi=300);
image = mask.ifthenelse([0, 160, 255], [255, 160, 0], blend=True)
image.write_to_file(sys.argv[1])
```

Makes:

![x](https://user-images.githubusercontent.com/580843/46326482-d883ab80-c5f4-11e8-9fa9-a1eff5b1f4be.png)

**Comment by hirthanan** [comment]
I'm trying to modify this vips_watermark function so that the text inside the watermark dynamically resizes with the watermark. 

```
int
vips_watermark(VipsImage *in, VipsImage **out, WatermarkTextOptions *to, WatermarkOptions *o) {
	double ones[3] = { 1, 1, 1 };

	VipsImage *base = vips_image_new();
	VipsImage **t = (VipsImage **) vips_object_local_array(VIPS_OBJECT(base), 10);
	t[0] = in;

	// Make the mask.
	if (
		vips_text(&t[1], to->Text,
			"width", 300,
			"height", 50,
			"dpi", o->DPI,
			"font", to->Font,
			NULL)
		) {
		g_object_unref(base);
		return 1;
	}

	// Replicate if necessary
	if (o->NoReplicate != 1) {
		VipsImage *cache = vips_image_new();
		if (vips_watermark_replicate(t[0], t[4], &cache)) {
			g_object_unref(cache);
			g_object_unref(base);
			return 1;
		}
		g_object_unref(t[4]);
		t[4] = cache;
	}

	// Make the constant image to paint the text with.
	if (
		vips_black(&t[5], 1, 1, NULL) ||
		vips_linear(t[5], &t[6], ones, o->Background, 3, NULL) ||
		vips_cast(t[6], &t[7], VIPS_FORMAT_UCHAR, NULL) ||
		vips_copy(t[7], &t[8], "interpretation", t[0]->Type, NULL) ||
		vips_embed(t[8], &t[9], 0, 0, t[0]->Xsize, t[0]->Ysize, "extend", VIPS_EXTEND_COPY, NULL)
		) {
		g_object_unref(base);
		return 1;
	}

	// Blend the mask and text and write to output.
	if (vips_ifthenelse(t[4], t[9], t[0], out, "blend", TRUE, NULL)) {
		g_object_unref(base);
		return 1;
	}

	g_object_unref(base);
	return 0;
}
```

For some reason, even though I'm passing both a width and a height as the same dimensions as my watermark into vips_text, it is not resizing correctly in the given space. Any idea what's wrong?

**Comment by jcupitt** [comment]
That's from before `vips_text()` had the auto-size feature. To enable auto-size, you must give a width and height in pixels, and it'll set dpi for you.

The docs have the details:

http://libvips.github.io/libvips/API/current/libvips-create.html#vips-text

**Comment by hirthanan** [comment]
> Hello @hirthanan,
> 
> `vips_text()` just makes a one-band mask image. It has no support for colour.
> 
> For coloured text, you need to combine it with other operations. For example, in Python:
> 
> ```python
> import sys
> import pyvips
> 
> mask = pyvips.Image.text("an orange background", dpi=300);
> image = mask.ifthenelse([0, 160, 255], [255, 160, 0], blend=True)
> image.write_to_file(sys.argv[1])
> ```
> 
> Makes:
> 
> ![x](https://user-images.githubusercontent.com/580843/46326482-d883ab80-c5f4-11e8-9fa9-a1eff5b1f4be.png)

I'm trying to achieve a dynamically resizing background with text in the simplest way using the vips C api.

**Comment by hirthanan** [comment]
> That's from before `vips_text()` had the auto-size feature. To enable auto-size, you must give a width and height in pixels, and it'll set dpi for you.
> 
> The docs have the details:
> 
> http://libvips.github.io/libvips/API/current/libvips-create.html#vips-text

Thanks for the help, removing DPI fixed the issue.

**Comment by YasirAlawa** [comment]
You can use something like that
`vips_text(out,"<span foreground=\"red\">Red!</span>",NULL);`

**Comment by Priyanshuiiitg** [comment]
Is it possible to give opacity to the background....

**Comment by jcupitt** [comment]
Sure, eg.:

```
$ vips text x.png '<span background="white">hello</span>' --rgba --dpi 600
```

To make:

![x](https://github.com/user-attachments/assets/83ef5749-5f80-4c20-80af-6db547744d07)
