### ISSUE TITLE
Question: crop tiles with vips

### ISSUE THREAD

**Issue by Gigas002** [libvips/libvips#1122]
Currently I use console version of MapTiler to crop .tif to tiles, the input string looks like
`￼maptiler -o tiles -srs EPSG:4326  -f png map.tif -zoom 0 17`
Is there something like this in vips? I know about dzsave, but it seems like it doesn't have needed parameters, that I wrote above, and also MapTiler naming system of images is quite different. 
I've also heard about gdal2tiles.py, but it needs installed python on target pc to run and also slower then vips.

**Comment by jcupitt** [comment]
You can probably get dzsave to do what you want. What does maptiler do with the parameters you are using above (to save me reading the docs)?

**Comment by Gigas002** [comment]
> You can probably get dzsave to do what you want. What does maptiler do with the parameters you are using above (to save me reading the docs)?

-o is output directory, -srs is dataset projection, -f sets output tile format and -zoom determines which layers of the tile pyramid will be generated.

**Comment by jcupitt** [comment]
Sorry, I need more information. Could you perhaps send a small sample source image and the output that maptiler creates?

**Comment by Gigas002** [comment]
> Sorry, I need more information. Could you perhaps send a small sample source image and the output that maptiler creates?

Sure, here you can have the source image (GeoTIFF) and the result, that maptiler creates. 
The full command line for that result was like: 
`-geodetic -nodata 0 0 0 -f png32 -o result/ -tms -resampling bilinear -srs "+proj=longlat +datum=WGS84 +no_defs" -zoom 8 12 source.tif`
`-geodetic` sets output tiling system to WGS84.
`-nodata 0 0 0` eliminates borders of multiple map sheets that are stitched together.  
`-tms` is tiling scheme OSGEO TMS (bottom-left origin), flipped Y axis as oppose to Google XYZ. This tiling scheme is defined as a standard for MBTiles.


[source.zip](https://github.com/libvips/libvips/files/2454346/source.zip)
[result.zip](https://github.com/libvips/libvips/files/2454347/result.zip)

**Comment by Gigas002** [comment]
I suppose the projections changes can be made through GdalWarp utility, so the main questions are how vips's dzsave work with GeoTIFFs and how to crop to selected zoom. I don't know exactly how MapTiler gets metadata from GeoTIFF, but it later calculates the zoom and exact tile numbers for each output file, as you can see in result.

**Comment by jcupitt** [comment]
Sorry, this dropped off my radar. I'll have a look tomorrow.

**Comment by Gigas002** [comment]
`vips dzsave in filename --layout google` 
Does almost what I need, but it doesn't get real x and y from GeoTiff for naming files/directories, and I can't change levels, that I want to have in result.
Sorry that it takes me too long for answering.

**Comment by Gigas002** [comment]
I've tested gdal2tiles.py recently, and it does exactly what I need, but the speed is low and the output tiles are very pixelated compared to maptiler's, so I'd still prefer vips if it's capable of making tiles this way.
Here's the source code of [gdal2tiles.py](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/scripts/gdal2tiles.py). Sorry I can't say much about it's code because I don't know python. I built it into .exe using PyInstaller and used it this way.
Here's the parameters I used to crop tiles from GeoTiff with gdal2tiles utility:

`gdal2tiles.exe D:\input.tif D:\output -s EPSG:4326 -p geodetic -z 10-14 -a 0,0,0 -r bilinear --tmscompatible --config GDAL_DATA D:\gdal\bin\gdal-data`

where:
-s EPSG:4326 - is the spatial reference system for the input data;
-p geodetic - tile cutting profile (mercator,geodetic,raster);
-z 10-14 - zoom levels to render;
-a 0,0,0 - NODATA transparency value to assign to the input data;
-r bilinear - resampling method;
--tmscompatible - when using the geodetic profile, specifies the base resolution as 0.703125 or 2 tiles at zoom level 0. Really important, the output structure depends on it;
--config GDAL_DATA %path% - path to gdal's additional files;

And [here's](https://www.gdal.org/gdal2tiles.html) the full documentation about gdal2tiles.py params.

**Comment by tmlunde** [comment]
The use case is given one would like to overlay two different images with different coverage area and resolution with deepzoom. For example min x'y and max x'y coordinates for the image are given, for example 0,0 and 1,1 and tiles should be produced for an area between -1,-1 and 1,1 - giving blank tiles between -1,-1 and 0,0 - would this be possible?

**Comment by FridayJew** [comment]
Still no options to set zoom levels to create pyramids? I like the way the vips works, but it can't cut my image into small enough tiles.

**Comment by jcupitt** [comment]
@tmlunde sorry, I missed your post.

Yes, you can enlarge the source image before generating the tiles, if I understand what you mean correctly. But dzsave just chops up big rasters into tiles, it doesn't to any of the reprojection that gdal supports.

**Comment by jcupitt** [comment]
@FridayJew dzsave will go down to 1x1 pixel tiles, it should be able to do what you want, if I understand your problem. Post a new question with an exact description of the behaviour you need.
