### ISSUE TITLE
PDFium?

### ISSUE THREAD

**Issue by robertmeta** [libvips/libvips#1123]
> If present, libvips will attempt to load PDFs via PDFium. This library must be packaged by https://github.com/libvips/docker-builds/tree/master/pdfium

I can't seem to find the docker-builds, am I missing them?

**Comment by jcupitt** [comment]
Ooop, the link has been updated incorrectly, I've fixed it now, thanks!

The correct link is:

https://github.com/jcupitt/docker-builds/tree/master/pdfium

You'll probably need to adapt the files a bit for your platform.

**Comment by robertmeta** [comment]
Thanks, will try but starting to feel like PDFium isn't worth the effort. :)

**Comment by jcupitt** [comment]
The licence is more liberal, but that's about the only advantage at the moment. Poppler is GPL, so you can't easily use it in closed source software.
