### ISSUE TITLE
VImage::new_from_file always returns empty images (Windows 10)

### ISSUE THREAD

**Issue by Fingolfin1196** [libvips/libvips#1125]
When calling `VImage::new_from_file` on a Windows 10 machine (64 bit), I always get an empty image. I'm running the following code:
```cpp
#include <iostream>
#include <vips/vips8>

using namespace vips;

int main(int argc, char *argv[]) {
    VIPS_INIT("FilterGraph");
    std::cout << "Start!" << std::endl;
    const auto image{VImage::new_from_file(R"(C:\Users\fingo\Iguana.jpg)")};
    std::cout << "Is image null: " << image.isNull() << std::endl;
    const auto data{image.data()};
    std::cout << "Is data null: " << (data != nullptr) << std::endl;
    std::cout << "End!" << std::endl;
    return 0;
}
```
Here, `isNull` is a `const` function that returns `vobject != nullptr`.

The console output is the following:
```
Start!
Is image null: 1
Is data null: 1
End!
```
`libvips` finds the file and, using the debugger, I can verify that it calls `VipsForeignLoadJpegFile`, but I can't follow the program any deeper using `gdb`, and the result is always empty. Using a relative path yields the same result.
The program is compiled with MinGW64 from MSYS2, and `libvips` was compiled manually using the same compiler, calling `./configure`, `mingw32-make` (which is, in fact, MinGW64) and `mingw32-make install`. Before that, I manually linked the precompiled version with the same results.
The main file presented above is the only file in a test project built with CMake, which is configured as follows and has no problems linking:
```cmake
cmake_minimum_required(VERSION 3.12)
project(VipsTest)

set(CMAKE_CXX_STANDARD 17)

# pkg-config
find_package(PkgConfig REQUIRED)

# VIPS
pkg_check_modules(VIPS REQUIRED vips vips-cpp gobject-2.0)
include_directories(${VIPS_INCLUDE_DIRS})

add_executable(VipsTest main.cpp)

target_link_libraries(VipsTest ${VIPS_LIBRARIES})
```
All of this works perfectly well on my OpenSUSE installation, but I need a Windows executable.
If any more detailed information is required, I'll be happy to provide it.

**Comment by jcupitt** [comment]
Hello @Fingolfin1196, did you mean to close this?

**Comment by Fingolfin1196** [comment]
Well, the original issue was an oversight on my part, which is why I closed it. I changed the inital comment though to reflect the real issue that I'm facing, which is that on Windows, loading an image file returns empty images.

**Comment by Fingolfin1196** [comment]
This situation is the same when loading a PNG image.

**Comment by Fingolfin1196** [comment]
Sorry, that was an error, too. I'm very sorry, I'll close it again.

**Comment by Fingolfin1196** [comment]
Sorry, that was an error, too. I'm very sorry, I'll close it again.

**Comment by jcupitt** [comment]
No problem, glad it's working.
