### ISSUE TITLE
Modify brightness/contrast of an image

### ISSUE THREAD

**Issue by clcaalu** [libvips/libvips#1126]
Hi,

How can I modify brightness and contrast of an image, on C++?
I've already seached for this question but I couldn't find it. Excuses if it's duplicated.

Thanks,

**Comment by jcupitt** [comment]
Hello @clcaalu, just scale the values. For brightness you'd normally add something, for contrast you normally multiply.

For example:

```c++
// g++ -g -Wall try281.cpp `pkg-config vips-cpp --libs --cflags`
  
#include <vips/vips8>

int
main(int argc, char **argv)
{
  if (VIPS_INIT("test"))
    vips_error_exit(NULL);

  vips::VImage a = vips::VImage::new_from_file(argv[1]);

  // shift everything up
  vips::VImage brightness = a + 50;
  brightness.write_to_file(argv[2]);

  // we want to leave values of 255 alone and pull the dark areas down
  vips::VImage contrast = a * 1.3 - (255.0 * 1.3 - 255.0);
  contrast.write_to_file(argv[3]);

  return 0;
}
```

Run like:

```
$ ./a.out ~/pics/Gugg_coloured.jpg b.jpg c.jpg
```

Gives:

![x](https://user-images.githubusercontent.com/580843/46597792-784fa680-cad9-11e8-8510-dffa2b53a7ce.jpg)

Original, brighter, more contrasty.

**Comment by clcaalu** [comment]
Thanks for the supersonic-speed reply :)
Like always, works like a charm!
