### ISSUE TITLE
HEIC support in libvips

### ISSUE THREAD

**Issue by vikasjio** [libvips/libvips#1127]
Hi:
iOS 12 captures images in heic (and heics) formats/extensions only. However I could not see their support in libvips pages.
May I know about support of heic/heics in libvips? I am mainly interested in its trans coding to JPEG, resizing, cropping, rotation etc. for the same. in which version or any roadmap?

Vikas

**Comment by lovell** [comment]
Hello, please see #671

**Comment by vikasjio** [comment]
Thanks.
