### ISSUE TITLE
Increase transparency of an image (C++)

### ISSUE THREAD

**Issue by clcaalu** [libvips/libvips#1128]
Hi again today : )

How can I make an image which already has 4 bands, more transparent? I guess this is to increase the alpha band, but I don't know how to do it. Help on C++ will be appreciated.

Thanks,
Claudia

**Comment by jcupitt** [comment]
The fourth band (A of RGBA) is opacity, so higher values mean more opaque. All you need to do is scale that down.

For example:

```c++
/* compile with
 *      g++ -g -Wall try282.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <vips/vips8>

int
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        vips::VImage a = vips::VImage::new_from_file(argv[1]);

        a *= {1, 1, 1, 0.5};
        
        a.write_to_file( argv[2] );

        return 0;
}
```

![x](https://user-images.githubusercontent.com/580843/46618372-37768280-cb17-11e8-99e3-0248f3b5063c.png)

The `{ }` syntax is C++-17 -- it gets turned into `std::vector<double>` automatically.

**Comment by clcaalu** [comment]
I'm getting the error "Microsoft C++ exception: std::length_error at memory location"
I wrote the same than you but I am using  VImage::new_from_memory instead of VImage::new_from_file. Do you think it could be the cause?

**Comment by jcupitt** [comment]
Perhaps you are using an old version of MSVC? I don't know when they implemented C++-17 support. 

It shouldn't matter where the image comes from, as long as it has four bands.

**Comment by jcupitt** [comment]
... post a complete sample program that shows the problem and I can probably fix it.

**Comment by jcupitt** [comment]
I'll close. Please reopen if this is still an issue.
