### ISSUE TITLE
vips im_printdesc failing on jp2 images

### ISSUE THREAD

**Issue by tessoldroyd** [libvips/libvips#1129]
Hi,

I am running libvips 8.7 from the command line. I am having trouble getting 'vips im_printdesc image' to work where image is of type .jp2 . I am getting an invalid file format error message.

Previously I was using version 8.6.5 this seemed to be working just fine. I have been using libvips for a while now and have a set of jp2 files that I use for testing, so I know the files are not corrupt. If I roll back to 8.6.5, everything seems to be working just fine.

Is this a bug in the new version?

Thanks,

Tess Oldroyd

**Comment by jcupitt** [comment]
Hello Tess,

I had no idea `im_printdesc` still worked! I'll have a look.

The currently supported thing is supposed to be `vipsheader -a <filename>`.

**Comment by tessoldroyd** [comment]
Thanks. I'll use vipsheader going forward. It seems to be working just fine.

Thanks for your help!
