### ISSUE TITLE
Pyvips install on MacOs

### ISSUE THREAD

**Issue by johndoe46** [libvips/libvips#1131]
Hello,

I developed and app with pyvips successfuly on linux and now I'm trying to install it under macos (the goal is to package it for end users on this OS). Libvips has been installed with macports and the testing is done in a virtualenv. When importing pyvips, here's what I get:
```
(myenv) $ python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
Traceback (most recent call last):
  File "/Users/macuser/myapp/myenv/lib/python3.6/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macuser/myapp/myenv/lib/python3.6/site-packages/pyvips/__init__.py", line 68, in <module>
    gobject_lib = ffi.dlopen(_gobject_libname)
  File "/Users/macuser/myapp/myenv/lib/python3.6/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/macuser/myapp/myenv/lib/python3.6/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/macuser/myapp/myenv/lib/python3.6/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libgobject-2.0.dylib': dlopen(libgobject-2.0.dylib, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0.dylib'
```

So I did a "export DYLD_LIBRARY_PATH="/opt/local/lib"" since I knew libgobject-2.0.dylib was there. Back with the import test I now have another error:

```
OSError: cannot load library '/opt/local/lib/libgobject-2.0.dylib': dlopen(/opt/local/lib/libgobject-2.0.dylib, 2): Symbol not found: _sqlite3_intarray_bind
  Referenced from: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
  Expected in: /opt/local/lib/libsqlite3.dylib
 in /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
```
at which point I just opened site-packages/pyvips/__init__.py and hardcoded a full path in both _vips_libname and _gobject_libname (yes, more yuk).

I guess this probably has more to do with macports than pyvips. I see you recommend installing vips with homebrew instead of macports so it's probably what I'll try anyway.

**Comment by johndoe46** [comment]
Allright, just tested: it's all nice and smooth with homebrew so I'll stick with it. I'll close this now.

**Comment by jcupitt** [comment]
Glad it's working.

The problem may have been the new-ish macOS policy of wiping environment variables before running system binaries. Your new value for `DYLD_LIBRARY_PATH` probably wasn't reaching Python, if you were using the Apple-supplied one. homebrew uses `/usr/local/lib`, which I think macOS will search by default (maybe?).

It's obviously good for security, but it makes the Python and Ruby interpreters that Apple ship difficult to use for development. I think most people install the homebrew Python. It's very unfortunate.

**Comment by johndoe46** [comment]
I'd rather use the python.org package for python but yes, I guess once we taste the convenience of homebrew it's hard to go back.

Talking about convenience (and dev lazyness ;) ), would it be possible to make a wheel package (pyvips+libvips) ? It's probably useless for linux, but I can see a use with macos/windows boxes. Maybe too much work/support...

**Comment by jcupitt** [comment]
pyvips is now in conda: https://libvips.github.io/libvips/2019/08/18/pyvips-in-conda.html

**Comment by johndoe46** [comment]
Not using Conda myself but it's quite popular, good move.
