### ISSUE TITLE
Check if VImage's VipsImage* is null

### ISSUE THREAD

**Issue by Fingolfin1196** [libvips/libvips#1132]
As far as I know, the `VImage` (or, more appropriately, its `VObject` base class) don't offer a possibility to check if the contained `vobject` pointer is null or not, as far as I can tell. This is a problem, since all functions that use `vobject` check if it is null and throw errors if it is, which I can't prevent.
For some time now, I've added a small `bool is_null const` function that just returns `vobject == nullptr`, which serves its purpose, but it's the only reason I need to recompile the library every time and can't just use the repository version.

**Comment by jcupitt** [comment]
Oh, interesting, I'm not sure I've ever needed to test for null. Could you give an example where this is useful?

I'm very happy to accept a PR to add an `is_null` test.

**Comment by Fingolfin1196** [comment]
In the project that I use `libvips` in, getting an empty `VImage` from a function call represents that there is no result. When the `VImage` is null, I (obviously) can't query it's dimensions, bands etc., each of which would lead to segmentation faults. To handle this possibility, a null check would be welcome.

**Comment by jcupitt** [comment]
Merged to git master, thanks!
