### ISSUE TITLE
Retrieving actual width of vips_text image

### ISSUE THREAD

**Issue by hirthanan** [libvips/libvips#1134]
Hi John,

I'm working with the C vips API, and the width of the text generated is much smaller than the max width specified in the command. How can I retrieve the dimensions after calling this command?

```
vips_text(&t[1], "$100",
			"width", 1000,
			"height", 200,
			"font", "Arial"
			"align", VIPS_ALIGN_CENTRE,
			NULL) 
```

FIXED: 
https://github.com/libvips/libvips/issues/521

**Comment by jcupitt** [comment]
Yes, autofit will adjust the DPI so the text fits within the box. It may be smaller, depending on the box aspect ratio.

If you then want an image of exactly that size, use `gravity` to pad the result of text out.

**Comment by jcupitt** [comment]
Eg. in Python:

```python
import sys
import pyvips

image = pyvips.Image.text("HelloWorld!", width=1000, height=200, font="arial")
image = image.gravity("centre", 1000, 200)

image.write_to_file(sys.argv[1])
```

Makes

![x](https://user-images.githubusercontent.com/580843/46813785-3fc8fa80-cd6f-11e8-9c58-eb9b5d26dbc0.png)
