### ISSUE TITLE
Java Wrapper

### ISSUE THREAD

**Issue by volyx** [libvips/libvips#1136]
Hi, I generated JNA Java wrapper. If you are interested in it, here is a repo - https://github.com/volyx/java-vips

It even works and returns current version :)
[Travis Log](https://travis-ci.com/volyx/java-vips)
[Test Source](https://github.com/volyx/java-vips/blob/master/src/test/java/io/github/volyx/TestSuite.java#L10)
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.github.volyx.TestSuite
Version: 7.38.5-Sat Apr  5 11:17:49 UTC 2014
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.56 sec
```

#633

**Comment by jcupitt** [comment]
Oh nice! 

It looks like you're calling the C API. I'd avoid that myself, it makes heavy use of varargs and is a pain from other languages. 

If you drop down a level to the gobject interface, there are no varargs and binding is relatively simple. All the other language bindings (I think) take this route.

Something like the C# binding might be worth looking at:

https://github.com/kleisauke/net-vips

It's a complete, high-level binding in only a couple of thousand lines of C#.

There are some notes here:

https://libvips.github.io/libvips/API/current/binding.md.html
