### ISSUE TITLE
Which libvips function replaces Imagick::mergeImageLayers on transparent PNGs?

### ISSUE THREAD

**Issue by alesvaupotic** [libvips/libvips#1138]
Hello,

I am looking for high speed compositing functions to merge 4-8 tranparent PNG's atop one another, sized around 1500x1500px. Can libvips compete in speed with` Imagick::mergeImageLayers`?

Stepping thru array with `composite2()` or simple `composite()` on whole array of images don't come near in terms of speed, at least in my tests.

http://phpimagick.com/Imagick/mergeImageLayers?layerMethodType=13

**Comment by jcupitt** [comment]
Hello, it should be reasonably quick, I think. You'd need to show a specific benchmark.

I made a set of sample images:

```
john@kiwi:~/try$ vips replicate ~/pics/PNG_transparency_demonstration_1.png x.png 2 3
john@kiwi:~/try$ vipsheader x.png 
x.png: 1600x1800 uchar, 4 bands, srgb, pngload
john@kiwi:~/try$ mkdir sample
john@kiwi:~/try$ for i in {1..5}; do cp x.png sample/$i.png; done
```

Then to compose the five images with libvips it's:

```
john@kiwi:~/try$ /usr/bin/time -f %M:%e vips composite "$(echo sample/*)" out.png 2
40488:0.55
```

So 40mb of memory, 0.55 seconds.

Is there a thing to do `over` on a list of images in imagemagick? I couldn't find one, except going via MIFF, which is slower. If I do it as a set of pairwise operations I see:

```
$ /usr/bin/time -f %M:%e convert sample/1.png sample/2.png -composite sample/3.png  -composite sample/4.png -composite sample/5.png out.png
54012:1.41
```

55mb, 1.41 seconds.

**Comment by jcupitt** [comment]
Oh, there's flatten:

```
$ /usr/bin/time -f %M:%e convert sample/*.png -flatten out.png
143340:1.02
```

But that removes the alpha, and it;s not clear to me exactly how it is merging the image layers.

**Comment by alesvaupotic** [comment]
Thanks for taking time to do this. Would it be to much to ask for your set of images so I can compare the merge to my current setup?

**Comment by jcupitt** [comment]
Sure, that was just the standard PNG demo image:

![png_transparency_demonstration_1](https://user-images.githubusercontent.com/580843/46870868-b7f2f700-ce27-11e8-827f-572009fca99f.png)

**Comment by jcupitt** [comment]
(copied two across and three down, of course)

**Comment by alesvaupotic** [comment]
Oh, I see. I'll check it out right now ... Thanks!

**Comment by alesvaupotic** [comment]
So, here are three runs of each version:

```

root@mybook:/var/www/sample# time vips composite "images/1.png images/2.png images/3.png images/4.png images/5.png" images/out-vips.png 2

real    0m1.046s
user    0m0.952s
sys     0m0.068s
root@mybook:/var/www/sample# time vips composite "images/1.png images/2.png images/3.png images/4.png images/5.png" out-vips.png 2

real    0m1.051s
user    0m0.964s
sys     0m0.060s
root@mybook:/var/www/sample# time vips composite "images/1.png images/2.png images/3.png images/4.png images/5.png" images/out-vips.png 2

real    0m1.072s
user    0m0.976s
sys     0m0.068s
root@mybook:/var/www/sample# time convert -page +0+0 images/1.png -page +0+0 images/2.png -page +0+0 images/3.png -page +0+0 images/4.png -page +0+0 images/5.png  -background none  -layers merge images/out-imagick.png

real    0m0.498s
user    0m0.440s
sys     0m0.028s
root@mybook:/var/www/sample# time convert -page +0+0 images/1.png -page +0+0 images/2.png -page +0+0 images/3.png -page +0+0 images/4.png -page +0+0 images/5.png  -background none  -layers merge images/out-imagick.png

real    0m0.503s
user    0m0.440s
sys     0m0.036s
root@mybook:/var/www/sample# time convert -page +0+0 images/1.png -page +0+0 images/2.png -page +0+0 images/3.png -page +0+0 images/4.png -page +0+0 images/5.png  -background none  -layers merge images/out-imagick.png

real    0m0.500s
user    0m0.440s
sys     0m0.028s
```

**Comment by jcupitt** [comment]
I tried on a big desktop machine:

```
$ time vips composite "$(echo sample/*)" out.png 2
real	0m0.346s
user	0m0.773s
sys	0m0.046s
$ time convert -page +0+0 sample/1.png -page +0+0 sample/2.png -page +0+0 sample/3.png -page +0+0 sample/4.png -page +0+0 sample/5.png  -background none  -layers merge out.png
real	0m0.645s
user	0m1.200s
sys	0m0.032s
```

It could be the compiler flags. `composite` has a fast vector path that needs vector support in your C++ compiler. When you run configure you should see (hopefully):

```
checking for gcc with working vector support... yes
checking for C++ vector shuffle... yes
checking for C++ vector arithmetic... yes
checking for C++ signed constants in vector templates... yes
```

You need gcc 7.3 or later, I think, I'm not sure about other compilers. If it's not detected, `composite` falls back to a not-very-optimised C path.

**Comment by alesvaupotic** [comment]
Wow, that's another story ... I knew there must be something wrong with my installation as I've used libvips many times before with better results. I'll check our config and recompile. 

Thanks for diving into this.  Your support is just excellent, kudos!
