### ISSUE TITLE
How to extract the biggest layer from tha pyramid tiled tiff

### ISSUE THREAD

**Issue by lallori** [libvips/libvips#1139]
Hi!

Is there a simple way using vips tools to extract the biggest layer of a puramid tiled tiff and create JPEG file?

Thanks.

L.

**Comment by jcupitt** [comment]
Hello, yes, when you read a tiff pyramid you get page 0 (the high res layer) by default. So just:

```
vips copy my_pyramid.tif x.jpg
```

will copy the highest layer out as a jpg image.

JPEG is limited to 65k x 65k pixels, so it may not fit, of course.

**Comment by lallori** [comment]
thank you very much. 

I will try it soon and let you know how it goes!
