### ISSUE TITLE
Will libvips benefit from AVX-512

### ISSUE THREAD

**Issue by andrzejbl** [libvips/libvips#1140]
Hi, 

will libvips benefit from https://www.intel.com/content/www/us/en/architecture-and-technology/avx-512-overview.html?

Thanks for your awesome work!

**Comment by kmartinez** [comment]
Many C compilers - with heavy Optimisation turned on - will look for loops which can use SSE. You can test this by writing a tiny bit of repetitive array processing and looking at the optimised assembler - if you see registers called xmm then its doing clever SSE parallelism. The newer avx registers are called things like ZMM0. I must have a look into when this is used. Clearly you should only get these on a CPU which supports avx-512. My guess is good maths libraries will use them possible/suitable.

**Comment by jcupitt** [comment]
Hello @andrzejbl,

It should do, yes. libvips uses three types of vector acceleration:

1. https://github.com/GStreamer/orc ... this is a runtime compiler. libvips generates an abstract assembler at run time, and orc turns that into SIMD for the current CPU. Various intel, amd, mips and arm ISAs are supported. Assuming ORC have added AVX512 support (I've not checked, I should look into this), libvips should use it. All the convolution, morphology and resize operators are sped up with this.

2. https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html ... this is a set of compiler extensions for handling vectors at C level. It's just used for the `composite` operation. libvips only uses `float[4]` (one pixel), so this one probably won't speed up with avx 512. I suspect this is also gcc only, I've not looked at clang support. 

3. Autovectorise. libvips is all marked up for auto vectorisation with `restrict`, and the inner loops are all tuned to be simple to vectorise (I hope). With gcc, you need to set `-march=skylake-avx512` and build with -O3 or above. I've not tried the clang vectoriser.

**Comment by andrzejbl** [comment]
Thank you @jcupitt, @kmartinez for a prompt reply!

So it's all about orc supporting AVX512 if I'm after resizing? 

Do you have any idea how I could test it to make sure that AVX512 speed up a resize task? I will have access to avx 512 CPU and I'd like to find out if https://github.com/lovell/sharp is working faster on it. 
Do you know of any particular set of images that will clearly show that AVX512 speed up the process?

**Comment by jcupitt** [comment]
Yes, as Kirk says you'd need to experiment. You can turn the orc path on and off at runtime, so that one is simple to check.

I have a skylake machine here:

```
john@yingna ~/pics $ more /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
...
```

For a 10k x 10k JPG image I see:

```
$ time vips reducev wtc.jpg x.jpg 1.3
real	0m0.638s
user	0m0.800s
sys	0m0.037s
$ time vips reducev wtc.jpg x.jpg 1.3 --vips-novector
real	0m1.906s
user	0m2.118s
sys	0m0.041s
```

So the orc path is about 3x faster on skylake.

I grepped the orc sources for avx, but found nothing :( It doesn't mean they are not using it, though -- I would do some tests.

**Comment by jcupitt** [comment]
`gaussblur` is a good one too:

```
$ time vips gaussblur wtc.jpg x.jpg 10 --vips-novector
real	0m4.618s
user	0m35.363s
sys	0m0.108s
$ time vips gaussblur wtc.jpg x.jpg 10
real	0m1.260s
user	0m7.812s
sys	0m0.053s
```

So about a 3.7x speedup.

**Comment by kmartinez** [comment]
many of us have 256 bit AVX2 - its the most recent ones that can use 512 bit registers - so we may expect more speed-up. There is some controversy about the AVX subsystem using so much power the core may not be able to max-out its clock frequency... [blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/](https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/)

**Comment by andrzejbl** [comment]
Hi, 

here are my results for 
```

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
```
``` 
$ grep avx /proc/cpuinfo

e4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves amd_ibpb arat pku ospke
```
```
$ vips -v
vips-8.7.0-Mon Sep 10 13:35:49 UTC 2018
```

``` 
$ identify heic0707a.jpg

heic0707a.jpg JPEG 29566x14321 29566x14321+0+0 8-bit sRGB 208.1MB 0.000u 0:00.000
```
```
$ time vips reducev heic0707a.jpg x.jpg 1.3

real    0m12.041s
user    0m13.608s
sys     0m0.292s
```
```
$ time vips reducev heic0707a.jpg x.jpg 1.3 --vips-novector

real    0m12.119s
user    0m13.672s
sys     0m0.300s
```
```
$ time vips gaussblur heic0707a.jpg x.jpg 10

real    0m13.536s
user    2m20.044s
sys     0m0.408s
```
```
$  time vips gaussblur heic0707a.jpg x.jpg 10 --vips-novector

real    0m14.701s
user    2m42.380s
sys     0m0.460s
```

Results are pretty much the same. Do you have any idea what am I doing wrong?

**Comment by jcupitt** [comment]
Hello, I guess you don't have orc enabled. Did you build libvips yourself, or is this the system one?

If you built yourself, check the output of configure carefully. You should see:

```
* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			MagickCore
Magick API version: 			magick6
load with libMagick: 			yes
save with libMagick: 			yes
accelerate loops with orc: 		yes
  (requires orc-0.4.11 or later)
```

I would use orc-0.4.28 or later for stability. Earlier ones are a bit crashy.

**Comment by andrzejbl** [comment]
I built it myself. 
After enabling orc:
```
$ time vips reducev heic0707a.jpg x.jpg 1.3

real    0m6.545s
user    0m8.104s
sys     0m0.312s
```
```
time vips reducev heic0707a.jpg x.jpg 1.3 --vips-novector

real    0m12.184s
user    0m13.724s
sys     0m0.324s
```
Only 1.86 speedup. 
Something else where I can look for speedup like yours?

**Comment by jcupitt** [comment]
Are you using libjpeg-turbo? If you are using regular libjpeg, the very slow decode/recode will make the shrink speedup appear relatively smaller.

You could try using uncompressed tiff instead: that's very fast to read/write, so you'll see the speedup from orc more clearly.

**Comment by andrzejbl** [comment]
I'm using libjpeg-turbo.
Another strange results:
```
 identify heic0707a.tif
heic0707a.tif TIFF 29566x14321 29566x14321+0+0 8-bit sRGB 525.8MB 0.000u 0:00.000
```
```
time vips reducev heic0707a.tif x.jpg 1.3
real    0m9.374s
user    0m10.856s
sys     0m0.380s
```
```
time vips reducev heic0707a.tif x.jpg 1.3 --vips-novector
real    0m14.896s
user    0m16.416s
sys     0m0.328s
```

**Comment by jcupitt** [comment]
I guess that's a vanilla uncompressed tiff? Could you post the output of `tiffinfo`?

I built libvips with -O3 and orc 0.4.28, made an image that size, and I see:

```
john@yingna ~/pics $ tiffinfo huge.tif
TIFF Directory at offset 0x4bb662e2 (1270244066)
  Image Width: 29566 Image Length: 14321
  Resolution: 400, 400 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 128
  Planar Configuration: single image plane
  ICC Profile: <present>, 3144 bytes
john@yingna ~/pics $ time vips reducev huge.tif x.jpg 1.3
real	0m1.827s
user	0m2.952s
sys	0m0.399s
john@yingna ~/pics $ time vips reducev huge.tif x.jpg 1.3 --vips-novector
real	0m7.069s
user	0m8.474s
sys	0m0.349s
```

A ~3.9x speedup.

**Comment by andrzejbl** [comment]
previous tiff was compressed. For uncompressed speedup is 3.65. 
Can I do anything else to have same speedup for jpg?

**Comment by jcupitt** [comment]
I see:

```
john@yingna ~/pics $ vips copy huge.tif huge.jpg
john@yingna ~/pics $ vipsheader huge.jpg 
huge.jpg: 29566x14321 uchar, 3 bands, srgb, jpegload
john@yingna ~/pics $ time vips reducev huge.jpg x.jpg 1.3 --vips-novector
real	0m8.555s
user	0m10.252s
sys	0m0.133s
john@yingna ~/pics $ time vips reducev huge.jpg x.jpg 1.3 
real	0m3.058s
user	0m4.517s
sys	0m0.173s
```

So a 2.8x speedup. It's not as good as the uncompressed tif, since the jpeg decode/encode time is significant.

Are you certain you are using libjpeg-turbo? It can be hard to tell. Test with (on ubuntu):

```
john@yingna ~/pics $ ldd $(which vips) | grep libjpeg
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f71d075a000)
john@yingna ~/pics $ dpkg -S /usr/lib/x86_64-linux-gnu/libjpeg.so.8
libjpeg-turbo8:amd64: /usr/lib/x86_64-linux-gnu/libjpeg.so.8
```

**Comment by felixbuenemann** [comment]
To speedup shrinking jpegs you should use shrink-on-load.

Using shrink-on-load you can decode the JPEG at 1/8, 1/4 or 1/2 the resolution, but the result will be similar to a nearest neighbor scaled image, so to reduce aliasing you can load the JPEG using shrink-on-load to about 2x of the target resolution and then do the rest of the resize with vips.

You can look at the source code for `vipsthumbnail` for an example on how do all that.

**Comment by felixbuenemann** [comment]
Looks like the code has moved to the [vips_thumbnail](https://github.com/libvips/libvips/blob/master/libvips/resample/thumbnail.c) function, which means you could also just use that directly if it fits your use-case.
