### ISSUE TITLE
Can't install vips 8.7.0 on Alpine 3.7 because of missing dependency pc:fftw3

### ISSUE THREAD

**Issue by szimek** [libvips/libvips#1142]
I don't really know much about the package ecosystem in Alpine, but we're using `mhart/alpine-node` Docker image and today the build started to fail with the following error:
```
Step 5/42 : RUN apk add --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/    curl    alpine-sdk    python    bash    lcms2-dev    vips-dev    fftw-dev    libpng-dev    util-linux
 ---> Running in 990799eca125
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  pc:fftw3 (missing):
    required by: vips-dev-8.7.0-r0[pc:fftw3]
                 vips-dev-8.7.0-r0[pc:fftw3]
                 vips-dev-8.7.0-r0[pc:fftw3]
```

Yesterday, it was using `vips-dev-8.6.3-r0` and it worked fine, but now even forcing this version still causes an error:
```
ERROR: unsatisfiable constraints:
  vips-dev-8.7.0-r0:
    breaks: world[vips-dev=8.6.3-r0]
```
so I assume that 8.6.3-r0 no longer exists in the repository.

Any tips how to fix this issue?

**Comment by lovell** [comment]
The `mhart/alpine-node` images are based on Alpine v3.7 but the `vips` package you're installing is in the `edge/testing` repo.

https://github.com/alpinelinux/aports/pull/5385 recently upgraded the `vips` package.

The Alpine v3.7 base image fails in a similar manner, but this is not unexpected when forcing packages built for Alpine Edge on older versions.
```sh
$ docker run -it --rm alpine:3.7 /bin/sh -c "apk add --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ vips-dev"
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  pc:fftw3 (missing):
    required by: vips-dev-8.7.0-r0[pc:fftw3] vips-dev-8.7.0-r0[pc:fftw3] vips-dev-8.7.0-r0[pc:fftw3]
```

Using the latest Alpine Edge image works as expected:
```sh
$ docker run -it --rm alpine:edge /bin/sh -c "apk add --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ vips-dev"
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/65) Installing libjpeg-turbo (1.5.3-r3)
...
```
(If you're using sharp then pre-built binaries for Alpine are now provided.)

**Comment by szimek** [comment]
Thanks! Yeah, we're using sharp, so I'll try to install the prebuilt binaries then ;)

**Comment by sarkistlt** [comment]
any instructions how to use prebuilt binaries? would be really helpful

**Comment by lovell** [comment]
See https://bugs.alpinelinux.org/issues/9561 for a possible workaround.

**Comment by marcj** [comment]
Fixed using

```
# necessary for npm package sharp
RUN apk add --update --no-cache gcc g++ make libc6-compat
RUN apk add vips-dev fftw-dev build-base --no-cache \
        --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ \
        --repository https://dl-3.alpinelinux.org/alpine/edge/main
```

using Alpine 3.8 and sharp@0.21.0.

**Comment by polarathene** [comment]
I had been having trouble with this for some time, the repository links weren't working for me(at least `https` due to SSL errors). I came across alternative ones on [sharps github repo advice for alpine images](https://github.com/lovell/sharp/blob/master/docs/install.md#alpine-linux):

```
apk add vips-dev fftw-dev build-base --update-cache \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/testing/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/main
```

**Comment by tngflx** [comment]
remove that https and make it http it works

**Comment by polarathene** [comment]
@tngflx yes, sorry I later found out that it was a lack of https support for the domain, and didn't update here. 

Is there any real reason to prefer `dl-3.alpinelinux.org` over `alpine.global.ssl.fastly.net`? Isn't `https` preferable?

**Comment by shiny** [comment]
```
apk add vips-dev fftw-dev build-base --no-cache \
        --repository http://dl-3.alpinelinux.org/alpine/edge/community \
        --repository http://dl-3.alpinelinux.org/alpine/edge/main
```

vips-dev has been moved from `testing` to `community`
