### ISSUE TITLE
Can't install vips 8.7.0 on Alpine 3.8 because of missing dependency pc:fftw3

### ISSUE THREAD

**Issue by dbslone** [libvips/libvips#1143]
This may be related to #1142 but my issue is using the `node:8-alpine` base image.  As of this morning I started having issues with building a docker image from `node:8-alpine` that uses vips-dev. The error is as follows:
```
+ apk add vips-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  pc:fftw3 (missing):
    required by: vips-dev-8.7.0-r0[pc:fftw3]
                 vips-dev-8.7.0-r0[pc:fftw3]
                 vips-dev-8.7.0-r0[pc:fftw3]
```

It appears that `vips-dev` is now only available from `alpine:edge` and no longer available for previous versions.

https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=v3.8
vs
https://pkgs.alpinelinux.org/packages?name=vips-dev&branch=edge

Below is an example of my Dockerfile
```
FROM node:8-alpine

# install system dependencies
RUN set -x \
    && apk update \
    && apk add --no-cache \
      curl \
      ffmpeg \
      git \
      imagemagick \
      jq \
      lftp \
      libelf \
      openjdk8 \
      openssh-client \
      parallel \
      postgresql-client \
      python \
      xz \
      zip \
    && apk add vips-dev fftw-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ \
    && rm -rf /tmp/*
```

Is there a way to force the image to use edge instead of 3.8? Or do I need to build vips from source?

**Comment by jcupitt** [comment]
Could this be an alpine packaging problem? If I try:

```
john@kiwi:~ $ docker run --rm alpine:latest
/ # apk add vips-dev --update-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  pc:fftw3 (missing):
    required by: vips-dev-8.7.0-r0[pc:fftw3] vips-dev-8.7.0-r0[pc:fftw3]
                 vips-dev-8.7.0-r0[pc:fftw3]
/ # apk add fftw3
ERROR: unsatisfiable constraints:
  fftw3 (missing):
    required by: world[fftw3]
/ # apk add fftw
(1/4) Installing fftw-double-libs (3.3.6p2-r2)
(2/4) Installing fftw-single-libs (3.3.6p2-r2)
(3/4) Installing fftw-long-double-libs (3.3.6p2-r2)
(4/4) Installing fftw (3.3.6p2-r2)
Executing busybox-1.28.4-r1.trigger
OK: 9 MiB in 17 packages
```

So `fftw` installs fine, but `fftw3` is not there.

Maybe the `vips-dev` package has a typo? Should it be pulling in `fftw` rather than `fftw3`?

**Comment by jcupitt** [comment]
I don't know much about Alpine. I'd check the issues on their `vips-dev` package.

**Comment by dbslone** [comment]
According to https://pkgs.alpinelinux.org/package/edge/main/x86/fftw-dev
`fftw-dev` doesn't install a subpackage called `fftw3` but does install one called `fftw` so maybe that is the issue

**Comment by dbslone** [comment]
@jcupitt when I look at https://hub.docker.com/_/alpine/ it shows that `alpine:latest` uses version 3.8 and not `edge`.

If I use the suggestion from @lovell in #1142 
```
docker run -it --rm alpine:edge /bin/sh -c "apk add --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ vips-dev"
```
it will build correctly from the terminal but anything not pointed at `alpine:edge` will not build

**Comment by lovell** [comment]
Hello, this looks like the same issue as #1142, namely an attempt to use the `vips` package from the `testing/edge` repo on non-Edge versions.

**Comment by dbslone** [comment]
@lovell sorry for the duplication wasn't sure if the issues were related. where can I find the correct repository url for non-edge versions?

**Comment by dbslone** [comment]
Thanks that helped me resolve my issue by upgrading the version of sharp and setting the ENV variable in my Dockerfile
