### ISSUE TITLE
Support separate in/out gamma values

### ISSUE THREAD

**Issue by Daiz** [libvips/libvips#1144]
Hello. I have a use case with ImageMagick where I scale grayscale images (the same black & white comics I talked about in #966) with different gamma in & out values. Basically, I do `convert in.png -gamma 0.454545 -filter Mitchell -resize xXXXX -gamma 1.8 out.png` - in other words, I first convert the source 2.2 gamma image to linear light with `1/2.2`, but then I set the output gamma to `1.8` (which came about as a result of subjective testing for optimal perceived image quality). However, with `vips_gamma()` and `exponent` it does not seem possible to replicate this at the moment - you can only use the same exponent going in (1/X) and out (X). It would be nice if it was possible to define two separate values for this like you can with ImageMagick's gamma operation.

As additional information, I am using libvips through [sharp](https://github.com/lovell/sharp), but my impression seems to be that this matter concerns libvips itself, which is why I'm filing the issue here.

**Comment by jcupitt** [comment]
Hello, you can do the same thing in vips. For example, in Python:

```
john@kiwi:~/pics$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x = x.gamma(exponent=1.0/2.4)
>>> x = x.resize(0.2, kernel="mitchell")
>>> x = x.gamma(exponent=1.8)
>>> x.write_to_file("x.jpg")
```

Should do what you want. Sharp would need to support a second gamma though.

**Comment by jcupitt** [comment]
Does sharp let you set a colourspace? You could set scrgb (linear rgb), then a gamma of 1.8 on the output.

**Comment by Daiz** [comment]
I think the main issue here is the way sharp's `.gamma()` function and pipelining works. Regardless, seeing as it is possible to fiddle with the gamma in libvips basically in the same manner as in ImageMagick, I can probably do something about this on sharp's end myself and hopefully make a pull request (or at least an issue) there to change this. Thanks for the info!
