### ISSUE TITLE
vips_thumbnail_buffer: pass options to underlying image loader

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#1147]
When using [`vips_thumbnail_buffer`](https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-buffer), there's no possibility to pass options to the underlying image loader (see [here](https://gist.github.com/kleisauke/0109790229d0b05e0ccc621a957aa5d8) for a C++ example).

Hints for implementation:
A simple way to solve this issue is to add a new `option_string` parameter (`"[name=value,...]"`) to `vips_thumbnail_buffer` and pass this string to the [`vips_image_new_from_buffer`](https://jcupitt.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-buffer) calls:

https://github.com/libvips/libvips/blob/ecdbf66f4dde3865f02b4974c798848839fc414c/libvips/resample/thumbnail.c#L841-L845

(Not sure if this will break API compatibility, perhaps a compatibility stub needs to be added.)

**Comment by jcupitt** [comment]
Yes, you're right, that's an oversight :( 

I suppose we'd need to add a new optional param, `open_args` or somesuch, with a string that gets passed down to `new_from_buffer`.
