### ISSUE TITLE
Bilinear triangle filter for upscaling

### ISSUE THREAD

**Issue by Rudgas** [libvips/libvips#1148]
Hi, I'd like to request the implementation of a/the triangle bilinear filter (As can be found in Pillow) for the upscaling of images.

**Comment by jcupitt** [comment]
This would need a new interpolator subclass with a 3x3 stencil, see

https://github.com/jcupitt/libvips/blob/master/libvips/resample/interpolate.c#L518

**Comment by jcupitt** [comment]
Hi, and thanks for opening the issue, btw

**Comment by jcupitt** [comment]
I had a look, but simply adding a new interpolator type for affine would not be enough. A triangle filter needs to know the scale factor, and that doesn't really exist here.

Fixing this will need an upscaling analogue of `reduce`.

**Comment by Rudgas** [comment]
Thanks for looking into this so quickly! I'm afraid going into the code myself is beyond me at the moment.

**Comment by Rudgas** [comment]
Ok, forget this request, I made a stupid mistake in my stacking code, using the wrong variable for iteration I stacked the same image. Results are very good now and hardly distinguishable from Pillows upscaling algorithm (when stacked). Thanks again for the quick response and friendly feedback!
