### ISSUE TITLE
shrink-on-load for openslide images

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1149]
The shrink-on-load logic in thumbnail does not have a path for openslide images. 

We'd need to: 

- open the base image
- read `openslide.level-count` to get the number of layers
- starting from `level_count - 1` (lowest res), step up the layers until we find one larger than the target (check `openslide.level[level].width` and `.height`) 
- perhaps should be larger by at least x2? though openslide levels are very spread out, so this could be very expensive
- open that layer as the source image

See https://github.com/libvips/pyvips/issues/72

**Comment by renexu** [comment]
@jcupitt have you scheduled this enhancement in a future release? when will it be?
Thank you.

**Comment by jcupitt** [comment]
Yes, it's in 8.8, due in the next month or two. You can build git master and get it now if you want.
