### ISSUE TITLE
vips_pngsave fails on a few files. No pattern seen.

### ISSUE THREAD

**Issue by JimHoving** [libvips/libvips#1150]
I was working on a thumbnailer and two cbz files did not produce thumbnails. The error was : 
>(cbztest:29227): VIPS-WARNING **: profile 'icc': 'desc': ICC profile tag start not a multiple of 4
cbztest: Save failed.
vips2png: unable to write "TMB_001.png"

The error is 100% reproducible even with the vipsthumbnail program:
>vipsthumbnail --vips-leak  -o tn_%s.png 001.jpg
(vipsthumbnail:5183): VIPS-WARNING **: profile 'icc': 'desc': ICC profile tag start not a multiple of 4
vipsthumbnail: unable to thumbnail 001.jpg
vips2png: unable to write "./tn_001.png"
memory: high-water mark 0 bytes

I have included error producing drawings. One is a bit lewd so its in an encrypted zip file, password "dirty". **Don't decrypt if you are offended by obscene manga drawings of ladies!**
[001.jpg.zip](https://github.com/libvips/libvips/files/2535397/001.jpg.zip)
![f_no_meikyuu-page-001](https://user-images.githubusercontent.com/44647591/47804077-301c5080-dd34-11e8-92ca-d733d6901bcd.jpg)

I buildt libvips from the source in the project pages tgz file so the problem might be in my environment.

>/projects/cbztest# ldd /usr/local/bin/vipsthumbnail
        linux-vdso.so.1 (0x00007ffcbb096000)
        libvips.so.42 => /usr/local/lib64/libvips.so.42 (0x00007fc50308a000)
        libMagickCore-7.Q16.so.6 => /usr/lib64/libMagickCore-7.Q16.so.6 (0x00007fc502bce000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fc502998000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc502781000)
        libtiff.so.5 => /usr/lib64/libtiff.so.5 (0x00007fc50250a000)
        libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007fc502287000)
        libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007fc502083000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fc501e51000)
        libpangoft2-1.0.so.0 => /usr/lib64/libpangoft2-1.0.so.0 (0x00007fc501c3d000)
        libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007fc5019f7000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007fc5017b4000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fc5014fb000)
        libfftw3.so.3 => /usr/lib64/libfftw3.so.3 (0x00007fc5011bc000)
        liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007fc500f3f000)
        liblcms2.so.2 => /usr/lib64/liblcms2.so.2 (0x00007fc500ce5000)
        libgif.so.7 => /usr/lib64/libgif.so.7 (0x00007fc500adc000)
        librsvg-2.so.2 => /usr/lib64/librsvg-2.so.2 (0x00007fc5008a7000)
        libgio-2.0.so.0 => /usr/lib64/libgio-2.0.so.0 (0x00007fc50050d000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007fc5002e9000)
        libpoppler-glib.so.8 => /usr/lib64/libpoppler-glib.so.8 (0x00007fc50008b000)
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007fc4ffe37000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007fc4ffb25000)
        libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007fc4ff800000)
        libwebpmux.so.2 => /usr/lib64/libwebpmux.so.2 (0x00007fc4ff5f6000)
        libwebp.so.6 => /usr/lib64/libwebp.so.6 (0x00007fc4ff397000)
        libexif.so.12 => /usr/lib64/libexif.so.12 (0x00007fc4ff152000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc4fedc9000)
        libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libgomp.so.1 (0x00007fc4feb9b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc4fe97b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc4fe5b3000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6 (0x00007fc4fe1ae000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libgcc_s.so.1 (0x00007fc4fdf97000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007fc4fdc35000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007fc4fda23000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fc4fd6e7000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc4fd4d6000)
        libltdl.so.7 => /usr/lib64/libltdl.so.7 (0x00007fc4fd2cc000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc4fd0c8000)
        libfribidi.so.0 => /usr/lib64/libfribidi.so.0 (0x00007fc4fceb0000)
        libgthread-2.0.so.0 => /usr/lib64/libgthread-2.0.so.0 (0x00007fc4fccae000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007fc4fc9f2000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fc4fc7eb000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc4fc5e3000)
        libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007fc4fc3d6000)
        libcroco-0.6.so.3 => /usr/lib64/libcroco-0.6.so.3 (0x00007fc4fc19a000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc4fbf83000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007fc4fbd2a000)
        libpoppler.so.73 => /usr/lib64/libpoppler.so.73 (0x00007fc4fb876000)
        libffi.so.6 => /usr/lib64/libffi.so.6 (0x00007fc4fb66d000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fc4fb3fa000)
        libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007fc4fb15b000)
        libEGL.so.1 => /usr/lib64/opengl/nvidia/lib/libEGL.so.1 (0x00007fc4faf49000)
        libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007fc4fad45000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fc4fab1b000)
        libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007fc4fa90d000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007fc4fa703000)
        libGL.so.1 => /usr/lib64/opengl/nvidia/lib/libGL.so.1 (0x00007fc4fa45f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc50386c000)
        libicuuc.so.63 => /usr/lib64/libicuuc.so.63 (0x00007fc4fa09b000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007fc4f9e6f000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fc4f9c1f000)
        libopenjp2.so.7 => /usr/lib64/libopenjp2.so.7 (0x00007fc4f99cd000)
        libGLdispatch.so.0 => /usr/lib64/opengl/nvidia/lib/libGLdispatch.so.0 (0x00007fc4f96ff000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fc4f94fb000)
        libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007fc4f92f5000)
        libGLX.so.0 => /usr/lib64/opengl/nvidia/lib/libGLX.so.0 (0x00007fc4f90c5000)
        libicudata.so.63 => /usr/lib64/libicudata.so.63 (0x00007fc4f74d7000)
        libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007fc4f72c0000)

**Comment by jcupitt** [comment]
Hello, yes I see the error here too. I'll have a look.

**Comment by jcupitt** [comment]
It looks like this is "expected" behavior from libpng -- it will signal an error if you attempt to write a PNG with an invalid ICC profile. The only thing libvips could do would be to ignore ALL libpng errors, which is not great.

I'm not sure what the best solution is. You can pass `strip` to the saver to remove all metadata, but thats not a great solution either.

```
john@kiwi:~/Downloads$ vips copy 001.jpg x.png

(vips:8145): VIPS-WARNING **: 17:24:24.585: profile 'icc': 'desc': ICC profile tag start not a multiple of 4
vips2png: unable to write "x.png"
john@kiwi:~/Downloads$ vips copy 001.jpg x.png[strip]
john@kiwi:~/Downloads$ 
```

**Comment by JimHoving** [comment]
You would think that the ICC profile would be lost in the conversion from jpg to png and the scaling of the image to the thumbnail. But I do not know a lot about image processing. :-)

I think "strip" will work fine for me since it is just a thumbnail and the saved image has no real value in it self.

Thanks for the help!

**Comment by jcupitt** [comment]
OK, sounds good. You can delete just the profile if you're using Python / C / PHP / etc., that would be less damaging. 

You'll find the colour can get messed up if you drop profiles and don't handle them.

**Comment by JimHoving** [comment]
Gray scale it is! :-) better than no thumbnail.
Now I just have to figure out which images are "bad" to strip colour and ICC.

**Comment by JimHoving** [comment]
Just tested this and it works like a charm!
Why check if the file is OK when VIPS and do it for you? :-D

if(vips_pngsave(ThumbOut, szOutFileName, NULL))
{
        // Did the save fail? Try again swith no profile
	printf("We are stripping the profile!\n");
	if(vips_pngsave(ThumbOut, szOutFileName,"profile","none" , NULL))
	    vips_error_exit("Save failed."); // We failed again
}

**Comment by JimHoving** [comment]
Problem is due to libpng behaviour and can easily be circumvented. Closing issue.
