### ISSUE TITLE
O_TMPFILE doens't work on each FS

### ISSUE THREAD

**Issue by wonko** [libvips/libvips#1151]
The changes introduced in https://github.com/jcupitt/libvips/commit/06802e41107d7125f12168b32fcbb045782d4c13 assumes that the filesystem mounted on `/tmp` has the capability to handle the O_TMPFILE flag. This is not always the case, making vips fail when trying to create these temporary files. 

Our use case was running vips in a docker container (docker for mac, nfs + overlayfs) but there might be others. I "fixed" this by removing the content from this commit from the code in my build (& applying a bit of C knowledge).

There should be a way to disable this behaviour, either at compile time or by adding a flag to the binary when running it. The later might be the more flexible option, the former the easier (but a bit brutal).

**Comment by jcupitt** [comment]
Oh no! I had no idea it didn't work everywhere. 

How does the failure happen? Does the `open()` call fail with `O_TMPFILE` set, or does it simply fail to delete the file?

**Comment by lovell** [comment]
This was reported a few days ago by @bodaniel - see https://github.com/lovell/sharp/issues/1436

The problem is that `O_TMPFILE` might be available at compile time but the necessary syscall not available in the kernel at runtime (e.g. Docker uses the host kernel).

Falling back to use a standard temporary file on failure would be the best approach.

**Comment by jcupitt** [comment]
Ah, looks like the `open()` fails, that's good, thank @lovell . 

I agree, it should be possible to have it fall back at runtime.

**Comment by wonko** [comment]
It fails as such:

```
/tmp # vips thumbnail_image in.jpg ...
VipsImage: unable to write to "/tmp/vips-0-1748437187.v"
unix error: Not supported
/tmp # 
```

Stracing this gives me the open call failing:

```
[pid 16721] open("/tmp", O_RDWR|O_TMPFILE, 0666) = -1 EOPNOTSUPP (Not supported)
```
which will eventually lead to the write failing (as there is no filehandle)

**Comment by eriken** [comment]
I still got this issue even with 8.7.1. However, I realised that the only host that had this issue was on the 3.13 kernel version. Once I migrated all to hosts with 4.14 kernel versions the errors vanished, for now atleast.

**Comment by eriken** [comment]
> unable to process image, reason: VipsImage: unable to write to "/tmp/vips-28-1779762517.v"
> unix error: Operation not supported

**Comment by jcupitt** [comment]
I tried in docker and it's working OK there -- O_TMPFILE fails and it correctly falls back to a plain open. I tried on a system with no O_TMPFILE support and that worked too.

I've added a bit more logging to 8.7.2, would you be able to try that? (head of 8.7 branch). Run with `--vips-info` and you should get some more output explaining what's happening.

**Comment by eriken** [comment]
@jcupitt 
We migrated all our containers to hosts with 4.14 kernels. It is not straight forward nor desirable to migrate these back.

Did you try this in docker using a container based on an image with a 3.13 kernel? If so a test that triggers temp writes should result int the error. 

This was the exact `uname` output:
> Linux host 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jcupitt** [comment]
You can't change the kernel in Docker, just userland, so I'd need a VM to try your environment. Is that Ubuntu 16.04?

**Comment by eriken** [comment]
Ah, ofc, my bad.

14.04 should give you a 3.x kernel.

**Comment by jcupitt** [comment]
I've tried 12.04, but it's all broken, unfortunately :( You can't install any packages due to hash mismatches. I don't think I'll be able to test this.

**Comment by eriken** [comment]
@jcupitt 
I will implement lbvips in another service we are running shortly. I am almost guaranteed to run into the same issue then as it will run on a lot of hosts running a mix of kernel versions. I will keep you updated.

**Comment by jcupitt** [comment]
OK, that would be great, thank you! 

As I said, the head of the 8.7 branch (8.7.2) has some extra logging for this issue, so if you could try that with `--vips-info` enabled, that might help clear it up.
