### ISSUE TITLE
How to set VIPS_DEBUG flag in my code using vips

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1156]

**Comment by jcupitt** [comment]
Hello,

Could you give some context? What output do you need, what code do you need it from, what are you trying to accomplish etc.

**Comment by tczf1128** [comment]
I want print this debug log when my program call vips functions.
`
#ifdef VIPS_DEBUG
	printf( "vips_cache_operation_buildp: " );
	vips_object_print_dump( VIPS_OBJECT( *operation ) );
#endif /*VIPS_DEBUG*/
`

**Comment by jcupitt** [comment]
Ah OK. You can set the `VIPS_DEBUG` macro in the configure line like this:

```
CFLAGS="-DVIPS_DEBUG" ./configure --prefix=...
```

when you build libvips, but that will produce a crazy amount of output. Usually it's best to edit the file you want to see output from (`operation.c` in your example) and uncomment the `#define` at the top:

https://github.com/libvips/libvips/blob/master/libvips/iofuncs/operation.c#L35

then rebuild.

**Comment by tczf1128** [comment]
thanks.
