### ISSUE TITLE
Method to calculate integral image (summed-area table) in libvips?

### ISSUE THREAD

**Issue by erdmann** [libvips/libvips#1160]
Hi John,

I often have need of integral images in performing various operations on extremely large images, such as large box filters (c.f. "Efficient and Accurate Gaussian Image Filtering Using Running Sums" [https://arxiv.org/pdf/1107.4958.pdf](url)).  However, I can't seem to find the right operation in libvips.

Is there a way to do this?  In other words, I'm looking for the libvips way to obtain the image one would get in numpy with:

`integral_image = im.cumsum(axis=0).cumsum(axis=1)`

Along similar lines, I often resort to calculating `im.avg() * im.width * im.height` to compute the overall sum of the pixels in a 1-band image, but this seems backward.  I'm aware of `vips_stats()`, but this also seems inefficient if the sum is all that's needed.  Is there a better way?

Many thanks in advance.

**Comment by jcupitt** [comment]
Actually, I think a simple W x H box of 1s will be optimised to a single box anyway, you probably don't need to set layers to 1.

It'll automatically turn your 2D box into a pair of 1D boxes too, I think.

**Comment by erdmann** [comment]
The difference of a pair of cumsums would often be enough, yes.  

I had imagined that the single-axis (horizontal, say) cumsum could be made efficient by taking advantage of the recursive structure of the computation and the fact that it's embarrassingly parallel since the individual rows are independent of each other.  Basically, to compute it tile-wise, and then make a final pass to add the correct offset profile for each tile by looking at the right edge of the one to its left.  I see that vips is able to compute `im.project()`, so maybe I can hack something together using `project` with strips of the image...

In re: the approximate filter:  excellent.  I have often wondered whether I should just take arbitrary convolution kernels and use SVD to write them as sums of outer products, to approximate the kernel to desired precision as a sum of separable ones.

Thanks again!

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
