### ISSUE TITLE
Turn black pixels into transparent pixels

### ISSUE THREAD

**Issue by clcaalu** [libvips/libvips#1165]
Hi,

I have an image in black and white, which already has 4 bands.
I want to turn black pixels into transparent pixels. How can I do that?

**Comment by jcupitt** [comment]
Hello, find all black pixels, then use `ifthenelse` to swap those for whatever you want. 

In Python:

```python
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])

# x == 0 on a 4 band image makes a 4 band mask with 0/255 for true/false
# to find pixels where x == 0 for all bands, we need to AND bands together 
mask = (x == 0).bandand()

# you can write pixel constants as arrays, so this will use RGBA [0, 0, 0, 0] as the pixel 
# for every point for which the mask is true, and x otherwise
x = mask.ifthenelse([0, 0, 0, 0], x)

x.write_to_file(sys.argv[2])
```

**Comment by clcaalu** [comment]
Thanks! I guessed the right approach : )
I forgot to mention I am working on C++. So when I try to use:
```
std::vector<float> v = { 0.0, 0.0, 0.0, 0.0 };
image_type res;
try {
	res = layerScaled.ifthenelse(v, layerScaled);
}catch (VError v) { printf("\n%s", v.what()); return false; }
```
I cannot even compile:
Error	C2664	'vips::VImage vips::VImage::ifthenelse(double,double,vips::VOption *)': cannot convert argument 1 from 'std::vector<float,std::allocator<_Ty>>' to 'vips::VImage'

and if I use  ` res = layerScaled.ifthenelse([0,0,0,0], layerScaled); ` it thinks is a lambda function...

If I use ` res = layerScaled.ifthenelse(125, layerScaled); ` works fine, but is not what I want

How can I do it, then?

**Comment by clcaalu** [comment]
Ok, the std::length_error is solved now. I had a 5 bands image cause I was using vips_addalpha and I didn't need to.
Now I get the error "Access violation reading location"

**Comment by jcupitt** [comment]
It's best to post complete programs I can etst, otherwise I'm not sure what's going on :( 

I made you a demo:

```c++
/* compile with
 *      g++ -g -Wall trans.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <vips/vips8>

int
main( int argc, char **argv )
{       
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        vips::VImage x = vips::VImage::new_from_file( argv[1] );

        vips::VImage mask = (x == std::vector<double>{0, 0, 0, 255}).bandbool( VIPS_OPERATION_BOOLEAN_AND );

        x = mask.ifthenelse(std::vector<double>{0, 0, 0, 0}, x);

        x.write_to_file(argv[2]);

        return( 0 );
}  
```

And a test image:

![x](https://user-images.githubusercontent.com/580843/48622444-b4aad800-e99e-11e8-8970-c4e6031e918d.png)

If I run:

```
$ g++ -g -Wall trans.cpp `pkg-config vips-cpp --cflags --libs`
$ ./a.out x.png y.png
```

I see:

![y](https://user-images.githubusercontent.com/580843/48622497-e2901c80-e99e-11e8-9c2c-f34edd11236d.png)

(pure black pixels have become transparent and show the white of the github page, grey pixels stay grey)

**Comment by jcupitt** [comment]
`bandand()` was missing from the cpp binding, it must have been dropped somehow. I've added it now, thanks!
