### ISSUE TITLE
vips dzsave from SVG:  Background is always only black

### ISSUE THREAD

**Issue by charger472** [libvips/libvips#1166]
Hi there

I try the dzsave from an SVG File and the background is always black in the jpeg. The SVG is transparent background.  What I like is a white background for the jpeg tile images.

I tried the following:

vips.exe dzsave input/myfile.svg[dpi=150] output/DZI --tile-size=256 --background 255

I use: vips-dev-8.7 for Windows
Here is the SVG File (simply Boxes and Text) 
[myfile.zip](https://github.com/libvips/libvips/files/2591568/myfile.zip)

Any ideas?

**Comment by jcupitt** [comment]
Hello, you need to give the baclground param to the thing that does the writing. For example:

```
$ vips copy myfile.svg[dpi=1] x.jpg[background=255]
```

sets background for the jpeg writer and makes:

![x](https://user-images.githubusercontent.com/580843/48660175-51c84800-ea55-11e8-9fc3-5d6e55bcfbd6.jpg)

For dzsave, the writer is given params via the `--suffix` argument, so:

```
$ vips dzsave myfile.svg[dpi=150] x --suffix=.jpg[background=255,Q=90]
```

Should do what you want.

**Comment by charger472** [comment]
Thank you!  I got a solution to export the SVG with white background.  But I will try your solution too.
