### ISSUE TITLE
vips support gif save now?

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1167]

**Comment by jcupitt** [comment]
Yes. There's now `magicksave`, and that includes GIF support.

```
$ vips copy horse.gif[n=-1] x.gif
```

Makes:

![x](https://user-images.githubusercontent.com/580843/48708239-ed92b900-ebf9-11e8-8925-5da96a142699.gif)

**Comment by tczf1128** [comment]
use which version?

**Comment by jcupitt** [comment]
It's in 8.7, the current stable version.

Cropping would be harder: you'd need to do some coding for that.

**Comment by tczf1128** [comment]
you mean I should do some work before crop gif image? Could you give me some tips?

**Comment by jcupitt** [comment]
If you load a GIF in libvips it is a tall, thin image. You'll need to cut each frame out, reassemble them, set the page-height, and save. There are some notes here:

https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html#toilet-roll-images

**Comment by tczf1128** [comment]
which APIs should I use?

**Comment by jcupitt** [comment]
I made a demo for you:

```python
import sys
import pyvips

# load all frames from file using n=-1
image = pyvips.Image.new_from_file(sys.argv[1], n=-1)
outfile = sys.argv[2]
left = int(sys.argv[3])
top = int(sys.argv[4])
width = int(sys.argv[5])
height = int(sys.argv[6])

# the image will be a very tall, thin strip, with "page-height" being the height
# of each frame
page_height = image.get("page-height")
n_frames = image.height / page_height

# make a list of new frames
frames = [image.crop(left, i * page_height + top, width, height)
          for i in range(0, n_frames)]

# assemble the frames back into a tall, thin image
def join(strip, frame):
    return strip.join(frame, "vertical")

new_image = reduce(join, frames)

# set the new page-height
new_image.set("page-height", height)

# and save back again
new_image.write_to_file(outfile)
```

I see:

```
$ python cropgif.py ~/pics/horse.gif x.gif 10 10 100 100
```

To make:

![x](https://user-images.githubusercontent.com/580843/48832477-2608d300-ed71-11e8-92bb-a5d4ee690dd0.gif)

**Comment by tczf1128** [comment]
Thanks so much!   it support insert other images or text in gif. My service is a image merge service,it insert images or texts into one image.

**Comment by jcupitt** [comment]
Sure, just add the text before you save again.

**Comment by tczf1128** [comment]
also support add images like png or jpg on this gif?

**Comment by jcupitt** [comment]
Of course, you can do anything.

**Comment by tczf1128** [comment]
ok. I will try it. Thanks

**Comment by zhaohuxing** [comment]
@jcupitt May I ask, does `libvips` support GIF format picture format conversion, crop, resize, and rotation processing?

**Comment by jcupitt** [comment]
@zhaohuxing yes, it does.

There's an example of crop a few posts back ^^ https://github.com/libvips/libvips/issues/1167#issuecomment-440598247

**Comment by zhaohuxing** [comment]
> If you load a GIF in libvips it is a tall, thin image. You'll need to cut each frame out, reassemble them, set the page-height, and save. There are some notes here:
> 
> https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html#toilet-roll-images

This link is 404

**Comment by jcupitt** [comment]
The new URL is: https://libvips.github.io/libvips/2017/03/16/What's-new-in-8.5.html

**Comment by sethify** [comment]
@jcupitt You wouldn't have any guidance on how attempt the python crop example above using the C api would you? We are not using thumbnail and have working code (on 1 page images) for resize and crop. At current, we can only perform resize on animated images (with a small 1 pixel tracking issue in the vertical, which must be rounding).

**Comment by jcupitt** [comment]
Here's a python program (from another issue) to annotate every frame in an animation:

```python
#!/usr/bin/python3

import sys
import pyvips

# load the animation, chop into pages
image = pyvips.Image.new_from_file(sys.argv[1], n=-1, access="sequential")
page_height = image.get("page-height")
n_pages = image.get("n-pages")
pages = [image.crop(0, page_number * page_height, image.width, page_height) 
         for page_number in range(0, n_pages)]

# generate the overlay ... a solid red squarem, then draw a transparent rect 
# inside that
overlay = pages[0].new_from_image([255, 0, 0, 255])
overlay = overlay.draw_rect(0, 
                            10, 10, overlay.width - 20, overlay.height - 20,
                            fill=True)

# render the overlay on every page
for i in range(len(pages)):
    pages[i] = pages[i].composite(overlay, 'over')

# recombine pages, save
recombined = pyvips.Image.arrayjoin(pages, across=1)
recombined.write_to_file(sys.argv[2])
```

And the same thing in C:

```C
/* compile with:
 *
 * 	gcc -g -Wall annotate-animated.c `pkg-config vips --cflags --libs`
 *
 */

#include <vips/vips.h>

static int
annotate_image( VipsObject *context, VipsImage *image, VipsImage **out )
{
	int page_height = vips_image_get_page_height( image );
	int n_pages = image->Ysize / page_height;
	VipsImage **overlay = (VipsImage **)
		vips_object_local_array( context, n_pages );
	VipsImage **page = (VipsImage **)
		vips_object_local_array( context, n_pages );
	VipsImage **annotated = (VipsImage **)
		vips_object_local_array( context, n_pages );

	/* Red as RGBA.
	 */
	double red[] = { 255, 0, 0, 255 };
	double transparent[] = { 0, 0, 0, 0 };

	int i;

	/* Split the image into frames.
	 */
	for( i = 0; i < n_pages; i++ )
		if( vips_crop( image, &page[i],
			0, page_height * i, image->Xsize, page_height, NULL ) )
			return( -1 );

	/* Make an overlay ... a solid red square, with a transparent hole.
	 */
	if( 
		!(overlay[0] = vips_image_new_from_image( page[0], 
			red, VIPS_NUMBER( red ) )) ||
		vips_draw_rect( overlay[0], 
			transparent, VIPS_NUMBER( transparent ),
			10, 10, overlay[0]->Xsize - 20, overlay[0]->Ysize - 20,
			"fill", TRUE,
			NULL ) )
		return( -1 );

	/* Draw the overlay on every page.
	 */
	for( i = 0; i < n_pages; i++ )
		if( vips_composite2( page[i], overlay[0], &annotated[i],
			VIPS_BLEND_MODE_OVER, NULL ) )
			return( -1 );

	/* Reassemble the frames.
	 */
	if( vips_arrayjoin( annotated, out, n_pages, 
		"across", 1,
		NULL ) )
		return( -1 );

	return( 0 );
}

int 
main( int argc, char **argv )
{
	VipsImage *image;
	VipsObject *context;
	VipsImage *x;

	if( VIPS_INIT( NULL ) ) 
		vips_error_exit( NULL ); 

	if( !(image = vips_image_new_from_file( argv[1], 
		"access", VIPS_ACCESS_SEQUENTIAL,
		NULL )) )
		vips_error_exit( NULL ); 

	context = VIPS_OBJECT( vips_image_new() );
	if( annotate_image( context, image, &x ) ) {
		g_object_unref( image );
		g_object_unref( context );
		vips_error_exit( NULL ); 
	}
	g_object_unref( image );
	g_object_unref( context );
	image = x;

	if( vips_image_write_to_file( image, argv[2], NULL ) ) {
		g_object_unref( image );
		vips_error_exit( NULL ); 
	}

	g_object_unref( image );

	return( 0 );
}
```

**Comment by sethify** [comment]
@jcupitt that is brilliant. Thank you. I've done an insane amount of reading and googling. Your example provided me with more context than anything I've found so far. Is there a source that explains how to use the C API (or just provides solid examples like yours?). Thank you very much.

**Comment by jcupitt** [comment]
There's a chapter in the docs, though it could be expanded:

https://libvips.github.io/libvips/API/current/using-from-c.html

**Comment by sethify** [comment]
> There's a chapter in the docs, though it could be expanded:
> 
> https://libvips.github.io/libvips/API/current/using-from-c.html

Thank you. The documentation is pretty good. Features like the `arrays` (showcased above) could use some examples to help people unleash libvips :)

**Comment by jcupitt** [comment]
You mean the `local_array` thing? That's documented here:

https://libvips.github.io/libvips/API/current/VipsObject.html#vips-object-local-array

But a note in the C intro page would be good, you're right.

**Comment by sergeevabc** [comment]
```console
$ vips.exe --version
vips-8.11.0-Thu Jun  3 10:57:25 UTC 2021

$ vips.exe copy in.png out.gif
VipsForeignSave: "out.gif" is not a known file format```

**Comment by jcupitt** [comment]
Hello @sergeevabc,

Could you open new issues, please? If issues are separated it makes it easier for other users to find answers.

I think you've probably downloaded the `-web` build. For security this is built without imagemagick support, so there is no `gifsave`. If you download the `-all` version it ought to work.

**Comment by sergeevabc** [comment]
@jcupitt, I used [vips-dev-w64-all-8.11.0.zip][1], the mentioned conversion does not work.

[1]: https://github.com/libvips/build-win64-mxe/releases/download/v8.11.0/vips-dev-w64-all-8.11.0.zip

**Comment by jcupitt** [comment]
It's working for me. I see:

```
User@WinDev2101Eval MINGW64 ~
$ unzip -qq Downloads/vips-dev-w64-all-8.11.0.zip

User@WinDev2101Eval MINGW64 ~
$ cd vips-dev-8.11/bin/

User@WinDev2101Eval MINGW64 ~/vips-dev-8.11/bin
$ ./vips.exe copy ~/Pictures/before.png x.gif

User@WinDev2101Eval MINGW64 ~/vips-dev-8.11/bin
$ file x.gif
x.gif: GIF image data, version 89a, 2560 x 1440
```

Please open an issue on https://github.com/libvips/build-win64-mxe if it's not working for you.
