### ISSUE TITLE
Problem working with multipage .svs files (jpeg2000 compressed)

### ISSUE THREAD

**Issue by JeremiasKrause** [libvips/libvips#1168]
Greetings,
my name is Jeremias and im (trying) to use libvips in combination with Openslide for image processing of .svs histology slides.
My aim is to convert a multipage .svs file with a jpeg2000 compression to bigtiff file with any other compression then jpeg2000.
By using the 'vips openslideload' i managed to create files, which i was able to open with the aperio imagescope software, but only 
if i was using a jpeg compression in combination with the bigtiff format. Thats fine. 
My problme is that those images contained only the 'base' from the previous .svs files and every other level of the prior multipage 
.svs file, as well as the thumbail and the label were lost. In Order to work properly with the images i need to (at least) keep the 
base, the thumbnail, label and one additional level to be able to show a preview of the Image.
Because of that i tried to manage to extract more then one layer with the 'openslideload' : vips openslideload [level=0:end] ..., but with this 
i ended up again, with images i was not able to open (using aperio imagescope):
- File F:\pyramid1.tiff open failed (100)
- cAIC:File F:\pyramid1.tiff(0) open failed, error=0
I also tried the commands tiffsave im_vips2tiff, but the results were not really different.
I was searching people with similar problems and this discussion (and the resulting post on the Libvips website) were the most promising things 
i was able to find:
https://github.com/libvips/ruby-vips/issues/112
https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html
Since im relatively new to working with linux and libvips, i wanted to ask if this is still the most viable option to work with multipage 
images (.tiff or .svs), since until now i have been working only with the libvips terminal tools (on a virtual machine with ubuntu) and i am 
a little bit unsure how to define a new property like 'imageheight' with the terminal tools.

Besides this conversation i found this one from 2013:
https://github.com/libvips/libvips/issues/72
And it is true that i am able to create a pyramidal tiff which i am able to open with aperio imagescope, i was not able to create a pyramidal 
tiff file with more then one level. Is there a way to solve this which this approach ?

Information about the multipage .svs file i want to convert:

jk98@jk98-VirtualBox:~/Desktop$ tiffinfo test2.svs
TIFF Directory at offset 0xaeb8202 (183206402)
  Subfile Type: (0 = 0x0)
  Image Width: 39680 Image Length: 50432 Image Depth: 1
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 8
  Compression Scheme: 33005 (0x80ed)
  Photometric Interpretation: RGB color
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library v10.2.41
39680x50432 (256x256) J2K/KDU Q=70;Mirax Digital Slide|AppMag = 20|MPP = 0.23250
TIFF Directory at offset 0xaf13294 (183579284)
  Subfile Type: (0 = 0x0)
  Image Width: 604 Image Length: 768 Image Depth: 1
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  YCbCr Subsampling: 2, 2
  Samples/Pixel: 3
  Rows/Strip: 16
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library v10.2.41
39680x50432 -> 604x768 - ;Mirax Digital Slide|AppMag = 20|MPP = 0.23250
  JPEG Tables: (289 bytes)
TIFF Directory at offset 0xba6ad6e (195472750)
  Subfile Type: (0 = 0x0)
  Image Width: 9920 Image Length: 12608 Image Depth: 1
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 8
  Compression Scheme: 33005 (0x80ed)
  Photometric Interpretation: RGB color
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library v10.2.41
39680x50432 (256x256) -> 9920x12608 J2K/KDU Q=70
TIFF Directory at offset 0xbb31d2c (196287788)
  Subfile Type: (0 = 0x0)
  Image Width: 2480 Image Length: 3152 Image Depth: 1
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 8
  Compression Scheme: 33005 (0x80ed)
  Photometric Interpretation: RGB color
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library v10.2.41
39680x50432 (256x256) -> 2480x3152 J2K/KDU Q=70
TIFF Directory at offset 0xbb6e09e (196534430)
  Subfile Type: (0 = 0x0)
  Image Width: 1240 Image Length: 1576 Image Depth: 1
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 8
  Compression Scheme: 33005 (0x80ed)
  Photometric Interpretation: RGB color
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library v10.2.41
39680x50432 (256x256) -> 1240x1576 J2K/KDU Q=70

I would appreciate any ideas, that could help me to save this problem.
Thank you for your time and patience.
With regards
Jeremias

**Comment by jcupitt** [comment]
Hello Jeremias,

libvips can only read openslide images, it can't write them (the openslide library does not support write), so you won't be able to make an image which looks like a slide image.

Your best bet is pyramidal tiff, as you said. What do you mean "i was not able to create a pyramidal tiff file with more then one level"? It should work, for example:

```
$ vips tiffsave CMU-1-Small-Region.svs x.tif --tile --pyramid --compression=jpeg
$ vipsheader -a x.tif 
x.tif: 2220x2967 uchar, 3 bands, srgb, tiffload
width: 2220
height: 2967
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: x.tif
vips-loader: tiffload
n-pages: 6
resolution-unit: cm
orientation: 1
```

So in this case it's made a six page tif, and each page will have one pyramid level in.

You'll need to find some other way to carry the label image over. Perhaps putting a separate tif file in the same directory, and indicating  that it contains the label by adding something to file filename.

The CLI is only useful for simple tasks. If you are trying to do anything fancy, I would use something like the Python binding:

https://pypi.org/project/pyvips/

**Comment by JeremiasKrause** [comment]
Thank you very much for the response.
I am sorry that i did not express me clearly enough. Of course you are right with 
the statement that you can create files with more than one bands, my problem is that 
i am not able to extract more than one layer from the .svs file and to move the extracted
layers in order into the new file.  
The advice to use the python binding is really great. I will try to reproduce the solution 
you posted in the earlier dicussions.
Again thank you for the fast and detailed response. 
With regards 
Jeremias

**Comment by jcupitt** [comment]
Ah OK ... yes, you'll need to put the label in a different file.

The Ruby binding works well on Windows too, if that's easier for you.

**Comment by JeremiasKrause** [comment]
Hello again,
I hope that it is ok to use this post again and not to create a new one. The issue is linked to this problem so i thought that it is appropriate to do so.
I tried this time to create a pyramidal tiff with the tiffsave command. At first i tried to convert the first layer from a .svs image into a multipage tiff (by using tiffsave). Since this did not work i tried to convert the .svs image into a .tiff and after that to convert the .tiff file into a pyramid one. 
Both times i ended up with an image that had the following information : 
vipsheader -a test3.tiff 
test3.tiff: 108394x76610 uchar, 3 bands, srgb, tiffload
width: 108394
height: 76610
bands: 3
format: 0 - uchar
coding: 0 - none
interpretation: 22 - srgb
xoffset: 0
yoffset: 0
xres: 1,000000
yres: 1,000000
filename: "test3.tiff"
vips-loader: tiffload
resolution-unit: cm
orientation: 1

As you can see, there is no 'n-pages' property. I was not able to open this created image with aperio imagescope. I would like to know wether you might have an idea what the problem could be. 
Both times i used something like : 
vips tiffsave y.svs x.tiff --tile --pyramid --compression=jpeg 

Those are the information gathered form the .svs file by using 'vipsheader -a' 
vipsheader -a test2.svs 
test2.svs: 108394x76610 uchar, 4 bands, rgb, openslideload
width: 108394
height: 76610
bands: 4
format: 0 - uchar
coding: 0 - none
interpretation: 17 - rgb
xoffset: 0
yoffset: 0
xres: 1,000000
yres: 1,000000
filename: "test2.svs"
vips-loader: openslideload
slide-level: 0
aperio.AppMag: 40
aperio.DSR ID: aperio01
aperio.Date: 05/15/12
aperio.DisplayColor: 0
aperio.Exposure Scale: 0.000001
aperio.Exposure Time: 109
aperio.Filename: 28145
aperio.Focus Offset: 0.000000
aperio.ICC Profile: ScanScope v1
aperio.ImageID: 28145
aperio.Left: 22.562445
aperio.LineAreaXOffset: 0.000000
aperio.LineAreaYOffset: 0.000000
aperio.LineCameraSkew: -0.000389
aperio.MPP: 0.2520
aperio.OriginalHeight: 76710
aperio.OriginalWidth: 113000
aperio.Parmset: EPC
aperio.ScanScope ID: SS1302
aperio.StripeWidth: 1000
aperio.Time: 16:33:32
aperio.Time Zone: GMT-07:00
aperio.Top: 21.282814
aperio.User: 91ca8f0c-b126-4ce2-98f5-c8361ddec3a2
openslide.comment: Aperio Image Library vFS90 01\r\n113000x76710 [0,100 108394x76610] (256x256) J2K/YUV16 Q=70|AppMag = 40|StripeWidth = 1000|ScanScope ID = SS1302|Filename = 28145|Date = 05/15/12|Time = 16:33:32|Time Zone = GMT-07:00|User = 91ca8f0c-b126-4ce2-98f5-c8361ddec3a2|Parmset = EPC|MPP = 0.2520|Left = 22.562445|Top = 21.282814|LineCameraSkew = -0.000389|LineAreaXOffset = 0.000000|LineAreaYOffset = 0.000000|Focus Offset = 0.000000|DSR ID = aperio01|ImageID = 28145|Exposure Time = 109|Exposure Scale = 0.000001|DisplayColor = 0|OriginalWidth = 113000|OriginalHeight = 76710|ICC Profile = ScanScope v1
openslide.level-count: 4
openslide.level[0].downsample: 1
openslide.level[0].height: 76610
openslide.level[0].tile-height: 256
openslide.level[0].tile-width: 256
openslide.level[0].width: 108394
openslide.level[1].downsample: 4.0000891169604831
openslide.level[1].height: 19152
openslide.level[1].tile-height: 256
openslide.level[1].tile-width: 256
openslide.level[1].width: 27098
openslide.level[2].downsample: 16.000946971799145
openslide.level[2].height: 4788
openslide.level[2].tile-height: 256
openslide.level[2].tile-width: 256
openslide.level[2].width: 6774
openslide.level[3].downsample: 32.00189394359829
openslide.level[3].height: 2394
openslide.level[3].tile-height: 256
openslide.level[3].tile-width: 256
openslide.level[3].width: 3387
openslide.mpp-x: 0.252
openslide.mpp-y: 0.252
openslide.objective-power: 40
openslide.quickhash-1: 19fe856ffa35cee36263ffee935c97d826008cf56455bcc0a93c7fdd0771f79a
openslide.vendor: aperio
tiff.ImageDescription: Aperio Image Library vFS90 01\r\n113000x76710 [0,100 108394x76610] (256x256) J2K/YUV16 Q=70|AppMag = 40|StripeWidth = 1000|ScanScope ID = SS1302|Filename = 28145|Date = 05/15/12|Time = 16:33:32|Time Zone = GMT-07:00|User = 91ca8f0c-b126-4ce2-98f5-c8361ddec3a2|Parmset = EPC|MPP = 0.2520|Left = 22.562445|Top = 21.282814|LineCameraSkew = -0.000389|LineAreaXOffset = 0.000000|LineAreaYOffset = 0.000000|Focus Offset = 0.000000|DSR ID = aperio01|ImageID = 28145|Exposure Time = 109|Exposure Scale = 0.000001|DisplayColor = 0|OriginalWidth = 113000|OriginalHeight = 76710|ICC Profile = ScanScope v1
tiff.ResolutionUnit: inch
slide-associated-images: label, macro, thumbnail

Thank you for your support.
With regards,
Jeremias

**Comment by jcupitt** [comment]
Hi again,

I think it's working, you are just using an older libvips that does not support the `n-pages` property. Try this:

```
$ vips tiffsave CMU-1-Small-Region.svs x.tif --tile --pyramid --compression=jpeg
$ vipsheader x.tif 
x.tif: 2220x2967 uchar, 3 bands, srgb, tiffload
```

By default, you just get page 0, the full resolution image. You can select other pages with the `page` parameter:

```
$ vipsheader x.tif[page=1]
x.tif: 1110x1483 uchar, 3 bands, srgb, tiffload
$ vipsheader x.tif[page=2]
x.tif: 555x741 uchar, 3 bands, srgb, tiffload
$ vipsheader x.tif[page=3]
x.tif: 277x370 uchar, 3 bands, srgb, tiffload
$ vipsheader x.tif[page=4]
x.tif: 138x185 uchar, 3 bands, srgb, tiffload
$ vipsheader x.tif[page=5]
x.tif: 69x92 uchar, 3 bands, srgb, tiffload
```

I don't know what formats aperio imagescope supports. Do they have any documentation?

**Comment by JeremiasKrause** [comment]
Thank you for the fast reply !
You were totally correct, it was necessary to update libvips. After the update i was able to create images with the 'n-pages' property, i can also open them now with aperio imagescope. As far as i know aperio imagescope should be able to open multipage tiff files. I think my problem was created by the missing property, since it is working now. 
Now that the image has multiple pages, i think that i confused some terms. vipsheader -a tells me that the file has 11 pages, while aperio imagescope still only sees the base of the image. I was expecting that it would show multiple layers . I added two pictures, one shows how it looks like now and the other how it should look like. Is there any way to use some of the additional pages as recognisable layers (recognisable for aperio) , or is this idea buried by the fact that openslide has no writing support, since the layers from the .svs file are recognised as 'openslide-layers' ?
Again thank you very much for your help ! 
With regards,
Jeremias 

![image1](https://user-images.githubusercontent.com/42405074/49671029-da3f7480-fa66-11e8-805d-32414cc3e4f0.PNG)
![image2](https://user-images.githubusercontent.com/42405074/49671035-df042880-fa66-11e8-9588-c2a681af64cf.PNG)

**Comment by jcupitt** [comment]
I think that might be as good as you'll get. You'd need to contact Aperio about format support.

**Comment by JeremiasKrause** [comment]
Thank you very much :)
