### ISSUE TITLE
libvips doesn't see installed libraries

### ISSUE THREAD

**Issue by a-ta-ta** [libvips/libvips#1169]
I'm on CentOS 7 (RHEL) and trying to install vips for further usage with ruby client.
```
 I have problems with configuring the Makefile:
./configure --prefix=/Users/john/vips \
    --with-giflib-includes=/opt/local/include \
    --with-giflib-libraries=/opt/local/lib \
    --with-tiff-includes=/opt/local/include \
    --with-tiff-libraries=/opt/local/lib \
    --with-jpeg-includes=/opt/local/include \
    --with-jpeg-libraries=/opt/local/lib
```

Output (not formatted as code for highlighting some lines):
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes

[Omitted some lines for the sake of readability]

checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.14 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking for XML_ParserCreate in -lexpat... yes
checking expat.h usability... yes
checking expat.h presence... yes
checking for expat.h... yes
checking for GSF... no
configure: WARNING: libgsf-1 not found; disabling dzsave support
checking for GSF_ZIP64... no
checking for FFTW... no
configure: WARNING: fftw not found; disabling fftw support
checking for MAGICK_WAND... no
checking for IMAGE_MAGICK... no
configure: WARNING: neither MagickCore nor ImageMagick found; disabling Magick support
checking for ImportImagePixels... no
configure: WARNING: ImportImagePixels not found; disabling magicksave
checking for ORC... no
configure: WARNING: orc-0.4.11 or later not found; disabling orc support
checking for LCMS... no
configure: WARNING: lcms2 not found; disabling ICC profile support
checking for OPENEXR... no
configure: WARNING: OpenEXR not found; disabling OpenEXR support
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... no
checking for NIFTI... libraries (none), headers (none)
checking for PDFIUM... libraries (none), headers (none)
checking for POPPLER... no
configure: WARNING: poppler-glib >= 0.16.0 or cairo >= 1.2 not found; disabling PDF load via poppler
checking for RSVG... no
configure: WARNING: librsvg-2.0 >= 2.34.0 or cairo >= 1.2 not found; disabling SVG load via rsvg
checking for ZLIB... yes
checking for OPENSLIDE... no
configure: OpenSlide >= 3.4.0 not found; checking for >= 3.3.0
checking for OPENSLIDE... no
configure: WARNING: OpenSlide >= 3.3.0 not found; disabling virtual slide support
checking for MATIO... no
configure: WARNING: matio not found; disabling matio support
checking for CFITSIO... no
configure: WARNING: cfitsio not found; disabling cfitsio support
checking for LIBWEBP... no
checking for libwebp... libraries (none), headers (none)
configure: WARNING: libwebp not found; disabling WEBP support
checking for PANGOFT2... yes
**checking for TIFF... no
checking for TIFF... libraries -L/opt/local/lib -ltiff, headers -I/opt/local/include**
checking for giflib... libraries -L/opt/local/lib -lgif, headers -I/opt/local/include
checking for PNG... yes
checking for IMAGEQUANT... no
configure: WARNING: libimagequant not found; disabling 8bpp PNG support
**checking for JPEG... no
checking for JPEG... libraries -L/opt/local/lib -ljpeg, headers -I/opt/local/include**
checking for jpeg_c_bool_param_supported... no
**checking for EXIF... no
configure: WARNING: libexif >= 0.6 not found; disabling exif support**
checking that generated files are newer than configure... done
configure: creating ./config.status

[Omitted some lines for the sake of readability]

* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable vips7 C++ API: 			no (default)
enable vips7 Python binding:		no (default)
enable vips8 Python overrides:		no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			none
Magick API version: 			none
load with libMagick: 			no
save with libMagick: 			no
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	no
  (requires libwebp-0.1.3 or later)
support webp metadata:			
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2: 		yes
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
**file import/export with libtiff:	yes (found by search)
file import/export with giflib:		yes (found by search)
file import/export with libjpeg:	yes (found by search)**
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
**use libexif to load/save JPEG metadata: no**

I have two questions about this:
1) Does this input mean the installed libvips will be able to read and modify JPEG and TIFF files?
2) Is there any way to make it see for example the `libexif`?
Because it was surely installed with `yum install libexif` (no any sophisticated `make`). Proof:
`rpm -ql libexif`
Output:
```
/usr/lib64/libexif.so.12
/usr/lib64/libexif.so.12.3.3
/usr/share/doc/libexif-0.6.21
/usr/share/doc/libexif-0.6.21/COPYING
/usr/share/doc/libexif-0.6.21/NEWS
/usr/share/doc/libexif-0.6.21/README
```
and so on.

I can add any additional info by request. I really want make this work!

**Comment by lovell** [comment]
Hello, are the `-devel` packages installed e.g. `libtiff-devel`?

**Comment by a-ta-ta** [comment]
Hello! Thanks you very much for the answer and for fastness.
No, it was just libtiff. I've installed the devel version. Now it changed to `file import/export with libtiff:	yes (pkg-config libtiff-4)`.
Is it critical that it's 4th?

**Comment by lovell** [comment]
The "4" refers to the (major) version number provided by the CentOS 7 package manager.

**Comment by a-ta-ta** [comment]
I think that it is done. Thanks a lot!
