### ISSUE TITLE
gifload_buffer: Image is defective, decoding aborted on a certain image

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1170]
The gif here https://www.dropbox.com/s/hl53bokik7k4792/defect.gif?dl=0 produces a
`gifload_buffer: Image is defective, decoding aborted` error when for example doing

```
vips copy defect.gif[n=-1]  output.gif
```

When converting it with Imagemagick to another gif with 
```
convert defect.gif another.gif
```
that one works fine (also shows fine in a browser)

Not sure if a vips or giflib issue.

**Comment by jcupitt** [comment]
Hello @chregu, it seems to work for me:

```
$ vips copy defect.gif[n=-1] x.tif
```

libvips 8.7, giflib 5.1.4. What giflib version are you using?

**Comment by chregu** [comment]
Mmmh, both of my test systems use giflib 4.1.6. One on ubuntu trusty, the other on Amazon Linux. 

When I compile giflib 5.1.4, it actually works as well.

I assume, not your problem then and I'll try to upgrade. Feel free to close the ticket.

**Comment by jcupitt** [comment]
OK, glad there's a simple fix.
