### ISSUE TITLE
EPS to PNG loose apha channel

### ISSUE THREAD

**Issue by Lucuz91** [libvips/libvips#1171]
Hi, i have a problem with file EPS.
I try to convert a EPS file to a PNG, the conversion go well but i loose trasparency.
With vipsthumbail and with pyvips I was not able to maintain transparency, but with imagemagick I managed this way "convert -colorspace RGB TD201887034.eps TD201887034.png"

Is there a way to do it even with Vips?

The version of Vips is 8.7.1, the version of Imagemagick (for magickload) is 7.0.8-14 both compiled from the source.

The vips configure is:
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			yes
enable vips7 C++ API: 			no (default)
enable vips7 Python binding:		no (default)
enable vips8 Python overrides:		no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			MagickCore
Magick API version: 			magick7
load with libMagick: 			yes
save with libMagick: 			yes
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		yes (lcms2)
file import with niftiio: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		yes
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		yes
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	yes
  (requires libwebp-0.1.3 or later)
support webp metadata:			yes
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2: 		yes
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with giflib:		no
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			yes
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no

I loaded a zip file with the pes file and the profile used to convert it

Thanks,
Luca

[test.zip](https://github.com/libvips/libvips/files/2615139/test.zip)

**Comment by jcupitt** [comment]
Sorry, libvips imports EPS via imagemagick, and I don't think this information is being made available. With your image, I see:

```
image->depth = 16
GetImageType() = 8
	ColorSeparationType
GetPixelChannels() = 4
image->columns = 210
image->rows = 124
image has 1 pages
will read 1 frames
vips_magick7_print_traits: channel traits:
	0) UpdatePixelTrait 
	1) UpdatePixelTrait 
	2) UpdatePixelTrait 
	3) UpdatePixelTrait 
vips_magick7_print_channel_names: channel names:
	0) UndefinedPixelChannel RedPixelChannel CyanPixelChannel GrayPixelChannel LPixelChannel LabelPixelChannel YPixelChannel 
	1) aPixelChannel GreenPixelChannel MagentaPixelChannel CbPixelChannel 
	2) bPixelChannel BluePixelChannel YellowPixelChannel CrPixelChannel 
	3) BlackPixelChannel 
```

There's no alpha, just a plain CMYK image.

**Comment by jcupitt** [comment]
I tried:

```
$ identify -verbose TD201887034.eps 
Image: TD201887034.eps
  Format: EPT (Encapsulated PostScript with TIFF preview)
  Class: DirectClass
  Geometry: 210x124+0+0
  Resolution: 72x72
  Print size: 2.91667x1.72222
  Units: Undefined
  Type: ColorSeparation
  Base type: ColorSeparation
  Endianess: Undefined
  Colorspace: CMYK
  Depth: 16/8-bit
  Channel depth:
    cyan: 1-bit
    magenta: 1-bit
    yellow: 1-bit
    black: 8-bit
...
  Transparent color: cmyk(0,0,0,0)
...
```

So I think all it's doing is setting (0, 0, 0, 0) to transparent, there's no alpha channel.

I can't see where this setting is coming from. I did add a thing to extract the XMP metadata, but there's no obvious transparency stuff in there.

Sorry, it's a mystery.

**Comment by jcupitt** [comment]
I'll close. Please reopen if anyone discovers where the `cmyk(0,0,0,0)` comes from.

**Comment by ZanonEdoardo** [comment]
Hi, I have the same problem in some files. When the illustrator files were thought for printing, the transparent channel can be specified as a color in Illustrator, for make it ignored by the printer.

Can this supported by libvips as apha channel?

**Comment by jcupitt** [comment]
Hello, please open a new issue with some sample files.
