### ISSUE TITLE
rendering multiline text with pango

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1172]
dose vips support rendering multiline text?

**Comment by jcupitt** [comment]
Yes, the docs explain:

**Comment by tczf1128** [comment]
thanks. And I want to insert \n according the pixel length of text.  for example, pixel length of "I am a text" is 200, I want insert \n at the 100 pixel position.

**Comment by jcupitt** [comment]
Just set the width to 100. Try experimenting, it's easy to test:

```
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> txt = pyvips.Image.text("hello there", width=100, dpi=300)
>>> txt.write_to_file("x.png")
```

![x](https://user-images.githubusercontent.com/580843/49156176-9cc74280-f314-11e8-880e-121f8de01c3c.png)

**Comment by tczf1128** [comment]
Hi! I find that the text wll be smaller when I set width and height, can vips not scale the text itself, and strip some text instead?

**Comment by sergeevabc** [comment]
> Yes, the docs explain…
> You can insert a \n to force a line break.

Does not work on my end as follows `$ vips.exe text test.png "Hello \n world"`

![test](https://user-images.githubusercontent.com/373718/124050060-44470d00-da09-11eb-9ad2-622110d564fa.png)

**Comment by jcupitt** [comment]
The `\n` in strings is a Python feature. You'll need to check your shell to find out how it embeds newlines.

On linux, for example, it's ^V^M (ctrl-V, then ctrl-M).
