### ISSUE TITLE
Autofitting text crops paragraphs

### ISSUE THREAD

**Issue by somebody32** [libvips/libvips#1174]
Hello,

I'm using vips to fit the text inside the fixed box, it works generally great except for a text with paragraphs.

Here is the repro script:

```ruby
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ultricies purus, sit amet hendrerit enim. Proin velit turpis, lacinia ac tortor sed, dictum tincidunt dolor. Fusce pulvinar nec sem at dictum. Nunc faucibus lectus ligula, et imperdiet nisl lacinia a. Vestibulum at egestas erat. Integer dignissim vitae dui ac faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sollicitudin volutpat tortor a vestibulum. Aenean nec posuere leo."
text += "\n\nAliquam a pellentesque risus, facilisis ullamcorper nunc. Ut a urna vel metus elementum mollis. Phasellus ultricies ipsum sit amet iaculis consequat. Donec ultricies lobortis velit sit amet mattis. Duis maximus fermentum neque sed viverra. Duis imperdiet ultrices erat eu sodales. In hac habitasse platea dictumst. Praesent porta mauris quis ipsum dignissim imperdiet eu non dui. Ut faucibus fermentum varius. Vivamus id venenatis purus, posuere hendrerit ipsum."
text += "\n\nTest Test"

text_mask = Vips::Image.text(text, width: 490, height: 725)
text_mask.write_to_file "debug.png"
```

And here is the result of it:
![debug](https://user-images.githubusercontent.com/25742/49340915-6e17d780-f646-11e8-97b5-b60af5043143.png)

As you can see, the final `Test Test` is cropped out.

It could be fixed by specifying `spacing: 1`, but any other value break it again.

Am I doing something wrong here? Thanks in advance!

**Comment by jcupitt** [comment]
Huh, that's weird. I'll have a look. Thanks for the report!

**Comment by jcupitt** [comment]
Looks like it might be a pango bug, but perhaps there's a workaround. I'll keep trying.

**Comment by somebody32** [comment]
@jcupitt Thanks! I've also managed to reproduce it with one line texts, so if you need more repro examples just let me know

**Comment by jcupitt** [comment]
Oh, interesting. Sure, a smaller example would be helpful.

**Comment by jcupitt** [comment]
Ah, found it, there was an error in the way DPI was being set. I'll add it to 8.7.2 as a fix.

**Comment by somebody32** [comment]
Great! Thanks a lot!

**Comment by jcupitt** [comment]
OK, I've pushed out 8.7.2 with this fix. Thank you very much for reporting this dumbness!

https://github.com/libvips/libvips/releases/tag/v8.7.2

**Comment by somebody32** [comment]
Just tried it, works great, thank you!
