### ISSUE TITLE
Calculate the change in dimension after tilt operation

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1177]
Hi John,

After croping a image leftcrop,topcrop  100,200  width = 1000 height=2000 and do rotation of 0.02 deg by keeping the rotating center at left middle x=0, y=0.5 and again embed at the same location 100,200.
though the image crop dimension do not change yet there  is a slight tilt in the X,Y-axis. Is there any formula to calculate this change in Y axis.So that I may need to embed at eg: 98, 198
There is a proprietary program which does same function but i cannot match it as I lack this formula.

**Comment by jcupitt** [comment]
Hello @vkkindia, it depends on the exact behaviour you want. The simplest thing would just be to centre the image after rotation, so it appears to rotate around the centre point.

You could also look at xoffset/yoffset in the result image and position relative to that. That would give you rotate about one corner.

**Comment by jcupitt** [comment]
I made you a demo:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])

# area to rotate
left = 100
top = 100
width = 100
height = 100
angle = 35

crop = image.crop(left, top, width, height)

# add an alpha for blending back with the source image
crop = crop.bandjoin(255)
crop = crop.rotate(angle)

# the rotated image will have changed size --- centre it over the patch it
# came from
new_left = left + width / 2 - crop.width / 2
new_top = top + height / 2 - crop.height / 2

image = image.composite2(crop, "over", x=new_left, y=new_top)

image.write_to_file(sys.argv[2])
```

With this image:

![apple](https://user-images.githubusercontent.com/580843/49595572-2e1b6200-f970-11e8-8a43-67170b88ec3f.jpg)

Running:

```
$ ./rotatesub.py ~/pics/apple.jpg x.jpg 
```

I see:

![x](https://user-images.githubusercontent.com/580843/49595620-47bca980-f970-11e8-9920-167d4624c266.jpg)

(you can see the rotated square in the top-left)

**Comment by vkkindia** [comment]
Thanks John,
But I am rotating the image with left middle as center.  So Iam using
Affine. With idx idy.


Earlier you have suggested this for overlay.

####

# scan the source image a second time ... now we will overlay the transformed
# tile
im = pyvips.Image.new_from_file(input_filename, access="sequential")

# ifthenelse will blend between the overlay and the original image
alpha = overlay[overlay.bands - 1]
pixels = overlay[0 : overlay.bands - 1]
im = alpha.ifthenelse(pixels, im, blend=True)

# and write back.
im.write_to_file(output_filename)

#####
Can I replace this second time read image with

image = image.composite2(crop, "over", x=new_left, y=new_top)

So that program will be faster.

**Comment by vkkindia** [comment]
Hi John,
Mine is similar to this site
https://en.m.wikipedia.org/wiki/Rotation_of_axes
How to get coordinates in term of X',y' so that I can embed at that points.

**Comment by jcupitt** [comment]
No, `composite` will be a little slower, probably. It might be quicker in the next version of libvips.

So you want to rotate about the centre of the left edge, is that right?

**Comment by vkkindia** [comment]
Yes in one option left centre and other option right centre

**Comment by jcupitt** [comment]
This rotates about the centre of the left edge, you'd need to adjust it a bit for the right edge.

```python
#!/usr/bin/python3
  
import sys
import math
import pyvips


def rotsub_centreleft(image, left, top, width, height, angle):
    """Rotate a rect about the centre of the left edge and paste back.
    """
    crop = image.crop(left, top, width, height)

    # add an alpha for blending back with the source image
    if crop.bands < 4:
        crop = crop.bandjoin(255)

    crop = crop.copy(xoffset=0, yoffset=0)
    crop = crop.rotate(angle)

    # xoffset / yoffset give the position of the origin in the rotated image
    xoffset = crop.xoffset
    yoffset = crop.yoffset

    # rotation will have moved a point on the left edge of the input by this 
    # much
    dx = (height / 2.0) * math.sin(2.0 * math.pi * angle / 360.0)
    dy = - (height / 2.0) * math.cos(2.0 * math.pi * angle / 360.0)

    image = image.composite2(crop, "over", 
                             x=(left - xoffset + dx), 
                             y=(top - yoffset + dy + height / 2.0))

    return image

for angle in range(0, 360, 10):
    image = pyvips.Image.new_from_file(sys.argv[1])
    image = rotsub_centreleft(image, 400, 400, 200, 100, angle)
    name = "%d.jpg" % angle
    print("writing %s ..." % name) 
    image.write_to_file("%d.jpg" % angle)
```

**Comment by vkkindia** [comment]
Thanks John this works as expected.
Are we doing this
dx = (height / 2.0)

because it is a left middle, in case if I want left top then how to change
this formula.
I was searching for several weeks for the formula and glad I got from you.
Pls give example for right middle too. Iam exhausted.

Thanks again.

**Comment by jcupitt** [comment]
Just get a pencil and work through the code with a few examples. It should be easy to see how to adjust it for right centre.
