### ISSUE TITLE
Autofitting emoji-only causes segfault

### ISSUE THREAD

**Issue by somebody32** [libvips/libvips#1178]
Hi,

this one-liner causes infinite loop:

```ruby
Vips::Image.text("😂👍👎🏾", width: 300, height: 100)
```
it starts filling output with `Pango-CRITICAL **: 13:27:02.056: pango_font_description_set_size: assertion 'size >= 0' failed` and eventually dies after a couple of minutes. 

Having the same line with any non-emoji symbol works great, ie:

```ruby
Vips::Image.text("a 😂👍👎🏾", width: 300, height: 100)
```

Maybe emoji-fonts behaving differently in terms of dpi/dimensions?

**Comment by jcupitt** [comment]
I think it's because your emoji font is not scaleable. Could you try the head of the 8.7 branch? I added a thing to break the fitting loop.

**Comment by somebody32** [comment]
Just tried, works perfectly!

**Comment by jcupitt** [comment]
OK, I'll close, thanks!

I'll wait a few days before pushing out 8.7.3 in case anything else comes up.
