### ISSUE TITLE
Q: command line, change color profile without resize

### ISSUE THREAD

**Issue by jrochkind** [libvips/libvips#1179]
If I'm doing a `vipsthumbnail` command, I can supply `--eprofile`, such as:

    vipsthumbnail input_something.jpg --size 100x100 --eprofile some/path/to/sRGB.icc -o output.jpg[Q=85,strip]

What if I have a jpg, and I want to change do an encode with sRGB... but I don't want to resize?

`vips copy` does not take an `--eprofile` arg.  Is there any other way to do this that I haven't found out?

I suppose if I knew the existing height/width of the image, I could use vipsthumbnail and just pass it the existing height/width as it's resize params... but that seems kind of weird.

**Comment by lovell** [comment]
Hello, to transform the colours in an image from its embedded profile to a new profile at the command line, use something like:
```
vips icc_transform input_something.jpg output.jpg[Q=85,strip] some/path/to/sRGB.icc --embedded
```
Use `vips icc_transform` on its own to list all the other available options.
