### ISSUE TITLE
Install via package managers on Linux?

### ISSUE THREAD

**Issue by andrefelipe** [libvips/libvips#1184]
(Newbie here sorry) I am having a hard time installing Vips from source on Amazon Linux. 

I could install 8.7.0 on Amazon Linux Ami 2, but could not install anymore the 8.7.2. And the problem is debugging or understanding the install details is beyond my knowledge.

Do you know if it is possible to have a install via the package managers, like:
"yum install libvips"

Thanks you very much!

—
Steps to install on Amazon Linux AMI 2:

// in sudo

yum install gtk-doc libxml2-devel libjpeg-turbo-devel libpng-devel libtiff-devel libexif-devel libgsf-devel ImageMagick-devel gobject-introspection-devel libwebp-devel libxml2-devel lcms2-devel curl expat-devel gcc gcc-c++

curl -OL https://github.com/libvips/libvips/releases/download/v8.7.0/vips-8.7.0.tar.gz
tar xf vips-8.7.0.tar.gz
cd vips-8.7.0
./configure --prefix=/usr/local LDFLAGS="-L/usr/lib -lz"
make
make install
ldconfig
vips --version

**Comment by kleisauke** [comment]
Amazon Linux 2 seems to be based on RHEL/CentOS 7[<sup>[1]</sup>](https://serverfault.com/a/906672/202694) so I assume you could use Remi's RPM repository, a third-party repository that includes an up-to-date version of libvips. @remicollet is temporarily providing it because libvips is not available in EPEL ([yet](https://bugzilla.redhat.com/1189137)).

```shell
# Install and enable the EPEL RPM package on Amazon Linux 2
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# Install the Remi repository configuration package
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm

# Install the yum-utils package (for the yum-config-manager command)
yum install yum-utils

# Command to enable the repository
yum-config-manager --enable remi

# Install libvips (+ development files and command-line tools)
yum install vips vips-devel vips-tools
```

Note that I have not test this on Amazon Linux 2, so I'm not sure if it will work.

**Comment by andrefelipe** [comment]
I can confirm it works! Just installed following your steps. Thank you very much!

**Comment by a14m** [comment]
@kleisauke thanks for the instructions, but I ran into some problem on `Amazon Linux AMI release 2018.03`

```
$sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

Loaded plugins: priorities, update-motd, upgrade-helper
epel-release-latest-7.noarch.rpm                                                                                    |  15 kB  00:00:00     
Examining /var/tmp/yum-root-akBPyQ/epel-release-latest-7.noarch.rpm: epel-release-7-11.noarch
Marking /var/tmp/yum-root-akBPyQ/epel-release-latest-7.noarch.rpm as an update to epel-release-6-8.9.amzn1.noarch
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:6-8.9.amzn1 will be updated
--> Processing Dependency: epel-release = 6 for package: remi-release-6.10-1.el6.remi.noarch
276 packages excluded due to repository priority protections
---> Package epel-release.noarch 0:7-11 will be an update
--> Finished Dependency Resolution
Error: Package: remi-release-6.10-1.el6.remi.noarch (installed)
           Requires: epel-release = 6
           Removing: epel-release-6-8.9.amzn1.noarch (installed)
               epel-release = 6-8.9.amzn1
           Updated By: epel-release-7-11.noarch (/epel-release-latest-7.noarch)
               epel-release = 7-11
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

any idea how to move forward? (cc @andrefelipe)

**Comment by jcupitt** [comment]
There's a simple dockerfile here that builds libvips 8.7.4 from source on amazon linux 2018.03:

https://github.com/jcupitt/docker-builds/tree/master/libvips-amazonlinux-2018.03

I realize that's not quite what you were asking for.

**Comment by a14m** [comment]
@jcupitt thanks for your help, yeah that's the current way of building libvips that I'm using, but it take around 10-12 minutes to build, so I'm looking into a faster approach of getting v8 for elastic beanstalk...
will investigate switching to Amazon Linux 2

**Comment by andrefelipe** [comment]
Please, if someone could help me.

I can not install libvips anymore on Amazon Linux 2 with the commands above.

I get this error:
```
Error: Package: vips-devel-8.8.0-1.el7.remi.x86_64 (remi)
           Requires: pkgconfig(libjpeg)
 You could try using --skip-broken to work around the problem
```

I confirmed Libjpeg is available:
`Package libjpeg-turbo-1.2.90-5.amzn2.0.3.x86_64 already installed and latest version`

And as far as I my knowledge goes, it is located on:
```
/lib64/libjpeg.so.62
/lib64/libjpeg.so.62.1.0
```

Couldn't go beyond that. And I tried to resort to manual installation but could not suffice all features I needed when running ./configure (I need Webp support and configure just couldn't find it).

If anyone could provide a way to install libvips 8.8.0 on Amazon Linux AMI 2, I would totally be grateful.

Thanks all!

**Comment by jcupitt** [comment]
The amazon libwebp is version 0.3.0, and libvips need 0.5 or later. You'll need to build that from source as well. I'll have a quick go at a dockerfile for you.

**Comment by andrefelipe** [comment]
Thanks for you commitment John!

Look forward to libvips gain more and more attention.

**Comment by kleisauke** [comment]
@andrefelipe Could you try to run `yum install "pkgconfig(libjpeg)"`, and see if that works?

@remicollet It looks like the the change within [`8.7.0-3`](https://git.remirepo.net/cgit/rpms/lib/vips.git/tree/vips.spec?id=290aaac3a459554ffbcfe474fe19055c40ff4a83#n253) that prefers pkg-config for locating required libraries (`requires libjpeg-turbo-devel`  -> `requires pkgconfig(libjpeg)`) breaks on Amazon Linux 2.
Perhaps it should be made conditional (`%if 0%{?fedora} || 0%{?rhel} >= 7`), just like the [ImageMagick6 spec file](https://git.remirepo.net/cgit/rpms/ImageMagick6.git/tree/ImageMagick6.spec#n94)?

**Comment by andrefelipe** [comment]
Thanks @kleisauke , I tried, it returns:
`No package pkgconfig(libjpeg) available.`

**Comment by jcupitt** [comment]
This builds the latest libwebp and libvips from source on amazonlinux:2

https://github.com/jcupitt/docker-builds/tree/master/libvips-amazonlinux2

But of course it would be better to use Remi's binary package if you can.

**Comment by andrefelipe** [comment]
Thanks @jcupitt I will try the manual installation. 

Will leave this issue open for the moment. But if you see it's better, you can close it.

Thanks again for the attention!

**Comment by remicollet** [comment]
>  Package libjpeg-turbo-1.2.90-5.amzn2.0.3.x86_64 already installed and latest version

This is the runtime package, not the "devel" one, you need libjpeg-turbo-devel.

But do you really need the "devel" stack ?

@kleisauke this dependency is auto-generated by RPM (from libvips.pc content ?)

@jcupitt FYI, you now have 2 set of packages in my repository, "vips" and "vips-full", with heic support (but with dependency on rpmfusion repository), see https://blog.remirepo.net/post/2019/05/22/HEIC-HEIF-images-support

**Comment by remicollet** [comment]
BTW, it really seems amzn packages are broken

On RHEL-7
```
$ rpm -q --provides libjpeg-turbo-devel
libjpeg-devel = 6b-47.el7
libjpeg-devel(x86-64) = 6b-47.el7
libjpeg-turbo-devel = 1.2.90-6.el7
libjpeg-turbo-devel(x86-64) = 1.2.90-6.el7
pkgconfig(libjpeg) = 1.2.90
```

On amazonlinux
```
$ rpm -q --provides libjpeg-turbo-devel
libjpeg-devel = 6b-47.amzn2
libjpeg-devel(x86-64) = 6b-47.amzn2
libjpeg-turbo-devel = 1.2.90-5.amzn2.0.3
libjpeg-turbo-devel(x86-64) = 1.2.90-5.amzn2.0.3

```

**Comment by kleisauke** [comment]
I tried this Dockerfile and it seems to work for me:
<details>
   <summary>Dockerfile</summary>

```Dockerfile
FROM amazonlinux:2

# Import archive signing keys and update packages
RUN rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 && \
    rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi && \
    rpm --import https://sourceforge.net/projects/libjpeg-turbo/files/LJT-GPG-KEY && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 && \
    yum update -y

# Install the latest version of libjpeg-turbo,
# since the version on Amazon Linux 2 is too old (v1.2.90)
RUN yum install -y yum-utils && \
    yum-config-manager --add-repo https://libjpeg-turbo.org/pmwiki/uploads/Downloads/libjpeg-turbo.repo && \
    yum install -y libjpeg-turbo-official && \
    echo '/opt/libjpeg-turbo/lib64' >> /etc/ld.so.conf.d/libjpeg-turbo-official-x86_64.conf && \
    ldconfig

# Update the PKG_CONFIG_PATH environment variable,
# since libjpeg-turbo is installed in a non-standard prefix
ENV PKG_CONFIG_PATH=/opt/libjpeg-turbo/lib64/pkgconfig:$PKG_CONFIG_PATH

# Install libvips (full-fat version)
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi && \
    yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 && \
    yum install -y --setopt=tsflags=nodocs \
        vips-full \
        vips-full-tools && \
    yum clean all

ENTRYPOINT ["/usr/bin/vips"]
CMD ["--version"]
```
</details>

@andrefelipe You could try to install the latest version of `libjpeg-turbo` from the "official" YUM repository:
```bash
yum install yum-utils
yum-config-manager --add-repo https://libjpeg-turbo.org/pmwiki/uploads/Downloads/libjpeg-turbo.repo
yum install libjpeg-turbo-official
echo '/opt/libjpeg-turbo/lib64' >> /etc/ld.so.conf.d/libjpeg-turbo-official-x86_64.conf
ldconfig
export PKG_CONFIG_PATH=/opt/libjpeg-turbo/lib64/pkgconfig:$PKG_CONFIG_PATH
```

After that, you should be able to install libvips from Remi's RPM repository without any problems.

**Comment by andrefelipe** [comment]
Thanks all for the help!

I have successfully installed vips-8.8.0, the vips-full one, with the commands on the Dockerfile above.

I did some tests and narrowed it down that my problem was installing the **vips-devel** package. It still complains about "Requires: pkgconfig(libjpeg)" even using the vips-full-devel and latest libjpeg-turbo. 

Well, I guess I can safely ignore that, as I don't need the "devel" packages.

My new problem now is to install the php Vips PECL, it doesn't find the vips install, here is the error:
```
configure: error: you need at least libvips 8.2 for this module
ERROR: `/var/tmp/vips/configure --with-php-config=/usr/bin/php-config --with-vips' failed
```
Guess I have to wait for the PHP extention to be updated.

Here is the exact steps to reproduce the error:

```
// create a new Amazon Linux 2 instance
sudo -i

// run all commands at the docker file above, to successfully install vips
vips --version
vips-8.8.0-Sat May 11 11:55:18 UTC 2019

// install PHP and PECL
amazon-linux-extras install -y php7.3
yum install -y php-pear php-devel gcc
pecl channel-update pecl.php.net

// try to install the Vips PECL
pecl install vips
```

Will close the issue now, as it seems it is unrelated to the main question. Vips is installing correctly. 

Thanks everybody for the help and attention! I appreciate.

**Comment by jcupitt** [comment]
You'll need the libvips headers to be able to build the pecl add-on, and I'd expect them to be in devel.

The PHP extension shouldn't need updating, I hope.

**Comment by andrefelipe** [comment]
Thanks @jcupitt for the attention. And thanks for your hard work.

**Comment by remicollet** [comment]
> pecl channel-update pecl.php.net

Use **php-pecl-vips** from remi-php73 repository ;)

**Comment by remicollet** [comment]
So, without any build, only package

```
FROM amazonlinux:2

RUN yum update -y

# Import archive signing keys and update packages
RUN rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 && \
    rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 && \
    yum update -y

RUN yum install -y yum-utils

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php73 && \
    yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 && \
    yum install -y --setopt=tsflags=nodocs --noplugins \
        vips-full-tools php-cli php-pecl-vips && \
    yum clean all

RUN vips --version && php --modules && php --version

```


Output: 
```
Step 6/6 : RUN vips --version && php --modules && php --version
 ---> Running in c666a299ff73
vips-8.8.0-Sat May 11 11:55:18 UTC 2019
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
Phar
readline
Reflection
session
sockets
SPL
standard
tokenizer
vips
zlib

[Zend Modules]

PHP 7.3.6 (cli) (built: May 28 2019 09:32:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by andrefelipe** [comment]
Thank you very much @remicollet

**Comment by jcupitt** [comment]
Nice @remicollet !

**Comment by andrefelipe** [comment]
Hello @remicollet me reopening this issue again. 

When installing on a brand new Amazon Linux AMI 2 with the commands you sent, it breaks at:

```
Error: Package: ImageMagick6-libs-6.9.11.1-1.el7.remi.x86_64 (remi)
           Requires: libraw_r.so.19()(64bit)
```

Do you have any ideas on how to solve? (I tried a lot already)

Here is your install code:

```
FROM amazonlinux:2

RUN yum update -y

# Import archive signing keys and update packages
RUN rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 && \
    rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 && \
    yum update -y

RUN yum install -y yum-utils

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php73 && \
    yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 && \
    yum install -y --setopt=tsflags=nodocs --noplugins \
        vips-full-tools php-cli php-pecl-vips && \
    yum clean all

RUN vips --version && php --modules && php --version
```

Thanks in advance

**Comment by remicollet** [comment]
> Hello @remicollet me reopening this issue again.

Not the right place for repository support.

**Comment by remicollet** [comment]
My package are built against official RHEL 7.7 released in Aug 2019.

So amazon's image is far behind....

So I have (re)add LibRaw 0.19.2 from RHEL in my repository, this solves this issue.
(version is 0.19.2-0 to ensure RHEL and CentOS will use 0.19.2-1 from official repo)

**Comment by andrefelipe** [comment]
Thank you very much @remicollet !

Will follow your guidance.

Have a nice week.

**Comment by istvanp** [comment]
I had the same issue with the `LibRaw` dependency. I fixed it by prioritizing the `remi` repo with:

```bash
yum-config-manager --setopt=remi.priority=1 --save
```

Turns out `amzn2-core` repo has the wrong version and won't let you install because of it.

> Hello @remicollet me reopening this issue again.
> 
> When installing on a brand new Amazon Linux AMI 2 with the commands you sent, it breaks at:
> 
> ```
> Error: Package: ImageMagick6-libs-6.9.11.1-1.el7.remi.x86_64 (remi-safe)
>            Requires: libraw_r.so.19()(64bit)
> ```
> 
> Do you have any ideas on how to solve? (I tried a lot already)
> 
> Here is your install code:
> 
> ```
> FROM amazonlinux:2
> 
> RUN yum update -y
> 
> # Import archive signing keys and update packages
> RUN rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 && \
>     rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi && \
>     rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 && \
>     yum update -y
> 
> RUN yum install -y yum-utils
> 
> RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
>     yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
>     yum-config-manager --enable remi-php73 && \
>     yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
>     rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 && \
>     yum install -y --setopt=tsflags=nodocs --noplugins \
>         vips-full-tools php-cli php-pecl-vips && \
>     yum clean all
> 
> RUN vips --version && php --modules && php --version
> ```
> 
> Thanks in advance

**Comment by jmschp** [comment]
Following @kleisauke instructions (thank you!), I created two [.ebextensions configuration files](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands), so it will install **libvips** in AWS Elastic Beanstalk Amazon Linux 2

.ebextensions/01_yum.config
```yml
commands:
  01_install_epel_rpm_package:
    command: yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  02_install_remi_repository_config_package:
    command: yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  03_install_yum_utils_package:
    command: yum -y install yum-utils
  04_command_enable_repository:
    command: yum-config-manager -y --enable remi
```

.ebextensions/02_yum_libvips.config

```yml
packages:
  yum:
    vips: []
    vips-devel: []
    vips-tools: []

```

**Comment by anthonydito** [comment]
Thanks for adding those .config examples @jmschp - those worked for me in my elastic beanstalk environment.
