### ISSUE TITLE
Add CMYK to * colorspace conversion

### ISSUE THREAD

**Issue by dbouron** [libvips/libvips#1186]
Hi,

Do you think that adding CMYK to * colorspace conversion may be revelant?
I saw some code in gimp project for handling CMYK to RGB conversion:
https://github.com/GNOME/gimp/blob/f8ce6b7440079f68b741c799527b3122383be3d6/libgimpcolor/gimpcolorspace.c#L372
Then, we just can route conversions for other colorspace
I think it could be better to handle it natively in libvips instead of dealing with icc profile.

**Comment by jcupitt** [comment]
Hello @dbouron, that cmyk->rgb conversion is just a quick hack, it won't work well. To do the job properly, you need to use a library like lcms2. libvips's lcms2 dependancy is optional, so it can't always do cmyk<->rgb conversions. 

You're right that if it has been built with lcms2, it could add some extra conversions, perhaps even with a default fallback cmyk profile. 

Let's tag this as an enhacement.

**Comment by jcupitt** [comment]
nip2 has nice cmyk, srgb and a98 profiles:

https://github.com/libvips/nip2/tree/master/share/nip2/data

So I'd be inclined to just copy those into libvips somewhere, though I'm not sure where. They should probably be bound to the library somehow (as base64 strings?) to avoid filesystem problems.

You can just use `vips_icc_transform` to do the actual processing.

**Comment by dbouron** [comment]
Hi @jcupitt, I used your default profiles to convert CMYK (left) to sRGB (right) image.
Well, colors seem to walk off...

About vips_icc_transform, in this case we don't need output_profile argument because we will load in/out profile from memory.
Do you prefer to add profile memory pointer as optional arguments or create a new method vips_icc_transform1?

![result](https://user-images.githubusercontent.com/21236440/50484265-d6f93200-09ef-11e9-8117-1088ea504f90.jpg)

**Comment by jcupitt** [comment]
Hello again,

It depends how you made the RGB for the image on the left. libvips is relative D65 by default, you probably used different settings, or perhaps a different CMS.

To set a profile from memory, attach to the image with `vips_image_set_blob()`, then convert.

**Comment by dbouron** [comment]
I took icm profiles from https://github.com/libvips/nip2/tree/master/share/nip2/data
My input profile was cmyk.icm and sRGB.icm for the output one.
Then, I loaded them with cmsOpenProfileFromMem from liblcms2.

**Comment by jcupitt** [comment]
Yes, but how did you get the RGB  for the left image? It was probably with different settings.

I've made a quick CMYK <-> XYZ convert, and added a set of routes. I'll polish it a bit more.

**Comment by jcupitt** [comment]
IM defaults to perceptual intent, I think. Try

```
vips icc_transform in.jpg out.jpg srgb.icm --intent perceptual
```

**Comment by jcupitt** [comment]
Perceptual intent means "I don't care about accuracy, just make it pretty!" Whether it's appropriate depends on your application, of course.

**Comment by jcupitt** [comment]
If I try:

```
convert flowers.jpg -profile ~/vips/share/nip2/data/cmyk.icm -profile ~/vips/share/nip2/data/sRGB.icm x.jpg 
```

I get the same result from imagemagick and libvips. 

You can try the ghostscript profiles:

```
convert flowers.jpg -profile /usr/share/color/icc/ghostscript/default_cmyk.icc -profile ~/vips/share/nip2/data/sRGB.icm z.jpg
```

But the black point is higher.

If you do:

```
convert flowers.jpg -colorspace rgb x.jpg
```

which I guess is the command you were running, you will not get the correct result. Imagemagick will use a very cheap and inaccurate conversion.

**Comment by jcupitt** [comment]
> Imagemagick will use a very cheap and inaccurate conversion.

At least, that's what it used to do! I should check what it does now. Anyway, the washed-out version is the correct one, the oversaturated one on the left is wrong.

**Comment by lovell** [comment]
Could the new built-in CMYK profile be made available when calling `vips_icc_import` and `vips_icc_export`, something similar to the way they currently offer `input_profile` and `output_profile` respectively?

**Comment by dbouron** [comment]
The oversaturated image on the left is the original one. I test with your branch, it seems to work fine, better than cmyk -> srgb with profile.
I try to add imagemagick default conversion (cmyk <-> srgb) without any profile and it produce the same result on this example.
Maybe it could be interesting to add both implementations? IM one doesn't need lcms2 and no embedded profile needed

**Comment by jcupitt** [comment]
@lovell that's a good idea. Perhaps setting the string `cmyk` as a filename could select the built-in cmyk profile?

**Comment by jcupitt** [comment]
With no profile specified, my guess is IM is doing something like:

```
r = 1.0 - (c * (1.0 - k) + k)
g = 1.0 - (m * (1.0 - k) + k)
b = 1.0 - (y * (1.0 - k) + k)
```

So it's a very approximate conversion, enough that you can recognize the image, but not much like what you'd get from a printer. 

An ICC printer profile is a pair of huge 3D lookup tables. You print out a big test chart with every combination of CMYK in 10% steps and measure each patch with a colorimeter. That gives you a mapping from ink density to surface colour. You then invert that mapping to get a conversion from desired surface colour to ink density, and store both the forward and reverse tables in a CMYK profile. At run time, lcms takes each CMYK point and does teterahedral interpolation with the forward mapping to recover the original colour.

If we have a mode with a real profile and a proper conversion, it should give much better results than the approximation that IM is using.

**Comment by jcupitt** [comment]
@dbouron oh sorry, I've just read your commit, and that's exactly what you've implemented!

We could use your code if lcms is not available, or do you think it should be a separate path?

**Comment by dbouron** [comment]
Yes IM is doing that. I agree, we can use this path if no lcms2 has been detected.
I guess the decision may be:

* Get embedded profile if exists and if HAVE_LCMS2
* Use generic profile if HAVE_LCMS2
* Use basic conversion otherwise

**Comment by jcupitt** [comment]
OK, sounds reasonable to me. Let's get this branch merged to master, then add Lovell's and your ideas on top of that in fresh issues or PRs.

**Comment by jcupitt** [comment]
OK, merged to master, plus two new issues for the follow-up features. I'll close!

**Comment by sonyarianto** [comment]
> IM defaults to perceptual intent, I think. Try
> 
> ```
> vips icc_transform in.jpg out.jpg srgb.icm --intent perceptual
> ```

I tried this but error `icc_transform: no input profile`

**Comment by jcupitt** [comment]
Hello @sonyarianto, I guess your input JPG did not have an embedded profile. You need to specify one, eg.

```
$ vips icc_transform cmyk.jpg rgb.jpg sRGB.icm --intent perceptual --input-profile cmyk.icm
```
