### ISSUE TITLE
VIPS_ARG_POINTER does not use CLASS in g_object_class_install_property

### ISSUE THREAD

**Issue by Fingolfin1196** [libvips/libvips#1187]
In the file `libvips/include/vips/object.h`, the definintion of the macro `VIPS_ARG_POINTER` includes calling `g_object_class_install_property`, which uses `G_OBJECT_CLASS( CLASS )` as the first argument in all other `VIPS_ARG_*` macros but `gobject_class` in `VIPS_ARG_POINTER`, which does not seem correct and leads to compiler errors, which are resolved after replacing it with `G_OBJECT_CLASS( CLASS )`.

**Comment by jcupitt** [comment]
Oh yes, you're right. Looks like a copy-paste error. I wonder why this was never spotted?

Thank you very much for reporting this!
