### ISSUE TITLE
VIPS dzave with Roche/Ventana BIF format

### ISSUE THREAD

**Issue by databaseddoctor** [libvips/libvips#1189]
Hi, I have been trying to generate image pyramids using VIPS and so far it works perfectly with SVS digital slide files.  However when I try to do:

vips dzsave slide_name.bif x

I get an error message that says:

openslide2vips: opening slide: Bad direction attribute "LEFT"

I thought VIPS uses openslide which supports bif format.  What's going here?  Am I missing something?

**Comment by jcupitt** [comment]
Sorry, I've not come across .bif format. Do you have a link to a sample file?

You could try the official `openslide-write-png` program to convert your slide to a PNG. If that fails, then the problem is probably in openslide rather than vips.

**Comment by databaseddoctor** [comment]
Interesting.  I will try to create a link to the sample file after proper patient de-identification.  In the meantime I will try openslide-write-png and see if that works.

**Comment by jcupitt** [comment]
I found a sample on the openslide site:

http://openslide.cs.cmu.edu/download/openslide-testdata/Ventana/

I'll test one of those here.

**Comment by jcupitt** [comment]
The `OS-2.bif` sample worked well for me:

```
$ time vips dzsave OS-2.bif x

real	19m46.766s
user	41m35.860s
sys	2m39.823s
```

openslide hasn't been updated since 2015. Perhaps `.bif` has gained some features since then and openslide doesn't know about them?

**Comment by databaseddoctor** [comment]
If there has been changes to the bif format that would be very unfortunate.
here is a link to my "problem" bif file

https://umich.box.com/s/3k87u6kq81wxvuelpudm5x83ecqe9i4e

let me also try few others.  Its always possible it corrupted.

**Comment by jcupitt** [comment]
Yes, fails for me too with `openslide-write-png`:

```
$ openslide-write-png UMFZ-_175_06142018091319AM.bif 0 0 1 100 100 x.png
openslide-write-png: UMFZ-_175_06142018091319AM.bif: Bad direction attribute "LEFT"
```

@bgilbert, do you know if `.bif` has changed recently?

**Comment by databaseddoctor** [comment]
um...that's interesting.  I will have to look at the settings on the Roche slide scanner.  Avoid whatever that says left.  BTW I tried OS-2.bif and it worked perfectly

**Comment by databaseddoctor** [comment]
Just talked to Roche and personally verified; BIF is no longer compatible with openslide.  Moving forward the slides will have to be scanned into TIF in order to take advantage of the library using Roche instrument.

**Comment by jcupitt** [comment]
There's a PR on openslide which might fix this issue:

https://github.com/openslide/openslide/pull/246

Would you be able to test it with your image?

**Comment by databaseddoctor** [comment]
Sure, I can give it a try.  My images are also from the newer DP200 instrument.  Chances are it will fix it if ChrisSmith96 was able to do it.   Also Roche actually came to our institution to partially address this problem.  They were not able to give me a clear answer.  Its up to the users/developers to fix the problem I guess.

**Comment by ajay1685** [comment]
> There's a PR on openslide which might fix this issue:
> 
> [openslide/openslide#246](https://github.com/openslide/openslide/pull/246)
> 
> Would you be able to test it with your image?

Are there any plans (is it possible) to merge this into libvips-openslide ? [openslide/openslide#246](https://github.com/openslide/openslide/pull/246)

**Comment by jcupitt** [comment]
Sorry, we're not responsible for openslide. I think this is on users to build their software stack and include this patch if they need it.

Ideally, someone (not libvips) needs to volunteer to make a new openslide release and include the various fixes that have accumulated.

**Comment by ajay1685** [comment]
> Sorry, we're not responsible for openslide. I think this is on users to build their software stack and include this patch if they need it.
> 
> Ideally, someone (not libvips) needs to volunteer to make a new openslide release and include the various fixes that have accumulated.

@jcupitt Thank you for clarification.

**Comment by itachi1232gg** [comment]
@jcupitt hello sir, https://github.com/openslide/openslide/pull/246 does not actually fix this issue. With this modification, I can open the bif file, but there's something wrong with image stitching. 
![image](https://user-images.githubusercontent.com/8243929/189129617-b7d3ec96-9c22-4a6b-b178-3b5ca86f916c.png)

**Comment by itachi1232gg** [comment]
Roche is good at making troubles.

**Comment by jcupitt** [comment]
Really, someone needs to take openslide under their wing and fix it up. It's not been touched in a long time now.

**Comment by bgilbert** [comment]
I've been working on OpenSlide again recently, but there's a pretty large backlog to work through, and the community has never really had active contributors.

**Comment by Rasaa84** [comment]
How can I read .bif images using pyvips. I am using `pyvips.Image.new_from_file('test.bif')` but get the following error. 

`Error: unable to call VipsForeignLoadOpenslideFile
  openslide2vips: opening slide: Bad direction attribute "LEFT"`

**Comment by jcupitt** [comment]
> OpenSlideError: Bad direction attribute "LEFT"

openslide can't read some Ventana images. There are patches available, but you'll have to apply them yourself.

There might be a new openslide version later this year that includes these fixes.

**Comment by Rasaa84** [comment]
Thanks for your response.

Do you know any patches that I can employ to resolve this issue?

**Comment by jcupitt** [comment]
Yes, they are up ^^^^ there in the issue you are replying to.

**Comment by suk-kim** [comment]
Is this problem not solved yet?

The left problem has been solved, but the problem of the image not opening properly is not solved.

**Comment by jcupitt** [comment]
Again, this is not a libvips issue. If you have a slide that's not working properly, please ask on the openslide tracker.
