### ISSUE TITLE
README missing configuration step on Webpage

### ISSUE THREAD

**Issue by grellyd** [libvips/libvips#1191]
There is a difference between the installation instructions on [https://jcupitt.github.io/libvips/install.html](https://jcupitt.github.io/libvips/install.html) and the README. Specifically, the README is missing the final step of:

`sudo ldconfig`

Until that step, for me vips would just produce the error "vips: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory". 

Hopefully adding the final step to the README would help others avoid the same problem.

**Comment by jcupitt** [comment]
Hello @grellyd, thanks for opening this issue. 

Not all linuxes need this, and it also depends on how you install libvips, so I'm not sure this would help everyone. Are you using one of the redhat derivatives?

**Comment by grellyd** [comment]
Hey @jcupitt, sorry I missed your comment notification.

I'm using Gentoo linux (4.9.76-gentoo-r1), and I installed vips via the source tarball (vips-8.7.2.tar.gz).

No pressure re the README. I just wanted to share my experience! Thanks for the response.
