### ISSUE TITLE
insert images or texts on gif

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1192]
how to insert images and texts on a gif?  need insert on each gif frame?

I use the vips.insert api to insert a image to another

**Comment by jcupitt** [comment]
Hello, try loading the gif and saving as PNG. You'll find it is a very tall, thin image, with all the frames stacked vertically.

```
$ vips copy somefile.gif[n=-1] x.png
```

So to write text on every frame, you need to write the text many times vertically.

The simplest way to do this is to make the text frame with an alpha, use `vips_replicate` to copy it many times vertically, then use `vips_composite2` to overlay the text on the gif image.

libvips 8.8 has a better way to do this, but it's not ready yet.

**Comment by tczf1128** [comment]
is there a simple demo to do this?

**Comment by jcupitt** [comment]
I made you a php example:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

if(count($argv) != 4) {
    echo("usage: ./label-gif.php input-image output-image \"some text\"\n");
    exit(1);
}

// we can stream the main image, and we want all frames
$image = Vips\Image::newFromFile($argv[1], [
  'access' => 'sequential', 
  'n' => -1
]);

$output_filename = $argv[2];
$text = $argv[3];

// the size of each frame
$page_height = $image->get('page-height');

$overlay = Vips\Image::text($text, ['width' => $image->width, 'dpi' => 150]);

// white text on a blue background
$overlay = $overlay->ifthenelse([255, 255, 255], [0, 0, 255]);

// tag as srgb
$overlay = $overlay->copy(['interpretation' => 'srgb']);

// add an alpha
$overlay = $overlay->bandjoin(255);

// expand to the size of a frame, transparent background 
$overlay = $overlay->embed(0, $page_height - $overlay->height, 
                           $image->width, $page_height);

// expand to the full size of the gif roll
$overlay = $overlay->replicate(1, $image->height / $page_height);

// composite on top of the gif
$image = $image->composite2($overlay, 'over');

// and write back
$image->writeToFile($output_filename);
```

It was more complicated than I expected :(

**Comment by tczf1128** [comment]
Thanks. It seems a little complicated

**Comment by 781545872** [comment]
> Hello, try loading the gif and saving as PNG. You'll find it is a very tall, thin image, with all the frames stacked vertically.
> 
> ```
> $ vips copy somefile.gif[n=-1] x.png
> ```
> 
> So to write text on every frame, you need to write the text many times vertically.
> 
> The simplest way to do this is to make the text frame with an alpha, use `vips_replicate` to copy it many times vertically, then use `vips_composite2` to overlay the text on the gif image.
> 
> libvips 8.8 has a better way to do this, but it's not ready yet.

Is it ready now?Could you give me a demo please?Thanks. @jcupitt

**Comment by jcupitt** [comment]
I fixed it up a bit and added it as an example:

https://github.com/libvips/php-vips/blob/master/examples/watermark-text.php

It's still rather complicated :(

**Comment by 781545872** [comment]
Thanks,I'll take a look!

**Comment by 781545872** [comment]
Thanks,I'll take a look!
