### ISSUE TITLE
Find a pattern location in the 1 bit tiff file

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1193]
Good morning John,

Is it possible to find the location of a pattern from another tiff file having  "+" of 10x10 mm in the another 1 bit tiff file. The + may not  be always contant size,slightly increased or decreased in the search tiff tile. It should also find multiple "+"  eg. 4 or 6.

**Comment by jcupitt** [comment]
Hello @vkkindia, 

You can use `spcor` to make a correlation surface, then search for peaks. The closer a pixel is to 1.0, the better that point is as a candidate position.

https://libvips.github.io/libvips/API/current/libvips-convolution.html#vips-spcor
