### ISSUE TITLE
Add a fallback path to CMYK2XYZ in case lcms2 is missing

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1195]
If there's no lcms2 available, we could have a simple fallback cmyk <-> xyz converter. 

@dbouron has a ncie patch here that would only need minor changes:

https://github.com/dbouron/libvips/commit/7231ffea468e191e899c3508370ca34daab0bf3d

See https://github.com/libvips/libvips/issues/1186

**Comment by jcupitt** [comment]
See https://github.com/libvips/libvips/pull/1196

**Comment by dbouron** [comment]
We can close this issue as #1196 has been merged
