### ISSUE TITLE
Join multiple images?

### ISSUE THREAD

**Issue by philipgiuliani** [libvips/libvips#120]
Hi i have a folder with these images: image_1.png, image_2.png, image_3.png. Its possible to join all this images togheter horizontaly? I found `vips join`, but that can only merge 2 images.

In ImageMagick i would do: `convert +append image_*.png output.png`

Thanks.

**Comment by sergeevabc** [comment]
> vips arrayjoin "17823.jpg 17824.jpg 17825.jpg 17826.jpg" ../out.png for vertical add --across 1

Something I was looking for, thank you. However, I can't figure out how to join two images vertically with a gap filled with a white background.

``` console
$ vips arrayjoin "in01.png in02.png" out.png --across 1 --(vspacing/shim?) 100 --background ???
```

**Comment by jcupitt** [comment]
You can use the `join` operator, see:

https://www.libvips.org/API/current/libvips-conversion.html#vips-join

eg.:

```shell
vips join nina.jpg theo.jpg x.jpg vertical --expand --shim 200 --background 255 --align centre
```

To make:

![tn_x](https://github.com/libvips/libvips/assets/580843/5a1bd7fd-4669-4943-98b8-2682298f1472)

**Comment by sergeevabc** [comment]
@jcupitt
--align **_centre_** made my day. And if someone dares to type _center_, then let the error sound with a Brummie accent: “This ain't gettin the babby a frock and pinny”, lol.

**Comment by sergeevabc** [comment]
@jcupitt, in your last example with two children you joined the images with a white background, but what if I want a transparent background? The `--background transparent` does not work.

**Comment by jcupitt** [comment]
You need to add alpha to the images first, then join with background 0 (0 in alpha is transparent).

```shell
vips bandjoin_const theo.jpg theo.png 255
vips bandjoin_const nina.jpg nina.png 255
vips join nina.png theo.png x.png vertical --expand --shim 200 --background 0 --align centre
```

To make:

![tn_x](https://github.com/libvips/libvips/assets/580843/252b9dc5-da5e-4aa3-8068-97384f7bd2b6)
