### ISSUE TITLE
Fastest way to compare images?

### ISSUE THREAD

**Issue by jtorresfabra** [libvips/libvips#1201]
Hi, 
Noob question here:
I'm looking for the fastest way to compare two images in order to say wether it has the same pixel values or not. 

So far I tried vips_equal so I get a uchar image with 0/255 values, is the faster way to traverse each ouput image values to check for a false?

**Comment by jcupitt** [comment]
Hello Jordi, 

Do `vips_equal()`, then `vips_min()` on that. That will loop over the images, but stop as soon as a difference is found.

**Comment by jtorresfabra** [comment]
Ah, makes sense! Thanks for your fast answer :)

**Comment by jcupitt** [comment]
I should have explained more. 

As you say, equal will give 0 or 255 for false or true. Min will start a set of threads to pull pixels through the equals operator, but is smart enough to know that for uchar pixels (what you'll get for equal), 0 is the minimum possible value. Therefore, as soon as it sees a 0 (false, or not equal), it'll stop and return that as the answer. 

If you run this on a pair of images on disc and set sequential access, libvips may not even have to decode all of the inputs.

**Comment by jtorresfabra** [comment]
ok I was reviewing the API for the min and was not really clear, now it is.
