### ISSUE TITLE
How to convert image from rgb to cmyk colorspace?

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1202]
I need a cmyk image to print

**Comment by jcupitt** [comment]
Hello @tczf1128 ,

Use `icc_transform` to move between two device spaces. For example, if you have an image in device space, tagged with a profile, try:

```
vips icc_transform wtc.jpg x.jpg cmyk.icm 
```

Where `cmyk.icm` is your printer profile.

If the input image has not been tagged but you know it is srgb, you can do:

```
vips icc_export k2.jpg x.jpg --output-profile cmyk.icm 
```

And it'll be converted from srgb using libvips functions, then exported to cmyk with the device profile.

**Comment by jcupitt** [comment]
libvips 8.8 will have a better way to do this, but it's not done yet, so I'd use `icc_transform` for now.

**Comment by tczf1128** [comment]
the way of libvips8.8 need printer profile too? when it ready?

**Comment by jcupitt** [comment]
You *always* need a printer profile, libvips 8.8 just has one built in.

It'll probably be this one:

https://github.com/libvips/nip2/blob/master/share/nip2/data/cmyk.icm

A good, free, fairly generic CMYK profile. But the real profile for your exact printer and paper would be much better.

**Comment by tczf1128** [comment]
ok. thanks
