### ISSUE TITLE
vips_insert has no option for gravity

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1213]
can I insert a sub image with x,y and gravity?

**Comment by jcupitt** [comment]
`insert` only lets you set position by (x, y) coordinate. If you want to position on the left centre edge (for example), you need to calculate their value.

**Comment by tczf1128** [comment]
any other api can do this?

**Comment by jcupitt** [comment]
Can you explain exactly what you want to do?

**Comment by tczf1128** [comment]
add text or image on a base image with gravity option

**Comment by jcupitt** [comment]
In python (for example) you could write:

```python
def insert_gravity(big, small, gravity):
    if gravity == "west":
        x = 0
        y = (big.height + small.height) / 2
    elif gravity == "north":
        ... etc.

   return big.insert(small, x, y)
```

**Comment by jcupitt** [comment]
You could use `composite` instead of insert -- you'd get support for transparency then.

**Comment by tczf1128** [comment]
ok thanks
