### ISSUE TITLE
Contour detection

### ISSUE THREAD

**Issue by harukizaemon** [libvips/libvips#1215]
I have a bunch of old code that uses OpenCV which I'm converting to use VIPS. Right now everything else works _except_ I have some contour detection code that uses OpenCV's `findContours`—specifically I'm looking for things that look like circular blobs—and I'm wondering if you can think of a way to use VIPS to achieve something similar?

**Comment by jcupitt** [comment]
Hi @harukizaemon 

findContours seems to search for equal-valued regions and return a set of lines, is that right? Sorry, there's no direct equivalent in libvips, you'd need to find another way to accomplish your task.

You could try a circular Hough transform. You give this a min and max radius, and it'll find circles within that range. It does need them to be rather circular to work well.

Alternatively, you could split the image into regions of equal pixel value with `label_regions`, then find the bounding box of each region with `hist_find_indexed`. "Circular" blobs would then be approximately square regions with 50% or more pixels with that label.

Do either of those sound possible?

**Comment by harukizaemon** [comment]
Hey @jcupitt,

I was thinking of giving the Hough circles a go.

I like your thinking re segmentation. Indeed, I've been wanting to think of a way to segment rather than use contours as the latter, while works fairly well, is still quite fragile.

I will have a look.

Thanks as always!
