### ISSUE TITLE
More than 5GB file meet error: openside2vips:opening slide:can't validate JPEG for directory 0:Expected Maker at 4294968343, found none.

### ISSUE THREAD

**Issue by owenustc** [libvips/libvips#1216]
Hi,
   I used vips to deal with big file, about 5GB ndpi file,  but met a error from openside2vips module.
Anyone help me to to fix the bug. My file is about 5.7GB, and the detailed information as follow: 
![Uploading image.png…]()

**Comment by owenustc** [comment]
@jcupitt 
 Hi, could you help me?  I will send my file to you by gmail.

**Comment by owenustc** [comment]
Hi, @jcupitt ,do you receive my big file with 5GB, and could the openside support the big file?

**Comment by jcupitt** [comment]
Hello again, yes, I replied on this issue, where you posted the link:

https://github.com/libvips/libvips/issues/1206#issuecomment-456038795

I think your image is probably corrupt.

**Comment by owenustc** [comment]
Hi, @jcupitt , I update my openslide to 3.41, and used debug mode to recompled openside.
I found that openside support big file with 5G.
But vips also has some bug for 5G file, could you help me? The error information as follow:
owen# vips dzsave  S105330-HE1718.ndpi x  --compression -1 --background 0 --centre --layout google

(vips:6488): VIPS-WARNING **: 19:46:11.021: error in tile 0 x 98592

(vips:6488): VIPS-WARNING **: 19:46:11.022: error in tile 0 x 98584

(vips:6488): VIPS-WARNING **: 19:46:11.022: error in tile 0 x 98600

(vips:6488): VIPS-WARNING **: 19:46:11.022: error in tile 0 x 98616

(vips:6488): VIPS-WARNING **: 19:46:11.022: error in tile 0 x 98608

(vips:6488): VIPS-WARNING **: 19:46:11.022: error in tile 0 x 98624

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98632

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98576

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98568

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 3840 x 98576

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98640

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98648

(vips:6488): VIPS-WARNING **: 19:46:11.023: error in tile 0 x 98656

(vips:6488): VIPS-WARNING **: 19:46:11.024: error in tile 0 x 98664

(vips:6488): VIPS-WARNING **: 19:46:11.024: error in tile 0 x 98672

(vips:6488): VIPS-WARNING **: 19:46:11.024: error in tile 0 x 98680

(vips:6488): VIPS-WARNING **: 19:46:11.025: error in tile 3840 x 98608

(vips:6488): VIPS-WARNING **: 19:46:11.025: error in tile 3840 x 98568

(vips:6488): VIPS-WARNING **: 19:46:11.025: error in tile 3840 x 98584

(vips:6488): VIPS-WARNING **: 19:46:11.025: error in tile 3840 x 98592

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98600

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98560

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98616

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98624

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98632

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98640

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98648

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98656

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98664

(vips:6488): VIPS-WARNING **: 19:46:11.026: error in tile 3840 x 98672

(vips:6488): VIPS-WARNING **: 19:46:11.027: error in tile 3840 x 98680
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321
openslide2vips: reading region: Restart marker not found at recorded position 216321

**Comment by owenustc** [comment]
root@nodeip-dev115:/home/owen# ls x/
1  10  2  3  4  5  6  7  8  9

**Comment by owenustc** [comment]
Hi, @jcupitt ,  you can used openside-3.41,  I used openside-3.4.1, recompiled it with debug mode. It is work with 5.7G. The detailed information as follow:
/owen# openslide-write-png --version
openslide-write-png 3.4.1, using OpenSlide 3.4.1
Copyright (C) 2007-2015 Carnegie Mellon University and others

OpenSlide is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License, version 2.1.
<http://gnu.org/licenses/lgpl-2.1.html>

OpenSlide comes with NO WARRANTY, to the extent permitted by law.  See the
GNU Lesser General Public License for more details.
root@nodeip-dev115:/home/owen# openslide-write-png S105330-HE1718.ndpi  0 0 0 100 100 x.png
root@nodeip-dev115:/home/owen#

**Comment by owenustc** [comment]
The tool, named openslide-write-png, had generated right result,  which is as follow:
root@nodeip-dev115:/home/owen# ls x.png
x.png

**Comment by jcupitt** [comment]
Perhaps your slide was corrupted during the upload? I tried again here using this docker image:

https://github.com/jcupitt/docker-builds/tree/master/libvips-openslide-alpine

I see:

```
$ docker run --rm -it -v /home/john/pics/openslide:/data libvips-openslide-alpine bash
bash-4.4# cd /data/
bash-4.4# md5sum S105330-HE1718.ndpi 
da1b232b7661f4bf8e7acb59dba6653a  S105330-HE1718.ndpi
bash-4.4# vipsheader S105330-HE1718.ndpi 
vipsheader: openslide2vips: opening slide: Can't validate JPEG for directory 0: Expected marker at 4294968343, found none
bash-4.4# ldd $(which vipsheader) | grep -i tiff
	libtiff.so.5 => /usr/lib/libtiff.so.5 (0x7fb136bbf000)
bash-4.4# openslide-write-png S105330-HE1718.ndpi 0 0 0 100 100 x.png
openslide-write-png: S105330-HE1718.ndpi: Can't validate JPEG for directory 0: Expected marker at 4294968343, found none
```

So it does not work here. 

1. What is the md5sum for your large file? Perhaps it is different.
2. Could you make a Dockerfile so that I can try your build?

**Comment by owenustc** [comment]
Hi,  John Cupitt,   I enjoyed my new year in the previous days.  And the
file attached is my docker image with openSide and vips tools.  The
command, called "docker load <  openslide_vips.img.tgz",  can build my
docker image in your system.
And you can try  the openslide-write-png tool of my image to decode the big
file with 5GB, which I provided to you. I guess that the tool, named
openslide-write-png, will work well, but vips meet error.
 openslide_vips.img.tgz
<https://drive.google.com/file/d/1t45_dcR9uCwWl5g62LGlFk5puZVYDSsP/view?usp=drive_web>

John Cupitt <notifications@github.com> 于2019年2月1日周五 下午8:16写道：

**Comment by jcupitt** [comment]
Hello @owenustc, happy new year!

As I said, your image does not work with openslide for me:

```
$ md5sum S105330-HE1718.ndpi 
da1b232b7661f4bf8e7acb59dba6653a  S105330-HE1718.ndpi
$ openslide-write-png S105330-HE1718.ndpi 0 0 1 1000 1000 x.png
openslide-write-png: S105330-HE1718.ndpi: Can't validate JPEG for directory 0: Expected marker at 4294968343, found none
$ which openslide-write-png 
/usr/bin/openslide-write-png
```

* What md5sum do you see? Try running `md5sum S105330-HE1718.ndpi` and see if you get the same value.
* Could you share the Dockerfile that made your image? I need to see how it was made to be able to find a problem.

**Comment by jcupitt** [comment]
I tried your docker image, but it only works for the start of the file:

```
root@cb3c3dd6fed7:/data# /usr/local/bin/openslide-write-png S105330-HE1718.ndpi  0 0 1 1000 1000 x.png
root@cb3c3dd6fed7:/data# /usr/local/bin/openslide-write-png S105330-HE1718.ndpi 100000 100000 0 1000 1000 x.png
openslide-write-png: Restart marker not found at recorded position 50866448
```

Does the whole file work for you?

**Comment by owenustc** [comment]
Hi @jcupitt , in my opinion, your command is error.  I tried many command, which are as follow, to work well.
me/owen# openslide-write-png  S105330-HE1718.ndpi 0 0 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 2 2 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 1000 10000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 100000 10000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 100000 100000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 100000 100000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 100000 100000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 100000 100000 1 1000 1000 x.png
root@nodeip-dev115:/home/owen# ls

**Comment by owenustc** [comment]
Hi, @jcupitt , All command with level zero are work right, which are as follow:
/owen# openslide-write-png  S105330-HE1718.ndpi 1000 1000 0 10 10 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 1000 1000 0 100 100 x.png
root@nodeip-dev115:/home/owen# openslide-write-png  S105330-HE1718.ndpi 1000 1000 0 100 100 x.png
root@nodeip-dev115:/home/owen#

So I think the pixel of your command is out of range in the file with level zero.

**Comment by owenustc** [comment]
Hi, @jcupitt , do you agree my opinion  and validate  all of commands, which I provided ?

**Comment by jcupitt** [comment]
Sorry, I need to test again. I'm on holiday at the moment, I'll be back on my work machine on 22 February.

**Comment by owenustc** [comment]
Hi @jcupitt , Do you validate these commands today?  I wait you back to find the  bug of vips or openslide.

**Comment by jcupitt** [comment]
Sorry, I've been horribly busy. I've tried your file again, and I think it's an openslide problem.

Here's what I see with `bild.ndpi`, a 2.1GB slide, running git master libvips on my machine:

```
$ vipsheader bild.ndpi 
bild.ndpi: 126976x98304 uchar, 4 bands, rgb, openslideload
$ openslide-write-png bild.ndpi 100000 98000 0 100 100 x.png
```

So that's extracting 100 x 100 pixels from near the bottom of the slide. If I check `x.png`, it's all white. If I move off the bottom of the slide, I see:

```
$ openslide-write-png bild.ndpi 100000 99000 0 100 100 x.png
$ 
```

So no error message, and `x.png` is now all transparent.

If I try with libvips, I see:

```
$ vips crop bild.ndpi x.png 100000 98000 100 100 
$ vips crop bild.ndpi x.png 100000 99000 100 100 
extract_area: bad extract area
$
```

So libvips will refuse to read off the image edge.

If I now try with your huge slide in your docker container, I see:

```
$ docker run -it -v /home/john/pics/openslide:/data --rm vips_openslide:1.0
root@da0705ac0d66:/# cd /data
root@da0705ac0d66:/data# vipsheader S105330-HE1718.ndpi 
S105330-HE1718.ndpi: 188160x103680 uchar, 4 bands, rgb, openslideload
root@da0705ac0d66:/data# openslide-write-png S105330-HE1718.ndpi 100000 103000 0 100 100 x.png
openslide-write-png: Restart marker not found at recorded position 146093701
```

That should read a 100 x 100 pixel patch from near the bottom of the slide, but instead it gives a format error. I think openslide is unable to read your slide file.

**Comment by owenustc** [comment]
Hi , @jcupitt , in your command, 100000 103000, could be out of S105330-HE1718.ndpi.

**Comment by jcupitt** [comment]
I was only fetching a 100x100 pixel patch, so 103000 + 100 < 103680.

**Comment by owenustc** [comment]
Hi, @jcupitt ,could you connect the openslide to see this problem?

**Comment by jcupitt** [comment]
I would recommend reporting the issue to the openslide mailing list, or opening an issue on their tracker.

**Comment by jcupitt** [comment]
I think this is an openslide problem, I'll close.
