### ISSUE TITLE
London meetup, 21st March 2019

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1222]
@kmartinez has skilfully managed to secure funding to help support a libvips meetup in London. I think this would be very informal (just meeting for a chat in a pub, with free beer), but we could get a seminar room in Imperial for an hour or two beforehand if anyone would like to present something. 

Jonas Øgaard will be in London 8 - 22 March, so how about an evening in that period? Does anyone have any preferences? @kleisauke, @lovell, are you around?

**Comment by lovell** [comment]
Sounds great, happy to meet wherever is good for those travelling from further afield. In terms of date preference, I can't do Wednesdays but otherwise mid-March looks pretty clear at the moment.

**Comment by kmartinez** [comment]
Hi! it would be good to announce 21st March as the proposed date and see how many people can make it. probably worth putting on the email list John? Can you spam contacts in London Lovell?

**Comment by jcupitt** [comment]
21 March was just when we met last year, it doesn't have to be the same this year. But perhaps ... why not! It's a Thursday, so it would seem to fit with Lovell. Any other suggestions?

**Comment by tomgallagher** [comment]
I'm around on the 21st and would like to come along.

**Comment by jcupitt** [comment]
OK, let's have the 21st as the proposed date then.

**Comment by kmartinez** [comment]
VIPS is celebrating 30 years! We started VIPS in 1989 so this year is a good time to celebrate all the cool things people are doing with libVIPS.. the more the merrier!

**Comment by alesvaupotic** [comment]
Guys, is this fixed for the 21st March? I'd fly in to meet you and share some thoughts.

**Comment by jcupitt** [comment]
Yes, I think so. We've not decided where to meet yet, but the date is fixed.

**Comment by jcupitt** [comment]
Just to have a proposal to discuss, how about meeting at Da Mario's:

http://www.damario.co.uk/da-mario/4526627955

It's just by Imperial, so we could meet earlier and have presentations and stuff, if anyone would like that. Or just meet at the restaurant. We could spend Kirk's money on pizza and then move on to a pub.

**Comment by alesvaupotic** [comment]
How many people usually attend?

**Comment by jcupitt** [comment]
This is only the second London one. I think it was six people last time, so tiny! Really it's just a chat in a pub.

**Comment by alesvaupotic** [comment]
Great. I'll book a short holiday with my wife and be there on Thursday evening. I simply love the library but I don't think I am using it as efficiently as I should. I thought maybe you or someone else might show me the way to improve if I present my use case? I am rewriting the production process for https://hoorayheroes.com/, have a look around. There is a sister site for the French, Austrian, German, Italian and Slovenian market, look for the flags down left. I'll explain more in person ...

**Comment by jcupitt** [comment]
Small update: hoorayheroes have very generously offered to pay some of the beer costs. Thank you very much!

**Comment by alesvaupotic** [comment]
No problem, I am really looking forward to meeting all of you and chat about image processing. As I said before, we found a good use for the library and it is only fair to contribute a bit. We are not experienced enough to commit any code to the project but we'll support it in other ways.

**Comment by kmartinez** [comment]
Hi everyone! good to see more people signing up for this London meetup! We will confirm the venue/s today!

**Comment by kmartinez** [comment]
Everyone is welcome to Da Mario's at 6:30 on March 21st! Please let us know if you are coming (for numbers/table). The food/drink will be heavily subsidised by the University of Southampton and hoorayheroes! We're looking forward to meeting new people and familiar faces.
http://www.damario.co.uk/pizza/4526627964

**Comment by jcupitt** [comment]
And after the meal I propose moving on to the Builder's Arms:

https://www.thebuildersarmskensington.co.uk/

Perhaps around 9pm, if anyone would like to join us later.

**Comment by tomgallagher** [comment]
Looking forward to it. Should we book a table at the Builders Arms, if it's possible?

**Comment by jcupitt** [comment]
It's a pretty quiet, backstreets pub, so I think we'll be OK. But good suggestion, I'll call by tomorrow and check, just in case.

The table in the pizzeria is booked for 10 under the secret codename "john".

**Comment by jcupitt** [comment]
I'll be in the Builders Arms from 5pm with Ales and perhaps Jonas, then moving on to the pizzeria at 6:30, if anyone would like to join us.

Unfortunately my mobile is being repaired :-( but I'll be contactable on email until 4:30 or so.

**Comment by fmitchell259** [comment]
Hi guys, I am very new to the development community and would love to come and chat and learn from more experienced people. This little meet up in a pub sounds great but I've just realised it's tonight! 

I'd be completely up for a meet up in the future. :)

**Comment by jcupitt** [comment]
Ah next time perhaps @fmitchell259.

I feel a little fragile today, but otherwise fine. Thank you all for coming!

**Comment by jcupitt** [comment]
A pic from the meeting.

![IMG_20190321_185749_3](https://user-images.githubusercontent.com/580843/54919780-93806800-4ef9-11e9-9f0f-3909628dde06.jpg)
