### ISSUE TITLE
What is the quickest way to composite a set of images and apply different opacity for each

### ISSUE THREAD

**Issue by alesvaupotic** [libvips/libvips#1223]
Hi, 

what I am looking for is to blend a few images, but I need to apply different opacity on each. Something like
`vips composite "images/1.png images/2.png images/3.png images/4.png images/5.png" images/out-vips.png 2` 
but 1.png would have the opacity od 100%, 2.png of 60%, 3.png of 10% ... You get the idea.

Can it be done without temporary files?

**Comment by jcupitt** [comment]
Hello @alesvaupotic,

You'd need temporary files if you use the vips CLI, but if you use Python / Ruby / C# / JavaScript etc. you don't need them.

In Python, something like:

```python
#!/usr/bin/python

import sys
import random
import pyvips

images = [pyvips.Image.new_from_file(filename, access="sequential")
          for filename in sys.argv[2:]]

# scale each alpha (band 4) randomly
# "*" will make a set of float images ... back to 8 bit
images = [(image * [1, 1, 1, random.random()]).cast("uchar")
          for image in images]

# composite!
image = images[0].composite(images[1:], "over")

image.write_to_file(sys.argv[1])
```

Then:

```
john@yingna ~/try/sample $ for i in {1..10}; do cp ~/pics/PNG_transparency.png $i.png; done
john@yingna ~/try/sample $ ls
10.png  1.png  2.png  3.png  4.png  5.png  6.png  7.png  8.png  9.png
john@yingna ~/try/sample $ ../try292.py x.png *.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/52277331-64636680-294c-11e9-96c7-94cd66485f90.png)

**Comment by alesvaupotic** [comment]
Oh, I see. I do use CLI at the momemnt, but will switch to your suggestion.

Thanks a lot!
