### ISSUE TITLE
Dicom loading

### ISSUE THREAD

**Issue by gedw99** [libvips/libvips#1225]
Can libvips load Dicom directly ? 
This is what i would prefer, but the readme says "It can also load images via ImageMagick or GraphicsMagick, letting it load formats like DICOM."

Maybe someone has the time to explain the quote from the readme please, as i am trying to understand the architectural dependency of ImageMagick / GraphicsMagick.

**Comment by jcupitt** [comment]
Hello @gedw99,

There's no direct DICOM support. You need to build libvips with ImageMagick and then use their DICOM loader. I've spent some time fixing up the IM DICOM system and it works reasonably well for the MRI / CT / PET images I work with.

For example, you can do:

```
$ vipsheader -a MRIm5.dcm 
MRIm5.dcm: 200x200 ushort, 1 band, grey16, magickload
width: 200
height: 200
bands: 1
format: ushort
coding: none
interpretation: grey16
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: MRIm5.dcm
vips-loader: magickload
magick-date:create: 2017-05-05T16:22:48+01:00
magick-date:modify: 2017-05-05T16:22:38+01:00
magick-dcm:AcquisitionNumber: 5 
magick-dcm:DeviceSerialNumber: 10128654
magick-dcm:FrameofReferenceUID: 2.16.756.5.5.100.8323328.22774.1484221677.1204.7
magick-dcm:ImageOrientation(Patient): -0.8234031129\-0.05753266985\-0.5645328206\0.03791537284\0.9870459094\-0.1558935446 
magick-dcm:ImagePosition(Patient): 8.747373231\-18.27474765\11.33745168
magick-dcm:ImagesinAcquisition: 7 
magick-dcm:ImageType: DERIVED\SECONDARY\OTHER 
magick-dcm:ImplementationClassUID: 1.2.276.0.7230010.3.0.3.6.0
magick-dcm:ImplementationVersionName: OFFIS_DCMTK_360 
magick-dcm:Instance(formerlyImage)Number: 5 
magick-dcm:InstanceCreationDate: 20170112
magick-dcm:InstanceCreationTime: 120931
magick-dcm:InstitutionName: Imperial College London 
magick-dcm:Manufacturer: Bruker BioSpin MRI GmbH 
magick-dcm:Manufacturer'sModelName: spect 
magick-dcm:MediaStorageSOPClassUID: 1.2.840.10008.5.1.4.1.1.4
magick-dcm:MediaStorageSOPInstanceUID: 2.16.756.5.5.100.8323328.22774.1484221677.1204.4
magick-dcm:Modality: MR
magick-dcm:MRAcquisitionType: 2D
magick-dcm:Patient'sBirthDate: 20161214
magick-dcm:Patient'sID: R7_3.5w_MCT_LIRA
magick-dcm:Patient'sName: R7
magick-dcm:Patient'sSex: O 
magick-dcm:Patient'sWeight: 0.001 
magick-dcm:PatientPosition: HFP 
magick-dcm:PhotometricInterpretation: MONOCHROME2 
magick-dcm:PixelSpacing: 0.15\0.15 
magick-dcm:ReferringPhysician'sName: nmrsu 
magick-dcm:RescaleIntercept: 0 
magick-dcm:RescaleSlope: 0.154761567 
magick-dcm:RescaleType: US
magick-dcm:ScanningSequence: RM
magick-dcm:SequenceVariant: NONE
magick-dcm:SeriesDate: 20170112
magick-dcm:SeriesDescription: Parametric image for T1 magnitude inversion recovery produced fr
magick-dcm:SeriesInstanceUID: 2.16.756.5.5.100.8323328.22774.1484221677.1204
magick-dcm:SeriesNumber: 230003
magick-dcm:SeriesTime: 114757
magick-dcm:SliceLocation: -1.5
magick-dcm:SliceThickness: 1.5 
magick-dcm:SoftwareVersion(s): ParaVision Acquisition 6.0.1\ParaVision 6.0.1\xtip 6.0.1
magick-dcm:SOPClassUID: 1.2.840.10008.5.1.4.1.1.4
magick-dcm:SOPInstanceUID: 2.16.756.5.5.100.8323328.22774.1484221677.1204.4
magick-dcm:StudyDate: 20161214
magick-dcm:StudyID: T1mapping 
magick-dcm:StudyInstanceUID: 2.16.756.5.5.100.8323328.27251.1481719368.4
magick-dcm:StudyTime: 124248
magick-dcm:TransferSyntaxUID: 1.2.840.10008.1.2.1
n-pages: 1
```

So the DICOM metadata comes in as tags with the `magick-dcm:` prefix, and pixels as a 2D array, or as a 3D array with the Z dimension mapped to pages. You can use things like vips_grid() to turn pages into volumes efficiently.

**Comment by choosehappy** [comment]
Stumbled upon this closed issue via google, so adding additional information for folks:

if the goal is to load digital pathology images, the latest version of openslide supports dicom (coming in the binaries soon)
https://openslide.org/formats/dicom/
https://github.com/openslide/openslide/issues/351

which i suspect should trickle into vips?

**Comment by jcupitt** [comment]
This all works now if you build libdicom, openslide and libvips from git master. I added ICC profile support to openslide as well, which is really useful for many of the slide formats.

For example, I see:

```
$ vipsheader -a 3DHISTECH\^SmoothMuscle\ \[ID_20210527084705\]/20210527\ 000000\ \[D1M\ 7S\ 1\]/Series\ 000\ \[SM\]/000001.dcm 
3DHISTECH^SmoothMuscle [ID_20210527084705]/20210527 000000 [D1M 7S 1]/Series 000 [SM]/000001.dcm: 57344x92160 uchar, 4 bands, srgb, openslideload
width: 57344
height: 92160
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 8244.02
yres: 8244.02
filename: 3DHISTECH^SmoothMuscle [ID_20210527084705]/20210527 000000 [D1M 7S 1]/Series 000 [SM]/000001.dcm
vips-loader: openslideload
slide-level: 0
dicom.AccessionNumber: A20210527084705
dicom.AcquisitionDateTime: 20210518215910+0200
dicom.AcquisitionDuration: 32
dicom.BitsAllocated: 8
dicom.BitsStored: 8
dicom.BurnedInAnnotation: NO
...
dicom.TimezoneOffsetFromUTC: +0200
dicom.TotalPixelMatrixColumns: 57344
dicom.TotalPixelMatrixFocalPlanes: 1
dicom.TotalPixelMatrixOriginSequence[0].XOffsetInSlideCoordinateSystem: 19.18547
dicom.TotalPixelMatrixOriginSequence[0].YOffsetInSlideCoordinateSystem: 32.54965
dicom.TotalPixelMatrixRows: 92160
dicom.TransferSyntaxUID: 1.2.840.10008.1.2.4.50
dicom.VolumetricProperties: VOLUME
openslide.level-count: 10
openslide.level[0].downsample: 1
openslide.level[0].height: 92160
openslide.level[0].tile-height: 1024
openslide.level[0].tile-width: 1024
openslide.level[0].width: 57344
openslide.level[1].downsample: 2
openslide.level[1].height: 46080
openslide.level[1].tile-height: 1024
openslide.level[1].tile-width: 1024
openslide.level[1].width: 28672
openslide.level[2].downsample: 4
openslide.level[2].height: 23040
openslide.level[2].tile-height: 1024
openslide.level[2].tile-width: 1024
openslide.level[2].width: 14336
openslide.level[3].downsample: 8
openslide.level[3].height: 11520
openslide.level[3].tile-height: 1024
openslide.level[3].tile-width: 1024
openslide.level[3].width: 7168
openslide.level[4].downsample: 16
openslide.level[4].height: 5760
openslide.level[4].tile-height: 1024
openslide.level[4].tile-width: 1024
openslide.level[4].width: 3584
openslide.level[5].downsample: 32
openslide.level[5].height: 2880
openslide.level[5].tile-height: 1024
openslide.level[5].tile-width: 1024
openslide.level[5].width: 1792
openslide.level[6].downsample: 64
openslide.level[6].height: 1440
openslide.level[6].tile-height: 1024
openslide.level[6].tile-width: 1024
openslide.level[6].width: 896
openslide.level[7].downsample: 128
openslide.level[7].height: 720
openslide.level[7].tile-height: 1024
openslide.level[7].tile-width: 1024
openslide.level[7].width: 448
openslide.level[8].downsample: 256
openslide.level[8].height: 360
openslide.level[8].tile-height: 1024
openslide.level[8].tile-width: 1024
openslide.level[8].width: 224
openslide.level[9].downsample: 512
openslide.level[9].height: 180
openslide.level[9].tile-height: 1024
openslide.level[9].tile-width: 1024
openslide.level[9].width: 112
openslide.mpp-x: 0.12129999999999999
openslide.mpp-y: 0.12129999999999999
openslide.vendor: dicom
slide-associated-images: label, macro
```

**Comment by jcupitt** [comment]
... this means [vipsdisp](https://github.com/jcupitt/vipsdisp) gets DICOM support too, including colour management:

![image](https://github.com/libvips/libvips/assets/580843/3835ee4f-3954-402e-a40d-e40bb520032e)

**Comment by choosehappy** [comment]
just build libdicom, openslide and libvips from git master, I can indeed confirm this works as expected : ) 

This is a huge game changer for us, amazing!!

**Comment by jcupitt** [comment]
Great!

It's not final yet, there's still some ongoing discussion over the libdicom API, so it might change. We're hoping to release it all by the end of September.

Any testing you could do would be really helpful.

**Comment by jcupitt** [comment]
I would have a look at ICC profile support too -- it means you can match the appearance of the vendor systems exactly. Except for hamamatsu, who have their own crazy thing.

**Comment by choosehappy** [comment]
> I would have a look at ICC profile support too

yes, this is going to be needed going forward and often overlooked by folks!

FYI, wrote a whole blog post on the topic: http://www.andrewjanowczyk.com/application-of-icc-profiles-to-digital-pathology-images/

> Any testing you could do would be really helpful

no problem, happy to report any issues. been using it for 24h now, and none to report however : )

**Comment by jcupitt** [comment]
Oh cool! I like your blog post.

One issue you don't mention is the crazy profiles used by most scanner manufacturers. The current GT450 scanner has a 13mb ICC profile (!!!?!?!?!). This makes web display very challenging, since you have to attach that profile to every tile you send to the browser, or you have to apply the profile on the server.

I think ICC profiles are still pretty new for the scanner vendors and they haven't really got the hang of them yet. Hopefully they'll hire some colour expert and switch to saner profiles (ie. 500 bytes or so, the size they ought to be) soon.

**Comment by jcupitt** [comment]
fwiw, in pyvips you can make a colour managed tile like this:

```python
# setting `rgb=True` makes openslide return images without alpha, speeding up downstream processing
image = pyvips.Image.openslideload("something.svs", rgb=True)
# any left/top/width/height, this does not need to be tile-aligned
tile = image.crop(100, 100, 256, 256)
# map to srgb using the ICC profile embedded in the slide
srgb_tile = tile.icc_transform("srgb")
# send to the client with no metadata
jpeg_tile = srgb_tile.jpegsave(strip=True)
```

**Comment by choosehappy** [comment]
> I think ICC profiles are still pretty new for the scanner vendors and they haven't really got the hang of them yet

I think that is exactly the case. Still a bit of the wild-west. There are some interesting companies cropping up, such as FFEI (I'm not affiliated), which uses calibrated slides to generate on-site, per-scanner, ICC profiles:

https://ffei.ai/

This will both greatly decrease cross-site/scanner variability, while also making the need for ICC profile utilization a requirement. This also makes sense from a computational overhead standpoint as its likely the most efficient way to correct for known biases!


Thanks for the code, noted it down!

**Comment by jcupitt** [comment]
That colour target slide is very cool! What a shame it's so expensive :( 

They should have included some saturated RGB samples and a better greyscale, sigh.

I don't suppose you know of any other colour target slides?

**Comment by choosehappy** [comment]
Unfortunately, i don't know any other slides, which is why i suspect the cost for these is high - a custom novel device for a specific niche is always going to be a bit pricy. I've spoken with them at conferences; there was a lot of research that went into the design. 

I'm hoping that as they become more popular, the demand will go up, and then the cost will come down via economies of scale....until the point that they are basically routine equipment that come included when one purchases a scanner

**Comment by miriam-groeneveld** [comment]
Any idea when DICOM support via OpenSlide will be available in libvips? Would be such a great feature!

**Comment by jcupitt** [comment]
It's there now if you build from source. 

Homebrew should update to include it in the next day or so. 

vipsdisp has it built in now:

https://flathub.org/apps/org.libvips.vipsdisp

libvips 8.15 will be out in a couple of weeks and will include openslide and libdicom in the windows binaries, and full support for the new colour management features.

**Comment by jcupitt** [comment]
Ah from the linked issue I see you're doing DICOM to TIFF. 

You can experiment with the libvips converter using vipsdisp:

- load the DCM file 
- right-click and select save-as
- enter something like `x.tif` and press Enter
- you'll get a set of TIFF save options:

![image](https://github.com/libvips/libvips/assets/580843/31c99184-5538-4f3b-9406-ee9e1d94c709)

- select jpeg / tile / pyramid / 256x256
- click Save and you'll get a progress bar

![image](https://github.com/libvips/libvips/assets/580843/c12bdf18-daef-4c5a-8b9b-866e123f5ee5)

- it should be reasonably quick and load most of your cores, hopefully

**Comment by jcupitt** [comment]
... or at the command-line, of course:

```!
$ vipsheader 3DHISTECH\^SmoothMuscle\ \[ID_20210527084705\]/20210527\ 000000\ \[D1M\ 7S\ 1\]/Series\ 000\ \[SM\]/000001.dcm
3DHISTECH^SmoothMuscle [ID_20210527084705]/20210527 000000 [D1M 7S 1]/Series 000 [SM]/000001.dcm: 57344x92160 uchar, 4 bands, srgb, openslideload
$ /usr/bin/time -f %M:%e vips copy 3DHISTECH\^SmoothMuscle\ \[ID_20210527084705\]/20210527\ 000000\ \[D1M\ 7S\ 1\]/Series\ 000\ \[SM\]/000001.dcm[rgb] x.tif[compression=jpeg,tile,pyramid,tile-width=256,tile-height=256]
1168008:67.52
```

So 1gb of RAM and needed 1m7s.

You can see it copies over the DICOM ICC profile too:

```
$ vipsheader -a x.tif
x.tif: 57344x92160 uchar, 3 bands, srgb, tiffload
width: 57344
height: 92160
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 8244.02
yres: 8244.02
filename: x.tif
vips-loader: tiffload
n-pages: 10
icc-profile-data: 63928 bytes of binary data
resolution-unit: in
bits-per-sample: 8
orientation: 1
```

**Comment by jcupitt** [comment]
> It's there now if you build from source.

To be a bit clearer:

1. If you build the new openslide4 with libdicom, then build libvips 8.14 with that, you'll get DICOM in libvips via openslide.
2. If you build libvips master instead, you'll also get ICC profile support for openslide images. This will be 8.15 RSN.

**Comment by jcupitt** [comment]
Ahem, sorry, final update, I noticed you are also writing DZI. libvips 8.15 has a faster DZI converter as well, usually about 3x quicker than 8.14.

```
$ /usr/bin/time -f %M:%e vips copy 3DHISTECH\^SmoothMuscle\ \[ID_20210527084705\]/20210527\ 000000\ \[D1M\ 7S\ 1\]/Series\ 000\ \[SM\]/000001.dcm[rgb] /usr/bin/time -f %M:%e vips copy 3DHISTECH\^SmoothMuscle\ \[ID_20210527084705\]/20210527\ 000000\ \[D1M\ 7S\ 1\]/Series\ 000\ \[SM\]/000001.dcm[rgb] x.dz
1343840:72.32
```

1.4gb of peak memuse, 1m12s of runtime for this 57344 x 92160 pixel DICOM. It writes the DZI as an uncompressed zip64 file called `x.dz`.

**Comment by miriam-groeneveld** [comment]
Thanks for the extensive answer John! We will wait for the release of libvips 8.15.

**Comment by jcupitt** [comment]
Here's the libvips 8.15 release issue, let's continue discussion (if any) there.

https://github.com/libvips/libvips/issues/3718
