### ISSUE TITLE
nip2 in batch mode gives: no "main" found

### ISSUE THREAD

**Issue by deftdawg** [libvips/libvips#1226]
I fixed up an obsolete homebrew formula to get nip 8.7.1 built and running on OSX ...  It starts and I am able to manipulate images in it, which is a truly amazing  experience (😍) compared to how I was working previously using convert and manually inspecting the results.

My challenge is attempting to use the workspace changes in batch mode to apply the same operations to via the command line, when I attempt to run nip2 in batch mode I always get the message ```no "main" found```

For my sanity, I attempted to use the [test.ws](https://gist.githubusercontent.com/jcupitt/da7dde6e3a215c145c5d764e32e7e0b8/raw/d652ad4e307e2e80f701a4822c6d789bdb39bfd9/annotate2.ws) and the solution provided in [#996](https://github.com/libvips/libvips/issues/996#issuecomment-396082747)

```
$ nip2 --version
nip2-8.7.1
linked to vips-8.7.4-Fri Jan 18 12:51:47 UTC 2019

$ nip2 -b annotate2.ws --set Workspaces.tab2.A3=\\\"pear\\\" -o x.png
no "main" found
```
Sadly, it yields the same result; no x.png output file is produced...    Any idea what is causing this error or how I can work around it?

**Comment by deftdawg** [comment]
Another test on nip2 8.4.0 on a Ubuntu 18.04 armhf system ...  I observe the following behaviour, however x.png is not created at the end, exit status is 0... 
```
$ nip2 --version
nip2-8.4.0
linked to vips-8.4.5-Wed Jan 18 12:36:44 UTC 2017
$ nip2 -b annotate2.ws --set Workspaces.tab2.A3=\\\"pear\\\" -o x.png && echo ---success---
vips warning: tiff2vips: no resolution information for TIFF image "/home/bananapi/.nip2-8.4.0/tmp/vips-1-K3UPWZ.tif" -- defaulting to 1 pixel per mm
vips warning: tiff2vips: no resolution information for TIFF image "/home/bananapi/.nip2-8.4.0/tmp/vips-2-FCKLWZ.tif" -- defaulting to 1 pixel per mm
vips warning: tiff2vips: no resolution information for TIFF image "/home/bananapi/.nip2-8.4.0/tmp/vips-3-K8THWZ.tif" -- defaulting to 1 pixel per mm
vips warning: tiff2vips: no resolution information for TIFF image "/home/bananapi/.nip2-8.4.0/tmp/vips-3-K8THWZ.tif" -- defaulting to 1 pixel per mm
---success---
```

**Comment by jcupitt** [comment]
Hello @deftdawg,

I'm impressed you got so far! It's very fiddly to get the quoting right for batch mode.

The three (!!!) backslashes is for .bat files on Windows. macOS is slightly less insane, try just:

```
$ nip2 -b annotate2.ws --set Workspaces.tab2.A3=\"pear\" -o x.png
```

ie. only one backslash. 

Explanation: nip2 syntax is `"pear"` for a literal string. But bash will use the `"` as a quote character to mean a single argument, so you add one backslash to get bash to pass the literal `"` down to nip2.

Windows is much, much more complex. It has two different types of `.exe` file: GUI and CLI, with a flag at the start of the binary saying which it is. If you launch a GUI program from the CLI, the Windows shell will not wait for termination, and the prompt will come back immediately. This means you can't use GUI EXEs in scripts. To get around this, you need a separate EXE (mine is called `nip2-cli.exe`) which is tagged as CLI. When this is run, it searches for and launches the GUI EXE, passing along any arguments, connects stdin/stdout/stderr back to the calling shell, and waits for termination before terminating itself and passing the exit status back. You also get an annoying terminal window pop up, but there's nothing you can do about that (I think).

Now you need a backslash to get the `"` through the first layer of the CLI, but you also need a backslash for that backslash to get it through the second layer (where `nip2-cli.exe` launches the real nip2 binary). And you also need a backslash for the quote. So three backslashes, grouped as `\\ \"`.

**Comment by jcupitt** [comment]
Oh, `no main found` means computation failed before it reached `main`, in this case because the extra backslashes were causing a syntax error when nip2 tried to interpret them.

**Comment by deftdawg** [comment]
Ah ok, so on my Linux machine, the quoting is what breaks things... Reducing it to what you described gives me the expected x.png file...  

However on OSX, even without anything needing quoting I get 'no main found' (see 2nd run):
```
$ nip2 -b annotate2.ws --set Workspaces.tab2.A3=\"pear\" -o x.png
no "main" found

$ nip2 -b annotate2.ws -o x.png
no "main" found
```

So I guess I can try building older release of nip2 on OSX, or do you think that is coming from libvips?

**Comment by jcupitt** [comment]
Funny, the default shell on macOS is bash, it should be identical. 

Have you swapped the shell for zsh, perhaps? That has different quoting rules.

**Comment by deftdawg** [comment]
No it's not quoting on the mac, even command line with no quotes, running in zsh results in the same thing on OSX
```
$ zsh
% nip2 -b annotate2.ws -o x.png
no "main" found
```
I'll try to rebuild with the same 8.4 nip2 version ubuntu uses a bit later

**Comment by jcupitt** [comment]
I'll try on my mac.

**Comment by deftdawg** [comment]
Here's is the brew formula I'm using...   You can build with the following command: ```brew install --build-from-source nip2.rb```

Formula:
```
class Nip2 < Formula
  desc "GUI for the VIPS image processing system"
  homepage "https://github.com/jcupitt/nip2"
  url "https://github.com/libvips/nip2/releases/download/v8.7.1/nip2-8.7.1.tar.gz"
  sha256 "3c3e7d4f82e9ee2241b81dff99179cc3234fa5744f008baf1dc545698f20f650"

  bottle do
    cellar :any
    sha256 "e0af078a5d9786c71077ed55dd415e978d144c0ba2016cc61fdea009b62eaa74" => :sierra
    sha256 "2333489eaae68a285287ea418de1445bcd4cc7bdc758b8cbf260f99e25e0d7b0" => :el_capitan
    sha256 "073238e0e5b4d984e66f8eedd3b458d553e16edf047eb6696ae1fd752d68e0a8" => :yosemite
  end

  option "with-test", "Enable build-time testing"
  deprecated_option "with-check" => "with-test"

  depends_on "pkg-config" => :build
#  depends_on "XML::Parser" => :perl
  depends_on "gettext"
  depends_on "glib"
  depends_on "gtk+"
  depends_on "vips"

  depends_on "fftw" => :recommended
  depends_on "gsl" => :recommended
  depends_on "goffice" => :recommended
  depends_on "libgsf" => :recommended

  def install
    args = %W[
      --disable-dependency-tracking
      --prefix=#{prefix}
    ]

    system "./configure", *args
    system "make", "check" if build.with? "check"
    system "make", "install"
  end

  test do
    # when first run, nip2 tries to create ~/Library/nip2-x.y.z
    # to hold temp files ... ~/Library is not present in homebrew's
    # private test home directory
    require "fileutils"
    mkdir_p ENV["HOME"] + "/Library"

    system "#{bin}/nip2", "--benchmark"
  end
end
```

**Comment by deftdawg** [comment]
From experimentation, seems like I get 'no main found' if I feed it a valid or an invalid file name...  so it's not really reading the ws file contents I guess.  

So as alternate test, I'm trying to feed the ws in via ``--stdin-ws``, but that doesn't seem to work on either Linux or OSX, so perhaps I've got the syntax wrong...
```
$ wc -l annotate2.ws
      88 annotate2.ws

$ cat annotate2.ws | nip2 -b --stdin-ws -o x.png

(nip2:2709): GLib-CRITICAL **: 13:47:23.998: g_path_get_dirname: assertion 'file_name != NULL' failed
Segmentation fault: 11
```

**Comment by jcupitt** [comment]
I just tried with your formula here and it works fine. Have you switched to zsh? If you have, try switching back to bash. I like zsh, but sadly everything breaks.

**Comment by deftdawg** [comment]
Hmm...  I mostly run bash, but have tried zsh too, doesn't seem to change anything for me...   commands with no quotes fail the same (on OSX) ruling out the shell, and --stdin-ws doesn't seem to work at all (on OSX or Linux).

Can you run ``nip2 -v; otool -L $(which nip2)`` on your mac?   I'm curious if you have a different libs in your build then I.

**Comment by jcupitt** [comment]
I just have the standard brew stuff, and I built nip2 with your formula. I see:

```
$ nip2 -b annotate2.ws --set Workspaces.tab2.A3=\"pear\" -o x.png
$
```

Making:

![x](https://user-images.githubusercontent.com/580843/52527082-b85aac00-2cba-11e9-952e-47718e7b996b.png)

otool shows:

```
$ otool -L $(which nip2)
/usr/local/bin/nip2:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
	/usr/local/opt/gsl/lib/libgsl.23.dylib (compatibility version 25.0.0, current version 25.0.0)
	/usr/local/opt/gsl/lib/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/libgsf/lib/libgsf-1.114.dylib (compatibility version 115.0.0, current version 115.45.0)
	/usr/local/opt/fftw/lib/libfftw3.3.dylib (compatibility version 9.0.0, current version 9.8.0)
	/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib (compatibility version 5801.0.0, current version 5801.3.0)
	/usr/local/opt/glib/lib/libgthread-2.0.0.dylib (compatibility version 5801.0.0, current version 5801.3.0)
	/usr/local/opt/gtk+/lib/libgtk-quartz-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.32.0)
	/usr/local/opt/gtk+/lib/libgdk-quartz-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.32.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib (compatibility version 4201.0.0, current version 4201.4.0)
	/usr/local/opt/pango/lib/libpango-1.0.0.dylib (compatibility version 4201.0.0, current version 4201.4.0)
	/usr/local/opt/atk/lib/libatk-1.0.0.dylib (compatibility version 23010.0.0, current version 23010.1.0)
	/usr/local/opt/cairo/lib/libcairo.2.dylib (compatibility version 11603.0.0, current version 11603.0.0)
	/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib (compatibility version 3801.0.0, current version 3801.0.0)
	/usr/local/opt/glib/lib/libgio-2.0.0.dylib (compatibility version 5801.0.0, current version 5801.3.0)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.9.0)
	/usr/local/opt/vips/lib/libvips.42.dylib (compatibility version 52.0.0, current version 52.5.0)
	/usr/local/opt/glib/lib/libgobject-2.0.0.dylib (compatibility version 5801.0.0, current version 5801.3.0)
	/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 5801.0.0, current version 5801.3.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by jcupitt** [comment]
I'll close. Please reopen if this is still a problem.
