### ISSUE TITLE
 "xmp-data" is of type VipsBlob, not VipsRefString with 8.8.0-dev

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1229]
With the latest code from master (8.8.0-dev), I get the following error with certain images:

```
$ vips copy xmp-problem.jpg foo.png

VipsImage: field "xmp-data" is of type VipsBlob, not VipsRefString
vips2png: unable to write "foo.png"
```

That worked fine (or at least without error) in 8.7 and before

Image, with which it can be reproduced:
![xmp-problem](https://user-images.githubusercontent.com/47106/52569099-b3a80c00-2e10-11e9-949b-78d67a007d17.jpg)

**Comment by jcupitt** [comment]
Hello @chregu,

Yes, 8.7 used blobs for tiff XMP (libtiff has XMP as bytes + length with no null termination, and XMP can contain embedded null characters), but strings for jpg XMP (always null terminated, no length), it was a bit mixed up. 8.8 tries to use blobs everywhere, for consistency. 

Your example works without error for me:

```
$ vips copy xmp.jpg x.png
$
```

Though now I check `x.png` it seems to have truncated the xmp :( 

```
$ vipsheader -f xmp-data x.png  | base64 -d
http://ns.adobe.com/xap/1.0/
```

I'll have a look.

**Comment by jcupitt** [comment]
It seems to copy XMP back and forth between JPG and PNG now. I'll check some other stuff too and add some more tests.

**Comment by chregu** [comment]
Bleh, stupid me. I was on a totally wrong checkout (jcupitt/libvips instead off libvips/libvips). Works for me now and glad you found a bug nevertheless ;)

**Comment by jcupitt** [comment]
Ah thanks for pointing it out. I'll close.
