### ISSUE TITLE
White streaks in PDF -> JPG conversion

### ISSUE THREAD

**Issue by brandoncc** [libvips/libvips#1230]
Hello,

I have a PDF which is producing white lines through images that are from the PDF when I convert the PDF to JPG with libvips. Is there a setting you could recommend tweaking to attempt to fix this? I have attached an example.

Thanks!

![image 1](https://user-images.githubusercontent.com/543973/52584328-9fe7b000-2de6-11e9-903e-cd9cfe9fabe2.png)

**Comment by jcupitt** [comment]
Hi @brandoncc, could you share the original PDF as well?

**Comment by lovell** [comment]
If this PDF is being rendered via ImageMagick (and not poppler) then https://stackoverflow.com/questions/47666012/why-does-rendering-a-png-from-this-pdf-using-imagemagick-create-these-streaky-ar might be relevant here.

**Comment by brandoncc** [comment]
@lovell I'm rendering with poppler.

**Comment by jcupitt** [comment]
If you try:

```
$ vips copy Cynthia\ \(1\).pdf[n=-1] x.png
```

And have a look at the PNG you'll see that the line spacing varies between photos, even on the same page, and that some photos have horizontal lines and some vertical.

If the lines were all horizontal and all had the same spacing, then it might be caused by libvips progressive generation of PDFs. But this looks like a poppler bug to me.

A simple way to work around it is to render at double size, then shrink down. In Ruby:

```
x = Vips::Image.new_from_file "x.pdf", dpi: 144, access: sequential
x = x.resize 0.5
```

I'll have a go with a different poppler version.

**Comment by jcupitt** [comment]
After the x2 trick:

<img width="268" alt="y" src="https://user-images.githubusercontent.com/580843/52619704-59538d80-2e9a-11e9-8540-bc202e5259f1.png">

You might need x4 to make them vanish completely.

**Comment by jcupitt** [comment]
I tried poppler 0.50 (from 2016), 0.68 and 0.74 and all show this issue. They don't appear if you preview in google-chrome (uses PDFium), but they do appear in firefox and evince.

I'd guess this was a cairo bug, since that's the renderer used by both poppler and firefox.

**Comment by brandoncc** [comment]
Thank you John!

**Comment by brandoncc** [comment]
Hi @jcupitt,

I finally implemented the fix. Here was my old code:

```ruby
# n: is the number of pages to load, -1 means all pages in tall, thin image
dpi = 72
image = Vips::Image.pdfload pdf_file, n: -1, dpi: dpi

# we can get the number of pages and the height of each page from the metadata
n_pages = image.get 'pdf-n_pages'
page_height = image.get 'page-height'

# loop down the image cutting it into an array of separate pages
pages = []
(0 ... n_pages).each do |page_number|

  pages << image.crop(0, page_number * page_height, image.width, page_height)
end

# make a 1-pixel-high black strip to separate each page
strip = Vips::Image.black image.width, 1

# and join the pages again
image = pages[0]
pages[1 .. -1].each do |page|
  image = image.join strip, 'vertical'
  image = image.join page, 'vertical'
end

image.write_to_file image_file_name
```

Here is the code I ended up using for now:

```ruby
dpi = 72
image = Vips::Image.new_from_file pdf_file, page: 0, dpi: dpi * 8, access: :sequential

# we can get the number of pages and the height of each page from the metadata
n_pages = image.get 'pdf-n_pages'
page_height = image.height / n_pages

image = image.resize(1.0 / 8)

# Now that we know how many pages are in the PDF, we can load each. We could
# have used n: -1 to load all pages and then #crop to cut it down, but when
# loading higher than 144 dpi it was very slow to do it that way.
pages = [image]
(1...n_pages).each do |page_number|
  next_page = Vips::Image.new_from_file(pdf_file, page: page_number, dpi: dpi * 8, access: :sequential)
  next_page = next_page.resize(1.0 / 8)
  pages << next_page
end

# make a 1-pixel-high black strip to separate each page
strip = Vips::Image.black image.width, 1

# and join the pages again
image = pages[0]
pages[1 .. -1].each do |page|
  image = image.join strip, 'vertical'
  image = image.join page, 'vertical'
end

image.write_to_file image_file_name
```

I ended up needing to use `* 8` in order to get rid of the streaks completely. The problem with using the resize solution in my old code is that it took a 37-second process at 72dpi and at 288dpi I gave up after waiting 30 minutes for it to process. The file being processed was a 19 page 8"x8" 50mb PDF.

I figured out that loading one page was still very fast though, so I came up with my tweaked version. The problem now is that it is a memory hog. The same PDF now takes 6GB to process, but only 43 seconds.

Do you happen to have any ideas for a middle ground solution between the two?

**Comment by brandoncc** [comment]
I ended up combining libvips with ghostscript. Ghostscript does a beautiful job converting to jpeg, then I load that jpg and do what I need to with vips, getting the win there over processing time and memory consumption in imagemagick.
