### ISSUE TITLE
How vips_text support unicode characters like  (๑S . Y๑) and  (⁎⁍̴̛ᴗ⁍̴̛⁎)

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1231]
It seem different language’s character

**Comment by jcupitt** [comment]
Hello, it should just work. I see:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.text "⁎⁍̴̛ᴗ⁍̴̛⁎", dpi: 300
=> #<Image 129x31 uchar, 1 bands, multiband>
irb(main):003:0> x.write_to_file "x.png"
=> nil
irb(main):004:0> 
```

Making:

![x](https://user-images.githubusercontent.com/580843/52776516-a883f480-3039-11e9-8ba7-aaed5f8c09cb.png)

**Comment by jcupitt** [comment]
(that's a UTF-8 encoded string)

**Comment by tczf1128** [comment]
also (๑S . Y๑) ?

**Comment by jcupitt** [comment]
It won't do colour, but it will render emoji and all unicode characters, as long as your font supports them. You would need to experiment.

```
$ vips text x.png "(๑S . Y๑)" --dpi 300
```

![x](https://user-images.githubusercontent.com/580843/52777150-07963900-303b-11e9-8d54-bd39adafa520.png)

**Comment by tczf1128** [comment]
which version of your vips?

**Comment by jcupitt** [comment]
Just the standard one. What platform are you using? I'm Ubuntu 18.10.

**Comment by tczf1128** [comment]
oh, my version is vips-8.6.4 now. vips 8.7 works well
