### ISSUE TITLE
Is there a way to compress NDPI file into smaller memory footprint?

### ISSUE THREAD

**Issue by panegyrize** [libvips/libvips#1232]
Hi,

I am currently working on a project that needs to compress NDPI files into smaller files to save memory space (format can be changed though). The first try is to compress the NDPI file with compression method as JPEG and a smaller quality level. Can vips achieve this?

Also, I would like to know why there isn't a way to output NDPI file. Is it because it is proprietary? 

Thanks.

**Comment by jcupitt** [comment]
Hello, ndpi uses jpeg200 internally, so I think using jpg compression would probably make the file bigger, unless you turned the quality down. You could try as tiled tiff with jpg Q 50.

libvips is able to open ndpi files thanks to openslide. It supports read, but not write. As you say, the format is proprietary.

There's a libvips branch which can load and save HEIF files. These can be quite a bit smaller than JPG. Unfortunately, it does not support tiled (grid) HEIF, so I don't think it would work for slide files.

**Comment by jcupitt** [comment]
I tried:

```
$ vips copy bild.ndpi x.tif[tile,compression=jpeg,Q=50]
$ ls -l bild.ndpi x.tif 
-rw-r--r-- 1 john john 2167418089 May  7  2015 bild.ndpi
-rw-r--r-- 1 john john  598391256 Feb 14 09:27 x.tif
```

You may find the quality loss unacceptable. You would need to experiment.

**Comment by panegyrize** [comment]
Hi John,

Thanks for the quick reply. Appreciate it.

I did not know NDPI uses j2k, which should beat JPEG on compression ratio. So literally speaking, this is not a feasible task.

The command you tried only outputs the level 0 image, which is also the highest resolution, is that correct? Can vips output the whole levels?

**Comment by jcupitt** [comment]
Yes, try:

```
vips copy bild.ndpi x.tif[compression=jpeg,Q=50,tile,pyramid]
```

You can see all the tiffsave options here:

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

It'll make the file ~30% larger, of course.

**Comment by panegyrize** [comment]
That works. Thanks!
