### ISSUE TITLE
Can i convert images to jpeg 2000 and jpeg xr ?

### ISSUE THREAD

**Issue by ericfelipe99** [libvips/libvips#1233]
Hi, 

Can i convert image files to jpeg 2000 and jpeg xr? 
i'm using the .net libvips

**Comment by jcupitt** [comment]
Hello @ericfelipe99, 

libvips has no direct support for those two formats, but it can save via imagemagick. If your IM has been configured with jp2k support you can write something like:

```C#
image.magicksave("somefilename", format = "J2K")
```
