### ISSUE TITLE
How to tile text watermark on an image by vips?

### ISSUE THREAD

**Issue by tczf1128** [libvips/libvips#1237]

**Comment by tczf1128** [comment]
like this [https://i.stack.imgur.com/vu9QO.jpg](url)

**Comment by tczf1128** [comment]
like this
https://i.stack.imgur.com/vu9QO.jpg

**Comment by jcupitt** [comment]
Hello, there's an example in ruby-vips:

https://github.com/libvips/ruby-vips/blob/master/example/watermark.rb

Use it like this:

```
$ ./watermark.rb ~/pics/cramps.png x.png Hello
```

To make:

![x](https://user-images.githubusercontent.com/580843/53232793-cf6aa800-3683-11e9-8e9d-b7c3090fcd28.png)

**Comment by tczf1128** [comment]
thanks. any c example? I'm not familiar with ruby

**Comment by jcupitt** [comment]
It's the same API, so you can just change the syntax, I think.

**Comment by kleisauke** [comment]
See https://github.com/libvips/php-vips/issues/78#issuecomment-415333685 for a PHP example that uses the `composite` operator.

**Comment by jcupitt** [comment]
Oh yeah, I'd forgotten about that php version, thanks Kleis. 

I'll update the ruby one to use composite as well.

**Comment by jcupitt** [comment]
I updated the ruby example. I'll close.
