### ISSUE TITLE
Q: Strange gamma (?) problem with an image

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1238]
I found this image on the internet, which produces "wrong" results when processed with vips.

The image, it reports a gamma of 1: 
![vision](https://user-images.githubusercontent.com/47106/53233163-fed1e280-368c-11e9-8db7-40affab383ef.png)

when I do 
```
vips copy strangegamma.png out.png[profile=path/to/srgb.icm]
```
or
```
vipsthumbnail strangegamma.png   --eprofile=path/to/srgb.icm -o out.png -s 500x500
```
It shows up way too dark (also without the profile setting), like this:
![out](https://user-images.githubusercontent.com/47106/53233380-8fa8be00-368d-11e9-9725-e0d40940dc0b.png)

If I do 
```
 vips gamma --exponent=2.2 out.png[profile=path/to/srgb.icm]
```
on the other hand, it shows up correctly.

Is there something wrong with vips or how can I detect, if an image needs gamma correction (with some scripting)? 

And by the way, thanks for the improved profile operations in 8.8, will save me some headaches. And also the heif support will come handy (so I don't need to fall back to imagemagick for that anymore)

**Comment by jcupitt** [comment]
Hello @chregu,

Yes, your PNG has a gamma of 1, as you say. libvips does not support the gamma tag, so it gets turned into an sRGB (gamma 2.4-ish) by vipsthumbnail.

I've never seen a gamma 1 PNG before. Do you think this is a serious problem? I'd hoped it was part of the PNG spec I could ignore!

**Comment by chregu** [comment]
It was also the first time I saw such a png.  And Photoshop doesn’t seem to process it correctly, either. So not sure how big of a deal it is. 

But there’s no possibility in vips to get the value of that tag right now? So I could apply the gamma correction by myself? 

It’s definitely just a nive-to-have for me.

**Comment by jcupitt** [comment]
No, libvips ignores all the gamma controls in libpng. It's ancient legacy stuff from before sRGB when (for example) macs used 1.8 and PCs used 2.2. It might have been useful in 1992, but I don't think it's worth supporting now.

It would be quite a lot of work to support all the gamma API. You can have different gammas for the background, for the alpha, and for each of the image channels, in 8 and 16-bit mode, and they need to interact in defined ways. Yuk!

**Comment by chregu** [comment]
I can live with that. Good to know what the issue is, anyway. I close.
