### ISSUE TITLE
Rotation: preservation of distribution of pixel values?

### ISSUE THREAD

**Issue by s-sajid-ali** [libvips/libvips#1239]
In [this notebook](https://colab.research.google.com/drive/1d73jZamicKar5d8D47tOC5cDSFz72Zt_#scrollTo=PHacYa4QWUFK), I have created a simple 2D test object and stacked it in 3D. The 2D object is a rectangle and the value of the each pixel is either 1 or 0. 

Now, I rotate this object by 5 degrees using both skimage and pyvips. Both preserve the sum of pixels but for some reason when I plot the histogram of the output image pixel values around 1, I see that the pyvips rotated version has many places where the pixel value exceeds 1. How does this happen ?

**Comment by jcupitt** [comment]
Hello @s-sajid-ali,

I tried this small program:

```python
#!/usr/bin/python3

import pyvips

image = pyvips.Image.black(100, 100).cast("float")
image = image.draw_rect(1, 10, 10, 50, 50)

for theta in range(360):
    rot = image.rotate(theta)
    if rot.max() > 1.0:
        print("image.min() =", image.min())
        print("image.max() =", image.max())
```

And it runs cleanly for me with git master libvips. I'll try some older versions.

**Comment by s-sajid-ali** [comment]
Is rotate a new feature in the master branch ? 

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-4-9e0dde72759a> in <module>()
      1 for theta in range(360):
----> 2     rot = image.rotate(theta)
      3     if rot.max() > 1.0:
      4         print("image.min() =", image.min())
      5         print("image.max() =", image.max())

~/packages/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.5.4-cn4y5gakwtozuu6thdozzmdekeo36qdg/envs/intelpy3/lib/python3.6/site-packages/pyvips/vimage.py in call_function(*args, **kwargs)
    802         @_add_doc(name)
    803         def call_function(*args, **kwargs):
--> 804             return pyvips.Operation.call(name, self, *args, **kwargs)
    805 
    806         return call_function

~/packages/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.5.4-cn4y5gakwtozuu6thdozzmdekeo36qdg/envs/intelpy3/lib/python3.6/site-packages/pyvips/voperation.py in call(operation_name, *args, **kwargs)
    130         logger.debug('VipsOperation.call: string_options = %s', string_options)
    131 
--> 132         op = Operation.new_from_name(operation_name)
    133 
    134         arguments = op.get_args()

~/packages/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.5.4-cn4y5gakwtozuu6thdozzmdekeo36qdg/envs/intelpy3/lib/python3.6/site-packages/pyvips/voperation.py in new_from_name(operation_name)
     58         vop = vips_lib.vips_operation_new(_to_bytes(operation_name))
     59         if vop == ffi.NULL:
---> 60             raise Error('no such operation {0}'.format(operation_name))
     61         return Operation(vop)
     62 

Error: no such operation rotate
  VipsOperation: class "rotate" not found
```

**Comment by jcupitt** [comment]
`rotate` was added in 8.7, I guess you're on an older version. 

You can also write: 

```python
  image = image.similarity(angle=theta)
```

If that's any easier.

I just noticed you have:

```python
    inter = pyvips.vinterpolate.Interpolate.new('bicubic')
```

libvips bicubic is just catmull-rom, so you will get slight ringing on edges. Use bilinear if you need a purely interpolatory function.

**Comment by jcupitt** [comment]
Oh duh, sorry, this program fails:

```python
#!/usr/bin/python3

import pyvips

image = pyvips.Image.black(100, 100).cast("double")
image = image.draw_rect(1, 20, 20, 5000, 5000, fill=True)

print("before rotate:")
print("image.min = ", image.min())
print("image.max = ", image.max())

rot = image.rotate(5)

print("after rot(5):")
print("image.min = ", rot.min())
print("image.max = ", rot.max())

interp = pyvips.Interpolate.new("bicubic")
rot = image.rotate(5, interpolate=interp)

print("after rot(5, interpolate=\"bicubic\"):")
print("image.min = ", rot.min())
print("image.max = ", rot.max())
```

I see:

```
john@kiwi:~/try$ ./rot.py 
before rotate:
image.min =  0.0
image.max =  1.0
after rot(5):
image.min =  0.0
image.max =  1.000000063329935
after rot(5, interpolate="bicubic"):
image.min =  -0.0792329541829313
image.max =  1.109202971103965
```

I agree, the bilinear one (the first) should be <= 1.0. I'll have a look.

**Comment by jcupitt** [comment]
It was a lack of precision in the coefficient calculation. I swapped float for double and it seems to work now.

I see:

```
john@kiwi:~/try$ ./rot.py 
before rotate:
image.min =  0.0
image.max =  1.0
after rot(5):
image.min =  0.0
image.max =  1.0
after rot(5, interpolate="bicubic"):
image.min =  -0.0792329541829313
image.max =  1.109202971103965
```

I'll see if the other interpolators need a similar change,

**Comment by s-sajid-ali** [comment]
@jcupitt : Thanks for the fix !  I'll use bilinear instead then. Would this be released a new version or would I have to build from source ? 

Also, does libvips/pyvips have a function that allows one to rotate an anisotropic image ? 
i.e. the case when ||x|| and ||y|| are not the same, meaning that the pixel distance along the two axes are not the same.

**Comment by jcupitt** [comment]
You'd need to build libvips from git master, sorry. The fix will be in libvips 8.8, due in a few weeks (hopefully). It's easy to build on *nix, but a bit harder on Windows.

Yes, you'd need to call `affine` yourself for skews and suchlike.

**Comment by jcupitt** [comment]
The `rotate` docs, fwiw. 

https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-rotate

**Comment by s-sajid-ali** [comment]
Is this an Autotools based package ? 
Is gtk-doc essential to the build ?
I use [spack](https://github.com/spack/spack) to build all the packages I need. I've made a first attempt at installing libvips [here](https://github.com/s-sajid-ali/spack/commit/9021bd02904cd80fde3077736cad01e8544d3dda). Does this look right ?

**Comment by jcupitt** [comment]
If you are building from a tarball, you don't need gtk-doc or swig, they get baked in by autotools. You will need things like glib, expat, jpeg-dev etc etc.

There are some dockerfiles here:

https://github.com/jcupitt/docker-builds

Eg. this one might be useful:

https://github.com/jcupitt/docker-builds/tree/master/pyvips-alpine

**Comment by jcupitt** [comment]
Oh, you don't need gobject-introspection either. 

libvips `configure` produces a summary at the end showing what features are enabled, keep adding stuff until you see `yes` in all the places you want.

I guess you'll want to build git master? You will need gtk-doc to build from git. I'll make a Dockerfile for you.

**Comment by jcupitt** [comment]
This one builds git master libvips plus pyvips on Alpine:

https://github.com/jcupitt/docker-builds/tree/master/pyvips-libvipsmaster-alpine

**Comment by jcupitt** [comment]
I'll close since this is merged to master now. Thanks!

**Comment by s-sajid-ali** [comment]
Thanks for the fix!
