### ISSUE TITLE
openslide2vips: reading region: Not a JPEG file: starts with 0xff 0x11

### ISSUE THREAD

**Issue by renexu** [libvips/libvips#1243]
I was trying to create the thumbnail from a Aperio svs file at level 1

vipsheader gives  
```
test.svs: 123504x91133 uchar, 4 bands, rgb, openslideload
```

vipsthumbnail  gives bunch of errors like
```
(vipsthumbnail:28273): VIPS-WARNING **: 13:51:06.229: error in tile 27840 x 0
...
openslide2vips: reading region: Not a JPEG file: starts with 0xff 0x11
...
```

looks like this is related to an openslide issue https://github.com/openslide/openslide/pull/211

not sure if this is something can be fixed in vips, if not is there a way I can force to use another loader like tiffload in vipsthumbnail and in pyvips.

Thanks

**Comment by jcupitt** [comment]
Sounds like openslide needs that fix. I don't think there's much libvips can do to help -- SVS files are not regular TIFFs, they just use some of the container features.

git master libvips does support fast thumbnailing of openslide images:

```
john@kiwi:~/pics/openslide$ vipsheader 50310.svs 
50310.svs: 61451x61228 uchar, 4 bands, rgb, openslideload
john@kiwi:~/pics/openslide$ time vipsthumbnail 50310.svs 

real	0m1.095s
user	0m1.071s
sys	0m0.025s
```

So it ought to be easy once openslide gets that patch.

**Comment by renexu** [comment]
Sadly, looks like no one is actually maintaining the openslide lib anymore. The last openslide release was almost 4 yrs ago...

**Comment by jcupitt** [comment]
bgilbert wrote openslide, then left CMU to work for redhat. He's been doing some support in his spare time, but really CMU should assign someone to clear the issues and put out a new version. There are quite a few useful improvements stuck in limbo.

Perhaps a commercial sponsor could help? I know quite a few companies have been using openslide, maybe one of them could contribute a few months of an engineer's time? 

This is probably a discussion for the openslide mailing list.

**Comment by renexu** [comment]
looks like there is nothing we can do at this point, close this
