### ISSUE TITLE
crash with some HEIC files

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1247]
This test image crashes with git master libvips and git master libheif

https://trac.ffmpeg.org/attachment/ticket/6521/IMG_4479.HEIC

See https://github.com/libvips/libvips/issues/671#issuecomment-469146624

**Comment by leslie-wang** [comment]
Just for your information. The same build at Raspberry PI works, no crash. Please let me know if you need any more information. 
```
$ vipsthumbnail ~/IMG_4479.HEIC --vips-info
VIPS-INFO: thumbnailing /home/pi/IMG_4479.HEIC
VIPS-INFO: selected loader is VipsForeignLoadHeifFile
VIPS-INFO: input size is 3024 x 4032
VIPS-INFO: pre-shrunk size is 240 x 320
VIPS-INFO: converting to processing space srgb
VIPS-INFO: residual reducev by 0.4
VIPS-INFO: reducev: 16 point mask
VIPS-INFO: reducev sequential line cache
VIPS-INFO: residual reduceh by 0.4
VIPS-INFO: reduceh: 16 point mask
VIPS-INFO: thumbnailing /home/pi/IMG_4479.HEIC as /home/pi/tn_IMG_4479.jpg
memory: high-water mark 1.05 MB
$ vipsthumbnail --vips-version
libvips 8.8.0-Sun Mar  3 15:45:41 UTC 2019
memory: high-water mark 0 bytes```

**Comment by jcupitt** [comment]
I think I've fixed it, but I've had to remove `autorotate` :( Perhaps it doesn't matter.

```
 * This is very hard to support properly with libheif. There's a thing to
 * disable autorot on decode, but the dimensions you get from querying the
 * image handle sometimes do and sometimes don't apply this rotation for you,
 * depending on the image. And the only way to discover if an image has an
 * orientation is to query the exif, which is not reliable.
 *
 * Perhaps we'll be able to support this in a future libheif.
```

**Comment by jcupitt** [comment]
Branch with the fix:

https://github.com/libvips/libvips/tree/fix-heif-autorotate

Now merged to master.

Thanks for reporting this, @leslie-wang !

**Comment by leslie-wang** [comment]
Thanks for quick fixing. I think it should be ok to remove autorotate as long as EXIF orientation data is preserved.

**Comment by jcupitt** [comment]
Actually, it's the other way around: at the moment, libheif will not let you disable autorotate.

I'll see if I can put an example together and open an issue.

**Comment by jcupitt** [comment]
It looks like libheif master has just added the function we need:

https://github.com/strukturag/libheif/issues/106#issuecomment-459766087

We can add an `autorotate` flag when this filters into a release version.

I opened an issue as well here:

https://github.com/strukturag/libheif/issues/117
