### ISSUE TITLE
Segfault in vips_image_write_to_buffer

### ISSUE THREAD

**Issue by dbouron** [libvips/libvips#1248]
Hello,

I have a segfault when trying to write image into a buffer. The function g_mutex_lock seems to be the root of the crash:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa1a1612735, pid=75, tid=0x00007fa19d882700
#
# JRE version: OpenJDK Runtime Environment (8.0_161-b14) (build 1.8.0_161-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.161-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libglib-2.0.so.0+0x8e735]  g_mutex_lock+0x5
```
```
Current thread (0x00007fa1f8181a80):  JavaThread "ImageProcessingFuturePool-10" daemon [_thread_in_native, id=401, stack(0x00007fa19d782000,0x00007fa19d883000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000040
```
It happens with memory cache and without.
Also, I have the same problem if I set concurrency to 1 thread.
The last warnings I had before crash are:
```
(java:75): VIPS-WARNING **: profile 'icc': 'GRAY': Gray color space not permitted on RGB PNG
```
or
```
(java:75): VIPS-WARNING **: profile 'icc': 0h: PCS illuminant is not D50
```
But, I don't know if it's correlated or not. Any ideas?

**Comment by jcupitt** [comment]
Hello @dbouron,

There are quite a few tests for writing to a buffer in the test suite, so it's probably more complex. I'd guess a bug related to the profile warnings (as you said).

I tried at the command-line:

```
$ vips pngsave_buffer mono.png --profile /usr/share/color/icc/colord/sRGB.icc
(vips:8499): VIPS-WARNING **: 14:42:36.648: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
vips2png: unable to write to buffer
```

And didn't get a crash. Can you make a test case?

**Comment by dbouron** [comment]
Unfortunately, I haven't the image where embedded profile produces this warning.
It is difficult to retrieve the image which has been processed just before the crash on our app.

When I strip the metadata when writing a png, this warning should not happened, right?

**Comment by jcupitt** [comment]
That'll stop the warning, but it shouldn't crash -- with 8.7 at least libpng will warn and then ignore the incompatible profile. I think it can vary with libpng version.

git master libvips will automatically and silently drop incompatible profiles for you.

Is your java binding perhaps ignoring the error return from `pngsave_buffer`?

**Comment by dbouron** [comment]
No, I check the status code returned by vips_image_write_to_buffer and I throw a new exception which is caught in java code.
Here are the version of my dependencies:

```shell
JPG_VERSION=1.4.2
PNG_VERSION=1.6.23
GLIB_VERSION=2.56.1
GIF_VERSION=5.1.4
WEBP_VERSION=1.0.0
ORC_VERSION=0.4.28
VIPS_VERSION=8.7.0
```

**Comment by jcupitt** [comment]
I'm libpng 1.6.34, so you could try that. I would consider updating to libvips 8.7.4 as well (there's a useful security fix).

**Comment by dbouron** [comment]
Ok, I will try and let you know

**Comment by dbouron** [comment]
Hi, the upgrade of these libraries didn't fixed the segfault. I will continue the investigation

**Comment by jcupitt** [comment]
Oh, shame. Let me know if you find a test case.

**Comment by dbouron** [comment]
Hi @jcupitt,

I found an image which produces a segfault when trying to write image into a buffer:

![olin](https://user-images.githubusercontent.com/21236440/54686008-87229680-4b18-11e9-9f54-81db8ce13d63.png)

Basically, this image is corrupted. Both identify or exiv2 complain when trying to extract metadata.
After some investigations, I see two potential problems:

- In function vips_foreign_save_png_buffer_build() (foreign/pgnsave.c), obuf and blob aren't initialized and when vips__png_write_buf() fails, their value maybe different to NULL.
Then in vips_image_write_to_buffer() (foreign/pngsave.c), the `if( blob )` condition is true, you jump into the then statement and make a memory access violation.

-  In vips_image_write_to_buffer() (foreign/pngsave.c), you don't check `result` value before reading/writing on pointers passed in parameters. `if( result == 0 && blob )` should be enough to avoid this case.

**Comment by jcupitt** [comment]
Oh no! You're right, there was a problem in vips_image_write_to_buffer() with corrupt or damaged images. I think I've fixed the segv.

I'm still not quite sure why png write is failing, I'll keep looking.

**Comment by jcupitt** [comment]
... and thank you very much for tracking this dumbness down.

**Comment by jcupitt** [comment]
I added a` png_set_interlace_handling()` for recent libpngs and I now just see:

```
$ vips copy broken-comb.png x.v
(vips:10337): VIPS-WARNING **: 21:49:00.471: bad adaptive filter value
```

So it's probably working now, or as well as it can.

**Comment by dbouron** [comment]
Your last commits seem to fix the bug.
I am making more tests to confirm that and let you know.

**Comment by dbouron** [comment]
@jcupitt, do you think it is possible to make an release of vips-8.8.0-rc1?

**Comment by jcupitt** [comment]
OK, thanks for letting me know!
