### ISSUE TITLE
Remove thumbnail EXIF tags for thumbnail function

### ISSUE THREAD

**Issue by leslie-wang** [libvips/libvips#1249]
I really like the feature vips preserves EXIF metadata when generating thumbnail image. It is very considerable and useful. But I'm not sure if it is worth keeping original tag of thumbnail EXIF binary data. The purpose of thumbnail is to occupy less space. Seems like sometimes original thumbnail tag is larger than generated thumbnail.

For example, I try to generate 75x75 thumbnail, but original thumbnail in EXIF tag is 160x120. So total size is `20552 Byte` for new 75x75 thumbnail. After removing the tag, new file size is `9054 Byte` while still preserving other useful EXIF data.

Or one option can be provided to let user decide to preserve or remove it.

**Comment by jcupitt** [comment]
Hello @leslie-wang, you can remove it yourself with something like:

```ruby
x = Vips::thumbnail "somefile.y", 75
x = x.remove "jpeg-thumbnail-data"
x.write_to_file "my-thumbnail.jpg"
```

It's often useful to remove XMP as well -- it can be huge.

**Comment by leslie-wang** [comment]
Thanks for the tip. It works. Wonderful!!! I'll close it.

**Comment by leslie-wang** [comment]
Besides normal thumbnail, I saw some phones also have `Photoshop Thumbnail`. Which name can I use to remove it too?
```
$ exiftool 5.jpg | grep -i thumbnail
Photoshop Thumbnail             : (Binary data 6871 bytes, use -b option to extract)
Thumbnail Offset                : 9308
Thumbnail Length                : 6871
Thumbnail Image                 : (Binary data 6871 bytes, use -b option to extract)
```

**Comment by leslie-wang** [comment]
Also, seems like some photos have other binary data which I want to remove in thumbnail image. Are there any name I can use to do that? Thanks
```
Red Tone Reproduction Curve     : (Binary data 2060 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 2060 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 2060 bytes, use -b option to extract)
```

**Comment by jcupitt** [comment]
Use `vipsheader -a myfile.jpg` to see all the metadata libvips has for an image. You can remove any fields you don't like.

**Comment by leslie-wang** [comment]
cool! this is exactly what I'm looking for. Thanks for the great project!

**Comment by jcupitt** [comment]
There's a chapter in the docs with some other thumbnailing tips, you probably saw:

https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html

**Comment by leslie-wang** [comment]
Appreciated the sharing. It is very useful.

After reading, I got other question, and will create one new issue for that.
