### ISSUE TITLE
Vips copy to create just 1:1 copy without processing

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1250]
If I use vips copy either in cmdline or python or c, it takes more time when compared to cp command, infact same time it takes for affine or similarity 

How to use it in c so that it just copy source to target. Or I have to stick with system calls.
Or will vips system will be better.

**Comment by jcupitt** [comment]
Hello @vkkindia, the libvips `copy` operation will decompress and recompress images, so it will be much slower than `cp`. I would just use `system("cp x y")`.

GIO is probably the best library if you need something more complex:

https://developer.gnome.org/gio/stable/
