### ISSUE TITLE
Is current thumbnail generation algorithm fastest?

### ISSUE THREAD

**Issue by leslie-wang** [libvips/libvips#1252]
From https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html, 
```
Shrinking images involves combining many pixels into one. Arithmetic averaging really ought to be in terms of the number of photons, but (for historical reasons) the values stored in image files are usually related to the voltage that should be applied to the electron gun in a CRT display.
``` 
Sometimes, as a user, I just need generation as fast as possible because quality is not that important. So is it possible to have an option like `--fastest` which uses `nearest neighbor` like algorithm, without much arithmetic averaging calculation. 

If you think current one is already the fastest, that would be wonderful.

**Comment by jcupitt** [comment]
Yes, the default algorithm is about as fast as you can get, I think, though of course I'd love to be proved wrong. pillow-simd is quicker for the actual shrink (they have a lot of hand-written AVX for the convolution), but vipsthumbnail should be faster end-to-end, especially if you are doing things like colour management too.

The `--linear` flag is more correct, but can have a huge speed penalty (perhaps 10x slower) for what is often only a small improvement.

**Comment by leslie-wang** [comment]
Thanks for answering the question. That is all I want to know!
