### ISSUE TITLE
Multi channel tiled + Pyramidal tiff 

### ISSUE THREAD

**Issue by ajay1685** [libvips/libvips#1253]
I have successfully used VIPS binaries to convert a large TIFF (RGB) to tiled pyramidal tiff. It is really fast and very useful. I am dealing with 7 channel 16-bit image planes, is there a way to use VIPS bianaries to compile  ome-tiff with multichannel tiled + pyramid OME-TIFF. 

Pyramid write support was introduced in OME.TIF files from bioformat 6.0.0, I am looking to accomplish similar to what the closed source format .qptiff does.

It would be great if we can use VIPS fast processing power to handle these very large image datasets. 

Here is link to another community where this functionality will benefit:
[https://groups.google.com/forum/#!topic/qupath-users/wU6FmvuCKmM](https://groups.google.com/forum/#!topic/qupath-users/wU6FmvuCKmM)

**Comment by jcupitt** [comment]
Hello @ajay1685,

Could you explain what you want to generate? libvips should be fine with a seven channel 16-bit tiff, it should just work.

libvips represents OME-TIFF as "toilet roll" images, ie. a very tall, thin strip of slices. You might need to chop up the strip and join them up as channels (instead of Z) before pyramiding.

**Comment by ajay1685** [comment]
Sorry for a confusing post.
I have a fluorescnet slide scan of tissue in 7 different 16-bit channel (35134x31358x7). I want to create an overlay image such as in .qptiff ([sample file link](https://downloads.openmicroscopy.org/images/Vectra-QPTIFF/perkinelmer/PKI_scans/LuCa-7color_Scan1.qptiff)) which can be loaded in [QuPath](https://qupath.github.io/) or [ImageScope](https://www.leicabiosystems.com/digital-pathology/manage/aperio-imagescope/)  with resolution and magnification info

The whole slide image processing software packages such as Aperio ImageScope, PhenoChart and QuPath relies on spatial resolution (microns per pixel) and magnification values, I guess OME-TIFF has this metadata in the right places, I could use bfconvert to produce a 7 channel 16-bit tiff with spatial reslution information but I have not found a way to do this using VIPS. bfconvert takes a few hours, while VIPS can do it in few seconds, if I knew how.

**Comment by jcupitt** [comment]
Oh dear, I’m still confused. Could you post a sample source image in
OMETIFF and a description of the pyramid you want to make?

Do you want to make seven separate pyramids, or one pyramid with seven
channels?

**Comment by ajay1685** [comment]
I have seven individual 16-bit Images (monochrome) in RAW Tiff format (35K x 32K pixel).

I want one ome.tiff file with multiple channels.  I want the resulting ome.tif to be a multi channel and tiled (and pyramid if possible).

I am not entirely sure about the Pyramid part, I know the image is tiled and has multiple channels.

**Comment by ajay1685** [comment]
I was doing it like this:
vips bandjoin "img_ch00.tif img_ch01.tif img_ch02.tif img_ch03.tif img_ch04.tif img_ch05.tif img_ch06.tif" final.ome.tif --tile --tile-height=256 --tile-width=256 --pyramid --vips-progress

When I run vipsheader final.ome..tif , I get 7 band sRGB image , shouldn't the out read monochrome ?

**Comment by jcupitt** [comment]
Ah, I think I understand. 

OME-TIFF images have each of your seven channels as separate pages -- so you need to make a seven page image, with each page as a huge 16-bit mono image.  

TIFF pyramids use pages for the pyramid layers, so you need to convert to a single, seven channel image, then form a pyramid from that.

To form a pyramid from your seven TIFFs, try this:

```
john@kiwi:~/pics/ome/demo$ ls
0.tif  1.tif  2.tif  3.tif  4.tif  5.tif  6.tif  x.tif
john@kiwi:~/pics/ome/demo$ rm x.tif 
john@kiwi:~/pics/ome/demo$ ls
0.tif  1.tif  2.tif  3.tif  4.tif  5.tif  6.tif
john@kiwi:~/pics/ome/demo$ vipsheader *.tif
0.tif: 1450x2048 uchar, 1 band, b-w, tiffload
1.tif: 1450x2048 uchar, 1 band, b-w, tiffload
2.tif: 1450x2048 uchar, 1 band, b-w, tiffload
3.tif: 1450x2048 uchar, 1 band, b-w, tiffload
4.tif: 1450x2048 uchar, 1 band, b-w, tiffload
5.tif: 1450x2048 uchar, 1 band, b-w, tiffload
6.tif: 1450x2048 uchar, 1 band, b-w, tiffload
john@kiwi:~/pics/ome/demo$ vips bandjoin "$(echo *.tif)" x.tif[tile,pyramid] 
john@kiwi:~/pics/ome/demo$ vipsheader x.tif
x.tif: 1450x2048 uchar, 7 bands, srgb, tiffload
john@kiwi:~/pics/ome/demo$ tiffinfo x.tif 
TIFF Directory at offset 0x1500008 (22020104)
  Image Width: 1450 Image Length: 2048
  Tile Width: 128 Tile Length: 128
  Resolution: 28.35, 28.35 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 4<unassoc-alpha, unassoc-alpha, unassoc-alpha, unassoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 7
  Planar Configuration: single image plane
... etc.
```

It's a seven channel RGB image, with the extra 4 channels as unassoc-alpha, which I think is correct.

You can form an OME-TIFF from your seven images as well, but it's a little harder. You need to join them top-to-bottom, then set the page-height, then save as TIFF. You can do it in one step from python / ruby / etc., but you'd need to make a temp file if you want to use the command line.

**Comment by ajay1685** [comment]
John,
Thank you for the details. I think that's how I used the vips_bandjoin and I did get the same info with vipsheader (7 bands sRGB, tiffload). Unfortunately neither QuPath nor ImageScope is able to load these 7 channel tif files generated by vips_bandJoin.

I only have very basic information about these image formats, I am sorry if my questions do not make sense. Here is some info i gathered so far.

QuPath uses bioformat image server to read 7 channel ome.tif. I don't think QuPath supports 16-bit generic tif. Writing pyramid was only introduced recently to bioformat ome.tif (in latest release v6.0.0)

It seems ome.Tif is the only viable format for me at the moment since,  *.qptiff is closed source and QuPath doesn't support generic 16-bit multiple channel tiffs.

With Ome.tif , the multiple images can be identified as "channels" with appropriate channel names, micron per pixel value, and magnification values.

Here is and example file: [LuCa-7color_Scan1.ome.tiff](https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/sub-resolutions/Fluorescence/LuCa-7color_Scan1.ome.tiff)
On this Bioformat Page:[https://docs.openmicroscopy.org/ome-model/6.0.0/ome-tiff/data.html]( https://docs.openmicroscopy.org/ome-model/6.0.0/ome-tiff/data.html)

Also here are examples of the 32-bit Tiff files with multiple channels, I dont know much about these 32-bit tif files with 7/8 channels. But these are also compatible with QuPath:
[https://downloads.openmicroscopy.org/images/Vectra-QPTIFF/perkinelmer/PKI_fields/](https://downloads.openmicroscopy.org/images/Vectra-QPTIFF/perkinelmer/PKI_fields/)

I think the ImageScope uses perkinelmer closed source code to read 7 channel .qptiff, I haven't tried opening ome.tif with ImageScope.

Can I use vips to make ome.tiff , such as in example LuCa-7color_Scan1.ome.tiff.

**Comment by jcupitt** [comment]
Yes, OME TIFF uses separate pages for each channel, so in libvips you just join your images up as pages, then save.

Are you OK with python / ruby etc., or you you want to use the command line? If you can only use the command-line, you have to do it in three stages with a large temp file.

**Comment by jcupitt** [comment]
In Ruby (for example) you could write:

```ruby
#!/usr/bin/ruby

require 'vips'

images = ARGV.map {|filename| Vips::Image.new_from_file filename, access: :sequential}

out = Vips::Image.arrayjoin images, across: 1

out.set_type GObject::GINT_TYPE, "page-height", images[0].height

puts "writing x.tif .."
out.write_to_file("x.tif")
```

Then:

```
john@kiwi:~/pics/ome/demo$ ls
0.tif  1.tif  2.tif  3.tif  4.tif  5.tif  6.tif  ome.rb
john@kiwi:~/pics/ome/demo$ vipsheader *.tif
0.tif: 1450x2048 uchar, 1 band, b-w, tiffload
1.tif: 1450x2048 uchar, 1 band, b-w, tiffload
2.tif: 1450x2048 uchar, 1 band, b-w, tiffload
3.tif: 1450x2048 uchar, 1 band, b-w, tiffload
4.tif: 1450x2048 uchar, 1 band, b-w, tiffload
5.tif: 1450x2048 uchar, 1 band, b-w, tiffload
6.tif: 1450x2048 uchar, 1 band, b-w, tiffload
john@kiwi:~/pics/ome/demo$ ./ome.rb *.tif
writing x.tif ..
john@kiwi:~/pics/ome/demo$ tiffinfo x.tif
TIFF Directory at offset 0x2d5008 (2969608)
  Image Width: 1450 Image Length: 2048
  Resolution: 28.35, 28.35 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 128
  Planar Configuration: single image plane
TIFF Directory at offset 0x5aa152 (5939538)
  Image Width: 1450 Image Length: 2048
  Resolution: 28.35, 28.35 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 128
...etc.
```

ie. it creates a seven page TIFF, which should (I think?) load into any OME-TIFF program.

**Comment by ajay1685** [comment]
I will setup python with libvips and try to write a script. I don't have experience with python. I have a few years of basic data manipulation, analysis and visualization experience in Matlab so I am optimistic that I can pull it off. 

I will report back,  thank you for taking time to explain and provide solution. Libvips is very fast and memory efficient with large files from my experience with a few tools on command line.

**Comment by jcupitt** [comment]
In py it would be:

```python
#!/usr/bin/python3

import sys
import pyvips

images = [pyvips.Image.new_from_file(filename, access="sequential") for filename in sys.argv[1:]]
out = pyvips.Image.arrayjoin(images, across=1)
out.set_type(pyvips.GValue.gint_type, "page-height", images[0].height)
print("writing x.tif ...")
out.write_to_file("x.tif")
```

**Comment by ajay1685** [comment]
Thank you for the python script, It generates TIFF file which I could open using imageJ. I am looking through vips API to see if I can tile each channel (256x256) in the resulting TIFF.

1. Vipsheader only reports 1 band, b-w (is this normal ?).
2. Is it possible to get each plane recognized as channels instead of time points (see the bioformat showinf results)


Here is the bioformat showinf results:
https://pastebin.com/AjkkqPJm

```C:\bioformats-develop\tools>showinf "x.tif"
Checking file format [Tagged Image File Format]
Initializing reader
TiffDelegateReader initializing x.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Initialization took 0.268s

Reading core metadata
filename = x.tif
Series count = 1
Series #0 :
        Image count = 7
        RGB = false (1)
        Interleaved = false
        Indexed = false (false color)
        Width = 35134
        Height = 31358
        SizeZ = 1
        SizeT = 7
        SizeC = 1
        Tile size = 35134 x 128
        Thumbnail size = 128 x 114
        Endianness = intel (little)
        Dimension order = XYCZT (uncertain)
        Pixel type = uint8
        Valid bits per pixel = 8
        Metadata complete = true
        Thumbnail series = false
        -----
        Plane #0 <=> Z 0, C 0, T 0
        Plane #1 <=> Z 0, C 0, T 1
        Plane #2 <=> Z 0, C 0, T 2
        Plane #3 <=> Z 0, C 0, T 3
        Plane #4 <=> Z 0, C 0, T 4
        Plane #5 <=> Z 0, C 0, T 5
        Plane #6 <=> Z 0, C 0, T 6


Reading pixel data (0-6)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at loci.common.DataTools.allocate(DataTools.java:1260)
        at loci.formats.FormatReader.openBytes(FormatReader.java:875)
        at loci.formats.ImageReader.openBytes(ImageReader.java:444)
        at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
        at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
        at loci.formats.tools.ImageInfo.readPixels(ImageInfo.java:821)
        at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1055)
        at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
C:\bioformats-develop\tools>```

**Comment by jcupitt** [comment]
>  I am looking through vips API to see if I can tile each channel (256x256) in the resulting TIFF.

Yes, try:

```python
x.write_to_file("x.tif", tile=True)
```

1. Yes, libvips keeps images like this as a set of separate one-band pages. Try `vipsheader -a x.tif` to see all the information it has.
2. You can put the XML in the `image-description` tag.

**Comment by ajay1685** [comment]
I extracted the image-description tag from the sample file ([LuCa-7color_Scan1.ome.tiff](https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/sub-resolutions/Fluorescence/LuCa-7color_Scan1.ome.tiff))

using vipsheader -a --field "image-description" LuCa-7color_Scan1.ome.tiff

When I use VIPS ArrayJoin to join image channels, do I need to modify/insert xml for each plane or compile one XML file for the final image.  

Here is the XML of the ome.tiff : https://pastebin.com/MAJMr3ik

**Comment by jcupitt** [comment]
The OME sample images I can find just have the XML in the topmost TIFF directory.

**Comment by jcupitt** [comment]
So something like:

```python
#!/usr/bin/python3

import sys
import pyvips

images = [pyvips.Image.new_from_file(filename, access="sequential") for filename in sys.argv[1:]]
out = pyvips.Image.arrayjoin(images, across=1)
out.set_type(pyvips.GValue.gint_type, "page-height", images[0].height)
out.set_type(pyvips.GValue.gstr_type, "image-description", "my great XML string")
print("writing x.tif ...")
out.write_to_file("x.tif")
```

**Comment by ajay1685** [comment]
I have looked at the xml content of the sample file, than I modified the xml (removed stuff and changed a few things to match to the content of my own 7 band image. The xml is saved in a file "metadata.xml". 

Is it possible to plugin the file name in the following line of code:
`out.set_type(pyvips.GValue.gstr_type, "image-description", X:\path\metadata.xml)`

**Comment by jcupitt** [comment]
Sure, in Python you can do something like:

```python
metadata = open("X:\path\metadata.xml").read()
```

to read a file into memory as a big string, then:

```
out.set_type(pyvips.GValue.gstr_type, "image-description", metadata)
```

To attach it to an image.

**Comment by ajay1685** [comment]
Is there a way to monitor progress of the operation within a python script ?

**Comment by jcupitt** [comment]
@ajay1685 sorry, I missed the reply.

You monitor progress by attaching handlers to the `eval` signal. This isn't exposed in Python, but it would be simple to add.

@NHPatterson that's an interesting thread. I think if you set `image-description` on an image and then save as a tiff pyr, it should put a copy of that XML in every pyramid level.

It sounds like BF needs more though -- they seem to look for the subresolution marker (if I understand that thread) so I don't know if that would be enough.

**Comment by NHPatterson** [comment]
@jcuputt This is related, but when I write a multi-channel tiff from pyvips (where each channel is a vips band), the resulting data format has RGB as the photometric interpretation. 

Here is how I get my image from a numpy array:
```python
bands, height, width = mc_5ch_im.shape
mc_5ch_im = mc_5ch_im.reshape(width * height * bands)

mc_5ch_im = pyvips.Image.new_from_memory(mc_5ch_im.data, width, height, bands,
                                  dtype_to_format[str(mc_5ch_im.dtype)])

mc_5ch_im.write_to_file("fromNumpy_5ch.tif", tile=True)
```

here is the vipsheader:
```
fromNumpy_5ch.tif: 15643x11068 ushort, 5 bands, rgb16, tiffload
```

is there a way to control this so that it isn't RGB 16? Each channel should be seen as a greyscale.

**Comment by jcupitt** [comment]
Yes, that's deliberate. We have experimented with other representations, but they've always just caused more confusion and incompatibility. 

libvips saves seven (for example) band images as RGB plus four bands of unassoc alpha.

**Comment by ajay1685** [comment]
@NHPatterson I haven't had any success with multiple channels, Bio-format takes a few hours to do the same. I was able to write TIFF with 7 channel in a minute or two using vips (but not bio-format compatible), I also tried inserting the custom xml for channel description and that didn't work either.

@jcupitt while I don't understand much about the TIFF files and associated data, vips is amazing at handling large files for what I have used so far.

**Comment by jcupitt** [comment]
@NHPatterson 
> Each channel should be seen as a greyscale

I don't think this is possible with TIFF. You can set the `PHOTOMETRIC_INTERPRETATION` to `MIN_IS_BLACK`, but that's only allowed for one-channel images. You'd need to add the other channels as `UNASSOC_ALPHA`, and that's not obviously better than tagging as RGB.

You can set channels to 7 and not set `UNASSOC_ALPHA`, but the TIFF spec disallows this and many readers will break (from memory).

**Comment by jcupitt** [comment]
I've made a new issue for improving bioformats compatibility.
