### ISSUE TITLE
Do we have a function for this operation of vertically expand  image in top half and vertically shrink image in bottom half.

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1255]
Do we have a  function for this operation of vertically expanding image in top half and vertically shrink image in bottom half.
Though i do it in two steps, any maths related function to do in a single function  to speed up.
![function](https://user-images.githubusercontent.com/40394331/54185787-dee55000-44cf-11e9-97bb-ef8bd6940b09.png)

**Comment by jcupitt** [comment]
No, chop it in half, do two resizes, and rejoin. 

libvips operations join up behind the scenes, so it should be quick.

**Comment by vkkindia** [comment]
that was very fast reply.
I am doing like that only, thought there might be a function
