### ISSUE TITLE
unsupported

### ISSUE THREAD

**Issue by neurophil** [libvips/libvips#1259]

**Comment by neurophil** [comment]
I have successfully converted several SVS files to DeepZoom format. I've tried converting a multilayer SVS file using the structure of this command: 

vips dzsave --vips-progress --vips-leak infile.svs output

This command, which works for single layer SVS files, is immediately followed by this output:

(vips:13700): Openslide-WARNING **: Downsampled images not correctly ordered: 1 < 16.0025
openslide2vips: unsupported slide format
memory: high-water mark 0 bytes
error buffer: openslide2vips: unsupported slide format

Any guidance on determining next steps will be greatly appreciated. 
Thank you. 

Phil

**Comment by jcupitt** [comment]
Hi @neurophil, it sounds like an openslide problem, you'll probably need to ask there.

Can you read the image with `openslide-write-png`?

**Comment by neurophil** [comment]
Thank you for this suggestion! I appears to be an issue with openslide. I will inquire further at openslide.org.

`openslide-write-png multilayer.svs 1 1 1 240 240 output.png`

> Openslide-WARNING **: Downsampled images not correctly ordered: 1 < 16.0025
> openslide-write-png: multilayer.svs: Not a file that OpenSlide can recognize

`openslide-show-properties multilayer.svs`

> Openslide-WARNING **: Downsampled images not correctly ordered: 1 < 16.0025
openslide-show-properties: multilayer.svs: Not a file that OpenSlide can recognize
