### ISSUE TITLE
Error while writing image that was loaded from a png file

### ISSUE THREAD

**Issue by PiFace314** [libvips/libvips#1260]
I was using vips 8.7.4, then a I built it again from master branch to get the text justification feature, and an error started to happen every time I try to open a png file then write it: 

    VIPS:ERROR:vipspng.c:579:png2vips_generate: assertion failed: (r->height == VIPS_MIN( 8, or->im->Ysize - r->top ))

This error happens only when I run `write_to_file` on an image that was loaded from a png file. If I create a text image and adapt it to have 4 bands (RGBA), for example, then write it to a file, the error does not happen. If I open only jpg files then write to file, the error doesn't happen either.

**Comment by jcupitt** [comment]
Hi PiFace, I'll have a look. Thanks for the report.

**Comment by jcupitt** [comment]
OK, should be fixed, I hope. A debug assert hadn't been updated after a recent cache size adjustment.

Thanks for flagging this up.

**Comment by PiFace314** [comment]
Tried it here, it's seems to be working, indeed! The error is no longer occurring.
