### ISSUE TITLE
Missing frame while writing to WebP (master)

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#1261]
I noticed that while writing to an animated WebP, a frame is missing. I've not found the root cause yet, will continue debugging tomorrow.

Test image: https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing_banana2.lossless.webp

<details><summary>Test case (notice n-pages and height)</summary>

```
$ vips copy dancing_banana2.lossless.webp[n=-1] dancing_banana2.lossless2.webp
```

```
$ vipsheader dancing_banana2.lossless.webp[n=-1] -a
dancing_banana2.lossless.webp: 990x8400 uchar, 4 bands, srgb, webpload
width: 990
height: 8400
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: dancing_banana2.lossless.webp
vips-loader: webpload
gif-loop: 0
page-height: 1050
gif-delay: 100
n-pages: 8
```

```
$ vipsheader dancing_banana2.lossless2.webp[n=-1] -a
dancing_banana2.lossless2.webp: 990x7350 uchar, 4 bands, srgb, webpload
width: 990
height: 7350
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: dancing_banana2.lossless2.webp
vips-loader: webpload
gif-loop: 0
page-height: 1050
gif-delay: 100
n-pages: 7
exif-data: 186 bytes of binary data
resolution-unit: in
exif-ifd0-Orientation: 1 (Top-left, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-YCbCrPositioning: 1 (Centered, Short, 1 components, 2 bytes)
exif-ifd2-ExifVersion: Exif Version 2.1 (Exif Version 2.1, Undefined, 4 components, 4 bytes)
exif-ifd2-ComponentsConfiguration: Y Cb Cr - (Y Cb Cr -, Undefined, 4 components, 4 bytes)
exif-ifd2-FlashPixVersion: FlashPix Version 1.0 (FlashPix Version 1.0, Undefined, 4 components, 4 bytes)
exif-ifd2-ColorSpace: 65535 (Uncalibrated, Short, 1 components, 2 bytes)
exif-ifd2-PixelXDimension: 990 (990, Long, 1 components, 4 bytes)
exif-ifd2-PixelYDimension: 8400 (8400, Long, 1 components, 4 bytes)
orientation: 1
```
</details>

System info:
OS: Fedora release 29 (Twenty Nine)
libwebp version: 1.0.2
libvips version: https://github.com/libvips/libvips/commit/16d6e995a36a8a3d8a6a8accfab171296e34aaa1

**Comment by jcupitt** [comment]
Hi Kleis, it seems to be missing the frame duration too. I'll investigate.

I don't think I had an animated webp for testing, so this is a good example.

**Comment by jcupitt** [comment]
It looks like this might be a libwebp issue. With git master libwebp, I see:

```
john@yingna ~/pics $ vipsheader -f n-pages dancing_banana2.lossless.webp 
8
john@yingna ~/pics $ vips copy dancing_banana2.lossless.webp[n=-1] x.gif 
john@yingna ~/pics $ vipsheader -f n-pages x.gif 
8
john@yingna ~/pics $ vips copy x.gif[n=-1] x.webp
john@yingna ~/pics $ vipsheader -f n-pages x.webp
7
john@yingna ~/pics $ gif2webp x.gif -o x.webp
Saved output file (3224 bytes): x.webp
john@yingna ~/pics $ vipsheader -f n-pages x.webp
7
```

It looks like libwebp always drops the first frame of any animation.

**Comment by kleisauke** [comment]
Maybe something goes wrong while converting webp to gif? I tried to convert the webp to gif using an online converter. You can download this image [here](https://t0.nl/dancing_banana2.lossless.gif).

With that image I see:
```
[kleisauke@pc-kaw ~]$ vipsheader -f n-pages dancing_banana2.lossless.gif
8
[kleisauke@pc-kaw ~]$ gif2webp dancing_banana2.lossless.gif -o x.webp 
Saved output file (192276 bytes): x.webp
[kleisauke@pc-kaw ~]$ vipsheader -f n-pages x.webp 
8
```

I also noticed that the frame duration of the gif is wrong (it should be 10 instead of 100) when using vips to convert the webp.

**Comment by kleisauke** [comment]
It seems that the new WebP saver does not retain image transparency either.
```
[kleisauke@pc-kaw ~]$ wget http://www.gstatic.com/webp/gallery3/5_webp_a.webp
[kleisauke@pc-kaw ~]$ vipsheader 5_webp_a.webp 
5_webp_a.webp: 300x300 uchar, 4 bands, srgb, webpload
[kleisauke@pc-kaw ~]$ vips copy 5_webp_a.webp x.webp 
[kleisauke@pc-kaw ~]$ vipsheader x.webp
x.webp: 300x300 uchar, 3 bands, srgb, webpload
```

I'll have a look next week, maybe I can fix this.

**Comment by jcupitt** [comment]
The frame duations seem OK now, and I think I've improved the timing. There still a missing frame though, argh. I'll fiddle a bit more this weekend.

**Comment by jcupitt** [comment]
OK, it seems to be all working now, with animations preserving the frames, frame ordering and delays correctly as you go gif -> webp -> gif.

There does still seem to be some transparency confusion argh.

**Comment by jcupitt** [comment]
Transparency samples:

https://developers.google.com/speed/webp/gallery2

See "Transparent compass card for overlays".

https://www.gstatic.com/webp/gallery3/5_webp_a.webp

Should render as:

https://www.gstatic.com/webp/gallery3/5.png

**Comment by jcupitt** [comment]
OK, all done, I hope :/ Let's make a new issue if more dumbness crops up.

**Comment by kleisauke** [comment]
Just tested with master and didn't found any issues with (animated/transparency) WebP images. Thanks! :+1:
