### ISSUE TITLE
Combining dzsave and icc_transform?

### ISSUE THREAD

**Issue by pragunvohra** [libvips/libvips#1266]
Hello,

Is there a way to combine dzsave and icc_transform? I'm trying to export large Aperio SVS files and I am currently just running a dzsave into jpg format. However, there is embedded color information in the source SVS file (I have the icc file for it) that I would like to do at the same time as dzsave.

It seems as though it would be much more processing work to independently instead run:
1) vips extract_area
2) vips icc_transform
3) vips dzsave
one at a time.

Thanks!

**Comment by jcupitt** [comment]
Hello, the CLI will let you run load/operate/save at once, so you could do:

```
vips icc_transform in.svs out.dz some-profile.icc
```

You need to use something like Python if you want to do more complex things.

```python
im = pyvips.Image.new_from_file("x.svs")
im = im.icc_transform("someprofile.icc")
im.dzsave("out", overlap=0)
```
