### ISSUE TITLE
Converting jp2 images to tif images

### ISSUE THREAD

**Issue by ruqayya** [libvips/libvips#1269]
Hi,

I have jp2 histology whole slide images which I want to convert to tif images to be able to see them in QuPath. First I have used Kakadu to convert jp2 file to tif file and then tried using libvips to generate the pyramidal tif images. I am using the following commands:

          $ kdu_expand -i input.jp2 -o output_tmp.tif -precise     
          $ vips tiffsave output_temp.tif output.tif --compression=jpeg --Q=90 --tile --tile-width=256 --tile-height=256 --pyramid --bigtiff

I get the following error on using vips command: 

(vips:12808): VIPS-WARNING **: error in tile 0 x 7800
TIFFFillStrip: Seek error at scanline 7740, strip 130
tiff2vips: read error

Any help would be appreciated. Thanks.

**Comment by jcupitt** [comment]
Hello @ruqayya, does `kdu_expand` have any options you can use to write a different sort of TIFF?

If you can configure your imagemagick for jp2k support, libvips should be able to read the file directly.

**Comment by ruqayya** [comment]
Thank you for your reply.

I tried imagemagick but I found it too slow to be practical for converting a lot of images. I waited for more than 20 minutes but with no luck so I tried the options available with kdu_expand. One option which excludes the 2 resolution levels worked out along with vips command. However, the converted image could not be opened in QuPath. 

I think the problem is with the kakadu converted tif image. I will try OpenJPEG for conversion.

**Comment by jcupitt** [comment]
Yes, openslide uses openjpeg for jp2k decode, so it should be OK.

**Comment by jcupitt** [comment]
I tried weith openjpeg and it seems to work for me:

```
john@yingna ~/pics $ opj_decompress -i sekscir25.jp2 -o x.tif
[INFO] Start to read j2k main header (85).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Stream reached its end !
[INFO] Generated Outfile x.tif
decode time: 5085 ms
john@yingna ~/pics $ vipsheader x.tif 
x.tif: 10726x9147 uchar, 3 bands, srgb, tiffload
john@yingna ~/pics $ vips tiffsave x.tif x-pyr.tif --tile --compression jpeg --Q 90 --pyramid --bigtiff
```

And the pyramid looks OK.
