### ISSUE TITLE
Corner Chamfer with vips

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1270]
Need to do image corner chamfer using pyvips, like:
![image](https://user-images.githubusercontent.com/73845/55125882-2281c000-5146-11e9-893d-dac5df6a6185.png)

Methods I attempt to work out so far:
![image](https://user-images.githubusercontent.com/73845/55126059-dd11c280-5146-11e9-862a-da51de998b92.png)

seems a bit over complicated.
Any one can suggest a better way to do this.

**Comment by jcupitt** [comment]
Hello @jindili,

A simple way to draw complex graphics is with SVG. For example:

```python
#!/usr/bin/python3
  
import pyvips

x = pyvips.Image.svgload_buffer(b"""
<svg viewBox="0 0 100 100">
  <circle r="15" cx="50" cy="18" fill="#900"/>
</svg>
""")

x.write_to_file("x.png")
```

To make:

![x](https://user-images.githubusercontent.com/580843/55149773-b3569c80-5142-11e9-8f7b-3a7d2d520571.png)

The libvips SVG loader is very fast and can render images of any size using only a little memory.

**Comment by jindili** [comment]
Hi, @jcupitt ,
Thanks for the tip
I used pyvips.Image.xyz to generate those graphics using for intersect or cut.
svg way seems more intuitive to use, I'll have a try.

In my case, need to process quite a lot of large tiff shapes of variant angle contour, I think I need a better way to calculate the coordinate of the blue point and together with the green point (r,0) to make a triangle using svg.

![image](https://user-images.githubusercontent.com/73845/55156484-01948b80-5195-11e9-87c3-ed76c4732a68.png)

![image](https://user-images.githubusercontent.com/73845/55156616-60f29b80-5195-11e9-8885-44b189eaca9c.png)

(1) calculate coordinate of the blue point (x,y)
(2) generate svg shape by three point: (0,0), (r,0) and (x,y)

for problem (1), 
I think point(x,y) is the top most point of the intersect area, so I can have it's coordinate.

for problem (2), need to checkout some svg document, and I'll post code here when I have it solved.

**Comment by jcupitt** [comment]
Do you need to calculate? With SVG you can just define two paths (circle and corner) then take the intersection. It will find the coordinates of blue and green for you.

**Comment by jindili** [comment]
I'll try convert all tiff files to svg vector and give it a try.

**Comment by jcupitt** [comment]
You can also render the two SVG images, or one SVG and one TIF,  and take the difference using vips AND, OR, EOR etc.
