### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by cup** [libvips/libvips#1271]
I have read through the comments in some other issues and it seems the owner is
not interested in this. However I still feel it is appropriate to revisit this,
as I see some new information.

It was said in another thread that the reason was because several libraries are
not offering static builds and so VIPS would need to build them, which is a
valid concern.

However the only example given that I could find was `libxml2`. Now it
is true that Cygwin does not currently offer this.

However MSYS2 does: http://repo.msys2.org/mingw/x86_64

**Comment by cup** [comment]
https://github.com/cygwinports/mingw64-x86_64-libxml2/issues/1
https://github.com/libvips/libvips/issues/1271
https://github.com/libvips/libvips/issues/365

**Comment by jcupitt** [comment]
Hello @cup,

There is a `libvips.a` in the pre-compiled Windows binary. Could you just link against that? You will need to rebuild the C++ API if you're not using g++, of course.

There are some licensing problems with static linking LGPL projects like libvips, as I expect you know. You'd need to check the licences of all the projects it depends on too.

Why do you need to make a static binary? Perhaps there's some other way to achieve the effect you are after.

**Comment by kleisauke** [comment]
If you looking for a semi-static  64 / 32-bit Windows binary then https://github.com/libvips/build-win64/issues/21#issuecomment-458112440 might be relevant here.

You can download these binaries here: https://github.com/kleisauke/libvips-packaging/releases. It will contain the necessary `libglib-2.0.lib`, `libgobject-2.0.lib` and `libvips.lib` files to link statically against.

**Comment by cup** [comment]
@jcupitt I prefer to have a single EXE in some cases.

As you have pointed out in the past it wont be truly static as it will still
rely on `msvcrt.dll` or similar, but typically those type files will be already
installed on a Windows system which means that install/remove for VIPS would
more or less involve a single file, `vips.exe`.

I understand its not always possible for several reasons, but I lean towards
projects that offer such a thing.

I have a folder `C:\ProgramData\Local\bin` on my PATH that I dump stuff like
this. So the problem would be if I need to uninstall VIPS in its current
existence I would need to write a `setup.sh` or similar that removes all the
DLL, as it will be difficult to remember what DLL belong to what project.

If VIPS doesnt offer a static build then it should offer an uninstaller.

@kleisauke those links are interesting but I am not seeing a static `vips.exe`
offered, so it appears you are suggesting that I build it myself. I have done
this previously with other projects like FFmpeg, but its a pain so I would
prefer just downloading static `vips.exe` thats already been compiled if
possible.

**Comment by kleisauke** [comment]
I just created a static executable only build (see commit https://github.com/libvips/build-win64-mxe/commit/e6aedbaae5faa7df0e99b5716f44e31710053d82). This build contains all libvips executables (`vips.exe`, `vipsedit.exe`, `vipsheader.exe` and `vipsthumbnail.exe`) without being dependent on external DLL files.

Note that this is the `-web` variant of libvips. It will contain only file format loaders that have been carefully tested and which are commonly used on the web. I can't build the `-all` distribution statically because it includes GPL libraries (distributing a statically linked binary against GPL libraries, without releasing the code as GPL, violates the GPL license).

Attachment: the 64 and 32-bit libvips Windows binaries from the above commit (uploaded to Amazon S3 because there is an upload limit on GitHub attachments).
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-web-8.7.4-static-exe.zip
https://libvips-packaging.s3.amazonaws.com/vips-dev-w32-web-8.7.4-static-exe.zip

**Comment by cup** [comment]
@kleisauke yes! that is exactly what i am looking for

thanks

i would only question why you dont just put it here?

https://github.com/libvips/build-win64-mxe/releases

**Comment by kleisauke** [comment]
> i would only question why you dont just put it here?
> https://github.com/libvips/build-win64-mxe/releases

Because 8.7.4 has already been released and I don't want to change existing GitHub releases. I'll consider releasing static executables on the `build-win64-mxe` repo when a new version of libvips is released.

I've created https://github.com/libvips/build-win64-mxe/issues/4 to keep track of this.

**Comment by cup** [comment]
https://github.com/libvips/build-win64/issues/21
https://github.com/libvips/build-win64-mxe/issues/4
https://github.com/libvips/libvips/issues/1271

**Comment by mickael-kerjean** [comment]
FYI, I created some documentations to statically compile (or I guess the term would be semi static) libvips: https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/deps/create_libresize.sh

Did some build both for linux amd64 and arm, works great :). As a gcc noob, it tooks me days to work it out and you will still need to dynamically compile against the glib and a few other ones like this "-lm -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -ldl"

**Comment by joshuarli** [comment]
FWIW while I wasn't able to convince the build system, it's possible with staticx. Read [here](https://stackoverflow.com/a/62526516/5348393).

**Comment by yisibl** [comment]
Is a statically linked version available for Linux and Mac?

**Comment by ospfranco** [comment]
I would like to compile libvips as a static lib for macOS, but I really don't know how to go about it, if anyone can give me a hand I would really appreciate it:

https://stackoverflow.com/questions/73168961/macos-xcode-how-to-link-compile-libvips

**Comment by jcupitt** [comment]
I posted a possible solution on that stackoverflow question.

@ospfranco please don't cross-post questions. It makes unnecessary extra work for maintainers.
