### ISSUE TITLE
How to simple install libvips with mozjpeg and libimagequant on Debian/Ubuntu?

### ISSUE THREAD

**Issue by nuno360** [libvips/libvips#1272]
I'm a basic Linux user, and what I know is that impossible to use libvips with mozjpeg and libimagequant with simple apt-get install command.

So I would like to know if there is some tutorial with step by step.

I start with to install mozjpeg with:

```
wget https://mozjpeg.codelove.de/bin/mozjpeg_3.1_amd64.deb
dpkg -i mozjpeg_3.1_amd64.deb
```

After install libvips:

`apt-get install libvips`

So now how I can configure libvips to use mozjpeg?

Thanks

**Comment by jcupitt** [comment]
Hello, there's a dockerfile here that builds libvips + mozjpeg:

https://github.com/jcupitt/docker-builds/tree/master/libvips-mozjpeg-ubuntu18.10

The README has some notes.

**Comment by jcupitt** [comment]
I'll close. Please reopen if this is still an issue.
