### ISSUE TITLE
dzsave with "associated images"

### ISSUE THREAD

**Issue by martinweihrauch** [libvips/libvips#1274]
Maybe you could consider to also put the "associated images" from OpenSlide into the szi? 
This would be an additional folder in the ZIP, on the same hierarchy level as the folder <image>_files and would contain (if available):
macro.jpg (image of the entire glass slide)
thumbnail.jpg (image of the scan area)
label.jpg (image of the glass slide label)

It is specified in our SZI document here:
https://github.com/smartinmedia/SZI-Format/blob/master/SZI%20format%20description%20-%202018-11-24.pdf

Best

Martin

**Comment by jcupitt** [comment]
Hello Martin, this was added a year ago: 

https://github.com/libvips/libvips/issues/853

it should work, let me know if it doesn't.

**Comment by jcupitt** [comment]
I think this is fixed.

**Comment by martinweihrauch** [comment]
I ran the latest version of NetVips.
with 
VipsConverter.ConvertToSzi(wsiFilename, sziFilename, tileSize, jpegQuality, true, progressCallback, cancelToken);
I converted a SVS.
There is no folder with associated images.

Also, I tried a Mirax with Netvips BTW and there it only converted the mrxs file into a very small 180 KB SZI, but not the full, so it had "neglected" the folder of the Mirax file. Do you want me to add a ticket to NetVips for that?

**Comment by jcupitt** [comment]
Oh heh, the work from a year ago was never merged. Let's merge it in this issue.

**Comment by martinweihrauch** [comment]
OK - you mean the associated images, right?
What about the MIrax issue. Is that NetVips related or Vips related (Mirax always worked though).

**Comment by jcupitt** [comment]
OK, this branch has that work, but moved on top of master:

https://github.com/libvips/libvips/tree/szi-associated

I see:

```
john@yingna ~/pics/openslide $ vips dzsave CMU-1.svs[attach-associated] x.szi
john@yingna ~/pics/openslide $ unzip -qq x.szi
john@yingna ~/pics/openslide $ ls x
associated_images  scan-properties.xml  x.dzi  x_files
john@yingna ~/pics/openslide $ ls x/associated_images/
label.jpg  macro.jpg  thumbnail.jpg
```

Re. your Mirax issue, it sounds like your libvips has been built without openslide support.

**Comment by martinweihrauch** [comment]
SVS conversion runs, so openslide must be included.

**Comment by jcupitt** [comment]
I made a test win build for you:

http://www.rollthepotato.net/~john/vips-dev-w64-all-8.8.0.zip

That's the szi-associated branch. Could you let me know if it works?

**Comment by martinweihrauch** [comment]
I tried it with a SVS, which contains associated images, but VIPS did not add these.
Also, I tried an MRXS and the process failed:
![grafik](https://user-images.githubusercontent.com/2306324/56141870-f4054100-5f9d-11e9-928b-29b80b164d2c.png)

**Comment by martinweihrauch** [comment]
The SVS --> SZI directory:
![grafik](https://user-images.githubusercontent.com/2306324/56141954-1b5c0e00-5f9e-11e9-9254-aa7ef69bd3cc.png)

**Comment by jcupitt** [comment]
Oh dear, that's bad. I'll try tonight on my PC.

**Comment by jcupitt** [comment]
Do you have another vips on your `PATH`? It could be picking up that in error. You need `attach-associated` as well, eg.:

```
john@yingna ~/vips-dev-8.8/bin $ wine ./vips.exe dzsave ~/pics/openslide/CMU-1.svs[attach-associated] ~/x.szi --overlap 0
```

Making:

```
john@yingna ~ $ unzip -qq x.szi
john@yingna ~ $ cd x/
john@yingna ~/x $ ls
associated_images  scan-properties.xml  x.dzi  x_files
john@yingna ~/x $ ls associated_images/
label.jpg  macro.jpg  thumbnail.jpg
```

**Comment by jcupitt** [comment]
... so it's working for me, I should have said.

**Comment by martinweihrauch** [comment]
Yes, the associated images work with that "tag", which I didnt see in the first place.
Thx!

**Comment by martinweihrauch** [comment]
Regarding Mirax:

The current vips tries to create a (large) szi/zip, it stopped at appr. 1.8 GB.
The vips version 8.3 however just creates a 180 kb szi (probably only using the mrxs file and ignoring the concurrent folder with the data files). I guess, that is the same problem, which NetVips has.

**Comment by jcupitt** [comment]
Huh, funny, I'll try with a large mirax file here.

vips 8.3 could be using an older libopenslide I guess, that might explain the failure.

**Comment by jcupitt** [comment]
I don't have a huge mrxs file. I tried with a 4gb `.ndpi` and it seems to work -- it made a 2.8gb szi. 

I tried with a 500MB mrxs and that worked too.

**Comment by jcupitt** [comment]
That's using the Windows build of vips-8.8 I linked above, to be clear.

**Comment by martinweihrauch** [comment]
Something is weird. 
I did this (with your latest version, which you sent me):
![grafik](https://user-images.githubusercontent.com/2306324/56223551-43b33d80-606e-11e9-849e-01471d2fad9d.png)
which means, I am in the folder for vips (8.8) and executing the vips.exe, so I am sure this is the right version. The tiling stops somewhere and I am left with a temporary file .gsf-save-P2TB0Z. There is no error command.

This is the image, which I am using:
https://drive.google.com/file/d/1NcA8Cz3mwMW_JbDeU98t_d1B5pqBVss-/view?usp=sharing

**Comment by jcupitt** [comment]
I've set it going, I'll see if it can write a >4gb file.

I guess you saw, that slide is mostly empty space:

```
$ vipsheader ~/pics/openslide/mrxs/NSCLC.mrxs/home/john/pics/openslide/mrxs/NSCLC.mrxs: 112284x224416 uchar, 4 bands, rgb, openslideload
$ vipsheader ~/pics/openslide/mrxs/NSCLC.mrxs[autocrop]
/home/john/pics/openslide/mrxs/NSCLC.mrxs: 35102x30539 uchar, 4 bands, rgb, openslideload
```

You can copy-paste text from the Windows console into your web browser (again, I expect you know). It's slightly awkward: right click on the title bar and select Edit / Mark, then drag the text with the mouse, then right-click on the title bar again and select Copy.

It's a little easier than screen-grabbing the window and pasting a PNG.

Likewise, you can copy-paste from a web browser into the command prompt, I'm sure you know.

**Comment by jcupitt** [comment]
This is now merged to master, I'll close. Please open a new issue if there are any problems.

**Comment by martinweihrauch** [comment]
Great, thanks!

Where could we get the fresh Windows binaries?
Will it be automatically integrated into the NetVips project?

Best

Martin


Von: John Cupitt <notifications@github.com>
Gesendet: Freitag, 26. April 2019 15:35
An: libvips/libvips <libvips@noreply.github.com>
Cc: info@smartinmedia.com; Author <author@noreply.github.com>
Betreff: Re: [libvips/libvips] dzsave with "associated images" (#1274)


This is now merged to master, I'll close. Please open a new issue if there are any problems.

**Comment by jcupitt** [comment]
The binary above ^^ should still work. I'll do an updated one in a week or so with the final release.

Yes, it'll appear in netvips.

**Comment by kleisauke** [comment]
@martinweihrauch The final NetVips 1.1 release will be in sync with the release of libvips 8.8. The pre-compiled Windows binaries will be updated then.
