### ISSUE TITLE
Vips affine cuts bottom image and also shift in the left side

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1276]
Hi John,
I am trying to run this command :

```
#resize 0.1mm (5px) from bottom_middle as center so that bottom portion will remain constant
vips affine image.tif  resize.tif[compression=ccittfax4,squash] "1.0 0.0 0.0 1.00035865433" --idx 0.5 --idy 1.0   --interpolate nearest
```

The resulted image cuts 0.02mm (1px) at the bottom, also in the left side there is 0.02 mm (1px) shift towards right.
Any solution will be helpful as I need a high accuracy output.
I have attached the files and you can check it. Pls see at this co-ordinates X=9.18mm, Y=278.90mm

image.tif https://drive.google.com/file/d/1Gadc18V6Yc_IgcsKGnyeVdqx6R0t1Q-k/view?usp=sharing 
resize.tif https://drive.google.com/file/d/1s0m7sg8DosVKadOW9Lh-1Hls8HCV670N/view?usp=sharing

Also if I try with --idx 0.5 --idy 0.0 for top_middle also Iam getting left shift.
If i try with --idx 0 --idy 0 it seems to be ok.

**Comment by jcupitt** [comment]
Hello, yes, that's corner vs. centre sampling. As you say, use `--idx`, `--idy` to change it.

I don't really understand what you are trying to achieve. Do you want to stretch the image vertically by one pixel?

**Comment by vkkindia** [comment]
Hi,

I want to stretch image vertically by 5px ( 0.1mm ) from bottom to top. So
that image stretch starts from bottom and incrementally to top

**Comment by jcupitt** [comment]
I would just use `resize`, it handles corner/centre for you.

For example, in Python:

```
#!/usr/bin/python3

# stretch an image vertically by 5 pixels, with the first and last lines in
# the image remaining (almost) equal

import sys
import pyvips

im = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
stretch = (im.height + 5) / im.height
im = im.resize(1, vscale=stretch, kernel="nearest")
im.write_to_file(sys.argv[2])
```

**Comment by vkkindia** [comment]
Ok i will try, but the requirement is image has to be enlarged only in the
top. So at bottom remain same.

Another case How to modify for this scenario: image at top remain same but
at bottom it has to be stretched. How to use resize here.

**Comment by jcupitt** [comment]
I'm not sure I understand. Don't you just want to stretch the image? How can the top remain the same if the image is stretched?

**Comment by vkkindia** [comment]
It we stretch the image from lefttop, then the image gets stretched
gradually from lefttop to bottom, at lefttop the stretch will be 0, and
gradually increases to the bottom.

Like that I want the image stretch from bottom middle.

**Comment by vkkindia** [comment]
tried using resize, this also trims 1px at bottom.
only lefttop works, idx 0 idy 0
I found one solution for trim when we use 
vips affine image.tif  resize_cmdline_bottommiddle.tif[compression=ccittfax4,squash] "1.0 0.0 0.0 1.00035865433" --idx 0.5 --idy 1.0   --interpolate nearest --oarea "0 0 35200 13948"
if we add extra  2px in im.height there is no trim.

Pls suggest is it the right way, is the image expansion actually happens.

**Comment by jcupitt** [comment]
`resize` shouldn't trim any pixels. For example, with this test image:

![beach](https://user-images.githubusercontent.com/580843/55681680-0d184d00-5921-11e9-9a86-d5800c551637.png)

If I run:

```
$ vips resize beach.png x.png 1 --vscale 1.005 --kernel nearest
```

I get:

![x](https://user-images.githubusercontent.com/580843/55681688-215c4a00-5921-11e9-8a02-7f1e331e6f5c.png)

If you zoom in on the bottom left corner, you see:

![x](https://user-images.githubusercontent.com/580843/55681711-81eb8700-5921-11e9-8b79-695a83253282.png)

Before top, after bottom. You can see that the the bottom row has not been clipped.

**Comment by vkkindia** [comment]
Thanks, checked with resize it works, but why from affine it is not
working. As I am using affine for rotation, resize operations it would be
helpful to know how to do it without either left and  or right and or top
and or bottom trimming.

**Comment by jcupitt** [comment]
I added some white dots to the top left of that PNG:

![beach](https://user-images.githubusercontent.com/580843/55822294-35f23b00-5af7-11e9-9117-1cd8e15da8df.png)

If I run:

```
$ vips affine beach.png x.png "1 0 0 1.05" --interpolate nearest
```

Then at the top I see:

![top](https://user-images.githubusercontent.com/580843/55822467-8ff30080-5af7-11e9-9ee5-20976295379c.png)

And at the bottom:

![bottom](https://user-images.githubusercontent.com/580843/55822533-b2851980-5af7-11e9-90d5-bdf1927e16a8.png)

So it is not clipping,

**Comment by jcupitt** [comment]
I think this is resolved, please reopen if not.
