### ISSUE TITLE
PNG Composite Issue (Watermark)

### ISSUE THREAD

**Issue by KarlAustin** [libvips/libvips#1277]
Hi,

Not an issue as such, more a "help, this is driving me mad".

I'm trying to WM an image, using a JPEG that's fine, add an Alpha channel with my opacity set, use composite2 and it's all good.

Using a PNG is a whole other ballgame. I have a PNG that has some completely transparent areas, some that are just opaque.  The issue is that I can't work out how to make it more opaque.  If I use premultiply it'll lower the opacity, within reason (mainly affecting the areas that are white), but it also darkens it at the same time.  I can't flatten it and add a new alpha, as that'll mess with the already opaque/transparent areas.

PNG code:
`        if (vips_premultiply(t[1], &t[2], "max_alpha", opacity, NULL )) {
            g_object_unref(base);
            return 1;
        }
        if (vips_composite2(t[0], t[2], out, o->Blend, "x", o->Left, "y", o->Top, "premultiplied", FALSE, NULL )) {
            g_object_unref(base);
            return 1;
        }`

If I set premultiply to true, then the image is just basically not blended at all, just placed over the top.  This is with VIPS_BLEND_MODE_OVER, although non of the modes make much different to the desired outcome when using PNG.

I must be missing something obvious.

Thanks,

Karl

**Comment by KarlAustin** [comment]
"Problem" solved.
`
double multiply[4] = {1, 1, 1, o->Opacity};
double addition[4] = {0, 0, 0, 0};
vips_linear(t[1], &t[2], multiply, addition, 4, NULL);
`
Instead of premultiply.

**Comment by jcupitt** [comment]
Hi Karl, yes, that's what I'd suggest.
