### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by leslie-wang** [libvips/libvips#1278]
Just wonder to know when next release is going to be available? Thanks.

**Comment by jcupitt** [comment]
Soon, I hope. There are just a couple of things that still need fixing.

**Comment by jcupitt** [comment]
There's a post up with release notes for 8.8:

https://libvips.github.io/libvips/2019/04/22/What's-new-in-8.8.html

It should be soon now.

**Comment by leslie-wang** [comment]
Thanks a lot! Looking forward.
