### ISSUE TITLE
wrap libvips in a namespace

### ISSUE THREAD

**Issue by CoachRDeveloper** [libvips/libvips#1280]
I am using C++ under Windows. I use the libs and includes from vips-dev-w64-web-8.7.4.zip. Libvips is using glib, which adds classes/types like GString, GDir etc to the global namespace. We use the same class names in our own framework. Is it possible to wrap the whole libvips library (including glib) in a separate namespace so it does not interfere with our own code?

Now I get all kinds of errors like:
error C2872: 'GString': ambiguous symbol

Or is there another workaround?

**Comment by jcupitt** [comment]
Hello @CoachRDeveloper, sorry, the libvips C++ binding is a mix of C and C++, and (I think) you can't put the C parts into a namespace. `GString`, `GDir` etc. are all from C.

I think your best solution would be not to use libvips and your GDir etc. names in the same file. I would make a small "adapter" class that wraps your image processing operations and does not expose the libvips API to the rest of your program.
