### ISSUE TITLE
dzsave tile sizes not matching

### ISSUE THREAD

**Issue by 9xg** [libvips/libvips#1282]
I am running some dzsave operations on whole-slides images (.svs) and observed an interesting issue. If I execute the following code:
`vips dzsave "file_HE_1.svs" he_tiles --tile-size 400 --depth one --suffix .jpg[Q=100]`
I obtain tiles which are not exactly 400x400 pixels. Instead, most (not all) have a size of 402x402 pixels. Is there a rationale behind that or am I missing something?
Many thanks!

**Comment by jcupitt** [comment]
Hello @9xg, `dzsave` saves with a one-pixel overlap, by default, so 400 x 400 pixel tiles away from the image edges will be 402 x 402. Try adding `--overlap 0`.
