### ISSUE TITLE
Why is dzsave in CLI significantly faster than when called via pyvips?

### ISSUE THREAD

**Issue by 9xg** [libvips/libvips#1284]
Hi,

I ran a few benchmarks in the last few days and observed an interesting behavior.
I compared the runtime speed on a fairly large .svs file between these two ways:
`vips dzsave "${PWD##*/}_HE_1.svs" he_tiles --tile-size 400 --depth one --overlap 0 --suffix .jpg[Q=100]` in the command line.

And the following code in python:
`pv.cache_set_max(0)
pv.cache_set_trace(False)
[...]
slide.dzsave(output_folder,tile_size=tileSize,depth='one',overlap=0,suffix='.jpg[Q=100]')`

I get runtimes of 15-20 minutes with the Python script and 5-7 minutes on the dzsave in command line.

Is this a concurrency issue or what might be a limiting factor?

Many thanks!

**Comment by jcupitt** [comment]
Hi @9xg, that's interesting, they should be the same speed. I'll try a benchmark here.

**Comment by jcupitt** [comment]
I tried this python program:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
image.dzsave(sys.argv[2], tile_size=400, depth='one', overlap=0,
             suffix='.jpg[Q=100]')
```

And I see (on a four core / 8 thread i7):

```
john@yingna ~/try $ time ./dzsave.py ~/pics/openslide/CMU-1.svs x

real	0m19.390s
user	1m40.994s
sys	0m9.067s
john@yingna ~/try $ time vips dzsave ~/pics/openslide/CMU-1.svs x2 --tile-size 400 --depth one --overlap 0 --suffix .jpg[Q=100]

real	0m19.586s
user	1m41.606s
sys	0m9.553s
```

So they are the same speed for me. 

There must be some other difference. Perhaps your Python version is linked to a different libjpeg? If one is using libjpeg-turbo and one not, that could explain it.

**Comment by 9xg** [comment]
Thanks @jcupitt. Is there an easy way to check whether pyvips uses Libjpeg or turbo?

**Comment by jcupitt** [comment]
It sounds like you might have more than one libvips installed, so just check you are running `vips` and `python` with the same environment. Look for the `PATH` and `LD_LIBRARY_PATH` env vars.

**Comment by 9xg** [comment]
For everyone facing this problem: In my case the solution was creating a new conda environment and installing libjpeg-turbo before anything else is installed!

**Comment by jcupitt** [comment]
pyvips is now in conda: https://libvips.github.io/libvips/2019/08/18/pyvips-in-conda.html
