### ISSUE TITLE
Does VIPS avoid re-compression when writing a cropped JPEG image?

### ISSUE THREAD

**Issue by KevinCain** [libvips/libvips#1285]
Let's suppose we have a JPEG file, which we read, crop, and then write as JPEG to a new file via VIPS (C++ API).  In this case, must VIPS re-encode the JPEG format, or is it being clever (or could it be induced to be clever with a VOption) by not re-compressing the JPEG, but instead 'truncating' the existing encoding?

The idea, of course, is to prevent destructive artifacts being accumulated over an intermediate file or two.

It looks like passing a file name suffix of '.jpg[Q=100]' to the LibVIPS 'write_to_file' method will direct VIPS to write the highest quality JPEG format possible, is that correct?

Thanks for any insight!

**Comment by jcupitt** [comment]
Hi @KevinCain,

No, libvips will always decompress and recompress. I would aim to do all transformations in one go, so load / shrink / crop / rotate / colour correct / sharpen / save, for example. I think shrine does this (I think).

You can do lossless cropping with the jpeg tools, eg.: `jpegtran -crop`, as I expect you know.

Try `vips jpegsave` at the command-line to see all the options to the jpeg saver. You can pass them as options encoded in the filename, or as optional parameters, eg.:

```ruby
image.jpegsave "somename.jpg", Q: 100
image.jpegsave "somename.jpg[Q=100]"
image.write_to_file "somename.jpg", Q: 100
image.write_to_file "somename.jpg[Q=100]"
str = image.write_to_buffer "[Q=100]"
str = image.write_to_buffer "", Q: 100
```

Encoding options into the filename is handy if you are writing command-line scripts. You can write:

```ruby
require 'vips'

image = Vips::Image.new_from_file ARGV[0]
image = image.rotate ARGV[2].to_f
image.write_to_file ARGV[1]
```

Now I can write:

```
$ ./script.rb ~/pics/mydoc.pdf[page=2] x.tif[compression=lzw]
```

But if you are setting options in your Ruby, I would use named params instead.

**Comment by KevinCain** [comment]
Thank you @jcupitt for your being characteristically fast, helpful and complete!  This makes good sense, all of it.  In this case I don't think I can avoid at least a single intermediate files, but hopefully with JPEG written at Q=100 the damage will be minimal.
