### ISSUE TITLE
get one tile

### ISSUE THREAD

**Issue by will4906** [libvips/libvips#1292]
Hi, I want to make a svs image file manage system by the web framework like django or flask. And I will mark on the pictures, so i decide to use the openlayers.

My problem is that it is not realistic to dzsave all files to zoomify, so i want to get the target tile when the frontend openlayers request the tile. Could the lib do this work?

Sorry for my poor english and best wishes.

**Comment by jcupitt** [comment]
Hello @will4906,

openslide python includes a script to do exactly this:

https://github.com/openslide/openslide-python/tree/master/examples/deepzoom

You'll find it's OK if you only have a few users, but if you need to support more than about 10 concurrent sessions on your server, you will need to preconvert the images with dzsave.

I made a simple C version:

https://github.com/jcupitt/tilesrv

Though it might need some work.
