### ISSUE TITLE
macOS binary

### ISSUE THREAD

**Issue by cseelus** [libvips/libvips#1295]
Any chance a binary for macOS could be provided, similar to the one for Windows that "contains ALL the file format loaders that libvips supports, including some very minor ones, and a complete copy of ImageMagick". 

Just wanted to try it out as an alternative to ImageMagick, but the number of dependencies the Homebrew formula would install is a bit insane imho:

`Required dependencies for vips: isl, mpfr, libmpc, gcc, libevent, open-mpi, fftw, fontconfig, giflib, imagemagick, libexif, libgsf, pixman, cairo, gdk-pixbuf, libcroco, fribidi, graphite2, harfbuzz, pango, librsvg, libxml2, openslide, orc, nspr, nss, qt and poppler`

**Comment by jcupitt** [comment]
Hello @cseelus,

The homebrew binary is roughly the same set of dependencies as that Windows zip. It should take only a few seconds to install -- behind the scenes, it'll just download the right binary for you. And of course it's a very convenient way to keep your install up to date with fixes as they come out.

If Windows had something like homebrew I wouldn't make a binary there either, heh.

**Comment by cseelus** [comment]
About 6 minutes in, it started to build qt from source and incapacitate my machine, that’s when I stopped it and uninstalled all other (25+) vips dependencies that were installed before qt.

I‘m on the most recent version of Mojave btw, so I expected Homebrew to just download the 28 dependencies as binaries.

A self contained binary can have its advantages I guess 😉

**Comment by jcupitt** [comment]
Oh strange, it shouldn't build qt from source. I'll try wiping and reinstalling homebrew.

**Comment by jcupitt** [comment]
It downloaded the qt binary for me. It was 4m to install all the packages on this 2012 imac -- it'd be quicker if you had some homebrew stuff on already.

I'm not sure why it pulls in qt and gcc.

**Comment by kleisauke** [comment]
FYI: @lovell is planning to move the [lovell/package-libvips-darwin](https://github.com/lovell/package-libvips-darwin) repo to the libvips organization. This allows users to use a "Homebrew tap" maintained by libvips.

The "tap" has the [same dependency tree](https://github.com/lovell/package-libvips-darwin/blob/master/Formula/vips.rb#L13-L28) as the `-web` variant of the Windows binaries (only file format loaders that have been carefully tested and which are commonly used on the web).

See the discussion here: https://github.com/lovell/package-libvips-darwin/pull/3.

**Comment by jcupitt** [comment]
Oh, that's nice!

**Comment by cseelus** [comment]
Thanks for testing it, @jcupitt 

Its strange that Homebrew tried to build qt from source on my machine, usually there are prebuilt binaries ("bottles") for most packages available for the current major version of macOS and I'm on 10.14.4. I guess your 2012 iMac was faster than my 2018 MPB because I was on battery though.

@kleisauke lovell/package-libvips-darwin looks promising, thanks for info!
