### ISSUE TITLE
composite2 using 2 CMYK TIFF images

### ISSUE THREAD

**Issue by kevinswarner** [libvips/libvips#1298]
I am not an imaging expert, so please forgive my lack of knowledge on this topic. I am very confused about the support (or lack of support) for working with CMYK images using vips. We have many CMYK TIFF images that we process for printing of very large files. I am trying to create a composite of two CMYK TIFF images...

vips composite2 image1.tif image2.tif output.tif atop

I get the following error message...

vips_colourspace: no known route from 'cmyk' to 'srgb'

The image "identify" info is...

image1.tif = TIFF 5827x8583 5827x8583+0+0 8-bit CMYK 1.2194MiB 0.000u 0:00.004
image2.tif = TIFF 5827x8583 5827x8583+0+0 8-bit CMYK 2.88595MiB 0.000u 0:00.002

We originally tried to use Sharp to do much of the work we need, but it has even less support for working with CMYK images, I think. Although honestly, I may be missing some key concepts about working with these images and color profiles, etc.

What are my options here? Do I need to only be working with sRGB images to begin with in order to use VIPS? We have been using Imagemagick, but we are running into performance and memory issues as we are attempting to do much of our image processing in AWS Lambda.

Thanks!

**Comment by jcupitt** [comment]
Hi @kevinswarner,

libvips has pretty good CMYK support, you should be able to make it do what you want.

In this case, you can composite many images in many different colourspaces (RGB, CMYK, LAB, Yxy etc.), so before it can start, composite has to move them all to a common compositing space. This is sRGB by default, but you can use anything.

Try:

```
vips composite image1.tif image2.tif output.tif atop --compositing-space cmyk
```

The irritating "no route" messages are fixed in 8.8, due in a week or so, though you'll still need the compositing space flag.

If you are running more than one or two vips operations on your images, I would use something like pyvips for the processing. It'll be much faster than the command-line, and won't need any temporary storage.

**Comment by jcupitt** [comment]
Oh of course you'll need to define what transparency means for your CMYK images. How do you want atop to blend them together?

**Comment by kevinswarner** [comment]
Thanks @jcupitt. I appreciate your help. I was originally using composite2. But I also tried composite.
Also, I am not sure what integers to use to map to the blend modes (is there a table that shows this map?), so I used 5 (for VIPS_BLEND_MODE_ATOP) as based on the docs, I just counted down from 0. Totally a guess.

Using composite...

    > vips composite "image1.tif image2.tif" output.tif 5 --compositing-space cmyk
    composite: unsupported compositing space

Using composite2...

    > vips composite2 image1.tif image2.tif output.tif atop --compositing-space cmyk
    composite: unsupported compositing space

Am I specifying the compositing space incorrectly? When viewing help for the command in CLI, I get the following...

```
blend an array of images with an array of blend modes
usage:
   composite in out mode [--option-name option-value ...]
where:
   in           - Array of input images, input VipsArrayImage
   out          - Output image, output VipsImage
   mode         - Array of VipsBlendMode to join with, input VipsArrayInt
optional arguments:
   x            - Array of x coordinates to join at, input VipsArrayInt
   y            - Array of y coordinates to join at, input VipsArrayInt
   compositing-space - Composite images in this colour space, input VipsInterpretation
			default: srgb
			allowed: error, multiband, b-w, histogram, xyz, lab, cmyk, labq, rgb, cmc, lch, labs, srgb, yxy, fourier, rgb16, grey16, matrix, scrgb, hsv
   premultiplied - Images have premultiplied alpha, input gboolean
			default: false
operation flags: sequential
```

I also tried using an int for compositing space, thinking that the docs were incorrect, but when I try...

```
> vips composite "image1.tif image2.tif" output.tif 5 --compositing-space 6
composite: enum 'VipsInterpretation' has no member '6', should be one of: error, multiband, b-w, histogram, xyz, lab, cmyk, labq, rgb, cmc, lch, labs, srgb, yxy, fourier, rgb16, grey16, matrix, scrgb, hsv
```

As far as the blend mode, I have two images, the same size. One is a solid image colored blue. The other is a "mask" image that has one small area of solid color red. I am just trying to "stamp" out an area from image1.tif based on the mask in image2. I am not sure if atop is the correct approach. I was going to experiment with different blend modes, but cannot get past these other issues.

```
image1.tif
|----------------|
|xxxxxxxxxxxxxxxx|
|xxxxxxxxxxxxxxxx|
|xxxxxxxxxxxxxxxx|
|xxxxxxxxxxxxxxxx|
|----------------|

image2.tif
|----------------|
|                |
|    yyy         |
|    yyy         |
|                |
|----------------|

ouput.tif (desired)
|----------------|
|                |
|    xxx         |
|    xxx         |
|                |
|----------------|
```
The empty area in image2 and output is transparent and should remain transparent.

Anyway, again, I really thank you for your help!

**Comment by jcupitt** [comment]
Sorry I wasn't thinking, use composite2, it's much simpler.

```
composite: unsupported compositing space
```

Ahem, sorry again, this works in 8.8, but you're right, not in 8.7.

For your stamping problem, I would just cut out a bit of image1 and paste it into a huge transparent image. I guess you are using CMYKA, is that right?

Can you use something like Python, or does it have to be command-line?

**Comment by kevinswarner** [comment]
I could use Python, but I have never used it before. I expect it would be pretty simple.

So, CMYK is not supported for this in the current version 8.7? Sounds like 8.8 will be out soon, so I can wait a bit. It sounds like the new version will make working with color spaces and profiles easier?

Yes, CMYKA.

As far as the stamping, when you say "cut out a bit", what function in VIPS are you suggesting? Do you mean simply extract a rectangle of w and h at x and y? Seems like that would work. I have been converting approaches that were used in our other library which used ImageMagick, so I have been following the already established strategies.

Again, thank you for your help.

**Comment by jcupitt** [comment]
Yes, 8.8 will support CMYK in composite2, and makes working with colourspaces a little easier.

Yes, you can just crop and insert:

```
# crop left, top, width, height
vips crop image1.tif crop.v 100 100 200 200
# make a huge black image
vips black black.v 1000 1000
# paste the crop into that
vips insert black.v crop.v output.tif 250 250
```

That's using two large temporary files, which is rather slow, and you'll need to remember to delete them. 

If you use Python you won't need the temp files, but of course you'd have to learn Python.

**Comment by kevinswarner** [comment]
Thank you for your help on this! Looking forward to 8.8.

**Comment by jcupitt** [comment]
8.8 is out now, so this should be simple. Please open a new issue if there's still a problem.
