### ISSUE TITLE
GIF frame delays

### ISSUE THREAD

**Issue by deftomat** [libvips/libvips#1299]
I'm working on GIF support for Sharp and I discovered that I cannot get/set an information about frame delays.

What I understand is that GIF allows you to specify a delay between each frame to control FPS.

Loading the image from file and saving it works OK as *libvips* somehow keeps the information about timing and pass it into `magicksave`.

However, the problem is when we want to create a new image from scratch. In that case, I'm not able to pass this information into `magicksave`.

**So, my question is:** Is there a way to obtain the timing from a loaded GIF file and change it before saving it into the new GIF file?

**Comment by jcupitt** [comment]
Hello, yes, it's kept in the `gif-delay` metadata item:

```
$ vipsheader -a 3198.gif 
3198.gif: 298x193 uchar, 3 bands, srgb, gifload
width: 298
height: 193
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: 3198.gif
vips-loader: gifload
page-height: 193
n-pages: 139
gif-delay: 3
gif-loop: 0
```

It's the inter-frame delay in centiseconds. It works for animated webp as well in libvips 8.8.

**Comment by jcupitt** [comment]
It's an int, I should have said, so in C++:

```
int old_delay = image.get("gif-delay");
image.set("gif-delay", 12);
```

**Comment by deftomat** [comment]
🎉  Easier then I thought!

Thank you very much for an almost instant response.

Also, thanks for an animated webp in v.8.8. 👍

**Comment by jcupitt** [comment]
No problem. It should probably be milliseconds rather than centiseconds :(
