### ISSUE TITLE
.gif to .webp conversion

### ISSUE THREAD

**Issue by alexxozo** [libvips/libvips#1303]
Hello, is it possible to convert a gif to an animated webp?

**Comment by jcupitt** [comment]
Hello @alexxozo,

Support for animated webp is a feature in 8.8, due in few weeks. There's an example here:

https://libvips.github.io/libvips/2019/04/22/What's-new-in-8.8.html

You can built git master yourself of course, if don't want to wait.

**Comment by alexxozo** [comment]
Thank you for the prompt response @jcupitt !
