### ISSUE TITLE
Issue in running libvips cpp sample program 

### ISSUE THREAD

**Issue by HackersSpirit** [libvips/libvips#1305]
Hi,
I am trying to run the below sample  cpp program using qt creator:
https://jcupitt.github.io/libvips/API/current/using-from-cpp.html
I have downloaded vips-dev-w64-all-8.8.0-rc1a.zip file.

Sample pro file:
QT += core
QT -= gui

CONFIG += c++11

TARGET = libvipsdemo1
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += main.cpp
win32: LIBS += -L$$PWD/../../../../../../vips-dev-8.8/lib/ \
               -llibasprintf

INCLUDEPATH += $$PWD/../../../../../../vips-dev-8.8/include
DEPENDPATH += $$PWD/../../../../../../vips-dev-8.8/include

When i build the program i get the following error:
 Cannot open include file: 'glib-object.h': No such file or directory

After resolving the above dependencies i the pro file becomes like:
INCLUDEPATH +=C:/vips-dev-8.8/include/glib-2.0
INCLUDEPATH +=C:/vips-dev-8.8/lib/glib-2.0/include

But then i get the following error:

main.obj : error LNK2019: unresolved external symbol g_log referenced in function main
main.obj : error LNK2019: unresolved external symbol vips_error referenced in function main
main.obj : error LNK2019: unresolved external symbol vips_error_exit referenced in function main
main.obj : error LNK2019: unresolved external symbol vips_init referenced in function main
main.obj : error LNK2019: unresolved external symbol vips_shutdown referenced in function main
main.obj : error LNK2019: unresolved external symbol vips_version referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VOption * __cdecl vips::VOption::set(char const *,int)" (__imp_?set@VOption@vips@@QEAAPEAV12@PEBDH@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VOption * __cdecl vips::VOption::set(char const *,char const *)" (__imp_?set@VOption@vips@@QEAAPEAV12@PEBD0@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl vips::VImage::width(void)const " (__imp_?width@VImage@vips@@QEBAHXZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class vips::VOption * __cdecl vips::VImage::option(void)" (__imp_?option@VImage@vips@@SAPEAVVOption@2@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class vips::VImage __cdecl vips::VImage::new_from_file(char const *,class vips::VOption *)" (__imp_?new_from_file@VImage@vips@@SA?AV12@PEBDPEAVVOption@2@@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl vips::VImage::write_to_file(char const *,class vips::VOption *)const " (__imp_?write_to_file@VImage@vips@@QEBAXPEBDPEAVVOption@2@@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: double __cdecl vips::VImage::avg(class vips::VOption *)const " (__imp_?avg@VImage@vips@@QEBANPEAVVOption@2@@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VImage __cdecl vips::VImage::embed(int,int,int,int,class vips::VOption *)const " (__imp_?embed@VImage@vips@@QEBA?AV12@HHHHPEAVVOption@2@@Z) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl vips::VImage::~VImage(void)" (__imp_??1VImage@vips@@QEAA@XZ) referenced in function main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VImage & __cdecl vips::VImage::operator=(class vips::VImage &&)" (__imp_??4VImage@vips@@QEAAAEAV01@$$QEAV01@@Z) referenced in function main
debug\libvipsdemo1.exe : fatal error LNK1120: 16 unresolved externals

**Comment by kleisauke** [comment]
I had a go with Qt Creator on Windows. This .pro file seems to work for me:
```
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        main.cpp

LIBS += -LC:/vips-dev-8.8/lib -lvips-cpp -lvips -lglib-2.0 -lgobject-2.0

INCLUDEPATH += C:/vips-dev-8.8/include
INCLUDEPATH += C:/vips-dev-8.8/include/glib-2.0
INCLUDEPATH += C:/vips-dev-8.8/lib/glib-2.0/include

DEPENDPATH += C:/vips-dev-8.8/include
```
(so you must explicitly link with `-lvips-cpp -lvips -lglib-2.0 -lgobject-2.0`)

Example program:
```cpp
#include <iostream>
#include <vips/vips8>

using vips::VImage;

int main(int argc, const char *argv[])
{
    if (argc < 3) {
        std::cout << argv[0] << " input output"
                  << std::endl;
        return 1;
    }

    if (vips_init(argv[0]) != 0) {
        vips_error_exit(nullptr);
    }

    VImage thumb = VImage::thumbnail(argv[1], 200);
    thumb.write_to_file(argv[2], VImage::option()->set("strip", true));

    vips_shutdown();

    return 0;
}
```

By running the above program with [this image](https://commons.wikimedia.org/wiki/File:Equus_quagga_burchellii_-_Etosha,_2014.jpg), the size will be adjusted to 200 pixels wide:
![output](https://user-images.githubusercontent.com/12746591/57134989-386b4c00-6da8-11e9-9b25-24e5443d5220.jpg)

**Comment by jcupitt** [comment]
Hello @HackersSpirit,

You'll probably have a couple of issues to get past:

## C++ ABI 

C++ compilers do not have a standard ABI, so you need to build every component in a C++ project with the same version of the same compiler. The C++ DLL in libvips-all was built with g++ 8.3, so you'll need to use that, plus the matching runtime.

```
$ x86_64-w64-mingw32-g++-win32 --version
x86_64-w64-mingw32-g++-win32 (GCC) 8.3-win32 20190406
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If you want to build with MSVC (for example), you'll need to recompile the C++ interface to libvips. This isn't hard, and this is the route that node bindings on Windows take. You can also just use the plain C API.

## Compiler flags

On *nix systems, `pkg-config` will generate the compiler flags for libraries for you. On Windows, you need to make them yourself.

When I build libvips, it ends up using this to compile `vips.c`:

```
x86_64-w64-mingw32-gcc-win32 -DHAVE_CONFIG_H -I. -I..  -I../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -mms-bitfields -I/home/john/GIT/build-win64/8.8/inst/lib/glib-2.0/include -I/home/john/GIT/build-win64/8.8/inst/include/poppler/glib -I/home/john/GIT/build-win64/8.8/inst/include/poppler -I/home/john/GIT/build-win64/8.8/inst/include/pixman-1 -I/home/john/GIT/build-win64/8.8/inst/include/pango-1.0 -I/home/john/GIT/build-win64/8.8/inst/include/openslide -I/home/john/GIT/build-win64/8.8/inst/include/libxml2 -I/home/john/GIT/build-win64/8.8/inst/include/librsvg-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/libpng16 -I/home/john/GIT/build-win64/8.8/inst/include/libgsf-1 -I/home/john/GIT/build-win64/8.8/inst/include/harfbuzz -I/home/john/GIT/build-win64/8.8/inst/include/glib-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/gdk-pixbuf-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/freetype2 -I/home/john/GIT/build-win64/8.8/inst/include/cairo -I/home/john/GIT/build-win64/8.8/inst/include/ImageMagick-6 -D_DLL -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0      -I/home/john/GIT/build-win64/8.8/inst/include  -O3 -MT vips.o -MD -MP -MF $depbase.Tpo -c -o vips.o vips.c
```

And this to link `vips.exe`:

```
x86_64-w64-mingw32-gcc-win32 -O3 -o .libs/vips.exe vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -mms-bitfields -I/home/john/GIT/build-win64/8.8/inst/lib/glib-2.0/include -I/home/john/GIT/build-win64/8.8/inst/include/poppler/glib -I/home/john/GIT/build-win64/8.8/inst/include/poppler -I/home/john/GIT/build-win64/8.8/inst/include/pixman-1 -I/home/john/GIT/build-win64/8.8/inst/include/pango-1.0 -I/home/john/GIT/build-win64/8.8/inst/include/openslide -I/home/john/GIT/build-win64/8.8/inst/include/libxml2 -I/home/john/GIT/build-win64/8.8/inst/include/librsvg-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/libpng16 -I/home/john/GIT/build-win64/8.8/inst/include/libgsf-1 -I/home/john/GIT/build-win64/8.8/inst/include/harfbuzz -I/home/john/GIT/build-win64/8.8/inst/include/glib-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/gdk-pixbuf-2.0 -I/home/john/GIT/build-win64/8.8/inst/include/freetype2 -I/home/john/GIT/build-win64/8.8/inst/include/cairo -I/home/john/GIT/build-win64/8.8/inst/include/ImageMagick-6 -D_DLL -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0  -L/home/john/GIT/build-win64/8.8/inst/lib ../libvips/.libs/libvips.dll.a -lMagickCore-6.Q16 -lpng16 -ltiff -ljpeg -lgmodule-2.0 -lexpat -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgsf-1 -lxml2 -lfftw3 -llcms2 -lgif -lrsvg-2 -lgdk_pixbuf-2.0 -lpoppler-glib -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo -lopenslide -lwebpmux -lwebpdemux -lwebp -lmatio -lz -lexif -L/home/john/GIT/build-win64/8.8/inst/lib
```

Those are generated automatically, so they can probably be simplified a bit if you're doing it by hand. Anyway, it'll be something like that, but with extras if you want to use the C++ interface.

**Comment by jcupitt** [comment]
Oop, accidental close.

**Comment by jcupitt** [comment]
Oh heh thanks Kleis!

**Comment by HackersSpirit** [comment]
@kleisauke @jcupitt : Thanks for the response.
@kleisauke : I cannot find the following files in the development folder:
vips-cpp  glib-2.0  gobject-2.0

@jcupitt : For your above explanation above what i understand is i have to build libvips on my windows machine before using it my program. Please let me know in misunderstood.
Also how can i make the use of C_API directly in my program

**Comment by jcupitt** [comment]
Qt Creator is based on gcc, it seems a compatible version, so the libvips binary should work. 

`-lvips-cpp` means link against the vips-cpp library, not a file called vips-cpp.

**Comment by jcupitt** [comment]
Sorry, it posted early, stupid laptop touchpad.

If you want to use the libvips C++ API with MSVC, you will need to rebuild the C++ API parts of libvips from source using your compiler (it's not difficult). You can use g++ 8.3 with Qt Creator and skip this step.

For example, these files are in the zip for `-lvips-cpp`:

```
john@kiwi:~/Desktop/x/vips-dev-8.8-rc1b$ find . -name "*vips-cpp*"
./bin/libvips-cpp-42.dll
./lib/libvips-cpp.def
./lib/libvips-cpp.a
./lib/pkgconfig/vips-cpp.pc
./lib/libvips-cpp.dll.a
./lib/libvips-cpp.lib
```

**Comment by HackersSpirit** [comment]
@jcupitt : Thanks  a lot for clear explanation. 
Actually i am building a project in which libvips is  a part and their are other library which depends on MSVC, so i need to run libvips using MSVC.
Their of couple of questions can you please provide a clarity over the same:
1. I am using MSVC 2015 . I will figure a way to build the lib file but is their existing link which i can follow 
would be more helpful.
2. What if i want to use plain C api will i have to follow all these steps. Currently i need to process and save dzi image.
Thanks in advance

**Comment by jcupitt** [comment]
I've not rebuilt the C++ API myself, but it's just these three files plus their includes:

https://github.com/libvips/libvips/tree/master/cplusplus

The C++ API automates object unref, makes vips calls into member functions and adds exceptions, so you have to handle all that yourself if you use the C API. Eg.:

```C
VipsImage *image = vips_image_new_from_memory (data.pointer(), data.size(),
    width, height, bands, VIPS_FORMAT_UCHAR);
if (vips_dzsave (image, "filename", 
    "overlap", 0,
    NULL))
    handle_error();
g_object_unref (image);
```

**Comment by jcupitt** [comment]
@lovell, sorry to ping you, and I think I've asked this before, but do you have some notes somewhere on building the libvips C++ API in MSVC?

**Comment by lovell** [comment]
Sharp uses the following `gyp` config that creates a `.vcxproj` project file to compile `vips-cpp.dll` on Windows:

https://github.com/lovell/sharp/blob/05d76eeadfe54713606a615185b2da047923406b/binding.gyp#L3-L37

The discussion at #508 might help here too.
