### ISSUE TITLE
Comparing performance with cv2 on Mac OSX

### ISSUE THREAD

**Issue by karanchawla** [libvips/libvips#1307]
System: Mac OS XP
Processor: 2.5 GHz Intel Core i7
Memory: 8Gb 

I'm trying to compare the `write_to_file` function's performance with opencv's `imwrite` function and it looks like pyvips performs worse than `imwrite` even though the benchmark says it's about 6 times faster than opencv. 

Here's the sample code I'm running:
```
import pyvips
 import cv2

 def process_cv_img():
     cv_img = cv2.imread('test.jpg')
     cv2.imwrite('cv_img.jpg', cv_img, [int(cv2.IMWRITE_JPEG_QUALITY), 100])

 def process_pyvips_img():
     lycon_img = pyvips.Image.new_from_file('test.jpg', access='sequential')
     lycon_img.write_to_file('lycon_img.jpg', Q=100)

 def main():
     for i in range(10):
         process_cv_img()
         process_pyvips_img()
```

On average the `write_to_file` operation takes 1.24 seconds whereas the `imwrite` operation takes 0.46 seconds. 

Am I missing something obvious here?

**Comment by lovell** [comment]
Hello, is there some code missing from this example? It appears to be doing a JPEG decode/encode roundtrip but with no further processing. If so, this isn't really testing either OpenCV or libvips.

A difference in JPEG library performance would suggest that OpenCV was linked against libjpeg-turbo and libvips linked against libjpeg.

It's also possible that OpenCV might not be using the same libjpeg chroma subsampling settings as libvips when the quality setting is maxed out at 100.

**Comment by jcupitt** [comment]
pyvips should be about 2x faster than cv2 in this case, since pyvips can run the decode and encode in  parallel. I tried this benchmark:

```python
#!/usr/bin/python3
  
import timeit
import sys
import pyvips
import cv2

def run_vips():
    img = pyvips.Image.new_from_file(sys.argv[1], access='sequential')
    img.write_to_file(sys.argv[2]) 

def run_cv2():
    img = cv2.imread(sys.argv[1])
    cv2.imwrite(sys.argv[2], img)

vips_time = timeit.timeit('run_vips()', 'from __main__ import run_vips', 
                          number=100)
print("vips time: %f" % vips_time)

cv2_time = timeit.timeit('run_cv2()', 'from __main__ import run_cv2', 
                         number=100)
print("cv2 time: %f" % cv2_time)
```

And on this laptop I see:

```
$ ./vips-vs-cv2.py ~/pics/k2.jpg x.jpg
vips time: 2.425389
cv2 time: 5.113483
```

As Lovell says, at Q > 90 libvips disables chroma subsample, which would explain some of the difference you see. And libvips installed via homebrew will not use libjpeg-turbo.

**Comment by karanchawla** [comment]
@lovell Thank you these comments help a lot. As you guessed it CV and libvips were linked against different libraries. I fixed that and could see better performance. 

@jcupitt Thanks for. The benchmarking example you gave is however, not comparing apples to apples since the default quality for `cv2.imwrite` is 95 and the default Q value for `pyvips` 
`jpegsave` is 75. 

A more accurate comparison would be 
```
#!/usr/bin/python3
  
import timeit
import sys
import pyvips
import cv2

def run_vips():
    img = pyvips.Image.new_from_file(sys.argv[1], access='sequential')
    img.write_to_file(sys.argv[2]) 

def run_cv2():
    img = cv2.imread(sys.argv[1])
    cv2.imwrite(sys.argv[2], img, [int(cv2.IMWRITE_JPEG_QUALITY), 75])

vips_time = timeit.timeit('run_vips()', 'from __main__ import run_vips', 
                          number=100)
print("vips time: %f" % vips_time)

cv2_time = timeit.timeit('run_cv2()', 'from __main__ import run_cv2', 
                         number=100)
print("cv2 time: %f" % cv2_time)
```

**Comment by jcupitt** [comment]
Maybe it depends on the cv2 version? I added the Q75 option and didn't see a significant difference here. 

I have:

```
$ pkg-config opencv --modversion
3.2.0
```
