### ISSUE TITLE
Ghosting created around repeated images in pdf

### ISSUE THREAD

**Issue by brandoncc** [libvips/libvips#1308]
I work on an application where we create PDFs with lots of duplicated repeatable images that form a cohesive background image. The PDF looks correct, but when I convert the pdf to a jpg, there is ghosting around each repeated image. I have attached an example PDF as well as the JPG that is created.

This is the code used to create this JPG file:

```ruby
image = Vips::Image.pdfload("/Users/brandoncc/Downloads/preview with background image.pdf")
image.write_to_file("/Users/brandoncc/Downloads/preview with background image.jpg")
```

I'm not applying a resize to the PDF, so I am surprised by this. Is there something I can do to fix it?

[preview with background image.pdf](https://github.com/libvips/libvips/files/3163047/preview.with.background.image.pdf)
![preview with background image](https://user-images.githubusercontent.com/543973/57469258-1277f880-723b-11e9-8298-6096a74cb802.jpg)

**Comment by jcupitt** [comment]
Hello @brandoncc,

Sorry, this is just how poppler (the library libvips uses for PDFs) renders your PDF. It looks the same in evince, for example, the desktop PDF viewer based on poppler.

I put your PDF here:

http://www.rollthepotato.net/~john/preview.with.background.image.pdf

And it also looks like that in firefox. Chrome doesn't draw the white lines at all, but it does have the black ones.

**Comment by brandoncc** [comment]
Ah, the old poppler biting me again. Thanks for helping me narrow it down. I'll see if I can find a way to get help from the poppler team (if there is such a thing). Thanks John!

**Comment by jcupitt** [comment]
@brandoncc Hi Brandon, I noticed your buildpack is still on 8.7.1. Would you mind bumping libvips to 8.8.1? It adds some useful security fixes. 

It might be a good idea to enable issues on the repo as well.

**Comment by brandoncc** [comment]
@jcupitt thank you for the heads up. I will put this on my todo list, and I will enable issues. Sorry for the delayed response.

**Comment by brandoncc** [comment]
@jcupitt I updated the buildpack and enabled issues. I also subscribed to releases for this repo so I can keep the buildpack up to date.

Thanks again.
