### ISSUE TITLE
Cannot convert PNGs to TIFF files

### ISSUE THREAD

**Issue by evanmcallaway** [libvips/libvips#1310]
Encountered on latest master.  This issue is not present when on version 8.7.

`vips copy test.png test.tiff` gives an error `VipsImage: field "xmp-data" is of type VipsRefString, not VipsBlob`

**Comment by jcupitt** [comment]
Hello @evanmcallaway, there have been problems with that during development, but current git master seems to work for me.

```
john@yingna ~/pics $ vipsheader -a summer.tif | grep xmp
xmp-data: 4649 bytes of binary data
john@yingna ~/pics $ vips copy summer.tif x.png
john@yingna ~/pics $ vips copy x.png x.tif
```

Do you have a test image where it fails?

**Comment by evanmcallaway** [comment]
Here's a sample image that I cannot convert to TIFF.  If it makes a different it's a greyscale image that I'm using for alpha compositing.

![test](https://user-images.githubusercontent.com/5093359/57707483-b4ca1e80-7635-11e9-8ded-2e98b826a94b.png)

**Comment by jcupitt** [comment]
It seems to be working for me.

```
john@yingna ~/pics $ vipsheader -a mono-xmp.png 
mono-xmp.png: 10750x7559 uchar, 1 band, b-w, pngload
width: 10750
height: 7559
bands: 1
format: uchar
coding: none
interpretation: b-w
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: mono-xmp.png
vips-loader: pngload
xmp-data: 1249 bytes of binary data
john@yingna ~/pics $ vips copy mono-xmp.png x.tif
john@yingna ~/pics $ 
```

Could you be using a slightly older libvips?

**Comment by evanmcallaway** [comment]
Should be current.  I just pulled latest master.
`$ vips --vips-version`
`libvips 8.8.0-Tue May 14 13:51:14 UTC 2019`

**Comment by evanmcallaway** [comment]
```
evan@evan-VirtualBox:~/dev/channels/h5117/channels$ vipsheader -a test.png
test.png: 10750x7559 uchar, 1 band, b-w, pngload
width: 10750
height: 7559
bands: 1
format: uchar
coding: none
interpretation: b-w
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: test.png
vips-loader: pngload
xmp-data: <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c145 79.163499, 2018/08/13-16:40:22        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:a...
evan@evan-VirtualBox:~/dev/channels/h5117/channels$ vips copy test.png out.tiff
VipsImage: field "xmp-data" is of type VipsRefString, not VipsBlob
```

**Comment by jcupitt** [comment]
It looks like the PNG reader is attaching xmp as a string rather than as a blob (xmp needs to be binary data). This was changed earlier in the development of 8.8:

https://github.com/libvips/libvips/blob/master/libvips/foreign/vipspng.c#L286

That code was using strings previously. It was swapped to blob in November 2018.

https://github.com/libvips/libvips/commit/b2325697c3cdb9be9b2f11ae4c572f6bfc341c33#diff-ea46133a4356957d60a9c7298740b07b

**Comment by evanmcallaway** [comment]
In that case I must have a broken build.  I'll clean everything and start from scratch.

Thanks for taking a look @jcupitt
