### ISSUE TITLE
Heif thumbnail unreadable when too small

### ISSUE THREAD

**Issue by t089** [libvips/libvips#1312]
Not sure if I am doing something wrong, but using the newest libvips 8.8.0 when thumbnailing [this](https://static.holidu.com/cms/7007/l/799.jpg) image, I get an unreadable file as output, if the width is too small.

This works and produces an image with a width of 400 pixels
`vips thumbnail 799.jpg x.heic 400`

while this produces a file `x.heic` that cannot be opened on my Mac (10.14.5)
`vips thumbnail 799.jpg x.heic 100`

```
$ vips --version
vips-8.8.0-Sat May 11 11:55:18 UTC 2019
```

**Comment by jcupitt** [comment]
Hi @t089, I agree, it looks like a problem in `heicsave`.

```shell
$ vipsthumbnail 799.jpg -o x.tif
$ vipsheader x.tif 
x.tif: 128x53 uchar, 3 bands, srgb, tiffload
$ vips copy x.tif x.heic
$ vipsheader x.heic 

(vipsheader:7393): GLib-GObject-WARNING **: 13:11:57.927: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(vipsheader:7393): GLib-GObject-WARNING **: 13:11:57.927: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
x.heic: 1x1 uchar, 3 bands, srgb, heifload
```

Thanks for reporting this, I'll have a look.

**Comment by jcupitt** [comment]
It looks like a problem with libheif. With git master libheif I see:

```
john@yingna ~/pics $ vips crop k2.png x.png 0 0 128 58
john@yingna ~/pics $ heif-enc x.png -o x.heic
Could not encode HEIF file: Encoder plugin generated an error: Invalid parameter value: Images smaller than 16 pixels are not supported
```

I've opened an issue here: https://github.com/strukturag/libheif/issues/130

**Comment by jcupitt** [comment]
There's a response from the libheif dev: this is a limitation in x265. It's been reported, but there's been no action yet. 

Workaround: don't use heif to store very small images.

**Comment by t089** [comment]
Hey John, Thanks for looking into this! Should we close?

**Comment by jcupitt** [comment]
Yes, I think so. There's not much libvips can do about it anyway.
