### ISSUE TITLE
Inverted colors after CMYK to sRGB conversion

### ISSUE THREAD

**Issue by dbouron** [libvips/libvips#1313]
Hello,
When i tried to convert color space CMYK to sRGB on this image:
![inverted](https://user-images.githubusercontent.com/21236440/58173255-2855d680-7c9b-11e9-959c-befff8fd554e.jpg)
It produced an image with inverted colors:
![out](https://user-images.githubusercontent.com/21236440/58173404-926e7b80-7c9b-11e9-9eaf-95447dc3aba1.jpg)

You can reproduce this issue with the following command and a libvips 8.8.0-rc1 with lcms2:
`$ vips colourspace inverted.jpg out.jpg srgb`

Also, if you try to load the original image and save the buffer with jpg format, it produces the same result.
This is because we execute the code inside the 'if-statement' [here](https://github.com/libvips/libvips/blob/master/libvips/foreign/vips2jpeg.c#L487) which inverts colors.
Do you have any ideas to fix it?

**Comment by jcupitt** [comment]
Hello @dbouron, this was fixed in rc2. It seems to work in 8.8.0 as released:

```shell
$ vips colourspace cmyk2.jpg x.png srgb
```

Makes:

![x](https://user-images.githubusercontent.com/580843/58180095-6229db80-7ca1-11e9-8e9e-49fac9fea35a.png)

**Comment by dbouron** [comment]
Hello,
Yes the latest libvips version fixed this problem.
Thank you
