### ISSUE TITLE
Unable to process image - "profile incompatible with image"

### ISSUE THREAD

**Issue by dkam** [libvips/libvips#1314]
Hi there, 
    What's the correct way to recover from this error : 

```
$ vipsthumbnail image.jpeg 

(vipsthumbnail:56142): VIPS-WARNING **: 11:13:30.752: profile incompatible with image
```

I get the same error in rubyvips. 

Identify seems to think it's sRGB, but imagemagick's resize creates a broken image.

```
$ identify -verbose image.jpeg 
Image: image.jpeg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 480x480+0+0
  Resolution: 300x300
  Print size: 1.6x1.6
  Units: PixelsPerInch
  Colorspace: sRGB
  Type: TrueColor
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
```

I've tried a few different input profiles:

```
$ vipsthumbnail image.jpeg --iprofile=lib/sRGBz.icc  
(vipsthumbnail:56266): VIPS-WARNING **: 11:17:17.321: profile incompatible with image

$ vipsthumbnail image.jpeg --iprofile=lib/tinyrgb.icc 
(vipsthumbnail:56277): VIPS-WARNING **: 11:17:26.379: profile incompatible with image

$ vipsthumbnail image.jpeg --iprofile=lib/cmyk.icm 
(vipsthumbnail:56311): VIPS-WARNING **: 11:18:23.673: profile incompatible with image
```

What's the right way to fix the profile?

**Comment by jcupitt** [comment]
Hello, could you post the broken image somewhere?

**Comment by dkam** [comment]
Sure. [Here](https://c.booko.info/covers/203239c2080e71ec/image.jpeg) and [another](https://c.booko.info/covers/87f6f2b955b9f9d2/image.jpeg)  and [another](https://c.booko.info/covers/a8d1ab8616981723/image.jpeg). I can provide more if needed.

**Comment by jcupitt** [comment]
I tried them with libvips 8.7.4 and they all worked, eg.:

```
$ vipsthumbnail bad-profile2.jpeg 
(vipsthumbnail:633): VIPS-WARNING **: 10:14:39.939: profile incompatible with image
```

Which version are you using?

**Comment by dkam** [comment]
I'm sorry - it looks like I wasn't careful enough - it does actually generate a thumbnail. The actual issue I have is in RubyVips when attempting resize - I assumed the error returned by vipsthumbnail was the same error as rubyvips Vips::Image.thumbnail:

```
VIPS-WARNING **: 19:58:46.411: embedded profile incompatible with image
Vips Error /1: #<Vips::Error: icc_transform: no input profile
```
I'll investigate further and open an issue in the RubyVips repository.
