### ISSUE TITLE
Opening JPEG2000 image leads to: magickload: unsupported colorspace 19 

### ISSUE THREAD

**Issue by Necklaces** [libvips/libvips#1315]
Hi, I have a hunch this is just a build issue, but just in case it isnt I'm making this issue to get your opinion(s).

[517122.jp2.zip](https://github.com/libvips/libvips/files/3211101/517122.jp2.zip)

The above (zipped) image is a JPEG2000, 3-component image with 8 bits/channel. The only weird thing about it is that it has 4 tiles with unnecessary reproduction of coding parameters from the main header in each non-initial tile-part header.

If I try to thumbnail it it gives:
```
vipsthumbnail 517122.jp2
vipsthumbnail: unable to thumbnail 517122.jp2
magickload: unsupported colorspace 19
```

As far as I understand libvips uses imagemagick to load the JPEG2000 image (via [magickload.c](https://github.com/libvips/libvips/blob/master/libvips/foreign/magickload.c)?), ImageMagick in turn uses OpenJPEG to load the image.

The weird thing is that this should already have been fixed in OpenJPEG: https://github.com/uclouvain/openjpeg/commit/98cfdd31340509895f3e2a36f667f66bb3cf1ff2

Building and installing OpenJPEG with a version after that commit results in OpenJPEG sucessfully loading the image as demonstrated with opj_decompress:

```
opj_decompress -i 517122.jp2 -o 517122.png
[...]
[INFO] Generated Outfile 517122.png
decode time: 139 ms
```

Same goes for imagemagick itself after that is built and linked to the latest openjpeg:

```
convert 517122.jp2 517122.png
```

517122.png is then viewable with no defects.

This is what I've tried:

1. Build latest git revision (master) of OpenJPEG with the COD marker fix.
2. Build latest git revision (master) of ImageMagick making sure it links to OpenJPEG
3. Build latest git revision (master) of Libvips making sure it links to ImageMagick

But no dice. I don't get why it doesn't work, thoughts?

**Comment by jcupitt** [comment]
Hello @Necklaces, just a guess, but could it be openslide? That also links to openjpeg, so unless you rebuild that too, you could end up pulling in an old version.

You can check which version of a lib an executable is pulling in at runtime with `ldd`, eg. 

```
ldd $(which vips) | grep -i jpeg
```

**Comment by Necklaces** [comment]
I saw the issue mentioning that so I'm compiling libvips with 

```
./configure --without-poppler  --without-openslide
```
` ldd $(which vips) | grep -i jpeg` gives me 
```
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fc151b61000)
```

**Comment by jcupitt** [comment]
Ooop, I got the lib name wrong, try:

```
ldd $(which vips) | grep -i jp2
```

**Comment by Necklaces** [comment]
I actually get nothing when I run `ldd $(which vips) | grep -i jp2`.. hmm

**Comment by jcupitt** [comment]
On ubuntu 19.04 I see:

```
john@kiwi:~$ ldd $(which vips) | grep -i jp2
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007fbe9c83f000)
```

**Comment by Necklaces** [comment]
Not sure what's wrong with my work setup, but on my home computer I get this now:

```
ldd $(which vips) | grep -i jp2
	libopenjp2.so.7 => /usr/local/lib/libopenjp2.so.7 (0x00007fcdca551000)
```

But I still get the same error. Just to make sure; have you tried vipsthumbnail against the image I uploaded? Did it work?

Gonna try on a ubuntu vm next, just to make sure.

**Comment by jcupitt** [comment]
I tried openjpeg 2.3.0-rc3 (the one on alpine) and it failed with some message about more than one CON2 block. I'll try with 2.3.1 (current stable) tomorrow.

**Comment by jcupitt** [comment]
Right, finally built everything. I get the `unsupported colorspace 19` error. I changed libvips to output a meaningful name instead and I now get `magickload: unsupported colorspace Rec601YCbCrColorspace`.

I'm not sure what to do about this. libvips does not support YCbCr directly. It would be (guess) half a day's work to add. It would probably be better to add proper jp2k support rather than going via ImageMagick, and then get OpenJPEG to do the conversion to RGB.

**Comment by jcupitt** [comment]
It seems to be just this image -- other jp2k images I have seem to work:

```
$ vipsheader sekscir25.jp2 
sekscir25.jp2: 10726x9147 uchar, 3 bands, srgb, magickload
$ vips copy sekscir25.jp2 x.jpg
$
```

**Comment by Necklaces** [comment]
Yeah so it's not just me, good to know at least! Thank you for troubleshooting with me!

This is unfortunately an image from a very specialized scanner that has a CFW from its vendor. Really is a shame that it produces these kinds of images, as we've almost always had problems with them, nevertheless they do seem to follow the jpeg2000 standard. Both OpenJPEG and Kakadu is able to handle them.

**Comment by jcupitt** [comment]
In the short-term at least I guess you'll have to go via something like TIFF.
