### ISSUE TITLE
msvcrt.dll related error - vips 8.8 (the all version) can't run on Win7 64

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1317]
Just run 
```vips -v```
upon This latest build vips-dev-w64-all-8.8.0

get error
can't locate entry point _free_locale in msvcrt.dll

![image](https://user-images.githubusercontent.com/73845/58489244-72f4b880-819d-11e9-8b84-faaa9a5536c8.png)

Tested on two machine of sytem Win7 Sp1 64bit,
both got the same error

another build vips-dev-w64-web-8.8.0 runs fine and returns version string:
vips-8.8.0-Sat May 11 11:55:18 UTC 2019

**Comment by jcupitt** [comment]
Oh, interesting, I've not tested on win7. I'll see if I can find what's calling free_locale().

**Comment by jcupitt** [comment]
Looks like it's harfbuzz, or perhaps ImageMagick. 

Could you test vips-dev-w64-web? If that works, then it's almost certainly ImageMagick.

https://github.com/libvips/libvips/releases/download/v8.8.0/vips-dev-w64-web-8.8.0.zip

**Comment by jindili** [comment]
vips-dev-w64-web-8.8.0 runs fine and returns version string:
vips-8.8.0-Sat May 11 11:55:18 UTC 2019

**Comment by jcupitt** [comment]
So it's a problem with the way ImageMagick has been built. I'll see if there's some way to make it work on win7.

**Comment by kleisauke** [comment]
Looks like this has already been reported to ImageMagick, see: https://github.com/ImageMagick/ImageMagick6/issues/42.

We could try to apply the patch mentioned in that issue.

**Comment by jcupitt** [comment]
OK, I've applied their patch and it's building now. I'll upload a test build once it's done.

The patch is very drastic: it simply disables all locale support in imagemagick. You could probably do something a bit neater than that, but it's good enough for now.

**Comment by jcupitt** [comment]
Could you test this build on win7 please jindili?

http://www.rollthepotato.net/~john/vips-dev-w64-transform-8.8.0.zip

**Comment by jindili** [comment]
Hi, John, It works now.

vips -v now runs fine and return:
vips-8.8.0-Sat May 11 11:55:18 UTC 2019

**Comment by jcupitt** [comment]
Oh great!

There should be a new libvips build fairly soon with this fix.

**Comment by toybuilder** [comment]
Ah, I ran into this problem today -- except I didn't know it at first because I was working inside a shell session launched under emacs and it silently swallowed the modal dialog from ever appearing.  It was only just a little while ago that I tried running under a fresh cmd console session that I got this error.

I also was able to get the build you made yesterday to work!

**Comment by kleisauke** [comment]
ImageMagick has applied the patch with commit https://github.com/ImageMagick/ImageMagick6/commit/b2de75c03d1a9dd6b36a5f0cf5503a0baabc2f02. 

As it disabled locale support, I was a little concerned that it was no longer possible to read images from non-ASCII filenames. But this still seems to work:
```
magick.exe convert -identify йцук.jpg x.png
Ð¹Ñ┼ÑƒÐº.jpg JPEG 1024x768 1024x768+0+0 8-bit sRGB 180667B 0.000u 0:00.008

magick.exe identify x.png
x.png PNG 1024x768 1024x768+0+0 8-bit sRGB 617076B 0.000u 0:00.000
```

I guess it's safe to update to ImageMagick-6.9.10-50 (which should contain this fix) within the `build-win64` repository.

**Comment by jindili** [comment]
Just tested, the newly released version:
vips-dev-w64-all-8.8.1.zip

has the same issue on Win7 sp1 64 bit.

**Comment by jcupitt** [comment]
Ooop, forgot to update IM in build-win64. I'll rebuild now, thanks for pointing this out.

**Comment by jcupitt** [comment]
There's now a 8.8.1a with the updated IM. Hopefully this will work.

**Comment by jindili** [comment]
Just tested, it works !

```
vips -v
```
get output:
```
vips-8.8.1-Sun Jul  7 10:04:59 UTC 2019
```

**Comment by jcupitt** [comment]
Great! I'll close

Yes, it's a new build, not a new version.

**Comment by jcupitt** [comment]
Also, nice work finding that IM patch, Kleis.
