### ISSUE TITLE
tif save incomplete

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1318]
using pyvips latest on win7 sp1 64bit
vips version: vips-8.7.4-Fri Jan 18 12:51:47 UTC 2019

pyvips code:

```
import os
import pyvips

# change to the directory of shape.pdf
os.chdir(r"C:\test\tifSaveError")

shape = pyvips.Image.pdfload("shape.pdf", dpi=50)
size_design = shape.height * 2
shape_extend = shape.gravity("south", size_design, size_design, extend="white")
shape_extend.write_to_file("shape_extend.jpg")
shape_extend.write_to_file("shape_extend.png")
shape_extend.write_to_file("shape_extend.tif")
```
attached the pdf file used (3kb of size):
[shape.pdf](https://github.com/libvips/libvips/files/3230354/shape.pdf)

![image](https://user-images.githubusercontent.com/73845/58523040-7fa4fb00-81f5-11e9-85cb-506f947976c9.png)

the saved jpg and png file is correct, but the tif file is incomplete, only top half part.
![image](https://user-images.githubusercontent.com/73845/58523108-d6123980-81f5-11e9-8643-e24addde6d45.png)

**Comment by jcupitt** [comment]
Hi Jindili, it's saved it as a multi-page TIFF. I'll change this behaviour for 8.8.1 to make it less likely to happen by accident.

As a workaround, add:

```
shape.remove("page-height")
```

Just after the `pdfload`.

**Comment by jcupitt** [comment]
OK, 8.8.1 will have nicer behaviour here and you won't need the `remove()` line. Thanks for reporting this!

**Comment by jindili** [comment]
It works! Thanks John.

I use this line before version 8.8.1 is released.
