### ISSUE TITLE
Tiff measure of cmyk

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1319]
Hi John,
Tried using vip's measure to measure a strip and when compared with gimp getting similar results for RGB. But how to get CMYK values, if the input tiff is a CMYK, (profile not saved in tiff). Tried few options but got only rgba values by mentioning cmyk.icm.  Can we get values with PDF input too.

**Comment by jcupitt** [comment]
Sure, this should work. 

In Python, for example:

```
john@kiwi:~/pics$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("cmyk-no-profile.jpg")
>>> x.getpoint(0, 0)
[43.0, 17.0, 21.0, 0.0]
```

Those four numbers are C, M, Y, K for pixel (0, 0).

**Comment by vkkindia** [comment]
Thanks John,
tried from a sample image
--------------
import pyvips
x = pyvips.Image.new_from_file("Frog_logo_CMYK_55_0_61_28.jpg",
access="sequential" )
point = x.getpoint(400, 360)
print('point {0}'.format(point)
--------------------
But in gimp I get 55_0_61_28 for cmyk. but vips shows as
point [177.0, 0.0, 254.0, 0.0]

**Comment by jcupitt** [comment]
GIMP will have done some processing on those values. Perhaps it has applied a default profile?

libvips is showing the exact pixel values stored in the file.
