### ISSUE TITLE
As a new discoverer of VIPS looking for moasic tools, the term "bands" was confusing

### ISSUE THREAD

**Issue by toybuilder** [libvips/libvips#1323]
I just discovered VIPS, evaluating it for a project which requires creating mosaics.  As I had just jumped right into the mosaic documentation, and don't have prior experience with VIPS, I was confused by the way the term "bands" were being used.  
After poking around for a while, I finally realized that "bands" are (in common paralance) color channels.  
At first, I thought bands were referring to stripes of data (a subregion).  Clearly, that's not the case.
May I suggest adding the definition of bands into the annotations-glossary?

**Comment by toybuilder** [comment]
While on the subject of being new to VIPS and looking at the docs with fresh eyes, I noticed in the description for mosaic:

> dx and dy give the displacement of sec relative to ref , in other words, the vector to get from the origin of sec to the origin of ref , in other words, dx will generally be a negative number.

I believe you mean dx will generally be a negative number for horizontal mosaic (default)?

**Comment by jcupitt** [comment]
Hello @toybuilder,

Yes, libvips inherited the "bands" name from HIPS, the system it was originally modelled on. The term is introduced in the docs, but it could be clearer. I'll add a note.

Yes, dx would be -ve for horizontal mosaics.

**Comment by toybuilder** [comment]
Thanks @jcupitt!  
And for vertical mosaic (which is what I normally do for the project I'm doing right now), that would be dy which would normally the negative displacement?

**Comment by jcupitt** [comment]
Yes, that's right.

The libvips mosaicing routines were written for the VASARI project. That had a camera on a translation stage moving in front of a painting, with everything lined up to within a few mm.

They should work OK for similar setups, perhaps a microscope stage or a scan back, but they won't work well for more free-form setups.

**Comment by toybuilder** [comment]
[VASARI]  Oh, interesting.  I actually have a potential project in the future for that very same application (scanning a painting)!  

I am still learning about VIPS, so I hope you don't mind a few more questions.  

So far, I have been using the CLI version of VIPS to get a feel for it.  I have successfully stitched a chain of jpg images into a good looking mosaic with good matching in the ROI.  Due to camera pointing issues on the test images, there is a small stair-step (as expected).  

Right now, I am iteratively appending an image to each successive mosaic so it looks like (5.jpg+(4.jpg+(3.jpg+(2.jpg+1.jpg)))))  -- where each term looks like:

vips mosaic 5.jpg 4321.v vertical 687 698 670 260 --hwindow 20 --harea 150 --dx0 --dy0

(I plan to do more of tree-based approach as you have suggested to others elsewhere)

I wanted to clean up the (very subtle) intensity discontinuities and tried to use the globalbalance, but am getting the message:
```
im_global_balance: mosaic root not found in desc file
is this really a mosaiced image?

```

Is this because I am using the command line version where each operation is a "closed" set of operation?  If I were to create the program where the images are opened into vipsimages (and the resulting mosaic as new vipsimages), would that problem go away?

**Comment by jcupitt** [comment]
Yes, use the py interface (for example) and globalbalance should work. 

Have you had a look at the libvips GUI, nip2? That has a mosaic example, including globalbalance.

Start up nip2, click File / Open Examples, double-click on `1_point_mosaic`, then load `1pt_mosaic.ws`.

**Comment by jcupitt** [comment]
In the workspace, B21 is the result of mosaicing, then B22 is after globalbalance. The C column then fixes the image gradient.

The images are from an IR tube camera, so complete correction is very tough. Things like gamma actually vary across the tube surface. You should get a better result with a CCD sensor.

**Comment by toybuilder** [comment]
Oh, wow, it didn't occur to me to look at nip2.  I just found the page with the Youtube video on it.  I'll start poking around on that!  Thank you!

Decades ago, when I was fresh out of school, I worked on the inverse problem -- sending images data to a monochrome CRT tube used as a photoplotter -- Unlike planar displays of today, the intensity was not uniform across the display surface!

**Comment by toybuilder** [comment]
I just fired up the Mosaic demo.  You could have heard my jaw hit the floor!  :)   This is great stuff!

I realize that I'm looking at this from a newbie perspective, but if there was a comment/link in the documentation that pointed to this nip2 demo, it would have answered so many questions right away.

**Comment by toybuilder** [comment]
Just wanted to let you know that with that hint to start with nip2, I was able to experiment and prototype the pipeline to generate the mosaic of my test images.  Once I got that to come out the way I want, I was able to reimplement that in C# using the NetVips binding!

Thank you very much!

**Comment by kleisauke** [comment]
I'm glad you figured out how to reimplement it in NetVips. For what it's worth, you can find the `1pt_mosaic.ws` example in NetVips here:
[samples/NetVips.Samples/Samples/OnePointMosaic.cs](https://github.com/kleisauke/net-vips/blob/master/samples/NetVips.Samples/Samples/OnePointMosaic.cs)
