### ISSUE TITLE
WebP compression in TIFF?

### ISSUE THREAD

**Issue by tumagonx** [libvips/libvips#1325]
libtiff-4.0.10 support webp, Does VIPS support compression parameter (like JPEG), webp format is badly limited in max. dimension it would be nice to see large TIFF image with tiled webp.

**Comment by jcupitt** [comment]
libvips does not support webp in tiff, but it would be simple to add. Some quick notes on the interface:

https://www.asmail.be/msg0055275680.html

**Comment by jcupitt** [comment]
Here's an experimental branch with webp in tiff support:

https://github.com/libvips/libvips/tree/add-tiff-webp-zstd

It seems to work, though it needs some tests still.

It supports tiling, so you can have webp-compressed images larger than 16k x 16k pixels:

```
$ vips copy openslide/CMU-1.svs x.tif[compression=webp,tile]
$ vipsheader x.tif
x.tif: 46000x32914 uchar, 4 bands, srgb, tiffload
```

Any testing would be great!

**Comment by tumagonx** [comment]
Thanks for the works!
I'm sorry can't test it in near time..

**Comment by jcupitt** [comment]
OK, let's merge to master and hope for testing when it's more widely available. Thanks!
