### ISSUE TITLE
Mimicking scipy's mirror boundary conditions for convolution?

### ISSUE THREAD

**Issue by erdmann** [libvips/libvips#1326]
Hi John,

I'm working on developing [Gaussian/Laplacian pyramids](https://docs.opencv.org/2.4/doc/tutorials/imgproc/pyramids/pyramids.html)  in vips, and I'm wondering the canonical way to mimic the 'mirror' mode found in [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html):
```
‘reflect’ (d c b a | a b c d | d c b a)
The input is extended by reflecting about the edge of the last pixel.

‘constant’ (k k k k | a b c d | k k k k)
The input is extended by filling all values beyond the edge with the 
same constant value, defined by the cval parameter.

‘nearest’ (a a a a | a b c d | d d d d)
The input is extended by replicating the last pixel.

‘mirror’ (d c b | a b c d | c b a)
The input is extended by reflecting about the center of the last pixel.

‘wrap’ (a b c d | a b c d | a b c d)
The input is extended by wrapping around to the opposite edge.
```
I see that I can use the `gravity` operation, but the `mirror` option in vips seems to be what scipy calls `reflect`, and I can't find the equivalent of scipy's `mirror` option.  

What's the right way to do this?

Many thanks in advance.

**Comment by jcupitt** [comment]
Hello Rob, I guess you could use the libvips `mirror` option, then move all the edges in one pixel. Would that do it?

It'd just be mirror, crop x 4, insert x 4.

**Comment by jcupitt** [comment]
Hree's how mirror is implemented:

https://github.com/libvips/libvips/blob/master/libvips/conversion/embed.c#L403

So you'd just need that, with a few -1 added.

**Comment by erdmann** [comment]
Thanks for the fast reply.  I can definitely manage it with various elemental operations if needed; I thought I might have overlooked an option somewhere.  

Assuming this doesn't slow down the pipeline much, I'll do it this way.

**Comment by jcupitt** [comment]
Yes, libvips does this kind of composition very efficiently, you won't see a speed hit.
