### ISSUE TITLE
write_to_memory are slow when run 90,000 times in image 192*192 pixel

### ISSUE THREAD

**Issue by xkxxfyf** [libvips/libvips#1327]
hi,thanks for provide vips. i met a problem when handle wholeslide(more than 40000*40000 pixel).
for saving memory,i split whole image into lots of tiles and follow step: read a tile to memory->turn tile object(pyvips.Image) to ndarray->handle ndarray->trun ndarray to tile object(pyvips.Image).
i find the whole processing need 300+sec ! Further testing i find pyvips.Image.write_to_memory take most time.it seems to be very slow when write small tiles many times.do i use it wrong?

code:

```python
FORMAT_TO_DTYPE = {
    'uchar': np.uint8,
    'char': np.int8,
    'ushort': np.uint16,
    'short': np.int16,
    'uint': np.uint32,
    'int': np.int32,
    'float': np.float32,
    'double': np.float64,
    'complex': np.complex64,
    'dpcomplex': np.complex128,
}

# map np dtypes to vips
DTYPE_TO_FORMAT = {
    'uint8': 'uchar',
    'int8': 'char',
    'uint16': 'ushort',
    'int16': 'short',
    'uint32': 'uint',
    'int32': 'int',
    'float32': 'float',
    'float64': 'double',
    'complex64': 'complex',
    'complex128': 'dpcomplex',
}

def image_to_array(wsi_img:pyvips.Image):
    mem_img = wsi_img.write_to_memory()
    np_3d = np.ndarray(buffer=mem_img,
                   dtype=FORMAT_TO_DTYPE[wsi_img.format],
                   shape=[wsi_img.height, wsi_img.width, wsi_img.bands])
    return np_3d
```

**Comment by jcupitt** [comment]
Hello @xkxxfyf,

libvips 8.8 has a new feature to speed up this type of problem. Have a look here:

https://github.com/libvips/pyvips/issues/100#issuecomment-493960943

On that benchmark anyway, the new `fetch` method gets a ~100x speedup.

**Comment by jcupitt** [comment]
Oh hang on, could you explain exactly what you are trying to achieve? 

If you can post some sample code, that would help.

**Comment by xkxxfyf** [comment]
thank you for help !@jcupitt
the new function fetch help me lift speed from 600+ sec to 60 sec in 128*128 pixel,but it don't achieve your sample speed about 12800 times in 0.5 sec,perhaps i only use two pipeline.
i try to split handle slide to three process,and this is the second process.it receive a class list.the class contains whole image(trans to pyvips.Region), tiles coordinates(use to fetch),tiles images(use pyvips.Image.extractarea ,ratain them instead of Region.fetch because i find them very quick in merge tiles to wholeslide:)).and the process return a class contains a tiles list.
here is my code. 
`def operation_tiles(img_tile_list: list, method, out_info_index=[0], **kwargs):
    
    def list_transpose(old_list):
        new_list = []
        if(isinstance(old_list[0], list)):
            for i in range(len(old_list[0])):
                temp_list = []
                for element in old_list:
                    temp_list.append(element[i])
                new_list.append(temp_list)
            return new_list
        else:
            new_list.append(old_list)
            return new_list

    tile_number = len(img_tile_list[0].tile_data)
    out_img_list=[]
    for img_tile in img_tile_list:
        if(isinstance(img_tile.data, pyvips.Region) == False):
            raise ValueError('img_tile.data[i] is not a pyvips.Region')
            
    for i in range(tile_number):
        ar_in = []
        
        

        for img_tile in img_tile_list:
            ar_i = img_tile.data.fetch(img_tile.index_list[i][0],
                                       img_tile.index_list[i][1],
                                       img_tile.index_list[i][2],
                                       img_tile.index_list[i][3])
            ar_i = np.ndarray(buffer=ar_i,
                   dtype=FORMAT_TO_DTYPE[img_tile.fmt],
                   shape=[img_tile.index_list[i][2], img_tile.index_list[i][3], img_tile.whole_channel])
            ar_in.append(ar_i)

        
        
        if(len(ar_in) == 1):
            ar_in = ar_in[0]
        
        ar_out = method(ar_in, **kwargs)
        
        
        
        if(isinstance(ar_out, list)):
            out_i = [array_to_image(k) for k in ar_out]
        elif(isinstance(ar_out, np.ndarray)):
            out_i = array_to_image(ar_out)
        else:
            raise ValueError('ar_out is not a list or np.ndarray')
            
        out_img_list.append(out_i)
    
    trans_img_list = list_transpose(out_img_list)
    out_tile_list = []
    for i,element in enumerate(out_info_index):
        img_tile_list[element].update_tile_data(trans_img_list[i])
        out_tile_list.append(img_tile_list)

    return out_tile_list`
