### ISSUE TITLE
What does "tiff2vips: subsampled images not supported" _actually_ mean?

### ISSUE THREAD

**Issue by linkyndy** [libvips/libvips#1328]
We've just received this error from a user-uploaded image (we can't find out more about the image due to our privacy policies).

In that way, I am curious what does the `tiff2vips: subsampled images not supported` error actually mean. And more importantly, if there is something we can do on our side to support/make this work in the future?

**Comment by jcupitt** [comment]
Hello @linkyndy,

That message means that the image has been saved in YCbCr space and with chroma subsampling, but does not use JPEG compression.

libtiff does not really support this kind of image: it relies on libjpeg to do expansion of chroma and has no routines for this itself. It's also difficult for libvips to support without a lot of extra work. 

Do you know who made this image and how? Chroma subsampling without JPEG compression is very unusual.

**Comment by linkyndy** [comment]
Hello @jcupitt, thanks for your quick reply!

We don't know anything about it. Just that it failed processing with this error. We can't dig in further, since it is user data.

However, we're getting a few of these every couple of minutes (0.34% of the images processed).

What would you recommend? Stop processing such images (if so, how can we target this kind of images via Vips?), or fix it somehow (another TIFF library, some operations to be performed etc.).

Thanks for all your help!

**Comment by jcupitt** [comment]
Huh how curious, I'm very surprised they are so common. 

It could be a malicious image: many readers will crash with images like this, since libtiff itself does not really support them. We only recently found (thanks to OSS Fuzz) and fixed this hole ourselves.

Could you send me a sample?

**Comment by linkyndy** [comment]
That’s interesting. Then we might as well skip processing these images.

Unfortunately, we can’t access, let alone share user data 😊

**Comment by jcupitt** [comment]
Perhaps you could run `tiffinfo` on the server and send me the output of that?

You can contact me privately and I could sign an NDA, if that helps at all.

**Comment by linkyndy** [comment]
I will do that. Regarding the images, I will see what I can do, but don't expect much 🙂

**Comment by linkyndy** [comment]
Coming back to this. Unfortunately, as expected, we can't do anything with user data, so we can't download/analyze/process such files manually. I'm sorry I can't help more than this here.

We'll leave this issue aside for now and keep monitoring it, see how much does it occur.

**Comment by jcupitt** [comment]
Could you add a little debugging code to the server to run tiffinfo on failing TIFF files and send that somewhere? You wouldn't be seeing user pixels, just the metadata from the header.

**Comment by linkyndy** [comment]
I can try that. Is that also available from ruby-vips? Or the only way is to run an external command for this?

**Comment by jcupitt** [comment]
Yes, you'd need to run an external command. It looks like:

```shell
$ tiffinfo crash.tif
TIFFReadDirectory: Warning, Unknown field with tag 37724 (0x935c) encountered.
TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 1170 Image Length: 2362
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Rows/Strip: 224
  Planar Configuration: separate image planes
  Software: Adobe Photoshop CC 2015.5 (Windows)
  DateTime: 2017:04:03 10:36:03
  XMLPacket (XMP Metadata):
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c132 79.159284, 
2016/04/19-13:13:40        ">
<?xpacket end="w"?>
  Photoshop Data: <present>, 5762 bytes
  EXIFIFDOffset: 0xca17c
  Predictor: horizontal differencing 2 (0x2)
TIFF Directory at offset 0xca17c (827772)
  ExifVersion: 0x30,0x32,0x32,0x31
  ColorSpace: 65535
  PixelXDimension: 1170
  PixelYDimension: 2362
```

`exiftool` is another useful one, though that needs things like perl to run.

**Comment by linkyndy** [comment]
I'm coming back to this. Looks like most of the errors related to this came from PSD/CR2 images. Others came from the fact that we were actually not having...libtiff installed in all environments.

These being said, I understood libvips doesn't support RAW image files and it delegates to Imagemagick, which in turn, depends on ufraw. I've installed the latter, however, I get the same errors locally when trying to load a CR2 file. Is there something else I miss?

**Comment by jcupitt** [comment]
You need to rebuild your imagemagick after installing ufraw (I think) to enable the delegate.

**Comment by linkyndy** [comment]
Apparently, imagemagick does its trick with CR2 images:

```
convert cr2:RAW_CANON_1DM2.CR2 test.png
```

I successfully get a PNG from this. I can also call `dcraw` on this image. However, if I try doing the following (using ruby-vips), I get:

```
irb(main):002:0> image = Vips::Image.new_from_file('RAW_CANON_1DM2.CR2')

(bundle:64837): VIPS-WARNING **: 09:48:44.579: Photometric tag is missing, assuming data is YCbCr

(bundle:64837): VIPS-WARNING **: 09:48:44.579: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:64837): VIPS-WARNING **: 09:48:44.579: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct

(bundle:64837): VIPS-WARNING **: 09:48:44.579: Photometric tag is missing, assuming data is YCbCr

(bundle:64837): VIPS-WARNING **: 09:48:44.579: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:64837): VIPS-WARNING **: 09:48:44.579: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct

(bundle:64837): VIPS-WARNING **: 09:48:44.580: Photometric tag is missing, assuming data is YCbCr

(bundle:64837): VIPS-WARNING **: 09:48:44.580: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:64837): VIPS-WARNING **: 09:48:44.580: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct
Traceback (most recent call last):
       [...snip...]
        3: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/image.rb:264:in `new_from_file'
        2: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/operation.rb:330:in `call'
        1: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/operation.rb:74:in `build'
Vips::Error (tiff2vips: subsampled images not supported)
```

I'll leave the image here, if needed: [RAW_CANON_1DM2.CR2.zip](https://github.com/libvips/libvips/files/3260513/RAW_CANON_1DM2.CR2.zip)

**Comment by linkyndy** [comment]
Also, we're seeing a lot of errors/warnings for `.tif` images:

```
MissingRequired: TIFF directory is missing required "ImageLength" field
tiff: unable to open "/tmp/part-dl20190612-7-18s597a" for input
```

```
TIFFSetField: /tmp/part-dl20190612-7-1ohbkjl: Unknown pseudo-tag 65538
TIFFSetField: /tmp/part-dl20190612-7-1ohbkjl: Unknown pseudo-tag 65538
TIFFSetField: /tmp/part-dl20190612-7-1hbrovh: Unknown pseudo-tag 65538
...
TIFFSetField: /tmp/part-dl20190612-7-4wtbb5: Unknown pseudo-tag 65538
TIFFSetField: /tmp/part-dl20190612-7-l7knzl: Unknown pseudo-tag 65538
linear: vector must have 1 or 4 elements
```

```
VipsJpeg: Corrupt JPEG data: premature end of data segment
TIFFSetField: /tmp/part-dl20190612-7-ml3jci: Unknown pseudo-tag 65538
...
TIFFSetField: /tmp/part-dl20190612-7-1i7ted3: Unknown pseudo-tag 65538
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
TIFFSetField: /tmp/part-dl20190612-7-1u5xb6p: Unknown pseudo-tag 65538
TIFFSetField: /tmp/part-dl20190612-7-1u5xb6p: Unknown pseudo-tag 65538
...
TIFFSetField: /tmp/part-dl20190612-7-6y55ip: Unknown pseudo-tag 65538
linear: vector must have 1 or 4 elements
```

```
tiff2vips: samples_per_pixel not a whole number of bytes
```

```
VIPS-WARNING **: Incompatible type for \"RichTIFFIPTC\"
```

I've pasted some assorted errors/warnings I could quickly find. I am curious, are these errors caused by poor user images, or they're from our side (we've forgot to install something, or we have an old version of something, or something is not configured)? If the first case, can we somehow "safely" suppress these? Our error tracking app is flooded by these.

**Comment by jcupitt** [comment]
Most of those look like RAW images, I think. git master libvips should be better at passing these down to libMagick so you don't see so many warnings.

You can suppress all libvips warning messages by setting the env var `VIPS_WARNING` to something.

**Comment by linkyndy** [comment]
I wouldn't be that much on _edge_ in the production environment 😊 We can update when a newer version will go out. But until then, that's the only thing that might be happening wrong with those images?

I will set the env var 👍

**Comment by jcupitt** [comment]
I think that's the main one, but we'd need to go through some sample images to check, of course.

**Comment by linkyndy** [comment]
Just to be sure, those errors come from `.tif` files; RAW files usually have other extensions, AFAIK. You're considering `.tif` files as RAW files as well?

**Comment by jcupitt** [comment]
Yes, they look like camera RAW files, certainly not regular TIFFs. Perhaps the file extension was changed somehow?

We'd need to do a proper investigation to know for sure.

**Comment by linkyndy** [comment]
We use our own [format parsing library](https://github.com/WeTransfer/format_parser) for this, which so far yielded good results; hence I would expect a file identified as `.tif` not to be a RAW file.

Nevertheless, I will dig more.

By the way, is there a way to tell whether `ufraw` was invoked or not by imagemagick for RAW files? I'm not entirely sure whether the library is properly processing images.

**Comment by jcupitt** [comment]
You could try renaming ufraw-batch to something else temporarily and see if imagemagick stops working on those images.

**Comment by jcupitt** [comment]
libvips 8.8.1 should handle this better. Please open a new issue if there is still a problem.

**Comment by revathi-murali** [comment]
So, we are getting the following error in libvips `8.9.0` 

```
Subsampling values [1,2] are not allowed in TIFF
tiff2vips: subsampled images not supported
```

---
Here is the tiffinfo on the same image:

```
OJPEGSubsamplingCorrect: Warning, Subsampling values [1,2] are not allowed in TIFF.
TIFF Directory at offset 0x8 (8)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 3424 Image Length: 4416
  Resolution: 400, 400 pixels/inch
  Bits/Sample: 8
  Compression Scheme: Old-style JPEG
  Photometric Interpretation: YCbCr
  FillOrder: msb-to-lsb
  YCbCr Subsampling: 1, 2
  YCbCr Positioning: centered
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 4416
  Planar Configuration: single image plane
  Page Number: 0-0
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  Make: Xerox
  Model: Xerox AltaLink B8055
  PageName: Page 1
  Software: 0.101.008.03810
  DateTime: 2019:12:30 15:38:24
  HostComputer: IntelInside/linux
  TargetPrinter: Xerox Printer
  YCbCrCoefficients: 0.299000,0.587000,0.144000
  JpegInterchangeFormat: 584
  JpegInterchangeFormatLength: 605734
  JpegProc: 1
TIFF Directory at offset 0x9406e (606318)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 3424 Image Length: 4416
  Resolution: 400, 400 pixels/inch
  Bits/Sample: 8
  Compression Scheme: Old-style JPEG
  Photometric Interpretation: min-is-black
  FillOrder: msb-to-lsb
  YCbCr Subsampling: 2, 2
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 4416
  Planar Configuration: single image plane
  Page Number: 1-0
  Make: Xerox
  Model: Xerox AltaLink B8055
  PageName: Page 2
  Software: 0.101.008.03810
  DateTime: 2019:12:30 15:38:25
  HostComputer: IntelInside/linux
  TargetPrinter: Xerox Printer
  JpegInterchangeFormat: 606768
  JpegInterchangeFormatLength: 638367
  JpegProc: 1
```

**Comment by jcupitt** [comment]
Those are old-style JPEG in TIFF images. 

They were part of the original 1992 TIFF6 document, but were never fully specified and were badly broken in several important ways.

In 1995, tech note 2, a TIFF6 addendum, replaced them with new-style JPEG in TIFF and deprecated old-style images. No one should have been making these images for 25 years, and perhaps should never have been making them, since they are not properly specified.

imagemagick and graphicsmagick still have special code for reading these things, but libvips does not.

**Comment by kmartinez** [comment]
Could you add a detector to your system that tells the user their image is non-standard and that it is being converted for them? that may persuade people they have an out-of-date image system or something that will help them.

**Comment by brendon** [comment]
A customer has triggered this for us by uploading a CR2 file. A tricky situation as it seems to pass muster as an image file and so isn't rejected by our validations but still fails to be processed into a thumbnail.

**Comment by jcupitt** [comment]
Yes, CR2 uses a TIFF container to hold the camera sensor data, but it's not really a TIFF image and most programs won't be able to load them. 

You need to check the file extension, or examine the tags carefully.

**Comment by brendon** [comment]
That was Rails letting that through as part of ActiveStorage:

```
irb(main):001:0> Rails.application.config.active_storage.variable_content_types
=>
["image/png",
 "image/gif",
 "image/jpg",
 "image/jpeg",
 "image/pjpeg",
 "image/tiff",
 "image/bmp",
 "image/vnd.adobe.photoshop",
 "image/vnd.microsoft.icon",
 "image/webp"]
```

Challenging as we just check that the content type is one of those before letting it through using the `activestorage-validator` gem. Goes to show there's always someone out there who will legitimately try throwing curveballs :D

**Comment by imjosh** [comment]
I ran into this same issue with Sharp.js which uses libvips, working with some scans from a Fujitsu PaperStream IP scanner that are 24-bit, YCbCr, with JPG compression.  

The error I'm getting from Sharp is `source input: Old-style JPEG compression support is not configured
tiff2vips: subsampled images not supported`

As a workaround, I'm using this Python script to fix these TIFFs before processing them further. 

```Python
from PIL import Image

def convert_tiff_24bit_to_8bit(input_path, output_path):
    # Open the 24-bit TIFF image
    with Image.open(input_path) as img:
        # Check the photometric interpretation
        try:
            photometric = img.tag[262][0]
        except KeyError:
            photometric = 2  # Default to RGB if tag is missing

        # Convert YCbCr to RGB if necessary
        if photometric == 6:  # YCbCr
            img = img.convert('RGB')

        # Convert the image to grayscale (8-bit)
        img_gray = img.convert('L')

        # Save as 8-bit TIFF without compression
        img_gray.save(output_path, 'TIFF', compression='raw')

    print(f"Conversion complete. 8-bit TIFF saved as {output_path}")

# Example usage
input_file = './YCbCr_24bit_jpgCompression_input.tif'
output_file = './output_8bit.tif'
convert_tiff_24bit_to_8bit(input_file, output_file)
```
