### ISSUE TITLE
Vipsthumbnail option to set opaque none

### ISSUE THREAD

**Issue by rps01** [libvips/libvips#1334]
Few of the assets background change from white to black while transcoding. This issue is resolved by using `-opaque none`  in convert command for imagemagick. 
Is there a similar option with vipsthumbnail command.

**Comment by jcupitt** [comment]
You can set the background to flatten against in savers. Try:

```
vipsthumbnail something.png -o t.jpg[background=0]
```

**Comment by rps01** [comment]
it doesn’t help, -background option in convert command also doesn’t resolve. Its -opaque none only that helps with imagemagick

**Comment by jcupitt** [comment]
I guess I don't understand what you want. Please show an example that fails.
