### ISSUE TITLE
Processing images with more than 256 bands (hyperspectral)?

### ISSUE THREAD

**Issue by erdmann** [libvips/libvips#1335]
Hi John,

I'm processing some 257-channel hyperspectral images (256 reflectances and a mask) and I encountered an error message that simply says "bad bands".  I see that comes as a hard-coded limit of 256 bands here: [arithmetic.c](https://github.com/libvips/libvips/blob/master/libvips/arithmetic/arithmetic.c#L381l).

I would also like to start using vips to process raw files from our macro-XRF setup, which implies a need to deal in 4096-channel images.

The [.v file format specification](https://jcupitt.github.io/libvips/API/current/file-format.html) allocates 4 bytes for the band count, but I assume that the 256-band limit comes from 1 byte being allocated to store the band count somewhere internally.  Is this a limitation that would be straightforward to extend?

Many thanks in advance.

**Comment by jcupitt** [comment]
Hi, I removed that limit, it was just there for programming convenience. If you come across any more, please let me know.

**Comment by erdmann** [comment]
I owe you so many beers.  Thanks!
