### ISSUE TITLE
Current status on building for Lambda ?

### ISSUE THREAD

**Issue by lundin** [libvips/libvips#1337]
Hi!
Is there any way one can explain how to build (what do i need to zip to a lambda deploy package to make vips work in a amazon linux/lambda enviroment ?)

There is this thread
https://github.com/libvips/libvips/issues/492

I tried the first shell script in this thread it seems no longer working. Tried all sorts of builds on Amazon EC2 to no avail.

However I build vips with package manager using docker from here:
#1184 (remi last post)

But what i dont understand is what do i need to copy/zip in order to do a exec of the vips shell command using golang? Can i even do that (take the vips binary etc) from this docker image and put into the lambda ?

Thanks :)

**Comment by jcupitt** [comment]
All you need to do (I think) is run that list of commands from Remi's Dockerfile on each instance you want to use php-vips on. They will automatically download and install a set of binaries for you.

**Comment by lundin** [comment]
Hi John and thanks for chiming in an all the great work with this lib. I use it alot with imaginary on some servers.

Not i understand this one though. So this time i wanted to add those binaries to a serverless binary/lambda function. Basically add all the needed files (minumun needed files to make vips work) and zip them and upload them together with the function (or add as a layer).

I did this with pdftk today and i only needed one single binary and one so file in order to modify a pdf. It would be awsesome to be able to pick the same for vips.

I dont need the PHP bindings etc, just raw vips so i can do external command and read stdin and stdout from it. Basically triggering a thumbnail process.

Any thoughts on this ?

**Comment by jcupitt** [comment]
Ooop, sorry for not replying, this dropped off my radar.

You can install to a private prefix, then just tar that up. For example:

https://github.com/jcupitt/docker-builds/blob/master/libvips-amazonlinux2/Dockerfile

Builds vips and libwebp to `/usr/local/vips`. You can tar up this directory and copy it to some other machine to run. You'll need to set `PATH` and perhaps `LD_LIBRARY_PATH` of course.
