### ISSUE TITLE
GIF/WEBP animation duration

### ISSUE THREAD

**Issue by deftomat** [libvips/libvips#1338]
Hi, we are using a custom Sharp fork with a GIF and WEBP support.

However, we find out that some source images have various delays between images.
Unfortunately, we are not able to keep these delays intact as VIPS provides only one (probably the first) value.

In our example, the source GIF have 4 frames, where delay after each of first 3 is 500ms and then 2500ms after the last one. Then, the animation repeats.

When we process it with VIPS, the duration of animation is 2000ms instead of 4000ms as VIPS tell us that `gif-delay` is 50;

**Comment by jcupitt** [comment]
Hello @deftomat 

Sorry, libvips only supports a single delay number for animated images.

**Comment by deftomat** [comment]
Is there any possibility to include support for multiple delay numbers? Are we limited by underling libraries?

**Comment by jcupitt** [comment]
We'd need to add this feature to webp and magick load/save and to gif load, and then have some new API for for passing the values around. I'd guess a few days of work. 

It would be an API break, so it would have to be a feature for the next libvips in about six month's time.

**Comment by jcupitt** [comment]
I'll tag this as an enhancement.

**Comment by deftomat** [comment]
Thanks for an info. 

Unfortunately, six months is too much for us 😞 . I would happily help with this feature if you want.

Then, we can use the custom build from master.

Can you point me a little bit into the right direction as I'm not familiar with codebase?

**Comment by jcupitt** [comment]
gifload.c would be the easiest place to start:

https://github.com/libvips/libvips/blob/master/libvips/foreign/gifload.c

You'll see it has a single int for delay. You'll need to swap that for an array of ints, and then when that's attached to the output image here:

https://github.com/libvips/libvips/blob/master/libvips/foreign/gifload.c#L578

You should probably attach the first delay as a simple int for compatibility, then attach the whole array as metadata under a different name, perhaps `gif-delay-array`.

When that's working, I'd attack `magicksave.c` and use the delay array (if present) to set a separate delay for each frame.

**Comment by deftomat** [comment]
AWESOME, thanks!

**Comment by kleisauke** [comment]
Perhaps we could turn `gif-delay` into an array just like `openslide.level`?:
https://github.com/libvips/libvips/blob/3245dd301b63d1747af535c03881383b91e6a048/libvips/foreign/openslide2vips.c#L416-L426

To set a delay of a single frame, you can just do:
```c
// first frame 10 centiseconds delay
vips_image_set_int( image, "gif-delay[0]", 10 );

// second frame 20 centiseconds delay
vips_image_set_int( image, "gif-delay[1]", 20 );

// etc.
```

And to set all frames to the same delay (to maintain backwards compatibility):
```c
// all frames 10 centiseconds delay
vips_image_set_int( image, "gif-delay", 10 );
```

For a new API, I would do this (this would be an API break):
```c
// first frame 100 milliseconds delay
vips_image_set_int( image, "frame[0].delay", 100 );

// second frame 200 milliseconds delay
vips_image_set_int( image, "frame[1].delay", 200 );

// set second frame disposal method to previous (GIF only)
vips_image_set_string( image, "frame[1].dispose", "previous" );

// set second frame disposal method to background (WebP / GIF)
vips_image_set_string( image, "frame[1].dispose", "background" );

// use alpha blending for the second frame (WebP only)
vips_image_set_string( image, "frame[1].blend", "alpha" );

// set loop count (both WebP / GIF)
vips_image_set_int( image, "loop-count", 2 );
```

This will deprecate the `gif-delay` and `gif-loop` metadata and switches the delays from centiseconds to milliseconds. It also allows you to set the dispose and blending methods for individual frames.

**Comment by jcupitt** [comment]
libvips supports array types for metadata, so you can do:

```
vips_image_set_array_int (VipsImage *image, const char *name, int **array, int n)
```

which would be neater. You'd be able to manipulate the array of delays from Python (for example) using ordinary Python arrays and not have to parse metadata names.

I don't know if tracking dispose etc is very useful. The loaders unpack everything to accumulated RGB on load, so knowing dispose doesn't help much.

**Comment by jcupitt** [comment]
I agree on milliseconds rather than centiseconds, it's very unfortunate that we didn't do that before. 

Looks like `vips_image_set_array_int()` doesn't actually exist in the C API, but it's just a couple of lines of code.

How about `gif-delay` as a single int in centisecs for compat, and `delay` as an array of millisecond times as the field that's shared with webp load/save?

**Comment by deftomat** [comment]
@jcupitt

I must admit that I'm not able to write `vips_image_set_array_int` function. 😞 

I tried to do something like:
```
vips_image_set_area( image, "delay", NULL, vips_array_int_new(gif->delay, gif->n_pages) );
```
where `gif->delay` is `int *delay`

Unfortunately, `vipsheader -a file.gif` prints:

```
delay: VIPS_TYPE_AREA, count = 1, data = 0x7f9052d41e00
```

What I was able to understand, there is an [GType transformation for (int[] -> string)](https://github.com/libvips/libvips/blob/8a98bea063d2373e7e2180a20c8298c05466d9af/libvips/iofuncs/type.c#L827).

So, what do I need to do to force `vipsheader` to use this transformation before it prints `delay` property?

I'm working mostly with TypeScript, so please bear with me 😉 

To me, it looks like using `vips_image_set_area` is probably not the right direction.

**Comment by jcupitt** [comment]
Hiya, I added `vips_image_get/set_array_int()` to git master for you:

https://github.com/libvips/libvips/commit/2aef873fcd23b741e7cda51c2bfe16bc247e5281

In the gif loader, you should be able to attach an array and then see it in the vips header. To attach:

```
int array[10];
int i;

for (i = 0; i < 10; i++)
  arrary[i] = i;
vips_image_set_array_int (image, "delay", array, 10);
```

Then try decoding a gif:

```
$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.gifload("3198.gif")
>>> x.get_fields()
['width', 'height', 'bands', 'format', 'coding', 'interpretation', 'xoffset', 'yoffset', 'xres', 'yres', 'filename', 'vips-loader', 'n-pages', 'gif-delay', 'gif-loop', 'delay']
>>> x.get("delay")
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by deftomat** [comment]
Thanks a lot. It works!

**Comment by jcupitt** [comment]
I had a go at making gifload set a delay array:

https://github.com/libvips/libvips/commit/5d928451ce26bc86870da07205984f8b185b1e2e

You'll need matching changes to webp load/save and magick load/save.

**Comment by deftomat** [comment]
@jcupitt Oh, I just finished it 😞 

It works for webp/gif save/load.

**Comment by deftomat** [comment]
PR: https://github.com/libvips/libvips/pull/1346

**Comment by jcupitt** [comment]
Oh heh no problem, I had an hour stuck on a train so it helped fill the time. I'll read your PR, thanks!
