### ISSUE TITLE
WEBP animation loop

### ISSUE THREAD

**Issue by deftomat** [libvips/libvips#1339]
Looks like WEBP supports `gif-delay` option but it definitely ignores `gif-loop` option as every WEBP animation generated by VIPS is infinite.

**Comment by kleisauke** [comment]
I assume you found the solution? I just encountered the same problem when I used it in combination with the `strip` option of `webpsave`:
```python
import pyvips

image = pyvips.Image.new_from_file('dancing-banana.gif', n=-1, access='sequential')
image.set("gif-loop", 2)
image.write_to_file("x.webp")

image = pyvips.Image.new_from_file('dancing-banana.gif', n=-1, access='sequential')
image.set("gif-loop", 2)
image.write_to_file("x2.webp", strip=True)
```
```bash
$ vipsheader -f gif-loop x.webp
2
$ vipsheader -f gif-loop x2.webp
0
```

**Comment by deftomat** [comment]
Yes, I thought that it was my mistake, so I closed it. However, then I discover that strip is causing it to strip all metadata. Even loop value. I updated our fork to make it work but I didn't create a PR as we still waiting for https://github.com/libvips/libvips/pull/1346

**Comment by deftomat** [comment]
Here is what I did to make it works: https://github.com/deftomat/libvips/commit/0e73001bda3fccd281b2978d2c2737754cc5cd04

**Comment by jcupitt** [comment]
So you'd like loop and delay to be set, even when `strip` is on, is that right?

Let's leave this open as a reminder to do this after delay array is merged. 

It looks like magicksave is missing strip support.

**Comment by jcupitt** [comment]
OK, done. `magicksave` has strip support too.

**Comment by deftomat** [comment]
Many thanks!
