### ISSUE TITLE
black creates very uncompressed images

### ISSUE THREAD

**Issue by jxu** [libvips/libvips#1340]
For example 

    vips black 50000.tiff 50000 50000 --bands 3

creates a 4.3 GB image even though this image can be compressed greatly. 

50000x50000 JPEG is 39.1 MB and 50000x50000 PNG is 7.3 MB.

**Comment by jcupitt** [comment]
Yes, that's an uncompressed TIFF, so it's huge. 

Try:

```
john@kiwi:~/pics$ vips black x.tif[compression=ccittfax4,squash] 50000 50000
john@kiwi:~/pics$ ls -l x.tif
-rw-r--r-- 1 john john 10762 Jun 16 22:27 x.tif
```

50k x 50k pixels in 10kb.

**Comment by jxu** [comment]
Thanks for responding so quickly.
