### ISSUE TITLE
Compress option

### ISSUE THREAD

**Issue by jxu** [libvips/libvips#1341]
It was not easy to find out how to just compress images but I think the following work:

    vips jpegsave 50000.jpeg 50000_compress.jpeg --optimize-coding -Q 90
    vips pngsave 50000.png 50000_compress.png --compression 9
    vips tiffsave 50000.tiff 50000_compress.tiff --compression deflate

What are the optimal compression flags? Is there a compress command?

**Comment by jcupitt** [comment]
Hello @jxu, sorry for the late reply.

No, there's no single command to compress images. It depends on the details of the file format, on the type of image, on what kinds of quality trade-offs the user wants to make, and so on. libtiff is especially bad for this: it supports at least five different types of compression and each one has several options you can tweak depending on what you want to do. 

I don't think it's possible to automate this kind of thing, so libvips tries to just hand the controls to the user.

**Comment by jxu** [comment]
Thanks for letting me know.
