### ISSUE TITLE
vipsthumbnail fails to save to output directory with png format

### ISSUE THREAD

**Issue by gurukashyap** [libvips/libvips#1347]
vipsthumbnail tn_hero.jpg --size 200x100 -o test/test.png

(vipsthumbnail:15559): VIPS-WARNING **: 10:57:28.733: profile 'icc': 0h: PCS illuminant is not D50
vipsthumbnail: unable to thumbnail tn_hero.jpg
vips2png: unable to write "./test/test.png"

test folder exists in current location. 
Where as I have use without -o option it works fine.

**Comment by jcupitt** [comment]
Without `-o` it will save as JPG. 

libpng is quite strict about the profiles it allows and seems to be blocking this one because of the non-standard illuminant. 

Could you upload the failing image somewhere?

**Comment by rps01** [comment]
Issue seems to be with ProPhoto profile assets.

```
vipsthumbnail Flowers-ProPhoto.jpg -s 1280x1280 -o ProPhoto.png

(vipsthumbnail:35845): VIPS-WARNING **: 13:30:22.280: profile 'icc': 0h: PCS illuminant is not D50
vipsthumbnail: unable to thumbnail Flowers-ProPhoto.jpg
vips2png: unable to write "./ProPhoto.png"
```

![Flowers-ProPhoto](https://user-images.githubusercontent.com/50220952/60131039-46f13680-974d-11e9-9449-d3d340ca2ccf.jpg)

**Comment by jcupitt** [comment]
Yes, looks like it:

```
john@kiwi:~/pics$ vips copy prophoto.jpg x.jpg
john@kiwi:~/pics$ vips copy prophoto.jpg x.png

(vips:13615): VIPS-WARNING **: 22:29:50.050: profile 'icc': 0h: PCS illuminant is not D50
vips2png: unable to write "x.png"
```

It works if you strip the profile:

```
john@kiwi:~/pics$ vips copy prophoto.jpg x.png[strip]
john@kiwi:~/pics$
```

But then of course your image will be incorrect. Probably it's best to export to sRGB:

```
john@kiwi:~/pics$ vipsthumbnail prophoto.jpg --eprofile srgb -o x.png
john@kiwi:~/pics$ 
```
