### ISSUE TITLE
Thumbnail without a specific output file extension

### ISSUE THREAD

**Issue by alex88** [libvips/libvips#1348]
Trying to thumbnail usign

```
vipsthumbnail Scan.jpeg --rotate --size 256x -f jpeg -o th
```

so without specifying a file extension throws error:

```
vipsthumbnail: unable to thumbnail Scan.jpeg
VipsForeignSave: "./th" is not a known file format
```

shouldn't `-f` force an output format no matter what the output file extension is?

**Comment by jcupitt** [comment]
Hello @alex88, 

`-f` sets the output format string, so the `./tn_%s.png[compression=9]` etc. pattern that's used to generate the output path. It has the same effect as the (now deprecated) `-o` option. There's no option to select the saver.

Are you planning to write to a pipe? I would use `thumbnail_buffer` from Python etc.

**Comment by alex88** [comment]
Hi @jcupitt thanks for the quick response, I was going to use vips via a library that doesn't let me change the filenames it uses for input/output and since they have no extension (they're just tempfiles) `vipsthumbnail` wasn't going to let me use those filenames, anyway I've found a workaround in the meantime
