### ISSUE TITLE
Error message on creating the mosaic image

### ISSUE THREAD

**Issue by vinaymuthanna0727** [libvips/libvips#1349]
Hi,
While creating the mosaic i am getting the error from libvips.
**Error Message :-**  im_avgdxdy: no points to average
Can i know the reason for this error message ?
How to resolve this issue ?

**Comment by jcupitt** [comment]
Hello, it's failed to find enough tie-points in the overlap area. Perhaps your overlap is too small, or contains large uniform areas?
