### ISSUE TITLE
class "magickload" not found, Alpine vips package

### ISSUE THREAD

**Issue by linkyndy** [libvips/libvips#1350]
I've been experimenting with libvips on a new Docker image (based on Alpine). Everything looks fine, however it seemed that BMP images could not be processed anymore. I manually tried:

```
Vips::Image.magickload('image.bmp')
```

and then I saw this:

```
Vips::Error (VipsOperation: class "magickload" not found)
```

I'm installing vips using:

```
FROM ruby:2.5-alpine

RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ \
  build-base \
  imagemagick \
  vips-dev
```

What's different in the Alpine libvips package? 🤔

**Comment by lovell** [comment]
The APKBUILD file for the `vips` package provided by Alpine's community repo is maintained at https://github.com/alpinelinux/aports/blob/master/community/vips/APKBUILD

The compile-time dependencies do not currently include *magick.

**Comment by linkyndy** [comment]
I see...should it be added? I know `brew` and `apt` make use of imagemagick at compile-time.

**Comment by jcupitt** [comment]
I think most people avoid exposing imagemagick to unknown files unless they spend some time locking it down, so Alpine does not enable it by default.

IM has become a lot safer over the last couple of years with their work with oss-fuzz -- perhaps this is no longer the issue that it was.
