### ISSUE TITLE
Bug with size of multiline text

### ISSUE THREAD

**Issue by levmorozov** [libvips/libvips#1352]
We successfuly use vips for many things (thanx for amazing lib!), including generating images with multiline text. But in some cases we get strange behaviour. What we normally see:

![image_2019-06-27_17-02-47](https://user-images.githubusercontent.com/979251/60273069-f5d47480-98fd-11e9-927e-f506af65b015.png)

But when "bug" happens we get:

![image_2019-06-27_17-02-25](https://user-images.githubusercontent.com/979251/60272955-c6256c80-98fd-11e9-88b3-0779add0b022.png)

(It's enough to remove/add one letter or change width/height to fix that, but it's not an usable option for us, because image generation is fully automated. So we can fix it only in hand-mode afterwards)

Code that reproduces situation (second picture above):

```
Image::text(
            'Proin velit turpis, lacinia ac tortor sed, dictum tincidunt dolor. Fusce pulvina',
            [
                'font' => 'PT Serif Bold',
                'fontfile' => 'Bold.ttf',
                'width' => 437,
                'height' => 100
            ]
        );
```
Font: https://fonts.google.com/specimen/PT+Serif

Are there any workarounds?

**Comment by jcupitt** [comment]
You've set width and height, and this puts text into autofit mode. It searches for a DPI setting that will "best" fit the text into the box.

I would set width and DPI and let height float with the text. You'll get text with a predictable size and no funny behaviour.

**Comment by jcupitt** [comment]
It is curious that autofit is so unstable in this case. I'll see if I can make it more predictable.

Test case:

```
$ vips text x.png "Proin velit turpis, lacinia ac tortor sed, dictum tincidunt dolor. Fusce pulvina" \
    --font "PT Serif Bold" --fontfile PT_Serif-Web-Bold.ttf --width 437 --height 400
```

**Comment by levmorozov** [comment]
>  You'll get text with a predictable size and no funny behaviour.

In some cases we have small titles, in some cases - larger (from 60-70 characters to 120-200). And variable size of font looks great in practice in our project. 
Except for these instabilities :(

**Comment by jcupitt** [comment]
I found a problem in the autofit loop, it seems to work better now. This will be in 8.8.1, thanks!

**Comment by levmorozov** [comment]
Great! Thanks!

**Comment by jcupitt** [comment]
OK 8.8.1 is out with this fix.
