### ISSUE TITLE
Glib error in vipsthumbnail called in bash script from PHP

### ISSUE THREAD

**Issue by mabeltron** [libvips/libvips#1353]
A client is having an intermittent problem with vipsthumbnail using libvips 8.8 on CentOS 7 with cPanel 80 using PHP 7.2.19 from Easyapache.

Using a bash script as a wrapper called by shell_exec from PHP, some files are converted correctly but others fail with the error `GLib: Cannot convert message: (null) (process:xxxxx): GLib-ERROR (recursed) **:`

The same script, run from the command line, always works. One file in the current test is 4.1Mb and this fails using PHP, and another 1.1MB and this works.

The command line in the bash script is `vipsthumbnail --vips-info $crop --size=$size "$input" -o $output\[Q=$quality,strip\] --iprofile /ssd/cmyk.icm --rotate` and the command in PHP is `vips_convert.sh -c -s 880x326 -i '/path/to/image.jpg' -o output.jpeg -q 75 2>&1`.

**Comment by jcupitt** [comment]
Hello @mabeltron,

Huh funny I've never seen a message like that. 

I'm very sorry, but this will be hard to debug without a test case. If you can find a way to make this happen on the command-line I should be able to fix it.

**Comment by mabeltron** [comment]
Hmm, I didn't think to try this but running the PHP script from the command line works so it may well be an issue with apache. I'm inclined to try and get them to use the PHP extension instead.
