### ISSUE TITLE
Graceful handling Mosaic in featureless area?

### ISSUE THREAD

**Issue by toybuilder** [libvips/libvips#1356]
Hi,
I've been steadily putting together a working solution using the mosaic functionality and have run into an issues that I am not sure how to handle, exactly.
In one of my image sets, there are two "panels" where the image is somewhat blown out AND the area is fairly featureless.  As a result, Mosaic cannot seem to find suitable tie-points and gives up.
In most cases, the dx/dy values are pretty consistent (within a pixel or two) -- so it would be nice if there was a way to "dead reckon" the stitching across an area with little features to tie the images together.  I don't know apriori if/when/where this would occur; and it would be nice not to have to have human intervention to handle the situation.
Is there a way to do this?   I suppose I could preload with an "aligner" image set, stitch, and then use the Rebuild function? 
Thank you!

**Comment by jcupitt** [comment]
The best solution is to do global optimisation, though it's more work.

You load up every overlapping pair and estimate the overlap. Weight each one by the size of the overlap (corner overlaps are not very useful, large overlaps probably more reliable) and put the whole lot into a big matrix. Do LMS and find the set of tile positions that minimise the average error.

This way, underdetermined regions, like smaller, flat areas, will be filled in by the surrounding overlaps.

**Comment by toybuilder** [comment]
Thanks for your reply. 
If I am understanding you correctly, I should ditch the mosaic1 function and instead figure out my own alignment with correl and merge functions?

**Comment by jcupitt** [comment]
You can use mosaic to find the overlap, eg.:

```python
im, dx, dy = a.mosic(b, 'horizontal', x1, y1, x2, y2, dx0=True, dy0=True)
```

Don't fetch pixels from `im`, just use the calculated dx / dy.

**Comment by toybuilder** [comment]
Ok, and then the next step would be to use those dx/dy values directly with merge, correct? I apologise for such a basic question; but it seems more prudent to ask.

Thank you very much.

**Comment by toybuilder** [comment]
I was able to use merge using dx/dy estimations to get a good result -- I actually used mosaic and used the resulting image, but with a fall back to using merge with the estimated dx/dy.  

Thanks!
