### ISSUE TITLE
Conan.io packaging

### ISSUE THREAD

**Issue by doronAtuar** [libvips/libvips#1358]
Is it possible to have a Conan package for this lib?

**Comment by jcupitt** [comment]
I'd be happy to help someone make one. It should be easy -- libvips has a completely standard autotools build system. 

Eg. here's the brew one for reference:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/vips.rb

**Comment by doronAtuar** [comment]
I'll try to find the time and take a shot at this

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by AhiyaHiya** [comment]
Oh jeez, I was looking for this and saw that no work was done.
Is it alright if I implement this conan recipe?

**Comment by jcupitt** [comment]
Sure, that'd be great!

**Comment by AhiyaHiya** [comment]
Ok, I'll hammer away at this. This could take some time, as quite a few packages libvips depend on do not have conan recipes themselves.

**Comment by jcupitt** [comment]
It depends what you're using libvips for, but for many people a lot of the optional dependencies are not very useful. NIfTI load/save, for example, will probably only be interesting to people working on brain imaging, and actively dangerous for anyone else.

The set of deps that we fuzz might be a good start:

https://github.com/google/oss-fuzz/tree/master/projects/libvips

**Comment by AhiyaHiya** [comment]
From a first glance, I didn't evaluate the usefulness of the dependencies; I did want to create a conan recipe that had the same output as the homebrew recipe. However, if the non-existing conan recipes conversion becomes a bigger scheduling issue than anticipated, then a discussion should be had to set an expectation to what is considered complete... good enough so to speak, for the average libvips user.

**Comment by jcupitt** [comment]
It's just a security issue --- if you use this binary in a webserver, for example, you'll be very vulnerable if you have the stranger dependencies enabled. 

Homebrew turns almost all of them on, but no one uses homebrew binaries in production (I hope!), so it's mostly OK.

I did try getting homebrew to disable the madder ones, but they hate packages which force the user to build from source, so they refused.
