### ISSUE TITLE
tiff2vips: page 1 differs from page 0

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1359]
We ran into the error `tiff2vips: page 1 differs from page 0` quite a number of times when processing the multi-page tiff from our customers. Most of it had the below warnings:

```
(bimg:23): VIPS-WARNING **: 09:28:04.130: Unknown field with tag 33000 (0x80e8) encountered
(bimg:23): VIPS-WARNING **: 09:28:04.130: Unknown field with tag 33000 (0x80e8) encountered
repeated n times
```

I did tiffinfo on one of the tiff files and here is the output for the same:

```
$ tiffinfo error.tiff
TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered.
TIFF Directory at offset 0x8 (8)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1872 Image Length: 2366
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  Thresholding: bilevel art scan
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2366
  Planar Configuration: single image plane
  Software: Kofax standard Multi-Page TIFF Storage Filter v3.03.000
  DateTime: 2019:06:27 09:23:24
  Tag 33000: 0
TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered.
TIFF Directory at offset 0xabb0 (43952)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1968 Image Length: 2371
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  Thresholding: bilevel art scan
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2371
  Planar Configuration: single image plane
  Software: Kofax standard Multi-Page TIFF Storage Filter v3.03.000
  DateTime: 2019:06:27 09:23:24
  Tag 33000: 0
TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered.
TIFF Directory at offset 0x11305 (70405)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1856 Image Length: 2334
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  Thresholding: bilevel art scan
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2334
  Planar Configuration: single image plane
  Software: Kofax standard Multi-Page TIFF Storage Filter v3.03.000
  DateTime: 2019:06:27 09:23:25
  Tag 33000: 0
.............. repeated
```

Not sure if the issue is something related to `TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered`.

Any idea how this can be fixed?

**Comment by jcupitt** [comment]
Hello, libvips multipage support assumes that all pages are equal size.

This works well for things like GIFs, PDFs (mostly) and volumetric TIFFs (eg. OME TIFF), but will not work for TIFFs like this where the page size varies randomly.

You'll need to process these a page at a time, sorry :(

**Comment by revathi-murali** [comment]
We have the usecase of converting multipage tiff to png. So now, we need to convert each tiff page to png and then use `vips_arrayjoin` to join the individual pngs. I am not sure of the memory consumption if we go with this approach. Do you suggest any other approach?

**Comment by jcupitt** [comment]
It should be fine, for example:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

multipage = image.get_typeof("n-pages") != 0 and image.get("n-pages") > 1

if multipage:
    n_pages = image.get("n-pages")

    pages = [pyvips.Image.new_from_file(sys.argv[1], access="sequential", page=i)
             for i in range(n_pages)]

    image = pages[0]
    for i in range(1, n_pages):
        image = image.join(pages[i], "vertical", expand=True, background=255)
        
image.write_to_file(sys.argv[2])
```

I'm not sure you can use `arrayjoin` as that expects pages to be set out in an equal grid, and yours change height.

This will probably for very large images (more than about 3000 pages), if that's an issue. You'd need to join the pages more carefully to get around that.

**Comment by revathi-murali** [comment]
@jcupitt Thanks for the explanation. We have a sample tiff file (refer attachment) which works when converting to png in one shot but throws error when we convert the individual pages to png and then join them.  

The tiff file has more than 100 pages. But when I convert the first 2 pages individually to png and then try to join those 2 pngs, then I got the following error

```(bimg:978): VIPS-WARNING **: 07:39:33.452: IDAT: CRC error

(bimg:978): VIPS-WARNING **: 07:39:33.456: [00][00][00][00]: invalid chunk type

(bimg:978): VIPS-WARNING **: 07:39:33.474: Not a PNG file

unable to write to buffer
```

Not sure if the issue is with the input tiff file because it is able to convert fine when we convert in one shot. 
[test_check_100.tif.zip](https://github.com/libvips/libvips/files/3400664/test_check_100.tif.zip)

**Comment by jcupitt** [comment]
Could you show the code that's failing? Or are you running that sample above?

**Comment by revathi-murali** [comment]
We use bimg - https://github.com/h2non/bimg for interacting with lib-vips. But we have forked the repo and made some changes - https://github.com/coupa/bimg

Step1:  For each page we call `bimg.Resize ` with options  {"type" : "png", PageToLoad: page}. Here the `PageToLoad` option is introduced by us to load the current page and convert that page to png. Each converted png is stored in an array.

We have made some changes in https://github.com/h2non/bimg/blob/master/vips.h#L361 to load the current page in tiff that would be converted to png i.e. code will be changed as below to load the current page of tiff in buffer

 vips_tiffload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, "page", opts->PageToLoad, NULL)

Step 2: Png image arrays are joined using vips_arrayjoin

**Comment by revathi-murali** [comment]
We use bimg - https://github.com/h2non/bimg for interacting with lib-vips.

**Step1:**  For each page we call `bimg.Resize ` with options  {"type" : "png", PageToLoad: page}. to convert each page in tiff to png. Here `PageToLoad` option is introduced by us to load the current page and convert that page to png. Each converted png is stored in an array.

We have made some changes in https://github.com/h2non/bimg/blob/master/vips.h#L361 to load the current page in tiff that would be converted to png i.e. code will be changed as below to load the current page of tiff in buffer

 `vips_tiffload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, "page", opts->PageToLoad, NULL)`

**Step 2:** Png image arrays are joined using vips_arrayjoin
    	
Let me know if you need any further info

**Comment by jcupitt** [comment]
Sorry, I don't know anything about bimg, it's got nothing to do with me.

I would try to implement that Python program above in bimg somehow.

**Comment by revathi-murali** [comment]
Okay thanks. And this is the change that we made for converting each page in tiff to png and joining them https://github.com/coupa/bimg/pull/6

**Comment by revathi-murali** [comment]
@jcupitt I used the above mentioned `python` code to convert the attached file `test_check_100.tif` to png and I am unable to open the output png. Attaching the output png.

![py_test_check_100](https://user-images.githubusercontent.com/2732287/61864974-09b8c980-aef0-11e9-8f18-4031b595b86d.png)

**Comment by jcupitt** [comment]
It's too big, so web browsers can't display it.

```
$ ../try298.py test_check_100.tif x.png
$ vipsheader x.png 
x.png: 1728x361152 uchar, 1 band, b-w, pngload
```

It'll need almost 3GB of memory just to hold the image for display. You can view it in nip2.

**Comment by revathi-murali** [comment]
Ahh got it! Thanks for the nip2 suggestion. 

I am still unable to figure out the exact root cause for the `IDAT CRC error - Invalid chunk type - Not a PNG file - Unable to write to buffer` when I convert using bimg. And btw, I am running inside the docker. Do you think if that could be an issue (though ideally it should not be)

**Comment by jcupitt** [comment]
No, docker should not be the cause.

**Comment by revathi-murali** [comment]
I think I kinda figured out the issue. After joining the `n` png images using the join method,  the  joined image is stored in `*C.VipsImage` object. In order to get the image buffer, `bimg` internally calls `C.vips_pngsave_buffer` at which point it throws the error "Not a PNG file" as it is unable to save the png file which is of huge dimension. Is there any better way to get the image buffer from `*C.VipsImage` object?

**Comment by jcupitt** [comment]
Sorry, no idea, you need to ask the bimg people.
