### ISSUE TITLE
Add support for AVIF

### ISSUE THREAD

**Issue by gunta** [libvips/libvips#1364]
**Why:**
- AVIF (AV1 Image File Format) is a [new image format based on the AV1](https://calendar.perfplanet.com/2018/is-avif-the-future-of-images-on-the-web/) video codec. 
- It supports both lossless and lossy compression and [saves up to 50% space 
at the same quality compared to JPG](https://hackernoon.com/start-using-superior-image-compression-today-932e8e086b72).

We can see [how it looks here](https://compare.rokka.io/_compare/#heif=40&jpeg=80&webp=80&av1=40&width=800&hash=d68ef212f18f8f20130a38f31ca5e945e93446a9) (view on Chrome).

**Supported in:**
- AV1 is supported already in `Chrome`, `Firefox` and `IE Edge`
- `VLC` supports AVIF
- `MP4Box` supports AVIF
- Android supports supports AV1 since `Android Q`
- `Apple` joined AV1 consortium

**Specs:**
- https://aomediacodec.github.io/av1-avif/

**How:**
- Perhaps trough [libavif](https://github.com/AOMediaCodec/libavif) or some [other implementation](https://github.com/strukturag/libheif/issues/96).

- Example implementation in [colorist](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by lovell** [comment]
libheif support was added to libvips v8.8.0, although you'll need the yet-to-be-released v8.9.0 to switch to `av1` compression instead of the `hevc` default.

https://github.com/libvips/libvips/blob/master/ChangeLog

See also https://github.com/libvips/libvips/issues/671 and https://github.com/libvips/libvips/pull/1360

**Comment by jcupitt** [comment]
Hello, you're in luck, Lovell added AV1 support last week:

https://github.com/libvips/libvips/commit/42f9f78c869e56dca27774e9524d3df5c651812f

**Comment by maxence33** [comment]
Hello 

I have installed on Ubuntu 18.04 from today's repos: 
libde265 and libx265
compiled libheif with the above 
compiled vips with the above (to vips 8.11.0)

Vips seems fine with libheif now : 
```
maxence@maxence-SSD:~/Desktop/smallerthebetter$ vips -l | grep _target
          VipsForeignSaveCsvTarget (csvsave_target), save image to csv (.csv), priority=0, mono
          VipsForeignSaveMatrixTarget (matrixsave_target), save image to matrix (.mat), priority=0, mono
          VipsForeignSaveVipsTarget (vipssave_target), save image to target in vips format (.v, .vips), priority=0, any
          VipsForeignSavePpmTarget (ppmsave_target), save to ppm (.ppm, .pgm, .pbm, .pfm), priority=0, rgb
          VipsForeignSaveRadTarget (radsave_target), save image to Radiance target (.hdr), priority=0, rgb
          VipsForeignSavePngTarget (pngsave_target), save image to target as PNG (.png), priority=0, rgba
          VipsForeignSaveJpegTarget (jpegsave_target), save image to jpeg target (.jpg, .jpeg, .jpe), priority=0, rgb-cmyk
          VipsForeignSaveWebpTarget (webpsave_target), save image to webp target (.webp), priority=0, rgba-only
          VipsForeignSaveHeifTarget (heifsave_target), save image in HEIF format (.heic, .heif, .avif), priority=0, rgba-only
```

Yet when converting to AVIF from a Ruby (https://github.com/libvips/ruby-vips v 2.1.2) higher level library (https://github.com/janko/image_processing v 1.12.1) I get error : 

**2021-06-26T13:40:21.830Z pid=16095 tid=mgv WARN: Vips::Error: VipsForeignSave: "/tmp/image_processing20210626-16095-b13rd2.avif" is not a known file format
15:40:21 sidekiq2.1 | VipsForeignSave: "/tmp/image_processing20210626-16095-b13rd2.avif" is not a known file format
15:40:21 sidekiq2.1 | 
15:40:21 sidekiq2.1 | 2021-06-26T13:40:21.830Z pid=16095 tid=mgv WARN: /home/maxence/.rvm/gems/ruby-2.7.2/gems/ruby-vips-2.1.2/lib/vips/image.rb:590:in `write_to_file'**

Any chance I might have missed a step ?

**Comment by maxence33** [comment]
It seems I was missing libaom in my libheif compilation ( https://aomedia.googlesource.com/aom/ )
added libaom successfully but libheif cannot compile anymore.. I have raised a ticket on libheif
