### ISSUE TITLE
Can I Specify the fallback font used to render text

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1369]
when generating text using vips 
```
import pyvips

image = pyvips.Image.text("Welcome to 厦门", width=1000, height=200, font="Arial")
image.tiffsave("text.tif")
```

Of course the chinese character "厦门" is not included in the Arial font, but it did render an output with these not included character

![text](https://user-images.githubusercontent.com/73845/61455960-864f2380-a997-11e9-860a-8a1ad03d9c17.jpg)

I think It might be using the system's default font.
But I want to check out if there is some way to specify the fallback font used to render when some character is not included.

**Comment by jcupitt** [comment]
Hi @jindili,

Not that I know of. That stuff is handled by fontconfig and pango (I think), so you'd need to investigate there.

You can load font files are runtime, of course, could that help?

```python
image = pyvips.Image.text("Welcome to 厦门", width=1000, height=200, fontfile="some-super-font.ttf", font="Super Font")
```

**Comment by jindili** [comment]
Tweak values in "65-nonlatin.conf" (in \vips-dev-8.8.0\etc\fonts\conf.d) would do the trick.

In my case, change this line:
line 104:
```
<family>Microsoft YaHei</family> <!-- han (zh-cn,zh-tw) -->
```
