### ISSUE TITLE
Question: Hough Line Peaks

### ISSUE THREAD

**Issue by DerrickMartinez** [libvips/libvips#1371]
First off, awesome library. It's so much quicker and more efficient than imagemagick!

I'm looking to straighten images, and thankfully there is a nice similarity function which makes it easy to rotate by degrees. But in order to determine the skew, I'm running it through canny & hough_line, and trying to get hough line peaks.

I'm supposed to get the bytes, which I read from another thread in the ruby forum they represent votes.

```
		img.Canny()
		img.Bandmean()
		img.HoughLine(vips.InputInt("width",4),vips.InputInt("height",4))
		log.Info(img.ToBytes())
```

For the 4x4, I get [8 29 2 0 22 57 0 0 100 253 0 0 68 234 4 0 6 213 1 0 227 111 1 0 125 163 2 0 13 108 1 0 224 9 2 0 187 186 2 0 218 127 2 0 53 60 0 0 124 199 1 0 184 74 2 0 175 162 1 0 0 0 0 0] Seems like too many coordinates?

Also how are these coordinates laid out? I'm supposed to count 0, 90, 180, and 270 votes right? Sorry, maybe I am doing this all wrong, but I'm not sure if I'm on the right track to figure out hough line peaks.

**Comment by jcupitt** [comment]
Hello @DerrickMartinez,

Which Ruby binding are you using? I don't think I've come across that one. In ruby-vips you'd just write:

```ruby
peaks = img.canny.bandmean.hough_line(4, 4)
```

The `hough_line` operator makes an image where pixels hold votes. You need to search the image to find the peak, then the coordinates of the peak give you the displacement and angle of the line.

I find it difficult to get good results with Hough: you need to do a lot of pre-filtering (Canny etc.) and peaks are often still fuzzy and hard to detect accurately.

Have you considered FFT instead? It's often quicker and more reliable, though it can depend on the image type.

**Comment by jcupitt** [comment]
Eg. here's an FFT-based straighten:

https://stackoverflow.com/a/52502597/894763

**Comment by jcupitt** [comment]
The hough_line docs explain how to get from peak coordinates back to line position:

https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-hough-line

For peak finding, use `max` and ask for the top eg. 10 peaks. You'll probably want to use a rank filter first to find local peaks.

**Comment by DerrickMartinez** [comment]
Thanks so much for responding! I'll probably check out FFT. 

If I go the vips route, I'd need to call vips-hough-line-> vips_rank -> vips_max? I don't know much about hough lines but I was trying to replicate the skimage lib's hough_line_peaks(). It returns angles. Any idea how that might be done? Sorry if it's a long question :)

**Comment by jcupitt** [comment]
Yes, the docs ^^^ say how. 

Imagine a line crossing an image. Now imagine a circle centred at the origin (ie. top left) large enough to just touch the line. Finally, imagine a line from the origin to the point where the circle and line cross.

Use `max` to get the x/y position of the peak, then x is 0 - 180 degrees for the angle of the line from the origin, and y is the line length (circle radius).

**Comment by DerrickMartinez** [comment]
Maybe this is a better question over at pylibvips.. I ran the example on known angles, and they all came back not what I'd expect.

Using the following: 
`#!/usr/bin/python

import sys
import pyvips

def to_rectangular(image):
    xy = pyvips.Image.xyz(image.width, image.height)
    xy *= [1, 360.0 / image.height]
    index = xy.rect()
    scale = min(image.width, image.height) / float(image.width)
    index *= scale / 2.0
    index += [image.width / 2.0, image.height / 2.0]
    return image.mapim(index)

image = pyvips.Image.new_from_file(sys.argv[1])
# to monochrome, take the fft, wrap the origin to the centre, get magnitude
fft = image.colourspace('b-w').fwfft().wrap().abs()
# sum of columns, sum of rows
cols, rows = to_rectangular(fft).project()
# blur the rows projection a bit, then get the maxpos
v, x, y = rows.gaussblur(10).maxpos()

# and turn to an angle in degrees we should counter-rotate by
angle = 270-360.0 * y / rows.height

print("Angle: "+str(angle))
print("y: "+str(y))
print("rows.height: "+str(rows.height))`

I tested three known images, and I got all wrong values. 

height=826
-----------------

actual: 13.51
y_value: 230
computed_angle: 169.757869249

--
actual: -8.0
y_value: 606
computed_angle: 5.88377723971

--
actual: 3.97
y_value: 212
computed_angle: 177.602905569

Am I doing something wrong?

**Comment by jcupitt** [comment]
You could try repeating the process -- you might get a better guess if the rotation angle is smaller.

Maybe a bit of extra filtering could help too. You could examine the output of the rect transform of the FFT and see if there's any tuning you could do of the `gaussblur()`.

**Comment by jcupitt** [comment]
Oh, it's the horizontal lines of text which should produce the biggest peak -- make sure you're getting that line from the FFT.

**Comment by DerrickMartinez** [comment]
Sorry, I'm not an expert on FFT. Where in this code would I look to find the that line?

Also, I think a deskew angle function which we can plug into vips_rotate() would be a nice feature in the future :)

**Comment by DerrickMartinez** [comment]
I ended up using the buffer from Vips in OpenCV with a few lines of code to get the angle. Someday, I hope there is a deskew angle find method :) Anyway, thanks for all your help!
