### ISSUE TITLE
 IDAT: CRC error when converting from tiff to png

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1374]
When we convert from tiff to png, we get this error intermittently. 

```
bimg:95): VIPS-WARNING **: 04:24:18.959: IDAT: CRC error
bimg:95): VIPS-WARNING **: 07:36:48.980: Not a PNG file
vips2png: unable to write to buffer
```
**Btw, we do the conversion of each tiff page to png and then join individual pngs together .**

**Comment by jcupitt** [comment]
Hi, you'll need to share some test images and code which reproduce this error.

**Comment by revathi-murali** [comment]
Here is the image:

[test_check_100.tif.zip](https://github.com/libvips/libvips/files/3425851/test_check_100.tif.zip)

As mentioned in https://github.com/libvips/libvips/issues/1359, we use [bimg](https://github.com/coupa/bimg). Since this is a different error, I thought I can create a new issue. Let me know we can talk in the https://github.com/libvips/libvips/issues/1359. If so, I can close this

**Comment by jcupitt** [comment]
Ah OK, sorry. I hadn't made the connection.

I can't help with bimg, it's not my project, you'll need to ask there.

I tried your test image with the Python code I posted in #1359 and it seems to work fine, so I don't think the problem is in libvips.

**Comment by revathi-murali** [comment]
Closing this in ref to https://github.com/libvips/libvips/issues/1359
