### ISSUE TITLE
add `map_image`

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1375]
We have `map` to put an image though a LUT: each pixel value is looked up in a table and swapped.

There's no operation where the LUT is an array of images rather than an array of constants. You have to do a long series of ifthenelse instead, which is rather slow.

Proposed API:

```C
int vips_map_image (VipsImage *in, VipsImage **out, VipsImage ***lut, int n)
```

Where pixel out(x, y) is calculated as:

    out(x, y) = lut[in(x, y)](x, y)

**Comment by jcupitt** [comment]
See https://github.com/libvips/pyvips/issues/112 for use case.

**Comment by jcupitt** [comment]
/cc @akaprasanga -- some results.

Here's a branch with `vips_switch()` implementing the proposed API:

https://github.com/libvips/libvips/tree/add-mapimage

## Benchmarks

First, with `ifthenelse`:

```python
#!/usr/bin/python3
  
import sys
import pyvips

texture_names = [
    "k2.jpg",
    "k4.jpg",
    "shark.jpg",
    "k110.jpg"
]
colors = [
    (232, 225, 199), 
    (211, 167, 73), 
    (210, 125, 60), 
    (151, 189, 174)
]

main = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

textures = [pyvips.Image.new_from_file(name)
                .replicate(100, 100)
                .crop(0, 0, main.width, main.height)
            for name in texture_names]

textured = main
for i, each_color in enumerate(colors):
    textured = (main == each_color).bandand().ifthenelse(textures[i], textured)

textured.write_to_file(sys.argv[2])
```

Then with `switch`:

```python
#!/usr/bin/python3
  
import sys
import pyvips

texture_names = [
    "k2.jpg",
    "k4.jpg",
    "shark.jpg",
    "k110.jpg"
]
colors = [
    (232, 225, 199), 
    (211, 167, 73), 
    (210, 125, 60), 
    (151, 189, 174)
]

main = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

textures = [pyvips.Image.new_from_file(name)
                .replicate(100, 100)
                .crop(0, 0, main.width, main.height)
            for name in texture_names]

masks = [((i + 1) * (main == each_color).bandand() / 255).cast("uchar")
         for i, each_color in enumerate(colors)]
    
index = masks[0]
for i in masks[1:]:
    index |= i

textured = index.switch([main] + textures)

textured.write_to_file(sys.argv[2])
```

## Timing

```
john@kiwi:~/pics$ time ~/try/texture2.py wtc.jpg x.jpg

real	0m3.440s
user	0m9.615s
sys	0m0.228s
john@kiwi:~/pics$ time ~/try/texture3.py wtc.jpg x.jpg

real	0m2.644s
user	0m6.851s
sys	0m0.278s
john@kiwi:~/pics$ 
```

## Conclusions

It's about 25% faster, which isn't very impressive. Most time is being spent making the index image. 

Instead of an index image, we should probably have two arrays of inputs: the first is a set of true/false images, the second the cases. The output pixel is from the first texture image whose case image is non-zero.

**Comment by jcupitt** [comment]
Link to C for new operation, for reference:

https://github.com/libvips/libvips/blob/add-mapimage/libvips/histogram/switch.c

**Comment by akaprasanga** [comment]
It's cool. Thank you for all your efforts!!

**Comment by jcupitt** [comment]
I fixed it up a bit more, I now see:

```
$ time ~/try/texture3.py wtc.jpg x.jpg
real	0m2.413s
user	0m6.737s
sys	0m0.264s
```

I added another operation to build the index image so you can now write:

```python
#!/usr/bin/python3

import sys
import pyvips

texture_names = [
    "k2.jpg",
    "k4.jpg",
    "shark.jpg",
    "k110.jpg"
]
colors = [
    (232, 225, 199),
    (211, 167, 73),
    (210, 125, 60),
    (151, 189, 174)
]

main = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

textures = [pyvips.Image.new_from_file(name)
                .replicate(100, 100)
                .crop(0, 0, main.width, main.height)
            for name in texture_names]

tests = [(main == each_color).bandand()
         for each_color in colors]

textured = pyvips.Image.switch(tests).case(textures + [main])

textured.write_to_file(sys.argv[2])
```

ie. you do `switch([list of tests]).case([list of results])` and for each pixel it'll evaluate all tests and the result is the matching case.

This gives:

```
$ time ~/try/texture4.py wtc.jpg x.jpg
real	0m2.100s
user	0m5.465s
sys	0m0.230s
```

So a notch faster again -- now about 40% quicker than `ifthenelse`. You'd see a bigger improvement for more complex cases.

I'll add some tests and merge.

**Comment by akaprasanga** [comment]
Ok sure ! Thanks once again !

**Comment by jcupitt** [comment]
OK, all done. This will be in 8.9.

**Comment by kleisauke** [comment]
@akaprasanga This is also integrated into NetVips (master branch). See the relevant unit tests:
[HistogramTests.cs#L151](https://github.com/kleisauke/net-vips/blob/a2209896565503fab34db587638405db55f6f3f9/tests/NetVips.Tests/HistogramTests.cs#L151)
[ConversionTests.cs#L787](https://github.com/kleisauke/net-vips/blob/a2209896565503fab34db587638405db55f6f3f9/tests/NetVips.Tests/ConversionTests.cs#L787)

**Comment by jcupitt** [comment]
Woah Kleis, you've rewritten all those tests in C#, ouch.
