### ISSUE TITLE
What is the best way to upgrade libvips on production server?

### ISSUE THREAD

**Issue by nuno360** [libvips/libvips#1378]
Hi,

I would like to know what is the best way to upgrade libvips on an production server (#1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16))?

Thanks.

**Comment by lovell** [comment]
You asked a very similar question previously at https://github.com/lovell/sharp/issues/1692 in case that helps jog your memory ;)

**Comment by nuno360** [comment]
@lovell I remember that. But libvips is different. I can't update it with npm. 

To upgrade just download the new version and compile it?

**Comment by jcupitt** [comment]
For most platforms, sharp will download a libvips binary for you when you install it.

If you are using the platform libvips (eg. apt or brew), then use those tools to update it.

If you built your own libvips previously, then uninstall it, download a newer tarball, and build and install that.

**Comment by nuno360** [comment]
Thanks @jcupitt I will do that.
