### ISSUE TITLE
Segmentation fault on concurrent requests to libvips (CPU goes high)

### ISSUE THREAD

**Issue by priyankatapar** [libvips/libvips#1380]
We are experiencing segfault issue on concurrent requests to libvips - **vips_init_image** & **vips_pngsave_buffer** (10 requests/sec for 60s duration). The CPU goes high during this time and does not drop for a long period of time.
This is the error -
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f598e2a940d]`

Is there any concurrency limit for libvips? Or any pointers on how to fix this?

**Comment by kleisauke** [comment]
Which libvips version is installed? And could you provide a GDB stacktrace? 

`vips_init_image` [indicates](https://github.com/h2non/bimg/blob/15cd11560781e3a634d3857b845d4c9c93aa454b/vips.h#L350-L377) that this is using bimg, maybe you should ask there?

@jcupitt I had a quick scan through bimg's code and noticed some weird things. For example, they are using [their own implementation](https://github.com/h2non/bimg/blob/5ab21d7b34fab791b48f496807edef05aa009b38/vips.go#L497-L528) of [`vips_foreign_find_load_buffer`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-foreign-find-load-buffer), [forcing the worker threads to 1](https://github.com/h2non/bimg/blob/5ab21d7b34fab791b48f496807edef05aa009b38/vips.go#L99-L103) and [calling `vips_thread_shutdown` too often](https://github.com/h2non/bimg/search?q=vips_thread_shutdown). Maybe we need to mark bimg as unstable within the README?

**Comment by jcupitt** [comment]
I've never really looked at the bimg source, that does sound a little odd. They seem to include some workarounds for very old libvips bugs.

Perhaps we could help with some kind of review? It's hard to find the time.

**Comment by priyankatapar** [comment]
Thanks @kleisauke for heads up! But we cannot move away from bimg right now since its in production. 
@jcupitt , we have a docker container running with 2 cores and there are 6 worker processes running inside container which calls vips methods, so is it fine if we set `VIPS_CONCURRENCY = 6` or do you foresee any issues? Or what value do you recommend for `VIPS_CONCURRENCY`?

**Comment by jcupitt** [comment]
I wouldn't set it -- just comment out all those lines.

I have some other stuff I have to finish, but when that's out of the way, I'll try to have a look through bimg and see if I can see any problems.

**Comment by revathi-murali** [comment]
I commented out the [concurrency code in bimg](https://github.com/coupa/bimg/blob/master/vips.go#L112_#L114), but still get the same seg error as mentioned in the issue description.

`[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f598e2a940d]`

I also tried with setting the concurrency to the no.of workers processing the task. Still no help.

**Comment by jcupitt** [comment]
Sorry, I wasn't very clear.

That concurrency setting looks like a workaround for a bug from a few years ago. It should be unnecessary now, and it's not going to be related to your crash.

I would guess your crash comes from some kind of interaction between libvips reference counts and the Go GC, but of course I've not looked at the code.

**Comment by revathi-murali** [comment]
Hmm, main point to note is that this happens mainly when we hit concurrent requests for converting pdf with png and we use `pdfium`.  Its like  `vips_init_image` internally calls `vips_pdfload_buffer` at which point we get segmentation fault. Do we need to add some locking before calling `vips_pdfload_buffer`??

**Comment by jcupitt** [comment]
Oh, interesting, I've not tested with pdfium much. You're right, perhaps it doesn't support parallel decoding.

Have you tested with poppler? That might narrow down the problem.

**Comment by jcupitt** [comment]
I checked the source and libvips is assuming is can decode several PDFs in parallel with pdfium.

It locks for this case:

1. open file "x.pdf"
2. thread 1 asks for page 10
3. thread 2 asks for page 15

So 2. and 3. will lock. But libvips does not lock for this case:

1. thread 1 opens file "x.pdf"
2. thread 2 opens file "y.pdf"
3. thread 1 asks for page 10 of "x.pdf"
4. thread 2 asks for page 15 of "y.pdf"

So the two page renders will run in parallel. Poppler allows this. We'd need to add more locking to `pdfiumload.c` to stop this happening.

**Comment by jcupitt** [comment]
I added some locks to 8.8 and this change should be in 8.8.2.

I can't really test it easily. Would you be able to try it out?

**Comment by revathi-murali** [comment]
Thanks a lot for the fix!

Sure, I can check tomorrow and update you.

**Comment by revathi-murali** [comment]
I tested the changes made in [this commit](https://github.com/libvips/libvips/commit/ff58c67e33358a1d7df12b7edc2c239ac47ef798) and we did not see any seg fault. Hurray! 

Sorry, I was pulled into something else and hence could not test it immediately. Once again, thanks a lot for the quick fix.

**Comment by jcupitt** [comment]
Oh nice! Glad it's working.
