### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [libvips/libvips#1382]
I would like to point out that identifiers like “[`_VipsStatistic`](https://github.com/libvips/libvips/blob/10c4831a709063189d67b7d6076b1b26bf62b2b2/libvips/arithmetic/statistic.h#L55 "Update candidate")” and “[`_JoinType`](https://github.com/libvips/libvips/blob/10c4831a709063189d67b7d6076b1b26bf62b2b2/libvips/mosaicing/global_balance.h#L38 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jcupitt** [comment]
Hello @elfring,

The libvips C++ API is a superset of the libvips C API, so it inherits a lot of those conventions.

The name `_VipsStatistic`, for example, is a glib convention for naming struct typedefs.  `_JoinType` is not part of the public API.

If you can point to part of the public C++ API which breaks a common convention, I'm sure we'd consider a rename.

I suppose we could remove the C part of the libvips C++ API, but that would be a lot of copy-paste work for little practical benefit (as far as I know).

**Comment by jcupitt** [comment]
Here's an example of glib naming, for example:

https://github.com/GNOME/glib/blob/master/glib/gtypes.h#L499

```C
typedef union _GDoubleIEEE754 GDoubleIEEE754;
union _GDoubleIEEE754
{
  gdouble v_double;
  struct {
    guint mantissa_low : 32;
    guint mantissa_high : 20;
    guint biased_exponent : 11;
    guint sign : 1;
  } mpn;
};
```

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by jcupitt** [comment]
Yes, I'm aware of that. libvips itself uses `vips__something` (ie. two underscores) to indicate internal linking, for example.

In practice, and especially for typedefs, it's not an issue on any useful platform, as far as I know. The convention comes from glib, and that's well-supported and used everywhere.

**Comment by elfring** [comment]
I suggest to [avoid the tampering with the reserved name space](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
Would you like to [improve standard compliance for the mentioned programming languages](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for naming rules")?

**Comment by jcupitt** [comment]
These things all come from the C API, where they are well established across many projects and will not be changed.

To address your concerns, we'd need to make C++-style wrappers for every C API that libvips relies on. This would be a lot of work for us (a small project), and it would mean duplicating and then maintaining a lot of extra documentation too.

I appreciate your concern, and I don't like breaking rules like this either, but it seems to be a theoretical problem rather than a practical one. I don't know of any compiler where this is actually an issue.

If anyone were to make a C++ compiler which could not use such common C libraries, I think it would not get many users, so my feeling is that this is unlikely to ever become a problem in the future.

**Comment by elfring** [comment]
>To address your concerns, we'd need to make C++-style wrappers for every C API that libvips relies on.

I do not get such an impression.


>…, but it seems to be a theoretical problem rather than a practical one.

I would prefer that questionable identifiers will just be renamed to achieve desired standard compliance instead of recurring worries around undefined software behaviour.


>…, so my feeling is that this is unlikely to ever become a problem in the future.

The problem seems to exist because involved programmers might pay insufficient development attention to specific language specifications.

**Comment by jcupitt** [comment]
One other point might be that the C++ naming rules are there to allow for mangling, and these are C extern names and will not be mangled. I think this makes any problems even less likely.

**Comment by elfring** [comment]
The important distinction is if an identifier may belong to the implementation according to the mentioned standard programming language specifications, isn't it?
