### ISSUE TITLE
vips_resize() not recognizing vscale argument

### ISSUE THREAD

**Issue by nschmeller** [libvips/libvips#1383]
When I call `vips_resize()` with the additional parameter `vscale`, the resulting image is only scaled by the `scale` argument as if I didn't include `vscale`. 

Here's the relevant part of code:

```
double xscale = (double)width / old_width;
double yscale = (gdouble)height / old_height;
LOG(INFO) << "new width: " << width << " old_width: " << old_width;
LOG(INFO) << "new height: " << height << " old_height: " << old_height;

if (!vips_resize(test, &test, xscale, yscale, NULL))
    {
        LOG(INFO) << "xscale: " << xscale << " yscale: " << yscale;

        vips_image_get(test, "width", &dim);
        LOG(INFO) << "New resized width: " << g_value_get_int(&dim);
        vips_image_get(test, "height", &dim);
        LOG(INFO) << "New resized height: " << g_value_get_int(&dim);
    }
```

and here's the output it generates:
```
I0804 14:06:23.527585 64198 convert.cpp:141] new width: 500 old_width: 275
I0804 14:06:23.527603 64198 convert.cpp:142] new height: 500 old_height: 440
I0804 14:06:23.530138 64198 convert.cpp:146] xscale: 1.81818 yscale: 1.13636
I0804 14:06:23.530208 64198 convert.cpp:149] New resized width: 500
I0804 14:06:23.530230 64198 convert.cpp:152] New resized height: 800
```
The "new resized height" should be 500 as was printed before the resize. The (incorrectly resized) image is being written correctly and everything else looks good besides this. My vips version is 8.8.1. 

For what it's worth, I set a gdb breakpoint at `vips_resize_build()` in `resize.c` in the libvips source code. When I was stepping through that function, I noticed that `if( vips_object_argument_isset( object, "vscale" ) )` (line 190 on master branch and 8.8 branch) was not taken, even though I do pass a `vscale` arg. Am I doing something wrong, or is the additional parameter not being passed correctly?

**Comment by jcupitt** [comment]
Hello @nschmeller,

In the libvips C API, extra optional arguments are passed as name-value pairs, so you need:

```C
if (vips_resize (in, &out, scale,
    "vscale", vscale,
    NULL)) 
    error-handling-code;
```

You also shouldn't use the same `VipsImage` for `in` and `out` -- you'll find you leak references. I would write something like:

```C
if (vips_resize (in, &out, scale,
    "vscale", vscale,
    NULL)) {
    g_object_unref (in);
    error-handling-code;
}
g_object_unref (in);
in = out;
```

Or use an unref pool. `vips_leak_set (TRUE);` is handy for finding reference leaks.

You could also use the C++ API, which automates most of this:

``C++
/* compile with:
 *
 *      g++ -g -Wall resize.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <vips/vips8>

using namespace vips;

int
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        VImage in = VImage::new_from_file( argv[1], VImage::option()
                ->set( "access", "sequential" ) ); 

        VImage out = in.resize( 0.2, VImage::option()
                ->set( "kernel", "cubic" )
                ->set( "vscale", 0.2 ) );

        out.write_to_file( argv[2] );

        vips_shutdown();

        return( 0 );
}
```

Except for the ugly `VImage::option` thing.

Most of the time, don't use `resize` unless you are sure that's what you want. `thumbnail` is faster and better quality.

**Comment by nschmeller** [comment]
This works perfectly, thank you so much. Also, thanks for the advice! That's definitely good to know about leaking references.
