### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [libvips/libvips#1384]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/libvips/libvips/blob/3ea72c286e704ce14049eca04cb37c3b58ea0a02/configure.ac#L452 "Update candidate")?

**Comment by jcupitt** [comment]
Hi again,

You're right, we were not using all of the flags we should for testing for pthread_setattr_default_np().

I don't think AX_PTHREAD is correct though -- libvips uses gthread for most of its threading functionality, so we need to use those flags when checking for setattr_default.

I've tried moving the test after GTHREAD, does that look OK? It builds the test program like this on my laptop:

```
configure:18152: checking for pthread_setattr_default_np
configure:18152: gcc -o conftest -g -Wall -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   conftest.c  -lgthread-2.0 -pthread -lglib-2.0 >&5
configure:18152: $? = 0
configure:18152: result: yes
```

Is that enough to fix your issue?

**Comment by elfring** [comment]
* How many software portability concerns are shared between “GTHREAD” and “PTHREAD”?
* Would you like to improve the build specification for corresponding parts “ACTION-IF-FOUND” and “ACTION-IF-NOT-FOUND”?

**Comment by jcupitt** [comment]
gthread is a portability layer over pthread and the Windows threading API.

glib no longer supports platforms without threading, so I think there's no not-found action here.

**Comment by elfring** [comment]
* I wonder about the variables “`save_…`”.
* Should the check for “`pthread_…_np`” depend on a precondition?
* Will the setting “`CC="$PTHREAD_CC"`” become relevant occasionally?
* Do you expect an error message for insufficient support of multi-threading?

**Comment by jcupitt** [comment]
libvips requires glib and glib requires threads, so it will fail a long time earlier on platforms without this.

Yes, PTHREAD_CC seems to be required for a build on AIX with the native compiler. I suppose glib must build there with gcc. Again, I think we can give that problem to glib.

**Comment by jcupitt** [comment]
You're right, I changed it to use safer names for the save variables.

I'll try building on macOS and win.

**Comment by jcupitt** [comment]
It seems to build OK on win, let's merge. Thanks for suggesting this improvement!

**Comment by elfring** [comment]
I am still unsure about [the presented movement of the check for “GTHREAD”](https://github.com/libvips/libvips/commit/0d2c14c967b26a5a6f238f27a08ad72a3abce8d2#diff-67e997bcfdac55191033d57a16d1408aR488 "Try to improve pthread discovery").
How will the clarification evolve further for affected software build details?

**Comment by jcupitt** [comment]
Previously, we were only getting `GTHREAD` libs and flags for older glibs, when gthread was optional. Now we always need these flags, since we will always test for `pthread_setattr_default_np()`. 

Therefore we we must always run `PKG_CHECK_MODULES(GTHREAD, gthread-2.0)`, and we must run it before we test for `pthread_setattr_default_np()`.

**Comment by elfring** [comment]
Thanks for another bit of background information.

I got build concerns because of the mentioned version constraints.
