### ISSUE TITLE
expecting same results as PIL

### ISSUE THREAD

**Issue by aravind3134** [libvips/libvips#1389]
Hi John,

I was trying to replace PIL commands with that of pyvips.

I could use extract_area method in vips successfully in place of crop in PIL. 

But, I could see inconsistencies when I tried to save using pngsave or write_to_file in vips.

Can you suggest a better way to replace the save method from PIL in pyvips? Am I doing something wrong? 

Thanks!

**Comment by jcupitt** [comment]
Hello @aravind3134,

You can use `crop` in pyvips too.

What kinds of inconsistencies do you see? Post an example and say what you think is wrong or missing.

**Comment by jcupitt** [comment]
I'll close. Please reopen if you have an example.
