### ISSUE TITLE
Helper methods to get page count of pdf using pdfium

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1393]
Are there any helper methods in `libvips`(using pdfium) to get the no. of pages in the pdf document?

**Comment by jcupitt** [comment]
Sure:

```
$ vipsheader -f n-pages nipguide.pdf 
58
```

Or in Python:

```
$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("nipguide.pdf")
>>> x.get("n-pages")
58
```

**Comment by revathi-murali** [comment]
Thanks 👍

**Comment by revathi-murali** [comment]
I would like to use the method `vips_foreign_load_pdf_header` directly and I am not sure how to pass the argument `VipsForeignLoad` to the method. Any suggestions?

**Comment by jcupitt** [comment]
That's internal API, you can't call it directly. 

libvips won't load the whole PDF on open, it just gets the header. Pages are only rendered when you ask for pixels.

Try:

```python
x = pyvips.Image.new_from_file("something.pdf")
n_pages = x.get("n-pages")
```

You'll find it's very quick, even for huge PDFs.
