### ISSUE TITLE
Noisy conversion from VipsImage to CV Mat

### ISSUE THREAD

**Issue by nschmeller** [libvips/libvips#1394]
I'm attempting to write a VipsImage to a Mat from openCV using libvips 8.8.1. I'm checking that the conversion was accurate by writing the VipsImage immediately before conversion and the converted Mat to .jpg images, and visually comparing them. In each test case, the VipsImage appears as expected, whereas the Mat image has a little blip of noise in the top left corner, sometimes extending to the top tenth of the image depending on filetype and whether a white pad was added to preserve aspect ratio. 

The expected image (aka the written VipsImage):
![image](https://user-images.githubusercontent.com/26189705/62835252-aaccb180-bc5e-11e9-8494-6e178b5f3628.png)

The image with the blip of noise in the top left corner, look all the way to the left beyond all the whitespace (aka the written Mat with padding):
![image](https://user-images.githubusercontent.com/26189705/62835268-ee272000-bc5e-11e9-9240-cbd468d70a6e.png)

The expected VipsImage _without padding_:
![image](https://user-images.githubusercontent.com/26189705/62835611-27fa2580-bc63-11e9-9038-058c3fb566c1.png)

The image with noise across the top tenth (aka the written Mat _without padding_):
![image](https://user-images.githubusercontent.com/26189705/62835280-4bbb6c80-bc5f-11e9-9d84-98839add77d4.png)

The input image for those examples was formatted as a gif (not animated). 

Another interesting observation is that jpg formatted images worked perfectly without padding, and only had the small blip of noise in the top left corner with padding. 

Here's my code to convert from VipsImage to cv::Mat (this was spliced together from #929 and #1105):
```
cv::Mat vipsToMat(VipsImage *image, int height, int width)
{
    int channels = 0;
    cv::Mat cv_mat;
    vips::VImage in = vips::VImage(image);

    // switch from RGB to BGR
    std::vector<vips::VImage> bands = in.bandsplit();
    vips::VImage t = bands[0];
    bands[0] = bands[2];
    bands[2] = t;
    in = vips::VImage::bandjoin(bands);

    switch (in.bands())
    {
    case 1:
        channels = CV_8UC1;
        break;
    case 2:
        channels = CV_8UC2;
        break;
    case 3:
        channels = CV_8UC3;
        break;
    case 4:
        channels = CV_8UC4;
        break;
    default:
        return cv_mat;
    }

    size_t image_data_size = 0;
    void *image_data = in.write_to_memory(&image_data_size);
    cv_mat = cv::Mat(in.height(), in.width(), channels, image_data);
    g_free(image_data);

    cv::imwrite("out.jpg", cv_mat);
    return cv_mat;
}
```

I'm lost on what I can change in my code to prevent this from happening. I'm assuming that the problem is in the function above, because the VipsImage that was written right before the function call was fine. My guess is that the noise comes from image header data being written on top of the memory space (and that I have to specify extra space for that data), but I'm not sure how to deal with that because the VImage `write_to_memory()` call should handle all of that. How do I get rid of the noise?

**Comment by jcupitt** [comment]
Huh very strange.

Does `cv::Mat()` take a copy of the data? If it doesn't, your `g_free()` afterwards could allow the memory area to be overwritten and that would cause noise.

I would try commenting out the `g_free()` and see if that fixes it.

**Comment by jcupitt** [comment]
If `cv::Mat()` does not take a copy, then you need to arrange for the `g_free()` to happen when the mat is finally freed. 

I don't know if opencv lets you attach finalizers -- if it doesn't, you'll probably need to subclass Mat and add it to the destroy.

The bandswapping is annoying, it's a shame that's necessary.

**Comment by nschmeller** [comment]
Turns out that the constructor I used for `cv::Mat()` does not take a copy, so freeing the image data was introducing noise into part of the Mat data. For future reference, I ended up using cv::Mat's `clone()` and freed after that. Thanks for the advice!

**Comment by jcupitt** [comment]
`clone()` is slower, of course. If you can find a way to hook into finalize you'll see a drop in memory use and a speedup.
