### ISSUE TITLE
hist_equal on colour image

### ISSUE THREAD

**Issue by harukizaemon** [libvips/libvips#1395]
I'd like to do a histogram equalisation on an sRGB image but only applying the equalisation to the lightness/intensity. I can see an easy path to HSV and thus using the V channel, but would there be a better option e.g. somehow getting to Lab and using the L channel instead? At first glance, it looks like I'd need a series of steps to get there.

**Comment by jcupitt** [comment]
Hi Simon, you can just use `colourspace`. In Python:

```
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])

x = x.colourspace("lab")
l = x[0]
ab = x[1:3]

# l is 0 - 100 float -- rescale to 0 - 65535 ushort
l = (l * 65535 / 100).cast("ushort")

l = l.hist_equal()

l = l * 100 / 65535

x = l.bandjoin(ab)
x = x.colourspace("srgb")

x.write_to_file(sys.argv[2])
```

**Comment by jcupitt** [comment]
Oh, I guess you could do:

```python
x = pyvips.Image.new_from_file()
original_inter = x.interpretation
x = x.colourspace("lab")

# process in lab space

x = x.colourspace(original_inter)
x.write_to_file()
```

And it'll work for cmyk and mono as well.

**Comment by harukizaemon** [comment]
Thanks as always @jcupitt! I'll translate that into some Ruby and see how I go.

**Comment by harukizaemon** [comment]
Worked beautifully! Only change I made was to use `x.extract_band(1, n: x.bands - 1)` so it'd work on RGB (no alpha) and mono.

**Comment by jcupitt** [comment]
Oh good point, I'd forgotten about alpha. It should be:

```python
ab = x[1:]
```

Or in Ruby you can slice with ranges, eg.

```
x[1]
x[1..2]
x[1...x.bands]
```
