### ISSUE TITLE
Possible memory leak when vips_vector_init

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1402]
I am using libvips `8.8.1` and use `bimg` to interact with libvips. When I ran the valgrind report, I could see some memory leaks from `vips_vector_init` and other parts. I have attached the valgrind report for the same. Not sure if the leaks are at the `vips` level or at the `gobject` level. Can you please have a look at the report and clarify?

Note: I am running the valgrind with libvips suppressions 

[vips_valgrind_report.txt](https://github.com/libvips/libvips/files/3524998/vips_valgrind_report.txt)

**Comment by jcupitt** [comment]
Those aren't leaks: it's just init stuff that's not freed. I should probably update the valgrind suppressions.

**Comment by revathi-murali** [comment]
Okay sure. Let me know once `libvips.supp` file is updated.

**Comment by jcupitt** [comment]
i'm using ASAN now rather than valgrind, so I may not get around to this myself any time soon. Please open a PR is you'd like something sooner.

**Comment by jcupitt** [comment]
libvips is now in OSS Fuzz and is continually tested by Google for memory leaks. You shouldn't need to test yourself, hopefully.

**Comment by revathi-murali** [comment]
> libvips is now in OSS Fuzz and is continually tested by Google for memory leaks. You shouldn't need to test yourself, hopefully.

Thats a good news! Thanks, I will close the issue then.

**Comment by jcupitt** [comment]
I wrote a post about it a few days ago, if you're interested:

https://libvips.github.io/libvips/2019/08/18/libvips-in-oss-fuzz.html
