### ISSUE TITLE
experiment with libspng

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1403]
libspng looks like a nice replacement for libpng:

https://libspng.org/

- faster
- much simpler and more modern API
- should be more robust

It's currently (Aug 2019) missing streaming (ie. decoding an image a few scanlines at a time) and encode (decode only for now).

These features are on their roadmap. When they go in, we should look at switching.

**Comment by jcupitt** [comment]
The 0.6 milestone looks like it should have enough for read support:

https://github.com/randy408/libspng/milestone/1

Randy says write support is some way off.

**Comment by jcupitt** [comment]
git master libspng now has progressive read support:

https://github.com/randy408/libspng/blob/master/examples/example.c#L76

So we can make an experimental `pngread` operation using it.

**Comment by jcupitt** [comment]
Experimental libspng reader here:

https://github.com/libvips/libvips/blob/libspng-experiment/libvips/foreign/spngload.c

It compiles, but I've not tried running it yet.

**Comment by jcupitt** [comment]
It seems to work. libspng benchmark, 10k x 10k RGB PNG:
    
``` 
$ time vips avg wtc.png
151.549325

real  0m3.167s
user  0m3.714s
sys 0m0.194s
```

And for libpng:
    
```
$ time vips avg wtc.png
117.065766
    
real  0m3.816s
user  0m4.177s
sys 0m0.221s
```

The avg is different since libspng is generating alpha 255.

```
/* Notes:
 *
 * an enum for interlace_method would be nice ... ADAM7 == 1, 
 *   no interlace == 0.
 * an equivalent of png_sig_cmp() from libpng (is_a_png on a memory area)
 *
 * This always reads RGBA8 or RGBA16. Other formst G8/G16/GA8 etc. etc. are
 * in the roadmap.
 *   
 * Most metadata support (eg. XMP, ICC, etc. etc.) is missing.
 *  
 * Load only, there's no save support for now.
 */ 
```

That's for v0.6. We should look again when v0.8 is out.

**Comment by jcupitt** [comment]
Update: libspng now supports all output formats, so this benchmarks runs a little quicker and generates identical pixels to libpng:

```
$ time vips avg wtc.png
117.065766

real  0m2.972s
user  0m3.376s
sys 0m0.197s
```

So now about 25% faster.

Next update once metadata support is working.

**Comment by kmartinez** [comment]
exciting times!

**Comment by kleisauke** [comment]
I tried a benchmark on Windows. The binaries were built from the [`libspng-experiment`](https://github.com/libvips/build-win64-mxe/tree/libspng-experiment) branch on the [`build-win64-mxe`](https://github.com/libvips/build-win64-mxe) repository. The [`README.md`](https://github.com/libvips/build-win64-mxe/blob/libspng-experiment/README.md) contains details about the versions used.

**Test image**
https://commons.wikimedia.org/wiki/File:North_Africa_and_Europe_from_Suomi_NPP_-_NASA_Earth_Observatory.jpg (10k × 10k pixels)
Converted to PNG with: 
```bash
$ vips copy North_Africa_and_Europe_from_Suomi_NPP_-_NASA_Earth_Observatory.jpg earth.png
```

**Benchmark**
<details>
  <summary>BenchmarkDotNet program</summary>

```csharp
namespace NetVips.Benchmarks
{
    using BenchmarkDotNet.Attributes;

    [Config(typeof(Config))]
    public class Benchmark
    {
        [GlobalSetup]
        public void GlobalSetup()
        {
            // Disable libvips' operation cache
            NetVips.CacheSetMax(0);
        }

        [Benchmark(Description = "libspng with zlib-ng", Baseline = true)]
        [Arguments("earth.png")]
        public void PNG(string input)
        {
            var im = Image.NewFromFile(input, access: "sequential");
            var _ = im.Avg();
        }
    }
}
```
</details>

**Results**
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.836 (1909/November2018Update/19H2)
Intel Core i5-8600K CPU 3.60GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.1.300
  [Host]            : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
  .Net Core 3.1 CLI : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT

Job=.Net Core 3.1 CLI  Toolchain=.NET Core 3.1  

```
|                    Method |     input |     Mean |   Error |  StdDev | Ratio |
|-------------------------- |---------- |---------:|--------:|--------:|------:|
|    **&#39;libspng with zlib-ng&#39;** | **earth.png** | **916.7 ms** | **0.95 ms** | **0.89 ms** | **1.00** |
| &#39;libspng without zlib-ng&#39; | earth.png | 1.161 s | 0.0010 s | 0.0008 s | 1.27 |
|     &#39;libpng with zlib-ng&#39; | earth.png | 1.217 s | 0.0009 s | 0.0008 s | 1.32 |
|  &#39;libpng without zlib-ng&#39; | earth.png | 1.456 s | 0.0028 s | 0.0026 s | 1.59 |

So, on this benchmark, libspng built with zlib-ng is about ±58% faster than libpng with vanilla zlib and ±32% faster when libpng is built with zlib-ng as well.

**Comment by jcupitt** [comment]
That's great! zlib-ng is impressive.

**Comment by jcupitt** [comment]
OK, it seems to be fixed up and working now, thanks to a lot of help from @randy408. I'll close this issue and make a PR.
