### ISSUE TITLE
gifload_buffer: Wrong record type detected

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1404]
When `vips_gifload_buffer` is called internally from my project, I get the following error:

`vips_realpath: unable to form filename\nunix error: No such file or directory\ngifload_buffer: Wrong record type detected\`

We use giflib alpine package -  https://pkgs.alpinelinux.org/package/edge/main/armhf/giflib

**Note**: The same gif file was working fine in vips - 8.7.4 but getting the error after upgrading to - `8.8.1`.

Please refer to the below sample gif file that causes the error:

![PIL-V_AN](https://user-images.githubusercontent.com/2732287/63597605-7ef4e880-c5db-11e9-98d0-7ec97555deba.gif)

**Comment by jcupitt** [comment]
I relaxed the rules for GIT parsing a bit and it works now. Thanks for the report!

This will be in 8.8.2.

**Comment by revathi-murali** [comment]
When `8.8.2` will be released?

**Comment by jcupitt** [comment]
No idea! Maybe a week or two?

**Comment by revathi-murali** [comment]
After applying the patch https://github.com/libvips/libvips/commit/4b677fb16a95f11ee1fe02502b1565cfc3d2ad19, I get a different error for the sample gif below:

```
vips_realpath: unable to form filename
unix error: No such file or directory
gifload_buffer: bad frame size
```
![PAINT](https://user-images.githubusercontent.com/2732287/63680062-64f01b80-c810-11e9-8fb1-29542a1d4caf.gif)

Note: The same gif was working fine in `v8.7.4`.

**Comment by jcupitt** [comment]
Thanks for the new example -- I relaxed the rules again and your brush GIF loads now.

https://github.com/libvips/libvips/commit/25e457736173369dcb0f7c09d07af68aedbdc175

**Comment by jcupitt** [comment]
And the moose.

**Comment by revathi-murali** [comment]
So for gifload loading forever (moose) - f6cc2a9055809f9cdda2eec6ab306b8156bbf8d5 is the fix?

**Comment by jcupitt** [comment]
OK, I think this is all working now, I'll close.
