### ISSUE TITLE
build vips with imagemagick

### ISSUE THREAD

**Issue by gurukashyap** [libvips/libvips#1405]
Hi,

I wanted to convert PSD to jpg using vipsthumbnail. However its complaining that format not supported. Can you tell me how can I build vips with imagemagick support. When i build i see this below. However i have installed imagemagick & set ld & cpp flags accordingly. The OS is Redhat linux. Any help is appreciated.

```
checking for IMAGE_MAGICK... no
configure: WARNING: neither MagickCore nor ImageMagick found; disabling Magick support
```

**Comment by kleisauke** [comment]
If you are able to install a third party repository, it might be easier to follow these instructions:
https://github.com/libvips/libvips/issues/1184#issuecomment-447973135

Remi's RPM repository contains an updated version of libvips with ImageMagick support.

**Comment by jcupitt** [comment]
Did you install `imagemagick-devel`? It contains all the headers you need to compile programs taht use imagemagick's API.

**Comment by gurukashyap** [comment]
I have built imagemagick from source , I am able to use imagemagick as well. However Libvips installation is not able to detect there is imagemagick.

https://www.imagemagick.org/script/install-source.php#unix

**Comment by jcupitt** [comment]
Then it depends where you installed it. `pkg-config` needs to be able to see the `.pc` file, so you need to have that area on your `PKG_CONFIG_PATH`.

Try:

```
$ pkg-config MagickWand --cflags
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6
$ echo $PKG_CONFIG_PATH 
/home/john/vips/lib/pkgconfig
```

**Comment by gurukashyap** [comment]
Thanks John after fixing pkg-config  by updating Imagemagick location, I was able to successfully build

**Comment by LachlanNewman** [comment]
> 

@gurukashyap do you remember what location you had to move imagemagick to?

**Comment by gurukashyap** [comment]
yes I moved to libs of vips.
