### ISSUE TITLE
gifload - loading forever

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1407]
I have a sample gif file which is loading forever when I run `gifload`

Vips Version: 8.8.1

Sample Gif file:

![MOOSE](https://user-images.githubusercontent.com/2732287/63683086-15611e00-c817-11e9-863a-fa438a170fdf.gif)

Note: The above image was loading fine in `v8.7.4`

**Comment by jcupitt** [comment]
This works with 8.8 HEAD. 8.8.2 should be out soon and will include this.
