### ISSUE TITLE
Building libvips from source

### ISSUE THREAD

**Issue by gurukashyap** [libvips/libvips#1408]
Hi,

I am trying to build libvips from source & see following issue during make / make install : Could you help me in figuring out.

/usr/bin/ld: warning: libjpeg.so.62, needed by ../libvips/.libs/libvips.so, may conflict with libjpeg.so.9
../libvips/.libs/libvips.so: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
../libvips/.libs/libvips.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
../libvips/.libs/libvips.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'

**Comment by jcupitt** [comment]
Hello @gurukashyap,

You are trying to compile libvips against libtiff and libjoeg. Your libtiff itself uses a different libjpeg to decompress jpeg-in-tiff images. These two versions of libjpeg are in conflict.

```
libvips ---> libtiff ---> libjpeg A
        ---> libjpeg B
``

You must use the same version of libjpeg everywhere.

**Comment by gurukashyap** [comment]
Thanks John it helped, I was able to make install after fixing libtiff version.
