### ISSUE TITLE
Enabling Logging in Libvips Java Wrapper

### ISSUE THREAD

**Issue by codecitizen** [libvips/libvips#1409]
I'm trying to enable logging in my libvips java wrapper by registering a log handler in GLib, calling (1). 

I mapped the function:

```java
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Pointer;

public interface GLibBindings extends Library {
  int g_log_set_handler(String log_domain, int log_levels, Callback log_func, Pointer user_data);
  void g_log(String log_domain, int log_levels, String format, Object...args);
}
```

Including the log (2) function to test. 

Calling `g_log` successfully forwards to my handler. But there seem to be no warning, debug or any other levels of logs coming from libvips.

This is how I register the VIPS handler:

```java
        int flags = Arrays.stream(GLogLevelFlags.values())
                .map(GLogLevelFlags::getVal)
                .reduce((l1, l2) -> l1 | l2).orElse(GLogLevelFlags.G_LOG_LEVEL_DEBUG.getVal());
        GLibLogHandler handler = (d, f, m, p) -> loggingFunction.accept(f, m);
        GLibBindingsSingleton.instance()
                .g_log_set_handler("VIPS", flags, handler, null);
```

*(`GLibLogHandler` and `GLibBindingsSingleton` are just some helper classes)*

So my question: Am I missing anything I have to setup besides registering the log handler?

(1) https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-log-set-handler
(2) https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-log

**Comment by jcupitt** [comment]
Hello @codecitizen, 

libvips does not have a huge amount of logging. There's some for thumbnail and convolution:

```
$ vips thumbnail k2.jpg x.jpg 128 --vips-info
VIPS-INFO: 16:37:27.037: thumbnailing k2.jpg
VIPS-INFO: 16:37:27.039: selected loader is VipsForeignLoadJpegFile
VIPS-INFO: 16:37:27.039: input size is 1450 x 2048
VIPS-INFO: 16:37:27.039: loading jpeg with factor 8 pre-shrink
VIPS-INFO: 16:37:27.039: pre-shrunk size is 181 x 256
VIPS-INFO: 16:37:27.039: converting to processing space srgb
VIPS-INFO: 16:37:27.039: residual reducev by 0.5
VIPS-INFO: 16:37:27.039: reducev: 13 point mask
VIPS-INFO: 16:37:27.041: reducev: using vector path
VIPS-INFO: 16:37:27.041: reducev sequential line cache
VIPS-INFO: 16:37:27.041: residual reduceh by 0.5
VIPS-INFO: 16:37:27.041: reduceh: 13 point mask
```

All `--vips-info` does is set `G_MESSAGES_DEBUG` so that the default log handler prints the messages.

**Comment by jcupitt** [comment]
I'd be interested in the technicalities of your java wrapper --- did you base it on the structure of any of the existing ones? I guess C# would be the closest:

https://github.com/kleisauke/net-vips

That one uses introspection, so the binding itself is rather small (~1500 lines) and (mostly) self-updates.

**Comment by codecitizen** [comment]
@jcupitt Hi,

okay, will test with the thumbnails function later. 

You can have a look at the java wrapper here: https://github.com/codecitizen/jlibvips 

We decided to map the C API and not the GObject structure, seemed easier and JNA has nice varargs support.

**Comment by codecitizen** [comment]
Should there appear any debug logs on `dzsave`? I'm explicitly adding this feature to jlibvips, since we experience a `-1` return value on `dzsave` when trying to save to `.webp` tiles, but can't figure out why the `-1` is given. So I hoped for more logs.

**Comment by codecitizen** [comment]
@jcupitt yeah so logging on thumbnails worked fine, thanks!

**Comment by jcupitt** [comment]
Did you figure out the webp problem?

You've probably seen quite a few `printf()`s in `dzsave.c` with `#ifdef DEBUG` wrapped around them. Perhaps some of them should be turned into `g_info()`?

**Comment by codecitizen** [comment]
We upgraded to the latest version of webp and all worked fine then. 

We compiled vips with DEBUG enabled, didn't see any output.

**Comment by jcupitt** [comment]
Try uncommenting these lines and rebuilding:

https://github.com/libvips/libvips/blob/master/libvips/foreign/dzsave.c#L151

You should see bucketloads of diagnostics on stdout.

**Comment by codecitizen** [comment]
@jcupitt thanks for the tip! Next time we're running into issues we sure make use of it. For the issue described before, it seems to have been a version incompatibility.

**Comment by Enerccio** [comment]
Does the logging work? I tried jlibvips but no logging, manual logging via `g_log` works fine. Or do you need to compile specific version of library?
