### ISSUE TITLE
Alpha for HEIC images is black

### ISSUE THREAD

**Issue by meyermarcel** [libvips/libvips#1411]
Converting from a PNG image with alpha to an HEIC image the transparent parts in the HEIC image are black.

![tree-with-transparency](https://user-images.githubusercontent.com/3398801/63752035-c7005d80-c8b0-11e9-90c3-1d150cee29c1.png)

Executing this command with the image above reproduces the HEIC image in [tree-with-transparency.heic.zip](https://github.com/libvips/libvips/files/3544979/tree-with-transparency.heic.zip) (no .heic supported by Github).

```
vips copy tree-with-transparency.png tree-with-transparency.heic
```
Vips version: `libvips 8.8.1-Sun Jul  7 10:04:59 UTC 2019`
OS: `macOS Mojave 10.14.6 (18G95)`
vips was installed with Homebrew which downloads the build from https://github.com/libvips/libvips/releases/download/v8.8.1/vips-8.8.1.tar.gz

I could not understand the comment above this line. It sounded for me that there is already awareness for alpha behaviour in HEIC images:
https://github.com/libvips/libvips/blob/8b1817ddd073c35aff3ae185b5e24fdea031a69e/libvips/foreign/heifsave.c#L205

Thanks @jcupitt for this library.

**Comment by jcupitt** [comment]
Hello @meyermarcel,

I think I just didn't have any HEIC samples with an alpha channel. The test images I could find were just shots on iphones.

I'll have a look -- thanks for the sample.

**Comment by meyermarcel** [comment]
Hey @jcupitt 

thanks for your quick response.

Just in case this is helpful, [here is the zipped image](https://github.com/libvips/libvips/files/3545450/tree-with-transparency.heif.zip) as .heif with [libheif](https://github.com/strukturag/libheif) 1.4.0_1 and transparent parts.

Created with this command:

```
heif-enc tree-with-transparency.png -o tree-with-transparency.heif
```

**Comment by meyermarcel** [comment]
[libheif](https://github.com/strukturag/libheif) 1.5.0 had a bug, so creating an heif with tranparency was broken. The recent release of [libheif 1.5.1](https://github.com/strukturag/libheif/releases/tag/v1.5.1) fixed this bug and creating heif images with transparency works again.

**Comment by jcupitt** [comment]
libheif master, v1.5.1 and v1.5.0 all fail with your PNG. I see:

```
$ heif-enc tree.png -o tree.heif
heif-enc: malloc.c:2392: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.  
Aborted (core dumped)
```

I'll open an issue. 1.4.1 works, fortunately. 

I enabled RGBA chroma in libvips `heifload` and it seems to work there too. 

I'll try `heifsave` next.

**Comment by jcupitt** [comment]
I enabled alpha in `heifsave` and it seems to mostly work. I get some funny edges though:

![x](https://user-images.githubusercontent.com/580843/64079031-3673b400-ccda-11e9-8c61-d9897f80223f.png)

It might be a bug in libheif, I'll keep digging.

**Comment by jcupitt** [comment]
For reference, test `heifload` with:

```
heif-enc tree.png -o tree.heif && vips copy tree.heif x.png && eog x.png
```

Test `heifsave` with:

```
vips heifsave tree.png x.heic && vips copy x.heic x.png && eog x.png
```

**Comment by jcupitt** [comment]
libheif issue reference: https://github.com/strukturag/libheif/issues/151

**Comment by meyermarcel** [comment]
Hey @jcupitt 

thanks for the quick response and the thorough analysis. I thought about the same opening an issue at strukturag/libheif but I cannot distinguish which of these causes the behaviour:

1. PNG with wrong/missing metadata
1. bug in libheif
1. bug in vips
or
1. possible enhancement in vips

Additionally I have only minor C/C++ knowledge. I tried to build the strukturag/libheif building on my macOS but I failed.
So thanks again for your this awesome repository. If I could help in any manner please let me know.

**Comment by jcupitt** [comment]
Ah, got it, we needed to set plane bits as well. I now see:

![x](https://user-images.githubusercontent.com/580843/64081571-f53fcc00-ccfa-11e9-8ffa-a19a9c424b27.png)

I think this is all working. This fix will be in 8.9, thanks for reporting it!

**Comment by jcupitt** [comment]
libheif have fixed their bug in master, 1.5.2 should work.

**Comment by yanxianrui** [comment]
I use libvips8.10.2 and libheif1.6.1 and seems still have this problem.

**Comment by yanxianrui** [comment]
I use vips8.10.2 and libheif1.6.1 and seem still have this.  
input: ![in](https://user-images.githubusercontent.com/25117053/103795735-4eeb9f80-5081-11eb-9032-e8df732106ef.png) 
output:  [out.zip](https://github.com/libvips/libvips/files/5777039/out.zip)
do i miss some params or something?  thanks for any reply.

**Comment by jcupitt** [comment]
This seems to be working for me. If I run:

```
vips copy out.heic y.png
```

Or:

```
heif-convert out.heic y.png
```

I see the correct transparency in `y.png`. This is with libheif 1.6.1 and libvips 8.10.

What are you using to test transparency in heic images?

**Comment by yanxianrui** [comment]
thanks for you response. 
I use  win10 hevc video extension. I later found that these pictures can be displayed normally on mac and ios. so I delete my question. It seems that win10 does not support heic with alpha...

**Comment by jcupitt** [comment]
Yes, heic is still very new, and quite complex. It'll take a while before it's well-supported everywhere.
