### ISSUE TITLE
Losing alpha channel with pdfload and crop

### ISSUE THREAD

**Issue by blackpond** [libvips/libvips#1412]
I have a pdf that I'm converting to pngs.  From my checks - the alpha channel is being retained, but the resulting files created seem to be flat?  Are there options for keeping the alpha?  From the docs I assumed that the alpha was kept unless you flattened it.  Thanks!

```ruby
pdf = Vips::Image.pdfload(Rails.root.join("public/uploads/pdf_package/#{model.id}/#{file_name}").to_s, dpi: 200, n: -1)

pp pdf.has_alpha?
=> true

pdf.write_to_file(Rails.root.join("public/uploads/pdf_package/#{model.id}/vip-all.png").to_s)
n_pages = pdf.get 'pdf-n_pages'
page_height = pdf.get 'page-height'

pages = @pages_array.map do |page_number|
  pp page.has_alpha?
 => true
  image.crop(0, (page_number - 1) * page_height, image.width, page_height)
end

pages.each_with_index do |page, index|
  page.write_to_file(Rails.root.join("public/uploads/pdf_package/#{model.id}/vip-#{@pages_array[index]}.png").to_s)
end

```

**Comment by jcupitt** [comment]
Hello, libvips just passes poppler's RGBA though, so I'd guess that poppler is not detecting the alpha. 

Could you upload a sample PDF somewhere?

**Comment by fatfrog** [comment]
Sure!  Here is the original PDF, along with a png I converted using Vips, and a second png I converted using "convert" in the terminal.  Thanks again!

https://drive.google.com/drive/folders/1eCOyaOARIaIm4YSPoQip34h9B9zQSTya?usp=sharing

**Comment by jcupitt** [comment]
I tried to improve the docs a little.

**Comment by jcupitt** [comment]
You should just be able to do `background: 0`, does that not work?

**Comment by jcupitt** [comment]
Oh, no problem, I'm glad it's working.

Do be careful of licensing: poppler is GPL, so if you use it in ruby-vips, everything else becomes GPL too. This means you have to open-source everything **if you distribute it**. Web apps are fine, since you're not distributing anything, but in something like electron, you could be affected.

You can configure libvips to use pdfium instead, which has an MIT licence, but it's a bit trickier to build.

**Comment by jcupitt** [comment]
(ruby-vips is part of Rails6, Amazon use it for their image resizing service, it's part of Google's OSS Fuzz etc. etc. so it's quite mainstream now)

**Comment by fatfrog** [comment]
background: 0 works.  Thanks for the licensing info - that had not occurred to me.  It is just a web app, but what would I have to do for it to be considered "distributed"?  By selling a plugin?

**Comment by jcupitt** [comment]
It's if you include a copy of poppler in any binaries you give people. For example, if you have a docker image of your system available and there's a copy of poppler in there, the whole thing becomes GPL and you need to make sure you gave out the sources for everything.

Something like AWS, where you have exclusive control of the machine, doesn't count and that's fine. It's if you give a copy of your system to someone else for their use.

https://opensource.stackexchange.com/questions/5892/gpl-and-distribution
