### ISSUE TITLE
pyvips  2x slower than PIL

### ISSUE THREAD

**Issue by AdrienF** [libvips/libvips#1413]
I don't know if this is a use case more favorable to PIL but with the following "simple" processing I report 2x slower performances using pyvips 2.1.8 with libvips 8.8.1 (API mode):
for a bunch of images (6292):
- load  image (160x58)
- convert to HSV
- scale some channels

Maybe I am not doing it properly using VIPS but I was surprised with the result.

Here is the following test code:

```python
def load_resize_convert_VIPS_file(filename):
    import numpy as np
    format_to_dtype = {
        'uchar':     np.uint8,
        'char':      np.int8,
        'ushort':    np.uint16,
        'short':     np.int16,
        'uint':      np.uint32,
        'int':       np.int32,
        'float':     np.float32,
        'double':    np.float64,
        'complex':   np.complex64,
    }

    image = pyvips.Image.new_from_file(filename, access='sequential')
    out = image\
        .resize(160 / image.width)\
        .sRGB2HSV()\
        .linear(1/255., 0., uchar=False)
    np_3d = np.ndarray(buffer=out.write_to_memory(),
                       dtype=format_to_dtype[out.format],
                       shape=[out.height, out.width, out.bands]).astype(np.float)
    np_3d[:,:,0] *= 360.

    return np_3d

def load_resize_convert_VIPS():
    import os
    path = "/media/Tom/Dev/Python/notebooks/outputs/7339/"
    with os.scandir(path) as it:
        for entry in it:
            if entry.name.endswith('.jpg') and entry.is_file():
                filename = path + entry.name
                np_3d = load_resize_convert_VIPS_file(filename)
                tmb_hsv = np_3d[:, :, 0], np_3d[:, :, 1], np_3d[:, :, 2]
    return tmb_hsv


def load_resize_convert_PIL():
    from PIL import Image
    from matplotlib.colors import rgb_to_hsv
    import numpy as np
    tmb_w = 160
    tmb_h = 58
    path = "/media/Tom/Dev/Python/notebooks/outputs/7339/"
    with os.scandir(path) as it:
        for entry in it:
            if entry.name.endswith('.jpg') and entry.is_file():
                filename = path + entry.name
                img = Image.open(filename)
                img = img.resize((tmb_w, tmb_h), Image.LANCZOS)
                arr_hsv = rgb_to_hsv(np.array(img) / 255.)
                arr_hsv[:, :, 0] *= 360.
                tmb_hsv = arr_hsv[:, :, 0], arr_hsv[:, :, 1], arr_hsv[:, :, 2]
    return tmb_hsv

if __name__ == '__main__':
    import os

    import timeit
    # Comparison between PIL loading and VIPS
    nrun = 1
    print("Mean processing time PIL : {:.8f} seconds".format(timeit.timeit("load_resize_convert_PIL()", setup="from __main__ import load_resize_convert_PIL", number=nrun) / nrun))
    print("Mean processing time VIPS : {:.8f} seconds".format(timeit.timeit("load_resize_convert_VIPS()", setup="from __main__ import load_resize_convert_VIPS", number=nrun) / nrun))
    # Mean processing time  PIL: 11.64372680  seconds
    # Mean processing time VIPS : 20.55690533 seconds
```

And some example images:
![2018-05-03_09-45-03](https://user-images.githubusercontent.com/4659733/63854763-2ab48480-c99e-11e9-8305-b6e45a6c657b.jpg)
![2018-05-03_10-00-02](https://user-images.githubusercontent.com/4659733/63854764-2ab48480-c99e-11e9-8d34-c303859887ad.jpg)
![2018-05-03_10-15-03](https://user-images.githubusercontent.com/4659733/63854765-2ab48480-c99e-11e9-9a90-9749d74e357f.jpg)

**Comment by jcupitt** [comment]
Hello @AdrienF,

You can make the vips one a bit simpler. 

* Instead of `x.sRGB2HSV()`, you can just do `.colourspace("HSV")`. libvips will pick a set of converters for you to get to HSV space.
* I wouldn't actually use HSV space unless you really have to. libvips supports the **much** better LCh space.
* pyvips has operator overloads, so instead of `x.linear()`, you can just write `x / 255`. It'll output a float image.
* You can use array constants to operate on specific channels, so `x * [1 / 255, 1 / 255, 360 / 255]` can replace the `*=360` as well (I think).

I'll try benchmarking it and see if there's anything else.

**Comment by jcupitt** [comment]
(Your example images are tiny, is that deliberate?)

**Comment by jcupitt** [comment]
You have the `import pyvips` inside the benchmark. Here's a version without `timeit` (which always annoys me):

```python
#!/usr/bin/python3   

import os
import time
import sys
import pyvips
from PIL import Image
from matplotlib.colors import rgb_to_hsv
import numpy as np

tmb_w = 160
tmb_h = 58

def load_resize_convert_pyvips(filenames):
    for filename in filenames:
        image = pyvips.Image.new_from_file(filename, access='sequential')
        out = image.resize(tmb_w / image.width).colourspace("hsv")
        out *= [1 / 255, 1 / 255, 360 / 255]
        np_3d = np.ndarray(buffer=out.write_to_memory(),
                           dtype=np.float32,
                           shape=[out.height, out.width, out.bands])
        tmb_hsv = np_3d[:, :, 0], np_3d[:, :, 1], np_3d[:, :, 2]
    
def load_resize_convert_PIL(filenames):
    for filename in filenames:
        img = Image.open(filename)
        img = img.resize((tmb_w, tmb_h), Image.LANCZOS)
        arr_hsv = rgb_to_hsv(np.array(img) / 255.) 
        arr_hsv[:, :, 0] *= 360.
        tmb_hsv = arr_hsv[:, :, 0], arr_hsv[:, :, 1], arr_hsv[:, :, 2]

if __name__ == '__main__':
    start = time.time()
    load_resize_convert_PIL(sys.argv[1:])
    print(f"PIL: {time.time() - start}s")
    
    start = time.time()
    load_resize_convert_pyvips(sys.argv[1:])
    print(f"pyvips: {time.time() - start}s")
```

I made 100 copies of a 4k x 3k jpg:

```
$ for i in {1..100}; do cp ../IMG_2603.jpg $i.jpg; done
$ vipsheader 1.jpg
1.jpg: 4032x3024 uchar, 3 bands, srgb, jpegload
```

Then running it, I see:

```
$ ./hsv2.py ~/pics/sample/*.jpg
PIL: 21.48312282562256s
pyvips: 11.922781944274902s
```

**Comment by jcupitt** [comment]
I meant to say, if you've not come across LCh, wiki has some background:

https://en.wikipedia.org/wiki/CIELAB_color_space#Cylindrical_representation:_CIELCh_or_CIEHLC

It's CIELAB, but with polar coordinates instead of ab. This means that distances in L and C are roughly perceptually uniform, something that's absolutely not true for HSV. Coordinates have a much clearer intuitive meaning too, and it's much easier to write equations to transform LCh images to achieve a specific effect.

libvips only has an HSV mode for compatibility with other software. Use LCh instead if you possibly can.

The `*=360` you are doing sounds like you are trying to make a degrees channel, is that right? That's what the h in LCh is, except it's much better :)

**Comment by AdrienF** [comment]
Hello John,

Thank you for your time, your code, and suggestions.

Running your code on my dataset of tiny images (6292 jpegs of size 160x58,
it is on purpose) I still got:
$ python script.py  tinyDataset/*.jpg
PIL: 11.49741244316101s
pyvips: 22.48672604560852s

When trying on larger images (147 of them):
$ python script.py  classicDataset/*.jpg
PIL: 10.541918992996216s
pyvips: 7.183633089065552s
$ vipsheader classicDataset/1.jpg
1.jpg: 4260x1534 uchar, 3 bands, srgb, jpegload

It seems VIPS gets better with larger image dimensions. I did not noticed
any timing differences between LCh and HSV conversion time. But thank you
for pointing to that colour space.

I work on "large" series of tiny images as I have interest in timelapse
processing and have access to these tiny and fast to download images to
analyze them. VIPS already gave better performances than ImageMagick in
other parts of the workflow when cropping large images.

I'll follow with interest any advances in VIPS.

Best regards,

Adrien Fontvielle


Le jeu. 29 août 2019 à 14:01, John Cupitt <notifications@github.com> a
écrit :

**Comment by jcupitt** [comment]
Ah, OK, yes, libvips has quite a large startup and shutdown time as it builds threadpools and creates pipelines. For small images, this will probably dominate processing.
