### ISSUE TITLE
Libvips 8.8.1 build failure against GraphicsMagick 1.3.28

### ISSUE THREAD

**Issue by GvMariani** [libvips/libvips#1415]
Trying to build libvips 8.8.1 from sources for Rosa 2016.1 Fresh (a Mandriva derivative) on x86_64, using GraphicsMagick 1.3.28 (by passing --with-magickpackage=GraphicsMagick to configure).

The build fails at the .libs/magick.o stage with a few "undeclared" errors:
************************
magick.c:413:4: error: 'CMYColorspace' undeclared here (not in a function)
  { CMYColorspace, "CMYColorspace" },
    ^
magick.c:416:4: error: 'HCLColorspace' undeclared here (not in a function)
  { HCLColorspace, "HCLColorspace" },
    ^
magick.c:417:4: error: 'HCLpColorspace' undeclared here (not in a function)
  { HCLpColorspace, "HCLpColorspace" },
    ^
magick.c:418:4: error: 'HSBColorspace' undeclared here (not in a function)
  { HSBColorspace, "HSBColorspace" },
    ^
magick.c:419:4: error: 'HSIColorspace' undeclared here (not in a function)
  { HSIColorspace, "HSIColorspace" },
    ^
magick.c:421:4: error: 'HSVColorspace' undeclared here (not in a function)
  { HSVColorspace, "HSVColorspace" },
    ^
magick.c:423:4: error: 'LabColorspace' undeclared here (not in a function)
  { LabColorspace, "LabColorspace" },
    ^
magick.c:424:4: error: 'LCHColorspace' undeclared here (not in a function)
  { LCHColorspace, "LCHColorspace" },
    ^
magick.c:425:4: error: 'LCHabColorspace' undeclared here (not in a function)
  { LCHabColorspace, "LCHabColorspace" },
    ^
magick.c:426:4: error: 'LCHuvColorspace' undeclared here (not in a function)
  { LCHuvColorspace, "LCHuvColorspace" },
    ^
magick.c:427:4: error: 'LogColorspace' undeclared here (not in a function)
  { LogColorspace, "LogColorspace" },
    ^
magick.c:428:4: error: 'LMSColorspace' undeclared here (not in a function)
  { LMSColorspace, "LMSColorspace" },
    ^
magick.c:429:4: error: 'LuvColorspace' undeclared here (not in a function)
  { LuvColorspace, "LuvColorspace" },
    ^
magick.c:434:4: error: 'scRGBColorspace' undeclared here (not in a function)
  { scRGBColorspace, "scRGBColorspace" },
    ^
magick.c:437:4: error: 'xyYColorspace' undeclared here (not in a function)
  { xyYColorspace, "xyYColorspace" },
    ^
magick.c:441:4: error: 'YDbDrColorspace' undeclared here (not in a function)
  { YDbDrColorspace, "YDbDrColorspace" },
***********************
... and one error about an argument number mismatch for the function GetImageMagick:
**********************
magick.c:660:3: error: too many arguments to function 'GetImageMagick'
   GetImageMagick( bytes, length, format ) );
*********************

The latter error perhaps is an useful hint about the origin of this issue: compatibility with recent (? Jan 2018???) GraphicsMagick sources...
Attaching the full log of a failed build.
[BuildFailed.txt](https://github.com/libvips/libvips/files/3552569/BuildFailed.txt)

**Comment by jcupitt** [comment]
Hello @GvMariani,

Thanks for reporting this. It was actually fixed a few weeks ago: https://github.com/libvips/libvips/commit/f36927e78dfa81e675cd27b2339d3bfee635e18f#diff-3720ed16345d4dc82cbe06aaf6b7e93e

Hopefully 8.8.2 will be out soon with this improvement. 

As a workaround, you could try building 8.8 HEAD.

**Comment by GvMariani** [comment]
I can also add that doing a build of the vips release previously provided by Rosa distro (8.5.8), on the same system and with the same graphicsmagick, works flawlessly...

**Comment by GvMariani** [comment]
> Thanks for reporting this. It was actually fixed a few weeks ago: [f36927e#diff-3720ed16345d4dc82cbe06aaf6b7e93e](https://github.com/libvips/libvips/commit/f36927e78dfa81e675cd27b2339d3bfee635e18f#diff-3720ed16345d4dc82cbe06aaf6b7e93e)
> Hopefully 8.8.2 will be out soon with this improvement.
I will wait for 8.8.2, thanks...
This issue can be closed now or do you prefer waiting for the 8.8.2 tagging?

**Comment by jcupitt** [comment]
8.8.2 is out now.
