### ISSUE TITLE
DNG files are loading the embedded JPEG thumbnail

### ISSUE THREAD

**Issue by ItalyPaleAle** [libvips/libvips#1416]
I am using vips 8.8.1 (with the govips bindings), and noticed that when I load a DNG file, it is loaded correctly, but the library is actually reading the embedded JPEG thumbnail rather than the image itself.

DNG files are essentially TIFF ones, so I would expect vips to load the RAW TIFF image instead.

**Comment by jcupitt** [comment]
Hello @ItalyPaleAle,

DNG files are complicated. They look like JPG files (this is why libvips is loading them as a jpg), but contain a "secret" non-standard TIFF with the camera RAW data. You can't load pixels directly: you have to use a RAW processor to reconstruct the image.

You could try forcing it to load via ImageMagick with (in Python):

```python
x = pyvips.Image.magickload("somefile.DNG")
```

I think ImageMagick will shell out to `dcraw` to render the image. You won't get much control over the process though -- you'll get better results if you use a proper RAW processor.

**Comment by jcupitt** [comment]
(that's from memory, I hope I have the details right)

**Comment by ItalyPaleAle** [comment]
Thanks @jcupitt for the quick response!

Yes I'm aware of the limitations of developing RAW files with dcraw/libraw/ImageMagick and agree that the colors are off. For this use case, I'm ok with the sub-par results.

However, in my experience DNG files appear as TIFF files, and in fact cannot be distinguished from TIFF files without parsing the metadata. This is what `file` shows for a DNG (generated by Lightroom):

````sh
$ file IMG_0651.DNG
IMG_0651.DNG: TIFF image data, little-endian, direntries=60, height=171, bps=746, compression=none, PhotometricIntepretation=RGB, manufacturer=Canon, model=Canon EOS M3, orientation=upper-left, width=256
````

Not sure what loader is being used by libvips - what's the way for me to check that?

**Comment by jcupitt** [comment]
Oh huh I misremembered -- DNGs are TIFFs which turn into JPG-compressed thumbnails if you follow the spec, but which have extra proprietary fields containing the raw camera data.

```
$ vipsheader 1.dng 
(vipsheader:5471): VIPS-WARNING **: 22:42:03.854: Unknown field with tag 37393 (0x9211) encountered
[a LOT of warning messages]
1.dng: 256x256 uchar, 3 bands, srgb, tiffload
```

So I see a 256 x 256 thumbnail with `tiffload`. If I force the magick loader:

```
$ vips magickload 1.dng x.v
$ vipsheader x.v
x.v: 2880x4308 ushort, 3 bands, rgb16, magickload
```

I see a large 16-bit image (and it takes a long time).
