### ISSUE TITLE
Wrong width and height for photos

### ISSUE THREAD

**Issue by lzjluzijie** [libvips/libvips#1420]
I am try to use libvips([bimg](https://github.com/h2non/bimg)) to resize photos. Basically it works fine, but some vertical photos taken with my RX100M6 has wrong width in libvips, which is actually the height of the photo, and the height of the photo is actually the width.

DSC03254.JPG:https://t.halu.lu/t/529

But all vertical photos taken with my mobile phone are OK.

IMG_20190118_142418.jpg:https://t.halu.lu/t/530

(These photos are too big for github, so I upload to my own server.)

```bash
[halulu@halulu-pc Desktop]$ vipsheader -f width IMG_20190118_142418.jpg
3000
[halulu@halulu-pc Desktop]$ vipsheader -f height IMG_20190118_142418.jpg
4000
[halulu@halulu-pc Desktop]$ vipsheader -f width DSC03254.JPG
5472
[halulu@halulu-pc Desktop]$ vipsheader -f height DSC03254.JPG
3648
```

I think it might be something related to rotation, but I have no idea how to figure out.

**Comment by jcupitt** [comment]
Hello @lzjluzijie,

It's the `orientation` tag. Your camera and phone have a sensor so they know which way the camera was held when the photo was taken. 

`vipsthumbnail` uses the tag to spin the image upright automatically, but `vipsheader` reports the width and height of the unrotated image (the image as it really appears in the file).

```
$ vipsheader -f width DSC03254.JPG 
5472
$ vipsheader -f orientation DSC03254.JPG 
6
```

6 means the camera was held sideways (the bottom of the camera pointing right).

You can see the "real" photo like this:

```
$ vips resize DSC03254.JPG x.jpg[strip] 0.1
```

`strip` will remove all metadata to prevent web browsers rotating the image:

![x](https://user-images.githubusercontent.com/580843/64237245-dfe1c200-cef3-11e9-9cfe-9d328667923c.jpg)

**Comment by lzjluzijie** [comment]
Thank you very much
