### ISSUE TITLE
tiffsave xres/yres arguments don't match docstring

### ISSUE THREAD

**Issue by f--f** [libvips/libvips#1421]
I noticed that the docstring for `tiffsave` describes the optional `xres` and `yres` arguments like this:

    xres (float): Horizontal resolution in pixels/mm
    yres (float): Vertical resolution in pixels/mm

But running

`pyvips.Image.grey(100, 100).tiffsave("grey.tif", xres=100, yres=100)`

and then checking the result with tiffinfo outputs `Resolution: 100, 100 pixels/cm` (xres and yres in pixels/cm, and not pixels/mm - this is the case even if resunit is specified as inches).

I suspect the confusion is that libvips stores xres/yres metadata in pixels/mm, which *does* get converted properly if it is specified in `tiffsave`.

The relevant section of existing code for handling resolution units seems to be here: https://github.com/libvips/libvips/blob/2da56b918d2301398d5ab3034e71aabd5f45a308/libvips/foreign/tiffsave.c#L145-L165

(Using vips 8.8.0)

**Comment by jcupitt** [comment]
Ooop, you're right, it's all messed up. I'll have a look. Thanks!

**Comment by jcupitt** [comment]
I think it's working now. There was a *10 missing from one side of an if :-( Thanks again for reporting this, it'll be in 8.8.2.

```

**Comment by f--f** [comment]
:grin: Looks good, thanks!

**Comment by jcupitt** [comment]
I added some tests too:

https://github.com/libvips/libvips/commit/f80c7a181039517d005241444ccef43e87923e3c
