### ISSUE TITLE
Extend text watermark example: how to make vips_replicate optional

### ISSUE THREAD

**Issue by comfortablynick** [libvips/libvips#1427]
I'm working on a C version (in addition to Python) of a program which uses vips to resize and watermark. I'm basing it on your example [here](https://gist.github.com/jcupitt/039ecdc172712cbb8969).

The example works so far. My current task is trying to make `vips_replicate` optional, based on a switch. I attempted to use a variable for the array index, but it gives a bad embed area error if `replicate = 1`. Is this easy to do, or do I have to maintain two separate functions?

Thanks for the help. Vips is very powerful but a little difficult for me to grasp the API.
```c
static int
label_image(VipsObject *base, VipsImage *in, VipsImage **out, const char *message)
{
    VipsImage **t = (VipsImage **)vips_object_local_array(base, 10);
    static double background[3] = {255, 255, 255};
    static double ones[3] = {1, 1, 1};
    int i = 0;
    int replicate = 0;

    // Make the mask
    if (vips_text(&t[i + 0], message, "dpi", 300, NULL) ||
        vips_linear1(t[i + 0], &t[i + 1], 0.7, 0.0, NULL) ||
        vips_cast(t[i + 1], &t[i + 2], VIPS_FORMAT_UCHAR, NULL) ||
        vips_embed(t[i + 2], &t[i + 3], 25, 25, t[i + 2]->Xsize + 200, t[i + 2]->Ysize + 200,
                   NULL)) {
        g_object_unref(base);
        vips_error_exit(NULL);
    }
    // TODO: why doesn't this work?
    if (replicate) {
        if (vips_replicate(t[i + 3], &t[i + 4], 1 + in->Xsize / t[i + 3]->Xsize,
                           1 + in->Ysize / t[i + 3]->Ysize, NULL) ||
            vips_crop(t[i + 3], &t[i + 4], 0, 0, in->Xsize, in->Ysize, NULL)) {
            g_object_unref(base);
            vips_error_exit(NULL);
        }
        ++i;
    }

    // Make the constant image to paint the text with.
    if (vips_black(&t[i + 4], 1, 1, NULL) ||
        vips_linear(t[i + 4], &t[i + 5], ones, background, 3, NULL) ||
        vips_cast(t[i + 5], &t[i + 6], VIPS_FORMAT_UCHAR, NULL) ||
        vips_copy(t[i + 6], &t[i + 7], "interpretation", in->Type, NULL) ||
        vips_embed(t[i + 7], &t[i + 8], 0, 0, in->Xsize, in->Ysize, "extend", VIPS_EXTEND_COPY,
                   NULL)) {
        g_object_unref(base);
        vips_error_exit(NULL);
    }

    // Blend the mask and text and write to output.
    if (vips_ifthenelse(t[i + 3], t[i + 8], in, out, "blend", TRUE, NULL)) return (-1);
    return (0);
}
```

**Comment by jcupitt** [comment]
I usually write stuff like this with an extra placeholder pointer. For example:

https://github.com/libvips/libvips/blob/master/libvips/resample/thumbnail.c#L570

So each section in the pipeline reads from the `in` image and uses one of the `t[]` slots. When it finishes, it updates `in` to point to the new end of the pipeline. 

As long as you don't accidentally reuse one of the `t[]` numbers, it's all safe, and you don't need to keep track of which `t[]` has the current end in. And you can add or remove stages without having to renumber everything.

**Comment by comfortablynick** [comment]
Thanks that helps. Not sure why I didn't think of that! 

Of course, it looks like you still have to keep track of the last `t[]` number you used.

**Comment by jcupitt** [comment]
Yes, it's a bit ugly. 

The C++ interface keeps tracks of all the refs and unrefs for you, of course, it's nicer to use.

I wouldn't unref `base` in that function. Usually you want to keep the unref in the same function as the matching ref (or I guess new in this case), or it just gets too confusing. You're missing one unref near the end, for example.

**Comment by comfortablynick** [comment]
Thanks, I think that was a copy/paste mistake. I should be unreffing `t` in the function, right?

**Comment by jcupitt** [comment]
Don't do any unrefs in the function -- unref `base` in the thing that created it when you're done.

Here's how vipsthumbnail does it (it calls it `process`, ie. the thing that tracks object lifetime for each processing cycle):

https://github.com/libvips/libvips/blob/master/tools/vipsthumbnail.c#L469

So there's a single ref and a single unref in the whole program and (hopefully) mistakes are impossible.

**Comment by comfortablynick** [comment]
Oh I see. That's the benefit of using `VipsObject` I suppose. It does seem easier after I saw that trick in your example.

Thanks again!
