### ISSUE TITLE
issue autogen.sh

### ISSUE THREAD

**Issue by michelrw99** [libvips/libvips#1432]
When run's autogen.sh;

./configure: line 25885: syntax error near unexpected token `fi'
./configure: line 25885: `fi'

**Comment by lovell** [comment]
It looks like you're trying to build from git. Did you see https://github.com/libvips/libvips#building-libvips-from-git ?

Please can you provide more information about the OS version you're using. Please can you provide the full output of running `autogen.sh`.

**Comment by michelrw99** [comment]
Hi, i've tried to:

wget https://github.com/libvips/libvips/releases/download/v8.8.1/vips-8.8.1.tar.gz
untar
and run autogen.sh

in CloudLinux Server release 6.10

[autogen-log.txt](https://github.com/libvips/libvips/files/3632861/autogen-log.txt)

**Comment by lovell** [comment]
If you're using the release tarballs then you shouldn't need to use `autogen.sh` as they already contain `./configure` for you to run directly.

https://github.com/libvips/libvips#building-libvips-from-a-source-tarball

**Comment by michelrw99** [comment]
Thanks for your patience, but ./configure reproduces the same error.
Attached:
[libvips-logs2.txt](https://github.com/libvips/libvips/files/3632925/libvips-logs2.txt)

**Comment by jcupitt** [comment]
When you run `autogen.sh`, it deletes `configure` and tries to regenerate it. Because you are missing a few system files (I think), your new `configure` won't work.

You need to delete your vips area and untar a fresh one. It should contain a working `configure`.

There's 8.8.3 out now, you probably saw.

**Comment by kayarre** [comment]
is there a way to generate a "release like" so that one can build from git without the extra dependency requirements of autogen.sh?

**Comment by jcupitt** [comment]
Hi, yes, do `make dist`. It'll build `vips-x.y.x.tar.gz`, a tarball with a configure baked into it.

**Comment by kayarre** [comment]
> Hi, yes, do `make dist`. It'll build `vips-x.y.z.tar.gz`, a tarball with a configure baked into it.

This does not appear to work for me. 
```
s$ make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/krs/build/vips/libvips'
make[1]: *** No rule to make target 'libvips.supp', needed by 'distdir'.  Stop.
make[1]: Leaving directory '/home/krs/build/vips/libvips'
Makefile:825: recipe for target 'dist' failed
make: *** [dist] Error 2
```

**Comment by jcupitt** [comment]
Is this git master libvips? That's in heavy development. I'd stick to the 8.8 branch, which ought to be stable.

**Comment by jcupitt** [comment]
I fixed "make dist" in master.
