### ISSUE TITLE
libVips Thumbnail C++

### ISSUE THREAD

**Issue by thenotoriousdev** [libvips/libvips#1436]
This is more of a question than issue, is there some example usage of vips thumbnail in c++? I am trying to compress the tiff image which is loaded as VImage.

**Comment by jcupitt** [comment]
Hello @thenotoriousdev 

Here's an example of thumbnailing a file in memory. It's more complex than you might think since it has to ensure memory is not released until libvips is done with it:

```c++
/* compile with
 *      g++ -g -Wall jaume2.cpp `pkg-config vips-cpp --libs --cflags`
 */

#include <iostream>
#include <pthread.h>
#include <vector>
#include <fstream>
#include <chrono>

#include <vips/vips8>

using namespace vips;
using namespace std;

int main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        vips_info_set( TRUE );

        size_t length;
        char *buffer;
        if( !(buffer = vips__file_read_name(argv[1], NULL, &length)) )
                vips_error_exit( NULL );
        VipsBlob *blob;
        blob = vips_blob_new( (VipsCallbackFn) vips_free, buffer, length );

        VImage out = VImage::thumbnail_buffer( blob, 6000 );

        printf( "out.width = %d\n", out.width());
        printf( "out.height = %d\n", out.height());

        vips_area_unref( (VipsArea *) blob );

        blob = out.jpegsave_buffer( VImage::option()->
                set("strip", 1) ->
                set("Q", 80) ->
                set("optimize_coding", TRUE)->
                set("interlace", TRUE) );

        return 0;
}
```

**Comment by jcupitt** [comment]
Thumbnailing a file on disc is very simple. You can pass args to thumbnail as above.

```c++
/* compile with
 *      g++ -g -Wall jaume3.cpp `pkg-config vips-cpp --libs --cflags`
 */

#include <vips/vips8>

int 
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        vips::VImage out = vips::VImage::thumbnail( argv[1], 300, NULL );
        out.write_to_file( argv[2], NULL );

        return 0;
}
```

**Comment by thenotoriousdev** [comment]
I am getting the following error when I am trying to load the data from the buffer - 
```
error: ‘thumbnail_buffer’ is not a member of ‘vips::VImage’
         vips::VImage thumbnailImg = vips::VImage::thumbnail_buffer(saveData.dataPtr,300);
```
I have initialized vips in my code. `saveData.dataPtr` is a `void *` to the data that is loaded using the `new_from_memory`. Is there something wrong in my understanding of the usage?

**Comment by thenotoriousdev** [comment]
I have the libvips-dev version, is there a way to check the concrete version of vips I am running, something like `--version` or `vips.__version__`?

**Comment by jcupitt** [comment]
Ah OK, I guess this is an older Debian? I would install your own libvips from source.

https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by jcupitt** [comment]
You'll need to set your `PATH` and `PKG_CONFIG_PATH` to point to `/usr/local`, and possibly `LD_CONFIG_PATH`, depending on your system.

**Comment by thenotoriousdev** [comment]
Oh Okay! That makes sense, is there any particular reason why the libvips-dev is still headed at v (8.2.2-1), is that the current stable version or something? I will try the above installation method and get back to you as I am done. Thanks.

**Comment by jcupitt** [comment]
It's just the libvips that your OS is set up for. If you're using an Ubuntu from five years ago, for example, the system libvips will be five years old.

Current stable is 8.8.3.

**Comment by thenotoriousdev** [comment]
Ah! That makes sense. Thanks. I am in the process of installation, will keep you posted.

**Comment by thenotoriousdev** [comment]
Cool the issue seems resolved with the new version install.
