### ISSUE TITLE
GlobalBalance errors with "unable to open: temp-XX" 

### ISSUE THREAD

**Issue by imagolive** [libvips/libvips#1437]
Some images are stitched together using this hack:

```
ImagePoint origA = new ImagePoint { x = 560, y = 374 }, refA = new ImagePoint { x = 560, y = 374 }, refB = new ImagePoint { x = 346, y = 381 };

List<Image> images = new List<Image>();
for (int i = 0; i < imputFileNames.Count; i++)
{
    Image image = Image.NewFromFile(imputFileNames[i]);
    if (image.Width > image.Height)
        image = image.Autorot();
    images.Add(image.Resize(0.1));
}

int dx0, dy0;
double scale1, rot1, dx1, dy1;
Image ongoingImage = null;
for (int i = 0; i < imputFileNames.Count; i++)
{
    if (i > 0)
    {
        ongoingImage = ongoingImage.Mosaic(images[i], "horizontal", (int)refA.x, (int)refA.y, (int)refB.x, (int)refB.y, out dx0, out dy0, out scale1, out rot1, out dx1, out dy1, hwindow: 10, harea: 25);
        refA.x = origA.x - dx0;
        refA.y = origA.y - dy0;
    }
    else
    {
        ongoingImage = images[0];
    }
}
ongoingImage = ongoingImage.Globalbalance();
ongoingImage.WriteToFile(outputFileName);
return outputFileName;
```

It stitches them ok but fails on the globalbalance step with:

![image](https://user-images.githubusercontent.com/23182810/66013861-6b547000-e4ff-11e9-9057-3929e0ab4bb7.png)

It is uses the NetVips wrapper but, looking at the code, the error seems to be coming up from libvips itself.

Any ideas why the above might cause a problem?

Thanks

**Comment by jcupitt** [comment]
Hello @imagolive,

Sorry, `globalbalance` doesn't work like that :(

Here's how it works:

1. When you join a pair of images with one of the pairwise join operations (mosaic, mosiac1, merge, etc.), the join operation is recorded in the image history. It's a one-line string in a special syntax, something like `join leftright a.png b.png result1 234 3456 23234  2324 123 2`. This gives the two input files, the output filename, and the parameters of the join.
2. When you run `globalbalance`, it reads the image history and builds a tree of join operations. Each leaf is a source file (eg. `a.png` above) plus the position, rotation etc. of that leaf in the final image.
3. It calculates all of the overlaps, reopens all of the original source files, extracts the overlaps, and finds the average pixel value in each overlap region in each image.
4. All of the overlaps go into a big solver to pick a scale factor for each leaf which will minimise overlap difference.
5. It reopens the original images again, scales each one, and reassembles the mosaic.

So what this means:

1. You must have all your original files on disc still, under their original names.
2. You can open the files, copy them and join them using the mosaic functions, then balance them.
3. You can't do any other operations. If you add / resize /  etc., `globalbalance` will no longer be able to work.

I suggest you make two passes over your images. First, do any resize, brightness, rotation etc. you need and make a new set of tiles, then in a second pass, assemble the processed tiles into a mosaic and balance it.
