### ISSUE TITLE
Netvips Crop image issue with non rectangular image

### ISSUE THREAD

**Issue by Jey1980** [libvips/libvips#1438]
I am using Netvips to clip image and based on four corner points, but image cannot be cropped using just by using top points, because top width and bottom width are not same.

Sample image - http://i.stack.imgur.com/x21me.png

**Comment by jcupitt** [comment]
I would crop to the bounding box of your four points, then draw a non-rectangular mask for the exact shape you want. You can put the mask in an alpha channel, or use it to cut away pixels you don't want.

SVG is probably the simplest way to draw the mask shape.

**Comment by Jey1980** [comment]
How can Netvips is used to Crop a tiff image, it doesn't accept four corner points??.   As per your opinion if I crop the image at first place, damage is already done, after that apply mask on the cropped image will not work. Is the any way to provide 4 corner points?

Also let me know how to put mask, when I check there are lot function has masking, I am not sure which one to apply

**Comment by jcupitt** [comment]
I made you a tiny cropper in Python (I don't have C# installed):

```python
#!/usr/bin/python3

import sys
import pyvips

def crop_poly(image, *points):
    # crop to bounding box
    x, y = zip(*points)
    left = min(x)
    top = min(y)
    crop = image.crop(left, top, max(x) - left, max(y) - top)

    # make alpha channel ... svgload makes a 4-band image, we want
    # the alpha from that
    svg = f"""
        <svg viewBox="0 0 {crop.width} {crop.height}">
            <polygon style="fill: white; stroke: none" points="
    """
    svg += " ".join([f"{x - left}, {y - top} " for x, y in points])
    svg += """
            "/>
        </svg>
    """
    alpha = pyvips.Image.svgload_buffer(bytes(svg, "ascii"))[3]
    
    return crop.bandjoin(alpha)

image = pyvips.Image.new_from_file(sys.argv[1])
image = crop_poly(image, 
                  [100, 100],
                  [image.width, 100],
                  [image.width / 2, image.height - 100])
image.write_to_file(sys.argv[2])
```

It can crop to any polygon, though here it is cropping to an inverted triangle. Run with:

```
$ ./try301.py ~/pics/Gugg_coloured.jpg x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/66203654-ca051f80-e6a0-11e9-9fcb-2ed753144b8d.png)

**Comment by Jey1980** [comment]
Thanks J, for your quick turaround, I will give a try...

**Comment by Jey1980** [comment]
@jcupitt 

        Can you post me the svg python output, so that I can try the same in C#. I understand that from the code that you are creating four corner using the 4 points and then pass on to the svgloadbuffer.

Thanks
JK

**Comment by jcupitt** [comment]
`points` should be something like `10,10 20,10 15,20`, ie. use spaces to separate coordinate pairs. You also need double quotes around all arguments.

```svg
<svg viewBox="0 0 191 1417">
  <polygon style="fill: white; stroke: none;" points="168,0 168,0 168,1417 168,1411"/>
</svg>
```

**Comment by Jey1980** [comment]
@jcupitt ,

I have attached Original image, clipping points and after clipped image as well.
        I have tried as you mentioned it worked, when I check the cropped image and alpha image. both image are with same size and same portion clipped.. I am sure I am missing something.
[Org.zip](https://github.com/libvips/libvips/files/3706641/Org.zip)

**Comment by jcupitt** [comment]
Hello, your `Org.tif` already has an alpha channel. You need to drop that before adding a new one.

In python:

```python
image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
if image.hasalpha():
    image = image[0:3]
image = crop_poly(image, 
                  [198, 195],
                  [359, 195],
                  [337, 1610],
                  [168, 1605])
image.write_to_file(sys.argv[2]) 
```

To make:

![x](https://user-images.githubusercontent.com/580843/66474461-445ee680-ea89-11e9-889d-540de2071c3c.png)

**Comment by jcupitt** [comment]
Sorry! I hadn't realized it was confidential.

**Comment by Jey1980** [comment]
Sorry to continue with previous issue, In continuation to the above problem, I need to identify the titled image and rotate it, Previously I have used TopRight and TopLeft , height and width to identify the titled image and rotate it back after clipping

            //// the new position of the rectangle in the rotated image
            double radians = (Math.PI * angle) / 180.0;
            double c = Math.Cos(radians);
            double s = Math.Sin(radians);
            int intXOffset = source.Xoffset;
            int intYOffSet = source.Yoffset;


            int left = Convert.ToInt32(topLeftX * c - topLeftY * s);
            int top = Convert.ToInt32(topLeftX * s + topLeftY * c);
            int width = Convert.ToInt32(Math.Sqrt(Math.Pow(topRightX - topLeftX, 2) +
                                                  Math.Pow(topRightY - topLeftY, 2)));
            int height = Convert.ToInt32(Math.Sqrt(Math.Pow(topRightX - bottomRightX, 2) +
                                                   Math.Pow(topRightY - bottomRightY, 2)));
 // after a rotate, the new position of the origin is given by .Xoffset, .Yoffset
            NetVips.Image tile = source.Crop(left + source.Xoffset, top + source.Yoffset, width, height);

Now I am not sure which one consider now, as now we use all the four corners considered for clipping.

**Comment by jcupitt** [comment]
Hi, transform the four corners, then take the bounding box of the four transformed points (if I understand your question).

**Comment by Jey1980** [comment]
Sorry for being late in asking it again. 

Do you mean transform top-left,top-right, bottom-right and bottom-left using something like below

  int left = Convert.ToInt32(topLeftX * c - topLeftY * s);
        int top = Convert.ToInt32(topLeftX * s + topLeftY * c);

**Comment by jcupitt** [comment]
Write a function to transform a point, pass your four corners through the function, then find the min and max of x and y to get the bounding box of the transformed square. If I understand what you want!

If I'm confused, post a small, complete program and I'll have a look again.

**Comment by Jey1980** [comment]
Hi,

Please find the below code for clipping and masking using 4 points. In below code I am not using rotate functionality.


        public NetVips.Image ImageRotateAndClip_Rotate(string ImageFilePath, System.Windows.Point imgTopLeft,
            System.Windows.Point imgTopRight, System.Windows.Point imgBottomLeft, System.Windows.Point imgBottomRight)
        {
            //string eventname = "ImageRotateAndClip";


            //Image source = Image.FromFile(ImageFilePath);

            NetVips.Image source = NetVips.Image.Tiffload(ImageFilePath, access: Enums.Access.Random);


            //// the angle the top edge is rotated by
            double dx = imgTopRight.X - imgTopLeft.X;
            double dy = imgTopRight.Y - imgTopLeft.Y;
            double angle = (180 / Math.PI) * Math.Atan2(dx, dy);
            if (angle < -45 || angle >= 45)
            {
                angle = 90 - angle;
            }

            //// therefore the angle to rotate by to get it straight
            angle = -angle;

            source = source.Rotate(angle);


            double topLeftX = imgTopLeft.X;
            double topLeftY = imgTopLeft.Y;
            double topRightX = imgTopRight.X;
            double topRightY = imgTopRight.Y;
            double bottomRightX = imgBottomRight.X;
            double bottomRightY = imgBottomRight.Y;
            double bottomLeftX = imgBottomLeft.X;
            double bottomLeftY = imgBottomLeft.Y;




            //// the new position of the rectangle in the rotated image
            double radians = (Math.PI * angle) / 180.0;
            double c = Math.Cos(radians);
            double s = Math.Sin(radians);
            int intXOffset = source.Xoffset;
            int intYOffSet = source.Yoffset;


            int left = Convert.ToInt32(topLeftX * c - topLeftY * s);
            int top = Convert.ToInt32(topLeftX * s + topLeftY * c);
            int width = Convert.ToInt32(Math.Sqrt(Math.Pow(topRightX - topLeftX, 2) +
                                                  Math.Pow(topRightY - topLeftY, 2)));
            int height = Convert.ToInt32(Math.Sqrt(Math.Pow(topRightX - bottomRightX, 2) +
                                                   Math.Pow(topRightY - bottomRightY, 2)));

            // after a rotate, the new position of the origin is given by .Xoffset, .Yoffset
            //NetVips.Image tile = source.Crop(left + source.Xoffset, top + source.Yoffset, width, height);


            double[] xArray = { topLeftX, topRightX, bottomRightX, bottomLeftX };
            double[] yArray = { topLeftY, topRightY, bottomRightY, bottomLeftY };

            Int32 minX = Convert.ToInt32(xArray.Min());
            Int32 maxX = Convert.ToInt32(xArray.Max());
            Int32 minY = Convert.ToInt32(yArray.Min());
            Int32 maxY = Convert.ToInt32(yArray.Max());


            if (source.HasAlpha())
            {
                source = source.ExtractBand(0, 3);
            }

            //Crop the maximum in case of the image is non rectangular shape
            NetVips.Image tile = source.Crop(minX + source.Xoffset, minY + source.Yoffset, (maxX - minX), (maxY - minY));

            //After cropping , Mask the image based on the the non regtangular width using svg
            string svg = "<svg viewBox=\"0 0 " + tile.Width + " " + tile.Height + "\">";
            svg += "<polygon style=\"fill: white; stroke: none \" points=\"";

            svg += (imgTopLeft.X - minX).ToString() + "," + (imgTopLeft.Y - minY).ToString() + " ";
            svg += (imgTopRight.X - minX).ToString() + "," + (imgTopRight.Y - minY).ToString() + " ";
            svg += (imgBottomRight.X - minX).ToString() + "," + (imgBottomRight.Y - minY).ToString() + " ";
            svg += (imgBottomLeft.X - minX).ToString() + "," + (imgBottomLeft.Y - minY).ToString() + "\"";
            svg += "/></svg>";
            var bytes1 = Encoding.UTF8.GetBytes(svg);
            NetVips.Image alphaimage = null;

            //Get the alpha image for mask
            try
            {

                alphaimage = NetVips.Image.SvgloadBuffer(bytes1)[3];
            }
            catch (Exception)
            { }

            //Join the alpha image band with cropped image to get the non rectangular clipped portaion
            NetVips.Image tile2 = tile.Bandjoin(alphaimage);

            GC.SuppressFinalize(tile2);
            GC.SuppressFinalize(alphaimage);
            GC.SuppressFinalize(tile);

            return tile2;
        }
