### ISSUE TITLE
define latitude and longitude of top left and bottom right corners

### ISSUE THREAD

**Issue by tandu** [libvips/libvips#1440]
Is it possible to define latitude and longitude for the image so that first tile starts not from 0_0 indexes but from something like 2343_433. And also tiles are having correct offset so that image fits into defined geo coordinates bounds on the background map. For clarity - I'm using leaflet map and going to use libvips dzsave instead of gdal2tiles because of its performance but I haven't found any information about how to properly define geo coordinates bounds for the image to build pyramid. In case bounds are defined I believe levels range should be calculated automatically.

**Comment by jcupitt** [comment]
Hello @tandu, sorry for not responding sooner.

No, dzsave does not support this. It's designed for simple image files and doesn't know anything about mapping or lat/long coordinates.

Could you achieve what you want by just renaming the files after running dzsave? A small Python or whatever script should be able to do this pretty quickly.
