### ISSUE TITLE
Is my implementation of resize + composite optimal?

### ISSUE THREAD

**Issue by juona** [libvips/libvips#1441]
Hello,

My application uses pyvips for a common simple task - load a few images, resize them, crop them and stack them on top of each other on a transparent background of a specified size. The code that I wrote is straightforward, essentially (the numbers here are somewhat random):

```python
import pyvips
import logging
import time

layers = [
  {
    "file": "./design-1",
    "scale": 3.914214463840399,
    "x": -3159,
    "y": -4182
  },
  {
    "file": "./design-2",
    "scale": 3.54375,
    "x": 1012,
    "y": 2347
  },
  {
    "file": "./design-3",
    "scale": 1.2209476309226932,
    "x": 3597,
    "y": 940
  }
];

slot_file_width = 7200
slot_file_height = 7200
output_file = "output-no-crop.tiff"

for i in range (0, 10):
  for layer in layers:
    layer["image"] = pyvips.Image.new_from_file(layer["file"], access = "sequential")

    if (layer["image"].bands == 3):
      layer["image"] = layer["image"].bandjoin(255)

    layer["image"] = layer["image"].resize(layer["scale"])

  bottom_layer = layers[0]

  top_layers = layers[1:]

  output = bottom_layer["image"]\
    .embed(bottom_layer["x"], bottom_layer["y"], slot_file_width, slot_file_height)

  if len(layers) > 0:
    output = output.composite(\
      list(map(lambda layer: layer["image"], layers)),\
      "over",\
      x=list(map(lambda layer: layer["x"], layers)),\
      y=list(map(lambda layer: layer["y"], layers))\
    )

  output.tiffsave(output_file, compression = "lzw")
```

On my Lenovo T430 (Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, dual-core, 2 threads per core) this operation takes <9s. Two of the images are 2000x3400 4-band PNGs, the third is a 2560x1536 JPEG.

Question: is it possible to optimise this piece of code at all?

- I have tried cropping the layers myself rather than leaving them "dangling outside of the frame", so to speak, but it very clearly made no difference.
- I have also tried not using PNGs/JPEGs and only using TIFFs (compressed) with `tiffload`. That made no difference either.
- All four threads are used to their fullest, so parallelism seems to be going alright.
- The output does not have to be TIFF, but I need a lossless format since the result will be used for some hi-def printing. I use compression since I upload the results to a cloud storage, so if I cut a few ms in processing time by saving uncompressed TIFFs, I will probably lose more since the file will end up a lot larger (also, storage is not free).

**Comment by jcupitt** [comment]
Hello @juona,

You create `top_layers`, but never use it, so you are compositing the bottom layer twice. I don't suppose that would make much difference though.

Are you building libvips yourself? I'd check that your C++ compiler supports vector shuffle: `composite` has a fast vector path that needs g++ 8 or better, I think. You should see this in configure:

```
checking for __attribute__((vector_size))... yes
checking for an ANSI C-conforming const... yes
checking for mode_t... yes
checking for off_t... yes
checking for size_t... yes
checking for gcc with working vector support... yes
checking for C++ vector shuffle... yes
checking for C++ vector arithmetic... yes
checking for C++ signed constants in vector templates... yes
checking for working memcmp... yes
```

Enabling `-O3` can help too.

For style, I think I'd write it like this:

```python
#!/usr/bin/env python3
  
from tqdm import tqdm
import pyvips

layers = [
  {
    "file": "./design-3.jpg",
    "scale": 3.914214463840399,
    "x": -3159,
    "y": -4182
  },
  {
    "file": "./design-2.tif",
    "scale": 3.54375,
    "x": 1012,
    "y": 2347
  },
  {
    "file": "./design-1.tif",
    "scale": 1.2209476309226932,
    "x": 3597,
    "y": 940
  }
];

slot_file_width = 7200
slot_file_height = 7200
output_file = "output-no-crop2.tif"

for i in tqdm(range(10)):
    stack = [] 
    for layer in layers:
        image = pyvips.Image.new_from_file(layer["file"], access="sequential")
        image = image.resize(layer["scale"])
        stack.append(image)

    background = pyvips.Image.black(slot_file_width, slot_file_height, bands=4)
    background = background.copy(interpretation="srgb")
    output = background.composite(stack, "over",
                                  x=list(map(lambda layer: layer["x"], layers)),
                                  y=list(map(lambda layer: layer["y"], layers)))

    output.write_to_file(output_file, compression="lzw")
```

Making the big, transparent background image is a little slower than using embed, as you had, but to code is neater.

**Comment by juona** [comment]
Thanks a ton for a quick answer, great support, as always!

Good catch with the `top_layers`. Here I made an excerpt of the original application code and modified it slightly just for this test. Adding `top_layers` was one of the modifications, so not checked thoroughly.

TBH off the top of my head I can't remember how I got vips on my system... : ]] That was long ago enough, but recently enough so that the version would be 8.7.4.

Any idea how much improvement I could expect with `shuffle` and `O3`?

And since we are talking builds, I believe that pyvips itself succeeded in building a vips binary extension, but just in case, "binding for the libvips image processing library, API mode" means just that, right?

**Comment by jcupitt** [comment]
Ah OK, try vips-8.8, it has some useful optimisations to `composite`.

I see:

```
$ time ./juona2.py 
100%|███████████████████████████████████████████| 10/10 [00:13<00:00,  1.33s/it]
real	0m13.473s
user	1m15.735s
sys	0m0.607s
```

So 13s for 10 iterations on this four core i7.

You can try:

```
$ python3
Python 3.7.3 (default, Aug 20 2019, 17:04:43) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.API_mode
True
```

So I'm using a compiled interface.

**Comment by juona** [comment]
Hmm, the performance on your computer is promising. I could surely get a faster VM for the actual deployment, and this would already be quite acceptable.

So you have already given me 3 things to try, I believe this can be closed for now. Thanks a lot!
