### ISSUE TITLE
Dzsave and openslide tiles not consistent 

### ISSUE THREAD

**Issue by pkochubey** [libvips/libvips#1444]
Hi, I catch interesting issue.
I use latest version: vips, openslide, openseadragon (OSD).
When I use openslide(deepzoomgenerator) + OSD all fine at zoom.
When I use vips + OSD on right side on slide I see glitch at zoom image. You cat see it on video ( https://yadi.sk/i/fNXqp9yVcIe53g ), first time I show openslide, second time vips. Problems reproduced at use any slide (svs, mrxs). I use all settings(vips dzsave, OSD, openslide tiling) by default. I'm don’t have any idea, any know what is it?

**Comment by jcupitt** [comment]
Hello @pkochubey,

I'd guess dzsave is not expanding edge tiles. Do you see problems at the bottom row too?

`dzsave` will expand edge tiles in google maps mode, but not in the default deepzoom mode. 

Does OSD have a gmaps mode? If it does, you could try turning that off, or enabling `--layout google` when you run dzsave.

**Comment by pkochubey** [comment]
Hello @jcupitt 

> Do you see problems at the bottom row too?
Yes, full right row has this problem. 

> Does OSD have a gmaps mode?
By default don't have.

Why dzsave is not expanding edge tiles by default? Any test case will be fall if it implement? I working with medical slides, and layout between openslide and dzsave should be the same.

**Comment by jcupitt** [comment]
DeepZoom pyramids do not have expanded edge tiles, so `dzsave` is just following the spec.

You need to write a gmaps pyramid instead with `--layout google`, or adjust OSD to expect small edge tiles.

**Comment by pkochubey** [comment]
Ok, `--layout google ` it definitely doesn't suit me.

> adjust OSD to expect small edge tiles.

Thanks, this is good idea, I check it

**Comment by jcupitt** [comment]
I think you can make OSD work with gmap pyramids if you change the javascript function that generates URLs for tiles, so that's probably another option.

**Comment by pkochubey** [comment]
This is right, but in first time I use openslide + OSD, and only after 10 minutes I will use result libvips dzsave. In my world, should be the same result between openslide and vips. In bad situation I will forked libvips and fix code for my situation.
