### ISSUE TITLE
Fail to update header text using vipsheader | sed | vipsedit

### ISSUE THREAD

**Issue by gvincke** [libvips/libvips#1450]
Hi,
I try to update the text of the image-description in the header of a v file, and tried the commands as described in the `man vipsedit`:
`vipsheader -f getext HSM0170.v | sed s/'Old text'/'New text'/ | vipsedit -e HSM0170.v`
The result is that it deleted the test of the header of the image.
Before i do the `vipsheader --field image-description HSM0170.v` give me all the information, and after the `vipsheader | sed | vipsedit` trio the `vipsheader --field image-description HSM0170.v` output is null.
`vipsheader -f getext HSM0170.v | sed s/'Old text'/'New text'/`output shows me that my sed command succeeded. So the problem is between the sed and the vipsedit.
So my question is : is `vipsedit -e HSM0170.v`still the right way to push back all the text info to the header of my file ?

Additionnal information : vips-8.8.0

Thanks a lot for your help and explanations.
Grégoire

**Comment by jcupitt** [comment]
Hello @gvincke,

I've not used `vipsedit -e` for years, it's probably broken :( I'll have a look. Thanks for the report!

**Comment by jcupitt** [comment]
Oh, it's just that `vipsedit` will start replacing the header before your sed finishes. Try going via an intermediate file:

```
john@yingna ~/pics $ vips copy k2.jpg x.v
john@yingna ~/pics $ vipsheader -f getext x.v | sed s/Pixel/Banana/ > x && vipsedit -e x.v < x
john@yingna ~/pics $ vipsheader -a x.v | grep Banana
exif-ifd2-BananaXDimension: 1450 (1450, Long, 1 components, 4 bytes)
exif-ifd2-BananaYDimension: 2048 (2048, Long, 1 components, 4 bytes)
```

**Comment by gvincke** [comment]
Great !!! You made my day !
I confirm that it works like a charm.
Thanks a lot !
Have a nice WE.
Grégoire
