### ISSUE TITLE
Net-Vips Dz image with color profile

### ISSUE THREAD

**Issue by kalozka1** [libvips/libvips#1451]
Hi,

I need to create dz image with color profile (i need to deal with Adobe RGB) in it, but I didn't succeed.

```
            using (NetVips.Image srcImage = NetVips.Image.NewFromFile(sourceFileFullPath))
            {
                srcImage.Dzsave(destinationTileFolderFullPath, container: "fs", tileSize: 512, strip: false);
            }
```

The same parameter (not stripping the meta data) gives me good result when I use Jpegsave to create thumbnails.

Can anyone give me a clue what am I doing wrong?

The source file [https://we.tl/t-1YBvvoyyRa](url)  has a color profile attached to it.
I'm using the Net-Vips v1.0.7 on windows in a .net 4.6.1 project.

Istvan

**Comment by jcupitt** [comment]
Hello @kalozka1,

`dzsave` always strips all tiles, since you don't want to replicate the metadata in every tile in a large pyramid.

I would transform your adobe98 image to srgb before calling `dzsave`.  Something like (in Python):

```python
x = pyvips.Image.new_from_file("some-jpg-with-an-adobe98-profile.jpg", access="sequential")
x = x.icc_transform("srgb")
x.dzsave("mypyr")
```

**Comment by kalozka1** [comment]
Thanks @jcupitt!

Does this mean that i cannot have adobe rgb image as pyramid?
Is this something specific for the pyramid images in general or it has to do to the implementation VIPS have?

**Comment by jcupitt** [comment]
libvips always strips all metadata from pyramid tiles. It would be very inefficient to save metadata on every tile in a pyramid -- the pyramid would be significantly larger. 

Instead, you should transform to srgb first.

**Comment by kalozka1** [comment]
Thank you @jcupitt!

Unfortunately converting to SRGB is not an option for me.

It is a little bit confusing/misleading that Dzsave has a parameter called 'strip', which in fact doesn't have an affect on the tripping behavior.

**Comment by jcupitt** [comment]
Could you explain why conversion to srgb will not work? I think it's very unlikely that your users would notice -- only people on wide gamut monitors with very high-end display setups will see any difference.

Another alternative would be to attach a profile to the DIV that displays the image using the CSS color-profile property. Could that solve your problem?

**Comment by jcupitt** [comment]
I made you a demo. Here's your test image as sRGB deepzoom. Put it in one one tab and resize it to fill the screen.

http://www.rollthepotato.net/~john/kalozka1/

Here's your test image as adobe98:

http://www.rollthepotato.net/~john/kalozka1/test.jpg

Put that in another tab and try flipping between them. I don't see any differences.

**Comment by jcupitt** [comment]
I made the dz image with:

```
vips icc_transform test.tif pyr.dz srgb
```

**Comment by kalozka1** [comment]
I understand why are you pushing me to the direction of srgb.

The solution im working on is for the photography industry.
Yes, my clients use professional monitors.

I need the adobe rgb. Believe me, i know pretty well hat is on stake here.

I solved the original question (including color profile in the images), by adding icc profile to each file of the dzsave. Yes, the file size sky rocketed. But i cannot get away without adobe rgb.

Do you see any ways how can i implement adobe rgb dz support in a better way?

**Comment by kalozka1** [comment]
The CSS color-profile property was a very interesting idea! But it seams to me that it is not really supported by the main browsers (Chrome, Firefox, Edge and Safari in my case).

**Comment by jcupitt** [comment]
Ah OK, I wasn’t sure. Most people are not very interested in colour,
unfortunately.

You need an extra “don’t strip” flag for dzsave. I’ll have a look.

**Comment by kalozka1** [comment]
Thank you!

**Comment by kalozka1** [comment]
Meanwhile I upgraded to Netvips v1.1.0 with Libvips v8.8.3. I appreciate the bug fixes :)

**Comment by jcupitt** [comment]
Could you have a rule like:

```css
img { 
  color-profile: url("http://example.com/profiles/adobe98.icm") 
}
```

To have the profile attached to the IMG tags that hold the tiles in the page? I've not tested this, of course :( It should make your pyramids load a little faster.

**Comment by jcupitt** [comment]
git master libvips has a new `no_strip` option for `dzsave`. This will be in libvips 8.9.

You'll still want to strip yourself, then reattach just the ICC profile, otherwise your tiles will be *huge*.

Thanks for the suggestion!

**Comment by kalozka1** [comment]
Thank you very much!
