### ISSUE TITLE
vips dzsave output only desired resolution

### ISSUE THREAD

**Issue by Tato14** [libvips/libvips#1454]
Hi! With the command `vips dzsave` I am ale to get a folder with all the levels of a `mrxs` image cropped. But, is it possible to output only, for example, full resolution (level 0) and not the rest?

Thanks!

**Comment by jcupitt** [comment]
Hello @Tato14,

Try `--depth one`. It will only write the largest pyramid layer.

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave

**Comment by Tato14** [comment]
Hi @jcupitt,

Thanks for the answer. And imagine that I have a whole slide at 40X and I want only tiles at 20X is there any way to get only this augmentation?
Thanks!

**Comment by jcupitt** [comment]
If the slide has a 20x layer, you can just pull that out. For example:

```shell
vips dzsave myfile.sys[level=1] x --depth one
```

But not all slide formats will have a half-size level, so you'd need to check.

If there is no 20x level, you can just shrink the top level by 2 and save as `.dz` (deepzoom):

```shell
vips resize myslide.svs x.dz[depth=one] 0.5
```

**Comment by jcupitt** [comment]
And use `vipsheader -a myslide.svs` to see all the levels.

**Comment by Tato14** [comment]
Ok! Thanks!

And kind of related: If an image have both 40x and 20x layers and I want to get tiles "covering" the same area on both augmentations I should half the size tile in 20x. As an example: 20X tile 256x256 --> 40X 512x512
Am I right?

And finally, which should be the computational cost of doing the second option (40X - 512x512) compared to the first one (20X - 256x256) ?

**Comment by jcupitt** [comment]
I wouldn't touch the tile size. Just leave it as the deepzoom default (256x256 for every layer), unless you really know what you are doing.
