### ISSUE TITLE
How to load an image file from memory in Python?

### ISSUE THREAD

**Issue by kaas3000** [libvips/libvips#1457]
Hello, when I try to load an existing memory block as a libvips Image object, the data is not what I expect it to be.  

The input image is loaded into an ImageSurface object of the cairo library. The image data of this object is retrieved and loaded into a libvips Image object.  
Both libraries output the image data in the same format (4\*8 bytes). (cairo stores the channels in a different order however, so they have to be switched)

This behaviour can be reproduced with script provided below.  
When an image file is loaded directly into a libvips Image, it's memory is printed and shows the expected data. (all zero's with 255 for a different channel every time)  
However, when the same image is loaded from cairo, the memory printed is different every time. Sometimes it resembles the expected data a bit, but sometimes it looks completely random.

How is it that loading data this way causes it to change?

Thanks in advance,
Kees

## Code to reproduce this issue

```python
#! /usr/bin/env python3
import argparse
import hashlib

import typing
from cairo import ImageSurface
from pyvips import Image, BandFormat


def surface_to_vips(cairo_image_surface: ImageSurface) -> Image:
    bands = 4
    width = cairo_image_surface.get_width()
    height = cairo_image_surface.get_height()
    img_bytes = bytes(cairo_image_surface.get_data())

    vips_image = Image \
        .new_from_memory(img_bytes, width, height, bands, BandFormat.UCHAR) \
        .copy(interpretation='srgb') \
        # .unpremultiply().cast(BandFormat.UCHAR)

    b, g, r, a = vips_image.bandsplit()
    out = r.bandjoin(g).bandjoin(b).bandjoin(a).copy()
    out = Image.new_from_memory(out.write_to_memory(), out.width, out.height, out.bands, out.format).copy(interpretation='srgb')
    return out


def get_im_from_file(file_name: str) -> Image:
    im = Image.new_from_file(file_name).cast('uchar')
    return im


def get_im_from_cairo(filename: str) -> Image:
    surf = ImageSurface.create_from_png(filename)  # type: ImageSurface

    return surface_to_vips(surf)


def md5(target: bytes, max_len=None) -> str:
    hash_object = hashlib.md5(target)
    result = hash_object.digest()

    if max_len is not None:
        result = result[0:max_len]

    return str(result)


def print_bands(im: Image):
    print('size: ' + str(len(im.write_to_memory())))

    for band in im.bandsplit():
        mv = memoryview(band.write_to_memory())
        print(str(len(mv)) + ' ' + md5(mv, 5), end=': ')

        if len(mv) > 32:
            print([a for a in mv.cast('@B')[0:16]], end=' ... ')
            print([a for a in mv.cast('@B')[-16:]])
        else:
            print([a for a in mv.cast('@B')])


if __name__ == '__main__':
    argument_parser = argparse.ArgumentParser()
    argument_parser.add_argument('--img')
    argument_parser.add_argument('--out-dir')

    args = argument_parser.parse_args()

    print('CAIRO')
    cairo_im = get_im_from_cairo(args.img)
    cairo_im.write_to_file(f'{args.out_dir}/cairo.png')
    print_bands(cairo_im)

    print('FILE')
    file_im = get_im_from_file(args.img)
    file_im.write_to_file(f'{args.out_dir}/file.png')
    print_bands(file_im)
```

## Example image file:

![4x4](https://user-images.githubusercontent.com/2116782/67695496-7935cd80-f9a5-11e9-96de-a22de5b5e5d5.png)

**Comment by jcupitt** [comment]
Hello @kaas3000 

It seems to work for me -- I see:

```
$ ./kaas3000.py --img ~/pics/test.png --out-dir .
CAIRO
size: 16
4 b'\xdb\n\x12Ff': [0, 204, 0, 0]
4 b'\x0e\x9f\xa9X\x80': [0, 0, 204, 0]
4 b'\x1bv\x99\xfc\x02': [0, 0, 0, 204]
4 b'\xc8\x83\xd1\xed\xe4': [204, 204, 204, 204]
FILE
size: 16
4 b"\xe6l\xca'\xda": [0, 255, 0, 0]
4 b'\x83\xf4\xeb\xd2\xa2': [0, 0, 255, 0]
4 b'\xbb\xd8"aU': [0, 0, 0, 255]
4 b'\xc8\x83\xd1\xed\xe4': [204, 204, 204, 204]
```

Cairo uses premultiplied alpha, so the 255s in the file become 204s in memory, but otherwise they are the same. 

You are not keeping a reference to the output of `write_to_memory`, could that be causing memory to be lost on GC? I would try:

```python
def print_bands(im: Image):
    pixels = im.write_to_memory()
    print('size: ' + str(len(pixels)))

    for band in im.bandsplit():
        pixels = band.write_to_memory()
        mv = memoryview(pixels)
        print(str(len(mv)) + ' ' + md5(mv, 5), end=': ')

        if len(mv) > 32:
            print([a for a in mv.cast('@B')[0:16]], end=' ... ')
            print([a for a in mv.cast('@B')[-16:]])
        else:
            print([a for a in mv.cast('@B')])
```

(perhaps memoryview keeps a reference to the buffer object for you, I'm unclear)

**Comment by jcupitt** [comment]
I think you might be using an old pyvips. There was an issue in older versions where it would not track memory references through `new_from_memory` calls.

```python
out = Image.new_from_memory(out.write_to_memory(), out.width, out.height, out.bands, out.format).copy(interpretation='srgb')
```

It could allow the result of `write_to_memory` here to be collected while `out` was still alive.

Are you using pyvips 2.1.8?

**Comment by kaas3000** [comment]
Oh no you are right. I can't believe it's as simple as that.
Updating pyvips fixes the issue.

Thank you very much for your quick answer!
