### ISSUE TITLE
Obsolete link in conversion/autorot.c

### ISSUE THREAD

**Issue by JelF** [libvips/libvips#1458]
https://github.com/libvips/libvips/blob/ab5641b4d89e31f30f63def4b7fa9faf0fbb9382/libvips/conversion/autorot.c#L104

I found original text through [web.archive.org](http://web.archive.org/web/20131010174825/http://www.80sidea.com/archives/2316), but it is not in english

**Comment by jcupitt** [comment]
I removed the broken link. Thanks!
