### ISSUE TITLE
Libvips library c++

### ISSUE THREAD

**Issue by kitkat730** [libvips/libvips#1462]
How to use libvips library in c++.I'm newbie to Libvips and i m succesfully execute it from command prompt but don't understand how to use this in microsoft visual studio. So Please give me in detail explanation about how to do this or any link.
[https://libvips.github.io/libvips/API/current/using-from-cpp.html](https://libvips.github.io/libvips/API/current/using-from-cpp.html)
In above link they say compile with 

```
g++ -g -Wall example.cc `pkg-config vips-cpp --cflags --libs`
```

but i don't got it.

**Comment by jcupitt** [comment]
Hello @kitkat730,

That command is for linux. 

It's much more complex on Windows -- there is a discussion here which seems to work:

https://github.com/libvips/libvips/issues/508

But it's quite difficult.

**Comment by kitkat730** [comment]
Hello @jcupitt  i have tried your solution but didn't got right anything. Still i have some error. and i tried everything but not got it or may be  i'm new to libvips so not understand fully it's installation on windows.
Here is error that i got on after compiling on visual studio on windows

1>------ Build started: Project: libVips, Configuration: Debug Win32 ------
1>libVips.obj : error LNK2019: unresolved external symbol _g_log referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol _vips_error referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol _vips_error_exit referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol _vips_init referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol _vips_shutdown referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol _vips_version referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VOption * __thiscall vips::VOption::set(char const *,int)" (__imp_?set@VOption@vips@@QAEPAV12@PBDH@Z) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VOption * __thiscall vips::VOption::set(char const *,char const *)" (__imp_?set@VOption@vips@@QAEPAV12@PBD0@Z) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __thiscall vips::VImage::width(void)const " (__imp_?width@VImage@vips@@QBEHXZ) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class vips::VOption * __cdecl vips::VImage::option(void)" (__imp_?option@VImage@vips@@SAPAVVOption@2@XZ) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class vips::VImage __cdecl vips::VImage::new_from_file(char const *,class vips::VOption *)" (__imp_?new_from_file@VImage@vips@@SA?AV12@PBDPAVVOption@2@@Z) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall vips::VImage::write_to_file(char const *,class vips::VOption *)const " (__imp_?write_to_file@VImage@vips@@QBEXPBDPAVVOption@2@@Z) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: double __thiscall vips::VImage::avg(class vips::VOption *)const " (__imp_?avg@VImage@vips@@QBENPAVVOption@2@@Z) referenced in function _main
1>libVips.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class vips::VImage __thiscall vips::VImage::embed(int,int,int,int,class vips::VOption *)const " (__imp_?embed@VImage@vips@@QBE?AV12@HHHHPAVVOption@2@@Z) referenced in function _main

I need solution of this error so i can use this on my project.

**Comment by jcupitt** [comment]
I would guess you have not rebuilt the C++ binding. 

You can't use the C++ binary that we distribute with MSVC, you must build it yourself.
