### ISSUE TITLE
difference between cv::Mat and vips_image

### ISSUE THREAD

**Issue by CasonTsai** [libvips/libvips#1463]
excuse me, there's a problem when i load image with libvips,
cv::Mat A : load image directly from file with opencv 
cv::Mat B : load image from file with libvips, get the data pointer , then transfom it to cv::Mat ,because opencv's rgb channel  order is different from libvips's rgb channel order,so finally change it's channel order .
And i print the values whose  index  are [0][0],[0][1],[1][0],[1][1] of cv::Mat A and cv::Mat B,
cv::Mat A:
![image](https://user-images.githubusercontent.com/18262642/68376167-1e5d5c80-0183-11ea-9d33-1ff945239ecb.png)

cv::Mat B:
![image](https://user-images.githubusercontent.com/18262642/68376132-0ab1f600-0183-11ea-8e21-88d7caddb481.png)

the values in same index are slightly different.
but when i save cv::Mat A and cv::Mat B as image files,these two images look the same,the Tnaked eye can't tell the difference.
![image](https://user-images.githubusercontent.com/18262642/68376582-c6732580-0183-11ea-9e64-accc23d7ffc8.png)

Is this due to using different jpeg libraries?

**Comment by jcupitt** [comment]
Hello @CasonTsai,

Yes, if these are jpg images and you are using different jpg libraries, you will see small differences in pixel values. I would try with png images -- you should get exactly the same numbers.

**Comment by CasonTsai** [comment]
@jcupitt  Thank you for your response. It helped me a lot.And i try the png images,it's same
cv::Mat A :
![image](https://user-images.githubusercontent.com/18262642/68380003-f7eeef80-0189-11ea-9191-d4ca41ed34ef.png)
cv::Mat B:
![image](https://user-images.githubusercontent.com/18262642/68380027-04734800-018a-11ea-9a37-957d854b789a.png)
