### ISSUE TITLE
Rejoin dzsave output jpeg files into a single file

### ISSUE THREAD

**Issue by Tato14** [libvips/libvips#1464]
Is there any way to rejoin splitted images like the ones generated with `vips dzsave` into a single one?

I managed to do it using opencv-python and using filenames as coordinates but big images (>~14000 tiles) just silently fails or give me strange errors.

In case you want to look at the code, is something similar to [this one](https://stackoverflow.com/questions/56058875/paste-images-together-using-filenames-as-positions/56255574#56255574) I posted some months ago.

Thanks!

**Comment by jcupitt** [comment]
Hello @Tato14, 

Sorry for the delay, this dropped off my to-do list.

Try:

```
vips arrayjoin "$(ls *.jpeg | sort -t_ -k2g -k1g)" x.jpg --across 20
```

How this works:

- The `ls` lists all the jpg files, one per line.
- But they'll be in alphabetical order! If they are named as `x_y.jpeg`, then `10_0.jpeg` will come before `1_0.jpeg`, for example.
- The `sort` command splits each line into fields on the `_` character, then sorts numerically by the second number, then the first.
- This puts files in order from left to right, then from top to bottom.
- `arrayjoin` joins a list of tiles into a single square image. 
- You just need to give it the number of tiles across (the `across` param).

Here's a more complete explanation, with examples and tips:

https://stackoverflow.com/questions/58874087/how-to-convert-dzi-files-to-multi-tile-pyramidal-tiff-format/58927878#58927878

**Comment by Tato14** [comment]
Hi,

Sorry for reopenning the issue but I just realize that `arrayjoin` works nicely with WSI without empty spaces. What if there are different tissue chunks where you obtained tiles but with empty spaces  between them? 

Thanks

**Comment by jcupitt** [comment]
Hi, you'd need to spot missing files and use `blank.png` for those positions.
