### ISSUE TITLE
unexpected - and changed - result of #-() in ruby-vips

### ISSUE THREAD

**Issue by D-W-L** [libvips/libvips#1467]
Hi, 
I use the package vips and ruby-vips from Debian sid which provides the version 8.8.3.

With the latest release the behavior of the #subtract / #- method has changed.
The testcase:
```ruby
images1 = Vips::Image.new_from_buffer jpg1, ''
images2 = Vips::Image.new_from_buffer jpg2, '' 
diff = images1 - images2
```

where jpg1 and jpg2 are images which come from a surveillance camera, taken within one second. With the previous release the difference of the images "diff", was a quite dark, grey image with some lighter spots where a movement was. With the current release the diff is very noisy with very bright base colors (red, green, blue).

Because I have saved the single steps of processing, it seems to me, that the change comes from the #subtract method. From my humble point of view it seems, that the subtraction is made:
```c
signed int - signed int
```
where it comes to an to an integer underflow, but not
```c
abs(unsigned int - unsigned int)
```
what I think will give the expected behavior, which was the behavior of the previous release.

**Comment by jcupitt** [comment]
Hello @D-W-L 

libvips does `uint8 - uint8 -> int16`, ie. the result should be a signed 16-bit image. I don't think anything has changed here, and these operations are checked as part of the test suite. Let me double-check.

**Comment by jcupitt** [comment]
I tried a test program:

```ruby
#!/usr/bin/env ruby

require 'vips'

puts "ruby-vips version #{Vips::VERSION}"
puts "linked to libvips version #{Vips::LIBRARY_VERSION}"

a = Vips::Image.new_from_file(ARGV[0])
b = Vips::Image.new_from_file(ARGV[1])

c = a - b

puts "format = #{c.format}"
puts "interpretation = #{c.interpretation}"
puts "max difference = #{c.max()}"
puts "min difference = #{c.min()}"
puts "avg difference = #{c.avg()}"
```

With 8.8 I see:

```
$ ./diff.rb  ~/pics/k2.jpg ~/pics/k4.jpg
ruby-vips version 2.0.16
linked to libvips version 8.8.4-Tue Nov 12 09:25:20 UTC 2019
format = short
interpretation = srgb
max difference = 226.0
min difference = -255.0
avg difference = -122.23578489690613
```

With 8.7 I see:

```
$ ./diff.rb  ~/pics/k2.jpg ~/pics/k4.jpg
ruby-vips version 2.0.16
linked to libvips version 8.7.4-Sun Aug  4 05:55:55 UTC 2019
format = short
interpretation = srgb
max difference = 226.0
min difference = -255.0
avg difference = -122.23578489690613
```

So I don't think libvips has changed. Do you have a pair of image which show a change in behaviour?

Another possibility is that the program you are using to view images may have changed. The difference image will be signed 16-bit, so how you save it and what you view it with will be important. If you save as TIFF, most viewers will probably let you view pixels, but they will differ in how they translate negative values into lightness.

You could try:

```
c = a - b
result = c / 2 + 128
result.write_to_file("x.jpg")
```

Now 0 will display as a mid-grey, negative values will be darker, and positive values will be lighter.

**Comment by D-W-L** [comment]
Hi John,

thank you for your quick reply! I'm very new to vips and do not know the concepts very well. I didn't had it on my screen, that the values could get negative and that would get image distortion in the saved jpeg. My fix is simple 

> ```ruby
> diff = diff.abs
>```

Thank you very much for vips and your support! Detlef
-- Closed --
