### ISSUE TITLE
Multiple actions on same command

### ISSUE THREAD

**Issue by devlfm** [libvips/libvips#1474]
Hi,
I have a command in imagemagick that I want to convert to vips to run on a batch file:

Requirements:
I need to set input file density;
I need to create a canvas with known dimensions, and add the input-file inside (center crop);
I need to add 2 stripes of 1cm on each side;
I need to add text (barcode and labels) on the left stripe;

ImageMagick:
```
convert input-file.jpg 
 -units pixelsperinch -resample 300 -units undefined
 -background #00ffff -gravity center -extent 7087x3583
 -bordercolor ivory -border 117x0
 -rotate -90
 -gravity South -font code128.ttf -pointsize 100 "encoded-128-text"
 -font Arial -pointsize 30 -annotate "some text label"
 -rotate 90 output-file.jpg
```
Note: the rotate command is to place the text vertically on the 1cm stripe.

I've been trying to convert, but I'm struggling with cli commands.

Thank you all

**Comment by jcupitt** [comment]
Hello @devlfm 

The libvips CLI only supports a single command at once, so you'd need to use temporary files and some shell scripting. Is this linux?

Alternatively, you can use something like Python, Ruby or PHP. They can join up commands without needing temporary files, so you get much better performance.

**Comment by devlfm** [comment]
Hi @jcupitt 
No.. its windows, I'm ok with creating separate commands.
I'm trying to playing around with `gravity` to create the canvas part, seems to fit the needs of `-background #00ffff -gravity center -extent 7087x3583` just struggling with the background option

**Comment by jcupitt** [comment]
Try:

```
vips gravity in.v out.v centre 7087 3583 --background "0,255,255"
```

I'd use vips (`.v`) files for the intermediates.

**Comment by jcupitt** [comment]
Oh, you could also try `.jpg` I guess. Avoid `.png`, it's very slow.

**Comment by devlfm** [comment]
Thank you for the tip! yes we are using only `.jpg`, -- background "255,0,0" outputs white.. I though that would be red, am I missing something?

**Comment by jcupitt** [comment]
Oooops sorry, try space not comma, ie. `--background "255 0 0"`.

**Comment by devlfm** [comment]
Yes! thats it ^^ I was trying and got it working too with `--extend background --background "255 0 0"`

**Comment by devlfm** [comment]
I decided to continue with IM for the text operations, and now I only need to join the images.
I have a big image 7087x3600, and a label-stripe.png from IM with 3600x115, and now I need to:
rotate 90 and add to the left, and then rotate -90 and to the right. Should I create two imagens already rotated on IM? or VIPS allows to rotate the input image before join?

**Comment by jcupitt** [comment]
Could you post a sample input and output image? I've become confused about what goes where :(

The 90 degree rotate is quite slow, so it's probably best to do that just once and as soon as you can.

The vips CLI is pretty basic. I use something like Python for scripting fancy stuff.

**Comment by jcupitt** [comment]
I realize you can't use Python, but just to show what it would look like:

```python
import sys
import barcode
import pyvips

# the main image
main = pyvips.Image.new_from_file(sys.argv[1])

# resize to 7000 pixels across
main = main.resize(7000 / main.width)

# expand to 7087 and a red background
main = main.gravity("centre", 7087, 3583,
                    extend="background", background=[255, 0, 0])

# render a strip of text as white on red
mask = pyvips.Image.text("hello world!", font="sans 28")
label1 = mask.ifthenelse(255, [255, 0, 0], blend=True)
label1 = label1.gravity("centre", 7087, 150,
                        extend="background", background=[255, 0, 0])

# make an SVG barcode and expand as well
ean = barcode.get_barcode_class('ean13')
svg = ean('5901234123457').render()
barcode = pyvips.Image.new_from_buffer(svg, "")
# we don't need the alpha on the svg
barcode = barcode[0:3]
barcode = barcode.gravity("centre", 7087, 150,
                          extend="background", background=[255, 0, 0])

# join vertically and rotate 90
result = label1.join(main, "vertical").join(barcode, "vertical").rot90()

result.write_to_file(sys.argv[2])
```

It runs in under a second on this PC, including generating the barcode.

**Comment by devlfm** [comment]
![input](https://user-images.githubusercontent.com/11923375/69164824-9a8f6280-0ae8-11ea-9448-b12c015d75a1.png)
![output](https://user-images.githubusercontent.com/11923375/69164842-9e22e980-0ae8-11ea-933e-197645b3964c.png)

I did on photoshop to exemplify.

**Comment by jcupitt** [comment]
Ah I was confused, I thought there was a barcode there.

What does your `-resample 300` do? Won't that enlarge the image? Why do you have a 7000 pixel jpg at one point?

**Comment by devlfm** [comment]
`-resample 300` is to convert the input dpi to desired dpi.

So there two steps for cropping the input (as the input is a user file and may not be correct size).
The first step is to crop to our product size;
The second step is to match the printer paper size (only in height)

I do it in two steps to crop the image to the desired size, and then add the pink area. Otherwise if image is bigger in height, there would not be the pink area on top/bottom.

The third step is to add the strip with the labels on each side

**Comment by jcupitt** [comment]
I think ImageMagick will use `-resample` to resize the image, not change the DPI recorded in the image metadata. You will get very large images if users upload something strange.

For example:

```
$ identify k2.jpg 
k2.jpg JPEG 1450x2048 1450x2048+0+0 8-bit sRGB 271883B 0.000u 0:00.000
$ convert k2.jpg -resample 300 x.jpg
$ identify x.jpg 
x.jpg JPEG 6042x8533 6042x8533+0+0 8-bit sRGB 1.69743MiB 0.000u 0:00.000
```

Now if I change the DPI recorded in the image file:

```
$ vips copy k2.jpg y.jpg --xres 0.9 --yres 0.9
$ convert y.jpg -resample 300 x.jpg
$ identify x.jpg 
y.jpg JPEG 19029x26877 19029x26877+0+0 8-bit sRGB 12.082MiB 0.000u 0:00.000
```

**Comment by jcupitt** [comment]
I think you need to find your exact page size, work out how many pixels you need at that page size for 300 dpi, and then resize to those target dimensions.

**Comment by devlfm** [comment]
The tests we made work fine with that command, usually customers send the files with +/- correct CM but at 200dpi or 254dpi, and I know the pixels size we need for the printer at 300dpi, and using that command IM resamples to match the size we need (but its experimental because there are a lot of techniques to resize with IM).
Currently I'm with the problem of joining images with `vips arrayjoin "left-stripe.png, input-cropped.v right-stripe.png` "output.jpg[Q=98]", I think I need some param.. because generated a file with 21261x3600 pixels ^^ and labels are OK but input-cropped.v is all black.

![image](https://user-images.githubusercontent.com/11923375/69169310-07f2c180-0af0-11ea-932c-a9a2fbd6a80e.png)

**Comment by jcupitt** [comment]
`arrayjoin` only does regular grids of images. You'll need to use `vips join horizontal` twice.

**Comment by jcupitt** [comment]
What size output image do you need to make for your printer, in pixels?

**Comment by jcupitt** [comment]
So:

```
vips join left-label.jpg main.jpg temp.jpg horizontal
vips join temp.jpg right-label.jpg out.jpg horizontal
```

In Python you can make your sample image like this:

```python
import sys
import pyvips

# load and size the main image to fit within 1440 x 1080
main = pyvips.Image.thumbnail(sys.argv[1], 1440, height=1080)

# expand to 1440 x 1116 with a red background
main = main.gravity("centre", 1440, 1116,
                    extend="background", background=[255, 0, 0])

# render a strip of text as white on red
mask = pyvips.Image.text("LABEL WITH SOME TEXT", font="sans 18")
label1 = mask.ifthenelse(255, [255, 0, 0], blend=True)
label1 = label1.gravity("centre", 1116, 72,
                        extend="background", background=[255, 0, 0])
label1 = label1.rot90()

mask = pyvips.Image.text("LABEL WITH SOME MORE TEXT", font="sans 18")
label2 = mask.ifthenelse(255, [255, 0, 0], blend=True)
label2 = label2.gravity("centre", 1116, 72,
                        extend="background", background=[255, 0, 0])
label2 = label2.rot270()

# join horizontally 
result = label1.join(main, "horizontal").join(label2, "horizontal")

result.write_to_file(sys.argv[2])
```

Its about 0.1s to make this:

![x](https://user-images.githubusercontent.com/580843/69170064-58b6ea00-0af1-11ea-99bb-765f2851455b.jpg)

**Comment by devlfm** [comment]
Thank you very much for your sample, I was able to create all individual commands of vips cli, just for testing. I'll try to create now a py file and use pyvips, it seams more flexible and access to vips buffer may increase performance.
Kind regards!
