### ISSUE TITLE
libvips extension for PHP on windows

### ISSUE THREAD

**Issue by flexphperia** [libvips/libvips#1475]
Is it possible to use libvips in PHP for windows? 

At the moment I am using CLI to perform several operations one by one using the `exec `command and saving after each operation to a temporary file and I would like to optimize it more.

**Comment by jcupitt** [comment]
Hello @flexphperia,

It shouldn't be too hard to make it work, but as far as I know no one has done it yet. We need a volunteer.

**Comment by flexphperia** [comment]
Maybe there is a plan to include such a DLL extension in the package with releases? Unfortunately, I don't know how to compile it myself but I would use it crazy :)
