### ISSUE TITLE
Upscaling creates a line of black pixels on the right side/bottom

### ISSUE THREAD

**Issue by VincentMarck** [libvips/libvips#1476]
Hi,

I've been trying to figure out why my app (using vips 8.8.3) sometimes leaves a line on the right and bottom side, and I've managed to narrow it down to vips itself. For as far as I can see it only happens with jpeg's, png's seem to be spared. I've tested this on multiple images, and simply running this from command line will show the issue:

vips affine original.jpg resized.jpg "1.5 0 0 1.5"

The further you upscale the image, the more obvious the black line seems to become. I've noticed this issue has actually been reported before and has been fixed since then, but only when resizing down (or at least for me), when upscaling it keeps happening. These threads mention the same issue:

- https://github.com/libvips/libvips/issues/131
- https://github.com/lovell/sharp/issues/1185

Here is an actual example:

Original:

![original](https://user-images.githubusercontent.com/38294896/69429831-c4d56000-0d34-11ea-889d-f0235c5935d5.jpg)

Resized (using the command above):

![resized](https://user-images.githubusercontent.com/38294896/69429871-d61e6c80-0d34-11ea-82c3-c95391402a31.jpg)

**Comment by jcupitt** [comment]
Hello @VincentMarck, 

Try:

```
vips affine original.jpg resized.jpg "1.5 0 0 1.5" --extend copy
```

It's to do with rounding behaviour: depending on the resize ratio, the sampling convention (centre vs. corner) and the size of the original, you can get fractional pixels visible in the output image.  `--extend-copy` will copy input pixels outwards. The default is `--extend black`, which will produce the line you see.

You might also want to consider using `--idx 0.5 --idy 0.5` to enable centre sampling. It usually gives more natural results for upsampling.

`affine` is a very low-level operation. I would use `resize` instead: it does all this for you:

```
vips resize pineapple.jpg x.jpg 1.5
```

To make:

![x](https://user-images.githubusercontent.com/580843/69432264-47f4b700-0d31-11ea-8aa5-a8c0eb8f699a.jpg)

It defaults to cubic.

**Comment by VincentMarck** [comment]
Ah, that makes sense, I get it now. Wasted so much time on figuring out where this line came from 😄

Thanks for the quick response!
