### ISSUE TITLE
Join 1 bit tiff to composite CMYK

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1477]
using imagemagick convert it can be done as

```
convert foo(c).TIFF foo(m).TIFF foo(y).TIFF foo(k).TIFF -set colorspace CMYK -combine +write info: out.tiff
```

How to do in VIPS, i tried with 

```
vips compite "c.tif m.tif y.tif k.tif" cmyk.tif[compression=lzw]  5 --compositing-space cmyk
vips_colourspace: no known route from 'b-w' to 'cmyk'
```

also tried with `--compositing-space 1ch`

thanks

**Comment by jcupitt** [comment]
Hello, you need to join the four one-band images together to make a four band CMYK image. 

```
vips bandjoin "c.tif m.tif y.tif k.tif" cmyk.tif
```

That'll be tagged as `b_w` with three alphas rather than CMYK (I think), so you'll need a second pass to tag it as CMYK.

```
vips copy cmyk.tif my_real_cmyk.tif --interpretation cmyk
```

Use something like Python and you can do it in a single step.

**Comment by vkkindia** [comment]
Thank you cuppit for the immediate  response.

The test_cmyk.pdf is seperated into 1 bit tiff using ghostscript
*gs-921-linux-x86_64  -dNOPAUSE -sDEVICE=tiffsep1 -sOutputFile=test_cmyk
-dBATCH test_cmyk.pdf*

With this command  *vips bandjoin "c.tif m.tif y.tif k.tif"
cmyk.tif[compression=lzw]*   when cmyk.tif is viewed, I got CMY and black
color as empty.
Then with this command *vips copy cmyk.tif
my_real_cmyk.tif[compression=lzw] --interpretation cmyk  *the black is
showing as CYAN color. what am i missing.  I am attaching the 1 bit
separated tiff  and original pdf.  The output tif files

**Comment by jcupitt** [comment]
Your gs is saving halftone planes with 0 == ink, 1 == no ink. Try inverting if you want a conventional CMYK TIFF.

```
$ gs -dNOPAUSE -sDEVICE=tiffsep1 -sOutputFile=test_cmyk -dBATCH cmyktest.pdf 
GPL Ghostscript 9.27 (2019-04-04)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
$ vips bandjoin "test_cmyk(Cyan).tif test_cmyk(Magenta).tif test_cmyk(Yellow).tif test_cmyk(Black).tif" x.tif
$ vips copy x.tif y.tif --interpretation cmyk
$ vips invert y.tif z.tif
```

You can also convert CMYK PDF directly to CMYK TIFF:

```
$ vips magickload cmyktest.pdf x.tif
```

**Comment by vkkindia** [comment]
The requirement is the result from vips should match
convert test_cmyk.pdf -negate x.tif

From vips I could not get only black color merged others are OK.
