### ISSUE TITLE
VipsOperation: class "icc_export" not found

### ISSUE THREAD

**Issue by LebronCurry** [libvips/libvips#1478]
vips-8.8.0  
vipsthumbnail -t test_1125.jpg -s 600x600 -o test_1125_out.jpg[Q=90,optimize_coding,strip]

VipsOperation: class "icc_export" not found

**Comment by jcupitt** [comment]
Hello, your libvps has probably been built without ICC profile support.

You need to check how it was built and ensure that the lcms2 headers were present.

**Comment by LebronCurry** [comment]
Thank you. My English is poor. Most of the pictures don't have this problem, only when dealing with individual pictures will appear.

**Comment by LebronCurry** [comment]
I installed lcms2, but this problem will still occur

**Comment by jcupitt** [comment]
You need to install the dev package (so you get the headers too), then reconfigure and rebuild libvips.

**Comment by LebronCurry** [comment]
Thank you.This problem has been solved.

**Comment by jcupitt** [comment]
Glad it's working, I'll close.
