### ISSUE TITLE
compilation error 8.8.3

### ISSUE THREAD

**Issue by lallori** [libvips/libvips#1479]
Hello!
I am upgrading from 8.7 to 8.8.3 from sources, because I need the heic support.

I am getting this compilation error:
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/libpng15 -I/usr/include/libgsf-1 -I/usr/include/glib-2.0 -I/usr/include/ImageMagick -g -O2 -MT magick.lo -MD -MP -MF .deps/magick.Tpo -c magick.c  -fPIC -DPIC -o .libs/magick.o
magick.c:518:4: error: ‘HCLpColorspace’ undeclared here (not in a function)
  { HCLpColorspace, "HCLpColorspace" },
    ^
magick.c:520:4: error: ‘HSIColorspace’ undeclared here (not in a function)
  { HSIColorspace, "HSIColorspace" },
    ^
magick.c:521:4: error: ‘HSVColorspace’ undeclared here (not in a function)
  { HSVColorspace, "HSVColorspace" },
    ^
magick.c:523:4: error: ‘LCHColorspace’ undeclared here (not in a function)
  { LCHColorspace, "LCHColorspace" },
    ^
magick.c:524:4: error: ‘LCHabColorspace’ undeclared here (not in a function)
  { LCHabColorspace, "LCHabColorspace" },
    ^
magick.c:525:4: error: ‘LCHuvColorspace’ undeclared here (not in a function)
  { LCHuvColorspace, "LCHuvColorspace" },
    ^
magick.c:527:4: error: ‘LMSColorspace’ undeclared here (not in a function)
  { LMSColorspace, "LMSColorspace" },
    ^
magick.c:529:4: error: ‘scRGBColorspace’ undeclared here (not in a function)
  { scRGBColorspace, "scRGBColorspace" },
    ^
magick.c:530:4: error: ‘xyYColorspace’ undeclared here (not in a function)
  { xyYColorspace, "xyYColorspace" },
    ^
magick.c:531:4: error: ‘YDbDrColorspace’ undeclared here (not in a function)
  { YDbDrColorspace, "YDbDrColorspace" },
    ^
make[3]: *** [magick.lo] Error 1
make[3]: Leaving directory `/root/vips-8.8.3/libvips/foreign'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/vips-8.8.3/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/vips-8.8.3'
make: *** [all] Error 2

Thanks for your great work!

Lorenzo

**Comment by jcupitt** [comment]
Hello @lallori,

It looks like your ImageMagick version is not supported. I would try and older or newer version, or disable imagemagick support in libvips.

**Comment by jcupitt** [comment]
An older or newer version of imagemagick, I mean.

**Comment by lallori** [comment]
ImageMagick.x86_64 0:6.7.8.9-18.el7 this is what I have on Centos 7. 

I can try to compile without imagemagick support. What's the configure option?

**Comment by jcupitt** [comment]
I added something to the head of the 8.8 branch to fix this (I think), so you could also try that.

To build without IM, use `--disable-magick`.
