### ISSUE TITLE
Error relocating /usr/lib/libvips.so.42: heif_image_handle_get_raw_color_profile: symbol not found

### ISSUE THREAD

**Issue by linkyndy** [libvips/libvips#1480]
Hello,

I am using libvips 8.8.3 on Alpine Linux (together with ruby-vips 2.0.16) and my CI builds started failing recently with this error:

```
LoadError:
  Could not open library 'vips.so.42': Error loading shared library vips.so.42: No such file or directory.
  Could not open library '/usr/lib/libvips.so.42': Error relocating /usr/lib/libvips.so.42: heif_image_handle_get_raw_color_profile: symbol not found
# ./vendor/bundle/ruby/2.5.0/gems/ffi-1.11.2/lib/ffi/library.rb:145:in `block in ffi_lib'
# ./vendor/bundle/ruby/2.5.0/gems/ffi-1.11.2/lib/ffi/library.rb:99:in `map'
# ./vendor/bundle/ruby/2.5.0/gems/ffi-1.11.2/lib/ffi/library.rb:99:in `ffi_lib'
# ./vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/vips.rb:473:in `<module:Vips>'
# ./vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/vips.rb:470:in `<top (required)>'
# ./vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/ruby-vips.rb:1:in `require'
# ./vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/ruby-vips.rb:1:in `<top (required)>'
```

I've figured that the only thing that changed is the Alpine [package](https://gitlab.alpinelinux.org/alpine/aports/issues/10962) from 8.8.3-r1 to 8.8.3-r2, where libheif was added as dependency. However, since that happened, why cannot libvips find the library, all of a sudden?

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/1979 - this appears to be an Alpine packaging problem.

**Comment by linkyndy** [comment]
Thanks @lovell for your answer! What's the fix to this, then? 🤔

**Comment by acidbiscuit** [comment]
@linkyndy 

It is possible to use latest released version instead of `edge` until the issue is resolved:

```
    --repository http://dl-3.alpinelinux.org/alpine/v3.10/community \
    --repository http://dl-3.alpinelinux.org/alpine/v3.10/main vips-dev
```

**Comment by linkyndy** [comment]
@acidbiscuit works. Thank you! 🙌

**Comment by Nakilon** [comment]
I have this on 3.11 and 3.12
