### ISSUE TITLE
Create a coordinates file grid without doing the tiling

### ISSUE THREAD

**Issue by Tato14** [libvips/libvips#1481]
I was wondering if there is any option in `vips dzsave` to just print the coordinates of the patches that would be tiles using all the parameters (`--background`, ` --depth`,  `--tile-size` `--skip-blanks`) but without actually writing the tiled file. 
Maybe an easier to understand, I just want the file names but not the files themselves.

Thanks

**Comment by jcupitt** [comment]
Sorry, no. It would be quite easy to add some `printf()`s, if you're OK with C.

**Comment by Tato14** [comment]
Not with C, maybe I could give a try to the pyvips package. Thanks!
