### ISSUE TITLE
load .svs to VipsImage, save to .tif

### ISSUE THREAD

**Issue by jgeiger04** [libvips/libvips#1482]
Hi. My intention is to load a .svs file with openslideload,
[then do some changes like normalization,]
and save again as a pyramid image (like .tif, as you mentioned in pyvips#69 .svs is a read-only format)
My code is based on Vips from C doc example.
This works and pixel avg is equal, so I think VipsImage is correctly saved.
```	VipsImage *in;
	VipsImage *out;
	double in_avg;
	double out_avg;

  if( VIPS_INIT( argv[0] ) )
    vips_error_exit( NULL );

  if( argc != 2 )
    vips_error_exit( "usage: %s infile", argv[0] );

  if( vips_openslideload( argv[1], &in, NULL ) )
    vips_error_exit( NULL );

  if( vips_vipssave( in, "test2vips.v", NULL ) )
    vips_error_exit( NULL );

  if( vips_vipsload( "test2vips.v", &out, NULL) )
    vips_error_exit( NULL );

  if( vips_avg( in, &in_avg, NULL) )
    vips_error_exit(NULL);
  if( vips_avg( out, &out_avg, NULL) )
    vips_error_exit(NULL);

  printf( "in pixel avg = %f\n", in_avg);
  printf( "out pixel avg = %f\n", out_avg);

  g_object_unref( in ); 
  g_object_unref( out );

```

But,
with command line I tried to save the .v file to .tif with `vips tiffsave test2vips.v test2vips.tif --compression jpeg --Q 100 --tile --pyramid --bigtiff`
I was not able to open saved .tif file with QuPath. Could it be just too large?
Why takes it 19-fold memory in comparison to source file .svs?
Does it have something to do with the number of levels as in (# 128 pyvips)?

Besides I tried to convert with `vips jpegsave` and `vips pngsave`. Results do not show the original image but checked pattern (png) or just white (jpg).

Also, conversion took some time, therefore I wonder if implementation in C shoudn't be faster than in python? How can I take advantage of that power? Is the creation of the pyramid file a bottleneck?

Thanks in advance for any comment.

**Comment by jcupitt** [comment]
Hello @jgeiger04,

Python will be as fast as C for tasks like this -- almost all time will be spent in libvips, so the speed of the programming language doesn't matter.

I'd do something like:

```python
import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
# brighten slightly etc.
# do what you like here
image *= 1.1
image.write_to_file(sys.argv[2])
```

Then run with:

```
$ ./process.py some-slide.svs my-pyramid.tif[tile,pyramid,compression=jpeg]
```

Sorry, I don't know QuPath. You could try in nip2 -- it should work there.

**Comment by jgeiger04** [comment]
Yes, you're right, I could open the created tif-files with nip2.
Thank you for the tips!
Can I combine the arguments for compression (deflate/jpeg/..) so that the file size doesn't explode like that?
The point is that a 100MB image will now be 2GB, but I also have 1.5GB images as original.
does the `image *= 1.1` enlarge the image once again?

**Comment by jcupitt** [comment]
The `*= 1.1` multiplies every pixel by 1.1, so it'll make the image 10% brighter. It was just an example.

You can't combine jpeg and deflate -- TIFF makes you pick one.

The file shouldn't get too much bigger. For example, with CMU-1.svs, I see:

```
$ vips copy CMU-1.svs x.tif[tile,pyramid,compression=jpeg]
$ ls -l CMU-1.svs x.tif 
-rw-r--r-- 1 john john 177552579 Apr  2  2019 CMU-1.svs
-rw-r--r-- 1 john john 138786437 Nov 29 16:54 x.tif
```

It's actually a little smaller, though I should probably have used a higher Q setting.
