### ISSUE TITLE
Add "depth" param to tiffsave, as per dzsave

### ISSUE THREAD

**Issue by oceanful** [libvips/libvips#1485]
Is it possible to create all possible levels in pyramidal TIFF, along the lines of what @ruven suggested in https://github.com/libvips/libvips/issues/1188#issuecomment-449403527:

> Why not just make vips create all possible layers until it's no longer physically possible? Down to a size of 1px, for example. 

Currently (or at least, the behavior as of vips-8.8.2), tiffsave will stop creating levels when the image fits in a single tile, but pyramidal image viewers like OpenSeadragon expect to be able to request levels for smaller images. FWIW, ImageMagick creates these levels by default.

(If I've missed an option in vips tiffsave that already does this, please let me know. Thank you!)

**Comment by jcupitt** [comment]
Yes, `tiffsave` stops when the image fits within a tile. `dzsave` will keep going until the image is 1x1 pixel, but I'm not sure if that's right for TIFF.

I tried with imagemagick:

```
$ convert k2.jpg -define tiff:tile-geometry=256x256 -compress jpeg ptif:x.tif
$ tiffinfo x.tif | grep "Image Width"
  Image Width: 1450 Image Length: 2048
  Image Width: 725 Image Length: 1024
  Image Width: 362 Image Length: 512
  Image Width: 181 Image Length: 256
  Image Width: 90 Image Length: 128
  Image Width: 45 Image Length: 64
```

No idea why it stops at 64x64.

**Comment by oceanful** [comment]
Interesting. Maybe it's hardcoded in imagemagick?

Would it be possible to add a vips option like "last-pyramid-geometry=64x64" to make it create levels until the image fits in 64x64?

Or a "full-pyramid" option to just go all the way down to 1 like dzsave. Either would help improve the compatibility between vips-made ptiffs and iipimage/OpenSeadragon.

**Comment by mhchu** [comment]
I've also encountered this issue. OpenSeadragon requests a smaller image than the smallest tile size and receives the last available size from my image server and then rescales it because it thinks it's smaller than it is. I'd prefer not to make smaller tiles because on my network connection it really slows things down with 4x or 16x more tiles. It would be great if setting a tile size of 512 also created 256, 128, 64, etc so smaller tiles are available but only if needed (instead of my generating all tiles at 128 or 64). Thanks!

**Comment by oceanful** [comment]
> Yes, `tiffsave` stops when the image fits within a tile. `dzsave` will keep going until the image is 1x1 pixel, but I'm not sure if that's right for TIFF.
> 

My research so far indicates that there's no TIFF standard for how many pyramid levels to generate. 

Given that tiling and pyramid-ing are technically independent features (usually but not necessarily used together), it would seem safe and correct to generate all possible pyramid levels, independent of the tile size, as per DeepZoom's behavior and @ruven's suggestion.

If we're worried about backwards compatibility, perhaps it can be made into an option, but I imagine that most software would continue working with pyramid images that have *more* levels than before.

What do you think?

**Comment by jcupitt** [comment]
dzsave has a `depth` option:

```
   depth        - Pyramid depth, input VipsForeignDzDepth
			default: onepixel
			allowed: onepixel, onetile, one
```

Perhaps we should add that to tiffsave. Let's tag this as an enhancement for 8.10.

**Comment by oceanful** [comment]
Wonderful. Thank you John!

**Comment by jcupitt** [comment]
OK, it's in git master, thanks for the suggestion!

**Comment by oceanful** [comment]
Thank you John!!
