### ISSUE TITLE
Triggering VipsForeignSave using gobject-introspection interface

### ISSUE THREAD

**Issue by v1993** [libvips/libvips#1487]
I'm writing Lua bindings using lgi (Lua GObject-Introspection) to this library (because as incorrectly noted on your website Lua does not have FFI, only LuaJit does). Right now I'm wrapping calling of operations.

Most of things are done by setting and reading respective properties of objects, so first I set all input ones and then read output ones. As seen in the Binding section manual, reading outputs trigger actual operation if I understand this correctly.

Now, here is a problem: write functions have no respective "output" properties. Manual says to use `vips_call()` on them, but it is obviously inapplicable to my case.

How can I trigger saving operations using GIR facilities?

**Comment by jcupitt** [comment]
Hello @v1993,

You can get FFI for plain Lua, for example:

https://github.com/jmckaskill/luaffi

I've no idea which ones work well though. That one does seem rather old. How is Lua gobject-introspection implemented? Perhaps they have an FFI binding you could use.

Operations execute when you run the `build` method. The call sequence should be:

- `operation_new`
- set required arguments
- set optional arguments
- run build method (execution, eg save, happens here)
- get required output
- get optional output

The previous version of ruby-vips used gobject-introspection, it might be helpful for you:

https://github.com/libvips/ruby-vips/blob/84d68f174b194905c271bd9fab5915e527bd634d/lib/vips/call.rb#L240

I had to abandon gobject-introspection for ruby-vips, unfortunately. It was too unstable, and too difficult to control object lifetime correctly. I found plain FFI was no harder, and was **much** simpler and more reliable.

**Comment by jcupitt** [comment]
I had to abandon gobject-introspection for pyvips as well :( It was too unreliable, and too slow.

**Comment by v1993** [comment]
@jcupitt Thank you for your help! Sadly, there are no well supported FFI implementations for Lua, especially for recent Lua versions (Lua 5.3 never had one). Being GC language, so far I had no problems in Lua with lifetime in GLib/GTK+.

So actual execution of operation happen when I call `Vips.cache_operation_build` and not when I read, say, `out` property?

**Comment by v1993** [comment]
Yep, just tested and turned out that it actually works as-is. Thank you!

**Comment by jcupitt** [comment]
I'm glad it's working. Good luck!

**Comment by jcupitt** [comment]
There's a section on object lifecycle in the vipsobject docs, perhaps you missed it:

https://libvips.github.io/libvips/API/current/VipsObject.html#VipsObject.description

It explains `build` etc.
