### ISSUE TITLE
feature request: please add VIPS_REGION_SHRINK_MAX option

### ISSUE THREAD

**Issue by rgluskin** [libvips/libvips#1490]
Hi,
I'm using VIPS to generate pyramids of WSI detection maps of single cells.
When shrinking using MEAN/MEDIAN/MODE, it's hard to find the cells when starting from the lowest zoom level (e.g. the features "disappear").
Would it be possible to implement a sort of "max-pooling" to address this ?

Thanks,
Roman

**Comment by jcupitt** [comment]
Hi Roman, I guess you'd need MAX (or perhaps MIN) added, is that right?

**Comment by rgluskin** [comment]
Yes, that is exactly what I think might help...

**Comment by jcupitt** [comment]
OK, it should be in now. Thanks for the suggestion!
