### ISSUE TITLE
How to use the function 'draw mask' and 'draw image'?

### ISSUE THREAD

**Issue by cihrenzai** [libvips/libvips#1491]
'x' and 'y' in draw_mask means what? Should the mask be a binary one-channel image?
I set x,y=0 or x,y=image.width,image.height but failed to get correct result 

Besides, whar does 'mode' mean in draw_image?

**Comment by jcupitt** [comment]
Hello @cihrenzai,

The `draw_` operations are only really useful for very simple "paintbox"-style programs (they are used to implement the nip2 paintbox). I'd be cautious about using them anywhere else. What are you trying to achieve?

Docs here:

https://libvips.github.io/libvips/API/current/libvips-draw.html#vips-draw-mask

Yes, the mask is a one-band, uchar image with 0 to 255 meaning transparent to solid. Values are used to blend the ink into the image. 

Example:

```
$ vips copy Gugg_coloured.jpg image.v
$ vips text x.v "hello world" --width 200 --height 200
$ vips draw_mask image.v "255 0 0" x.v 200 200
$ vips copy image.v x.jpg
```

To make:

![x](https://user-images.githubusercontent.com/580843/70324284-f830e800-1826-11ea-8615-2c452138c330.jpg)

The mode arg in `draw_image` lets you sum images.
