### ISSUE TITLE
Allow spaces in image array filenames

### ISSUE THREAD

**Issue by akemrir** [libvips/libvips#1493]
I am trying to composite few images, but I need to use paths with spaces. How Can I escape them to use with vips command line?

Standard shell space escaping is not working.
`vips composite "backgrounds\ additional/top.png backgrounds\ additional/bottom.png central.png" out.png 2 --x "3 10" --y "1 20"`

This command is not working either, because vips splits array by spaces.
`vips composite "backgrounds additional/top.png backgrounds additional/bottom.png central.png" out.png 2 --x "3 10" --y "1 20"` 

This command is not working, becuase ' is used explicitly
`vips composite "'backgrounds additional/top.png' 'backgrounds additional/bottom.png' central.png" out.png 2 --x "3 10" --y "1 20"`

**Comment by jcupitt** [comment]
Sorry, I don't think that's possible at the libvips CLI right now. You'll need to use something like Python.

Let's leave this issue open as an enhancement.

**Comment by jcupitt** [comment]
(something like python, php, ruby, etc. should give you much better performance and IO behaviour too, so it might be worth investigating anyway)

**Comment by akemrir** [comment]
I`ll try out ruby-vips.
But in case of enhancements to this in CLI, maybe a way to choose separator will do the job?

**Comment by jcupitt** [comment]
Supporting \ as an escape character in strings should be simple. It's just this function:

https://github.com/libvips/libvips/blob/master/libvips/iofuncs/type.c#L1292

**Comment by akemrir** [comment]
Similar problem I`ve experienced when I wanted to use vips write_to_file.
I was forced to use write_to_buffer and then write to file with custom code.

**Comment by jcupitt** [comment]
`vips_image_write_to_file` should be fine -- I tried this:

```C
/* compile with:
 *      gcc try305.c -g -Wall `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

#define SIZE (100)

int
main( int argc, char **argv )
{
        VipsImage *image;
        int x, y, z;
        VipsPel *mem;

        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        /* SIZE x SIZE rgba image.
         */
        if( !(mem = VIPS_ARRAY( NULL, 4 * SIZE * SIZE, VipsPel )) )
                vips_error_exit( NULL );
        for( y = 0; y < SIZE; y++ )
                for( x = 0; x < SIZE; x++ )
                        for( z = 0; z < 4; z++ )
                                mem[y * 4 * SIZE + x * 4 + z] = 2 * (x + y + z);

        /* Wrap up as a 4-band VipsImage.
         */
        if( !(image = vips_image_new_from_memory( mem, 4 * SIZE * SIZE,
                SIZE, SIZE, 4, VIPS_FORMAT_UCHAR )) )
                vips_error_exit( NULL );

        if( vips_image_write_to_file( image, 
                "this is a filename with spaces.png", NULL ) )
                vips_error_exit( NULL );

        g_object_unref( image );

        g_free( mem );

        return( 0 );
}
```

I see:

```
john@kiwi:~/try$ ./a.out 
john@kiwi:~/try$ ls this\ is\ a\ filename\ with\ spaces.png 
'this is a filename with spaces.png'
```

**Comment by akemrir** [comment]
This line right? https://github.com/libvips/libvips/blob/master/libvips/iofuncs/type.c#L1321
vips_break_token allows to use regexp as second argument?

**Comment by akemrir** [comment]
Yes, that's the case.

**Comment by jcupitt** [comment]
OK, this works now:

```
vips arrayjoin "k\ 2.jpg" x.png
```

Where `"k 2.jpg"` is a filename containing a space. You can escape break characters everywhere, so:

```
vips copy x.png y.jpg[profile=a\,b.icc,Q=50]
```

Sets a profile from a file called `"a,b.icc"`.

Thanks for the suggestion!

**Comment by akemrir** [comment]
Very useful. Thanks for update.

**Comment by jddcef** [comment]
And on windows where the backslash itself is a directory seperator, how to differentiate it in the path?

**Comment by jcupitt** [comment]
You can use a double backslash, eg.:

```
$ vips black "x\\y.v" 10 10
```

**Comment by jddcef** [comment]
Hi, i'm failing to get a simple test file with a space to be found by vips...
I've tried permutations like
D:\temp\BKLXSC\\1696099971.tiff
D:\temp\BKLXSC\ 1696099971.tiff
D:\temp\BKLXSC\\\\1696099971.tiff
D:\temp\BKLXSC\\ 1696099971.tiff

etc

**Comment by jcupitt** [comment]
What's the exact command you are tryiong to run?

I see:

```
jcupi@DESKTOP-HGI6HBR MINGW64 /f/vips-dev-8.14/bin
$ ./vips.exe black "x y.jpg" 10 10

jcupi@DESKTOP-HGI6HBR MINGW64 /f/vips-dev-8.14/bin
$ ./vips.exe invert "x y.jpg" "y x.jpg"

jcupi@DESKTOP-HGI6HBR MINGW64 /f/vips-dev-8.14/bin
$ ls
 libaom.dll*                libgsf-1-114.dll*          libunwind.dll*
 libc++.dll*                libharfbuzz-0.dll*         libvips-42.dll*
 libcairo-2.dll*            libheif.dll*               libvips-cpp-42.dll*
 libcgif-0.dll*             libimagequant.dll*         libwebp-7.dll*
 libexif-12.dll*            libjpeg-62.dll*            libwebpdemux-2.dll*
 libexpat-1.dll*            liblcms2-2.dll*            libwebpmux-3.dll*
 libffi-8.dll*              liborc-0.4-0.dll*          libxml2-2.dll*
 libfontconfig-1.dll*       libpango-1.0-0.dll*        libz1.dll*
 libfreetype-6.dll*         libpangocairo-1.0-0.dll*   vips.exe*
 libfribidi-0.dll*          libpangoft2-1.0-0.dll*     vipsedit.exe*
 libgdk_pixbuf-2.0-0.dll*   libpixman-1-0.dll*         vipsheader.exe*
 libgio-2.0-0.dll*          libpng16-16.dll*           vipsthumbnail.exe*
 libglib-2.0-0.dll*         librsvg-2-2.dll*          'x y.jpg'
 libgmodule-2.0-0.dll*      libspng-0.dll*            'y x.jpg'
 libgobject-2.0-0.dll*      libtiff-6.dll*

jcupi@DESKTOP-HGI6HBR MINGW64 /f/vips-dev-8.14/bin
$
```

**Comment by jddcef** [comment]
powershell:
`PS D:\Users\User\OneDrive\Apps> C:\Users\User\Downloads\vips-dev-w32-all-8.14.5\vips-dev-8.14\bin\vips.exe arrayjoin "D:\\temp\\BKLXSC-1696099971.tiff D:\\temp\\BKLXSC\\ 1696099971.tiff" d:\temp\blahtest.tif[lossless,compression=deflate]`
and all the other variations... results in
`VipsForeignLoad: file "D:\temp\BKLXSC\ 1696099971.tiff" does not exist`

cmd:
`C:\Users\User\Downloads\vips-dev-w32-all-8.14.5\vips-dev-8.14\bin>C:\Users\User\Downloads\vips-dev-w32-all-8.14.5\vips-dev-8.14\bin\vips.exe arrayjoin "D:\\temp\\BKLXSC-1696099971.tiff D:\\temp\\BKLXSC\\\\1696099971.tiff" d:\temp\blahtest.tif[lossless,compression=deflate]`
`VipsForeignLoad: file "D:\temp\BKLXSC\\1696099971.tiff" does not exist`

I right clicked on the file itself to confirm its existence -> copy path, and it gives the path: "D:\temp\BKLXSC 1696099971.tiff"

`vips-modules-8.14
libaom.dll
libarchive-13.dll
libbrotlicommon.dll
libbrotlidec.dll
libbrotlienc.dll
libc++.dll
libcairo-2.dll
libcfitsio.dll
libcgif-0.dll
libexif-12.dll
libexpat-1.dll
libffi-8.dll
libfftw3-3.dll
libfontconfig-1.dll
libfreetype-6.dll
libfribidi-0.dll
libgdk_pixbuf-2.0-0.dll
libgio-2.0-0.dll
libglib-2.0-0.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libharfbuzz-0.dll
libheif.dll
libhwy.dll
libIex-3_1.dll
libIlmThread-3_1.dll
libimagequant.dll
libjpeg-62.dll
libjxl.dll
libjxl_threads.dll
liblcms2-2.dll
libMagickCore-6.Q16-7.dll
libmatio-11.dll
libniftiio.dll
libOpenEXR-3_1.dll
libopenjp2.dll
libopenslide-0.dll
liborc-0.4-0.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpixman-1-0.dll
libpng16-16.dll
libpoppler-131.dll
libpoppler-glib-8.dll
librsvg-2-2.dll
libsharpyuv-0.dll
libspng-0.dll
libsqlite3-0.dll
libtiff-6.dll
libunwind.dll
libvips-42.dll
libvips-cpp-42.dll
libwebp-7.dll
libwebpdemux-2.dll
libwebpmux-3.dll
libxml2-2.dll
libz1.dll
libznz.dll
vips.exe
vipsedit.exe
vipsheader.exe
vipsthumbnail.exe
`

**Comment by jcupitt** [comment]
I tried in psh as well, it all seems to work here:

```
PS F:\vips-dev-8.14\bin> .\vips.exe arrayjoin "x\ y.jpg y\ x.jpg" x.jpg
PS F:\vips-dev-8.14\bin> .\vipsheader.exe x.jpg "x y.jpg" "y x.jpg"
x.jpg: 20x10 uchar, 1 band, b-w, jpegload
x y.jpg: 10x10 uchar, 1 band, b-w, jpegload
y x.jpg: 10x10 uchar, 1 band, b-w, jpegload
```

**Comment by jcupitt** [comment]
I tried with tiffs and drive letters and that works too:

```
PS F:\vips-dev-8.14\bin> .\vips.exe black "f:\b a.tif" 10 10
PS F:\vips-dev-8.14\bin> .\vips.exe black "f:\b a.tif" 10 10
PS F:\vips-dev-8.14\bin> .\vips.exe arrayjoin "f:\\a\ b.tif f:\\b\ a.tif" "f:\c d.tif"
PS F:\vips-dev-8.14\bin> .\vipsheader.exe "f:\c d.tif" "f:\a b.tif" "f:\b a.tif"
f:\c d.tif: 20x10 uchar, 1 band, b-w, tiffload
f:\a b.tif: 10x10 uchar, 1 band, b-w, tiffload
f:\b a.tif: 10x10 uchar, 1 band, b-w, tiffload
PS F:\vips-dev-8.14\bin>
```

**Comment by jcupitt** [comment]
There are two different ways of quoting backslash and space because there are two different things interpreting them.

In plain command-line arguments, just use space and put the whole thing in quotes. PSH doesn't use backslash as escape, so you don't need to quote it:

```
PS F:\vips-dev-8.14\bin> .\vips.exe black "f:\b a.tif" 10 10
```

`arrayjoin` is different -- that's a string encoding a list of paths that needs to be split by libvips. It uses (*nix style) backslash as an escape character, so you do need to escape backslash as double backslash, and space as backslash-space.

```
PS F:\vips-dev-8.14\bin> .\vips.exe arrayjoin "f:\\a\ b.tif f:\\b\ a.tif" "f:\c d.tif"
```

I agree, it's confusing :( If you use something like python, all this shell craziness goes away.

**Comment by jddcef** [comment]
I came right, your examples helped, I was doing everything except the right thing, embarrassed
