### ISSUE TITLE
How to monitor progress when processing large images?

### ISSUE THREAD

**Issue by frmdstryr** [libvips/libvips#1497]
Is there any way to monitor the progress when converting/saving large images?  Thank you!

**Comment by jcupitt** [comment]
Hello @frmdstryrm,

Yes, you connect to the "eval" signal:

https://libvips.github.io/libvips/API/current/VipsImage.html#VipsImage-eval

You can also set the `VIPS_PROGRESS` env var to see a simple ticker on stdout:

```
$ VIPS_PROGRESS=1 vips copy wtc.jpg x.v
vips x.v: 9372 x 9372 pixels, 4 threads, 9372 x 16 tiles, 128 lines in buffer
vips x.v: done in 0.773s
$
```

**Comment by jcupitt** [comment]
The next versions of ruby-vips and pyvips have signal support, eg.:

https://github.com/libvips/ruby-vips/blob/master/example/progress.rb

**Comment by frmdstryr** [comment]
Just what I was looking for. Thank you!
