### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by augustocdias** [libvips/libvips#1498]
Hello, I’m seeing some logging being printed to stdout from time to time (warnings mostly). Is there a way to disable it?

**Comment by jcupitt** [comment]
Hi, yes, libvips uses the glib logging systems, so you can use that to intercept, filter, enable, disable etc. messages.

https://developer.gnome.org/glib/stable/glib-Message-Logging.html

As a handy shortcut, set the env var `VIPS_WARNING` to disable all warnings.

**Comment by augustocdias** [comment]
if I set `VIPS_WARNING=0` it will then disable it right? is there a `VIPS_ERROR` and `VIPS_CRITICAL` too? What is the default level?
And that doesn't impact on what is being added to the error buffer right?

**Comment by jcupitt** [comment]
Yes, just define it to something to block all warning messages.

You can define `VIPS_INFO` to enable informative messages, but that's the only other one.

Yup, no effect on the error buffer.
