### ISSUE TITLE
vips resize corrupts image

### ISSUE THREAD

**Issue by angelmixu** [libvips/libvips#1499]
Hi!

While using the C interface I came to an strange behaviour, when resizing an image with a text (it's a LAB file with black text inside) it generates a bigger image, but with the insides of the text filled with random pixels.

It doesn't happen only when using nearest or linear interpolator, on the others, the image is corrupted.

I have taken a look at the interpolators, and it's a little difficult for me understanding the behaviour to fix it.

I have tested it on macOS Mojave, using libvips homebrew commandline:
```
$ vips -v
vips-8.8.4-Thu Dec  5 16:24:34 UTC 2019
```

The command lines I used:
```
$ vips resize failing_vips_resize_8bit.tif failing_vips_resize_8bit-out.tif 3.0 --kernel lanczos3
$ vips resize failing_vips_resize_16bit.tif failing_vips_resize_16bit-out.tif 3.0 --kernel lanczos3
```
Here it is attached the two original files, and the output of the command
[vips_resize_corruption.zip](https://github.com/libvips/libvips/files/3959988/vips_resize_corruption.zip)

If using the 16bit LAB image, the output image gets the text corrupted, and the 8bit one, can't be opened in Photoshop, it says the TIFF file uses an unsupported bit depth.

This is a screenshot of how Photoshop shows the 16bit output image:
![Screenshot 2019-12-13 at 10 26 34](https://user-images.githubusercontent.com/2285977/70789339-1cdf0f80-1d93-11ea-8a95-636d6c16e88f.png)

EDIT: I tested the 8bit image converted to RGB and it's working correctly.

**Comment by jcupitt** [comment]
The 8-bit one is fine, but the 16-bit one is not saving LABS back to 16-bit TIF correctly. 

I'll have a look, thanks for the report.

**Comment by jcupitt** [comment]
OK, fixed in master, thanks for the report!

**Comment by angelmixu** [comment]
Thanks for the quick fix! :)

**Comment by jcupitt** [comment]
The 8-bit one is saved as float TIFF, which photoshop does not support.

**Comment by jcupitt** [comment]
You can turn float LAB into 8-bit LAB like this:

```
vips lab2labq failing_vips_resize_8bit-out.tif x.tif
```

**Comment by angelmixu** [comment]
Oh :/
I could do that, but from a user's point of view, shouldn't a resize maintain the same bit depth of the original image?

**Comment by jcupitt** [comment]
libvips does not usually recode explicitly -- it's done by the savers and only when needed.

This case is odd because TIFF supports both 8-bit and 32-bit LAB, so there's an ambiguity. Let's add a recode as a nasty and hacky special case just for resize, since that must be the most common case.

**Comment by angelmixu** [comment]
Thanks!

The other issue is this one: https://github.com/libvips/libvips/issues/1473

I'm wondering if there could be a generic solution to both cases, but can't think of one right now :/
Maybe a tag for maintaining the output format that should be, or alike.

**Comment by jcupitt** [comment]
I changed my mind -- it was too hacky.

Instead, the "squash" option to tiffsave turns 3-band float LAB into 8-bit, eg.:

```
$ vips resize failing_vips_resize_8bit.tif x.tif[squash] 2
$ vipsheader x.tif
x.tif: 5400x240, labq, tiffload_stream
```

**Comment by jcupitt** [comment]
I think (?) this is done now, I'll close.
