### ISSUE TITLE
vips use url to generate thumbnail

### ISSUE THREAD

**Issue by LebronCurry** [libvips/libvips#1500]
hello.
Graphicsmagick can use  url to generate thumbnail.Can libvips do the same?
If libvips can,what is its command. Thanks.

**Comment by jcupitt** [comment]
Sorry, no, you have to download and then thumbnail.

libvips 8.9 adds this feature:

https://libvips.github.io/libvips/2019/11/29/True-streaming-for-libvips.html

So you can write:

```
$ curl -vs http://www.rollthepotato.net/~john/theo.jpg | \
    vips thumbnail_stream [descriptor=0] x.jpg 128
```

But it's still not quite done. Another couple of weeks.

**Comment by LebronCurry** [comment]
ok，Thank you for your answer。

**Comment by jcupitt** [comment]
Or perhaps:

```
aws s3 cp s3://mybucket/input.jpg - | \
    vips thumbnail_stream [descriptor=0] .jpg 128 | \
    aws s3 cp - s3://mybucket/output.jpg
```

**Comment by LebronCurry** [comment]
OK, ffmpeg or graphicsmagick can use url to directly process videos or pictures, which saves time to download files, especially for large files. I don't know how it is implemented. If libvips can also have this function that would be great.
For example,   vipsthumbnail "url" -s 200x200 -o out.jpg

**Comment by jcupitt** [comment]
The libvips one is actually much faster -- imagemagick is doing this:

```
curl some-uri -o /tmp/some-tmp-file
convert /tmp/some-tmp-file -resize 200x200 out.jpg
```

ie. it is downloading the whole of the URI to a temporary file, and only then starting work on the resize. 

libvips will do the download and resize at the same time, with no temporary file. You'll get the resize for "free", since it'll already be done when the download finishes.

**Comment by LebronCurry** [comment]
ok, thanks for answering. But then I still need to download the file to the server.

**Comment by jcupitt** [comment]
Sorry, I'm not sure I understand.

Anyway, libvips 8.9 should do what you need.

**Comment by LebronCurry** [comment]
Thanks, i will try 8.9 later.

**Comment by LebronCurry** [comment]
Hello, I use this command
  curl -vs http://www.rollthepotato.net/~john/theo.jpg |  vips thumbnail_stream [descriptor=0] x.jpg 128
error：vips: unknown action "thumbnail_stream"

My vips version is 8.9.0

**Comment by jcupitt** [comment]
It was renamed during development -- try:

```
curl -vs http://www.rollthepotato.net/~john/theo.jpg | vips thumbnail_source [descriptor=0] x.jpg 128
```

**Comment by LebronCurry** [comment]
Ok,Thanks.
