### ISSUE TITLE
Outdated documentation is still available

### ISSUE THREAD

**Issue by deftomat** [libvips/libvips#1501]
I tried to find API docs thru the Google search and the first result was https://jcupitt.github.io/libvips/API/current

Is it possible to shut down that page or redirect it to https://libvips.github.io/libvips/API/current ?

I was quite confused when I discover that multiple webp options was removed 🙂

**Comment by jcupitt** [comment]
Hi, yes, it's unfortunate. 

If I removed the jcupitt fork, github will redirect URLs like this:

https://github.com/jcupitt/libvips/blob/master/README.md

But they won't redirect github pages URLs like this:

https://jcupitt.github.io/libvips/API/current/libvips-create.html#vips-text

So I have to leave the jcupitt fork there, or every old libvips pages URL will break.

**Comment by jcupitt** [comment]
On reflection, let's remove the repo. Most pages URLs have probably been updated by now, and as you say, it'll force google to /finally/ update their libvips page order.

**Comment by deftomat** [comment]
Thanks 👍
