### ISSUE TITLE
Downsample svs file from 40X to 20X

### ISSUE THREAD

**Issue by Tato14** [libvips/libvips#1503]
Is there any possibility to downgrade a svs file from `level=0` (40X) to `level=1` (20X) and saving it in svs format? 

I know that there is the option to write in tiff format using:
`vips tiffsave sample.svs[level=1] slide.tiff --tile --compression=lzw` 

The problem is that I am using an script that takes into account the `level` label and I have samples from different sources and different `level=0` augmentation. I would like to homogenize the `level` labels. I would like also to avoid to write all the files in tiff (because on some of them I do not have write permission)
Thanks!

**Comment by jcupitt** [comment]
Hi @Tato14,

No, openslide can only read files, it can't write them. You'll need to use some other format if you want to create files yourself.

You can read the 20x layer out of an SVS if that would help.

**Comment by Tato14** [comment]
Hi again! I would like to reopen this issue since some months ago libvips supports OME-TIFF. Is there now a way to perform this downsampling?My svs files are 40X (0.25 openslide.mpp) and I would like to convert them to 20X (0.5 openslide.mpp)

Thanks!
J

**Comment by jcupitt** [comment]
You still can't write SVS files though.

You can write OME-TIFF, if that would help, for example:

```
john@kiwi:~/pics/openslide$ vips copy CMU-1.svs[level=1] x.tif[tile,pyramid,compression=jpeg,subifd]
john@kiwi:~/pics/openslide$ vipsheader CMU-1.svs x.tif
CMU-1.svs: 46000x32914 uchar, 4 bands, srgb, openslideload
x.tif: 11500x8228 uchar, 3 bands, srgb, tiffload
```

**Comment by Tato14** [comment]
Hi, I am trying to install libvips from tarball. Which are the specific Dependencies that I should install to run this properly? Thanks!

**Comment by jcupitt** [comment]
It depends on your platform. There are some sample docker build files here: https://github.com/jcupitt/docker-builds
