### ISSUE TITLE
Issue in autorot

### ISSUE THREAD

**Issue by augustocdias** [libvips/libvips#1505]
I think I found a bug in the `autorot` function. 
I tried some images from this [repo](https://github.com/recurser/exif-orientation-examples) and the 2, 4, 5 and 7 don't get rotated to the correct orientation.

**Comment by jcupitt** [comment]
Hello, yes, libvips just does the rotation modes, not the flips.

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-autorot

I've never seen a flip mode in a real image, only in test suites, so I thought it wasn't worth implementing them, but apparently there are a few real cases. 

There's an enhancement issue here: https://github.com/libvips/libvips/issues/1461
