### ISSUE TITLE
Support for LogLuv TIFF images

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#1506]
This format is slightly related to Radiance HDR. Pixels are encoded in CIELUV (u’, v’) space, so perhaps a new VipsInterpretation is needed (`VIPS_INTERPRETATION_LUV`?).

More info: http://www.anyhere.com/gward/pixformat/tiffluv.html
Comparison between other HDR encodings: http://www.anyhere.com/gward/hdrenc/hdr_encodings.html

Test image: http://www.anyhere.com/gward/pixformat/images/84y2.tif
<sup>(source: http://www.anyhere.com/gward/pixformat/tiffluvrend.html)</sup>

**TIFF info**
```bash
$ tiffinfo 84y2.tif
TIFF Directory at offset 0x200b28 (2100008)
  Image Width: 1000 Image Length: 700
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 16
  Sample Format: signed integer
  Compression Scheme: SGILog24
  Photometric Interpretation: CIE Log2(L) (u',v')
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 2
  Planar Configuration: single image plane
  Sample to Nits conversion factor: 1.7900e+02
```

**Output**
```bash
$ vips copy 84y2.tif x.png
```
![x.png](https://user-images.githubusercontent.com/12746591/71188051-8aea7180-2280-11ea-94b5-5026e891403a.png)

**Expected output**
![x](https://user-images.githubusercontent.com/12746591/71188234-e0268300-2280-11ea-8bea-3cff568c3b3b.png)

**Notes**
Although it is supported by LibTIFF, I'm not sure how much demand there is to support this format. It doesn't seem to be a very common format.

**Comment by jcupitt** [comment]
Sure, logluv is a nice thing. I agree, we'd need a new `interpretation` tag and a set of conversion functions.

**Comment by jcupitt** [comment]
I added LUV and some conversion functions, though they don't actually work correctly heh.

**Comment by jcupitt** [comment]
... so it needs fixing, and then tiff load and save needs a LOGLUV handler.

**Comment by jcupitt** [comment]
Oh heh tiny error in one formula, LUV works now. So just TIFF load and save, I think.

**Comment by jcupitt** [comment]
tiffload works, tiffsave is not quite right still.

**Comment by jcupitt** [comment]
After some tinkering, it seems like the best solution is to load and save libvips XYZ as libtiff LOGLUV. It's not easy to get libtiff to deliver L*u*v* from LOGLUV images, unfortunately, and the way they do white-point adaptation is awkward.

This is a really simple change, so I've merged straight to master.

**Comment by jcupitt** [comment]
Here's what you get for:

```
vips copy 84y2.tif x.png
```

![x](https://user-images.githubusercontent.com/580843/73385522-3695d100-42c5-11ea-8229-f905d6329300.png)

**Comment by kleisauke** [comment]
Great, I confirm it's working! The quality also seems to be better than the image in the start comment (which is generated by `magick convert`).

**Comment by jcupitt** [comment]
Yes, it looks like very slightly different gamma. Huh funny, I wonder why.
