### ISSUE TITLE
Add quantization support to vips installed from homebrew

### ISSUE THREAD

**Issue by nthapaliya** [libvips/libvips#1507]
When installing on MacOS with homebrew (with default options), the `vips` tool doesn't include quantization support. Example:

` vips copy 1911694.svg x.png[palette]` gives:
`(vips:16841): VIPS-WARNING **: 13:37:46.285: ignoring palette (no quantisation support)`

I understand it's the matter of installing `libimagequant` and recompiling from source, but I wasn't able to get this to work on my machine.

**Comment by jcupitt** [comment]
Yes, someone will need to make a homebrew formula for libimagequant.

**Comment by nthapaliya** [comment]
You can install 'libimagequant' from homebrew already:

https://formulae.brew.sh/formula/libimagequant

The thing I couldn't figure out was for vips to detect it during compilation.

**Comment by jcupitt** [comment]
Then it should be easy -- just edit `vips.rb` and add the line

```ruby
  depends_on "libimagequant"
```

in the obvious place. I tried on my mac and I see:

```
17:26 $ vips copy small.jpg x.png
17:26 $ ls -l x.png
-rw-r--r--@ 1 john  staff  265101 21 Dec 17:26 x.png
17:26 $ vips copy small.jpg x.png[palette]
17:27 $ ls -l x.png
-rw-r--r--@ 1 john  staff  146990 21 Dec 17:27 x.png
17:27 $ vips copy small.jpg x.png[palette,colours=16]
17:27 $ ls -l x.png
-rw-r--r--@ 1 john  staff  70685 21 Dec 17:27 x.png
```

**Comment by nthapaliya** [comment]
Thanks! That did the trick. I think I will open a PR on `vips.rb` to include this library too.
