### ISSUE TITLE
VipsJepg: out of order read at line 160

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#1509]
I am using Sharp library fro NodeJS but I am sure the error is related to Vips so opening issue here. 

When I try to resize this image, I get following error:

```
[Error: VipsJpeg: Premature end of JPEG file
VipsJpeg: out of order read at line 160
]
```

![shop-2607121_1920_2_2](https://user-images.githubusercontent.com/1086617/71337227-aac7b100-2570-11ea-98bc-dce3f5ae6e74.jpg)

**Comment by lovell** [comment]
This JPEG image is truncated and/or corrupt.

To explicitly tell sharp it can trust the image and continue to process by ignoring errors from libjpeg, set the `failOnError` property to `false`.

https://sharp.pixelplumbing.com/en/stable/api-constructor/

**Comment by adityapatadia** [comment]
Okay let me try that. I think the reason browsers decode it is because they also have implemented this "best effort" based decoding.

Thanks a lot for quick response. :)
