### ISSUE TITLE
How to install libheif dependency

### ISSUE THREAD

**Issue by Moriarty1230** [libvips/libvips#1511]
I used v8.8.4, installed by **./configure**
but:
**file import with libheif:               no**
How should I use the libheif dependency
**./configure --without-heif (default: test)** is what I looked up from   **./configure --help**
What does **(default: test)** mean
How to use it

**Comment by jcupitt** [comment]
Hello @alex99123,

You need to have libheiff installed before you configure libvips. You should see something like:

```
$ pkg-config libheif --modversion
1.5.0
```

On Ubuntu, for example, you need the `libheif-dev` package.

**Comment by alex99123** [comment]
Thanks for the quick response.
@jcupitt 
Here are my steps for install libheif:
**git clone https://github.com/strukturag/libde265.git
./autogen.sh
./configure
git clone https://github.com/strukturag/libheif.git
./autogen.sh
./configure
pkg-config libheif --modversion**

output:
Package libheif was not found in the pkg-config search path.
Perhaps you should add the directory containing `libheif.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libheif' found

Is something wrong with my PKG_CONFIG_PATH?
How do I fix it?

**Comment by jcupitt** [comment]
You need to run `make` and `sudo make install`. They will build and install libheif to `/usr/local`. You'll need to make sure `/usr/local/lib/pkgconfig` is on your `PKG_CONFIG_PATH`.

**Comment by alex99123** [comment]
Hello
Thanks a lot for taking the time to explain
@jcupitt 

I think libheif was installed successfully
**pkg-config libheif --modversion
1.6.1**

But when I import pyvips into a python environment, I made a mistake
**Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
Traceback (most recent call last):
  File "/home/alex991230/.local/lib/python3.5/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ImportError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex991230/.local/lib/python3.5/site-packages/pyvips/__init__.py", line 71, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/home/alex991230/.local/lib/python3.5/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/alex991230/.local/lib/python3.5/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/alex991230/.local/lib/python3.5/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
>>>**

**Comment by alex99123** [comment]
I have a question. With libheif installed, can libvips convert images to heif format and save them?

**Comment by jcupitt** [comment]
It looks like `/usr/local/lib` is not on your library path. Running `sudo ldconfig` might help, depending on your platform.

Yes, libvips can read and write heif, for example:

```
vips copy k2.jpg k2.heic
```

**Comment by alex99123** [comment]
Thank you very much. **sudo ldconfig** is useful
But I have another problem, Does it mean libvips and libheif don't work together?
**alex991230@alex-heif-test2:~$ vips --version
vips-8.9.0-Mon Jan  6 14:10:21 UTC 2020
alex991230@alex-heif-test2:~$ vips copy IMG_0344.heic IMG_0344.jpg
VipsForeignLoad: "IMG_0344.heic" is not a known file format**

**Comment by jcupitt** [comment]
Check the output of libvips configure. In the table at the end you should see:

```
accelerate loops with orc: 		yes
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		yes (lcms2)
file import with niftiio: 		yes
file import with libheif: 		yes
file import with OpenEXR: 		yes
file import with OpenSlide:		yes
```

ie. a "yes" next to libheif.

I think you'l have "no", so either libvips has not detected libheif, or it has detected it but your libheif has not been built correctly.

Try:

```
pkg-config libheif --variable builtin_h265_decoder
```

If you see "no", your libheif is missing libde265. You'll need to install that, then rebuild libheif, then try libvips again.

**Comment by alex99123** [comment]
I reinstalled **libde265**, and rebuild libheif.
**alex991230@alex-heif-test2:~$ pkg-config libheif --variable builtin_h265_decoder**
**yes**
libvips configure:
**ICC profile support with lcms:          no**
**file import with niftiio:               no**
**file import with libheif:               yes**
but:
**alex991230@alex-heif-test2:~$ vips copy IMG_0344.heic IMG_0344.jpg**
**VipsForeignSave: "IMG_0344.jpg" is not a known file format**
Did I need to install some packages for JPG files？

**Comment by alex99123** [comment]
I thought libvips was working correctly, convert from heic to jpeg format it perfect
But convert from jpeg to heic:
**alex991230@alex-heif-test2:~$ ls |grep IMG_0344.jpg**
**alex991230@alex-heif-test2:~$ vips copy IMG_0344.heic IMG_0344.jpg**
**alex991230@alex-heif-test2:~$ ls |grep IMG_0344.jpg**
**IMG_0344.jpg**
**alex991230@alex-heif-test2:~$ vips copy IMG_5864.JPG IMG_5864.heic**
**VipsForeignSave: "IMG_5864.heic" is not a known file format**

**Comment by jcupitt** [comment]
Yes, you are missing libde265. This is the library that libheif uses for decode. 

Install that, rebuild libheif, then rebuild libvips.

**Comment by alex99123** [comment]
I think I've installed libde265 correctly
**alex991230@alex-heif-test2:~$ pkg-config libheif --variable builtin_h265_decoder**
**yes**
**file import with libheif: 		yes**
**file import with libjpeg: 		yes**
I have finished installing after your previous reply

**Comment by jcupitt** [comment]
Oh, great! So is it working now?

**Comment by alex99123** [comment]
I can convert images from heic format to JPG format. @jcupitt 
like this:
**alex991230@alex-heif-test2:~$ vips copy IMG_0344.heic IMG_0344.jpg**
**alex991230@alex-heif-test2:~$ ls |grep IMG_0344.jpg**
**IMG_0344.jpg**

But I can't convert the image from JPG to heic
**alex991230@alex-heif-test2:~$ vips copy IMG_5864.JPG IMG_5864.heic**
**VipsForeignSave: "IMG_5864.heic" is not a known file format**

**Comment by jcupitt** [comment]
Converting to HEIC needs libx265, perhaps you are missing that?

If it is missing, you'll need to build it, rebuild libheif, and then rebuild libvips.

**Comment by alex99123** [comment]
This is my output:
**alex991230@alex-heif-test2:~$ pkg-config libheif --variable builtin_h265_decoder**
**yes**
At the same time I can convert images from heic format to JPG format. 
So I think my libde265 should be working

**Comment by jcupitt** [comment]
libde265 is the decoder, libx265 is the encoder. You need the encoder to create HEIC images.

Try:

```
pkg-config libheif --variable builtin_h265_encoder
```

**Comment by alex99123** [comment]
Oh, great! Everything is working.
Thanks a lot for taking the time to explain! @jcupitt

**Comment by jvence** [comment]
Is there any Dockerfile that builds libvips with HEIC support on Ubuntu or Amazon Linux?

**Comment by jcupitt** [comment]
On Ubuntu 20.04, Just install `libheif-dev`:

https://github.com/jcupitt/docker-builds/blob/master/libvips-ubuntu20.04/Dockerfile

On previous ubuntus it's tricker since the bundled libheif is too old.

**Comment by jvence** [comment]
Thanks for your help. I'm desperate! 
I get the following error:

> > Sending build context to Docker daemon   2.56kB
> Step 1/11 : FROM ubuntu:focal
>  ---> f63181f19b2f
> Step 2/11 : ENV DEBIAN_FRONTEND=noninteractive
>  ---> Running in 57424a4d6176
> Removing intermediate container 57424a4d6176
>  ---> 7dc034c3abc5
> Step 3/11 : RUN apt-get update
>  ---> Running in 7596020bfea1
> Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
> Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
> Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
> Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
> Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
>   At least one invalid signature was encountered.
> Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
>   At least one invalid signature was encountered.
> Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
>   At least one invalid signature was encountered.
> Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
>   At least one invalid signature was encountered.
> Reading package lists...
> W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
> E: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
> W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
> E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
> W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
> E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
> W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
> E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
> The command '/bin/sh -c apt-get update' returned a non-zero code: 100

**Comment by jcupitt** [comment]
We shouldn't clutter up this old issue. Please open a new one.
