### ISSUE TITLE
8.9.0 ABI compatibility

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#1513]
See [abi-compliance-checker ](https://rpms.remirepo.net/compat_reports/libvips/8.8.4_to_8.9.0-rc4/compat_report.html)result

At least the change on `vips__seek` may require a new soname.

**Comment by remicollet** [comment]
Also issue with `vips_mapimage,` reported in added symbols (present in headers), but not exported (objdump)

P.S. also not found in sources

**Comment by jcupitt** [comment]
Hi Remi, vips__seek is supposed to be internal API (hence the double underscore), so I was hoping that was OK.

`vips_mapimage()` is a stupid error on my part, I'll remove it.

Thanks for checking!

**Comment by remicollet** [comment]
if private, will be nice to not expose them (headers, and ABI)   ;)

**Comment by remicollet** [comment]
Same thing for structs ( _VipsArea, _VipsBlob...) if private, will be nice to be moved to some "private" header, and only obscure struct used in public API

**Comment by jcupitt** [comment]
Yes, Area, Blob etc. are opaque, though you can cast them to each other. 

I think glib has some stuff now for making opaque structs a little simpler, perhaps we should use that.

**Comment by lovell** [comment]
On a related note, it looks like the current [VIPS_SONAME](https://github.com/libvips/libvips/blob/master/libvips/include/vips/soname.h) value of 42 has been in use since v8.5.1. Perhaps we could do something to link this numeric soname suffix with the value of [LIBRARY_CURRENT](https://github.com/libvips/libvips/blob/master/configure.ac#L40)?

**Comment by jcupitt** [comment]
The `42` is the libtool ABI number, so it hasn't changed since (as you say) the 8.0 ABI finally stabilized.

It's not supposed to be directly related to the major.minor.micro version numbers.

**Comment by jcupitt** [comment]
OK, I think this is done (though the opaque struct stuff is not).

**Comment by kleisauke** [comment]
FWIW, here's a list of internal symbols that still needs to be exposed:
https://gist.github.com/kleisauke/72a15e33ae51a4ff30acc3bcf37e5f34

I noticed this while trying to fix the symbol visibility on Windows. See for example commit https://github.com/kleisauke/libvips/commit/f86c4ddda2ec9aa47bd9a0f3d7dca2f659cb6936 and https://github.com/kleisauke/libvips/commit/fba4a76c3855a399a91ea771d8eaa9f6606b41d3.

**Comment by kleisauke** [comment]
I just opened draft PR https://github.com/libvips/libvips/pull/2688 for this. Any testing would be great.
