### ISSUE TITLE
autorot spits out VIPS-WARNING **: can't remove metadata "orientation" on shared image on 8.9.0-rc

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1515]
When using `autorot` vips (on the CLI as also via library) reports a warning:

```
$ vips autorot someimage.jpeg  foo.jpg
(vips:14853): VIPS-WARNING **: can't remove metadata "orientation" on shared image
```

**Comment by jcupitt** [comment]
You're right, there was a copy missing. It seems to work for me now.

Thanks for reporting this!

**Comment by chregu** [comment]
Looks fine now to me

**Comment by chregu** [comment]
Found another one, when `autorotate=true` is set on loading and there are orientation exif tags.

```
$ vipsthumbnail  200x100-orientation-left.jpg[autorotate=true]

(vipsthumbnail:1482): VIPS-WARNING **: can't remove metadata "orientation" on shared image
(vipsthumbnail:1482): VIPS-WARNING **: can't remove metadata "exif-ifd0-Orientation" on shared image
```

with an image like this:
![200x100-orientation-left](https://user-images.githubusercontent.com/47106/71872378-86e19f00-311c-11ea-9509-b664d32d534a.jpg)

**Comment by jcupitt** [comment]
Ooop, you're right, I'll fix it.

**Comment by jcupitt** [comment]
It should be working now. There was a similar issue with tif orientation.

**Comment by chregu** [comment]
Looks fine now, thanks a lot.
