### ISSUE TITLE
LibJpeg: Improper call to JPEG library in state 0

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1517]
When I convert the **tiff file to png**, I get the following warnings and error:

```
(bimg:24): VIPS-WARNING **: 12:59:21.306: Depreciated and troublesome old-style JPEG compression mode, please convert to new-style JPEG compression and notify vendor of writing software

(bimg:24): VIPS-WARNING **: 12:59:21.307: error in tile 0 x 1

(bimg:24): VIPS-WARNING **: 12:59:21.307: error in tile 0 x 2
```
---
```
Error: LibJpeg: Improper call to JPEG library in state 0
tiff2vips: read error
vips2png: unable to write to buffer
```

Since its a customer tiff file, I wont be able to share the file here :(
The above error is thrown when the tiff file is converted to png

## Details

Libvips version: `8.8.3`

Running libvips on alpine `v3.9`

We use [bimg](https://github.com/h2non/bimg) to talk to `libvips`

**Note**: I have checked the libtiff config for enablement of supporting old-styled JPEG

**Comment by jcupitt** [comment]
Sorry, I don't think libvips will work with these old images.

You could try converting to new-style jpeg using imagemagick:

```
convert old-style-jpeg-compression.tif new.tif
```

**Comment by revathi-murali** [comment]
Is there any other alternative to imagemagick?

**Comment by jcupitt** [comment]
GraphicsMagick perhaps?

**Comment by revathi-murali** [comment]
Sorry, we have got rid of `imagemagick` and `graphicsmagick` and started using `libvips`. Hence we can't go back and use them again. Is there any way to convert to new style jpeg via `libvips` or `libtiff`?

**Comment by jcupitt** [comment]
Note that libtiff does not handle these images either:

```
$ tiffcp old-style-jpeg-in-tiff.tif x.tif
TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered.
tiffcp: old-style-jpeg-in-tiff.tif: Can't copy/convert subsampled image.
```

libvips would need extra code added to be able to handle these things. I would be happy to accept a PR.

**Comment by revathi-murali** [comment]
Okay thanks for the explanation
