### ISSUE TITLE
higher precision reduce

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1518]
The vector path currently uses a 16 x 16 -> 32 mul followed by a shift. We should experiment with 32 x 32 -> top 32 of 64. We could use the same precision as the C path.

See:

https://github.com/libvips/pyvips/issues/148#issuecomment-570721063

Similarly for the conv vector path.

**Comment by homm** [comment]
> The vector path currently uses a 16 x 16 -> 32 mul followed by a shift

It's not clear for me how this fits in the previous statement «2.6 bits for the coefficients, 10.6 for the accumulator». 16 x 16 -> 32 is totally enough for 8-bit sources, while «2.6 bits for the coefficients» is not.
