### ISSUE TITLE
[RFE] build heic support as a plugin

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#1519]
RFE Open for discussion

I notice libvips have some support for plugins

Would it be possible to make **heic** support a plugin ?

Context: as there still patent issue with llibheif and its dependency, it is not possible to include it in some distribution (Fedora, RHEL, CentOS...), or, only in some alternative repository (e.g. RPMFusion)

For now, I have to build 2 set of packages (in my repository)
- **vips** (without heic support)
- **vips-full** (with heic support and dependency on libheif from RPMfusion)

So user have the choice, but each set of packages create conflicts with the other (by design, only one can be installed)

Official repopsitories will **never** be able to provide heic support.

So, it would be nice, to be able to build heic as a plugin, which can be distribute in a separate (optional) packages, so
- **vips** (library)
- **vips-devel**
- **vips-doc**
- **vips-tools** (CLI command)
- **vips-heic** (requiring vips main package)
- ...

This will make downstream packager life a bit easier

Notice, this is what is done for ImageMagick (ImageMagick, ImageMagick-djvu, ImageMagick7-heic...)

**Comment by jcupitt** [comment]
Hi Remi, there's actually an issue already for this:

https://github.com/libvips/libvips/issues/1141

Please add a note to that about how useful it would be for packaging.

Perhaps something for 8.10.

**Comment by jcupitt** [comment]
I linked this note from #1141, let's continue discussion there.
