### ISSUE TITLE
Thumbnail gets not generated

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1520]
Hello
I am writing because I don't understand something with creating thumbnails :) It would be super cool, if someone can help me out, so in future I know why such things happen :)

We are using libvips 8.9
when I try to create a thumbnail out of this image with following arguments:

```
--rotate --eprofile=/path/to/srgb.icc --smartcrop=attention -s 240 image1.jpg -o image1.jpg[optimize_coding,strip]"}
```

it is failing... no thumbnail generated.

when I try to create it withouth the `--eprofile` it is working with no problem...

```
--rotate --smartcrop=attention -s 240 image1.jpg -o image1.jpg[optimize_coding,strip]"}
```

So many thanks if someone can give me a hint...

![000000063030 (1)](https://user-images.githubusercontent.com/942990/72064801-f8684b80-32dc-11ea-8b95-6e03c1957572.jpg)

**Comment by jcupitt** [comment]
Hello @daverupp ,

I tried your image here. I see:

```
$ vipsthumbnail dog.jpg --rotate --eprofile=srgb --smartcrop=attention -s 240 -o image1.jpg[optimize_coding,strip]
(vipsthumbnail:3876): VIPS-WARNING **: 12:39:21.960: profile incompatible with image
vipsthumbnail: unable to thumbnail dog.jpg
icc_transform: no input profile
```

(libvips has a high-quality built-in srgb profile, you can just use "srgb" to select it)

The problem is that your image has a profile embedded in it, but that profile is incompatible with the image. I guess it's left over from an earlier version of the file. 

By giving an export profile, you've asked vipsthumbnail to transform to sRGB, but there's no source profile for it to use, so it can't.

If you also supply an import profile, you can override the profile on the image:

```
$ vipsthumbnail dog.jpg --rotate --iprofile=/usr/share/color/argyll/ref/ClayRGB1998.icm --eprofile=srgb --smartcrop=attention -s 240 -o image1.jpg[optimize_coding,strip]

(vipsthumbnail:4065): VIPS-WARNING **: 12:44:26.412: profile incompatible with image
```

There's still a warning, but there is now a thumbnail image. 

![image1](https://user-images.githubusercontent.com/580843/72068930-ffdc2480-32dd-11ea-86c0-c7992c59c2f4.jpg)

**Comment by daverupp** [comment]
Thank you very much for taking the time to answer... 

this whole --eprofile thingy is a little tricky :) before we switched to the new 8.9 version we were using this profile: sRGB_v4_ICC_preference.icc

Is there a risk, just to leave the --eprofile parameter away? has this other side effects?

to avoid failing thumbnails in the future with also old or incompatible profile, can I set the --iprofile also globally to srgb.icc ?

thanks again for some hints about this topic :)

**Comment by jcupitt** [comment]
I think I would use the built-in libvips profile. You can see it here:

https://github.com/libvips/libvips/tree/master/libvips/colour/profiles

It's free and high-quality.

Profiles are important if you want to handle source images in strange colourspaces, like Adobe 98 or CMYK. If you don't have to deal with images like that, then just skip the whole mess.

**Comment by daverupp** [comment]
Difficult to say. I contribute as a developer, where we provide a cloud backup solution to users to backup their photos... and provide them with thumbnails when they are accessing them online.

**Comment by jcupitt** [comment]
Then I think CMYK images would be very unlikely.

I would do:

```
vipsthumbnail $user_input_file --rotate \
    --iprofile=srgb --eprofile=srgb --smartcrop=attention \
    -s 240 -o $thumbnail_file[optimize_coding,strip]
```

* Images with correct profiles will be transfomed to srgb, including CMYK images
* RGB images with broken profiles (like your dog pic) will not have their colour changed
* CMYK images with broken or missing profiles will fail

The last one should be rare, hopefully. I guess you should display a generic "this is an image" thumbnail in that case.

**Comment by daverupp** [comment]
Super... thx a lot for your help
Kind regards, and thank you very much for your hard work!
