### ISSUE TITLE
vips c error handling 

### ISSUE THREAD

**Issue by dineshkannaa** [libvips/libvips#1522]
Hi John,

> vips version : vips-8.7.0-Fri Aug 31 14:11:19 UTC 2018

Im calling VIPS API for thumbnail generation from Java using JNI . In some cases segmentation fault error occurs , which crashes the server . Im not able to reproduce the case .  Some of the traces are 

![1](https://user-images.githubusercontent.com/23660986/72153929-3f396c80-33d5-11ea-8073-21f38dcf3686.png)
![2](https://user-images.githubusercontent.com/23660986/72153948-49f40180-33d5-11ea-8452-857f6ac73422.png)
![3](https://user-images.githubusercontent.com/23660986/72153954-4eb8b580-33d5-11ea-8ae7-860774c5b85b.png)

Im thinking of handling the segmentation fault by signal handler . Is it advisable ? Any idea on how to handle this ?

**Comment by jcupitt** [comment]
Hello dinesh, I would update your libvips.

We joined OSS Fuzz in August 2019 and the versions since then have had a few crash fixes. It should be more robust now.

https://github.com/libvips/libvips/releases

**Comment by dineshkannaa** [comment]
Thank you. Will update and check .
