### ISSUE TITLE
vips_autorot() and vips_thumbnail_image() cancel each other out on 8.9.0

### ISSUE THREAD

**Issue by janko** [libvips/libvips#1523]
I've seen in 8.9.0 release notes that libvips has introduced a backwards incompatible change regarding metadata modification. This has caused an issue with auto-rotation in the ImageProcessing ruby gem, described [here](https://github.com/janko/image_processing/issues/64#issuecomment-573404816) in more detail.

To summarize, the following ruby-vips code auto-rotated the result image on 8.8.4, but on 8.9.0 it produces a rotated image (no auto-rotation applied):

```rb
require "vips"

Vips::Image.new_from_file("/path/to/rotated.jpg")
  .autorot
  .thumbnail_image(400)
  .write_to_file("/path/to/destination.jpg")
```

The reason why ImageProcessing gem ends up executing this code is that it doesn't know which combination of operations the user will apply. It calls `vips_autorot()` by default after loading the image to ensure the image is auto-rotated before any operations (which might or might not include `vips_thumbnail_image()`).

The ImageProcessing gem does resize-on-load with `vips_thumbnail()` when it can, but if the user has specified format-specific loader options, those cannot be passed to `Vips::Image.thumbnail` so in that case it has to use `vips_thumbnail_image()` instead.

If I don't call `vips_autorot()` or pass `no_rotate: true` to `vips_thumbnail_image()`, the auto-rotation works correctly.

My question is, is it possible to make `vips_autorot()` and `vips_thumbnail_image()` work together on 8.9.0, or was this change of behaviour by design? FYI, this code does produce the metadata modification warnings, which I managed to remove with `Vips.vips_cache_set_max 0`, but the result is still the same.

**Comment by jcupitt** [comment]
Hi @janko, thanks for testing this.

Your autorot example looks like a libvips bug, I'll fix it. Thanks for reporting this! I can reproduce it like this:

```
$ vips thumbnail x.jpg z.jpg 400
(vips:5582): VIPS-WARNING **: 13:53:18.058: can't remove metadata "orientation" on shared image
(vips:5582): VIPS-WARNING **: 13:53:18.058: can't remove metadata "exif-ifd0-Orientation" on shared image
```

Where `x.jpg` is an orientation 6 image.

As you say, doing autorot before thumbnail will absolutely kill performance. `thumbnail` will autorotate by default (it does it right at the end, so it only rotates the thumbnail) so (I think?) you shouldn't need to do this.

**Comment by jcupitt** [comment]
I think that should have fixed it. I added a test for this case too.

As I said, `thumbnail` should autorotate by default, so I think you can remove `autorot` from ImageProcessing. There's a `no-rotate` option to block autorot if you need to.

**Comment by jcupitt** [comment]
Oh wait, sorry, I'm confused.

Could you explain again why you need to call `autorot` before `thumbnail`? It would be great if we could find some way to avoid this.

**Comment by janko** [comment]
Thank you for helping me with this 🙏 

Let's say we have the following ImageProcessing code:

```rb
ImageProcessing::Vips
  .source("/path/to/rotated.jpg")
  .loader(fail: true)
  .resize_to_limit(400, 400)
```

which generates the following options:

```rb
{:source=>"/path/to/rotated.jpg",
 :loader=>{:fail=>true},
 :saver=>{},
 :format=>nil,
 :operations=>[[:resize_to_limit, [400, 400]]],
 :processor=>ImageProcessing::Vips::Processor}
```

An ImageProcessing "pipeline" object takes these options, and calls a series of "processor" operations based on these options. A "processor" is an abstraction that implements operations using a specific image processing library – there are both libvips and ImageMagick implementations in ImageProcessing. The processor doesn't know about the options above, it only applies operations it's told to.

Normally, to load the image, `Image.thumbnail` is used if `resize_*` is detected as a first operation. However, if there are also `loader` options specified, `Image.new_from_file` & `Image#thumbnail_image` are used instead, because `Image.thumbnail` doesn't accept format-specified loader options (such as `:fail` in our example).

The processor implements a `.load_image` method, which is called when we're *not* using resize-on-load, and it calls `Image.new_from_file` together with `Image#autorot` to ensure the image is auto-rotated. Since the processor doesn't have knowledge of all processing options, the `.load_image` processor method doesn't know whether there will be a subsequent `resize_*` operation that will call `vips_thumbnail()` and auto-rotate the image – the user might not want to resize the image at all – so it calls `Image#autorot` to ensure the image is auto-rotated before any subsequent operations.

The "pipeline" object that decides which processor operations to call deals with abstractions, so it it's hard for it to make a special case for libvips (as the same isn't needed for ImageMagick).

However, we can use the `no_rotate` option you mentioned for the `thumbnail_image` operation. It might introduce a backwards incompatibility in some unusual configurations, but that behaviour makes more sense to me in general. When `thumbnail` is used (resize-on-load), in that case `autorot` isn't being called anyway, so there we'll leave `thumbnail` to auto-rotate.

Sorry if I went too much in detail, but it helped me figure out the course of action 😃 I don't think anything else needs to be done on the libvips side, thanks again for the help 👍

**Comment by jcupitt** [comment]
Hmm I think I see! 

(tangent: if you `autorot` before `thumbnail_image`, you don't need `no_rotate` since the `autorot` will always have stripped any orientation tag)

Thinking about this again, my instinct would be that the performance difference is so stark that anything that does not have thumbnail first is essentially broken and should not be possible. JPG is the easy case -- what about PDF or SVG? There you /must/ rasterize to the correct resolution or, as well as bad performance, you'll get poor quality.

ImageMagick supports all this stuff too, through via a more manual route, and allowing pipelines without thumbnail first means the ImageMagick backend will also be unable to make this (almost) essential optimization.

**Comment by jcupitt** [comment]
Also, I'm sorry about this breaking change :( I've caused extra work.

**Comment by janko** [comment]
> (tangent: if you autorot before thumbnail_image, you don't need no_rotate since the autorot will always have stripped any orientation tag)

Yeah, this was the behaviour prior to 8.9.0, that's why I didn't bother with disabling auto-rotation for thumbnailing before, but in 8.9.0 it seems this wasn't the case anymore. That's what I wanted to check in this issue, whether this change was intended or not, but in https://github.com/libvips/libvips/issues/1523#issuecomment-573420884 you suggested it might be problematic to call both and have them work together. Or is this what https://github.com/libvips/libvips/commit/34fcd1fe69e3ea48e8e10cfa5bae8b388a49ffb4 fixes?

Thanks for reminding me again of the importance of resize-on-load. I actually just found out that you can still pass loader options even if using resize-on-load, via the filename string:

```rb
Vips::Image.thumbnail("/path/to/source.jpg[foo=bar]", ...)
```

This means ImageProcessing gem can use resize-on-load even when user specified loader options. The only time it cannot be used is if the user applied some operations before resizing, but we could potentially print a warning for those use cases 🤔

------

However, there is one common use case where I found using resize-on-load to be challenging – **image cropping**. The frontend would send the cropping coordinates scaled to original dimensions the backend, so in that case I want to apply cropping *before* resizing, to maintain accuracy of the cropping points to not have to worry about correctly scaling the numbers down for each thumbnail.

In a [Shrine demo application](https://github.com/shrinerb/shrine-crop-example/blob/f78924ebb9daf7acfd37c5179b155af5e10b912b/uploaders/image_uploader.rb#L29-L34) I used the following approach:

```rb
THUMBNAILS = {
  square: [150, 150],
  small:  [300, 300],
  medium: [600, 600],
  large:  [500, 500],
}

THUMBNAILS.transform_values do |(width, height)|
  thumb = Tempfile.new %w[thumb .jpg]

  Vips::Image.new_from_file("/path/to/source.jpg")
    .crop(params.values_at(:left, :right, :width, :height)) # params coming from the frontend
    .thumbnail_image(width, height: height, size: :down) # no resize-on-load
    .write_to_file(thumb.path)

  thumb
end # => { square: ..., small: ..., medium: ..., large: ... }
```

I guess the following might be a better alternative, which utilizes resize-on-load:

```rb
THUMBNAILS = {
  square: [150, 150],
  small:  [300, 300],
  medium: [600, 600],
  large:  [500, 500],
}

cropped = Tempfile.new %w[cropped .jpg]

Vips::Image.new_from_file("/path/to/source.jpg")
  .crop(params.values_at(:left, :right, :width, :height))
  .write_to_file(cropped.path)

THUMBNAILS.transform_values do |(width, height)|
  thumb = Tempfile.new %w[thumb .jpg]

  Vips::Image.thumbnail(cropped.path, width, height: height, size: :down)
    .write_to_file(thumb.path)

  thumb
end # => { square: ..., small: ..., medium: ..., large: ... }
```

Is the second approach more performant due to usage of resize-on-load?

> Also, I'm sorry about this breaking change :( I've caused extra work.

That's really ok, so many people including me benefit from your work, I'm ok doing some fixing if I understand the rationale 😉

**Comment by jcupitt** [comment]
Hi again Janko,

<blockquote>
That's what I wanted to check in this issue, whether this change was intended or not, but in #1523 (comment) you suggested it might be problematic to call both and have them work together. Or is this what 34fcd1f fixes?
</blockquote>

You can have both, but it'll be really slow, since you're not using `thumbnail`. And quality will be bad if you're resizing PDF or SVG.

Re. cropping: I would crop after thumbnail, so rescale the coordinates to the downsized image. I'd think it should be straightforward to do this accurately: just round the top left and bottom right corners to the nearest pixel.

I offered rubyday Verona a talk and they've turned me down! Tsh. Were you looking at that one?

**Comment by janko** [comment]
> You can have both, but it'll be really slow, since you're not using thumbnail. And quality will be bad if you're resizing PDF or SVG.

The reason the example wasn't using `thumbnail` is not because of `autorot`; when ImageProcessing gem detects that resize-on-load is possible, it just calls `thumbnail` directly without problem. The `autorot` was being added only when ImageProcessing decided resize-on-load was not possible (for other reasons), and that's just to account for cases when no resizing is being done during processing.

My question was just referring to whether the behaviour will be *correct* if we use both `autorot` and `thumbnail_image` ("correct" = no double-rotate). This was the case 8.8.4, but not on 8.9.0 (`autorot` might not have stripped the orientation tag). In fact, when I execute the following code for an image with orientation 6:

```rb
require "vips"
require "tempfile"

result = Tempfile.new %w[result .jpg]

image = Vips::Image.new_from_file("path/to/rotated.jpg")
image = image.autorot

image.write_to_file(result.path)

p Vips::Image.new_from_file(result.path).get("orientation")
```

* On 8.8.4: The image is successfully rotated and orientation is `1`
  - when I inspect `image.get("orientation")` after `autorot`, an exception is raised saying the `orientation` field doesn't exist (meaning it was stripped 👍 )
* On 8.9.0: The image is successfully rotated but the orientation *remains* `6`.
  - when I inspect `image.get("orientation")` after `autorot`, I get `6`

I believe this was the regression that was causing the bug in ImageProcessing.

**Comment by janko** [comment]
> I offered rubyday Verona a talk and they've turned me down! Tsh. Were you looking at that one?

Yes, I had actually applied to this conference as well, and to my positive surprise I was accepted! 😃 I'm sorry that you weren't, and that I might have taken your spot 😛, I would love to see libvips talked about more in the Ruby community. What was the topic of your talk?

**Comment by jcupitt** [comment]
Ah OK, I'm being dumb, sorry. Yes, it should be safe in 8.9.1 to do `autorot` then `thumbnail_image`. It was buggy in 8.9.0.

**Comment by jcupitt** [comment]
I was planning to talk about how to get the most from ruby-vips, and a little about the history of the library and how it works (but only a bit).

Yes, I think we would have made an interesting pair of talks, and it would have been good to meet. Some other time!
