### ISSUE TITLE
Error: not one band or 4 bands when joining images

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1525]
## Background
We have a usecase of converting multipage tiff to png where the input tiff file can have multi-pages with each page differing in width and height. Since libvips does not have the support to convert multipage tiff(that differs in width & height) to png, we convert each page in tiff file to png and then join the pngs. 

## Issue
So for one of the customer file, we get the following error using `arrayjoin` or `join`

```
vips arrayjoin "yc_page_1.png yc_page_2.png" yc_whole.png --across 1
arrayjoin: not one band or 4 bands
```

```
vips join yc_page_1.png yc_page_2.png yc_whole.png vertical
insert: images must have the same number of bands, or one must be single-band
```

Is there any workaround of fix for the same?

**Comment by jcupitt** [comment]
It sounds like you have a mix of G, GA, RGB and RGBA PNGs.

You need to pick a format for output (perhaps RGBA?) and convert all the images to that format before joining them.

**Comment by jcupitt** [comment]
In Python for example, something like:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
n_pages = image.get("n-pages")

def load_page(filename, i):
    page = pyvips.Image.new_from_file(filename, page=i, access="sequential")
    # mono -> rgb
    if page.bands < 3:
        page = page.colourspace("srgb")
    # make sure there's an alpha
    if page.bands == 3:
        page = page.bandjoin(255)

    return page

image = load_page(sys.argv[1], 0)
for i in range(1, n_pages):
    page = load_page(sys.argv[1], i)
    image = image.insert(page, 0, image.height, expand=True)

image.write_to_file(sys.argv[2])
```

**Comment by revathi-murali** [comment]
Thanks for the sample code. I will try and update you the result.

**Comment by revathi-murali** [comment]
I tried following the same approach but now I get `linear: vector must have 1 or 4 elements`. Am I missing something?

**Comment by jcupitt** [comment]
Sorry, no idea, post a sample image and the code that produces the error.

**Comment by revathi-murali** [comment]
I am using `arrayjoin` instead of `insert` and here is the code:
```
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
n_pages = image.get("n-pages")

def load_page(filename, i):
    page = pyvips.Image.new_from_file(filename, page=i, access="sequential")
    # mono -> rgb
    if page.bands < 3:
        page = page.colourspace("srgb")
    # make sure there's an alpha
    if page.bands == 3:
        page = page.bandjoin(255)

    return page

page = []
for i in range(0, n_pages):
    page.append(load_page(sys.argv[1], i))

image = pyvips.Image.arrayjoin(page, across=1, background=[255.0, 255.0, 255.0])

image.write_to_file(sys.argv[2])
```

So you recommend using `insert` and not `arrayjoin`?

**Comment by jcupitt** [comment]
I think that's fine, `arrayjoin` is a good choice. 

Try setting the background to `[255, 255, 255, 255]`, ie. 4 values for RGBA.

**Comment by jcupitt** [comment]
Or you can just use `background=255`, of course.

**Comment by revathi-murali** [comment]
Thanks. Can you explain me a bit on why adding an alpha channel solved the issue? I had a 2 page tiff file which when converted to pngs had 4 bands and 3 bands respectively. Joining failed because of the difference in the bands. So when we added an alpha channel to the 3-band png, join worked (because it now became 4 bands). So that means when joining images all should be of same bands?

**Comment by jcupitt** [comment]
Hello, sorry, I forgot to answer.

Yes, `arrayjoin` just pastes images together. It does some conversions, so it'll turn one band images into N band images, but it doesn't try to move all the images to a common colourspace, or add alphas.

The much more complex `composite` operator does do all that extra work, but it blends pixels, so it has to.

**Comment by int-ua** [comment]
ImageMagick workaround:
`$ convert image.png png32:image.png`

**Comment by jcupitt** [comment]
You can also use `colourspace` to move all of the inputs to a common colourspace for compositing. For example:

```python
image = image.colourspace('srgb')
```

**Comment by sergeevabc** [comment]
Dear @jcupitt,
I have 4 PNG [screenshots](https://github.com/user-attachments/files/20085397/2025-0507-1646.vips.join.png.zip) to combine. Usually I do it via `vips array 1.png 2.png 3.png 4.png out.png vertical`, but it does not work this time . Either VIPS 8.15.1 on Windows 7 x64 says `mages must have the same number of bands, or one must be single-band` or `enum 'VipsDirection' has no member '4.png', should be one of: horizontal, vertical`.

**Comment by sergeevabc** [comment]
@jcupitt 

``` console
$ vips arrayjoin "1.png 2.png 3.png 4.png" out.png --across 1
arrayjoin: not one band or 4 bands
```
