### ISSUE TITLE
dzsave is "Killed"

### ISSUE THREAD

**Issue by Mamikon95** [libvips/libvips#1526]
Hi, I have such an error, in the Linux system in the terminal when vips dzsave breaks in half and writes * Killed *. dmesg leads out of memory. What can i do?

**Comment by jcupitt** [comment]
Hello @Mamikon95,

That means the linux kernel has killed the vips process to try to rescue your system from memory exhaustion.

vips should not usually need that much memory for dzsave. Could you post some more information:

- code you ran
- image you ran on (just the dimensions and type)
- vips version
- platform version

**Comment by Mamikon95** [comment]
> Hello @Mamikon95,
> 
> That means the linux kernel has killed the vips process to try to rescue your system from memory exhaustion.
> 
> vips should not usually need that much memory for dzsave. Could you post some more information:
> 
> * code you ran
> * image you ran on (just the dimensions and type)
> * vips version
> * platform version

Yes

- vips dzsave test.svs library/test/ --suffix .jpg --vips-progress
- type .svs size is 400mb
- vips version - vips-8.8.4-Thu Dec  5 16:24:34 UTC 2019
- Operating System: CentOS Linux 7 (Core) Kernel: Linux 2.6.32-042stab141.3  Architecture: x86-64

**Comment by jcupitt** [comment]
Huh, weird, that shouldn't need much memory.

For example, I see:

```
$ /usr/bin/time -f %M:%e vips dzsave CMU-2.svs x --vips-progress
vips temp-1: 78000 x 30462 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
vips temp-1: done in 67.9s          
660844:67.95
```

ie. 68s of time and 660MB of memory to process the 370mb sample SVS here:

http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/

Do you know how much memory the process is using before it is killed?

**Comment by Mamikon95** [comment]
> Huh, weird, that shouldn't need much memory.
> 
> For example, I see:
> 
> ```
> $ /usr/bin/time -f %M:%e vips dzsave CMU-2.svs x --vips-progress
> vips temp-1: 78000 x 30462 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
> vips temp-1: done in 67.9s          
> 660844:67.95
> ```
> 
> ie. 68s of time and 660MB of memory to process the 370mb sample SVS here:
> 
> http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/
> 
> Do you know how much memory the process is using before it is killed?

/usr/bin/time -f %M:%e vips dzsave scripts/vips/tmp/3020-29_2016-002_2.svs svs_library/test/ --suffix .jpg --vips-progress        
vips temp-1: 44743 x 41057 pixels, 2 threads, 44743 x 1 tiles, 128 lines in buffer
227680:8.27: 12% complete

**Comment by Mamikon95** [comment]
@jcupitt Can't set an upper memory limit? so that the script works forcibly?

**Comment by jcupitt** [comment]
Sorry, I don't understand, an upper limit to what?

**Comment by Mamikon95** [comment]
> Sorry, I don't understand, an upper limit to what?

memory. Or what can i do, in order the script not be killed?

**Comment by jcupitt** [comment]
You can turn off threading to save a little memory, but of course it's slower:

```
$ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e vips dzsave CMU-2.svs x --vips-progress
vips temp-1: 78000 x 30462 pixels, 1 threads, 128 x 128 tiles, 128 lines in buffer
vips temp-1: done in 184s          
499996:183.97
```

500mb of memory and 180s.

Otherwise you'll just have to get more RAM. 220MB is very small. 

What's `ulimit -m`? Perhaps you could raise that.

**Comment by Mamikon95** [comment]
> You can turn off threading to save a little memory, but of course it's slower:
> 
> ```
> $ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e vips dzsave CMU-2.svs x --vips-progress
> vips temp-1: 78000 x 30462 pixels, 1 threads, 128 x 128 tiles, 128 lines in buffer
> vips temp-1: done in 184s          
> 499996:183.97
> ```
> 
> 500mb of memory and 180s.
> 
> Otherwise you'll just have to get more RAM. 220MB is very small.
> 
> What's `ulimit -m`? Perhaps you could raise that.

Thank you, I rebooted the server to free up memory now fine))
but I'm afraid that if 50 dzsave will work right away, then many will killed ((

**Comment by jcupitt** [comment]
Sure, you always need to throttle things like this.

I usually have a table in my database for jobs. When a user starts a job going, the code on the page appends a row with all the parameters. A background process waits for rows to appear and executes them one at a time. As each task finishes, it deletes the row from the jobs table and appends a new row with all the results to another table called completed-jobs.

It's very simple (just a few lines of bash), you don't need any locking, and it's simple to expose to users somehow.

**Comment by Mamikon95** [comment]
> Sure, you always need to throttle things like this.
> 
> I usually have a table in my database for jobs. When a user starts a job going, the code on the page appends a row with all the parameters. A background process waits for rows to appear and executes them one at a time. As each task finishes, it deletes the row from the jobs table and appends a new row with all the results to another table called completed-jobs.
> 
> It's very simple (just a few lines of bash), you don't need any locking, and it's easy to expose to users eg. via a "jobs" page.

thanks!
