### ISSUE TITLE
Specifying a loader on vips_thumbnail()

### ISSUE THREAD

**Issue by janko** [libvips/libvips#1527]
Hi @jcupitt, after realizing in https://github.com/libvips/libvips/issues/1523#issuecomment-573677765 that `vips_thumbnail()` (i.e. resize-on-load) can still receive loader options via the filename string, I've got into implementing that in the ImageProcessing gem.

Currently, the "loader" options that the user specifies are forwarded to the libvips loader:

```rb
ImageProcessing::Vips
  .source("/path/to/source.jpg")
  .loader(fail: true, ...) # passed to `Vips::Image.new_from_file`
```

However, there is one special option – `:loader` – which forces the loader that will be used, instead of letting libvips guess it ([which is sometimes necessary](https://github.com/janko/image_processing/issues/49)):

```rb
ImageProcessing::Vips
  .source("/path/to/source")
  .loader(loader: :svg) # force using `Vips::Image.svgload`
```

Is it possible to specify the libvips loader when using `vips_thumbnail()`, i.e. `Vips::Image.thumbnail`?

**Comment by jcupitt** [comment]
Sorry, no.

libvips should detect SVG files, I think it would be best to fix that. Do you have an example of a file which fails?

The SVG sniffer is here:

https://github.com/libvips/libvips/blob/master/libvips/foreign/svgload.c#L492

So it checks for first 24 chars are ASCII and "<svg" withing the first 1000 bytes. Do we need to raise that limit?

**Comment by janko** [comment]
My bad, this was already resolved [here](https://github.com/libvips/libvips/issues/1289). Thanks for the reply 😃
