### ISSUE TITLE
How to process bmp pictures with libvips

### ISSUE THREAD

**Issue by LebronCurry** [libvips/libvips#1528]
For example:
vipsthumbnail  test.bmp -s 200x200 -o out.jpg
But it is not available now.

**Comment by jcupitt** [comment]
Hello, libvips uses ImageMagick to load BMP files. It should work, as long as you have IM enabled.

**Comment by LebronCurry** [comment]
Hello, I use this command to compile:
./configure --with-magickpackage=GraphicsMagick 
Then display:
Magick package:            GraphicsMagick
Magick API version:        magick6

But still not:
vipsthumbnail: unable to thumbnail 0002.bmp
VipsForeignLoad: "0002.bmp" is not a known file format

**Comment by jcupitt** [comment]
I guess there's something strange about GraphicsMagick. I'll have a look.

**Comment by jcupitt** [comment]
It seems GM needs to be told to init the various loaders, at least in some configurations.

It seems to work for me now. This improvement will be in 8.9.1. 

Thanks for reporting this!

**Comment by LebronCurry** [comment]
Ok,thank you for your answer.
