### ISSUE TITLE
dzsave iiif layout: Need option to properly set info.json @id from the command line

### ISSUE THREAD

**Issue by regisrob** [libvips/libvips#1531]
Following @atomotic's [comment in #1465](https://github.com/libvips/libvips/issues/1465#issuecomment-552466906), there should be a command-line argument to set the scheme, server domain and optional prefix to be used in the info.json `@id`, instead of the default "https://example.com/iiif/"

See [Image API 2.1](https://iiif.io/api/image/2.1/#technical-properties): the `@id` property of the info.json must be "The base URI of the image as defined in URI Syntax, including scheme, server, prefix and identifier without a trailing slash."

**Comment by jcupitt** [comment]
Hello @regisrob, let's tag these issues as enhancements for 8.10. Thanks for opening them.

**Comment by regisrob** [comment]
Hello @jcupitt, thank you! In any case I think I can go ahead in adding LibVips to the IIIF-Awesome list (see [#286](https://github.com/IIIF/awesome-iiif/issues/286)) 👍

**Comment by jcupitt** [comment]
I added `--id` to dzsave to set the base URL. For example:

```
$ vips dzsave ../k2.jpg x --layout iiif --id https://banana.com
$ more x/info.json 
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://banana.com/x",
...
```

It adds the output directory name to make the full id. Does that look OK?

**Comment by regisrob** [comment]
Thank you @jcupitt, it should be ok like this!

**Comment by jcupitt** [comment]
Great, I'll close. Thanks you for the suggestion.
