### ISSUE TITLE
90 degree dzsave deviation

### ISSUE THREAD

**Issue by Mamikon95** [libvips/libvips#1533]
Hi! I open the scn file in aperio imagescope and there the image is 90 degrees to the left than in openseadragon (after dzsave). How can this problem be solved?

openseadragon - http://prntscr.com/qqy7zr
aperio imagescope - http://prntscr.com/qqy8aw

**Comment by jcupitt** [comment]
You can rotate during save with `dzsave`, try the `angle` argument.

**Comment by Mamikon95** [comment]
> You can rotate during save with `dzsave`, try the `angle` argument.

and if I use "vips openslideload" then in this case how to use "angle" and "autocrop"?

**Comment by jcupitt** [comment]
Use square brackets after the filename. Try:

```
vips openslideload x.svs y.dz[tile_size=512,angle=d90]
```

**Comment by Mamikon95** [comment]
> tile_size=512,angle=d90

Thanks, it works great :)
