### ISSUE TITLE
dzsave with ndpi images

### ISSUE THREAD

**Issue by JuanjoAlegria** [libvips/libvips#1534]
Hi!

I'm trying to convert some .ndpi images to DeepZoom format. For that I'm using the command
`vips dzsave 1.ndpi test`, but I'm running into a memory error. The output is:

> (vips:27027): VIPS-WARNING **: 01:27:09.584: Unknown field with tag 65420 (0xff8c) encountered
(vips:27027): VIPS-WARNING **: 01:27:09.584: Unknown field with tag 65421 (0xff8d) encountered
...(vips:27027): VIPS-WARNING **: 01:27:09.622: Unknown field with tag 65459 (0xffb3) encountered
(vips:27027): GLib-ERROR **: 01:27:09.624: ../glib/glib/gmem.c:135: failed to allocate 51527024640 bytes
`trap' para punto de parada/seguimiento (`core' generado)

I'm also getting the same kind of error with all the others .ndpi images :(

The versions are libvips 8.9.0, openslide 3.4.1, running in Manjaro Linux with kernel 4.14.

Any suggestions?

Thanks!

PD: i'm sorry for my english

**Comment by jcupitt** [comment]
Hi @JuanjoAlegria,

This is a bug in 8.9.0 -- vips does not recognise openslide images correctly. 8.9.1 has a fix and should be out in a few days.

In the meantime, you can force it to recognize openslide images like this:

```
vips openslideload 1.ndpi test.dz
```

**Comment by JuanjoAlegria** [comment]
That command did the trick :D thanks!
