### ISSUE TITLE
Stats about alpha band

### ISSUE THREAD

**Issue by freezy** [libvips/libvips#1535]
I'm using libvips for determining how to blend a texture in a 3D scene. I'm doing that by looking at how many pixels are fully transparent versus only somewhat transparent versus not transparent at all (the resulting blend modes would then be cut-out, transparent and opaque, respectively).

I've been using `vips_hist_find()` and loop through the resulting histogram, which works great. Using `kleisauke/net-vips`, I'm doing something like:

```cs
var hist = image.HistFind(3);
for (var i = 0; i < hist.Width; i++) 
{
	var alpha = (int)hist[i, 0][0];
	// increment counters by alpha depending on what range i is in
}
```

However, while `vips_hist_find()` seems fast, looping through the 256 elements is awfully slow. I suppose the actual histogram is only produced when accessing the result?

I was wondering if a) there was a faster way of doing this, and b) a way to even skip pixels? An approximation by only looking at 1% of all pixels would already be sufficient in my case.

**Comment by jcupitt** [comment]
Hello @freezy,

Yes, reading out pixels with `[]` is incredibly slow. It's not regenerating the histogram each time, it's just the call overhead.

I would write the histogram to memory and turn it into a C# array. You'd need to open a net-vips issue for the details. 

In ruby-vips, for example, it's:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file("/home/john/pics/k2.jpg")
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> x[1].hist_find.to_a
=> [[[6346], [11957], [15024], [14525], [11947],  ....
````

**Comment by jcupitt** [comment]
You could also use `linear`. This makes a ramp histogram (the identity function). 

Use `>128` to make it 0 for histogram entries under 128 and 255 for over, then divide by 255 to get 0 / 1, multiply you alpha hist by that, then take the average. 

In Ruby:

```
irb(main):004:0> mask = (Vips::Image.identity > 128) / 255
=> #<Image 256x1 float, 1 bands, histogram>
irb(main):005:0> (x[1].hist_find * mask).avg * 256
=> 925615.0
```

So 925615 pixels have a value > 128 in band 1.

**Comment by freezy** [comment]
Hi @jcupitt,

Thanks for the quick reply. libvips is awesome and your support is second to none!

I tried the `linear` approach. 33ms versus 314ms with the loop. This is amazing, thanks again!
