### ISSUE TITLE
Is it possible to determine a buffer's format using Vips?

### ISSUE THREAD

**Issue by jhford-scout24** [libvips/libvips#1538]
Hi,

I am trying to use the C API to implement a tool.  One of the things that I need to be able to do is determine which type of image a given buffer is.  I've tried using the `vips_foreign_find_load_buffer`, but that correctly says for a given picture that it'll use ImageMagick as the image loader, or the WebP loader as the loader, not that it's a bmp or a webp file.

I've tried looking at the source and I'm at a loss for how I could do this -- I'm not much of a C developer.  I also don't know where vips discussion occurs, so I'm falling back to here.

Thanks,

John

**Comment by jcupitt** [comment]
Hello @jhford-scout24,

`vips_foreign_find_load_buffer()` is it, I'm afraid. The libvips image type sniffer is just there to pick load operations.

You could try some other things:

- Have a table to map strings like `webpload` to a name your users would recognise, like `WebP`.
- You can make a `VipsObject` of that type and then read out the suffixes, if a filename suffix is useful. You'll get `".webp"` for `webpload`, or `".tif"`, `".tiff"` for `tiffload`, for example.
- You can use `libmagic`: https://linux.die.net/man/3/libmagic ... it has a function called `magic_buffer()` which seems to do what you want.

**Comment by jcupitt** [comment]
And questions here are fine, we use github issues for most things.
