### ISSUE TITLE
Allow to configure vips_pipe_read_limit

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#1540]
It would be nice that the limit for non-seekable streams (e.g. network streams) could be configured:
https://github.com/libvips/libvips/blob/4aeedd971131ee86005e236fe1b6cfdcbd128cd6/libvips/iofuncs/source.c#L718-L723

As users may want to lower this limit (1 GiB is alot). Perhaps we should also make it possible to set -1, which means [no limit](https://www.youtube.com/watch?v=qM5W7Xn7FiA) at all (why not).

See https://github.com/kleisauke/net-vips/issues/33 for context.

**Comment by jcupitt** [comment]
I added `vips_pipe_read_limit_set()`, `--vips-pipe-read-limit`, and an environment variable called `VIPS_PIPE_READ_LIMIT`. You can set -1 too.

Thanks for the reminder!

**Comment by kleisauke** [comment]
No problem! I added 2 small inline comments, but LGTM otherwise.

**Comment by jcupitt** [comment]
I've put your fixes in, let's close.
