### ISSUE TITLE
Remaining loaders/savers to rework for the source/target API

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#1541]
This issue tracks the remaining loaders and savers that might be reworked for the new [source/target API](https://libvips.github.io/libvips/2019/11/29/True-streaming-for-libvips.html). I mostly used [this comment](https://github.com/libvips/libvips/pull/1443#issuecomment-552190631) as reference. Feel free to add more information in the comments.

| Image suffix(es)       | Loader                 | Saver                   | Finished                           | 
|------------------------|----------------------- |-------------------------|:----------------------------------:|
| .gif                   | [gifload]<sup>1</sup>  | [magicksave]<sup>2</sup>| Loader &#9989;<br/>Saver &#11036;  |
| .heif, .heic, .avif    | [heifload]<sup>3</sup> | [heifsave]<sup>3</sup>  | Loader &#9989;<br/>Saver &#9989;   |
| .tif, .tiff            | [tiffload]             | [tiffsave]<sup>4</sup>  | Loader &#9989;<br/>Saver &#11036;  |
| .dz                    | -                      | [dzsave]<sup>5</sup>    | Saver &#11036;                     |
| .csv                   | [csvload]              | [csvsave]               | Loader &#9989;<br/>Saver &#9989;   |
| .ppm                   | [ppmload]              | [ppmsave]               | Loader &#9989;<br/>Saver &#9989;   |
| .mat<sup>6</sup>       | [matrixload]           | [matrixsave]            | Loader &#9989;<br/>Saver &#9989;   |
| .pdf                   | [pdfload]<sup>7</sup>  | -                       | Loader &#9989;                     |
| -                      | [rawload]<sup>8</sup>  | [rawsave]<sup>8</sup>   | Loader &#11036;<br/>Saver &#11036; |
| .v, .vips              | [vipsload]<sup>9</sup> | [vipssave]<sup>9</sup>  | Loader &#9989;<br/>Saver &#9989; |
| [whole-slide suffixes] | [openslideload]        | -                       | Loader &#9989;                     |

Loaders and savers missing from the above table: [analyzeload], [fitsload], [fitssave], [magick7load], [magickload], [matload], [niftiload], [niftisave], [openexrload] and [pdfiumload]. 
Already supports the new source/target API: [jpegload], [jpegsave], [tiffload], [radload], [radsave], [svgload], [webpload] and [webpsave].

### Notes:
1. libnsgif needs the whole source file available at once, it can't stream images (as far as I know), so it's not a great fit. It's rather like webp. giflib isn't much better: you can only find out the number of frames by scanning the entire image, and you have to discover the number of frames as part of reading the header.
2. Instead of relying on *magick to encode gif images, we might use the [gifenc] library to achieve this. It is a small C library (300 lines of C99 code) that can be used to create GIF animations. The same author also created [gifdec] (a small gif decoder) which is worth looking at.
3. We could use the [heif_context_read_from_reader] and [heif_context_write] functions.
4. tiffsave won't work well: it needs to make temp files (or temp memory objects) for pyramid layers. VipsTarget needs some new API here -- something like vips_target_tmp_from_target()?
5. dzsave uses libgsf for output, so I supposed we'd need another adapter to link libgsf to VipsTarget.
6. [matrixload] / [matrixsave] are used to read and write convolution matrices. They are very like the CSV load/save pair.
7. pdfium load is done too.
8. If we rework raw load/save we'd get early close for free.
9. Approximately the same as raw load/save (see 8).

[analyzeload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/analyzeload.c
[csvload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/csvload.c
[csvsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/csvsave.c
[dzsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/dzsave.c
[fitsload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/fitsload.c
[fitssave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/fitssave.c
[gifload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/gifload.c
[heifload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/heifload.c
[heifsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/heifsave.c
[jpegload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/jpegload.c
[jpegsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/jpegsave.c
[magick7load]: https://github.com/libvips/libvips/blob/master/libvips/foreign/magick7load.c
[magickload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/magickload.c
[magicksave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/magicksave.c
[matload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/matload.c
[matrixsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/matrixsave.c
[matrixload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/matrixload.c
[matrixsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/matrixsave.c
[niftiload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/niftiload.c
[niftisave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/niftisave.c
[openexrload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/openexrload.c
[openslideload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/openslideload.c
[pdfiumload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfiumload.c
[pdfload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfload.c
[ppmload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/ppmload.c
[ppmsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/ppmsave.c
[radload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/radload.c
[radsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/radsave.c
[rawload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/rawload.c
[rawsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/rawsave.c
[svgload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/svgload.c
[tiffload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/tiffload.c
[tiffsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/tiffsave.c
[vipsload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/vipsload.c
[vipssave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/vipssave.c
[webpload]: https://github.com/libvips/libvips/blob/master/libvips/foreign/webpload.c
[webpsave]: https://github.com/libvips/libvips/blob/master/libvips/foreign/webpsave.c
[whole-slide suffixes]: https://github.com/libvips/libvips/blob/babbb086f92a678b0aad87826d8ab738bce5570f/libvips/foreign/openslideload.c#L306-L315

[gifdec]: https://github.com/lecram/gifdec
[gifenc]: https://github.com/lecram/gifenc
[heif_context_read_from_reader]: https://github.com/strukturag/libheif/blob/f3e58e21a87be3704c5c4837984be7eb235717d5/libheif/heif.h#L395-L399
[heif_context_write]: https://github.com/strukturag/libheif/blob/f3e58e21a87be3704c5c4837984be7eb235717d5/libheif/heif.h#L902-L905
[poppler_document_new_from_stream]: https://developer.gnome.org/poppler/0.24/PopplerDocument.html#poppler-document-new-from-stream
[VipsGInputStream wrapper]: https://github.com/libvips/libvips/blob/6605029bc381ff4316bfa31010d038f0c1d8c8ca/libvips/foreign/svgload.c#L75-L360

**Comment by jcupitt** [comment]
Oh hey well done! This is a great idea.

I've started revising gifload to work with streams:

https://github.com/libvips/libvips/tree/revise-gifload2

not done yet though.

**Comment by jcupitt** [comment]
OK, gifload done and merged to master.

**Comment by kleisauke** [comment]
Awesome! I confirm `gifload_source` is working well. Tested with:
```bash
wget https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing-banana.gif
cat dancing-banana.gif | vips copy stdin[n=-1] x.webp
```

I'll have a look at `pdfload` this week (will be quite similar to `svgload`, I think).

**Comment by jcupitt** [comment]
I did csv load and save as well.

**Comment by jcupitt** [comment]
`matrixload` and `matrixsave` done too, plus `_source` versions.

**Comment by jcupitt** [comment]
`pdfload` done, and I added `pdfload_source`.

**Comment by jcupitt** [comment]
`heifload` and `heifsave` done too, plus `_source`/`_target` versions.

**Comment by kleisauke** [comment]
I started to revise `vipsload` for the source API, see: https://github.com/kleisauke/libvips/commit/a11b978fb70d338c2d7ffba8fd2b4ff1106d1b87.

While doing that, I noticed something strange in `csvload_source` and `matrixload_source`. I suspect that these lines: https://github.com/libvips/libvips/blob/175408733fcffed7aa0618c6d5ad5390ed5c4f88/libvips/foreign/matrixload.c#L405
https://github.com/libvips/libvips/blob/175408733fcffed7aa0618c6d5ad5390ed5c4f88/libvips/foreign/csvload.c#L603

Should check for `source->source` instead.

**Comment by jcupitt** [comment]
Wow you're right, they are all messed up. Too much copy-paste programming :(

I've revised them. Thanks!

**Comment by jcupitt** [comment]
... I'll try to add some tests too.

**Comment by jcupitt** [comment]
OK, tests added, plus ppm load/save to/from a connection.

**Comment by kleisauke** [comment]
I've added `openslideload` to the list and marked it as finished, since this is most likely done with commit https://github.com/libvips/libvips/commit/babbb086f92a678b0aad87826d8ab738bce5570f.

If someone wants to work on revising `vipsload`, then see https://github.com/libvips/libvips/issues/1541#issuecomment-649766008. Otherwise, I'll pick this up in the course of next week.

**Comment by jcupitt** [comment]
I'll add some tests for openslideload_source().

I'm reworking vipsdisp to use the new Source API, hence my current interest in this:

https://github.com/jcupitt/vipsdisp

**Comment by jcupitt** [comment]
I did vipsload_source() and updated the table.

**Comment by jcupitt** [comment]
... and vipssave_target.
