### ISSUE TITLE
Image saving hangs if leaks detection is enabled

### ISSUE THREAD

**Issue by DarthSim** [libvips/libvips#1542]
After I upgraded to `8.9.1` from `8.8.3`, image saving started to hang if `vips_leak_set(TRUE)` was called before. Everything before the saving works as expected.

`vipsthumbnail -v --size=200 image.jpg --vips-leak=1` hangs as well.

**Comment by jcupitt** [comment]
This one at least was simple. Thanks for the report, fix in 8.9.2.

**Comment by DarthSim** [comment]
Wow, that was fast! Thanks a lot!
