### ISSUE TITLE
Some GIF images aren't loaded properly

### ISSUE THREAD

**Issue by DarthSim** [libvips/libvips#1543]
My user sent me a GIF that isn't loaded properly by libvips. It looks like libvips doesn't properly blend frames.

![bad4](https://user-images.githubusercontent.com/380856/73546168-f1a9a000-4466-11ea-8ce4-139d325cc753.gif)

The result of `vipsthumbnail -v --size=200 -f tn_bad4.gif ~/Work/pictures-fixtures/bad4.gif[n=-1]`:

![tn_bad4](https://user-images.githubusercontent.com/380856/73546169-f1a9a000-4466-11ea-9a21-021bb7498879.gif)

The result of `vipsthumbnail -v --size=200 -f tn_bad4.png ~/Work/pictures-fixtures/bad4.gif[n=5
]`:

![tn_bad4](https://user-images.githubusercontent.com/380856/73546639-c3789000-4467-11ea-9b4b-dae0dae427d2.png)

Frames montaged with [gif_anim_montage](https://imagemagick.org/Usage/scripts/gif_anim_montage):

![frames](https://user-images.githubusercontent.com/380856/73546126-dccd0c80-4466-11ea-98bf-a3f15fc1c8ae.gif)

**Comment by jcupitt** [comment]
Huh you're right. I'll have a look. Thanks for the report!

**Comment by jcupitt** [comment]
That GIF has dispose set to `DISPOSAL_UNSPECIFIED` to mean "reuse previous frame". I think it should probably be `DISPOSE_DO_NOT`, from looking at the spec.

I've made gifload treat `UNSPECIFIED` the same as `DO_NOT`, and it seems to fix rendering.

This will be in 8.9.2, thanks!

**Comment by DarthSim** [comment]
Thank you! GIFs are still pretty terra incognita for me :(
