### ISSUE TITLE
Clarification of memory ownership

### ISSUE THREAD

**Issue by jhford** [libvips/libvips#1544]
Hi, I'm loading a picture from a memory buffer into a `VipsImage*` using `vips_image_new_from_buffer`.

Roughly speaking:
```c
int input_size = 0;
char *input_buf = read_all(STDIN_FILENO, &input_size);
VipsImage image = vips_image_new_from_buffer(input_buf, input_size, "", NULL);
```
`read_all` is a function where I read all of the bytes until EOF from the fd into a buffer, and set the number of bytes read as the `input_size` out parameter.  I am curious about how the memory works internally and want to make sure that I'm not doing something crazy.

For example, if I do `vips_resize()` on a VipsImage,
```c
VipsImage *out;
vips_resize(image, out, 2);
```
Then swap the VipsImage around (for chaining operations)
```c
VipsImage *newImage;
g_object_unref(image);
image = out;
```

What I'm noticing is that if I call free on `input_buf` immediately after calling `vips_image_new_from_buffer`, that when I later try to do a `vips_jpegsave()` call for the image, that I get an output size of 0bytes.  If I move `free(input_buf)` to after the export, everything works just fine.

My specific questions are:

1. Am I doing this totally wrong or misunderstanding the concepts?
1. Is the memory backing both of those `VipsImages` the memory originally allocated above for `inpu-t_buf`?
1. Does Vips internally do any reallocs or other memory managment needed to ensure that the backing buffer grows as needed?
1. Why am I not getting a crash or seemingly getting an error from libvips when I operate on a `VipsImage` for which I have freed the backing memory?

Thanks!

**Comment by jcupitt** [comment]
Hello @jhford,

No, libvips will not take a copy of the data. Images can be many GB, and it's not a good idea to copy unless you really have to. The docs have some notes, though perhaps they could be more explicit:

https://libvips.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-buffer

So you must not free the memory you pass to `new_from_buffer` until you have finished using it. An easy way to do this is to free the memory in a close signal on the image.

```C
void
my_free_function( VipsImage *image, void *user_data )
{
   char *input_buf = (char *) user_data;

    free( input_buf );
}

...
    g_signal_connect( image, "close", G_CALLBACK( my_free_function ), input_buf );
```

Have you seen `g_file_get_contents()`? It might save you some work.

https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-file-get-contents

On your questions, libvips is demand-driven, so there's no memory allocation and no processing until the final `jpegsave`. At that point, your image will be decompressed, processed and saved in chunks and in parallel. Everything is reference-counted, so even if you unref it, your initial input image will still exist until you finally shut down the output.

I'd set `"access"`, eg.

```C
VipsImage *image = vips_image_new_from_buffer(input_buf, input_size, "", 
    "access", VIPS_ACCESS_SEQUENTIAL, NULL);
```

You'll see a big increase in speed and drop in peak memory use, as long as you're not doing coordinate transformations.

**Comment by jhford** [comment]
So to make sure I understand the model here, roughly speaking:  I allocate memory from reading in the buffer, then I use the different vips functions to build a set of transforms that I want to do, then only when I do the final jpegsave, are all the transforms executed against my image, with any allocation or buffer growth happening and cleaned up inside the jpegsave call.

I will set the access for that, I just assumed the default action would be ideal here.

**Comment by jhford** [comment]
is 
```c
VipsImage *in, *out;
vips_resize(in, out, 2, NULL);
VipsImage *newImage;
g_object_unref(image);
image = out;
```
the correct way to reference count here?

**Comment by jcupitt** [comment]
Yes, it should work, but post a complete program and I can have a look.

**Comment by jcupitt** [comment]
`vips_object_local_array()` can be a more convenient way to manage references:

https://libvips.github.io/libvips/API/current/VipsObject.html#vips-object-local-array

It makes an array of pointers which will all be unreffed if they are non-NULL when the parent object is unreffed. It makes it easy and safe to chain image processing operations in C.
