### ISSUE TITLE
dzsave on tiff image results in all black output jpg 

### ISSUE THREAD

**Issue by miriam-groeneveld** [libvips/libvips#1545]
This issue might be related to #1471 ?
I have a multi-paged pyramidal tiff file that I convert to dz (using command vips dzsave file.tif file_output --tile-size=2560).
The output only contains black jpeg files. The sample format is floating point, not sure if that's the issue. Can't post the file here but can send it privately. This is the output of tiffinfo on the file:

 TIFF Directory at offset 0x222926aa (573122218)
  Image Width: 12224 Image Length: 27456
  Tile Width: 512 Tile Length: 512
  Resolution: 5142.07, 5142.07 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  SMin Sample Value: 0
  SMax Sample Value: 0.99999
  Planar Configuration: single image plane
TIFF Directory at offset 0x2adc8706 (719095558)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 6112 Image Length: 13728
  Tile Width: 512 Tile Length: 512
  Resolution: 2571.04, 2571.04 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane
TIFF Directory at offset 0x2d15530e (756372238)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 3056 Image Length: 6864
  Tile Width: 512 Tile Length: 512
  Resolution: 1285.52, 1285.52 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane
TIFF Directory at offset 0x2da6dd06 (765910278)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 1528 Image Length: 3432
  Tile Width: 512 Tile Length: 512
  Resolution: 642.759, 642.759 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane
TIFF Directory at offset 0x2dcc2a42 (768354882)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 764 Image Length: 1716
  Tile Width: 512 Tile Length: 512
  Resolution: 321.38, 321.38 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane
TIFF Directory at offset 0x2dd5c1ca (768983498)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 382 Image Length: 858
  Tile Width: 512 Tile Length: 512
  Resolution: 160.69, 160.69 pixels/cm
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: LZW
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane

**Comment by jcupitt** [comment]
Hello @miriam-groeneveld,

My guess would be that your float TIFF is using the range 0 - 1 for black to white, but that your tiles are RGB JPGs, which use 0 - 255 for black to white. You probably need to multiply by 256 before saving.

You could try:

```
vips linear file.tif file_output.dz[tile-size=256] 256 0
```
