### ISSUE TITLE
Support layer\series for big tiff

### ISSUE THREAD

**Issue by pkochubey** [libvips/libvips#1546]
Hi. I can't found any solution in vips for extract tiff layer from bigtiff format? Do you have any idea? When I use first ./bfconvert -series 2 *.btf *.tiff and after this try run "vips dzsave *.tiff /tiff" I get the error: "tiff2vips: tiled separate planes not supported".

**Comment by jcupitt** [comment]
Hello @pkochubey,

libvips only has limited support for plane separated TIFF images. Is there a flag you can give `bfconvert` to make it write a continuous image? That's `PLANARCONFIG_CONTIG` in TIFF parlance.

Alternatively, you should be able to read the btf image directly into libvips. Could you post an example image somewhere and explain what part you want to read out?

**Comment by pkochubey** [comment]
Hello @jcupitt 
btf file: https://yadi.sk/d/QukTG0Im9RyB3A it contains many tiff series entire.
If run vips dzsave demo.btf ./btf I catch tiles only for first series. But in first series I have low resolution image. More detail image stored in second series.

**Comment by jcupitt** [comment]
libvips uses `page` to pick out directories from TIFF files. Try:

```
vips dzsave demo.btf[page=4] x
```

You should get a 47961x41745 pixel image (is that the right one?).

You can use `vipsheader -a` to see all fields. For example:

```
$ vipsheader -a demo.btf 
demo.btf: 7207x20598 uchar, 3 bands, srgb, tiffload
width: 7207
height: 20598
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 0.0393701
yres: 0.0393701
filename: demo.btf
vips-loader: tiffload
n-pages: 6
resolution-unit: in
orientation: 1
```

So your image has six pages.

```
$ for i in {0..5}; do vipsheader demo.btf[page=$i]; done
demo.btf: 7207x20598 uchar, 3 bands, srgb, tiffload
demo.btf: 361x1030 uchar, 1 band, b-w, tiffload
demo.btf: 41377x49146 uchar, 3 bands, srgb, tiffload
demo.btf: 25x30 ushort, 1 band, grey16, tiffload
demo.btf: 47961x41745 uchar, 3 bands, srgb, tiffload
demo.btf: 29x25 ushort, 1 band, grey16, tiffload
```

**Comment by pkochubey** [comment]
Awesome, page flag works for this format. Thanks!

**Comment by lesolorzanov** [comment]
Hello, apologies for reopening this issue. It's still happening in 2025 :( 

I have vips version 8.17.0 

My image has 8 pages. 

None of these works:
```
vips dzsave demo.btf[page=N] x
vips dzsave demo.btf[N] x
vips dzsave demo.btf x

vips tiffsave demo.btf[page=N] x.tif
vips tiffsave demo.btf[N] x.tif
```

All of them say tiff2vips: tiled separate planes not supported

The `vipsheader -a` shows:

```
f: 54784x45056 uchar, 3 bands, srgb, tiffload
width: 54784
height: 45056
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 5802.9
yres: 5802.9
filename: demo.btf
vips-loader: tiffload
n-pages: 8
image-description: ImageJ=
hyperstack=true
images=3
channels=3
slices=1
frames=1
resolution-unit: cm
bits-per-sample: 8
orientation: 1
```

Do you have any suggestion? is it that I have to use a different symbol/key for the page?
Using imagemagick I can extract the second page, the first one is too large and imagemagick exits with an error.

bfconvert takes ages to convert btf to tif, I am still waiting, but then I will try to run vips on the converted image and see if that changes something.

**Comment by jcupitt** [comment]
You have a strange TIFF image -- plane-separated tiled. This is a format that's theoretically possible within the TIFF spec, but which readers are not expected to implement. It's outside the baseline.

libvips has quite a few extensions for TIFF variants that people have used, but not this one. We could add support, but it would maybe be a week's work.

Where is the image from? Maybe you can generate it in some other way?

**Comment by jcupitt** [comment]
I've opened a new issue since this is a new question.
