### ISSUE TITLE
tiff to dzi using libvips

### ISSUE THREAD

**Issue by saraada** [libvips/libvips#1547]
Hi, I am new to libvips and just installed it on my windows 10.
I need to convert tiff images to dzi. But I am not getting the procedure to download the dependencies or packages required. Can someone please guide or point me to the right source.

Thanks.

**Comment by jcupitt** [comment]
Hello, they are all included in the download. Just unzip it and run:

```
vips.exe dzsave file.tif output
```

To make `output.dzi` and `output_files/`.

**Comment by saraada** [comment]
Thanks. 
Now, how do I run it outside the directory?

**Comment by jcupitt** [comment]
From some other directory, you can use a path to `vips.exe`:

```
../../vips-8.9.1/bin/vips.exe file.tif output
```

You can add `c:/vips-8.9.1/bin` to your `PATH` (probably not a good idea), or you can write a wrapper script that sets `PATH` just for that process and runs `vips.exe`, then put that wrapper somewhere on your path.

If you are using something like Python, you can also set `PATH` just for your process.
