### ISSUE TITLE
Unsupported colorspace for heic assets

### ISSUE THREAD

**Issue by rps01** [libvips/libvips#1553]
```
vipsthumbnail example.heic -s 1280x1280 -o test2.jpeg
vipsthumbnail: unable to thumbnail example.heic
magickload: unsupported colorspace YCbCrColorspace
```

Vips version: libvips 8.8.4

Related issue: https://github.com/libvips/libvips/issues/1315

Other info:
```
ldd $(which vips) | grep -i heif
libheif.so.1 => /../../../install/libheif-1.6.1/lib/libheif.so.1
```

**Comment by jcupitt** [comment]
Hello @rps01,

Your libvips has been built without HEIC support, so it's trying to load via imagemagick and failing. You'll need to install libheif and recompile.

**Comment by rps01** [comment]
thanks @jcupitt , had only rebuilt imagemagick. Rebuilding vips solved above.
