### ISSUE TITLE
Could I get the intermediate metadata of vips_smartcrop?

### ISSUE THREAD

**Issue by tony612** [libvips/libvips#1554]
I want to smart-crop images, but I want to get the intermediate metadata(left, top, height, width) of vips_smartcrop. So that I track it in our ML system and can even use the intermediate metadata to call vips_crop to get the same result.

For example, given an 800x600 image, if smartcrop will crop it  to 300x300 at `left: 100, top: 100, height: 300, width: 300`. Is there a way to get the numbers `left: 100, top: 100, height: 300, width: 300`?

It would be better if I can get the numbers without really cropping it. So it's a dry-run job.

**Comment by jcupitt** [comment]
Hi @tony612,

You can just read `xoffset` and `yoffset` from the output image:

```

>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> y = x.smartcrop(100, 100, interesting="attention")
>>> y.xoffset
-1037
>>> y.yoffset
-846
>>> y.width
100
>>> y.height
100
```

They give the displacement from the image origin to the source origin. libvips is on-demand, so the crop isn't actually done until you use it for something.

**Comment by tony612** [comment]
Got it. I think this is what I need. Thank you!

**Comment by fauno** [comment]
Sorry to bump this, I need to do something similar but I don't understand what "They give the displacement from the image origin to the source origin" means, I've tested several things but the offsets I get don't seem to map to anything on the origin. Could you clarify? Thanks!

**Comment by jcupitt** [comment]
Sure, just:

```
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> y = x.smartcrop(100, 100, interesting="attention")
>>> y.xoffset
-1037
>>> y.yoffset
-846
>>> y.width
100
>>> y.height
100
>>> z = x.crop(-y.xoffset, -y.yoffset, y.width, y.height)
```

(in retrospect calling those temp images xyz was not a great idea heh)

**Comment by fauno** [comment]
Thanks! I got that far but I don't understand how to map those offsets back to the source image. For instance, I've tried resizing the thumbnail back to the source image, but the offsets don't correspond to the position of the thumbnail, so how do I use them?

But I had to produce the thumbnail using `vipsthumbnail -s 100x100 -m attention` because this produces errors, so maybe `vipsthumbnail` and `ruby-vips` are cropping differently?

```ruby
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> image = Vips::Image.new_from_file './image.jpg', access: :sequential
=> #<Image 854x480 uchar, 3 bands, srgb>
irb(main):003:0> thumbnail = image.smartcrop(100, 100, interesting: :attention)
=> #<Image 100x100 uchar, 3 bands, srgb>
irb(main):004:0> thumbnail.xoffset
=> -723
irb(main):005:0> thumbnail.yoffset
=> -70
irb(main):006:0> thumbnail.write_to_file '../thumbnail.jpg'

(process:2126731): VIPS-WARNING **: 10:40:27.383: error in tile 0 x 64

(process:2126731): VIPS-WARNING **: 10:40:27.383: error in tile 0 x 72

(process:2126731): VIPS-WARNING **: 10:40:27.384: error in tile 0 x 80
/usr/lib/ruby/gems/3.1.0/gems/ruby-vips-2.2.0/lib/vips/operation.rb:228:in `build': VipsJpeg: out of order read at line 480 (Vips::Error)
        from /usr/lib/ruby/gems/3.1.0/gems/ruby-vips-2.2.0/lib/vips/operation.rb:483:in `call'
        from /usr/lib/ruby/gems/3.1.0/gems/ruby-vips-2.2.0/lib/vips/image.rb:592:in `write_to_file'
        from (irb):6:in `<main>'
        from /usr/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /usr/bin/irb:25:in `load'
        from /usr/bin/irb:25:in `<main>'
```

![image](https://github.com/libvips/libvips/assets/468204/76e3fce7-8d53-453c-8ff8-3a1090d59efb)

The source image is 854x480, the image with black border is the 100x100 thumbnail resized to 480x480 and the yellow circle's top left corner is positioned at 723, 70.

I can move this to a discussion if it's annoying here.  This is for an open source project so I can link to example code afterwards!

**Comment by jcupitt** [comment]
You're using `access: :sequential`, but then looping over the image twice (once for smartcrop, another time for save), hence the out of order errors. Remove the access hint to stop that happening.

Could you link to the source image you used for testing?

**Comment by fauno** [comment]
Aaah, thanks! Ok, yeah, ruby-vips and vipsthumbnail are producing different croppings and the results are less confusing. The small square is the crop produced by ruby-vips:

![image](https://github.com/libvips/libvips/assets/468204/cf3cee0a-d331-4e9d-a155-23e698ab3a47)

Here's the source image:

![snapshot](https://github.com/libvips/libvips/assets/468204/c58887dd-b7a1-49ee-93d3-e7a68977eecb)

**Comment by jcupitt** [comment]
The smartcrop parameters have been tuned several times, you probably have different libvips binaries for your CLI and for ruby-vips.

**Comment by fauno** [comment]
Ok, I'll check. Thanks for your help!

**Comment by fauno** [comment]
Just for completion, the way to reproduce `vipsthumbnail` was this:

```ruby
Vips::Image.thumbnail 'file.jpg', 100, height: 100, crop: :attention
```
