### ISSUE TITLE
tiffsave RGBA pyramid

### ISSUE THREAD

**Issue by rgluskin** [libvips/libvips#1556]
Hi,
I'm using `vips tiffsave` to add the pyramid layers to an image I'm rendering.
I noticed that when the image has an alpha channel(a recently added requirement), the newly added layers' colors are distorted.

Here's a simple example:

```python
from PIL import Image, ImageDraw
from shapely.geometry import box
import numpy as np
from tifffile import TiffWriter

img_size = 2**10
fill_color = '#efe0b966'
compression_level = 1

img = Image.new("RGBA", (img_size, img_size))
draw = ImageDraw.Draw(img, 'RGBA')
draw.polygon(box(0,0,img_size-1,img_size-1).exterior.coords, fill=fill_color)


with TiffWriter("vips_test_image.tif", bigtiff=True) as tif:
    tif.save(np.array(img), compress=compression_level, photometric='rgb', subfiletype=0, tile=(1, 256, 256))
```
followed by

`vips tiffsave --compression=lzw --Q=100 --tile --tile-width=512 --tile-height=512 --pyramid --vips-progress "vips_test_image.tif" "vips_test_pyramid.tif"`

and then

```python
from openslide import OpenSlide
slide = OpenSlide("vips_test_pyramid.tif")

print(np.array(slide.read_region((0,0),level=0, size=(1,1)))[0,0,:])
print(np.array(slide.read_region((0,0),level=1, size=(1,1)))[0,0,:])
```
Output
```
[240 225 185 102]
[ 85  48 206 102]
```

If I change `RGBA` to `RGB` and `fill_color = '#efe0b9'` then both of the outputs are:
```
[239 224 185 255]
```

I tried turning on `bigtiff` flag but it didn't change anything... Is there some switch that I need to turn on ?

Thanks,
Roman

**Comment by jcupitt** [comment]
Hello, tiffsave is using the alpha as it shrinks the image, so I think it's actually correct.

This page explains the issue very clearly (IMO):

http://entropymine.com/imageworsener/resizealpha/

**Comment by rgluskin** [comment]
Hi John,
Thanks for the quick reply.
If I understand correctly their explanation is valid for the area boundaries.
The phenomenon I see is across the whole image, not just the boundaries.
Also, the calculation is not quite clear (alpha of 102 should be about 40%, which isn't quite fitting to the results I see).

**Comment by rgluskin** [comment]
![#f0e1b966](https://placehold.it/15/f0e1b966/000000?text=+) `#f0e1b966`
![#5530ce66](https://placehold.it/15/5530ce66/000000?text=+) `#5530ce66`

These are the solid colors I'm seeing, which are not at all close to each other :/

**Comment by jcupitt** [comment]
Hello again, I tried your example. Here's a slightly simpler program to generate your test image:

```python3
#!/usr/bin/python3

import sys
import pyvips

fill_colour = "#efe0b966"
img_size = 2 ** 10
svg = f"""
    <svg viewBox="0 0 {img_size} {img_size}">
        <rect width="{img_size}" height="{img_size}" fill="{fill_colour}" />
    </svg>
"""
x = pyvips.Image.svgload_buffer(bytes(svg, "utf8"))

x.write_to_file(sys.argv[1])
```

I can run it like this:

```
$ ./mksample.py x.tif
$ vips copy x.tif y.tif[pyramid,tile]
$ vips getpoint x.tif 0 0
237 222 185 102 
$ vips getpoint y.tif 0 0
237 222 185 102 
$ vips getpoint y.tif[page=2] 0 0
237 222 185 102 
```

So I see the same values in all images.

Could you have an old libvips? I'm using 8.9.1.

**Comment by rgluskin** [comment]
You're right, I was on 8.6.
Very sorry for wasting your time.
