### ISSUE TITLE
Still trouble with home-brew install on Macs

### ISSUE THREAD

**Issue by iowatom** [libvips/libvips#1558]
I have upgraded to vips 8.9.1 on a Mac laptop.
I had been having trouble with corrupted dzi files made with the command:

vips extract_area ImageName.mrxs[level=2] ImageName/tiles.dz 3744 4128 9056 7648

This had been attributed to a flawed pixman component of Cairo.
see:
https://github.com/libvips/php-vips/issues/91

The flaw seems to still be present in this  recent upgrade.
I looked in the Cellar files and pixman is version 0.38.4 unchanged from previous installs.

Assuming this is the problem, any Idea how to get this working again?
Thanks

**Comment by jcupitt** [comment]
I think you have three choices:

1. Wait for pixman to put out a new version.
2. Edit the `pixman.rb` formula to build the previous version.
3. Write a little Python to do the downsize and crop using libvips instead.

**Comment by kleisauke** [comment]
pixman 0.40.0 is now available within Homebrew, see: https://github.com/Homebrew/homebrew-core/pull/53456.
