### ISSUE TITLE
Add support for JPEG XL

### ISSUE THREAD

**Issue by gunta** [libvips/libvips#1559]
Why:
JPEG XL is the future of all image formats.

Explanation here:
https://www.slideshare.net/cloudinarymarketing/imagecon-2019-jon-sneyer

Reference implementation here:
https://gitlab.com/wg1/jpeg-xl

**Comment by jcupitt** [comment]
Sure, looks interesting. PRs etc. very welcome.

**Comment by kmartinez** [comment]
nice to see AVX2 being used! probably requires a delicate config/make as so many CPUs don't have it but as you say - it could be the future!

**Comment by dkam** [comment]
Integrating JPEG-XL is beyond me, but [ImageMagick](https://github.com/ImageMagick/ImageMagick/blob/main/coders/jxl.c) has integrated it.
