### ISSUE TITLE
Documentation for vips_percent() not clear

### ISSUE THREAD

**Issue by gil-c** [libvips/libvips#1560]
Hello,

I think that the description of vips_percent() might be wrong. It says:

> vips_percent() returns (through the threshold parameter) the threshold above which there are percent values of in . If for example percent=10, the number of pels of the input image with values greater than threshold will correspond to 10% of all pels of the image.

Isn't it the other way around: "the threshold **under** which there are percent values of in"?

**Comment by jcupitt** [comment]
Oh yes, you're right, thanks! I'll revise it.

**Comment by jcupitt** [comment]
OK, fixed in master, thank you again for reporting this dumbness.
