### ISSUE TITLE
Inserting text in image

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1562]
I am trying to insert text in a image and it is working well for tif files, 

But if the ori.tif:  10425x8520 uchar, 1 band, b-w, tiffload
the resulted image_with_text.tif: 10425x8520 uchar, 2 bands, b-w, tiffload

How to make it as 1 band image
Iam using this program from

https://gist.github.com/jcupitt/039ecdc172712cbb8969

I also gave vips_flatten before writing the tiff file  but the result is same getting 2 bands.

But if I use cmd line of VIPs flatten image_with_text.tif new.tif

The output tif is fine with 1 band.

How to do with the watermark.c program

**Comment by jcupitt** [comment]
Hello, I updated the watermark program to the latest libvips (it now uses composite), and added support for RGB, mono and CMYK images. 

Try again, it shoulud work for your case now.

**Comment by vkkindia** [comment]
Still getting error for 1 bit tiff image when saved in ccittfax4.

(watermark:6873): VIPS-WARNING **: can only squash 1-band uchar and 3-band float lab -- disabling squash
Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding
wbuffer_write: write failed
unix error: Unknown error -1

I tried to save 
overlay = t[9];
	printf("Saving overlay\n") ;
	vips_image_write_to_file( t[9], argv[3], NULL ) ;

and this image tiffinfo is 
---------------------------
tiffinfo overlay.tif 
TIFF Directory at offset 0x8 (8)
  Image Width: 10425 Image Length: 8520
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-black
  Extra Samples: 1<unassoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 2
  Rows/Strip: 128
  Planar Configuration: single image plane

-------------------

**Comment by jcupitt** [comment]
The overlay image has an alpha channel, so it won't save as a fax image. Why do you want to save the overlay?

**Comment by vkkindia** [comment]
I just shared the info. I need the input 1 bit tiff with watermark and
saved as 1bit tiff with ccittfax4

**Comment by vkkindia** [comment]
Actually that is the output when used with watermark program while save as ccittfax4 for 1 bit image.

(watermark:6873): VIPS-WARNING **: can only squash 1-band uchar and 3-band float lab -- disabling squash
Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding
wbuffer_write: write failed
unix error: Unknown error -1

**Comment by jcupitt** [comment]
Ah I see, I didn't realize you wanted to watermark faxes.

Yes, the output has an alpha channel, so it won't save to a fax image. Perhaps inverting the watermark onto the image would work better for this type of image?

Try:

https://gist.github.com/jcupitt/c59271564f3cf93de4d535b066d1897d

**Comment by vkkindia** [comment]
The new water mark program gives exact result as my need rather than invert. 
And idea to make light density text or some tint in the background.

**Comment by jcupitt** [comment]
You'd need to dither the text, I suppose. Make an eg. 5x5 image with your dither pattern, replicate to the same size as the text mask, and AND with that before EORing with the image.

**Comment by jcupitt** [comment]
For example: https://gist.github.com/jcupitt/fea1f7c6b1b6d7375b18bc0867acd242

**Comment by vkkindia** [comment]
Thank you
