### ISSUE TITLE
constructing multilayered zoomable file from multiple smaller files

### ISSUE THREAD

**Issue by brianbourke75** [libvips/libvips#1563]
I was hoping for a bit of help to see if vips could help me with an issue.  I need to take a series of OME TIFF fluorescent microscopy images stored in 32 bit floating point accuracy, each representing a different area on the slide and construct them into a zoomable image format with colorized layers.  I am open to which output format is used.

thanks!

**Comment by jcupitt** [comment]
Hello, yes, this should be simple. I think I'd use deepzoom for the output. Something like:

```python
import sys
import random
import pyvips

image = pyvips.Image.black(60000, 60000)

for filename in sys.argv[2:]:
    tile = pyvips.Image.new_from_file(filename, access='sequential')
    x = random.randint(0, image.width - tile.width)
    y = random.randint(0, image.height - tile.height)
    image = image.insert(tile, x, y)

image.write_to_file(sys.argv[1])
```

Then run with:

```
./manyjoin.py out.dz a.tif b.tif c.tif
```

To paste a, b, and c at random positions in a large image and write as a deepzoom pyramid. If you share some sample images I could add some more detail.

**Comment by brianbourke75** [comment]
Thanks for the feedback and while I was able to get the script to work it seems to be producing blank images.  My first instinct is because the images are 32 bit floating point pixels in the range of 0-2.0ish and probably need to be rescaled to 0-255 range.  Does that sound right to you?  Thanks!

**Comment by jcupitt** [comment]
Yes, that sounds likely. Try:

```python
image *= 128
```

Before saving it.

**Comment by brianbourke75** [comment]
That seems to have done it!  Now to translate it to the .Net binding.  Thanks!

**Comment by jcupitt** [comment]
Sorry, I missed your reply.

For TIFF output, use something like:

```
./manyjoin.py out.tif[pyramid,tile,compression=jpeg] a.tif b.tif c.tif
```

To write a jpeg-compressed tiled tiff pyramid.

You could also use deepzoom format, if this is for web use. Something like:

```
./manyjoin.py out.dz a.tif b.tif c.tif
```

To create `out_files` and `out.dzi`.

**Comment by brianbourke75** [comment]
I actually am writing this to a deepzoom format and it does not seem to be using paging on the output inspite of the input being paginated.

**Comment by jcupitt** [comment]
Huh, I'm not sure what's going on. Do you have a sample dataset you can share?

**Comment by brianbourke75** [comment]
Unfortunately I am not allowed as it may have confidential information.  I will try somethings and get back.

**Comment by jcupitt** [comment]
I've been doing a little work with OME pyramids and I think I have a clearer view of what's going on.

OME uses single-band images and stores them in consecutive pages of the TIFF file. You'll need to rearrange these pages into libvips colour images, then paste the colour images together, then save as something like deepzoom.

```python
#!/usr/bin/python3

import sys
import random
import pyvips

def ome_to_vips(image):
    """Convert an OME-style image to libvips-style.

    OME images are one band, and instead use multiple pages to represent colour.
    Crop an image into separate pages and join them up bandwise.
    """ 
    if image.get_typeof("page-height"):
        page_height = image.get("page-height")
    else:
        page_height = image.height

    pages = [image.crop(0, y, image.width, page_height) 
             for y in range(0, image.height, page_height)]

    return pages[0].bandjoin(pages[1:])

def colourize(image):
    """Make an RGB visualization image from a many-band OME.

    You'll want to swap this for something better.
    """

    return image[0:3].cast("uchar").copy(interpretation="srgb")

image_list = [ome_to_vips(pyvips.Image.new_from_file(filename))
              for filename in sys.argv[2:]]

composite = pyvips.Image.black(1000, 1000, bands=3).copy(interpretation="srgb")
for image in image_list:
    x = random.randint(0, composite.width - image.width)
    y = random.randint(0, composite.height - image.height)
    composite = composite.insert(colourize(image), x, y)
    
composite.write_to_file(sys.argv[1])
```

Run with:

```
$ ./try309.py x.dz ~/pics/ome/multi-channel-z-series.ome.tif[n=-1]
```

To make `x.dzi` and `x_files`, a deepzoom pyramid.
