### ISSUE TITLE
Missing TIFF headers (Subfile Type & Page Number) when compressing in CCITT Group 4

### ISSUE THREAD

**Issue by jclavoie-jive** [libvips/libvips#1565]
Hello! I am a new user of vips and I am doing some preliminary tests in order to maybe replace graphicsmagick. We're getting very good performance results so it is very interesting.

However, when saving a TIFF in a multipage tiff & group4 compression, it is missing 2 header values that are required per [RFC3949](https://tools.ietf.org/html/rfc3949) :
**Subfile Type**
and
**Page Number**

Also, not strickly needed per RFC but nice to have, is there a way to force encoding to be big-endian or does libvips only support little-endian today?

I haven't found anything inside the doc, but is there a way today to enable these fields when saving a tiff?

Thanks for your help!

As an annex, here's the result of tiffinfo generate by graphicsmagick vs vips.
GM:
`Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1728 Image Length: 2348
  Resolution: 204, 391 pixels/inch
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: lsb-to-msb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2348
  Planar Configuration: single image plane
  Page Number: 0-2
  DocumentName: gm_final_superfine.tiff`

vips:
`Image Width: 1728 Image Length: 4312
  Resolution: 204, 392 pixels/inch
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 128
  Planar Configuration: single image plane`

**Comment by jcupitt** [comment]
Hello @jclavoie-jive,

libvips sets subfile type for pyramidal images, but not for multipage, you're right. I suppose it just needs to be `FILETYPE_PAGE` for pages of a many page image, is that right?

It doesn't set `TIFFTAG_PAGENUMBER`. Do fax images have any conventions for page numbers? From zero?

The tiff writer writes in native byte order (the libtiff default). It'd be easy to add an option, though the tiff writer already has too many options, so there would need to be a string case for it, I think.

**Comment by jclavoie-jive** [comment]
> Hello @jclavoie-jive,
> 
> libvips sets subfile type for pyramidal images, but not for multipage, you're right. I suppose it just needs to be `FILETYPE_PAGE` for pages of a many page image, is that right?
> 
> It doesn't set `TIFFTAG_PAGENUMBER`. Do fax images have any conventions for page numbers? From zero?
> 
> The tiff writer writes in native byte order (the libtiff default). It'd be easy to add an option, though the tiff writer already has too many options, so there would need to be a string case for it, I think.

Thanks for the quick reply. You are right the page numbering starts from 0. 
From what I see testing with graphics magick, the subfile is only set if there is more than 1 page. However page number is always set.
I also checked the byproduct when initially converting from PDF to Tiff with Ghostscript, and this one always set the subfile as a multi-page document even if there's only 1 page. Also they don't seem to write the page number correctly as it always shows {x}-0 while graphicsmagick correctly show {x}-{total} when using tiffinfo

**Comment by jcupitt** [comment]
OK, let's tag this as an enhancement for 8.10. Thanks for the suggestion!

**Comment by jcupitt** [comment]
I had a quick go -- git master should now support `PAGENUMBER` and `FILETYPE_PAGE`. Any testing would be very welcome.

**Comment by jclavoie-jive** [comment]
> I had a quick go -- git master should now support `PAGENUMBER` and `FILETYPE_PAGE`. Any testing would be very welcome.

Thank! I'll try to have look to test it.

**Comment by jcupitt** [comment]
This will be in 8.10, thanks for suggesting it.
