### ISSUE TITLE
Question about usage for -level -white-threshold GM/IM equivalents

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1567]
Hello,

I would like to translate the following GraphicsMagick (or ImageMagick) command to lipvips **command line** or Netvips .NET Binding for Windows 64bit to gain performance on large images. 
My question is similar to https://github.com/libvips/libvips/issues/884 but the -level and -white-threshold parts are not discussed on that post.

Can someone please suggest what the best equivalent method is for

>gm convert -level 20%,1.0,80% -white-threshold 90% -fill white -fuzz 10% -opaque rgb(230,220,190)

explanation of GM commands:
-level <black_point>, gamma , <white_point>   = adjust image contrast levels
-white-threshold <threshold> = pixels above the threshold become white
-fill white = set color for next fill operation
-fuzz <value> = set fuzzyness approximation for next color operation
-opaque rbg(r,g,b) = replace rgb color with fill color (white) and fuzzyness.

Ideally I would like to do the libvips operation on a Region of Interest (w,h with offset x,y)

A few other tests that I did show frighenting performance benefit when using lipvips when compared to GM or IM. Brilliant work!
Thank you

--

**Comment by jcupitt** [comment]
Hello @CanadianHusky, could you post a sample image and expected result?

**Comment by CanadianHusky** [comment]
Certainly, 
input.jpg and output.jpg are in this link in high res original version

https://www.dropbox.com/s/l2z5jsv7nspikdc/input_output.zip?dl=0
link will stay alive for 1 week

below is a preview side by side considered an excellent result, original scan on left and after cleanup filter with this GM command that I would like to replicate over the libvips command line and by loading the image fully into memory for best performance.

`>gm time convert -level 30%,1.0,80% -white-threshold 90% -fill white -fuzz 15% -opaque rgb(230,225,195) "C:\temp\input.jpg" "C:\temp\output.jpg"
`
the RGB values are determined with a color picker code by the user that clicks on the background. It is possible that more than 1 RGB triplet replacement will be executed if the original image has to many variations
The level, threshold and fuzz values control how aggressive or gentle the filter will work. The filter structure, combined with the right parameters does excellent work in scan background cleanup and preserve existing detail. The example file is a generic example, the filter structure and sequence is intended and designed to clean up almost any scan with low contrast and heavy background. I have many other examples that work equally well with the right parameters.

thank you

![image](https://user-images.githubusercontent.com/35332003/76076711-703ab580-5fb0-11ea-8562-27cd30e8e653.png)

![image](https://user-images.githubusercontent.com/35332003/76077573-00c5c580-5fb2-11ea-95c8-2ec1786bdd16.png)

**Comment by jcupitt** [comment]
I had a quick go in python:

```python
#!/usr/bin/python3

import sys 
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

# typical paper background colour
paper = [212, 205, 190]

# typical black ink colour 
ink = [62, 73, 67]

# stretch the image so that ink gets down to ~30 and paper gets up to ~240
ink_target = 30
paper_target = 240
scale = [(paper_target - ink_target) / (p - i) for p, i in zip(paper, ink)]
offset = [ink_target - i * s for i, s in zip(ink, scale)]
lut = pyvips.Image.identity().linear(scale, offset)
image = image.maplut(lut.cast("uchar"))

# find distance to 255 of each pixel ... small distances go to white
d = image - 255
d = (d * d).sum()
image = (d < (100 ** 2)).ifthenelse(255, image)

image.write_to_file(sys.argv[2])
```

It stretches the range out for each channel, then moves stuff near the top to white, so it's very similar to your GM script, except that the paper scraps that are left over lose their yellow colour. I see:

![x2](https://user-images.githubusercontent.com/580843/76104260-f663f580-5fca-11ea-86ea-6ffad81a306e.jpg)

It's a little quicker than the GM version:

```
$ /usr/bin/time -f %M:%e ./clean.py input.jpg x2.jpg
93592:0.69
$ /usr/bin/time -f %M:%e ./clean.sh input.jpg 2.jpg
559540:0.89
```

So GM is 900ms and 560mb of memory, pyvips is 700ms and 94mb of memory. A lot of time is spent in calculating the distance, you could speed it up by revising that.

I think you could improve it quite a bit with a better paper detector. I'll have a quick go.

**Comment by CanadianHusky** [comment]
Wow! 
Your knowledge and your commitment to support users of libvips is truly impressive.
The python version is fully sufficient. I can take it from here. 
The memory saving improvement is significant and speed is 22% faster too.

If I may comment; 
the libvips library is obviously extremely powerful as you just proved and has many low level functions that can be used as building blocks to create a custom function/filter for almost any type of requirement. The problem for 'regular' programmers that want to use libvips, although maybe experienced on general programming or business apps is that it would have taken weeks of studying and experimenting with the library to come with the ways you calculate scale, offset, lut in your example. 
Therefore I appreciate not only the time and effort you invested in the library itself, but also answering questions so promptly and concise here.

**Comment by jcupitt** [comment]
Ah it's just basic image processing. To improve it, I would look at doing a gaussian blur to remove low frequency artefacts (the shadows and folds), and use dE76 to find pixels close to paper white.

**Comment by jcupitt** [comment]
Here's a better background remove filter:

![x](https://user-images.githubusercontent.com/580843/76142332-b5b8ba80-6064-11ea-9e8c-24231c66b80c.jpg)

It's made with this nip2 workspace:

www.rollthepotato.net/~john/clean.ws

It removes low frequences (ie. paper folds etc.), stretches the contrast range, finds pixels close to white in CIELAB and moves them to white, and boosts saturation.

**Comment by jcupitt** [comment]
Here's the improved filter in python:

```python
#!/usr/bin/python3

import sys 
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

# aim for 250 for paper with low freq. removal
# ink seems to be slightly blueish
paper = 250
ink = [150, 160, 170]

# remove low frequencies .. don't need huge accuracy
low_freq = image.gaussblur(20, precision="integer")
image = image - low_freq + paper

# pull the ink down
ink_target = 30
scale = [(paper - ink_target) / (paper - i) for i in ink]
offset = [ink_target - i * s for i, s in zip(ink, scale)]
image = image * scale + offset

# find distance to white of each pixel ... small distances go to white
white = [100, 0, 0]
image = image.colourspace("lab")
d = image.dE76(white)
image = (d < 12).ifthenelse(white, image)

# boost saturation (scale ab)
image = image * [1, 2, 2]

image.write_to_file(sys.argv[2])
```

It's about 10x slower, but it's noticably better, IMO.

**Comment by CanadianHusky** [comment]
On some input files the processing time is irrelevant, even if it takes 10
minutes because there is no original to rescan and correct. Having a
maximum quality filter like this as an option is extremely useful when the
primary concern is quality.
Thank you very much.

**Comment by CanadianHusky** [comment]
Looking at the result closer, it seems the libvips library was really meant
to be used for such image cleanup work.
I inspected the result closer and would not have expected that level of
correction is possible without loosing fine detail and no distortion in
objects that need to be preserved.
I will experiment with the parameters of this function to see how well it
behaves for other types of scans.
The way your last script cleaned fold marks and dirt, without killing
actual objects is really amazing.

**Comment by jcupitt** [comment]
nip2 is useful for tuning these things, if you've not tried it. There's a win binary here:

https://github.com/libvips/nip2/releases/tag/v8.7.0

Load `clean.ws` I linked above, then drag an image into A1 to process it. Double-click on a thumbnail to open a view window. You can drag sliders to adjust all the parameters of the filter, and watch each image in the process change.
