### ISSUE TITLE
.Net use example for replacing colors

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1568]
Hello,

Can someone please share the the Netvips .NET binding equivalent of this code taken from

https://github.com/libvips/libvips/issues/884

Is there a link with more advanced .Net use example other than the 'Getting Started' page at https://kleisauke.github.io/net-vips/tutorial/getting_started.html

thank you
```
require 'vips'

image = Vips::Image.new_from_file ARGV[0], access: :sequential

# the colour we search for as an RGB triple 
match = [40, 100, 90]

# find  euclidean distance between each RGB pixels in the input and our match
# colour
distance = Vips::Image.sum(((image - match) ** 2).bandsplit) 

# swap pixels more than 50 away for white
image = (distance > 50 ** 2).ifthenelse([255, 255, 255], image)

image.write_to_file ARGV[1]
```

**Comment by jcupitt** [comment]
Hello, if you need C# code, I'd ask on the net-vips issue tracker.

**Comment by CanadianHusky** [comment]
Understood. Thank you.
