### ISSUE TITLE
Question about compiling?

### ISSUE THREAD

**Issue by diuming** [libvips/libvips#1569]
make[2]: Nothing to be done for `all-am'.
Does it be complete compiled?
thx

**Comment by jcupitt** [comment]
Hello @diuming,

Could you give some more information, please? What are you trying to do?

**Comment by diuming** [comment]
@jcupitt thanks for replying

I'm trying to compile `vips` as static library on Mac.
there are no errors. except `make[2]: Nothing to be done for all-am`.
I can also install vips static library using `make install`. but more `Nothing to be done for...` appear.
```
PKG_CONFIG_PATH
lcms-2.9(static library)
glib-2.64.0(static library)
orc-0.4.31(static library)
jpeg-9d(static library)
tiff-4.1.0(static library)
fftw-3.3.8(static library)

./configure LDFLAGS="-framework Foundation" --prefix=/dir/vips-8.9.1 \
--with-expat=/dir/expat-2.2.9 \
--with-zlib-includes=/dir/zlib-1.2.11/include --with-zlib-libraries=/dir/zlib-1.2.11/lib \
--enable-shared=no
```
[make_log.txt](https://github.com/libvips/libvips/files/4306707/make_log.txt)

**Comment by diuming** [comment]
@jcupitt 

macOS 10.15.3
I don't install `build-essential` on my macOS. does it the root cause?
thx

**Comment by jcupitt** [comment]
Your `make.log` looks OK, I think. Don't you see installed files? I'll try on my mac.

**Comment by jcupitt** [comment]
I ran:

```
cd GIT/libvips
git pull
rm -rf ~/vips
./autogen.sh --prefix=/Users/john/vips --disable-shared
make
make install
```

And in `~/vips/lib` I see:

```
$ ls ~/vips/lib
girepository-1.0 libvips-cpp.la   libvips.la
libvips-cpp.a    libvips.a        pkgconfig
```

So I think it's working.

**Comment by diuming** [comment]
@jcupitt thanks for help, I got it! ^_^
