### ISSUE TITLE
Investigate usage of libavif for AVIF support

### ISSUE THREAD

**Issue by renchap** [libvips/libvips#1570]
Currently AVIF support is done using `libheif`.

A new library, `libavif` is being developped to handle this format and may be a better alternative: https://github.com/AOMediaCodec/libavif

`libheif` has a problematic license/patents (see #1519). I did not investigate it further, but `libavif` might fix this.
`libavif` seems to have a lot of work ongoing on the performance side, and will probably be faster and lighter than `libheif`, which is critical when you want to serve dynamically resized images in AVIF format (coming soon in Chrome & Android). Note: I did not ran any benchmarks on this point.

 A potential drawback of using `libavif` is distro's support, as it is younger and not yet in any major distros.

Some additional benchmarks / data about AVIF: https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4

**Comment by jcupitt** [comment]
Sounds interesting, let's experiment with it. It looks like the existing libheif loader could be adapted without much work.

**Comment by gunta** [comment]
[Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=960620) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863) started implementing support for AVIF images so we expect to see a sudden huge need increase in a few weeks.

You can already test AVIF image files in [Chrome Canary](https://www.google.com/chrome/canary/) by starting with the `--enable-features=AVIF` flag enabled.

Sample images for testing [here](https://resources.link-u.co.jp/avif/encoded/).

The recommended standard:

| Type           | Content-Type        | File Extension |
|----------------|---------------------|----------------|
| Static Image   | `image/avif`          | `avif`           |
| Animated Image | `image/avif-sequence` | `avifs`          |

**Comment by Tom910** [comment]
Now chrome released support the AVIF - https://jakearchibald.com/2020/avif-has-landed/

**Comment by volym3ad** [comment]
Any ETA for this? Is it already in roadmap?

**Comment by lovell** [comment]
The next release of libheif has build flags to prevent the inclusion of any HEVC-related code and therefore the patent problems originally reported in this issue - see https://github.com/strukturag/libheif/pull/337

libheif can be compiled with support for one or more of the aom, dav1d and rav1e coders.

The aom+libheif+libvips combo is now continuously fuzz tested - see https://github.com/google/oss-fuzz/pull/4463

The precompiled libvips binaries for Windows will soon include aom+libheif - see https://github.com/libvips/build-win64-mxe/issues/13

Is the inclusion of libavif support in libvips still something that is required given these recent advances?

**Comment by jcupitt** [comment]
I agree, I think this issue is now covered. I'll close.

**Comment by Raicuparta** [comment]
Trying to resurrect this. If I understand correctly, one current advantage of libavif is that it supports image sequences, while libheif doesn't. Could this be another reason to use libavif instead of libheif?

**Comment by jcupitt** [comment]
libvips supports AVIF image sequences with libheif:

```
$ vips copy silver-gear-cogs-animation-5.gif[n=-1] x.avif
```

To make this:

http://www.rollthepotato.net/~john/x.avif

Though it's missing support for delay metadata I think.

**Comment by zhifengzhuang** [comment]
> libvips supports AVIF image sequences with libheif:
> 
> ```
> $ vips copy silver-gear-cogs-animation-5.gif[n=-1] x.avif
> ```
> 
> To make this:
> 
> http://www.rollthepotato.net/~john/x.avif
> 
> Though it's missing support for delay metadata I think.
@jcupitt Hello!Will this problem be solved by libheif in future?I get a static avif image when convert gif to avif.

**Comment by jcupitt** [comment]
Hi @zhifengzhuang,

I think the animation support in AVIF has only just been agreed and libheif does not yet support it. When libheif has this feature, we can add support to libvips.

(I've not checked for a while, perhaps I'm out of date)

**Comment by zhifengzhuang** [comment]
@jcupitt Thanks.I got it.
