### ISSUE TITLE
Question about vips7compat.h?

### ISSUE THREAD

**Issue by diuming** [libvips/libvips#1573]
Hi,

I take a look `vips.h`. It's very difference between vips7.x and vips8.x. 
The functions(im_open, im_shrink, im_close, im_add_callback.....) almost move to `vips7compat.h`
so, does it be deprecated in the future(it's important for me, because, i'm a swift user)?

I read the latest document on web that It start from `vips_image_new_from_file`. 
I practiced.  please refer to `testVIPS swift` function.
thanks

testVIPS.swift(I use swift to direct call vips c functions.)
```
public func testVIPS(atPath path: String) {
    vips_init("Testing")
    guard let image = vips_image_new_from_file(path, NULL) else {
    //guard let inImage = im_open(path, "rs") else {
        print("OMG!")
        return
    }
    print("image: \(image)")
}

===compiler complaint===
error: 'vips_image_new_from_file' is unavailable: Variadic function is unavailable
guard let image = vips_image_new_from_file(path, NULL) else {
```

**Comment by jcupitt** [comment]
Hello @diuming,

Yes, the vips8 C API uses varargs a lot. You'll need to use a different API from Swift.

Can you use C++? The vips8 C++ API does not use varargs.

Otherwise, you will need to use the gobject API. This is awkward for humans to use, but good for language bindings.

**Comment by diuming** [comment]
@jcupitt Ok, I try to use C++. the library is `libvips-cpp.a` right?

**Comment by jcupitt** [comment]
Yes, that's right.

**Comment by diuming** [comment]
@jcupitt  thanks
