### ISSUE TITLE
heifload: bad image dimensions on decode

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1574]
Good day
I have some weired behavior when trying to generate a thumbnail out of a heic image, maybe someone can help me out here.

when I try this command:
/vipsthumbnail --size=900x900 20200303_150422.heic --vips-info
everything works as expected

when I try this command:
/vipsthumbnail --size=324x324 20200303_150422.heic --vips-info

I got following error:
(vipsthumbnail:15141): VIPS-WARNING **: 15:58:00.237: error in tile 0 x 120./vipsthumbnail: unable to thumbnail 20200303_150422.heic
heifload: bad image dimensions on decode
heifload: bad image dimensions on decode
heifload: bad image dimensions on decode
heifload: bad image dimensions on decode

Do we need to check something before generating the thumbnail?
the original image exif is:
original image is 
Exif Image Width                : 4608
Exif Image Height               : 3456

**Comment by jcupitt** [comment]
Hello @daverupp,

It's working for me with my test images, eg.:

```
$ vipsthumbnail Example1.heic -s 324x324
```

Could you share the image that's failing for you? Also, which libvips version, which platform, how did you make the binary etc.

**Comment by daverupp** [comment]
Sorry for the poor information...
we build on ubuntu 18.04 libvips 8.9.0 built from source. 

Please see attached the HEIC image, that is producing errors... 
(actually it is taken by a Samsung Galaxy with the picture format HEIF/HEIC) This is a new setting you can choose for android 10 to save some space... so I think, this will be soon quite a standard and would be super cool, if you will find out something about that error... thank you so much for looking into it.
(Sorry, it has to be a zip...)

[20200313_115653.heic.zip](https://github.com/libvips/libvips/files/4329578/20200313_115653.heic.zip)

**Comment by jcupitt** [comment]
Thanks! Yes, I see an error too. I'll have a look.

**Comment by jcupitt** [comment]
It looks like a libheif bug, something to do with fetching thumbnails from rotated images, perhaps? I tried git master libheif and that fails too, so you may have found a current issue.

I'll try to prepare a bug report for the very helpful libheif maintainer.

**Comment by jcupitt** [comment]
Submitted libheif issue for reference: https://github.com/strukturag/libheif/issues/211

**Comment by daverupp** [comment]
Thank you very much for taking care.
So, I close here the thread and I hope, libheif maintainers will have a look into this.

all the best
dave

**Comment by jcupitt** [comment]
Update: the sample image is from a clearly broken HEIC encoder, so it's a wontfix from the libheif maintainers.

The phone manufacturers should perhaps be notified that their firmware is producing incorrect images.

**Comment by lovell** [comment]
Good to see Samsung are keeping up their reputation as provider of buggy image encoding software.

https://www.google.com/search?q=Samsung+invalid+SOS+parameters

**Comment by jcupitt** [comment]
Hehe I didn't like to point :) What if Samsung and Adobe collaborated on a product? It could be truly extraordinary.

**Comment by jcupitt** [comment]
Thinking about this again, we could add a simple workaround to `thumbnail` to stop it using the embedded HEIC thumbnail if the aspect ratio looks incorrect. It'd be much slower if the thumbnail was broken, but at least you'd get an image.

Does that sounds reasonable?

**Comment by jcupitt** [comment]
This patch seems to work for me, if anyone would like to test it:

```
diff --git a/libvips/foreign/heifload.c b/libvips/foreign/heifload.c
index 772420ab..9ade3504 100644
--- a/libvips/foreign/heifload.c
+++ b/libvips/foreign/heifload.c
@@ -18,6 +18,8 @@
  * 	- revise for new VipsSource API
  * 10/5/20
  * 	- deprecate autorotate -- it's too difficult to support properly
+ * 31/7/20
+ * 	- block broken thumbnails, if we can
  */
 
 /*
@@ -277,6 +279,71 @@ vips_foreign_load_heif_get_flags( VipsForeignLoad *load )
 	return( VIPS_FOREIGN_SEQUENTIAL );
 }
 
+/* We've selcted the page. Try to select the associated thumbnail instead, 
+ * if we can.
+ */
+static int
+vips_foreign_load_heif_set_thumbnail( VipsForeignLoadHeif *heif )
+{
+	double main_aspect;
+	double thumb_aspect;
+	heif_item_id thumb_ids[1];
+	int n_thumbs;
+	struct heif_image_handle *thumb_handle;
+	struct heif_image *thumb_img;
+	struct heif_error error;
+
+	/* We need the main image aspect ratio so we can sanity-check
+	 * the thumbnail.
+	 */
+	main_aspect = (double) 
+		heif_image_handle_get_width( heif->handle ) /
+		heif_image_handle_get_height( heif->handle );
+
+	n_thumbs = heif_image_handle_get_list_of_thumbnail_IDs( 
+		heif->handle, thumb_ids, 1 );
+
+	if( n_thumbs > 0 ) {
+		error = heif_image_handle_get_thumbnail( heif->handle,
+			thumb_ids[0], &thumb_handle );
+		if( error.code ) {
+			vips__heif_error( &error );
+			return( -1 );
+		}
+
+		/* Just checking the width and height of the handle isn't
+		 * enough -- we have to decode it and test the decoded
+		 * dimensions. 
+		 */
+		error = heif_decode_image( thumb_handle, &thumb_img,
+			heif_colorspace_RGB, 
+			heif_chroma_interleaved_RGB,
+			NULL );
+		if( error.code ) {
+			vips__heif_error( &error );
+			return( -1 );
+		}
+
+		thumb_aspect = (double) 
+			heif_image_get_width( thumb_img, 
+				heif_channel_interleaved ) /
+			heif_image_get_height( thumb_img, 
+				heif_channel_interleaved );
+
+		VIPS_FREEF( heif_image_release, thumb_img );
+
+		if( fabs( main_aspect - thumb_aspect ) < 0.1 ) {
+			VIPS_FREEF( heif_image_handle_release, heif->handle );
+			heif->handle = thumb_handle;
+		}
+		else {
+			VIPS_FREEF( heif_image_handle_release, thumb_handle );
+		}
+	}
+
+	return( 0 );
+}
+
 /* Select a page. If thumbnail is set, select the thumbnail for that page, if
  * there is one.
  */
@@ -307,26 +374,8 @@ vips_foreign_load_heif_set_page( VipsForeignLoadHeif *heif,
 		}
 
 		if( thumbnail ) {
-			heif_item_id thumb_ids[1];
-			int n_thumbs;
-			struct heif_image_handle *thumb_handle;
-
-			n_thumbs = heif_image_handle_get_list_of_thumbnail_IDs( 
-				heif->handle, thumb_ids, 1 );
-
-			if( n_thumbs > 0 ) {
-				error = heif_image_handle_get_thumbnail( 
-					heif->handle,
-					thumb_ids[0], &thumb_handle );
-				if( error.code ) {
-					vips__heif_error( &error );
-					return( -1 );
-				}
-
-				VIPS_FREEF( heif_image_handle_release, 
-					heif->handle );
-				heif->handle = thumb_handle;
-			}
+			if( vips_foreign_load_heif_set_thumbnail( heif ) )
+				return( -1 );
 
 			/* If we were asked to select the thumbnail, say we
 			 * did, even if there are no thumbnails and we just
```

**Comment by jcupitt** [comment]
... and merged to master after some revision. It feels like a safe change, and should be simple to remove if necessary. The workaround will be in 8.10.

**Comment by igorescobar** [comment]
There is definitely something up with the current support. Like, If I try to resize a `heif` file using libvips `.resize({ width: 100 })` I get the `bad image dimensions on decode` error and if I do the same with `.resize({ width: 600 })` it works. The same happens with `.resize({ height })` and `.resize({ width: 100, height: 100 })`. Some dimensions just get rejected not sure why.
