### ISSUE TITLE
Question: how to implement contrast limited adaptive histogram equalization

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1576]
I would like to implement Imagemagick's 

`-clahe  widthxheight{%}{+}number-bins{+}clip-limit{!} `
https://imagemagick.org/script/command-line-options.php#clahe

operator with Netvips.
Is this possible by using the low level functions ?
A python example would be wonderful.
thank you

**Comment by jcupitt** [comment]
Hello @CanadianHusky, you're in luck, it's there already:

https://libvips.github.io/libvips/API/current/libvips-histogram.html#vips-hist-local

Try setting `max_slope` to `hist_local`.

**Comment by CanadianHusky** [comment]
The command works as explained in the API Doc but performance of this function is quite different than the other functions I tested so far.

vipsimg is a 9000x5700 pixel rgb jpg.
`Dim result As Image = vipsimg.HistLocal(100, 100, 25)`
44 seconds execution time with 100% CPU time on all cores. Very little memory usage but a lot of disk IO. 

The following does the -clahe plus a gauss blur, colorspace changes and dithering and finishes in 35 seconds on the same input file.

`magick "input.jpg" -clahe 100x100+32+3 -blur 6x2 -colorspace gray +dither -colors 2 -normalize "output.jpg"
`

to compare apples to apples, the -clahe command alone
`magick "input.jpg" -clahe 100x100+32+3 "output.jpg"`
= 18 seconds

No big deal. The other functions I use are around 3 to 5 times faster with libvips.

**Comment by jcupitt** [comment]
Huh that is slow, I wonder why? Even if you drop the window to a tiny 5x5 it's still pretty bad. It probably needs a bit of tuning.

**Comment by kleisauke** [comment]
@CanadianHusky I haven't really tried to benchmark this, I'll try to do this today. Could you confirm that the `operation flags:` are `sequential` within this pre-release? For example, I now see:
```
$ vips.exe hist_local
local histogram equalisation
usage:
   hist_local in out width height [--option-name option-value ...]
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
   width        - Window width in pixels, input gint
                        default: 1
                        min: 1, max: 10000000
   height       - Window height in pixels, input gint
                        default: 1
                        min: 1, max: 10000000
optional arguments:
   max-slope    - Maximum slope (CLAHE), input gint
                        default: 0
                        min: 0, max: 100
operation flags: sequential
```

> I also notived that 8.9.2 dev version is reported as April 21. Maybe something isn't updated internally. I was expecting a May date there.

That's the date of the changelog, see:
https://github.com/libvips/libvips/blob/ffa10eb1483b742344e84edc6563a3f21d7fadef/configure.ac#L29

**Comment by CanadianHusky** [comment]
Yes, operation flag is sequential for me as well 

![image](https://user-images.githubusercontent.com/35332003/81933647-68257480-95f6-11ea-822e-b2d117587953.png)

**Comment by jcupitt** [comment]
I had a quick look, and I think libvips and magick are implementing different algorithms.

https://www.imagemagick.org/discourse-server/viewtopic.php?t=35285

If you run:

```
$ time magick input.jpg -clahe 100x100+256+3 magick.jpg
real	0m16.904s
user	0m50.584s
sys	0m3.139s
```

IM is splitting the image into non-overlapping 100x100 pixel tiles and computing a histogram for each tile. For each input pixel, it maps it through the local histogram, then does bilinear interpolation to hide tile boundaries. It uses the 3 to set the maximum contrast change. Ideally, the 100x100 should have the same aspect ratio as the image, or you'll get strange effects along the image edges.

The libvips equivalent:

```
$ time vips hist_local input.jpg vips.jpg 100 100 --max-slope 3
real	0m28.764s
user	1m46.851s
sys	0m0.233s
```

Works with a rolling 100x100 pixel window. For every pixel, it computes the histogram of the 100x100 neighborhood and uses that custom hist to adjust the contrast. To stop this being appallingly slow, it computes the histogram as a series of deltas, so at each point it will only add and remove 100 pixels from the hist (not recompute all 10,000).

Anyway: the libvips one is  slower, but *much* more accurate, and should not suffer from any strange edge effects.

**Comment by jcupitt** [comment]
Here's an example (click to zoom in):

![x](https://user-images.githubusercontent.com/580843/81937000-e845dd00-95ea-11ea-9248-44b930bee63e.jpg)

That's original, `magick ~/pics/bigjupio.jpg -clahe 100x100+256+3 magick.jpg` and `vips hist_local ~/pics/bigjupio.jpg vips.jpg 100 100 --max-slope 70`.

You'll see that the magick one has nasty vertical banding (caused by the 100x100 tiles they use), and fails to enhance a lot of details, for example, the blue around Io.

**Comment by jcupitt** [comment]
Having said all that, the libvips one has not been tuned much and I'm sure you could make it quicker with some time in kcachegrind etc.

**Comment by CanadianHusky** [comment]
Your statement that IM and Vips have different CLAHE algorithm implemented is correct. After testing and comparing IM, Vips and openCV for speed and quality over the last few weeks - I eventually settled with openCV. 

Here the algorithm explained from openCV from http://amroamroamro.github.io/mexopencv/opencv/clahe_demo_gui.html

...So to solve this problem, adaptive histogram equalization is used. Here image is divided into small blocks called "tiles" (TileGridSize is 8x8 by default in OpenCV). Then each of these blocks are histogram equalized as usual. So in a small area, histogram would confine to a small region (unless there is noise). If noise is there, it will be amplified. To avoid this, contrast limiting is applied. If any histogram bin is above the specified contrast limit (by default 40 in OpenCV), those pixels are clipped and distributed uniformly to other bins before applying histogram equalization. After equalization, to remove artifacts in tile borders, bilinear interpolation is applied.

The trick for me was to apply the CLAHE function on the Luminosity channel of the image and not on the whole RGB data. That made significant improvement in the types of images I work with. That tip was from 
https://stackoverflow.com/questions/24341114/simple-illumination-correction-in-images-opencv-c

**Comment by jcupitt** [comment]
That's the same as the imagemagick algorithm. It's a bit quicker, but you'll see a range of quality problems, like the banding above. Of course if it works for your case, that's great.

**Comment by CanadianHusky** [comment]
You are correct about quality problems when the input image is somthing like bigjupio.jpg but in my case, no matter what parameters I tried using awesome nips2 app I cannot get enough difference between the areas I want.

With openCV and IM I get almost identical results, main difference that IM is about 10x to 20x slower.

from the input image above the following pipeline
clahelimit = 6;
tilesize = 4;
cv1._SmoothGaussian(3, 3, 0.6, 0.6); //kernel size 3x3, sigma x/y 0.6,0.6
CvInvoke.CvtColor(cv1, cv2, CvEnum.ColorConversion.Bgr2Lab, 0); //clahe filter must be applied on luminance channel or grayscale image
CvInvoke.CLAHE(cv2(0), clahelimit, New Size(tilesize, tilesize), cv1); 

produces a near perfect result where I can identify the filled areas with simple thresholding
![image](https://user-images.githubusercontent.com/35332003/82033163-02dc8c80-96a5-11ea-8ca4-d0cd7cd5d3ab.png)

the equivalent vips command I use is
vipsimg = vipsimg.Gaussblur(3, 0.6)
vipsimg = vipsimg.Colourspace("b-w").HistLocal(100, 100, 50)

using nips2 I tried a lot of combinations for tilesize and maxslope but I either do not get enough contrast difference, or it overshoots and amplifies the unwanted noise

.HistLocal(100, 100, 50)
![image](https://user-images.githubusercontent.com/35332003/82033638-ae85dc80-96a5-11ea-9ec9-4296b16d556b.png)

.HistLocal(25, 25, 50)
![image](https://user-images.githubusercontent.com/35332003/82033729-d5441300-96a5-11ea-91d8-b371dc9030ac.png)
