### ISSUE TITLE
Installation of libvips on aws ec2 linux centos server.

### ISSUE THREAD

**Issue by husaindevelop** [libvips/libvips#1577]
Please be informed that we are trying to convert openslide (.svs, .tiff) formats in .dzi format for viewing it in our whole slide image viewer. We found libvips and its binding in php (php-libvips that enables conversion in .php language server side) the best option to convert the the files in .dzi. Unfortunately as part of the first step, we are unable to install libvips library on our aws ec2 linux centos server based on installation instructions given by you. Guidance on how to move forward would be greatly appreciated. Thanking you in advance

**Comment by jcupitt** [comment]
I updated the aws dockerfile to include openslide support:

https://github.com/jcupitt/docker-builds/tree/master/libvips-amazonlinux2

That builds libvips to /usr/local/vips. tar that up, then untar on your server to install (or you can just do the build on your server, of course).

**Comment by jcupitt** [comment]
(hello from stackoverflow, by the way!)

**Comment by husaindevelop** [comment]
First of all, thanks for replying.  Docker is certainly a new concept for me. I went through couple of articles and found that i need to install docker in my server. Shall install it soon

Once installation is done, should i just need to run these commands to install libvips.
docker pull amazonlinux:2
docker build -t libvips-amazonlinux:2 .

**Comment by jcupitt** [comment]
Docker will let you make a copy of your server environment on any machine. You can build a binary  there and upload it to your server for installation.

Alternatively, you can build on your server itself, if that's easier. If you build on the server, you won't need docker.

**Comment by husaindevelop** [comment]
1.Docker successfully installed. 
2.Ran the following commands:
docker pull amazonlinux:2
docker build -t libvips-amazonlinux:2 .

Got the message of successfully built. When i reentered the command "docker build -t libvips-amazonlinux:2 ", We got the following messages:
Step 1/15 : FROM amazonlinux:2
 ---> 484b3aa1f601
Step 2/15 : RUN yum update -y   && yum groupinstall -y "Development Tools"      &                                            & yum install -y wget tar
 ---> Using cache
 ---> f4a2fb66ad3e
Step 3/15 : RUN yum install -y  libjpeg-devel   libpng-devel    libtiff-devel   l                                            ibgif-devel
 ---> Using cache
 ---> 635836230142
Step 4/15 : RUN yum install -y  libpng-devel    glib2-devel     libjpeg-devel   e                                            xpat-devel      zlib-devel      orc-devel       lcms2-devel     libexif-devel   l                                            ibgsf-devel
 ---> Using cache
 ---> b0528aab35e9
Step 5/15 : RUN yum install -y  https://dl.fedoraproject.org/pub/epel/epel-releas                                            e-latest-7.noarch.rpm
 ---> Using cache
 ---> 60ead4f08563
Step 6/15 : RUN yum install -y  openslide-devel
 ---> Using cache
 ---> 0cab2244812c
Step 7/15 : ENV VIPSHOME /usr/local/vips
 ---> Using cache
 ---> 775eb549fa65
Step 8/15 : ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig
 ---> Using cache
 ---> 02ac0bbdae86
Step 9/15 : ARG WEBP_VERSION=1.0.2
 ---> Using cache
 ---> dcc659016060
Step 10/15 : ARG WEBP_URL=https://storage.googleapis.com/downloads.webmproject.or                                            g/releases/webp
 ---> Using cache
 ---> cd8a75d381b6
Step 11/15 : RUN cd /usr/local/src      && wget ${WEBP_URL}/libwebp-${WEBP_VERSIO                                            N}.tar.gz       && tar xzf libwebp-${WEBP_VERSION}.tar.gz       && cd libwebp-${W                                            EBP_VERSION}    && ./configure --enable-libwebpmux --enable-libwebpdemux        -                                            -prefix=$VIPSHOME       && make V=0     && make install
 ---> Using cache
 ---> 3b58943839e8
Step 12/15 : ARG VIPS_VERSION=8.9.1
 ---> Using cache
 ---> 8b50c92b7a98
Step 13/15 : ARG VIPS_URL=https://github.com/libvips/libvips/releases/download
 ---> Using cache
 ---> 5445fc186824
Step 14/15 : RUN cd /usr/local/src      && wget ${VIPS_URL}/v${VIPS_VERSION}/vips                                            -${VIPS_VERSION}.tar.gz         && tar xzf vips-${VIPS_VERSION}.tar.gz  && cd vip                                            s-${VIPS_VERSION}       && ./configure --prefix=$VIPSHOME       && make V=0     &                                            & make install
 ---> Using cache
 ---> 24855162bab1
Step 15/15 : RUN ls $VIPSHOME/lib
 ---> Using cache
 ---> d93f72ebc112
Successfully built d93f72ebc112

But still folder "/usr/local/vips/" did not get created as mentioned in readme, What's the next process ?

on a sidenote:
during installation, after a message "Successfully built d93f72ebc112" it displayed a particular message:
root@mbracecloud ~]# docker build -t libvips-amazonlinux:2 .libvips
unable to prepare context: unable to evaluate symlinks in context path: lstat /root/.libvips: no such file or directory

**Comment by jcupitt** [comment]
The `docker build` command make the binary inside a container. You'll need to copy the files out of the container so you can upload to your server.

https://docs.docker.com/engine/reference/commandline/cp/

I don't think the command `docker build -t libvips-amazonlinux:2 .libvips` is correct. I would do something like:

```
git clone https://github.com/jcupitt/docker-builds.git
cd docker-builds/libvips-amazonlinux2
docker pull amazonlinux:2
docker build -t libvips-amazonlinux:2 .
id=$(docker create libvips-amazonlinux:2)
docker cp $id:/usr/local/vips - > vips.tar.gz
docker rm -v $id
```

**Comment by husaindevelop** [comment]
alternatively, is it possible we directly build onto the server.

**Comment by husaindevelop** [comment]
Is it possible to run libvips right from docker container

**Comment by jcupitt** [comment]
Yes, those command will copy the files out of the container.

**Comment by husaindevelop** [comment]
You mean this command
git clone https://github.com/jcupitt/docker-builds.git
cd docker-builds/libvips-amazonlinux2
docker pull amazonlinux:2
docker build -t libvips-amazonlinux:2 .
id=$(docker create libvips-amazonlinux:2)
docker cp $id:/usr/local/vips - > vips.tar.gz
docker rm -v $id

**Comment by jcupitt** [comment]
Yes, have a look at the docker documentation. `create` makes a new temporary container from the image, `cp` copies out the files, `rm` removes the temporary container.

**Comment by husaindevelop** [comment]
Well i did go through the documentation.  I ran the above commands as stated by you. Docker container seems to have been created based on the message "Successfully built d93f72ebc112" displayed in the cli. 
On running the below command, which should copy the container's files to /usr/local/vips $id=$(docker create libvips-amazonlinux:2)
docker cp $id:/usr/local/vips - > vips.tar.gz
It displayed no message on running the command, and folder "vips" was not created as needed.

**Comment by husaindevelop** [comment]
Thanks for prompt reply Mr. John Cuppit. Okay, understood that i need to unzip the vips.tar.gz and upload it to the server. But do i need to again use docker cp command to copy that tar file into server or could i be able to find the .tar file inside my file directories.

**Comment by husaindevelop** [comment]
an update. Found the vips.tar.gz file in /root/docker-builds/libvips-amazonlinux2 folder. Is that the one ?

**Comment by jcupitt** [comment]
It'll be in the directory where you ran the command.

**Comment by husaindevelop** [comment]
Found the vips.tar.gz file in /root/docker-builds/libvips-amazonlinux2 folder. 
Next step: Should i create the vips folder manually in "/usr/local/" and then untar the vips.tar file inside it ?

**Comment by jcupitt** [comment]
It'll make the directory for you. Try:

```
mv vips.tar.gz /usr/local
tar xf vips.tar.gz
```

But that won't be enough to link it to your PHP, of course. How do you plan to manage the deployment?

**Comment by husaindevelop** [comment]
Thanks, did it, the /usr/local/vips is up and full of libvips files. as a first try could i now use libvips command to convert .svs file to .dzi using cli ? Regarding php deployment, i was thinking phpvips binding could do my job or alternatively i could go for shell_exec php command to execute cli command through the server.  

Since we come this far, i would like to tell you why we need this lib in php. 
Our clienteles "microbiologists" would upload a .tiff, .svs, .ndpi file from our application
On backend, we would use your lib to process them into .dzi file to make it compatible for openseadragon viewer.

Inputs from you would be valuable ?

**Comment by jcupitt** [comment]
Yes, you should be able to. It comes with a wrapper script, try:

```
/usr/local/vips/bin/vips-8.9 vips --version
```

You'll need to get the various support libraries installed on the server too.

**Comment by husaindevelop** [comment]
Got an error on running this command:
/usr/local/vips/bin/vips-8.9 vips --version
vips: error while loading shared libraries: libgsf-1.so.114: cannot open shared object file: No such file or directory

**Comment by jcupitt** [comment]
Yes, you need to install the support libraries. Keep adding them with yum until it works, eg. `yum install libgsf`.

**Comment by husaindevelop** [comment]
Installion underway

**Comment by jcupitt** [comment]
Some friends of mine made easyzoom: https://easyzoom.com/ That's libvips and openseadragon.

I would stick to just shell_exec for now. 

You can call the library directly from PHP, and it'll be a bit quicker and easier, but installation would be harder. I would find someone who's knowledgeable about PHP admin.

**Comment by husaindevelop** [comment]
libgsf got installed, but the next dependency liborc-0.4.so.0 error still shows despite installing it.

Here is the output of cli command run. 
Package orc-0.4.26-1.el7.i686 already installed and latest version
Nothing to do
[root@mbracecloud vips]# /usr/local/vips/bin/vips-8.9 vips --version
vips: error while loading shared libraries: liborc-0.4.so.0: cannot open shared object file: No such file or directory

**Comment by jcupitt** [comment]
You might need `orc-devel`.

**Comment by husaindevelop** [comment]
Installed all the vips dependencies and ran the dzsave to convert .TIF to dzi file. It worked, but .svs file is failing. Displays error "VipsForeignLoad: "test.svs" is not a known file format"

**Comment by jcupitt** [comment]
You must have another libvips installed on your server somewhere. Perhaps one you installed with yum is still there?

**Comment by husaindevelop** [comment]
Yes, maybe, i'm not sure. I tried many times installing libvips seeing your readme before contacting you. How do i uninstall it.

**Comment by jcupitt** [comment]
Just with `yum`, unless you did anything unusual.

**Comment by husaindevelop** [comment]
I don't get you. I remember i used this command "sudo yum install libvips-dev", but it did not end in success.

**Comment by husaindevelop** [comment]
I did yum remove libvips-dev, but it does not find the package.

**Comment by husaindevelop** [comment]
Just remembered, docker container is still not deleted. Should i do it ?

**Comment by husaindevelop** [comment]
Could there be any conflict with docker-builds where i originally got my vip.tar.

**Comment by husaindevelop** [comment]
Hi cuppit, good morning, sure you are fine and back at work. Take care of yourself and family against pandemic virus threatening all of us.

Thank you so very much for guiding through the process implementing libvips. Configuration was successful, but obtaining desired outcome failed. Going by your observation last night that there could be possible conflict with already existing lib, we went ahead flushing out from docker downwards and rebuilt the entire environment brick by brick. But then the outcome was what was before. 

While appreciating your consistent support drawing upon your valuable time and effort, we await its continuity leading to the desired outcome where we are able to convert .svs file into .dzi file.

Looking forward.

**Comment by jcupitt** [comment]
Try this:

```
$ docker run -it --rm libvips-amazonlinux:2
bash-4.2# /usr/local/vips/bin/vips-8.9 vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   attach-associated - Attach all asssociated images, input gboolean
			default: false
   level        - Load this level from the file, input gint
			default: 0
			min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
			default: false
   associated   - Load this associated image, input gchararray
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
			default: false
   access       - Required access pattern for this file, input VipsAccess
			default: random
			allowed: random, sequential, sequential-unbuffered
   fail         - Fail on first error, input gboolean
			default: false
```

If that works, you have a working libvips inside the docker container. You just need to copy it into your server.

**Comment by husaindevelop** [comment]
Thanks, shall check it and update you.

**Comment by husaindevelop** [comment]
Below is the output i got after running the said commands
docker run -it --rm libvips-amazonlinux:2               
bash-4.2# /usr/local/vips/bin/vips-8.9 vips --version
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020
bash-4.2# /usr/local/vips/bin/vips-8.9 vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   attach-associated - Attach all asssociated images, input gboolean
                        default: false
   level        - Load this level from the file, input gint
                        default: 0
                        min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
                        default: false
   associated   - Load this associated image, input gchararray
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
                        default: false
   access       - Required access pattern for this file, input VipsAccess
                        default: random
                        allowed: random, sequential, sequential-unbuffered
   fail         - Fail on first error, input gboolean
                        default: false
bash-4.2#

Is this the file i need to copy out of the container and upload into the server ?
/root/docker-builds/libvips-openslide-alpine/openslide-init.patch

**Comment by jcupitt** [comment]
No, you just need that `vips.tar.gz` file unpacked to `/usr/local`, like we did earlier.

Next, could you try this in your server (not in the docker container):

```
/usr/local/vips/bin/vips-8.9 vips --version
/usr/local/vips/bin/vips-8.9 vips openslideload
```

**Comment by husaindevelop** [comment]
Ran the said commands, got the below output:
[root@xxx vips]# /usr/local/vips/bin/vips-8.9 vips --version
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020
[root@xxx vips]# /usr/local/vips/bin/vips-8.9 vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   attach-associated - Attach all asssociated images, input gboolean
                        default: false
   level        - Load this level from the file, input gint
                        default: 0
                        min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
                        default: false
   associated   - Load this associated image, input gchararray
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
                        default: false
   access       - Required access pattern for this file, input VipsAccess
                        default: random
                        allowed: random, sequential, sequential-unbuffered
   fail         - Fail on first error, input gboolean
                        default: false

**Comment by jcupitt** [comment]
OK, so it should be working. That's odd. Could you try with this SVS file:

http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/

I see:

```
$ /usr/local/vips/bin/vips-8.9 vipsheader CMU-1.svs 
CMU-1.svs: 46000x32914 uchar, 4 bands, srgb, openslideload
```

**Comment by husaindevelop** [comment]
I'm trying the command with CMU-1-Small Region file, shall update you shortly.

**Comment by husaindevelop** [comment]
Worked. Objective accomplished, .svs converted in .dzi. The culprit was the .svs file i was earlier using. It would have been corrupted. My bad. anyways Heartfelt thanks Mr.John for guiding me through this whole process which almost looked alien to me.  

Now to the next step
I'm moving forward to using php command shell_exec to execute the same command i ran in cli. Shall update you as soon as i do it.
