### ISSUE TITLE
Question: Is it possible to create TIFF multi-channel image?

### ISSUE THREAD

**Issue by diuming** [libvips/libvips#1580]
Is it possible to create TIFF multi-channel image?
like photoshop
![cc](https://user-images.githubusercontent.com/39903550/77034957-4472f300-69e6-11ea-8426-070b7eb4dff4.png)

the `multi-channel` not `multi-page`
thanks

ex
1.tiff, 2.tiff, 3.tiff, 4.tiff, 5.tiff, 6.tiff (all 8bit gray) -> output multichannel.tiff

**Comment by jcupitt** [comment]
You need `bandjoin`, in case anyone is looking for a solution.
