### ISSUE TITLE
How to get TIFF xres and yres in C++?

### ISSUE THREAD

**Issue by diuming** [libvips/libvips#1581]
I want to get xres and yres in c++.
I can get width and height, but I don't have any ideal for xres and yres?
could you give me a hint, thanks

```
    VImage inImage = VImage::new_from_file(inFile,
                                           VImage::option()->set("access", VIPS_ACCESS_SEQUENTIAL));
    int width = inImage.width();
    int height = inImage.height();
```

**Comment by jcupitt** [comment]
You need `.xres()` and `.yres()`. They give resolution in pixels / mm.

**Comment by diuming** [comment]
@jcupitt thanks! I got it.
