### ISSUE TITLE
how to remove background and tint?

### ISSUE THREAD

**Issue by betorcs** [libvips/libvips#1582]
I have done research and also tried nip2, but I could not get the wanted results. Can you tell me if with vips I can remove background and apply tint remain pixels?

Having JPEG images like this plan:
![cd77125d-552c-4e99-91e1-c46dafce2e57-plan pdf0](https://user-images.githubusercontent.com/1232290/77065062-5ab98880-69bf-11ea-8423-132ede9e0a4c.jpg)

Wanted result:
![d4a5a3a9-9fe7-4cdf-9d9b-cb4bfb6922cd](https://user-images.githubusercontent.com/1232290/77066599-37440d00-69c2-11ea-8790-86bba1b8d9d3.png)
> background transparent and tint

**Comment by jcupitt** [comment]
I had a quick go in nip2:

[clean.zip](https://github.com/libvips/libvips/files/4354846/clean.zip)

Monochrome, threshold, clean, tint.

It makes this:

![clean](https://user-images.githubusercontent.com/580843/77073423-2c4fa380-69e7-11ea-9198-aece3ac707d2.png)

**Comment by betorcs** [comment]
ow @jcupitt  you are very fast... thank you very much. now I'll try to replace that white background to transparent..

I really appreciate your job and vips.

Thank you
