### ISSUE TITLE
Create thumbnail for the smallest dimension

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1583]
Hello
I have a question about generating thumbnails with the --size parameter.
As far as I understand, we have to set the box of the thumbnail by {width}x{height} ... or {width}x

Is it possible, to generate thumbnails for the **smallest dimension**... lets say I define just 320px and libvips will take care to generate thumbnails for landscape (??x320) and for portrait (320x??)

so we have the same quality of generated thumbnails respecting the orientation?

thx for any help

**Comment by jcupitt** [comment]
You're right, this wasn't possible. I added a smartcrop mode to fix this:

```
john@kiwi:~/pics$ vipsthumbnail k2.jpg --size 320 --smartcrop all
john@kiwi:~/pics$ vipsheader tn_k2.jpg
tn_k2.jpg: 320x452 uchar, 3 bands, srgb, jpegload
```

Thanks for the suggestion!

**Comment by daverupp** [comment]
Do you know, when a new Release including latest commits will come?
:)

**Comment by jcupitt** [comment]
Releases are about every six months, so the next one will be June, I'd guess.

**Comment by daverupp** [comment]
Ok. Thanks again for your quick response, and I am looking forward to the new release.
Keep healthy and all the best!
