### ISSUE TITLE
VImage::text() - Is Optimisation necessary?

### ISSUE THREAD

**Issue by DFKSingleton** [libvips/libvips#1584]
For test purposes with my security camera image processing program, I used VImage::text() to write text to my image, so that I could identify which part of the image was which. After successfully completing my tests, to remove unwanted parts of the image, I decided to use valgrind to check for memory leaks and other program problems. To my surprise, the valgrind tool callgrind identified that my program was using over 55% of its time in VImage::text()! In my test image, there were 120 'blobs' that I needed to label. The code that I used to insert the text is the following:
```
/**
 * Marks the image so that the number of the blob is marked next to the blob. Used for diagnostic purposes.
 * @param rImage The image to mark.
 */
void BlobInfoList::numberBlobsInImage(vips::VImage &rImage) {
   for (BlobInfoList::t_cIter iter = begin(); iter != end(); ++iter) {
      using namespace vips;
      char buf[16];
      sprintf(buf, "%d", iter->getBlobNo());
      try {
         VImage label = VImage::text(buf, VImage::option()->set("dpi", 72)->set("font", "sans 12"));
         rImage = rImage.insert(label, iter->getStartX(), iter->getStartY());
      } catch (const VError &er) {
         fprintf(stderr, "VError: %s\n", er.what());
         break;
      }
   }
}
```
I used the graphical tool KCacheGrind to see the output from callgrind. 
![grafik](https://user-images.githubusercontent.com/18052758/77295893-fe1fdb80-6ce6-11ea-8deb-bbf7aa4c40c6.png)
I started my test with an older version of libvips but upgraded to the latest version - vips-8.9.1 with the same results. Running my test program with 'blob numbering' disabled (over an .ini file switch) results in an over 10 times improvement in run time! Because I only used VImage::text() for test purposes, slow the performance is not an issue for me. However I am submitting this as an issue, because it could be helpful for others. 
I hope that I have included enough information, but would be delighted to to let you have my complete test program and test image, it it would help.

**Comment by jcupitt** [comment]
Hello @DFKSingleton,

Interesting that it's so slow. libvips is using pangoft2 to render text, so I guess it's in there somewhere. What platform and version of pangoft2 are you using?

**Comment by DFKSingleton** [comment]
Thanks for the rapid reply. I am using Ubuntu 18.04 LTS, running in a virtual machine under VirtualBox and Windows. I had to install pangoft2 to get libvips to write text, so it should be the latest version. 
`apt list --installed` reports:
    `libpangoft2-1.0-0`
If you would like me to do any tests, let me know. I would be delighted to help if possible.

**Comment by DFKSingleton** [comment]
I have done some more investigation. I have compiled libvips with the -O0 -g3 and debugging enabled options. I have installed the sources for pangoft2 and also compiled and installed them with the same options. I have then run valgrind/callgrind again and inspected the callgrind output with kcachegrind again. After exporting the graph, I get a rather super and long JPG image, showing more or less completely, where the program is spending its time! I attach it below. Sorry for the size!

**Comment by DFKSingleton** [comment]
/home/david/workspace/VipsTestLines/callgrind_output.jpg

**Comment by jcupitt** [comment]
That's a lot of pango. Yes, kcachegrind is a great tool.

**Comment by DFKSingleton** [comment]
Sorry, did not mean to close the issue. It may be that the authors want to do something with the issue.

**Comment by jcupitt** [comment]
If you have time, a complete, standalone test program that shows the issue would be helpful. It'd save me having to make one so I can benchmark too.

**Comment by DFKSingleton** [comment]
No problem! You can have my test program as it stands. What is the best way of sending it to you? The .zip file is some 8MB big (probably too big for github). One small thing: the program is an Eclipse project. Is that OK for you, or should I add a standard Linux ./configure build?

**Comment by jcupitt** [comment]
For testing and benchmarking, you need the smallest program you can make that shows the problem. Ideally only 10 lines or so.

**Comment by DFKSingleton** [comment]
I could not manage 10 lines - but how about 38 lines? See below. This program draws a series of numbers in a grid on a black 3-band image. I used a 3-band image because that is what my original much larger test program did. If you would like and more information or help, please let me know.
```
/**
 * pangotest.cpp
 * Program to test utilisation of pango function through libvips (possible performance problems)
 */

#include <stdio.h>
#include <vips/vips8>

using namespace vips;

int main(int argv, char **argc) {
   printf("VipsPangoTest started.\n");
   clock_t startTicks = clock();
   if (VIPS_INIT(argc[0]))
      vips_error_exit(NULL);

   const int width = 640, height = 480, bufSize = width * height, buf3Size = bufSize * 3, NO_GRID_LINES = 10;
   const int xSpacing = width / NO_GRID_LINES, ySpacing = height / NO_GRID_LINES;
   unsigned char *p3Buf = new unsigned char[buf3Size];
   memset(p3Buf, 0, buf3Size);
   VipsImage *pDiagLineImage = vips_image_new_from_memory_copy(p3Buf, buf3Size, width, height, 3, VIPS_FORMAT_UCHAR);
   VImage diagLineImage(pDiagLineImage);
   delete[] p3Buf;
   for (int y = 0; y < NO_GRID_LINES; y++) {
      for (int x = 0; x < NO_GRID_LINES; x++) {
         char buf[16];
         sprintf(buf, "%d", 1 + x + y * NO_GRID_LINES);
         VImage label = VImage::text(buf, VImage::option()->set("dpi", 72)->set("font", "sans 12"));
         diagLineImage = diagLineImage.insert(label, (x + 1) * xSpacing, (y + 1) * ySpacing);
      }
   }
   diagLineImage.write_to_file("myPangoTestOutput.jpg", NULL);
   vips_shutdown();
   clock_t endTicks = clock();
   printf("VipsPangoTest successfully ended. CPU time = %f ms\n",
         ((float) (endTicks - startTicks)) * 1000 / CLOCKS_PER_SEC);
   return 0;
}

```

**Comment by jcupitt** [comment]
Hey, that's great! I'll have a look, thank you David.

**Comment by jcupitt** [comment]
I changed your program slightly to be:

```c++
/* compile with:
 *
 * g++ -g -Wall txt2.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <stdio.h>
#include <vips/vips8>

using namespace vips;

int main(int argv, char **argc) {
   printf("VipsPangoTest started.\n");
   if (VIPS_INIT(argc[0]))
      vips_error_exit(NULL);

   clock_t startTicks = clock();
   const int width = 640; 
   const int height = 480; 
   const int NO_GRID_LINES = 10;
   const int xSpacing = width / NO_GRID_LINES;
  const int ySpacing = height / NO_GRID_LINES;

   VImage diagLineImage = VImage::black(width, height,
        VImage::option()->set("bands", 3));

   for (int y = 0; y < NO_GRID_LINES; y++) {
      for (int x = 0; x < NO_GRID_LINES; x++) {
         char buf[16];
         sprintf(buf, "%d", 1 + x + y * NO_GRID_LINES);
         VImage label = VImage::text(buf, 
                VImage::option()->set("dpi", 72)->set("font", "sans 12"));
         diagLineImage.draw_image(label, (x + 1) * xSpacing, (y + 1) * ySpacing);
      }
   }
   diagLineImage.write_to_file("myPangoTestOutput.jpg", NULL);
   vips_shutdown();
   clock_t endTicks = clock();
   printf("VipsPangoTest successfully ended. CPU time = %f ms\n",
         ((float) (endTicks - startTicks)) * 1000 / CLOCKS_PER_SEC);
   return 0;
}
```

Though it makes no useful difference to the runtime.

90% of runtime is in `pango_layout_get_extents()`. This is the thing that, given a string to render, tells you the left / top / width / height in pixels of the image. I'm not sure what libvips can do better here.

**Comment by DFKSingleton** [comment]
I am inclined to agree with you, that it is difficult to get libvips to do things better. I have absolutely no experience with pango, so I do not know it there is a better way to do things. I did spend just a little time googling for pango examples but could not find anything that really made me really enthusiastic. As I said at the start of this issue, I only use VImage::text for test purposes. It is switched off in my operational program. If you want to close the issue, it is OK by me.
