### ISSUE TITLE
Revise libvips operation cache defaults

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1585]
The libvips operation cache is useful if you are doing many operations on a few images, but less useful if you are doing a few operations on many images. Web servers, for example, will often do just one or two operations on millions of images.

1. We could set the libvips operation cache defaults to much smaller numbers, perhaps the last 10 operations and just a few MB of memory. People could grow the cache if they wanted.
2. Alternatively, we could keep the current default, but have an environment variable (`VIPS_SERVER`?), compile-time option or API which turns down all the defaults. It'd be handy to have a single control which set everything small.

Any thoughts? Other options? My 2p would probably be option 2., but I'm very persuadable.

**Comment by lovell** [comment]
I believe most sharp users who change the defaults do so only to disable caching entirely.

https://github.com/search?q=%22sharp.cache%28false%29%22&type=Code

**Comment by jcupitt** [comment]
@ioquatix your cache issue fyi.

**Comment by DFKSingleton** [comment]
My (long-running) program regularly reports its vips memory usage as per the following example:
```
Vips Sub-system
vips Cachegrosse:672
vips 'tracked mem' (Mb):99
vips max mem benutzt (Mb):145
```
I am doing relatively few operations on lots of images. The cache size can rise to nearly 1000.
PS: translating from German: Grosse -> Size and benuzt -> used

**Comment by jcupitt** [comment]
Another idea:

The libvips cache doesn't know about a lot of memory -- for example, if you use vips_image_new_from_memory(), it won't add that memory area to the tracked pool, and therefore it won't add to the pressure on the cache.

We could add a little API to the memory tracker to let operations record "foreign" memory, ie. memory allocations which libvips knows must be there, but which are not allocated and freed via tracked_new/tracked_free. Operations like vips_image_new_from_memory() could note memory on startup, and clear it during `::close` handling.

Operations which have knowledge of foreign memory:

- vips_image_new_from_memory()  -- we should hook into `foreign_buffer` handling in vips_image_build()
- vips_image_new_from_buffer() -- add some code inside foreign.c somewhere

Can anyone think of any others?

**Comment by jcupitt** [comment]
Actually maybe that's not a great idea. External memory could be from eg. mmap and should not be counted as a malloc.

I've just dropped the default cache_max to 100 operations.
