### ISSUE TITLE
[Question/Help] ignoring palette (no quantisation support)

### ISSUE THREAD

**Issue by d30jeff** [libvips/libvips#1586]
I've followed the build instruction with Docker [here](https://github.com/libvips/libvips/issues/1577?fbclid=IwAR0VtNXKDkEPYbIchXyPHK-v3u2hVw1afAh_pr-qTOpxVwLeOBai2RkFYfs)

I'm getting 
`ignoring palette (no quantisation support)`
when I upload PNG files in my Amazon Linux 2 machine.

However JPEG files get successfully compressed. 

Correct me if I'm wrong, but what I understand so far is the library I'm using 
(https://www.npmjs.com/package/sharp) depends on this library.

I've managed to install libvips locally with `brew install vips` and it works fine.

**Comment by lovell** [comment]
Cross posted at https://github.com/lovell/sharp/issues/2136
