### ISSUE TITLE
add stream support to vipsheader

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1594]
`vipsheader` doesn't currently know about the new stream system.

Possible syntax:

```
cat k2.jpg | vipsheader -a stdin
cat k2.jpg | vipsheader -a [descriptor=0]
```

**Comment by dineshkannaa** [comment]
> `vipsheader` doesn't currently know about the new stream system.
> 
> Possible syntax:
> 
> ```
> cat k2.jpg | vipsheader -a stdin
> cat k2.jpg | vipsheader -a [descriptor=0]
> ```

@jcupitt  Is this supported now ?

**Comment by jcupitt** [comment]
Sorry, not yet.

**Comment by jcupitt** [comment]
OK, this is in 8.10.
