### ISSUE TITLE
Overzealous tests in VImage constructor and assignment operator ?

### ISSUE THREAD

**Issue by jaubourg** [libvips/libvips#1595]
The following snippets will always fail:

```cpp
vips::VImage i1;
vips::VImage i2( i1 ); // fails here
```

```cpp
vips::VImage i1;
vips::VImage i2
i1 = i2; // fails here
```

from what I can gather, the culprits are, respectively, [this assert](https://github.com/libvips/libvips/blob/master/cplusplus/include/vips/VImage8.h#L101) and [this assert](https://github.com/libvips/libvips/blob/master/cplusplus/include/vips/VImage8.h#L125) if glib asserts are on and [this referencing](https://github.com/libvips/libvips/blob/master/cplusplus/include/vips/VImage8.h#L108) and [this referencing](https://github.com/libvips/libvips/blob/master/cplusplus/include/vips/VImage8.h#L132) if they are off.

Is there a reason not to accept NULL vobject in right-hand operands while allowing it at construction?

For the little story, I'm testing my implementation of vips under heavy load and came by these lines of code (I seem to have an unrelated issue but thought the behavior highlighted by the snippets was probably not intended).

**Comment by jcupitt** [comment]
Hello @jaubourg,

This was a while ago now, but I think the idea was to avoid uninitialized (or NULL) images where possible. It adds complexity and API for (I think?) no benefit.

It allows them to be declared for the cases where you need declaration and use to be separate, but you can't do anything with a declared NULL image, except assign to it.

Could you explain why you need to be able to manipulate NULL images?

**Comment by jaubourg** [comment]
The problem arises when you have a VImage as a member of a class which instances you may move around before loading the image (which is pretty much what I have).

I'm 100% on board with having any method called on a NULL image failing hard (because it makes no sense to act on one) but not being able to assign or to copy-construct based on a NULL image seems a little bit extreme to me. In my case, the only option will be to extend the VImage class with my own OR implement a copy constructor and an assignment operator for all classes that have a VImage member to try and work around the asserts.

Would you be OK with a pull request enabling copy construction and assignment from a NULL image and just that ? Like I said, having any operation other than those two fail hard on a NULL image is fine and desirable.

**Comment by jcupitt** [comment]
That sounds reasonable. Sure, a PR would be great, thank you!
