### ISSUE TITLE
Vips 250 dpi tiffsave issue

### ISSUE THREAD

**Issue by kelilevi** [libvips/libvips#1598]
Switching from Photoshop to Vips, so far is going well, and I really like it. But now I am stacked. My final image has to be in .tiff, with 150 dpi and AdobeRGB1998.icc embedded (using the final image for printing trough a RIP software). The input format/dpi is unknown so I need to convert the images. Is working well if the image is 150 dpi, or 300 dpi, but if I have a 250 dpi or 75 dpi (etc.) image after the whole process, the final image is still showing 250 dpi and the Rip software is printing smaller size than the desired (expecting 150 dpi).  If I open in Photoshop same think – is showing 250 dpi, rather than 150 even if I set the x-y-res to 5.9055118560791 (150 dpi).
Tried to save with writeToFile() and with tiffsave() - same result. Opened the image with magickload() – the final output dpi is good, but somewhere the profile is switching because the output color is flat (mostly if the original image doesn’t have a tagged profile).
Any help or guidelines is gladly appreciated.  

Using PHP 7.2.24 on Ubuntu 18.04.4 bionic with Vips 8.7.4 
My code:
```
<?PHP
$image = Vips\Image::newFromFile($srcFile,['access' => Vips\Access::SEQUENTIAL]);

//converting/adding the profile, if untagged
if ($image->get('interpretation') != 'srgb'){
	$image = $image->icc_import(["embedded" => true, "input_profile" => $profile_sRGB_file]);
	$image = $image->icc_export(['output_profile' => $profile_Adobe98_file]);
}

$dpi_150_rounded = 5.906;
// if not 150 dpi - resize
if (round($image->get('xres'),3) != $dpi_150_rounded || round($image->get('yres'),3) != $dpi_150_rounded){
	// calculate scale percent
	$image_dpi_percent = (5.9055118560791 * 100 / $image->get('xres'))/100;
	$image = $image
		->copy(["xres" => 5.9055118560791, "yres" => 5.9055118560791])
		->resize($image_dpi_percent, ["vscale" => $image_dpi_percent]);
}

// more code: adding text, barcode, corner shape etc...

// save the final image: .tiff, 150 dpi, embed profile, change resunit
$image->tiffsave($folder_save_tif . $file_save_tif, [
	'profile' => $profile_to_embed,
	'xres' => 5.9055118560791*10, 
	'yres' => 5.9055118560791*10, 
	'bigtiff' => true,
	'resunit' => "inch",
]);
?>
```

**Comment by jcupitt** [comment]
Hello @kelilevi,

If you're setting 150dpi in tiffsave but it's showing up as 250dpi, there must be some other piece of metadata in the image. Perhaps there's an XMP block? Or maybe it's using `PHOTOSHOP_DATA`?

I would use `tiffinfo` or `vipsheader -a` and check for other metadata types.

**Comment by kelilevi** [comment]
Thank you jcupitt! Probably you're right, Attached is my vipsheader -a data. Is there any way (from PHP) to delete the PHOTOSHOP_DATA or the XMP block without using the "strip" (I need the .icc data in file)?
Thank you!

250_dpi_saved.tif: 3106x2506 uchar, 3 bands, srgb, tiffload
width: 3106
height: 2506
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 0.590551
yres: 0.590551
filename: 250_dpi_saved.tif
vips-loader: tiffload
n-pages: 1
icc-profile-data: 560 bytes of binary data
xmp-data: 17071 bytes of binary data
photoshop-data: 9126 bytes of binary data
image-description: 5539491*-*Blah*-*16 x 20*-*1*-*2/2  ~312*-*0*-*3
resolution-unit: in
orientation: 1

**Comment by jcupitt** [comment]
Just `$image->remove("xmp-data")`, I think.

**Comment by jcupitt** [comment]
I would remove `image-description` and `photoshop-data` as well.

**Comment by kelilevi** [comment]
Success!!! Remove("photoshop-data") is the key.
Thank you very much your help!
