### ISSUE TITLE
Libvips installation compile failed

### ISSUE THREAD

**Issue by LebronCurry** [libvips/libvips#1599]
Hello.When I installed libvips on the server, most of them were successful, but some of them will report errors during make. Do you know the reason?
The error is as follows：

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpangoft2-1.0.so: undefined reference to `g_log_structured_standard'
collect2: error: ld returned 1 exit status
make[1]: *** [vips] Error 1
make[1]: Leaving directory `/opt/soft/vips-8.8.0/tools'
make: *** [check-recursive] Error 1

**Comment by lovell** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1655751

**Comment by LebronCurry** [comment]
I have solved the problem，thanks.

**Comment by ArunJRK** [comment]
How was this resolved?

**Comment by LebronCurry** [comment]
> How was this resolved?

I remember that I uninstalled a free-type package first, and then reinstalled libvips
