### ISSUE TITLE
Some pyramid tiffs resize very slowly if you use the largest page

### ISSUE THREAD

**Issue by klintarg** [libvips/libvips#1600]
For some pyramid tiff files, I'm seeing a large performance loss if I resize from the largest page (vs the time it takes to resize a non-pyramidal tiff file of the same content). I've created a script with an example image to demonstrate the issue.

I've tested this on vips 8.9.1 on MacOS and Linux.

Example output:
./tiff_issue.sh 
Converting jpg to a tiff
Converting jpg to a pyramid tiff
Resizing non-pyramid tiff

real	0m0.555s
user	0m0.519s
sys	0m0.047s
Resizing pyramid tiff

real	0m8.795s
user	0m8.553s
sys	0m0.378s
Resizing pyramid tiff with page 2

real	0m0.085s
user	0m0.075s
sys	0m0.033s

[bugreport.tar.gz](https://github.com/libvips/libvips/files/4429104/bugreport.tar.gz)

**Comment by jcupitt** [comment]
I see sane numbers on linux too. 

Perhaps some other loader is jumping in? I see:

```
$ vipsheader input/*
input/testimage-nopy.tiff: 6000x4000 uchar, 3 bands, srgb, tiffload
input/testimage-py.tiff: 6000x4000 uchar, 3 bands, srgb, tiffload
```

Do you see `tiffload` as well?

**Comment by klintarg** [comment]
Yes: 
```
vipsheader input/*
input/testimage-nopy.tiff: 6000x4000 uchar, 3 bands, srgb, tiffload
input/testimage-py.tiff: 6000x4000 uchar, 3 bands, srgb, tiffload
```

I've tested this on debian sid with the current package, on MacOS Catalina with brew's current package, and on MacOS Mojave with brew's current package. I've also (accidentally) tested it with an older version of vips using the port build on MacOS. 

I've also observed this code-side on RHEL 7-like systems using a build from the libvips-sharp build script.

**Comment by klintarg** [comment]
Here's the version data from my Mojave system:
```
vips --version
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020
$ which vips
/usr/local/bin/vips
```

**Comment by Algae666** [comment]
I see it in MacOS Catalina:

⇒  ./tiff_issue.sh 
Converting jpg to a tiff
Converting jpg to a pyramid tiff
Resizing non-pyramid tiff

real	0m0.495s
user	0m0.458s
sys	0m0.045s
Resizing pyramid tiff

real	0m3.139s
user	0m3.151s
sys	0m0.210s
Resizing pyramid tiff with page 2

real	0m0.076s
user	0m0.063s
sys	0m0.026s

**Comment by klintarg** [comment]
Ok, this is getting even stranger. I tried this on my Debian buster VM (vips version 8.7.4) and I get relatively sane results:
`
$ ./tiff_issue.sh 
Converting jpg to a tiff
Converting jpg to a pyramid tiff
Resizing non-pyramid tiff

real	0m0.523s
user	0m0.475s
sys	0m0.047s
Resizing pyramid tiff

real	0m0.772s
user	0m0.659s
sys	0m0.056s
Resizing pyramid tiff with page 2

real	0m0.600s
user	0m0.064s
sys	0m0.040s

`

**Comment by jcupitt** [comment]
It's working in Catalina for me with current homebrew libvips.

Could you perhaps make a docker image which shows this problem?

**Comment by jcupitt** [comment]
I suppose one of your TIFFs will be tiled and one not. Perhaps that could interact badly with deflate compression with some libtiff versions?

**Comment by klintarg** [comment]
This is aggravatingly inconsistent amongst the 10 or so machines and VMs I've tried. I'll try to find a config that replicates it in docker. My initial attempts using Debian docker images don't replicate the issue (even though my physical Debian Sid machine does). I suspect some package is interacting here, but haven't isolated which yet.

**Comment by jcupitt** [comment]
I'll close. Please reopen if there's progress on this issue.
