### ISSUE TITLE
Support for half precision / float16

### ISSUE THREAD

**Issue by HansPinckaers** [libvips/libvips#1602]
Hi there,

I'm using libvips for data augmentation of large images for training neural networks, and it works very well. Thanks for all the work. 

I have a feature request: to save some memory, after my libvips pipeline when I convert to numpy, would it be possible to cast to 'half precision' floats? Something like pyvips.BandFormat.HALF.

Kind regards,
Hans

**Comment by jcupitt** [comment]
Hello Hans,

Sorry, libvips does not have direct support for the half formats. You could do the cast in numpy, or perhaps scale to uint8 or uint16.

I tend to normalize to 0 - 255 and process as uint8, but of course it depends on your data.

**Comment by HansPinckaers** [comment]
Ok, thanks!
