### ISSUE TITLE
Support for HWB color model?

### ISSUE THREAD

**Issue by sebastienbarre** [libvips/libvips#1606]
Hi. Thanks for the great work on libvips. 

I was wondering if supporting the [HWB color model](https://en.wikipedia.org/wiki/HWB_color_model) was considered (and possibly rejected?).

Now I see HSV is supported, and the path from HSV to HWB is trivial, but my use case is scripting from Nodejs, using [sharp](https://sharp.pixelplumbing.com/), where performing the conversion manually pixel by pixel is painfully slow...

More specifically, I wrote a script to "colorize" monochrome line icons (such [as these](https://icons8.com/icons/ios)) for personal use. Given a target color C in RGB format, for every source pixel S in RGB format found in the (essentially monochrome) PNG, the target pixel T is a copy of C converted to HWB space, where T(W) = S(W). Essentially I'm borrowing the whiteness from the source pixel to colorize the target pixel, the rest is unchanged (i.e T(H) = C(H) and T(B) = C(B)). T is then converted to RGB for final output to PNG. 

There is a quick linear interpolation done as well, so it's really T(W) = S(W) * a + b, just so that T(W) stretches from C(W) to 1.0, instead of 0.0 to 1.0. Essentially whatever is black in the original icon (the outline) becomes the target color, and if there is any grayscale in the PNG (unlikely), they map to a "whitened" version of C, stretching from C to white.

Now sharp is wrapping `linear`, which I could use for that last step, but unfortunately I still need to perform the conversion from RGB to HWB pixel by pixel at this point (using Nodejs [Qix-/color-convert](https://github.com/Qix-/color-convert)).

Thanks

**Comment by jcupitt** [comment]
Hello @sebastienbarre,

If you don't need to exactly duplicate HWB, I'd use LCh instead. It's quite a bit better.

In this case, the line art icons have the shape in the alpha and 0s in the RGB channels. So I think all you need to do is swap the 0s for your target colour.

Eg.:

![icons8-finn-250](https://user-images.githubusercontent.com/580843/79060954-c91dfd80-7c82-11ea-8343-2c1967d9703f.png)

With:

```python
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])
alpha = x[3]
rgb = x.new_from_image([12, 45, 180])
x = rgb.bandjoin(alpha)
x.write_to_file(sys.argv[2])
```

Becomes:

![x](https://user-images.githubusercontent.com/580843/79060988-3598fc80-7c83-11ea-8d86-324d4926dc7d.png)



Do you want to exactly duplicate the HWB calculation? If you're OK with doing something better, I'd use LCh instead. Eg.

```python

**Comment by sebastienbarre** [comment]
Thanks John. 

Originally I had tried with LCh, since sharp provides a [`modulate`](https://sharp.pixelplumbing.com/api-operation#modulate) function that internally uses [libvips `linear`](https://github.com/lovell/sharp/blob/master/src/operations.cc#L188). The math didn't quite work out, but maybe I need to double check. The advantage of W in HWB is that it impacts both measures of brightness/lightness/luminance and saturation/chroma at the same time (since W = (1 - S)V. Tweaking only the hue didn't land on the exact target color, especially when I'm trying to replace the black with a color that is not fully saturated/pure. 

As for replacing the 0, yes, that would work, but unfortunately I *do* have some icons with some grays in it :)

I appreciate the feedback.

PS: I did look at the PR that introduced HSV, and it wasn't too scary--the path from RGB is fine, and the path from HSV is even easier. I could push a PR, but I totally understand if you don't want to introduce more color models...

**Comment by jcupitt** [comment]
HWB is very simple, so you could make it yourself in a couple of lines, eg.:

```python
H, S, V = image.colourspace("hsv").bandsplit()
W = (1 - S) * V
B = 1 - V
image = H.bandjoin([W, B])
```

Though a colourization using LCh (or Lab) should still be better. Do you have a sample greyscale icon you'd like to colourize?

**Comment by sebastienbarre** [comment]
Thanks John,

Yes, the issue here is not difficulty per se, but availability and performance :) I'm doing this from nodejs, using [sharp](https://sharp.pixelplumbing.com)--which may or may not have been the smartest choice, but ultimately I'm just creating a small CLI, something easy to install, no compilation required, can be run from `npx`, etc. So this is not a libvips issue ultimately, it's more than capable to do this, and I appreciate the pointers you have been giving me so far. 

The code above looks great, unfortunately no such flexibility available from nodejs (I believe). There is an [extractChannel](https://sharp.pixelplumbing.com/api-channel#extractchannel) and a [joinChannel](https://sharp.pixelplumbing.com/api-channel#joinchannel) command being exposed, maybe they are the same as `bandsplit` and `bandjoin`, but once that channel is extracted, I don't see any convenient, overloaded object-oriented operators like the ones you are using to perform `W = (1 - S) * V` for example...

Here is a [sample grayscale icon](https://barre.io/icons/notion/original/heydenver.png). The outside of the company logo is alpha, but the inside is not, so the company name itself is white (on black). In other words, the outside of the logo is transparent, but the inside shows several different grayscales where the text is anti-aliased, from black to full white. Let's say I want to colorize the icon with #1569b3 RGB; full black is to become that color, and everything from back to white stretches (in my current code, excerpt below) from #1569b3's whiteness level (I recall it's around 12%) to 100% whiteness; the blackness is kept the same in my code, because #1569b3 is not fully saturated. In other words, the replacement color saturation is not to be "increased" or made more "chromatic", and everything from that color to pure white in the original image should be a "lighter/whiter" version of that color, while never being more saturated. 

Again, my thanks

```javascript
sharp(file)
      .toColorspace('srgb')
      .raw()
      .toBuffer({ resolveWithObject: true })
      .then(({ data, info }) => {
        let color_hwb = Color(color).hwb().object();
        let scale = (100.0 - color_hwb.w) / 100.0;
        let pixel_count = info.width * info.height;
        let target_buffer = Buffer.allocUnsafe(pixel_count * info.channels);
        let target_pos = 0;
        let source_it = data.values();
        for (let i = 0; i < pixel_count; i++) {
          let source_color = Color({
            r: source_it.next().value,
            g: source_it.next().value,
            b: source_it.next().value,
          });
          let target_color = Color({
            h: color_hwb.h,
            w: source_color.white() * scale + color_hwb.w,
            b: color_hwb.b
          }).rgb().object();
          target_buffer.writeUInt8(target_color.r, target_pos++);
          target_buffer.writeUInt8(target_color.g, target_pos++);
          target_buffer.writeUInt8(target_color.b, target_pos++);
          for (let j = 3; j < info.channels; j++) {
            target_buffer.writeUInt8(source_it.next().value, target_pos++); // alpha(s)
          }
        }
        return sharp(target_buffer, { raw: info })
          .png()
          .toBuffer();
      })
      .then(data => fs.writeFile(file, data).then(() => true))
      .catch(error => 'Failed colorizing ' + file + '. ' + error.message)
```

**Comment by jcupitt** [comment]
Yes, sharp is an image resize package, not really a general image processing system. I made a general purpose binding for libvips here:

https://github.com/libvips/node-vips

Although I'm not sure anyone's ever used it heh. It might be more suitable.

**Comment by jcupitt** [comment]
I had another quick go:

```python
#!/usr/bin/python3

import sys
import pyvips

white = [100, 0, 0]
red = [53.2, 80.1, 67.2]

for filename in sys.argv[1:]:
    x = pyvips.Image.new_from_file(filename, access="sequential")
    L, a, b, A = x.colourspace("lab").bandsplit()
    r = L / 100
    new_lab = r * white + (1 - r) * red
    x = new_lab.bandjoin(A)
    x = x.colourspace("srgb")
    x.write_to_file(f"colourized-{filename}")
```

That's taking lightness from your icon, scaling it to 0 - 1, then using that to blend smoothly between white and your target colour (solid red here, but in CIELAB coordinates). 

I get:

![x](https://user-images.githubusercontent.com/580843/79085342-1c9a5500-7d30-11ea-8e0a-a530997e7fb1.png)

It should look a little better since it's doing the blend in a perceptually linear colourspace.

**Comment by sebastienbarre** [comment]
Very nice, thanks John.
