### ISSUE TITLE
Weird color result using "vips_linear"

### ISSUE THREAD

**Issue by betorcs** [libvips/libvips#1607]
Hi @jcupitt ,

Let me see if you can help me, I have the following sample code. It works fine when applying tint colors: yellow, red, green, blue, black and white. But when applying orange, pink and violet It's giving an weird result. I attached the original image and images results.

Thanks in advance.

```python
from pyvips import Image

palette = {
  'orange': [255, 165, 0, 255],
  'pink': [255, 192, 203, 255],
  'violet': [238, 130, 238, 255],
  'yellow': [255, 255, 0, 255],
  'red': [255, 0, 0, 255],
  'green': [0, 128, 0, 255],
  'blue': [0, 0, 255, 255],
  'black': [0, 0, 0, 255],
  'white': [255, 255, 255, 255]
}

def tint(color):
  im = Image.new_from_file('sample.png', access='sequential')
  im = im.flatten(background=255)
  im = im.colourspace('b-w')
  im = (im >= 210).bandand().ifthenelse([0, 0, 0, 0], im)
    
  lut = Image.identity()
  lut *= palette[color]
  out = im.maplut(lut)
  out.write_to_file('plan-%s.png' % color)

if __name__ == "__main__":
    for color in palette:
      tint(color)
```

**original image**

![sample](https://user-images.githubusercontent.com/1232290/79180839-537c7380-7de1-11ea-80ab-ea68dba43db3.png)

**result table**

| color | image |
|---|---|
|orange  | ![plan-orange](https://user-images.githubusercontent.com/1232290/79179050-26c65d00-7ddd-11ea-97b6-e3ac611b3087.png) |
|pink  | ![plan-pink](https://user-images.githubusercontent.com/1232290/79179051-27f78a00-7ddd-11ea-8aca-0dae2cea9654.png) |
|violet  | ![plan-violet](https://user-images.githubusercontent.com/1232290/79179057-28902080-7ddd-11ea-8bca-9504ae719e94.png)|
|yellow  | ![plan-yellow](https://user-images.githubusercontent.com/1232290/79179060-2928b700-7ddd-11ea-85fb-ace0104784ed.png)|
|red | ![plan-red](https://user-images.githubusercontent.com/1232290/79179055-27f78a00-7ddd-11ea-9c3e-a1ae77d10ebe.png) |
|green  | ![plan-green](https://user-images.githubusercontent.com/1232290/79179049-26c65d00-7ddd-11ea-951c-d925512bfc70.png)|
|blue  | ![plan-blue](https://user-images.githubusercontent.com/1232290/79179046-25953000-7ddd-11ea-8c04-d11f1d848b06.png)|
|black  | ![plan-black](https://user-images.githubusercontent.com/1232290/79179042-23cb6c80-7ddd-11ea-876c-6980f0d010c7.png)|
|white  |![plan-white](https://user-images.githubusercontent.com/1232290/79179059-28902080-7ddd-11ea-8a0c-e53f12e75eac.png) |

**Comment by jcupitt** [comment]
Hello @betorcs 

I think it's this line:

```python
  lut *= palette[color]
```

You're going to get huge values here. If the lut is 255, you'll get `255 * palette[color]`, and that'll be clipped to 255.

You need to greyscale the image, find pixels over 210, and set them to the tint. Try:

```
  im = Image.new_from_file('sample.png', access='sequential')
  im = im.flatten(background=255)
  im = im.colourspace('b-w')
  im = (im >= 210).ifthenelse(palette[color], im)
  im.write_to_file('plan-%s.png' % color)
```

If you want to use a lut, you could try:

```
  lut = Image.identity()
  lut = (lut > 210).ifthenelse(palette[color], lut)
  im = im.maplut(lut)
```

Though I don't know if it'd be faster.

**Comment by jcupitt** [comment]
I tried and you need to set the interpretation too. I'd use:

```python
def tint(color):
  im = Image.new_from_file('sample.png', access='sequential')
  im = im.flatten(background=255)
  im = im.colourspace('b-w')
  lut = Image.identity()
  lut = (lut >= 210).ifthenelse(255, palette[color])
  lut = lut.copy(interpretation="srgb")
  im = im.maplut(lut)
  im.write_to_file('plan-%s.png' % color)
```

**Comment by betorcs** [comment]
@jcupitt thank you very much, for the explanation and the sample. I did a quick test using your sample code and it's seems the properly color is being applied, only background looks not being transparent anymore, but I think I can adjust it with your explanation all make sense now.
