### ISSUE TITLE
Installation in Azure cloud - Error:Unable to load DLL \ 'libvips-42.dll\ ' or one of its dependencies

### ISSUE THREAD

**Issue by sergiosolorzano** [libvips/libvips#1608]
Hi, anyone has this running in Azure that can shed some light on installation process there pls?

I can run an azure function app with libvips library from localhost for this function app - manipulation for images output correctly. I setup my local environment by saving l[ibvips win64](https://github.com/libvips/libvips/releases) in a folder in my windows 10 PC, added libvips bin folder to environment PATH and in Visual studio I installed nuget NetVips, NetVips.Native.win-64.

This is the method I run:                                 var rgbThumbnail = NetVips.Image.ThumbnailBuffer(thisRGBImgBytes, 256);

I'm trying to run the .Net Core 3.1 V3 function app from azure. When I run from cloud I get "Error:Unable to load DLL \ 'libvips-42.dll\ ' or one of its dependencies. The specified module could not be found . (0x8007007E)"

I had expected for the nuget packages in VS to suffice when uploading to the function app in azure. I've looked on the internet how to install libvips in Azure but I can't find any reference. Can someone please help?

thank you

**Comment by kleisauke** [comment]
Perhaps GDI32 is not available in Azure Cloud? The `NetVips.Native*` Windows NuGet packages were accidentally linked against `GDI32.dll`, see:
https://github.com/kleisauke/net-vips/issues/61#issuecomment-586273354

You could try testing these binaries:
https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.1-static

**Comment by sergiosolorzano** [comment]
Hi @kleisauke 

Thanks for this. I'm sorry, I'm new to this.

I have replaced the folder in my windows 10 PC [vips-dev-8.9](https://github.com/libvips/libvips/releases) for the [binaries ](https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.1-static)you've suggested. Then recompiled and uploaded the function app to Azure. The same error earlier reported occurs.

I'm sorry, I'm quite new to this - is this how I can test these binaries in Azure?

**Comment by sergiosolorzano** [comment]
Got to the bottom of this in case someone has this issue - a Microsoft specialist helped out: ensure the function app setting is setup for 64-bit or 32-bit depending on libvips you're using. 

Unfortunately the error message wasn't too obvious to realize this was the issue.

Azure doesn't throw error now but still can't get a rendered image at client generated at Azure.

If someone can help please: I am creating a thumbnail, need to send it as base64string from cloud to client, then save thumbnail to file. The below generates an image I can't read at client:

Azure's cloud function app uses libvips library and generates binary of thumbnail:
byte[] thisRGBImgBytes = (byte[])reader["thisRGBImg"];//tested and works correctly to receive source image at azure
var thumb = NetVips.Image.ThumbnailBuffer(thisRGBImgBytes, 256);//tested and works correctly: create thumbnail
//thumb.WriteToFile("myoutput2.jpg");//this would work correctly at local if we wrote to file at this point.
byte[] thumbnailBytes = rgbThumbnail.WriteToMemory();//byte of thumbnail
string thumbnailBytesString = Convert.ToBase64String(thumbnailBytes);//base64string to send to client

At client:
byte[] thumbnailBytes = Convert.FromBase64String(thumbnailBytesString);
File.WriteAllBytes("output.jpg", thumbnailBytes);//can't open generated file

**Comment by sergiosolorzano** [comment]
resolved and answer within this post

**Comment by kleisauke** [comment]
I'm glad you figured it out, it's weird that the `HRESULT` value was `0x8007007E` (`DllNotFoundException`). Usually when there is a 32/64-bit mismatch it gives a `HRESULT` of `0x8007000B` (i.e. `BadImageFormatException`).

fwiw, you could also try to install the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package, it will automatically choose the appropriate NetVips.Native.* package based on which OS/bitness it's running on. This can be useful for cross-platform deployments.
