### ISSUE TITLE
Load image regression

### ISSUE THREAD

**Issue by MathemanFlo** [libvips/libvips#1609]
Hello,
starting from version 8.9.1 (compared to 8.9.0) I experience a very strange behavior. Simple programs like 
`/*...*/
VipsImage* img = vips_image_new_from_file("image.TIF",NULL);
vips_image_write_to_file(img, "result.TIF", NULL);
g_object_unref(img);
/*..*/`
do not work anymore for some images. I have some images where it works but I also have some where it does not work and I can not find any sane pattern behind it. It does not depend on the source and destination format nor does it depend on the bit depth. Using the DLLs from 8.9.0 (I'm developing on windows) everything works fine.
Florian

**Comment by jcupitt** [comment]
Huh weird. If you post a sample image that fails, I can investigate.

**Comment by MathemanFlo** [comment]
Thank you so much for the quick reply.
Here I have two examples. One works and the otherone not. By replacing the dlls and using the ones from 8.9.0 both examples work.
![works_not](https://user-images.githubusercontent.com/28649121/79329892-dce29180-7f18-11ea-8083-65443a03166f.png)
![works](https://user-images.githubusercontent.com/28649121/79329893-dd7b2800-7f18-11ea-8215-bc8ffc8d47b7.png)

**Comment by jcupitt** [comment]
Sorry, just came back to this, could you upload some TIFFs that show the problem? Or is this resolved by the 1/2/4 bit TIFF PR?

**Comment by MathemanFlo** [comment]
Yes it is. They have a width of 259, hence there is a fractional byte in
each line. If you read and write these files without the fix you see that
it changed on the right after the fix they remain the same.

John Cupitt <notifications@github.com> schrieb am Do., 18. Juni 2020, 15:58:

**Comment by jcupitt** [comment]
Ah good, it should be fixed in master. Thanks for the report.
