### ISSUE TITLE
big image is cut off (dzsave for openseadragon)

### ISSUE THREAD

**Issue by h2108** [libvips/libvips#1611]
Hi, 
i have a big image (3025 x 5783 px. 300dpi) and about the last 1/8th of the image is
not shown in the final image. There are pieces missing.
i have another one, which is 3600 x 5097px, 240dpi, which works fine.
i tried every possible option, but nothing works.
what do i am missing?
thanks a lot.

**Comment by jcupitt** [comment]
Hello @h2108,

You need to give more information. What does `vipsheader` say for your image? What command are you running? What version of libvips are you using, and what platform?

**Comment by h2108** [comment]
Hello jcupitt, 

sure, was a bit late.
i am on mac osx mojave, and running vips-8.9.1_1 (just upgraded it last evening)
(or what would be the command to get the version information?)
i use the command: vips dzsave myimage.jpg myimagefoldername

by vipsheader, do you mean the information i get, when i use this command:
vipsheader -a file.jpg ?

That would be the result i get:
------
width: 3025
height: 5783
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11,811
yres: 11,811
filename: /Users/henrikhentschel/Documents/Sites/Nomadenschaetze-Doc/234144/234144.jpeg
vips-loader: jpegload
jpeg-multiscan: 0
jpeg-chroma-subsample: 4:4:4
exif-data: 6639 bytes of binary data
resolution-unit: in
exif-ifd0-ImageWidth: 5783 (5783, Short, 1 components, 2 bytes)
exif-ifd0-ImageLength: 3025 (3025, Short, 1 components, 2 bytes)
exif-ifd0-BitsPerSample: 8 8 8 (8, 8, 8, Short, 3 components, 6 bytes)
exif-ifd0-Compression: 5 (LZW compression, Short, 1 components, 2 bytes)
exif-ifd0-PhotometricInterpretation: 2 (RGB, Short, 1 components, 2 bytes)
exif-ifd0-ImageDescription: 183x400cm (183x400cm, ASCII, 10 components, 10 bytes)
exif-ifd0-Make: Phase One (Phase One, ASCII, 10 components, 10 bytes)
exif-ifd0-Model: P 45+ (P 45+, ASCII, 6 components, 6 bytes)
exif-ifd0-Orientation: 1 (Top-left, Short, 1 components, 2 bytes)
exif-ifd0-SamplesPerPixel: 3 (3, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 3000000/10000 (300,0000, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 3000000/10000 (300,0000, Rational, 1 components, 8 bytes)
exif-ifd0-PlanarConfiguration: 1 (Planar format, Short, 1 components, 2 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-Software: Adobe Photoshop CS5 Macintosh (Adobe Photoshop CS5 Macintosh, ASCII, 30 components, 30 bytes)
exif-ifd0-DateTime: 2019:03:28 15:36:48 (2019:03:28 15:36:48, ASCII, 20 components, 20 bytes)
exif-ifd0-Artist: Fotostudio Huber (Fotostudio Huber, ASCII, 17 components, 17 bytes)
exif-ifd1-Compression: 6 (JPEG compression, Short, 1 components, 2 bytes)
exif-ifd1-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-YResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd2-ExposureTime: 9466/757281 (1/80 sec., Rational, 1 components, 8 bytes)
exif-ifd2-FNumber: 1100/100 (f/11,0, Rational, 1 components, 8 bytes)
exif-ifd2-ExposureProgram: 1 (Manual, Short, 1 components, 2 bytes)
exif-ifd2-ISOSpeedRatings: 50 (50, Short, 1 components, 2 bytes)
exif-ifd2-ExifVersion: Exif Version 2.2 (Exif Version 2.2, Undefined, 4 components, 4 bytes)
exif-ifd2-DateTimeOriginal: 2015:03:11 02:40:40 (2015:03:11 02:40:40, ASCII, 20 components, 20 bytes)
exif-ifd2-DateTimeDigitized: 2015:03:11 02:40:40 (2015:03:11 02:40:40, ASCII, 20 components, 20 bytes)
exif-ifd2-ShutterSpeedValue: 632193/100000 (6,32 EV (1/80 sec.), SRational, 1 components, 8 bytes)
exif-ifd2-ApertureValue: 69189/10000 (6,92 EV (f/11,0), Rational, 1 components, 8 bytes)
exif-ifd2-ExposureBiasValue: 0/1000 (0,00 EV, SRational, 1 components, 8 bytes)
exif-ifd2-LightSource: 255 (Other, Short, 1 components, 2 bytes)
exif-ifd2-FocalLength: 800/10 (80,0 mm, Rational, 1 components, 8 bytes)
exif-ifd2-ColorSpace: 65535 (Uncalibrated, Short, 1 components, 2 bytes)
exif-ifd2-PixelXDimension: 3025 (3025, Long, 1 components, 4 bytes)
exif-ifd2-PixelYDimension: 5783 (5783, Long, 1 components, 4 bytes)
exif-ifd2-FileSource: DSC (DSC, Undefined, 1 components, 1 bytes)
exif-ifd2-SceneType: Directly photographed (Directly photographed, Undefined, 1 components, 1 bytes)
exif-ifd2-FlashPixVersion: FlashPix Version 1.0 (FlashPix Version 1.0, Undefined, 4 components, 4 bytes)
jpeg-thumbnail-data: 5807 bytes of binary data
orientation: 1
iptc-data: 8032 bytes of binary data
xmp-data: 6118 bytes of binary data
icc-profile-data: 1992 bytes of binary data
-----

**Comment by jcupitt** [comment]
I tried on my mac (mojave, current brew) and it seems to be working for me. I tested like this:

```
$ vipsheader x.jpg 
x.jpg: 6048x8064 uchar, 3 bands, srgb, jpegload
```

So a little larger than your image. I ran this command:

```
$ vips dzsave x.jpg x
```

Then checked the images like this:

```
$ ls x_files/
0  1  10 11 12 13 2  3  4  5  6  7  8  9
$ cd x_files/13
$ ls
...
23_31.jpeg
```

There are a lot of tiles, but I can see that the highest numbered one is 23_31, so the image has 24 by 32 tiles. I rebuilt the image like this:

```
$ vips arrayjoin "$(ls *.jpeg | sort -t_ -k2g -k1g)" x.jpg --across 24
```

And `x.jpg` looks like my original image, so all tiles must be there.

**Comment by h2108** [comment]
Wow. Thanks a lot.
i get the same result, i get an image which looks like the original,
but in openseadragon viewer, it is still not complete.

what i noticed is, that the last pictures in folder 13 (in my case all pictures with number 11)
are white. so, no pictures on it and only 2kb in size.

would it be possible, that i send you the picture and you can again try it with my picture?
just to make sure, that it is not the pictures fault.

**Comment by jcupitt** [comment]
Sure, I can test here if you like. My email is jcupitt@gmail.com.

**Comment by jcupitt** [comment]
Hello, I tried your test image:

```
john@kiwi:~/pics$ vips dzsave 234144.jpeg x
john@kiwi:~/pics$ cd x_files/
john@kiwi:~/pics/x_files$ ls
0  1  10  11  12  13  2  3  4  5  6  7  8  9
john@kiwi:~/pics/x_files$ cd 13
john@kiwi:~/pics/x_files/13$ ls
...
10_0.jpeg   11_22.jpeg  2_1.jpeg   4_14.jpeg  5_9.jpeg   7_3.jpeg   9_19.jpeg
...
john@kiwi:~/pics/x_files/13$ vips arrayjoin "$(ls *.jpeg | sort -t_ -k2g -k1g)" x.jpg --across 12
```

And I get the original image back again.

**Comment by h2108** [comment]
Thanks.
mmhhm. strange. I also see the bottom images in the tiles. so all images seem
to be there. 
then it must be an issue with the openseadragon viewer.

**Comment by jcupitt** [comment]
It could be your server as well, or perhaps the way you are copying the tiles to the server. Anyway, good luck!
