### ISSUE TITLE
Can't read image saved to file

### ISSUE THREAD

**Issue by sergiosolorzano** [libvips/libvips#1612]
->sorry I don't see the button to classify this post as Question-<

Hi, I am creating a thumbnail, then send this thumbnail as base64string from cloud to client, then save thumbnail to file. The below generates an image at client but I can't open/read this saved image:

Azure's cloud function app uses libvips library and generates binary of thumbnail:

```C#
//tested and works correctly to receive source image at azure
byte[] thisRGBImgBytes = (byte[])reader["thisRGBImg"];
//tested and works correctly: create thumbnail
var thumb = NetVips.Image.ThumbnailBuffer(thisRGBImgBytes, 256);
//this would work correctly runing function app at Localhost if we wrote to file at this point.
//thumb.WriteToFile("myoutput2.jpg");

//generate byte array of thumbnail
byte[] thumbnailBytes = rgbThumbnail.WriteToMemory();
//base64string to send to client
string thumbnailBytesString = Convert.ToBase64String(thumbnailBytes);
```

At client:

```C#
byte[] thumbnailBytes = Convert.FromBase64String(thumbnailBytesString);
//Tested with the same function app running at localhost: can't open generated image file
File.WriteAllBytes("output.jpg", thumbnailBytes);
```

**Comment by jcupitt** [comment]
Could it be a binary / text mixup? Perhaps something is being interpreted as utf8 when it should be binary?

I would check the length of the file created by `WriteToFile` against the result of `WriteToMemory` and the binary object you get back from `ConvertFromBase64`. Hopefully they all match.

**Comment by jcupitt** [comment]
Oh, does `WriteAllBytes` need a flag to set binary mode?

**Comment by kleisauke** [comment]
Try swapping
```csharp
byte[] thumbnailBytes = rgbThumbnail.WriteToMemory();
```

with:
```csharp
byte[] thumbnailBytes = rgbThumbnail.WriteToBuffer(".jpg");
```

**Comment by jcupitt** [comment]
Ah! Of course! Duh.

**Comment by sergiosolorzano** [comment]
Thanks a bunch. Tested len using WriteToMemory and found it consistent byteLen WriteFromMemory= 262144 stringLenConvertingByteToBase64= 349528 byteLenConvertedBackToByteArray =262144

WriteToBuffer did the trick and works great ! :)
