### ISSUE TITLE
vips_thumbnail_buffer use preview jpeg from heic instead of real heic

### ISSUE THREAD

**Issue by ZorinArsenij** [libvips/libvips#1614]
Try to use vips_thumbnail_buffer on heic(3024x4032) image with params:
```
size = VIPS_SIZE_DOWN
width = 1200
height = 1200
```
But the result has size equal to 240x320. I guess that it tries to generate thumb from heic preview(jpeg). Is this what you intended or is it a bug? If it should be, then how can I disable generation thumb from heic preview(jpeg).

Also i get thumb 240x320, if use params:
```
size = C.VIPS_SIZE_DOWN
width = C.VIPS_MAX_COORD
height = C.VIPS_MAX_COORD
```

But if i use `size = C.VIPS_SIZE_BOTH`, the result is thumb of requested size.

[Sample](https://cloud.mail.ru/public/43iZ/cZ85W5r9n)

**Comment by jcupitt** [comment]
Hello @ZorinArsenij,

I tried this test program:

```python
#!/usr/bin/python3

import sys
import pyvips
    
with open(sys.argv[1], "rb") as f:
    buf = f.read()

x = pyvips.Image.thumbnail_buffer(buf, 1200, size="down")
x.write_to_file(sys.argv[2])
```

And it seems to work with my test images. I wasn't able to download your sample.

There was a bug with thumbnail selection in HEIC images that was fixed last year. Which version of libvips you are using?

**Comment by ZorinArsenij** [comment]
Hello @jcupitt 
My vips version is:
```
sh-4.2# vips --version
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020

```
I call this function from my golang code:
```
int vipsThumbnailBuffer(void *buf, size_t len, VipsImage **out, options_t options) {
	int retval = vips_thumbnail_buffer(buf, len, out, options.width,
		"height",    options.height,
		"size",      options.size, // C.VIPS_SIZE_DOWN
		NULL);

	return retval;
}
```
The width and height of out image is:
```
log.Printf("width: %d; height: %d", C.vips_image_get_width(out), C.vips_image_get_height(out))
width: 240; height: 320
```

I haven't got this problem with `vips 8.8.3`.
Where can I upload a sample to provide to you?

**Comment by jcupitt** [comment]
Hi, I was able to download your image, and I see the problem here too. I'll investigate. Thanks!

**Comment by jcupitt** [comment]
I think I've fixed it, there was a `>=` when there should have been a `>` :-( 

This fix will be in 8.9.2, thank you very much for reporting it!

**Comment by ZorinArsenij** [comment]
@jcupitt, thank you very much. And when is it worth waiting for 8.9.2?

**Comment by jcupitt** [comment]
A few fixes have built up, so I'll push out a new version. Later today, hopefully.

**Comment by jcupitt** [comment]
OK, it seems to all be working:

https://github.com/libvips/libvips/releases/tag/v8.9.2

Please open a new issue if there are any problems.
