### ISSUE TITLE
vips_image_new_from_buffer doesn't autorotate some heic files

### ISSUE THREAD

**Issue by ZorinArsenij** [libvips/libvips#1616]
Hello
I use this code for loading image from buffer:
```
VipsImage* vipsImageFromBufferWithAutorotate(void *buf, size_t len, bool autorotate) {
	VipsImage *out = vips_image_new_from_buffer(buf, len, NULL, "autorotate", autorotate, NULL);
	if (out == NULL) {
		return NULL;
	}

	return out;
}
```
But when i use some heic files, autorotate doen't correctly work.
For example i use this file: 
[rotate.heic.zip](https://github.com/libvips/libvips/files/4512243/rotate.heic.zip)

In viewer it looks like:

<img width="411" alt="viewer" src="https://user-images.githubusercontent.com/32309372/79905855-919c1780-841f-11ea-8dad-44032445c544.png">

But after processing it with `vips_image_new_from_buffer` and saving as jpg, it looks like:

<img width="847" alt="processed" src="https://user-images.githubusercontent.com/32309372/79906171-02433400-8420-11ea-8289-adedc1b208a6.png">

Also if i log width and height before saving `VipsImage` as jpg, i got:
```
width: 1280; height: 720
```
But i expected to get:
```
width: 720; height: 1280
```

**Comment by jcupitt** [comment]
We've revised heifload for libvips 8.10 and this should be fixed.

See: https://github.com/libvips/libvips/pull/1681
