### ISSUE TITLE
Documentation issue in VipsForeignTiffCompression

### ISSUE THREAD

**Issue by MathemanFlo** [libvips/libvips#1618]
Hello,
I found an issue in the [documentation](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#VipsForeignTiffCompression). 

> Use prediction to set the lzw or deflate prediction, default none.

I had to use _predictor_ and not prediction.

And I also had to set none, I think it is not the default value but horizontal is?

**Comment by jcupitt** [comment]
Good catch, fixed in master. Thanks!
