### ISSUE TITLE
Vips thumbnail_source issue 

### ISSUE THREAD

**Issue by dineshkannaa** [libvips/libvips#1620]
getting this exception 

> (vips:35446): VIPS-WARNING **: 12:04:00.124: Interlace handling should be turned on when using png_read_image

while  calling `thumbnail_source` command for a image. But working fine when using VIPS C API .

**Comment by jcupitt** [comment]
Hello, thanks for the report.

Could you post sample code and a test image, please? Also platform, libvips version, etc.

**Comment by dineshkannaa** [comment]
platform: CentOS Linux release 7.6.1810
vips version: 8.9.0

I couldnt share the image file here as its confidential

**Comment by jcupitt** [comment]
How are you triggering the error? This works for me:

```
cat k2.png | vips thumbnail_source [descriptor=0] x.jpg 128
```

Have you tried updating libvips to the current version (8.9.2)?

I'm jcupitt@gmail.com if you can share a dropbox link.

**Comment by jcupitt** [comment]
I'll close. Please reopen if more information is available.
