### ISSUE TITLE
 The results obtained by using different blending modes for multiple pictures are different from ps

### ISSUE THREAD

**Issue by frankie-price** [libvips/libvips#1622]
## Want

Hi, I want to composite one original picture with two pictures by multiply mode and soft-light mode, then get the same effect as Photoshop(ps-result.png).

## Problem

I used the `mix-blend-mode` in CSS3 to get the same results as Photoshop, but I got different results(libvips-result.png) when using libvips for the same operation. Is there something wrong with my operation?

## Codes
```python
import pyvips

def blend(imagepath, opacity):
    # opacity images
    multiply_image = pyvips.Image.new_from_file('./multiply.png', access='sequential')
    multiply_image = (multiply_image * [1, 1, 1, opacity]).copy(interpretation='srgb')

    soft_light_image = pyvips.Image.new_from_file('./soft-light.png', access='sequential')
    soft_light_image = (soft_light_image * [1, 1, 1, opacity]).copy(interpretation='srgb')

    # image to be blending
    image = pyvips.Image.new_from_file('./test.jpg', access='sequential')

    # blend
    first_blend_image = image.composite2(multiply_image, 'multiply')
    second_blend_image = first_blend_image.composite2(soft_light_image, 'soft-light')

    second_blend_image.pngsave('libvips-result.png')

blend('./test.jpg', 0.6)
```

Layers in Photoshop:
```
- multiply.png `Multiply blend; Opacity:60%`
- soft-light.png `Soft Light blend; Opacity:60%`
- source.jpg
```
SVG with css3 mix-blend-mode:
```svg
<svg id="image_color" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1000" height="1000" viewBox="0 0 1000 1000">
  <image id="source" data-name="source" width="1000" height="1000" xlink:href="./test.jpg"/>
  <image id="multiply" style="mix-blend-mode: multiply;opacity: 60%" width="1000" height="1000" xlink:href="./multiply.png"/>
  <image id="soft-light" style="mix-blend-mode: soft-light;opacity: 60%" width="1000" height="1000" xlink:href="./soft-light.png"/>
</svg>

```

## Files
- libvips result image:
![libvips result image](https://sd-assets.oss-us-west-1.aliyuncs.com/libvips-result.png?x-oss-process=image/resize,h_500)
- ps result image:
![ps result image](https://sd-assets.oss-us-west-1.aliyuncs.com/ps-result.png?x-oss-process=image/resize,h_500)
- source image:
![source image](https://sd-assets.oss-us-west-1.aliyuncs.com/test.jpg?x-oss-process=image/resize,h_500)
- multiply texture image:
![multiply texture image](https://sd-assets.oss-us-west-1.aliyuncs.com/multiply.png?x-oss-process=image/resize,h_500)
- soft-light texture image:
![soft-light texture image](https://sd-assets.oss-us-west-1.aliyuncs.com/soft-light.png?x-oss-process=image/resize,h_500)

here are the source code and images files
https://sd-assets.oss-us-west-1.aliyuncs.com/blend-example.zip

Thanks for your help.

**Comment by jcupitt** [comment]
Hello @frankie-price, thank you very much for the detailed report, I'll have a look.

**Comment by jcupitt** [comment]
I think I don't understand exactly what opacity means. Try this tiny SVG;

```svg
<svg xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  width="1000" height="1000" viewBox="0 0 1000 1000">
  <image width="1000" height="1000" xlink:href="./test.jpg"/>
  <image style="mix-blend-mode: multiply; opacity 100%"  
    width="1000" height="1000" xlink:href="./multiply.png"/>
</svg>
```

If you view in chrome and adjust `opacity` you'll see it makes no difference, and that's (obviously) not how your pyvips code implements it.

Do you know of a good description of svg opacity?

**Comment by jcupitt** [comment]
If you set opacity to 100%, pyvips and chrome produce the same output.

**Comment by frankie-price** [comment]
> c

Hi, jcupitt, thanks for your quickly response,  I use `opacity`  to adjust the affect of the texture.

I tried the code you gave, there is a colon missing, so nothing happens. 

Please try the following svg.
```svg
<svg xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  width="1000" height="1000" viewBox="0 0 1000 1000">
  <image width="1000" height="1000" xlink:href="./test.jpg"/>
  <image style="mix-blend-mode: multiply; opacity 100%"  
    width="1000" height="1000" xlink:href="./multiply.png"/>
</svg>
```

**Comment by jcupitt** [comment]
Oh heh thanks! I'll experiment a bit more.

**Comment by jcupitt** [comment]
I think CSS opacity doesn't control the inputs to the blend mode, instead it controls how the layer is overlaid on the parent, that is, there's an implicit `over` that joins the layers after the mix blend modes have been computed.

I tried this py:

```python3
#!/usr/bin/python3

import pyvips
  
def load(name):
    return pyvips.Image.new_from_file(name, access='sequential')

def mul(imagepath, opacity):
    base = load(imagepath)
    layer = base.composite2(load('./multiply.png'), 'multiply')

    return base.composite2(layer * [1, 1, 1, opacity], 'over')

image = mul('./test.jpg', 0.6)
image.write_to_file('new-result.png')
```

And it seems to give the same results as that mul SVG above.  Does that sound right?

**Comment by frankie-price** [comment]
Thank you. 

They only have very small difference on the border of texture image.

If so, then if add the second image for soft-light blending, what is the order of their blending? 

I tried this py:
```python
import pyvips

def load(filename):
    return pyvips.Image.new_from_file(filename, access='sequential')

def blend(imagepath, opacity):
    multiply_image = load('./multiply.png')
    soft_light_image = load('./soft-light.png')
    base = load('./test.jpg')

    # opacity images
    multiply_image = (multiply_image * [1, 1, 1, opacity]).copy(interpretation='srgb')

    soft_light_image = (soft_light_image * [1, 1, 1, opacity]).copy(interpretation='srgb')

    # blend
    layer = base.composite2(multiply_image, 'multiply')
    layer = base.composite2(layer * [1, 1, 1, opacity], 'over')

    layer2 = layer.composite2(soft_light_image, 'soft-light')
    layer2 = layer2.composite2(layer2 * [1, 1, 1, opacity], 'over')

    layer2.pngsave('new-reslut.png')

blend('./test.jpg', 0.6)
```

## results

### group 1

multiply + soft-light + opacity 0.6 
- ps 
![ps](https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.6.png?x-oss-process=image/resize,h_500)
- vips
![vips](https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.6.png?x-oss-process=image/resize,h_500)

### group 1

multiply + soft-light + opacity 0.3
- ps 
![ps](https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.3.png?x-oss-process=image/resize,h_500)
- vips
![vips](https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.3.png?x-oss-process=image/resize,h_500)

**Comment by frankie-price** [comment]
Thank you. 

They only have very small difference on the border of texture image.

If so, then if add the second image for soft-light blending, what is the order of their blending? 

I tried this py:
```python
import pyvips

def load(filename):
    return pyvips.Image.new_from_file(filename, access='sequential')

def blend(imagepath, opacity):
    multiply_image = load('./multiply.png')
    soft_light_image = load('./soft-light.png')
    base = load('./test.jpg')

    layer = base.composite2(multiply_image, 'multiply')
    layer = base.composite2(layer * [1, 1, 1, opacity], 'over')

    layer2 = layer.composite2(soft_light_image, 'soft-light')
    layer2 = layer2.composite2(layer2 * [1, 1, 1, opacity], 'over')

    layer2.pngsave('new-reslut0.3.png')

blend('./test.jpg', 0.3)
```

## results

### group 1

multiply + soft-light + opacity 0.6 
- ps 
https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.6.png
![ps](https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.6.png?x-oss-process=image/resize,h_500)
- vips
https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.6.png
![vips](https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.6.png?x-oss-process=image/resize,h_500)

### group 1

multiply + soft-light + opacity 0.3
- ps 
https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.3.png
![ps](https://sd-assets.oss-us-west-1.aliyuncs.com/ps-mul-light-0.3.png?x-oss-process=image/resize,h_500)
- vips
https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.3.png
![vips](https://sd-assets.oss-us-west-1.aliyuncs.com/vips-mul-light-0.3.png?x-oss-process=image/resize,h_500)

**Comment by jcupitt** [comment]
I think (untested) you need to make three layers: base, mul(base) and soft(mul(base)), and then combine those three layers with your opacity settings.

**Comment by jcupitt** [comment]
This seems to work, or at least gets very close:

```python
#!/usr/bin/python3

import pyvips
  
def load(name):
    return pyvips.Image.new_from_file(name, access='sequential')

def layer(base, overlay, mode, opacity):
    layer = base.composite2(overlay, mode)
    return base.composite2(layer * [1, 1, 1, opacity], 'over')

image = load('test.jpg')
image = layer(image, load('multiply.png'), 'multiply', 0.6)
image = layer(image, load('soft-light.png'), 'soft-light', 0.6)
image.write_to_file('new-result.png')
```

I get:

![new-result](https://user-images.githubusercontent.com/580843/80870656-c9b51d00-8c9f-11ea-9ce7-4e2602bd2664.png)

**Comment by jcupitt** [comment]
I made a better comparison pair:

![compare](https://user-images.githubusercontent.com/580843/82338604-034a8f80-99e5-11ea-9540-41e21fd1b8d8.png)

That's vips on the left, photoshop on the right. There seems to be a small difference in alpha handling on the shirt edge, but otherwise they look close, I think. 

I'll have a go at adding an opacity parameter to composite.

**Comment by jcupitt** [comment]
I think this is done, I'll close. I'll make a new enhancement issue for opacity for composite.

**Comment by sergeevabc** [comment]
Is there a CLI command to place one image on top of another in the lower right corner with a slight indentation, making the overlaid image a little transparent?

**Comment by jcupitt** [comment]
Hi @sergeevabc, you'd need to adjust the transparency of the image to be overlaid first. For the CLI, it would need to be a two stage operation. You need something like pyvips before you can do it in one step.
