### ISSUE TITLE
Question : jpg to pdf

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1628]
Hello,

has there been any change or news since #935  (2018) about option to save jpg as pdf using libvips directly ?
I can do that operation with GraphicsMagick or ImageMagick but the memory use for 21,600x43,200 pixel jpg is massive. 
I was hoping that libvips could have an option to keep the jpeg file data as is, and just 'wrap' the bytes into a pdf jacket, adding the required pdf header with the correct sized mediabox and image xref pdf object without decompressing the image bytes at all.
thank you

**Comment by jcupitt** [comment]
Hello, there's `magicksave`, but I don't know how much memory it'd need.

**Comment by jcupitt** [comment]
I tried:

```
16:06 $ vipsheader CMU-1.svs 
CMU-1.svs: 46000x32914 uchar, 4 bands, srgb, openslideload

16:08 $ /usr/bin/time -l vips magicksave CMU-1.svs x.pdf
      657.83 real       482.06 user       100.78 sys
4531978240  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
   2696104  page reclaims
       672  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
     38083  voluntary context switches
   1025376  involuntary context switches
16:19 $ ls -l x.pdf
-rw-r--r--  1 john  staff  2075520730 27 Apr 16:19 x.pdf
```

I don't know if that counts as low memory use :(

**Comment by CanadianHusky** [comment]
Hello,
thank you very much for such a quick response.
My Windows Command line does not seem to know the 'magicksave' command
`\vips-dev-w64-web-8.9.1\vips-dev-8.9\bin\vips.exe magicksave "input.jpg" "output.pdf"`
command line responds with
`vips: unknown action "magicksave"`

**Comment by CanadianHusky** [comment]
If the 'maximum resident set size' in your test amounts to approx 4.2 Gigabytes for 46,000x32914 pixels with 4 bands, the result is almost identical to GraphicsMagick as far as Memory use is concerned.

**Comment by jcupitt** [comment]
You need `vips-dev-w65-all` -- `magicksave` is not included in the `web` zip for security reasons.

**Comment by jcupitt** [comment]
There are programs to pull JPG images out of PDFs. I don't know about wrapping a JPG as a PDF, but I imagine it's possible.

**Comment by CanadianHusky** [comment]
Understood. Thank you
