### ISSUE TITLE
Issue with transparent gif

### ISSUE THREAD

**Issue by maximilian-biolit** [libvips/libvips#1632]
vips-8.9.2
 
using this command
`vips copy inp.gif[n=-1] out.gif`
Input gif:
![inp](https://user-images.githubusercontent.com/44665803/80584777-7d08e200-8a12-11ea-8859-1b76f6e99a55.gif)
Output:
![out](https://user-images.githubusercontent.com/44665803/80584802-88f4a400-8a12-11ea-93d0-534c569f9792.gif)

**Comment by maximilian-biolit** [comment]
``` vips copy inp.gif[n=-1] out.png```

![out](https://user-images.githubusercontent.com/44665803/80585371-83e42480-8a13-11ea-96a7-cd4b4e5144c5.png)

**Comment by jcupitt** [comment]
Hi @maximilian-biolit, thanks for the nice example, I'll have a look.

**Comment by jcupitt** [comment]
This works in 8.10:

```
vips copy inp.gif[n=-1] x.gif
```

Generating:

![x](https://user-images.githubusercontent.com/580843/80590610-1f759500-8a14-11ea-993a-5fca92d48fc1.gif)

It was this PR:

https://github.com/libvips/libvips/pull/1550

**Comment by maximilian-biolit** [comment]
@jcupitt Okay! thank you!
