### ISSUE TITLE
Error during vips openslideload

### ISSUE THREAD

**Issue by Mamikon95** [libvips/libvips#1633]
Hi there
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020

I use the command "vips openslideload test.svs /test/test.dz --autocrop --vips-progress"
When it comes to 39%, I get an error

```
vips temp-1: 64800 x 43614 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
vips temp-1: 39% complete
** (vips:27622): CRITICAL **: 16:47:11.868: gsf_output_write: assertion 'output != NULL' failed

** (vips:27622): CRITICAL **: 16:47:11.868: gsf_output_close: assertion 'GSF_IS_OUTPUT (output)' failed

** (vips:27622): CRITICAL **: 16:47:11.868: gsf_output_set_error: assertion 'GSF_IS_OUTPUT (output)' failed

** (vips:27622): CRITICAL **: 16:47:11.868: gsf_output_error: assertion 'GSF_IS_OUTPUT (output)' failed
Segmentation fault
```

in Centos 7 checked, such an error comes out.
there are no errors in windows

**Comment by jcupitt** [comment]
Hello @Mamikon95 ,

I'd guess there's something messed up in the way you did the build on centos, but it's hard to say for sure. Maybe try a more recent libgsf-1?

**Comment by Mamikon95** [comment]
> libgsf-1

http://prntscr.com/s85os2

libgsf-1 is latest version

this happens not with all svs but with some. But it’s strange that everything is fine in windows

**Comment by jcupitt** [comment]
1.4.27 is actually very old (2013 I think) and does not have support for large files, especially zip64. I would try updating that.

**Comment by jcupitt** [comment]
The windows binary is built with the latest version of all packages, but centos7 is almost 10 years old. If you use platform libraries, you need to be rather careful, unfortunately.

**Comment by Mamikon95** [comment]
> The windows binary is built with the latest version of all packages, but centos7 is almost 10 years old. If you use platform libraries, you need to be rather careful, unfortunately.

Thank you, unfortunately for Centos 7 I can not find a more recent version ((

**Comment by jcupitt** [comment]
Yes, you'll need to build it yourself. You'll probably find you need to build your own glib as well.

**Comment by jcupitt** [comment]
Or you could switch to centos8, of course.

**Comment by Mamikon95** [comment]
> Or you could switch to centos8, of course.

Thanks, I still decided to upgrade to Debian 10 :)

**Comment by jcupitt** [comment]
Actually, centos7 is working for me in docker:

https://github.com/jcupitt/docker-builds/tree/master/libvips-centos7.2

I see:

```
john@kiwi:~/GIT/docker-builds/libvips-centos7.2 (master)$ docker run -it --rm -v $PWD:/data libvips-centos7.2:latest     /usr/local/bin/vips-8.9 vips openslideload /data/CMU-1.svs /data/test.dz --autocrop --vips-progress
vips temp-1: 46000 x 32914 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
vips temp-1: done in 113s          
john@kiwi:~/GIT/docker-builds/libvips-centos7.2 (master)$ ls -R test_files/ | wc
  31696   31679  358348
```

**Comment by Mamikon95** [comment]
> Actually, centos7 is working for me in docker:
> 
> https://github.com/jcupitt/docker-builds/tree/master/libvips-centos7.2
> 
> I see:
> 
> ```
> john@kiwi:~/GIT/docker-builds/libvips-centos7.2 (master)$ docker run -it --rm -v $PWD:/data libvips-centos7.2:latest     /usr/local/bin/vips-8.9 vips openslideload /data/CMU-1.svs /data/test.dz --autocrop --vips-progress
> vips temp-1: 46000 x 32914 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
> vips temp-1: done in 113s          
> john@kiwi:~/GIT/docker-builds/libvips-centos7.2 (master)$ ls -R test_files/ | wc
>   31696   31679  358348
> ```

Yes, it works for me too, but not for all svs files

**Comment by jcupitt** [comment]
Then I think you'd need to share the file it fails on somehow. Perhaps deb10 will fix the problem.

**Comment by Mamikon95** [comment]
> `/test` will be in your root filesystem, perhaps you've filled that up? You're not supposed to write large files there. Try writing to `/home/someuser/test` instead.

I read somewhere that you need to increase VIPS_DISC_THRESHOLD
But where can I do this?

**Comment by jcupitt** [comment]
Use `df` to see how much space you have and where, then try writing the output of dzsave to a filesystem with a lot of free space.

You don't need to change the disc threshold.

**Comment by Mamikon95** [comment]
> Use `df` to see how much space you have and where, then try writing the output of dzsave to a filesystem with a lot of free space.
> 
> You don't need to change the disc threshold.

http://prntscr.com/s8obil

**Comment by Mamikon95** [comment]
but apparently something is overflowing

**Comment by Mamikon95** [comment]
after dzsave http://prntscr.com/s8oktq

**Comment by Mamikon95** [comment]
@jcupitt 
Oh found
http://prntscr.com/s8oozj
there it is indicated in the "df test"
But why is this happening? what can be done?

**Comment by jcupitt** [comment]
Don't paste screenshots, just copy-paste the text. You can put triple backticks (`) around the text to make it appear in a computer font, eg.

```
john@kiwi:~/GIT/libvips (master)$ df -k
Filesystem     1K-blocks      Used Available Use% Mounted on
udev             3850704         0   3850704   0% /dev
tmpfs             775768      3744    772024   1% /run
/dev/sda1      238140040 218276448   7743736  97% /
tmpfs            3878828    473996   3404832  13% /dev/shm
tmpfs               5120         4      5116   1% /run/lock
tmpfs            3878828         0   3878828   0% /sys/fs/cgroup
```

You've put some large files in your root filesystem somewhere, you'll need to find and remove them. Perhaps you have some SVS files in there?

**Comment by Mamikon95** [comment]
> Don't paste screenshots, just copy-paste the text. You can put triple backticks (`) around the text to make it appear in a computer font, eg.
> 
> ```
> john@kiwi:~/GIT/libvips (master)$ df -k
> Filesystem     1K-blocks      Used Available Use% Mounted on
> udev             3850704         0   3850704   0% /dev
> tmpfs             775768      3744    772024   1% /run
> /dev/sda1      238140040 218276448   7743736  97% /
> tmpfs            3878828    473996   3404832  13% /dev/shm
> tmpfs               5120         4      5116   1% /run/lock
> tmpfs            3878828         0   3878828   0% /sys/fs/cgroup
> ```
> 
> You've put some large files in your root filesystem somewhere, you'll need to find and remove them. Perhaps you have some SVS files in there?

There are many pyramidized svs in the file system, and many images in them. Therefore, the inodes limit has been reached. But there is a lot of free space in the file system.

**Comment by jcupitt** [comment]
Ah that makes sense. You can reformat your drive with more inodes, possibly. I would put the pyramid images on a separate partition.

**Comment by Mamikon95** [comment]
> Ah that makes sense. You can reformat your drive with more inodes, possibly. I would put the pyramid images on a separate partition.

thanks, maybe you know a way to reformat a partition without losing data?

**Comment by jcupitt** [comment]
Sorry, no :(

**Comment by Mamikon95** [comment]
> Sorry, no :(

thanks:)

**Comment by jcupitt** [comment]
I had one other thought: you could zip up your pyramids. It would save the inodes and some disc space as well.

dzsave can write a zip directly, eg.:

```
vips dzsave CMU-1.svs x.zip 
```

**Comment by Mamikon95** [comment]
> I had one other thought: you could zip up your pyramids. It would save the inodes and some disc space as well.
> 
> dzsave can write a zip directly, eg.:
> 
> ```
> vips dzsave CMU-1.svs x.zip 
> ```

but then i can it use in javascript? openseadragon

**Comment by jcupitt** [comment]
You'd need to add some JS to read out the zip header and fetch tiles. I'll close.
