### ISSUE TITLE
Copys TIFF Lab with transparency and alpha output is wrong

### ISSUE THREAD

**Issue by angelmixu** [libvips/libvips#1634]
Hi!

I'm using some TIFF files in LAB format with a transparency and additional alphas, and the output when copying the images are wrong.
Some channels are missed, or empty.

Here it is a .zip with the files:
[tiff_files.zip](https://github.com/libvips/libvips/files/4558420/tiff_files.zip)

I'm using this version from homebrew in macOS:
> % vips -v
> vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020

And using these command-line for copying the files:
```
vips copy "TIF LAB 8b TRANSP.tif" lab8_out.tif
vips copy "TIF LAB 16b TRANSP.tif" lab16_out.tif
```

**Comment by boxerab** [comment]
These are interesting files.  Here are screenshots from opening these files in Krita

![lab8_out](https://user-images.githubusercontent.com/95393/80864604-bc714180-8c51-11ea-8e9c-db2cdc063fb1.png)

![lab16_out](https://user-images.githubusercontent.com/95393/80864616-c98e3080-8c51-11ea-9ef5-000e1e220317.png)

![TIF LAB 8 TRANSP](https://user-images.githubusercontent.com/95393/80864618-cc892100-8c51-11ea-9a2d-407869e0aafa.png)

![TIF 16 LAB TRANSP](https://user-images.githubusercontent.com/95393/80864620-d1e66b80-8c51-11ea-8e34-8179bdf94c78.png)

Are these files being displayed as expected ?

**Comment by boxerab** [comment]
The other odd thing about these images is that the data is signed, including the alpha channels.

**Comment by boxerab** [comment]
It looks like `vips` is converting the alpha channel from 16 to 8 bit precision, and is not handling the signed nature of the data.

**Comment by angelmixu** [comment]
Hi @boxerab , this is how I see the images in photoshop (the original images "TIF LAB*.tif" were generated using Photoshop):

In this case, the selected transparency channel is wrong and a channel is lost:
![Screenshot 2020-05-04 at 09 36 22](https://user-images.githubusercontent.com/2285977/80944910-e611a080-8dea-11ea-9a6e-191866432952.png)
Here the color information is lost, maybe because of choosing the wrong transparency channel? But still all channels are listed:
![Screenshot 2020-05-04 at 09 36 10](https://user-images.githubusercontent.com/2285977/80944922-eb6eeb00-8dea-11ea-813c-a37834f8b0d5.png)
Original 8bit:
![Screenshot 2020-05-04 at 09 35 57](https://user-images.githubusercontent.com/2285977/80944924-eca01800-8dea-11ea-8907-b37a2c856d09.png)
Original 16bit:
![Screenshot 2020-05-04 at 09 35 38](https://user-images.githubusercontent.com/2285977/80944926-edd14500-8dea-11ea-9489-a5518b7e608f.png)

The issue about the output for an 8bit LAB being a 16bit is this one: https://github.com/libvips/libvips/issues/1473

**Comment by angelmixu** [comment]
Hi! This commit in our custom branch looks like fixes this issue :)
https://github.com/angelmixu/libvips/commit/b031680d6db862d4bfaeb01d7264733c4be90338 

At this moment I can't put it in libvips master as we have to fix some issues because our branch is way behind master and there will be some some conflicts.
