### ISSUE TITLE
A few questions about libvips library design

### ISSUE THREAD

**Issue by boxerab** [libvips/libvips#1636]
I'm asking this here because this is one of the few OSS libraries I have found that cares so much about both memory and CPU performance:

1. Do you worry about shared cache of core and it's hyper-threaded partner when optimizing ?
1. Do you use thread affinity in any way in the library ?
1. How do you measure cache misses, false sharing, compute bottlenecks etc ?
1. How do you design your transforms to avoid false sharing of cache lines ?

Thanks!

**Comment by jcupitt** [comment]
Hi @boxerab,

These are good questions. 

1. No, libvips has no special code or design for hyperthreading. It assumes is an unbounded set of independent and equal threads, with some small fixed number in hardware. 

2. libvips uses gthread as a portability layer across posix and win, and that has limited support for these more advanced features.

https://developer.gnome.org/glib/stable/glib-Threads.html

I suppose we hope that the scheduler won't move threads unnecessarily.

3. I've profiled with cachegrind and tried to maintain locality and ordering, but I can't claim to have been very rigorous about it. I'm sure there's lots of room for improvement.

4. libvips threads are largely independent -- each one is given a separate copy of the entire pipeline, and they each work on different parts of the image. This is why libvips is able to run (almost) without locking. My instinct is that there would be limited cache sharing, but I don't have any evidence for that.

**Comment by boxerab** [comment]
> 
>     1. No, libvips has no special code or design for hyperthreading. It assumes is an unbounded set of independent and equal threads, with some small fixed number in hardware.

Thanks. As you probably know, a core and its hyperthreaded twin share a lot of resources, so, performance can drop if each thread of the pair is working on memory-intensive task where each thread thrashes the other L1 cache. But, of course managing this would require design changes to libvips. 

> 
>     2. libvips uses gthread as a portability layer across posix and win, and that has limited support for these more advanced features.
> 
> 
> https://developer.gnome.org/glib/stable/glib-Threads.html
> 
> I suppose we hope that the scheduler won't move threads unnecessarily.
> 
I think it would be interesting to add CPU affinity support to gthreads.


>     1. I've profiled with cachegrind and tried to maintain locality and ordering, but I can't claim to have been very rigorous about it. I'm sure there's lots of room for improvement.

Did you know that Intel VTune has a free license for open source projects ?

https://software.intel.com/en-us/articles/qualify-for-free-software#opensourcecontributor

I have one for my project, and it was interesting to see where the performance bottlenecks are.
Learning curve is not that bad.

> 
>     2. libvips threads are largely independent -- each one is given a separate copy of the entire pipeline, and they each work on different parts of the image. This is why libvips is able to run (almost) without locking. My instinct is that there would be limited cache sharing, but I don't have any evidence for that.

Right, so the surprising thing is that if two threads share a cache line (64 bytes) and the first thread writes to that line, then it invalidates the cache of the second thread and it has to fetch slower memory. One solution is to align memory allocations on 64 byte boundaries, and also align the memory buffer size to 64.

**Comment by jcupitt** [comment]
Yes, thread affinity for gthread would be fun. I've no idea how to do the win32 implementation though :(

I'll have a look at vtune, thanks!

I think libvips threads will share cache lines very rarely, so I'd be surprised if 64-byte alignment made much difference. Of course experiment trumps speculation and it'd be interesting to see numbers. You could add the 64-byte thing to `vips_tracked_malloc()` very easily:

https://github.com/libvips/libvips/blob/master/libvips/iofuncs/memory.c#L308

**Comment by jcupitt** [comment]
It sounds like linux, BSD, macos and win all approach thread affinity slightly differently:

https://news.ycombinator.com/item?id=10929385

It would probably be tricky to make a simple wrapper for it.

**Comment by boxerab** [comment]
> I think libvips threads will share cache lines very rarely, so I'd be surprised if 64-byte alignment made much difference. Of course experiment trumps speculation and it'd be interesting to see numbers. You could add the 64-byte thing to `vips_tracked_malloc()` very easily:
> 
> https://github.com/libvips/libvips/blob/master/libvips/iofuncs/memory.c#L308

Yes, since each `vips` thread is mostly working independently, you avoid many of these issues.
If you used a traditional thread pool, then situation would be quite different.

The hacker news discussion was interesting. Of course, as you said, always need to test in your own work flow.
