### ISSUE TITLE
Comments Metadata is lost on resize

### ISSUE THREAD

**Issue by screamingjungle** [libvips/libvips#1640]
I'm looking to retain EXIF+IPTC+Comments (all) metadata on vips resize. EXIF and IPTC is retained but not Comments.

vips-8.9.2
"vips resize 1.jpg 2.jpg 1"

Wondering if this by design... not able to find any info on this.

**Comment by jcupitt** [comment]
Hello @screamingjungle,

libvips preserves EXIF, XMP, ICC, and IPTC metadata in JPEG. Can you give an example of a JPEG file containing metadata which is not preserved?

**Comment by screamingjungle** [comment]
Apologies  - it's an exif comment - found it. closing issue. Thanks for the quick reply!

The software (ifran) I'm using seems to miss seeing the exif comment after the resize but it's there looking at php's exif_read_data.  It's the image viewer's bug not vips!

**Comment by jcupitt** [comment]
Huh that's odd, I wonder why irfanview can't see it. Anyway, I'm glad it's not our fault heh.
