### ISSUE TITLE
JPEG JFIF information replaces resolution when unit is 0

### ISSUE THREAD

**Issue by angelmixu** [libvips/libvips#1641]
Hi!

Using this jpeg file: 
![waterfinal2](https://user-images.githubusercontent.com/2285977/81047489-cba6f800-8eba-11ea-8f7b-4851b8150b6e.jpg)

When being opened, the resolution is veeery big.
As I could debug on the jpeg2vips.c file, is that when there's JFIF information, and the unit is 0, it puts the Xres and Yres of the VipsImage to 100.

After taking a look at jpeg specifications here:
https://www.w3.org/Graphics/JPEG/jfif3.pdf
https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format

Respectively, it says:
`units = 0: no units, X and Y specify the pixel aspect ratio`
`00 : No units; width:height pixel aspect ratio = Ydensity:Xdensity`

So, as I understand, when the unit is 0, it's not a resolution that is specified, but an aspect ratio of the image. So, when unit 0, the resolution main JPEG resolution should be aplied this aspect ratio.
In this case 100/100 is 1, so it would maintain a 72 DPI for this image.

What do you think?

**Comment by jcupitt** [comment]
I agree, this looks wrong.

How about leaving xres, but setting yres from that for the specified aspect ratio? I patched master.

**Comment by angelmixu** [comment]
For me it looks fine!
Thanks @jcupitt !!! :)

**Comment by angelmixu** [comment]
hey @jcupitt I was testing the fix, and with this fix it generates a VipsImage of 1x1 resolution.
xres and yres are just declared before the jfif switch and are set to 1.
Later, when looking for EXIF info, there isn't any, so the output image resolution is 1x1.
Looks like the main JPEG value for resolution is not read anywhere.

**Comment by jcupitt** [comment]
Yes, perhaps we should default to 72dpi.
