### ISSUE TITLE
How to uninstall libvips?

### ISSUE THREAD

**Issue by narFnarF** [libvips/libvips#1643]
I used the instructions on how to build from source (https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball). It was successful in building but I was lacking some dependancies.

Now I need to uninstall what I just installed. How do I do this? 
(sorry if it's a dumb question. I'm fairly new to the linux universe).

I tried to look around for instructions on how to uninstall libvips built from source, but found none. Maybe it's something you would want to provide?

In case it makes a difference:
* I'm on a Raspberry Pi 2B
* running Raspbian Stretch

**Comment by jcupitt** [comment]
Hello @narFnarF,

Just `make uninstall` from the directory you ran `make install` in. If you no longer have the build area, you can install again, then immediately uninstall afterwards.

By default, it'll have installed to `/usr/local`. You can also just go there and delete the files by hand (it's pretty obvious which ones you need to nuke).

You probably know, but libvips is available for the r-pi -- just `apt install libvips42` -- so you may not need to build it yourself.

**Comment by narFnarF** [comment]
Thanks for your detailed answer. You answered my questions, and then all the following questions I was about to ask! 😄 

The reason I need to build is that the packaged version for Raspbian is too old. For context, I'm trying to run [Bibliogram](https://github.com/cloudrac3r/bibliogram), which depends on [Sharp](https://sharp.pixelplumbing.com/install), which depends on a recent version of libvips.

Unfortunately, I had deleted my source folder, so I'm currently doing the `./configure` and `make` part again (takes a while on a Pi!). Will I need to also do `make install` before I do `make uninstall` ?

**Comment by jcupitt** [comment]
I'm not sure to be honest. It's harmless to install twice (all it does is copy some files) so it doesn't matter too much.

sharp includes a libvips ARM binary, it might work without you building your own.

You might need to configure your system so that node sees packages in `/usr/local`, I don't know raspbian very well.

**Comment by narFnarF** [comment]
Thanks for your help. The uninstall worked!

As I suggested in my first message, it might be nice to add a line in the doc on how to uninstall, even if it's considered an obvious knowledge :)

Thanks again!

**Comment by jcupitt** [comment]
OK, glad it's working.
