### ISSUE TITLE
Make thumbnail

### ISSUE THREAD

**Issue by sonyarianto** [libvips/libvips#1644]
Hi @jcupitt I have question.
How to make image like this using vips CLI (or any VIPS command)
1. I have for example image .png with size 160x85 let say aaa.png
2. I want the final image is aaa.jpg with size 300x300 and above image is located on the center of new image.

How to do that? Thank you in advance.

**Comment by sonyarianto** [comment]
Oh sorry solved by using this command. Thank you.

vips gravity logo.png logo.jpg[Q=100] centre 300 300 --background "255 255 255"

**Comment by jcupitt** [comment]
That's right. You don't need all the 255s, this will work too:

```
vips gravity logo.png logo.jpg[Q=100] centre 300 300 --background 255
```

**Comment by sonyarianto** [comment]
ohhh @jcupitt this is great tip, thank you very much
