### ISSUE TITLE
sudo apt install - doesn't get the latest version

### ISSUE THREAD

**Issue by drewlr** [libvips/libvips#1645]
Hi!

I'm trying to install the latest libvips on Ubuntu 18.04.3 , but running

```
sudo apt-get update
sudo apt install libvips libvips-dev
```

gets 8.4.5 only.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libvips42' instead of 'libvips'
libvips-dev is already the newest version (8.4.5-1build1).
libvips42 is already the newest version (8.4.5-1build1).
The following packages were automatically installed and are no l

```

Am I doing something wrong?

Thanks!
Andrea

**Comment by jcupitt** [comment]
Hello @drewlr,

Ubuntu 18.04 ships with libvips 8.4.5. You'll need to update your Ubuntu, or build libvips yourself.

**Comment by drewlr** [comment]
I see, thanks @jcupitt !

Out of curiosity, do you have a list of what OS and versions ships with which versions of libvips?

We are considering integrating it into a package, but would be curious to see these stats to get an idea of what might be a good compromise between "latest" and "easy to install" in the short term.

**Comment by jcupitt** [comment]
Sorry, there are so many I don't try to track them all. Deployment via something like docker is probably simplest if you want a certain version available at runtime.

For example, here's one that deploys current stable libvips on ubuntu 18.04:

https://github.com/jcupitt/docker-builds/tree/master/libvips-ubuntu18.04

**Comment by drewlr** [comment]
I see, thanks!

**Comment by martimpassos** [comment]
hi @jcupitt, I'm trying to get the latest version on Ubuntu 20.04. Is building by myself still the only option? I could only get 8.9.1 via `apt`

**Comment by martimpassos** [comment]
hi @jcupitt, I'm trying to get vips 8.10 or above on Ubuntu 20.04. I could only get to 8.9.1 via `apt`. Is building it myself the only option in this scenario too?

**Comment by jcupitt** [comment]
Hi @martimpassos,

You could add a PPA, though I don't know which would be best. Alternatively, you can make your own PPA and use that. You can also make a binary and deploy as a tarball (libvips is a relocatable package).
