### ISSUE TITLE
How to get Photometric Interpretation usingC program

### ISSUE THREAD

**Issue by vkkindia** [libvips/libvips#1646]
Hi John,

The test.tif has 
***snip***
Photometric Interpretation: min-is-white
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 245
  Planar Configuration: single image plane
***snip***

for some tiff files the Photometric Interpretation: is min-is-white and for others it is min-is-black
I am struck at in my c program :

int image_width = vips_image_get_width(in); // iam getting width
VipsInterpretation inter = vips_image_get_interpretation(in); //how to get its value

how to get Interpretation.

thank you

**Comment by jcupitt** [comment]
Hello @vkkindia 

libvips converts 1 bit images to 0 == black, 255 == white, so you can't tell what the TIFF photometric interpretation was.

**Comment by vkkindia** [comment]
right now I am doing this manually specifying miniswhite while saving outfile

vips_image_write_to_file( in_file, out_file, "compression",VIPS_FOREIGN_TIFF_COMPRESSION_CCITTFAX4,"miniswhite",1, NULL )

any idea on how to get this details from input tiff itself

**Comment by jcupitt** [comment]
You're right, libvips doesn't tell you. You can get it from `tiffinfo`:

```
$ tiffinfo cramps.tif | grep "Photometric Interpretation"
  Photometric Interpretation: min-is-white
```

**Comment by vkkindia** [comment]
Thanks
