### ISSUE TITLE
GIF images aren't loaded properly. Another case

### ISSUE THREAD

**Issue by DanteG41** [libvips/libvips#1649]
8.9.2 (https://github.com/libvips/libvips/issues/1543) fixed loading for some gifs. But there was another case
![test](https://user-images.githubusercontent.com/5330084/81548626-ff8c8c80-9396-11ea-98c3-74f93c4c812d.gif)
![tn_test](https://user-images.githubusercontent.com/5330084/81548700-1cc15b00-9397-11ea-954c-69cd248251cd.png)

**Comment by jcupitt** [comment]
Oh argh, thank you for the report. 

git master libvips has some more improvements to the gif loader, I see:

```
vipsthumbnail bird.gif[n=-1] -o x.png
```

![x](https://user-images.githubusercontent.com/580843/81550474-32735800-9378-11ea-9836-d8de5d8d07bf.png)

Though it's still leaving the tips of the wings. GIF is such an annoying format :( I'll have a look.

**Comment by jcupitt** [comment]
Another option is to abandon giflib, which has some serious problems, and try libnsgif instead. See this issue: https://github.com/libvips/libvips/issues/1084

**Comment by kleisauke** [comment]
It might also be worth looking at [gifdec](https://github.com/lecram/gifdec). It's less than 500 lines of C99.

**Comment by jcupitt** [comment]
OK, I think this is now fixed in master. Any testing would be great!

Thank you again for the report, @DanteG41.

**Comment by jcupitt** [comment]
I had a quick look at gifdec. It seems nice, but it only supports read from file, so we'd need to rework it on top of (perhaps) VipsSource, and it does not seem very robust. For example, it crashes with a segv if part of a frame lies outside the canvas.

**Comment by jcupitt** [comment]
8.10 beta2 is up now and includes this fix. 

https://github.com/libvips/libvips/releases/tag/v8.10.0-beta2

I'll close.
