### ISSUE TITLE
Freeing memory in postclose signal for vips_pngload_buffer

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1651]
I am calling `vips_pngload_buffer` in one of my go functions to load the png and here is how I call it.

vips.go
```
var buf []byte
var image *C.VipsImage
....
imageBuf := unsafe.Pointer(&buf[0])
err := C.vips_init_image(imageBuf, length, &image)
```
vips.h
```
int vips_init_image (void *buf, size_t len, VipsImage **out) {
   code = vips_pngload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
.
.
.
}
```
I saw in libvips code that _You must not free the buffer while @out is active. The 
 #VipsObject::postclose signal on @out is a good place to free_. So I changed the method to something like this:

vips.h
```
void clear_objects_after_postclose(VipsImage **image, void *user_data) {
  g_free( user_data );
}

int vips_init_image (void *buf, size_t len, VipsImage **out,) {
   code = vips_pngload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
   g_signal_connect(out, "postclose", G_CALLBACK( clear_objects_after_postclose ), buf);
}
```

But i get segmentation violation here and a ton of glib-Gobject errors:
```
 GLib-GObject-WARNING **: 15:43:45.745: instance of invalid non-instantiatable type '(null)'

 GLib-GObject-CRITICAL **: 15:43:45.745: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

 GLib-GObject-WARNING **: 15:43:45.745: instance of invalid non-instantiatable type '(null)'

 GLib-GObject-CRITICAL **: 15:43:45.745: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

 GLib-GObject-CRITICAL **: 15:43:45.745: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

 GLib-GObject-CRITICAL **: 15:43:45.745: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
```

Any help here?

**Comment by jcupitt** [comment]
Hi, you've got a * too few. Try:

```C
g_signal_connect(*out, "postclose", G_CALLBACK( clear_objects_after_postclose ), buf);
```

**Comment by jcupitt** [comment]
(I would build with `-Wall`, it should catch errors like this at compile-time)

**Comment by jcupitt** [comment]
And I wouldn't use `RANDOM` unless you really have to. It will be slow.

**Comment by revathi-murali** [comment]
> And I wouldn't use `RANDOM` unless you really have to. It will be slow.

So `VIPS_ACCESS_SEQUENTIAL` is recommended?

**Comment by revathi-murali** [comment]
Also is there a way to check if `buf` is actually freed? I see the same count in the objects alive.

**Comment by jcupitt** [comment]
`buf` isn't an object, freeing it won't affect the live object list.

Yes, SEQ is faster and uses less memory, there are some notes here:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html#sequential-access

`thumbnail` is much faster again, if you are shrinking images.

**Comment by revathi-murali** [comment]
I am doing `vips_arrayjoin` and there is no explicit mention of clearing the input image in postclose call for `vips_arrayjoin`. 
I tried freeing up the input image object via `vips_area_unref` -> resulted in seg fault.
`g_signal_connect` - Did not clean up the object.

```
static void
clear_image_after_close(VipsImage **out, VipsImage **in) {
  vips_area_unref(VIPS_AREA(in));
}
```
```
int 
vips_arrayjoin_bridge(VipsImage **in, VipsImage **out, int n) {
  int result;
  double background[4] = {255.0, 255.0, 255.0, 255.0};
  VipsArrayDouble *vips_bg = vips_array_double_new(background, 4);

  result = vips_arrayjoin(in, out, n, "across", 1, "background", vips_bg,  NULL);
  vips_area_unref(VIPS_AREA(vips_bg));
  // vips_area_unref(VIPS_AREA(in)); -> This results in  seg fault
  // g_signal_connect(*out, "close", G_CALLBACK( clear_image_after_close ), *in); -> does not clear the object
  return result;
}
```

**Comment by revathi-murali** [comment]
I am doing `vips_arrayjoin` and there is no explicit mention of clearing the input image in postclose call for `vips_arrayjoin`. 
I tried trying to free up the input image object. Can you let me know the options?
I tried with `vips_area_unref(VIPS_AREA(in))` and `g_signal_connect(on postclose of out)` but it did not free

```
int 
vips_arrayjoin_bridge(VipsImage **in, VipsImage **out, int n) {
  int result;
  double background[4] = {255.0, 255.0, 255.0, 255.0};
  VipsArrayDouble *vips_bg = vips_array_double_new(background, 4);

  result = vips_arrayjoin(in, out, n, "across", 1, "background", vips_bg,  NULL);
  vips_area_unref(VIPS_AREA(vips_bg));
  // How to clear `in`?
  return result;
}
```

**Comment by kleisauke** [comment]
#1652 might be also relevant here.

**Comment by revathi-murali** [comment]
@kleisauke So you are saying that freeing up input object for`vips_arrayjoin` depends on `vips_array_image_append`?

``vips_array_image_append` gives an entirely new array object and this new array is passed to `vips_arrayjoin`.

**Comment by jcupitt** [comment]
Sorry, I don't understand the question :( 

All libvips operations work in the same way: you unref the inputs after calling the operation, and you own the refs to any outputs.

You can use arrayjoin like this:

```C
/* compile with:
 *
 * gcc -g -Wall arrayjoin.c `pkg-config vips --cflags --libs`
 *
 * test with:
 *
 * ./a.out ~/pics/k2.jpg ~/pics/shark.jpg x.jpg
 *
 */

#include <vips/vips.h>

int
main( int argc, char **argv )
{
        VipsImage *images[2];
        VipsImage *result;
        int i;

        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        vips_leak_set( TRUE );

        for( i = 0; i < 2; i++ )
                if( !(images[i] = vips_image_new_from_file( argv[i + 1],
                        "access", VIPS_ACCESS_SEQUENTIAL,
                        NULL )) )
                        vips_error_exit( NULL );

        if( vips_arrayjoin( images, &result, 2, NULL ) )
                vips_error_exit( NULL );

        for( i = 0; i < 2; i++ )
                g_object_unref( images[i] );

        if( vips_image_write_to_file( result, argv[3], NULL ) )
                vips_error_exit( NULL );

        g_object_unref( result );

        return( 0 );
}
```

I would not call the C API myself for a language binding (I've said this before), it's for programmers, not for programs. I would use the gobject layer.

**Comment by revathi-murali** [comment]
@jcupitt Here is how I am clearing the objects

vips.go
```
var out *C.VipsImage
vImage := C.vips_array_image_get(inputArray, &length)
returnCode := C.vips_arrayjoin_bridge(vImage, &out, length)
C.vips_area_unref(C.VIPS_AREA(inputArray)) -> Clearing inputArray. But could see live objects
```
vips.h

````
int 
vips_arrayjoin_bridge(VipsImage **in, VipsImage **out, int n) {
  double background[4] = {255.0, 255.0, 255.0, 255.0};
  VipsArrayDouble *vips_bg = vips_array_double_new(background, 4);

  result = vips_arrayjoin(in, out, n, "across", 1, "background", vips_bg,  NULL);
  vips_area_unref(VIPS_AREA(vips_bg));
  int i;
  for(i = 0; i < n; i ++) {
    g_object_unref(in[i]); -> Could see live objects still present
  }
  return result;
}
````

So  I am freeing the objects in the following manner


- inputArray - Cleared in Go file. Refer vips.go
- vImage - Cleared in C file. Refer vips.h 

But I could see live objects at the end of the run :|

**Comment by jcupitt** [comment]
Sorry, that's all mixed up. You are unreffing twice, you'll see crashes somewhere else.

It sounds like you have reference counting problems everywhere. I would start again -- make a small, self-contained example that just calls one vips operation, and get that running correctly. Once you understand how the ref counting works, then expand slowly, testing for leaks with every addition.
