### ISSUE TITLE
vips_text() align incorrect parameter names

### ISSUE THREAD

**Issue by keiviv** [libvips/libvips#1654]
The _align_ parameters for vips_text() are supposed to be _left/centre/right_ — as both the documentation and common logic (with a British spelling) suggest. 

Despite the logic and own documentation — VipsAlign actually uses absolutely different parameters names: _low/centre/high_, where _low_ means _left_, and _high_ means _right_.

An correct attempt to use _left_ or _right_ results an error.

It looks like it was originally written for the purpose of vertical alignment, and later switched to horizontal justification without properly altering or aliasing the parameter names.

##### To sum it up:
1. The vips_text documentation for _align_ is currently incorrect.
2. One must first find and then use the correct yet rather confusing names for it, which is not high... I mean low... I mean right.
3. While not critical, it adds to the [wtf pool](http://commadot.com/wtf-per-minute/), which in some cases could be already full for other reasons.

##### Suggested improvement:
Aliasing it would be most helpful for new Vips users like myself — to save an extra minute and to maintain a high-quality perception of the library. Vips is the greatest image meta lib of all, with the coolest devs I ever encountered on GitHub — so let this not spoil the image for future users :)

##### References:
> create/text.c:546:
````c
@align: #VipsAlign, left/centre/right alignment
````
> create/text.c:152:
````c
   case VIPS_ALIGN_CENTRE:
      palign = PANGO_ALIGN_CENTER;
      break;

   case VIPS_ALIGN_HIGH:
      palign = PANGO_ALIGN_RIGHT;
      break;

   default:
      palign = PANGO_ALIGN_LEFT;
      break;
   }
````
> iofuncs/enumtypes.c:298:
````c
      if( etype == 0 ) {
      static const GEnumValue values[] = {
         {VIPS_ALIGN_LOW, "VIPS_ALIGN_LOW", "low"},
         {VIPS_ALIGN_CENTRE, "VIPS_ALIGN_CENTRE", "centre"},
         {VIPS_ALIGN_HIGH, "VIPS_ALIGN_HIGH", "high"},
         {VIPS_ALIGN_LAST, "VIPS_ALIGN_LAST", "last"},
         {0, NULL, NULL}
      };
````
##### P.S. 
As a non-British person, I first thought it's their kinky way to name things (like Alice did) so my own documentation contained a note:

> Fook mi guv'nor: low = left / centre = center / high = right / talking white rabbit = high

Then an actual British person came and stated saying something angrily, of which I could only understand "knackered", "centre" and "bloody". He then typed on my keyboard "This is not how we call left and right, you berk arse". At that point I had an eureka moment — "maybe" — thought I — "this is not how they call left and right". So I shared this discovery of mine with you.

**Comment by jcupitt** [comment]
Ooop! I've fixed this dumbness, thanks for the report.

Yes, the Bringlish spelling of API terms is a historical accident. I hope it's not too annoying.

**Comment by keiviv** [comment]
While British is historically understandable, the terms _low_ and _high_ for _left_ and _right_ are absolutely confusing in the context of horizontal alignment. I don't care about it for myself — as I'm already aware of this quirk — but of future Vips users: Your fix — while technically accurate, ironically makes it harder to guess the right names — as it omits the wrong-right pair relations:

##### Before:
1. User tries to use left or right for left or right.
2. Gets an error.
3. Looks up VipsAlign, says "wtf", quickly understands the relations of the wrong-right terms. 

##### With the fix:
1. User tries to use left or right for left or right.
2. Gets an error.
3. Looks up VipsAlign, says "wtf", stares at the list of terms _none_ of which has anything to do with left or right at all.

Wonder if it is possible to add aliases with the non-wtf terms for future users. You and I can live with it, but imagine you saw that list for the first time while trying to align right.

**Comment by jcupitt** [comment]
VipsAlign is used for vertical alignment too, so low/center/high means low coordinate, centre coordinate, high coordinate.

The API is generated at runtime by introspecting the library binary, so it'd be tricky to add aliases. We'd need to change the underlying C.

**Comment by keiviv** [comment]
Maybe some note for future users then?

**Comment by jcupitt** [comment]
I supose you could have:

```C
typedef enum _VipsAlign {
    VIPS_ALIGH_LEFT = 0,
    VIPS_ALIGN_LOW = 0,
    VIPS_ALIGN_TOP = 0,
    VIPS_ALIGN_CENTRE = 1,
    VIPS_ALIGN_RIGHT = 2,
    VIPS_ALIGN_HIGH = 2,
    VIPS_ALIGN_BOTTOM = 2
} VipsAlign
```

But that might be more confusing. IDEs (for example) would offer users seven possible values for text alignment and it wouldn't be obvious how they differed.

**Comment by keiviv** [comment]
This is not terribly urgent, I'm sure some time later you'll find the best way to do it. Maybe sit on it?

**Comment by jcupitt** [comment]
I tried to revise the docs again, and mentioned the low/centre/high thing.
