### ISSUE TITLE
`text` will load a fontfile even if it's already loaded

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#1655]
`text` does not keep track of which fontfiles it has already loaded, so a loop like:

```lua
for i = 1, 10000 do
   vips.Image.text(text, {width = 100, height = 100, fontfile = 'your_fontfile.ttf', font = 'Your_Font'})
end
```

Will slow down and also eat memory. It seems fontconfig does not try to stop this either.

See https://github.com/libvips/lua-vips/issues/35 for the original context.

**Comment by jcupitt** [comment]
It's a simple change so I just patched master. Thanks for the report @keiviv.

**Comment by keiviv** [comment]
**John** — you and @kleisauke  are the most professional devs I ever encountered on GitHub (or like anywhere) — your responses are quick and on point. On top of that, I saw you helping Vips users with answers and examples everywhere — from here to Reddit. 

In my hundreds of interactions with devs, I never encountered anything better than Vips.
