### ISSUE TITLE
How to calculate gamma exponent using input from a slider

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1658]
I'm using a slider to control the gamma of an image with values in the range [-100, 0, 100]. Where -100 is lighter, 100 darker and 0 is disabled.

The problem is that I don't know how to map those integer values to to a correct exponent. Any idea or documentation that I can read to find a possible way to calculate that?.

I'm using libvips from the command line with version `vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020`.

Thanks.

**Comment by jcupitt** [comment]
Hello @jfcalvo,

`vips gamma` calculates `y = x ^ (1 / gamma)`:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-gamma

So 1.0 does nothing, values towards 0 make it darker, values greater than 1.0 make it lighter. `(slider + 100) / 100` should work OK.

**Comment by jfcalvo** [comment]
Thank you very much @jcupitt. I have modified the formula a little bit and it's working for me.
