### ISSUE TITLE
Please support loading from Gio

### ISSUE THREAD

**Issue by hongquan** [libvips/libvips#1659]
I'm writing application with GTK+ and Python (through PyGObject), and would like to use Vips for some image processing.

Because my app is a GTK+ app, it is convenient to use Gio for reading file, because Gio can handle loading from disk or any network service (FTP, SFTP, SMB, etc.) with the same API. From `Gio.FileStreamInput`, I would like to feed to Vips but find no API from its GIR-binding. The `Vips.Image.new_from_file` function can't be used because file is not always local.

I don't want to use CFFI binding, because this library is not distributed on Ubuntu repo yet. Also, GIR is not an issue to me, because my app already uses some GObject-based libraries (GTK, GStreamer), which are not installable from pip.

**Comment by jcupitt** [comment]
Hello @hongquan,

libvips supports custom connections: read and write objects which you can link to your own code. There's a pyvips example here:

https://github.com/libvips/pyvips/blob/master/examples/connection.py

You should be able to use that to link to GIO.

pyvips used to use gobject-introspection, but we had to switch away. It was slow and unreliable. The cffi binding is much, much better.

You could try checking out an old branch of pyvips and see if the goi binding still works, but I don't intend to support it.

**Comment by hongquan** [comment]
Thanks.
