### ISSUE TITLE
Recommended golang binding for libvips

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1660]
Hi, 

I am currently using bimg https://github.com/h2non/bimg/ for my go projects. But @jcupitt  mentioned about auditing bimg code as certain functions are not optimal or probably having some issues with memory leak or something.

Other options are:

- [imgproxy](https://github.com/imgproxy/imgproxy) 
- [govips](https://github.com/davidbyttow/govips)  

But not sure if they are being audited.

Any recommendations from libvips team here?

**Comment by revathi-murali** [comment]
@jcupitt ^^

**Comment by jcupitt** [comment]
Sorry, I've never used Go and I don't know anything about any of these bindings.

**Comment by tinkyawoo** [comment]
Sorry to revive the thread. Go binding of vips (davidbytow) doesn't seem to have IfThenElse function implemented. Is there a way to call that function?

**Comment by jcupitt** [comment]
Sorry, no idea, I'd ask on the govips repo.

**Comment by tinkyawoo** [comment]
Thanks. It's not that I specifically needed that function. What I need is to get pixels above threshold and the rest zeroed so that I can do selected masking and bluring specific part of image based on certain thresholds. I am new to vips and trying to wrap around my head how to successfully use the library and see if I can achieve things with it on my next project. Is there any other way that I can do that kind of things in currently available exposed function in govips?

**Comment by jcupitt** [comment]
You can use AND and OR, of course, would that work?

The relational operators use 0 and 255 for FALSE and TRUE, so eg. (in python):

```python
image = (image > 200) & image
```

zeros all pixels of 200 or less.

You can do that to a look up table as well:

```python
# `identity` makes a ramp LUT, ie. the identity function
lut = pyvips.Image.identity()
lut = (lut  > 200) & lut
image = image.maplut(lut)
```

`maplut` is pretty quick and always takes the same length of time no matter how complex the expression that generated the lut, so it can give a nice speedup.

**Comment by jcupitt** [comment]
`ifthenelse` has the nice property that it short-circuits. 

For each region of pixels it computes, it evaluates the condition image first, then checks for all true or all false. If theres no pixel-picking to do for this area, it then just forwards the pixel region request to either the true image or the false image.  This means you can blur a small part of a large image, and it'll only blur the area that needs it, the rest of the image will not be computed.

The bool operators don't do this, so they can be quite a bit slower in some cases.

**Comment by jcupitt** [comment]
.... sorry, last post, I'd think ifthenelse would be simple to add, you could try making a PR for the feature.

**Comment by tinkyawoo** [comment]
Yes, in Python I used to do the same treatment of image as it array in Numpy like image < 200, things like that. But now, I need to work on golang and need libvips but those easy-to-use features like in Python are nowhere near that. To do that in golang and in C is to use vips_more, vips_less, but those are not implemented in govips wrapper either. So, I am trying to find ways to go around that or even ways to implement and add those features myself. But I am a bit rusty in C now and not comfortable managing low-level details like 20 years ago. If I need to, I must anyway.

**Comment by jcupitt** [comment]
libvips was designed to be self-binding. pyvips, php-vips and ruby-vips (for example) introspect the libvips library they find at runtime and present the operations they find. You can add a new C func to libvips and it automatically appears in pyvips.

Ideally govips would be rewritten to work this way too.

**Comment by tinkyawoo** [comment]
Ah, all is good now. CGO is in fact easy to work with. After reconfiguring my development environment, was able to crawl up libvips headers and able to access straight from Go code. I just had to write some nice memory-safe wrapper to expose pure Go function to safely use without worrying about memory management (like how other Govips functions nicely wrap around C functions). Now I know I can deal with the beast, my long journey started :D 

BTW, I can see your repo host libvips too. Is there any variation from original one?

Thanks @jcupitt

**Comment by jcupitt** [comment]
libvips used to live in my area, but we set up libvips.org and moved it there. My copy is just a fork for dev now.
