### ISSUE TITLE
tiffsave to add compression to a multipage TIFF

### ISSUE THREAD

**Issue by dgutman** [libvips/libvips#1661]
##I have a collection of multipage TIFF files that do not appear to have any compression, so the resulting files were huge.   Is there a generic way to have vips (or pyvips) go through a multipage tiff image, and if a page is  'Compression Scheme: None' to apply lzw/deflate to those pages?

**Comment by jcupitt** [comment]
Hello @dgutman,

Unfortunately, libvips can only write multipage TIFFs where each page has the same dimensions.

If your images are like this, you can just do:

```
vips copy in.tiff[n=-1] out.tiff[compression=deflate]
```
