### ISSUE TITLE
How to do common image adjustments like brightness, contrast, exposure or saturation

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1662]
Hi, I'm totally lost about how to do basic image adjustments using vips command line like these ones:
* Brightness
* Exposure
* Saturation
* Contrast
* Shadows

Any documentation or commands that I'm missing?. I'm using `vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020`.

Thanks in advance.

**Comment by jcupitt** [comment]
There's an open issue here with some questions and examples: https://github.com/libvips/libvips/issues/59

The vips CLI is pretty basic and you'll find it's awkward to use for anything complex. I would use something like Python or Ruby.

If you must use the CLI, you need `linear`. This performs linear transforms, ie. `y = a * x + b`.

For example:

```
vips linear input.jpg output.jpg 1.2 0
```

And each pixel in `output.jpg` will be 20% brighter. You can adjust each band separately like this:

```
vips linear input.jpg output.jpg "1 1.2 1" 0
```

And just the middle (green) band will be brightened.

For saturation, transform to CIELAB and scale AB.

```
vips colourspace input.jpg t1.v lab
vips linear t1.v t2.v "1 1.2 1.2" 0
vips colourspace t2.v output.jpg srgb
```

There's quite a complex thing for mapping tones, see `tonelut`.

**Comment by jfcalvo** [comment]
Thank you very much for the quick response @jcupitt 

I will try to play with your examples. I need to use the command line because I'm using Elixir for this project and I don't have the possibility of using a library.

**Comment by jfcalvo** [comment]
@jcupitt I understand that the following is to increment the brightness:

```
vips linear input.jpg output.jpg "1 1.2 1" 0
```

How is possible to reduce it?

**Comment by jcupitt** [comment]
Hello again, sorry, this dropped off my radar.

Your example will scale green by 20%. You can use a number less than 1 to reduce it, for example:

```
vips linear input.jpg output.jpg 0.7 0
```

To decrease brightness by 30%.
