### ISSUE TITLE
possible bug in TIF LZW compression

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1663]
Hello,

There seems to be a strange issue in the LZW compression logic when input image has been modified with a linear transformation like ( img * 2 - 255 )
Very simple example to reproduce the problem below

```
Dim input As String = "c:\temp\input.tif"
        Dim vipsimg As Image = Image.NewFromFile(input, True, access:=Enums.Access.Sequential) 
        vipsimg = vipsimg * 2 - 255 'increase contrast *****
        vipsimg.Jpegsave("C:\temp\output.jpg", 75) 'works
        vipsimg.Tiffsave("C:\temp\output_lzw.tif", "lzw") 'FAILS ??? Output file is corrupt. Why ?
        vipsimg.WriteToFile("c:\temp\output_uncompressed.tif") 'works
        vipsimg.Pngsave("c:\temp\output.png") 'works
        vipsimg.Dispose()
        vipsimg = Nothing

```

Strangely, when I do another transformation instead of the line with *****, for example
`vipsimg = vipsimg.Gaussblur(4)`
save with LZW compression works!?

can someone explain this behaviour please ?

Input file is here
https://www.dropbox.com/s/0ml14f2zoyhpdmt/input.tif?dl=0
but it does not matter what file is used as input

PS: I use libvips via the netvips binding

**Comment by jcupitt** [comment]
Hi again, that's because things like `y = x * a + b` will make a float image, and LZW will not work well with float pixels (and the image will be huge).

Add `x.cast("uchar")` before save to make sure you're saving an 8-bit image.

**Comment by jcupitt** [comment]
This isn't a problem with most file formats, since they only support 8 or 16-bit pixels, so they will get cast back automatically. TIFF lets you save float images, so you need to cast yourself.

**Comment by CanadianHusky** [comment]
I learned something new. Thank you! Indeed with the cast, it works fine.
