### ISSUE TITLE
2, 4 Bit TIFF write support

### ISSUE THREAD

**Issue by MathemanFlo** [libvips/libvips#1665]
Hello,
I've got a question concerning the support of writing 2 and 4 bit TIFFs. I looked a bit through the code of tiff2vips and vips2tiff to get some idea whether it is supported or not and I have the impression that it should be supported for reading. In this case the interpretation is set to VIPS_INTERPRETATION_GREY16 for 4 bits per sample. I also found VIPS_INTERPRETATION_GREY16 in the vips2tiff code but I think it is not really supported but only 1bit output is. Is this correct? If yes is it planned to support this format in the near future because it would be somehow mission critical in our case.
Regards
Florian

**Comment by jcupitt** [comment]
Hello @MathemanFlo,

You're right, the TIFF reader supports any depth read, but only 1, 8, 16, 32 and 64-bit write.

Happy to accept a PR if you're able.

**Comment by MathemanFlo** [comment]
Hallo,
I'm rather unfamiliar with the code base of libvips and I'm also a bit unsure how this feature could look like, because it would have to convert uchar8 grayscale to 4 bit per sample. Further more it is maybe desireable to be somewhat consistent with squash. So I will think about a reasonable behavior and take a look into the code. `eightbit2onebit` is probably a good place to start at. To summarize it: I might need some help but I think I'll do it as I need the 4 bit output.

**Comment by jcupitt** [comment]
Yes, we'd probably need to deprecate squash and put something better in. Perhaps an int for depth to write at?
