### ISSUE TITLE
Trying to use background color with alpha channel in gravity is not working using a jpeg file

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1666]
Hi,

I'm trying the following operation from the command line to have an image that has background with some transparency (notice the `--background` parameter) for `gravity` operation:

```sh
vips thumbnail input.png output.v 600 --height 300
vips gravity output.v final.v centre 600 300 --extend background --background "255, 0, 0, 50"
vips pngsave final.v final.png
```

Everything is fine with the previous command list but when I try to do the same using a `jpeg` file instead of a `png` is not possible for me to use a background color with the alpha component:

```sh
vips thumbnail input.jpeg output.v 600 --height 300
vips gravity output.v final.v centre 600 300 --extend background --background "255, 0, 0, 50"
vips pngsave final.v final.png

linear: vector must have 1 or 3 elements
```

I have been investigating vips files with `vipsheader` tool and looks like the temporal vips files are png when you use a png as input and jpeg when you use a jpeg as input.

I'm missing something here? I though that vips file where some internal neutral type of file used by vips but looks like it's replicating the input file format.

I'm using `vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020`.

Thanks in advance.

**Comment by jcupitt** [comment]
Hi @jfcalvo,

You need to add an alpha. JPG files will be RGB, PNG files will often (but not always) be RGBA.

Try:

```
vips bandjoin_const a.v b.v 255
```

To append a constant 255 (opaque) band.

I expect you know, but you don't need a separate `pngsave`. You can write:

```
vips gravity output.v final.png centre 600 300 --extend background --background "255, 0, 0, 50"
```

**Comment by jfcalvo** [comment]
Thanks @jcupitt 

This is working perfectly for me.
