### ISSUE TITLE
pngsave operation with background param not working as expected

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1667]
Using the `pngsave` operation I can't set the background of the output to red color.

I'm using the following command with version `vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020`:

```sh
vips pngsave input.png output.png --background "255, 0, 0"
```

I'm using the following image as `input.png`:

![input](https://user-images.githubusercontent.com/446497/83352259-928f6580-a34a-11ea-9ecd-35b274c9ca55.png)

This input image has some transparency areas in the top and bottom. I'm expecting these areas to be red for `output.png` after execute the `pngsave` command defined before.

Maybe I'm missing something or the background params doesn't work in that way?.

Thanks in advance.

**Comment by jcupitt** [comment]
Hi @jfcalvo,

The `background` param to savers is used if the image needs to be flattened (ie. have the alpha squashed out) before save because the save format does not support alpha.

Try:

```
vips copy palace.png "x.jpg[background=255 0 0]"
```

JPG does not support alpha, so when flattening out the alpha to get the image ready, it'll use the bg property.

If you want to turn your RGBA PNG into a plain RGB PNG you'll need to flatten it yourself, eg.:

```
vips flatten palace.png x.png --background "255 0 0"
```

**Comment by jfcalvo** [comment]
Thank you very much for your help @jcupitt 

It's possible to set the background with alpha? Something like this:

```sh
vips flatten palace.png x.png --background "255 0 0 20"
```

I know that the previous command doesn't works because is flattening the image and we are discarding the alpha channel. Do I have another way to do that?

**Comment by jcupitt** [comment]
Could you explain what effect you need? Are you trying to make a 20% transparent red?

**Comment by jfcalvo** [comment]
What I would like to do is replace every transparent pixel of the png input with certain color, yes for example a 20% transparent red. My first though was that background parameter was doing that.

**Comment by jcupitt** [comment]
I'm not sure you can do that as a one-liner. Do you have something like Python or Ruby available?

**Comment by jfcalvo** [comment]
I can try with Python I guess. How can I do it with Python?

**Comment by jcupitt** [comment]
There are quite a few ways, but a simple one would be:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
background = image.new_from_image([255, 0, 0, 20])
image = background.composite(image, "over")
image.write_to_file(sys.argv[2])
```

That's loading the first arg, then using it to make a new constant image (transparent red), then overlaying the image on top of the tinted background and writing to the second arg.

Run like this:

```
$ ./calvo.py ~/pics/palace.png x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/83463463-f3f82700-a465-11ea-81f9-057a76cc0671.png)

**Comment by jcupitt** [comment]
It would be simpler to start with just the image and then add the new borders, of course.

**Comment by jfcalvo** [comment]
Thank you very much @jcupitt. This is exactly what I was trying to do.
