### ISSUE TITLE
Openslide enabled Ubuntu build container

### ISSUE THREAD

**Issue by twilson7755** [libvips/libvips#1668]
I am trying to build a 'sharp' based nodejs application running in a ubuntu container that supports the various openslide formats.  As such I need to generate an openslide enabled libvips release on ubuntu 20.04.  I don't currently see a build container to support this and was hoping you could provide one or some guidance on how to achieve this using one of your other build containers as a starting point.  Could you also clarify where in the container the generated build can be found.

Thanks,

Terry

**Comment by jcupitt** [comment]
Hi Terry,

Ubuntu 20.04 includes current libvips built with openslide support. Enter:

```
apt install libvips-dev
npm install sharp
```

And it should just work.

**Comment by twilson7755** [comment]
Worked just as you described ... thanks!
