### ISSUE TITLE
dzsave: how to correct color or saturation

### ISSUE THREAD

**Issue by hhentschel** [libvips/libvips#1670]
I noticed a different saturation (or color) output, after using
_vips dzsave image.jpg foldername_ 

The result has a lower saturation, not much, maybe 10% lower. One can see it on some colors.

Why is this happening and is there a way to change the saturation/ color output?

I did´nt find anything [here ](https://github.com/libvips/libvips/issues/1662)and [here](https://github.com/libvips/libvips/issues/59).

**Comment by jcupitt** [comment]
Hello @hhentschel,

Sorry, you'd need to give some sample images and show the problem.

At a guess, perhaps your input image has a colour profile? dzsave will strip profiles from tiles as it writes, since most people will not want a copy of the same (potentially quite large) profile in every output tile.

**Comment by hhentschel** [comment]
Hi jcupitt, 

it is the same image we discussed in this [question](https://github.com/libvips/libvips/issues/1611).

If you don´t have it anymore, i could send it again to you.
The image does have a color profile.
Is there a way to disable the removal of the color profile? Or will the image grow very big then?

**Comment by jcupitt** [comment]
I would convert the image to srgb before making the deepzoom pyramid. This will make your pyramid smaller and it should look the same to your users.

Try:

```
vips colourspace 234144.jpeg x.dz srgb
```

To make `x.dzi` and `x_files`.

**Comment by hhentschel** [comment]
Thanks, unfortunatly it is not working.
i get the same result. 
i also tried converting first only the image 
`vips colorspace 234144.jpeg x.jpg srgb`
and then your line of code, but did`nt work.

**Comment by jcupitt** [comment]
It looks like your profile only works with perceptual intent. Try:

```
vips icc_transform 234144.jpeg x.dz srgb --intent perceptual --embedded
```

**Comment by hhentschel** [comment]
still no luck.
i also tried relative instead of perceptual, but no difference.

it looks like icc_transform makes it more redish, which is missing
when i try the colorspace.
And there is a difference in the redish tone, when viewing the whole image (
a lot of red) and as soon as i zoom in, there is less red.

**Comment by jcupitt** [comment]
Could you have made a mistake? It's working for me.

I ran:

```
vips icc_transform 234144.jpeg x.dz srgb --intent perceptual --embedded
vipsthumbnail 234144.jpeg 
```

Here's `x_files/9/0_0.jpeg`. It has no profile and has been converted to sRGB:

![0_0](https://user-images.githubusercontent.com/580843/83762754-c8488d00-a66f-11ea-84d2-f8f9045b114c.jpeg)

Here's the output of `vipsthumbnail`. It still has a profile and is in Adobe98 (I think):

![tn_234144](https://user-images.githubusercontent.com/580843/83762900-f8902b80-a66f-11ea-8271-4d17c5526088.jpg)

They look the same to me.

**Comment by hhentschel** [comment]
Thats true, i get the same result. But a soon as you zoom in, the color changes.
Your first image is like this one, no zooming in:
![image](https://user-images.githubusercontent.com/2101975/83813192-31a2bd00-a6bd-11ea-8388-0fddc4a48891.png)

But as soon as i zoom in the red tone disappears and it gets more green:
![image](https://user-images.githubusercontent.com/2101975/83813306-5eef6b00-a6bd-11ea-9b85-3970d419e039.png)

**Comment by jcupitt** [comment]
Perhaps you have some tiles left over from an earlier run? Maybe your web browser has cached the old tiles? I would try saving to a new directory under a new name.

**Comment by hhentschel** [comment]
Good Point. I will/can test that on monday.

Is there also a way to sharpen the image with vips?

**Comment by jcupitt** [comment]
Yes, many ways. Have a look at `vips sharpen`.

**Comment by jcupitt** [comment]
I think we're done, I'll close.

**Comment by hhentschel** [comment]
Hi, 
sorry for that delay: 
Just to recap and for future questions:
First issue: it's working now, probably the browser cache, but i also saved them in a new directory.

Second Question: vips sharpen works great. I had some issues finding the right coding formular, but with this, it works just fine for me:
vips sharpen x.jpeg newname.jpeg --m2 25

thanks!
