### ISSUE TITLE
composite: images do not have same numbers of bands

### ISSUE THREAD

**Issue by levmorozov** [libvips/libvips#1676]
Sorry if its stupid question. I have some old code like this:
```php
$shadow = Image::newFromArray($zeros)->bandjoin([$zeros, $zeros, $alpha]);
$frame->composite($shadow, BlendMode::OVER);
```
And it's worked before (two years ago maybe), but not working with fresh releases of libvips. Got error "'composite: images do not have same numbers of bands". But both images has 4 bands.

After reading docs, i tried:
```php
$frame->composite($shadow, BlendMode::OVER, ['compositing_space' => Interpretation::SRGB]);
```
but it have not changed anything. Only working solution is:

```php
$shadow = $shadow->copy(['interpretation' => 'srgb']);
```
Please, can you give a hint - why `compositing_space` is not working?

**Comment by jcupitt** [comment]
Hello @levmorozov, sorry your code broke. 

Yes, you need to set the interpretation now. `newFromArray` makes a mono image, then running bandjoin on that just adds bands and does not change the interpretation. You will have a mono image with three alpha channels.

As you said, you can do:

```php
$shadow = Image::newFromArray($zeros)->bandjoin([$zeros, $zeros, $alpha])->copy(['interpretation' => 'srgb']);
```

You could also just do:

```php
$shadow = Image::newFromArray($zeros)->bandjoin($alpha);
```

That'll make a mono + alpha, which will be automatically converted to RGB + alpha by composite.

**Comment by levmorozov** [comment]
Thanks for answer!

About your second example. I tried:
```php
$alpha = ...generate 2d array...
$shadow = Image::newFromArray($zeros)->bandjoin([$alpha]);
$shadow->pngsave(...) 
```
and then:
```php
$frame = Image::newFromFile('some.png'); // 4 bands
$shadow = Image::newFromFile('shadow.png'); // 2 bands
$frame->composite($shadow, BlendMode::OVER, ['compositing_space' => Interpretation::SRGB]);
```
Its works just fine! So, i dont understand why not working that:

```php
$frame = Image::newFromFile('some.png');
$alpha = ...generate 2d array...
$shadow = Image::newFromArray($zeros)->bandjoin([$alpha]);
$frame->composite($shadow, BlendMode::OVER, ['compositing_space' => Interpretation::SRGB]);
```
it's throws error "images do not have same numbers of bands"

I look for differences and found only one: `format`: `uchar` for files and `double` for newFromArray_bandjoin image. But dont know how to change that...

**Comment by jcupitt** [comment]
Ooop, sorry, I should have tested it.

`newFromArray` makes a image tagged as `array`, meaning a generic N band image. These don't really have alphas, since they don't have a fixed number of bands. You need to specifically tag it as a monochrome image (`b-w`).

Try:

```php
$shadow = Image::newFromArray($zeros)->bandjoin([$alpha])->copy(['interpretation' => 'b-w']);
```

What's `zeros`? I wouldn't make a huge array, that'll be very slow. I would make a drop shadow with something like this:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$image = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);

# make a shadow by taking the image alpha and blurring it ... if there's no
# alpha, use a white block (ie. not transparent) the size of the image
if ($image->hasAlpha())
  $alpha = $image->extract_band(3);
else
  $alpha = Vips\Image::black($image->width, $image->height)->add(255);
$shadow_size = 30;
$alpha = $alpha->gravity('centre', 
  $image->width + $shadow_size * 2, $image->height + $shadow_size * 2);
$alpha = $alpha->gaussblur($shadow_size / 2);
$background = Vips\Image::black($alpha->width, $alpha->height)
  ->bandjoin($alpha)
  ->copy(['interpretation' => 'b-w']);
  
# composite the image over the shadow with an offset
$image = $background->composite($image, 'over', [
  'x' => -$shadow_size, 
  'y' => -$shadow_size
]);

$image->writeToFile($argv[2]);
```

Then:

```
$ ./try308.php ~/pics/PNG_transparency_demonstration_1.png x.png
```

Turns:

![PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/580843/84229379-5645cd00-aae1-11ea-8945-ce224044f806.png)

Into:

![x](https://user-images.githubusercontent.com/580843/84229439-75dcf580-aae1-11ea-89c5-9fc97d525933.png)

You can make drop shadows with CSS too, of course.

**Comment by levmorozov** [comment]
>  image tagged as array, meaning a generic N band image

Ah..  Now I understand! Thanks!
 
I'm missed that difference multiband/b-w in generated/saved image somehow, and its lead me in totally wrong direction.

> What's zeros? I wouldn't make a huge array, that'll be very slow.

Yep. Zeros is just [[0,0,0,..],[0,0,0,..],...] array.  Not very efficient.`Image::black` is much better solution, thank you.

I our case we generate dynamically baguette frame with some image inside it. And generate 2 inner shadows (8 narrow linear shadows actually). Something like this:

![photo_2020-06-10 09 12 37](https://user-images.githubusercontent.com/979251/84233245-a0877800-aafa-11ea-94cc-f9998e6cb747.jpeg)

blur looks like more appropriate way to do that, so, thanks again for example.

**Comment by jcupitt** [comment]
Huh that looks nice. I think we're done, I'll close.
