### ISSUE TITLE
how to know about missing libraries

### ISSUE THREAD

**Issue by abubelinha** [libvips/libvips#1677]
Hi. Sorry if this is already explained somewhere but I don't know much about compilation, so I didn't know exactly how to search the issues.

This is my problem.
I have been using vips for the last 10 years in a quite simple way. Just for conversion of tiff files in WindowsXP command line. I believe I had downloaded and installed a precompiled binary (vips 7.18.2), so I guess the different libraries needed were already included there.

My scripts used the old style `im_vips2tiff` command, which now is named `tiffsave` [as described here](https://github.com/libvips/libvips/issues/454). 

```
vips im_vips2tiff input-image.tif output-image.deflate.tif:deflate,tile:256x256,pyramid
vips im_vips2tiff input-image.tif output-image.jpeg-50.tif:jpeg:50,tile:256x256,pyramid

```
Now I have to get rid of that old computer, and I want to take the ocassion to migrate my stuff to the university computing cloud. This will be a Linux system and I am just an user. 
So the main problem I have is that I am not sure if the different error messages I find are my fault (because I still don't know the correct syntax), or they might be due to missing libraries (so I should tell the IT staff to recompile vips and include them).

So, my questions:

(1) Is there **any vips command which shows information about the current installation**, summarizing all the different options which are available and those which are not (due to missing optional libraries)?  (i.e. something like "tiff support: true, jpeg compression support: false, ..." and so on)

(2) Some **examples of errors I got**. Is it my fault, or is it some **missing library?**

```
$ vips tiffsave "test.tif" "test.tif.to.deflate.tif" --compression deflate
test.tif.to.pyr.tif: AdobeDeflate compression support is not configured
wbuffer_write: write failed

$ vips im_vips2tiff "test.tif" "test.tif.to.deflate.pyr.tif":deflate,tile:256x256,pyramid
test.tif.to.deflate.pyr.tif: AdobeDeflate compression support is not configured
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
unix error: Unknown error -1

$ vips tiffsave "test.tif" "test.tif.to.jpeg.pyr.tif" --compression jpeg --Q 90 --tile --tile-width 256 --tile-height 256 --pyramid
TIFFSetField: test.tif.to.jpeg.pyr.tif: Unknown pseudo-tag 65537
TIFFSetField: /scratch/4111408/vips-4-2142353891.tif: Unknown pseudo-tag 65537
TIFFSetField: /scratch/4111408/vips-3-1404711265.tif: Unknown pseudo-tag 65537
TIFFSetField: /scratch/4111408/vips-2-2788658965.tif: Unknown pseudo-tag 65537
TIFFSetField: /scratch/4111408/vips-1-1201493709.tif: Unknown pseudo-tag 65537
TIFFSetField: /scratch/4111408/vips-0-1227324129.tif: Unknown pseudo-tag 65537
test.tif.to.pyr.tif: JPEG compression support is not configured
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
unix error: Unknown error -1

$ vips tiffsave "test.tif" "test.tif.to.jpeg.pyr.tif" --compression jpeg --Q 50 --tile --tile-width 256 --tile-height 256 --pyramid
Segmentation fault (core dumped)

$ vips -v
vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
```
Also, why the error is different when I changed from _--Q 90_ to _--Q 50_?

Thanks a lot in advance

**Comment by jcupitt** [comment]
Hello @abubelinha,

You can test for features with eg.:

```
vips pdfload
```

You'll get either a help page or an error, depending on whether the PDF loader is configured.

From your messages, it looks like your libtiff has been built without JPEG or libz support.  You'll need to rebuild libtiff.

**Comment by abubelinha** [comment]
OK thanks. 
So, is this the list of all those possible features/commands, so I can test each one?
https://libvips.github.io/libvips/API/current/func-list.html#function-list

For example, which one in that list would tell me about "no jpeg or libz support"?
I ask because `vips tiffsave` does not return me an error.

What I am trying to know is to find all possible missing things right now, so the IT staff can install all of them. It is not easy to get their attention, and they are chances it will took them days to attend my request and give me an answer.
So I wouldn't like to find another possible missing functionality in a couple of weeks. I would probably have to post it here again, and then go back to the IT staff and wait until they recompile things and give me an answer.

Suggested enhancement:

Perhaps you could provide (in future libvips install instructions) an "installation_test" script which we can run, so we can know if something is missing right away. 
Also a good company to that script would be a zip file including sample of all possible needed file formats to feed the script ("test.tif", "test.pdf" and so on ... because there are file formats I don't know by now, but maybe I discover them when I deep a little bit more in vips).

**Comment by abubelinha** [comment]
> You'll need to ask an expert :(

But in my case those experts are our cloud IT staff, so we are back at the beginning:

> I would build libvips yourself (you don't need the IT staff) and experiment with it.

OK, now at least you know I tried ... LOL.

Fortunately in the meantime, the IT guys have been pretty nice and fast: they already added jpeg zlib support to the shared vips they built. 

Just one more related question:
Now libvips is already installed and ready for CLI bash-scripting usage in this shared Linux server ... what other steps are needed if I also want to use it from python?

I found different info pages about it, but I am a bit lost because they show different ways of importing functions. I don't understand if the different importing styles come from different ways of installing it. Which one is preferred?

This: https://github.com/libvips/pyvips
```
import pyvips
image = pyvips.Image.new_from_file('some-image.jpg', access='sequential')

```
Or this: https://github.com/libvips/libvips/wiki/Python
```
#!/usr/bin/python
import sys
from gi.repository import Vips
im = Vips.Image.new_from_file(sys.argv[1])
```

Thanks a lot in advance again

**Comment by jcupitt** [comment]
Oh heh ah well. Anyway, I'm glad it's working.

For python, make sure you have the libvips development files available like this:

```
pkg-config vips --cflags
```

You should see compile flags, ask IT if you don't, then just 

```
pip install pyvips
```

The first import style is correct, the second is for an older version of pyvips that is no longer supported. I'll remove it.

**Comment by jcupitt** [comment]
libvips 8.10 has a new feature: 

```
$ vips --vips-config
native win32: no, native OS X: no, open files in binary mode: no, enable debug: no, enable deprecated library components: yes, ...
```

So you can see what options it was built with.
