### ISSUE TITLE
Cannot disable VIPS_INFO logs via bimg integration

### ISSUE THREAD

**Issue by diegomontoya** [libvips/libvips#1685]
We are using bimg/golang library which is wrapper for libvips but we are getting tongs of `VIPS-INFO: reduceh: 9 point mask
VIPS-INFO: reducev: 9 point mask` logs which we are unable to disable. 

Is there a way to disable this info? Thanks.

We are on Centos and build everything from scratch with default ./configure options with no overrides. Not sure why it is prettying INFO which I consider debug level input.

**Comment by jcupitt** [comment]
Hello @diegomontoya,

The info output is disabled by default, I'm not sure why you're seeing it. Something must be enabling it.

It gets printed if you have an environment variable called `VIPS_INFO`, so you could search for that and see if it's being defined anywhere. It's also printed if you have `VIPS` in your `G_MESSAGES_DEBUG` environment variable. 

You can also enable it using the glib logging framework, so I suppose that's possible too.

**Comment by 05365863216** [comment]
The info output is disabled by default, I'm not sure why you're seeing it. Something must be enabling it.

It gets printed if you have an environment variable called VIPS_INFO, so you could search for that and see if it's being defined anywhere. It's also printed if you have VIPS in your G_MESSAGES_DEBUG environment variable.

You can also enable it using the glib logging framework, so I suppose that's possible too.

**Comment by 05365863216** [comment]
question

**Comment by diegomontoya** [comment]
@jcupitt  We can confirm there is no VIPS_INFO variable via ```declare``` and also no ```G_MESSAGES_DEBUG``` env was set. We even tested with env ```G_MESSAGES_DEBUG``` set to a non-existing program "none" and it still doesn't printed the VIPS INFO reduceh messages. We are going to manually comment out the reduceh info logs for now.

**Comment by jcupitt** [comment]
That's very odd. If you can make a dockerfile that shows the problem I could have a look in a debugger.

**Comment by jcupitt** [comment]
Oh, it could be an old glib. Apparently before 2.31 it could output debugging by default.

You could check your glib version number and perhaps update.

**Comment by kleisauke** [comment]
Is this CentOS 6? If so, https://github.com/libvips/libvips/issues/1876 might be relevant here.

**Comment by diegomontoya** [comment]
@kleisauke  Yes this is Centos6 and exact same bug as #1876. 

I have since moved on to alpine linux with updated glib which does not have this issue.

**Comment by diegomontoya** [comment]
Duplicate of  #1876.

**Comment by spolanyev** [comment]
The problem exists for libvips 8.14.5 built on Amazon Linux 2 with `--buildtype=release`

![output](https://github.com/libvips/libvips/assets/107479417/dbd407ad-b736-477f-99a3-1278b63efaae)

**Comment by lovell** [comment]
@spolanyev This is probably a question for the https://github.com/davidbyttow/govips repo.
