### ISSUE TITLE
composite2 does not support cmyk as compositing space

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1689]
vips version: vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
operating system: Windows 10 64bit

get error on composite two cmyk image using composite2:

```
pyvips.error.Error: unable to call composite2
  composite2: unsupported compositing space
```

simple pyvips code to reproduce

```
import pyvips

cmyk_bg = pyvips.Image.new_from_file("cmyk_bg.tif")
cmyk_text = pyvips.Image.new_from_file("cmyk_text.tif")

print("cmyk_bg: ", cmyk_bg)
print("cmyk_text: ", cmyk_text)

img = cmyk_bg.composite2(cmyk_text, "over", x=0, y=0, compositing_space="cmyk")

print("img: ", img)

img.tiffsave("cmyk_composite2.tif")
```

full output log:
```
cmyk_bg:  <pyvips.Image 1000x1000 uchar, 4 bands, cmyk>
cmyk_text:  <pyvips.Image 1000x1000 uchar, 4 bands, cmyk>
Traceback (most recent call last):
  File "vips_composite2.py", line 9, in <module>
    img = cmyk_bg.composite2(cmyk_text, "over", x=0, y=0, compositing_space="cmyk")
  File "C:\Python37_64\lib\site-packages\pyvips\vimage.py", line 805, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "C:\Python37_64\lib\site-packages\pyvips\voperation.py", line 215, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call composite2
  composite2: unsupported compositing space

```

**Comment by jindili** [comment]
For now, with CMYK image, I use ifthenelse instead
https://libvips.github.io/pyvips/vimage.html#pyvips.Image.ifthenelse

**Comment by jcupitt** [comment]
Hello @jindili,

I've had a go at adding support, but I don't have any test images. Do you have a sample CMYKA image?

**Comment by jindili** [comment]
Hi @jcupitt 

I use these two CMYK (one is CMYKA)  image:

[cmyk.zip](https://github.com/libvips/libvips/files/4839470/cmyk.zip)

**Comment by jcupitt** [comment]
`cmyk_bg.tif` is actually a photoshop file, but perhaps that doesn't matter.

I don't think `cmyk_text.tif` has an alpha -- it's just a plan CMYK TIFF.

I tried making a text image like this:

```
john@kiwi:~/pics$ vips text x.v hello --dpi 300
john@kiwi:~/pics$ vips colourspace x.v cmyk.v cmyk
john@kiwi:~/pics$ vips bandjoin "cmyk.v x.v" cmyka.tif
```

Then tried:

```
john@kiwi:~/pics$ vips composite2 cmyk_bg.tif cmyka.tif x.tif over --compositing-space cmyk
```

And it seems to have worked (I think). Anyway, try git master if you can.

**Comment by jindili** [comment]
Hi @jcupitt 

I found an instruction to build vips on Windows:
https://github.com/libvips/libvips/wiki/Build-for-Windows

But seems the page is bit of old which is published on 8 Apr 2017, 
Is that still work, I'll give it a try.

**Comment by jcupitt** [comment]
It still works, but it runs on linux, not windows. Building on windows is much harder, unfortunately.

**Comment by jcupitt** [comment]
beta2 of 8.10 is up now, and includes win binaries.

https://github.com/libvips/libvips/releases/tag/v8.10.0-beta2

Hopefully this fix is included. I'll close.

**Comment by jindili** [comment]
rc1 for windows works, get result as expected.
