### ISSUE TITLE
vispthumbnail --xres and --yres

### ISSUE THREAD

**Issue by adamu** [libvips/libvips#1691]
Hello, thanks for the great library.

Would you consider adding the `--xres` and `--yres` options from `tiffsave` to the `vipsthumbnail` command?

My situation:

I have some pathology (SVS and NDPI) images. The output of `vipsheader -f xres` for these images is `1`, however the resolution can be extracted via openslide from the `aperio.MPP` (for SVS) and `tiff.XResolution` / `tiff.ResolutionUnit` (for NDPI) headers.

I would like to be able to calculate the resolution and provide it to `vipsthumbnail`, otherwise I get a thumbnail with a resolution value of 10 pixels/cm.

**Comment by jcupitt** [comment]
Hi @adamu,

You can do this already -- try:

```
vipsthumbnail something.svs --size 500x500 --output other.tif[xres=3.1415,yres=3.1415]
```

You can get the resolution from the original files with:

```
vipsheader -f openslide.mpp-x something.svs
vipsheader -f openslide.mpp-y something.svs
```

Then calculate pixels per mm from that.

The openslide loader should probably do this by default, I'll have a look.

**Comment by jcupitt** [comment]
I added xres/yres read to libvips master, this change will be in 8.10. 

I now see:

```
$ vipsheader -f xres OS-2.ndpi 
4403.4000000000005
```

Thanks for suggesting this useful improvement!

In the meantime, you can workaround as above.

**Comment by adamu** [comment]
Thanks for the fast response! And I hadn't noticed `openslide.mpp-x` and `mpp-y` - very useful, thanks.

Sorry if I confused things by talking about `tiffsave`. I'm actually trying to save a jpeg (the default behaviour). If I try to use the options for a jpeg, I get:

> jpegsave_target: no property named `xres'

**Comment by jcupitt** [comment]
Ah OK. Yes, with jpeg you need to set xres/yres yourself. 

You can go via a `.v` intermediate image:

```
vipsthumbnail --size 500x500 --output x.v
vipsedit x.v --xres=3.1415 --yres=3.1415
vips copy x.v x.jpg
rm x.v
```

Or use something like Python and avoid the intermediate file.

```python
thumb = pyvips.Image.new_from_file("something.svs")
xres = 1000.0 / float(thumb.get("openslide.mpp-x"))
yres = 1000.0 / float(thumb.get("openslide.mpp-y"))
thumb.copy(xres=xres, yres=yres).write_to_file("other.jpg")
```

**Comment by jcupitt** [comment]
... or wait for 8.10, of course.

**Comment by adamu** [comment]
Great, thanks again!
