### ISSUE TITLE
vips thumbnail transparent issue

### ISSUE THREAD

**Issue by dineshkannaa** [libvips/libvips#1692]
Hi,
  While generating jpeg thumbnail for a transparent png image , the generated thumbnail turns negative. The command looks like this 
 `vips thumbnail transparent.png  t1.jpg 1024`
Im unable to share the image ere as it is confidential . Is there any ways to fix this ?

vips version: vips-8.9.0

**Comment by jcupitt** [comment]
libvips flattens transparency against black, by default. To flatten against white instead, try:

```
vips thumbnail transparent.png t1.jpg[background=255] 1024
```

**Comment by dineshkannaa** [comment]
@jcupitt  Oh ok . Could you please tell how to do that in this API
```
vips_thumbnail_buffer(imageIn, imageInSize, &imageOut, width, "height", height, "auto_rotate",
        TRUE, NULL)
```
Also shall I confirm that "[background=255]" affects only the transparence sector of the image and no other sector is affected

**Comment by jcupitt** [comment]
Yes, it's just used for the removal of alpha.

You can call flatten yourself, or give it as an option to save.

**Comment by dineshkannaa** [comment]
> You can call flatten yourself, or give it as an option to save.

vips_image_write_to_buffer(vipsImageOut, ".jpg", &outBuffer, &outBufferSize,
            NULL);
do you mean in this method ? If so , Please share a sample to do the flatten
