### ISSUE TITLE
Is 1 bit PNG output possible ?

### ISSUE THREAD

**Issue by CanadianHusky** [libvips/libvips#1693]
Hello,
I have read 
https://github.com/libvips/libvips/issues/1388 and http://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-pngsave

I am still not clear if 1 bit PNG output is possible now or not ?
Any comment welcome, thank you

**Comment by jcupitt** [comment]
Sorry, no, it's on the to-do list, but not yet done.

**Comment by CanadianHusky** [comment]
Understood, thank you

**Comment by jcupitt** [comment]
This is in now, it'll be supported in 8.10.

```
vips copy k2.jpg x.png[bitdepth=1]
```

**Comment by kmartinez** [comment]
wow we've come full circle. the SUN workstations we started with only had one bit pixels ;-)

**Comment by CanadianHusky** [comment]
In professional digital printing 1 bit monochrome images still have great
value. Both for pure BW printing and for color separated cmyk offset
printing

Thanks for incorporating this
