### ISSUE TITLE
Getting segmentation violation when trying to Auto rotate a JPEG.

### ISSUE THREAD

**Issue by rapidcoder7** [libvips/libvips#1696]
Hi Folks,

I am getting Segmentation violation when trying to auto rotate an image. 

![small-tn copy](https://user-images.githubusercontent.com/8473463/86086494-bbdd0780-ba56-11ea-8dd0-afcbff8149ed.jpeg)

The above has an orientation of 2 in exif. I set it using the below command:
`exiftool -Orientation=2 -n <image_path>`

Below is the stack trace:

> (govips:2487): GLib-GObject-CRITICAL **: 22:12:52.397: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x4a1ddfb]

runtime stack:
runtime.throw(0x44d3aea, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 8 [syscall]:
runtime.cgocall(0x43d5920, 0xc000068be0, 0xc0000100f0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000068bb0 sp=0xc000068b78 pc=0x400558b
github.com/davidbyttow/govips/pkg/vips._Cfunc_vips_cache_operation_buildp(0xc0000100f0, 0xc000000000)
	_cgo_gotypes.go:1269 +0x49 fp=0xc000068be0 sp=0xc000068bb0 pc=0x4184519
github.com/davidbyttow/govips/pkg/vips.vipsCallOperation.func2(0xc0000100f0, 0x860ccf0)
	/Users/rdhamecha/go/pkg/mod/github.com/davidbyttow/govips@v0.0.0-20200412130214-cbefdd8c639a/pkg/vips/bridge.go:66 +0x9d fp=0xc000068c18 sp=0xc000068be0 pc=0x419f44d
github.com/davidbyttow/govips/pkg/vips.vipsCallOperation(0xb04ba40, 0xc00006b300, 0x2, 0x2, 0x0, 0x0)
	/Users/rdhamecha/go/pkg/mod/github.com/davidbyttow/govips@v0.0.0-20200412130214-cbefdd8c639a/pkg/vips/bridge.go:66 +0x17b fp=0xc000068ca8 sp=0xc000068c18 pc=0x418511b
github.com/davidbyttow/govips/pkg/vips.vipsCall(0x44c40f6, 0x7, 0xc00006b300, 0x2, 0x2, 0xc00006b300, 0x0)
	/Users/rdhamecha/go/pkg/mod/github.com/davidbyttow/govips@v0.0.0-20200412130214-cbefdd8c639a/pkg/vips/bridge.go:49 +0x61 fp=0xc000068ce8 sp=0xc000068ca8 pc=0x4184f71
github.com/davidbyttow/govips/pkg/vips.Autorot(0x880d010, 0x0, 0x0, 0x0, 0x1, 0x880d010, 0xc000021740)
	/Users/rdhamecha/go/pkg/mod/github.com/davidbyttow/govips@v0.0.0-20200412130214-cbefdd8c639a/pkg/vips/operators.go:112 +0x10f fp=0xc000068d60 sp=0xc000068ce8 pc=0x418912f
github.com/davidbyttow/govips/pkg/vips.(*ImageRef).Autorot(0xc000021740, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rdhamecha/go/pkg/mod/github.com/davidbyttow/govips@v0.0.0-20200412130214-cbefdd8c639a/pkg/vips/operators.go:118 +0x50 fp=0xc000068da8 sp=0xc000068d60 pc=0x41892a0
imageutil.transformImage(0xc000150000, 0x5b49, 0x5d49, 0x1, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	vipsimageutil.go:115 +0x373 fp=0xc000068e80 sp=0xc000068da8 pc=0x43d2c63
imageutil.TestTransformImage.func1(0xc000142200)
	vipsimageutil_test.go:106 +0x145 fp=0xc000068f70 sp=0xc000068e80 pc=0x43d4615
testing.tRunner(0xc000142200, 0x44dfce0)
	/usr/local/go/src/testing/testing.go:909 +0xc9 fp=0xc000068fd0 sp=0xc000068f70 pc=0x40fc2a9
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000068fd8 sp=0xc000068fd0 pc=0x4060681
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000142100, 0x44c8174, 0x12, 0x44dfcf8, 0x40b9501)
	/usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc000142000)
	/usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000142000, 0xc0000f1d40)
	/usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc00000e6e0, 0x4829e40, 0x5, 0x5, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0000f8080, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x176
imageutil.TestMain(0xc0000f8080)
	vipsimageutil_test.go:25 +0x85
main.main()
	_testmain.go:50 +0x135

goroutine 7 [chan receive]:
testing.(*T).Run(0xc000142200, 0x44cae42, 0x17, 0x44dfce0, 0x1d1afde9e52d0)
	/usr/local/go/src/testing/testing.go:961 +0x377
imageutil.TestTransformImage(0xc000142100)
	vipsimageutil_test.go:102 +0x50
testing.tRunner(0xc000142100, 0x44dfcf8)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2

**Comment by lovell** [comment]
Hi, did you intend to ask this question at the https://github.com/davidbyttow/govips repo rather than libvips?

This image appears to work and be correctly oriented using `vips autorot ...` at the command line (I also tested using sharp), so it would probably be best to investigate and remove `govips` as a possible source of any problems first.

**Comment by rapidcoder7** [comment]
Thank you. I’ll ask there.
