### ISSUE TITLE
Build fails on Amazon Linux when including librsvg

### ISSUE THREAD

**Issue by AdamT213** [libvips/libvips#1700]
I adapted @jcupitt's [dockerfile](https://github.com/jcupitt/docker-builds/blob/master/libvips-amazonlinux2/Dockerfilel) to build a version with svg support, but it fails on make install with this output: 

`libtool: link: gcc -g -O2 -o .libs/introspect introspect.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/local/vips/include -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/librsvg-2.0 -I/usr/include/libpng12 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/ImageMagick-6 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -pthread -Wl,--export-dynamic -pthread  -L/usr/lib64:/usr/lib:/usr/local/vips/lib -lgirepository-1.0 ./.libs/libvips.so -lz -lMagickCore-6.Q16 -lpng12 -ltiff -ljpeg -lgthread-2.0 -lgmodule-2.0 /usr/lib64/libexpat.so /usr/lib/libpangoft2-1.0.so /usr/lib/libpango-1.0.so -lfreetype /usr/lib/libfontconfig.so -llcms2 /usr/lib/librsvg-2.so -lgio-2.0 /usr/lib/libgdk_pixbuf-2.0.so -lgobject-2.0 -lglib-2.0 /usr/lib/libcairo.so -L/usr/local/vips/lib /usr/local/vips/lib/libwebpmux.so /usr/local/vips/lib/libwebpdemux.so /usr/local/vips/lib/libwebp.so -lm -fopenmp -pthread -Wl,-rpath -Wl,/usr/local/vips/lib -Wl,-rpath -Wl,/usr/lib64
  **gcc: error: libgomp.spec: No such file or directory`**

Before including librsvg (and the nonstandard package versions it depends on), this built fine. I dont know what `libgomp.spec` is, but I can confirm that it is present at:
`/usr/lib/gcc/x86_64-amazon-linux/6.4.1/libgomp.spec`
`/usr/lib/gcc/x86_64-amazon-linux/4.8.5/libgomp.spec`

 The script is included below. Many thanks in advance!

    `export VIPSHOME=/usr/local/vips`
     `export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:$VIPSHOME/lib/pkgconfig`
     `export LDFLAGS=-L/usr/lib64:/usr/lib:$VIPSHOME/lib`
     `export LD_LIBRARY_PATH=/usr/lib64:/usr/lib:$VIPSHOME/lib`
      `export PATH=/usr/bin:$PATH`
      `export CPPFLAGS=-I/usr/include`

      `yum update -y`
      `yum groupinstall -y "Development Tools"`
      `yum install -y wget tar`
      `yum install -y gcc64 libjpeg-devel.x86_64 libpng-devel.x86_64 libtiff-devel.x86_64 libgif-devel.x86_64 gobject- introspection.x86_64 gobject-introspection-devel.x86_64`
      `yum install -y libpng-devel.x86_64 glib2-devel.x86_64 libjpeg-devel.x86_64 expat-devel.x86_64
      zlib-devel.x86_64 orc-devel.x86_64 lcms2-devel.x86_64 libexif-devel.x86_64 libgsf-devel.x86_64`

      `yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
      `yum install -y openslide-devel.x86_64`

      `wget http://ftp.gnome.org/pub/GNOME/sources/libcroco/0.6/libcroco-0.6.8.tar.xz`
      `tar xvfJ libcroco-0.6.8.tar.xz`
      `cd libcroco-0.6.8`
      `./configure --prefix=/usr`
      `make`
      `sudo make install`
      `cd ..`

      `sudo yum install -y pixman-devel.x86_64 harfbuzz-devel.x86_64 freetype-devel.x86_64`
      `wget http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.10.91.tar.gz`
      `tar xvf fontconfig-2.10.91.tar.gz`
      `cd fontconfig-2.10.91`
      `./configure --prefix=/usr`
      `make`
      `sudo make install`
      `cd ..`

      `wget http://cairographics.org/releases/cairo-1.12.14.tar.xz`
      `tar xvfJ cairo-1.12.14.tar.xz`
      `cd cairo-1.12.14`
      `./configure --prefix=/usr`
      `make`
      `sudo make install`
      `cd ..`

      `wget http://ftp.gnome.org/pub/GNOME/sources/pango/1.34/pango-1.34.1.tar.xz`
      `tar xvfJ pango-1.34.1.tar.xz`
      `cd pango-1.34.1`
      `./configure --prefix=/usr`
      `make`
      `sudo make install`
      `cd ..`

      `wget http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.28/gdk-pixbuf-2.28.2.tar.xz`
      `tar xvfJ gdk-pixbuf-2.28.2.tar.xz`
      `cd gdk-pixbuf-2.28.2`
      `./configure --prefix=/usr`
      `make V=0`
      `sudo make install`
      `cd ..`

      `wget http://ftp.gnome.org/pub/gnome/sources/librsvg/2.40/librsvg-2.40.3.tar.xz`
      `tar xvfJ librsvg-2.40.3.tar.xz`
     ` cd librsvg-2.40.3`
      `./configure --prefix=/usr`
      `make V=0`
      `sudo make install`
      `cd /usr/local/src`

      `wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.2.tar.gz`
      `tar xzf libwebp-1.0.2.tar.gz`
      `cd libwebp-1.0.2`
      `./configure --enable-libwebpmux --enable-libwebpdemux --prefix=$VIPSHOME`
      `make V=0`
      `make install`

      `cd /usr/local/src`
      `wget https://github.com/libvips/libvips/releases/download/v8.9.1/vips-8.9.1.tar.gz`
      `tar xzf vips-8.9.1.tar.gz`
      `cd vips-8.9.1`
      `./configure --prefix=$VIPSHOME`
      `make V=0`
       `#FAILS HERE, ALL OTHER PACKAGES ARE INSTALLED`
      `sudo make install`
      `make clean`
      `ls $VIPSHOME/lib`
      `ldconfig`
      `pkg-config --list-all`

**Comment by lovell** [comment]
Hi, a search for `libgomp.spec: No such file or directory` suggests the following might help:

https://stackoverflow.com/questions/48998558/gcc-error-libgomp-spec-no-such-file-or-directory-with-amazon-linux-2017-09-1
