### ISSUE TITLE
Seems textPath is not support in pyvips.Image.svgload_buffer

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1707]
Seems textPath is not support in pyvips.Image.svgload_buffer
version: vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
os: Windows 10 64bit
```
import pyvips

svg = """
    <svg version="1.1"
        baseProfile="full"
        width="500" height="500"
        viewBox="0 0 500 500"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink">
      <path id="curve" d="M73.2,148.6c4-6.1,65.5-96.8,178.6-95.6c111.3,1.2,170.8,90.3,175.1,97" />
      <text width="500">
        <textPath xlink:href="#curve">
          this is some text go around the curve
        </textPath>
      </text>
    </svg>
    """
img = pyvips.Image.svgload_buffer(svg.encode(encoding="utf-8")).extract_band(3, n=1)
img.tiffsave("text_around_curve.tif")
```

same svg open in chrome browser:
![image](https://user-images.githubusercontent.com/73845/86710427-8aaf9900-c04d-11ea-8e6f-94ff9213f352.png)

**Comment by jindili** [comment]
Maybe it's librsvg related:

![image](https://user-images.githubusercontent.com/73845/86729727-5beeee00-c060-11ea-9ef8-9bb8c2b72ed6.png)

I read from the link here:
[https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#_other_svg_implementations](https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#_other_svg_implementations)

**Comment by jcupitt** [comment]
That's right, libvips hands SVG rendering off to librsvg. We should maybe switch to resvg.

**Comment by jindili** [comment]
Just test latest resvg，seem textPath convertion has some issue， not that same as in Chrome Browser

![image](https://user-images.githubusercontent.com/73845/86783739-4b0ba000-c093-11ea-8a07-221e110d9e70.png)

The first several letters crowed together.

**Comment by jindili** [comment]
I end up using Inkscape to do the svg to image convertion
```
inkscape.exe text_along_curve.svg -o text_along_curve_test.png
```

![text_along_curve_test](https://user-images.githubusercontent.com/73845/87105551-e4060b00-c28d-11ea-934e-b73275a2e809.png)

the result image is correct as expected.
