### ISSUE TITLE
Is is possible to achieve Text on Curve Effect with pyvips?

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1710]
Something like this:

![image](https://user-images.githubusercontent.com/73845/87042048-b2595980-c225-11ea-970c-7b3108c1bb4c.png)

Having the shape in raster format (tif format) or vector( svg format)
![image](https://user-images.githubusercontent.com/73845/87042140-d2891880-c225-11ea-99f5-67fb0f9609b6.png)

I tried using textPath in SVG then convert to image using pyvips.Image.svgload_buffer, sadly textPath is not supported by librsvg.

I want to make a text image strip, and then wrap it around the target curve shape, but don't have a clue.
![image](https://user-images.githubusercontent.com/73845/87042534-60fd9a00-c226-11ea-9c4c-3d539ba759a6.png)

**Comment by jcupitt** [comment]
Sorry, this is probably not possible with pyvips. You could try inkscape -- it has a command-line mode that can render SVG to PNG.

**Comment by jindili** [comment]
Thanks @jcupitt , inkscape is good to do this task.  I'll use it for now to handle svg features that librsvg is not yet supported.

But, I still wonder if I try build an index image using vips_xyz(), then mapim it,
Maybe it's bit of complex to build the index image, but it's one time work.

![image](https://user-images.githubusercontent.com/73845/87106378-e701fb00-c28f-11ea-8722-aa91a3991f93.png)


Kind like mapping the texture to an rope, the deform the rope accrod to given curve.
