### ISSUE TITLE
Invert not working as expected

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1711]
Hi,

I have a problem with the following image applying `invert` operator over it.

![image_example](https://user-images.githubusercontent.com/446497/87043897-119f7580-c1f6-11ea-9e12-c40b19d177d3.png)

After executing the following command (using `vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020` on MacOS 10.14.6):

```sh
$ vips invert image_example.png output.png
```

What I get is a total transparent image with the dimensions of `image_example.png`.

![output](https://user-images.githubusercontent.com/446497/87044065-50cdc680-c1f6-11ea-8f26-b050032ebb10.png)

I'm doing something wrong?

**Comment by jcupitt** [comment]
Hello @jfcalvo,

Your image has a solid alpha channel (255). When you invert it, you get a fully transparent alpha (0). Remove the alpha before inverting.

**Comment by jfcalvo** [comment]
@jcupitt using the following image as source:

![example](https://user-images.githubusercontent.com/446497/87128310-b02be500-c28f-11ea-9763-1d1da95beede.png)

What I get if I apply invert overt it is the following:

![example_invert](https://user-images.githubusercontent.com/446497/87128417-e10c1a00-c28f-11ea-9b56-60257d4704b7.png)

But what I would like it to get is something more like the following (not inverting alpha pixels that are fully transparent):

![example_expected_invert](https://user-images.githubusercontent.com/446497/87128540-14e73f80-c290-11ea-8473-4776467c3c70.png)

Do you think that something like that is possible with other operators?

Could be a good idea to add an optional parameter to invert so it ignore the totally transparent pixels on alpha channel so we get something like the last image?

Thanks.

**Comment by jcupitt** [comment]
You need something like:

```
$ vips extract_band dog.png rgb.png 0 --n 3
$ vips extract_band dog.png alpha.png 3
$ vips invert rgb.png irgb.png
$ vips bandjoin "irgb.png alpha.png" x.png
```

ie. separate the alpha and RGB, invert the RGB, reattach.

There are other ways of doing it: invert is `255 - x`, so you could also write:

```
$ vips linear dog.png x.png -- "-1 -1 -1 1" "255 255 255 0"
```

**Comment by jfcalvo** [comment]
Thanks John. I will go for the linear solution for simplicity, it's working perfectly for me.
