### ISSUE TITLE
What is the size limit when reading images with vips?

### ISSUE THREAD

**Issue by CoderAstrid** [libvips/libvips#1712]
Ask a question...
Hello
i try to read large image with 30 000 X 23 000, 4bit bitmap.
but failed as follows:

> Exception thrown at 0x00007FF8D62FA799 in LargeImgDemo.exe: Microsoft C++ exception: vips::VError at memory location 0x000000D39F6F9EE0.
> Unhandled exception at 0x00007FF8D62FA799 in LargeImgDemo.exe: Microsoft C++ exception: vips::VError at memory location 0x000000D39F6F9EE0.

My code is:
`VImage in = VImage::new_from_file(m_szPathName, VImage::option()->set("access", VIPS_ACCESS_RANDOM));`
`out_log("width = %d, height = %d\n", in.width(), in.height());`

I am using libvipscpp.lib(v8.9.2) at msvc(rebuild successed at vs).
I have successfully read a little smaller image.
So I think there is a limit to the image size.

Regards.

**Comment by jcupitt** [comment]
Hello @CoderAstrid,

There should be (almost) no limit. I regularly process 300,000 x 300,000 pixel slide images. What image format are you using?

If it's TIFF, 8.10 has a new TIFF reader which supports 4-bit images, so that might fix it.

**Comment by CoderAstrid** [comment]
i'm using now 4-bit index grayscale bitmap.

**Comment by jcupitt** [comment]
But what file format? TIFF? PNG? BMP? Something else?

**Comment by CoderAstrid** [comment]
thank you for reply, my format is bmp

**Comment by jcupitt** [comment]
Ah -- BMP is loaded via imagemagick, so there are quite low limits on file size.

Try 4-bit PNG. If you update to vips 8.10, you can also use 4-bit TIFF.

**Comment by CoderAstrid** [comment]
i understand, but v8.10 has no released? for now, i am using v8.92-dev-cpp.
Thank you for your kindly reply.

**Comment by jcupitt** [comment]
It's out in beta, it should work for you:

https://github.com/libvips/libvips/releases/tag/v8.10.0-beta2

**Comment by CoderAstrid** [comment]
very thanks, good solution.
