### ISSUE TITLE
SVG with Style not working

### ISSUE THREAD

**Issue by igorescobar** [libvips/libvips#1713]
Hi,

I have `librsvg2` with `croco3` on my container and I just found a tricky SVG today that has this `style` tag inside of it. 

This is the SVG file:
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 400 140" enable-background="new 0 0 400 140" xml:space="preserve">
<style>
  .a {
    fill: #c00000;
  }
</style>
<title>rails-logo</title>
<g>
	<path class="a" d="M346.6,121.5v18.1c0,0,23.4,0,32.7,0c6.7,0,18.2-4.9,18.6-18.6c0-0.6,0-6.5,0-7c0-11.7-9.6-18.6-18.6-18.6
		c-4.2,0-16.3,0-16.3,0V87l32.3,0V68.8c0,0-22.2,0-31,0c-8,0-18.7,6.6-18.7,18.9c0,1.2,0,5.2,0,6.3c0,12.3,10.6,18.6,18.7,18.6
		c22.5,0.1-5.4,0,15.4,0c0,8.8,0,8.8,0,8.8"/>
	<path class="a" d="M171.4,117.1c0,0,17.5-1.5,17.5-24.1s-21.2-24.7-21.2-24.7h-38.2v71.3h19.2v-17.2l16.6,17.2h28.4
		L171.4,117.1z M164,102.5h-15.3V86.2h15.4c0,0,4.3,1.6,4.3,8.1S164,102.5,164,102.5z"/>
	<path class="a" d="M236.3,68.8c-4.9,0-5.6,0-19.5,0c-13.9,0-18.6,12.6-18.6,18.6c0,13,0,52.2,0,52.2h19.5v-12.5H236v12.5h18.9
		c0,0,0-38.5,0-52.2C254.9,72.2,241.1,68.8,236.3,68.8z M236,106.9h-18.4V89.6c0,0,0-3.9,6.1-3.9c5.6,0,1,0,6.7,0
		c5.4,0,5.5,3.9,5.5,3.9V106.9z"/>
	<rect x="263.8" y="68.8" class="a" width="20.3" height="70.8"/>
	<polygon class="a" points="312.6,121.3 312.6,68.8 292.4,68.8 292.4,121.3 292.4,139.6 312.6,139.6 339.9,139.6 339.9,121.3
		"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.8,13.5,54,40,33,75S9,139.6,9,139.6z"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.8,13.5,54,40,33,75S9,139.6,9,139.6z"/>
	<path class="a" d="M9,139.6h79c0,0-15.1-68.9,34.9-96.8c10.9-5.3,45.6-25.1,102.4,16.9c1.8-1.5,3.5-2.7,3.5-2.7
		S176.8,5.1,118.9,10.9C89.7,13.5,53.9,40,32.9,75S9,139.6,9,139.6z"/>
	<path class="a" d="M173.6,16.5l0.4-6.7c-0.9-0.5-3.4-1.7-9.7-3.5l-0.4,6.6C167.2,14,170.4,15.2,173.6,16.5z"/>
	<path class="a" d="M164.1,37.7l-0.4,6.3c3.3,0.1,6.6,0.5,9.9,1.2l0.4-6.2C170.6,38.3,167.3,37.9,164.1,37.7z"/>
	<path class="a" d="M127.1,6.5c0.3,0,0.7,0,1,0l-2-6.1c-3.1,0-6.3,0.2-9.6,0.6l1.9,5.9C121.3,6.6,124.2,6.5,127.1,6.5z"/>
	<path class="a" d="M131.9,43.3l2.3,6.9c2.9-1.4,5.8-2.6,8.7-3.5l-2.2-6.6C137.3,41.1,134.4,42.2,131.9,43.3z"/>
	<path class="a" d="M86.5,17L82,10.1c-2.5,1.3-5.1,2.7-7.8,4.3l4.6,7C81.4,19.8,83.9,18.3,86.5,17z"/>
	<path class="a" d="M107,62l4.8,7.2c1.7-2.5,3.7-4.8,5.9-7.1l-4.5-6.8C110.9,57.4,108.8,59.7,107,62z"/>
	<path class="a" d="M92.5,94.2l8.1,6.4c0.4-3.9,1.1-7.8,2.1-11.7l-7.2-5.7C94.2,86.9,93.3,90.6,92.5,94.2z"/>
	<path class="a" d="M48.7,46.7l-7.1-6.2c-2.6,2.5-5.1,5-7.4,7.5l7.7,6.6C44,51.9,46.3,49.2,48.7,46.7z"/>
	<path class="a" d="M18.5,91.4L7,87.2c-1.9,4.3-4,9.3-5,12l11.5,4.2C14.8,100,16.9,95.1,18.5,91.4z"/>
	<path class="a" d="M91,119.6c0.2,5.3,0.7,9.6,1.2,12.6l12,4.3c-0.9-3.9-1.8-8.3-2.4-13L91,119.6z"/>
</g>
</svg>
```

This is the actual result:
<img width="385" alt="Screenshot 2020-07-13 at 11 44 06" src="https://user-images.githubusercontent.com/24032/87296099-2b92ce00-c4fe-11ea-807d-c47efef888f3.png">

This is the expected result:
<img width="961" alt="Screenshot 2020-07-13 at 11 43 28" src="https://user-images.githubusercontent.com/24032/87296050-15850d80-c4fe-11ea-9672-c6c053df5624.png">

If I convert all the `class="a"` into `style="fill: #c00000"` it works but I was wondering if this was supposed to be working or if it's not supported.

Thanks!

**Comment by jcupitt** [comment]
Hello @igorescobar,

I think librsvg 2.47 might support this:

https://people.gnome.org/~federico/blog/css-in-librsvg-is-now-in-rust.html

But of course I've not tested it.

**Comment by kleisauke** [comment]
This is what I see on my Fedora PC with librsvg 2.48.7:
![x](https://user-images.githubusercontent.com/12746591/87298123-f1c7c480-c509-11ea-8519-949230ddce59.png)

Which I think is the expected result.

**Comment by igorescobar** [comment]
@kleisauke I'm running on version 2.40 (latest for Debian o.O https://packages.debian.org/search?searchon=sourcenames&keywords=librsvg)

Did you build it from the source or got it from another source?

**Comment by jcupitt** [comment]
I just tried here: it's working for me on Ubuntu 20.04 (the current LTS (long term support) version) with the system librsvg (2.48.2).

Debian is extremely conservative. You'll probably need to build your own stack if you want to use recent library features.

**Comment by igorescobar** [comment]
Yeah, I think I will migrate my image to use Alpine instead.

Thanks guys!

**Comment by kleisauke** [comment]
See also: https://github.com/libvips/libvips/issues/939#issuecomment-381068869.

If you are using sharp, you might also consider using the prebuilt binaries. It follows a release model similar to Alpine.
