### ISSUE TITLE
How to isolate only the non-white portion of a Leica SCN image?

### ISSUE THREAD

**Issue by brahmakulkarni** [libvips/libvips#1715]
Leica SCN image files are used for Whole Slide Images (WSIs). These images do have quite a bit of white space surrounding the actual image. When using ImageScope to view, it automatically detects where the actual image starts and bases the coordinate system accordingly, i.e., the origin is at the top left corner of the actual image (not including the surrounding white spaces). Is there any way in which I can do the same using pyvips so that my origin is also set at the top left corner of the actual image in the Leica SCN file?

**Comment by jcupitt** [comment]
Hello @brahmakulkarni,

Try:

```python
x = pvips.Image.new_from_file("something.scn", autocrop=True)
```

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-openslideload

You could also try looking through the slide metadata to see if there any any extra hints left by the scn loader. Try `vipsheader -a something.scn`.

**Comment by brahmakulkarni** [comment]
@jcupitt 
Thank you so much! It works!
