### ISSUE TITLE
Can I get image metadata from vips?

### ISSUE THREAD

**Issue by priyankatapar** [libvips/libvips#1719]
Can I get below image details from vips? If so, which attributes would give those?

- Color depth
- Resolution and color depth information
- document size information
- DPI

Any pointers will be great help, thanks!

**Comment by jcupitt** [comment]
You can see all the metadata on an image like this:

```
$ vipsheader -a nina.jpg
nina.jpg: 6048x4032 uchar, 3 bands, srgb, jpegload
width: 6048
height: 4032
bands: 3
format: uchar
coding: none
interpretation: srgb
... etc.
```

**Comment by priyankatapar** [comment]
Thanks for the quick response @jcupitt , much appreciated! I will get back if I need to some more details.

**Comment by priyankatapar** [comment]
@jcupitt , is there a way to get colour depth/ bit depth, in above command I only see Colour Space like `sRGB` and not the exact colour depth/ bit depth?

**Comment by jcupitt** [comment]
Yes, `format` is the C type name for the pixel format, so `uchar` is an unsigned 8-bit integer. There are 10 formats: 8, 16 and 32-int int, signed and unsigned, 32 and 64-bit float, and 64 and 128-bit complex.

**Comment by jcupitt** [comment]
`sRGB` is a hint about how pixels values should be interpreted, it's not a bit depth. You can have a 128-bit `sRGB` complex image, for example.

**Comment by priyankatapar** [comment]
Thanks @jcupitt  for answering all the queries with details! I am closing this question for now.

**Comment by angstyloop** [comment]
Here a short C program that is equivalent to `vipsheader -a`. I hope it helps somebody searching the web for "C VIPS Metadata" like this thread helped me!

https://gist.github.com/angstyloop/b0aa0dfc04d765fc0119f59ff2e27b1d

It uses code taken and modified from libvips/tools/vipsheader.c, the source code of the `vipsheader` command line tool.
