### ISSUE TITLE
v8.10.0-beta2 start error on Windows 10

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1720]
**Describe the bug**
run 
vips -v
get error:
![image](https://user-images.githubusercontent.com/73845/87543388-42d8e380-c6d7-11ea-980e-fdadca3d48c0.png)

vips.ext can't find entry point

**Environment**

 - OS: Windows 10 64bit
 - Vips: v8.10.0-beta2 from vips-dev-w64-all-8.10.0-beta2.zip

**Comment by jcupitt** [comment]
Thanks for the report -- it's working for me under wine, but failing on a real win10 system.

It looks like poppler-glib is built against the wrong libstdc++, but I'm not sure how this has happened. I'll investigate.

**Comment by jcupitt** [comment]
Ah, found it, should be fixed for -rc1. Thanks!

**Comment by jcupitt** [comment]
Yes, rc1 seems to have fixed this.

**Comment by jindili** [comment]
@jcupitt You're welcome, libvips is now an essential part of my toolchain and You did help me a lot.

**Comment by jindili** [comment]
rc1 work all right.
