### ISSUE TITLE
PDF to image conversion does not use specified tile-height

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#1721]
Tile-height should ideally be changed and lead to performance improvement. This is described here: https://github.com/libvips/libvips/issues/379#issuecomment-182272832

However, changing tile-height has no effect as per below examples.

```
root@machine# time vips copy bizz_2176220.pdf x.jpg  --vips-tile-height=4096

real    0m1.898s
user    0m1.829s
sys     0m0.072s
root@machine# time vips copy bizz_2176220.pdf x.jpg  --vips-tile-height=128 

real    0m1.857s
user    0m1.827s
sys     0m0.036s

```

This is PDF file: https://img.folders.eu/live/publsh/bizz/217/62/20/bizz_2176220.pdf

As per my limited knowledge, the parameter is not used at all as per this code: https://github.com/libvips/libvips/blob/df72de89d0835e701b2903e68bc369f4a6676bf7/libvips/foreign/pdfload.c#L482

Also I am not able to extract specific page using page argument.

**Comment by adityapatadia** [comment]
I have also tried to change the constants before compiling VIPS from source but they also don't seem to have any effect: https://github.com/libvips/libvips/blob/a5b04091ee95d28bf2725c00ed253ab2b3ad49bd/libvips/include/vips/private.h#L145-L149

**Comment by adityapatadia** [comment]
When I use `pdftocairo`, the results are almost similar.

```
root@machine# time pdftocairo -png -f 4 -l 4 -r 192 bizz_2176220.pdf 

real    2m7.953s
user    2m4.682s
sys     0m0.926s

root@machine# time vips pdfload bizz_2176220.pdf x.jpg  --page 4 --dpi 192

real    2m3.026s
user    1m59.486s
sys     0m0.965s
```

These times are unacceptable for our use-case. So thinking what can be done to improve these times?

**Comment by jcupitt** [comment]
Hello @adityapatadia,

The "chunking" in pdfload is set here:

https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfload.c#L476

Images are rendered in chunks 5000 pixels high.

Your page is only 2200 pixels high:

```
$ vipsheader bizz_2176220.pdf[page=3,dpi=192]
bizz_2176220.pdf: 1587x2245 uchar, 4 bands, srgb, pdfload
```

So changing this number won't improve speed.

I tried in imagemagick;

```
$ /usr/bin/time -f %M:%e convert -density 192 bizz_2176220.pdf[3] im.jpg
173172:16.50
$ /usr/bin/time -f %M:%e vips copy bizz_2176220.pdf[page=3,dpi=192] vips.jpg
132672:133.77
```

imagemagick uses ghostscript for PDF rendering, so it seems that in this case ghostscript is just much faster than poppler.

**Comment by jcupitt** [comment]
What do you mean when you say that you can't extract a page? Could you give an example?

**Comment by adityapatadia** [comment]
> What do you mean when you say that you can't extract a page? Could you give an example?

Leave that for now, I found this `vips pdfload` command which accepts `--page` argument.

**Comment by adityapatadia** [comment]
> imagemagick uses ghostscript for PDF rendering, so it seems that in this case ghostscript is just much faster than poppler.

That seems just correct. See the timings with Ghostscript.

```
time gs -sDEVICE=pngalpha -o my.png -sDEVICE=pngalpha -r192 -dFirstPage=4 -dLastPage=4 bizz_2176220.pdf 

real    0m12.643s
user    0m12.072s
sys     0m0.564s
```

Do you think that only viable option to improve conversion speed is to use ghostscript?

**Comment by jcupitt** [comment]
There's pdfium as well, but the libvips support for that is currently broken.

You don't need to use `pdfload` -- try:

```
vips copy bizz_2176220.pdf[page=3,dpi=192] vips.jpg
```

Note that pages number from 0, so `page=3` extracts the fourth page.

**Comment by adityapatadia** [comment]
Okay then I think only option is to use Ghostscript. PDFium is pain to compile and moreover there is no good nodejs binding is available.

Hope some day, VIPS will have super fast conversion support. Should I close this issue now?

**Comment by jcupitt** [comment]
Yes, pdfium looks like the best option, but it's still not in a good state.

Be careful with ghostscript: the licence does not allow you to use it on a website unless your whole website is open source:

https://www.ghostscript.com/license.html

_Bottom line, if you distribute our software, or make the functionality of the software available to users interacting with it remotely through a computer network, you must share your source code._

You may need to buy a commercial licence.

**Comment by adityapatadia** [comment]
We will keep the licence thing in mind. Thanks for your help. :)
