### ISSUE TITLE
Failed to open svs file

### ISSUE THREAD

**Issue by renexu** [libvips/libvips#1723]
**Describe the bug**

**To Reproduce**
a sample image can be downloaded from https://drive.google.com/file/d/1eNXcUrsG3xrJD2RaXDT0Vw3gX6l8QQZI/view?usp=sharing
run `vipsheader`

error
```
(vipsheader:77802): GLib-CRITICAL **: 11:08:09.148: g_strchug: assertion 'string != NULL' failed

(vipsheader:77802): GLib-CRITICAL **: 11:08:09.149: g_strchomp: assertion 'string != NULL' failed
[1]    77802 segmentation fault  vipsheader Scan\ 4x\ -\ 1B\ -\ Colon\ Benign.svs
```

**Environment**
I tried this in two different envs
 - OS: [MacOS 10.15.5]
 - Vips: [8.9.1]

 - OS: [Ubuntu 18.04]
 - Vips: [8.7.4]

**Comment by jcupitt** [comment]
Wow, I've not seen that one before. Yes, I see a crash here too.

Thanks for the report, I'll investigate.

**Comment by jcupitt** [comment]
I've fixed this in master -- your slide has a property called `aperio.Panoptiq` with a NULL value. This change will be in libvips 8.10.

Thanks again for reporting this.

**Comment by renexu** [comment]
Thank you @jcupitt
