### ISSUE TITLE
Is it Possible to Create An Image and Manipulate Pixels?

### ISSUE THREAD

**Issue by tfink419** [libvips/libvips#1724]
I was looking at this as an alternative to GDLib. I'm not trying to modify an existing image. I want to dynamically generate an image with a custom width and height, in RGBA, and modify the pixels to specific RGBA values.

I can't seem to be able to do this. I can generate a Matrix image in memory of a custom size, but I can't turn that into an RGBA image.

**Comment by tfink419** [comment]
Is this the purpose of libvips, or is my intent better suited for a lower-level library like libpng?

**Comment by jcupitt** [comment]
Sure, can you give an example of an image you might want to create?

A simple way is to use `xyz` to make an image where each pixel has the value of its coordinates, then calculate the pixels you need from that. You can make any image that can be expressed as `pixel = function(x, y)`.

**Comment by jcupitt** [comment]
For example, this makes a red circle:

```python
#!/usr/bin/python3

import sys
import pyvips

# make an image where band 0 is the x coordinate and band 1 the y coordinate
xy = pyvips.Image.xyz(int(sys.argv[1]), int(sys.argv[1]))

# move the origin to the centre
xy = xy - [xy.width / 2, xy.height / 2]

# a one-band image where pixels are distance from the centre
d = (xy[0] ** 2 + xy[1] ** 2) ** 0.5

# relational operations make uchar images with 0 for false, 255 for true
alpha = d < xy.width / 3

# make a solid red image
rgb = xy.new_from_image([255, 0, 0])

# join on the alpha, tag as srgb
image = rgb.bandjoin(alpha).copy(interpretation="srgb")

image.write_to_file(sys.argv[2])
```

**Comment by jcupitt** [comment]
libvips also has a very fast SVG renderer, so you can use SVG to draw your image. For example:

```python
#!/usr/bin/python3
  
import pyvips

x = pyvips.Image.svgload_buffer(b"""
<svg viewBox="0 0 200 200">
  <circle r="100" cx="100" cy="100" fill="#900"/>
</svg>
""")

x.write_to_file("x.png")
```

**Comment by tfink419** [comment]
Thanks for that information. Its a very interesting way to create an image, but I don't know if it matches my use-case.
I'm trying to use the C or C++ libraries which I think is missing some of these conveniences you used for fast array manipulation.
The image I'm trying to create is not geometric in nature and the colors are very dynamic.
I'm iterating through each pixel, checking multiple arrays that matches that [x, y] and setting a color based on the sum of those array position values.
Notably my arrays don't necessarily have all the pixel values mapped, I'm checking for its existence in each array and then use its value.

**Comment by jcupitt** [comment]
You can wrap an image around a C array like this:

```C
/* compile with:
 *      gcc try283.c -g -Wall `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

#define SIZE (100)

int
main( int argc, char **argv )
{
        int x, y, z;
        unsigned char *mem;
        VipsImage *image;

        if( VIPS_INIT( argv[1] ) )
                vips_error_exit( NULL );

        /* SIZE x SIZE rgba image.
         */
        if( !(mem = malloc( 4 * SIZE * SIZE )) )
                vips_error_exit( NULL );
        for( y = 0; y < SIZE; y++ )
                for( x = 0; x < SIZE; x++ )
                        for( z = 0; z < 4; z++ )
                                mem[y * 4 * SIZE + x * 4 + z] = 
                                        2 * (x + y + 64 * z);

        /* Wrap up as a 4-band VipsImage.
         */
        if( !(image = vips_image_new_from_memory( mem, 4 * SIZE * SIZE,
                SIZE, SIZE, 4, VIPS_FORMAT_UCHAR )) )
                vips_error_exit( NULL );

        /* Tag as srgb.
         */
        image->Type = VIPS_INTERPRETATION_sRGB;

        if( vips_image_write_to_file( image, argv[1], NULL ) )
                vips_error_exit( NULL );

        g_object_unref( image );

        free( mem );

        return( 0 );
}
```

You can probably do your iteration and summing with libvips -- it'll thread them and use your vector unit where it can.

**Comment by tfink419** [comment]
Well I got it to work, but unfortunately it appears to be a tad slower than when I was using gdlib.
Example:
With gd: 0.005551 seconds
With libvips: 0.017094 seconds
I'm creating a png blob and sending it up through a Ruby C Extension.
Maybe I'm doing it wrong. I think the step of having to create and iterate through the mem array is causing that slow down. I was hoping to create a blank image, and manipulate the pixels individually as I step through the x,y coordinates.

**Comment by jcupitt** [comment]
It sounds like you are just using libvips and GD for PNG encode. All they are doing is calling libpng for you (there's no processing), so they should be about the same speed. 

You could try setting `compression: 0` as an option -- libpng uses 6 by default, which is pretty slow. Even so, PNG is a slow format. PPM (for example) should be much faster.

You could maybe move more of your processing to libvips. If you post your code I could have a look.

**Comment by tfink419** [comment]
Here's the code as is:
```c++
static VALUE buildImage(VALUE self, VALUE southWestIntRuby, VALUE northEastIntRuby, VALUE stepIntRuby, VALUE pointsRuby) {
  void *pngPointer = NULL;
  VipsImage *im;
  const char* coordError =
    "Coordinates have format: [lat(int), long(int)]";
  const char* mallocError =
    "Memory failed to be allocated";

  Check_Type(southWestIntRuby, T_ARRAY);
  if(RARRAY_LEN(southWestIntRuby) != 2) {
    rb_raise(rb_eArgError, "%s", coordError);
  }
  Check_Type(northEastIntRuby, T_ARRAY);
  if(RARRAY_LEN(northEastIntRuby) != 2) {
    rb_raise(rb_eArgError, "%s", coordError);
  }
  Check_Type(pointsRuby, T_ARRAY);

  int south = NUM2INT(rb_ary_entry(southWestIntRuby, 0));
  int west = NUM2INT(rb_ary_entry(southWestIntRuby, 1));
  int north = NUM2INT(rb_ary_entry(northEastIntRuby, 0));
  int east = NUM2INT(rb_ary_entry(northEastIntRuby, 1));
  int stepInt = NUM2INT(stepIntRuby);

  int width = ((east-west)/stepInt)+1;
  int height = ((north-south)/stepInt)+1;

  int x, y;
  unsigned char *mem = new unsigned char[CHANNELS * width * height];
  if(!mem) rb_raise(rb_eRuntimeError, "%s", mallocError);

  unsigned int gstoreInd = 0;

  VALUE point;
  short currentPointExists = (RARRAY_LEN(pointsRuby) > 0);
  int currentPointLat, currentPointLong;
  double currentPointQuality;
  if(currentPointExists) {
    point = rb_ary_entry(pointsRuby, 0);
    checkPointArray(point);
    currentPointLat = NUM2INT(rb_ary_entry(point, 0));
    currentPointLong = NUM2INT(rb_ary_entry(point, 1));
    currentPointQuality = NUM2DBL(rb_ary_entry(point, 2));
  }
  
  // Iterate through coordinates, changing each pixel at that coordinate based on the point(s) there
  double quality;
  u_int color, pos;
  int lat, lng;
  for(lat = south, y = height-1; lat <= north; lat += stepInt, y--) {
    for(lng = west, x = 0; lng <= east; lng += stepInt, x++) {
      quality = 0;
      if(currentPointExists && currentPointLat == lat && currentPointLong == lng) {
        quality = currentPointQuality;
        if(++gstoreInd < RARRAY_LEN(pointsRuby)) {
          point = rb_ary_entry(pointsRuby, gstoreInd);
          checkPointArray(point);

          currentPointLat = NUM2INT(rb_ary_entry(point, 0));
          currentPointLong = NUM2INT(rb_ary_entry(point, 1));
          currentPointQuality = NUM2DBL(rb_ary_entry(point, 2));
        }
        else {
          currentPointExists = 0; // false
        }
      }
      if(quality > 12.5) {
        quality = 12.5;
      }
      if(quality < 0) {
        quality = 0;
      }
      color = quality*8;
      pos = y*width*CHANNELS+x*CHANNELS;
      mem[pos] = GRADIENT_MAP[color][0];
      mem[pos+1] = GRADIENT_MAP[color][1];
      mem[pos+2] = GRADIENT_MAP[color][2];
      mem[pos+3] = ALPHA;
    }
  }

  size_t imageSize;

  /* Turn the array we made into a vips_image */
  im = vips_image_new_from_memory( mem, CHANNELS * width * height, width, height, CHANNELS, VIPS_FORMAT_UCHAR );
  if(!im) vips_error_exit( NULL );

  im->Type = VIPS_INTERPRETATION_sRGB;

  /* Turn the vips image into a png blob */
  if( vips_pngsave_buffer(im, &pngPointer, &imageSize, "compression", 3, NULL) )
    vips_error_exit( NULL );
  g_object_unref(im); 
  delete[] mem;

  if(!pngPointer) {
    vips_error_exit( NULL );
  }

  VALUE stringRuby = rb_str_new((char *)pngPointer, imageSize);
  g_free(pngPointer);
  return stringRuby;
}
```
So you are saying there is a way to move this iteration and summing into libvips? Hopefully saving on processing time. I can send the incoming data in a different order or format if needed. One issue might be that the incoming data is a nest of ruby arrays, I'm not sure if re-processing it into C-arrays will be serious enough of a cost.

As of right now its not doing any summing as I said, but eventually this will have multiple arrays of points. As well there will be a multiple for the value in each array.

**Comment by jcupitt** [comment]
Huh so your point array is (lat, long, quality) and the output is a false-colour PNG with colour dots for points and black elsewhere, is that right? Rather than scanning the image, I'd think it would be quicker and safer to make a large black image and then draw the pixels in the point array. At the moment, points will flail to plot if you set `stepInt` incorrectly, for example. Is the point array a regular (rectangular) grid?

You could use libvips for the false colour and the summing. You're right that point array -> image might be better in C. Try setting `compression` to 0 if you need more speed.

**Comment by tfink419** [comment]
You have it right, except the default color is red.
I think that is why gdlib is my fastest implementation right now, with gdlib I can prefill the image with the 0-value color, and then only paint pixels that are different, and in my image there ideally is a lot of "empty" space.
And yea, the function is very delicate to the given parameters, but I do sanitization before sending it down to the C code.
The points array is rectangular, it is the result of a PSQL BETWEEN query on lat and long bounds.

**Comment by tfink419** [comment]
Thanks for all the help. After more research and adding the second set of data, it's clear my throttle is actually on the retrieval side. I'm going to figure out a way to build the data as chunks of images and use libvips to perform the various math functions on equally sized and mapped image chunks.

**Comment by jcupitt** [comment]
That sounds very sensible. Do open a new issue if you need any help.
