### ISSUE TITLE
Unable to resize animated webp image

### ISSUE THREAD

**Issue by pomirleanu** [libvips/libvips#1730]
**To Reproduce**
-  vipsthumbnail --size=500x500 video.webp[n=-1] -o small.webp

**Error**

- webp: bad image dimensions

**Test file**
I've added the file in an archive because .webp it's not supported.
[video.zip](https://github.com/libvips/libvips/files/4947755/video.zip)

**Comment by jcupitt** [comment]
You're right, it was not checking image bounds correctly for very large animated webp images. I now see:

```
john@kiwi:~/pics$ vipsthumbnail video.webp[n=-1] -o x.gif
john@kiwi:~/pics$
```

![x](https://user-images.githubusercontent.com/580843/87946549-12f45c00-ca9a-11ea-9648-12cd929ed12c.gif)

Thanks for reporting this.  The fix should be in 8.10, due in a week or so.
