### ISSUE TITLE
Why some images generated by libvips appear cropped differently on certain devices?

### ISSUE THREAD

**Issue by jgguenard** [libvips/libvips#1736]
I'm not certain if this a bug or a misunderstanding but some images processed by libvips appear differently on 2 different PCs:

Here's one of the files:
https://us-east-1.linodeobjects.com/niche-canvas/p/7fe2f9c2-dbc5-476a-8745-6496d38d9e6e/p4-large.jpg

When two of my teammates open this file in Preview or Ms Paint, they see it this way:

![Rendering1](https://user-images.githubusercontent.com/2058552/88087014-409edb00-cb56-11ea-991c-714195702a3f.jpg)

But the way it should look is:

![Rendering2](https://user-images.githubusercontent.com/2058552/88086043-b5711580-cb54-11ea-9954-137e326b96cf.jpg)

As you can see, the tree at the right side of the first image is truncated. We are all working on Windows 10 machines.

We use a simple mix of **extract** and **composite** functions to generate a mirror bleeding effect. 

Has anyone ever encountered this issue? 

It's driving me mad...

**Comment by jcupitt** [comment]
Wow that's odd. Could you post your code?

libvips has a built-in thing to extend edges with a mirror, btw, try:

```
$ vips embed Gugg_coloured.jpg x.jpg 100 100 1172 1496 --extend mirror
```

The numbers are left, top of the input in the output, and width, height of the output.

**Comment by jcupitt** [comment]
Docs for `embed` here:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-embed

**Comment by jgguenard** [comment]
> Docs for `embed` here:
> 
> https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-embed

I'm using the implementation for NodeJs (Sharp) and they don't expose this function in their API unfortunately.

Here is the code:

```typescript
    // bleed (mirror mode)
    if (options.bleed > 0) {
        const roundedBleed = Math.round(options.bleed);
        // top
        const top = await image
            .clone()
            .extract({ left: 0, top: 0, width: resizeWidth, height: roundedBleed })
            .pipe(sharp())
            .flip()
            .toBuffer();
        // bottom
        const bottom = await image
            .clone()
            .extract({ left: 0, top: resizeHeight - roundedBleed, width: resizeWidth, height: roundedBleed })
            .pipe(sharp())
            .flip()
            .toBuffer();
        // pad image vertically
        await image.extend({ top: roundedBleed, left: roundedBleed, bottom: roundedBleed, right: roundedBleed });
        await image.composite([
            { input: top, gravity: 'north' },
            { input: bottom, gravity: 'south' }
        ]);
        const postImage = await image.clone().pipe(sharp());
        const postImageInfo = await postImage.metadata();
        // left
        const left = await postImage
            .clone()
            .extract({ left: roundedBleed, top: 0, width: roundedBleed, height: postImageInfo.height })
            .pipe(sharp())
            .flop()
            .toBuffer();
        // right
        const right = await postImage
            .clone()
            .extract({ left: resizeWidth, top: 0, width: roundedBleed, height: postImageInfo.height })
            .pipe(sharp())
            .flop()
            .toBuffer();
        await image.composite([
            { input: top, gravity: 'north' },
            { input: bottom, gravity: 'south' },
            { input: left, gravity: 'west' },
            { input: right, gravity: 'east' }
        ]);
        postImage.destroy();
    }

    // ...

    // export
    await image
        .jpeg(exportOptions)
        .toFile(outFile);
    image.destroy();
```

If it's a bug related to Sharp, I'll create an issue in their repo then. But I'm considering using Go for this service since I feel like missing a lot of features with Sharp.

**Comment by jcupitt** [comment]
Yes, sharp isn't intended to be a general purpose image processing library -- it's a fixed pipeline for image resizing, with a few extra features.

There isn't an official Go binding and I've seen reports of leaks and memory errors with most of them, unfortunately :(

**Comment by jcupitt** [comment]
I meant to say, I would open an issue on the sharp repo.

You'll need a test case that shows the problem, of course, which sounds like it might be tricky.

**Comment by jgguenard** [comment]
Will do, thanks!
