### ISSUE TITLE
Can dzsave parallelism/scaling be improved?

### ISSUE THREAD

**Issue by rmontroy** [libvips/libvips#1737]
>Oh gosh, yes, you must use openslide. The TIFF loader won't load SVS files correctly.

_Originally posted by @jcupitt in https://github.com/libvips/libvips/issues/1492#issuecomment-662007128_

**Comment by rmontroy** [comment]
@jcupitt:
 Well, I built it with OpenSlide included, but it's still not using as much cpu as available. I also ran it against pre-built 8.9.2 (in case there was another issue with how I built it), and this is as good as it gets:
```
root@6475dbe0f06c:/# vipsheader medium.svs 
medium.svs: 51792x40706 uchar, 4 bands, rgb, openslideload
root@6475dbe0f06c:/# vips dzsave medium.svs x --vips-progress
vips temp-1: 51792 x 40706 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
vips temp-1: done in 73.6s  
```
```
top - 21:54:04 up 1 min,  2 users,  load average: 2.14, 0.53, 0.18
Tasks: 148 total,   2 running,  78 sleeping,   0 stopped,   0 zombie
%Cpu0  : 60.2 us, 11.6 sy,  0.0 ni, 28.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 58.1 us, 13.2 sy,  0.0 ni, 28.4 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 57.0 us, 15.8 sy,  0.0 ni, 27.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 56.6 us, 15.3 sy,  0.0 ni, 27.8 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  : 59.2 us, 12.3 sy,  0.0 ni, 28.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  : 56.3 us, 15.3 sy,  0.0 ni, 28.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  : 60.7 us, 15.5 sy,  0.0 ni, 23.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  : 57.2 us, 15.5 sy,  0.0 ni, 27.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 15834776 total, 14466928 free,   684968 used,   682880 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 14876044 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                     
 5438 root      20   0 5168764 419312  21828 S 581.4  2.6   1:22.23 vips              
```
Is there a specific environment and/or large-ish test images that I can use to try to reproduce the expected behavior (that you're seeing)?

**Comment by rmontroy** [comment]
Taking another look at your [previous comment](https://github.com/libvips/libvips/issues/1492#issuecomment-661979049):

> ```
> $ time vips dszsave 10381_text.svs x
> real	4m47.453s
> user	11m47.527s
> sys	1m48.640s
> $ ls -l 10381_test.svs 
> -rw-rw-r-- 1 john john 596835563 Jun 10 14:32 10381_test.svs
> $ vipsheader 10381_test.svs
> 10381_test.svs: 45056x114688 uchar, 4 bands, srgb, openslideload
> ```
> So a 6GB SVS in under 5m.

That's actually a 569MB file you tested. So, perhaps I can't expect any miracles, but it would be nice if it scaled better on bigger machines.

**Comment by kleisauke** [comment]
Thanks for tracking this in a separate issue!

> An openslide option to directly output flattened RGB rather than RGBA could maybe give a speedup.

I had a quick go with this OpenSlide patch: https://gist.github.com/kleisauke/1881bbeae4e923a54ad82724f351bbd2.

Although it uses [`CAIRO_FORMAT_RGB24`](https://www.cairographics.org/manual-1.17.2/cairo-Image-Surfaces.html#cairo-format-t) as output format (i.e. a 4-band ARGB image with the alpha channel unused), it appears to be 5 seconds (~19%) faster than `CAIRO_FORMAT_ARGB32`.
```bash
$ vipsheader CMU-1.svs 
CMU-1.svs: 46000x32914 uchar, 4 bands, srgb, openslideload
$ time vips dzsave CMU-1.svs x.zip

real	0m24.255s
user	1m15.746s
sys	0m18.361s
```

It's a bit unfortunate that Cairo can't output a 3-band RGB image. I think it would speed things up even more, since the `vips_flatten` / `argb2rgba` calls can be skipped.

**Comment by jcupitt** [comment]
Ooop, I need stronger glasses, sorry about that.

I did a few experiments with the openslide sample images. I ran:

```
$ vips avg CMU-1.svs
```

`avg` is very simple, so this just tests openslide load speed. I ran on my two-core, four-thread laptop, watched top, and noted typical load:

File | %cpu user
  ---- | ----
JP2K-33003-2.svs | 52% 
CMU-1.svs | 54%
CMU-3.mrxs | 65%
CMU-1.ndpi | 78% 

There's a surpring range. It's clear openslide alone can't get enough parallelism from the load libraries to saturate the machine.

You can test dzsave in isolation like this:

```
$ vips black x.dz 100000 100000
```

ie. write a large pyramid where every tile is black. This gets about 50% user, 25% sys and 25% idle. You can remove file create like this:

```
$ vips black x.dz[container=zip] 100000 100000
```

Which moves it to 55% user, 20% sys, 25% idle.

**Comment by jcupitt** [comment]
I didn't lock the clocks, I probably should have.

**Comment by rmontroy** [comment]
> It's a bit unfortunate that Cairo can't output a 3-band RGB image. I think it would speed things up even more, since the vips_flatten / argb2rgba calls can be skipped.

This is great! I did a quick test on my MBP and it reduces execution time by >18%.
The vips_flatten / argb2rgba calls don't seem to take all that much time anyway.

**Comment by rmontroy** [comment]
> This is great! I did a quick test on my MBP and it reduces execution time by >18%.

The speedup is more noticeable on a larger file size/cpu ratio. On a 8 core, 16 thread instance, the 472MB file was 6.3% faster, the 3.7GB file improved by 11.4%.

**Comment by rmontroy** [comment]
`$ vips avg huge.svs`

On a 16 vCPU EC2 instance, CPUs were sleeping 61-62% of the time

`$ vips black x.dz 100000 100000`
`$ vips black x.dz[container=zip] 100000 100000`

With both of these, CPUs were idle ~70% of the time.

**Comment by jcupitt** [comment]
Openslide images can have empty areas, so you do need an alpha channel. I was thinking that we could have a flag to openslideload that does the flatten as part of the ARGB to RGB conversion. I'll try a benchmark.

**Comment by rmontroy** [comment]
I'm trying to do some off-CPU profiling according to this: http://www.brendangregg.com/FlameGraphs/offcpuflamegraphs.html#Off-CPU — but I'm not having much luck.
https://dzsave-performance.s3.us-east-2.amazonaws.com/off-CPU.svg

This is part of a larger project that I need to get back to, but I'll try to come back to this issue in a few weeks.

**Comment by rmontroy** [comment]
I'm not going to investigate this further, so closing for now.
