### ISSUE TITLE
Getting negative values for buffer length in vips_pngsave_buffer

### ISSUE THREAD

**Issue by revathi-murali** [libvips/libvips#1739]
We are using libvips `v8.9.1` running on alpine docker image. So when we are trying to save the png image, for some images, we noticed that the length of the buffer is returned as negative. i.e `len` in `vips_pngsave_buffer` is returning a negative integer value. Is it something to do with memory?

**Comment by jcupitt** [comment]
You need to share some code I can test.

At a guess, perhaps you are not checking the return value from `vips_pngsave_buffer()`? If the operation fails, the `len` will not be set and will contain random data.

**Comment by revathi-murali** [comment]
No, the return value of vips_pngsave_buffer is zero. I am not sure if it could be a memory issue? I am running on alpine docker image.

**Comment by jcupitt** [comment]
Perhaps. I can't help unless you share some code that I can run to show the problem.

**Comment by jcupitt** [comment]
`VIPS_DISC_THRESHOLD` is documented here:

https://libvips.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-file

**Comment by jcupitt** [comment]
I'll close. Please reopen if you can find a test case that shows the problem.
