### ISSUE TITLE
Math Operations On Images

### ISSUE THREAD

**Issue by tfink419** [libvips/libvips#1741]
I'm having trouble understanding how to perform math operations on an image.

I want to divide all values in an image by one number. This is a snippet of me playing around with this.
I couldn't get divide to work so I tried just multiplying by 1, I figured it should at least return the exact same image back
```c
// image_1 is pulled from a png data buffer, I already checked that this image is properly loaded by resaving it
image_2 = vips_image_new_matrixv (1, 1, 1.0);
// if(!image_2)
//   vips_error_exit( NULL );
// if(vips_cast(image_2, &image_3, VIPS_FORMAT_USHORT, NULL))
//   vips_error_exit( NULL );
image_3 = image_2; // When the lines above are commented out

if(vips_multiply (image_1, image_3, &image_2, NULL))
  vips_error_exit( NULL );
g_object_unref(image_3);
g_object_unref(image_1);

char file_path[256];
sprintf(file_path, "/Users/tyler/sites/quality_map_image/libvips_image%d.png", i);
if( vips_image_write_to_file( image_2, file_path, NULL ) )
  vips_error_exit( NULL );
```

The image I'm inputting is a 16-bit 1 band grayscale image
![test_image2](https://user-images.githubusercontent.com/583973/88366587-bec1d400-cd46-11ea-8024-9e8a4928fc38.png)
and the result is just a black image
![libvips_image1](https://user-images.githubusercontent.com/583973/88366594-c3868800-cd46-11ea-8094-e187af722040.png)

I also want to do similar types of math with add and subtract. Mostly operations like `Number-Image`

**Comment by tfink419** [comment]
I got it to work by creating a matrix at the same width and height as the image. But I would prefer not to have to fill an array with width x height of the same number for all these operations

**Comment by jcupitt** [comment]
Hello @tfink419,

You need `vips_linear(in, out, a, b)`. It computes `in * a + b`, ie. the linear transform.

https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-linear

You can give a small array for `a` and `b`, so you can use a different constant for every band, or `vips_linear1()` take a single constant. 

`new_matrix` is for things like convolution masks. I wouldn't use it for general image processing, it's slow and needs a lot of RAM.

If you can use it, the C++ binding has a full set of operator overloads, so you can just write:

```c++
VImage x = VImage::new_from_file(filename);
x = (x << 2) * 3 - x % 2;
x.write_to_file(filename2);
```

And it'll call the correct operations and handle all the unrefs.

**Comment by tfink419** [comment]
Thanks @jcupitt, this is great.
I'm going to stick to use the C library so I can efficiently double up on operations like so
```c
 // num = num*1/scale - low
    if(vips_linear1((image_1, &image_2, 1/scale, 0-range_low, NULL))
      vips_error_exit( NULL );
```

**Comment by jcupitt** [comment]
OK, sounds reasonable. 

If you'll be doing a lot of maths, a simple optimisation is to operate on a LUT instead. Make a ramp lut with `vips_identity()` (the identity function), then do your maths on that image. When you have transformed it, use `vips_maplut()` to pass the large image through the lut.

**Comment by tfink419** [comment]
I'm not sure if I can use identity. One of the math calculations performed on the image is as follows
```c
// num = (num.abs+num)/2
if(vips_abs (image_2, &image_1, NULL))
  vips_error_exit( NULL );
if(vips_add (image_1, image_2, &image_3, NULL))
  vips_error_exit( NULL );
g_object_unref(image_1);
g_object_unref(image_2);
if(vips_linear1(image_3, &image_1, 0.5, 0, NULL))
  vips_error_exit( NULL );
g_object_unref(image_3);
```
What I'm doing with this is stripping the value to a low and high bounds
i.e.
```
if(pixel_value < low)
  pixel_value = low;
if(pixel_value > high)
  pixel_value = high;
```

Is there another way to do this

**Comment by jcupitt** [comment]
You can use `vips_ifthenelse()` to use a condition image to pick between two other images. It should work on a LUT, if I understand your meaning. Use `vips_image_new_from_image()` to make a constant image. 

libvips has ref pools, so you can remove a lot of your unrefs. Something like this:

```C
int
rotate_with_background( VipsObject *scope, VipsImage *in, VipsImage **out )
{
        VipsImage **t = (VipsImage **) vips_object_local_array( scope, 10 );

        VipsArrayDouble *array;
        int result;

        array = vips_array_double_newv( 3, 255.0, 0.0, 0.0 );

        result =
                vips_black( &t[0], 1, 1, NULL ) ||
                vips_linear1( t[0], &t[1], 1.0, 255.0, NULL ) ||
                vips_cast( t[1], &t[2], VIPS_FORMAT_UCHAR, NULL ) ||
                vips_embed( t[2], &t[3], 0, 0, in->Xsize, in->Ysize,
                        "extend", VIPS_EXTEND_COPY,
                        NULL ) ||
                vips_bandjoin2( in, t[3], &t[4], NULL ) ||
                vips_similarity( t[4], &t[5],
                        "angle", 45.0,
                        NULL ) ||
                vips_flatten( t[5], out,
                        "background", array,
                        NULL );

        vips_area_unref( (VipsArea *) array );

        return( result );
}
```

When the caller unrefs `scope`, all the objects allocated local to scope will also be unreffed. This lets you chain operations with `||`.

**Comment by tfink419** [comment]
I thought `vips_ifthenelse` would be what I'm looking for but I have no idea how to use it, I'm so confused by so much of the library 😅. It is really powerful I can tell, the things I've done so far have been great.

Okay that's interesting, that can help a lot with the 21 counts of `g_object_unref` I already have scattered around.

**Comment by jcupitt** [comment]
Post some sample code if you like and I'll redo it with ifthenelse.

**Comment by tfink419** [comment]
Here's what I have right now that could be an ifthenelse
```c
// num = num*1/scale - low
if(vips_linear1(image_1, &image_2, 1/scale, 0-range_low, NULL))
  vips_error_exit( NULL );
g_object_unref(image_1);

// num = (num.abs+num)/2
if(vips_abs (image_2, &image_1, NULL))
  vips_error_exit( NULL );
if(vips_add (image_1, image_2, &image_3, NULL))
  vips_error_exit( NULL );
g_object_unref(image_1);
g_object_unref(image_2);
if(vips_linear1(image_3, &image_1, 0.5, 0, NULL))
  vips_error_exit( NULL );
g_object_unref(image_3);

// num = high-low-num
if(vips_linear1(image_1, &image_2, -1, range_high-range_low, NULL))
  vips_error_exit( NULL );
g_object_unref(image_1);

// num = (num.abs+num)/2
if(vips_abs (image_2, &image_1, NULL))
  vips_error_exit( NULL );
if(vips_add (image_1, image_2, &image_3, NULL))
  vips_error_exit( NULL );
g_object_unref(image_1);
g_object_unref(image_2);
if(vips_linear1(image_3, &image_1, 0.5, 0, NULL))
  vips_error_exit( NULL );
g_object_unref(image_3);
```

It is using some funky math properties to do this:
```pseudo
pixel_value = pixel_value/scale - low;
if(pixel_value < 0)
  pixel_value = 0;
if(pixel_value > high-low)
  pixel_value = high-low;
```

**Comment by jcupitt** [comment]
Something like:

```C
/* compile with:
 *
 * 	gcc -g -Wall range.c `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

static int
range( VipsObject *scope, VipsImage *in, VipsImage **out, int low, int high )
{
	VipsImage **t = (VipsImage **) vips_object_local_array( scope, 10 );

	if( !(t[0] = vips_image_new_from_image1( in, low )) ||
		!(t[1] = vips_image_new_from_image1( in, high )) ||
		vips_less( in, t[0], &t[2], NULL ) ||
		vips_ifthenelse( t[2], t[0], in, &t[3], NULL ) ||
		vips_more( t[3], t[1], &t[4], NULL ) ||
		vips_ifthenelse( t[4], t[1], t[3], out, NULL ) ) 
		return( -1 );

	return( 0 );
}

int 
main( int argc, char **argv )
{
	double scale;
	int low;
	int high;
	VipsImage *image;
	VipsImage *x;
	VipsObject *scope;

	if( VIPS_INIT( argv[0] ) )
		return( -1 );

	scale = atof( argv[3] );
	low = atoi( argv[4] );
	high = atoi( argv[5] );

	if( !(image = vips_image_new_from_file( argv[1], 
		"access", VIPS_ACCESS_SEQUENTIAL,
		NULL )) )
		vips_error_exit( NULL );

	if( vips_linear1( image, &x, 1.0 / scale, -low, NULL ) ) {
		g_object_unref( image );
		vips_error_exit( NULL );
	}
	g_object_unref( image );
	image = x;

	scope = VIPS_OBJECT( vips_image_new() ); 
	if( range( scope, image, &x, low, high ) ) {
		g_object_unref( scope );
		g_object_unref( image );
		vips_error_exit( NULL );
	}
	g_object_unref( scope );
	g_object_unref( image );
	image = x;

	if( vips_image_write_to_file( image, argv[2], NULL ) ) { 
		g_object_unref( image );
		vips_error_exit( NULL );
	}
	g_object_unref( image );

	return( 0 );
}
```

**Comment by tfink419** [comment]
Thanks for this, I'll test it all out by tomorrow. I've been working on getting the ruby c extension to run on Heroku, I got it working by putting my whole web application into a docker.
Scope will help a lot as well, I think I'm running into issues of not clearing all the data and the app failing out after this warning 
```
(vips:92650): VIPS-WARNING **: 22:05:12.636: not enough data
```

**Comment by jcupitt** [comment]
If you're using Ruby, I think I'd just use ruby-vips. I don't think you'll gain much by writing C yourself.

**Comment by tfink419** [comment]
I'll play around with that. I figured that doing all these operations on the image and sending it up to ruby each time before I actually need the buffer would cause slow downs. I was already using C as well for some other optimizations.

I seem to be able to find all the operations I need in ruby-vips, they just use different names.

**Comment by jcupitt** [comment]
ruby-vips is pretty close to C for speed -- you use ruby to build the image processing pipeline, but all the actual execution happens inside libvips and is the same whether you call the library from Ruby or C.

The operations should have the same names in C and Ruby: they are both generated automatically from the libvips source. For example, you can write:

```ruby
image = Vips::Image.new_from_file filename, access: :sequential
image = image.linear 12, 45
image = (image < 100).ifthenelse(100, image)
image = (image > 200).ifthenelse(200, image)
image.write_to_file filename2
```

ruby-vips just adds a few handy shortcuts and operator overloads.

**Comment by jcupitt** [comment]
If you know the image is 8-bit, you can write:

```ruby
image = Vips::Image.new_from_file filename, access: :sequential
lut = Vips::Image.identity
lut = lut.linear 12, 45
lut = (lut < 100).ifthenelse(100, lut)
lut = (lut > 200).ifthenelse(200, lut)
image = image.maplut lut
image.write_to_file filename2
```

ie. exactly the same, just operate on the lut instead. It works for 16-bit uint image too, of course.

**Comment by tfink419** [comment]
Thanks for this, I'll try it out using just ruby-vips today.

**Comment by tfink419** [comment]
How do I load an array of values into a ruby-vips image with RGBA interpretation. You can't use `interpretation=` in rub-vips

**Comment by tfink419** [comment]
Well I got all the code working in C. Same code I have in Ruby except the final part so I'm not sure if its right. One question about using a lut for all the math. Will it work on a UINT32 image?

**Comment by jcupitt** [comment]
Do you mean a pointer to a C array, or a ruby Array object?

No, it'll need to be uint8 or uint16. A uin32 LUT would have 4bn entries and would be larger than your image (probably). It's usually possible to find a function that transforms the set of different input values into 2**8 or 2**16 integers.

**Comment by tfink419** [comment]
Okay makes sense, yea that LUT would definitely be larger than my file.
I might be able to lose some precision during the processing and use the LUT. But for now this is working great.
The array I'm working with for the Ruby code is a ruby Array object that looks like this
```
[r, g, b, a, r, g, b, a, ...]
```
I'm using this array as a false color LUT to map the final image to.

**Comment by jcupitt** [comment]
You can make a new image from a 2D array:

```ruby
lut = Vips::Image.new_from_array [
    [r1, g1, b1, a1],
    [r2, g2, b2, a2],
...
    [r256, g256, b256, a256],
]
```

That'll make a 4 x 256, one-band `double` image. Use `bandfold` to turn the X axis into the colour axis (so you get a 1 x 256 four-band image), `copy` to set the interpretation, and `cast` to make it uchar. 

```ruby
lut = lut.bandfold.copy(interpretation: :srgb).cast(:uchar)
```

`bandfold` and `copy` are very quick: they just change how pixels are addressed, not the pixels themselves.

**Comment by jcupitt** [comment]
If you've not tried it, nip2 is very handy for debugging. You can write an intermediate image out as a `.v` (vips format) file and it'll keep all of the metadata and the exact pixel value. Run nip2 on it, and you can check every pixel. It has some nice stuff for viewing double and complex images -- press F1 and check the user guide. 

Something simple like:

```ruby
module Vips
    class Image
        def debug(image)
            if $debug
                image.write_to_file("x.v")
                system("nip2 x.v")
                File.delete("x.v")
            end
            image
        end
    end
end
```

Now you can insert `.debug` into pipelines and check the image at that point. 

You can use nip2 to develop and execute pipelines too, but that's more effort. I made a nip2 worksapce to analyze PET-CT scans that has about 14,000 nodes.

**Comment by tfink419** [comment]
Perfect, with that I should have the ruby code finished up and I can compare performance
nip2 will so helpful going forward. I've been manually inspecting the images, which has been hard at times.

**Comment by jcupitt** [comment]
Yes, it's handy -- turn on the display control (scale and offset for each pixel, plus a useful gear menu) and the status bar (see exact pixel values as you move the mouse), i and o to zoom in and out, cursor / shift-cursor / ctrl-cursor to scroll, number keys to zoom in, 0 to shrink to fit. Right-click to view the header.

**Comment by tfink419** [comment]
Everything is working great so far.

I have a question about if there exists an operation for a certain use case of mine. Look at this image, this is the false color version of my results,
![image](https://user-images.githubusercontent.com/583973/88820688-dd78fe00-d17e-11ea-8a5b-df13d78ac615.png)
If you examine it you see spread out are small pixel 'holes' of blue-green. These are 0's in the original data image and are the result of thin gaps between polygons. Is there an operation I could use to find these single pixel 'holes' and fill them in. I looked at `fill_nearest` and it seems to not be the use case I need. I only want to fill in these 1 pixel holes and nothing more.
One approach I had taken was measuring the original data a double the precision and subsampling it down to the preferred size. This helped a little but there are still some gaps.

**Comment by jcupitt** [comment]
The usual trick is to make a mask with 255 for the stray pixel locations, then do a median filter and use ifthenelse to paste the result of the median into the holes. You can use the morphological operators to tune the mask so it's just isolated pixels.

**Comment by jcupitt** [comment]
Something like this?

![x](https://user-images.githubusercontent.com/580843/88822511-d91f0600-d1bb-11ea-85a4-f59249708189.png)

That's without the morphology, so it's changed the outline of the blue areas slightly, but perhaps that's OK.

**Comment by tfink419** [comment]
I would prefer to only clean up the small holes, but I think it would be OK to slightly alter larger areas that are 0. I'll have to play around with it. So the morphology allows me to select which pixels operations are being performed on? I'll have to figure out how to isolate those pixels, maybe by stealing one bit from the value to flag if its the result of no polygon being found.

**Comment by jcupitt** [comment]
You can use morphologies to match patterns, eg. a set pixel with 8 clear pixels around it. Your image has quite a few vertical stripes which I guess you want to clean too, so you'd need something a bit more complex.

**Comment by tfink419** [comment]
Yea the vertical stripes I figured are the biggest issue. Thats why I thought it might be a good route to individually flag pixels and just map that value. Is that a possibility? I don't think it would be hard for me to do, I could sacrifice an entire band of my RGBA data images and turn that into its own flag field for other future cases.

**Comment by jcupitt** [comment]
Are the stripes always vertical? You could search for a pattern like:

```
0 0 0
0 1 0 
0 ? 0
```

Where ? means don't care. Each time you run that morph, it'll eat a pixel off the top of a line. Run it four times and you'll remove all your lines.

**Comment by tfink419** [comment]
They aren't here's the some good examples I found in my data. 
![856](https://user-images.githubusercontent.com/583973/88875898-590a9780-d1df-11ea-9d49-4a9816d7499c.png)
![852-1](https://user-images.githubusercontent.com/583973/88876053-b1419980-d1df-11ea-97c2-048d96a1fcc4.png)
![852-2](https://user-images.githubusercontent.com/583973/88876055-b1da3000-d1df-11ea-987f-e7c7bc3e522e.png)

They are 32 bits encoded into an RGBA which can be manipulated like so 
```
  def self.bandjoin(image)
    bands = image.bandsplit
    bands = bands.each_with_index.map do |band, ind|
      band.cast(:uint) << 8*(3-ind)
    end
    Vips::Image.sum(bands)
  end

  def self.split_into_bands(image)
    bands = (0..3).map do |band|
      ((image.copy >> 8*(3-band) & 255)).cast(:uchar)
    end
    joined = bands[0].bandjoin(bands[1..3])
    joined
  end
```
Like I said, I think if I pull one of those bands out, and use a bit to flag the pixel as _found_ polygon_, I could pretty easily transform the individual bits of the flag band into masks. It will be more accurate then this morphology method.

**Comment by tfink419** [comment]
```
  def self.clean_zeros(image_blob)
    image = bandjoin(Vips::Image.new_from_buffer image_blob, "", access: :sequential)
    median_ranked = image.median(2)
    image = (image == 0).ifthenelse(median_ranked, image)
    split_into_bands(image).
      pngsave_buffer(compression: 9, strip: true)
  end
```
This seems to work perfectly on these 3 images even just checking for 0, but I'm thinking of doing some version of my above comments route
![zeroes_cleaned0](https://user-images.githubusercontent.com/583973/88878215-aa695580-d1e4-11ea-9642-abe33ce58941.png)
![zeroes_cleaned1](https://user-images.githubusercontent.com/583973/88878216-aa695580-d1e4-11ea-8efa-b730b1b9b827.png)
![zeroes_cleaned2](https://user-images.githubusercontent.com/583973/88878217-ab01ec00-d1e4-11ea-831e-a14def91cd15.png)

**Comment by tfink419** [comment]
I forgot I am trying to do this before I create the data image, when I have all this information at my disposal, so I can just create a second image from memory based on bool values.

**Comment by jcupitt** [comment]
Ah, that sounds much cleaner.
