### ISSUE TITLE
vips_region_fetch failed with 'pngload: non-recoverable state'

### ISSUE THREAD

**Issue by xiaoguzhu** [libvips/libvips#1748]
**Describe the bug**
When handling some png file, vips_region_fetch failed with message 'pngload: non-recoverable state'.  It fails ONLY in 8.10 win64, while it works fine in 8.9.2 [win64.]

**To Reproduce**
use this png file:
![03060](https://user-images.githubusercontent.com/38777031/88798968-58223780-d1d8-11ea-87e8-07e0eebc80f8.PNG)

vips_image_new_from_file
vips_region_new
vips_region_fetch

**Environment**
 - OS:  Win10 Home
 - Vips: 8.10rc

**Comment by jcupitt** [comment]
Hello @xiaoguzhu,

Thanks for testing rc1. This looks like an issue with libspng, I think:

```
$ vips copy ~/pics/axe.png x.jpg
pngload: non-recoverable state
``` 

I'll pass the bug report on.

**Comment by jcupitt** [comment]
OK, libspng have fixed this and rc2 should have the fix. Thanks again for the report.
