### ISSUE TITLE
Creating new images

### ISSUE THREAD

**Issue by Zeranoe** [libvips/libvips#1751]
I'm attempting to use libvips to do some image filtering, and I'm wondering the best way to create a new image and populate it with data? I'm using the C++ interface, and logically I was thinking I could create a new image by specifying the width, height, and format, which allocates a buffer of some kind that allows me to modify values at any x/y position.

After some testing it appears it isn't this easy, and I believe this is due to the way libvips works with memory. So far I've looked at:
* Creating an "image" with a `std::vector<unsigned char>` and populating the `VImage` with `new_from_memory()`
  * I believe I need to manage the memory, which I really need to avoid
* Creating an `std::vector<unsigned char>` image and using the C API `vips_image_new_from_memory_copy()`
  * I'd like to avoid using the C API in a C++ setting
* Creating an `std::vector<unsigned char>` image, using `new_from_memory()`, and then leveraging the copy constructor to "duplicate" the image into a libvips managed image, and finally freeing the vector image
  * Awkward
* Since I'm creating an mask, copy the input image, clear the contents, change the format, and begin processing
  * Logically awkward

I'm essentially trying to implement a function like `VImage& createMask(const VImage& in, const int& param)`

**Comment by jcupitt** [comment]
Hello @Zeranoe,

You can make an image from a C++ array with `new_from_memory`. I'd make the array in any way you like, then wrap a `VImage` around it afterwards.

You can get libvips to allocate the memory and then write to it, but it's not very pretty. libvips images are shared and cached, so they need to be immutable. If you modify them without vips knowing, bad things can happen.

**Comment by jcupitt** [comment]
To free the memory, use `g_signal_connect` to link to the `postclose` signal on the image.

**Comment by Zeranoe** [comment]
I will proceed with using `new_from_memory`, and will look into `g_signal_connect` to offload the management.

It seems to me like this would be a common task, so I'm curious why the C++ API doesn't implement a template function for this that sets the signal too? If it's something that hasn't been implemented yet but would be a good idea, I would be happy to create a pull request for it.

**Comment by jcupitt** [comment]
Sure, please PR away. I'd call it `new_from_memory_steal`, since it would "steal" ownership of the pointer from the caller. This is convention used elsewhere in glib and libvips.

**Comment by Zeranoe** [comment]
Sounds good, I'll work on that and close this.
