### ISSUE TITLE
[Bug report with solution] error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by huskier** [libvips/libvips#1752]
**When I try to compile the libvips from the source code, I've encountered the following error:**
parallel-tests: installing './test-driver'
libvips/Makefile.am:77: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
............
./configure: line 3659: syntax error near unexpected token `1.30.0'
./configure: line 3659: `GOBJECT_INTROSPECTION_CHECK(1.30.0)'

**I've gotten a solution from the following link:**
https://github.com/thestinger/vte-ng/issues/4

**The solution is:**
clone https://github.com/GNOME/gobject-introspection and look for the m4/ directory, where the instrospection.m4 file is. Copy that file to vte-ng/m4 directory and tun the autogen.sh again.

**Comment by jcupitt** [comment]
Hello @huskier,

Thanks for the report. I tried here with git master libvips:

```
tar xf ../vips-8.10.0.tar.gz 
cd vips-8.10.0/
CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --prefix=/home/john/vips
make
make install
```

And it seems to work fine. How did you trigger this error? Did you perhaps run autogen.sh rather than configure?

**Comment by huskier** [comment]
@jcupitt Yes, the bug is triggered when I run autogen.sh rather than configure.

Actually, there is no "condigure" file in the gitcloned package, and only autogen.sh is available.

**Comment by jcupitt** [comment]
Yes, you need to have gobject-introspection installed to be able to run `autogen.sh`. The official tarball releases include a pre-built `configure`.

**Comment by huskier** [comment]
Thanks for your explanation.

**Comment by pauky** [comment]
If you use centos, it should be `gobject-introspection-devel`.
