### ISSUE TITLE
Recombining spot colors

### ISSUE THREAD

**Issue by ademmler** [libvips/libvips#1760]
Hi there,

lets say I have a preseparated image having CMYK+1 Spotcolor.
The spotcoler has a "alternate color space description" as CMYK values as well.

Example:   
Spotcolor Name = HKS5
Replacement Color: C =0, M=30, Y=100, K=0

How would I recombine this channel into the cmyk image ...

**Comment by jcupitt** [comment]
Hello @ademmler,

I guess this is an extra layer that's printed after CMYK, is that right? Has it been half-toned? You'd probably just do:

```python
merged = spot_layer.ifthenelse(spot_colour, cmyk_layers)
```

But we'd need some sample files to check. How are the spot colours encoded? In `IMAGE_DESCRIPTION`?

**Comment by ademmler** [comment]
Hello jcupitt,

Yes you are right, it is a halftone plane. Attached sample data and a out.tiff showing what the final result should be. How can I set the "color" of this layer?

[Device_N_test.zip](https://github.com/libvips/libvips/files/5016014/Device_N_test.zip)

thx for your response

**Comment by jcupitt** [comment]
This seems to work:

```python
#!/usr/bin/python3

import pyvips

def load(filename):
    return pyvips.Image.new_from_file(filename, access="sequential")

# these have 0-255 for no-ink to full-ink
c = load("p-000001-Cyan.tif")
m = load("p-000001-Magenta.tif")
y = load("p-000001-Yellow.tif")
k = load("p-000001-Black.tif")

# so we need to invert to change to ink density
cmyk_layers = c.bandjoin([m, y, k]).invert().copy(interpretation="cmyk")

# the extra layer
x = load("p-000001-HKS 05.tif")

# this extra layer also has 0 for full ink, 255 for no ink, so again, we 
# must invert
spot_layer = load("p-000001-HKS 05.tif").invert()

# the colour of the overprint in cmyk percentages, taken from colors.txt 
spot_colour = [
        255 * 0,
        255 * 0.431373,
        255 * 0.988235,
        255 * 0
]

merged = spot_layer.ifthenelse(spot_colour, cmyk_layers)

merged.write_to_file("x.tif")
```

**Comment by ademmler** [comment]
Hi,

thx for the working example - I need to see how this has to be in C++.
I forgot to mention this in the beginning.

**Comment by ademmler** [comment]
HI there,

I corrected my sample code. When I compile I get still 2 errors. What do I need to do?

g++ -g -Wall -o out test.cpp `pkg-config vips-cpp --cflags --libs`

test.cpp:17:23: error: use of undeclared identifier 'bandjoin'
        VImage cmyk_layers = bandjoin(c, m, y, k).invert().copy(VImage::option(...
                             ^
test.cpp:30:18: error: use of undeclared identifier 'spot_layer'
        VImage merged = spot_layer.ifthenelse(spot_colour, cmyk_layers);


#include <stdlib.h>
#include <vips/vips8>

using namespace vips;

int
main( int argc, char **argv )
{
	//if( VIPS_INIT( argv[0] ) )
	//	vips_error_exit( NULL ); 
 
	VImage c = VImage::new_from_file("p-000001-Cyan.tif", VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
	VImage m = VImage::new_from_file("p-000001-Magenta.tif", VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
	VImage y = VImage::new_from_file("p-000001-Yellow.tif", VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
	VImage k = VImage::new_from_file("p-000001-Black.tif", VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
	
	VImage cmyk_layers = bandjoin(c, m, y, k).invert().copy(VImage::option()->set("interpretation", VIPS_INTERPRETATION_CMYK));
	
	cmyk_layers.write_to_file("cmyk.tif");
	
	float spot_colour[4] = {
        255 * 0,
        255 * 0.431373,
        255 * 0.988235,
        255 * 0
	};
	
	VImage spotlayer = VImage::new_from_file("p-000001-HKS 05.tif", VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL)).invert(); 
	
	VImage merged = spot_layer.ifthenelse(spot_colour, cmyk_layers);
	
	merged.write_to_file("merged.tif");
	
}

**Comment by jcupitt** [comment]
Try `VImage::bandjoin`, and `spotlayer`.

**Comment by jcupitt** [comment]
This seems to work:

```C++
#include <stdlib.h>
#include <vips/vips8>

using namespace vips;

int 
main( int argc, char **argv )
{       
        if(VIPS_INIT(argv[0]))
                vips_error_exit(NULL);  
   
        VImage c = VImage::new_from_file("p-000001-Cyan.tif", 
                VImage::option()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
        VImage m = VImage::new_from_file("p-000001-Magenta.tif", 
                VImage::option()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
        VImage y = VImage::new_from_file("p-000001-Yellow.tif", 
                VImage::option()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
        VImage k = VImage::new_from_file("p-000001-Black.tif", 
                VImage::option()->set ("access", VIPS_ACCESS_SEQUENTIAL)); 
        
        VImage cmyk_layers = c
                .bandjoin(y)
                .bandjoin(m)
                .bandjoin(k)
                .invert()
                .copy(VImage::option()
                        ->set("interpretation", VIPS_INTERPRETATION_CMYK));
        
        std::vector<double> spot_colour = {
                255 * 0,
                255 * 0.431373,
                255 * 0.988235,
                255 * 0
        };

        VImage spot_layer = VImage::new_from_file("p-000001-HKS 05.tif", 
                VImage::option()->set("access", VIPS_ACCESS_SEQUENTIAL));
        
        VImage merged = spot_layer
                .invert()
                .ifthenelse(spot_colour, cmyk_layers);

        merged.write_to_file("merged.tif");

        return 0;
}
```

**Comment by jcupitt** [comment]
(I edited and improved the code a couple of times, in case you just saw this on email)

**Comment by ademmler** [comment]
> (I edited and improved the code a couple of times, in case you just saw this on email)

Hi jcupitt,  

thx so much for helping me. I must have missed the emails. From time to time I come here to check news.
I appreciate your work very much.

Alexander

**Comment by ademmler** [comment]
Pls help me to get this work - thx.

**Comment by jcupitt** [comment]
I copy-pasted the code and tried:

```
g++ -g -Wall x.cpp `pkg-config vips-cpp --cflags --libs`
```

And it compiles cleanly for me. Perhaps you are using an old C++ compiler that does not support `{}` initialization?

**Comment by jcupitt** [comment]
If you don't have a c++11 compiler, you can write eg.;

```C++
        VImage cmyk[4] = {c, m, y, k};
        std::vector<VImage> vec_cmyk(cmyk, cmyk + 4); 
        VImage cmyk_layers = VImage::bandjoin(vec_cmyk)
                .invert()
```

**Comment by ademmler** [comment]
Hi, thx so much. 

I think I have an C++11 compiler with Xcode on board.
Mac OS X 10.14.6 is my OS.

g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ademmler** [comment]
After testing I have to say that result and expectation differs.
I upload my code, sample files and two tiff for verification:

expectation.tiff = correct result
merged.tiff = result from vips

[recombine.zip](https://github.com/libvips/libvips/files/5069171/recombine.zip)

**Comment by jcupitt** [comment]
Is that the correct zip? That one does not have either of those files in.

**Comment by ademmler** [comment]
Sorry  - my mistake!!

out.tiff = correct result
merged.tif = result from vips

**Comment by jcupitt** [comment]
Ah OK. Those two files have the same pixels, but `out.tiff` has an ICC profile and `merged.tif` does not.

`out.tiff` has some XMP as well, I don't know if that's important.

**Comment by jcupitt** [comment]
You can attach an ICC profile like this:

```C++
                .invert()
                .copy(VImage::option()
                        ->set("interpretation", VIPS_INTERPRETATION_CMYK));

        char *contents;
        size_t length;
        if(!g_file_get_contents(
                "/usr/share/color/icc/colord/FOGRA27L_coated.icc", 
                &contents, &length, NULL))
                throw -1;
        cmyk_layers.set(VIPS_META_ICC_NAME,
                (VipsCallbackFn) g_free, contents, length);
```

You might want something more C++-ish than `g_file_get_contents`.

**Comment by ademmler** [comment]
Hi jcupitt,

thx for telling me - this is nice to know.
What I was trying to point out is, that the "black shadow" above the orange filed is missing and I don‘t know why?
The pixels in the black plane are there - they should be multiplied to the orange to simulate the overprinting.

Reds Alexander

**Comment by ademmler** [comment]
???

**Comment by jcupitt** [comment]
It was the weekend.

I hadn't noticed that the K layer was not masked. Is this to do with the order in which the layers are printed? Are they printed as C, M, Y, spot, K?
