### ISSUE TITLE
how can I get an image with round corners using libvips?

### ISSUE THREAD

**Issue by 781545872** [libvips/libvips#1763]

**Comment by jcupitt** [comment]
Hello,

There's a simple example here: https://github.com/libvips/ruby-vips/issues/228#issuecomment-608972136

**Comment by 781545872** [comment]
Thank you very much!I'll try it.

**Comment by jcupitt** [comment]
It depends a bit on exactly what you want to do. Post a specific example if you need more detail.

**Comment by 781545872** [comment]
Can you give me a C example?

**Comment by jcupitt** [comment]
Here's a rounded crop in ruby:

```ruby
#!/usr/bin/ruby

require 'vips'

image = Vips::Image.new_from_file ARGV[0], access: :sequential

radius = 50
rect = Vips::Image.new_from_buffer %(
  <svg viewBox="0 0 #{image.width} #{image.height}">
    <rect rx="#{radius}" ry="#{radius}" 
     x="0" y="0" width="#{image.width}" height="#{image.height}" 
     fill="#fff"/>
  </svg>
), ""

image = image.bandjoin rect[3]
image.write_to_file ARGV[1]
```

Run like this:

```
$ ./rounded_crop.rb ~/pics/bambi.png x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/89420677-f65b5380-d72a-11ea-97cb-c443bb5984e8.png)

**Comment by jcupitt** [comment]
In C:

```C
/* compile with:
 *
 *   gcc -g -Wall rounded_crop.c `pkg-config vips --cflags --libs`
 *
 */

#include <vips/vips.h>

int
main(int argc, char **argv)
{
	VipsImage *image;
	char *svg;
	VipsImage *alpha;
	VipsImage *x;

	if(VIPS_INIT(argv[0]))
		vips_error_exit(NULL);

	if(!(image = vips_image_new_from_file(argv[1],
		"access", VIPS_ACCESS_SEQUENTIAL,
		NULL)))
		vips_error_exit(NULL);

	svg = g_strdup_printf(
		"<svg viewBox=\"0 0 %1$d %2$d\"> "
		  "<rect rx=\"%3$d\" ry=\"%3$d\" "
		    "x=\"0\" y=\"0\" width=\"%1$d\" height=\"%2$d\" "
		    "fill=\"#fff\"/> "
		"</svg>",
		image->Xsize, image->Ysize, 50);
	if(!(alpha = vips_image_new_from_buffer(svg, strlen(svg), "", NULL))) {
		g_object_unref(image);
		g_free(svg);
		vips_error_exit(NULL);
	}
	g_free(svg);

	/* Get the alpha from the SVG image.
	 */
	if(vips_extract_band(alpha, &x, 3, NULL)) {
		g_object_unref(image);
		g_object_unref(alpha);
		vips_error_exit(NULL);
	}
	g_object_unref(alpha);
	alpha = x;

	/* Join to the main image.
	 */
	if(vips_bandjoin2(image, alpha, &x, NULL)) {
		g_object_unref(image);
		g_object_unref(alpha);
		vips_error_exit(NULL);
	}
	g_object_unref(alpha);
	g_object_unref(image);
	image = x;

	if(vips_image_write_to_file(image, argv[2], NULL)) {
		g_object_unref(image);
		vips_error_exit(NULL);
	}
	g_object_unref(image);

	return 0;
}
```

**Comment by jcupitt** [comment]
You could make it quite a bit quicker by drawing a single circle, cutting it into 4, and just pasting that at the corners. It would be more work, of course.

**Comment by 781545872** [comment]
When I run the example, I got `VipsForeignLoad: buffer is not in a known format`.
It's correct to run your computer?
My vips version is:
`[root@eac941ad75c8 data]# vips -v
vips-8.9.2-Sun Jun 14 11:36:25 UTC 2020`

**Comment by jcupitt** [comment]
Perhaps your libvips has been built without SVG support?

Try:

```
$ vips svgload_buffer
load SVG with rsvg
usage:
   svgload_buffer buffer out [--option-name option-value ...]
where:
   buffer       - Buffer to load from, input VipsBlob
   out          - Output image, output VipsImage
optional arguments:
   dpi          - Render at this DPI, input gdouble
			default: 72
			min: 0.001, max: 100000
... etc.
```

**Comment by 781545872** [comment]
Yes,it's exactly the problem.I don't install librsvg in my computer.After I install it and rebuild libvips,I success to get result I want.Thank you very much.

**Comment by songjiayang** [comment]
@jcupitt  hi John ,  would you mind telling me how to get an image with inner circle,  example like:
The original image:
![image](https://user-images.githubusercontent.com/1459834/173353227-723f71e4-67a6-4ce3-903f-77daca08334a.png)

inner circle image:
![image](https://user-images.githubusercontent.com/1459834/173353354-f1df2a05-38e8-47c8-9b06-c3fbdbf19bcb.png)

**Comment by jcupitt** [comment]
@songjiayang something like:

```ruby
#!/usr/bin/ruby

require 'vips'

image = Vips::Image.new_from_file ARGV[0]

cx = image.width / 2
cy = image.height / 2
r = [cx, cy].min
mask = Vips::Image.svgload_buffer <<-EOS
<svg viewBox="0 0 #{image.width} #{image.height}">
    <circle cx="#{cx}" cy="#{cy}" r="#{r}" fill="#000" />
</svg>
EOS

# use the alpha from the svg as the alpha for our image
image.bandjoin(mask[3]).write_to_file(ARGV[1])
```

That assumes that the input image doesn't have an alpha, and that you want to write an image with an alpha (so write to eg. PNG). 

You could make it more flexible with maybe:

```ruby
if image.has_alpha?
  # extract the input alpha, combine with the mask we've just created,
  # reattach
  rgb = image[0..2]
  alpha = image[3]
  alpha &= mask[3]
  image = rgb.bandjoin(alpha)
else
  image = image.bandjoin(mask[3])
end

image.write_to_file(ARGV[1])
```

So if there's an alpha on the input image, that'll AND the two together.

**Comment by songjiayang** [comment]
>  It works, thank you so much.

**Comment by Hpsyche** [comment]
hello,jcupitt.

I tried this code.For PNG,it's work. But for JPEG,it seems that the corner background alwalys is black.
How can i get the white background?

**Comment by jcupitt** [comment]
It's making an RGBA image, so you need to flatten against white when you make the jpeg. Try `image.write_to_file(filename, background: 255)`.

**Comment by Hpsyche** [comment]
1. In C, it seems don't have parameters like `background ` in `vips_image_write_to_file`;
2. I try to add this code after `vips_bandjoin2`, but it won't work(even if the target output is PNG format).
```C
if (vips_embed(image, &x, 0, 0, image->Xsize, image->Ysize, "extend", VIPS_EXTEND_WHITE, NULL))
  {
    g_object_unref(image);
    vips_error_exit(NULL);
  }
```

**Comment by jcupitt** [comment]
`"background"` has type `VipsArrayDouble`, so in C you need eg.:

```C
VipsArrayDouble *background = vips_array_double_newv( 1, 255.0 );

if( vips_image_write_to_file( image, "out.jpg", "background", background, NULL ) ) 
    ....
vips_area_unref( VIPS_AREA( background ) );
```
