### ISSUE TITLE
Vips with C++ example code fails to open image from file. Documentation is not helpful.

### ISSUE THREAD

**Issue by ibrag474** [libvips/libvips#1764]
```C++
#include <vips/vips8>

using namespace vips;

int
main (int argc, char **argv)
{
  if (VIPS_INIT (argv[0]))
    vips_error_exit (NULL);

  if (argc != 3)
    vips_error_exit ("usage: %s input-file output-file", argv[0]);

  VImage in = VImage::new_from_file (argv[1],
    VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL));

  double avg = in.avg ();

  printf ("avg = %g\n", avg);
  printf ("width = %d\n", in.width ());

  in = VImage::new_from_file (argv[1],
    VImage::option ()->set ("access", VIPS_ACCESS_SEQUENTIAL));

  VImage out = in.embed (10, 10, 1000, 1000,
    VImage::option ()->
      set ("extend", "background")->
      set ("background", 128));

  out.write_to_file (argv[2]);

  vips_shutdown ();

  return (0);
}
```

As long as it can only output it run successfully or not, I cannot understand why it fails. I have the JPEG file in the same directory as project. I tried to replace `argv[1]` and `argv[2]` with the name of input and output files with no luck. Also, what is `argc` and `argv` where they come from? It is not documented too!

**Comment by jcupitt** [comment]
Hello @ibrag474,

`int main(int argc, char **argv){}` is what every command-line program uses for startup. For example, I can compile this code with:

```
$ g++ -g -Wall example.cc `pkg-config vips-cpp --cflags --libs`
```

And then run it like this:

```
$ ./a.out ~/pics/k2.jpg x.jpg
avg = 102.93
width = 1450
```

To read from `k2.jpg` and write to `x.jpg`.

**Comment by jcupitt** [comment]
We have new C++ docs for the upcoming 8.11 release:

https://libvips.github.io/libvips/API/8.11/cpp/index.html
