### ISSUE TITLE
Missing background optional argument for vips_jpegsave function

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1771]
Hi @jcupitt,

Looks like the `background` optional argument is not present for some reason in the documentation for `vips_jpegsave` [located here](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave).

I have been calling this function from C code and looks like the `background` optional argument is totally functional. Maybe you forgot to add it to the docs?

I'm doing something similar to this and the background argument it's working fine for me:

```c
vips_jpegsave(in, filename, "Q", q, "interlace", interlace, "strip", strip, "background", background_vips_array, NULL)
```

I think the same is happening for the other `vips_*save` functions.

**Comment by jcupitt** [comment]
Hi @jfcalvo,

Yes, there are various fields define in the loader base class which don't appear in the docs, eg.:

```
$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename [--option-name option-value ...]
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   Q            - Q factor, input gint
			default: 75
			min: 1, max: 100
   profile      - ICC profile to embed, input gchararray
   optimize-coding - Compute optimal Huffman coding tables, input gboolean
			default: false
   interlace    - Generate an interlaced (progressive) jpeg, input gboolean
			default: false
   trellis-quant - Apply trellis quantisation to each 8x8 block, input gboolean
			default: false
   overshoot-deringing - Apply overshooting to samples with extreme values, input gboolean
			default: false
   optimize-scans - Split spectrum of DCT coefficients into separate scans, input gboolean
			default: false
   quant-table  - Use predefined quantization table with given index, input gint
			default: 0
			min: 0, max: 8
   subsample-mode - Select chroma subsample operation mode, input VipsForeignJpegSubsample
			default: auto
			allowed: auto, on, off
   strip        - Strip all metadata from image, input gboolean
			default: false
   background   - Background value, input VipsArrayDouble
   page-height  - Set page height for multipage save, input gint
			default: 0
			min: 0, max: 10000000
```

They are documented here, though it's a bit skimpy:

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#VipsForeignLoad--access

**Comment by jcupitt** [comment]
For background specifically, it's used in the save base class if the image needs to be flattened before calling the actual saver. jpegsave has no code to handle it.

**Comment by jfcalvo** [comment]
Understood. I will take a look to https://libvips.github.io/libvips/API/current/VipsForeignSave.html#VipsForeignLoad--access for those attributes.

Thank you very much.
