### ISSUE TITLE
Vips::Error (VipsOperation: class "monochrome" not found ):

### ISSUE THREAD

**Issue by Piyush-Chaudhary** [libvips/libvips#1773]
Getting the error while viewing a page with  **monochrome: true** like 
`<%= image_tag Category.first.image.variant(resize_to_fit: [400, 400], monochrome: true) %>` and image is not displaying but if remove the  **monochrome: true** as 
`<%= image_tag Category.first.image.variant(resize_to_fit: [400, 400]) %>` everything seems fine.

**Comment by jcupitt** [comment]
Sorry, no idea. Is this Rails? You probably need to open an issue on the image_processing gem.

**Comment by jcupitt** [comment]
Or perhaps your image is very strange, or maybe you are using a very old version of libvips. Maybe it's been compiled incorrectly?

You need to give a lot more information.

**Comment by Piyush-Chaudhary** [comment]
Yes, it's rails. 
Okay, thanks, I'll ask on image_processing gem.
