### ISSUE TITLE
Error when installing vips8.10.0 for CentOS 6.9

### ISSUE THREAD

**Issue by gohkimnam** [libvips/libvips#1774]
**Describe the bug**
Trying to install vips8.10.0 but run into errors. please advise.

**To Reproduce**
extract tar file, ./configure and make install
- error: redefinition of typedef ‘VipsImage’
- error: redefinition of typedef ‘VipsRegion’

**Screenshots**
![image](https://user-images.githubusercontent.com/30908362/89856015-acf78200-dbca-11ea-85c1-b3ff3263af33.png)

**Environment**
 - OS: CentOS 6.9
 - Vips: 8.10.0

**Additional context**
Was trying to do npm install for create-strapi-app

**Comment by lovell** [comment]
The screenshot mentions 8.9.2 rather than 8.10.0. Perhaps you need to uninstall any old versions first from the paths mentioned in the error.

**Comment by jcupitt** [comment]
libvips is doing something like this:

```C
struct _A;
typedef struct _A A;
typedef struct _A A;
```

Which is fine in C++, but it seems some C compilers in some modes throw an error, I'm not sure exactly when. You have `-std=gnu99`, could that be triggering it?

Either way, we should perhaps remove the multiple typedefs for greater portability. 

If you change this code in `image.h`:

```C
typedef struct _VipsImage {
...
} VipsImage;
```

To:

```C
struct _VipsImage {
...
};
```

And the same in `region.h`, it might fix it. Could you test?

**Comment by jcupitt** [comment]
I removed the typedef redefinitions and git master libvips now builds cleanly on centos 6.9.

https://github.com/jcupitt/docker-builds/blob/master/libvips-centos6.9/Dockerfile

This change will be in 8.10.1, thank for reporting it!
