### ISSUE TITLE
Possible memory safety issue

### ISSUE THREAD

**Issue by axyz** [libvips/libvips#1776]
@jcupitt

Hi, this may be a bit of a shot in the the dark, but maybe there is something obvious that I may be missing.

Sometime ago I asked for help for a relatively simple function that reduces an image and make it appear on a light background changing its white parts. https://github.com/libvips/libvips/issues/973

It worked pretty well all this time but, after moving to kubernetes (possible differences in available memory and/or network conditions), it started behaving strangely. The output image gets mixed up with other unrelated images (possibly coming from other requests) or grey areas or even coloured noise.

Some examples:
![image](https://user-images.githubusercontent.com/412723/89908719-83505200-dbee-11ea-8957-5aa7a0ca4420.png)
![image](https://user-images.githubusercontent.com/412723/89908826-ad097900-dbee-11ea-9428-1844e601fe77.png)
![image](https://user-images.githubusercontent.com/412723/89908854-b561b400-dbee-11ea-8283-f241c84d4a53.png)

The C function is called by a go service and each request should live in its own isolated thread, while I'm definitely going to investigate more deeply about this assumption as well as possibly faulty cache issues, I thought it may be worth having another pair of eyes on the C part in case there is some obvious issue on how the objects are created and unreffed in the process.

current function code:
```c
static double PACKSHOT_GRAY_LEVEL = 246;
static double PACKSHOT_SCALE = 0.86;
static double PACKSHOT_WHITE_THRESHOLD = 250;
static double PACKSHOT_FEATHER_AMOUNT = 1;
static double PACKSHOT_OVERLAY[3] = {246.0, 246.0, 246.0};

static int
wof_generate_packshot(VipsImage **out, VipsImage *product) {

  VipsImage *base = vips_image_new();
  VipsImage **t = (VipsImage **) vips_object_local_array(VIPS_OBJECT(base), 6);
  VipsArrayDouble *overlayColor = vips_array_double_new(PACKSHOT_OVERLAY, 3);

  int width = product->Xsize;
  int height = product->Ysize;

  if (
    // resize product image in t[0]
    vips_resize( product, &t[0], PACKSHOT_SCALE, NULL ) ||

    // find pixels over PACKSHOT_WHITE_THRESHOLD and feather slightly ... JPG compression arifacts
    // will typically be in the 250-255 range
    //
    // bandand() ANDs all the tests together, ie. we find pixels where r AND g
    // AND b are all > PACKSHOT_WHITE_THRESHOLD
    vips_more_const1( t[0], &t[1],
                      PACKSHOT_WHITE_THRESHOLD,
                      NULL ) ||
    vips_bandand( t[1], &t[2], NULL ) ||
    vips_gaussblur( t[2], &t[3],
                    PACKSHOT_FEATHER_AMOUNT,
                    "precision", VIPS_PRECISION_INTEGER,
                    NULL ) ||

    // Make the new background, and blend with our product shot.
    !(t[4] = vips_image_new_from_image1( t[0], PACKSHOT_GRAY_LEVEL )) ||
    vips_ifthenelse( t[3], t[4], t[0], &t[5],
                     "blend", TRUE,
                     NULL ) ||

    // Expand outwards with the new background colour.
    vips_gravity( t[5], out,
                  VIPS_COMPASS_DIRECTION_CENTRE,
                  width,
                  height,
                  "extend", VIPS_EXTEND_BACKGROUND,
                  "background", overlayColor,
                  NULL )

  ) {
    g_object_unref(base);
    vips_area_unref((VipsArea *) overlayColor);
    return 1;
  }

  g_object_unref(base);
  vips_area_unref((VipsArea *) overlayColor);

  return 0;
}
```
my understanding is that `vips_object_local_array` will take care of unreffing all the elements when base is unreffed. Also the grey layer is create as a brand new image only based on the sizes of the original one, not sure what else may cause some kind of concurency and memory sharing issues here.

go wrapper:
```go
// CreatePackshot adds the packshot effect on a picture
func CreatePackshot(image []byte) ([]byte, error) {
	jpgImage, err := ensureJPEG(image)
	if err != nil {
		return nil, err
	}

	var out *C.VipsImage

	prod, err := toVipsImage(&jpgImage)
	if err != nil {
		return nil, err
	}

	error := C.wof_generate_packshot(&out, prod)
	defer C.g_object_unref(C.gpointer(prod))
	if error == 1 {
		return nil, catchVipsError()
	}

	buf, err := toBimgImage(out, 85)
	if err != nil {
		return nil, err
	}

	return buf, nil
}
```

Thanks for your help

**Comment by jcupitt** [comment]
Hi @axyz,

Wow that looks bad. Could it be filename aliasing? libvips can close and reopen files during processing to try to keep the number of file handles down, so if you replace or delete the file while it's executing, it'll become very confused.

**Comment by axyz** [comment]
@jcupitt the `product` image is never read from file, but always from a network response. The Vips images are always created using `vips_init_image1` with a bytes buffer:

```go
func vipsRead(buf []byte) (*C.VipsImage, error) {
	var image *C.VipsImage
	imageType := bimg.DetermineImageType(buf)

	if imageType == bimg.UNKNOWN {
		return nil, errors.New("Unsupported image format")
	}

	length := C.size_t(len(buf))
	imageBuf := unsafe.Pointer(&buf[0])

	err := C.vips_init_image1(imageBuf, length, C.int(imageType), &image)
	if err != 0 {
		return nil, catchVipsError()
	}

	return image, nil
}
```

**Comment by axyz** [comment]
sorry that was also a wrapper function:

```c
int
vips_init_image1(void *buf, size_t len, int imageType, VipsImage **out) {
  int code = 1;

  	if (imageType == JPEG) {
  		code = vips_jpegload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  	} else if (imageType == PNG) {
  		code = vips_pngload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  	} else if (imageType == WEBP) {
  		code = vips_webpload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  	} else if (imageType == TIFF) {
  		code = vips_tiffload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  #if (VIPS_MAJOR_VERSION >= 8)
  #if (VIPS_MINOR_VERSION >= 3)
  	} else if (imageType == GIF) {
  		code = vips_gifload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  	} else if (imageType == PDF) {
  		code = vips_pdfload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  	} else if (imageType == SVG) {
  		code = vips_svgload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  #endif
  	} else if (imageType == MAGICK) {
  		code = vips_magickload_buffer(buf, len, out, "access", VIPS_ACCESS_RANDOM, NULL);
  #endif
  	}

  	return code;
}
```

**Comment by jcupitt** [comment]
Ah OK. Then I think it must be a bimg issue -- something is being unreffed which should not be unreffed.

**Comment by axyz** [comment]
@jcupitt Do you have anything specific in mind that could cause this kind of errors assuming that files are not involved?

I'm trying to check the whole request flow to identify what functions from bimg are used and all the places where there is an interface between go and C code.

I will share here the flow as I identified it (omitting non relevant paths) as it may be easy for you to spot issues on the usage of vips itself. Hopefully the issue is on the go side or some trivial error with the usage of vips, otherwise it may be a dangerous bug in vips itself or the bimg bindings that would be worth investigating further.

I know that without a way to replicate the issue this is all quite difficult though.

 <details>
  <summary>Show request flow</summary>

read the source image from the response body and close the body Reader

```go
body, err := ioutil.ReadAll(rsp.Body)

rsp.Body.Close()
```

Create the packshot from body and save it to output

```go
output, err := tools.CreatePackshot(body)
```

returns the output in the response body

```go
rsp.Body = ioutil.NopCloser(bytes.NewReader(output))
```

## tools.CreatePackshot

```go
func CreatePackshot(image []byte) ([]byte, error) {
```

check if the image is a JPEG, if not convert to it

```go
jpgImage, err := ensureJPEG(image)
```

```go
func ensureJPEG(image []byte) ([]byte, error) {
	format := bimg.DetermineImageType(image)

	if format == bimg.JPEG {
		// nn case it as already a JPEG
		return image, nil
	}

	// ...
	// convert to JPEG
}
```

```go
// DetermineImageType determines the image type format (jpeg, png, webp or tiff)
func DetermineImageType(buf []byte) ImageType {
	return vipsImageType(buf)
}
```

```go
func vipsImageType(buf []byte) ImageType {
	if buf[0] == 0xFF && buf[1] == 0xD8 && buf[2] == 0xFF {
		return JPEG
	}
	// ...
	// oher formats
}
```

Declare a pointer to a `VipsImage` to save the output of the C function

```go
var out *C.VipsImage
```

Convert the jpeg image to a `VipsImage`

```go
prod, err := toVipsImage(&jpgImage)
```

```go
func toVipsImage(buf *[]byte) (*C.VipsImage, error) {
	if len(*buf) == 0 {
		return nil, errors.New("Image buffer is empty")
	}

	image, err := vipsRead(*buf)
	if err != nil {
		return nil, err
	}

	return image, nil
}
```

Call the C function to generate the packshot

```go
error := C.wof_generate_packshot(&out, prod)
defer C.g_object_unref(C.gpointer(prod))
if error == 1 {
	return nil, catchVipsError()
}
```

```go
func catchVipsError() error {
	s := C.GoString(C.vips_error_buffer())
	C.vips_error_clear()
	C.vips_thread_shutdown()
	return errors.New(s)
}
```

Convert back to `BimgImage` and returns

```go
buf, err := toBimgImage(out, 85)
if err != nil {
	return nil, err
}

return buf, nil
```

```go
func toBimgImage(image *C.VipsImage, quality int) ([]byte, error) {
	tmpImage, err := vipsPreSave(image)
	if err != nil {
		return nil, err
	}

	// When an image has an unsupported color space, vipsPreSave
	// returns the pointer of the image passed to it unmodified.
	// When this occurs, we must take care to not dereference the
	// original image a second time; we may otherwise erroneously
	// free the object twice.
	if tmpImage != image {
		defer C.g_object_unref(C.gpointer(tmpImage))
	}

	length := C.size_t(0)
	saveErr := C.int(0)
	interlace := C.int(0)
	qual := C.int(quality)
	strip := C.int(1)

	var ptr unsafe.Pointer
	defer C.free(ptr)
	saveErr = C.vips_jpegsave_bridge1(tmpImage, &ptr, &length, strip, qual, interlace)
	if int(saveErr) != 0 {
		return nil, catchVipsError()
	}

	buf := C.GoBytes(ptr, C.int(length))

	// Clean up
	C.g_free(C.gpointer(ptr))
	C.vips_error_clear()

	return buf, nil
}
```

```go
func vipsPreSave(image *C.VipsImage) (*C.VipsImage, error) {
	var outImage *C.VipsImage

	// Apply the proper colour space
	if vipsColourspaceIsSupported(image) {
		err := C.vips_colourspace_bridge1(image, &outImage, C.VIPS_INTERPRETATION_sRGB)
		if int(err) != 0 {
			return nil, catchVipsError()
		}
		defer C.g_object_unref(C.gpointer(image))
		image = outImage
	}

	return image, nil
}
```

```c
int
vips_colourspace_bridge1(VipsImage *in, VipsImage **out, VipsInterpretation space) {
	return vips_colourspace(in, out, space, NULL);
}
```

```c
int
vips_jpegsave_bridge1(VipsImage *in, void **buf, size_t *len, int strip, int quality, int
interlace) {
	return vips_jpegsave_buffer(in, buf, len,
		"strip", INT_TO_GBOOLEAN(strip),
		"Q", quality,
		"optimize_coding", TRUE,
		"interlace", INT_TO_GBOOLEAN(interlace),
		NULL
	);
}
```

## C.wof_generate_packshot

```c
static double PACKSHOT_GRAY_LEVEL = 246;
static double PACKSHOT_SCALE = 0.86;
static double PACKSHOT_WHITE_THRESHOLD = 250;
static double PACKSHOT_FEATHER_AMOUNT = 1;
static double PACKSHOT_OVERLAY[3] = {246.0, 246.0, 246.0};

static int
wof_generate_packshot(VipsImage **out, VipsImage *product) {

  VipsImage *base = vips_image_new();
  VipsImage **t = (VipsImage **) vips_object_local_array(VIPS_OBJECT(base), 6);
  VipsArrayDouble *overlayColor = vips_array_double_new(PACKSHOT_OVERLAY, 3);

  int width = product->Xsize;
  int height = product->Ysize;

  if (
    // resize product image in t[0]
    vips_resize( product, &t[0], PACKSHOT_SCALE, NULL ) ||

    // find pixels over PACKSHOT_WHITE_THRESHOLD and feather slightly ... JPG compression arifacts
    // will typically be in the 250-255 range
    //
    // bandand() ANDs all the tests together, ie. we find pixels where r AND g
    // AND b are all > PACKSHOT_WHITE_THRESHOLD
    vips_more_const1( t[0], &t[1],
                      PACKSHOT_WHITE_THRESHOLD,
                      NULL ) ||
    vips_bandand( t[1], &t[2], NULL ) ||
    vips_gaussblur( t[2], &t[3],
                    PACKSHOT_FEATHER_AMOUNT,
                    "precision", VIPS_PRECISION_INTEGER,
                    NULL ) ||

    // Make the new background, and blend with our product shot.
    !(t[4] = vips_image_new_from_image1( t[0], PACKSHOT_GRAY_LEVEL )) ||
    vips_ifthenelse( t[3], t[4], t[0], &t[5],
                     "blend", TRUE,
                     NULL ) ||

    // Expand outwards with the new background colour.
    vips_gravity( t[5], out,
                  VIPS_COMPASS_DIRECTION_CENTRE,
                  width,
                  height,
                  "extend", VIPS_EXTEND_BACKGROUND,
                  "background", overlayColor,
                  NULL )

  ) {
    g_object_unref(base);
    vips_area_unref((VipsArea *) overlayColor);
    return 1;
  }

  g_object_unref(base);
  vips_area_unref((VipsArea *) overlayColor);

  return 0;
}
```

</details>

**Comment by jcupitt** [comment]
I doubt if it's a bug in libvips -- it's used in very large and complex threaded systems like node without this kind of thing happening. Of course you never know.

With other bindings, the tricky part has been getting the host language GC to interact nicely with libvips reference counting. I don't know how bimg handles this, but it would be an obvious thing to check.

I've never used go before, but I had a quick try last night with git master bimg. I did:

```go
package main

import (
        "bimg"
        "os"
        "fmt"
)

func main() {
        buffer, err := bimg.Read("test.jpg")
        if err != nil {
                fmt.Fprintln(os.Stderr, err)
        }

        newImage, err := bimg.NewImage(buffer).Resize(800, 600)
        if err != nil {
                fmt.Fprintln(os.Stderr, err)
        }

        size, err := bimg.NewImage(newImage).Size()
        if size.Width == 800 && size.Height == 600 {
                fmt.Println("image size is valid")
        }

        bimg.Write("new.jpg", newImage)

}
```

Then:

```
go build leak.go
VIPS_LEAK=1 ./leak
```

And it seemed to work correctly. 

It'd be helpful to force the Go GC to run very aggressively, so excess unrefs are spotted at once. I found this:

https://golang.org/pkg/runtime/

But I'm not sure which one would be best. I'll keep digging.

If you could make a complete, runnable Go program containing your code, that would be very helpful.

**Comment by jcupitt** [comment]
@h2non, could I ask your opinion on this? Perhaps there's a problem with the way the extra C code is linking to bimg?

**Comment by axyz** [comment]
@jcupitt I creaed a minimal implementation that is as close as possible to the real service (using skipper for routing, getting original images from network and applying the filter using a loopback)

https://github.com/axyz/packshot-example

**Comment by jcupitt** [comment]
Thank you very much for the example -- I ran it and there are no obvious problems. 

I'll see if I can poke about inside it.

**Comment by axyz** [comment]
@jcupitt one possible issues may be that this pointer https://github.com/axyz/packshot-example/blob/master/tools/vips.go#L18 could be garbage collected and then passed via an unsafe pointer to `vips_init_image1`.

We are trying to force go to keep it alive as it may otherwise lead to this kind of unexpected behaviours. Unfortunately not having a way to reproduce the issue on the first place is hard to tell if that is actually the issue, but we added:

```go
defer runtime.KeepAlive(jpgImage)
```

and trying to figure out if we still have some (or less) cases after this change.

**Comment by axyz** [comment]
@jcupitt the garbage collection of that unsafe pointer seemed to be the issue. Maybe this may be of interest for @h2non and other go libraries using vips and/or for documentation purposes.

We haven't observed new corrupted images since the fix, I will close the ticket and in case reopen if we get new issues in the coming days.

Thanks for the great support as always.

**Comment by jcupitt** [comment]
I'm glad you found it -- those kind of errors are about the most difficult to track down.
