### ISSUE TITLE
vips8.10 libspng error "pngload: non-recoverable state" when converting png to jpeg

### ISSUE THREAD

**Issue by wppd** [libvips/libvips#1778]
hey john, just run some tests with libvips+libspng and encounter an error.

test file

[some.png.zip](https://github.com/libvips/libvips/files/5073363/some.png.zip)

```
vips --version
vips-8.10.0
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10

```
```
vipsheader -a some.png 
some.png: 1200x1200 uchar, 4 bands, srgb, pngload
width: 1200
height: 1200
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 2.83465
yres: 2.83465
filename: some.png
vips-loader: pngload
```

```
vips jpegsave some.png some.jpg
pngload: non-recoverable state
```

I run other normal pngs with vipsheader, they have 'xmp-data' but this one doesn't have. Didn't find any "xmp" related in libspng repository so I thought this might be related to libvips.

for your information:

it works with libvips 8.9.2 and the vipsheader result is totally different

```
vipsheader -a some.png 
some.png: 1200x1200 uchar, 4 bands, srgb, pngload
width: 1200
height: 1200
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: some.png
vips-loader: pngload
icc-profile-data: 560 bytes of binary data
xmp-data: 33539 bytes of binary data
```

**Comment by jcupitt** [comment]
Hi @wppd, thanks for the report.

Yes, I see this with git master libspng too, so it looks like a bug there. I'll open an issue on their repo.

**Comment by jcupitt** [comment]
It looks like this PNG has not coded the text chunks in the header correctly and that's broken image read.

The next libspng should have a workaround for this.
