### ISSUE TITLE
How to optimise compiled code?

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#1779]
I am compiling libvips on my own. I could not find any info about what optimisations are enabled by default and what can I enable to improve performance?

Currently I provide these flags while compiling. `CFLAGS="-O3 -march=broadwell -ffast-math -ftree-vectorize" CXXFLAGS="-O3 -march=broadwell -ffast-math -ftree-vectorize"`

Also any help on running libvips on ARM will also be appreciated.

**Comment by jcupitt** [comment]
Those sound reasonable. I suppose this is gcc?

`tree-vectorize` is enabled by default for `O3`. I'd be cautious about `fast-math` -- it can change the results of computation, and libvips has not been tested in this mode. Make sure you enable orc -- it will give a large speedup for many operations.

I've never tried building on ARM myself, but I know debian etc. ship on ARM, so I imagine it's straightforward.

**Comment by adityapatadia** [comment]
Yes, this is GCC. I suppose I just need to keep liborc installed to enable the orc optimisations?

I have been using fast-math since long time and it works great so far. I will try building for arm with `-march` switch. Does it use NEON instructions on ARM?

**Comment by jcupitt** [comment]
Yes, I think orc has a NEON backend, and I think gcc does as well. It might be worth testing.

**Comment by adityapatadia** [comment]
Okay, I will compile for ARM with `-march` switch.

**Comment by adityapatadia** [comment]
I was wondering if using LLVM instead of GCC will produce better code? Any experience or benchmarks?

**Comment by jcupitt** [comment]
I've not tried very recently, but they are generally pretty similar. gcc perhaps makes slightly faster code, llvm certainly complies much more quickly.
