### ISSUE TITLE
Are those functions public?

### ISSUE THREAD

**Issue by augustocdias** [libvips/libvips#1780]
Are the functions `vips_jpegload_source` and `vips_svgload_source` public? 
I'm including just `vips/vips.h` and I'm getting undefined symbol for them.

**Comment by jcupitt** [comment]
They are not public, though they could be. You're supposed to just use the wrapper, `vips_image_new_from_source()`.

Are you sure you need to call them directly?

**Comment by augustocdias** [comment]
No I don't need. I'm generating the rust bindings for the new api introduced in the version 8.9 and I was wondering if those were missing because for other formats they're present. Example: `vips_pngload_source` and `vips_csvload_source` are there.

**Comment by jcupitt** [comment]
Ah, OK. Yes, they are in the python and ruby and C++ APIs, for example. I'll add them to C.

I think we've talked about this before, but I would not wrap the C API. The C++ API, for example, is based on the gobject interface, not the C one.

**Comment by augustocdias** [comment]
Yeah. I'm aware. But then I'd have to learn how to use gobject whereas rust has a tool to generate everything by just providing the .h file.

**Comment by jcupitt** [comment]
Fair enough! I've added them to the public C API for 8.11.
