### ISSUE TITLE
Finding blob stats

### ISSUE THREAD

**Issue by Zeranoe** [libvips/libvips#1782]
I'm using libvips to label connected-components, and I'm curious about some of the wording in the docs. I currently have the image properly labeled, but I'm wondering how I can use this to find some stats about each blob.

The API states:

### vips_hist_find_indexed ()
> This operation is useful in conjunction with vips_labelregions(). You can use it to find the centre of gravity of blobs in an image, for example.

### vips_labelregions ()
> Use vips_hist_find_indexed() to (for example) find blob coordinates.

If I understand `vips_hist_find_indexed ()` correctly, it simply preforms an operation (normally sum) on all the points in the `in` image that correlate to the given `index` image region. In general, I'm trying to find the center (brightest sub-pixel location in the blob) of a labeled region within the image coordinate system, along with the blobs intensity (which I believe is just the result of `vips_hist_find_indexed ()`). I understand that some of this is probably out of the scope of libvips, but the wording for the API leads me to believe I'm missing some parts.

**Comment by jcupitt** [comment]
Hello @Zeranoe,

Average intensity of blobs should be easy -- take the histogram of the label image to find the number of pixels in each blob, use `hist_find_indexed` to find the sum of each blob, then divide.

The coordinates of the peak brightness in each blob would be harder. You could use `hist_find_indexed` to find the maximum value in each blob, then mask out just those pixels, then use `hist_find_indexed` again on an `xy` image to find the average position of the selected pixels.

**Comment by jcupitt** [comment]
If you just want the position of the max in one of the blobs, calling `maxpos` directly might be better.

**Comment by Zeranoe** [comment]
> You could use hist_find_indexed to find the maximum value in each blob, then mask out just those pixels,

This seems interesting, though could you elaborate a bit on how you could find the max in the blob using just `hist_find_indexed ()`? I believe you could use it to find the brightest blob in the overall image, but I'm missing how it could be used to find a max within the blob itself.

Do you have any insight on this?:
> Use vips_hist_find_indexed() to (for example) find blob coordinates.

I'm mainly confused with how you can go from a blob sum to an `xy`.

**Comment by jcupitt** [comment]
You make an xy image (a two-band image where each pixel stores it's coordinates) with `xyz`, then sum that for each blob. Divide by the number of pixels in each blob to get the average blob position. 

If you weight by pixel brightness, you'd get something like the centre of gravity for each blob.

**Comment by Zeranoe** [comment]
Thank you, that's enough for me to get started!
