### ISSUE TITLE
vipsthumbnail takes 14 seconds for one tiff file

### ISSUE THREAD

**Issue by tand826** [libvips/libvips#1784]
**Describe the bug**
`vipsthumbnail CMU-1.tiff` with libvips 8.10.0 takes 14 seconds to save its thumbnail while libvips 8.9.2 saves in 0.004sec.

**To Reproduce**
1. Use Image [CMU-1.tiff](https://data.cytomine.coop/open/openslide/generic-tiff/CMU-1.tiff) or [another one](https://data.cytomine.coop/open/uliege/earthworm-transv-posterior-to-clitellum-02.tiff) (both reproduce the bug)
2. Install libglib2.0-dev libexpat1-dev libtiff5-dev libjpeg62-turbo-dev libgsf-1-dev openslide-tools libpng-dev
3. Install vips8.10.0 from tarball 

<details>
<summary>stdout of "vips --vips-config"</summary>

native win32: no
native OS X: no
open files in binary mode: no
enable debug: no
enable deprecated library components: yes
enable docs with gtkdoc: no
gobject introspection: no
enable radiance support: yes
enable analyze support: yes
enable PPM support: yes
use fftw3 for FFT: no
Magick package: none
Magick API version: none
load with libMagick: no
save with libMagick: no
accelerate loops with orc: no
ICC profile support with lcms: no
file import with niftiio: no
file import with libheif: no
file import with OpenEXR: no
file import with OpenSlide: no
file import with matio: no
PDF import with PDFium: no
PDF import with poppler-glib: no
SVG import with librsvg-2.0: no
zlib: yes
file import with cfitsio: no
file import/export with libwebp: no
text rendering with pangoft2: no
file import/export with libspng: no
file import/export with libpng: yes (pkg-config libpng >= 1.2.9)
support 8bpp PNG quantisation: no
file import/export with libtiff: yes (pkg-config libtiff-4)
file import/export with giflib: no
file import/export with libjpeg: yes (pkg-config)
image pyramid export: yes
use libexif to load/save JPEG metadata: no

</details>

3. Run the command
```
vipsthumbnail CMU-1.tiff
```

**Expected behavior**
Saves thumbnail image data to disk in a moment.

**Actual behavior**
vipsthumbnail takes about 14 sec to save "tn_CMU-1.jpg". With "--vips-progress" argument, stdout is like below.
```
$ vipsthumbnail CMU-1.tiff --vips-progress
vipsthumbnail temp-21: 128 x 92 pixels, 36 threads, 128 x 128 tiles, 640 lines in buffer
vipsthumbnail temp-21: done in 14.4s
```

**Environment**
 - OS: Debian 10
 - Vips: 8.10.0

**Additional context**
- After reinstalling libvips8.9.2, vipsthumbnail worked perfectly.
- **tiles** are 128 x 128 with 8.10.0, but 128 x 16 with 8.9.2.
```
# with libvips8.9.2
$ vipsthumbnail CMU-1.tiff --vips-progress
vipsthumbnail temp-24: 128 x 92 pixels, 36 threads, 128 x 16 tiles, 640 lines in buffer
vipsthumbnail temp-24: done in 0.00452s 
```

- `pyvips.Image.thumbnail("CMU-1.tiff", 128)` finishes less than a second with both libvips8.10.0 and libvips8.9.2.
- `pyvips.Image.thumbnail("CMU-1.tiff", 128).jpegsave("thumb.jpg")` finishes in 14 second with libvips8.10.0.

**Comment by jcupitt** [comment]
You're right, the page-based pyramid detector was not working. It should be fixed now in 8.10 HEAD. This fix will be in 8.10.1. Would you be able to test the fix?

Thank you very much for reporting this!

**Comment by tand826** [comment]
@jcupitt Thank you for quick response!

I tested the fix and got stdout as below, and it worked perfectly!

```bash
$ vipsthumbnail CMU-1.tiff --vips-progress
vipsthumbnail temp-24: 128 x 92 pixels, 4 threads, 128 x 1 tiles, 128 lines in buffer
vipsthumbnail temp-24: done in 0.00283s          
memory: high-water mark 263.33 KB
```

Just in case, I used the Dockerfile like below.

```Dockerfile
FROM debian:stable

# dependencies
RUN apt update -y && apt install -y wget build-essential pkg-config libglib2.0-dev libexpat1-dev libtiff5-dev libjpeg62-turbo-dev libgsf-1-dev openslide-tools libpng-dev git autoconf gtk-doc-tools gobject-introspection gettext libtool

# build and install libvips
RUN git clone -b 8.10 https://github.com/libvips/libvips
RUN cd libvips && ./autogen.sh --prefix=/usr && CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --prefix=/usr --enable-debug && make && make install

# test vipsthumbnail
RUN wget https://data.cytomine.coop/open/openslide/generic-tiff/CMU-1.tiff -O /libvips/CMU-1.tiff
CMD vipsthumbnail /libvips/CMU-1.tiff --vips-progress
``` 

To test again, please save the code above as "Dockerfile" and run these commands.
```bash
docker build . -t libvips_test
docker run -it --rm libvips_test
```

Thanks again!

**Comment by jcupitt** [comment]
Great! Thank you for testing.
