### ISSUE TITLE
Compare whether the two graphs are the same?

### ISSUE THREAD

**Issue by xlievo** [libvips/libvips#1786]
How to compare two pictures at pixel level to get whether they are the same picture? thank you.

**Comment by xlievo** [comment]
Okay! #1201 has the answer.
Do vips_equal(), then vips_min() on that.

Now what if I want to get a different array of pixels?

**Comment by jcupitt** [comment]
Hello @xlievo,

Do you mean, find the pixels at which they differ?

**Comment by xlievo** [comment]
Yes, I guess it's a stupid question :)
It should be in the return result of the equal()

**Comment by jcupitt** [comment]
You can do something a little fancier. For example, spatial cielab. 

Convert the images to CIELAB, blur them, find the colour difference, then pick pixels which are over some threshold. In Python:

```python
def scielab(a, b):
    return a.dE76(b).gaussblur(5) > 10
```

**Comment by xlievo** [comment]
Thank you for your answer. It's great!

**Comment by sedubois** [comment]
I am a beginner with this great Vips library, trying to write a Ruby on Rails test that will fail when an image has changed. Can the spatial cielab test with threshold described above be used for this purpose?

I tried:

```ruby
require "vips" # using gem: ruby-vips
require "application_system_test_case"

class ScreenshotDiffTest < ApplicationSystemTestCase
  setup do
    a = Vips::Image.new_from_file "a.png"
    b = Vips::Image.new_from_file "b.png"
  end

  test "scielab" do
    diff = a.dE76(b).gaussblur(5) > 10
    assert_equal 0.0, diff.max
  end
end
```

Visually, when using the same file for a and b, `diff.write_to_file("diff.png")` results in an all black image; with different images, the same export will be mostly black except for white areas where there are differences. This seems logical. However the above test fails as, regardless of whether the same or different images are used, `diff.min` returns 0.0 and `diff.max` returns 255.0.

This however works:

```ruby
  test "pixel_equality" do
    assert_equal 255.0, (a == b).min
  end 
```

So that's a start. But I would be curious to get things to work with the other test.

**Comment by jcupitt** [comment]
Hi, the greater-than is making a bool image, with 0 for false and 255 for true, where true means "pixels differ by more than the threshold at this point".

You're looking for whole image difference, so you need to find the largest difference in the whole image and see if that passes the threshold. Something like:

```ruby
  test "scielab" do
    diff = a.dE76(b).gaussblur(5)
    diff.max > 10
  end
```

**Comment by sedubois** [comment]
Thanks! However for some reason, `diff.min` returns 0.0 and `diff.max` returns 255.0, both for identical and for different images. Therefore I don't manage to make any meaningful assertion to distinguish them.

```ruby
  test "a and b are the same (scielab)" do
    diff = a.dE76(b).gaussblur(5)
    puts diff.min # ==> prints 0.0 whether images are different or not
    puts diff.max # ==> prints 255.0 whether images are different or not
    assert_operator diff.max, :<=, 10 # ==> fails whether images are different or not
  end
```

I would expect `diff.min` and `diff.max` to return the same value when comparing an image against itself. However, in that case still `diff.min` still returns 0.0 and `diff.max` returns 255.0.

**Comment by jcupitt** [comment]
Something has gone badly wrong, you shouldn't get that result. Could you post a complete runnable program plus sample images so I can test here?

With this program:

```ruby
#!/usr/bin/ruby

require "vips"

def scielab(a, b)
  a.dE76(b).gaussblur(5)
end

a = Vips::Image.new_from_file(ARGV[0])
b = Vips::Image.new_from_file(ARGV[1])
diff = scielab(a, b)

puts "min scielab = #{diff.min}"
puts "max scielab = #{diff.max}"
puts "avg scielab = #{diff.avg}"
```

I see:

```
$ # different images
$ ./scielab.rb ~/pics/k2.jpg ~/pics/shark.jpg
min scielab = 0.8712942600250244
max scielab = 100.10624694824219
avg scielab = 48.43221705028996
$ # same image
$ ./scielab.rb ~/pics/k2.jpg ~/pics/k2.jpg
min scielab = 0.0
max scielab = 0.0
avg scielab = 0.0
$ # slightly different image
$ vips rotate ~/pics/k2.jpg x.jpg 0.1
$ ./scielab.rb ~/pics/k2.jpg x.jpg
min scielab = 0.0
max scielab = 35.6917724609375
avg scielab = 3.165092206827999
```

**Comment by sedubois** [comment]
[Here you'll find](https://github.com/sedubois/vips-scielab-demo) the script you provided with test images.

This is what I get with some PNG screenshot generated by my mac:
```
% ./scielab.rb a.png a.png
min scielab = 0.0
max scielab = 255.0
avg scielab = 127.5
```

The 3 values are not the same even though I use the same image twice. 

However the script works fine with the same image which has first been converted to JPG:
```
% ./scielab.rb a.jpg a.jpg          
min scielab = 0.0
max scielab = 0.0
avg scielab = 0.0
```

How to fix scielab to work with PNG images?

Tested on macOS 14.0 with Ruby 3.2.2 and ruby-vips 2.1.4.

PS: At first I couldn't understand why I was getting `require: cannot load such file -- vips (LoadError)` with the script you gave (and with the gem available on the system), until I realized that `/usr/bin/ruby` is my mac's old system Ruby and not the Homebrew-installed one which is first on the path. Fixed it by changing the start of the script to `#!/usr/bin/env ruby`.

**Comment by jcupitt** [comment]
Ah, ok, yes, you need to flatten out alpha before comparing colour. libvips treats images as big arrays of numbers and doesn't know about features like alpha -- it's just a convention that the final band might (or might not) be an alpha.

Try:

```ruby

a = Vips::Image.new_from_file(ARGV[0])
b = Vips::Image.new_from_file(ARGV[1])
a = a.flatten if a.has_alpha?
b = b.flatten if b.has_alpha?
diff = scielab(a, b)
```

**Comment by sedubois** [comment]
Thanks @jcupitt! That solves it. My understanding is that this doesn't detect differences in transparency, is there any way to detect that too? Out of curiosity as that's a need I don't have for now.

**Comment by jcupitt** [comment]
Sorry, I was sure I answered! It will detect transparency differences -- `flatten` is computing:

```
rgb' = rgb * a / 255
```

So it's like placing your rgba image over some black paper. It's probably what you want, but of course you can implement something else if it isn't.
