### ISSUE TITLE
vips_gaussblur call with small values for sigma is causing unexpected results

### ISSUE THREAD

**Issue by johntrunc** [libvips/libvips#1793]
Hi, not sure if this is a bug or not.

I'm executing calls to `vips_gaussblur`with a value of `0.5` and I'm receiving a black image after use `vips_jpegsave_buffer` for some reason. I'm doing the following:

```c
vips_gaussblur(in, out, 0.5, "precision", VIPS_PRECISION_APPROXIMATE, NULL);
```

In the documentation that is showed calling `vips gaussblur` I can see that the minimum value is `0,01`:

```
   sigma        - Sigma of Gaussian, input gdouble
			default: 1,5
			min: 0,01, max: 1000
```

When I'm using a value of `0.01` as sigma I'm getting even more strange results with this warning:

```
GLib-GObject-WARNING **: 15:12:41.923: value "-1" of type 'gint' is invalid or out of range for property 'width' of type 'gint'
```

Using a value of `0.6` is making everything works as expected.

What should be the minimum and maximum values for the sigma value? 

There is some different between calling `vips_gaussblur` from C and using the `vips gaussblur` command line?

I'm using vips-8.9.2 on MacOS 10.14.6 with the following image:

![fly](https://user-images.githubusercontent.com/70328146/91447151-a3337700-e878-11ea-900e-be9d88288870.jpg)

**Comment by jcupitt** [comment]
Hello @johntrunc,

I'd avoid approx mode, it doesn't work very well. Int mode should be fine, as long as you don't need extreme precision. `--vips-info` turns on some logging which can be useful:

```
$ vips gaussblur planes.jpg x.png 0.4 --vips-info
VIPS-INFO: 18:28:15.106: gaussblur mask width 1
VIPS-INFO: 18:28:15.107: vips_convi_intize: too inaccurate
VIPS-INFO: 18:28:15.107: convi: using C path
VIPS-INFO: 18:28:15.108: vips_convi_intize: too inaccurate
VIPS-INFO: 18:28:15.108: convi: using C path
```

At 0.4, it's generating a 1x1 mask, so you won't see any effect. Try lowering the minimum amplitude and the mask will grow:

```
$ vips gaussblur planes.jpg x.png 0.4 --min-ampl 0.01 --vips-info
VIPS-INFO: 18:31:09.342: gaussblur mask width 3
VIPS-INFO: 18:31:09.345: convi: using vector path
VIPS-INFO: 18:31:09.347: convi: using vector path
```

Though the blur will be very slight.

**Comment by johntrunc** [comment]
Thanks @jcupitt the `--vips-info` flag is very useful. I was a little bit confuse about the minimum 0,01 value in the documentation. Thanks for clarification.

**Comment by jcupitt** [comment]
I agree the warning is odd. 

I had a look and there was a problem in mask size calculation for small masks. It should be fixed in 8.10.1, thanks for the report!

**Comment by jcupitt** [comment]
(this change fixes the warning you were seeing re. width of -1, it won't make any difference to the blur)

**Comment by johntrunc** [comment]
Thanks John for the change. By the way I'm using `VIPS_PRECISION_APPROXIMATE` because the default (integer I guess) is pretty slow compared to the approximate version (taking sometimes seconds to do the blur). Is that expected?

**Comment by jcupitt** [comment]
gaussblur should be quick, especially if you have vector code generation enabled. I see:

```
$ /usr/bin/time -f %M:%e convert ~/pics/nina.jpg -blur 3x2 x.jpg 
582268:2.80
$ /usr/bin/time -f %M:%e vips gaussblur ~/pics/nina.jpg x.jpg 2 --precision float
51788:0.94
$ /usr/bin/time -f %M:%e vips gaussblur ~/pics/nina.jpg x.jpg 2 --precision approximate
48564:0.91
$ /usr/bin/time -f %M:%e vips gaussblur ~/pics/nina.jpg x.jpg 2 --vips-novector
49140:0.90
$ /usr/bin/time -f %M:%e vips gaussblur ~/pics/nina.jpg x.jpg 2 
49208:0.34
```

So imagemagick is 2.8s, the libvips int C path is 0.9s and with vector extensions enabled, 0.34s. It'll vary a lot with the size of the blur, of course.

**Comment by johntrunc** [comment]
John how can I know if vector extensions is enabled?

**Comment by jcupitt** [comment]
Try `vips --vips-config` at the CLI. You should see a line like:

```
accelerate loops with orc: yes
```

**Comment by jcupitt** [comment]
Oh, and `--vips-info` says too, of course.

```
$ vips gaussblur nina.jpg x.jpg 2 --vips-info
VIPS-INFO: 16:48:00.144: gaussblur mask width 7
VIPS-INFO: 16:48:00.150: convi: using vector path
VIPS-INFO: 16:48:00.153: convi: using vector path
```

**Comment by johntrunc** [comment]
I got some interesting results:

For some reason `vips --vips-config` is not working for me (the output is empty):

```sh
$ vips --vips-config
$
```

This is the vips version that I'm using:

```sh
$ vips --version
vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
```

For a sigma value of `2` it shows `convi: using vector path`:

```sh
$ time vips gaussblur example.jpeg output.jpeg 2 --vips-info
VIPS-INFO: 09:49:46.082: gaussblur mask width 7
VIPS-INFO: 09:49:46.090: convi: using vector path
VIPS-INFO: 09:49:46.093: convi: using vector path
vips gaussblur fixtures/example.jpeg output.jpeg 2 --vips-info  1,23s user 0,07s system 166% cpu 0,784 total
```

For a sigma value of `125` (It's a common value for my use case) I'm getting `convi: using C path` instead of `convi: using vector path` and taking 2 minutes and 45 seconds. Is that normal?:

```sh
$ time vips gaussblur example.jpeg output.jpeg 125 --vips-info
VIPS-INFO: 09:51:16.111: gaussblur mask width 449
VIPS-INFO: 09:51:16.118: convi: using C path
VIPS-INFO: 09:51:16.129: convi: using C path
vips gaussblur fixtures/example.jpeg output.jpeg 125 --vips-info  585,25s user 1,57s system 354% cpu 2:45,31 total
```

For a sigma value again of `125` but using `approximate` precision I don't get any information about `convi` but the result is much faster (5 seconds):

```sh
$ time vips gaussblur example.jpeg output.jpeg 125 --precision approximate --vips-info
VIPS-INFO: 09:57:32.540: gaussblur mask width 449
vips gaussblur fixtures/example.jpeg output.jpeg 125 --precision approximate   18,41s user 0,12s system 352% cpu 5,259 total
```

I have to say that the input image `example.jpeg` is big, this is the info that `vipsheader` gives to me:

```sh
$ vipsheader example.jpeg
example.jpeg: 7360x4912 uchar, 3 bands, srgb, jpegload
```

**Comment by jcupitt** [comment]
`--vips-config` is a libvips 8.10 feature, you'd need to update for that.

Wow, 125 is simply huge. Yes, the vector path only uses a 16-bit accumulator, so it can't do massive blurs without losing precicion and libvips will fall back to the C path. The approximate blur (it's a set of stacked block blurs) will perform much better in this case. If the results look OK, sure, carry on using it.

Very large blurs are usually fastest as a shrink followed by a zoom, perhaps `image.resize(0.1).resize(10)`. It might be worth benchmarking something like that.

**Comment by jcupitt** [comment]
I tried here on a large JPG image:

```
$ time vips gaussblur nina.jpg x.jpg 125
real	0m38.763s
$ time vips gaussblur nina.jpg x.jpg 125 --precision approximate
real	0m2.615s
09:22 $ time ( vips resize nina.jpg x.jpg 0.1 && vips resize x.jpg x2.jpg 10 )
real	0m0.748s
```

**Comment by johntrunc** [comment]
The `gaussblur` operation is not necessary here after the last resize?

> 09:22 $ time ( vips resize nina.jpg x.jpg 0.1 && vips resize x.jpg x2.jpg 10 )

**Comment by jcupitt** [comment]
No -- take a look at the file. You'll need to adjust the 10 and 0.1 to match your sigma 125, of course. It won't be exactly a gaussian blur, but it should be a reasonable approximation. By default, `resize` downsizes with lanczos3 and upsizes with cubic (I think?) so it should look smooth. You could try setting cubic for both if you notice artefacts.

**Comment by johntrunc** [comment]
Ok, thanks for the help John, really appreciate it. I will try to play with the resize and see if I can get good results with that.
