### ISSUE TITLE
configuration for jp2 export

### ISSUE THREAD

**Issue by rgritti** [libvips/libvips#1794]
Hi, I am trying to save an image in JP2 with `vips_magicksave_buffer`.
I use the function in this way:
```
jp2save(VipsImage *in, void **buf, size_t *len) {
	return vips_magicksave_buffer(in, buf, len,
		"format", format,
                "quality", 85,
		NULL
	);
}
```
After fixing the library dependencies, I don't get any error, but the resulting image is 8 times bigger than the JPG it started from. Am I missing something?

**Comment by rgritti** [comment]
While testing I discover the same behaviour from command-line:
```
user:~/Downloads$ opj_compress -i test.png -o openjpg.jp2

[INFO] tile number 1 / 1
[INFO] Generated outfile openjpg.jp2
encode time: 1218 ms 

user:~/Downloads$ vips magicksave test.png vips.jp2 --format JP2

-rw-r--r-- 1 rgritti domänen-benutzer 3922790 Aug 28 16:52 test.png
-rw-r--r-- 1 rgritti domänen-benutzer 2890092 Aug 28 17:03 openjpg.jp2
-rw-r--r-- 1 rgritti domänen-benutzer 9305320 Aug 28 17:03 vips.jp2
```
vips creates a much bigger file.

**Comment by jcupitt** [comment]
Hi @rgritti,

You could try `file vips.jp2` at the command-line, it should confirm what format the file was written in.

jp2k is a very complex file format with multiple modes. There are probably a range of switches that need to be set the right way before you can write a jp2 file in a useful way. Writing via imagemagick will sort-of work, but a proper jp2k write operation would be much better.

Are you forced to use jp2k? If you are just looking for something better than JPG, then mozjpeg, HEIC or AVIF are all better choices than jp2k.

**Comment by rgritti** [comment]
Hi, thanks for the quick reply.
```
user:~/Downloads$ file vips.jp2
vips.jp2: JPEG 2000 Part 1 (JP2)
```

Yes, I have to export files in jp2k for safari/apple devices.

**Comment by jcupitt** [comment]
Yes, it looks like it's writing a jp2k file, just not very well, heh.

You could try changing `--quality` for `magicksave`, it might help reduce the size.

Would HEIC work for Safari/Apple? It's `vips heifsave` at the CLI, if you'd like to test it.

**Comment by rgritti** [comment]
Not really, but I discovered that they will support webP from the next version, so I will just support webP.

Thanks a lot!
