### ISSUE TITLE
Orientation wrong when creating JPEG out of HEIC

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1796]
Hello @jcupitt, me again :)

**Describe the bug**
When I try to create a jpeg version out of the HEIC image, I get for most of the Portrait images taken by the iPhone a landscape jpeg image...

**To Reproduce**
1. Use Image attached HEIC image
2. I use following arguments: 
--eprofile=srgb --iprofile=srgb --size=4096x3024 19de8241-7b11-4824-8ebb-63ebb36fb9db.heic -o a603ccf0-2b8f-44bf-842d-787d51dc0f5f_output.jpg[optimize_coding]
3. I also tried this arguments:
--eprofile=srgb --iprofile=srgb --size=3024x4032 9e0feb35-281e-42d3-a25a-2deb6f6bde47.heic -o 12ab45c3-97f6-4d8b-b042-3f72ad1d128c_output.jpg[optimize_coding]
4. And also these arguments:
 --eprofile=srgb --iprofile=srgb --size=4096x3024 80d5e6fe-29ea-4264-a88f-260e87181b09.heic[autorotate] -o a3394835-8dda-411a-82f7-180a0c71ac8b_output.jpg[optimize_coding]

5. See error
Image is landscape, when opening it on the computer

**Expected behavior**
I would expect to have also a portrait image...

**Actual behavior**
I get a landscape image,
Can you send me the proper arguments to get the correct format JPEG version out of this HEIC image?

**Environment**
(please complete the following information)
 - OS: [Ubuntu 18]
 - Vips: [8.9]

[IMG_2521.HEIC.zip](https://github.com/libvips/libvips/files/5145247/IMG_2521.HEIC.zip)

Thank you very much for looking into it.

**Comment by jcupitt** [comment]
Hi @daverupp,

It seems to work for me. I see:

```
$ vipsheader IMG_2521.HEIC
IMG_2521.HEIC: 3024x4032 uchar, 3 bands, srgb, heifload
$ vips copy IMG_2521.HEIC x.jpg
$ vipsheader x.jpg 
x.jpg: 3024x4032 uchar, 3 bands, srgb, jpegload
```

So it's portrait everywhere. What version of libvips are you using, and what commands are you running?

**Comment by jcupitt** [comment]
Oh, libvips 8.9. Try the current version.

**Comment by daverupp** [comment]
@jcupitt , wow that was super fast :)
Ok, will do, i saw a former post, that version 8.10 respects all orientations... 

Will check to get the latest version on our ubuntu. thx for answering...

**Comment by daverupp** [comment]
So I don't have to use any --rotate or [autorotate] flags in the arguments with the latest version?

**Comment by jcupitt** [comment]
`vipsthumbnail` has had autorotate on by default for a while now.

We reworked autorotate as part of 8.10 and we had to make autorotate always on everywhere for HEIC to fix some other bugs. The read library does not really support disabling autorotate.

**Comment by daverupp** [comment]
So actually to create just a copy of the HEIC to JPEG I should not use vipsthumbnail... instead just vips ?

**Comment by jcupitt** [comment]
Do you want to convert the image from HEIC to JPG? Yes, just use `copy`.

`vipsthumbnail` is designed to resize images.

**Comment by daverupp** [comment]
ahhh that I think was my mistake from the beginning :D .. thx a lot

**Comment by daverupp** [comment]
So I am using now:
Starting process /home/vcap/app/vips copy 0053d999-0bac-4bdb-96d1-b0ec989774a4.heic 9e825bad-11a2-49e9-80df-750c91a26864_output.jpg

Still landscape image... so, I check with updating to version 8.10? should have this already worked with version 8.9 ?

**Comment by jcupitt** [comment]
No, 8.10 has all the fixes for autorot and HEIC images.
