### ISSUE TITLE
vipsthumbnail problem with alpha transparent png

### ISSUE THREAD

**Issue by tobsn** [libvips/libvips#18]
if I convert alpha transparent pngs to jpeg they look very interesting... from png to png works but it loses the transparency.

examples (480px):
Original: https://dl.dropbox.com/u/1656816/vips/Opera-icon-high-res.png
PNG: https://dl.dropbox.com/u/1656816/vips/thumb.png
JPEG: https://dl.dropbox.com/u/1656816/vips/thumb.jpeg

it seems like the transparency in the png is still there but it gets displayed with a gray background under OSX.

**Comment by franklinwise** [comment]
I don't understand that being expected behavior.  How do I preserve the transparency?

**Comment by jcupitt** [comment]
Hi @franklinwise, this is if you thumbnail to a jpg image (the default). Jpeg does not support transparency, so you need to flatten it out with a background.

If you thumbnail to something like png, which does support transparency, it'll be kept. 

```
vipsthumbnail file.png --format %s.png
```

**Comment by franklinwise** [comment]
@jcupitt - Awesome, thanks. I didn't realize that jpeg was the default.

**Comment by shilpi230** [comment]
I have 7.42.2 I am also having same issue and i am converting from png to jpeg only how can i preserve the transparency ?

**Comment by shilpi230** [comment]
And this doesn't seem to work  ```vipsthumbnail rtd-img.png -o x.jpg[background=255]``` with me.

**Comment by shilpi230** [comment]
never mind it works i was using zsh and i had to give it inside quote Thank u :)
