### ISSUE TITLE
About dependency-reduced shared libraries

### ISSUE THREAD

**Issue by CL-Jeremy** [libvips/libvips#1802]
Hi,
I recently noticed that, with the release of 8.10.0, the two shared libraries in `libvips-8.10.0-linux-x64.tar.br` are largely linked statically. The resulting file is then quite portable for distribution online.

I'm interested in the build process. You certainly aren't specifying each of them with `-l` manually, are you? I'd be very grateful if you could share the script, if that doesn't involve too much work. I have both the latest Ubuntu and Fedora installed if that matters. Thanks in advance.

**Comment by jcupitt** [comment]
Hi @CL-Jeremy,

We don't distribute any linux binaries. Which files do you mean? Is this part of sharp?

**Comment by lovell** [comment]
@CL-Jeremy Please see https://github.com/lovell/sharp-libvips
