### ISSUE TITLE
Adding libRAW / RAW support to libvips

### ISSUE THREAD

**Issue by tru** [libvips/libvips#1804]
Hello,

We are evaluating vips for our project and we need to have support for RAW images (at least to read - we never output or do operations on the source file).

What would be the right way to integrate libRAW into libvips? Write a new foreign load function? Could it be modelled around something already in there like jpeg or png support?

Would such integration be welcomed upstream or would it be better if we build a pipeline in code that would convert raw to tiff before pushing it into libvips?

Thanks for reading and responding in advance.

**Comment by jcupitt** [comment]
Sure, happy to add a libraw reader. I would model it on `csvload.c`. Copy-paste that and strip out the CSV parsing and it's not too much code.

libvips can already read RAW via imagemagick. Try:

```
vips magickload panasonic.raw x.png
```

Though all IM does is shell out to `ufraw-batch` (I think).

libvips has it's own shell out system, so you can also use something like (untested):

```python
image = pyvips.Image.system(f"ufraw-batch --output=%s --out-type=ppm --out-depth=16 -i {filename}", out_format="%s.ppm")
```
