### ISSUE TITLE
Faster way to calculate shrink on load value

### ISSUE THREAD

**Issue by johntrunc** [libvips/libvips#1805]
Hi @jcupitt 

I have a question regarding the shrink scale on load for JPEG files. I'm doing something like this:

```c
vips_jpegload("example.jpeg", out, "shrink", shrink, NULL);
```

I'm working with big images where a desired width and height output is needed. So I'm using the shrink on load feature getting good performance results.

In order to calculate the value for `shrink` I need first to get the original width and height of the source image. I'm doing that loading first the image with `vips_image_new_from_file` and using `vips_image_get_width` and `vips_image_get_height` function to get these values. This double image "loading" process is slowing the performance for me.

It is possible to get these values without opening the file twice? Or there is an alternative way that can allow me to calculate the `shrink` value for a specific width and height indicated as output?.

Thanks.

**Comment by jcupitt** [comment]
Hi @johntrunc,

`new_from_file` is very quick -- all it does is read the header. Pixel decode is delayed until you do some processing. And the header decode is reused when you open the file a second time.

**Comment by johntrunc** [comment]
Ok, so I guess that first loading with `vips_image_new_from_file` to read headers and later do a second load with `vips_jpegload` and a calculated `shrink` value is fine. Thanks.
