### ISSUE TITLE
Affine + resize performance

### ISSUE THREAD

**Issue by kaas3000** [libvips/libvips#1810]
Hi,

I came across some libvips behaviour that I could not explain.

See the following python script (dependency: [affine](https://pypi.org/project/affine/)):

```python
import argparse
from math import ceil
from time import time

import pyvips
from affine import Affine
from pyvips import Image, Kernel

pyvips.cache_set_max(0)

parser = argparse.ArgumentParser()
parser.add_argument('filename')
args = parser.parse_args()

scale_x = 6.435381355932203
scale_y = 6.434928631402183
rotation = 34.051919898386

data_img = Image.new_from_file(args.filename)
if data_img.bands == 3:
    data_img = data_img.bandjoin(0)
photo_data = data_img.cast('uchar').write_to_memory()


def transform_image(early_resize: bool):
    bands = 4
    img_format = 'uchar'

    photo_width = data_img.width
    photo_height = data_img.height
    graphic_width = ceil(data_img.width * scale_x)
    graphic_height = ceil(data_img.height * scale_y)

    vips_img = Image.new_from_memory(photo_data, photo_width, photo_height, bands, img_format)

    # Resize operation
    resize_kernel = Kernel.LANCZOS3 if (scale_x <= 1 or scale_y <= 1) else Kernel.MITCHELL
    vips_img = vips_img.resize(scale_x, kernel=resize_kernel, vscale=scale_y)

    if early_resize:
        # Force doing the resize before running affine()
        vips_img = Image.new_from_memory(vips_img.write_to_memory(), vips_img.width, vips_img.height, bands, img_format)

    # Affine transform
    affine_transform = Affine.identity()
    affine_transform = affine_transform.rotation(rotation)
    vips_transform_matrix = (affine_transform.a, affine_transform.b, affine_transform.d, affine_transform.e)
    vips_img = vips_img.premultiply().affine(
        vips_transform_matrix,
        oarea=[0, 0, int(round(graphic_width)), int(round(graphic_height))],
        idx=-int(round(vips_img.width / 2)),
        idy=-int(round(vips_img.height / 2)),
        odx=int(round(graphic_width / 2)),
        ody=int(round(graphic_height / 2)),
    ).unpremultiply()

    # Write to memory to actually do the affine transform
    vips_img.write_to_memory()
    vips_img.write_to_file('out.png')


if __name__ == '__main__':
    start_time = time()
    transform_image(True)
    print('With early resize took %f' % (time() - start_time))

    start_time = time()
    transform_image(False)
    print('Without early resize took %f' % (time() - start_time))
```

This script loads an image, resizes it and rotates it before writing the result to `out.png`.

An example of the terminal output looks like:
```
$ vips --version
vips-8.10.1-Fri Sep  4 11:40:49 UTC 2020

$ python test.py drop.jpg 
With early resize took 11.640619
Without early resize took 30.298763
```

The question that I have is this: why is it so much faster to do the resize seperate from from the affine operation?

Thanks for all that you do!
Kees

**Comment by jcupitt** [comment]
Hi @kaas3000,

It's because you're computing everything twice. When you run:

```
    vips_img.write_to_memory()
    vips_img.write_to_file('out.png')
```

The first one will render the whole pipeline to a huge memory area then throw the memory area away, and the second will run the whole pipeline again, but this time render to a PNG file.

The `early_resize` branch is effectively caching the resize, so the second render is just doing the rotate.

`copy_memory` is useful for things like this. This allocates a large memory area, renders the image to that, wraps the memory area up as an image, and copies over all metadata from the pipeline. Use it as eg.:

```python
    new_image = image.copy_memory()
```

Try that in your `if early_resize`, and use it at the end with eg.:

```
    vips_img = vips_image.copy_memory()
    vips_img.write_to_file('out.png')
```

You can also do the resize and rotate in one step with affine. For example:

```
    vips_image = vips_img.premultiply().similarity(scale=scale_x, angle=rotation).unpremultiply()
```

It should be much quicker.

**Comment by kaas3000** [comment]
Thanks for the quick response @jcupitt.

I didn't know that `copy_memory()` would copy the metadata from the pipeline.

There are still some things unclear to me. 
If I understand you correctly, the most inefficient part of the script is rendering to png after rendering to memory.
When the script is modified to only render to memory, the difference in performance remains however. 
When you run the pipeline once, it shouldn't matter whether the resize operation is "cached" right?
```
$ python test.py drop.jpg 
With early resize took 6.767382
Without early resize took 18.568072
```


Furthermore, the similarity function does not accept a resize kernel as far as I know. Unless you know a way to keep the speed of `similarity()` with the visual improvements that the resize kernels supply?

**Comment by jcupitt** [comment]
You can give similarity and affine an interpolator. It's bilinear by default, but there are other options:

```
$ vips -l interpolate
  VipsInterpolate (interpolate), VIPS interpolators
    VipsInterpolateNearest (nearest), nearest-neighbour interpolation
    VipsInterpolateBilinear (bilinear), bilinear interpolation
    VipsInterpolateBicubic (bicubic), bicubic interpolation (Catmull-Rom)
    VipsInterpolateLbb (lbb), reduced halo bicubic
    VipsInterpolateNohalo (nohalo), edge sharpening resampler with halo reduction
    VipsInterpolateVsqbs (vsqbs), B-Splines with antialiasing smoothing
```

**Comment by jcupitt** [comment]
I think you've found a bizarre bug. I made a smaller test program:

```python3
#!/usr/bin/python3

from math import sin, cos, radians
import sys
import pyvips

img = pyvips.Image.new_from_file(sys.argv[1])
img = pyvips.Image.new_from_memory(img.write_to_memory(),
    img.width, img.height, img.bands, img.format)

img = img.resize(2) 

rotation = 35
vips_transform_matrix = (
        cos(radians(rotation)), -sin(radians(rotation)),
        sin(radians(rotation)),  cos(radians(rotation))
    )
img = img.affine(vips_transform_matrix)

img.write_to_memory()
```

If I run with `VIPS_PROGRESS` set you can see some info about the loops it's executing:

```
$ VIPS_PROGRESS=1 ./affine.py ~/pics/x.jpg
affine.py /home/john/pics/x.jpg: 1024 x 768 pixels, 8 threads, 1024 x 16 tiles, 256 lines in buffer
affine.py /home/john/pics/x.jpg: done in 0.00471s          
affine.py temp-40: 2559 x 2433 pixels, 8 threads, 2559 x 16 tiles, 256 lines in buffer
affine.py temp-40: done in 5.39s    
```

(trimmed slightly for clarity)

The first loop is loading from the JPG file into memory. It's loading 16 scanlines at a time, and it looks reasonable. 

The second loop is the resize plus affine. It's rendering this again in 16 scanline chunks -- this is causing massive overcomputation, since the resize has to run repeatedly.

If I change the `write_to_memory` / `new_from_memory` to be:

```python3
img = img.copy_memory()
```

I now see:

```
$ VIPS_PROGRESS=1 ./affine.py ~/pics/x.jpg
affine.py /home/john/pics/x.jpg: 1024 x 768 pixels, 8 threads, 1024 x 16 tiles, 256 lines in buffer
affine.py /home/john/pics/x.jpg: done in 0.00477s          
affine.py temp-39: 2559 x 2433 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
affine.py temp-39: done in 0.23s   
```

Now it's using 128x128 tiles and it's about 25x faster.

Summary: don't use `write_to_memory` / `new_from_memory`, just use `copy_memory()` instead.

I'll see if I can find out why w-to-m is making it pick the wrong tile size.

**Comment by jcupitt** [comment]
I changed the hint rules for tile size and it now behaves sensibly. With your code, I see:

```
$ ./resize-affine.py ~/pics/babe.jpg
With early resize took 3.509785
Without early resize took 5.823474
```

This change will be in 8.10.2. Thanks for pointing this dumbness out!

I'd still use `copy_memory()` rather than `write_to_memory` / `new_from_memory`.

You can do the upsize and rotate in one step like this:

```python
#!/usr/bin/python3

import argparse
from math import ceil, sin, cos, radians
from time import time
import pyvips

parser = argparse.ArgumentParser()
parser.add_argument('filename')
args = parser.parse_args()

scale_x = 6.435381355932203
scale_y = 6.434928631402183
rotation = 34.051919898386

def transform_image(data, width, height):
    bands = 4
    img = pyvips.Image.new_from_memory(data, width, height, bands, 'uchar')

    # interpolator ... there are other options, see `vips -l interpolate`
    interp = pyvips.Interpolate.new('bicubic')

    img = img \
        .premultiply() \
        .similarity(scale=scale_x, angle=rotation, interpolate=interp) \
        .unpremultiply()

    return img.write_to_memory(), img.width, img.height

if __name__ == '__main__':
    img = pyvips.Image.new_from_file(args.filename, access='sequential')
    if img.bands == 3:
        img = img.bandjoin(0)

    start_time = time()
    (new_data, new_width, new_height) = transform_image(img.write_to_memory(), 
            img.width, img.height)
    print('took %f' % (time() - start_time))
```

**Comment by kaas3000** [comment]
It's astonishing to see how quickly and detailed you always are with your answers @jcupitt!
Even this bug is fixed immediately.

I can't thank you enough.

Kees
