### ISSUE TITLE
libvips-42.dll was not found

### ISSUE THREAD

**Issue by rajkumarks7** [libvips/libvips#1813]
**Describe the bug**
i am using the bimg for go but was getting file not found after building exe. the application by using the command go build . the error is "the code execution cannot proceed because libvips-42.dll was not found . Reinstalling the program may fix this problem".

i was also getting other errors that libglib-2.0-0.dll is missing from your computer.

but it was working fine when i am running in the same pc. 

**Environment**
(please complete the following information)
 - OS: windows 10
 - Vips: 8.10

**Comment by lovell** [comment]
I don't think bimg supports Windows - see https://github.com/h2non/bimg/issues/334 or ask at that repo instead.

**Comment by rajkumarks7** [comment]
i think it is working. i am able to use it in my ide with windows10 but when i build a exe using the golang getting the error.
