### ISSUE TITLE
Convert a .eps or .ai file with transparent background to a .png file. 

### ISSUE THREAD

**Issue by labSupport** [libvips/libvips#1816]
How can i preserve transparency when i convert a .ai or .eps vector image with transparent background to a .png image.

**Comment by jcupitt** [comment]
Hello @labSupport,

libvips uses imagemagick to load these files, so it depends how imagemagick handles transparency. Perhaps you could convert to SVG? libvips has a very fast and well-tested SVG loader.

**Comment by labSupport** [comment]
Thank you. I tried to load the vector files with `vips_magickload()` and it worked. The transparent background is preserved.

**Comment by jcupitt** [comment]
OK, I'm glad it's working.
