### ISSUE TITLE
iiif tiling - incorrect image dimensions output to info.json file

### ISSUE THREAD

**Issue by Linden6** [libvips/libvips#1818]
When viewing iiif files created with:
`vips dzsave in.jpg out --layout iiif --tile-size 512 --suffix ".jpg[Q=90]"`
at smaller zoom levels OpenSeadragon sometimes requests edge tiles that don't exist.  However, unlike issue #1621 the problem is not with the size of the tiles generated, but with the 'width' and 'height' values output to the associated 'info.json' file.  They are sometimes too large by a pixel.

For example when converting this image:
[https://upload.wikimedia.org/wikipedia/commons/d/d7/Giovanni_Bellini_-_Saint_Francis_in_the_Desert_-_Google_Art_Project.jpg](https://upload.wikimedia.org/wikipedia/commons/d/d7/Giovanni_Bellini_-_Saint_Francis_in_the_Desert_-_Google_Art_Project.jpg)
the original size is 30,000 × 26,319 pixels, but the dimensions output to the generated 'info.json' file are .
  "width": 30000,
  "height": 26320
When fully zoomed out the tiles along the bottom edge are missing:
![Grimshot 2020-09-16 17-57-32](https://user-images.githubusercontent.com/43049925/93368797-570b9f00-f846-11ea-9549-a80dd95de42d.png)
After manually editing the 'info.json' file with the correct dimensions, the file renders perfectly:
![Grimshot 2020-09-16 18-00-51](https://user-images.githubusercontent.com/43049925/93369025-ab168380-f846-11ea-844b-217843dbbd6d.png)
This problem doesn't arise for all images.  This file, for example, presented no problems:
[https://upload.wikimedia.org/wikipedia/commons/5/50/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg](https://upload.wikimedia.org/wikipedia/commons/5/50/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg)
Its dimensions are 30,000 × 21,952 - both even numbers.

It would appear, therefore, that the issue may arise from a rounding error.

Thanks.
[vips-8.10.1 compiled on Linux 5.7.0-2-amd64]

**Comment by jcupitt** [comment]
Huh how weird, I'll have a look. Thanks for the report!

(I love that painting btw)

**Comment by jcupitt** [comment]
Yes, it was setting the wrong width and height. dzsave keeps (many) versions of each layer with different amouts of padding. It was using the dimensions of the version that it padded to an even number of scanlines ready for the x2 downsize (if that makes sense). If this extra pixel of padding crossed a tile boundary, that edge tile could drop.

Thank you very much for reporting this, the fix will be in 8.10.2 and credited to you.

**Comment by Linden6** [comment]
That's great.  Many thanks!

**Comment by danmichaelo** [comment]
Thanks a lot to both of you! I ran into the same problem, and was so glad to find that the problem had already been identified and fixed! Tried compiling the latest source, and can confirm that the fix is working 🎉

**Comment by qudratullah1061** [comment]
Great. Really helped.
