### ISSUE TITLE
How to limit number of colors in image

### ISSUE THREAD

**Issue by Lustmored** [libvips/libvips#1822]
I am trying to help with downstream support of libvips in PHP intervention library. I had no problems implementing all of its functionality using VIPS but one:

http://image.intervention.io/api/limitColors
> Method converts the existing colors of the current image into a color table with a given maximum count of colors. The function preserves as much alpha channel information as possible and blends transparent pixels against a optional matte color.

I have read VIPS function list many times now and see no way to implement limitColors in efficient way so need a bit of help.

What functions and in what way shall I use to achieve it? Code snip in any language would be very helpful.

Thanks,
Jakub

**Comment by jcupitt** [comment]
Hello @Lustmored,

Unlike imagemagick, libvips does not support indexed images -- all images are truecolor (to use imagemagick's term, I think). Instead, paletteization is built into the save operations. 

This makes maths on images much simpler (you don't need an extra path for indexed images), and it moves palettization closer to the operations where it is useful, so you can tune it for the image format.

For example:

```
vips pngsave x.jpg x.png --bitdepth 2
```

To write a four colour image, or:

```
vips pngsave x.jpg x.png --palette --Q 90 --bitdepth 4 --dither 0.5
```

To write a dithered 16 colour image, with the 16 colours chosen automatically. tiffsave has similar controls.

**Comment by Lustmored** [comment]
Thanks a lot @jcupitt!

With that information I was able to easily implement missing function.
