### ISSUE TITLE
"Hello world" link at Wiki Documentation page

### ISSUE THREAD

**Issue by AMurkin** [libvips/libvips#1826]
**Describe the bug**
Please fix the link to "Hello world" at [Wiki Documentation page](https://github.com/libvips/libvips/wiki/Documentation)
Text says: Various Hello World programs
Current link: https://github.com/Hello_World
It gives 404 github error page.

**To Reproduce**
1. Open [Wiki Documentation page](https://github.com/libvips/libvips/wiki/Documentation)
2. Click "Hello World" link in "Various Hello World programs" line
3. See 404 github error page

**Expected behavior**
I suppose it should be https://github.com/libvips/libvips/wiki/Hello-World

**Comment by jcupitt** [comment]
I fixed some of the links.

Anyone can edit the wiki, if you see any other broken links.

**Comment by jcupitt** [comment]
(and thanks for pointing this out!)
