### ISSUE TITLE
Increase tile size limit for tiled tiff.

### ISSUE THREAD

**Issue by antoinegerardin** [libvips/libvips#1830]
tiffsave currently limits tile size to 1024x1024.
It would be great relax this limit to allow the creation of much larger tiles (say at least 8192x8192).
This would help us to fine tune our algorithms as we start to routinely process 100Kx100K images.
Thanks!

**Comment by jcupitt** [comment]
Hi @antoinegerardin,

Current libvips allows tiles up to 32768 I think, so you should be OK. Are you using an older version?

I would be cautious about making tiles that large -- I think you're likely to see massive memory use and probably less parallelism too. To write an image with 8k tiles, libvips would need 8192 * 2 * 100000 pixels of write buffer, so perhaps 5GB of memory just for the output buffering. Reading an image with tiles that large would need many, many GB as well.

Why do you need huge tiles? Perhaps there's another way of doing it. I regularly process 250k x 250k images on my laptop, though I expect you are doing something fancier.

**Comment by jcupitt** [comment]
I'll close. Please reopen if you still have issues.
