### ISSUE TITLE
Stop printing VIPS_WARNING messages to console

### ISSUE THREAD

**Issue by tonimelisma** [libvips/libvips#1835]
In seemingly minor issues, the library writes warning messages to the console. I am under the understanding that no library should ever write any messages to console as default behavior.

I am aware that as a workaround the user can set an environment variable VIPS_WARNING to suppress warnings.

I suggest that the library should default to providing all warnings and errors only via the API and only print to console when set to debug mode.

Please let me know if you are looking for a pull request to satisfy this requirement.

**Comment by jcupitt** [comment]
Hi @tonimelisma,

libvips doesn't print to the console. It uses the glib logging framework for warning messages, and the default glib log handler will send warnings to stderr. If an application that uses libvips wants to control warning messages, it can hook into the glib logging system and direct them somewhere else (or block them entirely).

All `VIPS_WARNING` does is:

```C
static void
empty_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
        const gchar *message, gpointer user_data )
{
}

...

        if( g_getenv( "VIPS_WARNING" ) )
                g_log_set_handler( G_LOG_DOMAIN, G_LOG_LEVEL_WARNING,
                        empty_log_handler, NULL );
```

ie. install an empty warning log handler for the VIPS domain.

**Comment by tonimelisma** [comment]
So the default is to print warnings on stderr? Can't this default be changed in libvips?

**Comment by jcupitt** [comment]
The glib logging framework, if you're curious:

https://developer.gnome.org/glib/unstable/glib-Message-Logging.html

**Comment by jcupitt** [comment]
Libraries should not really change logging settings -- that's supposed to be done at the application level. Imagine if you were an application writer and every library you started up made slightly different and incompatible changes to logging ... ugh!

We have tried to only emit warnings when there is a real warning condition (output is likely to be different from expected, or requests could not be exactly satisfied). If you come across any messages you think should not be there, do please say. There are probably some which are too chatty.

**Comment by tonimelisma** [comment]
Hey John - thanks for both the speedy replies as well as for great software. You're a hero!

So basically what you're saying is, glib logging is a logging framework which has defaults typical for an application (print warnings to stderr), not ones typical for a library (never print anything to stdout/stderr). Because libvips has chosen to use it for logging, you can't set a default of not printing to console because if the host application was also using glib logging itself and set different logging settings, libvips would then overwrite them?

And I guess there's no way to know if the host application is using glib logging and set proper settings? So, you know, as a solution, if the application hasn't changed any logging settings, the default when using libvips would be to not print anything to stderr?

A tricky situation. I guess there's a level of interpretation here but it still seems to me like this is the only library I know which by default prints anything to stderr.

My root issue is that I'm using libvips via bimg (the Go package) which doesn't provide any direct interface to set the glib logging settings. So all and all, I can't find any way to disable the warnings.

Naturally this could be fixed via better defaults in bimg but it seems like the project maintainers are swamped. Considering there's about a 100 open issues and 16 pull requests, each with no engagement from the primary maintainer, I fear that writing a patch would likely be wasted work.

**Comment by jcupitt** [comment]
I think it's something that bimg should set (it's the application layer here). It should redirect glib logging output to wherever is appropriate for a web server (it knows and libvips does not).

I agree bimg is in a difficult spot. It's become very popular and I think perhaps maintenance has outgrown the resources of the original developer. Someone in the community ought to step up and help. Perhaps a few of the commercial users could contribute an engineer-day a month? The bimg dev would have to buy in to this, of course.

The `VIPS_WARNING` env var is a horrible hack that we put in to let people disable these warnings if there's no application level support. You should be able to set it from go before bimg starts up, I'd think, or even from the thing that launches your server.

**Comment by lovell** [comment]
In Node.js land, sharp registers a warning handler:

https://github.com/lovell/sharp/blob/6ed1f49ad37105b728aab3256328e949b04bd76e/src/sharp.cc#L33-L34

...then places warning messages into a queue:

https://github.com/lovell/sharp/blob/00e65f6f14b837e2eb448a96e0dd2e9479533492/src/common.cc#L522-L525

These are exposed through a sharp instance as warning events:

```js
const output = await sharp(input)
  .resize(100)
  .on("warning", (msg) => { ... })
  .toBuffer();
```

I notice you've already opened a bimg issue for this at https://github.com/h2non/bimg/issues/355

**Comment by jcupitt** [comment]
Oh, that's a nice thing to have @lovell. Yes, I think something similar in bimg would be the best solution. Most web servers will have warning logs too, of course, which is where you'd probably expect them by default.

**Comment by jcupitt** [comment]
(@tonimelisma it's usually considered rude to cross-post issues. You are making volunteers who do this in their spare time and for fun do unnecessary extra work. It's better to ask once and only ask again somewhere else if you have to.)

**Comment by tonimelisma** [comment]
Apologies. To be honest how I'd appraise the situation I also considered this unwanted behavior from libvips (a library defaulting to print something to stderr).

The suggested solution looks nice. But as said, looks to me like a PR to bimg would most likely be time wasted as the PRs don't seem to mostly get merged.

In my case I'm creating a command-line utility (batch image transformation), not a web server. To add insult to injury, no, for some reason setting the environment variable within my go program (´os.Setenv("VIPS_WARNING", "FALSE")´) does nothing and I can't find any way to turn the console logging off, except perhaps packaging my app so it's run via a wrapper shell script that manipulates the environment instead of being run directly. Not exactly the correct solution.

**Comment by jcupitt** [comment]
That's bizarre, you'd think `os.Setenv()` would work.

It would need to happen before `vips_init()` is called. I would run in a debugger, put a break on `vips_init()`, and see what's triggering it. Perhaps Go is somehow starting libvips before you get a chance to run your code?

**Comment by tonimelisma** [comment]
It seems to do it automatically, there's nothing I can do in the code.

Apologies for sounding like a broken record, but can you clarify if my previous assumption was correct: libvips can't set its own default for the glib logging framework without potentially overwriting any settings set by the app? So the use of the glib logging framework restricts libvips for setting its own defaults in terms of whether it outputs something to stderr or not?

**Comment by jcupitt** [comment]
I don't know much about Go. I suppose you'd need to investigate how it does package init and if there's any way you can get in there first.

Yes, that's right, libvips uses the glib logging framework, and glib's default behaviour (not libvips!) is to print warnings to stderr. You can catch logging output and direct it somewhere else, of course, but that's something that needs to be done at the application level, not the library level.

If you can call C from your code, you could redirect glib, of course. It's just one function call. Is there a Go binding for glib?

**Comment by tonimelisma** [comment]
Thanks for the support John, and thanks again for great contribution to open source. I'll grit my teeth and look at submitting a PR to bimg, will close this issue. Hope you have a great weekend!

**Comment by jcupitt** [comment]
We could add some API, eg. `vips_disable_logging()`, which just set a NULL handler (exactly what `VIPS_WARNING` does), but that would still need to be wrapped by bimg before you could call it.

**Comment by tonimelisma** [comment]
FYI to anyone else looking into the same issue, I have replaced bimg with [govips](https://github.com/davidbyttow/govips) and today merged a PR fixing this issue there. Now all glib, libvips and govips messages are handled by govips.

So in case you are developing CLI apps, you have control into what gets printed to console, or if you're developing server backends, your server logs will not be full of messages you don't want there.
