### ISSUE TITLE
Building with pdfium warns incompatible pointer type

### ISSUE THREAD

**Issue by Projkt-James** [libvips/libvips#1837]
**Describe the bug**
When building with pdfium in an Amazon Linux 2 docker container the make step warns of incompatible point type for the pdfload functions but still successfully completes build.

**To Reproduce**
1. Download pdfium binaries from https://github.com/bblanchon/pdfium-binaries
2. ./configure --with-pdfium-includes=/path/to/pdfium --with-pdfium-libraries=/path/to/lib
3. make
(I can provide an example dockerfile if required)

**Expected behavior**
Build to complete without pointer warnings.

**Actual behavior**
Warnings printed at make step.

**Screenshots**
![image](https://user-images.githubusercontent.com/750541/94391106-0118ee80-0198-11eb-972e-20dd26282b65.png)

**Environment**
 - OS: Windows 10 (Docker Container [lambci/lambda](https://hub.docker.com/r/lambci/lambda/))
- Vips 8.9.1

**Comment by jcupitt** [comment]
Hello @Projkt-James,

Yes, pdfium build has been broken for a while -- libvips has not kept up with changes in pdfium. Some brave person needs to spend an afternoon fixing it.

In the meantime, you need to build against poppler.

**Comment by jcupitt** [comment]
There's an issue tracking this: https://github.com/libvips/libvips/issues/1400

I'll close this one.
