### ISSUE TITLE
.svs to .tiff conversion

### ISSUE THREAD

**Issue by dsuppes-htl** [libvips/libvips#1838]
We utilize Leica/Aperio AT2 scanners in-house for whole-slide scanning, and use Leica/Aperio's ImageScope program for viewing the .svs output from the scanners. We have a client that's looking to get a straight conversion from .svs to .tiff, but I'm struggling to make this work.

Every time I try a tiffsave operation, I get an error stating _32 bits per pixel images are not supported_ when I try to open the output file. I've tried an extract_band operation, and while I'm able to open the output file in ImageScope, it has numerous issues (image is pre-zoomed to 20% with no way to zoom out to the whole-slide view, label image is replace with a "banded" whole-slide image, thumbnail may or may not be present, etc.).

My initial starting point was this thread: https://github.com/libvips/libvips/issues/72

There were a few others that I dug through as well, but I can't seem to find the links now.

Any thoughts or suggestions?

**Comment by jcupitt** [comment]
Hello @dsuppes-htl,

Could you post a sample image from their scanner somewhere, and a sample TIFF showing the kind of file you need to create.

**Comment by jcupitt** [comment]
Oh, plus platform (win, linux, mac etc.), vips version, and how you made or downloaded the vips binary.

**Comment by dsuppes-htl** [comment]
I'm on Windows, running vips 8.10.1, that was downloaded from the [vips website](https://libvips.github.io/libvips/).

You can see a couple of samples [here](https://drive.google.com/drive/folders/1GYOdwPhjSOGsQ_knEd-aFNQNOsZ3gO5r?usp=sharing). The _Sample1.svs_ file is the default output from the scanner, the _Sample1a_ file is a raw .tif, and the _Sample1b_ file is an lzw .tif; these are the only .tif types the scanner can output. Of these two .tif formats, obviously the lzw .tif is more friendly size-wise, but I believe that my client would be perfectly fine with any sort of .tif format that looks/acts the same way as these do.

**Comment by jcupitt** [comment]
Do you know which libvips binary you downloaded? You'll need `vips-dev-w64-all-8.10.1.zip` for SVS support. The `-web` version will appear to work, but will not give the correct result.

I'll download your samples, thanks!

**Comment by dsuppes-htl** [comment]
I do have the `-all` vips version, not the the `-web` version.

**Comment by jcupitt** [comment]
I had a look with tiffinfo. `Sample1b.tif` contains 6 images:

1. 17927x16973 pixel RGB of the whole slide, LZW, tiled, plus a huge and mysterious ICC profile.
2. 819x768 pixel RGB of the whole slide, LZW, untiled, no profile
3. 4481x4198 pixel RGB, whole slide, LZW, tiled, no profile
4. 2240x2099 pixel RGB, whole slide, LZW, tiled, no profile
5. 671x641 pixel RGB, label image, LZW, untiled
6. 1600x643 pixel RGB, macro image, JPEG compression

The six images seem to be using the TIFF `ImageDescription` tag to describe their structure.

This is not a standard TIFF image, it's something Aperio use for their slide output. You'd need to do some development work to generate it yourself, and you'd probably need to get a spec from Aperio.

libvips can write standard pyramidal TIFFs with eg.:

```
vips copy Sample1.svs mypyramid.tif[pyramid,tile,compression=jpeg,Q=90,tile-width=240,tile-height=240] 
```

The svs file is compressed with jp2k, so I think it's OK to use high-quality JPEG. I see:

```
$ ls -l
total 2375720
-rw-rw-r-- 1 john john 155405627 Sep 30 14:48 mypyramid.tif
-rw-rw-r-- 1 john john 985938005 Sep 29 10:52 Sample1a.tif
-rw-rw-r-- 1 john john 537319985 Sep 29 10:52 Sample1b.tif
-rw-rw-r-- 1 john john  74042125 Sep 29 10:51 Sample1.svs
```

So it's about 2x the size of the SVS.

**Comment by dsuppes-htl** [comment]
I appreciate all the work you've put into this one John.

I tested the copy to pyramidal tiff line you posted, and I'm basically getting the same sort of thing I was when I was trying the extract_band command. The slide image is pre-zoomed to 20% with no way to zoom out (although zooming in seems to be fine), and it seems to replace the label image from the slide with the thumbnail.

I've dropped a quick screenshot of what I'm seeing in ImageScope in here so you can get an idea, and I uploaded the `Sample1pyramid.tif` output from libvips to the [sample folder](https://drive.google.com/drive/folders/1GYOdwPhjSOGsQ_knEd-aFNQNOsZ3gO5r?usp=sharing) I created previously.

Any thoughts on why it might be doing this pre-zoom thing?
![Capture](https://user-images.githubusercontent.com/68702010/94713972-b66ab400-0308-11eb-9603-3c9e473f0ac3.PNG)


For reference, here's a screenshot of what I see when I open the original .svs
![Capture1](https://user-images.githubusercontent.com/68702010/94713981-b9fe3b00-0308-11eb-81c5-79545bb23a4b.PNG)

**Comment by jcupitt** [comment]
It's because the Aperio TIFFs are non-standard -- they are expecting certain things in certain places, and strange non-standard sets of zoom levels. You'd need to do some development work to fix these problems.

**Comment by dsuppes-htl** [comment]
Gotcha, I guess I mis-understood that in your previous post.

As I said, thanks a ton for all the work, I'll pass all the pertinent info along to my client on this.

**Comment by 3Kims** [comment]
Hi hello, @dsuppes-htl , I am facing exact same problem, image corruption during straight conversion from .svs to .tiff and have not worked it out for 2 years.

Were you able to find solution for the conversion?

**Comment by jcupitt** [comment]
@3Kims This issue isn't about reading SVS, it's about how to write a TIFF that's compatible with the TIFFs written by the Aperio scanning software.

If you have a tricky SVS, open a discussion, post a sample, and I can have a look.

**Comment by VincePlantItAi** [comment]
will do, thanks alot!
