### ISSUE TITLE
vipsthumbnail: How to not upscale thumbnails againt original

### ISSUE THREAD

**Issue by jasomdotnet** [libvips/libvips#1841]
Hi,
first of all, I'm surprised with the speed `vips` process images (in comparison to PHP's `Imagick`). Great job!

This is my command:
```
parallel vipsthumbnail input.jpg --rotate --eprofile /usr/share/nip2/data/sRGB.icm --size {} -o %s-{}.jpg[profile=none,strip,optimize_coding] --vips-leak ::: 512x288 256x144 1440x1440 2560x2560
```
When I process, let's say 1920x1080 image, command upscale this image to 2560x1440. It's not desired. Please, how can I set to not upscale images above dimension of the input?

Documentation I found [here](https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html#thumbnail-size) is not clear to me:

> You can append < or > to mean only resize if the image is smaller or larger than the target. 

**Where** to append `<` or `>`? Which one to append?

In the case of `1920x1080` image I would like to end up with name of image `input-2560x2560.jpg` with real dimensions `1920x1080` or just no image.

**Comment by jcupitt** [comment]
Hi @jasomdotnet,

It's the same syntax as imagemagick, so:

```
$ vipsheader k2.jpg
k2.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
$ vipsthumbnail k2.jpg --size "4000x4000>"
$ vipsheader tn_k2.jpg 
tn_k2.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
```

**Comment by jasomdotnet** [comment]
I stared 2 minutes on your answer. I tried to compose something like this:
```
parallel vipsthumbnail 169_DSC_0796a.jpg --rotate --eprofile /usr/share/nip2/data/sRGB.icm --size {} -o %s-{}.jpg[profile=none,strip,optimize_coding] --vips-leak ::: "512x288>" "256x144>" "1440x1440>" "2560x2560>"
```
but it didn't work :D It still creates upscaled thumbnails with dimensions higher the source. Also my single thumbnail command did not work:
```
vipsthumbnail source.jpg --rotate --eprofile /usr/share/nip2/data/sRGB.icm --size="1440x1440>" -o source-1440x1440.jpg[profile=none,optimize_coding]  --vips-leak
```
What am I doing wrong? Do I need `vipsheader`? What is `vipsheader`?

**Comment by jcupitt** [comment]
Oh, vipsheader is just a handy thing to display image headers. You could use "identify" or "file" instead.

`--rotate` is deprecated now, I think, autorot is the default. libvips comes with a built-in high-quality srgb profile, so you can just use `--eprofile srgb`. 

I tried:

```
$ file astronauts.png 
astronauts.png: PNG image data, 900 x 900, 8-bit/color RGB, non-interlaced
$ vipsthumbnail astronauts.png --eprofile srgb --size="1440x1440>" -o source-1440x1440.jpg[profile=none,optimize_coding]  --vips-leak
memory: high-water mark 3.84 MB
$ file source-1440x1440.jpg 
source-1440x1440.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 900x900, components 3
```

So it's working for me. What libvips version are you using? I'm using current stable (8.10).

**Comment by jasomdotnet** [comment]
Yes, you right, I'm using non-actual version `libvips 8.4.5-Wed Jan 18 12:36:44 UTC 2017` (that one available for Ubuntu 18.04, my server, with command `apt-get install libvips-tools`).

I'm going to compile actual installation file. Thank you for now, you reactions were helpful for me.

**Comment by jasomdotnet** [comment]
So I ended up with compiled version `libvips 8.11.0-Wed Sep 30 17:28:28 UTC 2020` + bonus knowledge that something like `vipsheader` exist (I can use it as part of valid jpeg detection) and final commands:

**1. Parallel**
```
parallel vipsthumbnail source.jpg --eprofile srgb --size {} -o %s-{}.jpg[profile=none,strip,optimize_coding] ::: "512x288>" "256x144>" "1440x1440>" "2560x2560>"
```
**2. Single**
```
vipsthumbnail source.jpg --eprofile srgb --size="512x288>" -o thumbnail-512x288.jpg[interlace,profile=none,strip,optimize_coding]
...
vipsthumbnail source.jpg --eprofile srgb --size="2560x2560>" -o thumbnail-2560x2560.jpg[interlace,profile=none,optimize_coding]
```
and  Once again, thank you. After several days, my "jpeg epos" is going to final :D

If somebody finds this thread useful just like this comment as a feedback.

**Comment by jasomdotnet** [comment]
So I ended up with [compiled](https://github.com/libvips/libvips/wiki/Build-for-Ubuntu) version `libvips 8.11.0-Wed Sep 30 17:28:28 UTC 2020` + bonus knowledge that something like `vipsheader` exist (I can use it as part of valid jpeg detection) and final commands:

**1. Parallel**
```
parallel vipsthumbnail source.jpg --eprofile srgb --size {} -o %s-{}.jpg[profile=none,strip,optimize_coding] ::: "512x288>" "256x144>" "1440x1440>" "2560x2560>"
```
**2. Single**
```
vipsthumbnail source.jpg --eprofile srgb --size="512x288>" -o thumbnail-512x288.jpg[interlace,profile=none,strip,optimize_coding]
...
vipsthumbnail source.jpg --eprofile srgb --size="2560x2560>" -o thumbnail-2560x2560.jpg[interlace,profile=none,optimize_coding]
```
After several days, my "jpeg epos" is going to final :D

If somebody finds this thread useful just like this comment as a feedback.

**Comment by jcupitt** [comment]
Glad it's working!

But I wouldn't use 8.11, that's the development version and is not supported. I would stick to 8.10:

https://github.com/libvips/libvips/releases/tag/v8.10.1

**Comment by jasomdotnet** [comment]
All right, on production server I will compile vips against version 8.10.
