### ISSUE TITLE
How to generate an image from the command line?

### ISSUE THREAD

**Issue by TimotheeJeannin** [libvips/libvips#1842]
When I try to generate an image from the command line, it's always black.

![ok](https://user-images.githubusercontent.com/1969368/94780283-7ff46e00-03c8-11eb-8a30-8d5f7a0acc4a.jpeg)

Here is what I tried:

```
vips perlin ok.jpeg 50 50
vips eye ok.jpeg 50 50
vips gaussmat ok.jpeg 1 0,1
```
Is there anything wrong with my libvips installation? 
Am I using libvips incorrectly?

**Comment by jcupitt** [comment]
Hello @TimotheeJeannin,

They are making images outside the range that .jpg can represent. You can see what's happening if you use vips (.v) format:

```
$ vips perlin x.v 128 128
$ vips max x.v
0.206959
$ vips min x.v
0.000000
```

`perlin` has a switch (`--uchar`) to use 0-255 instead:

```
$ vips perlin x.jpg 256 256 --uchar --cell-size 16
```

To make:

![x](https://user-images.githubusercontent.com/580843/94781934-736d1700-03c2-11eb-9fd8-1637c1e8e15f.jpg)

**Comment by jcupitt** [comment]
For gaussmat, try using text output, eg.:

```
$ vips gaussmat x.csv 1 0.1
$ more x.csv 
0	2	3	2	0
2	7	12	7	2
3	12	20	12	3
2	7	12	7	2
0	2	3	2	0
```

**Comment by TimotheeJeannin** [comment]
Thank you for the quick answer! You're awesome! :smiley: 
And libvips is such a great library!
