### ISSUE TITLE
icc_transform: no input profile Error

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1843]
Ask a question...
Hello @jcupitt 
Maybe you know a hint how to solve this thumbnailing issue:

I try these settings:
`vipsthumbnail --rotate --eprofile=srgb --iprofile=srgb` 

on the attached image... 

and it is not working with following warning:
profile incompatible with image

The picture is a grayscale image... Do you know how we can avoid errors like this? Do I have to check first if it is grayscale and then use vipsthumbnail without profile arguments?

![testImage](https://user-images.githubusercontent.com/942990/94817407-41c57180-03fd-11eb-8b4d-e32b53a6cd5c.JPG)

Thank you again for any hints and help
cheers dave

Platform information
OS: [Ubuntu 18.04 LTS]
Vips: [8.10.1]

**Comment by jcupitt** [comment]
Hi @daverupp,

Yes, it's a mono image (not RGB) so you'd need a mono profile as the fallback.

You can just omit the `iprofile` and vipsthumbnail will pick something appropriate. `rotate` is the default as well. I would use:

```
vipsthumbnail mono.jpg --eprofile=srgb -o my-thumbnail.jpg[strip]
```

**Comment by daverupp** [comment]
@jcupitt  thx a lot.
Can I obmit in general the iprofile argument? vipsthumbnail will choose the appropriate one always?

**Comment by jcupitt** [comment]
Yes, libvips since 8.8 has supplied appropriate fallback profiles automatically. You only need iprofile for special cases -- eg. you somehow know that a JPG image is in Adobe98, but it has no embedded profile.

**Comment by daverupp** [comment]
Thanks a lot again for your super responsive help.
wish you a nice day

**Comment by jcupitt** [comment]
I've updated the docs to make this clearer.
