### ISSUE TITLE
Invalid heif images when image widthxheight has some odd value

### ISSUE THREAD

**Issue by jaume-pinyol** [libvips/libvips#1848]
**Describe the bug**
Hi,
I have a weird issue when generating heic image using libvips that has some odd number as width or height, like `615 x 461`. If both are pair everything works fine.

I've tried in different environment with vipsthumbnail and it happens the same in all of them.

**To Reproduce**
```bash
$ wget https://github.com/tigranbs/test-heic-images/raw/master/image1.heic
$ vipsthumbnail images/testdata/format/image1.heic  -s 760x461 -o ./image-1-test.heic --vips-progress
      vipsthumbnail temp-26: 615 x 461 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
      vipsthumbnail temp-26: done in 0.959s

$  heif-info images/testdata/format/image-1-test.heic 
     MIME type: image/heic
     image: 614x460 (id=1), primary
       color profile: rICC
       alpha channel: no
       depth channel: no
```
As you can see the output image from vips-thumbnail has `615 x 461` pixels but the heif-info says it has 614x460. And probably this is what make the image unprocessable. I don't know if the issue is with libheif or vips, I'm still investigating.

**Expected behavior**
A working image

**Actual behavior**
The image only work if the WidthxHeight are even values
```bash
$ vipsthumbnail images/testdata/format/image1.heic  -s 760x460 -o ./image-1-test.heic --vips-progress
   vipsthumbnail temp-26: 614 x 460 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer  
   vipsthumbnail temp-26: done in 0.957s          
$ heif-info images/testdata/format/image-1-test.heic 
   MIME type: image/heic
   image: 614x460 (id=1), primary
    color profile: rICC
    alpha channel: no
    depth channel: no
```
This image works fine, and can be shown.

**Environment**
I've tried in different environments:
- OS:
   * Ubuntu groovy build from source
   * Amazon linux 2 build from source
   * MacOs Catalina installed with brew
- Vips: 8.10.1
- LibHeif: 1.9.1
- Libde265: 1.0.7
- Libx265: 3.4

**Comment by jcupitt** [comment]
Hello @jaume-pinyol,

Thanks for the report. This is a known limitation of HEIC, see: https://github.com/strukturag/libheif/issues/191

You can see the problem like this:

```
$ vipsthumbnail image1.heic -s 760x461 -o x.v
$ vipsheader x.v
x.v: 615x461 uchar, 3 bands, srgb, heifload
```

So thumbnail is creating an image of the correct size. But when I save as HEIC:

```
$ vips copy x.v x.heic
$ vipsheader x.heic
x.heic: 614x460 uchar, 3 bands, srgb, heifload
```

It loses the bottom and right edges.

**Comment by jaume-pinyol** [comment]
hi, thanks for the fast response, and sorry to open a bug that is not a bug, so I'll close or feel free to close it ;)

I guess that the only solution I have is for now to round it to even numbers when resizing if the final width height will have an odd number.
