### ISSUE TITLE
Deleting file after open it with vips_image_new_from_file

### ISSUE THREAD

**Issue by johntrunc** [libvips/libvips#1849]
Hi,

I have notice that once that you create an image from a file using `vips_image_new_from_file` is not possible to delete that file because it is used in following steps and it should be there until the image is processed and output saved again.

Do we have any way to open the file with `vips_image_new_from_file` delete the file and continue processing that image so the original file is not used?

Thanks.

**Comment by jcupitt** [comment]
Hello @johntrunc,

I think this is only a problem on Windows -- other platforms let you delete open files. As a workaround, you can read to memory and then open from there, something like (untested):

```python
with open(filename, 'rb') as f:
    data = f.read()
image = pyvips.Image.new_from_buffer(data)
```

Of course, it'll probably be slower and need more memory.

**Comment by johntrunc** [comment]
Hi John, thanks for the quick response.

I'm using MacOS and if I do the following I get errors from vips:

1. Open a file with `vips_image_new_from_file`
2. Delete the original opened file.
3. Process the image in different ways.
4. Save the image with `vips_jpegsave`.

These errors are never happening if I don't delete the original file specified to `vips_image_new_from_file`.

**Comment by johntrunc** [comment]
Additionally the same thing is happening if instead of loading from file I use the `*__buffer` methods trying to read from a memory buffer (i.e. downloading from S3 and getting the info into a memory buffer instead of file). If I free the buffer from memory after getting an image using `vips_jpegload_buffer` I get errors decoding the jpeg that are only avoided if I don't free the buffer until finishing working with the image.

**Comment by jcupitt** [comment]
I suppose I'm not exactly sure what you're doing or what the precise error is.

Could you make a tiny test program (eg. in python), say what behaviour you see, and what behaviour you need.

**Comment by johntrunc** [comment]
This is an example of what I'm doing (I'm not checking errors or anything):

```c
#include <stdio.h>
#include <vips/vips.h>

int
main( int argc, char **argv )
{
  VipsImage *img, *out;

  if VIPS_INIT(argv[0]) {
    vips_error_exit(NULL);
  }

  // 1. Loading the image
  vips_jpegload("example.jpeg", &img, NULL);

  // 2. Deleting the file
  remove("example.jpeg");

  // 3. Processing the image
  vips_invert(img, &out, NULL);

  // 4. Saving it as png
  vips_pngsave(out, "output.png", NULL);

  return(0);
}
```

Is something like that possible? I mean it's possible to delete the origin image in this case the file "example.jpeg" after the `vips_jpegload` or will libvips need it for further processes before saving it on step 4?

For me is causing the `output.png` to be badly generated (probably because an error in the invert that I'm not checking). I'm not getting any warning or error for this small example.

**Comment by jcupitt** [comment]
Ah gotcha. Here's your program with error handling:

```C
/* compile with:
 *      gcc -Wall -g try194.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <vips/vips.h>

int
main( int argc, char **argv )
{ 
  VipsImage *img, *out;
  
  if( VIPS_INIT( argv[0] ) )
    vips_error_exit( NULL );

  if( !(img = vips_image_new_from_file( argv[1], NULL )) )
    vips_error_exit( NULL );

  printf( "opened file\n" );
  printf( "  width = %d, height = %d\n", img->Xsize, img->Ysize );

  if( unlink( argv[1] ) )
    vips_error_exit( "unable to unlink" );

  if( vips_invert( img, &out, NULL ) ||
    vips_image_write_to_file( out, argv[2], NULL ) )
    vips_error_exit( NULL );

  g_object_unref( img );
  g_object_unref( out );

  return( 0 );
}
```

If I run it, I see:

```
$ cp ~/pics/k2.jpg .
$ ./a.out k2.jpg x.jpg
opened file
  width = 1450, height = 2048
k2.jpg: unable to open for read
unix error: No such file or directory
$
```

What's happening is that after `new_from_file`, libvips is noting the filename and the seek position in the file, then closing the file descriptor. When you try to fetch pixels (execute the invert pipeline and save), libvips will reopen the file, seek back to the correct point, and restart the read operation. In this case, that's obviously failing since the file is no longer there.

This behaviour is to save on file descriptors. In languages like Ruby or C#, images are only closed when the garbage collector runs -- this means it is very easy to run out of file descriptors if you are handling large sets of images. By closing whenever it can, libvips makes working with large sets of images easier.

**Comment by jcupitt** [comment]
One solution is to load the image via a file descriptor rather than a filename. If libvips doesn't know the filename, it can't do the close-and-reopen trick.

```C
/* compile with:
 *      gcc -Wall -g try194.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <vips/vips.h>

/* Open an image via its file descriptor. This prevents libvips fro using
 * early-close tricks.
 */
static VipsImage *
new_via_file_descriptor( const char *filename )
{
  FILE *fp;
  VipsSource *source;
  VipsImage *image;

  if( !(fp = fopen( filename, "rb" )) ) { 
    vips_error( "new_via_file_descriptor", "unable to open file" );
    return( NULL );
  }

  if( !(source = vips_source_new_from_descriptor( fileno( fp ) )) ) {
    fclose( fp );
    return( NULL );
  }
  fclose( fp );
        
  if( !(image = vips_image_new_from_source( source, "", NULL )) ) {
    g_object_unref( source );
    return( NULL );
  }
  g_object_unref( source );

  return( image );
}

int
main( int argc, char **argv )
{
  VipsImage *img, *out;

  if( VIPS_INIT( argv[0] ) )
    vips_error_exit( NULL );

  if( !(img = new_via_file_descriptor( argv[1] )) )
    vips_error_exit( NULL );

  printf( "opened file\n" );
  printf( "  width = %d, height = %d\n", img->Xsize, img->Ysize );

  if( unlink( argv[1] ) )
    vips_error_exit( "unable to unlink" );

  if( vips_invert( img, &out, NULL ) ||
    vips_image_write_to_file( out, argv[2], NULL ) )
    vips_error_exit( NULL );

  g_object_unref( img );
  g_object_unref( out );

  printf( "success!\n" );

  return( 0 );
}
```

I see:

```
$ cp ~/pics/k2.jpg .
$ ./a.out k2.jpg x.jpg
opened file
  width = 1450, height = 2048
success!
$
```

**Comment by jcupitt** [comment]
Docs for the source stuff here:

https://libvips.github.io/libvips/API/current/VipsTargetCustom.html#vips-source-new-from-descriptor

**Comment by johntrunc** [comment]
Thank you very much John. I will try the source trick, really helpful.
