### ISSUE TITLE
magicksave configured with GraphicsMagick does not write transparency

### ISSUE THREAD

**Issue by cthorner** [libvips/libvips#1851]
When converting a PNG image to GIF I am able to get ImageMagick to magicksave with transparent background. But for some reason the background appears black with GraphicsMagick. I am also able to save WEBP images in both libraries from the same source with transparent background. Just not GIF for GM.

Is there a setting to let GM know it is transparent?

**Comment by jcupitt** [comment]
Hello @cthorner,

IM and GM forked a long time ago now and behind the scenes they have drifted quite far apart. In this case, further than libvips has followed them.

It looks like all transparency is broken with GM at the moment, eg.:

```
$ vips magicksave lion.png x.png
```

Writes a PNG with a black background.

Someone needs to sit down and find out how to get GM to write transparency.

**Comment by jcupitt** [comment]
I had a quick look and libvips is writing pixels to GM using this code:

https://github.com/libvips/libvips/blob/master/libvips/foreign/magick.c#L321

```C

	Image *constitute_image;

	g_assert( image );
	g_assert( image->signature == MagickSignature );

	constitute_image = ConstituteImage( width, height, map, type, 
		pixels, &image->exception );
	if( !constitute_image ) 
		return( MagickFalse );

	(void) CompositeImage( image, CopyCompositeOp, constitute_image, x, y );
	DestroyImage( constitute_image );
```

Which is based on the ImportImagePixels compat code in GM:

https://sourceforge.net/p/graphicsmagick/code/ci/default/tree/wand/magick_compat.c#l315

So I think there's probably no simple fix -- libvips is using the recommended compatibility code.

Someone would need to spend some time looking into this.

**Comment by cthorner** [comment]
Ok, thanks for the pointer. Could it's be because ImageMagic v7 switched from storage types: IntegerPixel to LongPixel and GM didn't.

http://ftp.icm.edu.pl/pub/unix/graphics/ImageMagick/www/porting.html

"The IntegerPixel storage type is removed (use LongPixel instead) and LongLongPixel is added"

From your link above:
```
%    o type: Define the data type of the pixels.  Float and double types are
%      normalized to [0..1] otherwise [0..MaxRGB].  Choose from these types:
%      CharPixel, ShortPixel, IntegerPixel, LongPixel, FloatPixel, or
%      DoublePixel.
```

It looks like IntegerPixel is still in use in GM.

**Comment by jcupitt** [comment]
I think it's probably more complex -- GM never implemented IM6's `ImportImagePixels` API call and only has a very limited compatibility stub. We'd need to find out how you're supposed to do that kind of thing with GM.

**Comment by jcupitt** [comment]
Seems to be fixed in master with https://github.com/libvips/libvips/commit/d1f84b0985e977374c6ea126eca9e70a71c43467

Mailing list thread https://marc.info/?l=graphicsmagick-help&m=160253804001039&w=2

Thanks bfriesen!

This change will be in 8.11.

**Comment by lofcz** [comment]
@jcupitt Would it be possible to include this in 8.10.3 instead? I've had some trouble building LibVips for windows (to try this myself) and this could potentially fix this the issue I'm having with transparent gifs in 8.10.X

**Comment by lofcz** [comment]
@jcupitt  thanks! ❤️

**Comment by jcupitt** [comment]
Sorry, I should have updated this issue. Yes, I backported it to 8.10.3.

It changes behaviour, which is bad for a stable branch, but on the other hand the old behaviour was mostly useless :(
