### ISSUE TITLE
Not sure if bug, feature or wrong aproach: "Premature end of JPEG file" msg when vipsthumbnail to same file.

### ISSUE THREAD

**Issue by jasomdotnet** [libvips/libvips#1854]
When I run following command:

```
vipsthumbnail /var/www/example.com/tmp/josephine-mb2016-3-2.jpg --eprofile srgb --size="4096x4096>" -o /var/www/example.com/tmp/josephine-mb2016-3-2.jpg[Q=90,interlace,profile=none,optimize_coding]
```

I get:

```
(vipsthumbnail:30921): VIPS-WARNING **: 19:16:13.505: read gave 2319 warnings

(vipsthumbnail:30921): VIPS-WARNING **: 19:16:13.507: VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image

vipsthumbnail: unable to thumbnail /var/www/example.com/tmp/josephine-mb2016-3-2.jpg
VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image
```
Image `josephine-mb2016-3-2.jpg` has following dimensions `1000x662`.

My goal is resize image above "4096x4096" so I can start to cut thumbnails from it later on.

**Expected behaviour:** Optimize image with no resize.

**My VIPS version:** `libvips 8.11.0-Thu Oct  1 06:21:43 UTC 2020`

**Comment by jcupitt** [comment]
Hi @jasomdotnet,

That's weird. Could the image file be truncated? Try uploading it somewhere.

I wouldn't use 8.11-- it's in active development and not very stable. I would stick to 8.10.

**Comment by kleisauke** [comment]
Does this error only occur if the input and output image are the same? If so, https://stackoverflow.com/a/63589444/10952119 might be relevant here.

**Comment by jcupitt** [comment]
Oh heh you're right, it won't work if the input and output files are the same, I hadn't noticed. Nice catch Kleis.

**Comment by jasomdotnet** [comment]
Then we [have](https://stackoverflow.com/a/63589444/10952119) an answer on question from title: Wrong approach :-)
