### ISSUE TITLE
Can build libvips for Android Platform?

### ISSUE THREAD

**Issue by jiangdongguo** [libvips/libvips#1855]
Hi, Thanks for your great lib! Now I want to use it on Android Application, Can it be builded to so files and use on Android platform?If yes, how should I construct the configure command.Hope your reply, Thanks again!

**Comment by jcupitt** [comment]
I imagine so, but I've never tried. Sorry I can't be more help.

**Comment by jiangdongguo** [comment]
oh,I see. Thanks for your reply!
