### ISSUE TITLE
Is it possible to make transparent backgrounds on png/webp Image Pyramid tiles (with google layout)?

### ISSUE THREAD

**Issue by ilyaerkhov** [libvips/libvips#1858]
I tried adding `--background "255 0 0 0"` (assuming that the last value is alpha) to my command, but it brings up error "linear: vector must have 1 or 3 elements". Using `--suffix ".png[background=255 0 0 0]"` outputs solid white background.

**Comment by jcupitt** [comment]
Hi @ilyaerkhov, yes, it should work. For example (the area around the lion is transparent):

![lion](https://user-images.githubusercontent.com/580843/96007476-6b878b00-0e36-11eb-946b-11e151cacabe.png)

Then:

```
vips dzsave lion.png x --suffix .png --layout google
```

Makes `x/1/0/0.png `:

![0](https://user-images.githubusercontent.com/580843/96007655-996ccf80-0e36-11eb-842d-510199e7f82f.png)

**Comment by ilyaerkhov** [comment]
Ah, I see! Thank you, everything is working great now.
