### ISSUE TITLE
vipsthumbnail for appleRAW

### ISSUE THREAD

**Issue by daverupp** [libvips/libvips#1859]
Hey @jcupitt 
On Tuesday evening Apple announced this new AppleRAW image format. Do you have already some insights about this and how libvips will be handling this kind of images?

I know i am super early, but maybe you heard already something :) 
cheers Dave

**Comment by jcupitt** [comment]
Heh you are quick!

I don't think anyone knows much about the format yet. If a high-quality free library appears that can decode it, we'll probably add support. You might be waiting a while though.

**Comment by daverupp** [comment]
I found out, that this will be a *.dng (Digital Negative).
Since libjpeg is supporting lossless conversion, I tried it with vipsthumbnailer *dng -o *jpeg and it worked super nice.

So questions solved :)
