### ISSUE TITLE
convert webp to pyramid tiff segmentation faults

### ISSUE THREAD

**Issue by barryspearce** [libvips/libvips#1860]
**Describe the bug**
When using vips from the command line to convert a webp to a pyramid tiff results in a segmentation fault.

**To Reproduce**
1. Image 
[9508b7_73d53d2e7e8b42d4a4918d2de8e0f2ca_mv2_d_3873_2380_s_2.zip](https://github.com/libvips/libvips/files/5396399/9508b7_73d53d2e7e8b42d4a4918d2de8e0f2ca_mv2_d_3873_2380_s_2.zip)
(Added as zip due to github not allowing webp)
2. Command:
vips im_vips2tiff 9508b7_73d53d2e7e8b42d4a4918d2de8e0f2ca_mv2_d_3873_2380_s_2.webp 9508b7_73d53d2e7e8b42d4a4918d2de8e0f2ca_mv2_d_3873_2380_s_2.ptif:jpeg:90,tile:256x256,pyramid

**Expected behavior**
A pyramid tiff should be created. No segmentation fault should occur.

**Actual behavior**
The command exits with segmentation fault.

**Environment**
 - OS: Manjaro  with 5.4.64-1-MANJARO kernel
 - Vips: 8.10.1-1

**Comment by jcupitt** [comment]
Hi @barryspearce,

You're using the old vips7 syntax. Try:

```
vips tiffsave 9508b7_73d53d2e7e8b42d4a4918d2de8e0f2ca_mv2_d_3873_2380_s_2.webp x.tif --compression jpeg --pyramid --tile --tile-width 256 --tile-height 256
```

It seems to work fine for me.

You're right that the vips7 interface is crashing in this case, which obviously shouldn't happen. I'll have a look. Thanks for reporting this.

**Comment by jcupitt** [comment]
I've fixed it in 8.10 HEAD and credited you in the changelog, this will be in 8.10.3. 

Thanks for reporting this dumbness.

**Comment by barryspearce** [comment]
Grand! Thanks for the heads up on the syntax change. I've changed my code to call with the new syntax and all is good.
Thanks!

**Comment by jcupitt** [comment]
I forgot to say, you can add `--Q 90` to that command as well, if you want. Try `vips tiffsave` (no arguments) at the command-line to see a summary.
