### ISSUE TITLE
Error: Input buffer has corrupt header: magickload_buffer: unsupported colorspace YCbCrColorspace

### ISSUE THREAD

**Issue by hisham** [libvips/libvips#1861]
**Describe the bug**
Updated from 8.10.1_1 to 8.10.2 and I now get this error for some heic images: 

(node:10855) UnhandledPromiseRejectionWarning: Error: Input buffer has corrupt header: magickload_buffer: unsupported colorspace YCbCrColorspace

**To Reproduce**
I am using libvips via node sharp library. 

**Expected behavior**
The same image works with 8.10.1_1
**Environment**
(please complete the following information)
 - OS: Mac OS 10.15.7
 - Vips: 8.10.2
- Node 13.14.0
- Sharp 0.26.2
- Vips installed via homebrew 2.5.6

**Comment by jcupitt** [comment]
Hi @hisham,

Could you post a sample image that fails?

I tried here and I see:

```
✘-1 ~/GIT/libvips/test/test-suite/images [master|⚑ 1] 
16:56 $ vipsheader Example1.heic 
Example1.heic: 4032x3024 uchar, 3 bands, srgb, heifload
```

ie. loading via `heifload` (not imagemagick) and works OK.

**Comment by hisham** [comment]
Yes - try this image (github does not support heic uploads): 

https://drive.google.com/file/d/1XLof65h5WhF0MqR27tazgnBZvt-mh1em/view?usp=sharing

Running `vips rot test.heic out.heic d90` returns `magickload: unsupported colorspace YCbCrColorspace` with vips version 8.10.2, but vips version 8.10.1_1 works fine.

**Comment by lovell** [comment]
Inspecting this file with `heif-info` I see:
```
Box: ftyp -----
size: 36   (header size: 8)
major brand: heic
minor version: 0
compatible brands: mif1,MiHE,miaf,MiHB,heic
```

I think this `> 32` check needs to be relaxed to at least `> 36`:

https://github.com/libvips/libvips/blob/a1ae0d1d68045c7468091d07db0132bcadb99f70/libvips/foreign/heifload.c#L272

**Comment by jcupitt** [comment]
I've relaxed the rules about header size and your test file works now. I've credited you in the ChangeLog.

This fix will be in 8.10.3, thanks!

**Comment by jcupitt** [comment]
I made it 64, just in case.

**Comment by leereichardt** [comment]
Just came over from https://github.com/lovell/sharp/issues/2409. I can confirm that was is also an issue with the [attached image](https://www.dropbox.com/s/zpkje50ukxkagui/heic.HEIC?dl=0) and it worked with the previous version as noted above. heic-info below: 



MIME type: image/heic
Box: ftyp -----
size: 36   (header size: 8)
major brand: heic
minor version: 0
compatible brands: mif1,MiPr,miaf,MiHB,heic

**Comment by jcupitt** [comment]
Hi @leereichardt, I tried your image and it's working with 8.10 HEAD.
