### ISSUE TITLE
find_trim does not respect alpha chanel, it is discouraging

### ISSUE THREAD

**Issue by JelF** [libvips/libvips#1866]
**Describe the bug**
find_trim ignores alpha chanel

**To Reproduce**
Use following image: 
![Logo_TV_2015](https://user-images.githubusercontent.com/861181/97195732-bb623c80-17bc-11eb-84d2-d8d7d001f1bb.png)

`image.crop(*image.find_trim(background: image.get_point(0,0))`

**Expected behavior**
Image should be trimed by alpha chanel bounds

![18550a0a18a001350000803f08021203706e67](https://user-images.githubusercontent.com/861181/97195929-eba9db00-17bc-11eb-9ae1-9bf115052548.png)

**Actual behavior**

Image trimed by rgb components

![18550a0a18a001350000803f08021203706e67 (1)](https://user-images.githubusercontent.com/861181/97196184-3af00b80-17bd-11eb-916f-8d45442ca33b.png)

**Environment**
 - OS: 4.19.97-gentoo
 - Vips: vips-8.9.1

**Workaround**

I splited image into bands and manualy merged trims, it worked

**Comment by JelF** [comment]
I consider this is a bug because it is completly discouraging

**Comment by jcupitt** [comment]
Hello @JelF,

Don't set background. Try:

```
$ vips find_trim logo.png 
8
5
134
140
```

The numbers are left, top, width, height. If I draw that box on `logo.png` I get:

![x](https://user-images.githubusercontent.com/580843/97204069-88fd1300-17ad-11eb-8685-7cb5cf11d141.png)

There is an issue that `find_trim` is designed for photographic images and can trim a little aggressively on vector art. We plan to add a vector art option for 8.11.

**Comment by jcupitt** [comment]
There are some notes in the docs about the `background` parameter and how to set it:

https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-find-trim
