### ISSUE TITLE
Delete levels from pyramidal files

### ISSUE THREAD

**Issue by kimalaacer** [libvips/libvips#1870]
Ask a question...
Is there a way to delete all levels from a .svs file and keep only level[0] without changing metadata or underlying compression.

**Comment by jcupitt** [comment]
Hi @kimalaacer, SVS is a read-only format, libvips can't write it.

The best you could do is save as a tiled JPEG TIFF, eg.:

```
vips copy in.svs out.tif[tile,compression=jpeg,Q=90]
```

**Comment by kimalaacer** [comment]
Thanks, 
I was successful using this : !vips tiffsave in.svs out.tif --pyramid=False --compression=jpeg --Q=90. 
my original in.svs is compressed with jpeg Q=70 tile 240. 
So, i was trying to not to lose through additional compression.

I will try your code and see which is faster. 

much appreciate your help.
