### ISSUE TITLE
Vips arrayjoin with different dimension images 

### ISSUE THREAD

**Issue by andrei0807** [libvips/libvips#1871]
I split image by vips.
so I got tile images.
original file dimension is 254x254
I split this by 100x100 dimension.
so I got 9 files
some file's dimensions are 54x100, 100x54 instead of 100x100.
it's good.
I am going to join these again.
When I use arraryjoin, I got 300x300 image.
How to solve this issue?

**Comment by jcupitt** [comment]
Hello @andrei0807,
 
You need to crop after `arrayjoin` if you need to remove the edges.

How are you splitting the image? `dzsave` can do this quickly. eg.:

```
vips dzsave k2.jpg x --layout google --depth one --tile-size 100 
```

**Comment by andrei0807** [comment]
Thanks for your response.
I had split images before.
but I have to merge these again.
There is no method by vips?

**Comment by jcupitt** [comment]
I suppose you could also do it in stages.

Join the main body of the image with `arrayjoin`. Join the strips for the right and bottom edges with two more `arrayjoin` calls. Finally, join the three pieces together with two plain `join` operations.

**Comment by jcupitt** [comment]
Or you can compute the original size, then do `arrayjoin` followed by `crop`. It would only be a couple of lines of Python.

**Comment by andrei0807** [comment]
Thanks.
But I don't know original image's size.
Can I get image's size by vips?

**Comment by jcupitt** [comment]
Could you calculate the original image size from the tiles? 

Pick one row and one column and add up all the widths and heights.
