### ISSUE TITLE
Error with HEIF to PNG conversion

### ISSUE THREAD

**Issue by jfcalvo** [libvips/libvips#1873]
Hi @jcupitt I have found some errors trying to convert a HEIF file with alpha channel to PNG. I thought it would be interesting share it with you.

I have created the HEIF file with the export option in MacOS Preview (with the Alpha option enabled), this is the source PNG:

![alpha](https://user-images.githubusercontent.com/446497/97922256-7742df00-1d5c-11eb-8da2-d9f609a97b2d.png)

And this is the created HEIF file (zipped to avoid problems with unsupported files in Github):

[alpha.heic.zip](https://github.com/libvips/libvips/files/5478200/alpha.heic.zip)

When I try to do a `vips copy` like the following one:

```sh
$ vips copy alpha.heic output.png
```

I get multiple errors of these types:

```
(vips:32969): VIPS-WARNING **: 22:43:40.525: error in tile 0 x 0
heif: Unsupported feature: Unsupported color conversion (4.3003)
```

The generated `output.png` file is invalid.

I'm using the following versions:

* MacOS 10.14.6
* Vips vips-8.10.2-Mon Oct 12 16:43:59 UTC 2020
* libheif 1.9.1

**Comment by jcupitt** [comment]
Hi @jfcalvo,

I think this is a probably a limitation of libheif. I see:

```
$ heif-convert alpha.heic x.png
File contains 1 images
Could not decode HEIF image: 0: Decoder plugin generated an error: Invalid image size
```

I'd open an issue there.

**Comment by jcupitt** [comment]
(removed bug tag since I think this is not a libvips bug)
