### ISSUE TITLE
Rotation without changing size

### ISSUE THREAD

**Issue by johntrunc** [libvips/libvips#1874]
Hi,

I'm trying to do an operation and I'm little bit lost about what the best approach to do it. I would like to do a rotation of an image (specifying an angle), I have seen that `vips_rotate` do exactly that. At the same time I would like to get as a result the image rotated without modifying the original size of it and without transparent areas.

I've been thinking about doing a rotate and after that some kind of zoom to the image but not really sure if there is a better or native way to do this.

This is an example of what I would like to do.

The original image (640x427):

![fox](https://user-images.githubusercontent.com/70328146/97999842-1e228c00-1dec-11eb-8d79-aae7053dee36.jpg)

The rotated image with an angle of 12 using vips rotate (858x661):

![fox-rotated-12](https://user-images.githubusercontent.com/70328146/97999953-3beff100-1dec-11eb-92ac-4df06d98e627.jpg)

The result that I'm trying to get where there is not transparent areas and the original image size is respected (640x427):

![fox-result](https://user-images.githubusercontent.com/70328146/98000026-51fdb180-1dec-11eb-9eb4-e652bdb0891e.jpeg)

Thanks!

**Comment by jcupitt** [comment]
Hi @johntrunc,

You need to calculate the size and position of the largest rectangle you can fit in the rotated image, then crop that out and size it up to match your original. There's no direct operation in libvips that does this, you'd need to do a little trig.

**Comment by johntrunc** [comment]
Thank you very much for the clarification @jcupitt 

It's time to take a look to my old trigonometry lessons 😄
