### ISSUE TITLE
How do you silence "VIPS-INFO" output on CentOS 6 libvips build?

### ISSUE THREAD

**Issue by elohanlon** [libvips/libvips#1876]
When I build libvips **8.10.2** on CentOS 6 (which is my target platform in this case), `vipsthumbnail` always outputs a bunch of 'VIPS-INFO' log lines, but the same build steps result in (expected) silent operation on CentOS 7.

Command: `vipsthumbnail owl.jpg --smartcrop attention -s 128`

CentOS 6:
```
$ vipsthumbnail owl.jpg --smartcrop attention -s 128
VIPS-INFO: thumbnailing owl.jpg
VIPS-INFO: selected loader is VipsForeignLoadJpegFile
VIPS-INFO: input size is 600 x 397
VIPS-INFO: loading with factor 1 pre-shrink
VIPS-INFO: pre-shrunk size is 600 x 397
VIPS-INFO: converting to processing space srgb
VIPS-INFO: residual reducev by 0.322418
VIPS-INFO: reducev: 19 point mask
VIPS-INFO: reducev: using vector path
VIPS-INFO: reducev sequential line cache
VIPS-INFO: residual reduceh by 0.322418
VIPS-INFO: reduceh: 19 point mask
VIPS-INFO: cropping to 128x128
VIPS-INFO: shrinkv by 2
VIPS-INFO: shrinkv sequential line cache
VIPS-INFO: shrinkh by 3
VIPS-INFO: residual reducev by 0.5
VIPS-INFO: reducev: 13 point mask
VIPS-INFO: reducev: using vector path
VIPS-INFO: reducev sequential line cache
VIPS-INFO: residual reduceh by 0.497409
VIPS-INFO: reduceh: 13 point mask
VIPS-INFO: convi: using C path
VIPS-INFO: gaussblur mask width 13
VIPS-INFO: convi: using C path
VIPS-INFO: convi: using C path
VIPS-INFO: thumbnailing owl.jpg as ./tn_owl.jpg
$
```

CentOS 7:
```
$ vipsthumbnail owl.jpg --smartcrop attention -s 128
$
```

Is it possible that I need to pass an extra configure argument during the CentOS 6 build steps to hide the default display of these VIPS-INFO log lines?

In addition to libvips 8.10.2, I'm also seeing "VIPS-INFO" output appearing by default when I build libvips 8.7.4 or 8.8.0 on CentOS 6.

**Comment by jcupitt** [comment]
Hi @elohanlon,

libvips uses the glib logging framework, so message are being produced by that somehow:

https://developer.gnome.org/glib/unstable/glib-Message-Logging.html

Perhaps something in your system has set the G_DEBUG env var? Or maybe your platform glib has been built with info logging permanently enabled?

**Comment by elohanlon** [comment]
HI @jcupitt,

Thanks for the quick reply, and the info!  I'll look into the glib settings!

**Comment by kleisauke** [comment]
I think the problem here is that prior GLib version 2.32 log messages at levels `INFO` or `DEBUG` are shown by default (CentOS 6 ships with GLib 2.28.8). AFAIK, there is no way to disable this behaviour with environment variables.

Perhaps we could disable these messages for these older GLib versions unless the `G_MESSAGES_DEBUG` environment variable is set? This should match the behaviour of GLib 2.31 and newer.

See for example this untested patch:
<details>
 <summary>Patch</summary>

```diff
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Kleis Auke Wolthuizen <github@kleisauke.nl>
Date: Mon, 9 Nov 2020 21:59:00 +0100
Subject: [PATCH 1/1] Don't print debug/info output with GLib older than 2.31



diff --git a/libvips/iofuncs/init.c b/libvips/iofuncs/init.c
index 1111111..2222222 100644
--- a/libvips/iofuncs/init.c
+++ b/libvips/iofuncs/init.c
@@ -284,6 +284,28 @@ empty_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
 {       
 }
 
+#if !GLIB_CHECK_VERSION( 2, 31, 0 )
+/* Ensure to disable debug/info logging by default unless G_MESSAGES_DEBUG is
+ * set to an appropriate value (this matches GLib 2.31.0 and newer).
+ */
+static void
+default_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
+	const gchar *message, gpointer user_data )
+{
+	const char *domains;
+
+	if( log_level & (G_LOG_LEVEL_DEBUG | G_LOG_LEVEL_INFO) ) {
+		domains = g_getenv( "G_MESSAGES_DEBUG" );
+		if( !domains || (!g_str_equal( domains, "all" ) &&
+			!g_strrstr( domains, log_domain )) ) {
+	  		return;
+		}
+	}
+
+	g_log_default_handler( log_domain, log_level, message, user_data );
+}
+#endif /*!GLIB_CHECK_VERSION( 2, 31, 0 )*/
+
 /* Attempt to set a minimum stacksize. This can be important on systems with a
  * very low default, like musl.
  */
@@ -318,10 +340,6 @@ set_stacksize( guint64 size )
 static void
 vips_verbose( void ) 
 {
-	/* Older glibs were showing G_LOG_LEVEL_{INFO,DEBUG} messages
-	 * by default
-	 */
-#if GLIB_CHECK_VERSION ( 2, 31, 0 )
 	const char *old;
 
 	old = g_getenv( "G_MESSAGES_DEBUG" );
@@ -338,7 +356,6 @@ vips_verbose( void )
 
 		g_free( new );
 	}
-#endif /*GLIB_CHECK_VERSION( 2, 31, 0 )*/
 }
 
 /**
@@ -590,6 +607,11 @@ vips_init( const char *argv0 )
 		g_log_set_handler( G_LOG_DOMAIN, G_LOG_LEVEL_WARNING, 
 			empty_log_handler, NULL );
 
+#if !GLIB_CHECK_VERSION( 2, 31, 0 )
+	g_log_set_handler( G_LOG_DOMAIN, G_LOG_LEVEL_INFO |
+		G_LOG_LEVEL_DEBUG, default_log_handler, NULL );
+#endif
+
 	/* Set a minimum stacksize, if we can.
 	 */
         if( (vips_min_stack_size = g_getenv( "VIPS_MIN_STACK_SIZE" )) )
```
</details>

**Comment by elohanlon** [comment]
@kleisauke I think you're right, and I didn't have any luck with environment variables.  And @jcupitt, thank you for pointing me in the right direction with glib!  Here's what I found, along with some more info about my situation:

Prior to creating this github issue, I ended up having to build glib myself because the CentOS 6 version that yum gave me (2.28.8) resulted in the VIPS-INFO messages AND some additional "GLib-GObject-CRITICAL" messages.

In CentOS 7, I still got the VIPS-INFO messages, but I didn't see the "GLib-GObject-CRITICAL" messages, so I figured the older version of glib was causing issues.  So I built glib 2.57.1 on CentOS 6 (because I had an issue building 2.56.1) and then built libvips.  The "GLib-GObject-CRITICAL" messages went away, but the VIPS-INFO ones remained.

I looked through the glib 2.57.1 configuration options and discovered "--enable-debug=no", and when I rebuilt glib with that option the VIPS-INFO messages went away.  I'm guessing that whatever RPM builds glib on CentOS 6 and CentOS 7 doesn't make use of that parameter.

So hopefully that info helps anyone else who finds their way to this github issue for the same reason.  I'd be interested in knowing if your proposed patch hides the INFO messages though, since that would probably be easier for people who don't want to build glib themselves.

**Comment by jcupitt** [comment]
Huh curious, you'd think `--disable-debug` would be the default setting. 

Thanks for the update!

**Comment by jcupitt** [comment]
I just tried building glib-2.57.1 and I didn't get INFO messages. 
I tried 2.28.6 as well, and that also hid INFO messages by default.

**Comment by elohanlon** [comment]
Hmm...If I'm interpreting this correctly, it looks like odd minor versions of glib enable debugging by default:

https://github.com/GNOME/glib/blob/2.57.1/configure.ac#L50-L53

```
# if the minor version number is odd, then we want debugging.  Otherwise
# we only want minimal debugging support.
m4_define([glib_debug_default],
          [m4_if(m4_eval(glib_minor_version % 2), [1], [yes], [minimum])])dnl
```

I wasn't expecting that, but this is the first time I've ever built glib, so that may be normal for that library.  I'm going to test this out later on with a build of 2.58.3.

Still, I'm not sure why I was still getting debug output in the CentOS 7 2.56.1 rpm from yum.  And the configure file for 2.28.8 seems to have the same default for an even minor version: https://github.com/GNOME/glib/blob/2.28.8/configure.ac#L41-L44

**Comment by jcupitt** [comment]
I've been experimenting with various older glibs. glib-2.30.2 seems to be a good test case -- you get the annoying INFO messages even if you build it with `--enable-debug=no`, which seems like a clear bug.

I've pushed a patch to 8.10 based on Kleis's suggestion. It seems to work, but what an ugly hack! But it does hide these messages unless you ask for them.

**Comment by elohanlon** [comment]
I was planning on testing with even-number glib 2.58.3 on CentOS, but it turns out that the automake version I had was too old (`require Automake 1.13.3, but have 1.11.1`).  But I was able to get even-number 2.56.4 to build after all and I'm glad to report that it _does_ default to hiding the INFO messages, so I'll go with that version in the end.

Thank you for the patch to handle older versions!  I'm glad it works despite the ugliness, haha.
