### ISSUE TITLE
Asynchronous read, write support for VipsConnection

### ISSUE THREAD

**Issue by akash-akya** [libvips/libvips#1877]
I'm building vips binding for Elixir/Erlang, currently trying to integrate `VipsConnection` with elixir stream abstraction. 

The problem is that vips invokes blocking `read` on `VipsSource` which blocks elixir scheduler indefinitely. What would perfect is the ability to yield control immediately and resume operation whenever data is available. 

Is it possible to provide an interface for "async read"? maybe by passing callback which should be invoked once data is available? Something like https://developer.gnome.org/gio/stable/GInputStream.html#g-input-stream-read-async

I only know basics of GObject, so wanted to know your opinion on this

**Comment by jcupitt** [comment]
Hi @akash-akya,

I think the best solution would probably be to use a background thread for load.

gobject has an async-style system but you (obviously) need to use the glib message dispatch loop, and I doubt if elixir/erlang will be able to adopt that.

You could also think of it as the difference between pull and push systems. Something like imagemagick is a push systems, so as data arrives you can call operations to process it. libvips however is a pull system, so libvips will ask for data when it needs it and it's up to the host to supply it when asked.

**Comment by akash-akya** [comment]
Hi @jcupitt,
 
Thanks for the quick reply.

> I think the best solution would probably be to use a background thread for load.

Yes, this is _somewhat_ possible <sup>[1](#footnote1)</sup>. But I wanted to avoid the complexity of managing threads and reuse existing dedicated IO schedulers. 

There are 2 things to consider:
* since a C function can not be preempted, this mess up preemptive scheduling in elixir/erlang
* it's not possible to call erlang/elixir a function from a "C function" (NIF) _synchronously_

> so libvips will ask for data when it needs it and it's up to the host to supply it when asked.

I'm aware of this and I want to connect this to elixir stream. 

In elixir, it's possible to block the _caller_ without blocking the _thread_ in which the call is made. and i was thinking pull system along that line.
```
function read()
     send aws_s3, :read
     receive data   # blocks the caller till we receive data, but not the thread
     return data
end
```
Anyway, now that I think of it, I don't think it's possible to do something like this in a C function easily.

> gobject has an async-style system

Thanks, I will look into this.

<a name="footnote1">1</a>: https://erlang.org/pipermail/erlang-questions/2018-January/094626.html

**Comment by jcupitt** [comment]
The glib event loop is documented here:

https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html

Programs which want to do async/await-style processing need to run this occasionally. Erlang will have a similar event loop somewhere, perhaps you can hook into that?
