### ISSUE TITLE
"g_object_unref: assertion 'G_IS_OBJECT (object)' failed" on vips_shutdown()

### ISSUE THREAD

**Issue by tonimelisma** [libvips/libvips#1881]
Apologies John, I know I'm opening a new issue every day, even before the previous ones have been properly closed.

I'm trying to track a bug between govips and libvips. When the program ends and I call ```vips_shutdown()```, I get the mystical (critical!) error from glib:

```g_object_unref: assertion 'G_IS_OBJECT (object)' failed```

This only happens when I close the vips image before calling vips_shutdown(). I can also let the program terminate without calling vips_shutdown() and I don't get the error, so it's a combination of closing the image and calling vips_shutdown. Closing the image in govips runs the C code ```if (G_IS_OBJECT(*image)) g_clear_object(image);```

I've been trying to drill down into vips_shutdown() and can't figure out where it's clearing the object, to figure out what's wrong with my code.

What am I doing wrong in govips? Am I just supposed to set the govips ımage objects to nil so they're unusable after the image is closed, but leave to libvips image pointer uncleared? I'm guessing this hoards the memory until I eventually call vips_shutdown()? Or is there something else I need to do to the image in libvips so libvips realizes the image object has already been cleared and doesn't try to do the assert thing?

**Comment by jcupitt** [comment]
Hey @tonimelisma, don't worry, that's fine.

It could be a double unref. What does closing an image mean? Generally you should somehow be certain that every ref has a matching unref. If there's an `if` guarding an unref, that smells bad. You should know you own a ref and also know you must unref it. There should be no `if` involved.

I usually debug refcounting by making the minimal program I can, eg. python for convenience:

```python
import pyvips 

x = pyvips.Image.black(10, 10)
```

And run that with logging enabled. Make sure that all refs are acquired and released as you'd expect. Once you have the minimum working, slowly ramp up the complexity:

```python
import pyvips 

x = pyvips.Image.black(10, 10)
x = None
```

```python
import pyvips 

x = pyvips.Image.black(10, 10)
x = x.add(12)
```

etc.

Once you have the base working, and the various call cases, hopefully, by induction, it'll be correct for all cases.

**Comment by jcupitt** [comment]
... and prove it's a double unref by making a minimal test case and commenting out one of your unrefs. Hopefully the error will vanish.

**Comment by tonimelisma** [comment]
So basically close() in this case is the govips counterpart to vips_image_new_from_file(). Whereas vips_image_new_from_file() creates a new image ref (in libvips using C), close is a govips function which destroys and releases that imageref (in govips, using also C).

So as far as I can see, govips is creating the ref and unrefing correctly.

The question to libvips on the C level is, am I not allowed to unref via using g_clear_object(image) when I'm done with the image? Would it be better if I used g_object_unref(image) instead?

**Comment by jcupitt** [comment]
It's probably more complex than that -- I would look at the Go GC, and how object finalizers work. An explicit `close` operation sounds bad.

In Ruby, for example, which has a similar GC model to Go (I think), it's done in the gobject base class. Every new instance takes a ref, and at the same time registers an unref in the matching finalizer. 

Debugging refcounting is the second more horrible task in programming, just behind debugging race conditions :(

**Comment by tonimelisma** [comment]
Right on the money, John. With the plethora of pull requests we just integrated to pull govips 2.0 together one of them was a two-line patch adding GC support for imageRefs, which I forgot all about! So indeed, manually closing the image will double-unref as it's in addition to the GC doing its work.

Thanks for the help, once again!
