### ISSUE TITLE
HEIF file that worked in 8.9.2 errors in 8.10.2

### ISSUE THREAD

**Issue by vansante** [libvips/libvips#1882]
**Describe the bug**
I have a HEIF file that used to work in version 8.9.2, but errors in verson 8.10.2

**To Reproduce**
1. Use Image: [testheif.zip](https://github.com/libvips/libvips/files/5524035/testheif.zip)
2. Run `vipsthumbnail test3.heic`
3. See error

**Expected behavior**
A thumbnail is generated

**Actual behavior**
An error: `VipsForeignLoad: "test3.heic" is not a known file format`

**Environment**
 - OS: Debian Buster
 - Vips: 8.10.2

**Comment by lovell** [comment]
This is the same problem as reported in #1861 and fixed via commit https://github.com/libvips/libvips/commit/b1e636346a3ffeee5b6c05945d52f1804bd62afb

**Comment by jcupitt** [comment]
Yes, this fix is in 8.10.3, out in a few days (I guess?).

Thanks for reporting the problem, @vansante.
