### ISSUE TITLE
Possible to adjust seeds for Perlin/Worley (in either LibVips or PyVips)? 

### ISSUE THREAD

**Issue by dzz** [libvips/libvips#1884]
I'm using these functions for some texture generation. But I'm struggling to figure out a way to either change the domain for the perlin/worley functions, or change the seed. Looking at the underlying C source, i see there is a seed field in the struct but I'm not sure how I could go about manipulating this through the API. 

Any hints/pointers?

**Comment by jcupitt** [comment]
Hi @dzz, no the seed isn't exposed in the API.

What controls do you need? Just to be able to set it on create? Would this be enough?

```python
image = pyvips.Image.worley(128, 128, cell_size=8, seed=1234)
```

**Comment by dzz** [comment]
That would work perfectly!

**Comment by jcupitt** [comment]
OK, added to git master. This will be in 8.11. Thanks for the suggestion!

**Comment by dzz** [comment]
Amazing! I think other folks will find this useful as well. :)
