### ISSUE TITLE
libvips as native PHP version 7.4 with FFI support implementation

### ISSUE THREAD

**Issue by cr-solutions** [libvips/libvips#1885]
Hi guys,

I like to port the libvips as native to PHP version 7.4 with FFI support.
Open an image as VipsImage and resizing looks like working, but if I like to save the image as file I get the following error:

"jpegsave: no property named `'

from function

"vips_image_write_to_file"

my FFI::cdef for this function looks like:

`int vips_image_write_to_file(VipsImage *image, const char *name);`

whats wrong here? What does this error mean?

PHP code looks like: 

`
$file_new = "./test.jpg";
$ret = $ffi->vips_image_write_to_file($hVipsImageNew[0], $file_new);
`

$hVipsImageNew[0] is returned by "vips_resize" and contains the VipsImage *

**Comment by jcupitt** [comment]
Hi @cr-solutions, 

`vips_image_write_to_file()` needs a `NULL` at the end. It takes a list of name-value pairs, for example (in C):

```C
if (vips_image_write_to_file (image, "myfilename.jpg", 
    "Q", 95, 
    "profile", "/some/icc/profile.icm",
    NULL )) 
    error_handling_code (...);
```

The type of each argument can vary (int and str in this case), so it's a nightmare to call from FFI.

Instead, it's much, much simpler to use the GObject API to libvips and rely on introspection. You can do the entire binding in just a few hundred lines of code, and it'll automatically stay up to date if libvips changes.

https://libvips.github.io/libvips/API/current/binding.md.html

You can see how ruby-vips handles `vips_image_write_to_file()` here:

https://github.com/libvips/ruby-vips/blob/master/lib/vips/image.rb#L514-L554

It calls `vips_foreign_find_save()` to find the save operation from the filename, then uses introspection to save the image, passing any optional arguments along.

**Comment by jcupitt** [comment]
Another option would be to reimplement php-vips-ext in PHP using FFI:

https://github.com/libvips/php-vips-ext/blob/master/vips.c

Then the existing php-vips could just run on top of it. It might save you some work, and you can use implementation ideas from the C version.

**Comment by cr-solutions** [comment]
Hi @jcupitt,

thanks for your answers.

I checked the ruby implementation and also the python one 
http://www.rollthepotato.net/~john/html/_modules/pyvips/vimage.html

But I'm not sure how to do the part of 

` return pyvips.Operation.call(_to_string(ffi.string(name)),
                                     _to_string(ffi.string(filename)),
                                     string_options=_to_string(
                                         ffi.string(options)
                                     ), **kwargs)`

with PHP::FFI

I tried also to use cdef like

`int vips_image_write_to_file(VipsImage *image, const char *name, ...);`

instead of 

`int vips_image_write_to_file(VipsImage *image, const char *name);`

but this cause an seg fault error in PHP

can you maybe help me to solve it, if I share you my code via your gmail address?

**Comment by jcupitt** [comment]
You need to implement something like this in PHP:

https://github.com/libvips/php-vips-ext/blob/master/vips.c#L927-L1046

The sample code in the binding chapter of the docs does the same thing.

**Comment by cr-solutions** [comment]
@jcupitt thanks for the inspiration!

useing FFI:cdef 

like `int vips_image_write_to_file(VipsImage *image, const char *name, char *argv[]);`

solved my problem with "vips_image_write_to_file" 

**THANKS SO MUCH**

**Comment by jcupitt** [comment]
I think that's just put a NULL at the end of the arg list. You won't be able to pass options to savers :( 

You need to implement something like `vips_php_call_array()`.

**Comment by cr-solutions** [comment]
No,

it works perfect like: 

```
$ret = $ffi->vips_image_write_to_file($hVipsImageNew[0], $file_new.'[Q=5,strip=true]', NULL);
var_dump($ret, $ffi->vips_error_buffer()); $ffi->vips_error_clear();
```

**Comment by jcupitt** [comment]
Sure, but only with options encoded as a string. You won't be able to pass options to things like resize either :(

**Comment by jcupitt** [comment]
... of course, if that's good enough, then great!
