### ISSUE TITLE
Consider publishing versioned formulae of vips on homebrew

### ISSUE THREAD

**Issue by jseppi** [libvips/libvips#1886]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to specify the version of `vips` that gets installed by `brew install vips`. This is so I can know that my local version is the same as being used in other external services.

**Describe the solution you'd like**
To be able to install specific versions of vips from homebrew. For example, `brew install vips@8.10.2`.

**Describe alternatives you've considered**
I haven't considered others, but would be happy to hear some.

**Additional context**

**Comment by jcupitt** [comment]
Hello @jseppi, I think this is a homebrew issue. They used to support versioned installs, but this feature was removed a few years ago to simplify support. These days all you get is the latest.

I think if you need very exact features, something like docker might be your best bet.

**Comment by jseppi** [comment]
ah, fair enough, @jcupitt. I'm admittedly not super clear on how homebrew works. Appreciate the response!
