### ISSUE TITLE
High memory usage for jpeg resize

### ISSUE THREAD

**Issue by MatthewMiele** [libvips/libvips#1887]
Hi! 
We have been using libvips for a while now and its working really well. We choose it for its memory efficiency but today we found a case that causes the memory to peak at around 1.2GB.  

Just wondering if this is normal for this case or if there's any tips to debug this for us to understand in the future if this is normal behaviour or if something is wrong.

Our understanding is that jpeg should also be using shrink on load for maximum efficiency?

```
$ vipsthumbnail --vips-version
libvips 8.7.4-Fri Jan 18 17:07:38 UTC 2019
```

```
$ vipsheader mega.jpeg
mega.jpeg: 17953x12874 uchar, 3 bands, srgb, jpegload
```

```
$ time vipsthumbnail mega.jpeg --vips-leak
memory: high-water mark 6.93 MB

real	0m0.908s
user	0m0.534s
sys	0m0.366s
```

**Comment by jcupitt** [comment]
Hi @MatthewMiele,

You'll see high memory use for interlaced JPEGs, perhaps you've hit one of those? You can check with `vipsheader`:

```
$ vips copy st-francis.jpg x.jpg[interlace]
$ vipsheader -f interlaced x.jpg 
1
```

Interlaced JPGs can't be shrunk efficiently, unfortunately, because you have to decode the entire image to get any pixels out.

```
$ vipsheader st-francis.jpg 
st-francis.jpg: 30000x26319 uchar, 3 bands, srgb, jpegload
$ /usr/bin/time -f %M:%e vipsthumbnail st-francis.jpg 
49020:3.20
$ /usr/bin/time -f %M:%e vipsthumbnail x.jpg 
2360940:8.87
```

49MB vs. 2.3GB.

**Comment by jcupitt** [comment]
fwiw, people usually handle this by testing for interlaced JPGs before attempting to shrink, and letting much lower size limits for them.

You can get some pathological TIFFs as well, sadly.

**Comment by MatthewMiele** [comment]
Your spot on! Its an interlaced JPEG!

```
$ vips copy mega.jpeg x.jpg[interlace]
$ vipsheader -f interlaced x.jpg
1
```

Thanks for your help! I have learnt something new today! Looks like we will need to do some extra testing as you mentioned.

Is there some reading you can recommend on this subject? or perhaps a list of known gotchas when it comes to image formats such as this issue

**Comment by jcupitt** [comment]
`vips copy mega.jpeg x.jpg[interlace]` writes an interlaced jpg. Try this:

```
$ vipsheader -f interlaced mega.jpg
```

To see if your huge image is interlaced.

Sorry, I don't know of a good resource to read up. Bitter experience is all you get :(

**Comment by MatthewMiele** [comment]
Ah! I miss read your example. Your code duplicated a non interlaced image and saved it as interlaced to show the difference in memory.

Its still coming back as interlaced! Phew! 😂 
```
$ vipsheader -f interlaced mega.jpeg
1
```

Thanks again! Ill close of this ticket
