### ISSUE TITLE
Is Cairo and XQuartz Required?

### ISSUE THREAD

**Issue by iq-dot** [libvips/libvips#189]
Hey Guys,

I am trying to install libvips using homebrew and I get errors that it requires Cairo which has a dependency on XQuartz.

I was really hoping to avoid installing XQuartz on OSX and I thought libvips was the library.

brew install -v homebrew/science/vips
cairo: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
pango: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
Error: Unsatisified requirements failed this build.

~:$ brew info vips
vips: stable 7.40.11
http://www.vips.ecs.soton.ac.uk/
Not installed
From: https://github.com/homebrew/homebrew-science/blob/master/vips.rb
==> Dependencies
Build: pkg-config ✘
Required: fontconfig ✘, gettext ✘, glib ✘
Recommended: libpng ✘, jpeg ✘, orc ✘, libgsf ✘, libtiff ✘, fftw ✘, little-cms ✘, pango ✘, libexif ✘
Optional: openslide ✘, imagemagick ✘, graphicsmagick ✘, openexr ✘, cfitsio ✘, webp ✘

But I can't see from the brew info that it has a dependency on cairo. Can someone confirm?

I did try to install Cairo before but it failed due to XQuartz and I haven't since tried to install it again after seeing it's XQuartz dependency.

**Comment by mikemliu** [comment]
for posterity, i needed the following:
```
brew install vips --without-pango --without-pygobject3
```

**Comment by smber1** [comment]
Happy for the above to be submitted for posterity as works for me too!
