### ISSUE TITLE
How do you properly subtract two PPM images?

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1894]
I am about to evaluate vips for using it in my own astronomical image reduction project (see https://github.com/ewelot/airtools). Currently I am playing with the command line program, using vips version 8.10.2 on Debian "Buster". I am trying to do some image arithmetics on 16bit PPM images. Unfortunately I am not able to obtain expected results. For reference I am using the output from
  pnmarith -subtract sky.ppm stars.ppm > x.diff.ppm

Here is what I tried so far:
# 1st attempt
vips subtract sky.ppm stars.ppm x.vips.ppm

# 2nd attempt
vips subtract sky.ppm stars.ppm x.sub.v
vips cast x.sub.v x.sub16.v ushort
vips ppmsave x.sub16.v x.vips2.ppm

# 3rd attempt
vips ppmload sky.ppm   x.sky.v
vips ppmload stars.ppm x.stars.v
vips subtract x.sky.v x.stars.v x.diff.v
vips cast x.diff.v x.diff16.v ushort
vips ppmsave x.diff16.v x.vips3.ppm

All PPM images produced by vips are incorrect (from visual inspection) and all 3 files are different (different MD5sum) which is quite odd as well.

Any hints on this topic?
Thanks, Thomas.

**Comment by jcupitt** [comment]
Hi @ewelot, it should work. Could you post some sample images and say what you think the errors are?

I tried:

```
$ vipsheader x*.ppm
x.ppm: 3232x2071 ushort, 1 band, grey16, ppmload
x2.ppm: 1450x2048 ushort, 1 band, grey16, ppmload
$ vips subtract x.ppm x2.ppm x.v
$ vipsheader x.v
x.v: 3232x2071 int, 1 band, grey16, ppmload
```

So 16-bit ushort - ushort makes a signed 32-bit image, but ppm does not support signed int images, so the -ves will be chopped off when converting back to ppm. You'll need to perhaps add an offset, or use PFM (which supports float pixels) instead.

I would use something like python rather than the command-line for this kind of thing -- it should be quite a bit quicker and simpler.

**Comment by jcupitt** [comment]
libvips also supports FITS, which might be useful for astronomical work.

**Comment by ewelot** [comment]
Hi John,

please find attached some sample data files.
I suspect there is some data conversion going on when reading those PPM images, because also simple image statistics do not match original pixel intensity values. Those original statistics (e.g. measured using ImageJ or any other software) give

```
Channel,Color,Area,Mean,StdDev,Mode,Min,Max,Median
1,red,39600,1015.136,215.304,1000,969,16103,1001
2,green,39600,1017.434,269.087,998,969,19825,1000
3,blue,39600,1009.748,165.750,999,970,13417,1000

```
compared to:
```
$ vips max sky.ppm 
65293.000000

```

I'll most likely make use of vips via C and/or python, but for the time being just sticking to the command line. I have seen those functions handling FITS reading and writing as well. I will certainly use them as well, but the handling of FITS date can get very complex as it is just a container format and the layout of image data variees at lot when using different software. I'll probably come back to this later on (using a different topic/question).

Thanks for your help,
Thomas
[samples.zip](https://github.com/libvips/libvips/files/5579727/samples.zip)

**Comment by jcupitt** [comment]
You're right, the ppm loader was defaulting to LSB first, but it should be MSB first. I've fixed this in the 8.10 branch and master, and credited you.

I now see:

```
$ vips stats sky.ppm x.csv
$ more x.csv
969	19825	120475802	127967295652	1014.1060774410774	220.80548546111336	85	15	172	69
969	16103	40199381	42643484609	1015.1358838383838	215.30438893264721	85	15	172	69
969	19825	40290401	43860108123	1017.4343686868687	269.08664374992219	96	104	172	69
970	13417	39986020	41463702920	1009.7479797979798	165.7495583852681	39	144	171	69
```

Which I think matches your imagej result.

**Comment by jcupitt** [comment]
(and thanks for reporting this dumbness, the fix will be in 8.10.3)

**Comment by jcupitt** [comment]
I've patched ppmsave to byteswap if necessary as well.

**Comment by ewelot** [comment]
Thanks for fixing this so quickly!
