### ISSUE TITLE
Produce individual tiff layer files from pyramid command?

### ISSUE THREAD

**Issue by nator** [libvips/libvips#1895]
I'm creating a pyramid tiff with 512x tiled layers, webp compression, and all goes well. For various post-processing tasks it would be much better if I was able to pull and move the individual layers as files -- I know I can load just the page I need using vips but I'm trying to avoid transferring the entire ptiff if I know I just need layer 2, for example.

I understand the tiff format for ptiffs is essentially just concatenated individual tiffs, and e.g. tiffsplit can do this task in a flash.

Is there any way to achieve this using libvips / pyvips so I don't need to add another dependency and external call to tiffsplit? I tried manually resizing each layer and exporting and it's slower than a single pyramid command (and actually seems to corrupt the image if I call resize more than once on the same vimage??).

Thanks for any ideas!

**Comment by jcupitt** [comment]
Hi @nator,

Sorry, libvips will always decompress and recompress, so something like tiffsplit will be a lot quicker. 

When it writes a pyr tiff, libvips actually creates the layers as separate files and then combines them, so I suppose you'd really like to be able to disable the recombine stage. I don't think there's any API for that though.

**Comment by nator** [comment]
Thanks John, that makes sense and is such a special case it doesn't make sense to make a new API for this. Tiffsplit should be great, I was just worried I might have missed a shortcut. :)
