### ISSUE TITLE
Lzw compression fails when writing ome.tif

### ISSUE THREAD

**Issue by ajay1685** [libvips/libvips#1896]
**Describe the bug**
Lzw compression fails when writing ome.tif for large images, link to sample image included below.

**To Reproduce**

1. Use Sample Image 'https://downloads.openmicroscopy.org/images/SVS/77917.svs'
2. libvips 8.10.2 with latest NetVIps from Nuget package manager 
3. Write ome.tif use lzw as compression
4. Exception:
`
unable to call VipsForeignSaveTiffFile
TIFFAppendToStrip: Maximum TIFF file size exceeded
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
TIFFAppendToStrip: Maximum TIFF file size exceeded
`
5. Another way to reproduce using pre compiled binaries

```
PS D:\WholeSlideImages\SVS> vips copy 77917.svs 77917-lzw.ome.tif[pyramid,subifd,compression=lzw]
TIFFAppendToStrip: Maximum TIFF file size exceeded
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
TIFFAppendToStrip: Maximum TIFF file size exceeded
```
No compression works fine on the same file:
```
PS D:\WholeSlideImages\SVS> vips copy 77917.svs 2-77917-none.ome.tif[pyramid,subifd,compression=none] --vips-progress
vips.exe temp-2: 96999 x 45667 pixels, 16 threads, 128 x 128 tiles, 384 lines in buffer
vips.exe temp-2: done in 42.8s
```

**Expected behavior**

expect to write ome.tiff with lzw compression for small or large file (but failed for large file).

**Actual behavior**
ome.tiff with no compression works as expected, but lzw compression fails with exception for large file. Lzw compression works when the file is relatively smaller.

**Screenshots**
without compression: Succesful
```
Processing: D:\WholeSlideImages\SVS\77917.svs
height: 45667
width: 96999
bands: 3
Micron per pixel X: 0.253
Micron per pixel Y: 0.253
Magnification: 40X
Conversion time: 0:0:37 (hh:mm:ss)
```
With lzw compression: Exception
```
Processing: D:\WholeSlideImages\SVS\77917.svs
height: 45667
width: 96999
bands: 3
Micron per pixel X: 0.253
Micron per pixel Y: 0.253
Magnification: 40X
unable to call VipsForeignSaveTiffFile
TIFFAppendToStrip: Maximum TIFF file size exceeded
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
TIFFAppendToStrip: Maximum TIFF file size exceeded
Conversion time: 0:1:36 (hh:mm:ss)
```

**Environment**

 - OS: Windows 10
 - Vips: 8.10.2 precompiled binaries & included openslide binaries, I am using NetVips

**Comment by jcupitt** [comment]
Hi @ajay1685,

Have you tried turning on bigtiff? libvips is unable to set the bigtiff flag automatically for compressed files.

Something like:

```
vips copy 77917.svs 77917-lzw.ome.tif[pyramid,subifd,bigtiff,compression=lzw]
```

**Comment by ajay1685** [comment]
that worked, thanks.
