### ISSUE TITLE
Make the graph more complex

### ISSUE THREAD

**Issue by hzm199822** [libvips/libvips#1900]
I want to ask two questions. The first one is about the processing of pictures. Last time I finished the puzzle, I got a white puzzle on a complete picture through your method。But is there any way to make the white area of this image more complicated. In particular, can we do some processing on the edge of the white block and the whole picture. For example, bold, white becomes a random and complex color
![1_back](https://user-images.githubusercontent.com/68108652/100070939-7988ec80-2e75-11eb-94e7-50702efd98ef.png)

**Comment by hzm199822** [comment]
vips = require "vips"
local filename = "/home/hzm/hzm/vips/bg_1.jpg"
local image = vips.Image.new_from_file(filename)

function random_edge(size)
	local edges = {
		{size/2,0},
		{size,size/2},
		{size/2,size},
		{0,size/2}
	}
	 local array = edges[math.random(1,4)]
	 --return unpack(edges[math.random(1,4)])
	 return array[1],array[2]
end

math.randomseed(tonumber(tostring(os.time()):reverse():sub(1,7)))

local size = 36
local radius = size/8--
local black = vips.Image.black(size+2*radius,160)

local mask = black:draw_rect(255,radius,radius,size,size,{fill = true})
local left1,top1 = random_edge(size)
mask = mask:draw_circle(255,radius+left1,radius+top1,radius,{fill = true})
local left2,top2 = random_edge(size)
mask = mask:draw_circle(0,radius+left2,radius+top2,radius,{fill = true})


left1 = math.random(160,image:width()-mask:width())
top1  = math.random(0,image:height()-mask:height())

left2 = math.random(50,160)
top2 = math.random(0,100)

crop = image:crop(left1,top1,mask:width(),mask:height())..mask
crop:write_to_file("/home/hzm/hzm/vips/square.jpg")

--make a transparent piece tp draw on the image 
transparent = (black..black..black..mask):copy{interpretation = "srgb"}
image = image:composite(transparent,"dest-out",{x=left1,y=top1})
image = image:composite(transparent,"dest-out",{x=left2,y=top2})

image:write_to_file("/home/hzm/hzm/vips/back.png")








--print("used time:"..e-s.."seconds")

**Comment by jcupitt** [comment]
Hi again, 

Those white holes aren't white, they are transparent. The white you see is the github page background showing through.

You could draw something solid in there, but of course you'd lose the transparency. Is that OK?

**Comment by hzm199822** [comment]
Yes, as long as it's not all white, it's too easy to recognize. I wonder if we can add some complex images to the transparency or something like this

**Comment by hzm199822** [comment]
![image](https://user-images.githubusercontent.com/68108652/100085550-20c24f80-2e87-11eb-8684-ef2f6be04c78.png)

**Comment by hzm199822** [comment]
Because your function is too complex. I can't understand the meaning of many parameters through the document. Can you help me change the code.

**Comment by jcupitt** [comment]
Your code makes the hole by combing the black square with the mask as the alpha, then using `dest-out` to cut the hole.

You could use any image instead of black and user `over` to lay it on top of the background. Does that sound OK?

You could also keep the transparency and add a shadow effect, which might look nice.

**Comment by hzm199822** [comment]
This is what I did myself
![image](https://user-images.githubusercontent.com/68108652/100086000-bd84ed00-2e87-11eb-84d2-924d09aabb74.png)
![image](https://user-images.githubusercontent.com/68108652/100086039-caa1dc00-2e87-11eb-8248-3891a75782b0.png)

**Comment by hzm199822** [comment]
I want to turn this white transparent shape into a shadow. Is there any way

**Comment by jcupitt** [comment]
Sure, blur and offset the mask, for example. Use `:gaussblur(blur_radius)`.

**Comment by hzm199822** [comment]
Can you modify it in our example? I don't understand these functions correctly, so I think I will fail to use them

**Comment by hzm199822** [comment]
I don't know which stage to use and how to use it. I think it can be understood from the command line that it is not a form at all in Lua function

**Comment by hzm199822** [comment]
![image](https://user-images.githubusercontent.com/68108652/100089306-70efe080-2e8c-11eb-98c9-3da2eb2cb3ae.png)

**Comment by hzm199822** [comment]
What should shadows do

**Comment by hzm199822** [comment]
How to turn transparent parts into shadows or complex images

**Comment by hzm199822** [comment]
How to add shadow effects
？？

**Comment by hzm199822** [comment]
There is another problem
![image](https://user-images.githubusercontent.com/68108652/100091264-579c6380-2e8f-11eb-8cb3-45664badd4f0.png)

![image](https://user-images.githubusercontent.com/68108652/100091296-6125cb80-2e8f-11eb-8165-10065c803d76.png)
write_to_file How can this function take so long?

**Comment by hzm199822** [comment]
Can there be a faster way to write files?

**Comment by jcupitt** [comment]
For example:

```lua
#!/usr/bin/luajit

vips = require "vips"

local filename = arg[1]
local image = vips.Image.new_from_file(filename)

function random_edge(size)
    local edges = {
        {size / 2, 0},
        {size, size / 2},
        {size / 2, size},
        {0, size / 2}
    }

    return unpack(edges[math.random(1, 4)])
end

math.randomseed(tonumber(tostring(os.time()):reverse():sub(1, 7)))

local size = 360
local radius = size / 8
local black = vips.Image.black(size + 2 * radius, size + 2 * radius)

local mask = black:draw_rect(255, radius, radius, size, size, {fill = true})
local left1, top1 = random_edge(size) 
mask = mask:draw_circle(255, 
    radius + left1, radius + top1, radius, {fill = true})
local left2, top2 = random_edge(size)
mask = mask:draw_circle(0, 
    radius + left2, radius + top2, radius, {fill = true})

local left = math.random(0, image:width() - mask:width())
local top  = math.random(0, image:height() - mask:height())
crop = image:crop(left, top, mask:width(), mask:height()) .. mask
print("writing square.jpg ...")
crop:write_to_file("square.jpg")

local hole = (black .. black .. black .. mask):copy{interpretation = "srgb"}
image = image:composite(hole, "dest-out", {x = left, y = top})

-- blur and offset the mask to make the shadow
local shadow_radius = 10
-- make the mask larger all around
local big_mask = mask:embed(shadow_radius, shadow_radius, 
    mask:width() + 2 * shadow_radius, mask:height() + 2 * shadow_radius)
local shadow = big_mask:gaussblur(shadow_radius)

-- and composite the shadow under the image
image = image:composite(shadow, "dest-over", {x = left, y = top})

print("writing back.jpg ...")
image:write_to_file("back.jpg", {background = 255})
```

To make eg.:

![back](https://user-images.githubusercontent.com/580843/100095028-ce1a7080-2e51-11eb-9803-f3334448e02e.jpg)

**Comment by jcupitt** [comment]
The slow speed you are seeing is because of PNG. Try again with JPG if you don't care about transparency.

**Comment by hzm199822** [comment]
It's strange that I spend a lot less time running this script on my own virtual machine than on a machine with better performance. Why? Mainly in this (write)_ To_ File) function, I checked the compilation libraries of the two machines. It seems that there are more libraries installed in the local virtual machine. Is there a problem here

**Comment by hzm199822** [comment]
This is a native virtual machine
linux-vdso.so.1 (0x00007ffe5a9d0000)
	libvips.so.42 => /usr/local/lib/libvips.so.42 (0x00007f8c3f18e000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f8c3f12e000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8c3f005000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c3ee13000)
	libMagickCore-6.Q16.so.6 => /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6 (0x00007f8c3eb47000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f8c3eb0f000)
	libimagequant.so.0 => /lib/x86_64-linux-gnu/libimagequant.so.0 (0x00007f8c3eafd000)
	libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f8c3ea7c000)
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f8c3e9f7000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f8c3e9f1000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f8c3e9c3000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f8c3e9aa000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f8c3e959000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f8c3e912000)
	libgsf-1.so.114 => /lib/x86_64-linux-gnu/libgsf-1.so.114 (0x00007f8c3e8ca000)
	libfftw3.so.3 => /lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f8c3e6c4000)
	liborc-0.4.so.0 => /lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f8c3e641000)
	liblcms2.so.2 => /lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f8c3e5e6000)
	libgif.so.7 => /lib/x86_64-linux-gnu/libgif.so.7 (0x00007f8c3e5d9000)
	librsvg-2.so.2 => /lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007f8c3dce9000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f8c3db08000)
	libpoppler-glib.so.8 => /lib/x86_64-linux-gnu/libpoppler-glib.so.8 (0x00007f8c3daa7000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f8c3d984000)
	libIlmImf-2_3.so.24 => /lib/x86_64-linux-gnu/libIlmImf-2_3.so.24 (0x00007f8c3d6a6000)
	libopenslide.so.0 => /lib/x86_64-linux-gnu/libopenslide.so.0 (0x00007f8c3d672000)
	libcfitsio.so.8 => /lib/x86_64-linux-gnu/libcfitsio.so.8 (0x00007f8c3d373000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8c3d350000)
	libwebpmux.so.3 => /lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007f8c3d146000)
	libwebpdemux.so.2 => /lib/x86_64-linux-gnu/libwebpdemux.so.2 (0x00007f8c3cf41000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f8c3ccd8000)
	libmatio.so.9 => /lib/x86_64-linux-gnu/libmatio.so.9 (0x00007f8c3cc75000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8c3cc59000)
	libexif.so.12 => /lib/x86_64-linux-gnu/libexif.so.12 (0x00007f8c3cc11000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c3cac2000)
	libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f8c3cab6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8c3ca41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8c3f6ba000)
	liblqr-1.so.0 => /lib/x86_64-linux-gnu/liblqr-1.so.0 (0x00007f8c3c833000)
	libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f8c3c679000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f8c3c5ba000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8c3c5a5000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8c3c468000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f8c3c453000)
	libltdl.so.7 => /lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f8c3c448000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f8c3c406000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c3c3eb000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f8c3c342000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f8c3c319000)
	libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f8c3c109000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8c3c103000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f8c3bffe000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f8c3bfe1000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007f8c3bfd6000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8c3bfcb000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f8c3bfbf000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f8c3bf97000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f8c3bf85000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f8c3bf25000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f8c3bef8000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8c3bedc000)
	libpoppler.so.97 => /lib/x86_64-linux-gnu/libpoppler.so.97 (0x00007f8c3bb97000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8c3b9b6000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f8c3b90f000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f8c3b90a000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8c3b8de000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f8c3b8cf000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f8c3b6c5000)
	libHalf.so.24 => /lib/x86_64-linux-gnu/libHalf.so.24 (0x00007f8c3b680000)
	libIex-2_3.so.24 => /lib/x86_64-linux-gnu/libIex-2_3.so.24 (0x00007f8c3b65f000)
	libIlmThread-2_3.so.24 => /lib/x86_64-linux-gnu/libIlmThread-2_3.so.24 (0x00007f8c3b655000)
	libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f8c3b52a000)
	libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f8c3b4d4000)
	libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f8c3b445000)
	libhdf5_serial.so.103 => /lib/x86_64-linux-gnu/libhdf5_serial.so.103 (0x00007f8c3b0c8000)
	libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f8c3aee2000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f8c3aeb3000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f8c3aea9000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f8c3ae52000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f8c3adc2000)
	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007f8c3ac73000)
	libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x00007f8c3ac41000)
	libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007f8c3ac01000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8c3abfb000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8c3abf3000)
	libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f8c3abca000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f8c3aba7000)
	librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f8c3ab87000)
	libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007f8c3ab19000)
	libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f8c3ab06000)
	libnettle.so.7 => /lib/x86_64-linux-gnu/libnettle.so.7 (0x00007f8c3aacc000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f8c3a8f6000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f8c3a8a7000)
	libldap_r-2.4.so.2 => /lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f8c3a851000)
	liblber-2.4.so.2 => /lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f8c3a840000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f8c3a832000)
	libsz.so.2 => /lib/x86_64-linux-gnu/libsz.so.2 (0x00007f8c3a82d000)
	libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f8c38d6c000)
	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007f8c38d37000)
	libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007f8c38d30000)
	libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007f8c38d2b000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f8c38d11000)
	libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f8c38b8f000)
	libhogweed.so.5 => /lib/x86_64-linux-gnu/libhogweed.so.5 (0x00007f8c38b55000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f8c38ad1000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f8c387fb000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f8c386c5000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f8c386af000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f8c385d0000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f8c3859f000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f8c38598000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f8c38589000)
	libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f8c3856c000)
	libgssapi.so.3 => /lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f8c38527000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f8c38502000)
	libaec.so.0 => /lib/x86_64-linux-gnu/libaec.so.0 (0x00007f8c384f9000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f8c384f2000)
	libheimntlm.so.0 => /lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f8c384e6000)
	libkrb5.so.26 => /lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f8c38453000)
	libasn1.so.8 => /lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f8c383aa000)
	libhcrypto.so.4 => /lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f8c38372000)
	libroken.so.18 => /lib/x86_64-linux-gnu/libroken.so.18 (0x00007f8c38359000)
	libwind.so.0 => /lib/x86_64-linux-gnu/libwind.so.0 (0x00007f8c3832f000)
	libheimbase.so.1 => /lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f8c3831d000)
	libhx509.so.5 => /lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f8c382cf000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f8c38292000)

![图片](https://user-images.githubusercontent.com/68108652/100180427-1b124b80-2f13-11eb-9588-f235d10fe9f3.png)




local vips = require "vips" 
local b = os.clock()
local filename = arg[1] 
local image = vips.Image.new_from_file(filename) 
function random_edge(size) 
	local edges = { {size / 2, 0},
		{size, size / 2},
		{size / 2, size},
		{0, size / 2} } 
	return unpack(edges[math.random(1, 4)]) end 
math.randomseed(tonumber(tostring(os.time()):reverse():sub(1, 7))) 

local size = 36 
local radius = size / 8 
local r = math.random(0,120)
local black = vips.Image.black(size + 2 * radius, 160) 

local mask = black:draw_rect(255, radius, radius+r, size, size, {fill = true})

local left1, top1 = random_edge(size) 
mask = mask:draw_circle(255, radius + left1, radius + top1 + r, radius, {fill = true}) 

local left2, top2 = random_edge(size)
mask = mask:draw_circle(0,radius + left2, radius + top2 + r , radius, {fill = true})
 
local left3 = math.random(160, image:width() - mask:width()) 
local top3 = math.random(0, 0) 

local left4 = math.random(50, 160) 
local top4 = math.random(0, 120)

local crop = image:crop(left3, top3, mask:width(), mask:height()) .. mask 
crop = crop * 1.4


local b1 = os.clock()
crop:write_to_file("square.png") 
local e1 = os.clock()

local b2 = os.clock()
local hole = (black .. black .. black .. mask):copy{interpretation = "srgb"}
image = image:composite(hole, "dest-out", {x = left3, y = top3}) 
image = image:composite(hole, "dest-out", {x = left4, y = top4})

-- blur and offset the mask to make the shadow 
local shadow_radius =15
 -- make the mask larger all around 
local big_mask = mask:embed(shadow_radius, shadow_radius, mask:width() + 2 * shadow_radius, mask:height() + 2 * shadow_radius) 
local shadow = big_mask:gaussblur(shadow_radius) 
-- and composite the shadow under the image
image = image:composite(shadow, "dest-over", {x = left3, y = top3}) 
image = image:composite(shadow, "dest-over", {x = left4, y = top4}) 
local e2 = os.clock()

local b3 = os.clock()
image:write_to_file("back.jpg", {background = 255})
local e3 = os.clock()
print(b1-b)
print(e1-b1)
print(e2-b2)
print(e3-b3)
print(e3-b)

**Comment by hzm199822** [comment]
This is a higher performance machine
linux-vdso.so.1 =>  (0x00007fff5634b000)
        libvips.so.42 => /usr/local/lib/libvips.so.42 (0x00007fd6f7d8d000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fd6f7b77000)
        libpng15.so.15 => /lib64/libpng15.so.15 (0x00007fd6f794c000)
        libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007fd6f76f7000)
        libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007fd6f74f3000)
        libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007fd6f7154000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fd6f6f04000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fd6f6bee000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fd6f69c4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd6f66c2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd6f64a6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd6f60e3000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd6f5ddc000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd6f5bc6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd6f59c2000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fd6f5760000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007fd6f5558000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fd6f5331000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd6f5117000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007fd6f4ed5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd6f8441000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007fd6f4c96000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fd6f4a91000)

       
![图片](https://user-images.githubusercontent.com/68108652/100180728-c7543200-2f13-11eb-8bef-317bd38f18fd.png)
