### ISSUE TITLE
VIPS Fails to recognize HEIC from iPhone 12

### ISSUE THREAD

**Issue by codydietrich** [libvips/libvips#1902]
It seems that an iPhone 12 produces HEIC images with slightly different bytes at the start of the file, which `libvips` fails to recognize as a HEIF file when trying to select which loader to use. Using `heifload` loads the files as expected.

**To Reproduce**
1. Use this HEIC image - [IMG_4631.HEIC.zip](https://github.com/libvips/libvips/files/5597913/IMG_4631.HEIC.zip)
2. Run any vips operation that does not specify a loader - `vips thumbnail IMG_4631.HEIC out.jpg 2000`
3. `libvips` does not recognize the file

**Expected behavior**
`libvips` should recognize this file as a HEIF file and use `heifload` to load the file

**Actual behavior**
`libvips` does not recognize the file

**Environment**
(please complete the following information)
 - OS: Ubuntu 18.04
 - Vips: 8.11.0
 - libheif: 1.9.1

**Comment by jcupitt** [comment]
Hi @codydietrich,

It's working for me with libvips built against git master libheif. 

```
john@yingna ~/pics $ vipsheader iphone12.heic 
iphone12.heic: 3024x4032 uchar, 3 bands, srgb, heifload
john@yingna ~/pics $ vips copy iphone12.heic x.jpg
john@yingna ~/pics $
```

I think we probably just need to be patient and wait for libheif updates to percolate through.
