### ISSUE TITLE
PNG with huge metadata fails with zTXt: chunk data is too large

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1903]
**Describe the bug**

This PNG with some huge metadata - https://www.dropbox.com/s/pwrtywnlg2lahc2/huge.png?dl=0 - can't be read by vips, but works just fine with imagemagick. It just throws a "zTXt: chunk data is too large" warning and is then unable to proceed

Maybe this is on purpose, then it's fine for me (I currently just fall back to imagemagick when that happens, convert it to a PNG without that metadata and reread it vips, as it's a very uncommon case for us)

**To Reproduce**
1. Use Image https://www.dropbox.com/s/pwrtywnlg2lahc2/huge.png?dl=0
2. Use Configuration. Used vips 8.10.3 - had some compilation problems with master, 
3. 

```
$ vips VipsCopy huge.png lala.png

(vips:48): VIPS-WARNING **: 07:07:27.045: zTXt: chunk data is too large

(vips:48): VIPS-WARNING **: 07:07:27.046: zTXt: chunk data is too large
png2vips: unable to read source huge.png
```

**Expected behavior**
No error happens. The image is read and ready for transformations.

**Actual behavior**
See above.

**Environment**
(please complete the following information)
 - OS: Amazon Linux and MacOS
 - Vips: [e.g. 8.8, 8.9, etc]

**Comment by lovell** [comment]
Did you see https://sourceforge.net/p/libpng/bugs/270/ ?

**Comment by jcupitt** [comment]
Hello, I just got around to looking at this, and the sample image is gone. Does anyone still have a copy?

**Comment by chregu** [comment]
Ooops. It's back there, sorry about that.

**Comment by jcupitt** [comment]
I see the error with libpng:

```
$ vipsheader ~/huge.png
(vipsheader:2154209): VIPS-WARNING **: 15:27:56.374: zTXt: chunk data is too large
```

libspng works fine:

```
$ vipsheader ~/huge.png
/home/john/huge.png: 1200x800 uchar, 4 bands, srgb, pngload
```

I'll check the libpng docs and see if the limit can be raised at runtime somehow.

**Comment by jcupitt** [comment]
Ah I thought this seemed familiar. We did this a while ago, I just couldn't see if on a quick search.

```C
        /* By default, libpng refuses to open files with a metadata chunk 
         * larger than 8mb. We've seen real files with 20mb, so set 50mb.
         */
#ifdef HAVE_PNG_SET_CHUNK_MALLOC_MAX
        png_set_chunk_malloc_max( read->pPng, 50 * 1024 * 1024 );
#endif /*HAVE_PNG_SET_CHUNK_MALLOC_MAX*/
```

Your file has a mind-boggling 102MB metadata chunk.

Do you need to be able to read this @chregu, or would a warning (eg. "102mb metadata chunk ignored") be OK?

**Comment by jcupitt** [comment]
Actually, a warning would be tough since libpng treats chunk out of size bounds as an error, and aborts read. I think all we can do is raise the limit.

**Comment by jcupitt** [comment]
I tried raising the limit to 150mb and the image reads now, but with a warning:

```
$ vipsheader huge.png 
(vipsheader:48772): VIPS-WARNING **: 17:32:26.351: zTXt: truncated
huge.png: 1200x800 uchar, 4 bands, srgb, pngload
```

So the metadata chunk is zlib-compressed text, and it's been truncated! So it won't read anyway.

Raising the limit starts starts to get into DoS attack territory, so I think it's best to leave it at 50mb. 

Another fix is to switch to libspng for PNG read. It handles this is a saner manner.

**Comment by jcupitt** [comment]
Thanks for the report, by the way, it's always interesting to see the crazy image files that people come across.

**Comment by chregu** [comment]
Thanks to you, too. Switching to libspng  was on our TODO list anyway and looks like that will solve the problem for us.
