### ISSUE TITLE
pixel median of band stack

### ISSUE THREAD

**Issue by indus** [libvips/libvips#1904]
I have a timeseries of images and want to process them in python to get the median for every pixel (preferable weighted median to tweak the output by available quality information for every image). Is there a way to do this with libvips?
```bandrank``` seems to go in that direction, but it is unclear to me how to sort the images/bands/pixels (and even less how to apply weighting).
Suggestions welcome.

**Comment by jcupitt** [comment]
Hi @indus,

Yes, bandrank does this, but it's not weighted, as you say.

You can trick it into do more complex weighting by scaling images before calling bandrank, and by hiding an image id in the bottom few bits. If you only have a few images, a set of if-then-else tests might be quicker and easier.

**Comment by jcupitt** [comment]
... and you can use `case` to turn an array of image ids back into an RGB image.

**Comment by indus** [comment]
Thanks for the hint. I have to give it a try. I'm closing this for now but propably report back later.
