### ISSUE TITLE
How to create a BIGTIFF white image ?

### ISSUE THREAD

**Issue by gvincke** [libvips/libvips#1905]
Hi @jcupitt ,
I hope you are in good health,
I was wandering how to create a white 8-bit sRGB BIGTIFF file.
Here is my goal : i work in Digital Pathology. I have 5 images that are zones that have been scanned on a glass slide. I want to regroup them in a single image at the exact position they had on the slide.
My idea was :
1) create a white TIFF image with the slide dimension (width : 203781px, height: 73733px). For now i used :
`vips xyz slide.tiff[bigtiff,compression=jpeg,tile] 203781 73733 --csize 1`
this to have a 8-bit sRGB file needed by vips insert for step 2
2) place my 5 images on this white BIGTIFF using :
`vips insert slide.tiff sample-i.tiff slide-i.tiff x y width heigth` and so on 5 time by re using the output image as input for next insert;
3) create a pyramidal image to be used by openslide : `vips tiffsave final-slide.tiff  final-slide.pyr.tiff  --tile --pyramid --compression jpeg -Q 95 --tile-width 256 --tile-height 256 --bigtiff`
==> by now only the first step is a problem for me : create a 8-bit sRGB white file.
Observations :
`vips black`  gives me a one band (b-w) image but not a sRGB
`vips grey` gives me a 2 band image (i need 3 for `vips insert` to include the 3 band sRGB samples images)
`vips xyz` gives me 32 bit image that leads to errors at step 2 with `vips insert`

Using `vips xyz slide.tiff[bigtiff,compression=jpeg,tile] 203781 73733 --csize 1` i succeed to do all the steps but the background color (color where there is no sample) is yellow, not white.
==> how to do the same, but creating a white image ?
Thanks for your advises.
Have a nice day.
Grégoire

**Comment by jcupitt** [comment]
Hi @gvincke,

I would use something like python or ruby -- they will be much quicker than the CLI, since they won't need any huge intermediate files, and you won't need to worry about what format they are in.

In Ruby, for example you could write:

```ruby
require 'vips'

image = Vips::Image.black 203781, 73733
slide1 = Vips::Image.new_from_file "slide1.tiff", access: :sequential
image = image.insert slide1, 102345, 12334
# etc. for slide2, finally:
image.tiffsave "final.tif", bigtiff: true, pyramid: true, compression: :jpeg, Q: 85, tile_width 256, tile_height: 256, bigtiff: true
```

**Comment by jcupitt** [comment]
Python is the same with the obvious small syntax changes:

```python
import pyvips

image = pyvips.Image.black(203781, 73733)
slide1 = pyvips.Image.new_from_file("slide1.tiff", access="sequential")
image = image.insert(slide1, 102345, 12334)
# etc. for slide2, finally:
image.tiffsave("final.tif", bigtiff=True, pyramid=True, compression="jpeg", Q=85, tile_width=256, tile_height=256, bigtiff=True)
```

**Comment by jcupitt** [comment]
If you have to use the CLI, try:

```
vips black image.tiff 203781 73733 --bands 3
```

But it will be extremely slow. Python/Ruby/PHP/C#/Lua/Javascript etc. will be (a guess) 100x faster.

**Comment by gvincke** [comment]
@jcupitt ,
I always used vips in CLI, and just went to try it with python using pyvips : difference of speed and storage burden is indeed impressive !!!!!
Thanks to have spot this on !
I succeed to adapt your script to have the image i need, except that background is black, instead of white.
How can i set that image set by `image = pyvips.Image.black(203781, 73733)` is white instead of black ?
Thank you !
Grégoire

**Comment by jcupitt** [comment]
Just add 255, eg.:

```python
image = pyvips.Image.black(203781, 73733) + 255
```

That'll make a float image, so you'll need to cast down to 8 bits:

```python
image = pyvips.Image.black(203781, 73733) + 255
image = image.cast("uchar")
```

**Comment by jcupitt** [comment]
Where do your `"slide1.tiff"` files come from? You might be able to just load the openslide images directly and not use the tiff intermediates.

**Comment by gvincke** [comment]
> Where do your `"slide1.tiff"` files come from? You might be able to just load the openslide images directly and not use the tiff intermediates.

From a collection of old tiff files used by a partner. Some are crops of the same slide, and my goal is to rebuild the original slide.

**Comment by gvincke** [comment]
> Just add 255, eg.:
> 
> ```python
> image = pyvips.Image.black(203781, 73733) + 255
> ```
> 
> That'll make a float image, so you'll need to cast down to 8 bits:
> 
> ```python
> image = pyvips.Image.black(203781, 73733) + 255
> image = image.cast("uchar")
> ```

PERFECT !
Thanks you so much !
Have a nice WE.
Grégoire
