### ISSUE TITLE
icc_transform writes image data to stdout if output filename starts ./

### ISSUE THREAD

**Issue by barryspearce** [libvips/libvips#1906]
**Describe the bug**
icc_transform is writing the image data to std output instead of the output file specified if the output filename starts with ./

**To Reproduce**
Use any image, in the current directory or in a sub directory - it doesn't matter where as long as it can be pathed below the current directory.

vips icc_transform test.jpg ./test.sRGB.jpg sRGB --intent perceptual

which fails vs

vips icc_transform test.jpg test.sRGB.jpg sRGB --intent perceptual

which works.

**Expected behavior**
The image data should be written to the specified output file.

**Actual behavior**
The image data is written to stdout.

**Screenshots**
n/a

**Environment**
 - OS: Manjaro (fully up to date on a 5.4.74 kernel)
 - Vips: 8.10.1-1

**Comment by jcupitt** [comment]
Hello @barryspearce, yes, libvips will do this for any operation with any filename that starts with a dot, for example:

```
vips copy x.jpg .jpg
```

But the rule will also catch things like:

```
vips copy x.jpg ./y.jpg
```

Which is obviously undesired behaviour.

I suppose when testing it should really start from the end of the filename, work right-to-left to find the final dot, then see if that is also the first character. Yuk.

**Comment by jcupitt** [comment]
OK, should be fixed, thanks for pointing this dumb problem out. I've credited you in the changelog.

The fix will be in 8.10.3.
