### ISSUE TITLE
Possible way to lower memory usage?

### ISSUE THREAD

**Issue by lamka02sk** [libvips/libvips#1907]
I am writing a simple image processing server in Rust with libvips crate (C bindings) and actix_web framework.
The problem is that each request allocates more and more memory (about 40-60MB per request) and it only stabilizes when it hits about 6GB, which is a lot. My guess is that it's all just some kind of in-memory cache, but I am not sure. Is it possible to clear this excess memory after every request somehow?
The allocations happen only when calling thumbnail function with options passed, if I don't pass any options to thumbnail, the memory stays the same, but of course, I can't really do any processing :)
```rust
    let options = ThumbnailOptions {
        height: 200,
        size: Size::Both,
        no_rotate: false,
        crop: Interesting::Centre,
        linear: false,
        import_profile: "sRGB".to_string(),
        export_profile: "sRGB".to_string(),
        intent: Intent::Relative
    };

    let image = libvips::ops::thumbnail_with_opts("data/image.jpg", 600, &options).unwrap(); // <- memory allocated here
```
Thank you

**Comment by jcupitt** [comment]
Hello @lamka02sk,

That sounds like an interesting project.

The memory use sounds too high -- I would guess you have some kind of unref problem. How are you handling unref, how large are these images, and what version of libvips are you using? What does `.unwrap()` do?

I tried a tiny Python benchmark (this should have the same memory behaviour as Rust):

```python
#!/usr/bin/python3

import sysy
import pyvips

for filename in sys.argv[1:]:
    thumb = pyvips.Image.thumbnail(filename, 600, height=200, size="both",
            crop="centre", import_profile="srgb", export_profile="srgb")
    data = thumb.write_to_memory()
```

I ran it like this:

```
$ vipsheader ~/pics/nina.jpg
/home/john/pics/nina.jpg: 6048x4032 uchar, 3 bands, srgb, jpegload
$ mkdir sample
$ for i in {1..1000}; do cp ~/pics/nina.jpg sample/$i.jpg; done
$ /usr/bin/time -f %M:%e ./thumb.py sample/*.jpg
136548:55.34
```

And watched memory use in "top". RES settled at about 130MB by iteration 100 and stayed fairly level. Max RES was 136MB. This is with libvips 8.10 on Ubuntu 20.04.

**Comment by lamka02sk** [comment]
Hi @jcupitt,
I will do some more in-depth testing today after work and let you know how it goes.
Rust should handle all unrefs automatically by itself when the function ends, so I will also check how the binding library works, maybe there is some mistake in there.
The amount of memory also depends on which image I try to process. With some, it is "just" 2GB, with another it is 6GB. All images I test with are at max. 5MB in size (not too much).

**Comment by jcupitt** [comment]
You will need to call `g_object_unref()` on all libvips references somehow. For example, the C++ API uses this as a base class:

https://github.com/libvips/libvips/blob/master/cplusplus/include/vips/VImage8.h#L61-L188

It will call `g_object_ref()` and `g_object_unref()` as references are created, copied and freed. 

The python API is simpler:

https://github.com/libvips/pyvips/blob/master/pyvips/gobject.py#L112-L127

It registers `g_object_unref()` as a finalizer for every GObject reference.

If you call `vips_object_print_all()`, libvips will print a table of every object with live references. It can be a useful way to spot reference leaks. 

If you set the env var `VIPS_LEAK`, libvips will dump a table of leaked object references on exit, plus the memory high-water mark:

```
$ VIPS_LEAK=1 vips invert ~/pics/nina.jpg x.jpg
memory: high-water mark 46.51 MB
```

**Comment by jcupitt** [comment]
libvips has an object cache which you could try disabling, but I think it's more likely that you have a reference leak. 8.10 has a smaller default cache, I would make sure you're using that.

You can disable the cache with `vips_cache_set_max(0);`, docs here:

https://libvips.github.io/libvips/API/current/VipsOperation.html#vips-cache-set-max

**Comment by lamka02sk** [comment]
So, I update my vips installation to 8.10.2 and I also use Ubuntu 20.04, just like you mentioned, so there should be minimal differences between our environments.
I also tried to run your script first and the results were:
```
$ vipsheader ./josh-withers-zD4RXNVvnPE-unsplash.jpg 
./josh-withers-zD4RXNVvnPE-unsplash.jpg: 3640x5464 uchar, 3 bands, srgb, jpegload
$ mkdir sample
$ for i in {1..1000}; do cp ./josh-withers-zD4RXNVvnPE-unsplash.jpg sample/$i.jpg; done
$ /usr/bin/time -f %M:%e ./thumb.py sample/*.jpg
773260:308.72
```
My results are 755MB of memory...which is a lot more than you measured.
Now I wanted to try the same in my Rust program. I created new empty route, initialized VipsApp (which I didn't do before) and ... it always crashed on 2nd request (1st request is ok). I found out, VipsApp is the reason it crashes, when I remove it, everything works. I measured around 260MB of peak memory.
When the crash happens, there are these errors:
```
(Test Libvips:1551806): GLib-CRITICAL **: 18:06:59.526: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(Test Libvips:1551806): GLib-CRITICAL **: 18:06:59.526: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(Test Libvips:1551806): GLib-CRITICAL **: 18:06:59.526: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(Test Libvips:1551806): GLib-CRITICAL **: 18:06:59.526: g_hash_table_lookup: assertion 'hash_table != NULL' failed

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
I tried to find what it means, but there is not much about this out there.

**Comment by jcupitt** [comment]
Huh it seems very slow too: I'm more than 5x faster. I wonder what's going on? This PC is a 4 core i7-6700, fwiw.

I'll try to make a dockerfile, perhaps we can get consistent results that way.

What Rust binding are you using?

**Comment by jcupitt** [comment]
I would guess your error error is from `vips_init()` not being called, if that helps.

**Comment by lamka02sk** [comment]
I was running it on my laptop with Ryzen 4700U, which should be pretty much on paar with yours in single-threaded performance. Laptop was on AC and I had CPU boost clock maxed out the whole time.
This is the Rust binding I am using: https://crates.io/crates/libvips. In the last try I also used the example from README just to be sure: https://github.com/olxgroup-oss/libvips-rust-bindings
Is it possible that when I create app with VipsApp, it somhow stays opened somewhere and when second request tries to initialize new VipsApp with the same name it fails?

**Comment by lamka02sk** [comment]
> Is it possible that when I create app with VipsApp, it somhow stays opened somewhere and when second request tries to initialize new VipsApp with the same name it fails?

I think this is the case, I just moved the VipsApp creation in main function before framework initialization and it works

**Comment by jcupitt** [comment]
I made a quick dockerfile:

https://github.com/jcupitt/docker-builds/blob/master/libvips-ubuntu18.04/Dockerfile

I see:

```
$ docker pull ubuntu:bionic
$ docker build -t libvips-ubuntu18.04 .
$ docker run -it --rm -v $PWD:/data libvips-ubuntu18.04 
root@936864e667b1:/usr/local/src# cd /data
root@936864e667b1:/usr/local/src# wget -q https://images.unsplash.com/photo-1585258769225-995099be2116
root@936864e667b1:/usr/local/src# mkdir sample; for i in {1..1000}; do cp photo-1585258769225-995099be2116 sample/$i.jpg; done
root@936864e667b1:/usr/local/src# /usr/bin/time -f %M:%e ./thumb.py sample/*.jpg
128404:42.75
```

It's a bit quicker since this makes a release build. Do you see comparable memory use on your machine?

**Comment by jcupitt** [comment]
Ah I didn't know Augusto had finished that binding, that's great.

I would check for reference leaks. Try `VIPS_LEAK=1 ./my-test-program` and hopefully you'll get no output.

**Comment by lamka02sk** [comment]
I just finished running my Rust program with VIPS_LEAK enabled and example code from bindings README. After running 10k requests, the output was: `memory: high-water mark 685.51 MB`. After processing  only 1 request, the output is around 86MB, which means, each thread/worker/CPU core only should allocate around 86MB of memory (considering I have 8 CPU cores). Unfortunately the actual peak memory usage was up to 3.4GB. It is rising slowly, but still.
I will also try to run the docker image you provided to see if the problem occurs also with CLI version of vips.

**Comment by lamka02sk** [comment]
Ok, the results from Docker are almost exactly the same as yours :)
`129536:50.32`

**Comment by jcupitt** [comment]
Yes, that sounds reasonable. Memory use will scale with the number of threads -- try:

```
VIPS_CONCURRENCY=1 ./some-test-prog
```

And it'll run with a threadpool size of 1, which should help.

**Comment by lamka02sk** [comment]
Yes, the CLI version runs fine. But unfortunately it looks like there is some kind of leak in Rust bindings, because 3.4GB is a lot for 8 threads and it was only 10k requests. I left the program running during night (100k request) and the memory usage at the end was 5.2GB (vs. 3.4GB after 10k requests). After all requests finished, it was still consuming 4.2GB of memory (vs. 2.3GB after 10k requests). 
10M requests on framework itself (no vips) used at maximum 65MB of memory (stabilised after 100K), so there definietely has to be something that is not cleared after work is done.

**Comment by lamka02sk** [comment]
I guess I will try to call CLI from Rust and see what happens

**Comment by jcupitt** [comment]
Yes, it sounds like those rust bindings have some kind of reference count bug. Someone needs to look through it and fix the leak.

Calling `vipsthumbnail` with `system()` would be a fix, if that's all you need. If you want to do something fancy, you probably need to use something like pyvips and shell out to that.
