### ISSUE TITLE
Error: glib: Error creating thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by mscherer82** [libvips/libvips#1911]
**Error message:**
glib: Error creating thread: Resource temporarily unavailable
vips2png: unable to write to target target

The error occurs on my linux server. On my local windows machine it works fine.

**Code:**

sharp(fileData).resize(300, 200).png({ quality: 90 }).toBuffer();

**Environment**
 - OS:  Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0 x86_64)
 - Vips: 8.10.0-linux-x64

Please let me know what additonal information I can provide.
Thank you.

**Comment by jcupitt** [comment]
Hello @mscherer82, sorry, I don't know.

Perhaps you have hit the thread limit? Linux has a limit to the number of threads that can exist in one process.

**Comment by jcupitt** [comment]
Here's a useful answer:

https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

It could be systemd, or perhaps your docker, or perhaps your shell.

**Comment by mscherer82** [comment]
Thank you very much. It actually has to do with how many processes are running on my machine. When stopping some of them the upload works fine again. I havn't found out which value exactly causes the problem because all the limits seems to be set to a high value.
