### ISSUE TITLE
ppmsave and header metadata

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1913]
The current implementation of ppmsave is writing a timestamp information to the header of the output image file. While this is allowed syntax, it is rarely used in practice. Sometimes it is desirable to not have any such metadata/comments written to the image file, e.g. to allow checking for identity of two images based on some simple hash value. Unfortunately the timestamp is written to the header even if I am using the "strip" option which normally should suppress the writing of metadata.

Is this done on purpose or should it better skip the writing of timestamp information when supplying the "strip" option?

**Comment by jcupitt** [comment]
Good idea! It's in git master.

**Comment by ewelot** [comment]
The latest patch introduced a regression. Accidentally the strip option also removed the magic number from output. Could you please fix this?
