### ISSUE TITLE
ppmsave: regression from recent commit

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1917]
**Describe the bug**
There is a regression introduced by [this commit](https://github.com/libvips/libvips/commit/970ba8cfcc84d83c65687acd64192b3f9121b7b2): the magic number is accidentally removed from PPM header when setting the `strip` option.

**To Reproduce**
Any use of `ppmsave`with `strip=true`

**Expected behavior**
The magic number must be written to the output file regardless of using the `strip` option.

**Environment**
 - OS: Debian Linux 10
 - Vips: 8.10.2 patched with recent changes to ppmsave and ppmload

(note: the referenced commit is a result of [this discussion](https://github.com/libvips/libvips/issues/1913))

**Comment by jcupitt** [comment]
Hello, this was fixed yesterday with: https://github.com/libvips/libvips/commit/d58105aac603dae4b76ac1689199dede2c5ea093

**Comment by ewelot** [comment]
I didn't know it was fixed already ... thanks!
