### ISSUE TITLE
v8.10.3 Version release date?

### ISSUE THREAD

**Issue by david-taggun** [libvips/libvips#1920]
Hey team,

Just wanting to get a feel on when release 8.10.3 will be dropping? There are some bugfixes in there that I'm waiting for around HEIC files etc. 

I've seen echos around the issues that it'll be in a few days aka 18 days ago.

Love your work by the way!

Cheers.

**Comment by jcupitt** [comment]
Hi @david-taggun,

Someone just needs to do the work. Unfortunately I have a huge deadline coming up in the next week or so (a large, three-year project is winding up) and I don't really have time right now.

Once my deadline has passed I'll be back on libvips.

**Comment by david-taggun** [comment]
Yeah, no worries mate! Goodluck with your project wrap up 😀
