### ISSUE TITLE
howto truncate values to a given range

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1922]
I am trying to subtract two images and truncate the result to a given range, e.g. for 16bit integer images to 0 - 65535. The idea behind is that there is no negative signal/intensity in real images. I have tried subtract() and casting the result type but this would simply wrap negative values around the maximum value (like C does). What is the best way to achieve this? Maybe I have overlooked some simple libvips function which does the truncation?

Thanks for help,
Thomas

**Comment by jcupitt** [comment]
Hello @ewelot,

Casting will truncate range to the type range (it's a saturated cast), for example:

```
john@yingna ~/pics $ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x.max()
255.0
>>> x.format
'uchar'
>>> x += 12.2
>>> x.max()
267.20001220703125
>>> x.format
'float'
>>> x = x.cast("uchar")
>>> x.max()
255.0
>>> x.format
'uchar'
```

So just cast to `ushort` in your case, I think.

**Comment by ewelot** [comment]
I have to slightly correct my initial observation: a negative value is NOT wrapped around the maximum value of the given data range but it is actually replaced by the maximum value - instead of the minimum value (0). There is no problem in adding, which means any value above maximum is replaced by the maximum (as shown by your example). So to me it looks rather like a bug in the implementation of cast() function, isn't it?

I am attaching a test case example (two images and a small python program).
[subimages.zip](https://github.com/libvips/libvips/files/5658742/subimages.zip)

**Comment by jcupitt** [comment]
Huh you're right, it looks like int -> ushort fails for negatives. I'll investigate. Thanks!

**Comment by jcupitt** [comment]
I think it's fixed in 8.10 HEAD. This should be in 8.10.3. Thanks for reporting this dumb thing.

I added some more tests as well.

**Comment by ewelot** [comment]
That's great! I'll test later on.
Despite this issue, I'd like to know if there is a simple way of thresholding an image, e.g. to replace all values below (or above) this threshold by the threshold value?

**Comment by jcupitt** [comment]
I use `ifthenelse`, eg.:

```python
y = (x > 100).ifthenelse(100, x)
```

**Comment by ewelot** [comment]
I can confirm the latest fix does solve the issue.

About thresholding. Does it work the same way with 3-band images (e.g. rgb) and providing a vector containing 3 different thresholds to be applied bandwise?

**Comment by jcupitt** [comment]
That's right `(x > 100)` makes a three band boolean image.

**Comment by ewelot** [comment]
Can I use a vector in this expression, like `(x > (60, 100, 80))` to apply different thresholds for each band?

**Comment by jcupitt** [comment]
Sure, eg. `(x > [10, 20, 30]).ifthenelse([30, 40, 50], 255)`.

**Comment by ewelot** [comment]
Your help is much appreciated, and thanks again for the fix!
