### ISSUE TITLE
question get exact diff image.

### ISSUE THREAD

**Issue by zzjin** [libvips/libvips#1923]
I need real diff two images  to give least common part as new image.
but after some issue search I find dE76 most match.

command is: `vips dE76 c_ori.png c_chg.png c_diff.png`

| What I want is:(using ps) | But What I got: |
| --- | --- |
| ![want](https://user-images.githubusercontent.com/679757/101483071-97387480-3992-11eb-95b9-818097b6fe6e.png) |  ![got](https://user-images.githubusercontent.com/679757/101483090-9ef81900-3992-11eb-9871-ff068ac1e6ad.png) |
| origin image: | changed image: |
| ![origin](https://user-images.githubusercontent.com/679757/101483005-8425a480-3992-11eb-9e73-1c21ddafca86.png) |  ![changed](https://user-images.githubusercontent.com/679757/101483017-8982ef00-3992-11eb-8b72-2a9255f67e11.png) |

**Edit:** using combined command did the work:
```shell
vips relational origin.png changed.png sub_diff.png noteq
vips bandbool sub_diff.png sub_diff2.png or
vips ifthenelse sub_diff2.png changed.png ../images/empty.png diff.png
```
**imagemagick** version:
```shell
magick compare -compose dst-in -lowlight-color none changed.png origin.png diff.png
```
But wonder if there will be one api could do this.

**Comment by jcupitt** [comment]
Hi @zzjin, the vips CLI is pretty basic -- I'd use something like Python / Ruby / Lua etc. for more complex tasks.

In this case you could write (untested):

```python
orig = pyvips.Image.new_from_file("...")
new = pyvips.Image.new_from_file("...")
alpha = (abs(a - b) > 10).bandbool()
diff = alpha.ifthenelse(new, 0).bandjoin(alpha)
```

ie. make an alpha (a mask) with 255 for the changed areas, then output an RGBA image with just the new pixels.

**Comment by zzjin** [comment]
thanks for response!
```python
mask = (abs(orig - new) > 0).bandor()
```
will this translate to raw c language impl? since golang do not allow operator overloading like Python/C++
BTW,I think I will try using `vips_subtract `

**Comment by jcupitt** [comment]
Sure, the C equivalent would be something like (untested):

```C
{
    VipsImage **t = (VipsImage **)
                vips_object_local_array( VIPS_OBJECT( scope ), 1 );

    if( vips_subtract( orig, new, &t[0], NULL ) ||
        vips_abs( t[0], &t[1], NULL ) ||
        vips_relational_const1( t[1], &t[2], VIPS_RELATIONAL_MORE, 0.0, NULL ) ||
        vips_bandbool( t[2], &t[3], VIPS_BANDBOOL_OR, NULL ) )
            return(-1 )
}
```

**Comment by zzjin** [comment]
Exact worked! Thanks!
just using works fine: 
```c
if (vips_subtract(ori, chg, &t[0], NULL) ||
		vips_bandbool(t[0], &t[1], VIPS_OPERATION_BOOLEAN_OR, NULL) ||
		vips_ifthenelse(t[1], chg, empty, &t[2], NULL))
		vips_error_exit(NULL);
```
