### ISSUE TITLE
Creating ramp image

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#1925]
I am trying to create a 1D ramp image where each pixel value is set to the column index. Unfortunately I am not able to find the python equivalent of any of the following C functions: `vips_identity(), vips_xyz(), vips_grey()`. Am I missing something? Any hint is appreciated.

**Comment by ewelot** [comment]
I could probably use something like `pyvips.Image.new_from_array(range(256))` but still I'd like to know if there is a python equivalent of the mentioned functions.

**Comment by jcupitt** [comment]
Hi again, they are class methods, eg. `ramp = pyvips.Image.identity()`.

**Comment by ewelot** [comment]
I see, but how do I know which function (e.g. on [this list](https://libvips.github.io/libvips/API/current/func-list.html)) is a normal function and which one is a class method? I suppose all the create functions are class methods but what about other groups?

**Comment by jcupitt** [comment]
The pyvips docs have examples:

https://libvips.github.io/pyvips/vimage.html#pyvips.Image.identity

Every operation which has no input image arguments is wrapped as a class method.

**Comment by ewelot** [comment]
Ah, I was not aware of this docs. This helps a lot, thanks again.
