### ISSUE TITLE
Broken link on documentation home page

### ISSUE THREAD

**Issue by electroly** [libvips/libvips#1928]
**Describe the bug**
On the page <https://libvips.github.io/libvips/API/current/>, the "VIPS website" link is broken. It points to 
<https://libvips.github.io/usr/share/gtk-doc/html/libvips/> but this address returns a 404 error.

**To Reproduce**
1. Open <https://libvips.github.io/libvips/API/current/>
1. Click "VIPS website" in the sentence "The latest version of this documentation..."

**Expected behavior**
The link should work.

**Actual behavior**
Browser shows a 404 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/171909/101995389-e2f36280-3c9f-11eb-932b-704e7d825124.png)

**Environment**
(please complete the following information)
- N/A

**Comment by jcupitt** [comment]
Hello @electroly !

I think I've fixed it -- the link in the XML was being rewritten by the script that made the pages for the docs. I'll regenerate the docs once 8.10.3 is out of the door.

Thank you for reporting this dumb thing.

**Comment by jcupitt** [comment]
Updated docs are there, and the link seem to work now.
