### ISSUE TITLE
PNG with huge metadata also fails with libspng with pngload: non-recoverable state

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1930]
**Describe the bug**

Same problem as in #1903, but with libspng. An image with huge metadata (https://www.dropbox.com/s/pwrtywnlg2lahc2/huge.png?dl=0 ) fails to parse correctly

**To Reproduce**
1. Use Image https://www.dropbox.com/s/pwrtywnlg2lahc2/huge.png?dl=0 with vips 8.10.3
2. Use Configuration '....'
3.

```
$ vips VipsCopy huge.png convert.png
pngload: non-recoverable state
vips2png: unable to write to target convert.png
``` 
(`vipsheader` works, though)

Also happens with the following (smaller, but still way too much metadata) image: https://www.dropbox.com/s/4voxjv5nme8v1tp/huge-meta.png?dl=0
That one works, when I use libpng instead of libspng

**Expected behavior**
No error happens. The image is read and ready for transformations.

**Actual behavior**
See above

**Environment**
(please complete the following information)
 - OS: Amazon Linux 2
 - Vips: 8.10.3

**Comment by chregu** [comment]
Since this doesn't happen on load of the image, but later, when we apply the operations (when doing copy or save), it's a little bit harder to fix like in the other bug (strip the metadata with imagemagick, then just reload the image). 

But could also be done, if such huge PNGs just are not meant to be parsed by vips.

**Comment by jcupitt** [comment]
Oh no! When I tested with libspng I only used vipsheader, it didn't occur to me that it might fail during read. I'll have a look.

**Comment by chregu** [comment]
And now I found a smallish PNG, which also fails with libspng, but does work with libpng (and imagemagick)

https://www.dropbox.com/s/5n4bs6vaunm5g41/logo.png?dl=0

**Comment by jcupitt** [comment]
Yes, I see the read failure with your huge PNG as well.

Let's pass this on to the libspng maintainer. I'm sure he'd be interested.

Your second image works for me with git master spng:

```
john@yingna ~/pics $ vipsheader broken-sbit-chunk.png 
broken-sbit-chunk.png: 140x110 uchar, 4 bands, srgb, pngload
john@yingna ~/pics $ vips copy broken-sbit-chunk.png x.jpg
john@yingna ~/pics $
```

So that one's probably been ticked off.

**Comment by jcupitt** [comment]
OK, I've handed this over to randy.

**Comment by chregu** [comment]
Thanks a lot

**Comment by randy408** [comment]
> Oh no! When I tested with libspng I only used vipsheader, it didn't occur to me that it might fail during read. I'll have a look.

This is because `spng_get_ihdr()` will only read the header, the first ~30 bytes.

**Comment by jcupitt** [comment]
True, but `vipsheader` is calling `spng_get_phys()` as well, and that appears to return successfully.

**Comment by randy408** [comment]
The `spng_get_<chunk>()` functions trigger parsing up to the image data or the end of the file, depending on the situation. But for `spng_get_ihdr()` this is not the case, so a parsing-related error can be returned from e.g. `spng_get_trns()` followed by the less useful `non-recoverable state` for subsequent calls.
