### ISSUE TITLE
How to replace color starting from the border ?

### ISSUE THREAD

**Issue by gvincke** [libvips/libvips#1936]
Hi @jcupitt 
Following the discussion in #872 on how to replace color from the image, (script works, thanks !) i realize that my topic is quite different : i would like not to replace all occurence of a color in the image, but only areas of that color that are reaching the borders  of the image. 
At the end it's to be used on digital pathology images, but here is a example with a small image : 
![8](https://user-images.githubusercontent.com/1370541/102615731-b2477900-4136-11eb-861d-827bcd9957b9.png)

After process i would like to have the same image but with black area touching the borders (and only in theses areas) replaced by grey (#999999; [153,153,153]) for example : 
![8-grey](https://user-images.githubusercontent.com/1370541/102615853-e327ae00-4136-11eb-84b7-2d5a921ea369.png)
Do you think it is possible using pyvips ?
Thank you in advance for any advise.
Grégoire

**Comment by jcupitt** [comment]
Hi @gvincke,

Sure, you can flood-fill from the edges. You start at pixel (0, 0) (for example) and find all pixels with the same value which are connected up/down/left/right. Something like:

```
y = x.draw_flood(128, 0, 0, equal=True)
```

ie. starting at (0, 0) set all connected pixels which are equal to the start pixel to 128.

This won't work for large images though :( The searching process would be much too slow and need far too much memory.

You could perhaps do it on a low-res version, then scale that up?

**Comment by gvincke** [comment]
This is working for every pixel, but what if i only what the flood drawing be done when the source pixel is black, and only black ? I tried to add test as 4th argument, but did not succeed. How i am supposed to define the test (do only if source pixel is black) ?

**Comment by jcupitt** [comment]
Sorry, I don't understand. It will only tag pixels equal to the start colour, so if the start colour is black, it'll only pick those.

Could you post an example?

**Comment by gvincke** [comment]
![8-corners](https://user-images.githubusercontent.com/1370541/102643936-5265c800-4160-11eb-8e6b-3b2393e2e731.png)
In this example, only the top left corner will be filled in grey if starting at (0,0) :
![new-8-corners](https://user-images.githubusercontent.com/1370541/102645193-5a266c00-4162-11eb-9ebb-7945f0665ffe.png)
So i plan to move around the border, test if i am on a black pixel, and only if i am on a black pixel, draw_flood().
<pre>w=image.width
h=image.height
for x in range(0, w, 5):
    for y in (0, h):
        #test if black:
            image = image.draw_flood(128, x, y, equal=True)
</pre>
Then redo for the vertical borders.
If i do not test if the start pixel is black, all the image will be grey.
The  result i want being : 
![new-8-corners](https://user-images.githubusercontent.com/1370541/102646058-b50c9300-4163-11eb-817e-fb9d85b73b34.png)

**Comment by jcupitt** [comment]
Ah I see. I would add a one pixel black border around the image, eg.

``
image = image.embed(1, 1, image.width + 2, image,height + 2)
```

Now flood from (0,0) and you'll get all 0 pixels which touch the edge. You could crop the border off again afterwards, if you need to be pixel-accurate.

**Comment by gvincke** [comment]
Works perfectly, even on a 80000x40000 image !
Thank you !

**Comment by jcupitt** [comment]
Oooof, that will just EAT memory. You could perhaps draw on just one 8-bit channel (the alpha) and save a bit of RAM. 

Anyway, if it's working, that's great.

**Comment by daton89** [comment]
Hi guys, I have been trying to execute the draw_flood form the command line, but I don't get how it should work, I need to solve the same problem as yours, so I have an image that I want to floodfill with the command:

`vips draw_flood ./vipprova.jpg 128 0 0 --equal=true`

but the image is not changing, how should this work from the command line?
