### ISSUE TITLE
When libheif is used with rav1e, libvips fails to build on macos

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#1939]
Can you explain why this build is failing? https://github.com/gumlet/sharp-libvips/runs/1601384630

**Comment by lovell** [comment]
Hi, there's rather a lot going on in there and you've not provided much information. It looks like you've forked/modified https://github.com/lovell/sharp-libvips/

Please can you narrow this problem down to only the dependencies that are failing (e.g. rav1e, heif, vips), perhaps provided as a minimal Dockerfile and shell script to make it easy for someone else to follow/reproduce the exact set of steps you are taking.

**Comment by adityapatadia** [comment]
Yes, I have copied your repo. I just replaced libaom with rav1e and made necessary modifications for rust availability under macos. I will try to make a shell script. Meanwhile, let me know if you have any idea why would this happen.

**Comment by kleisauke** [comment]
It looks like the `Requires.private` field within the pkg-config file of libheif doesn't include `rav1e`, I opened PR https://github.com/strukturag/libheif/pull/408 to fix this.
