### ISSUE TITLE
Was this linear light change from 8.9.2 to 8.10.0 intentional?

### ISSUE THREAD

**Issue by jjonesrs** [libvips/libvips#1941]
While testing the upgrade from 8.9.2 to 8.10.5, I noticed that the contents of the resized JPEGs changed. I narrowed down the version to the 8.10.0 release.

I reproduced the change outside of our pipeline using `vipsthumbnail.exe`.

Here's the command:
`vipsthumbnail.exe shoes.png --linear --size 80x -o "shoes80x80-8-9-2.jpg[background=255]"`

Version 8.9.2 produces:
![shoes80x80-8-9-2](https://user-images.githubusercontent.com/16615108/103048795-a566c300-4544-11eb-9d3f-b46dafa1cbe3.jpg)

Version 8.10.0 produces:
![shoes80x80-8-10-0](https://user-images.githubusercontent.com/16615108/103048833-c0d1ce00-4544-11eb-8900-c4d321376feb.jpg)

Version 8.10.0 without the `--linear` option produces:
![shoes80x80-8-10-0-no-linear](https://user-images.githubusercontent.com/16615108/103048900-f70f4d80-4544-11eb-97ee-e7d1365556e8.jpg)

If this change represents intended behavior, then I'll switch our pipeline away from using linear light.

Here's the original image for reference:
![shoes](https://user-images.githubusercontent.com/16615108/103048845-c9c29f80-4544-11eb-9d35-f8179385844e.png)

**Comment by jcupitt** [comment]
Hi @jjonesrs, oh dear, that's bad. I'll have a look -- thanks for the report!

**Comment by jcupitt** [comment]
Yes, as quick workaround, I'd move away from linear light for now.

**Comment by jcupitt** [comment]
That was painful, but I think I've fixed this. Could I use a small detail from your `shoes.png` image for the libvips test suite? It would help prevent this regressing again.

**Comment by jcupitt** [comment]
I added a test to that branch using the tip of one of the shoes. Please let me know if that's not OK.

https://github.com/libvips/libvips/blob/revise-premultiply/test/test-suite/images/rgba.png

**Comment by jcupitt** [comment]
There's a PR for this now, I'll close. Thanks for the report! The fix should be in 8.10.6.
