### ISSUE TITLE
VipsForeignLoad: file "C:\Path\To\Folder\*.png" does not exist

### ISSUE THREAD

**Issue by Worfhard** [libvips/libvips#1942]
Hello
When I use this command in cmd or powershell `vips webpsave "C:\Path\To\Folder\*.png" "C:\Path\To\Folder\Webp\*.webp" --near-lossless --Q=95 --reduction-effort=5`
I get the error `VipsForeignLoad: file "C:\Path\To\Folder\*.png" does not exist`

I'm trying to convert all my .png images to .webp images from C:\Path\To\Folder\ and put them in C:\Path\To\Folder\Webp\
If I specify the input.png image name and path and output.webp it works fine, example `vips webpsave "C:\Path\To\Folder\Screenshot1.png" "C:\Path\To\Folder\Webp\test.webp" --near-lossless --Q=95 --reduction-effort=5`

Version: vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020
vips-dev-w64-all-8.10.5

Windows 10

**Comment by jcupitt** [comment]
Hello @Worfhard,

That's right, `vips` will not loop over globs for you, you'll need to do that in your scripting language.

In bash, you could use something like:

```bash
for filename in *.png; do
  echo processing $filename ...
  vips copy $filename ${filename%.png}.webp[near-lossless,Q=95,reduction-effort=5]
done
```

I expect it's very similar in psh.

**Comment by Worfhard** [comment]
Oh alright, thanks!
