### ISSUE TITLE
Use Jpeg-Turbo for Mac with brew

### ISSUE THREAD

**Issue by uucly** [libvips/libvips#1943]
Hi,

i installed vips with `brew install vips` and it automatically installs vips with the normal libjpeg. Is there a way to install vips with brew on mac with jpeg-turbo? Or can i configure vips in the code to use libjpeg-turbo?

Thanks for your support,
Sven

**Comment by jcupitt** [comment]
Hi @uucly,

Sorry, `brew` has a policy of using libjpeg and not libjpeg-turbo. I've tried several times to get them to switch, but without success.

You'll need to build by hand if you need libjpeg-turbo support. You could use Docker, perhaps.

**Comment by uucly** [comment]
Hi jcupitt,

wow thanks for your quick response. And thank you for your hint regarding the Docker solution. I will try that.
