### ISSUE TITLE
Openjpeg symbol lookup error at runtime when processing PDF

### ISSUE THREAD

**Issue by olivier-lacroix** [libvips/libvips#1944]
Hello there,

I am using libvips via sharp, and have been trying to add pdf support by recompiling libvips with poppler.

This seemed to work well (ie I was able to process _some_ pdf files), until I received the following for a particular pdf file at run time:

`nodejs: symbol lookup error: /[...]/node_modules/sharp/build/Release/../../vendor/8.10.5/lib/libvips.so.42: undefined symbol: opj_stream_default_create`

`opj_stream_default_create` is defined by the openjpeg2 library, on which poppler depends.

The build script I am using is a modified version of the sharp-libvips one, where openjpeg and poppler are compiled statically. Main modifications are highlighted [here](https://github.com/olivier-lacroix/sharp-libvips/blob/6bbc2cc7ddf6b8dc5910bdd7c80b32a01975e98c/build/lin.sh#L382-L415)

Any idea of what I am doing wrong? any idea if this is an issue with libvips? with poppler? or (maybe more likely) with my build script :-) ?

Thanks in advance for any help or guidance you may be able to provide

**Comment by jcupitt** [comment]
Hi @olivier-lacroix,

That must be one of the first openjpeg API calls that poppler makes. Perhaps none of them are working? At a guess, maybe you built openjpeg with both static and dynamic libraries and accidentally linked against the dynamic one.

I expect you know, but poppler is GPL and linking against it means that your who application is now GPL. You must distribute sourcecode, including all your build scripts, if you distribute code.

libvips 8.11 has fixed up PDFium support, it might be worth looking at that. PDFium is MIT licenced, so there's no requirement for you to open your code.

I'll remove the bug tag, since this is not a libvips issue.

**Comment by olivier-lacroix** [comment]
Thanks @jcupitt . Yes, all openjpeg functions are missing.

I build both openjpeg and poppler as static only. libvips is built as shared.

The symbols are reported by `readelf` as undefined in both libpoppler.a and libvips.so.

All the linking magic is a bit beyond me: you reckon the issue is at poppler level? ie poppler should pull in openjpeg dependencies into libpoppler.a ?

Thanks for the licence remainder, I _think_ my use case falls under 'private use': I just intend to use the binaries with sharp in a CI pipeline to build a corp. website. I may be wrong here :-)

**Comment by jcupitt** [comment]
Ah, you're probably OK then.

Are you using poppler-glib? They support several APIs in several versions of the library. I see:

```
 $ ldd $(which vips) | grep popp
	libpoppler-glib.so.8 => /usr/lib/x86_64-linux-gnu/libpoppler-glib.so.8 (0x00007fdaf55ca000)
	libpoppler.so.97 => /usr/lib/x86_64-linux-gnu/libpoppler.so.97 (0x00007fdaf24c7000)
```

**Comment by jcupitt** [comment]
You need git master libvips for easy PDFium support, by the way.

**Comment by jcupitt** [comment]
You can always build poppper and openjpeg dynamically, of course. I don't like static linking myself. You just copy the relevant `.so` objects into the vips lib area.

**Comment by kleisauke** [comment]
I think this can be fixed with doing:
```bash
sed -i'.bak' 's/^Requires.private:.*/& openjp2/' poppler-glib.pc
```
just before the `make install/strip` command of poppler (untested).

**Comment by olivier-lacroix** [comment]
Thanks @kleisauke . Unfortunately, this is not enough to have poppler properly link in openjp2.

**Comment by olivier-lacroix** [comment]
Thanks @jcupitt. Yes, I do build poppler-glib. I am using static linking for consistency with what is done in the sharp-libvips build srcipt

**Comment by olivier-lacroix** [comment]
@jcupitt , @kleisauke , [issue reported at poppler ](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1019)

**Comment by olivier-lacroix** [comment]
@kleisauke , it seems like you were right! Adding the following seems to do the trick

`sed -i'.bak' '/-lpoppler/i Requires.private: libopenjp2' poppler.pc.cmake`

Running the full build pipeline now. I'll confirm once done.

**Comment by olivier-lacroix** [comment]
@jcupitt , @kleisauke , I can confirm this is working properly ! Thanks a lot for the quick help!

**Comment by jcupitt** [comment]
I just noticed the cross-post. @olivier-lacroix, please don't open the same issue in several places, it creates unnecessary extra work for the volunteers who support this software in their spare time.

**Comment by olivier-lacroix** [comment]
@jcupitt fair enough. Apologies.
