### ISSUE TITLE
Can't convert SVS to DJI

### ISSUE THREAD

**Issue by MrNightingale** [libvips/libvips#1953]
Hi, Guys!
I'm trying to convert `svs` file to `dji` via Windows binary and see next errors and warnings. Can you help me?

**File that I'm trying to convert**
`http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-JP2K-33005.svs`

**Command** 
`D:\Software\vips-dev-w64-web-8.10.5\vips-dev-8.10\bin> .\vips dzsave cmu.svs cmu`

**Error**
```
(vips.exe:16960): VIPS-WARNING **: 18:39:16.610: error in tile 0 x 0

(vips.exe:16960): VIPS-WARNING **: 18:39:16.616: error in tile 240 x 0

(vips.exe:16960): VIPS-WARNING **: 18:39:16.618: error in tile 480 x 0
...
source input: Compression scheme 33005 tile decoding is not implemented
source input: Compression scheme 33005 tile decoding is not implemented
source input: Compression scheme 33005 tile decoding is not implemented
```
**Result**: empty folder with next name `cmu-5KB1W0`

Thanks in advance!

**Comment by jcupitt** [comment]
Hello @MrNightingale,

I think you need the `-all` binary. The `-web` version does not include openslide, since it is not tested for security.

https://github.com/libvips/libvips/releases/download/v8.10.5/vips-dev-w64-all-8.10.5.zip

**Comment by MrNightingale** [comment]
@jcupitt Works like a charm! Thanks!
