### ISSUE TITLE
Image has a one-pixel black edge on its left and top after use vips similarity

### ISSUE THREAD

**Issue by 781545872** [libvips/libvips#1955]
sample.jpeg :
![sample](https://user-images.githubusercontent.com/13492988/103905180-3e96fb80-5139-11eb-8b54-936da16c49ef.jpeg)
out.jpeg :
![out](https://user-images.githubusercontent.com/13492988/103905031-0f808a00-5139-11eb-8007-8feb2c88163b.jpeg)
cmd:
vips similarity sample.jpeg out.jpeg --angle 180
version:
vips-8.9.2-Thu Sep 24 07:26:18 UTC 2020

**Comment by jcupitt** [comment]
Hello @781545872, I think this is because of corner vs. centre convention. Try:

```
vips similarity sample.jpeg out.jpeg --angle 180 --idx 1 --idy 1
```

![out](https://user-images.githubusercontent.com/580843/103914525-dc6ed400-5101-11eb-8f88-650443132c3b.jpeg)

**Comment by 781545872** [comment]
@jcupitt Thanks for replying. I'll close the issue.
