### ISSUE TITLE
Fast Multiple Thumbnails Per Image 

### ISSUE THREAD

**Issue by awesomecoder111** [libvips/libvips#1957]
I'm generating 5 thumbnails for a jpg image. The original image dimensions can vary widely in size from 300 to 15000 pixels (300 <= width, height <= 15000). The thumbnails will be around 1200x1000, 600x400, 250x250 etc.

Option 1:
* Compute shrink as [here](https://github.com/libvips/libvips/blob/df3b80fa40f4800e6949d356c800891af81537db/libvips/resample/thumbnail.c#L471): 
* Load image using vips_image_new_from_file with shrink [here](https://github.com/libvips/libvips/blob/df3b80fa40f4800e6949d356c800891af81537db/libvips/resample/thumbnail.c#L1040)
* for each desired thumbnail: vips_thumbnail_image and then write it out to disk

Option 2:
* call vips_thumbnail 5 times in parallel for each thumbnail.

Questions:
1. Am I using the right operations to make option 1 as fast as it can be? Option 2 could be faster but is resource heavy.
2. My concern with Option 1 is that I see  [documentation](https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-image) mentions vips_thumbnail_image can "produce poorer quality output". Will this be an issue.
3. Should "sequential" access be enabled for the image loading in this scenario for option 1?

This is similar to https://github.com/libvips/php-vips/issues/103, but I don't see these options mentioned there.

**Comment by jcupitt** [comment]
Hi @awesomecoder111,

Because of the way libvips works, multiple parallel vipsthumbnail is by far the fastest. It shouldn't be too resource-heavy. At the CLI, for example, you can do:

```
$ vipsheader wtc.jpg
wtc.jpg: 9372x9372 uchar, 3 bands, srgb, jpegload
$ time parallel vipsthumbnail wtc.jpg -s {} -o wtc-{}.jpg ::: 1200 600 300 150 75
real	0m0.540s
user	0m1.838s
sys	0m0.152s
```

Five thumbnails in 500ms. `vips_thumbnail_image()` is very slow and only for emergencies. You need to use `vips_thumbnail()` to get all the nice shrink-on-load stuff.

**Comment by awesomecoder111** [comment]
Thanks @jcupitt!

- `vips_thumbnail_image() is very slow and only for emergencies` doesn't option 1 handle this by doing the shrink on load manually?
- say I didn't do option 2 in parallel, do you suspect calling vips_thumbnail 5 times sequentially would be better than option 1?

**Comment by jcupitt** [comment]
Ah is this only for jpg? True, your option 1 would be equivalent then, and it's not much code to copy-paste.

Poorer quality output is for things like PDF and SVG where `vips_thumbnail` will be able to compute the load resolution and not need to rely on downsampling.

Yes, `sequential` should help a bit.

Still, I would just run `thumbnnail` five times in parallel. If you are extremely resource constrained (under 100mb of ram for your whole system) then just run it five times sequentially.

The best thing of course would be to do some experiments. You should be able to mock up and test a range of solutions very quickly in something like Python.
