### ISSUE TITLE
creating a thumbnail by height\width

### ISSUE THREAD

**Issue by GuyMoreh11** [libvips/libvips#1958]
Hey!
I'm using int `vips_thumbnail_buffer( void *buf, size_t len, VipsImage **out, int width, ... )` to create thumbnails.
But I want to be able to specify just height or just width, there is a way to do it? 

Thanks!

**Comment by jcupitt** [comment]
Hi @GuyMoreh11, just use a huge number (10m?) for the axis you're not interested in.

**Comment by GuyMoreh11** [comment]
That's works, thanks
