### ISSUE TITLE
Use libvips to speed up image shading removal

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1959]
Description of image shading removal:
![image](https://user-images.githubusercontent.com/73845/104259361-3b469b80-54bc-11eb-982e-85971064fbf5.png)

There is a solution with detailed explanation by @kavyamusty using Numpy and OpenCV, with the result in image above, 
https://github.com/kavyamusty/Shading-removal-of-images

I think it's quite good, and @divertingPan manage to speed it up quite lot (about 7x faster) with numba：
https://github.com/kavyamusty/Shading-removal-of-images/issues/1

but I think maybe libvips is good at this kind of task and able to speed up even more.

@jcupitt , Hi John, I'm working on it with pyvips, any suggestions ？

**Comment by jcupitt** [comment]
Hello, min / max / median of a moving rect are types of rank filter. You can reimplement that algorithm like this:
```
#!/usr/bin/python3
  
import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

image = image.colourspace("b-w")

size = 20
mx = image.rank(size, size, (size * size) - 1)
mn = mx.rank(size, size, 0)

image = image - mn + 255

image.write_to_file(sys.argv[2])
```

And run like this:

```
$ /usr/bin/time -f %M:%e ./minmax.py ~/pics/writing.jpg x.jpg
71860:1.18
```

So 1.4s of CPU, 72mb of memory to make:

![x](https://user-images.githubusercontent.com/580843/104268702-716c2700-548c-11eb-86af-aad142513556.jpg)

**Comment by jcupitt** [comment]
Rank filtering is quite slow, I'd generally use a gaussblur for this kind of task. I'm sure opencv has a fast rank filter too, though I don't know what it's called.

**Comment by jindili** [comment]
Hi @jcupitt ,Thanks for you quick solution.

Wow, Never thought it was so simple using pyvips.

Test the code with an image taken with my phone of size 2592x4608, take 9 seconds to process:
![image](https://user-images.githubusercontent.com/73845/104276967-e8330f80-54e0-11eb-9632-c3a97580cbb1.png)

Result is quite good. zoom out to have a close view:
![image](https://user-images.githubusercontent.com/73845/104277324-98a11380-54e1-11eb-8521-a976d8153585.png)
The large title text not seems so good, I think I should do some pre processing before the rank filter.

Attached my original image:
![input](https://user-images.githubusercontent.com/73845/104277573-0a795d00-54e2-11eb-8c71-c6d1231ba28d.jpg)

**Comment by jcupitt** [comment]
The 20 is not large enough -- try turning it up a bit. 30 maybe?

**Comment by jindili** [comment]
30 give a much better result for the big title part
![image](https://user-images.githubusercontent.com/73845/104278230-35b07c00-54e3-11eb-8a81-d7ff75f190fb.png)

I'll try 40, and 50

**Comment by jindili** [comment]
As the value increase, time taken to process is increasing significantly.

and content text getting worse,
![image](https://user-images.githubusercontent.com/73845/104278590-cdae6580-54e3-11eb-9256-3ec101e6cb88.png)

For this image, I think 30 is a good value to use, but for a general usage for random input image,
Is there some way I can calculate a good threshold value and then use that value to apply the rank filter ?

**Comment by jcupitt** [comment]
You could try using `gaussblur` instead (high pass filtering). For example:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")

image = image.colourspace("b-w")

image = 3 * (image - image.gaussblur(30)) + 255

image.write_to_file(sys.argv[2])
```

Run as:

```
$ /usr/bin/time -f %M:%e ./remove-bg.py ~/pics/bigtext.jpeg x.jpg
65868:0.59
```

ie. 0.6s, 65mb of memory, to make:

![x](https://user-images.githubusercontent.com/580843/104325579-b28e2680-54e0-11eb-816a-7bcd3c2fd5f9.jpg)

**Comment by jindili** [comment]
That's much faster and get a better, sharper text (left:gaussblur, right: rank filter with size 30)
![image](https://user-images.githubusercontent.com/73845/104333146-df1b6000-552b-11eb-96ac-a35526d84914.png)

I'll do some optimization to clean up the background based on this.

Thanks @jcupitt

**Comment by jcupitt** [comment]
I added a new fast path to git master libvips for large rank filters on 8-bit images.

Old:

```
john@yingna ~/pics $ time vips rank k2.jpg x.jpg 50 50 1200
real	0m22.301s
user	2m50.061s
sys	0m0.224s
```

New:

```
john@yingna ~/pics $ time vips rank k2.jpg x.jpg 50 50 1200
real	0m0.388s
user	0m2.363s
sys	0m0.020s
```

**Comment by jindili** [comment]
Wow! more than 20x faster!
@jcupitt Awesome optimisation.
