### ISSUE TITLE
Is there any way to check a truncated image?

### ISSUE THREAD

**Issue by 781545872** [libvips/libvips#1960]
For example, I can use exiftool to check.
![image](https://user-images.githubusercontent.com/13492988/104282602-457f8e80-54ea-11eb-876f-3f9c47b7c06f.png)

**Comment by jcupitt** [comment]
Hello @781545872,

Yes, set the `fail` flag on image load and libvips will raise an error for image corruption. For example:

```python
john@kiwi:~/pics$ python
Python 2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("truncated.png", fail=True)
>>> x.avg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/GIT/pyvips/pyvips/vimage.py", line 921, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/john/GIT/pyvips/pyvips/voperation.py", line 292, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call avg
  pngload: libpng read error
```

So the open worked (libvips open is lazy and does not decode any pixels, so it cannot detect truncation), but when you try to compute something that will read all pixels (here the pixel average), you get an error.

**Comment by 781545872** [comment]
Hello @jcupitt ,
I found an image that can compute avg correctly!
However, exiftool shows that it's a truncated image.
![truncated](https://user-images.githubusercontent.com/13492988/104404488-bfb91d00-5595-11eb-9bea-7baef48c60fa.png)

**Comment by jcupitt** [comment]
In this case, libvips can get all the pixels out successfully, so it's happy. It's true it doesn't check that the file is completely correct.

**Comment by 781545872** [comment]
I can check this case using imagemagick.However, it cost too much time.It's a bad news for me that libvips can not check that the file is completely correct.

**Comment by 781545872** [comment]
@jcupitt Will libvips check image completely correct?

**Comment by jcupitt** [comment]
It's using libpng or libspng to tread the file and if libpng is not detecting the problem, then libvips can't either, sorry.

**Comment by 781545872** [comment]
All right, I will try other ways.
Thank you for your answer.
I will close the issue.
