### ISSUE TITLE
Image smoothing after mapim transform

### ISSUE THREAD

**Issue by jindili** [libvips/libvips#1963]
I test run some pyvips code from an old blog post:
http://libvips.blogspot.com/2015/11/fancy-transforms.html

The result of mapim of dense grid seems blurry,  I try to fix that with gaussblur and simple image scale up,
here is the Code:
```python
import pyvips

def to_rectangular(image):
    xy = pyvips.Image.xyz(image.width, image.height)
    xy *= [1, 360.0 / image.height]
    index = xy.rect()
    scale = min(image.width, image.height) / float(image.width)
    index *= scale / 2.0
    index += [image.width / 2.0, image.height / 2.0]
    return image.mapim(index)


def to_rectangular_ScaleUP(image, RATIO_ScaleUP):
    image = image.resize(RATIO_ScaleUP)
    xy = pyvips.Image.xyz(image.width, image.height)
    xy *= [1, 360.0 / image.height]
    index = xy.rect()
    scale = min(image.width, image.height) / float(image.width)
    index *= scale / 2.0
    index += [image.width / 2.0, image.height / 2.0]
    return image.mapim(index).resize(1 / RATIO_ScaleUP)


def to_rectangular_gauss(image, blur):
    xy = pyvips.Image.xyz(image.width, image.height)
    xy *= [1, 360.0 / image.height]
    index = xy.rect()
    scale = min(image.width, image.height) / float(image.width)
    index *= scale / 2.0
    index += [image.width / 2.0, image.height / 2.0]
    return image.mapim(index.gaussblur(blur))


img_grid = pyvips.Image.new_from_file("grid.png")
img_polar2rect = to_rectangular(img_grid)
img_polar2rect.tiffsave("output.tif")

img_polar2rect_2x = to_rectangular_ScaleUP(img_grid, 2)
img_polar2rect_2x.tiffsave("output_ScaleUP_2x.tif")

img_polar2rect_3x = to_rectangular_ScaleUP(img_grid, 3)
img_polar2rect_3x.tiffsave("output_ScaleUP_3x.tif")

img_polar2rect_gauss = to_rectangular_gauss(img_grid, 3)
img_polar2rect_gauss.tiffsave("output_ScaleUP_gauss.tif")

```
and the result side by side:
![image](https://user-images.githubusercontent.com/73845/104582228-9504bc80-569a-11eb-9883-da36a66dc103.png)

Seems gaussblur has no obvious effect here,
and result of scale up is good, 3x is slightly better than 2x.

I want to know is there some way better to do this kind of smoothing. ( Better smoothing quality, time is not important this time)

The grid image used for the test:
![grid](https://user-images.githubusercontent.com/73845/104581930-39d2ca00-569a-11eb-93b1-ba7559cad7ed.png)

**Comment by jcupitt** [comment]
Hi again, `mapim` uses bilinear interpolation by default, you can try others. For example:

```
interp = pyvips.Interpolate.new('bicubic')
return image.mapim(index, interpolate=interp)
```

**Comment by jindili** [comment]
bicubic seems almost the same here
![image](https://user-images.githubusercontent.com/73845/104589422-cc786680-56a4-11eb-9b24-191affe989c0.png)

I'll try other Interpolate options.

**Comment by jindili** [comment]
Test of all interpolation with code:
```python
import pyvips

list_interpolate = ["nearest", "bilinear", "bicubic", "lbb", "nohalo", "vsqbs"]

def to_rectangular(image, interp):
    xy = pyvips.Image.xyz(image.width, image.height)
    xy *= [1, 360.0 / image.height]
    index = xy.rect()
    scale = min(image.width, image.height) / float(image.width)
    index *= scale / 2.0
    index += [image.width / 2.0, image.height / 2.0]
    interp = pyvips.Interpolate.new(interp)
    return image.mapim(index, interpolate=interp)


img_grid = pyvips.Image.new_from_file("grid.png")

for interp in list_interpolate:
    img_polar2rect = to_rectangular(img_grid, interp)
    img_polar2rect.tiffsave("output_{}.tif".format(interp))
```

result:
![image](https://user-images.githubusercontent.com/73845/104603959-e66f7480-56b7-11eb-9cc3-59be72150e4a.png)
![image](https://user-images.githubusercontent.com/73845/104604041-fab37180-56b7-11eb-9205-6d5e993bb630.png)

seems vsqbs has the best smoothing, compare with scale up 2x and 3x
![Uploading image.png…]()

Seems 3x scaleup is the best.
