### ISSUE TITLE
NetVips.VipsException:“unable to call jpegsave VipsJpeg: out of order read at line 1048 ”

### ISSUE THREAD

**Issue by 3400442579** [libvips/libvips#1965]
![3](https://user-images.githubusercontent.com/34226979/105125318-16cf6c80-5b17-11eb-85f7-ea5ff5f0df9e.jpg)

 var image = NetVips.Image.NewFromFile(@"C:\Users\jxw\Desktop\17\3.jpg", access: Enums.Access.Sequential);
            var newImg = image.FlipVer();
            newImg.Jpegsave(@"C:\Users\jxw\Desktop\3_v.jpg");

NetVips:1.2.4
NetVips.Native.win-x64:8.10.5.1
window10

**Comment by jcupitt** [comment]
Hello @3400442579,

You can't use vertical flip in sequential mode. The "How it opens files" chapter in the docs explains how sequential mode works:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by 3400442579** [comment]
thanks
