### ISSUE TITLE
Why does vips_text insert hyphens after line breaks with '/'?

### ISSUE THREAD

**Issue by piface314** [libvips/libvips#1969]
I'm using vips to write some text with word wrapping and justification. However, I noticed that in some cases, when there are two words separated by a `/` and the line break/word wrapping occurs precisely before that `/`, a hyphen is inserted after it.

Example (in Lua, with some dummy text):
```lua
local vips = require 'vips'
local text = 'Lorem ipsum dolor lorem ipsum sit/amet.'
vips.Image.text(text, {width = 220, justify = true}):write_to_file('text.png')
```
outputs this:
![text](https://user-images.githubusercontent.com/22157025/105778554-5f3dbe80-5f4b-11eb-9216-7f488053041b.png)

That `/` does not belong to the text, and I'm not sure hyphenation is enabled (actually, I don't know if that feature exists at all). Is that something with Pango?

**Comment by jcupitt** [comment]
Huh I've never seen that before. Yes, it looks like it's a new pango feature:

https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/

It's not obvious how to turn this feature off.

**Comment by piface314** [comment]
Oh, I see. Thansk for pointing that post out! There is a [markup](https://developer.gnome.org/pango/stable/pango-Markup.html) attribute to enable/disable that. So the solution would be:

```lua
local vips = require 'vips'
local text = '<span insert_hyphens="false"
>Lorem ipsum dolor lorem ipsum sit/amet.</span>'
vips.Image.text(text, {width = 220, justify = true}):write_to_file('text.png')
```
![text](https://user-images.githubusercontent.com/22157025/105851732-3ad0f900-5fc2-11eb-895f-cb9537169aef.png)
