### ISSUE TITLE
How to join two images top to bottom with largest being retained?

### ISSUE THREAD

**Issue by benjamind** [libvips/libvips#197]
So I'm using tbjoin to join two images top to bottom, but it appears that only the narrowest width is retained.

So if the second image is wider than the first, I end up with the images joined but the second image is cropped to the width of the first.

How do I join the images such that all the content is retained?

**Comment by sergeevabc** [comment]
And if there are two logos (one is larger than the other), how can they be combined horizontally so that the larger one becomes the size of the smaller one?

**Comment by jcupitt** [comment]
Please open a new issue for a new question. If you post on closed issues, everyone on the old issue gets an annoying email, and any answers are difficult for other users to find.
