### ISSUE TITLE
I am unable to load all pages in a pdf to images using libvips python bindings?

### ISSUE THREAD

**Issue by abhipn** [libvips/libvips#1973]
I have pdf document with multiple pages, and I am using this below code,

It returns only the first page? What am I doing wrong here?
```

# libvips built with pdfium
libvips: vips-8.11.0 
```

```
import pyvips
document_images = pyvips.Image.pdfload(filename, n=3, dpi=DPI)
# output
<pyvips.Image 2550x6600 uchar, 4 bands, srgb>
```

If I want all pages I had to loop over and get each page, something like this works but is there any way I can get all at once to improve performance

```
n = 0
pages = []
while True:
   try:
       page = pyvips.Image.pdfload(file, n=n, dpi=DPI)
   except:
       break
    pages.append(page)
```

**Comment by jcupitt** [comment]
Hello @abhipn,

libvips loads multi-page images as very tall, thin strips (so-called "toilet roll" images). It sets the `page-height` metadata item to the length of each page.

```
john@kiwi:~/pics$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("thesis.pdf")
>>> x.height
842
>>> x = pyvips.Image.new_from_file("thesis.pdf", n=10)
>>> x.height
8420
>>> 
```

**Comment by abhipn** [comment]
@jcupitt Thank you for responding back, is there a way to get each page as a separate image file?

**Comment by jcupitt** [comment]
1. Sure, use eg. `image_new_from_file("data.pdf", page=12)` to get just page 12 as an image.

2. libvips is a lazy, streaming image processing library, so computation only happens when pixels are processed. The `new_from_file` is quick because all it does it create a start point. The PDF render won't happen until `write_to_memory` is called.

It might be possible to speed up your tests. Post a complete, runnable benchmark, with sample data, and I'll have a look.

**Comment by abhipn** [comment]
@jcupitt  My goal is to convert a pdf to image, then resize the image resolution to (380, 380, 3) and get the final array,

latency is very import in my use-case, but this seems to be not helping , if you know something please let me know,


[document to convert](https://file.io/tcYWMQznIGYa)

```
document_page = pyvips.Image.pdfload(
                    file_path,
                    page=1,
                    dpi=300,
                    memory=True,
                    fail=True,
                )
def convert_vips2numpy(img):
    return np.ndarray(
        buffer=img.write_to_memory(),
        dtype=np.uint8,
        shape=[img.height, img.width, img.bands],
    )

document_image = convert_vips2numpy(document_image)
from PIL import Image
document_image = Image.frombuffer("RGB", (380, 380), document_image, decoder_name="raw")
import numpy as np
document_image = np.array(document_image)
document_image.shape
# (380, 380, 3) #RGB

```

**Comment by jcupitt** [comment]
Hello, your document has been deleted by `file.io`, could you upload again?

**Comment by abhipn** [comment]
@jcupitt Here is another link https://file.io/j4AS6JogyrZ5

**Comment by jcupitt** [comment]
I would change a couple of things:

1. You are loading at 300 DPI and then downsizing to 380x380. Why not just render at 380x380 in the first place? You'll save quite a lot of time.
2. You are using PIL to convert to RGB (and drop the alpha), but this is simpler and faster in pyvips. You can use use array slicing, eg. `page = page[0:3]` to get the first three channels.

Here's a revised version of your code:

```python
import sys

import pyvips
import numpy as np
                    
def convert_vips2numpy(img):
    return np.ndarray(
        buffer=img.write_to_memory(),
        dtype=np.uint8,
        shape=[img.height, img.width, img.bands],
    )
    
image = pyvips.Image.thumbnail(sys.argv[1], 380, height=380, size="force")
image = image[0:3]
np_image = convert_vips2numpy(image)
print(np_image.shape)
```

I see:

```
$ time ./pdf2numpy2.py ~/pics/BIRUK_DUBALE._Full\ Stack_Green\ Card_Maryland.pdf[page=1]
(380, 380, 3)
real	0m0.248s
user	0m0.697s
sys	0m0.564s
```

That's with poppler, but pdfium is pretty similar. 

You could render all pages at once like this:

```
$ time ./pdf2numpy2.py ~/pics/BIRUK_DUBALE._Full\ Stack_Green\ Card_Maryland.pdf[n=-1]
(1140, 380, 3)
real	0m0.262s
user	0m0.681s
sys	0m0.589s
```

You can see the numpy array is taller. It only takes slightly longer.

**Comment by abhipn** [comment]
@jcupitt I needed that 300dpi for later usage (i.e., another pipeline)?

**Comment by jcupitt** [comment]
No, thumbnail uses target pixel size rather than DPI. I would render twice, once at 380x380, and once at high resolution.
