### ISSUE TITLE
JPEG XL support

### ISSUE THREAD

**Issue by jonsneyers** [libvips/libvips#1974]
libjxl 0.3 was released: https://gitlab.com/wg1/jpeg-xl/-/releases
The decode api is now stable.

Seems like a good occasion to implement JPEG XL support.

**Comment by lovell** [comment]
Hi Jon, there's an existing enhancement issue for this at #1559 - let's continue to track it there.

**Comment by jonsneyers** [comment]
Sorry, should have checked first :)
