### ISSUE TITLE
why not support cmakelist?

### ISSUE THREAD

**Issue by LightSun** [libvips/libvips#1975]
Ask a question...

**Comment by jcupitt** [comment]
Hello @LightSun,

We don't have the resources to support more than one build system. We probably should move on from autotools, and cmake is OK, but I keep hoping something better will come along. meson looks very nice, for example.

Perhaps the choice will be clearer in a few years time.

**Comment by LightSun** [comment]
@jcupitt Is this support android and ios ?  how to build for android?

**Comment by jcupitt** [comment]
Yes, you can cross-compile with autotools. You'd need to look at the docs:

https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

**Comment by LightSun** [comment]
ok, thanks.
