### ISSUE TITLE
Histogram calculations yield wrong values due to 32-bit overflow

### ISSUE THREAD

**Issue by erdmann** [libvips/libvips#1976]
**Describe the bug**

Hi John,

Calculations involving histograms seem to be limited to 32-bit unsigned integers, which causes failures for images with more than 2**32 pixels.  The problem arises, for example, for any attempt to perform histogram equalization on such images since the calculation of the cumulative histogram is a necessary step in the process, and the cumulative histogram always rises to the total number of pixels in the image prior to normalization.

The following screenshot from nip2 shows the bug in practice.  The top cell shows a failed global histogram equalization on a radiograph, the middle cell shows the histogram for the pre-equalized image, and the bottom cell shows the associated cumulative histogram.  The wrap-around happens twice in this case.

<img src="https://user-images.githubusercontent.com/406404/106444284-d6101580-647d-11eb-93af-91a8cd73d1a5.png" width="600">

(I'm aware that as a work-around for the special case of histogram equalization, I can calculate a reduced-resolution version of the image and then `hist_find -> hist_cum -> hist_norm` followed by `maplut` on the original image.)

**To Reproduce**
A minimal but contrived example follows:

```shell
$ vips black black.v 65537 65537
$ vipsheader black.v
black.v: 65537x65537 uchar, 1 band, multiband
$ vips hist_find black.v hist.csv
$ head hist.csv
131073	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
$ python -c "print(65537**2)"
4295098369 # the first entry should've been this
$ python -c "print(65537**2 % 2**32)"
131073 # but it wrapped around at 32 bits
$ vips --version
vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020
```

I'd guess this is a known issue, but I don't know how hard it is to change the internal type of histograms to use 64-bit integers.  

Many thanks in advance!

**Comment by jcupitt** [comment]
Hi @erdmann, nice to hear from you.

Yes, this is one of those "ahh 2**32 will be enough for anyone!" moments back in the 90s. I've not been bitten by this myself, but it's obviously possible.

One simple solution would be to use double for large histograms. You can represent ints up to 2**53, so that should give a good bit more headroom. "Large" would need defining, perhaps eg. `width * height > 2 ** (32 - bits_per_sample)`.

A better fix would be to add support for int64 / uint64 images. It's not so much work, but would be a large API break. Perhaps that's something for libvips9.

**Comment by erdmann** [comment]
Thanks for the quick response, @jcupitt!

Is there a way to induce the use of double-precision histograms from the start?  Or is it necessary to first find a 32-bit histogram, then convert that to double, then integrate it?

For example, the following still fails, but maybe just because I lack the incantation to force double in the hist_find computation:
```shell
$ vips cast black.v double_black.v double
$ vipsheader double_black.v
double_black.v: 65537x65537 double, 1 band, multiband
$ vips hist_find double_black.v double_hist.csv
$ head double_hist.csv 
131073
```

As an additional note for those who may encounter a similar problem, for the above problem with the radiograph it was a simple matter to just divide the histogram by a constant prior to integration and mapping in order to avoid overflow in the histogram equalization process:
<img src="https://user-images.githubusercontent.com/406404/106452603-6ce1cf80-6488-11eb-99bd-753aff4561a4.png" width="600px">

**Comment by jcupitt** [comment]
It needs a small code change to the histogram finder to make it accumulate double for huge images. I'll make a test branch.

Nice to see someone using nip2. I've been working on nip3 recently, did you see? There's a new imageviewer here:

https://github.com/jcupitt/vipsdisp

It'll be the nip3 image view window. It has a few improvements over the nip2 image view window, including much faster startup, support for image pyramids, log-scale images, and a more modern look and feel.

**Comment by erdmann** [comment]
I use nip2 all the time, and it's the tool I teach our cultural heritage conservation and restoration post-graduate students to use at the University of Amsterdam and at the Rijksmuseum.  I would be crippled without it as a viewer, especially given that I'm routinely working with 50+ gigapixel images these days.  It's very exciting to hear that there's work on a successor; I hadn't noticed.  I'll definitely check out the new viewer too.

Thanks!

**Comment by jcupitt** [comment]
OK, git master libvips seems to make sensible histograms for huge images. Any testing very welcome, of course.

![shot](https://user-images.githubusercontent.com/580843/106483548-8bef5a00-64a6-11eb-8f36-42df99a5a1f5.jpg)
