### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by LightSun** [libvips/libvips#1978]
```java
./configure.ac: line 5: syntax error near unexpected token `[vips],'
./configure.ac: line 5: `AC_INIT([vips], [8.8.1], [vipsip@jiscmail.ac.uk])'
```

I ensure autoconf, automake is installed. but why still error? Could you help me?

**Comment by LightSun** [comment]
i resolved

**Comment by jcupitt** [comment]
Hi, you can just run `configure`, you don't need to install autotools.

You only need the autotools packages if you want to rebuild the `configure` script.
