### ISSUE TITLE
How to add an operation for libvips? 

### ISSUE THREAD

**Issue by LightSun** [libvips/libvips#1983]
Hello , Libvips is very good project. I like it and study it. But I am new for glib. don't know how to do for 'add an operation'
on source code ? Could you help me ?

And how to know the all supported operations?

**Comment by jcupitt** [comment]
Hi, there's an example here:

https://github.com/jcupitt/vips-gmic

You can list operations with:

```
vips -l
```

**Comment by LightSun** [comment]
@jcupitt thanks

**Comment by LightSun** [comment]
@jcupitt how to now the all option of an operation?

**Comment by jcupitt** [comment]
Just run it at the command line with no arguments, eg.:

```
$ vips embed
embed an image in a larger image
usage:
   embed in out x y width height [--option-name option-value ...]
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
   x            - Left edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   y            - Top edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   width        - Image width in pixels, input gint
			default: 1
			min: 1, max: 1000000000
   height       - Image height in pixels, input gint
			default: 1
			min: 1, max: 1000000000
optional arguments:
   extend       - How to generate the extra pixels, input VipsExtend
			default: black
			allowed: black, copy, repeat, mirror, white, background
   background   - Color for background pixels, input VipsArrayDouble
```

**Comment by LightSun** [comment]
@jcupitt How can I see the options in source code?

**Comment by jcupitt** [comment]
The vipsobject docs cover this:

https://libvips.github.io/libvips/API/current/VipsObject.html

You can use vips_object_get_args() to get a list of all the operation arguments, and vips_object_get_argument() to fetch all the details for one argument.

The C source code has some examples. The Python and Ruby bindings are useful too.

**Comment by LightSun** [comment]
ok thanks
