### ISSUE TITLE
Compilation against glib >= 2.67.3 fails due to C vs C++ linkage

### ISSUE THREAD

**Issue by lovell** [libvips/libvips#1987]
Compilation of the C++ files in libvips v8.10.5 is failing against the latest glib v2.67.3, which is triggered by the change in https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1715

```
In file included from /target/include/glib-2.0/glib/gmacros.h:241,
                 from /target/lib/glib-2.0/include/glibconfig.h:9,
                 from /target/include/glib-2.0/glib/gtypes.h:32,
                 from /target/include/glib-2.0/glib/galloca.h:32,
                 from /target/include/glib-2.0/glib.h:30,
                 from ../../libvips/include/vips/vips.h:87,
                 from reducev.cpp:68:
/opt/rh/devtoolset-9/root/usr/include/c++/9/type_traits:2282:3: error: template with C linkage
 2282 |   template<typename _MemPtr, typename _Arg, typename... _Args>
      |   ^~~~~~~~
```

There's a proposed follow-up change to "fix" this at https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935 but this does mean there's now at least one version of glib out in the wild that libvips cannot be compiled against, so perhaps we need to fix this too.

**Comment by jcupitt** [comment]
OK, I think I've fixed it.

**Comment by lovell** [comment]
Thanks, does this need backporting to 8.10?

The upstream "fix" https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935 was closed as invalid so there will probably be all manner of broken packages when Homebrew picks up the latest glib.

**Comment by jcupitt** [comment]
Ah argh, you're right. I'll patch 8.10 too.

**Comment by jcupitt** [comment]
OK, I merged your librsvg fix to master as well and updated the changelog too.
