### ISSUE TITLE
vips_dzsave() - Add an option to perform region shrink in linear color

### ISSUE THREAD

**Issue by f1ac** [libvips/libvips#1988]
Currently vips_dzsave() shrinks each 2x2 region without taking image colorspace into account, and most images are in sRGB. This tends to make astronomical photos and synthetic images with high frequency noise on dark background pitch black at lower zoom levels. For example, a 2x2 region containing one star (1 bright pixel and 3 black pixels) would become barely visible after just one shrinkage (using bright pixel value of 187 here):

Gamma space shrinkage:
(187 + 0 + 0 + 0) / 4 = **46**

Linear color shrinkage assuming image is in sRGB (gamma 2.4):
( ((187/255)^2.4 + 0 + 0 + 0) / 4) ^ (1/2.4) * 255 = **104**

The difference is quite noticeable:
![image](https://user-images.githubusercontent.com/13987066/107882237-dc2bda80-6ef0-11eb-9c4a-cbc7679e520d.png)

**Comment by jcupitt** [comment]
Hi @f1ac,

You can do the shrink in any colourspace -- just transform before the dzsave.

For example:

```
$ vips colourspace wtc.jpg x.dz scrgb
```

Now it'll transform the JPG file to scRGB (linear float 0 - 1), make the pyramid in linear space, then transform back to sRGB for the JPG save of each tile. XYZ would work well too.

For mono images, grey16 would be an OK choice, though I guess the precision might not be high enough, depending on the tile format.

**Comment by f1ac** [comment]
Hi @jcupitt,

Thank you, didn't realize it is possible to chain operations this way.

**Comment by jcupitt** [comment]
You can only chain the loaders and savers with one operation inbetween :( the libvips CLI interface is a bit limited.

You can do unlimited chaining in something like Python, of course.

**Comment by f1ac** [comment]
@jcupitt 

BTW it seems vips crashes at start if I try to specify any dz arguments. I tried to exclude them one by one, but it only works if I omit [] block entirely:
`.\vips.exe colourspace infile.vips outfile.dz[layout=google,overlap=0,suffix=.png,tile-size=1024] xyz --vips-progress`
`vips.exe temp-11: 1 x 1 pixels, 16 threads, 1 x 16 tiles, 384 lines in buffer`
`vips.exe temp-11: done in 0.00297s`
`vips.exe temp-4: 524288 x 262144 pixels, 16 threads, 524288 x 1 tiles, 384 lines in buffer`
`Exception code=0xc0000005 flags=0x0 at 0x00007FF99B444589. Access violation - attempting to read data at address 0x0000000398039000`

Could this be a bug? It is reproducible with versions 8.7 - 8.10. The only difference is that some versions do not print last line. Input file is a 524288 x 262144 sRGB UCHAR vips.

**Comment by f1ac** [comment]
Did more tests and it seems vips crashes when I specify tile-size value greater than default 256.

**Comment by jcupitt** [comment]
Huh that's odd. It's working for me on linux.

You could try in WSL as a workaround. I'll see if I can see why it's crashing on Windows.

**Comment by jcupitt** [comment]
Actually, we should have a new issue for this crash. Would you mind opening a bug report?

**Comment by f1ac** [comment]
I'll try to gather more data, so far it seems this only happens with files at least 524288 x 262144 in size, tile-size > 340 and only when gz_save is chained with colourspace op.
