### ISSUE TITLE
Crash when chaining colourspace and dzsave operations

### ISSUE THREAD

**Issue by f1ac** [libvips/libvips#1989]
Vips crashes when chaining colourspace and dzsave operations with large files and tile sizes.

**Conditions**
- input file should be at least 1 channel uchar 524288x262144 image. Tested with 1- and 3- channel png and vips formats. Not reproducible for 262144x262144 size.
- tile-size argument should be at least 340

**Example**
```
.\vips.exe colourspace infile.png outfile.dz[tile-size=1024] xyz --vips-progress
vips.exe temp-11: 1 x 1 pixels, 16 threads, 1 x 16 tiles, 384 lines in buffer
vips.exe temp-11: done in 0.00297s
vips.exe temp-4: 524288 x 262144 pixels, 16 threads, 524288 x 1 tiles, 384 lines in buffer
Exception code=0xc0000005 flags=0x0 at 0x00007FF99B444589. Access violation - attempting to read data at address 0x0000000398039000
```

**Steps to reproduce**
- Generate a file which is large enough `.\vips.exe black infile.png 524288 262144`
- Execute `.\vips.exe colourspace infile.png outfile.dz[tile-size=340] xyz`
- Vips crashes after several seconds

**Environment**
 - Windows 10 Pro x64 20H2
 - Vips 8.10.5, 8.9.2, 8.8.4, 8.7.4 official windows releases (some versions crash silently without printing the error, not tested with earlier versions)
 - 32Gb RAM

**Comment by jcupitt** [comment]
Sounds like it might be an int32 overflow, I'll have a look. Thanks for reporting this.

**Comment by jcupitt** [comment]
Here's a tiny bash script to produce the crash:

```
#!/bin/bash

if [ ! -f huge.v ]; then
  echo generating huge.v ...
  vips black huge.v 524288 10000
fi

echo running dzsave on conversion to XYZ ...
valgrind vips colourspace huge.v outfile.dz[tile-size=500] xyz
```

And there's an int overflow in `vips_region_copy()`. This is fixed in git master, and I've credited you in the changelog.

Thanks for reporting this! The fix will be in the next version.
