### ISSUE TITLE
Documentation for Crop CLI

### ISSUE THREAD

**Issue by DSLituiev** [libvips/libvips#1990]
**Is your feature request related to a problem? Please describe.**
Documentation for `vips crop`, hopefully [here](https://libvips.github.io/libvips/API/current/using-cli.html)

I saw `vips crop` command in this [SO post](
https://stackoverflow.com/a/48376269/894763), but google finds only `smartcrop`  command elsewhere. 

I would like to understand :
- what is the order of location parameters (offset-x, offset-y, width or end-x, height or end-y)
- how to make it preserve the original format. I have a pyramidal TIFF64. When I convert it, I get TIFF.

**Describe the solution you'd like**
a documentation page

**Comment by jcupitt** [comment]
Hi @DSLituiev,

It's documented here:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-crop
