### ISSUE TITLE
Writing TIFFTAG_XRESOLUTION

### ISSUE THREAD

**Issue by iwbh15** [libvips/libvips#206]
Hi all,
When writing the resolution values with values other than integers such as 123 or 123.0, the tags are not written correctly into the Tiff file using commands such as

``` bash
$ vips tiffsave k2.jpg out_i2.tif --compression jpeg --Q 100 --tile --tile-width 512 --tile-height 512 --pyramid --resunit VIPS_FOREIGN_TIFF_RESUNIT_CM --xres 123.1 --yres 123.1
```

I have investigated the behaviour in the code with an example value of 1234.5678001.
In the function `make_tiff_write()` the variable `tw->xres` will be initialized with a value of 1234.5678001000001.

When, in `write_tiff_header()`, the tag is set with `TIFFSetField(tif, TIFFTAG_XRESOLUTION ...)` the variable tw->xres has a value of 1234.5677490234375.
Then, in the tif file a value of 1234.568437 can be found.

When instead of `CopyField( TIFFTAG_XRESOLUTION, f )` the resolution value will be directly written by a modification of function `tiff_copy()`, the tw-xres has a value of 1234.56812 in that stage.
Then, in the tif file a value of 1234.568082 can be found.

I wouldn't have expected a loss of accuracy in this dimension due to the limited number accuracy. Could there be some conversion problems?

In addition, when integer values > 10000 are used as xres/yres values they are clipped. Can that be changed in a next version of libvips. This would be helpful since we are dealing with highres images.
Thanks, peter

**Comment by CoolFanyu** [comment]
When I use inches, it will convert the RESOLUTION to an integer.
When i use cm, it will save an integer calculated by (2^32-1)/RESOLUTION.
