### ISSUE TITLE
How to get background color of a png image?

### ISSUE THREAD

**Issue by 781545872** [libvips/libvips#2111]
![image](https://user-images.githubusercontent.com/13492988/108486597-335af200-72d9-11eb-832e-abc25b15f9e2.png)
I use identify -verbose to get background color.
Is there any way to get png background color using libvips?

**Comment by jcupitt** [comment]
I added a thing to git master libvips to read out background. You now see:

```
$ vipsheader -a audi-8.png 
audi-8.png: 2500x2500 ushort, 3 bands, rgb16, pngload
width: 2500
height: 2500
bands: 3
format: ushort
coding: none
interpretation: rgb16
xoffset: 0
yoffset: 0
xres: 200
yres: 200
filename: audi-8.png
vips-loader: pngload
background: 255 255 255 
```

Thanks for the suggestion.

**Comment by 781545872** [comment]
hello again @jcupitt.Is gif supported?I can get background color using magickwand.
![image](https://user-images.githubusercontent.com/13492988/108583068-2ccc8900-7372-11eb-921f-c0ad55046225.png)

**Comment by jcupitt** [comment]
I added bg for gifload as well.

```
$ vipsheader -a 3198.gif 
temp-0: 298x193 uchar, 3 bands, srgb, gifload
width: 298
height: 193
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: temp-0
vips-loader: gifload
n-pages: 139
loop: 0
delay: 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
background: 104 54 42 
```

**Comment by jcupitt** [comment]
Off-topic, but please don't post screenshots. Just copy-paste the text and put it in triple backticks, eg.:

```
    ```C
    int this_is = some( C_code );
    ```
```

Displays as:

```C
int this_is = some( C_code );
```

See: https://guides.github.com/features/mastering-markdown/

**Comment by 781545872** [comment]
I will pay attention to it later.Thanks for your answer!
