### ISSUE TITLE
Image Comparison in C

### ISSUE THREAD

**Issue by sethify** [libvips/libvips#2117]
Hello,

We have an existing image transform pipeline that crops, resizes and converts images as they are requested. We are experimenting with using libvips for this process (so far libvips has been amazing). 

As part of our the test suite we would like to compare images generated by the libvips solution vs the old solution. We don't expect them to be identical, but would like to know how different they are. Google led me here: 

https://stackoverflow.com/questions/36524206/is-possible-to-detect-if-two-images-are-the-same-using-ruby-vips8 

This solution seemed seemed very interesting. Fortunately/unfortunately we are using C (we wrote our own Go binding) and this magic doesn't appear to be as easy. 

I expect the team will have many ideas about how to perform diffing, so, access raw pixels is probably what I need. What is the best way with the C API? (Images are already in memory, loaded from a buffer).

Thank you.

**Comment by jcupitt** [comment]
Hello @sethify,

It sounds like something along the lines of spatial CIELAB would work for this case:

https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/SCIELAB

https://www.researchgate.net/publication/2629449_Color_Image_Quality_Metric_S-CIELAB_and_Its_Application_on_Halftone_Texture_Visibility

It's really simple -- just do a gauss blur before calculating delta E.

In ruby (for example):

```
def scielab(a, b, sigma)
    a.gaussblur(sigma).dE76(b.gaussblur(sigma)).avg
end
```

ie. blur both, calculate the delta E, then take the average. `sigma` is a parameter that sets the "scale" of the test, ie. how close the observer is.
