### ISSUE TITLE
vips_thumbnail fails when the target dimensions are bigger than the original, it is supposed to crop and only downsize

### ISSUE THREAD

**Issue by Andrewsville** [libvips/libvips#2157]
## Bug report

`vips_thubmnail` fails under specific circumstances with a not very clear error message `smartcrop: bad extract area`:

1. The input image has one or both dimensions smaller than the thumbnail.
2. `crop != VIPS_INTERESTING_NONE` meaning the image should be cropped to fill the whole thumbnail.
3. `size == VIPS_SIZE_DOWN` meaning the original image should only be downscaled, if necessary.

**To Reproduce**

1. Have an image, for example 300 x 300 px.
2. `vips thumbnail original.jpeg thumb.jpg 400 --height 200 --size down --crop entropy`
3. See the error `smartcrop: bad extract area`

**Expected behavior**

This combination of parameters and input image obviously means that `vips_thubmnail` cannot (completely) do what it is asked to - the image is not big enough to fill the thumbnail dimensions and vips cannot upscale it. This means that there are IMO two solutions:

1. Be strict and return an error but explain what is wrong (the image is too small and cannot be upscaled).
2. Do what's possible and generate a thumbnail with at lest one dimension smaller than the requested thumbnail size.

**Actual behavior**

`vips_thubmnail` fails with a not very clear error message `smartcrop: bad extract area` probably because it calculates coordinates out of the image bounds.

A simple workaround for the moment is to set the thumbnail dimensions to `min(original_dimension, requested_dimension)` making it do the suggested solution 2 from above.

**Environment**

Ubuntu Groovy with distribution vips:

```
andrew@andrew-x1:~$ vips -v
vips-8.10.2-Tue Oct 13 14:56:17 UTC 2020
```

as well as compiled from the latest 8.10.6-beta2 relase:

```
andrew@andrew-x1:/$ vips -v
vips-8.10.6-Mon Mar  8 15:23:31 UTC 2021
```

**Comment by jcupitt** [comment]
Hi @Andrewsville, ooops, I'm so sorry, this dropped off my todo list.

I've fixed this in master so it does your 2. above and this improvement should be in 8.12. Thank you very much for the idea!
