### ISSUE TITLE
Assume AV1 compression for *.avif files

### ISSUE THREAD

**Issue by der-eismann** [libvips/libvips#2160]
## Bug report

**Describe the bug**
When I execute `vips copy test.jpeg test.avif` it should automatically choose the correct codec. However I get an `heifsave: Unsupported compression` error since I don't have an HEIF codec installed, only AV1.
`vips heifsave main.jpeg vips_output.avif` produces the same error
`vips heifsave main.jpeg vips_output.avif --compression=av1` works fine

**To Reproduce**
1. Compile libvips with libheif that only has AV1 support
2. `vips copy test.jpeg test.avif`
3. `heifsave: Unsupported compression`

**Expected behavior**
vips should automatically choose the AV1 codec for *.avif files

**Actual behavior**
vips tries to use the HEIF codec which is not present

**Environment**
 - OS: Fedora 34 Beta
 - Vips: 8.10.6

**Comment by jcupitt** [comment]
Good idea! Thanks for the suggestion.

**Comment by jcupitt** [comment]
Added to master with https://github.com/libvips/libvips/commit/8c4486327e3a8b7d855c2a996b866df36b0ea0c1
