### ISSUE TITLE
Support libaom's latest 9 speed setting

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#2180]
Libaom now supports 9 speed setting: https://aomedia.googlesource.com/aom/+/refs/tags/v3.0.0

It would help to encode image faster. Can we add support for this?

**Comment by lovell** [comment]
Yes, a PR for this would be welcome but it would be dependent on https://github.com/strukturag/libheif/pull/451 being merged and released.

**Comment by jcupitt** [comment]
Looks like strukturag/libheif#451 has been merged! PRs very welcome.

**Comment by jcupitt** [comment]
.... I went ahead and made the change. This will be in 8.11.
