### ISSUE TITLE
The animation effect of the copied gif picture is incorrect

### ISSUE THREAD

**Issue by zplzpl** [libvips/libvips#2193]
## Bug report

The animated effect of the copied gifs is incorrect.

vips copy ./10.gif[n=-1] test.gif

original gif:
![10](https://user-images.githubusercontent.com/7931755/114302001-b50d1600-9af9-11eb-8bfb-3f7b902da42b.gif)

copy gif:
![test](https://user-images.githubusercontent.com/7931755/114302007-b76f7000-9af9-11eb-8e99-68d1e148d5c3.gif)

**Expected behavior**

One hundred percent copy

**Environment**
(please complete the following information)
 - OS: Ubuntu 16.04 (WSL)
 - Vips: libvips 8.10.2

**Comment by jcupitt** [comment]
Hi @zplzpl,

We've switched GIF libraries for vips 8.11 and your example loads correctly there. It might be possible to fix the loader in 8.10, I'll have a look.

**Comment by jcupitt** [comment]
This should be fixed in 8.11. Please open a new issue if it's still broken in that version.
