### ISSUE TITLE
Add full colour mode to vips_text

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2194]
`vips_text()` always outputs a one-band text mask.

The underlying font renderer has supported RGBA output for a while -- we should add support for this too, perhaps with an `rgba` flag to enable it. This would allow for things like colour emoji rendering, and also pango markup like `<span foreground="red">Red!</span>`.

It should be pretty easy.

**Comment by jcupitt** [comment]
It seems pangoft2 does not support colour rendering, unfortunately. I suppose we'd need to switch to pango cairo for text rendering, and paint to a bitmap.

Branch with a quick hack for colour pangoft2 output (which does not work):

https://github.com/libvips/libvips/tree/text-colour-rendering

Here's where pango does the rendering:

https://gitlab.gnome.org/GNOME/pango/-/blob/master/pango/pangoft2-render.c#L226

Search for `load_flags` and you'll see it's always mono.

**Comment by jcupitt** [comment]
`svgload` uses cairo to render to a bitmap, so we can probably copy-paste a lot of code from there.

**Comment by lovell** [comment]
Could the underlying problem be a limitation of freetype rather than pango? It looks like `load_flags` is based on the selected font e.g. `ft_render_mode_mono` will be used for 1-bit bitmap fonts, whereas `ft_render_mode_normal` will be used for vector fonts.

**Comment by jcupitt** [comment]
Actually, it wasn't so bad! That branch ^^ now uses cairo for text rendering. I see:

```
$ vips text x.png "😀<span foreground='red'>red</span><span background='cyan'>blue</span>" --dpi 300 --rgba
```

To make:

![x](https://user-images.githubusercontent.com/580843/114408051-f3a9db80-9ba0-11eb-9d14-68c6943fd36c.png)

We get proper extents for emojii too.

**Comment by jcupitt** [comment]
PR here https://github.com/libvips/libvips/pull/2195
