### ISSUE TITLE
vips alters alpha channel for HEIC files

### ISSUE THREAD

**Issue by george-polevoy** [libvips/libvips#2214]
## Bug report

Opacity is reduced from value 255 to value 239 in HEIC files with transparency exported with libvips.

**To Reproduce**
1. vips copy source-image.png output-image.heic[Q=60]. Also tried max quality, no difference. The error is similar with any quality setting. 
2. open both in photoshop, output-image.heic shows checker background even through the black letters which are opaque in the original. Note there is also a soft shadow with transparency in the image, it is also somewhat reduced. I don't know if it is gradually reduced or shifted.

**Expected behavior**
Expected to get a similar image with same transparency level.

**Actual behavior**
Expected to see a similar image in o.heic file as the o.png as well as the original.

**Screenshots**

Original:
![image](https://user-images.githubusercontent.com/2792885/115604077-9d980f00-a2e9-11eb-9701-74911e0faf99.png)

Resulting:
![image](https://user-images.githubusercontent.com/2792885/115603792-4134ef80-a2e9-11eb-801d-26a71d17b2f6.png)

**Environment**

``` sh
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

``` sh
vips --version
vips-8.10.6-Tue Mar 23 20:52:58 UTC 2021
```

I'm running libvips in a docker environment. The image I'm using is based on Ubuntu. The rest of the Dockerfile is taken from docker repository. 
``` docker
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
	build-essential \
	unzip \
	wget

# stuff we need to build our own libvips ... this is a pretty random selection
# of dependencies, you'll want to adjust these
RUN apt-get install -y \
	glib-2.0-dev \
	libexpat-dev \
	librsvg2-dev \
	libpng-dev \
	libgif-dev \
	libjpeg-dev \
	libexif-dev \
	liblcms2-dev \
	libheif-dev \
	liborc-dev \
    libtiff-dev \
    libwebp-dev



ARG VIPS_VERSION=8.10.6
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download

WORKDIR /usr/local/src

RUN wget -q ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
	&& tar xzf vips-${VIPS_VERSION}.tar.gz \
	&& cd vips-${VIPS_VERSION} \
	&& ./configure \
	&& make V=0 \
	&& make install \
	&& ldconfig
```

``` sh
pkg-config libheif --print-variables
builtin_h265_decoder
builtin_h265_encoder
exec_prefix
includedir
libdir
pcfiledir
prefix
```

**Comment by george-polevoy** [comment]
After a more close look at the dockerfile I realised that I was using Ubuntu 18, and libheif should be outdated there.

Let me try to use mcr.microsoft.com/dotnet/core/sdk:3.1-focal so it's ubuntu 20.04

Let's see if this solves the problem.

**Comment by jcupitt** [comment]
Hi @george-polevoy ,

I tried with the standard PNG demo image:

```
john@banana ~/pics $ vips copy PNG_transparency_demonstration.png x.heic
john@banana ~/pics $ vips copy x.heic x.png
```

And I see:

![PNG_transparency_demonstration](https://user-images.githubusercontent.com/580843/115609535-8e13c880-a2df-11eb-8780-345fa2c3073b.png)
![x](https://user-images.githubusercontent.com/580843/115609552-94a24000-a2df-11eb-86e0-ddc055704a11.png)

Average RMS of the difference in the alpha is c. 1, which feels about right for lossy compression. This is using the libheif that comes with ubuntu 20.10.

**Comment by george-polevoy** [comment]
I confirm that updating to 20.04 solves the issue
