### ISSUE TITLE
Failed to use same font

### ISSUE THREAD

**Issue by molfar** [libvips/libvips#2220]
When I try to load same font multiple times from same file - it works as expected

```
Vips::Image.text 'Sample text', font: "Helvetica 300", fontfile: '/tmp/helvetica.ttf'
Vips::Image.text 'Sample text', font: "Helvetica 300", fontfile: '/tmp/helvetica.ttf'
```

But when same font loaded multiple tomes, but from different files, it throws an error

```
Vips::Image.text 'Sample text', font: "Helvetica 300", fontfile: '/tmp/7yguhwergw.ttf'
Vips::Image.text 'Sample text', font: "Helvetica 300", fontfile: '/tmp/we34gwerf4.ttf'
```

I use latest libvips 8.10 and ruby-vips (2.1.0)

**Comment by molfar** [comment]
#950

**Comment by jcupitt** [comment]
Hi again, I changed that error into a warning in git master, so this should be better in 8.11. Thanks!
