### ISSUE TITLE
Libvips license is not complaint with Poppler license

### ISSUE THREAD

**Issue by gpoo** [libvips/libvips#2222]
I stumble upon the comment in https://github.com/libvips/libvips/issues/689#issuecomment-385033270 about not using MuPDF because it is AGPL licensed. Fair point.

However, I noticed the libvips is a derivative work of Poppler-glib, and Poppler is a GPL library, not LGPL. See https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/README.md#history-and-gpl-licensing

> Please note that xpdf, and thus poppler, is licensed under the GPL, 
> not the LGPL.  Consequently, any application using poppler must also
> be licensed under the GPL.

I am afraid that libvips is violating Poppler's license.

**Comment by jcupitt** [comment]
Hi @gpoo,

I'm not a lawyer (naturally) but here's my understanding:

- libvips can optionally be built to use Poppler for PDF rendering, but Poppler is not part of libvips.

- If the libvips poppler loader is enabled, then the program that uses poppler (via the libvips bridge) is indeed GPL, but the libvips source code is not itself GPL.

- We ship various binaries, eg. as part of sharp, but these do not have GPL libraries enabled for exactly this reason.

libvips 8.11 (coming in a couple of months) uses loadable modules for GPL libraries to make it easier for users and packagers to comply with the various licenses.

Here's a stackexchange thread which tries to explain the rules around optional dependencies:

https://softwareengineering.stackexchange.com/questions/175887/handling-optional-gpl-dependencies

**Comment by gpoo** [comment]
Indeed.
