### ISSUE TITLE
watermark text scales with image 

### ISSUE THREAD

**Issue by ringofhealth** [libvips/libvips#2225]
Hi!

Didn't really want to open a new issue with watermark since there is quite a few lying around regarding this issue. I was hoping to get a little bit of assistence on how to execute the final step of gluing the watermark with the main image. 

I want to watermark on the bottom right of the image, but the image size can vary greatly, so the text for the watermark should be 1/3 of the max image width. 

the operation I would like to do is

I have been looking at the ruby script you have wrote for this

https://github.com/libvips/ruby-vips/blob/master/example/watermark.rb

its pretty helpful, and I feel like I gotten pretty far,

I am using elixir to do the conversion and there is a library called vix that basically maps most of the native vips operation just like the ruby vips, with the exeception that elixir is a functional based lang, so all the operations are pass through 

Here is what I have so far

```

  def convert(input, output, {:resize_watermark, size, user}) do
    with {:ok, vipsimg} <- Image.new_from_file(input),
         {:ok, max_width} <- Image.width(vipsimg),
         {:ok, {text, _}} <-
           Operation.text("watermark TEXT", width: round(max_width), dpi: round(max_width / 3), font: 'Arial'),
         {:ok, overlay} <- Operation.composite2(vipsimg, text, :VIPS_BLEND_MODE_OVER),
         {:ok, final} <- Operation.thumbnail_image(overlay, size),
         :ok <- Vix.Vips.Image.write_to_file(final, output) do
      {:ok, output}
    else
      {:error, _reason} = e ->
        e

      e ->
        {:error, e}
    end
  end
end
```

so the issue is that in the ruby script this line here

`overlay = (text.new_from_image [255, 128, 128]).copy interpretation: :srgb` 

It looks like the script is generating a new image file from the text layer in memory then using bandjoin to compose it. The library I am using does not offer something like this as far as I can tell

https://hexdocs.pm/vix/Vix.Vips.Image.html#content

here is the operation that it currently supports

https://hexdocs.pm/vix/Vix.Vips.Operation.html#summary

my current code  generates the overlay as WHITE text on BLACK background. I am not sure what step I need to take to make the watermark Semi transparent. 

What should I do here?

**Comment by jcupitt** [comment]
Hello, yes, `new_from_image` just makes a new constant image based on an existing image. The code is here:

https://github.com/libvips/ruby-vips/blob/master/lib/vips/image.rb#L505

It should be simple to add to vix.

**Comment by ringofhealth** [comment]
it sounds like `overlay = (text.new_from_image [255, 128, 128]).copy interpretation: :srgb` is REQUIRED to make the watermark image transparent

**Comment by ringofhealth** [comment]
vix implemented #new_from_image, this issue is resolved
