### ISSUE TITLE
No PNG support in libvips under prebuilt windows binary

### ISSUE THREAD

**Issue by SkyDiverCool** [libvips/libvips#2233]
## Bug report

When trying to use(decode) any png image with the prebuilt vips windows binary it outputs
`im_png2vips: no PNG support in your libvips`
While a dll is available in the same folder for both libpng and libspng

**To Reproduce**
1. Attempt to decode any png image
2. See Error `im_png2vips: no PNG support in your libvips`

**Screenshots**
![image](https://user-images.githubusercontent.com/11019122/116649692-8f508f80-a988-11eb-95ff-c1daa3b05007.png)
![image](https://user-images.githubusercontent.com/11019122/116649710-9a0b2480-a988-11eb-877d-3921332f5308.png)

**Environment**
 - OS: Windows 10
 - Vips: 8.10.6 (vips-dev-w64-all-8.10.6)

**Comment by jcupitt** [comment]
Hi @SkyDiverCool,

`im_png2vips` is the old vips7 API. libvips 8.10 has a new PNG loader and we didn't implement a vips7 wrapper for it, perhaps we should have done.

How are you using the function? At the command-line, or from a language? At the CLI, the new vips8 operation is:

```
vips pngload input-file.png output-file
```

It should be a bit quicker.

**Comment by jcupitt** [comment]
I just saw your screenshot. Try this;

```
vips tiffsave something.png output.tif --compression jpeg --Q 75 --tile --pyramid --tile-width 512 --tile-height 512
```

It will be a little faster.

The vips8 CLI documentation is here:

https://libvips.github.io/libvips/API/current/using-cli.html

**Comment by jcupitt** [comment]
I added a basic vips7 wrapper for the new png loader, but performance will be pretty bad. I'd update to the new vips8 interface.
