### ISSUE TITLE
How to compile and use on RPi4 ? 

### ISSUE THREAD

**Issue by AndKe** [libvips/libvips#2236]
I downloaded https://github.com/libvips/libvips/releases/download/v8.10.6/vips-8.10.6.tar.gz
did ./configure , make , and sudo make install.

still vips -v  shows the old version 8.7.4
how do I actually switch to the compiled version?

**Comment by jcupitt** [comment]
Hi @AndKe,

`configure` will put vips into `/usr/local`, so you have to have that first on your PATH, or you need to remove the system one. 

Removing the system one is probably easiest, just `apt remove libvips` I think.
