### ISSUE TITLE
Banding issues with gamma adjustment

### ISSUE THREAD

**Issue by Daiz** [libvips/libvips#2238]
### Environment
- OS: Ubuntu 18.04 / Windows 10
- VIPS: 8.10.6
- ImageMagick: 6.9.1 Q16

### Describe the bug
I am trying to scale color images in linear light / with gamma correction, much like I was doing with ImageMagick beforehand, but trying to do the same with libvips results in notable banding artifacts.

This is a crop of one of my source images:

![source](https://user-images.githubusercontent.com/3596343/117126822-fb296280-ada3-11eb-8b67-58e3e64b3a69.png)

And here are the results of downscaling it to 320x320 with both ImageMagick and libvips, both without and with gamma correction, displayed at 150% zoom:

![vips-banding](https://user-images.githubusercontent.com/3596343/117126957-2613b680-ada4-11eb-8f6d-6d90dc83c325.png)

As you can see, the gamma-adjusted VIPS resize demonstrates notable banding not present in the other variants.

### To Reproduce

Here are the commands used to generate the examples in the above image:

**ImageMagick (default)**
```
$ convert source.png -filter Mitchell -resize x320 resize-nogamma-imagick.png
```

**ImageMagick (gamma)**
```
$ convert source.png -colorspace sRGB -gamma 0.454545 -filter Mitchell -resize x320 resize-gamma-imagick.png
```

**libvips (default)**
```
$ vips resize source.png resize-nogamma-libvips.png 0.32 --kernel mitchell
```

```javascript
sharp("source.png")
  .resize(320, 320, { kernel: "mitchell" })
  .png()
  .toFile("resize-nogamma-libvips.png");
```

**libvips (gamma)**
```
$ vips gamma source.png t1.v --exponent 0.454545
$ vips resize t1.v t2.v 0.32 --kernel mitchell
$ vips gamma t2.v resize-gamma-libvips.png --exponent 2.2
```

```javascript
sharp("source.png")
  .resize(320, 320, { kernel: "mitchell" })
  .gamma(2.2)
  .png()
  .toFile("resize-gamma-libvips.png");
```

### Expected behavior
Gamma adjustment for the goal of scaling in linear light should not result in notable banding artifacts.

### Actual behavior
Using gamma adjustment can result in very notable banding artifacts.

### Additional context
I am primarily using libvips via [sharp](https://github.com/lovell/sharp), and I included the original sharp code samples that made me notice the issue. I then replicated what sharp does with the libvips CLI to confirm what the sharp pipeline is doing and the results were indeed the same. The sharp commands were ran in Ubuntu 18.04, while I used the libvips CLI on Windows 10.

Based on the fact that I am using a Q16 ImageMagick build (16 bits per channel), my first guess would be that libvips operates internally only at 8 bits per channel, and the results of gamma operations are rounded at each step, thus resulting in banding in the final output?

**Comment by Daiz** [comment]
Okay, it seems like my guess above was indeed correct, as converting to rgb16 before running the rest of the pipeline does indeed give the results I desire:

![resized-gamma16-libvips](https://user-images.githubusercontent.com/3596343/117131571-45addd80-adaa-11eb-99ba-5d093ef7ccca.png)

With this being the set of CLI commands used:

```
$ vips colourspace source.png tt1.v rgb16
$ vips gamma tt1.v tt2.v --exponent 0.454545
$ vips resize tt2.v tt3.v 0.32 --kernel mitchell
$ vips gamma tt3.v tt4.v --exponent 2.2
$ vips colourspace tt4.v resized-gamma16-libvips.png srgb
```

With that being the case, I'm off to file an issue on sharp's end instead, as it doesn't seem to provide a way to run pipelines in 16 bits per channel as-is...

**Comment by jcupitt** [comment]
sharp has `.toColourspace('rgb16')`, perhaps that would fix it?

https://sharp.pixelplumbing.com/api-colour#tocolourspace

Yes, as you guessed, `gamma` does not change the image bit depth. `rgb16` is probably a good choice since `gamma` has a fast path for 8 and 16-bit images, but not for float.

**Comment by Daiz** [comment]
That's what I first reached for, but using it doesn't actually do anything to get rid of the banding:

![test](https://user-images.githubusercontent.com/3596343/117133211-a2aa9300-adac-11eb-8de2-8bc68d2ccafb.png)

Looking at the pipeline code, I think it's still doing all the internal processing at 8 bits per channel, and only converting to 16 bits per channel at the end of that... which is the basically the opposite of what I want, which is to run the pipeline with 16 bits per channel and then convert to 8 bits per channel at the end.

**Comment by jcupitt** [comment]
Yes, sharp looks like an API to an image processing library, but behind the scenes it's a fixed pipeline and the `.toColourspace()` etc. methods are switches that turn parts of that fixed pipeline on or off. It's why you can give them in any order. Or that's my understanding.

I made a pure JS (just FFI) libvips binding for node as an experiment:

https://github.com/libvips/node-vips

which is a true API, but I've never used it in production and it needs some expert to kick the tires and no doubt fix my terrible JS.

**Comment by Daiz** [comment]
Upon further investigation, it seems that sharp's pipeline operates in the *depth of the input*. Using the following code...

```javascript
const rgb16png = await sharp(input)
  .toColorspace("rgb16")
  .png()
  .toBuffer();

await sharp(rgb16png)
  .resize(320, 320, { kernel: "mitchell" })
  .gamma(2.2)
  .toColorspace("srgb")
  .png()
  .toFile(output);
```

...I can actually get the desired result with sharp:

![resized-rgb-16bpc-gamma-sharp](https://user-images.githubusercontent.com/3596343/117134904-e7372e00-adae-11eb-8b52-4e346fe8ec4f.png)

However, having to use two separate sharp pipelines for this is not very optimal - ideally, I think would like to do something like this:

```javascript
await sharp(input)
  .colorspace("rgb16")
  .resize(320, 320, { kernel: "mitchell" })
  .gamma(2.2)
  .toColorspace("srgb")
  .png()
  .toFile(output);
```

With the idea obviously being that the `.colorspace` would set the colorspace that the pipeline is ran in, while the existing `.toColorspace` defines the colorspace for the final output, as it already does.

**Comment by lovell** [comment]
There's a future possible enhancement to optionally use 16-bit linear at https://github.com/lovell/sharp/issues/1317

**Comment by Daiz** [comment]
@lovell I presume that would still benefit from the `gamma` fast path for 16-bit images mentioned above? And what if any are the current plans for the actual implementation, seeing as the issue has been open since 2018? Would the `.colorspace()` operator I suggested above be possibly simpler to implement?

**Comment by lovell** [comment]
> And what if any are the current plans for the actual implementation, seeing as the issue has been open since 2018? 

PRs to implement enhancements are always welcome.

**Comment by Daiz** [comment]
For my personal purposes just running the pipeline in rgb16 would be enough (like how feeding sharp an rgb16 image right now does) so that's what any PR I would open on the matter would aim to achieve, whether it be via eg. `sharp(input, { colorspace: "rgb16" })` or `sharp(input).colorspace("rgb16")`. If either of these sounds like something that sharp would accept and merge, then I could definitely take a stab at it.

**Comment by lovell** [comment]
@Daiz Great, thank you for offering, the `{ linear: true }` constructor option would be equivalent to running the pipeline in RGB16 so if you're able to help that would most definitely be a welcome improvement.
