### ISSUE TITLE
test suite fails on armhf

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#2244]
I am in the process of building binary packages of libvips for armhf architecture (e.g. RPi). While there is apparently no problem in compiling the sources, it fails on some tests of the included test suite. Please have a look at the log file attached.

Thanks,
Thomas
[test-suite.log](https://github.com/libvips/libvips/files/6445531/test-suite.log)

**Comment by jcupitt** [comment]
Yes, it's been reported before, someone with arm hardware for testing needs to look into it.

**Comment by ewelot** [comment]
I believe I found the reason why some tests are currently failing on armhf, at least on RPi.

It turns out that it is not architecture related. The tests are failing due to specific locale settings, which on the Raspbian OS is set to a non-empty LC_ALL shell variable whereas on other Linux distributions, e.g. Debian or Ubuntu this variable is not set.

In my case (a current Raspbian system with german language settings) it is `LC_ALL=de_DE.UTF-8` The result of `vips abs` is a floating point number and has a language specific string representation. Computing the value of `dif` in the function `test_difference()` causes a syntax error, the failing command being
```
echo '0,000000 <= 10' | bc -l
```

A simple solution is to always run the tests with an empty variable LC_ALL. This ensures standard representation of floating point numbers e.g. resulting in
```
echo '0.000000 <= 10' | bc -l
```

Cheers,
Thomas

**Comment by jcupitt** [comment]
Oh how funny. 

The tester already has `export LC_NUMERIC=C`, but I guess that's not enough in this case. Could you check if adding `unset LC_ALL` fixes this?

The line should go in here:

https://github.com/libvips/libvips/blob/master/test/variables.sh.in#L13

ie. in `variables.sh.in`. You'll need to re-run `configure` after making the change.

**Comment by ewelot** [comment]
That is exactly the place where I modified the source. The patch I used is as follows:
```
Description: unset LC_ALL to avoid error in test suite on Raspbian
 unsetting LC_ALL is required on Raspbian for calculations done by bc
Author: T. Lehmann, t.lehmann@mailbox.org
Bug: https://github.com/libvips/libvips/issues/2244
Last-Update: 2021-05-09
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
Index: vips-8.10.6/test/variables.sh.in
===================================================================
--- vips-8.10.6.orig/test/variables.sh.in
+++ vips-8.10.6/test/variables.sh.in
@@ -10,6 +10,7 @@ vipsthumbnail=$top_srcdir/tools/vipsthum
 vipsheader=$top_srcdir/tools/vipsheader
 
 # we need bc to use '.' for a decimal separator
+unset LC_ALL
 export LC_NUMERIC=C
 
 # test for file format supported
```
and I was able to successfully compile and build packages for Raspbian linux. I am not sure why and when the system setup has introduced a non-empty setting of LC_ALL which is highly discouraged (ref. https://wiki.debian.org/Locale).

**Comment by jcupitt** [comment]
If you make a PR, I'll merge and you'll get the credit. Or I can just make the change if you prefer.

**Comment by ewelot** [comment]
Just make the change, that will be faster. I still need to learn how to do a PR properly ...

**Comment by jcupitt** [comment]
OK, done.
