### ISSUE TITLE
regression: ppmsave doesn't honour strip option

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#2245]
The same bug was reported in issue #1913. It was fixed in master but apparently the fix was removed later on which means
the issue is still present in release 8.10.6.

How to reproduce:
```
convert rose: rose.ppm
vips linear rose.ppm x.ppm[strip=true] 1 10
hexdump -C x.ppm | head -5
```
Kind regards,
Thomas

**Comment by jcupitt** [comment]
Yes, this is a 8.11 feature. It's in git master libvips.
