### ISSUE TITLE
Strip all metadata except the color profile?

### ISSUE THREAD

**Issue by grishka** [libvips/libvips#2282]
I'd like to write a webp file while stripping metadata like EXIF but keeping the color profile so the colors always look accurate. I'm using libvips in a server application and the files I'm processing are uploaded by users, so it's important to not leak any sensitive data that might be in EXIF tags. I'm currently passing `strip=true` to `vips_image_write_to_file` but that strips everything, including the color profile.

**Comment by jcupitt** [comment]
Hi @grishka,

I would remove all metadata except the ICC profile. In Python, something like:

```python
# take a private copy of the image before we start modifying it 
image = image.copy()

for field in image.get_fields():
    if field != "icc-profile-data":
        image.remove(field)

image.write_to_file(filename)
```

See https://libvips.github.io/libvips/API/current/libvips-header.html#vips-image-get-fields
