### ISSUE TITLE
arrayjoin needs hoverlap / voverlap arguments

### ISSUE THREAD

**Issue by Frosin** [libvips/libvips#2286]
I have a collection of splitted images using the command: 

```
vips dzsave x.tif zoomed --overlap = 1 --tile-size = 256
```

But I can't get the original image from the fragment collections using the command:

```
vips arrayjoin $(ls * .jpeg | sort -t_ -k2g -k1g) x2.tif[tile,pyramid,compression=jpeg] --across 5 - -hspacing 256 --vspacing 256
```

because some of the `0_x.jpeg` files do not have a size of 258x258 pixels. For example, `0_0.jpeg` is 257x257 and `0_1.jpeg` is 257x258. What is the reason for this? How do I collect the correct image?

**Comment by jcupitt** [comment]
Hi @Frosin,

I suppose the best solution would be for `arrayjoin` to have optional `hoverlap` and `voverlap` arguments. I'll tag this as an enhancement.

As a workaround, you could add a line of padding to the left and top of the left and top edge tiles. Could that work for you?

**Comment by Frosin** [comment]
@jcupitt Thank you very much! I guess this should work, but I don't know how to add 1px padding using vips yet, how can I do that?

**Comment by jcupitt** [comment]
Are you only using the CLI, or can you use python / ruby / C# etc. etc.?

**Comment by Frosin** [comment]
Unfortunately there is no library for golang so I use the cli

**Comment by jcupitt** [comment]
There are two or three Go bindings, though I've not been involved with them and don't know how well they work.

At the CLI you can do something like (untested):

```bash
for tile in 0_*.jpg; do 
  vips gravity $tile new_$tile east 258 258
done
for tile in *_0.jpg; do 
  vips gravity $tile new_$tile south 258 258
done
vips gravity 0_0.jpeg new_0_0.jpg south-east 258 258
```

Then check the tiles and move them over the originals.

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-gravity

**Comment by Frosin** [comment]
Many thanks! It didn't quite work for me because the dimensions of the outer images are less than 258, but I got the general idea

**Comment by jcupitt** [comment]
Thinking about this again, hoverlap / voverlap wouldn't work since then columns could vary in size, and arrayjoin needs a regular grid.

I think the best solution is to pad the left and top rows so all tiles are the same size.
