### ISSUE TITLE
`vips_text` fails to render large text input (Cairo's 32k limit?)

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#2300]
It seems that `vips_text` (or one of the dependencies used for text rendering) fails to render when a large text input is given. This was reported downstream at https://github.com/kleisauke/net-vips/issues/129.

From that bug report, the user is trying to render a text with a size of 3.5Gb(!) which generates odd/overflowed dimensions. In order to reproduce this bug across the various text rendering systems, I came up with this script:
<details>
  <summary>find.py</summary>

```python
import sys

import pyvips
from bisect import bisect_right

if len(sys.argv) != 3:
    print(f'usage: {sys.argv[0]} start end')
    sys.exit(-1)

def repeat_text(times):
    return pyvips.Image.text('Lorem ipsum dolor sit amet ' * times, font='Arial 22px', width=512)

class ImageRangeSearch(object):
    def __init__(self, start, end):
        self.start = start;
        self.end = end;
    def __len__(self):
        return end - start - 1;
    def __getitem__(self, index):
        print(f'trying {self.start + index} ...')
        return repeat_text(self.start + index)

class ImageAvgCompare(object):
    def __init__(self, value):
        self.value = value
    def __lt__(self, other):
        avg = other.avg()
        print(f'\tavg = {avg}')
        return avg <= self.value
    def __gt__(self, other):
        avg = other.avg()
        print(f'\tavg = {avg}')
        return avg > self.value

start = int(sys.argv[1])
end = int(sys.argv[2])

# avg == 0.0 is considered a render error,
# find the first bad occurrence of this image
needle = ImageAvgCompare(0.0)
haystack = ImageRangeSearch(start, end)

index = start + bisect_right(haystack, needle);

print(f'first bad image: {index}')

good = repeat_text(index - 1)
bad = repeat_text(index)

good.write_to_file(f'good-{index - 1}.png');
bad.write_to_file(f'bad-{index}.png');
```
</details>

This script tries to repeat the well-known "Lorem ipsum" text until it encounters a rendering error (`avg == 0.0`) using a simple bisection algorithm. Running that on libvips 8.11 produces (on my Fedora PC):
```bash
$ python find.py 0 6000
trying 2999 ...
	avg = 0.0
trying 1499 ...
	avg = 41.41576955957927
trying 2249 ...
	avg = 41.405755552710744
trying 2624 ...
	avg = 0.0
trying 2437 ...
	avg = 0.0
trying 2343 ...
	avg = 41.41334929023536
trying 2390 ...
	avg = 0.0
trying 2367 ...
	avg = 0.0
trying 2355 ...
	avg = 41.40915790438929
trying 2361 ...
	avg = 0.0
trying 2358 ...
	avg = 41.42392341049288
trying 2360 ...
	avg = 0.0
trying 2359 ...
	avg = 0.0
first bad image: 2359
$ vipsheader good-2358.png
good-2358.png: 500x32746 uchar, 1 band, b-w, pngload
$ vipsheader bad-2359.png 
bad-2359.png: 500x32771 uchar, 1 band, b-w, pngload
```

Looking at the dimensions, it seems that it has reached the 32k limit of Cairo(?). If so, perhaps we can return an error if one of the dimensions exceeds 32767 pixels?

**Comment by jcupitt** [comment]
Holy crap! That's a lot of text.

Yes, Cario has a very well documented, and very annoying, 16.16 fixed point coordinate limit. It's unfixable, sadly.

There's a PR to make svgload return an error for coordinates out of bounds, it sounds like text needs one too.

**Comment by kleisauke** [comment]
> There's a PR to make svgload return an error for coordinates out of bounds, it sounds like text needs one too.

Did you mean PR #2298? I had a quick look, but didn't notice any error logic for images larger than 32767 pixels on either dimension. I don't think `rsvg_handle_render_document` contains this logic either, since commit https://github.com/GNOME/librsvg/commit/90779ad40f9a7d1d6ba294e663973ff9c895d4e0 only introduces this limit in the `rsvg-convert` utility.

**Comment by jcupitt** [comment]
Something inside `rsvg_handle_render_document` has the code, perhaps cairo? I see:

```
$ vipsheader circle.svg[scale=1000]
circle.svg: 100000x100000 uchar, 4 bands, srgb, svgload
$ vips copy circle.svg[scale=1000] x.png

(vips:3705078): librsvg-WARNING **: 14:40:20.670: cannot render on a cairo_t with a failure status (status="invalid value (typically too big) for the size of the input (surface, pattern, etc.)")

(vips:3705078): VIPS-WARNING **: 14:40:20.670: error in tile 0 x 0

(vips:3705078): VIPS-WARNING **: 14:40:20.923: error in tile 0 x 0
svgload: SVG rendering failed
glib: cairo error: "invalid value (typically too big) for the size of the input (surface, pattern, etc.)"

vips2png: unable to write to target x.png
```

There are other SVG rendering libraries, but they all seem to use cairo, so I suppose they'll all have this problem.

There's the KDE one, which is supposed to be nice, but of course that would pull in a ton of extra code.

**Comment by lovell** [comment]
> There are other SVG rendering libraries, but they all seem to use cairo, so I suppose they'll all have this problem.

We previously considered [resvg](https://github.com/RazrFalcon/resvg) in https://github.com/libvips/libvips/discussions/2048, which might solve this problem.

The latest version renders via a rust port of Skia, which appears to use uint32 for dimensions - see https://github.com/RazrFalcon/tiny-skia/blob/2e6aa247308867f2715399d12dc2afb454b925c7/src/pixmap.rs#L43-L44 - plus SVG2 support is under heavy development - see https://github.com/RazrFalcon/resvg/issues?q=is%3Aissue+is%3Aopen+label%3Asvg2

**Comment by jcupitt** [comment]
Oh cool, I forgot that issue, you're right.

So let's just have a dimension check in vips_text(), as you originally said Kleis.

**Comment by jcupitt** [comment]
I had a quick go. With libvips master I now see:

```
john@banana ~/try $ vips text x.png "hello world" --dpi 37000
john@banana ~/try $ vips text x.png "hello world" --dpi 38000
text: text image too large
john@banana ~/try $ vipsheader x.png
x.png: 32721x4773 uchar, 1 band, b-w, pngload
```
