### ISSUE TITLE
libvips generates larger files than imagemagick with mozjpeg when converting PNG to JPEG

### ISSUE THREAD

**Issue by brenogazzola** [libvips/libvips#2314]
Hi! I'm testing switching from image magick to libvips and have compiled mozjpeg/imagemagick/libvips from source. For some reason libvips files are much bigger than image magick files at the same quality level. I've went over the `jpegsave` documentation and as much image magick documentation as I could, but could not find the reason for the difference. What am I missing?

**To Reproduce**
The file below is an artwork that belongs to me, feel free to download it:

```
$ wget https://s3.sa-east-1.amazonaws.com/active-storage-dev.festalab.com.br/ojg3oam9u20gz7860s7d699pluaa
$ mv ojg3oam9u20gz7860s7d699pluaa original.png
$ convert original.png -quality 85 im.jpg
$ vips jpegsave original.png vips.jpg -Q 85
$ du -h *

328K	im.jpg
3.2M	original.png
404K	vips.jpg

$ convert original.png -quality 50 im.jpg
$ vips jpegsave original.png vips.jpg -Q 50
$ du -h *

144K	im.jpg
3.2M	original.png
204K	vips.jpg
```

**Expected behavior**
Vips should generate an image with the same file size as image magick, since they are both using mozjpeg

**Actual behavior**
Vips file is much larger than image magicks.

**Environment**
OS: Ubuntu 20.04
Mozjpeg: 4.0.3
ImageMagick: 7.1.0-0
Libvips: 8.11.0

**Additional context**
The Ansible playbooks used to compile everything:

1 - Buildtools and dev libs (no jpeg-turbo): [here](https://github.com/FestaLab/railway/blob/main/roles/ami_buildtools/tasks/main.yml)
2 - Mozjpeg: [here](https://github.com/FestaLab/railway/blob/main/roles/ami_mozjpeg/tasks/main.yml)
3 - ImageMagick: [here](https://github.com/FestaLab/railway/blob/main/roles/ami_imagemagick/tasks/main.yml)
4 - Libvips: [here](https://github.com/FestaLab/railway/blob/main/roles/ami_libvips/tasks/main.yml)

Output of `convert --version`
```
convert -version
Version: ImageMagick 7.1.0-0 Q16 x86_64 2021-06-13 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib fontconfig freetype heic jbig jng jpeg lcms lzma openexr pangocairo png tiff webp x xml zlib
```

Output of `vips --vips-config`
```
enable debug: no
enable deprecated library components: yes
enable modules: yes
enable docs with gtkdoc: no
gobject introspection:  no
RAD load/save: yes
Analyze7 load/save: yes
PPM load/save: yes
GIF load:  yes
generate C++ docs: no
use fftw3 for FFT: yes
accelerate loops with orc: yes
ICC profile support with lcms: yes (lcms2)
zlib: yes
text rendering with pangocairo: yes
font file support with fontconfig: yes
EXIF metadata support with libexif: yes
JPEG load/save with libjpeg: yes (pkg-config)
JXL load/save with libjxl: yes (dynamic module: yes)
JPEG2000 load/save with libopenjp2: no
PNG load with libspng: no
PNG load/save with libpng: yes (pkg-config libpng >= 1.2.9)
8bpp PNG quantisation: yes
TIFF load/save with libtiff: yes (pkg-config libtiff-4)
image pyramid save: yes
HEIC/AVIF load/save with libheif: yes (dynamic module: yes)
WebP load/save with libwebp: yes
PDF load with PDFium:  no
PDF load with poppler-glib: yes (dynamic module: yes)
SVG load with librsvg-2.0: yes
EXR load with OpenEXR: yes
slide load with OpenSlide: yes (dynamic module: yes)
Matlab load with matio: yes
NIfTI load/save with niftiio: no
FITS load/save with cfitsio: yes
Magick package: MagickCore (dynamic module: yes)
Magick API version: magick7
load with libMagickCore: yes
save with libMagickCore: yes
```

**Comment by lovell** [comment]
Hi, did you see the mozjpeg-related options in the documentation?

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave ?

You'll need to set `trellis_quant`, `overshoot_deringing`, `optimize_scans` and `quant_table`.

**Comment by jcupitt** [comment]
Hi @brenogazzola,

I tried your image with the mozjpeg options:

```
$ vips jpegsave original.png x.jpg --Q 85 --optimize-scans --trellis-quant --quant-table=3 --interlace
$ ls -l x.jpg 
-rw-r--r-- 1 root root 332943 Jun 23 08:24 x.jpg
```

About the same as IM.

**Comment by brenogazzola** [comment]
Ah... I just saw my mistake. I tried the same thing in a machine that did not have MozJPEG installed:
```
$ wget https://s3.sa-east-1.amazonaws.com/active-storage-dev.festalab.com.br/ojg3oam9u20gz7860s7d699pluaa
$ mv ojg3oam9u20gz7860s7d699pluaa original.png
$ convert original.png -quality 85 im.jpg
$ vips jpegsave original.png vips.jpg -Q 85
$ du -h *

400K	im.jpg
3.2M	original.png
404K	vips.jpg
```

It seems that ImageMagick was automatically applying the extra MozJPEG options without my knowledge. I guess that explains why I couldn't find them anywhere in the docs.

Sorry guys, thanks for the help.
