### ISSUE TITLE
Cannot get VIPS to export AVIF

### ISSUE THREAD

**Issue by maxence33** [libvips/libvips#2324]
Hello 
I am currently trying to have Vips convert files to AVIF but without much luck. 
I am opening this ticket as I mistakenly commented on a closed ticket ( https://github.com/libvips/libvips/issues/1364 ).

Basically I installed libde265 and libx265 on Untunu 18.04
then compiled libheif and Vips. 
All good, no complaint and it seemed to be happy with AVIF too : 

```
maxence@maxence-SSD:~$ vips -l | grep _target
          VipsForeignSaveCsvTarget (csvsave_target), save image to csv (.csv), priority=0, mono
          VipsForeignSaveMatrixTarget (matrixsave_target), save image to matrix (.mat), priority=0, mono
          VipsForeignSaveVipsTarget (vipssave_target), save image to target in vips format (.v, .vips), priority=0, any
          VipsForeignSavePpmTarget (ppmsave_target), save to ppm (.ppm, .pgm, .pbm, .pfm), priority=0, rgb
          VipsForeignSaveRadTarget (radsave_target), save image to Radiance target (.hdr), priority=0, rgb
          VipsForeignSavePngTarget (pngsave_target), save image to target as PNG (.png), priority=0, rgba
          VipsForeignSaveJpegTarget (jpegsave_target), save image to jpeg target (.jpg, .jpeg, .jpe), priority=0, rgb-cmyk
          VipsForeignSaveWebpTarget (webpsave_target), save image to webp target (.webp), priority=0, rgba-only
          VipsForeignSaveHeifTarget (heifsave_target), save image in HEIF format (.heic, .heif, .avif), priority=0, rgba-only
```
Though Heic works well but no AVIF
```
maxence@maxence-SSD:~/Desktop/test images$ vips copy i.jpg i.avif
heifsave: Unsupported compression
```
I realised I was maybe missing libaom which I installed but then libheif wouldn't compile. (please see here https://github.com/strukturag/libheif/issues/526 )

Well I was kinda lost but then I found these PPA : 
https://launchpad.net/~strukturag/+archive/ubuntu/libheif

Then added **ppa:strukturag/libheif** and **ppa:strukturag/libde265** and sudoed an update. 
So as per my (short) knowledge of Ubuntu I should have an working AVIF friendly libheif version now (?)

Then I tried to compile with the tarball of another post : http://www.rollthepotato.net/~john/vips-8.11.1.tar.gz
But still no luck with AVIF. Yet for example HEIC back and forth to JPEG seem to work fine. (and any other conversion from common formats to JPEG, WEBP etc ..)

If of any interest my ruby interpreter returns this at the moment: 

```
VIPS-INFO: 11:27:47.957: found /usr/local/lib/vips-modules-8.11
VIPS-INFO: 11:27:47.957: using configure-time prefix
VIPS-INFO: 11:27:47.957: VIPS_PREFIX = /usr/local
VIPS-INFO: 11:27:47.957: VIPS_LIBDIR = /usr/local/lib
VIPS-INFO: 11:27:47.957: prefix = /usr/local
VIPS-INFO: 11:27:47.957: libdir = /usr/local/lib
VIPS-INFO: 11:27:47.958: searching "/usr/local/lib/vips-modules-8.11"
VIPS-INFO: 11:27:47.958: loading "/usr/local/lib/vips-modules-8.11/vips-heif.so"

(process:7747): GLib-GObject-WARNING **: 11:27:47.959: cannot register existing type 'VipsForeignLoadHeif'

(process:7747): GLib-CRITICAL **: 11:27:47.959: g_once_init_leave: assertion 'result != 0' failed

(process:7747): GLib-GObject-CRITICAL **: 11:27:47.959: g_type_register_static: assertion 'parent_type > 0' failed

(process:7747): GLib-CRITICAL **: 11:27:47.959: g_once_init_leave: assertion 'result != 0' failed
```

**Comment by jcupitt** [comment]
Hi @maxence33,

It works like this:

```
libvips <-- libheif <---+--- avif libs
                        |
                        +--- heic libs
```

ie. you need to build libheif with support for the libraries you want to use for AVIF encode and decode, and HEIC encode and decode. AVIF is a HEIF container with the AV1 codec, and HEIC is a HEIF container with the h265 codec.

You can check which ones you have set up like this:

```
$ pkg-config libheif --print-variables
builtin_avif_decoder
builtin_avif_encoder
builtin_h265_decoder
builtin_h265_encoder
exec_prefix
includedir
libdir
pcfiledir
prefix
```

So I have support for AVIF and HEIC enabled. Once you have them both turned on, you should be able to load and save AVIF and HEIC.

Ubuntu 18.04 is pretty old now, it'll be quite challenging to get recent versions of everything built there, could you update to a more recent stable version of Ubuntu?

I'm not sure what's causing those warnings. I'd guess you have several installs of libvips (perhaps one with modules enabled and one without?) and they are crashing into each other. I'd wipe the install area and try again.

**Comment by jcupitt** [comment]
Ah OK, so it should work then. Wipe the install area, rebuild libvips, and it should be fine.

**Comment by jcupitt** [comment]
I made you a test install on ubuntu 18.04:

https://github.com/jcupitt/docker-builds/blob/master/libvips-ubuntu18.04/Dockerfile

Just run those commands top-to-bottom and it should work.

**Comment by maxence33** [comment]
Hi John, 
Just upgraded to Ubuntu 20.04 
Seems Vips got corrupt in the way with
`vips: error while loading shared libraries: libmatio.so.4: cannot open shared object file: No such file or directory `

I will remove the current version installed as I see in Synaptic (looks like it is 8.9.1-2) and proceed with your docker file. 
I see your comments for Ubuntu 18.04 and will adapt to Ubuntu 20.04 . Should even be easier now

**Comment by jcupitt** [comment]
After you update ubuntu you'll need to rebuild everything, since your old build will be depending on libraries that have been replaced. Wipe your install area and rebuild.

**Comment by maxence33** [comment]
Hi John 
Everything now works flawlessly 👍
Thank you

**Comment by jcupitt** [comment]
That's great! I'll close.

**Comment by saurabhbhatia** [comment]
Just adding here for documentation purposes, `libheif ` with `apt-get` can be installed via `libheif-dev` package.

Source: https://github.com/strukturag/libheif/issues/21
