### ISSUE TITLE
Unsupported CMYK icc profile

### ISSUE THREAD

**Issue by Ole-Gi** [libvips/libvips#2329]
## Bug report

**Describe the bug**
While worked with pyvips found problem with icc_transform on some JPEG CMYK images.
Got such error: `unable to call icc_transform VipsIcc: Couldn't link the profiles`
After extracting icc profile with exiftool tried to run libvips icc_transform directly with command line tool and got same problem: `icc_transform: no output profile`

Please see example of image and problem icc profile [here](https://drive.google.com/drive/folders/1R8MhClauIkEinA3H3Gtyp1hvD97d9uy_?usp=sharing)

**To Reproduce**
1. Use Image Sample-jpg-image-50kb_cmyk.jpg
2. Run command ` vips icc_transform --pcs=xyz  Sample-jpg-image-50kb_cmyk.jpg x.jpg Sample-jpg-image-50kb_cmyk.icc`
3. See error `icc_transform: no output profile`

**Expected behavior**
icc transform generates new image without error.

**Actual behavior**
icc transform fails with the error `icc_transform: no output profile`

**Environment**
 - OS: MacOS 10.15
 - Vips: vips-8.11.0-Wed Jun  9 18:20:35 UTC 2021

**Comment by jcupitt** [comment]
Hi @Ole-Gi,

You should see some warning messages. I get:

```
$ vips icc_transform --pcs=xyz Sample-jpg-image-50kb_cmyk.jpg x.jpg Sample-jpg-image-50kb_cmyk.icc

(vips:943323): VIPS-WARNING **: 16:38:09.597: input profile does not support relative intent

(vips:943323): VIPS-WARNING **: 16:38:09.600: output profile does not support relative intent
icc_transform: no output profile
```

So your profiles don't support relative intent, which is the libvips default. I enabled debugging to get some more info:

```
$ vips icc_transform Sample-jpg-image-50kb_cmyk.jpg x.v Sample-jpg-image-50kb_cmyk.icc
loading input profile, intent relative, from blob 0x556b141aefa0
icc profile loaded from blob to make: 0x556b141a84e0
description: SWOP (Coated), 20%
copyright: (c) 2001 Adobe Systems Inc.
profile class: 0x73636e72
PCS: 0x4c616220 (Lab )
matrix shaper: 0
version: 2.1
n_intents = 10
  0: Perceptual, in CLUT = 1, out CLUT = 0
  0x1: Relative colorimetric, in CLUT = 0, out CLUT = 0
  0x2: Saturation, in CLUT = 0, out CLUT = 0
  0x3: Absolute colorimetric, in CLUT = 0, out CLUT = 0
  0xa: Perceptual preserving black ink, in CLUT = 0, out CLUT = 0
  0xb: Relative colorimetric preserving black ink, in CLUT = 0, out CLUT = 0
  0xc: Saturation preserving black ink, in CLUT = 0, out CLUT = 0
  0xd: Perceptual preserving black plane, in CLUT = 0, out CLUT = 0
  0xe: Relative colorimetric preserving black plane, in CLUT = 0, out CLUT = 0
  0xf: Saturation preserving black plane, in CLUT = 0, out CLUT = 0

(vips:950669): VIPS-WARNING **: 17:09:58.972: profile does not support relative input intent
loading input profile, intent relative, from blob 0x556b141b3770
icc profile loaded from blob to make: 0x556b141b4000
description: Chemical proof
copyright: Created by Graeme W. Gill. Released into the public domain. No Warranty, Use at your own risk.
profile class: 0x70727472
PCS: 0x4c616220 (Lab )
matrix shaper: 0
version: 2.2
n_intents = 10
  0: Perceptual, in CLUT = 1, out CLUT = 1
  0x1: Relative colorimetric, in CLUT = 1, out CLUT = 1
  0x2: Saturation, in CLUT = 1, out CLUT = 1
  0x3: Absolute colorimetric, in CLUT = 1, out CLUT = 1
  0xa: Perceptual preserving black ink, in CLUT = 0, out CLUT = 1
  0xb: Relative colorimetric preserving black ink, in CLUT = 0, out CLUT = 1
  0xc: Saturation preserving black ink, in CLUT = 0, out CLUT = 0
  0xd: Perceptual preserving black plane, in CLUT = 0, out CLUT = 0
  0xe: Relative colorimetric preserving black plane, in CLUT = 0, out CLUT = 0
  0xf: Saturation preserving black plane, in CLUT = 0, out CLUT = 0
loading output profile, intent relative, from blob 0x556b141b2950
icc profile loaded from blob to make: 0x556b141b7cd0
description: SWOP (Coated), 20%
copyright: (c) 2001 Adobe Systems Inc.
profile class: 0x73636e72
PCS: 0x4c616220 (Lab )
matrix shaper: 0
version: 2.1
n_intents = 10
  0: Perceptual, in CLUT = 1, out CLUT = 0
  0x1: Relative colorimetric, in CLUT = 0, out CLUT = 0
  0x2: Saturation, in CLUT = 0, out CLUT = 0
  0x3: Absolute colorimetric, in CLUT = 0, out CLUT = 0
  0xa: Perceptual preserving black ink, in CLUT = 0, out CLUT = 0
  0xb: Relative colorimetric preserving black ink, in CLUT = 0, out CLUT = 0
  0xc: Saturation preserving black ink, in CLUT = 0, out CLUT = 0
  0xd: Perceptual preserving black plane, in CLUT = 0, out CLUT = 0
  0xe: Relative colorimetric preserving black plane, in CLUT = 0, out CLUT = 0
  0xf: Saturation preserving black plane, in CLUT = 0, out CLUT = 0

(vips:950669): VIPS-WARNING **: 17:09:58.976: profile does not support relative output intent
icc_transform: no output profile
```

So it's trying to load the embedded profile with relative intent, failing, and falling back to it's standard CMYK profile (that's the second profile in the dump, which does support relative).

Finally it tries to load your output profile. This only supports input perceptual, so it fails.

CMYK ICC profiles are usually huge lookup tables. A complete profile will often have 8 tables: CMYK -> CIELAB, CIELAB -> CMYK, then repeated four times for the four usual rendering intents. Your profile only contains one of the 8 tables. 

I think the best you can do is probably:

```
$ vips icc_transform Sample-jpg-image-50kb_cmyk.jpg x.jpg srgb --intent perceptual
```

That'll import with the embedded profile, and export with the standard srgb profile to make:

![x](https://user-images.githubusercontent.com/580843/123996648-72a3f880-d9c7-11eb-8210-f3fa97cbc067.jpg)

You can use `cmyk` instead if you need CMYK output.

**Comment by Ole-Gi** [comment]
Hi @jcupitt , thanks for fast response!
I also found this solution with fallback to general icc profile.
But do you plan to support such profile without relative intent?

**Comment by jcupitt** [comment]
You're right, it could search the set of supported intents and pick one of them. It would need to pick an intent that both profiles supported, and was closest to the specified intent. I'm not sure how useful that would be -- it sounds complicated and confusing.

Plus in this case, you'll always need to use a different output profile, since your profile is input only.

**Comment by jindili** [comment]
Hi John,

How to enable the debugging output ?

I try adding the system environment variable G_MESSAGES_DEBUG=VIPS, seems not work,
Is that need a special debugging build of vips on windows ?

**Comment by jcupitt** [comment]
You have to recompile with `-DDEBUG`, sorry. Perhaps it should be changeable at runtime.

**Comment by Ole-Gi** [comment]
@jcupitt I've applied fallback to cmyk if error appeared, thanks.
