### ISSUE TITLE
jp2k: libvips built without JPEG2000 support

### ISSUE THREAD

**Issue by petoor** [libvips/libvips#2365]
Hi John
Trying to save a jpeg 2000 image with tiffsave i get
```
pyvips.error.Error: unable to call tiffsave
jp2k: libvips built without JPEG2000 support

```
Currently i build libvips with libjpeg-turbo8-dev, which package am i missing?
Also is there a better choice than libjpeg-turbo8-dev?

**Comment by jcupitt** [comment]
Hi @petoor, you need OpenJPEG for jp2k support. I think the package is `libopenjp2-7-dev`.
