### ISSUE TITLE
Segmentation Fault in libgsf v1.14.47 when running test_format

### ISSUE THREAD

**Issue by troubas** [libvips/libvips#2371]
# Bug report
I'm not sure if this is an issues with libvips or with libgsf. It depends if libgsf can know if memory access is safe?

Can anyone confirm this bug?

**To Reproduce**
1. Use vips-8.11.2
2. Use libgsf 1.14.47
3. Build libvips
4. Run test `test_formats.sh`

**Expected behavior**
Should run without error?

**Actual behavior**
Segmentation fault on action dzsave

```
testing dzsave sample.jpg .zip ... ./test_formats.sh: line 128: 11267 Segmentation fault 
```

Which executes the following command (paths removed for brevity; assuming to be in directory test/)
```
../tools/.libs/vips dzsave test-suite/images/sample.jpg  tmp-3446/savertest.zip
```

**Environment**
 - OS: Guix
 - Vips: 8.11.2
 - libgsf: 1.14.47

**Additional context**
```
Thread 1 "vips" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b11bd0 in gsf_outfile_zip_close ()
   from /gnu/store/a7xxamcsr5dny69a6ym6b72ljxqs33xl-libgsf-1.14.47/lib/libgsf-1.so.114
```

**Comment by jcupitt** [comment]
Hi @troubas, thanks for the report.

That's odd, it's working here, and of course `test_formats.sh` is run as part of our test suite, which is executed on every commit, so it should always pass.

Can you make a reproducer, perhaps in a dockerfile?

**Comment by troubas** [comment]
Hei @jcupitt, you're welcome. It might be associated with the guix system I'm using =/

I can easily provide you with a package file for guix. Which should provide an exact copy of my build. Are you willing to install the guix package manager to test?

I don't have any experience with docker so it would probably take some time to set up a dockerfile.

**libvips.scm**
``` guile
(define-module (gnu packages libvips)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix download)
  #:use-module (guix packages)
  #:use-module (guix build-system gnu)
  #:use-module (gnu packages)
  #:use-module (gnu packages algebra)
  #:use-module (gnu packages ghostscript)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages graphics)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages image)
  #:use-module (gnu packages image-viewers)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages pdf)
  #:use-module (gnu packages photo)
  #:use-module (gnu packages python)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xml))

(define-public libvips
  (package
    (name "libvips")
    (version "8.11.2")
    (source (origin
             (method url-fetch)
             (uri
               (string-append
                 "https://github.com/libvips/libvips/releases/download/v"
                 version "/vips-" version ".tar.gz"))
             (sha256
              (base32 "01kfsfqrggxirrwbmg7apiz3d9rwabpn6v29njaawqacxrvbfnmv"))))
    (build-system gnu-build-system)
    (inputs
     `(("expat", expat)
       ("fftw", fftw)
       ("glib", glib)
       ("imagemagick", imagemagick)
       ("imv", imv)
       ("lcms", lcms)
       ("libexif", libexif)
       ("libgsf", libgsf)
       ("libheif", libheif)
       ("librsvg", librsvg)
       ("libtiff", libtiff)
       ("libwebp", libwebp)
       ("libxml2", libxml2)
       ("libpng", libpng)
       ("openexr", openexr)
       ("openjpeg", openjpeg)
       ("pango", pango)
       ("python", python)
       ("poppler", poppler)))
    (native-inputs
      `(("bc", bc)
        ("pkg-config", pkg-config)))
    (home-page "https://libvips.github.io/libvips")
    (synopsis "libvips : an image processing library")
    (description
     "libvips is a demand-driven, horizontally threaded image processing
      library.")
    (license license:gpl2+)))

libvips
```

Which can be built using `guix build -f libvips.scm`.

**Comment by jcupitt** [comment]
I use this machine for lots of differenet things, I can't risk breaking anything. I'll make you a demo dockerfile.

**Comment by jcupitt** [comment]
Ah looks like you can't run guix in docker. Guix needs nscd, that has to run in the host OS, and I don't want to do that on this machine.

It would have to be a VM I think.

**Comment by troubas** [comment]
Can confirm that the bug does not occur on archlinux with the same versions of the library. I've noticed there are different glib versions (well variants really as it is the same version but have a different hash) installed in guix for some of the packages. Might be the cause.

However it is clearly not a bug in libvips or libgsf so I suggest closing this ticket?

Thanks for your help though!

**Comment by jcupitt** [comment]
I noticed in the guix docs that you need to use nscd to avoid crashes with glibc version differences. 

https://guix.gnu.org/manual/en/html_node/Application-Setup.html#Name-Service-Switch-1

Perhaps there's a problem in your nscd setup? I'll close.

**Comment by troubas** [comment]
Thanks for the tip! However I think this doesn't apply in my case. I'm running the build on a guix distribution.
