### ISSUE TITLE
large JPEG 2000 file conversion takes a lot of memory

### ISSUE THREAD

**Issue by michaeltran262** [libvips/libvips#2382]
Hello,

I am using libvips 8.11.2 for jp2 conversion to jpg, png and tiff using `jp2kload`. When I convert large ~750 MB jp2 file, libvips uses approximately more than 6 GB of RAM. Is it possible to convert large JPEG2000 files without taking this large amounts of memory? I wish to deploy libvips into a docker container with 4 GB memory limit to convert and download image files. 

Thanks in advance.

**Comment by jcupitt** [comment]
Hi @michaeltran262,

My guess would be you're not using the libvips jp2k loader and it's fallen back to the imagemagick jp2k loader, which does use a lot of memory.

For example, with a 10,000 x 10,000 pixel jp2 image and the imagemagick loader, I see:

```
$ /usr/bin/time -f %M:%e vips copy wtc.jp2 x.jpg
1276272:11.96
```

1.2GB of memory and 15s of runtime. If I enable the native libvips jp2k loader, I see:

```
$ /usr/bin/time -f %M:%e vips copy wtc.jp2 x.jpg
147640:4.61
```

150mb and 5s of runtime.

You can see which loader it is using with `vipsheader`:

```
$ vipsheader wtc.jp2
wtc.jp2: 9372x9372 uchar, 3 bands, srgb, jp2kload
```

That's the native libvips loader. If it's using imagemagick, you'll see `magickload`.
