### ISSUE TITLE
How to process Amazon hosted images.

### ISSUE THREAD

**Issue by qudratullah1061** [libvips/libvips#2390]
Hi,

Thank you for this great library. Really helpful. I came up here with a question. What steps are necessary to do if I want to process images hosted on the amazon s3 bucket with the lipvips command line?

I am executing the command using PHP function exec();
Here is an example.

exec('vips tiffsave "' . $inputPath . '" "' . $outputPath . '" --tile --pyramid ' . $compression . ' ' . $quality . ' --tile-width ' . $tileSize . ' --tile-height ' . $tileSize, $output, $error);

The $inputPath is the path of an image hosted on the same server where I am executing this script. But what if I want to use the amazon s3 bucket image or remote image url? Please help.

Thank you soo much.

**Comment by jcupitt** [comment]
Hi @qudratullah1061,

There's an example here:

https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html#true-streaming

```
aws s3 cp s3://mybucket/input.jpg - | \
  vips thumbnail_source [descriptor=0] .jpg 128 | \
    aws s3 cp - s3://mybucket/output.jpg
```
