### ISSUE TITLE
npm Dependency for latest libvips version

### ISSUE THREAD

**Issue by Shivam-Pathak1** [libvips/libvips#2410]
I am trying to use sharp package for image processing in my npm project. The sharp version is 0.28.3. My Dockerfile is trying to install all the npm dependencies.
When I do an npm i libvips, the latest version appears to be 0.0.2. But sharp version 0.28.3 is compatible only with libvips version > 8.10.6
Can I please understand how can I install the respective dependency via npm on my Dockerfile which spins a Linux image?

**Comment by jcupitt** [comment]
Hello @Shivam-Pathak1,

Unless you have a very strange platform, sharp will automatically download the correct libvips binary during `npm install sharp`. You don't need to install anything else.
