### ISSUE TITLE
Cannot install libvips on Debian (BeagleBone)

### ISSUE THREAD

**Issue by arijitdas123student** [libvips/libvips#2423]
Hey, 
I was trying to install [libvips](https://github.com/libvips/libvips/releases/tag/v8.11.3) on my [BeagleBone AI](https://beaglebone.ai) running Debian but found an error : 
``````
debian@beaglebone:~/Downloads/libvips-8.11.3$ ./configure
-bash: ./configure: No such file or directory
``````
Can someone help me out of this please?

**Comment by jcupitt** [comment]
Hi @arijitdas123student, libvips will be in your package manager, try just:

```
sudo apt install libvips
```

**Comment by arijitdas123student** [comment]
Hi @jcupitt! Yes, I've tried doing it. I'm actually trying to install a CLI using npm but getting errors as it needs to have libvips >= 8.10.5. 
`ERR! sharp Use with glibc 2.24 requires manual installation of libvips >= 8.10.5`

**Comment by jcupitt** [comment]
Ah, OK. You've probably downloaded the wrong tarball, you need:

https://github.com/libvips/libvips/releases/download/v8.11.3/vips-8.11.3.tar.gz

ie. the tarball we made, not the one github makes for us.

You'll need to check the summary at the end of configure carefully and install any packages it needs.

**Comment by arijitdas123student** [comment]
Alrighty....thanks for sharing...I will check it out and will let you know if that works!

**Comment by kmartinez** [comment]
if there is a specific fix we can add it to https://github.com/libvips/libvips/wiki/Build-for-Ubuntu
Cheers!

**Comment by arijitdas123student** [comment]
@jcupitt @kmartinez The problem is that it's taking too much time for compilation and building libvips on my Beaglebone AI. I even added an external SD Card and added a 2 GB swap to it. Yet after 3 hours of compilation it doesn't end and gets disconnected and stops abruptly. 

I was doing this : 
````
wget https://github.com/libvips/libvips/releases/download/v8.10.5/vips-8.10.5.tar.gz
tar xf vips-8.10.5.tar.gz
cd vips-8.10.5
./configure
make -j
sudo make install
sudo ldconfig
````
And couldn't succeed after sudo make install. 🙁

**Comment by jcupitt** [comment]
I suppose the beagle is too slow for native builds, sadly. I would cross-compile from a linux host.

Though >3h is surprising -- I have an rpi4 and libvips builds in less than a minute. Is the beagle really 300x slower?

**Comment by lovell** [comment]
It looks like you're using sharp on a 32-bit ARMv7 CPU with a Debian 9 based OS. If you upgrade to Debian 10 (BeagleBoard provide AM5729 Debian 10.3 with glibc 2.28) then sharp will download prebuilt linux-armv7 libvips binaries at `npm install` time.

**Comment by arijitdas123student** [comment]
@lovell @jcupitt Solved it by upgrading to Debian 10. Thanks for the help! :)
