### ISSUE TITLE
What is the best way to tile an image with another image?

### ISSUE THREAD

**Issue by brandoncc** [libvips/libvips#2427]
If I have image1 that is 100x100 and image2 which is 750x750, what is the most efficient way to tile image2 with 7 and a half of image1 in each direction? joinarray says it accepts a grid, but it doesn't seem to accept more than one row in the grid?

This is the version I currently wrote, which has a big O that leaves something to be desired, and therefore is slow:

```ruby
require 'down'
require 'vips'

width = 750
height = 750

image1_file = Down.download 'https://placeimg.com/100/100/cat.jpg'
image1 = Vips::Image.new_from_file(image1_file.path)
image1_row = image1

while image1_row.width < width
  image1_row = image1_row.join image1, 'horizontal'
end

image2 = image1_row

while image2.height < height
  image2 = image2.join image1_row, 'vertical'
end

image2 = image2.crop 0, 0, height, width

```

Here is the result of that code:

![image](https://user-images.githubusercontent.com/543973/132741755-e40893fc-e16d-470a-a02b-d9f6cd1181c9.png)

Thanks!

**Comment by jcupitt** [comment]
Hi @brandoncc,

You need `replicate`:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-replicate

Something like:

```ruby
target_width = 100000
target_height = 100000
image = Vips::Image.new_from_file filename
huge = image.replicate image.width / target_width + 1, image.height / target_height + 1
huge = image.crop 0, 0, target_width, target_height
```

**Comment by jcupitt** [comment]
You're right, you could use `arrayjoin`, but `replicate` should be a bit faster.
