### ISSUE TITLE
Unable to convert many png after update to libvips v8.11.3

### ISSUE THREAD

**Issue by Lathanderjk** [libvips/libvips#2433]
Converting of many png pictures start crashing after update to v8.11.3 with message "vip song: too many text chunks" after downgrade to v8.11.2 everything is back to normal.

Example png:

![hp-17a-cf217a-original-laserjet-toner-cartridge-black-216027](https://user-images.githubusercontent.com/9073634/133084652-531d26a5-4536-42a9-affe-c31fce1115da.png)

**Comment by jcupitt** [comment]
Hi @Lathanderjk, thanks for the test image.

8.11.3 added a thing to detect PNG images with very large numbers of text chunks. This is a DoS attack pattern, unfortunately. 

Your image has 28 text chunks (!!!), it seems to have a text chunk for each line of each metadata type. 

I've raised the limit to 50 for 8.11.4, would you be able to test this?

**Comment by Lathanderjk** [comment]
Thank you,  
Looks enough for all we tested so far.

**Comment by jcupitt** [comment]
That's great, thank you for checking. We'll push out 8.11.4 in a day or two.

**Comment by jcupitt** [comment]
OK, it's out, I'll close. Thanks for reporting this.
