### ISSUE TITLE
No package 'yes' found magick package

### ISSUE THREAD

**Issue by dvargas135** [libvips/libvips#2448]
I used `./configure --with-magickpackage` and then checked the config log. I happened to find this error but I'm not sure how to install 'yes' package

```
configure:17749: $PKG_CONFIG --exists --print-errors "$with_magickpackage"
Package yes was not found in the pkg-config search path.
Perhaps you should add the directory containing `yes.pc'
to the PKG_CONFIG_PATH environment variable
No package 'yes' found
configure:17752: $? = 1
configure:17766: result: no
No package 'yes' found
configure:17782: WARNING: yes not found; disabling Magick support
```

**Comment by jcupitt** [comment]
Hi @dvargas135,

You need to give the name of the magick package you want to use, for example:

```
./configure --with-magickpackage=GraphicsMagick
```

By default it'll use ImageMagick, so if it wasn't detecting it, you're probably missing the development headers.
