### ISSUE TITLE
Progress percentage looping per page instead of global percentage

### ISSUE THREAD

**Issue by LionelArn2** [libvips/libvips#2450]
Hello :)

I'm having frequent issues with the values reported by the progress attached to a NetVips.Image when an image with multiple pages is being written (e.g. with using tiffsave with pyramid=true).
For example, if I have an image with height=25000 and pageHeight=5000, the percentage reported (int value) will go from 0 to 100% 5 times. This means my code has to keep track of which page is currently being exported in order to calculate a global progress percentage. This is not really ideal because it is sometimes impossible to keep track of which page is currently being exported (not sure why but I do not necessarily receive the page progress values chronologically).

Would it be possible to have the libvips algorithm calculating the export progress take the number of pages into account to report a global progress value? This would be much more robust than letting the user do it.

**Comment by jcupitt** [comment]
Hi again, 

This is a bug (or misfeature?) in the tiff saver. For example:

```
$ vips copy 3198.gif[n=-1] x.tif --vips-progress
vips temp-2: 298 x 193 pixels, 32 threads, 298 x 16 tiles, 640 lines in buffer
vips temp-2: done in 0.004s          
vips temp-8: 298 x 193 pixels, 32 threads, 298 x 16 tiles, 640 lines in buffer
vips temp-8: done in 0.00393s          
vips temp-9: 298 x 193 pixels, 32 threads, 298 x 16 tiles, 640 lines in buffer
vips temp-9: done in 0.00462s          
... etc.
```

It's looping one for each page, rather than one for the whole TIFF.

**Comment by jcupitt** [comment]
OK, should be fixed in master. Thank you for pointing out this dumb thing, @LionelArn2.

This will be in 8.12. I've credited you in the changelog, I hope that's OK.

**Comment by LionelArn2** [comment]
That's great, thanks for your responsiveness :)
