### ISSUE TITLE
Build libvips with Imagemagick

### ISSUE THREAD

**Issue by dvargas135** [libvips/libvips#2451]
I built imagemagick with the flag `--with-modules` and everything went fine but when i tried to build libvips afterwards i get the same error 
```
Package yes was not found in the pkg-config search path.
Perhaps you should add the directory containing `yes.pc'
to the PKG_CONFIG_PATH environment variable
```
I would like to use imagemagick and not graphicsmagick

I'm using `ImageMagick 7.1.0-8 Q16-HDRI x86_64 2021-09-18` and vips 8.11.4

**Comment by dvargas135** [comment]
how do i get this 'yes' package? I think i have all the dependencies. I'm on Debian 10

**Comment by lovell** [comment]
Did you mean to add this as a comment to your existing discussion about this issue at https://github.com/libvips/libvips/discussions/2449 ?

**Comment by jcupitt** [comment]
I'll close. Please use the existing discussion.
