### ISSUE TITLE
When creating a source from a file, there is no detection if its a named pipe

### ISSUE THREAD

**Issue by vibbix** [libvips/libvips#2467]
## Bug report

**Describe the bug**
If i am writing an image to a named pipe, and try to open it with vips_source_new_from_file(filename) for IPC reasons, the call fails.

**To Reproduce**
1. mkfifo /tmp/test-pipe
2. create a Vips Source with vips_source_new_from_file
3. result -1 & error

**Expected behavior**
The source should be similar to that of one created by vips_source_new_from_descriptor

**Actual behavior**
Creates the error above, resulting in:
```
vips__seek: unable to seek
unix error: Illegal seek
```

**Environment**

 - OS: macOS 11.6
 - Vips:  v8.10.6 (although newer versions create similar results from my limited tests) & v8.11.4
Specifically:
 https://github.com/kleisauke/libvips-packaging/releases/download/v8.10.6

**Comment by jcupitt** [comment]
Hi @vibbix, thanks for the report.

Yes, I see this too. I tried this test program:

```python
#!/usr/bin/python3

# try:
#   mkfifo /tmp/test-pipe
#   ./fifo.py /tmp/test-pipe x.jpg &
#   cat ~/pics/k2.jpg > /tmp/test-fifo

import sys
import pyvips

source = pyvips.Source.new_from_file(sys.argv[1])
image = pyvips.Image.new_from_source(source)

target = pyvips.Target.new_to_file(sys.argv[2])
image.write_to_target(target, ".jpg") 
```

I see:

```
$ ./fifo.py /tmp/test-pipe x.jpg &
[1] 589494
$ cat ~/pics/k2.jpg > /tmp/test-pipe
$ Traceback (most recent call last):
  File "/home/john/try/./fifo.py", line 11, in <module>
    source = pyvips.Source.new_from_file(sys.argv[1])
  File "/home/john/GIT/pyvips/pyvips/vsource.py", line 62, in new_from_file
    raise Error("can't create source from filename {0}"
pyvips.error.Error: can't create source from filename /tmp/test-pipe
  vips__seek: unable to seek
unix error: Illegal seek
```

It works if you use a file descriptor rather than a filename:

```
$ vipsthumbnail stdin < /tmp/test-pipe & 
[1] 568231
$ cat k2.jpg >/tmp/test-pipe
$ 
[1]+  Done                    vipsthumbnail stdin < /tmp/test-pipe
$ 
```

So I suppose it's assuming named files are seekable, rather than testing for the capability.

**Comment by jcupitt** [comment]
OK, fixed in master, this should all work now.

Thanks for finding this stupidity!
