### ISSUE TITLE
Cannot load library 'C:\vips-dev-8.11\bin\libgobject-2.0-0.dll': error 0x7e

### ISSUE THREAD

**Issue by prspct15** [libvips/libvips#2479]
I've been wandering around trying to find the solution to this issue, but I think I have to resort here.

> Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyvips
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyvips\__init__.py", line 19, in <module>
>     import _libvips
> ModuleNotFoundError: No module named '_libvips'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyvips\__init__.py", line 70, in <module>
>     gobject_lib = ffi.dlopen(_gobject_libname)
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cffi\api.py", line 150, in dlopen
>     lib, function_cache = _make_ffi_library(self, name, flags)
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cffi\api.py", line 832, in _make_ffi_library
>     backendlib = _load_backend_lib(backend, libname, flags)
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cffi\api.py", line 828, in _load_backend_lib
>     return backend.load_library(path, flags)
> OSError: cannot load library 'C:\vips-dev-8.11\bin\libgobject-2.0-0.dll': error 0x7e

I have referred to the solution from a similar but different issue from the past (https://github.com/libvips/pyvips/issues/44#issuecomment-390160980) but it does no wonder for me either. 

If there's any other information needed, please let me know. Thank you in advance.

**Comment by kleisauke** [comment]
Was Python installed from the Microsoft Store? If so, comment https://github.com/libvips/pyvips/issues/210#issuecomment-706220637 might be relevant here.

**Comment by prspct15** [comment]
I downloaded Python directly from https://www.python.org/ , don't think that is the workaround for this issue.

**Comment by kleisauke** [comment]
Are you sure? Since issue https://github.com/libvips/pyvips/issues/286 had a similar problem with Microsoft Store's Python, which was located in this directory:
```
C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0
```
(i.e., the same path as mentioned in this issue)

If I download Python 3.10.0 directly from https://www.python.org/ it is installed in:
```
C:\Users\<username>\AppData\Local\Programs\Python\Python310
```

Perhaps you could try to turn off the app execution aliases for Python?: https://stackoverflow.com/a/58773979

**Comment by matshou** [comment]
I have the same problem with python installation in:

```
C:\Users\<username>\AppData\Local\Programs\Python\Python310
```

I've made sure to disable app execution as can be seen here:

![ApplicationFrameHost_l56zGgQUco](https://user-images.githubusercontent.com/16436920/152624387-6b57e4c7-d836-4caf-8bec-e009ce31cab9.png)

**Comment by matshou** [comment]
I was able to resolve the issue by using `vips-dev-w64-web-8.12.2-static` artifact from the latest release.
