### ISSUE TITLE
Add support for IIIF v3

### ISSUE THREAD

**Issue by martimpassos** [libvips/libvips#2480]
Currently `--layout iiif` produces a IIIF 2.1 compliant `info.json`. Looking forward, more and more people will need to generate  [IIIF v3](https://iiif.io/api/image/3.0/) tiles (mostly just adding the height to the tile size folder naming convention) and updated `info.json`s

**Comment by martimpassos** [comment]
Its pretty much the same. I don't know any C, but let me know if a PR with commented pseudo code would be of help. It should be a matter of replicating existing code with minor tweaks (mostly renaming json fields and the tile size directories to include height as well)

**Comment by jcupitt** [comment]
If directory names are changing, we will probably need a new flag called eg. `--iiif3` to write IIIF3 pyramids or we might break old readers.

**Comment by jcupitt** [comment]
... supporting `full/` efficiently needs some changes to other parts of libvips, so it's on the back burner for now.

**Comment by martimpassos** [comment]
I'm building `add-iiif3` on a Docker image to test it and should have some feedback on Monday. Thanks for looking into this so quickly!

**Comment by martimpassos** [comment]
I'm getting 
```
./autogen.sh: 17: ./autogen.sh: autoconf: not found
./autogen.sh: 26: ./autogen.sh: aclocal: not found
```
when trying to `docker run libvips-iiif3 ./autogen.sh --prefix=/home/usr/vips`. Here's my Dockerfile:
```
FROM ubuntu:bionic

RUN apt-get update && apt-get install -y \
    git \ 
    glib-2.0-dev \
    libexpat-dev \
    gtk-doc-tools \
    gobject-introspection

RUN git clone -b add-iiif3 https://github.com/libvips/libvips.git

WORKDIR /libvips
```

**Comment by jcupitt** [comment]
You need quite a few more packages if you build from git (the release tarballs have this stuff built in).

Try (untested):

```
FROM ubuntu:21.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    git \
    autoconf \
    libtool \
    gtk-doc-tools \
    gobject-introspection

WORKDIR /usr/local/src
ENV LD_LIBRARY_PATH /usr/local/lib
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig

RUN apt-get install -y \
  glib-2.0-dev \
  libexpat-dev \
  libgsf-1-dev \
  libjpeg-dev \
  libexif-dev 

RUN git clone https://github.com/libvips/libvips \
  && cd libvips \
  && git checkout add-iiif3 \
  && ./autogen.sh \
  && make V=0 \
  && make install
```

**Comment by jcupitt** [comment]
... I fixed a few small things, it should all be working now.

**Comment by martimpassos** [comment]
thanks, I was able to build your dockerfile and do some testing, everything seems alright. Thanks again for looking into this!

**Comment by jcupitt** [comment]
(you're credited on the changelog, let me know if that's not OK)

**Comment by jrochkind** [comment]
This is amazing, thank you!
