### ISSUE TITLE
cgifsave speed

### ISSUE THREAD

**Issue by dloebl** [libvips/libvips#2531]
We are currently working on improving the LZW encoding speed of cgif further. 
However, vips seems not to benefit that much from this optimization yet. 
It looks as if most time is spent in libimagequant. Changing the dither and effort parameter improves the speed, but the contribution of cgif to the overall time is still relatively small. 
Right now I can think of avoiding this by detecting whether there are < 256 colors present in the frame(s) and choosing the palette(s) with a different method in this case.

Valgrind's callgrind tool indicates, that most instructions are spent in libimagequant:
`$ valgrind --tool=callgrind vips copy earth.gif[n=-1] out.gif`<details>
  <summary>Show output</summary>
<pre>
  Ir 6,402,284,941 (100.0%)  PROGRAM TOTALS
  Ir                      file:function
  1,499,297,819 (23.42%)  ???:liq_write_remapped_image_rows [/usr/lib/libimagequant.so.0]
    742,797,440 (11.60%)  ???:0x0000000000008980 [/usr/lib/libimagequant.so.0]
    567,076,364 ( 8.86%)  ???:0x0000000000004ec0'2 [/usr/lib/libimagequant.so.0]
    538,913,980 ( 8.42%)  ???:0x0000000000005540 [/usr/lib/libimagequant.so.0]
    480,203,152 ( 7.50%)  ???:0x0000000000004520 [/usr/lib/libimagequant.so.0]
    480,203,152 ( 7.50%)  ???:0x0000000000004630 [/usr/lib/libimagequant.so.0]
    270,890,528 ( 4.23%)  ???:0x00000000000020f0 [/usr/lib/liblqr-1.so.0.3.2]
    197,696,581 ( 3.09%)  ???:0x0000000000009030 [/usr/lib/libimagequant.so.0]
    189,694,558 ( 2.96%)  ???:cgif_addframe [/usr/lib/libcgif.so.0.0.2]
    183,040,000 ( 2.86%)  ???:0x0000000000004bf0 [/usr/lib/libimagequant.so.0]
    166,766,583 ( 2.60%)  ???:__memset_avx2_unaligned_erms [/usr/lib/libc-2.33.so]
    148,403,200 ( 2.32%)  ???:0x0000000000008430 [/usr/lib/libimagequant.so.0]
    119,989,750 ( 1.87%)  ???:0x0000000000001170 [/usr/lib/libcgif.so.0.0.2]
    106,272,452 ( 1.66%)  ???:0x0000000000004740 [/usr/lib/libimagequant.so.0]
    106,271,176 ( 1.66%)  ???:0x00000000000041c0 [/usr/lib/libimagequant.so.0]
     98,948,008 ( 1.55%)  ???:__memcpy_avx_unaligned_erms [/usr/lib/libc-2.33.so]
     94,579,196 ( 1.48%)  /home/dbl/projects/libvips/libvips/foreign/libnsgif/lzw.c:lzw_decode [/home/dbl/vips/lib/libvips.so.42.14.0]
     84,653,978 ( 1.32%)  /home/dbl/projects/libvips/libvips/foreign/cgifsave.c:vips_foreign_save_cgif_sink_disc [/home/dbl/vips/lib/libvips.so.42.14.0]
     83,085,813 ( 1.30%)  ???:0x0000000000004ec0 [/usr/lib/libimagequant.so.0]
</pre>
</details>

![earth](https://user-images.githubusercontent.com/34104349/141359120-eed01dc4-101b-43f4-b086-808e937a0283.gif)

**Comment by jcupitt** [comment]
Hi again,

That's right, by far the biggest cost is dithering down to the palette (ie. RGB -> indexed).

A simple way to improve this for a simple copy of GIF -> GIF would be to keep the image in an indexed form. So the GIF loader would make a one-band, 8-bit image with the palette attached as metadata, and the GIF saver would have a shortcut to save directly with no dithering and no palette selection. imagemagick does this.

Although this gives a great speedup, copying GIF -> GIF is probably not very common. Usually you'd want to do something like a resize, which would force you to unpack to RGB, and then force palette optimisation and redithering.

We could have an option for a fixed palette (eg. the 3:3:2 cube) and dither to that, but I don't know how much time palette selection takes.

**Comment by kleisauke** [comment]
FWIW, I also searched for alternatives to libimagequant and came across this repository: https://github.com/DarthSim/quantizr.

It current fails to link with libvips master, due to the missing `liq_set_speed` declaration.
```
/usr/bin/ld: ../libvips/.libs/libvips.so: undefined reference to `liq_set_speed'
```
(PR https://github.com/DarthSim/quantizr/pull/1 resolves this)

Having tested this with the above image, it is unfortunately slower than using the [BSD-2-Clause licensed libimagequant fork](https://github.com/lovell/libimagequant).

Quantizr:
```bash
$ time vips copy earth.gif[n=-1] x.gif

real	0m1.055s
user	0m1.074s
sys	0m0.029s
```

libimagequant v2.4.1:
```bash
$ time vips copy earth.gif[n=-1] x.gif

real	0m0.562s
user	0m0.706s
sys	0m0.073s
```

**Comment by jcupitt** [comment]
Yes, `libimagequant` has had a lot of work put into it, it would be hard to beat.

Maybe we could have a pool of worker threads and encode each frame of an animation in parallel? It sounds like a lot of work though :(

**Comment by lovell** [comment]
I think my (friendly) BSD fork of libimagequant at https://github.com/lovell/libimagequant is very slightly faster than the latest GPL upstream, thanks mainly to https://github.com/lovell/libimagequant/commit/d7d506a647ea167094c1a486fbacf8c5b7a3bf4b and https://github.com/lovell/libimagequant/commit/1f9e64d98143d6984a2358b48d126c8b302dc52f although this will probably come at the cost of quality/precision.

The `nearest_search` logic is currently the bottleneck so the use of OpenMP might help for larger images, and perhaps an AVX implementation of the `colordifference` function might be possible too.

**Comment by jcupitt** [comment]
Here's a benchmark vs. imagemagick for libvips 8.12. This is a 140 frame video clip (a very common case):

```
$ /usr/bin/time -f %M:%e vipsthumbnail 3198.gif[n=-1] --size 128 -o x.gif
46128:2.40
$ /usr/bin/time -f %M:%e convert 3198.gif -resize 128x128 x.gif
166280:5.52
```

So libvips is more than 2x faster, needs 3x less memory and, thanks to better palette selection and dithering, makes a better quality GIF.

**Comment by jcupitt** [comment]
@dloebl There's a "what's new in 8.12" news post which talks about cgif:

https://www.libvips.org/2021/11/14/What's-new-in-8.12.html

I've linked to your project, but of course we could add something more if you like. Open a PR if you'd like to expand the cgif section.

https://github.com/libvips/libvips/blob/gh-pages/_posts/2021-11-14-What's-new-in-8.12.md

**Comment by DarthSim** [comment]
Sorry if this is offtopic 😅

> Yes, libimagequant has had a lot of work put into it, I think it would be hard to beat.

Just released the new version of Quantizr, and it overperforms libimagequant (BSD-2 fork):

Quantizr
```
$ /usr/bin/time -f %M:%e vips copy /images/earth.gif[n=-1] x.gif
28204:1.21
```

libimagequant:
```
$ /usr/bin/time -f %M:%e vips copy /images/earth.gif[n=-1] x.gif
30980:1.52
```

It also generates a little bit better image:
```
$ dssim .tmp/wat-arun.png .tmp/wat-arun.quantizr3.png .tmp/wat-arun.liq1.png
0.00547782	.tmp/wat-arun.quantizr3.png
0.00548659	.tmp/wat-arun.liq1.png
```

<details>
  <summary>The results</summary>

Original:

![wat-arun](https://user-images.githubusercontent.com/380856/142874781-43d75c17-e96f-4080-a833-0243d7f24822.png)

Quantizr:

![wat-arun quantizr3](https://user-images.githubusercontent.com/380856/142874789-a378dbdb-8a81-4b4a-80e9-e1a5e548250b.png)

libimagequant:

![wat-arun liq1](https://user-images.githubusercontent.com/380856/142874773-239f4f96-74d9-4994-9e0d-6e011a474ecd.png)
</details>

**Comment by jcupitt** [comment]
That's a very nice result! 

I would be cautious interpreting DSSIM numbers --- it doesn't always measure what you are interested in. Here's a side-by-side of a detail from your two images:

![comp](https://user-images.githubusercontent.com/580843/142880109-61e56d5f-b159-4b3c-b308-df379c5876b7.png)

That's libimagequant on the right. It looks like they are using a fancier dither, or perhaps using different weighting factors to propagate errors.

**Comment by jcupitt** [comment]
This has been revised for 8.13.
