### ISSUE TITLE
Regression with VipsInsert and 8.12

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#2548]
## Bug report

**Describe the bug**
The output of VipsInsert is different (and sometimes the pasted image even missing) than in 8.11

**To Reproduce**
1. vips VipsInsert bg.png barcode.png out.png 10 10

Images used:
![bg.png](https://user-images.githubusercontent.com/47106/142759414-568aec78-a856-4da8-ad82-77b957c27991.png)
![barcode.png](https://user-images.githubusercontent.com/47106/142759420-9a721d5c-fa72-4f70-9409-1900e46d6450.png)

**Expected behavior**

The output with 8.11 (which looks correct to me)

![8 11](https://user-images.githubusercontent.com/47106/142759406-c9b4e9f9-467e-4091-8102-c3122bb30363.png)

**Actual behavior**

The output with 8.12

![8 12](https://user-images.githubusercontent.com/47106/142759445-cd591a13-c1aa-4487-94fe-ac9b43ed5892.png)

Depending on which x/y values, the output looks even more different. 

**Environment**
 - OS: Amazon Linux 2
 - Vips: 8.12

**Comment by jcupitt** [comment]
Hi @chregu,

Yes, I see this too, I agree it's a bug. I'll have a look, thanks for the report.

**Comment by jcupitt** [comment]
OK, fixed in the 8.12 branch, thanks for reporting this. Some kind of brain fart in refactoring, sorry :( I'll add a test for this case.

This is a bad bug. We'll wait another day in case any other horrors emerge, then push out 8.12.1.

**Comment by jcupitt** [comment]
Actually there was a test for this exact case, but for complicated reasons it was able to pass. Anyway, 8.12.1 a few days should include this fix.

**Comment by chregu** [comment]
Thanks a lot for the prompt sunday fix. Our tests also go through again, now.
