### ISSUE TITLE
arm64: "free(): invalid next size (fast)" with VipsCopy and paletted PNG

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#2549]
## Bug report

**Describe the bug**

Doing `vips VipsCopy foo.png bar.jpg` with a "platted" PNG leads to a memory error on ARM64 platforms, no matter which output format. It works fine on a x86 system
```
free(): invalid next size (fast)
Aborted
```

**To Reproduce**
1. Use ![Image](https://user-images.githubusercontent.com/47106/142776587-60b73970-d427-477e-b0d6-4b8463d262a3.png)
2. `vips VipsCopy foo.png bar.jpg`
3. See error

**Expected behavior**
No error

**Actual behavior**
```
free(): invalid next size (fast)
Aborted
```

**Environment**
(please complete the following information)
 - OS: Amazon Linux 2 ARM64 (tested in a docker image on Apple M1 and AWS arm64 instances)
 - Vips: 8.11 and 8.12 with libspng 0.7.0. But it happens on save, not on load (tested in a PHP script)

**Comment by kleisauke** [comment]
I was able to reproduce this crash with the libvips v8.12.0 Windows ARM64 binaries on my Raspberry Pi 4B by simply doing:
```powershell
vips.exe avg x.png
```

Doing the same with the v8.11.4 binaries, which was built against libspng 0.6.3, works without problems.

/cc @randy408 as I suspect this could be a bug in the ARM NEON intrinsics implementation of libspng 0.7.0 (which is enabled by default now).

**Comment by chregu** [comment]
I can confirm, that my lines above work with libspng 0.6.3 as expected (with vips 8.12)

**Comment by chregu** [comment]
Opened a ticket at libspng, since I could now reproduce it just with the library alone. I'll therefore close this one. Thanks for your help.
