### ISSUE TITLE
autogen error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by eustas** [libvips/libvips#2554]
## Bug report

**To Reproduce**
1. run `autogen.sh`
3. See `error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL`

**Expected behavior**
Autogen should generate configure, etc.

**Environment**
 - OS: Debian
 - Vips: master

**Comment by eustas** [comment]
Executing (incomplete?) configure reports:
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 4318: syntax error near unexpected token `1.30.0'
./configure: line 4318: `GOBJECT_INTROSPECTION_CHECK(1.30.0)'
```

**Comment by lovell** [comment]
Hi, did you see #1752 ?

**Comment by eustas** [comment]
Indeed, this seems to be the same issue. I believe it is worth adding a check to `autogen.sh`, so that users will not be confused anymore and get the problem reported in a human-readable way.

Same for missing `gtk-doc-tools` dependency.

**Comment by jcupitt** [comment]
Perhaps something like this at the top of autogen.sh?

```
if ! gtkdocize; then
        echo "*** You must have gtkdocize to be able to reconfigure"
        exit 1
fi      

# this will only detect the most basic kind of missing gio error,
# hopefully that's enough to catch this most times
if ! pkg-config gobject-introspection-1.0 --exists; then
        echo "*** You must have gobject-introspection to be able to reconfigure"
        exit 1
fi
```

Very basic, but it would catch most errors.

**Comment by eustas** [comment]
Looks good!

**Comment by jcupitt** [comment]
OK, committed to master. Thanks for the suggestion @eustas.
