### ISSUE TITLE
`vipsthumbnail --linear` produces solid black thumbnail

### ISSUE THREAD

**Issue by evazion** [libvips/libvips#2562]
`vipsthumbnail --linear` produces a solid black thumbnail for this image:

https://cdn.donmai.us/original/00/00/00002e288f5980308ffb4ba644f64d62.jpg

Steps to reproduce:

```
wget https://cdn.donmai.us/original/00/00/00002e288f5980308ffb4ba644f64d62.jpg
vipsthumbnail --linear -s 180 00002e288f5980308ffb4ba644f64d62.jpg -o thumbnail.jpg
```

Expected output:

![](https://files.catbox.moe/hnvpeb.jpg)

Actual output:

![](https://files.catbox.moe/vbxl5u.jpg)

It works when not using the `--linear` option. It also works when striping the color profile from the image first with `exiftool -ICC_Profile= 00002e288f5980308ffb4ba644f64d62.jpg` before thumbnailing it.

Tested with libvips-8.9.1 on Ubuntu 20.04.3 and libvips-8.12.1 (compiled from source) on Ubuntu 21.04.

**Comment by jcupitt** [comment]
Hi @evazion,

I think your image has a broken profile. It looks like it supports input (device RGB to PCS), but not output (PCS back to device space).

I made a small test case using your image converted to XYZ using the embedded profile, and with the same profile attached to it:

http://www.rollthepotato.net/~john/broken-profile.v

You can convert to srgb using the srgb profile like this:

```
$ vips icc_export broken-profile.v x.jpg --output-profile srgb
```

To make:

![x](https://user-images.githubusercontent.com/580843/143845564-ad68b369-8a28-4bf6-8a53-afe31e7c4023.jpg)

But try using the embedded profile:

```
$ vips icc_export broken-profile.v x.jpg
```

And you get a black image:

![x](https://user-images.githubusercontent.com/580843/143845923-744fa8a9-44d6-4ee5-b9d3-f837116ffcd6.jpg)

libvips uses `cmsIsIntentSupported( profile, intent, LCMS_USED_AS_OUTPUT )` to try to verify that a profile will work, but that's obviously not detecting this bad profile correctly. 

I think this looks like an lcms bug. I'll ask for an opinion there.

**Comment by jcupitt** [comment]
Yes, this is an lcms bug, it should be fixed in the next update.

**Comment by jcupitt** [comment]
(and thank you for finding and reporting this bad thing, @evazion)

**Comment by evazion** [comment]
Thanks. I can confirm that when using lcms from master, the problem is fixed.
