### ISSUE TITLE
Image processing issues in GUI version of vips/nip2  v.8.6.0 (Mac OSX) 

### ISSUE THREAD

**Issue by freyaSH** [libvips/libvips#2566]
Hello 

I’m a conservator student trying to learn nip2/vips and I’m having some issues with the GUI based version of NIp2/Vips (8.6.0) for OSX (Monterey). Unfortunately, I am not a programmer, so I don’t know what to do about the errors. 

So, I am trying to create a false colour infrared image and all steps go well until I get to the "falsecolour" tab. Some functions have gone missing in the K9 & K2 in the “falsecolour” tab, and in B2 & B4 in the “results” tab, which means that a false colour image can't be made. The functions in these sections become unavailable after having uploaded the VIS and IR images. 

I get the following error messages:

Error in row.
Error in row K9.object: Bad left hand side of '.'.
Error in binary ..
left = no value
right = .value
Called from "Pair_falsecolour.object" (K9.object, K2.object)

Error in row. 
Error in row K2.object: Bad left hand side of '.'.
Error in binary ..
left = no value
right = .value
Called from "Pair_falsecolour.object" (K9.object, K2.object)

Bad left hand side of '.'.
Error in binary ..
left = <function>
right = .K9
Called from "B2" (B2)

Bad left hand side of '.'.
Error in binary ..
left = <function>
right = .K2
Called from "B4" (B4)

Many thanks in advance for any help

**Comment by jcupitt** [comment]
Hi @freyaSH,

Sorry, it's very hard to work out what could have gone wrong from your description. I'll try to make a false-colour infrared later today and post a list of the steps.
