### ISSUE TITLE
Add linear color encoding for JXL save operation

### ISSUE THREAD

**Issue by f1ac** [libvips/libvips#2568]
Currently JxlColorEncodingSetToSRGB() is always used in jxlsave.c, but it seems calling JxlColorEncodingSetToLinearSRGB() would be more appropriate when input image has VIPS_FORMAT_FLOAT and/or VIPS_INTERPRETATION_scRGB. Currently exported linear images appear as if they have additional gamma of 2.2 applied to them because of this issue. 

Libjxl tests seem to follow this logic (float input means linear output when input file has no ICC profile) at https://github.com/libjxl/libjxl/blob/main/lib/jxl/roundtrip_test.cc

**Comment by f1ac** [comment]
Also it seems libjxl now has JxlEncoderSetICCProfile() method, so it can be used instead of the logic above when input files have a profile. As I can see currently ICC profiles are not handled for JXL.

**Comment by jcupitt** [comment]
Hi @f1ac,

Sure, this all sounds good. Let's tag this as an enhancement for 8.13.

**Comment by jcupitt** [comment]
OK, done! I've made a PR here:

https://github.com/libvips/libvips/pull/2815

Any testing very welcome.

It looks like libjxl now has EXIF, XMP etc. as well, so we should also add support for them, and perhaps bump the minimum supprted libjxl version.

**Comment by f1ac** [comment]
@jcupitt Are there any nightly builds for windows? I gave up trying to compile the library, so can't test this w/o binaries unfortunately.

**Comment by jcupitt** [comment]
With WSL2 it should be a one-liner to build from source now:

https://github.com/libvips/build-win64-mxe

Just:

```
./build.sh all --nightly
```

To build git master libvips for windows. It does take a while :(

**Comment by jcupitt** [comment]
Of course, having looked at this, there's no simple way to build a specific commit. I'll try to add this feature.

**Comment by f1ac** [comment]
I've managed to build vips master, then changed the branch in plugins/nightly/overrides.mk to "vips-all_GH_CONF  := libvips/libvips/branches/add-more-libjxl-metadata". The second time it was much faster, but I guess it did not pick up the new branch as resulting JXL files are identical to the ones converted with v8.12.2. I either need to clean up build folder or the overrides do no work.

**Comment by kleisauke** [comment]
If you want to test specific commits or branches, I think you also need to change `nightly_version` here:
https://github.com/libvips/build-win64-mxe/blob/4ddf96c4c152f129d320d27fcf11ade9f9f73e65/build/build.sh#L133
to:
```bash
nightly_version=$(wget -q -O- 'https://api.github.com/repos/libvips/libvips/git/refs/heads/add-more-libjxl-metadata' | sed -n 's#.*"sha": "\([^"]\{7\}\).*#\1#p' | head -1)
```
(to test the [`add-more-libjxl-metadata`](https://github.com/libvips/libvips/tree/add-more-libjxl-metadata) branch)

or just:
```bash
nightly_version="bb8d107445759cb5db2c15bd5ea3335905a2e817"
```
(to test commit https://github.com/libvips/libvips/commit/bb8d107445759cb5db2c15bd5ea3335905a2e817)

I'll try to add support for the `--commit` option tomorrow (see https://github.com/libvips/build-win64-mxe/issues/44).

**Comment by jcupitt** [comment]
I posted a sample output image in linear space here: https://github.com/libvips/libvips/pull/2815#issuecomment-1134699259

There's an ICC profile too.

**Comment by f1ac** [comment]
@jcupitt GIMP shows both jpg and jxl do not have embedded ICC, jpeg has EXIF data.
