### ISSUE TITLE
"error: template with C linkage"

### ISSUE THREAD

**Issue by DUOLabs333** [libvips/libvips#2575]
## Questions, enhancements, tips, etc.

Please use libvips discussions for other topics.

https://github.com/libvips/libvips/discussions

## Bug report
When compiling with `./configure --enable-static --without-magick --without-lcms  --without-OpenEXR --without-nifti --without-pdfium --without-rsvg --without-matio --without-libwebp --without-cfitsio --without-zlib --without-poppler --without-pangoft2 --enable-introspection=no --without-openslide` and `make -j8`, it fails with "error: template with C linkage"

**To Reproduce**
1. Use source code from 8.12.1 (though it is present in 8.7.0)
2. Configure with `./configure --enable-static --without-magick --without-lcms  --without-OpenEXR --without-nifti --without-pdfium --without-rsvg --without-matio --without-libwebp --without-cfitsio --without-zlib --without-poppler --without-pangoft2 --enable-introspection=no --without-openslide`
3. make

**Expected behavior**
The build will finish successfully

**Actual behavior**
Errors
**Screenshots**

**Environment**
(please complete the following information)
 - OS: [e.g. Ubuntu 16.04, MacOS 10.13] Arch Linux ARM
 - Vips: [e.g. 8.8, 8.9, etc] 8.12.1

**Additional context**

**Comment by DUOLabs333** [comment]
I'm not using docker, just my base system. I just took the source and compiled using the GNU ld. I'm not sure what you mean by "objects being compiled".

**Comment by jcupitt** [comment]
I was trying to run arch linux in a docker container to see if I could reproduce your problem.

It looks like the container is renamed, `archliux:base` seems to work, I'll try that.

**Comment by jcupitt** [comment]
This builds cleanly:

```
FROM archlinux:base

# build packages
RUN pacman -Sy --noconfirm \
	base-devel \
	git \
	wget 

RUN pacman -S --noconfirm \
	fftw \
	libexif \
	libgsf \
	libheif \
	libimagequant \
	libjpeg-turbo \
	libpng \
	libtiff \
	orc 

ARG VIPS_VERSION=8.12.1
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download
ENV VIPSHOME /usr/local/vips

ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig

RUN cd /usr/local/src \
	&& wget ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
	&& tar xf vips-${VIPS_VERSION}.tar.gz \
	&& cd vips-${VIPS_VERSION} \
	&& ./configure --enable-static --prefix=$VIPSHOME \
		--enable-introspection=no \
		--without-magick \
		--without-lcms \
		--without-OpenEXR \
		--without-nifti \
		--without-pdfium \
		--without-rsvg \
		--without-matio \
		--without-libwebp \
		--without-cfitsio \
		--without-zlib \
		--without-poppler \
		--without-pangoft2 \
		--without-openslide \
	&& make V=0 \
	&& make install
```

So I suppose the problem must be ARM. Maybe some bug in the linker backend, perhaps? Or maybe you are running an old version of arch?

**Comment by DUOLabs333** [comment]
I updated 2 days ago.

**Comment by DUOLabs333** [comment]
Arch Linux ARM does have libvips in its repository though.

**Comment by jcupitt** [comment]
Could you try that dockerfile? Does it work for you? If it does, it might help narrow down the problem.

**Comment by DUOLabs333** [comment]
It does not work.

**Comment by jcupitt** [comment]
You are trying on ARM I guess? Or x64?

**Comment by DUOLabs333** [comment]
ARM64. It may be an Arch thing, so I'm trying Debian.

**Comment by DUOLabs333** [comment]
It seems to work with Debian, so it's a problem with Arch (this happens a lot with other libraries).

**Comment by mildred** [comment]
Got the problem tryin to build [filestash](https://github.com/mickael-kerjean/filestash) (which uses libvips) on Docker

I'm using `FROM debian:unstable-slim`

**Comment by mildred** [comment]
It seems a problem with the build script, I don't get errors with this Dockerfile:

```Dockerfile
FROM debian:unstable-slim
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt install -y curl make gcc g++ xz-utils pkg-config python3-pip autoconf libtool unzip python-setuptools cmake git
RUN apt install -y wget tar libglib2.0-dev libpangoft2-1.0-0

ARG VIPS_VERSION=8.12.1
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download
ENV VIPSHOME /usr/local/vips

ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig

RUN cd /usr/local/src \
	&& wget ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
	&& tar xf vips-${VIPS_VERSION}.tar.gz \
	&& cd vips-${VIPS_VERSION} \
	&& ./configure --enable-static --prefix=$VIPSHOME \
		--enable-introspection=no \
		--without-magick \
		--without-lcms \
		--without-OpenEXR \
		--without-nifti \
		--without-pdfium \
		--without-rsvg \
		--without-matio \
		--without-libwebp \
		--without-cfitsio \
		--without-zlib \
		--without-poppler \
		--without-pangoft2 \
		--without-openslide \
	&& make V=0 \
	&& make install

ARG VIPS_VERSION=8.7.0
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download
ENV VIPSHOME /usr/local/vips

ENV PKG_CONFIG_PATH $VIPSHOME/lib/pkgconfig

RUN cd /usr/local/src \
	&& wget ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
	&& tar xf vips-${VIPS_VERSION}.tar.gz \
	&& cd vips-${VIPS_VERSION} \
	&& ./configure --enable-static --prefix=$VIPSHOME \
		--enable-introspection=no \
		--without-magick \
		--without-lcms \
		--without-OpenEXR \
		--without-nifti \
		--without-pdfium \
		--without-rsvg \
		--without-matio \
		--without-libwebp \
		--without-cfitsio \
		--without-zlib \
		--without-poppler \
		--without-pangoft2 \
		--without-openslide \
	&& make V=0 \
	&& make install

```

**Comment by mildred** [comment]
`#include <glib.h>` does not seem to accept well being included in an `extern "C"` in C++ builds

**Comment by mildred** [comment]
Seems fixed in latest version
