### ISSUE TITLE
Incorrect dimensions for certain animated GIFs

### ISSUE THREAD

**Issue by evazion** [libvips/libvips#2577]
Vips returns incorrect dimensions for certain animated GIFs. I think it counts the size of the largest frame, which I think is the wrong behavior.

Examples:

https://cdn.donmai.us/original/df/dd/dfdd1b6d012b188d38f91663ffcc02b3.gif (vips: 1908x2571; actual: 624x634)
https://cdn.donmai.us/original/ad/8c/ad8ca4312cfc0cd9e7ebf043bb23c6e1.gif (vips: 414x539; actual: 319x529)
https://cdn.donmai.us/original/3c/af/3caf11e7479878b2d42b3241de2023e4.gif (vips: 140x123; actual: 127x123)
https://cdn.donmai.us/original/42/a9/42a94ddf074bd633eb881b6039046638.gif (vips: 688x480; actual: 640x480)
https://cdn.donmai.us/original/51/bf/51bf255e0d0fbed3bf16a14b97778812.gif (vips: 250x301; actual: 249x301)

(For the last one, Firefox and Chrome say it's 250x301, but exiftool and other programs say it's 249x301?).

Steps to reproduce:

```bash
$ wget https://cdn.donmai.us/original/df/dd/dfdd1b6d012b188d38f91663ffcc02b3.gif
$ vipsheader dfdd1b6d012b188d38f91663ffcc02b3.gif
dfdd1b6d012b188d38f91663ffcc02b3.gif: 1908x2571 uchar, 4 bands, srgb, gifload
$ exiftool -ImageSize dfdd1b6d012b188d38f91663ffcc02b3.gif
Image Size                      : 624x634
```

Verbose output:

```
$ exiftool -verbose dfdd1b6d012b188d38f91663ffcc02b3.gif
  ExifToolVersion = 12.30
  FileName = dfdd1b6d012b188d38f91663ffcc02b3.gif
  Directory = .
  FileSize = 185450
  FileModifyDate = 1488403497
  FileAccessDate = 1639170816
  FileInodeChangeDate = 1639170816
  FilePermissions = 33152
  FileType = GIF
  FileTypeExtension = GIF
  MIMEType = image/gif
  GIFVersion = 89a
  ScreenDescriptor (SubDirectory) -->
  + [BinaryData directory, 7 bytes]
  | ImageWidth = 624
  | ImageHeight = 634
  | HasColorMap = 1
  | ColorResolutionDepth = 7
  | BitsPerPixel = 7
  | BackgroundColor = 253
  | PixelAspectRatio = 0
Graphic Control: delay=0.10
Application Extension: NETSCAPE/2.0
  + [BinaryData directory, 3 bytes]
  | AnimationIterations = 0
Image: left=0 top=0 width=624 height=634
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.00
Image: left=180 top=181 width=84 height=175
Graphic Control: delay=0.20
Image: left=178 top=180 width=85 height=153
Graphic Control: delay=0.10
Image: left=178 top=180 width=86 height=176
Graphic Control: delay=0.10
Image: left=178 top=180 width=86 height=176
Graphic Control: delay=0.10
Image: left=178 top=180 width=85 height=153
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.10
Image: left=181 top=194 width=83 height=162
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.10
Image: left=181 top=194 width=83 height=162
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.10
Image: left=181 top=194 width=83 height=162
Graphic Control: delay=0.10
Image: left=178 top=180 width=85 height=153
Graphic Control: delay=0.10
Image: left=181 top=196 width=83 height=160
Graphic Control: delay=0.10
Image: left=178 top=180 width=86 height=176
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.10
Image: left=181 top=194 width=83 height=162
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=181 top=195 width=83 height=161
Graphic Control: delay=0.10
Image: left=181 top=194 width=83 height=162
Graphic Control: delay=0.10
Image: left=183 top=194 width=80 height=139
Graphic Control: delay=0.10
Image: left=1308 top=1408 width=600 height=1163
  FrameCount = 27
  Duration = 2.7
$ identify dfdd1b6d012b188d38f91663ffcc02b3.gif 
dfdd1b6d012b188d38f91663ffcc02b3.gif[0] GIF 624x634 624x634+0+0 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[1] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[2] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[3] GIF 84x175 624x634+180+181 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[4] GIF 85x153 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[5] GIF 86x176 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[6] GIF 86x176 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[7] GIF 85x153 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[8] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[9] GIF 83x162 624x634+181+194 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[10] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[11] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[12] GIF 83x162 624x634+181+194 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[13] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.000
dfdd1b6d012b188d38f91663ffcc02b3.gif[14] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[15] GIF 83x162 624x634+181+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[16] GIF 85x153 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[17] GIF 83x160 624x634+181+196 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[18] GIF 86x176 624x634+178+180 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[19] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[20] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[21] GIF 83x162 624x634+181+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[22] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[23] GIF 83x161 624x634+181+195 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[24] GIF 83x162 624x634+181+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[25] GIF 80x139 624x634+183+194 8-bit sRGB 256c 0.000u 0:00.009
dfdd1b6d012b188d38f91663ffcc02b3.gif[26] GIF 600x1163 624x634+1308+1408 8-bit sRGB 256c 185450B 0.000u 0:00.009
```

For this gif, the first frame is 624x634, but the final frame is size 600x1163 at offset (1308, 1408). So it looks like vips is extending the canvas to fit the largest frame. I think this is against spec:

> https://www.w3.org/Graphics/GIF/spec-gif89a.txt
>
> 20. Image Descriptor.
>
> a. Description. Each image in the Data Stream is composed of an Image Descriptor, an optional Local Color Table, and the image data. **Each image must fit within the boundaries of the Logical Screen, as defined in the Logical Screen Descriptor.**

Tested with libvips-8.12.1. Earlier versions produced the correct output, so I think this was introduced with nsgif.

**Comment by jcupitt** [comment]
Hi again @evazion, this looks like a possible libnsgif issue I think -- frames are perhaps not being clipped against the logical screen size.

@tlsa can I ping you? Do you have any thoughts on this?

**Comment by tlsa** [comment]
It's one of those areas where the only thing any of the decoders agree on is that you cannot follow the spec, because of all the GIFs in the wild that are improperly encoded.  The libnsgif approach is to:

1. [Ignore the logical screen descriptor dimensions if it's a common screen resolution](http://source.netsurf-browser.org/libnsgif.git/tree/src/libnsgif.c#n1253).
2. [Increase the dimensions for any frame that requires more space](http://source.netsurf-browser.org/libnsgif.git/tree/src/libnsgif.c#n806).

Other decoders all handle it slightly differently. It's pretty rare.

@evazion Do you have any idea what software created them?

**Comment by tlsa** [comment]
> Other decoders all handle it slightly differently. It's pretty rare.

The Wuffs library has a [good write-up](https://github.com/google/wuffs/blob/main/test/data/artificial-gif/frame-out-of-bounds.gif.make-artificial.txt) here.

**Comment by tlsa** [comment]
@jcupitt I think I will change us to use "policy 4", which would make these work, and with some other changes, not break anything else I'm aware of. It might take a week or two, because I'm in the middle of a bunch of other changes.

**Comment by evazion** [comment]
Sorry, I don't know what software created these files. These are user-uploaded files uploaded to my website over the course of 15 years. For what it's worth, I have about 15,000 animated gifs and I only found 13 with out-of-bounds frames like this.

Policy 4 (the Chromium policy) sounds good to me. For my purposes, I'm just trying to match what a typical web browser does.

**Comment by tlsa** [comment]
@evazion Okay, thanks! :smile_cat:

**Comment by tlsa** [comment]
> @jcupitt I think I will change us to use "policy 4", which would make these work, and with some other changes, not break anything else I'm aware of. It might take a week or two, because I'm in the middle of a bunch of other changes.

Been super busy and not had time to do all the other changes, so I've just fixed this and pushed it upstream.

**Comment by jcupitt** [comment]
OK, merged to master, thank you everyone!
