### ISSUE TITLE
Can't open gifs larger than 16384x16384

### ISSUE THREAD

**Issue by evazion** [libvips/libvips#2578]
#2179 added a maximum size limit of 16384x16384 to GIFs. My problem is that I have legitimate GIFs larger than this:

https://cdn.donmai.us/original/c2/70/c27030227dbd595694a1a06566f44723.gif (516x18034)
https://cdn.donmai.us/original/b7/d0/b7d009e9f6c2a82d8ae1ae9517f70389.gif (500x18239)
https://cdn.donmai.us/original/9a/e2/9ae232fb56335f68bd818010e963bee1.gif (600x19099)

#2419 added an `unlimited` option for PNGs. The straightforward fix would be to add an `unlimited` option for GIFs too. But in my opinion, a better fix though would be to have a global option for removing all limits from all loaders. Or even better, allow setting a max memory limit instead of trying to indirectly limit memory usage through ad-hoc limits like this.

**Comment by jcupitt** [comment]
Hi @evazion,

Good grief, I thought 16k was absurdly large. Sure, let's make it a check against 64k instead.

**Comment by jcupitt** [comment]
Change: https://github.com/libvips/libvips/commit/1fe283cc8523373ebf0fc9ab1bec11b17c716034

Thanks for the suggestion, btw., this will be in 8.12.2.
