### ISSUE TITLE
When was "not a jpeg" error fixed?

### ISSUE THREAD

**Issue by brandoncc** [libvips/libvips#2581]
Hi John,

You mentioned a previous bug on https://github.com/libvips/ruby-vips/issues/321. I'm on 8.10.6, can you tell me if I am experiencing the bug you were referring to?

Thanks

**Comment by lovell** [comment]
Please can we track this in the original report at https://github.com/libvips/ruby-vips/issues/321

**Comment by brandoncc** [comment]
Sorry @lovell I was on a timeline and not getting a response on the other PR so it was a shot in the dark (I realize open source doesn't follow timelines). No disrespect intended, and I hope none was taken :-)

**Comment by lovell** [comment]
The phrase "on a timeline" sounds like your current employer might like to get involved in https://opencollective.com/libvips
