### ISSUE TITLE
IIIFv3 folder names generated by dzsave contain trailing comma

### ISSUE THREAD

**Issue by whalehub** [libvips/libvips#2589]
**Describe the bug**
If you use the command `vips dzsave --layout iiif3 example.png example` to convert an image to an IIIFv3 folder structure, the resulting folders on the second level will all have a trailing comma in their name, e.g. `/example/1536,1536,512,464/512,464,/0/default.jpg`. All other software in the IIIF ecosystem that I've encountered so far, such as [OpenSeadragon](https://openseadragon.github.io/) or [Dezoomify](https://github.com/lovasoa/dezoomify-rs), don't expect this trailing comma, so requests end up returning a `404 - Not Found` error.

**To Reproduce**
1. Run the command `vips dzsave --layout iiif3 example.png example` in a folder with an image named `example.png`.
2. Browse to the second level of the newly created `example` folder and check that the folder names contain a trailing comma.

**Expected behavior**
Generated folder names don't contain a trailing comma.

**Actual behavior**
Generated folder names do contain a trailing comma.

**Screenshots**
N/A

**Environment**
 - **OS:** Windows 10 & Debian 11
 - **Vips:** v8.12.1

**Additional context**
N/A

**Comment by jcupitt** [comment]
Hi @whalehub, thanks for raising this.

This is strange -- I think the trailing commas come from eg.:

https://cdn.dx.artsmia.org/barbari-map-iiif-vips/index.html

You'll see tiles have names like:

https://cdn.dx.artsmia.org/barbari-map-iiif-vips/14336,6144,1024,1024/512,/0/default.jpg

Perhaps the trailing comma here means "use default height", which I suppose matches width. That would mean we just need to remove the trailing `,` in the iiif3 branch.

**Comment by jcupitt** [comment]
(removing default values from the URI spec would be a sensible change for iiif3, since it makes it possible to always use a static tile set for a pyramid)

**Comment by whalehub** [comment]
@jcupitt I suppose another option would be to add a new flag that allows users to switch between the two variants. I've already compiled vips with #2590 for my own use case, so I don't mind either way.

**Comment by jcupitt** [comment]
I believe the trailing comma is needed for IIIF2. I'll add a note to the PR.

**Comment by martimpassos** [comment]
Hi @jcupitt, pardon my ignorance, but how hard would it be to make 8.12.2 the version used by `apt` on Ubuntu 22.04?

**Comment by jcupitt** [comment]
Hi @martimpassos, you'd need to ask the Ubuntu maintainers, but I think they usually won't update even minor versions. Someone would probably need to backport this fix to 8.12.1.

I would look into compiling your own libvips, or switching to a more recent Ubuntu. Current LTS is 24.04 and that has this fix. Maybe you could deploy in a container?

**Comment by martimpassos** [comment]
I'm working on a research project with very limited resources server-wise. I'm on 22.04 after upgrading myself. Turns out I was having trouble with glib2 because of a 20.04 conflict, but I was able to fix it. Thanks!
