### ISSUE TITLE
 about -gcflags all=-N -l

### ISSUE THREAD

**Issue by WAYLON** [libvips/libvips#2592]
When I build the executable I add this parameter: -gcflags all= -n -l

Go build github.com/h2non/bimg: invalid flag in pkg-config --cflags: -xpreprocessor

However, this is normal when I don't add this parameter. How can I solve this problem? This is what happens when you debug code in Goland

**Comment by jcupitt** [comment]
Hi @WAYLON,

You'll need to explain exactly what you're doing and how libvips is involved. I can't reproduce your problem from what you've posted.

Though (just a guess) perhaps you need: `-gcflags='all=-N -l'`? ie. you're missing some quotes.

**Comment by WAYLON** [comment]
`Go build-gcFlags ='all= -n -l' `   does not compile properly
`Go build `   will compile normally

**Comment by lovell** [comment]
Cross-posted at https://github.com/h2non/bimg/issues/390 which is probably the right place for this, so will close.
