### ISSUE TITLE
Tiffsave failed silently for a large image

### ISSUE THREAD

**Issue by joesong168** [libvips/libvips#2605]
## Bug report

**Describe the bug**
Tiffsave failed for a large image

**To Reproduce**
1. Use Image ['...'](https://temp-libvips-issue.s3.amazonaws.com/c196a06cc1a3fa147b3521219cffa623.tif)
2. vips tiffsave c196a06cc1a3fa147b3521219cffa623.tif b.ptif --tile --pyramid --compression jpeg --tile-width 512 --tile-height 512 -Q 80

**Expected behavior**
No visible error but the generated ptif is not valid

**Actual behavior**
A valid ptif file

**Screenshots**

**Environment**
(please complete the following information)
 - OS: Seems every os
 - Vips: 8.9

**Additional context**
The image is converted from a CMYK image in Adobe PS. I listed its header below but didn't find something abnormal

PS D:\> vipsheader -a c196a06cc1a3fa147b3521219cffa623.tif

(vipsheader.exe:35716): VIPS-WARNING **: 23:05:18.520: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsheader.exe:35716): VIPS-WARNING **: 23:05:18.528: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsheader.exe:35716): VIPS-WARNING **: 23:05:18.532: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsheader.exe:35716): VIPS-WARNING **: 23:05:18.534: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsheader.exe:35716): VIPS-WARNING **: 23:05:18.536: Incompatible type for "RichTIFFIPTC"; tag ignored
c196a06cc1a3fa147b3521219cffa623.tif: 134800x3815 uchar, 4 bands, srgb, tiffload
width: 134800
height: 3815
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: c196a06cc1a3fa147b3521219cffa623.tif
vips-loader: tiffload
n-pages: 1
icc-profile-data: 3144 bytes of binary data
xmp-data: 16812 bytes of binary data
photoshop-data: 3344 bytes of binary data
resolution-unit: in
orientation: 1

**Comment by jcupitt** [comment]
Hi @joesong168,

It should work, though it'll need a lot of memory. I see:

```
$ vips --version
vips-8.9.3-Sat Jan  1 16:05:07 UTC 2022
$ vipsheader x.tif
x.tif: 136000x4000 uchar, 4 bands, cmyk, tiffload
$ vips tiffsave x.tif b.ptif --tile --pyramid --compression jpeg --tile-width 512 --tile-height 512 -Q 80
$ /usr/bin/time -f %M:%e vips tiffsave x.tif b.ptif --tile --pyramid --compression jpeg --tile-width 512 --tile-height 512 -Q 80
1401660:26.50
```

So 1.5gb of memory and about 30s of processing.

What exact version of libvips are you seeing this error with? What exact platform?

**Comment by jcupitt** [comment]
... how do you know the PTIF is not valid? Perhaps your viewer program cannot handle images this wide?

If you are using linux, vipsdisp can view very large images quickly:

https://flathub.org/apps/details/org.libvips.vipsdisp

**Comment by joesong168** [comment]
Thanks a lot for your quick response!
Here is the environment and the resulting ptif image.

vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020
Windows 10
Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.20 GHz
24 GB RAM

https://temp-libvips-issue.s3.amazonaws.com/c196a06cc1a3fa147b3521219cffa623.ptif

**Comment by jcupitt** [comment]
Your image seems fine, though it's all black. Could you share the source image?

**Comment by joesong168** [comment]
https://temp-libvips-issue.s3.amazonaws.com/c196a06cc1a3fa147b3521219cffa623-cmky.tif
If vips could convert cmky tiff to pyramid tiff directly, that would be fantastic.

**Comment by jcupitt** [comment]
Your source image is CMYKA, and it's all transparent.

When it is saved with JPEG compression, the transparency is flattened out (JPEG compression can't do transparency), so it turns black.

If you remove the alpha channel, it all works fine.

**Comment by joesong168** [comment]
Great, is there any command in vips to do the CMYK to RGB transform and removal of alpha channel?

**Comment by jcupitt** [comment]
You can do it in two commands, eg.:

```
$ vips extract_band c196a06cc1a3fa147b3521219cffa623-cmky.tif t1.v 0 --n 4
$ vips colourspace t1.v x.tif[tile,pyramid,compression=jpeg,tile-width=512,tile-height=512,Q=80] srgb
```

Makes:

![x](https://user-images.githubusercontent.com/580843/147879147-6c85b4ab-a765-4690-a671-90255d6bd760.jpg)

You do it in one step with Python:

```python
import pyvips

image = pyvips.Image.new_from_file("c196a06cc1a3fa147b3521219cffa623-cmky.tif", access="sequential")
image = image[0:4].colourspace("srgb")
image.write_to_file("x.tif", tile=True, pyramid=True, Q=80, tile_width=512, tile_height=512, compression="jpeg")
```

**Comment by joesong168** [comment]
Excellent, thanks a lot!
