### ISSUE TITLE
Typo in install documentation

### ISSUE THREAD

**Issue by colt005** [libvips/libvips#2606]
## Questions, enhancements, tips, etc.

Please use libvips discussions for other topics.

https://github.com/libvips/libvips/discussions

## Bug report

**Describe the bug**
[Install documentation](https://www.libvips.org/install.html) for libvips has a typo.
glib2.0-dev needs to be libglib2.0-dev

Libvips doesn't build unless proper libraries specified.

**Screenshots**

![Image](https://user-images.githubusercontent.com/20831836/147917701-c4420e16-2723-47a3-bb09-c9b782cc02e0.png)

**Additional context**
I would like to submit a PR but I couldn't find any contribution guides.

**Comment by lovell** [comment]
Thank you for offering to submit a PR, the relevant file can be found on the `gh-pages` branch at https://github.com/libvips/libvips/blob/gh-pages/install.md
