### ISSUE TITLE
Error: unable to copy to memory vips_tracked: out of memory ___ size == 2704MB

### ISSUE THREAD

**Issue by shrutibarsanoor** [libvips/libvips#2610]
I want clear some of the area in the tiff file hence i used pyvips and vips shared module.

tiff_img = i
clear_area = i.draw_rect(0, 0, 78034, 2204, fill=True )
where i am getting out of memory ___ size == 2704MB error. I am using python2.7 and windows10 pyvips version:2.1.14

**Comment by jcupitt** [comment]
Hi @shrutibarsanoor,

You are trying to draw on a huge image, and that will force the whole image into memory. The draw operations are only there for small images, they will not work on anything large.

What are you trying to achieve?

**Comment by jcupitt** [comment]
If you want to black out part of a large image, make an area of black and insert it, eg.:

```
$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> black = pyvips.Image.black(200, 100)
>>> x = x.insert(black, 500, 500)
>>> x.write_to_file("x.jpg")
>>> 
```

That'll be fast and will use very little memory.

**Comment by shrutibarsanoor** [comment]
I missed to mention one more thing. the above mentioned code will work for most of the time. i will receive error message randomly.  I will try solution witch is provided thank you

**Comment by jcupitt** [comment]
```python
        black = py.Image.black(78030, 2204)
        ref_file_after_area_cleared = load_out_put_file.insert(black, 0, 0)
```

Should that be:

```
        ref_file_after_area_cleared = load_ref_file.insert(black, 0, 0)
```

**Comment by shrutibarsanoor** [comment]
No that's not the problem issue remains same.
   
        # load ref and op file
        load_ref_file = py.Image.new_from_file(ref_file, access="sequential" )
        load_out_put_file = py.Image.new_from_file(op_file, access="sequential")

        black = py.Image.black(78030, 2204)
        ref_file_after_area_cleared = load_ref_file.insert(black, 0, 0)
        op_file_after_area_cleared = load_out_put_file.insert(black, 0, 0)
        
       mask = (ref_file_after_area_cleared == op_file_after_area_cleared).bandbool("or")
       shrink = mask.shrink(16,16)
       shrink.write_to_file(diff_file_path.tif)

**Comment by shrutibarsanoor** [comment]
Without access = "sequential" its working fine but writing 7gb of file in temp directory in run time. any way to avoid this.

**Comment by jcupitt** [comment]
This works reliably for me:

```python
#!/usr/bin/python3

import pyvips
import sys

# load ref and op file
load_ref_file = pyvips.Image.new_from_file(sys.argv[1], access="sequential" )
load_output_file = pyvips.Image.new_from_file(sys.argv[2], access="sequential")

black = pyvips.Image.black(78030, 2204)
ref_file_after_area_cleared = load_ref_file.insert(black, 0, 0)
op_file_after_area_cleared = load_output_file.insert(black, 0, 0)

mask = (ref_file_after_area_cleared == op_file_after_area_cleared).bandand()
shrink = mask.shrink(16,16)
shrink.write_to_file(sys.argv[3])
```

What kind of TIFF images are you processing? What do you see if you run `tiffinfo` on them?

**Comment by shrutibarsanoor** [comment]
size = 109.3MB = 104400/63000 pixels 
Resolution = 2540.0 ppi

**Comment by jcupitt** [comment]
Try running `tiffinfo` so I can see what kind of TIFF file you are processing. Eg.:

```
$ tiffinfo ~/pics/k2.tif
TIFF Directory at offset 0x8908816 (87f010)
  Image Width: 1450 Image Length: 2048
  Resolution: 72.009, 72.009 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 128
  Planar Configuration: single image plane
```

**Comment by shrutibarsanoor** [comment]
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 100000 Image Length: 62000
  Resolution: 2540, 2540 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 336
  Planar Configuration: single image plane
  DocumentName: G:\Esko\bg_data_colorpilot_v220\screens\Addruling_testing.TIF
  ImageDescription: G:\Esko\bg_data_colorpilot_v220\screens\Addruling_testing.TIF
  Make: Esko
  Software: Esko TIFFOut V2.0
  Group 4 Options: (0 = 0x0)

**Comment by jcupitt** [comment]
I made a similar image and ran the program 10 times, it all seems OK for me.

What libvips version are you using? I'll try with 8.2.12 (current stable).

**Comment by shrutibarsanoor** [comment]
I am using 8.12.0

**Comment by jcupitt** [comment]
8.12.0 had a bug in insert, could you try updating to 8.12.1?

**Comment by flaggp** [comment]
@jcupitt how can i convert a jpg image to png image of size 920pixels using libvips command

**Comment by jcupitt** [comment]
@flaggp please open a discussion for a new question.
