### ISSUE TITLE
processing images from .dat files

### ISSUE THREAD

**Issue by pishty1** [libvips/libvips#2614]
Hello, i normally use libvips to process images from medical slides scanner (normally Hamamatsu) to dzi, however, i have new images from 3DHistech scanners and they produce the images as .dat files with a Slidedat.ini file. Is there away i can convert the .dat file to a dzi so i can view them on openseadragon ?
The content of the Slidedat.ini file is below:
[GENERAL]
SLIDE_VERSION = 01.03
SLIDE_NAME = 2021.1
PROJECT_NAME = Pannoramic Slide Scanner
SLIDE_ID = 3CED04DF52594E52A428B6A2FF0EE99C
IMAGENUMBER_X = 936
IMAGENUMBER_Y = 2656
SLIDE_CREATION_FINISHED = True
CURRENT_SLIDE_VERSION = 2.2
IMAGE_OVERLAP_MICROMETERS_X = 0
IMAGE_OVERLAP_MICROMETERS_Y = 0
SLIDE_POSITION_X = 2500
SLIDE_POSITION_Y = 22780
SLIDE_CONTENT = DIGITAL_SLIDE
SLIDE_CREATIONDATETIME = 17/06/2021 12:41:35
VIMSLIDE_CAMERA_REAL_BITDEPTH = 24
CONFOCAL = NO
DISK_POSITION = 0
FOCUS_MAP = AUTO
FOCUS_LIMIT = ENABLED
FOCUS_LIMIT_LO = 2190
FOCUS_LIMIT_UP = 2290
FLAT_FIELD_CORRECTION = DISABLED
EXTENDED_FOCUS_ALGORITHM = FL Image
VIMSLIDE_SLIDE_BITDEPTH = 8
CAMERA_TYPE = Point Grey GS3-U3-51S5M-C
ADAPTER_SIZE = 1
OPTOVAR_SIZE = 1
OBJECTIVE_MAGNIFICATION = 40
OBJECTIVE_NAME = Plan-Apochromat
SLIDE_TYPE = SLIDE_TYPE_BRIGHTFIELD
CameraImageDivisionsPerSide = 8
[HIERARCHICAL]
INDEXFILE = Index.dat
PAGEELEMENTCOUNT = 128
PAGELENGTH = 2048
HIER_COUNT = 4
NONHIER_COUNT = 4
HIER_0_NAME = Slide zoom level
HIER_0_COUNT = 9
HIER_0_DEFAULT = 0
HIER_0_SECTION = LAYER_0_SECTION
HIER_0_VAL_0 = ZoomLevel_0
HIER_0_VAL_0_SECTION = LAYER_0_LEVEL_0_SECTION
HIER_0_VAL_1 = ZoomLevel_1
HIER_0_VAL_1_SECTION = LAYER_0_LEVEL_1_SECTION
HIER_0_VAL_2 = ZoomLevel_2
HIER_0_VAL_2_SECTION = LAYER_0_LEVEL_2_SECTION
HIER_0_VAL_3 = ZoomLevel_3
HIER_0_VAL_3_SECTION = LAYER_0_LEVEL_3_SECTION
HIER_0_VAL_4 = ZoomLevel_4
HIER_0_VAL_4_SECTION = LAYER_0_LEVEL_4_SECTION
HIER_0_VAL_5 = ZoomLevel_5
HIER_0_VAL_5_SECTION = LAYER_0_LEVEL_5_SECTION
HIER_0_VAL_6 = ZoomLevel_6
HIER_0_VAL_6_SECTION = LAYER_0_LEVEL_6_SECTION
HIER_0_VAL_7 = ZoomLevel_7
HIER_0_VAL_7_SECTION = LAYER_0_LEVEL_7_SECTION
HIER_0_VAL_8 = ZoomLevel_8
HIER_0_VAL_8_SECTION = LAYER_0_LEVEL_8_SECTION
HIER_1_NAME = Slide filter level
HIER_1_COUNT = 3
HIER_1_DEFAULT = 0
HIER_1_SECTION = LAYER_1_SECTION
HIER_1_VAL_0 = FilterLevel_0
HIER_1_VAL_0_SECTION = LAYER_1_LEVEL_0_SECTION
HIER_1_VAL_1 = FilterLevel_1
HIER_1_VAL_1_SECTION = LAYER_1_LEVEL_1_SECTION
HIER_1_VAL_2 = FilterLevel_2
HIER_1_VAL_2_SECTION = LAYER_1_LEVEL_2_SECTION
HIER_2_NAME = Microscope focus level
HIER_2_COUNT = 1
HIER_2_DEFAULT = 0
HIER_2_SECTION = LAYER_2_SECTION
HIER_2_VAL_0 = ExtFocusLevel
HIER_2_VAL_0_SECTION = LAYER_2_LEVEL_0_SECTION
HIER_3_NAME = Scan info layer
HIER_3_COUNT = 2
HIER_3_DEFAULT = 0
HIER_3_SECTION = LAYER_3_SECTION
HIER_3_VAL_0 = ScanInfoLayer_DefaultLevel
HIER_3_VAL_0_SECTION = LAYER_3_LEVEL_0_SECTION
HIER_3_VAL_1 = ScanInfoLayer_XMLInfoLevel
HIER_3_VAL_1_SECTION = LAYER_3_LEVEL_1_SECTION
NONHIER_0_NAME = Scan data layer
NONHIER_0_COUNT = 10
NONHIER_0_SECTION = NONHIERLAYER_0_SECTION
NONHIER_0_VAL_0 = ScanDataLayer_ScanMap
NONHIER_0_VAL_0_SECTION = NONHIERLAYER_0_LEVEL_0_SECTION
NONHIER_0_VAL_0_IMAGENUMBER_X = 1
NONHIER_0_VAL_0_IMAGENUMBER_Y = 1
NONHIER_0_VAL_1 = ScanDataLayer_XMLInfoHeader
NONHIER_0_VAL_1_SECTION = NONHIERLAYER_0_LEVEL_1_SECTION
NONHIER_0_VAL_1_IMAGENUMBER_X = 1
NONHIER_0_VAL_1_IMAGENUMBER_Y = 1
NONHIER_0_VAL_2 = ScanDataLayer_SlideThumbnail
NONHIER_0_VAL_2_SECTION = NONHIERLAYER_0_LEVEL_2_SECTION
NONHIER_0_VAL_2_IMAGENUMBER_X = 1
NONHIER_0_VAL_2_IMAGENUMBER_Y = 1
NONHIER_0_VAL_3 = ScanDataLayer_SlideBarcode
NONHIER_0_VAL_3_SECTION = NONHIERLAYER_0_LEVEL_3_SECTION
NONHIER_0_VAL_3_IMAGENUMBER_X = 1
NONHIER_0_VAL_3_IMAGENUMBER_Y = 1
NONHIER_0_VAL_4 = ScanDataLayer_SlidePreview
NONHIER_0_VAL_4_SECTION = NONHIERLAYER_0_LEVEL_4_SECTION
NONHIER_0_VAL_4_IMAGENUMBER_X = 1
NONHIER_0_VAL_4_IMAGENUMBER_Y = 1
NONHIER_0_VAL_5 = ScanDataLayer_StagePositionMap
NONHIER_0_VAL_5_SECTION = NONHIERLAYER_0_LEVEL_5_SECTION
NONHIER_0_VAL_5_IMAGENUMBER_X = 1
NONHIER_0_VAL_5_IMAGENUMBER_Y = 1
NONHIER_0_VAL_6 = ScanDataLayer_Empty
NONHIER_0_VAL_6_SECTION = NONHIERLAYER_0_LEVEL_6_SECTION
NONHIER_0_VAL_6_IMAGENUMBER_X = 1
NONHIER_0_VAL_6_IMAGENUMBER_Y = 1
NONHIER_0_VAL_7 = ProfileXMLHeader
NONHIER_0_VAL_7_SECTION = NONHIERLAYER_0_LEVEL_7_SECTION
NONHIER_0_VAL_7_IMAGENUMBER_X = 1
NONHIER_0_VAL_7_IMAGENUMBER_Y = 1
NONHIER_0_VAL_8 = ProfileXML
NONHIER_0_VAL_8_SECTION = NONHIERLAYER_0_LEVEL_8_SECTION
NONHIER_0_VAL_8_IMAGENUMBER_X = 1
NONHIER_0_VAL_8_IMAGENUMBER_Y = 1
NONHIER_0_VAL_9 = ScannedFOVsMap
NONHIER_0_VAL_9_SECTION = NONHIERLAYER_0_LEVEL_9_SECTION
NONHIER_0_VAL_9_IMAGENUMBER_X = 1
NONHIER_0_VAL_9_IMAGENUMBER_Y = 1
NONHIER_1_NAME = StitchingLayer
NONHIER_1_COUNT = 1
NONHIER_1_SECTION = NONHIERLAYER_1_SECTION
NONHIER_1_VAL_0 = DataLevel_V1.0
NONHIER_1_VAL_0_SECTION = NONHIERLAYER_1_LEVEL_0_SECTION
NONHIER_1_VAL_0_IMAGENUMBER_X = 1
NONHIER_1_VAL_0_IMAGENUMBER_Y = 1
NONHIER_2_NAME = StitchingIntensityLayer
NONHIER_2_COUNT = 1
NONHIER_2_SECTION = NONHIERLAYER_2_SECTION
NONHIER_2_VAL_0 = StitchingIntensityLevel
NONHIER_2_VAL_0_SECTION = NONHIERLAYER_2_LEVEL_0_SECTION
NONHIER_2_VAL_0_IMAGENUMBER_X = 2
NONHIER_2_VAL_0_IMAGENUMBER_Y = 1
NONHIER_3_NAME = VIMSLIDE_HISTOGRAM_DATA
NONHIER_3_COUNT = 1
NONHIER_3_SECTION = NONHIERLAYER_3_SECTION
NONHIER_3_VAL_0 = default
NONHIER_3_VAL_0_SECTION = NONHIERLAYER_3_LEVEL_0_SECTION
NONHIER_3_VAL_0_IMAGENUMBER_X = 1
NONHIER_3_VAL_0_IMAGENUMBER_Y = 1
[DATAFILE]
FILE_COUNT = 22
FILE_0 = Data0000.dat
FILE_1 = Data0001.dat
FILE_2 = Data0002.dat
FILE_3 = Data0003.dat
FILE_4 = Data0004.dat
FILE_5 = Data0005.dat
FILE_6 = Data0006.dat
FILE_7 = Data0007.dat
FILE_8 = Data0008.dat
FILE_9 = Data0009.dat
FILE_10 = Data0010.dat
FILE_11 = Data0011.dat
FILE_12 = Data0012.dat
FILE_13 = Data0013.dat
FILE_14 = Data0014.dat
FILE_15 = Data0015.dat
FILE_16 = Data0016.dat
FILE_17 = Data0017.dat
FILE_18 = Data0018.dat
FILE_19 = Data0019.dat
FILE_20 = Data0020.dat
FILE_21 = Data0021.dat
[LAYER_0_LEVEL_0_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 8.67706237424547E-02
MICROMETER_PER_PIXEL_Y = 8.67706237424547E-02
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 218.31884057971
OVERLAP_Y = 218.31884057971
IMAGE_CONCAT_FACTOR = 0
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_1_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 0.173541247484909
MICROMETER_PER_PIXEL_Y = 0.173541247484909
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 109.159420289855
OVERLAP_Y = 109.159420289855
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_2_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 0.346931589537223
MICROMETER_PER_PIXEL_Y = 0.346899819972466
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 54.5797101449276
OVERLAP_Y = 54.5797101449276
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_3_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 0.693863179074447
MICROMETER_PER_PIXEL_Y = 0.693799639944933
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 27.2898550724638
OVERLAP_Y = 27.2898550724638
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_4_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 1.38714376941751
MICROMETER_PER_PIXEL_Y = 1.38689917934502
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 13.6449275362319
OVERLAP_Y = 13.6449275362319
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_5_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 2.77312965588893
MICROMETER_PER_PIXEL_Y = 2.77240868015362
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 6.82246376811595
OVERLAP_Y = 6.82246376811595
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_6_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 5.54625931177787
MICROMETER_PER_PIXEL_Y = 5.54481736030723
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 3.41123188405797
OVERLAP_Y = 3.41123188405797
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_7_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 11.0879082666881
MICROMETER_PER_PIXEL_Y = 11.0841064879521
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 1.70561594202899
OVERLAP_Y = 1.70561594202899
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_0_LEVEL_8_SECTION]
IMAGE_FILL_COLOR_BGR = 16777215
MICROMETER_PER_PIXEL_X = 22.1666073072411
MICROMETER_PER_PIXEL_Y = 22.1571730292031
DIGITIZER_WIDTH = 301
DIGITIZER_HEIGHT = 251
OVERLAP_X = 0.852807971014494
OVERLAP_Y = 0.852807971014494
IMAGE_CONCAT_FACTOR = 1
IMAGE_FORMAT = JPEG
IMAGE_COMPRESSION_FACTOR = 80
[LAYER_1_LEVEL_0_SECTION]
ZSTACK_STEP_COUNT = 0
ZSTACK_FIRST_LEVEL = 0
FILTER_NAME = 
ZDIFF = -1
XDIFF = 0
YDIFF = 0
COLOR_R = 0
COLOR_G = 0
COLOR_B = 0
USE_RED_CHANNEL = False
USE_GREEN_CHANNEL = False
USE_BLUE_CHANNEL = False
FILTER_REAL_POSITION = 0
IS_MASTER_FILTER = True
STORING_CHANNEL_NUMBER = 0
IS_STITCHING_FILTER = True
ACTIVE = ON
MODIFY = ON
THRESHOLD = 0
DATA_IN_THIS_FILTER_LEVEL = FilterLevel_0
EXPOSUREPERCENTAGE = 0
DIGITALGAIN = 0
EXTENDED_STEP_SIZE = 0
EXTENDED_STEP_COUNT = 1
VIMSLIDE_HISTOGRAM_DATA_CHANNEL_SIZE = 256
EXCITATION_WAVELENGTH = 0
EXCITATION_BANDWIDTH = 0
EMISSION_WAVELENGTH = 0
EMISSION_BANDWIDTH = 0
[LAYER_1_LEVEL_1_SECTION]
ZSTACK_STEP_COUNT = 0
ZSTACK_FIRST_LEVEL = 0
FILTER_NAME = 
ZDIFF = -1
XDIFF = 0
YDIFF = 0
COLOR_R = 0
COLOR_G = 0
COLOR_B = 0
USE_RED_CHANNEL = False
USE_GREEN_CHANNEL = False
USE_BLUE_CHANNEL = False
FILTER_REAL_POSITION = 0
IS_MASTER_FILTER = False
STORING_CHANNEL_NUMBER = 1
IS_STITCHING_FILTER = False
ACTIVE = ON
MODIFY = ON
THRESHOLD = 0
DATA_IN_THIS_FILTER_LEVEL = FilterLevel_0
EXPOSUREPERCENTAGE = 0
DIGITALGAIN = 0
EXTENDED_STEP_SIZE = 0
EXTENDED_STEP_COUNT = 1
VIMSLIDE_HISTOGRAM_DATA_CHANNEL_SIZE = 256
EXCITATION_WAVELENGTH = 0
EXCITATION_BANDWIDTH = 0
EMISSION_WAVELENGTH = 0
EMISSION_BANDWIDTH = 0
[LAYER_1_LEVEL_2_SECTION]
ZSTACK_STEP_COUNT = 0
ZSTACK_FIRST_LEVEL = 0
FILTER_NAME = 
ZDIFF = -1
XDIFF = 0
YDIFF = 0
COLOR_R = 0
COLOR_G = 0
COLOR_B = 0
USE_RED_CHANNEL = False
USE_GREEN_CHANNEL = False
USE_BLUE_CHANNEL = False
FILTER_REAL_POSITION = 0
IS_MASTER_FILTER = False
STORING_CHANNEL_NUMBER = 2
IS_STITCHING_FILTER = False
ACTIVE = ON
MODIFY = ON
THRESHOLD = 0
DATA_IN_THIS_FILTER_LEVEL = FilterLevel_0
EXPOSUREPERCENTAGE = 0
DIGITALGAIN = 0
EXTENDED_STEP_SIZE = 0
EXTENDED_STEP_COUNT = 1
VIMSLIDE_HISTOGRAM_DATA_CHANNEL_SIZE = 256
EXCITATION_WAVELENGTH = 0
EXCITATION_BANDWIDTH = 0
EMISSION_WAVELENGTH = 0
EMISSION_BANDWIDTH = 0
[LAYER_2_SECTION]
EXTENDED_FOCUS_LEVEL = -1
ZERO_FOCUS_LEVEL = 0
LAST_Z_STACKED_ZOOM_LEVEL = 9
[LAYER_2_LEVEL_0_SECTION]
OFFSET_IN_MICROMETERS = 0
[LAYER_0_SECTION]
SHARPENED = 16
[NONHIERLAYER_0_LEVEL_0_SECTION]
SCANMAP_IMAGE_TYPE = PNG
SCANMAP_IMAGE_WIDTH = 117
SCANMAP_IMAGE_HEIGHT = 332
[NONHIERLAYER_0_LEVEL_5_SECTION]
STAGEPOSMAP_IMAGE_TYPE = PNG
STAGEPOSMAP_IMAGE_WIDTH = 117
STAGEPOSMAP_IMAGE_HEIGHT = 332
[NONHIERLAYER_0_LEVEL_2_SECTION]
THUMBNAIL_IMAGE_TYPE = JPEG
THUMBNAIL_IMAGE_WIDTH = 1480
THUMBNAIL_IMAGE_HEIGHT = 3388
[NONHIERLAYER_0_LEVEL_3_SECTION]
BARCODE_IMAGE_TYPE = JPEG
BARCODE_IMAGE_WIDTH = 1701
BARCODE_IMAGE_HEIGHT = 1341
BARCODE_IMAGE_FLIP = False
[NONHIERLAYER_0_SECTION]
SCANNER_HARDWARE_VERSION = Pannoramic DESK
SCANNER_SOFTWARE_VERSION = 2.0.5.93613
SCANNER_CAMERA_TYPE = Point Grey GS3-U3-51S5M-C
SCANNER_HARDWARE_ID = PDESK-027910
OBJECT_GUIDE_HYSTERESIS_X = 104
OBJECT_GUIDE_HYSTERESIS_Y = 104
AVEGARE_IMAGE_OVERLAP_X_IN_PIXELS = 218.31884057971
AVEGARE_IMAGE_OVERLAP_Y_IN_PIXELS = 218.31884057971
CAMERA_ROTATION = 8.39293044902263E-02
IccProfileColorScheme = 0
IccProfileWhitePoint = 0
IccProfileGamma = 0
SCANNING_TIME_IN_SEC = 1560
SCANNED_FOV_COUNT = 8221
[NONHIERLAYER_1_SECTION]
DATA_FORMAT_VERSION = 258
[NONHIERLAYER_2_LEVEL_0_SECTION]
COMPRESSSED_STITCHING_VERSION = 1
COMPRESSSED_STITCHING_TABLE_WIDTH = 117
COMPRESSSED_STITCHING_TABLE_HEIGHT = 332
COMPRESSSED_STITCHING_ORIG_CAMERA_TILE_WIDTH = 2408
COMPRESSSED_STITCHING_ORIG_CAMERA_TILE_HEIGHT = 2008
COMPRESSED_STITCHING_ORIG_CAMERA_TILE_OVERLAP_X = 208
COMPRESSED_STITCHING_ORIG_CAMERA_TILE_OVERLAP_Y = 208
COMPRESSED_STITCHING_ORIG_SLIDE_SCANNED_AREA_IN_PIXELS__LEFT = 2716
COMPRESSED_STITCHING_ORIG_SLIDE_SCANNED_AREA_IN_PIXELS__TOP = 229473
COMPRESSED_STITCHING_ORIG_SLIDE_SCANNED_AREA_IN_PIXELS__RIGHT = 238899
COMPRESSED_STITCHING_ORIG_SLIDE_SCANNED_AREA_IN_PIXELS__BOTTOM = 381473
[NONHIERLAYER_3_SECTION]
VIMSLIDE_HISTOGRAM_DATA_CHANNEL_NUM = 3
VIMSLIDE_HISTOGRAM_DATA_FORMAT_VERSION = 257
VIMSLIDE_HISTOGRAM_DATA_CHANNEL_SIZE = 256
[NONHIERLAYER_0_LEVEL_4_SECTION]
PREVIEW_IMAGE_TYPE = JPEG
PREVIEW_IMAGE_WIDTH = 501
PREVIEW_IMAGE_HEIGHT = 1161

Many thanks for your help, awesome library.

**Comment by jcupitt** [comment]
Hi @pishty1,

Sorry, openslide dos not support 3dhistech. You'll need to download the appalling 3dhistech software from their website and use that.

**Comment by pishty1** [comment]
Thank you for the prompt response @jcupitt.
I remember i was able to process their mrxs files to dzi before but it seems like they've changed the formats.
