### ISSUE TITLE
VipsForeignLoad: "/tmp/ActiveStorage-28657-20220112-4-8e2faa.jpg" is not a known file format

### ISSUE THREAD

**Issue by dorianmariefr** [libvips/libvips#2620]
## Bug report

**Describe the bug**

Somehow when trying to process an image I got this error:

```
VipsForeignLoad: "/tmp/ActiveStorage-28657-20220112-4-8e2faa.jpg" is not a known file format
```

**To Reproduce**

1. user uploads an image
2. I transform it using rails's active storage `attachment.file.variant(**options).processed`
2. See error

**Expected behavior**

Either says the file is not found somehow (maybe because of a server/dyno restart?) (I'm on Heroku), or maybe a missing package? not sure

Or actually process the file and return a new processed file

**Actual behavior**

Errors out

**Environment**

 - OS: (`uname -a`) `Linux c5450f47-0d17-4a40-8f95-2c64a40e8e2c 4.4.0-1097-aws #102-Ubuntu SMP Fri Sep 10 22:18:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Vips: I can't seem to find it, it's on Heroku, I used an Aptfile to install `libvips`, probably the latest on the latest stable version of ubuntu

**Additional context**

I'm on a rails app, users can upload images, I process them (size, remove filenames, remove metadata, optimize, etc.)

**Comment by jcupitt** [comment]
Hi @dorianmariefr,

Sorry, I'm not sure I can say what's wrong without a lot more information. Could the file have been deleted half-way through processing? That might cause an error like this.

Rails doesn't use libvips or ruby-vips directly, instead it's via the image_processing gem. Maybe ask there?

**Comment by jcupitt** [comment]
Or possibly your libvips has been built without jpeg support. But that seems unlikely.

**Comment by dorianmariefr** [comment]
ok thanks I will ask on image_processing repo
