### ISSUE TITLE
Does libvips provide a way to access the ICC Profile Data of an image?

### ISSUE THREAD

**Issue by AttilaTheFun** [libvips/libvips#2624]
I'm aware of the APIs for transforming the ICC Profile of an image. and detecting the presence of one, but I'm not sure if there is currently a way to access the actual embedded ICC Profile data for an image. I'm using libvips currently (via github.com/davidbyttow/govips), but I'm forced to pull in another dependency (github.com/mandykoh/prism) just to sniff out whether the image has a wide color image profile (e.g. Display P3). I'd love to just be able to do this all through vips if possible.

**Comment by jcupitt** [comment]
Hi @AttilaTheFun,

Yes, you can just get the metadata item `icc-profile-data`. The API is here:

https://www.libvips.org/API/current/libvips-header.html

eg. in Python, it's:

```python
profile = image.get("icc-profile-data")
```

**Comment by AttilaTheFun** [comment]
Ah interesting! I'll have to see if they provide a way to get these metadata values by name. If not, I could probably help them add APIs to do so.

**Comment by AttilaTheFun** [comment]
@jcupitt what is the GType of the value returned from vips_image_get with the key VIPS_META_ICC_NAME ("icc-profile-data")? Is it just binary data? Or is it structured in some way?

**Comment by jcupitt** [comment]
It's a `VipsBlob`, so simple binary data. You need to parse it with a library that can read ICC profiles to get information about it. libvips already links lcms2, so that would be a good choice.

libvips does this on load, for example:

https://github.com/libvips/libvips/blob/master/libvips/colour/icc_transform.c#L630-L687

**Comment by AttilaTheFun** [comment]
Awesome, thanks for the context @jcupitt. 
What would you think about exposing the `vips_icc_get_profile_image` API in `color.h`?
I could just copy it into another library, but I think it would be a nice util to have, especially given that `vips_profile_load` is already exposed. 
Maybe it could be renamed to `int vips_get_icc_profile(VipsImage *in, VipsBlob **profile)` while we're at it.

**Comment by jcupitt** [comment]
I don't think that's a good idea. libvips has a general metadata get/set system which language bindings are supposed to use. If they implement that, then all you need is:

```python
profile = image.get("icc-profile-data")
```

and there's no need for extra API.

**Comment by AttilaTheFun** [comment]
Yeah, you're right, I should just get the VipsBlob and do my own processing on that. I'll close this ticket because there's a way to access the ICC Profile Data as a VipsBlob.
