### ISSUE TITLE
Inaccurate colours when source image uses Adobe RGB

### ISSUE THREAD

**Issue by aopal** [libvips/libvips#2629]
## Bug report

**Describe the bug**
Running vips operations on images that have an embedded Adobe RGB colour profile results in inaccurate colours in images output by vips.

**To Reproduce**

1. Run `vips copy foo_original.jpg foo_out.jpg` using one of sample images listed below
2. Visually compare original image to vips' output

**Expected behavior**
Colours should be visually identical since no transformations have been applied, just a `vips copy`.

**Actual behavior**
Some colours are visibly different.

**Screenshots**

Example 1:

The colour of the woman's dress is significantly more muted than the original

| Original | vips output |
|------|------|
|    ![dress_orig](https://user-images.githubusercontent.com/13202534/150575959-97714c63-b77d-4dbe-9dc5-6976df454252.jpg)      |  ![dress_vips](https://user-images.githubusercontent.com/13202534/150575969-3be4575d-a302-4197-a536-6fc42b12a882.jpg)   |

Zoomed in comparison:
<img width="1331" alt="Screen Shot 2022-01-21 at 1 06 55 PM" src="https://user-images.githubusercontent.com/13202534/150578040-1805567a-4442-4900-b9fb-30bef947b3e8.png">

Example 2:

The colour of the large red and blue square is similarly muted

| Original | vips output |
|------|------|
|    ![panel_orig](https://user-images.githubusercontent.com/13202534/150576282-2241d9b3-7c54-482c-a106-d5134c5cb4aa.jpg)     |  ![panel_vips](https://user-images.githubusercontent.com/13202534/150576293-b7757cc0-58d5-4099-a35e-27d9e264362f.jpg)   |

Zoomed in comparison:
<img width="1543" alt="Screen Shot 2022-01-21 at 1 06 03 PM" src="https://user-images.githubusercontent.com/13202534/150578084-4ca6992f-8d04-4172-a41d-04e61330e759.png">

**Environment**
 - OS: Ubuntu 20.04 running in docker
 - Vips: 8.12.1
 - libjpeg-turbo: 2.0.3-0ubuntu1.20.04.1
 - littleCMS: 2.12

**Additional context**
The only two images that exhibit this issue I've been able to find are the above examples, so I'm not 100% certain the issue is unique to Adobe RGB. I've tested several other Adobe RGB images as well as several images using other high-gamut profiles (display P3, ProPhoto), none of which have exhibited the same issue.

**Comment by jcupitt** [comment]
Hi @aopal,

That's a weird one. I think it's just the jpeg save quality. Try this:

```
vips copy red-dress.jpg x.jpg[subsample-mode=off]
```

You should find it looks identical. 

I think what's happening is that for Q < 90 libvips saves with chroma subsample enabled. The red dress has spots which are just the right spacing to make chroma subsample go a bit crazy. I suppose the original photographer must have noticed this and made sure to save as 4:4:4.

**Comment by aopal** [comment]
Yup, turning off chroma subsampling fixed things. Thanks!
