### ISSUE TITLE
Encrypted PDF files

### ISSUE THREAD

**Issue by BasixKOR** [libvips/libvips#2635]
Currently loading encrypted PDF files fails with this message:

```
glib: Document is encrypted
```

Could we have a password provided via arguments?

**Comment by jcupitt** [comment]
Hi @BasixKOR,

Sure, why not. Could you supply a test PDF?

**Comment by BasixKOR** [comment]
I can't give you the PDF file I have since it contains my private information but you can drop any PDF files here and get a example of protected PDFs: https://smallpdf.com/protect-pdf/

**Comment by jcupitt** [comment]
I made an encryted PDF for testing:

[nipguide-protected.pdf](https://github.com/libvips/libvips/files/7958340/nipguide-protected.pdf)

Password "banana". Encrypted with AES128 I think.

**Comment by jcupitt** [comment]
OK, seems to work. I tested with:

```
vips copy nipguide-protected.pdf[password=banana,page=12] x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/151554834-036a5032-0503-44e7-bbe7-72ccfb115323.png)

This will be in 8.13.

`pdfiumload` needs a similar option.

**Comment by jcupitt** [comment]
... I did pdfium too. I'll close.

Thanks for the suggestion!
