### ISSUE TITLE
I cannot upgrade or install libvips on my Gatsby Website

### ISSUE THREAD

**Issue by mluce194** [libvips/libvips#2638]
When I try to do "Gatsby develop", I get an error with libvips saying I have to upgrade it. However, I cannot upgrade it and I cannot install it either.

**To Reproduce**
1. Type on npm terminal "gatsby develop"
2. The following message comes up:
```
Error: Something went wrong installing the "sharp" module
  dlopen(/Users/marie-luce/Documents/projets/1-SEOAlternative/www/node_modules/sharp/build/Release/sharp-darwin-x64.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
    Referenced from: /Users/marie-luce/Documents/projets/1-SEOAlternative/www/node_modules/sharp/build/Release/sharp-darwin-x64.node
    Reason: Incompatible library version: sharp-darwin-x64.node requires version 56.0.0 or later, but libvips-cpp.42.dylib provides version 55.0.0
  Possible solutions:
  - Update Homebrew: "brew update && brew upgrade vips"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install
```
3. Type on npm terminal "brew update && brew upgrade vips" (as recommended in step 2)
4. The following error comes up:
`Already up-to-date.
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
Error: vips not installed`

I tried installing vips again (although it is supposed to be already installed) by typing: "brew install vips"

But I got the following error:

```
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
qt: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: vips: An unsatisfied requirement failed this build.
```

**Comment by lovell** [comment]
Please can you open an installation issue on the sharp repo via https://github.com/lovell/sharp/issues/new?assignees=&labels=installation&template=installation.md and answer all of the questions.
