### ISSUE TITLE
improve vips__random

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2642]
libvips uses a fast random number generator for operations like gaussnoise. It could use a bit of polish :/

```
vips gaussnoise x.png 512 512 --mean 128 --sigma 25
```

Generates:

![x](https://user-images.githubusercontent.com/580843/152210281-c4d5d946-3a34-4a91-b4a4-9b83ae9e05e3.png)

See: http://isthe.com/chongo/tech/comp/fnv/#FNV-source

**Comment by jcupitt** [comment]
I revised it very quickly, I now see:

![x](https://user-images.githubusercontent.com/580843/152213484-cb70a4df-7b50-446a-8163-5e773e7bb149.png)

**Comment by mhirsch** [comment]
Wow! That was a fast (but not random) response! Thank you.
