### ISSUE TITLE
New build system snags

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2650]
The new meson build systems still has a few small snags. This issue keeps track of them as we find them.

- [x] Fix build with GraphicsMagick: we used to have a `--magick-package` option you could use to select the `pkg-config` package to use for IM support. This should be reimplemented.
- [x] Revise docs. 
- [x] Switch to `gnu99` std?
- [x] Fix doxygen 
- [x] Fix g_assert() disabling etc.

**Comment by jcupitt** [comment]
Docs: I had a go at the main README, but the install section of the website (it's in the gh-pages branch) will need revising too.

**Comment by jcupitt** [comment]
I've updated the website too, and moved CI to meson.

**Comment by jcupitt** [comment]
Looks like the docy paths are messed up, I see:

```
$ meson setup build --prefix=~/vips -Ddoxygen=true
...
$ cd build
$ ninja
$ ninja
[2/495] Generating vipsmarshal_c with a custom command
INFO: Reading ../libvips/iofuncs/vipsmarshal.list...
[3/495] Generating vipsmarshal_h with a custom command
INFO: Reading ../libvips/iofuncs/vipsmarshal.list...
[6/495] Generating vips-cpp-docs with a custom command
warning: tag INPUT: input source 'README.md' does not exist
warning: tag INPUT: input source 'VConnection.cpp' does not exist
warning: tag INPUT: input source 'VError.cpp' does not exist
warning: tag INPUT: input source 'VImage.cpp' does not exist
warning: tag INPUT: input source 'VInterpolate.cpp' does not exist
warning: tag INPUT: input source 'vips-operators.cpp' does not exist
warning: tag INPUT: input source 'include/vips/VConnection8.h' does not exist
warning: tag INPUT: input source 'include/vips/VError8.h' does not exist
warning: tag INPUT: input source 'include/vips/VImage8.h' does not exist
warning: tag INPUT: input source 'include/vips/VInterpolate8.h' does not exist
warning: tag INPUT: input source 'include/vips/vips8' does not exist
warning: source 'README.md' is not a readable file or directory... skipping.
warning: source 'VConnection.cpp' is not a readable file or directory... skipping.
warning: source 'VError.cpp' is not a readable file or directory... skipping.
warning: source 'VImage.cpp' is not a readable file or directory... skipping.
warning: source 'VInterpolate.cpp' is not a readable file or directory... skipping.
warning: source 'vips-operators.cpp' is not a readable file or directory... skipping.
warning: source 'include/vips/VConnection8.h' is not a readable file or directory... skipping.
warning: source 'include/vips/VError8.h' is not a readable file or directory... skipping.
warning: source 'include/vips/VImage8.h' is not a readable file or directory... skipping.
warning: source 'include/vips/VInterpolate8.h' is not a readable file or directory... skipping.
warning: source 'include/vips/vips8' is not a readable file or directory... skipping.
...
```

And no useful docs are generated in `build/cplusplus/html`.

**Comment by eli-schwartz** [comment]
The Doxyfile lists its input files relative to the root of the source directory -- doxygen looks for files relative to the current working directory it is run in. For a command executed via ninja, that will be the build directory.

It should be possible to do a bit more in configure_file, and prefix each input filename with `@VAR_POINTING_TO_SOURCE_ROOT@`.

**Comment by jcupitt** [comment]
OK, doxy is fixed, hopefully. Thanks @eli-schwartz.

**Comment by jcupitt** [comment]
g_assert() etc. fixed with https://github.com/libvips/libvips/pull/2682

**Comment by eli-schwartz** [comment]
With regard to your configure.ac change, note that autotools *does* support optionally building out of tree, and while that can be inadvertently broken by bad (non-idiomatic) usage of configure.ac and Makefile.an, `make distcheck` will fail if it does not work.

Unfortunately not many people, relatively speaking, even know that out of tree builds are possible (and not everyone uses distcheck).

So the doxygen docs were always broken for out of tree autotools builds, but worked for in-tree builds.

...

Autotools does have `@abs_top_builddir@` as an automatic substitution for this.

**Comment by jcupitt** [comment]
Yes, it was just a quick hack to keep autotools going for a little longer. We plan to delete it all and be meson-only for 8.14.

**Comment by eli-schwartz** [comment]
I only mentioned it because I'm a bit of a buildsystems nerd. :p
