### ISSUE TITLE
Exif data contains "extra" information

### ISSUE THREAD

**Issue by rafaelsierra** [libvips/libvips#2653]
Hi, I am trying to add bindings to set and get metadata from images on govips[1], but whenever I set `exif-ifd2-UserComment` to `hello world`, I always get back `hello world (hello world, Undefined, 19 components, 19 bytes)`

At first I thought it was something about the `vips_image_get_as_string` function I was using, but then I tried locally just `vips_image_get` (combined with `g_value_get_string`) and got the same result.

The same happens when using `pyvips`, which indicates the "problem" is on libvips itself, not on a specific binding.

Is it possible to return only the value that was actually set without the verbose information about the exif value?

[1] - https://github.com/davidbyttow/govips/pull/265

**Comment by jcupitt** [comment]
Hello @rafaelsierra,

This is a problem with exif -- it doesn't have a simple string representation. libvips tries to fix this by adding some extra stuff in brackets after the string representation, but it's still very awkward.

When reading an exif field with `_get`, you need to drop the trailing ` ( ... )`. This is not an easy thing to do correctly. A better system would be a good idea.

There was a long discussion about this last year:

https://github.com/libvips/libvips/pull/2518
