### ISSUE TITLE
Porblems installing on Centos

### ISSUE THREAD

**Issue by AstonJ** [libvips/libvips#27]
I'm having trouble installing Vips on my centos box.

I've downloaded the latest files:

wget http://www.vips.ecs.soton.ac.uk/supported/current/vips-7.30.0.tar.gz
wget http://www.vips.ecs.soton.ac.uk/supported/current/nip2-7.30.1.tar.gz

And on `./configure` I get: 

```
configure: error: Package requirements (glib-2.0 >= 2.6 gmodule-2.0 >= 2.4 libxml-2.0 gobject-2.0) were not met:

No package 'glib-2.0' found
No package 'gmodule-2.0' found
No package 'gobject-2.0' found
```

However I have `yum install glib2` and rerun ./configure but get the same error. Am I doing something wrong?
Is there a guide I can follow to install on Centos?
Sorry to be such a noob.

**Comment by LITTLEKKKK** [comment]
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Leaving directory `/public/software/libvips/vips-8.10.5/test'
make[2]: Leaving directory `/public/software/libvips/vips-8.10.5/test'
Making all in fuzz
make[2]: Entering directory `/public/software/libvips/vips-8.10.5/fuzz'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/public/software/libvips/vips-8.10.5/fuzz'
make[2]: Entering directory `/public/software/libvips/vips-8.10.5'
make[2]: Leaving directory `/public/software/libvips/vips-8.10.5'
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/public/software/libvips/vips-8.10.5'
make: warning:  Clock skew detected.  Your build may be incomplete.


this is my problem. what should I do?

**Comment by jcupitt** [comment]
Please don't post unrelated questions on old issues. Make a new post on discussions instead:

https://github.com/libvips/libvips/discussions
