### ISSUE TITLE
"Apparent Greyscale" transform

### ISSUE THREAD

**Issue by dg1727** [libvips/libvips#271]
I wonder if the VIPS team might be interested in adding the following algorithm for converting colour to greyscale:  
http://resources.mpi-inf.mpg.de/ApparentGreyscale/
I didn't find mention of it in the VIPS documentation, including the output of the `vips list classes` commandline (as of vips-7.42.3).

**Comment by jcupitt** [comment]
Hi, in fact by coincidence vips got a better greyscale a couple of days ago:

https://github.com/jcupitt/libvips/issues/266

I tried their test image with vips master and got this:

![vips-greyscale](https://cloud.githubusercontent.com/assets/580843/7229585/54bea3e6-e75d-11e4-8a1a-4e2504f57c20.png)

Which (I think) actually looks better. They have too much contrast in the foreground (in my opinion).

**Comment by dg1727** [comment]
I think "contrast in the foreground" is what they are aiming for.  Many people would say that the red flower in the original stands out against the blue and green around it, so it's right for it to have high contrast in the greyscale as well.  

It seems like you're pushing for a soon release of vips 8.0, and I wouldn't want that to be delayed, but maybe this other greyscale method can be considered after that release?  

Or if you don't run the project that way, then you can close this suggestion, and if others make the same request later, then maybe this feature will be added.

**Comment by jcupitt** [comment]
Sure, let's leave this open and tagged as "enhancement". Their algorithm does look interesting.
