### ISSUE TITLE
Image color is wrong after converting it using vipsthumbnail

### ISSUE THREAD

**Issue by KasperDeSmedt** [libvips/libvips#2713]
## Bug report

**Describe the bug**
After using the vipsthumbnail comment line tool to convert album art to a smaller size the colors are different.

**To Reproduce**
1. Use Image:
   ![OriginalImage](https://user-images.githubusercontent.com/61057232/157486992-44fb5e7b-3135-4033-b9d3-a59cd2c273a6.jpeg)
2. Execute `vipsthumbnail OriginalImage.jpeg -o ResultImage.jpeg` in a terminal.
3. Resulting Image:
  ![ResultImage](https://user-images.githubusercontent.com/61057232/157487364-cf851827-969f-4b4b-ab41-63a09c0ae415.jpeg)

**Expected behavior**
Image colors stay the same.

**Actual behavior**
Image colors are lighter.

**Environment**
 - OS: Ubuntu 20.10
 - Vips: 8.12.1 & 8.12.2

**Comment by jcupitt** [comment]
Hi @KasperDeSmedt,

What a good test image, I love Massive Attack.

It's a CMYK JPEG image with no embedded profile, so I suppose the CMYK->RGB conversion has failed for you. It should work though, I'm curious what went wrong. I see:

```
$ vipsthumbnail massive-attack.jpeg 
```

To make:

![tn_massive-attack](https://user-images.githubusercontent.com/580843/157495023-3badfed9-bd77-4536-bf1d-ce3972f6e35c.jpg)

I'll try with some other libvips versions and see if I can reproduce it.

Do you know what lcms version you are using?

**Comment by KasperDeSmedt** [comment]
Hi @jcupitt,
The problem was indeed that I build without `liblcms2-dev`.
Thanks for the fast response.
