### ISSUE TITLE
Photo generated in pyramid tiff format displayed malformed in openseadragon

### ISSUE THREAD

**Issue by joesong168** [libvips/libvips#2716]
## Bug report

**Describe the bug**
Photo generated in pyramid tiff format displayed malformed in openseadragon

**To Reproduce**
1. Use image http://viewers.etu.wiki/3d9583122daa92eee0aa6caea6c13cb6.tif
2. Use windows 10 vips 8.12
3. Apply following commands
        vips extract_band 3d9583122daa92eee0aa6caea6c13cb6.tif 3d9583122daa92eee0aa6caea6c13cb6.v 0 --n 3 
        vips colourspace 3d9583122daa92eee0aa6caea6c13cb6.v 3d9583122daa92eee0aa6caea6c13cb6g_generated.tif[tile,pyramid,compression=webp,tile-width=512,tile-height=512] srgb

**Expected behavior**
A zoom-able photo

**Actual behavior**
Malformed photo while zoom out

**Screenshots**
[If applicable, add screenshots to help explain your problem.](http://viewers.etu.wiki/printscreen.PNG)

**Environment**
(please complete the following information)
 - OS: Windows 10
 - Vips: 8.12
 - openseadragon: latest

**Additional context**

**Comment by jcupitt** [comment]
Hello @joesong168,

It seems to be working for me when I view the image with vipsdisp.

``
$ vips copy 3d9583122daa92eee0aa6caea6c13cb6.tif x.tif[tile,pyramid,compression=webp,tile-width=512,tile-height=512]
```

![shot](https://user-images.githubusercontent.com/580843/157851307-68fee958-c509-492c-8a42-7d2f61855b6f.png)

What sort of malformed images are you seeing? How are you getting openseadragon to process your pyramidal TIFF? Perhaps it does not support webp compression?

**Comment by joesong168** [comment]
This is the print screen of my server
http://viewers.etu.wiki/printscreen.PNG

This is the pyramid tiff I generated
http://viewers.etu.wiki/3d9583122daa92eee0aa6caea6c13cb6.ptif

I guess the problem might be related to thumb setting. If you might the image to its smallest form, you might see the problem.

I have lots of other images that is embedded in webp without this problem.

**Comment by jcupitt** [comment]
Ah, yes I see an error in your ptif in the second layer. The ptif I made here seems OK:

![shot](https://user-images.githubusercontent.com/580843/157868172-6375a1ad-776d-45b8-82ca-0a8cccd9ccf7.png)

I suppose it must be a bug in the libtiff or libwebp your libvips is using.

Which libvips binary are you using?

https://github.com/libvips/build-win64-mxe/releases

**Comment by joesong168** [comment]
Great to hear that the issue is located. The version I used should be [vips-dev-w64-all-8.12.2.zip](https://github.com/libvips/build-win64-mxe/releases/download/v8.12.2-build2/vips-dev-w64-all-8.12.2.zip). But to be sure, I upload the file for you to confirm. http://viewers.etu.wiki/vips-dev-8.12.rar

**Comment by jcupitt** [comment]
There are several different 8.12.2 listed there. Have you tried the most recent one?

**Comment by joesong168** [comment]
Hi @jcupitt, just figure out that I am actually using a vips in alpine:3.14 docker with following setting

RUN set -x -o pipefail \
        && wget -O- https://github.com/libvips/libvips/releases/download/v$VIPS_VERSION/vips-$VIPS_VERSION.tar.gz | tar xzC /tmp \
        && apk add \
        zlib libxml2 glib gobject-introspection \
        libjpeg-turbo libexif lcms2 fftw giflib libpng \
        libwebp orc tiff poppler-glib librsvg libgsf openexr \
        && apk add --virtual vips-dependencies build-base \
        zlib-dev libxml2-dev glib-dev gobject-introspection-dev \
        libjpeg-turbo-dev libexif-dev lcms2-dev fftw-dev giflib-dev libpng-dev \
        libwebp-dev orc-dev tiff-dev poppler-dev librsvg-dev libgsf-dev openexr-dev \
        py-gobject3-dev \
        && cd /tmp/vips-$VIPS_VERSION \
        && ./configure --prefix=/usr \
                       --disable-static \
                       --disable-dependency-tracking \
                       --enable-silent-rules \
                       --enable-pyvips8 \
        && make -s install-strip \
        && cd $OLDPWD \
        && rm -rf /tmp/vips-$VIPS_VERSION \
        && apk del --purge vips-dependencies \
        && rm -rf /var/cache/apk/*

Would you find anything that might be suspicious?

**Comment by jcupitt** [comment]
I tried this dockerfile:

```
FROM alpine:3.14

RUN apk update && apk upgrade

# basic packages libvips likes
RUN apk add \
        build-base \
        autoconf \
        automake \
        libtool \
        bc \
        zlib-dev \
        expat-dev \
        jpeg-dev \
        tiff-dev \
        glib-dev \
        libjpeg-turbo-dev \
        libexif-dev \
        lcms2-dev \
        fftw-dev \
        giflib-dev \
        libpng-dev \
        libwebp-dev \
        orc-dev \
        libgsf-dev

# add these if you like for text rendering, PDF rendering, SVG rendering, 
# but they will pull in loads of other stuff
RUN apk add \
        gdk-pixbuf-dev \
        poppler-dev \
        librsvg-dev

# there are other optional deps you can add for openslide / openexr /
# imagmagick support / Matlab support etc etc

ARG VIPS_VERSION=8.12.2
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download

RUN wget -O- ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
        | tar xzC /tmp
RUN cd /tmp/vips-${VIPS_VERSION} \
        && ./configure --prefix=/usr \
                --disable-static \
                --disable-debug \
                --disable-deprecated \
        && make -j 16 V=0 \
        && make install

RUN apk add \
        python3-dev \
        py3-pip

RUN pip3 install wheel
RUN pip3 install pyvips

WORKDIR /data
```

And tested it with:

```
$ docker run --rm -t -v $PWD:/data pyvips-alpine \
    vips copy 3d9583122daa92eee0aa6caea6c13cb6.tif \
        x.tif[tile,pyramid,compression=webp,tile-width=512,tile-height=512]
```

And it generated a correct image. You'll need to post a complete dockerfile before I could test your setup.

**Comment by joesong168** [comment]
Finally I configured out where the issue lies in. In my script I am using following command to get web pyramid file.
vips extract_band /tmp/$etag /tmp/$etag.v 0 --n 3
vips colourspace /tmp/$etag.v /tmp/$etag.tif[tile,pyramid,compression=webp,tile-width=512,tile-height=512] srgb
Although it works in almost all other images, it failed in this one.

**Comment by joesong168** [comment]
You are right. Even myself couldn't replay it on my desktop. Maybe next time when I can replay it. I will reopen this thread. Thanks a lot for your help anyway.

**Comment by jcupitt** [comment]
Ah well, I'm glad it's working now.

**Comment by joesong168** [comment]
Vips 8.14.2 used a new way to compile from source. May I know how to create a docker for this new version?

**Comment by jcupitt** [comment]
I made you a sample dockerfile:

https://github.com/jcupitt/docker-builds/blob/master/pyvips-alpine/Dockerfile

**Comment by joesong168** [comment]
Great! Thanks a lot.

**Comment by joesong168** [comment]
One more question. How to add openJPGE to the docker image?

**Comment by jcupitt** [comment]
Just add `openjpeg-dev` to the list of packages at the top.

**Comment by joesong168** [comment]
Thanks.
