### ISSUE TITLE
Alpha Extrasample with WebP compression and tiffsave

### ISSUE THREAD

**Issue by John-P** [libvips/libvips#2717]
## Bug report

I am writing some tiled TIFFs and when using WebP compression, some libraries have trouble opening them (see original issue here: https://github.com/cgohlke/tifffile/issues/122). It appears that an extrasamples is being defined for an alpha channel when the WebP tile images are just RGB. They do load correctly in GNOME image viewer and OpenSlide, however there does appear to be some metadata mismatch going on here.

**To Reproduce**
1. Use Image 'CMU-1-Small-Region.svs' (https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/)
2. Use tiffsave (see below)
3. Try to read with tifffile (see below)

Write
```
vips tiffsave CMU-1-Small-Region.svs CMU-1-Small-Region.webp.tiff \
--tile --tile-width 256 --tile-height 256 \
--compression webp \
--vips-progress \
--xres 20040 --yres 20040
```

Read
```python
import tifffile

tiffile.imread("CMU-1-Small-Region.webp.tiff")
```

**Expected behavior**
No error output.

```python
import tifffile

tiff = tifffile.TiffFile("CMU-1-Small-Region.webp.tiff")
print(tiff.pages[0].tags["ExtraSamples"])
...
KeyError: "ExtraSamples"
```

**Actual behavior**

```
   6393                         t = numpy.zeros(size, data.dtype)
   6394                         size = min(data.size, size)
-> 6395                         t[:size] = data[:size]
   6396                         data = t.reshape(shape)
   6397                 return data

ValueError: could not broadcast input array from shape (256,256,3) into shape (196608,)
```

```python
import tifffile

tiff = tifffile.TiffFile("CMU-1-Small-Region.webp.tiff")
print(tiff.pages[0].tags["ExtraSamples"])
TiffTag 338 ExtraSamples @661964 SHORT @661972 (<EXTRASAMPLE.UNASSALPHA: 2>,)
```

See https://github.com/cgohlke/tifffile/issues/122 for further discussion.

**Environment**
(please complete the following information)
 - OS: PopOS/Ubuntu 21.10
 - Vips: 8.12.2

**Comment by jcupitt** [comment]
Hi @John-P,

openslide images are all RGBA, so the TIFF will be saved as RGB plus an unpremultiplied alpha (non-assoc).

You can flatten out the openslide alpha before save, would that fix it?

**Comment by jcupitt** [comment]
Ah hang on, perhaps the libtiff webp writer doesn't know about alpha? That might explain it.

**Comment by John-P** [comment]
Ah yes, that would make a lot of sense. Is vips is reading with openslide then it will will be adding an alpha channel. It does seem that something isn't quite right though. Also, an command line option to write with no alpha would be helpful for such images where openslide adds a blank alpha channel.

**Comment by jcupitt** [comment]
I tried:

```
$ vips copy PNG_transparency_demonstration.png x.tif[compression=webp,tile,tile-width=128,tile-height=128]
$ tiffinfo x.tif
TIFF Directory at offset 0x80248 (13978)
  Image Width: 800 Image Length: 600
  Tile Width: 128 Tile Length: 128
  Resolution: 28.34, 28.34 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: WEBP
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Planar Configuration: single image plane
```

And I can view the image correctly, including the alpha, so I think it's working. Here's the test PNG:

![PNG_transparency_demonstration](https://user-images.githubusercontent.com/580843/157908485-1707acd2-16f4-49f1-9a54-8bef463eb132.png)

You can remove alpha with `extract_band`, eg.:

```
$ vips extract_band CMU-1-small-region.svs x.tif[compression=webp,tile] 0 --n 3
```

ie. starting from band 0, take 3 bands (RGB).

**Comment by jcupitt** [comment]
Hi again, I checked this with libvips 8.15, and I think it's working correctly, and I think the webp tiles all have alpha. For example:

```
$ vips copy PNG_transparency_demonstration.png x.tif[tile,compression=webp]
$ vips copy x.tif x.png
```

Makes a correct PNG, including a complete alpha. Here's the output:

![x](https://github.com/libvips/libvips/assets/580843/ea81b6e1-ff25-4c18-ac39-4cd18d77169d)

**Comment by jcupitt** [comment]
> Also, a command line option to write with no alpha would be helpful for such images where openslide adds a blank alpha channel.

Thanks for suggesting this, we added an `rgb` option to `openslideload` in libvips 8.14. You can write:

```
$ vips copy x.svs[rgb] x.tif
```

And the TIFF file will be written without an alpha.

**Comment by jcupitt** [comment]
Sorry, final comment, I came across your nice paper about WSIC:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10502236/

libvips 8.15 has a new threaded TIFF writer:

https://github.com/libvips/libvips/blob/gh-pages-8.15/_posts/2023-10-10-What's-new-in-8.15.md#better-tiffsave

SVS to pyramidal JPEG TIFF is about 2x faster now, on this PC at least.
