### ISSUE TITLE
improve animated webp write

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2722]
Animated webp images are written with a series of crops and saves. Instead, they should use `sink_disc` and stream the image to the output in a single iteration.

See https://github.com/lovell/sharp/issues/3068

**Comment by adityapatadia** [comment]
Hey,
Can you point us to files which has these specific functions and how can we solve this? Not too good with CPP but will try to see if we can raise a PR. This issue of not having timeout is causing production problems.

**Comment by jcupitt** [comment]
It's a little complex, unfortunately. You'd need to rework the webp writer using something like the gif writer as a model. It should use the sink API and accumulate pages in a temporary buffer.

https://github.com/libvips/libvips/blob/master/libvips/foreign/cgifsave.c

**Comment by jcupitt** [comment]
Let's switch discussion to the PR.
