### ISSUE TITLE
Webp encoded pyramid tiff don't display well

### ISSUE THREAD

**Issue by joesong168** [libvips/libvips#2762]
## Bug report

**Describe the bug**
Webp encoded pyramid tiff don't display well. Part of it is displayed lighter 

**To Reproduce**
1. Use Image '...'
http://viewers.etu.wiki/sample.ptif

2. Open in openseadraong

**Expected behavior**
A normal pyramid tiff image

**Actual behavior**
Part of the image is missing when enlarged.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](http://viewers.etu.wiki/printscreen.png)

**Environment**
(please complete the following information)
 - OS: Win and Mac
 - Vips: 8.12.2

**Additional context**
encoded by following command

vips extract_band $file /tmp/$etag.v 0 --n 4
vips colourspace /tmp/$etag.v /tmp/$etag.tif[tile,pyramid,compression=webp,tile-width=512,tile-height=512] srgb

**Comment by jcupitt** [comment]
Hi @joesong168, did you mean to close this?

I think it's cased by differences in rounding behaviour. OSD is expecting round-up, but libvips does round-down for TIFF pyramids. If you are unlucky, this can cause differences in the number of tiles across or down an image.

Fixing it would mean changing the way the tiff save operation handles rounding, l which I suppose might have consequences for compatibility. We'd probably need a flag for "save as OSD-compatible TIFF pyramid".

**Comment by jcupitt** [comment]
... a workaround would be to expand the input image to the next highest power of two. That way there would be no rounding in the layer sizes.
