### ISSUE TITLE
tiffsave bug when creating tiled pyramid from multi-band images

### ISSUE THREAD

**Issue by ruven** [libvips/libvips#2763]
There seems to be a bug when using tiffsave to save multi-band images as tiled pyramids. The first (full size) resolution in the pyramid is correctly encoded, but all the lower resolutions seem to be corrupted.

I've attached an example 8 band image in vips format, which is correctly encoded:
[multiband.v.gz](https://github.com/libvips/libvips/files/8492459/multiband.v.gz)

And the tiff created from it using the command 
`vips tiffsave multiband.v multiband.tif --tile --pyramid --compression none --tile-width 256 --tile-height 256`
[multiband.tif.gz](https://github.com/libvips/libvips/files/8492466/multiband.tif.gz)

If you take, for example, the 5th band from the 4th resolution (I used tiffsplit to extract each resolution), which consists of a single tile of size 250x150 pixels you can see that the left hand side of the image is missing:
![multiband_resolution4](https://user-images.githubusercontent.com/776628/163483991-376cdead-5e75-4435-b4ab-f35f110dbdd8.jpg)

I get the same result with both vips 8.12.2 and vips 8.10.x.

**Comment by jcupitt** [comment]
Hi Ruven, nice to hear from you!

I think this is cased by alpha handling. Your image is tagged as `b-w`, so libvips is treating it as a greyscale image with 7 (!!!) alpha channels. During pyramid shrink, it's premuiltiplying band 0 with band 1 to prevent fringing, and that's breaking your image. Though it's curious that the break doesn't seem to affect all tiles equally, I'll have a look.

If you tag your image as `multiband`, you won't get premultiplication before shrink and it all works:

```
$ vipsedit multiband.v -i multiband
$ vips tiffsave multiband.v m.tif --tile --pyramid
```

Using vipsdisp (https://flathub.org/apps/details/org.libvips.vipsdisp) I see:

![x](https://user-images.githubusercontent.com/580843/163556281-a848cedd-f83b-4b65-8873-e86bb279110b.png)

**Comment by ruven** [comment]
OK, I see! Everything indeed works properly if I set it to multiband.

However, the tiffsave documentation you get when you type just `vips tiffsave` says that there is a parameter for pre-multiplication `--premultiply`, which accepts an input gboolean but is false by default. So, is this in fact true by default? And when you try to set this to 0 or false, it gives an error `tiffsave: too many arguments`. It doesn't complain if there is no argument.

Yes, hope to see you soon ;-)

**Comment by jcupitt** [comment]
The `--premultiply` flag means save as premultipied TIFF. A few applications need it, I forget exactly which. I'm sure you don't heh.

Bool flags don't take a value, adding them implies TRUE.

**Comment by ruven** [comment]
Thanks for resolving this for me!

**Comment by jcupitt** [comment]
Actually, there is a bug, it's not handling the alpha correctly. I'm still looking :/

**Comment by jcupitt** [comment]
Ahhh found it, it's your test image, the final band (which the tiff shrinker uses as the alpha) has a sharp cutoff, so all bands go to zero in that area on shrink.

```
$ vips extract_band multiband.v x.v 7
$ vips linear x.v x1.v 50 0
$ vips falsecolour x1.v x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/163671663-f1884f1d-760f-407d-8b74-2e3dba942b80.png)
