### ISSUE TITLE
conversion of  bayer raw images into jpeg images in libvips

### ISSUE THREAD

**Issue by shameerasl** [libvips/libvips#2771]
Hi. I am again here to  accquire more information regarding libvips commands.  Can libvips convert raw files to jpeg files? Type of the raw file is bayer rggb. I am using libvips in windows. And your small reference also will be great help.Thanks in advance

**Comment by jcupitt** [comment]
Hi @shameerasl, this is best handled by a specialist library. I'd look at libraw:

https://www.libraw.org/

There's been some discussion about integrating this with libvips, but no one has volunteered yet.

https://github.com/libvips/libvips/discussions/2075#discussioncomment-2332258
