### ISSUE TITLE
libvips terminating while writing tiff file

### ISSUE THREAD

**Issue by ademmler** [libvips/libvips#2789]
I tried to use 1bit tiffs but I get repettetive errors while writing the result and "abortrap 6" reached finally.

(process:5101): VIPS-WARNING **: 11:18:51.671: Unknown field with tag 32781 (0x800d) encountered
(process:5101): VIPS-WARNING **: 11:18:51.681: error in tile 0 x 127
libc++abi.dylib: terminating with uncaught exception of type vips::VError: tiff2vips: out of order read -- at line 2835, but line 0 requested
tiff2vips: out of order read -- at line 2835, but line 127 requested

Samples files can be found in the discussion below.

### Discussed in https://github.com/libvips/libvips/discussions/2777
<div type='discussions-op-text'>
<sup>Originally posted by **ademmler** April 25, 2022</sup>
How can I set / convert 1bit BW images to 8Bit Greyscale using libvips and c++.</div>

**Comment by jcupitt** [comment]
Sorry @ademmler, I've been horribly busy. I'll try to look at this soon.

**Comment by jcupitt** [comment]
Solved in the discussion linked above.

**Comment by ademmler** [comment]
Yep - thank you so much!
