### ISSUE TITLE
Unsafe cast in jpeg2vips when calling vips_source_read

### ISSUE THREAD

**Issue by flga** [libvips/libvips#2799]
Hey, first of all thank you for working on vips, it's truly an amazing project :+1: 

## Bug report
`vips_source_read()` returns -1 if there's a problem reading from the underlying src, `source_fill_input_buffer()` casts the `gint64` return to `size_t` causing an infinite loop due to the signed to unsigned cast.

From a quick search pdfiumload and sbuf could have the same problem.

**To Reproduce**
Create a custom source that breaks after reading the first 1k of data. It's not the only way to break it but this is conceptually similar to a test I was implementing for a custom source and target pipeline. I was expecting the problem to be on my end so I created a quick and dirty (emphasis on dirty :smile:) repro.

```#include <stdio.h>
#include <unistd.h>
#include <vips/vips.h>

static gint64 nread = 0;
FILE *f;

// emulate a faulty reader that fails after reading 1k
gint64 read_cb(VipsSourceCustom *source_custom, gpointer buffer, gint64 size, gpointer user_data) {
  int n;
  if (nread >= 1024) {
    printf("-1\n");
    return -1;
  }

  n = fread(buffer, sizeof(char), size, f);
  nread += n;
  return n;
};

int main() {
  f = fopen("box.jpg", "r");
  VipsSourceCustom *source_custom = vips_source_custom_new();
  g_signal_connect(source_custom, "read", G_CALLBACK(read_cb), NULL);

  VipsImage *img;
  if (vips_jpegload_source(VIPS_SOURCE(source_custom), &img, "access", VIPS_ACCESS_SEQUENTIAL, NULL)) {
    printf("%s\n", vips_error_buffer());
    return 1;
  }

  if (vips_jpegsave(img, "out.jpg", NULL)) {
    printf("%s\n", vips_error_buffer());
    return 1;
  }

  return 0;
}
```
box.jpg (it's not super relevant what image it is, but this is the one I used)
![box](https://user-images.githubusercontent.com/3987005/167932901-1943061a-183b-4dd0-8098-ac1d53696c5b.jpg)

**Expected behavior**
If `vips_source_read` returns -1 `source_fill_input_buffer` should handle the error.

**Environment**
 - OS: Manjaro
 - Vips: 43db3985d0c0f0321434f2bd1cda36c7dd4fa1e5

**Comment by jcupitt** [comment]
Hi @figa,

This is a classic read() bug, I'd hoped we'd dodged it by using gint64 instead, but we obviously missed a couple. Hopefully I've fixed this. Patch: https://github.com/libvips/libvips/commit/5221df224f573653045799fdb98f8fdc19922f2d

Thanks for pointing this out! And I've credited you in the changelog.
