### ISSUE TITLE
nsgif copyright file is missing

### ISSUE THREAD

**Issue by mika-fischer** [libvips/libvips#2800]
See https://source.netsurf-browser.org/libnsgif.git/tree/COPYING

It should be present here https://github.com/libvips/libvips/tree/master/libvips/foreign/libnsgif

**Comment by jcupitt** [comment]
Oooop, sorry about that. Thanks for pointing this out.

**Comment by mika-fischer** [comment]
Thanks for the quick fix, but was it on purpose to put the fix in the add-tiffsave_target and not in master?

**Comment by jcupitt** [comment]
:facepalm: it's either too much or too little coffee :( fixed now
