### ISSUE TITLE
vips_target_finish can fail silently resulting in corrupted or null output

### ISSUE THREAD

**Issue by flga** [libvips/libvips#2801]
## Bug report

**Describe the bug**
Currently `vips_target_finish` returns `void`, this can be a problem because it needs to call `vips_target_flush` which can fail.
This silences any errors that might occur on the last write to the target, and can be particularly devious if all the writes up to that point fit into the target buffer, causing the only write to actually occur to fail silently.

In summary, when using the streaming api (at least _custom) any output that is less than `VIPS_TARGET_BUFFER_SIZE` can fail unbeknownst to the caller.

**To Reproduce**
Load and save a small image with a write implementation that fails.
```c
#include <stdio.h>
#include <unistd.h>
#include <vips/vips.h>

gint64 write_cb(VipsTargetCustom *target_custom, gpointer data, gint64 length, gpointer user_data) {
  printf("quick, duck! it's a cosmic ray!\n");
  return -1;
};

int main() {
  VipsSource *source = vips_source_new_from_file("box.jpg");
  VipsTargetCustom *target_custom = vips_target_custom_new();
  g_signal_connect(target_custom, "write", G_CALLBACK(write_cb), NULL);

  VipsImage *img;
  if (vips_jpegload_source(source, &img, "access", VIPS_ACCESS_SEQUENTIAL, NULL)) {
    printf("%s\n", vips_error_buffer());
    return 1;
  }

  if (vips_jpegsave_target(img, VIPS_TARGET(target_custom), NULL)) {
    printf("%s\n", vips_error_buffer());
    return 1;
  }

  printf("phew!\n");
  return 0;
}
```
box.jpg
![box](https://user-images.githubusercontent.com/3987005/168396878-07aaf23a-fbaa-4206-9bfb-dc7d0178df38.jpg)

**Environment**
 - Vips: 7561d4e52c9961e9f644fe23247248704f4498b6

**Comment by jcupitt** [comment]
You're right, I remember worrying about this.

I've made a PR for a fix.
