### ISSUE TITLE
jxlssave produces XYB encoded JXL images when setting distance=0

### ISSUE THREAD

**Issue by f1ac** [libvips/libvips#2818]
When trying to produce lossless JXL images, currently XYB encoded images are generated, and they are not technically lossless. libjxl will generate an error in this case in upcoming builds, see https://github.com/libjxl/libjxl/pull/1270

As I understand basic_info.uses_original_profile should be true if the file is lossless to avoid XYB encoding, and false otherwise for better compression. I can see "jxl->info.uses_original_profile = TRUE;" line in the encoder, so not sure why this issue happens.

Reproducible in 8.12.2 and latest master on windows.

**Comment by f1ac** [comment]
Looked at wrong branch, indeed current master has 'jxl->info.uses_original_profile = JXL_FALSE;' which causes all files to become XYB encoded. I think the correct way to handle this is to change this line to 'jxl->info.uses_original_profile = jxl->lossless;'

**Comment by jcupitt** [comment]
I tried this, but it just makes jxlsave lock up if `uses_original_profile` is TRUE. There must be some other change needed as well.

I should probably sit down and read cjxl again :(

**Comment by f1ac** [comment]
Didn't lock up for me when I tried lossless conversion using [add-more-libjxl-metadata](https://github.com/libvips/libvips/tree/add-more-libjxl-metadata) branch where uses_original_profile is TRUE, I only tried with float images though.
