### ISSUE TITLE
cgifsave: number of colours in palette is one less than it could/should be

### ISSUE THREAD

**Issue by lovell** [libvips/libvips#2852]
The number of colours in the palette of GIF output via cgifsave is currently set to one less than it could be due to this line:

https://github.com/libvips/libvips/blob/bae0342d9506a4e6f2e5e8ba0bb612c6a601044e/libvips/foreign/cgifsave.c#L685

This can be highlighted by setting `bitdepth` to 1, resulting in a call to `liq_set_max_colors` with the value 1, which is out of the 2-256 range it supports. We currently ignore the error return code so the output GIF has the (default) bitdepth of 8, which is incorrect.

I'm probably to blame here as I originally wrote this code, with the logic of decrementing by 1 to allow space for an extra "colour" for the transparency, if any. However I think with all the recent updates to this code that this logic is no longer required, so the following change should fix this.

```diff
- vips__quantise_set_max_colors( cgif->attr, (1 << cgif->bitdepth) - 1 );
+ vips__quantise_set_max_colors( cgif->attr, 1 << cgif->bitdepth );
```

I'm aware there's more refactoring going on in and around this code so am creating an issue to track it rather than open a PR that may conflict with any work-in-progress.

**Comment by jcupitt** [comment]
Ooop, good catch, I'll fix it in my branch.

**Comment by jcupitt** [comment]
Should be fixed with https://github.com/libvips/libvips/pull/2853

**Comment by kleisauke** [comment]
I noticed that this change produces artefacts with `skate.gif` from https://github.com/libvips/libvips/pull/2824#issuecomment-1147855022, see:
```bash
$ vips copy skate.gif[n=-1] x.gif
```
https://t0.nl/x.gif

Reverting it back to `(1 << cgif->bitdepth) - 1` seems to fix it.
```diff
@@ -731,7 +731,7 @@ vips_foreign_save_cgif_build( VipsObject *object )
 	/* Set up libimagequant.
 	 */
 	cgif->attr = vips__quantise_attr_create();
-	vips__quantise_set_max_colors( cgif->attr, 1 << cgif->bitdepth );
+	vips__quantise_set_max_colors( cgif->attr, (1 << cgif->bitdepth) - 1 );
 	vips__quantise_set_quality( cgif->attr, 0, 100 );
 	vips__quantise_set_speed( cgif->attr, 11 - cgif->effort );
```

**Comment by lovell** [comment]
This looks like it might be something to do with `CGIF_FRAME_GEN_USE_TRANSPARENCY`. Perhaps we should restore the decrement and clamp to a 2-256 range. If max colours equals 2 then we might also have to unset `CGIF_FRAME_GEN_USE_TRANSPARENCY`.
