### ISSUE TITLE
[8.13.0-rc1] libniftiio detection broken with meson

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#2877]
Using autotools

`checking for NIFTI... libraries -lniftiio -lznz, headers -I/usr/include/nifti`

Using meson
```
Run-time dependency niftiio found: NO (tried pkgconfig)

meson.build:510:0: ERROR: Dependency "niftiio" not found, tried pkgconfig
```

Notice: nifticlib-devel package doesn't provide any pkgconfig file.

**Comment by kleisauke** [comment]
Looks like nifticlib only provides the CMake package definition files since v3.0.0, see commit:
https://github.com/NIFTI-Imaging/nifti_clib/commit/158ead7d69829997dfa16da88910831dbdf4f683

Fedora is still on v2.0.0.
https://src.fedoraproject.org/rpms/nifticlib

**Comment by jcupitt** [comment]
On Debian, the best solution I've found (not a very good one) is to make my own `.pc` file, eg.:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include/nifti
Name: libniftiio
Description: nifti library
Version: 3.0.1
Requires: xproto
Cflags: -I${includedir}
Libs: -L${libdir} -lniftiio -lznz
```

Maybe we need to add something to `meson.build` to improve this? `-DNIFTI_CFLAGS` and `-DNIFTI_LIBS` perhaps?

**Comment by remicollet** [comment]
> Fedora is still on v2.0.0.

=> https://bugzilla.redhat.com/show_bug.cgi?id=2099283

**Comment by kleisauke** [comment]
I just opened PR #2882 for this.
