### ISSUE TITLE
`vips arrayjoin` `--across` does not seem to default to 1

### ISSUE THREAD

**Issue by Nakilon** [libvips/libvips#2892]
I need to join image files vertically.

When I do
```
vips arrayjoin "imgf000050_0002.png imgf000051_0001.png imgf000052_0001.png imgf000053_0001.png imgf000054_0001.png imgf000055_0001.png" joined.png
```
I get
![image](https://user-images.githubusercontent.com/2870363/175615154-3ff17f19-3bfe-47bf-ae8b-553e49ef355e.png)
Help says:
```
$ vips arrayjoin
join an array of images
usage:
   arrayjoin in out [--option-name option-value ...]
where:
   in           - Array of input images, input VipsArrayImage
   out          - Output image, output VipsImage
optional arguments:
   across       - Number of images across grid, input gint
			default: 1
			min: 1, max: 1000000
...
```
I.e. the `--across` (the direction is not really clear to me from this text) is 1 by default, but when I do
```
vips arrayjoin "imgf000050_0002.png imgf000051_0001.png imgf000052_0001.png imgf000053_0001.png imgf000054_0001.png imgf000055_0001.png" joined.png --across 1
```
I get
![image](https://user-images.githubusercontent.com/2870363/175615482-d60ba730-a37c-4adf-b5d6-b129d81cc14c.png)
that I suppose means that the "across" means the horizontal direction, and the default value seems to be like Infinity rather than 1.

macOS, vips-8.11.3

P.S.: how do join with no black spacing?

**Comment by jcupitt** [comment]
Hi @Nakilon,

`across` defaults to the number of input images, ie. images are laid out horizontally by default.

https://www.libvips.org/API/current/libvips-conversion.html#vips-arrayjoin

The help test in `vips arrayjoin` output is confusing, I agree. Maybe we should change it to -1?

> P.S.: how do join with no black spacing?

There should not be any black spacing, can you give an example?

**Comment by Nakilon** [comment]
> give an example?
[Архив.zip](https://github.com/libvips/libvips/files/8985241/default.zip)

**Comment by jcupitt** [comment]
Ah OK. Your images are not all the same height, but `arrayjoin` always writes a grid with all cells are the same size. It's designed for very large image grids (eg. 100,000 images).

If you want to join a mixed set of images vertically, use `join` to make a set of pairwise vertical joins.
