### ISSUE TITLE
Added crystal language bindings for libvips

### ISSUE THREAD

**Issue by naqvis** [libvips/libvips#2904]
I've created [Crystal](https://crystal-lang.org) language bindings [crystal-vips](https://github.com/naqvis/crystal-vips) for libvips. Would like to understand the process of getting this binding listed on repo README. Should I need to follow some process or I can have a PR submitted with updated README.md?

**Comment by jcupitt** [comment]
Hi @naqvis,

This is very cool! Nice job! I'll try to have a look at your code.

Sure, make a PR to the libvips README, or perhaps gh-pages, and we can add a link. Maybe we should have a table of known bindings? There are a few now.

**Comment by naqvis** [comment]
> Sure, make a PR to the libvips README, or perhaps gh-pages, and we can add a link. Maybe we should have a table of known bindings? There are a few now.

Thank you @jcupitt . I've raised PR https://github.com/libvips/libvips/pull/2905 to address them.

**Comment by kmartinez** [comment]
Very cool - I  didn't know about crystal before!
