### ISSUE TITLE
Applying vips_convsep and then using vips_magicksave to save image in gif format results in white (blank) images

### ISSUE THREAD

**Issue by talwinder-adv** [libvips/libvips#2909]
## Bug report

**Describe the bug**
Applying vips_convsep and then using vips_magicksave to save image in gif format results in white (blank) images

**To Reproduce**
1. Use Image 'original.jpg'
2. Apply convolution sharpening vips_convsep on image. You can use the attached mask mask_10.mat
`vips convsep original.jpg intermediate.v mask_10.mat`
3. Now, try saving the image using vips_magicksave to save the image in gif format
`vips magicksave intermediate.v magicsaveoutput.gif`
4. Error: See the final image looks too bright and almost blank
5. If we try vips_gifsave instead of vips_magicksave, we see the correct output. Using gifsave works fine.
`vips gifsave intermediate.v gifsaveoutput.gif`

Note: I tried with other images and I am getting the same blank output. This behavior is for majority of the images we save using magicksave after applying convsep

**Expected behavior**
vips_magicksave should not make the image blank and should save the sharpened image as seen with vips_gifsave (this working correctly) 

**Actual behavior**
vips_magicksave is making the image blank while saving

**Environment**
(please complete the following information)
 - OS: MacOS 12.4
 - Vips: 8.12.2
 
**Screenshots**
I have attached all the images mentioned in the steps for your reference. 
Original Image:
![original](https://user-images.githubusercontent.com/108735047/177343517-7d00a782-c258-4c0f-be43-14a9c8dee185.jpg)

Actual output (using magicksave)
![magicsaveoutput](https://user-images.githubusercontent.com/108735047/177343774-4fef7fe1-30ae-4107-823f-d6150dd287b9.gif)

Expected output (using gifsave)
![gifsaveoutput](https://user-images.githubusercontent.com/108735047/177343917-568a939e-d70d-454d-8ada-04527e385fb9.gif)

[mask+intermediate.zip](https://github.com/libvips/libvips/files/9046882/mask%2Bintermediate.zip)

**Comment by talwinder-adv** [comment]
Thanks for the reply and explanation @jcupitt, do you know how mature is cgif compared to imagemagick?
Would you recommend switching to cgif instead?

**Comment by jcupitt** [comment]
I think it's fine -- it's a small library (only 1,000 lines of code) with a test suite, and it's fuzzed. Shopify (for example) use cgif for GIF write with libvips.

The upcoming libvips 8.13 has a revised GIF saver that's improved again:

https://www.libvips.org/2022/05/28/What's-new-in-8.13.html
