### ISSUE TITLE
Compiling Vips with deprecated features disabled breaks pyvips

### ISSUE THREAD

**Issue by felixbuenemann** [libvips/libvips#2947]
If I compile Vips 8.13.0 with `--enable-deprecated-no` the resulting libvips crashes when importing pyvips.

The shortest test I have is:

```shell
pip3 install --user pyvips && python3 -c 'import pyvips'

(process:15908): GLib-CRITICAL **: 17:37:34.977: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(process:15908): GLib-CRITICAL **: 17:37:34.979: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
**
GLib-GObject:ERROR:gtype.c:2744:g_type_register_static: assertion failed: (static_quark_type_flags)
Aborted
```

I tested this with libvips compiled in an Amazon Linux 2 Docker container (public.ecr.aws/lambda/python:3.9) on x86_64 and arm64.

**Comment by kleisauke** [comment]
I could reproduce this using this Dockerfile:
<details>
   <summary>Dockerfile</summary>

```Dockerfile
FROM amazonlinux:2

RUN \
  yum update -y && \
  yum groupinstall -y "Development Tools" && \
  yum install -y \
    expat-devel \
    glib2-devel \
    lcms2-devel \
    libexif-devel \
    libgsf-devel \
    libjpeg-devel \
    libpng-devel \
    orc-devel \
    python3-devel \
    python3-pip \
    && \
  pip3 install meson ninja

RUN \
  curl -L https://github.com/libvips/libvips/releases/download/v8.13.0/vips-8.13.0.tar.gz | tar xz && \
  cd vips-8.13.0 && \
  meson setup build --prefix=/usr --buildtype=release -Ddeprecated=false -Dintrospection=false && \
  meson compile -C build && \
  meson install -C build

RUN \
  pip3 install --user pyvips && python3 -c 'import pyvips'

```
</details>

(removing the `-Ddeprecated=false` option would indeed make this error vanish)

But I could not reproduce it on my Fedora 36 PC. I tried building libvips with Meson and Autotools, using the `-Ddeprecated=false` and `--disable-deprecated` options respectively.

For now, I can recommend building libvips with the deprecated components enabled, or to install libvips via the package manager, for example:
<details>
   <summary>Dockerfile</summary>

```Dockerfile
FROM amazonlinux:2

RUN \
  yum update -y && \
  yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
  yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
  yum install -y yum-utils && \
  yum-config-manager --enable remi && \
  # https://github.com/remicollet/remirepo/issues/169
  sed -i '/^\[remi-safe\]/a\priority=10' /etc/yum.repos.d/remi-safe.repo && \
  yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
  yum install -y --setopt=tsflags=nodocs \
    gcc-c++ \
    python3-devel \
    python3-pip \
    vips-devel \
    vips-heif \
    vips-magick-im6 \
    vips-poppler

RUN \
  pip3 install --user pyvips && python3 -c 'import pyvips'
```
</details>

(see https://github.com/libvips/libvips/issues/1184#issuecomment-447973135 for details)

**Comment by kleisauke** [comment]
Looks like this was regressed by commit https://github.com/libvips/libvips/commit/fa6c034b325eafcb9e6f6b3dc00244ac040c744f somehow. It seems [`gobject_init()`](https://github.com/GNOME/glib/blob/2.56.1/gobject/gtype.c#L4360) is never called causing [`g_assert_type_system_initialized()`](https://github.com/GNOME/glib/blob/2.56.1/gobject/gtype.c#L139-L140) to fail.

I still don't know why this only manifests when disabling deprecated components and why I can't reproduce this locally. As a temporary workaround, you could do:
```bash
$ sed -i '/link_args: nodelete_link_args,/d' libvips/meson.build 
```

Just before `meson setup build ...`. Note that this only affects the API mode of pyvips, ABI mode is fine.

**Comment by kleisauke** [comment]
Commit https://github.com/kleisauke/pyvips/commit/57918d9bf6b31f19837151d8d5370d3ae8607d4c seems to fix this. This can be tested with:
```bash
$ pip3 install --user git+https://github.com//kleisauke/pyvips.git@remove-deprecated-symbols
```

AFAIK, these functions were only used by libvips' test suite, so it's probably safe to remove it.
https://github.com/libvips/libvips/blob/87fbafaebe713d35fef1c4b8913c2cadf3cd5e95/test/test-suite/test_iofuncs.py#L12-L16

@jcupitt Should I open a PR for this on the pyvips repository? Hopefully the `@pytest.mark.xfail` would still work if these functions are removed. After that, we can just remove that test for 8.14.

**Comment by felixbuenemann** [comment]
@kleisauke Thanks, your pyvips fix works.

I think your Fedora PC might be using pyvips API mode, it only crashes in ABI mode.

I'll leave this open for @jcupitt to figure out the testing issue.

**Comment by kleisauke** [comment]
It seems that on Amazon Linux 2 `-Wl,-z,nodelete` causes the runtime linker to keep libvips open, even when undefined symbols are found (i.e., `vips_path_mode7` and `vips_path_filename7`). When CFFI falls-back to ABI mode at runtime, `vips_init()` is called on the already opened shared libvips library, causing the `static_quark_type_flags` assertion to fail since the GLib type system is never initialized.

Debug reproduction:
```bash
$ pip3 install --user pyvips && \
  LD_DEBUG=files python3 -c 'import pyvips' 2>&1 | awk '{$1=""; print $0}' | grep '_libvips.abi3.so\|libgobject-2.0.so.0\|libvips.so.42' | grep -v 'needed by'
```

<details>
  <summary>Log on F36</summary>

```
file=/home/kleisauke/.local/lib/python3.10/site-packages/_libvips.abi3.so [0]; dynamically loaded by /lib64/libpython3.10.so.1.0 [0]
file=/home/kleisauke/.local/lib/python3.10/site-packages/_libvips.abi3.so [0]; generating link map
file=libvips.so.42 [0]; generating link map
file=libgobject-2.0.so.0 [0]; generating link map
/home/kleisauke/.local/lib/python3.10/site-packages/_libvips.abi3.so: error: symbol lookup error: undefined symbol: vips_path_mode7 (fatal)
file=/home/kleisauke/.local/lib/python3.10/site-packages/_libvips.abi3.so [0]; destroying link map
file=/lib64/libvips.so.42 [0]; destroying link map
file=/lib64/libgobject-2.0.so.0 [0]; destroying link map
file=libgobject-2.0.so.0 [0]; dynamically loaded by /usr/lib64/python3.10/site-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so [0]
file=libgobject-2.0.so.0 [0]; generating link map
activating NODELETE for /lib64/libgobject-2.0.so.0 [0]
calling init: /lib64/libgobject-2.0.so.0
opening file=/lib64/libgobject-2.0.so.0 [0]; direct_opencount=1
file=libvips.so.42 [0]; dynamically loaded by /usr/lib64/python3.10/site-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so [0]
file=libvips.so.42 [0]; generating link map
activating NODELETE for /lib64/libvips.so.42 [0]
calling init: /lib64/libvips.so.42
opening file=/lib64/libvips.so.42 [0]; direct_opencount=1
calling fini: /lib64/libvips.so.42 [0]
calling fini: /lib64/libgobject-2.0.so.0 [0]

```
</details>

<details>
  <summary>Log on AMZN2</summary>

```
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; dynamically loaded by /lib64/libpython3.7m.so.1.0 [0]
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; generating link map
file=libvips.so.42 [0]; generating link map
file=libgobject-2.0.so.0 [0]; generating link map
/root/.local/lib/python3.7/site-packages/_libvips.abi3.so: error: symbol lookup error: undefined symbol: vips_path_filename7 (fatal)
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; destroying link map
opening file=/lib64/libgobject-2.0.so.0 [0]; direct_opencount=1
opening file=/lib64/libvips.so.42 [0]; direct_opencount=1
```
</details>

<details>
  <summary>Log on AMZN2 w/o nodelete</summary>

```
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; dynamically loaded by /lib64/libpython3.7m.so.1.0 [0]
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; generating link map
file=libvips.so.42 [0]; generating link map
file=libgobject-2.0.so.0 [0]; generating link map
/root/.local/lib/python3.7/site-packages/_libvips.abi3.so: error: symbol lookup error: undefined symbol: vips_path_filename7 (fatal)
file=/root/.local/lib/python3.7/site-packages/_libvips.abi3.so [0]; destroying link map
file=/lib64/libvips.so.42 [0]; destroying link map
opening file=/lib64/libgobject-2.0.so.0 [0]; direct_opencount=1
file=libvips.so.42 [0]; dynamically loaded by /root/.local/lib/python3.7/site-packages/_cffi_backend.cpython-37m-x86_64-linux-gnu.so [0]
file=libvips.so.42 [0]; generating link map
calling init: /lib64/libgobject-2.0.so.0
calling init: /lib64/libvips.so.42
opening file=/lib64/libvips.so.42 [0]; direct_opencount=1
calling fini: /lib64/libvips.so.42 [0]
file=/lib64/libvips.so.42 [0]; destroying link map
calling fini: /lib64/libgobject-2.0.so.0 [0]
```
</details>

> I think your Fedora PC might be using pyvips API mode, it only crashes in ABI mode.

This is vice-versa, it only crashes in API mode (e.g., removing `/usr/lib64/pkgconfig/vips.pc` prior `pip3 install --user pyvips` also fixes this). Anyway, I'm glad you found this bug, because this would mean that building libvips without the deprecated components would always cause pyvips to fall-back to ABI mode, despite being built in API mode.

**Comment by jcupitt** [comment]
@kleisauke yes, I think those functions were part of a vips7 compatibility thing in the vips7 -> vips8 transition. We no longer support vips7-style option strings, so I agree they can go.

**Comment by kleisauke** [comment]
Great! I just opened PR https://github.com/libvips/pyvips/pull/341 and https://github.com/libvips/libvips/pull/2954 for this.

**Comment by jcupitt** [comment]
Good stuff! Thanks for reporting this, @felixbuenemann
