### ISSUE TITLE
```vips thumbnail``` always fails on warnings [8.13.x]

### ISSUE THREAD

**Issue by kstanikviacbs** [libvips/libvips#2973]
Based on my findings it seems like calling ```vips thumbnail``` with 8.13.x with images causing vips warnings leads to vips failing and stopping.  This was not the case before (8.12.x). Also - passing ```fail-on``` parameter to overwrite the default one:  (```none```) has no effect. 

Could it be considered a bug introduced somehow by that change: https://github.com/libvips/libvips/commit/f06c9f3bcffec2c9f09c8ca460ac534cc03c2188 or control over failing logic has changed in another way and I've missed that?

**Comment by jcupitt** [comment]
Hi @kstanikviacbs,

Ooof that's annoying, I thought we'd fixed this. I agree, it's not working properly, I see:

```
$ vips thumbnail broken.jpg[fail-on=warning] x.jpg 200 
(vips:1321105): VIPS-WARNING **: 09:57:54.589: read gave 2 warnings
(vips:1321105): VIPS-WARNING **: 09:57:54.589: VipsJpeg: Premature end of JPEG file
$ echo $?
0
```

I'll have a look.

**Comment by kstanikviacbs** [comment]
Thanks, I really appreciate the quick reaction.

**Comment by jcupitt** [comment]
Ah it's the thumbnail fail-on, as you guessed. You now need to set this at that level. Try:

```
$ vips thumbnail broken.jpg x.jpg 200 --fail-on warning

(vips:1325101): VIPS-WARNING **: 10:27:50.401: error in tile 0 x 96

(vips:1325101): VIPS-WARNING **: 10:27:50.401: error in tile 0 x 104

(vips:1325101): VIPS-WARNING **: 10:27:50.401: error in tile 0 x 30
VipsJpeg: Premature end of input file
error buffer: VipsJpeg: Premature end of input file
$ echo $?
1
```

**Comment by kstanikviacbs** [comment]
The thing is that no matter which ```fail-on``` I set I no longer get an image as an output while processing broken image, it's basically just empty file. Doing same with 8.12.x results with renderable image.

**Comment by jcupitt** [comment]
It's working for me. With this test JPG:

![nina](https://user-images.githubusercontent.com/580843/182366646-0f8edcdd-c0c5-4d86-a543-43edbf6502b2.jpg)

I see:

```
$ head -c 200000 nina.jpg > broken.jpg
$ rm x.jpg
$ vips --version
vips-8.13.1
$ vips thumbnail broken.jpg x.jpg 200 

(vips:1335612): VIPS-WARNING **: 12:44:14.553: read gave 2 warnings

(vips:1335612): VIPS-WARNING **: 12:44:14.553: VipsJpeg: Premature end of JPEG file

memory: high-water mark 4.64 MB
error buffer: VipsJpeg: Premature end of JPEG file
$ echo $?
0
```

And it writes:

![x](https://user-images.githubusercontent.com/580843/182366819-83d9ee4a-e874-401e-ad69-bd6d1a5b30e6.jpg)

**Comment by kstanikviacbs** [comment]
Sure thing, please give that one a try: ![corrupted](https://user-images.githubusercontent.com/72518394/182367091-592627ad-637e-4b92-a790-a7dfd4a91c5e.jpg)

**Comment by kstanikviacbs** [comment]
I started wondering if this has something to do with some changes introduced in handling  Huffman code errors which is the case for this one from above. Perhaps it might be related to libjpeg instead, right?

**Comment by jcupitt** [comment]
With your file I see:

```
$ vips copy broken.jpg x.jpg
VipsJpeg: Corrupt JPEG data: bad Huffman code
VipsJpeg: Corrupt JPEG data: bad Huffman code
```

So there's an error in the header, not in the pixel data. Without a header, there's not much libvips can do.

I wonder how firefox is displaying it? I suppose they have some extra code to fix up corrupt huffman codes.

**Comment by kstanikviacbs** [comment]
Interesting fact is that exactly the same image works with 8.12.x.

**Comment by kstanikviacbs** [comment]
Ok, there's one thing that's different, 8.12.2 treats it like a warning:
`$ vips -v
vips-8.12.2-Thu Feb 10 17:18:53 UTC 2022
 $ vips thumbnail corrupted.jpg test.jpg 200

(vips:15): VIPS-WARNING **: 11:53:19.198: read gave 39632 warnings

(vips:15): VIPS-WARNING **: 11:53:19.198: VipsJpeg: Corrupt JPEG data: bad Huffman code`

**Comment by jcupitt** [comment]
Ah, it's this change:

https://github.com/libvips/libvips/blob/master/libvips/foreign/jpeg2vips.c#L332-L333

ie. more than 100 warnings counts as an error. This change was needed to prevent a class of denial-of-service attack: you can make jpg decodes extremely slow (as in many, many minutes) by deliberately making a file which will trigger 10000s of warnings.

**Comment by jcupitt** [comment]
Here's the issue: https://github.com/libvips/libvips/issues/2749

**Comment by kstanikviacbs** [comment]
Ach, gotcha, thanks for clarification. Well, I'm afraid I need to adjust that parameter for my use case, it's not exposed to API in any way right? The only way to go for me would be to change it on my side and build from sources, correct?

**Comment by jcupitt** [comment]
Other loaders have an `unlimited` option to disable DoS limits, perhaps the JPEG loader should as well.

But yes, until we add it, you'll have to patch the sources yourself.

**Comment by kstanikviacbs** [comment]
Understood, thanks for all your support, this is really helpful. 

Would be great to have such option there as well at some point in the future. For the time being - I would discuss options with the team and potentially patch the sources by myself.

**Comment by jcupitt** [comment]
I had a few minutes, so I added `unlimited` to 8.13, this change will be in 8.13.1. We shouldn't add API in a stable branch, but I think this is necessary to fix a regression.

**Comment by jcupitt** [comment]
(and thanks for reporting this issue!)
