### ISSUE TITLE
Thumbnailing a JPEG2000 image result in a JPEG 2000 codestream

### ISSUE THREAD

**Issue by kaspergrubbe** [libvips/libvips#2977]
## Bug report

Hi!

I am not sure this is a bug or not, I might be misunderstanding the JPEG2000 format, but the results seems odd to me, sorry if this is expected behavior.

**To Reproduce**

1. Use Image [ernie-the-staffie.jp2.zip](https://github.com/libvips/libvips/files/9261616/ernie-the-staffie.jp2.zip)
2. Thumbnail the jp2 image: `vipsthumbnail ernie-the-staffie.jp2 --vips-info --size 40x -o 40.jp2`
3. Analyze the original image and the resulting image: `file ernie-the-staffie.jp2 && file 40.jp2`
4. Analyze the mimetype of the original image and the resulting image: `file --mime-type ernie-the-staffie.jp2 && file --mime-type 40.jp2`

**Expected behavior**
I would expect the resulting image to be the same filetype as the original.

**Actual behavior**

Thumbnailing:

```
$ vipsthumbnail ernie-the-staffie.jp2 --vips-info --size 40x -o 40.jp2
VIPS-INFO: 17:46:02.272: thumbnailing ernie-the-staffie.jp2
VIPS-INFO: 17:46:02.275: selected loader is VipsForeignLoadJp2kFile
VIPS-INFO: 17:46:02.275: input size is 500 x 500
VIPS-INFO: 17:46:02.281: loading with factor 3 pre-shrink
VIPS-INFO: 17:46:02.281: pre-shrunk size is 63 x 63
VIPS-INFO: 17:46:02.281: converting to processing space srgb
VIPS-INFO: 17:46:02.281: residual reducev by 0.634921
VIPS-INFO: 17:46:02.281: reducev: 11 point mask
VIPS-INFO: 17:46:02.285: reducev: using vector path
VIPS-INFO: 17:46:02.285: reducev sequential line cache
VIPS-INFO: 17:46:02.285: residual reduceh by 0.634921
VIPS-INFO: 17:46:02.285: reduceh: 11 point mask
VIPS-INFO: 17:46:02.285: converting to output space srgb
VIPS-INFO: 17:46:02.285: thumbnailing ernie-the-staffie.jp2 as ./40.jp2
```

Comparing filetypes:

```
$ file ernie-the-staffie.jp2 && file 40.jp2
ernie-the-staffie.jp2: JPEG 2000 Part 1 (JP2)
40.jp2: JPEG 2000 codestream
```

Comparing mimetypes:

```
$ file --mime-type ernie-the-staffie.jp2 && file --mime-type 40.jp2
ernie-the-staffie.jp2: image/jp2
40.jp2: application/octet-stream
```

**Environment**
 - OS: MacOS 12.5
 - Vips: vips-8.13.0

**Comment by jcupitt** [comment]
Hi @kaspergrubbe, I agree, this doesn't look right. Let's try to fix this in the 8.14 cycle.

**Comment by kaspergrubbe** [comment]
@jcupitt Thanks for having a look, I hope you're having a wonderful weekend! 🥇

**Comment by jcupitt** [comment]
OK, fixed in master. Thanks for pointing this out!

**Comment by kaspergrubbe** [comment]
Thank you! :)
