### ISSUE TITLE
Saving low bit depth PNG results in distorted image.

### ISSUE THREAD

**Issue by jeffska** [libvips/libvips#2985]
Saving a PNG with bitdepth < 8 results in a distorted image. See this example of a monochrome image saved at 1bpp:

![image](https://user-images.githubusercontent.com/1580906/184519503-389434e7-db09-4802-9dec-53ea21226d84.png)

The same occurs with bit depths of 2 and 4, but the distortions are smaller.

The cause seems to be the lack of a bit mask on the right side of the or operation on line 280 in spngsave.c

```c
        for( x = 0; x < n; x++ ) {
                bits <<= spng->bitdepth;
                bits |= p[x];


                if( (x & pixel_mask) == pixel_mask )
                        *q++ = bits;
        }
```

**Comment by jcupitt** [comment]
Hi @jeffska,

Oh dear, that's bad. I can't reproduce this though -- with libspng enabled and these commands:

```
$ vips text x.v A --dpi 600
$ vips relational_const x.v x2.v more 128
$ vips copy x2.v x.png[bitdepth=1]
```

I see:

![x](https://user-images.githubusercontent.com/580843/184530325-088b0e4e-0d5b-40da-8946-d0cff8a24a60.png)

Regular libpng seems to work too.

Could this be related to your hardware platform? I'm testing on amd x64. Maybe it's a signed/unsigned issue?

**Comment by jcupitt** [comment]
Ah I found a missing shift, it looks like maybe a copy-paste brainfart when adapting the code from the tiff saver.

Thanks for the report! I've credited you in the changelog.

**Comment by jeffska** [comment]
Good deal, thank you. When I get a bit of time I'll try to get the Docker-based dev. environment spun up so I can just to a PR next time.
