### ISSUE TITLE
`vips_image_wio_input` fails with `jxlload: error JxlDecoderProcessInput` for JXL input 

### ISSUE THREAD

**Issue by gurpreetg** [libvips/libvips#3005]
👋 I noticed that `vips_image_wio_input` doesn't seem to work with JPEG-XL. Here is a program to reproduce the issue
```
#include <stdio.h>
#include <vips/vips.h>

int main( int argc, char **argv )
{
  if( VIPS_INIT( "jxlwioinput" ) )
    vips_error_exit( NULL ); 

  vips_cache_set_max(0);

  VipsImage *in;

  char* filename = argv[1];

  if( !(in = vips_image_new_from_file(filename, "access", VIPS_ACCESS_SEQUENTIAL, NULL )) )
    vips_error_exit( NULL );

  if (vips_image_wio_input(in)) {
    vips_error_exit("failed wio_input"); 
  }

  return( 0 );
}
```

**Output**
```
➜  ./jxlwioinput ~/Downloads/sample_image.jxl
jxlwioinput: failed wio_input
jxlload: error JxlDecoderProcessInput
```

**Sample Image**

JXL: [sample_image.jxl.zip](https://github.com/libvips/libvips/files/9395790/sample_image.jxl.zip)

I ran `cjxl source_for_jxl.jpg sample_image.jxl --quality=90` to generate `sample_image.jxl` from `source_for_jxl.jpg`

_source_for_jxl.jpg_
![source_for_jxl](https://user-images.githubusercontent.com/8185304/185964432-c0ba7033-5ed0-45b3-b18e-8a6b1cce05f4.jpg)

**Comment by jcupitt** [comment]
Hi @gurpreetg,

It's working with git master libvips plus libjxl 0.7:

```C
/* compile with
 *
 *      gcc -g -Wall wio.c `pkg-config vips --cflags --libs`
 */
 
#include <vips/vips.h>

int
main( int argc, char **argv )
{       
        if( VIPS_INIT( argv[0] ) )
                return( -1 );

        VipsImage *in;

        if( !(in = vips_image_new_from_file( argv[1], 
                "access", VIPS_ACCESS_SEQUENTIAL, 
                NULL )) )
                vips_error_exit( NULL );

        if( vips_image_wio_input( in ) )
                vips_error_exit( NULL );

        printf( "success, pixels at %p\n", in->data );

        g_object_unref( in );

        vips_shutdown();

        return( 0 );
}
```

I see:

```
$ gcc -g -Wall wio.c `pkg-config vips --cflags --libs`
$ ./a.out ~/pics/k2.jxl
WARNING: CPU supports 1a00 but software requires 2000000000000000
success, pixels at 0x7f06bdf60020
memory: high-water mark 17.26 MB
```

I think the warning is a highway bug that didn't get fixed in 1.0.0.

**Comment by jcupitt** [comment]
Its working with libvips 8.13 plus libjxl 0.7 as well, if that's any help.

**Comment by jcupitt** [comment]
This is also working with libvips 8.13 and libjxl 0.6.1.

I think you must have an older version of libjxl or libvips. I would update to current stable. Please reopen if this is strill broken.
