### ISSUE TITLE
Link failure with i686 MinGW on Linux

### ISSUE THREAD

**Issue by alucryd** [libvips/libvips#3012]
## Bug report

**Describe the bug**
Trying to build a standalone windows DLL on linux fails at link time with i686 MinGW with a bunch of undefined references. The same build in exactly the same conditions works fine with x86_64 MinGW (and also for a whole bunch of cross linux and android targets).

**To Reproduce**
Build static versions of the following using MinGW:
- cgif
- libexif
- glib2
- libheif
- libimagequant
- libjpeg-turbo
- libjxl
- libopenexr
- libopenjpeg
- orc
- pango
- libpng
- libtiff
- libwebp
- zlib
Then build libvips with these features enabled.

**Expected behavior**
The libvips DLL shoud link correctly.

**Actual behavior**
The libvips fails to link due to undefined references, despite all libraries being present in the link command.

**Environment**
 - OS: Arch Linux
 - Vips: 8.13.0

**Additional context**

i686 log: https://paste.xinu.at/x6Gjfd2WoMXYpcN8/
x86_64 log: https://paste.xinu.at/tXff2BFjBoY5irG1/

**Comment by jcupitt** [comment]
Hi @alucryd,

Sorry, no idea. I suppose there's a problem with the way you've built lcms and openjpeg, but you've not given enough information for me to able able to tell.

I guess you've seen the mxe build system Kleis made?

https://github.com/libvips/build-win64-mxe

It builds static and dynamic libvips for native windows x86_64, i686, aarch64 and armv7, and you can pick which packages you'd like to include.

**Comment by alucryd** [comment]
Thanks for the swift reply. It's highly unlikely that lcms and openjpeg are incorrectly built, libvips and all dependencies are built exactly the same way for i686 and x86_64, the only difference is the toolchain prefix, which is why I'm at a loss. I have 50+ libraries built with these toolchains, everything is as code using a custom buildbot, and this is the first time I've run into a discrepancy between i686 and x86_64.

Thank you for the links, I'll have a look.

I'll keep investigating, I'm happy to provide any additional information, I have easy access to all the build logs every step of the way.

**Comment by kleisauke** [comment]
From the linker errors, it looks like a x86 calling convention mismatch, specifically `__stdcall` versus `__cdecl`. Was OpenJPEG build with CMake? If so, could you try to apply this patch?:
https://github.com/mxe/mxe/blob/52533413b0f41ce09db5a685b70010f8514cdff8/src/openjpeg-1-fixes.patch

That makes `libopenjp2.pc` aware of the `lcms2` dependency and ensures that it defines `OPJ_STATIC` when building statically linked libraries, which in turn prevents it from using the `__stdcall` calling convention and `__declspec(dll{ex,im}port)` attributes - see:
https://github.com/uclouvain/openjpeg/blob/be95561917aa9b1d8ea4614820a534917cfa6bbe/src/lib/openjp2/openjpeg.h#L85-L114

**Comment by alucryd** [comment]
@kleisauke Yes, it was built with cmake. Will give the patch a try, thank you very much.

**Comment by alucryd** [comment]
@kleisauke Passing `-DOPJ_STATIC` fixed the openjpeg link errors, thanks! Only lcms remains, I tried patching it to define `CMSEXPORT` and `CMSAPI` to blank, but that didn't help. Opened an issue upstream: https://github.com/mm2/Little-CMS/issues/334
