### ISSUE TITLE
Suggestion because handling of write_to_target has changed for PBM/PGM/PPM files

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#3016]
I just came across some inconsistency between different versions of libvips: Using pyvips with older libvips version 8.10.6 the function write_to_target(target, **".ppm"**) on a single-band image creates a PGM image as expected (from input image data point of view). But using newer versions of libvips - e.g. version 8.12.1 (as in Ubuntu 22.04) - will create a 3-band PPM image.

The old behaviour has some advantage because it keeps the number of image bands unchanged on output. Using the new version any program would have to deal with different cases depending on image data you would like to save and choose appropriate parameters in write_to_target(), e.g. in the former case I should have used write_to_target(target, **".pgm"**) instead.

On the other hand, the new behaviour is more strict on interpretation of the output file format. Specifying ".ppm" would alway create a 3-band PPM image which is not a bad idea either.

To suit both aspects - and reduce the work of the programmer :) - it might be convenient to keep the old behaviour e.g. by adding a write_to_target(target, **".pnm"**) which could create the most appropriate output image format being either of PBM/PGM/PPM. The name PNM is used by netpbm exactly for that reason and described there as "portable anymap file format".

Thomas

**Comment by jcupitt** [comment]
Hi @ewelot,

You can set the format explicitly, eg.:

```
vips copy k2.jpg x.ppm[format=pgm]
```

So even though the image is RGB and you are saving to a PPM file, it will be converted to mono and saved as PGM. 

I like the PNM idea, let's make this an enhancement.

**Comment by jcupitt** [comment]
I had a moment,  it seems to work. Thanks for the idea!
