### ISSUE TITLE
How to render text using fallback fonts?

### ISSUE THREAD

**Issue by HexCodeFFF** [libvips/libvips#3023]
I have a standard text font and a separate emoji font that I want to use to render dynamic/user-generated text. I'm using PyVips on Windows and I can't even get it to load fonts from a file let alone multiple. If using fallback fonts/combining fonts isn't possible in vips, consider this a feature request. vips uses Pango to render text which does support fallback fonts so it shouldn't be too complex

**Comment by HexCodeFFF** [comment]
Ok so I figured out fonts can be given fallbacks by comma-separating them in the `font` field but the same doesn't appear to be the same of the `fontfile` field which is what I want

**Comment by jcupitt** [comment]
Hi @HexCodeFFF,

You can load multiple font files, would that solve your problem? During startup, call `text()` once for each font you want to load.

**Comment by HexCodeFFF** [comment]
oh really? I genuinely gave up and [forked the repo](https://github.com/HexCodeFFF/libvips-multifont) and [hacked in a way to load multiple fonts](https://github.com/HexCodeFFF/libvips-multifont/blob/8962b6dbb7f35116460d6dbee2aa4225463f59a3/libvips/create/text.c#L371-L397)
I'll test your suggestion because yes loading multiple font files would solve my problem

**Comment by HexCodeFFF** [comment]
I'm unable to test it because i'm using pyvips and I can't figure out how to add an operation to a pyvips pipeline without using the result of it.

**Comment by jcupitt** [comment]
I’ve not actually tested it, and fontconfig behaviour might vary across
platforms, but from memory I think it’d work.

**Comment by jcupitt** [comment]
Yes, loading several fonts seems to work, on linux anyway. I see:

```
$ python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.text("hello", font="MissFajardose Regular 50")
>>> x.write_to_file("x.png")
```

I get some helvetica text. If I then run:

```
>>> x = pyvips.Image.text("x", fontfile="MissFajardose-Regular.ttf")
>>> x = pyvips.Image.text("world", font="MissFajardose Regular 50")
>>> x.write_to_file("x.png")
>>> 
```

I now get the fancy font.

**Comment by HexCodeFFF** [comment]
it works on windows! definitely a janky fix but if it works it works haha
as previously mentioned, [I did create a way to load multiple fonts at once](https://github.com/HexCodeFFF/libvips-multifont/blob/8962b6dbb7f35116460d6dbee2aa4225463f59a3/libvips/create/text.c#L371-L397) in a fork by splitting the font files by a delimiter (I used `\n`). if you'd like me to make a pull to merge this just let me know

**Comment by jcupitt** [comment]
I read your patch, but I'm not sure it's necessary. How about adding a note to the docs explaining `fontfile` behaviour in more detail? That would probably be simpler.

**Comment by HexCodeFFF** [comment]
The reasoning behind my patch is that the multiple calls to text() would waste time actually rendering out the placeholder text and in my experience throw an exception when given no text. I do think text()'s treatment of fonts does need better documentation regardless

**Comment by AndreKR** [comment]
I came here because I also wondered how to load multiple fonts. The "rendering a text for the side effect of loading a font" method feels very hacky and I'd appreciate if @HexCodeFFF's patch would find its way into libvips. I'm using libvips through [sharp](https://github.com/lovell/sharp) by the way.

**Comment by reticivis-net** [comment]
> Yes, loading several fonts seems to work, on linux anyway. I see:
> 
> ```
> $ python3
> Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyvips
> >>> x = pyvips.Image.text("hello", font="MissFajardose Regular 50")
> >>> x.write_to_file("x.png")
> ```
> 
> I get some helvetica text. If I then run:
> 
> ```
> >>> x = pyvips.Image.text("x", fontfile="MissFajardose-Regular.ttf")
> >>> x = pyvips.Image.text("world", font="MissFajardose Regular 50")
> >>> x.write_to_file("x.png")
> >>> 
> ```
> 
> I now get the fancy font.

Coming back to this ages later, it works on linux but not on windows for some reason
