### ISSUE TITLE
Shrink modes that pick the same value across all bands

### ISSUE THREAD

**Issue by manthey** [libvips/libvips#3030]
The `VIPS_REGION_SHRINK_*` options pick one of four pixels for each band, but it could be a different pixel on each band.  For instance, `VIPS_REGION_SHRINK_MODE` might pick the upper-left pixel of band 0 and the upper-right pixel of band 1.  It would be desirable in some instances to have a shrink mode (other than NEAREST) which always picks the same pixel across all bands.

This could probably be done via something like (for mode)
```
                TYPE v[] = {0, 0, 0, 0}; \
                for( z = 0; z < nb; z++ ) { \
                        v[0] += tp[z]; \
                        v[1] += tp[z + nb]; \
                        v[2] += tp1[z]; \
                        v[3] += tp1[z + nb]; \
                } \
                int b0 = (v[0] == v[1]) | \
                        (v[0] == v[2]) | \
                        (v[0] == v[3]); \
                int b1 = (v[1] == v[0]) | \
                        (v[1] == v[2]) | \
                        (v[1] == v[3]); \
                int index = ((~b0) & 0x1) + (~(b0 ^ b1) & 0x1); \
                \
                for( z = 0; z < nb; z++ ) { \
                        TYPE v[] = {tp[z], tp[z + nb], tp1[z], tp1[z + nb]}; \
                        tq[z] = v[index]; \
                } \
```
(note -- I didn't actually try this code), where the index is computed for all bands via some method, then used for all bands.  This could do something for MODE, MEDIAN, MAX, and MIN.  We'd have to add new constants (`VIPS_REGION_SHRINK_*_ALL_BANDS`?)

For the initial collation of values for all bands, adding the bands together is probably the wrong approach.  For min and max it could be those functions, for median and mode I'm not sure what a cheap function would be.  Obviously, something like max across bands doesn't really make sense (e.g., how do you pick the max of [0, 1] and [1, 0] or, more complexly, [3, 0, 0] and [0, 2, 2]), but picking a consistent pixel across bands means the output pixel is actually one of the input pixels.

Is this worth adding?  If so, I could make a PR.  If not, feel free to close the issue.

**Comment by jcupitt** [comment]
Hi @manthey,

The MAX, MODE etc. things for shrink went in to support pyramids of label images. For example, images that come out of classifiers use perhaps index 1 for trees, index 2 for grassland, index 3 for water. During a shrink, it makes no sense to average labels, so you have to use something else to reduce aliasing.

Maybe you could use a palette? Could you turn your many-band image into a one-band image plus a colour look up table?

**Comment by manthey** [comment]
Yes, I can use a palette.  I think I'm convinced this isn't a good idea.  Thank you.
