### ISSUE TITLE
Segfault when using AVIF conversion and sharpen together

### ISSUE THREAD

**Issue by adityapatadia** [libvips/libvips#3039]
Please check https://github.com/lovell/sharp/issues/3358 for more information on this. I have provided steps to reproduce it with Nodejs.

In a nutshell, AVIF output when used with sharpen operation results in immediate segfault in 8.13. Everything was working fine until 8.12.

**Comment by kleisauke** [comment]
Please don't cross-post, it makes unnecessary extra work. Answered here: https://github.com/lovell/sharp/issues/3358#issuecomment-1242779068.

**Comment by adityapatadia** [comment]
Okay I will close this one. Let's track it there.
