### ISSUE TITLE
vipsheader -a stdin segfaults on filename

### ISSUE THREAD

**Issue by pclewis** [libvips/libvips#3043]
## Bug report

**Describe the bug**
`vipsheader -a stdin` segfaults when it gets to filename

**To Reproduce**
1. `vips text .png hi | vipsheader -a stdin`

**Expected behavior**
```
10x10 uchar, 1 band, b-w, pngload
...
yres: 2.835
filename: {stdin, NULL, or just omitted}
vips-loader: pngload
vips-sequential: 1
```

**Actual behavior**
```
10x10 uchar, 1 band, b-w, pngload_source
...
yres: 2.835
Segmentation fault (core dumped)
```

**Environment**
 - OS: Linux, Windows
 - Vips: 8.13.0, 8.13.1

**Additional context**
`vips text .png hi | vipsheader -f filename stdin` prints "NULL" and doesn't crash

**Comment by jcupitt** [comment]
Ooop! Thanks for reporting this @pclewis. Fixed in git master and 8.13.
