### ISSUE TITLE
Cannot build 8.13.1, but works fine if i switch to 8.13.0

### ISSUE THREAD

**Issue by hanssonrickard** [libvips/libvips#3059]
I am trying to build libvips 8.13.1 on Almalinux 8.6 (basically Redhat 8.6) and i get error message.
But if i change to 8.13.0 it works perfectly fine.

Here is the error message i get during compile:

#9 14.01 [14/492] Compiling C object libvips/foreign/libforeign.a.p/dzsave.c.o
#9 14.01 FAILED: libvips/foreign/libforeign.a.p/dzsave.c.o 
#9 14.01 cc -Ilibvips/foreign/libforeign.a.p -Ilibvips/foreign -I../libvips/foreign -I. -I.. -Ilibvips/include -I../libvips/include -Ilibvips/include/vips -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/cfitsio -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/OpenEXR -I/usr/include/orc-0.4 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -DDEBUG_LEAK -fPIC -DHAVE_CONFIG_H=1 -pthread -D_REENTRANT -MD -MQ libvips/foreign/libforeign.a.p/dzsave.c.o -MF libvips/foreign/libforeign.a.p/dzsave.c.o.d -o libvips/foreign/libforeign.a.p/dzsave.c.o -c ../libvips/foreign/dzsave.c
#9 14.01 ../libvips/foreign/dzsave.c: In function ‘gsf_output_dir_new_valist’:
#9 14.01 ../libvips/foreign/dzsave.c:345:36: error: ‘errno’ undeclared (first use in this function)
#9 14.01   if( g_mkdir( root, 0777 ) != 0 && errno != EEXIST ) {
#9 14.01                                     ^~~~~
#9 14.01 ../libvips/foreign/dzsave.c:345:36: note: ‘errno’ is defined in header ‘<errno.h>’; did you forget to ‘#include <errno.h>’?
#9 14.01 ../libvips/foreign/dzsave.c:191:1:
#9 14.01 +#include <errno.h>
#9 14.01  #pragma GCC diagnostic pop
#9 14.01 ../libvips/foreign/dzsave.c:345:36:
#9 14.01   if( g_mkdir( root, 0777 ) != 0 && errno != EEXIST ) {
#9 14.01                                     ^~~~~
#9 14.01 ../libvips/foreign/dzsave.c:345:36: note: each undeclared identifier is reported only once for each function it appears in
#9 14.01 ../libvips/foreign/dzsave.c:345:45: error: ‘EEXIST’ undeclared (first use in this function); did you mean ‘ATEXIT’?
#9 14.01   if( g_mkdir( root, 0777 ) != 0 && errno != EEXIST ) {
#9 14.01                                              ^~~~~~
#9 14.01                                              ATEXIT
#9 14.13 [15/492] Compiling C object libvips/foreign/libforeign.a.p/exif.c.o
#9 14.13 [16/492] Compiling C object libvips/foreign/libforeign.a.p/fitsload.c.o
#9 14.14 [17/492] Compiling C object libvips/foreign/libforeign.a.p/jp2kload.c.o
#9 14.17 [18/492] Compiling C object libvips/foreign/libforeign.a.p/jp2ksave.c.o
#9 14.19 [19/492] Generating enumtypes.c with a custom command (wrapped by meson to capture output)
#9 14.22 [20/492] Compiling C object libvips/foreign/libforeign.a.p/jpeg2vips.c.o
#9 14.22 [21/492] Compiling C object libvips/foreign/libforeign.a.p/jpegload.c.o
#9 14.22 [22/492] Compiling C object libvips/foreign/libforeign.a.p/fitssave.c.o
#9 14.25 [23/492] Compiling C object libvips/foreign/libforeign.a.p/foreign.c.o
#9 14.25 ninja: build stopped: subcommand failed.

-------

The following package is installed for libgsf-devel (name, version, repo):

libgsf-devel.x86_64                        1.14.41-5.el8                        powertools

Tell me if you need any other/more information from my side.

**Comment by hanssonrickard** [comment]
Attached is the Dockerfile i use to perform the build, in case you wish to try to replicate the problem.

[Dockerfile.zip](https://github.com/libvips/libvips/files/9629196/Dockerfile.zip)

**Comment by jcupitt** [comment]
I think there was a slight regression in 8.13.1. Could you try the head of the 8.13 branch? It should have a fix.

**Comment by hanssonrickard** [comment]
Thanks.
I cloned the 8.13 branch and it worked with that one (could see in the changelog that there was a fix specifically for this issue).
