### ISSUE TITLE
Embedded ICC profile is lost and image loses saturation when encoding Display P3 image to PNG

### ISSUE THREAD

**Issue by AttilaTheFun** [libvips/libvips#3075]
## Bug report

**Describe the bug**

I've observed an issue where when I load an image with an embedded Display P3 ICC profile, when I export the image to a PNG  it loses saturation and reverts to an sRGB profile. The same image when written to a JPEG correctly embeds the Display P3 profile and does not lose saturation.

Note that I'm using libvips via the govips bindings and I'm not sure if this is an issue with how the wrapper library is using exporting PNGs or an issue with libvips itself, but the relevant code that calls into vips to export the PNG should be here:
https://github.com/davidbyttow/govips/blob/19c388d12dab283becd7068b7a134740c18216b6/vips/foreign.c

**To Reproduce**

1. Decode the attached, original Display P3 PNG image with libvips.
2. Export a JPEG and verify that the Display P3 profile is embedded and the image has retained its saturation.
3. Export a PNG and verify that the Display P3 profile has been replaced with an sRGB profile and the image has lost saturation.

**Expected behavior**

When I decode and then encode a PNG with an embedded ICC profile this should be preserved.
Also if I use the icc_transform API, the exported PNG should have the new, embedded ICC profile in it.

**Actual behavior**

VIPS works as expected with JPEG images but PNGs lose the embedded Display P3 profile.

**Screenshots**

Input PNG with Display P3 profile:
![Display P3](https://user-images.githubusercontent.com/3255391/193468789-787fd8b4-6b82-4b72-948f-b14ddf626998.png)

On a Mac you can run the following commands to extract the ICC profile and get its name:
```
logan@Logans-MacBook-Pro InputImages % sips -x ExtractedProfile.icc Display\ P3.png 
/Users/logan/Developer/TestImages/InputImages/Display P3.png
logan@Logans-MacBook-Pro InputImages % sips -g description ExtractedProfile.icc
/Users/logan/Developer/TestImages/InputImages/ExtractedProfile.icc
  description: Display P3
```

Output PNG with missing / incorrect Display P3 profile:
![Display P3 Encoded to Display P3](https://user-images.githubusercontent.com/3255391/193468919-42005184-c782-432e-bfb0-837570316248.png)

Running the same commands again you can see that this one has the  sRGB IEC61966-2.1 profile not Display P3:
```
logan@Logans-MacBook-Pro OutputImages % sips -x ExtractedProfile.icc Display\ P3\ Encoded\ to\ Display\ P3.png
/Users/logan/Developer/TestImages/OutputImages/Display P3 Encoded to Display P3.png
logan@Logans-MacBook-Pro OutputImages % sips -g description ExtractedProfile.icc                              
/Users/logan/Developer/TestImages/OutputImages/ExtractedProfile.icc
  description: sRGB IEC61966-2.1
```

**Environment**

I'm using libvips through the govips bindings, testing locally on my M1 Max MacBook Pro.
My installed vips version is 8.13.0.

**Comment by lovell** [comment]
Cross-posted at https://github.com/davidbyttow/govips/issues/308

**Comment by jcupitt** [comment]
Hi @AttilaTheFun,

Please don't cross-post bug reports. It makes extra, unnecessary, duplicate work for volunteer maintainers.

This bug was fixed in 8.13.2, so updating your libvips should fix it.

**Comment by AttilaTheFun** [comment]
Ah okay, sorry about that @jcupitt. I wasn't sure which side the bug was on but in the future I'll just make one report here and only open one on the bindings once we've ruled it out on the vips side. I'll close the other bug report now.

Re: 8.13.2, I installed vips locally via homebrew and the current stable version there is 8.13.1:
https://formulae.brew.sh/formula/vips
Do you plan on pushing 8.13.2 to home-brew as well?

**Comment by jcupitt** [comment]
Anyone can update homebrew, someone just has to get around to making a PR. If you have a moment, it'd save me 30 minutes of firing up an elderly mac.

**Comment by AttilaTheFun** [comment]
Sure thing! I can figure that out today.
