### ISSUE TITLE
Custom dzsave output filename

### ISSUE THREAD

**Issue by ouzhou** [libvips/libvips#3091]
this output file alway start with indexs 0,0
```
vips dzsave wtc.tif gmapdir --layout google
```

i want to custom output file name like this imagemagick command line code , my start index is 23,12
```
	convert "$input" \
		-monitor \
		+gravity \
		-crop 256x256 \
		-set filename:tile "%[fx:page.x/256+23]_%[fx:page.y/256+12]" \
		+repage +adjoin \
		"${base}5_%[filename:tile].png"
```

**Comment by lovell** [comment]
You've already asked this at https://github.com/lovell/sharp/issues/3405 so let's continue there rather than cross-post.
