### ISSUE TITLE
gifload: increased memory usage for huge single frame GIFs

### ISSUE THREAD

**Issue by dloebl** [libvips/libvips#3092]
Recently, we faced an issue concerning the memory usage when loading single frame GIFs with huge source dimensions:
[example.gif](https://user-images.githubusercontent.com/34104349/195308149-cdf56ac7-9236-47ea-9b39-12942e98b321.gif)
```
$ vipsheader example.gif
example.gif: 65535x65535 uchar, 3 bands, srgb, gifload
```

Loading the GIF can lead to a maximum memory usage of well above 16GB:
```
$ vips gifload example.gif out.png

(vips:3042): GLib-ERROR **: 11:50:58.032: ../glib/glib/gmem.c:169: failed to allocate 17179344900 bytes
Trace/breakpoint trap (core dumped)
```

It looks like `gifload` has to keep a complete RGBA frame in memory. I can see why `gifload`/`libnsgif` has to keep parts of the image in memory for animated GIFs - for area blending I guess, but are there ways to improve the memory usage when loading single frame GIFs?

**Comment by jcupitt** [comment]
Hi @dloebl,

libnsgif always loads the entire source file into memory, and always keeps a couple of frames of the decompressed animation. It originally came from a web browser, so you can imagine it's pretty focussed on screen-size images.

I tried here (this PC has a lot of memory):

```
$ /usr/bin/time -f %M:%e vips copy huge.gif x.tif[tile,compression=jpeg]
memory: high-water mark 997.11 MB
17844832:40.10
```

So about 18gb of malloc and 1gb of pixel buffers.

A sort-of workaround would be to open the image and check the dimensions (this is quick and doesn't need much memory), then ban crazy GIFs.

**Comment by jcupitt** [comment]
@tlsa can I ping you on this? 

I suppose it might be possible for libnsgif to add API like eg. `nsgif_line_decode()` to fetch a single line of decompressed pixels. Would there be any interest in this from your side? It's an extreme corner case, so I can imagine it not being very relevant to your needs.

**Comment by tlsa** [comment]
> I suppose it might be possible for libnsgif to add API like eg. `nsgif_line_decode()` to fetch a single line of decompressed pixels.

Maybe, so long as the `nsgif_line_decode()` can return which line it has decoded as well as the decoded data (to handle interlacing).

> Would there be any interest in this from your side? It's an extreme corner case, so I can imagine it not being very relevant to your needs.

I've not been thinking about that codebase for a while, so I'd have to look into it to see how much work it would be. At a guess it would take quite a bit of refactoring.

**Comment by jcupitt** [comment]
Thank you!

I don't think there's anything easy we can do to improve this. Probably checking dimensions and banning huge GIFs is the best thing, eg.:

```python
image = pyvips.Image.new_from_file("huge.gif")
# ban images that would need more than 1gb of ram to decode
if image.width * image.height * 4 > 1000000000:
    raise Exception("image too large")
```
