### ISSUE TITLE
Unexpected size limit on number of image bands (maybe FITS only?)

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#3114]
FITS cubes are often used when imaging a given astronomical target with multiple filters (e.g. RGB) or when capturing (monochrome) time series. In the latter use case the cube might contain many thousands of images. The FITS cube header keywords NAXIS1 and NAXIS2 describe the x-y-dimensions of each image, while NAXIS3 corresponds to the number of images (bands).

Unfortunately vips failed to process images containing many bands. I can load and process (e.g. using avg) a cube of NAXIS1xNAXIS2xNAXIS3 = 184x164x1020 pixels but fails to process 184x164x1021 pixels. Note that the maximum number of bands depends on the function invoked, e.g. it is somewhat lower for fitssave() compared to avg().

Is there a (hidden) limit on the number of bands somewhere?
Is there a reason for this?

Thanks,
Thomas

**Comment by ewelot** [comment]
Forgot to mention that I have been using pyvips 2.1.14 and libvips 8.10.6 for the tests but found (similar or identical) problems using current versions pyvips 2.2.1 and libvips 8.13.2. The test program is as simple as
```
#!/usr/bin/python3

import sys
import pyvips

inimg = pyvips.Image.new_from_file(sys.argv[1])
print("bands=", inimg.bands)
print("avg=  ", inimg.avg())
#inimg.fitssave("out.fits")
exit()
```

**Comment by jcupitt** [comment]
Huh strange, I tried:

```
$ vips black x.fits 10 10 --bands 10000
$ vipsheader x.fits
x.fits: 10x10 uchar, 10000 bands, multiband, fitsload
```

Which seems to work. But if I try:

```
$ vips copy x.fits x.tif
fits: unable to open "x.fits"
fits: attempt to open too many files
```

Perhaps this because FITS is band separate (each band is a separate plane) but libvips is band interleaved?

Other formats seem fine, eg.:

```
$ vips black x.tif 10 10 --bands 10000
$ vips avg x.tif
0.000000
```

**Comment by jcupitt** [comment]
Or:

```
$ vips black x.v 10 10 --bands 10000
$ vips avg x.v
0.000000
$ vipsheader x.v
x.v: 10x10 uchar, 10000 bands, multiband
```

**Comment by ewelot** [comment]
Yes, FITS cubes are band separate, that means the data of the second image plane follows the data of the first image plane. Just in case, the full documentation of the FITS file format is available [here](https://fits.gsfc.nasa.gov/fits_standard.html).

**Comment by jcupitt** [comment]
So I think this is a cfitsio limit, not libvips. Someone would need to dig into the cfitsio sources and find out why it's opening so many files, and if there's a way to remove that limit.

**Comment by ewelot** [comment]
I don't think there is a problem with cfitsio. Other applications using cfitsio have no problems to work with MUCH larger cubes. Here is a small example program using astropy which mimics my previous example using pyvips:
```
#!/usr/bin/python3

import sys
import numpy as np
from astropy.io import fits

hdu_list = fits.open(sys.argv[1])
hdu_list.info()
img = hdu_list[0].data
hdu_list.close()

print("size=", img.shape)
print("avg= ", np.mean(img))
exit()
```

While the number of read() syscalls in the pyvips approach is similar to the number of bands it is much lower in the case of the astropy program. Please also note that the vips fitsload() function itself has no problem opening very large FITS cubes (larger than previous examples) but the observed errors appear later, apparently after all bands have been read.

**Comment by jcupitt** [comment]
Ahh looking at `fits.c` again I see that it has to open the image once for each band. This is so that it can do on-demand reading of pixels as the pipeline requests them.

How large (in XY terms) do FITS images get? Perhaps we should give up on on-demand reading and instead just pull the entire thing into memory on load, then serve pixels from that. I think this is probably what astropy is doing.

**Comment by ewelot** [comment]
> ...
> How large (in XY terms) do FITS images get? Perhaps we should give up on on-demand reading and instead just pull the entire thing into memory on load, then serve pixels from that. ...

Well, it depends. Ten years ago we have seen images of about 10 gigapixels in size (see [here](https://www.eso.org/public/images/eso1242a/)). A typical CMOS camera used by amateurs today has about 60 megapixels. During processing images can get larger a few times (subsampling). But mostly those images are monochrome or tri-color (RGB). FITS cubes from time-series are much smaller, in most cases less than 2048x2048 pixels. Some high-speed cameras (in terms of astronomical targets this means exposure times of ~1ms) might create cubes of several 100000 image planes.

**Comment by jcupitt** [comment]
Ooooof wow, so it sounds like there's no one way to read out pixels which will work efficiently for all cases, at least with the current way fits loading is set up in libvips.

We probably need to move the band (plane) loop inside the loader and iterate on each subregion fetch. Let's tag this as an enhancement.

**Comment by ewelot** [comment]
Yes, this sounds reasonable. Maybe a temporary solution is to choose a full copy into memory if the number of bands is larger than 10. This would allow some further testing (e.g. simple math, conversion and image writing) using image cubes which are well below memory size. Would be much appreciated.

**Comment by jcupitt** [comment]
I had a go: https://github.com/libvips/libvips/pull/3120

Let's shift any discussion and/or testing to that PR.

**Comment by jcupitt** [comment]
OK, fix merged to master.
