### ISSUE TITLE
12bit AVIF does not round-trip correctly

### ISSUE THREAD

**Issue by AttilaTheFun** [libvips/libvips#3123]
## Bug report

Back in February I inquired about the possibility of adding support for >8bit HEIC/AVIF images and @jcupitt implemented support for them super quickly! 😊
https://github.com/libvips/libvips/discussions/2627

Unfortunately I didn't really have an opportunity to test this until recently. iOS 16 and MacOS Ventura just released which have native support for AVIF images, so I went about integrating support for them with my app.

I've found that 8bit AVIF images work fine and going from a 16bit TIFF to a 12bit AVIF also looks awesome. 

However, the colors for some >8bit AVIF images appear to be distorted when imported into libvips and then exported back out as the same, higher bit depth.

**To Reproduce**

Download the linked 12bit AVIF image and attempt to import it + export it as a 12bit AVIF image. 

**Expected behavior**

Importing and exporting a 12bit AVIF image with the same bit depth should produce output that is visually indistinguishable from the original.

**Actual behavior**

The colors change substantially becoming a lot lighter.

**Screenshots**

Github doesn't support AVIF images so I uploaded them here:
https://drive.google.com/drive/folders/1261mh02nTeH89v8leCAu8AI9Q8rAuHrP?usp=share_link

**Environment**

 - OS: MacOS Ventura
 - Vips: 8.13.12 (Homebrew)

**Comment by jcupitt** [comment]
Hi again,

I've not been able to reproduce this. Could you share some code that shows this issue?

I tried roundtripping like this:

```
$ vips icc_import Display\ P3.tiff x.v
$ vips icc_export x.v x.tif --depth 16
```

The first line makes a float PCS image with the P3 profile attached, the second line converts back to device space using the embedded P3 profile.

I made a pair of srgb jpgs for evaluation like this:

```
$ vips colourspace Display\ P3.tiff x1.jpg srgb
$ vips colourspace x.tif x2.jpg srgb
```

And they seem identical to me. I'd upload the samples, but my ISP seems to be having a brainfart and it's timing out :(

**Comment by AttilaTheFun** [comment]
Hey @jcupitt ! I've been able to successfully convert 16bit TIFF -> 12bit AVIF without distortion.

I think it may be a property of the 12bit AVIF image image I shared above:
https://drive.google.com/drive/folders/1261mh02nTeH89v8leCAu8AI9Q8rAuHrP?usp=share_link

I got it from this collection of AVIF sample images:
https://github.com/link-u/avif-sample-images
IIRC the one I shared was the profile 2 / 12-bit / YUV422 fox image.

I think it could have something to do with how they produced these images -- I believe they're demonstrating the effects of chroma subsampling in combination with higher bit depth images. They have a ton of samples to choose from. 

Could you try the image I linked or one of the ones from their collection of samples? Thanks!

**Comment by jcupitt** [comment]
Argh I'm so dumb, I tested the wrong image sigh. I'll try again with the avif.

**Comment by jcupitt** [comment]
Sorry, just be be clear, you mean the file `avif-12bit.avif`, is that right?

**Comment by jcupitt** [comment]
I ran:

```
$ vips icc_import avif-12bit.avif x.v
$ vips icc_export x.v x.avif --depth 16
$ vips colourspace avif-12bit.avif x1.jpg srgb
$ vips colourspace x.avif x2.jpg srgb
```

To make:

![x1](https://user-images.githubusercontent.com/580843/199071115-f97ba049-e304-4866-bf63-b9e3f6691ba6.jpg)

![x2](https://user-images.githubusercontent.com/580843/199071139-88380980-af79-47ce-af0d-131ca320f804.jpg)

Which look OK I think.

**Comment by jcupitt** [comment]
I tried without the `--depth 16` and that worked too. How are you storing the PCS image? Perhaps that's being clipped?

**Comment by kleisauke** [comment]
> * Vips: 8.13.12 (Homebrew)

Did you mean version 8.13.2? The upcoming libvips 8.13.3 ought to include better rules for 16-bit AVIF save (commit https://github.com/libvips/libvips/commit/fbef6746253bf26392eeb11b7e4106ac4ea3761a).

**Comment by AttilaTheFun** [comment]
> > * Vips: 8.13.12 (Homebrew)
> 
> 
> 
> Did you mean version 8.13.2? The upcoming libvips 8.13.3 ought to include better rules for 16-bit AVIF save (commit https://github.com/libvips/libvips/commit/fbef6746253bf26392eeb11b7e4106ac4ea3761a).

Ah yes this was a typo, sorry! And that sounds great for 8.13.3. Do you know when that will ship?

**Comment by AttilaTheFun** [comment]
> I tried without the `--depth 16` and that worked too. How are you storing the PCS image? Perhaps that's being clipped?

Hmm I'm not sure -- I'm using the govips bindings. Would this be an issue with the loading parameters?

**Comment by AttilaTheFun** [comment]
Update: So I'm still getting this issue and I don't even need to do an icc transform to make the loss of saturation happen.
Just reading in and writing back out the same fox AVIF image above makes it happen. Also, I *have* been able to make non-distorted 12-bit AVIFs from 16-bit TIFFs and even when I convert this AVIF to a jpeg I see the distortion so I think it's happening on the load side. 

This makes me think govips bindings must not be loading the image correctly.

The C on the govips side that loads the image is:
```
    code = vips_heifload_buffer(buf, len, out, "page", params->page, "n",
                                params->n, "thumbnail", params->heifThumbnail,
                                "autorotate", params->autorotate, NULL);
```
Are they missing a param here?

**Comment by jcupitt** [comment]
I've just made 8.13.3, which includes the improves AVIF 16-bit write that Kleis noted. WOuld you be able to test?

**Comment by AttilaTheFun** [comment]
Sure -- is libvips 8.13.3 available through Homebrew? I can install it and test again shortly.

**Comment by jcupitt** [comment]
No yet -- someone needs to update `vips.rb`. 

You could patch your copy and test that way -- just edit the file and update the URL and the md5sum.

**Comment by AttilaTheFun** [comment]
Hi @jcupitt -- I was trying to update vips.rb like this:
```
brew bump-formula-pr -n --tag v8.13.3 vips
```

But I keep getting this error:
```
An error occurred while installing hpricot (0.8.6), and Bundler cannot continue.
```
When I open the make log:
```
sions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
```

Are you able to bump the libvips forumula? I don't know why it won't work on my machine 🙁

**Comment by jcupitt** [comment]
You don't need to use bump-formula, just edit the `vips.rb` file and change the URL.

I'll have a quick go now.

**Comment by AttilaTheFun** [comment]
Ok I tried to make a homebrew for 8.13.3 manually here @jcupitt 
https://github.com/Homebrew/homebrew-core/pull/114502

**Comment by jcupitt** [comment]
Looks good! Did it fix your issue?

**Comment by AttilaTheFun** [comment]
@jcupitt so I just updated vips to 8.13.3 and I'm still having the issue. 
Also, I just realized the images you shared above are actually brighter than the original too, very similar to the ones I'm getting locally. Here I opened the original and one of the ones you generated side by side and took a screenshot:

<img width="1510" alt="Screenshot 2022-11-02 at 12 28 07 PM" src="https://user-images.githubusercontent.com/3255391/199546477-1e4d1812-37d4-4f45-8f88-4e3d3225a6fa.png">

I can't tell if it's just the exposure that's being brought up or if it's actually losing dynamic range, but the original has much darker blacks and looks much higher contrast.

**Comment by AttilaTheFun** [comment]
I went back to the sample images where I got it from and I downloaded their PNG and I went through the same steps and I was able to make a correct looking AVIF from it:

<img width="1487" alt="Screenshot 2022-11-02 at 12 44 22 PM" src="https://user-images.githubusercontent.com/3255391/199550258-f3b4ad36-10f2-47d8-af1f-9972b62b99be.png">

I think something is getting messed up when these AVIF files are being loaded into VIPS which then affects any image produced from them. Can you try your steps again but this time open the original and the output image side by side so you can see the difference?

**Comment by jcupitt** [comment]
That's so weird, I see it too now. It looks like a constant offset -- I made a tiny patch:

https://github.com/libvips/libvips/commit/7bff57bcd969464dc61370f55ad9d4c52538fd8a

And that seems to work for the 10 and 12 bit sources. But why it's necessary, or where the magic numbers come from, I've no idea.

I see:

```
$ vips copy fox.profile2.10bpc.yuv422.avif fox-10.png
$ vips copy fox.profile2.12bpc.yuv422.avif fox-12.png
```

To make:

![sample](https://user-images.githubusercontent.com/580843/199613638-bfc4d9c3-6915-4ca2-a3f0-aa4803528755.png)

Original, 10 bit, 12 bit.

**Comment by AttilaTheFun** [comment]
That's so weird, though it does look correct. 

Also, weirdly, MacOS Ventura seems to really dislike 4:2:2 AVIF images. I can see 4:4:4 and 4:2:0 okay but the 4:2:2 images appear black on my machine.
(This part doesn't have anything to do with vips -- I think they just don't have support for those.)

Could you also verify that you can round-trip a 16-bit AVIF? 
E.g. 16-bit TIFF (you can use the one I linked) to 16-bit 4:4:4 AVIF to 16-bit 4:4:4 AVIF?

Ultimately I really want to be converting 16-bit TIFF images to 16-bit 4:4:4 AVIF images and making sure that those AVIF images can round trip.

**Comment by jcupitt** [comment]
I'll have a look at the command-line libheif converter and see if I can reproduce it there. If I can, I'll file a bug upstream.

**Comment by jcupitt** [comment]
Yes, `heif-convert` has this issue as well. I've reported it upstream.

**Comment by kmilos** [comment]
> `heif-convert` has this issue as well.

What about [`avifdec`](https://github.com/AOMediaCodec/libavif)?

**Comment by AttilaTheFun** [comment]
@jcupitt @kmilos I also found some official AVIF test images from the AOMediaCodec repo here:
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles
This includes the fox image I shared above -- it was contributed by Link-U -- as well as some others.

One question I had was if libvips supports the --range argument too? I would like to create HDR images with it if possible, E.g. from the Netflix examples:
```
avifenc -c aom --speed 0 --jobs 12 --depth 10 --ignore-icc --cicp 9/16/9 --range full --yuv 444 --min 40 --max 40 original_hdr_cosmosXXXXX.png hdr_cosmosXXXXX_cicp9-16-9_yuv444_full_qp40.avif
```

**Comment by jcupitt** [comment]
We'd need to add range etc. to `heifsave` I think, though I don't know if libheif has API for this.

**Comment by AttilaTheFun** [comment]
@jcupitt it looks like they have at least some support for it here:
https://github.com/strukturag/libheif/blob/ea78603d8e47096606813d221725621306789ff2/libheif/plugins/heif_encoder_aom.cc#L939
Does this mean it will default to the full range? Is that equivalent to the avifenc command with --range full above?
Also does libvips support 32-bit TIFF images?

**Comment by jcupitt** [comment]
We should probably have a new issue for range support.

> Also does libvips support 16-Bit IEEE Float TIFF images?

No, just 32, 64 and 128-bit. It would be pretty easy to add, I think.

**Comment by jcupitt** [comment]
Dirk has fixed this in libheif, and it all seems to work now, hooray!

You'll need to build git master libheif, or wait for the release of the next version. Please open a new issue if the next libheif doesn't fix this.

**Comment by jcupitt** [comment]
We should probably have new issues for range support, and for half float support in tiff load, if anyone has the time to make them.

**Comment by AttilaTheFun** [comment]
Thanks @jcupitt ! 

I created this issue for half-float TIFF images:
https://github.com/libvips/libvips/issues/3144

And this one for the range flag:
https://github.com/libvips/libvips/issues/3143

Speaking of the range flag, is there a good way to detect if an image contains any extended dynamic range values? 

My understanding of float images is that they use 0-1 for standard dynamic range and >1 for extended dynamic range. Would I have to open a float image and scan through all the pixels looking for any in the extended range? Also for AVIF images would I use the same approach?
