### ISSUE TITLE
Calling vips_icc_transform reduces bit depth from 16 -> 8

### ISSUE THREAD

**Issue by AttilaTheFun** [libvips/libvips#3124]
## Bug report

I'm trying to add support for high-bit-depth (>8bit) images to my app and I found an issue with the vips_icc_transform function.

If I import a 16-bit TIFF image and write it back out, the input and output images both correctly report a band format of UShort (16-bit) and a Type of VIPS_INTERPRETATION_RGB16. 

However, when I call vips_icc_transform passing *the same Display P3 profile already embedded in the image*, the BandFormat changes to UChar (8-bit) and and interpretation of VIPS_INTERPRETATION_sRGB.

I've tried the Perceptual, Relative and Absolute intents with the same result.

**To Reproduce**

I've uploaded a 16-bit Display P3 TIFF file here:
https://drive.google.com/file/d/1Ysihv5eacF1gwUBLIdMG8tHk8YCUp6xy/view?usp=share_link
As well as the Display P3 ICC profile I extracted from it here:
https://drive.google.com/file/d/1U4UCubmVuB7G7i-4b7znEuMCFUrKLuoY/view?usp=share_link

**Expected behavior**

The BandFormat / Interpretation should be preserved when calling vips_icc_transform.

**Actual behavior**

The BandFormat / Interpretation is reduced to 8-bit.

**Environment**
(please complete the following information)
 - OS: MacOS Ventura
 - Vips: 8.13.0

**Comment by jcupitt** [comment]
Hi @AttilaTheFun,

`icc_transform` is supposed to write 8 bit by default, so:

```
$ vips icc_transform Display\ P3.tiff x.tiff srgb
$ vipsheader x.tiff 
x.tiff: 1024x683 uchar, 3 bands, srgb, tiffload
```

And only write 16 bit if you ask for it:

```
$ vips icc_transform Display\ P3.tiff x.tiff srgb --depth 16
$ vipsheader x.tiff 
x.tiff: 1024x683 ushort, 3 bands, rgb16, tiffload
```

What are you running to make it preserve bitdepth?

**Comment by AttilaTheFun** [comment]
Ah thanks @jcupitt !
I didn't know about the depth parameter -- I'm using vips from Go via the govips bindings but I believe they don't pass it. 
I'll update my fork to pass this parameter and verify that the bit depth is preserved and close the issue if it is.

Also what is the correct way to tell if an image has 16bit color depth? Is checking for the interpretation being RGB16 the best option or is there an alternative?

**Comment by jcupitt** [comment]
Yes, I'd check for rgb16 (or grey16).

**Comment by AttilaTheFun** [comment]
Thanks @jcupitt ! I found where govips was passing 0 for the bit depth (so it defaulted to 8-bit) and once I fixed that I was able to produce a really nice looking 12-bit AVIF image from one of my Canon R5 Tiff Files.
