### ISSUE TITLE
About  default png filter in pngsave 

### ISSUE THREAD

**Issue by jishi92** [libvips/libvips#3135]
## Questions

I use govips to thumbnail a png image and find the result image is bigger than origin one.
During a series of checks, I find the pngsave.filter affects this result.
I fixed this problem by remove the filter parameter.
But the pngsave.filter=default_filter= VIPS_FOREIGN_PNG_FILTER_NONE.

So, I test this case by bimg and it appears again. I see the doc [https://www.libvips.org/API/current/VipsForeignSave.html#vips-pngsave-buffer] and the confirm the default filter.

## Bug report

**Describe the bug**
Is there any bug in pngsave about filter parameter?
Why  the results is different from default_filter parameter and no filter parameter?
I read the libvips code and cant find any abnormal.

**Screenshots**
I think any png image can cause the bug,this is my case.

the origin png : 473k 512x512
![lena](https://user-images.githubusercontent.com/22196414/199426236-4f10d7e5-fbd7-460b-943b-5dc6ba23bbd7.png)

with no filter param: 442k 500x500
![lena-filter-no](https://user-images.githubusercontent.com/22196414/199426145-c5aa0450-a822-4ad7-b8b3-ef6940872b7a.png)

with default filter param :699k 500x500

![lena-filter-none](https://user-images.githubusercontent.com/22196414/199426510-e1620a65-de21-4a09-92da-6c0bb296242b.png)

**Environment**
 - OS: centos-8.4, MacOS 12.4
 - Vips: vips-8.12.1

**Comment by jishi92** [comment]
By the way, what is the meaning of filter in png_save and what is its greatest use? 
I can't quite understand what it means.

**Comment by jcupitt** [comment]
Hi @jishi92,

randy408 made a useful table showing how compression level and filter interact:

https://github.com/libspng/spngt/blob/master/results/kodak_params.csv

The filter is used to preprocess the pixel values before sending them to the compressor. Picking the right filter can increase spatial correlation and improve the effectiveness of compression. It depends on the image type -- you might want different settings for line art and photographs, for example.

**Comment by jcupitt** [comment]
Is there a bug here? I'm not sure I understand.

**Comment by jishi92** [comment]
Hi @jcupitt,
I think pic2 and pic3 should have the same size. Because the pngsave_init func with default filter 
`static void vips_foreign_save_png_init( VipsForeignSavePng *png )
{
	png->compression = 6;
	png->filter = VIPS_FOREIGN_PNG_FILTER_NONE;
	png->Q = 100;
	png->dither = 1.0;
	png->effort = 7;
}
`
However,
`vips_pngsave_buffer(in, buf, len,
		"strip", INT_TO_GBOOLEAN(strip),
		"compression", compression,
		"interlace", INT_TO_GBOOLEAN(interlace),
		**"filter", VIPS_FOREIGN_PNG_FILTER_NONE,**
		"palette", INT_TO_GBOOLEAN(palette),
		"Q", quality,
		"effort", effort,
		NULL
	);`

and 

`vips_pngsave_buffer(in, buf, len,
		"strip", INT_TO_GBOOLEAN(strip),
		"compression", compression,
		"interlace", INT_TO_GBOOLEAN(interlace),
		"palette", INT_TO_GBOOLEAN(palette),
		"Q", quality,
		"effort", effort,
		NULL
	);`

have dDifferent results.

I'm not sure I made myself clear.

**Comment by jcupitt** [comment]
I tried here:

```
$ vips copy lena.png x.png[filter=none]
$ vips copy lena.png x2.png
$ vips copy lena.png x3.png[filter=all]
$ ls -l x*.png
-rw-r--r-- 1 john john 735908 Nov  2 13:00 x2.png
-rw-r--r-- 1 john john 476217 Nov  2 13:00 x3.png
-rw-r--r-- 1 john john 735908 Nov  2 13:00 x.png
```

And the default does seem to be `none`. I'll try with 8.12.

I suppose you're using libpng? What do you see for:

```
$ vips --vips-config | grep PNG
PNG load/save with libspng: false
PNG load/save with libpng: true
```

**Comment by jishi92** [comment]
My centos on docker use libpng:
```
PNG load with libspng: no
PNG load/save with libpng: yes (pkg-config libpng >= 1.2.9)
```
My Mac use all of them:
```
PNG load with libspng: yes
PNG load/save with libpng: yes (pkg-config libpng >= 1.2.9)
```

**Comment by jishi92** [comment]
this is my result:
![image](https://user-images.githubusercontent.com/22196414/199502280-d656c101-6786-4397-bd4b-19948f9adba2.png)
x and x1 is diffent , x1 and x2 is same.

**Comment by jcupitt** [comment]
Ah, yes, the default changed in 8.13. If you update your libvips you should find the behaviour matches the docs. 

The current supported version is 8.13.3:

https://github.com/libvips/libvips/releases/tag/v8.13.3

**Comment by jishi92** [comment]
oh, I got it.

I use libvips 8.12 and the default_png_filter=VIPS_FOREIGN_PNG_FILTER_ALL,and it changed to VIPS_FOREIGN_PNG_FILTER_NONE in 8.13. 

May I ask why this change was made, what's the biggest benefit of this change?
This change appears to make the exported image larger.

**Comment by jcupitt** [comment]
You can see the ratuionale here:

**Comment by jcupitt** [comment]
Here's an example line art image:

![logo](https://user-images.githubusercontent.com/580843/199514420-04e32a4f-0d3b-44ed-87be-6db59e072196.png)

I see:

```
$ time vips copy logo.png filter-none.png[filter=none]
real	0m0.133s
user	0m0.159s
sys	0m0.017s
$ time vips copy logo.png filter-all.png[filter=all]
real	0m0.210s
user	0m0.211s
sys	0m0.034s

$ ls -l filter*
-rw-r--r-- 1 john john 122073 Nov  2 14:22 filter-all.png
-rw-r--r-- 1 john john  92934 Nov  2 14:22 filter-none.png
```

So `none` is 40% faster and makes files 30% smaller.

**Comment by jishi92** [comment]
Yes,`none` can be faster than `all`. I also found it in my code.
However, if a png image just be read and export ,then it gets bigger.
Not to mention thumbnail image.I don't think this is reasonable.

**Comment by jcupitt** [comment]
I think that's only true for photographic images. 

Most PNGs will get smaller if you turn the filter off.

**Comment by jishi92** [comment]
Ok,I know. Thank you jcupitt.
