### ISSUE TITLE
cmyk to srgb brightness increase

### ISSUE THREAD

**Issue by SpicerSolutions** [libvips/libvips#3136]
Hello,

I'm not sure whether this is intended but there appears to be a shift in the brightness (possibly gamma) of a cmyk image when using the thumbnail method.

Please see attached original and thumbnail.

I'm using vips 8.13.2

![tn_original](https://user-images.githubusercontent.com/14977825/199486115-af691212-65df-419d-bae3-6f4ff585f63d.jpg)
![original](https://user-images.githubusercontent.com/14977825/199486117-615d22a4-0449-4683-a5ca-f245f4f8ec03.jpg)

**Comment by jcupitt** [comment]
Hi @SpicerSolutions, I think this is fixed in 8.13.3 (there was a bug thumbnailing images with a non-sRGB output profile). Could you try updating?

https://github.com/libvips/libvips/releases/tag/v8.13.3

**Comment by SpicerSolutions** [comment]
Thanks for getting back to me. I have now tried the same using 8.13.3. I'm afraid this doesn't appear to have made any difference.

![new](https://user-images.githubusercontent.com/14977825/199516667-e5ccb15a-a863-4f7d-be2b-79868ec8fcf5.jpg)

VIPS-INFO: 14:30:24.411: thumbnailing original.jpg
VIPS-INFO: 14:30:24.418: selected loader is VipsForeignLoadJpegFile
VIPS-INFO: 14:30:24.418: input size is 1000 x 562
VIPS-INFO: 14:30:24.418: loading with factor 2 pre-shrink
VIPS-INFO: 14:30:24.420: pre-shrunk size is 500 x 281
VIPS-INFO: 14:30:24.420: converting to processing space srgb
VIPS-INFO: 14:30:24.467: residual reducev by 0.256
VIPS-INFO: 14:30:24.467: reducev: 25 point mask
VIPS-INFO: 14:30:24.470: reducev: using vector path
VIPS-INFO: 14:30:24.470: reducev sequential line cache
VIPS-INFO: 14:30:24.470: residual reduceh by 0.256
VIPS-INFO: 14:30:24.470: reduceh: 25 point mask
VIPS-INFO: 14:30:24.471: converting to output space srgb
VIPS-INFO: 14:30:24.471: thumbnailing original.jpg as ./new.jpg

Johnny

**Comment by jcupitt** [comment]
I had a look at your file: it's a CMYK JPEG with no embedded profile. libvips is using a high-quality CMYK profile by default, which obviously doesn't match the default quick and dirty CMYK handling used by web browsers. I think libvips is probably more correct here. 

You can make a full-size RGB from your original like this:

```
$ vips colourspace landscape.jpg x.jpg srgb
```

To make:

![x](https://user-images.githubusercontent.com/580843/199529681-5698efb3-b0e7-4161-b9f9-34772b83d286.jpg)

Which should match the thumbnail.
