### ISSUE TITLE
icc_transform: incompatible profile isn't ignored

### ISSUE THREAD

**Issue by dloebl** [libvips/libvips#3139]
Since 1297f2c6d790aba928c1f9376674890ad75c6e39 incompatible source profiles do not seem to be ignored anymore:

**Before 1297f2c6d790aba928c1f9376674890ad75c6e39:**
```
$ vips icc_transform --input-profile=sRGB.icm test.jpg bef.jpg sRGB.icm

(vips:9111): VIPS-WARNING **: 10:55:58.075: profile incompatible with image
```
| original | output |
| - | - |
| ![test](https://user-images.githubusercontent.com/34104349/199690097-5a26bbdc-76d5-4774-be65-625d2ba7e7d9.jpg) |  ![bef](https://user-images.githubusercontent.com/34104349/199692114-50a786d9-3fa2-48ee-95b2-6511442726b5.jpg) |

**Current master (17ca29adc9c52ef48cf5a9a59c26a83d0693fbbe):**
```
$ vips icc_transform --input-profile=sRGB.icm test.jpg now.jpg sRGB.icm
```
| original | output |
| - | - |
| ![test](https://user-images.githubusercontent.com/34104349/199690239-f8edae02-78b9-4f05-9e49-08b942ebb679.jpg) | ![now](https://user-images.githubusercontent.com/34104349/199692196-c3d1cfed-14f4-4449-b645-6c64ea19d265.jpg) |

[sRGB.icm](https://github.com/libvips/libvips/blob/master/libvips/colour/profiles/sRGB.icm)
[test.jpg](https://user-images.githubusercontent.com/34104349/199690097-5a26bbdc-76d5-4774-be65-625d2ba7e7d9.jpg)

```
$ vipsheader test.jpg
test.jpg: 640x426 uchar, 4 bands, cmyk, jpegload
```

**Comment by jcupitt** [comment]
Hi Daniel, 

I added a test for this specific case, but I don't think we can do the general test we used to have :( Thanks for the report!

BTW you could write:

```
$ vips icc_transform --input-profile=sRGB.icm test.jpg bef.jpg sRGB.icm
```

As:

```
$ vips icc_transform --input-profile=srgb test.jpg bef.jpg srgb
```

Since you can use the libvips built in profile names anywhere you use a profile filename. master has `p3` and `cmyk` as built in profiles as well.
