### ISSUE TITLE
How to get the dependency version of image lib in the libvips ?

### ISSUE THREAD

**Issue by Mhuang77** [libvips/libvips#3148]
Are there some commands or functions to get the lib version in the libvips or the pyvips? for example, get the libpng version or the libjpeg version

**Comment by jcupitt** [comment]
Hi @Mhuang77,

Not built in to libvips. You can use the standard OS tools of course, eg.:

```
$ ldd $(which vips) | grep jpeg
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f7e5790a000)
$ dpkg -S libjpeg.so.8
libjpeg-turbo8:i386: /usr/lib/i386-linux-gnu/libjpeg.so.8.2.2
libjpeg-turbo8:amd64: /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
libjpeg-turbo8:i386: /usr/lib/i386-linux-gnu/libjpeg.so.8
libjpeg-turbo8:amd64: /usr/lib/x86_64-linux-gnu/libjpeg.so.8
$ dpkg -s libjpeg-turbo8 | grep Ver
Version: 2.1.2-0ubuntu1
```

**Comment by jcupitt** [comment]
... you can get the pyvips version and the libvips version numbers.

```
$ python3
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.__version__
'2.2.1'
>>> [pyvips.version(i) for i in range(3)]
[8, 14, 0]
```

**Comment by Mhuang77** [comment]
> Hi @Mhuang77,
> 
> Not built in to libvips. You can use the standard OS tools of course, eg.:
> 
> ```
> $ ldd $(which vips) | grep jpeg
> 	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f7e5790a000)
> $ dpkg -S libjpeg.so.8
> libjpeg-turbo8:i386: /usr/lib/i386-linux-gnu/libjpeg.so.8.2.2
> libjpeg-turbo8:amd64: /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
> libjpeg-turbo8:i386: /usr/lib/i386-linux-gnu/libjpeg.so.8
> libjpeg-turbo8:amd64: /usr/lib/x86_64-linux-gnu/libjpeg.so.8
> $ dpkg -s libjpeg-turbo8 | grep Ver
> Version: 2.1.2-0ubuntu1
> ```
@jcupitt 
In this way, I get the png version like this
libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16
According to this site :  http://www.libpng.org/pub/png/libpng.html  libpng16.so.16

**Comment by jcupitt** [comment]
The `16` is the API number, not the version number. You need to use `dpkg` (on Debian-derived systems) to get that. I see:

```
$ ldd $(which vips) | grep png
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f62897a8000)
$ dpkg -S  libpng16.so.16
libpng16-16:i386: /usr/lib/i386-linux-gnu/libpng16.so.16
libpng16-16:amd64: /usr/lib/x86_64-linux-gnu/libpng16.so.16.37.0
libpng16-16:i386: /usr/lib/i386-linux-gnu/libpng16.so.16.37.0
libpng16-16:amd64: /usr/lib/x86_64-linux-gnu/libpng16.so.16
$ dpkg -s libpng16-16 | grep Ver
Version: 1.6.37-3build5
```

Unless you have a very, very strong reason to update, I would stick with the libpng supplied by your distro. If you must update it, you'll need to build it and all downstream packages that depend on it from source to a private prefix.

**Comment by Mhuang77** [comment]
> 

OK, Thank you very much!
