### ISSUE TITLE
ICC transforms with XYZ PCS don't roundtrip correctly

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3150]
This works:

```
vips icc_import input.jpg t1.v
vips icc_export t1.v output.jpg
```

But this has a visible colour difference:

```
vips icc_import input.jpg t1.v --pcs xyz
vips icc_export t1.v output.jpg
```

See https://github.com/libvips/php-vips/issues/169

**Comment by romanzks** [comment]
I did a little research and noticed that the bug has been reproducible since version 8.11.0.
In earlier versions, error "icc_import: no input profile" is issued.

**Comment by jcupitt** [comment]
I did a little digging and I think the issue is that these two paths are not exactly equal:

```
device rgb -> icc_import(pcs=xyz) -> xyz 
device rgb -> icc_import(pcs=lab) -> lab2xyz -> xyz
```

ie. the lcms option to output xyz does not give exactly the same results as requesting lab, and then using the libvips lab2xyz. Perhaps lcms is using D50 lab, and libvips is using D65 lab?

I'll try reading the lcms sources and see if I can find the formula they are using.

**Comment by kleisauke** [comment]
I just opened PR #3368 for this.
