### ISSUE TITLE
Can dzsave continue to tile an image after hitting a corrupt tile?

### ISSUE THREAD

**Issue by Austinkf1** [libvips/libvips#3151]
I am using a vips build built using https://github.com/libvips/build-win64-mxe to use a specific pull request of openslide with the BIF format. 

I am having an error, potentially from some image tiles being corrupted. 
 (vips.exe:7752): VIPS-WARNING **: 15:24:33.037: error in tile 30208 x 79872.

Once dzsave hits this error it just stops tiling the image, and I was wanting to know if there was a way to set dzsave to just replace corrupt tiles with black tiles, or something, so that the tiling process can complete.

**Comment by jcupitt** [comment]
Hello @Austinkf1,

It's a limitation of openslide, unfortunately. It can't recover from errors, so once you hit a bad tile, you have to stop.

However BIF slides can be read as regular TIFF files, so if you use that loader instead, it should work. Try maybe:

```
vips tiffload something.bif x.dz
```

And it should generate a deepzoom pyramid in `x.dzi` and `x_files`.

**Comment by Austinkf** [comment]
Thanks @jcupitt,

I've tried the line you gave with the image I have. When used with my image it just creates a .dz file without any errors or _files folder or an actual dzi file. Is there a log I can check to see if something is happening when it runs?

**Comment by Austinkf1** [comment]
@jcupitt 

So when I run the tiffload to dzsave, like you showed, it's only tiling the id tag in the BIF. The actual tissue iamge is not being tiled. Is there a way to set the series to use in the command to tile the correct image?

**Comment by jcupitt** [comment]
I downloaded the BIF sample from openslide and had a poke about:

https://openslide.cs.cmu.edu/download/openslide-testdata/Ventana/

Unfortunately I was wrong :( sorry. Although BIF files looks like standard TIFFs, they are not, and you can't read them correctly with a standard TIFF loader. I should have checked more carefully before suggesting that, I hope I didn't waste too much of your time.

Summary: openslide does not support restart after error, so if your BIF file has a broken tile, there's not much you can do (as far as I know).
