### ISSUE TITLE
OK, I added an enhancement issue to pyvips. Thanks for the idea!

### ISSUE THREAD

**Issue by jaho8** [libvips/libvips#3154]
OK, I added an enhancement issue to pyvips. Thanks for the idea!

_Originally posted by @jcupitt in https://github.com/libvips/libvips/issues/2953#issuecomment-1198150605_

**Comment by jaho8** [comment]
Dvlop main product token

**Comment by kleisauke** [comment]
Spam? This is already being tracked in https://github.com/libvips/pyvips/issues/342.
