### ISSUE TITLE
Manual Ubuntu build instructions require an extra steps on 20.04

### ISSUE THREAD

**Issue by brendon** [libvips/libvips#3177]
Here's what I had to do to get the latest `libvips` installed on Ubuntu 20.04. There are some steps missing in the Wiki but I can't seem to make an edit there:

### Compile VIPS from source
Remove the old vips
```
$ sudo apt-get remove libvips42
```

Add the PPA for `libcgif-dev` per: https://github.com/lovell/cgif-packaging
```
$ sudo add-apt-repository ppa:lovell/cgif
$ sudo apt-get update
$ sudo apt-get install libcgif-dev
```

Install the dependencies:
```
$ sudo apt install git build-essential automake libtool swig libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev gtk-doc-tools libopenslide-dev libmatio-dev libgif-dev libwebp-dev libjpeg-turbo8-dev libexpat1-dev libexif-dev libtiff5-dev libcfitsio-dev libpoppler-glib-dev librsvg2-dev libpango1.0-dev libffi-dev libopenjp2-7-dev libimagequant-dev libcgif-dev libgirepository1.0-dev libheif-dev
```
(note I added `libheif-dev` which isn't necessary)

Install a modern version of meson:
```
$ sudo apt-get install python3-pip
$ sudo pip3 install meson
```

Compile VIPS:
```
$ wget https://github.com/libvips/libvips/releases/download/v8.13.3/vips-8.13.3.tar.gz
$ tar xf vips-8.13.3.tar.gz
$ cd vips-8.13.3
$ meson setup build-dir --prefix=/usr/local --buildtype=release
$ cd build-dir
$ meson compile
$ meson test
$ sudo meson install
```

Hope that helps with keeping the Wiki up to date :) My main need for this was being able to correctly process rotation information and the version that comes with 20.04 doesn't have this sadly.

**Comment by jcupitt** [comment]
Hi @brendon,

Thanks for this, I'll update the wiki.

We had to disable public wiki updates, unfortunately, after some malicious edits :( 

We need to move all the useful material from the wiki into the main docs and shut the wiki down, but no one's got around to it yet. There's an issue here: https://github.com/libvips/libvips/issues/2805

**Comment by brendon** [comment]
Thanks @jcupitt :) Looks good to me! Hopefully it will be of help to others :)
