### ISSUE TITLE
Image Resizing Failing For GIFs Frame Too Large

### ISSUE THREAD

**Issue by Hrishikesh-Thakkar** [libvips/libvips#3181]
I am trying to resize the following [GIF](https://gasfn25jo7ihtd6hweq44q3lymldirlacwdy5cjadirnjuhpomiq.arweave.net/MCRW66l30HmPx7EhzkNrwxY0RWAVh46JIBoi1NDvcxE) 

Original Dimensions are: 1270 x 1270 and a total of 149 Pages

I am resizing to the following Dimensions:
1. 250 x 250 (**Successful**)
2. 500 x 500 (**Successful**)
3. 750 x750 (**Unsuccessful**)

It fails for the last case and after some digging I found that the limits are set in [libvips](https://github.com/libvips/libvips/blob/v8.13.0/libvips/foreign/cgifsave.c#L715-L726). I am not able to conclude how the dimensions are violating the constraints. 

Constraints Being: 

```C
	/* Reject images that exceed the pixel limit of libimagequant,
	 * or that exceed the GIF limit of 64k per axis.
	 *
	 * Frame width * height will fit in an int, though frame size will
	 * need at least a uint.
	 */
	if( (guint64) frame_rect.width * frame_rect.height > INT_MAX / 4 || 
		frame_rect.width > 65535 || 
		frame_rect.height > 65535 ) {
		vips_error( class->nickname, "%s", _( "frame too large" ) );
		return( -1 );
	}
```

Currently I have the latest vips(8.13.3) version installed.

**Comment by jcupitt** [comment]
Hello @Hrishikesh-Thakkar,

How are you doing the resize? It should work. With your test file, I can run:

```
vipsthumbnail huge.gif[n=-1] -o x.gif --size 750
```

To make:

![x](https://user-images.githubusercontent.com/580843/203790393-0d4edfc1-6f64-4a5e-b004-9eb558bc7f54.gif)

**Comment by jcupitt** [comment]
(that's with 8.13.3)

**Comment by Hrishikesh-Thakkar** [comment]
Interesting @jcupitt 
I am not using Thumbnail, I am passing the scale as 0.5905511811023622 and KernelAuto as the parameters.

**Comment by kleisauke** [comment]
Cross-posted at https://github.com/davidbyttow/govips/issues/335.

**Comment by jcupitt** [comment]
And cross-posted here too: https://stackoverflow.com/questions/74561078/unable-to-determine-why-frame-too-large-for-gif-govips

**Comment by jcupitt** [comment]
I would just use `thumbnail` -- it has extra logic for handling resize of multi-page images.

If you must use `resize` yourself, you need to calculate the resize factor very carefully to avoid rounding issues on page boundaries, and you need to set the `page-height` metadata value on the output image.

**Comment by jcupitt** [comment]
... and again, please, please don't cross-post.

**Comment by Hrishikesh-Thakkar** [comment]
Thanks and Apologies @jcupitt. Appreciate the prompt response.
