### ISSUE TITLE
vips resize is locale-aware and silently ignores other separators

### ISSUE THREAD

**Issue by kapouer** [libvips/libvips#3191]
Using libvips 8.13.3 (as found on debian/bookworm).

I am not sure locale-aware command-line inputs are useful:

> vips resize big.jpeg a.jpeg 0.5

just casts 0.5 to 0 and outputs a one-pixel image.

> vips resize big.jpeg a.jpeg 0,5

works but it took me half an hour to figure that out...

**Comment by jcupitt** [comment]
Hi @kapouer,

Oh dear, that's bad. libvips is supposed to use ASCII for numeric parsing, but it's obviously not doing that here. I'll have a look.

**Comment by jcupitt** [comment]
OK, fixed in master, thank you very much for pointing out this silly thing. This will be in 8.14, due RSN.
