### ISSUE TITLE
Allow setting the min quality for imagequant or choose better default

### ISSUE THREAD

**Issue by PaulSchiretz** [libvips/libvips#3197]
When using libimagequant the quality is set by using a range like 0 - Q,

In quantise.c libvips is setting the quality like `vips__quantise_set_quality( quantise->attr, 0, Q );` which equals 0 - Q

According to libimagequant/pngquant documentation the default would be something like 65-80. When i compare setting the Q to 80 using libvips the quality is worse than setting 65-80 using imagequant directly. So it looks like a lower boundary on the quality setting has an effect on the quantization quality and is NOT only a hard limit when to fail quantization.

It would be really great to have the possibility to set the min_quality as well, simply make it something like Q - 20 by default to avoid adding another setting.

Any thoughts on this?

**Comment by PaulSchiretz** [comment]
Hi @jcupitt,

Thanks for the quick response.

Almost, i thought something like  `vips__quantise_set_quality( quantise->attr, VIPS_MAX(20, Q - 20), Q );` to have a range of 20.

BUT as wanted to provide a sample i have seen that i messed up my floyd dither setting in the test before, so it seems the single Quality parameter like it is `vips__quantise_set_quality( quantise->attr, 0, Q );` is perfectly fine.

it also states in the imagequant docu:
Instructs libimagequant to use the least amount of colors required to meet or exceed the max quality. If conversion results in quality below the min quality the image won't be converted

So i would say let's keep things as they are for now!

sorry to bother you :-) and thanks again!

**Comment by jcupitt** [comment]
Ah, that's good. I'll close.
