### ISSUE TITLE
Version 8.13.3 and macOS 10.11

### ISSUE THREAD

**Issue by haoxi911** [libvips/libvips#3235]
## Bug report

**Describe the bug**
`sharp@0.31.2` which uses `libvips@8.13.3` won't load on macOS 10.11, `sharp@0.31.1` which uses `libvips@8.13.2` works fine. May I ask if there is any unexpected breaking changes? 

It might be a problem because `sharp@^0.31.1` will install `0.32.2` automatically.

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp/issues/3438
