### ISSUE TITLE
fitssave should not write 3D cube for single band image 

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#3265]
There is a small glitch in fitssave: when saving a single band 2D image it unnecessarily writes a 3D FITS cube. It is just an issue of the FITS header which currently contains NAXIS=3 and NAXIS3=1 but instead should be changed to NAXIS=2 and no NAXIS3 keyword if the image data is just a single banded ordinary 2D image.

The current behaviour might foul subsequent processing by another software.
 
Thomas

**Comment by jcupitt** [comment]
Hi again, I think I fixed it (a one-liner, phew). I now see:

```
SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                    8 / number of bits per data pixel                  
NAXIS   =                    2 / number of data axes                            
NAXIS1  =                 1024 / length of data axis 1                          
NAXIS2  =                  768 / length of data axis 2                          
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
END       
```

Thanks for reporting this!

**Comment by jcupitt** [comment]
(this will be in 8.14.1)
