### ISSUE TITLE
vips_text changes global state

### ISSUE THREAD

**Issue by midn1** [libvips/libvips#3275]
**Describe the bug**

This bug was found by the use of wxWidgets and libvips at once. Upon calling `vips_text`, the wxWidgets user interface changes DPI to that of the one selected when calling `vips_text`.

**To Reproduce**
1. Initialize a wxFrame, in which you draw text with a wxDC.
2. Call `vips_text` with different DPIs.
3. Text drawn afterwards by wxWidgets has different resolution.

**Expected behavior**
I expected libvips to manage fonts on its own.

**Actual behavior**
libvips alters the resolution of the fontmap it uses, thereby changing global state that may be shared with other libraries.

I suspect the issue manifests in [line 220 of text.c](https://github.com/libvips/libvips/blob/ef2646ef6ae2b0c14a17cef0050bbc49b81a0514/libvips/create/text.c#L220), as I'm certain wxWidgets also uses Pango and/or Cairo.

**Screenshots**
Here is my software in action. When I first connect the nodes in the node graph, `vips_text` is called for the first time. Then, each time I change the DPI, another call to `vips_text` is triggered. The wxWidgets UI is affected.

![2023-01-14 00-43-54](https://user-images.githubusercontent.com/7090833/212433388-bcb3de7e-dd4e-45b6-ab2b-fe5d94ac216d.gif)

To clarify, only the "HEllo World" is drawn with `vips_text`. The rest is with the wxWidgets API, and so the two should not collide with each other like this.

**Environment**
 - OS: Debian 5.10
 - Vips: 8.14.1

**Comment by midn1** [comment]
Interestingly enough, this bug occurs even when explicitly selecting a different font. I'm not sure if that puts a strain on my theory.

**Comment by jcupitt** [comment]
Hi @midn1,

What a crazy bug! I use libvips from my own pango/cairo GUIs (eg. https://github.com/libvips/nip2 ) and I've not seen this. I suppose wxWidgets must be using a different API.

libvips is calling `pango_cairo_font_map_get_default()`:

https://docs.gtk.org/PangoCairo/type_func.FontMap.get_default.html

Then calling `pango_cairo_font_map_set_resolution()` (as you say). The docs say:

> Note that since Pango 1.32.6, the default fontmap is per-thread. Each thread gets its own default fontmap. In this way, PangoCairo can be used safely from multiple threads.

Are you using an older pango? Perhaps we need to make our own fontmap.

**Comment by jcupitt** [comment]
Could you test this patch?

```diff
diff --git a/libvips/create/text.c b/libvips/create/text.c
index 9157c71a9..070120de4 100644
--- a/libvips/create/text.c
+++ b/libvips/create/text.c
@@ -133,6 +133,7 @@ vips_text_dispose( GObject *gobject )
 {
        VipsText *text = (VipsText *) gobject;
 
+       VIPS_UNREF( text->fontmap );
        VIPS_UNREF( text->layout ); 
        VIPS_UNREF( text->context ); 
 
@@ -389,7 +390,7 @@ vips_text_build( VipsObject *object )
                return( -1 );
        }
 
-       text->fontmap = pango_cairo_font_map_get_default();
+       text->fontmap = pango_cairo_font_map_new();
        text->context = pango_font_map_create_context(
                PANGO_FONT_MAP( text->fontmap ) );
```

**Comment by midn1** [comment]
The patch does fix the problem.

I'm having a hard time figuring out which version of Pango I have. Debian states 1.46.2, but wxWidgets itself may have been compiled with an older Pango.

**Comment by jcupitt** [comment]
OK, I cleaned it up a bit and made a PR. Thanks for the report!
