### ISSUE TITLE
libvips on windows - process never exits and keeps using 2.5% of CPU

### ISSUE THREAD

**Issue by andy250** [libvips/libvips#3286]
We built libvips from source (8.12.2) on linux targeting windows. In production environment (Windows Servier 2016) on multiple servers we observe this behavior:

![image](https://user-images.githubusercontent.com/10115397/212940344-bca5b812-ff1f-4f05-a9b0-2987ecce82c8.png)

These thumbs are created and process never exits, reporting 2.5% of cpu usage.

The command we use if basically converting jpg/pdf/tiff/heic/png into jpeg thumbnails. It seems like it's happening randomly. In the end the server is fully loaded up to 100% of cpu.

taskkill command fails with 
```
ERROR: The process with PID 18412 could not be terminated.
Reason: Access is denied.
```

Only way to kill these processes is using Task Manager GUI (right click - kill process).

What more info could we potentially provide to get some help resolving the problem?

**Comment by jcupitt** [comment]
Hi @andy250,

Wow that's an odd one. I would build latest stable (8.14) using the official build system:

https://github.com/libvips/build-win64-mxe

I know Kleis has made a range of patches to the various packages to improve the behaviour on windows, one of those might help. Do you get the hang just with your code, or is this with `vipsthumbnail` as well?

@kleisauke, does this sound like a problem you've seen before?

**Comment by kleisauke** [comment]
It sounds like the same issue that was fixed with commit https://github.com/libvips/libvips/commit/4611651d90d5afe3f8628be2735a1d35be32f3b2, which only occurred when processing GIF images.

**Comment by andy250** [comment]
Thank you guys for the swift response. I will try a new build for sure. I'll try to report how I'm doing it, maybe you can see a problem with the build itself.
@jcupitt Im not sure I understand your question about `vipsthumbnail` - basically I use only vips.exe like this:
vips thumbnail "source.pdf" "output.jpg" 600 --size=both --no-rotate=true

**Comment by andy250** [comment]
For the record here is my build flow:
* Ubuntu 20.04 build server
* install docker https://docs.docker.com/engine/install/ubuntu/
```
git clone https://github.com/libvips/build-win64-mxe.git
cd build-win64-mxe
sudo ./build.sh all --without-mozjpeg --with-hevc
```
I'll treat some servers with 8.14 now and will report back if the issue still occurs.

**Comment by andy250** [comment]
With libvips 8.14 the problem is resolved. Thank you guys!
