### ISSUE TITLE
Very slow write_to_file in pyvips

### ISSUE THREAD

**Issue by nitishsaDire** [libvips/libvips#3294]
Hey all, I am using pyvips library for loading thumbnails from raw data, resizing them, and saving them to jpg.
The loaded thumbnail is of size 8192x5464, resizing them to have max dim=1024, then storing them to jpg. 

I was comparing the speed of pyvips for the above-mentioned tasks with PIL from the following code:

FOR PYVIPS:
```
for idx, filepath in tqdm(enumerate(filepaths)):
    with rawpy.imread(filepath) as raw:
        thumb = raw.extract_thumb()
        if thumb.format == rawpy.ThumbFormat.JPEG:
            thumb_rgb = pyvips.Image.new_from_buffer(BytesIO(thumb.data).read(), "")
            w,h = thumb_rgb.width, thumb_rgb.height
    max_d = max(thumb_rgb.width, thumb_rgb.height)
    size = 1024
    if max_d > size:
        ratio = max_d/size
        thumb_rgb = thumb_rgb.shrink(ratio, ratio)
        w,h = thumb_rgb.width, thumb_rgb.height
    thumb_rgb.write_to_file(os.path.join("{}.jpg".format(idx))
```

FOR PIL:
```
for idx, filepath in tqdm(enumerate(filepaths)):
    with rawpy.imread(filepath) as raw:
        thumb = raw.extract_thumb()
        if thumb.format == rawpy.ThumbFormat.JPEG:
            thumb_rgb = Image.open(BytesIO(thumb.data))
            w,h = thumb_rgb.size
    max_d = max(thumb_rgb.size) 
    size = 1024
    if max_d > size:
        ratio = size / max_d
        thumb_rgb = thumb_rgb.resize((int(ratio * s) for s in thumb_rgb.size), Image.Resampling.LANCZOS)
    thumb_rgb.save('{}.jpg'.format(idx))
```

Unfortunately, the pyvips version is slower than pil version. If I remove the save part from both versions, i.e last lines, then pyvpis part is 2x faster than pil. So there seems to be some issue with the way I am saving pyvips to jpg. I have tried different ways but no luck.  Please guide me in this

Thanks in advance!

**Comment by jcupitt** [comment]
See https://github.com/libvips/pyvips/issues/374
