### ISSUE TITLE
Trouble viewing 12bit AVIF created from 16bit PNG in Safari 16 / OSX

### ISSUE THREAD

**Issue by richardmonette** [libvips/libvips#3323]
Not sure if this is more of a Safari / OSX bug but I've observed that on OSX in `vips-8.14.1` running

`vips heifsave 16bit.png src16bitpng.avif`

creates an AVIF with `Image Pixel Depth : 12 12 12` as reported by exiftool, which is expected, however when trying to view in OSX Preview I see

<img width="1771" alt="Screenshot 2023-02-02 at 4 12 27 PM" src="https://user-images.githubusercontent.com/1041278/216450587-74dfd6bb-b8c0-4fb8-8b24-94bdc81be200.png">

and in Safari 16 I see

<img width="872" alt="Screenshot 2023-02-02 at 4 13 15 PM" src="https://user-images.githubusercontent.com/1041278/216450690-fb47bc1a-6a3a-4624-8ed5-0aa3a470a792.png">

i.e. nothing at all, although the title in the tab does seem to indicate the browser understood the dimensions even if nothing was displayed.

Loading the same image in Chrome renders fine.

I also tried `vips heifsave 8bit.png src8bitpng_cmdline.avif` which works fine in OSX Preview, Safari and Chrome. Because the bit depth appears to affect the results I suspect that is the difference in bit depth causing the problem.

I did also try a source 16bit PNG which did not have an alpha channel and that appears to work. I am wondering if perhaps the issue arrises from the expected range of the alpha channel, i.e. if the RGB pixels are 12bit, should the alpha channel be 12bit as well, or is the alpha channel alpha 8bit regardless of color/rgb depth?

**Comment by jcupitt** [comment]
Hi @richardmonette,

macOS has pretty poor AVIF support, so I think you need to stick to 8 bit images there. Hopefully they'll fix it soon.

**Comment by richardmonette** [comment]
@jcupitt thanks for taking a look. I think for now what we'll do is set the `bitdepth` parameters https://www.libvips.org/API/current/VipsForeignSave.html#vips-heifsave to 8 for all our AVIFs for the time being, since the majority of our input data is 8bit anyways

**Comment by suphamster** [comment]
I think that problem still actual. Example:
`vips --vips-progress heifsave --effort 3 --bitdepth 8 prefs_idle.png -Q 60 prefs_idle.avif"`
produces broken images on Windows 10 (https://github.com/libvips/build-win64-mxe/releases/download/v8.14.2/vips-dev-w64-all-8.14.2.zip). Without "--bitdepth 8" libvips just crashes.
prefs_idle.png file https://workupload.com/file/pNsXjtJhcBF
