### ISSUE TITLE
pyvips.Image.text cannot set line spacing

### ISSUE THREAD

**Issue by donghuikugou** [libvips/libvips#3335]
pyvips.Image.text('LED COLOR METAL\nFLASHY DICES', font='Prompt-Regular 60', fontfile='Prompt-Regular.ttf', spacing=30)

Line spacing can be increased，but Line spacing cannot be reduced

**Comment by jcupitt** [comment]
Hi @donghuikugou,

Good idea, I changed it to allow negative line spacing.

```
$ vips text x.png 'hello^Mworld' --spacing -150 --dpi 300
```

To make

![x](https://user-images.githubusercontent.com/580843/219043420-0ef7e530-3fe8-4fae-af2b-a9ef8f8f3027.png)
