### ISSUE TITLE
Broken table formatting in documentation

### ISSUE THREAD

**Issue by andreas-kupries** [libvips/libvips#3336]
## Bug report

**Describe the bug**

Table formatting at https://www.libvips.org/API/current/libvips-create.html#vips-buildlut is broken.
It shows as
```
For example, consider this 2 x 2 matrix of (x, y) coordinates:

<tgroup cols='2' align='left' colsep='1' rowsep='1'> <tbody> <row> <entry>0</entry> <entry>0</entry> </row> <row> <entry>255</entry> <entry>100</entry> </row> </tbody> </tgroup>

We then generate:

<tgroup cols='2' align='left' colsep='1' rowsep='1'> <thead> <row> <entry>Index</entry> <entry>Value</entry> </row> </thead> <tbody> <row> <entry>0</entry> <entry>0</entry> </row> <row> <entry>1</entry> <entry>0.4</entry> </row> <row> <entry>...</entry> <entry>etc. by linear interpolation</entry> </row> <row> <entry>255</entry> <entry>100</entry> </row> </tbody> </tgroup>

This is then written as the output image, with the left column giving the index in the image to place the value.
```

This looks to me as if the table tags got overquoted to make them look like ordinary text.

**To Reproduce**

Referenced page was visited and read with a browser (firefox, although likely not brower-dependent).

**Expected behavior**

To see a proper table

**Actual behavior**

Table formatting shows as ordinary text

**Screenshots**

n/a

**Environment**

n/a, docs issue

**Additional context**

n/a

**Comment by andreas-kupries** [comment]
Ditto https://www.libvips.org/API/current/libvips-create.html#vips-invertlut

**Comment by jcupitt** [comment]
Argh, the old docbook markup is no longer supported in current gtkdoc. I've redone them in ascii art, thanks!

**Comment by jcupitt** [comment]
There are a few others that need fixing too:

```
~/GIT/libvips/libvips (master) $ grep -l tgroup */*.c
arithmetic/add.c
arithmetic/arithmetic.c
arithmetic/divide.c
arithmetic/multiply.c
arithmetic/subtract.c
arithmetic/sum.c
deprecated/im_lab_morph.c
```

**Comment by andreas-kupries** [comment]
Just seen, the `See Also` section of
https://www.libvips.org/API/current/libvips-generate.html#vips-image-pipelinev
