### ISSUE TITLE
Documentation confusion about VipsDemandStyle

### ISSUE THREAD

**Issue by andreas-kupries** [libvips/libvips#3337]
## Bug report

At https://www.libvips.org/API/current/VipsImage.html#VipsDemandStyle
it is said

> These demand styles are given below in order of increasing restrictiveness.

After their descriptions are provided in the order of

1. VIPS_DEMAND_STYLE_THINSTRIP
2. VIPS_DEMAND_STYLE_FATSTRIP
3. VIPS_DEMAND_STYLE_SMALLTILE
4. VIPS_DEMAND_STYLE_ANY

which I consider to be __decreasing__ restrictiveness.

**Describe the bug**

See above.

**To Reproduce**

Visit with browser

**Expected behavior**

Order and text describing the order to match

**Actual behavior**

Order looks to be inverse of what it is described as.

**Other notes**

Is it possible for the documentation to mention the demand style of each operation ?
Or am I missing this somewhere ?

**Comment by jcupitt** [comment]
OK, I tried to improve the docs. Thanks for pointing this out!

https://github.com/libvips/libvips/commit/682cd33ad73049ffa481eb793dc1748382d257a3
