### ISSUE TITLE
PDFs with offset header are not being processed

### ISSUE THREAD

**Issue by JannKleen** [libvips/libvips#3339]
**Describe the bug**
The foreign loader for pdfium and Doppler seems to expect the header of the file to start with the first character, unfortunately that doesn't seem to be a requirement (s. https://github.com/pdf-association/pdf20examples/blob/master/PDF%202.0%20with%20offset%20start.pdf).
Even though I think PDFs formatted like that are mostly created by accident, it stops us from processing PDFs that at least pdfium (I don't know about poppler) itself should be able to handle.

I believe these are the relevant sections of code: https://github.com/libvips/libvips/blob/870f9e5ee5f30f4cdb39c98e400150591ccab078/libvips/foreign/pdfiumload.c#L792-L817
https://github.com/libvips/libvips/blob/870f9e5ee5f30f4cdb39c98e400150591ccab078/libvips/foreign/popplerload.c#L678-L703

**To Reproduce**
1. Download `https://github.com/pdf-association/pdf20examples/blob/master/PDF%202.0%20with%20offset%20start.pdf`
2. Run `vipsthumbnail PDF\ 2.0\ with\ offset\ start.pdf` 
3. See error

**Expected behavior**
PDFs that pdfium is able to parse should be passed to pdfium for processing.

**Actual behavior**
PDFs with an offset magic header are not being processed.

**Environment**
- Debian with vips-8.14.1 / pdfium
- MacOS with vips-8.14.1 / poppler

**Comment by jcupitt** [comment]
Indeed, the file works:

```
$ vips pdfload ~/pics/PDF\ 2.0\ with\ offset\ start.pdf x.jpg
```

It's the autodetect that fails. Having to search a (perhaps?) very large file for the magic `%PDF-2.0` string sounds terrible, and perhaps unreliable.

Maybe it should try to use the filename suffix if sniffing fails?

**Comment by lovell** [comment]
> the sample looks from the outside like an HTML document with a nested SVG

LOL, it looks like I was served the GitHub 500 error page rather than the sample file. Trying again I see the Linux `file` command interprets this sample as "ISO-8859 text, with CRLF, CR line terminators". I guess we could use a similar approach to SVG, where the first 1000 chars are tested (whilst never forgetting the WebP file with `<svg` in the compressed pixel data).

Do we know if there's any limitation on what can appear before the magic string, e.g. UTF-8 only? That might help filter out obviously-invalid files.

**Comment by jcupitt** [comment]
The file says:

```
# A PDF processor may encounter PDF 2.0 files that contain information
# before the actual PDF 2.0 data. This can occur, for example,
# in a print workflow when a print processor needs to write printer
# control data to select a PDF processing mode.
#
# You cannot rely on all PDF 2.0 processors to successfully open
# PDF files with non-PDF data beforehand; a PDF 2.0 processor
# might reject this as invalid any file that does not start with
# a percent sign and then "PDF".
#
# It is not recommended that a PDF producer write any data
# into a PDF file other than the actual PDF data, unless needed
# for a specific workflow or use case.

%PDF-2.0
```

So I suppose "printer control data to select a PDF processing mode" could in principle be any binary data :( argh.

But it does sound like the offset will almost always be small, so I suppose 1000 characters ought to be enough.

Offset headers are a PDF2 thing, so maybe we can search for `%PDF-2.0`? That would make false positives less likely.

**Comment by JannKleen** [comment]
> Offset headers are a PDF2 thing, so maybe we can search for %PDF-2.0? That would make false positives less likely.

However pdfium seems to handle offsets for PDF1 files as well. I'm not sure if you'd like to mirror the compatibility of the pdf processing libraries or the PDF standard. 
(I have resorted to stripping out everything before the magic block before sending it to vips, but I understand that might not be the best solution for vips itself).

**Comment by jerbob92** [comment]
What I do is mimicking the behavior of the Acrobat PDF viewer: Look for the `%%EOF` marker in the last 1024 bytes of the file.

**Comment by project0** [comment]
Has anyone a fix or workaround for this cases? I am using it along with the sharp library and facing actually issues with such files.

**Comment by jcupitt** [comment]
> What I do is mimicking the behavior of the Acrobat PDF viewer: Look for the %%EOF marker in the last 1024 bytes of the file.

That's a good idea! But it would only work for file and memory sources, of course. With pipes, we'd be forced to load the entire file into memory before we could decide what to do with it.

**Comment by jcupitt** [comment]
Oh, interesting. Is it usually in the first 16 bytes? That would be very simple for us to add.

**Comment by project0** [comment]
> Oh, interesting. Is it usually in the first 16 bytes? That would be very simple for us to add.

I cant tell you, i was just choosing something pragmatic without being to aggressive. Its probably usually less. 

In my case PDFs had a carrier return at the beginning of the file like `\r\n%PDF-1.6\r%\xE2`

**Comment by jcupitt** [comment]
I chopped the PDF detection logic around based on your suggestion, and credited you. It now looks for `%PDF` within the first 32 bytes of the file. This change will be in libvips 8.16.

Thanks very much!
