### ISSUE TITLE
Enhancement: investigate alternative to libgsf for dzsave

### ISSUE THREAD

**Issue by lovell** [libvips/libvips#3354]
### Context

The optional libgsf dependency is used to create ZIP files as part of the `vips_dzsave*` operations.

### Problem

It appears this dependency is `LGPL-2.1-only`, which is incompatible with a few upstream dependencies and downstream consumers made available under some other licences, including but not limited to `LGPL-3.0-or-later` and `Apache-2.0`.

https://gitlab.gnome.org/GNOME/libgsf/-/issues/28

Examples:

* libheif is made available under `LGPL-3.0-or-later`, so to meet licensing terms we cannot link against both libgsf and libheif in the same process.
* imagemagick is made available under `ImageMagick` licence, which a contains patent clause and is incompatible with `LGPL-2.1-only`, therefore libgsf and libimagemagick cannot be used together in the same process.
* sharp is made available under `Apache-2.0` so cannot use libvips compiled with support for libgsf (it has been erroneously doing so, but this will stop).

### Possible solutions

* libzip is well-maintained, is made available under `BSD-3-Clause` and is available on many Linux - https://github.com/nih-at/libzip
* minizip-ng is well-maintained, is made available under `Zlib`, but isn't readily packaged yet - https://github.com/zlib-ng/minizip-ng

**Comment by Posvar** [comment]
@jcupitt - is it fixed though? I'm getting the same error and I've tried 14.4, 14.3 and 14.1 with same message:
vips: unknown action "dzsave"
