### ISSUE TITLE
Color corruption loading ome.tif with interleaved data

### ISSUE THREAD

**Issue by frmdstryr** [libvips/libvips#3397]
## Bug report / Feature Request

When loading an ome.tif that is has interleaved data the color becomes corrupted when saving (eg using vips thumbnail).

For example the following image (screenshot of qupath)

![image](https://user-images.githubusercontent.com/380158/226709267-3a03f7a7-b39a-4dc6-a8ce-1189f1bdcc7e.png)

when converted using vipsthumbnail looks like this

![tn_JP2K-33003-1 ome](https://user-images.githubusercontent.com/380158/226709370-7377cbed-9fe4-4893-a329-df0500a338ff.jpg)

**To Reproduce**
1. Download https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs
2. Open with QuPath and export as OME TIFF with default options  (or I can send the file if needed)
3. The image description should have `Interlaved="true"` in the pixels tag (see https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels_Interleaved)
4. Run `vipsthumbnail JP2K-33003-1.ome.tif`

**Expected behavior**
The thumbnail should look the same

**Actual behavior**
Colors are messed up.

**Screenshots**

**Environment**
(please complete the following information)
 - OS: KDE Neon (Ubuntu 22.04)
 - Vips: 8.14.2
 
**Additional context**

It may not be related to interleaved data but  I tried several other ome.tif files that I could find and those seem to work fine. The interleaved flag was the only difference I could find.

I'm not sure if vips needs to parse the xml, I think having a flag to pass "interleaved" with tiffload would be ok.

**Comment by frmdstryr** [comment]
It seems like no other viewer can open this format so the problem is more with QuPath's export.

**Comment by jcupitt** [comment]
Hi @frmdstryr,

I'll have a look if you could send me the exact TIFF that's failing (otherwise I'll use the wrong qupath version or something like that).

**Comment by frmdstryr** [comment]
It seems to happen with any image I export with QuPath so I found a much smaller file from here https://matthews.sites.wfu.edu/misc/graphics/formats/formats.html an saved that

Both are zipped [Archive.tar.gz](https://github.com/libvips/libvips/files/11051653/Archive.tar.gz) (the ome.tif one is the one that is problematic)

**Comment by jcupitt** [comment]
I think it's a QuPath bug. They've set the photometric interpretation to RGB colour, but the file is YCbCr.

Try:

```
$ vips copy lzw.tif x.tif[compression=jpeg,tile]
$ ls -l x.tif lzw.ome.tif 
-rw-rw-r-- 1 john john 108190 Mar 23 12:26 lzw.ome.tif
-rw-r--r-- 1 john john 103344 Mar 23 14:26 x.tif
```

So both files are chrominance-subsampled YCbCr, as you can see from `tiffinfo` on the one that libvips wrote:

```
$ tiffinfo x.tif 
=== TIFF directory 0 ===
TIFF Directory at offset 0x18fa8 (102312)
  Image Width: 640 Image Length: 480
  Tile Width: 128 Tile Length: 128
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
```

But the bioformats one is:

```
$ tiffinfo lzw.ome.tif 
=== TIFF directory 0 ===
TIFF Directory at offset 0x8 (8)
  Image Width: 640 Image Length: 480
  Tile Width: 256 Tile Length: 256
  Resolution: 28.346, 28.346 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: ...
  Software: OME Bio-Formats 6.12.0
```

So they are missing the JPEG data (could they be using the obsolete JPEG in TIFF encoding?), and it has the wrong photometric interpretation.

**Comment by jcupitt** [comment]
I uploaded the libvips one here:

http://www.rollthepotato.net/~john/x.tif

It seems to work in most viewers.

I'd open a bug report on qupath or bioformats.

**Comment by frmdstryr** [comment]
Will do, thanks for taking a look!

I was curious if any files exported like that could be salvaged.  I used tiffile to overwrite the photometric tag and it works perfectly now with vips, kirta, and others so it is definitely that.

```py
import tifffile
with tifffile.TiffFile('lzw.ome.tif', mode='r+') as f:
    f.pages[0].tags['PhotometricInterpretation'].overwrite(tifffile.PHOTOMETRIC.YCBCR)
```

Thank you!
