### ISSUE TITLE
PR #3287 broke support for some tiff files

### ISSUE THREAD

**Issue by manthey** [libvips/libvips#3403]
I have a small OME tif that I use to test various functions.  In libvips 8.14.1 it worked and in libvips 8.14.2 I get an `tiff2vips: tile size out of range` error.

This is a file with three main images, each at three resolutions.  The tile size on all layers is reported as 1024 x 1024, and the main images are 2106 x 2016 pixels in size.  The lowest resolution images are 527 x 504, but still list a tile size of 1024 x 1024.  The logic introduced here: https://github.com/libvips/libvips/blob/master/libvips/foreign/tiff2vips.c#L2937-L2938 makes it so this file fails to open.

As noted in PR #3287, in the real world, tile sizes are frequently larger than image sizes.  This is especially true in pyramidal images files with the lowest resolution image is almost always smaller than a full tile.

Here is link to a public test file: https://data.kitware.com/api/v1/file/5cb9c6288d777f072b4e85f0/download

I think the change in PR #3287 is overly restrictive and should be rolled back or changed.

This was tested on a local build in an Ubuntu 20.04 environment with the source for libvips 8.14.2 checked out of github.

**Comment by lovell** [comment]
Hi David, thanks for reporting this. I've relaxed the sanity check via PR #3404, which allows your sample image to be processed.
