### ISSUE TITLE
Request: Scharr edge detection

### ISSUE THREAD

**Issue by Zireael07** [libvips/libvips#3422]
Title. I see Sobel and Canny are on offer, but Scharr is conspicuously missing

**Comment by jcupitt** [comment]
Hi @Zireael07,

It's just a couple of lines of eg. python, but I agree it'd be useful to have an implementation built in. Let's tag this as an enhancement.

**Comment by Zireael07** [comment]
Thanks a lot, this means libvips/its official GUI should suit my use case well <3

Leaving this open because of the feature request itself

**Comment by jcupitt** [comment]
I made a PR for scharr and prewitt detectors, and made sobel a bit more accurate for non-uchar images.
