### ISSUE TITLE
Expected member name or ';' after declaration specifiers on windows

### ISSUE THREAD

**Issue by inloveable** [libvips/libvips#3431]
I'm been facing this problem for serveral times.

I tried to use libvips on my recent project for very simple purposes.

![微信图片_20230405195312](https://user-images.githubusercontent.com/88480407/230072596-0d776cf7-56c7-4afa-994a-3996aa857a96.png)

But I always enconter the same problem.The documentation said that I should just download the binaries then everywhing would work,I'm now so doomed.....Some body could help me with this?Please.....

**Comment by inloveable** [comment]
This error magically dispeared after I commented a line where the error cames from. I still don't know why and what's the outcoming of it.

**Comment by jcupitt** [comment]
Hi, could you copy paste the entire error message? Please don't post screenshots of error messages, they are hard to search for.

**Comment by inloveable** [comment]
Thank you for your reply,but I fixed this problem by commented one varriable(**singals),which I cant't recall the type,in gobject inner headers,which I couldn't remember either.
I understand that this might cause series disaster,but so far libvips works fine for me.

I still have one problem left though. When I use g_object_unref,I go LNK_2019 error on MSVC.And I don't understand which glib library should I directly link. I user CMake btw,so I have to link these libraries one by one on windows.

I wonder if you have any information about this?

**Comment by jcupitt** [comment]
You need libgobject for `g_object_unref()`.

What MSVC version are you using?

**Comment by inloveable** [comment]
![微信图片_20230406164623](https://user-images.githubusercontent.com/88480407/230324648-5ffc7ab9-350c-4ee4-981e-b017092b4d58.png)

My MSVC version.

**Comment by inloveable** [comment]
I managed to solve the linkage problem btw,thanks,turns out I'm tring to link my test program,but the qtcreator is actually linking my main program,which didn't link to any glib libraries in cmake.

**Comment by inloveable** [comment]
@jcupitt  Hi! This is my commented file,please have a look?



![微信图片_20230406165851](https://user-images.githubusercontent.com/88480407/230328189-2b95582b-1bc2-42bc-86f6-fb93b7f4bd4d.png)

You can see on line 157 where I commented the property(which is where my IDE brought me to).

However from my very limited experience on cpp,I highly doubt that this problem is  simply a complier bug,nothing wrong about libvips. It's just very depressing that I ran into this bug when I try to use C binding the last time（because it's hard for me to complie cpp binding for me back then),and so this time.

You may consider this issue closed,sorry for taking your time.

**Comment by jcupitt** [comment]
I would guess there's a stray `#define` in one of your includes that's breaking things. Maybe `#include` the glib headers before other files?

**Comment by inloveable** [comment]
I tried what you said.it would work.But extern "C" must be removed so as to pass the compile.

**Comment by inloveable** [comment]
Thank you!

**Comment by inloveable** [comment]
one more question plz. I read the documentation about dzsave.
![微信图片_20230406172444](https://user-images.githubusercontent.com/88480407/230334361-ae409797-5e09-41c1-af15-d643587e6068.png)

What is the sequence of these optional arguments?they don't actually match my code anyway
![微信图片_20230406172619](https://user-images.githubusercontent.com/88480407/230334735-a2ca7551-925b-435f-8907-192f50cdf30d.png)
