### ISSUE TITLE
Can't use dzsave on 8.14.2

### ISSUE THREAD

**Issue by exp111** [libvips/libvips#3433]
**Describe the bug**
When using libvips v8.14.2 dzsave isn't found. Using the latest windows binaries (from vips-dev-w64-all-8.14.2.zip).
Running `.\vips.exe dzsave` returns `vips.exe: unknown action "dzsave"`

**To Reproduce**
1. Get libvips from https://github.com/libvips/build-win64-mxe/releases/tag/v8.14.2
2. Run  `.\vips.exe dzsave`
3. See error

**Expected behavior**
dzsave should run

**Actual behavior**
dzsave isn't found

**Environment**
 - OS: Windows 10 19044.2728
 - Vips: v8.14.2

**Additional context**
v8.14.1 works fine. Also tried the other v8.14.2 x64 binaries, but the same issue occurs

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/issues/3354
