### ISSUE TITLE
Issue in vips_region_prepare_to random rects with TIFF files

### ISSUE THREAD

**Issue by DavidStorm** [libvips/libvips#3439]
Hi. I have a process to take parts of source image and copy in destination image in different positions. My code works with jpg, psd... files, but does not work with tiff files

Environment:

LibVips (C and C++) from Drew in MacOS Ventura 13.2.1 and Xcode Version 14.3.
Vips 8.14.1

Sample Code:

This is part of my filter function. InitRepeat and GetNextRect provide valid rects from different positions in source file a valid rects for destination.

static int
repeat_gen(VipsRegion *or, void *seqPtr, void *inPtr, void *riPtr, gboolean* stop)
{	
.....
	if(InitRepeat(&localX, &localY, &localWidth, &localHeight, &globalX, &globalY, &globalWidth, &globalHeight))
	{
		do
			{
				VipsRect irect;

				int gX = globalX-ri->offsetX;
				int gY = globalY-ri->offsetY;
				
				irect.left = localX;
				irect.top = localY;
				irect.width = localWidth;
				irect.height = localHeight;
			
				if( vips_region_prepare_to( ir, or, &irect, gX, gY ) )
					return( -1 );
			}

		while (GetNextRect(&localX, &localY, &localWidth, &localHeight, &globalX, &globalY, &globalWidth, &globalHeight));
	}
.....
}

Using jpg as source, works.
Using tif as source, does not works because vips_region_prepare_to fail. I get this error in the console after several calls in my gen function:
VIPS_LOG: : error in tile 0 x 0
VIPS_LOG: : error in tile 0 x 80
VIPS_LOG: : error in tile 0 x 96
VIPS_LOG: : error in tile 0 x 112
VIPS_LOG: : error in tile 0 x 384
VIPS_LOG: : error in tile 0 x 400
It seems it’s not possible read tiles on top of the image if they are read before.

Source images:
![Julia](https://user-images.githubusercontent.com/15983218/231820131-8e780cbf-69a1-40cb-8b26-b5757c62cb26.jpg)

[Julia.tif.zip](https://github.com/libvips/libvips/files/11224165/Julia.tif.zip)

Expected behavior:
![DistanceCropRapportV-OK](https://user-images.githubusercontent.com/15983218/231819873-7ebb7358-0ebc-4608-ae9e-e2c2dd4e1666.jpg)

Actual behavior:
![DistanceCropRapportV-BAD](https://user-images.githubusercontent.com/15983218/231820100-68985a92-aafd-45c8-bdb6-93a0744a130b.jpg)

There is any call to read random titles in tiff files?
Any idea how to fix the problem?

**Comment by jcupitt** [comment]
Hi @DavidStorm,

Sorry, you'd need to post a complete runnable example before I could say what was wrong.

Just a guess, but perhaps you are using sequential mode and the tiff image is striped?

You probably don't need to use regions. I would expect crop and insert to be simpler and just as quick (and need less memory), though it depends on your exact requirements.

**Comment by DavidStorm** [comment]
Hi John,

Don’t worry. I compiled a version with debug information and I saw TIFF_DONTCHECK_SEQUENTIAL was not defined.
Recompiling the version, the code works again.

You can close the issue.
Thanks.
