### ISSUE TITLE
webpsave_timeout test runs even when libwebp is not available

### ISSUE THREAD

**Issue by thesoulless** [libvips/libvips#3446]
## Bug report

**Describe the bug**
Meson does not check libwebp availability before running `webpsave_timeout` test.

**To Reproduce**
1. Use centos:7 as the base image (or any other distros where libwebp is not available)
2. Build with meson (meson setup build && cd build && meson compile)
3. Run `meson test`, it will fail on webpsave_timeout test case

**Expected behavior**
Run the test only if `libwebp_dep.found()`

**Actual behavior**
Running the test regardless of `libwebp_dep.found()` result.

**Environment**
 - OS: CentOs 7
 - Vips: 8.14.2

**Comment by kleisauke** [comment]
Fixed with commit afe6c606c998e193d80246fa5bc6d9acf5ee18d2.
