### ISSUE TITLE
PDF load with pdfium does not support PDF forms

### ISSUE THREAD

**Issue by lucaslenz** [libvips/libvips#3455]
Hello! Not sure that this is a correct place for reporting, but I didn't found any related information to this.

Environment:

Vips 8.14.2 with PDFium Build 5715

What I need to do:
I want to load a PDF that contains inputs and checkboxes with user input in it. 

What I tried to do:
When I load and save the file using PDFium and libvips the user input is blank, meaning the page gets rendered correctly but without the values of the form. When using libvips with Poppler the user input is contained within the image. I don't really want to use Poppler because of the AGPL license. 

I'm not quite sure where the problem here is, but I can imagine that there are some flags need to be set when using PDFium to extract the input of the form elements. No doubt PDFium is able to render it. But that's only guessing as I'm not really into this topic.

For now I cannot really say anything else of interest. I can not provide the specific PDF file but I could create one to help reproduce the issue.

Thanks in advance!

**Comment by jcupitt** [comment]
Hi @lucaslenz,

You could try viewing your test PDF in Chrome -- it uses pdfium to render the browser view, so if it works there, libvips should be able to support it.

**Comment by lucaslenz** [comment]
HI @jcupitt,
thanks for the fast response!

I already did that. That's why I said `No doubt PDFium is able to render it`. So technically it should be possible.

**Comment by jcupitt** [comment]
Ah OK. Then a test PDF would be helpful, thank you.

**Comment by lucaslenz** [comment]
This is an example PDF with user content in it: https://file.io/1swRtMQRekAC

Here is an Image of the PDF
![Bildschirmfoto 2023-04-21 um 13 04 59](https://user-images.githubusercontent.com/19750938/233620858-6331305a-d91c-41ab-beac-7390cd6d3b23.png)

And this is the extracted image.
![example](https://user-images.githubusercontent.com/19750938/233621419-2b72ecfc-252e-47f5-823c-f1ca36c0d65c.jpg)

**Comment by jcupitt** [comment]
Thanks for the test file -- I agree I see the issue here too with pdfium 4290, while poppler and chrome are fine.

I'll see if there's a simple fix.

**Comment by kleisauke** [comment]
I just opened PR #3456 for this.
