### ISSUE TITLE
vipsthumbnail: handling b-w with strip

### ISSUE THREAD

**Issue by esiqveland** [libvips/libvips#3461]
We are doing resize of lots of photos. We get all kinds of different formats that we first decode and produce a jpeg if it is not already jpeg. We are testing using `vipsthumbnail` for the second step that is resizing to a more uniform size.

According to https://github.com/libvips/libvips/blob/master/doc/Using-vipsthumbnail.md its recommended to set `--export-profile srgb` with `strip` option to save space on metadata, which is great! But it seems to have some trouble with grayscale sources.

See `input.jpg`:
```
$ vipsheader input.jpg
input.jpg: 750x1334 uchar, 1 band, b-w, jpegload
```

```
$ vipsthumbnail --export-profile sRGB --size '240>' -o 'out.jpg[Q=75,strip]'  input.jpg 
(vipsthumbnail:97799): VIPS-WARNING **: 11:30:09.424: profile incompatible with image

(vipsthumbnail:97799): VIPS-WARNING **: 11:30:09.425: profile incompatible with image
vipsthumbnail: unable to thumbnail input.jpg
icc_transform: unable to load or find any compatible input profile
```

It seems like it can not produce an output compatible with sRGB colourspace, which makes sense I guess. Could it automatically fallback to handle it as b-w or would that break with the requirements for `strip`, and that it will assume sRGB encoding? In this case it works as expected when we remove `--export-profile sRGB`, but would that leave the same benefits together with `strip`?

**Environment**
 - OS: ubuntu 20.04
 - Vips: 8.14.2 (built from source)

```
$ vipsthumbnail --version
vips-8.14.2
````

**Comment by jcupitt** [comment]
(it's `--export-profile srgb`, so all lower case, I expect you know)

**Comment by esiqveland** [comment]
Ok, that is great, thank you! I can confirm it works from latest commit on 8.14 branch.

Would it make sense if the result was `1 band, b-w` ? Would that save more disk space?

**Comment by jcupitt** [comment]
Yes, good idea, though you'd need to test the image before thumbnailing it. Something like (in python for convenience):

```python
image = pyvips.Image.new_from_file(filename)
if image.bands == 1:
  profile_name = "sgrey"
else:
  profile_name = "srgb"
thumb = pyvips.Image.thumbnail(filename, 240, export_profile=profile_name)
thumb.write_to_file(output_filename, strip=True)
```

**Comment by esiqveland** [comment]
Thank you for the help! I think we can close this one.
