### ISSUE TITLE
Release v8.14.2 should indicate dzsave has been removed

### ISSUE THREAD

**Issue by ianengelbrecht** [libvips/libvips#3468]
This is not indicated in the list of changes. Refer to issue #3354

**Comment by jcupitt** [comment]
Hi @ianengelbrecht,

dzsave is no longer enabled in the pre-built windows binaries, but it still works fine everywhere else. 

You can build 8.14.2 yourself and enable it, or use libvips on any other platform.

**Comment by ianengelbrecht** [comment]
Thanks @jcupitt, okay I understand then.
