### ISSUE TITLE
vipsthumbnail change image colors when using --export-profile srgb

### ISSUE THREAD

**Issue by romanzks** [libvips/libvips#3479]
```bash
vipsthumbnail input.jpg --size 1920 --export-profile srgb -o oputput.jpg
```

**Debian GNU/Linux 11**
**vips-8.14.2**

---

`input.jpg`
![source](https://user-images.githubusercontent.com/1418745/235897775-7043c432-0414-40e8-90ca-7884e4b0708c.jpg)

`oputput.jpg`
![output](https://user-images.githubusercontent.com/1418745/235898205-5cf9a7a7-a2ce-4059-bde3-21606c31d78b.jpg)

**Comment by kleisauke** [comment]
I'll investigate, providing an explicit fallback ICC profile seems to workaround this. For example:
```console
$ vipsthumbnail input.jpg --size 1920 --import-profile srgb --export-profile srgb -o output.png
```

`output.png`:
![output](https://user-images.githubusercontent.com/12746591/236412074-be954ec5-2e2b-42b9-a9bf-fa8cf2029714.png)

This ensures that lcms2 takes care of the colourspace conversions when the input image has no ICC profile (i.e. this image), or if the profile embedded in the input image is broken.

**Comment by kleisauke** [comment]
The builtin sRGB <-> XYZ  colour conversion seems not to be the issue.
```console
$ vips colourspace input.jpg x.v xyz
$ vips colourspace x.v x.png srgb
```

But this will change the colors a bit:
```console
$ vips icc_export input.jpg x2.png --output-profile srgb --pcs xyz
```

Perhaps we need to pass the XYZ values to lcms2 differently (D65 versus D50?), or perhaps there's a issue with XYZ to sRGB conversion in lcms2 (precision/optimization error?).

**Comment by kleisauke** [comment]
> Perhaps we need to pass the XYZ values to lcms2 differently (D65 versus D50?)

This seems to be the culprit. I just opened PR #3491 for this.
