### ISSUE TITLE
How to get the raw pixel data of an image via the command-line?

### ISSUE THREAD

**Issue by aradalvand** [libvips/libvips#3493]
Hi there, sorry if this is a dumb question, but I'll appreciate it if you point me in the right direction:

Is there a way I can use the libvips command-line utilities to get the raw pixel data of an image, in the form of an array of RGB values?

There's this other program I want to use that does some special processing on an image (Blurhash, in case that's relevant), but it only receives a two-dimensional array of "linear(0-1) RGB values" (where the first dimension is the X axis and the second dimension is the Y axis) and I'm struggling to find out how I can use vips to obtain that necessary data from an image file as the input, for example, and then pass it to that program.

Thank you in advance.

**Comment by jcupitt** [comment]
Hi @aradalvand,

You could use CSV or PPM format, would that work?

```
$ vips crop mono.jpg x.csv 1000 1000 3 3
$ cat x.csv
81	82	81
76	76	76
72	71	69
```

So that's 3x3 pixels from (1000, 1000). If you only use the suffix, it'll write to stdout:

```
$ vips crop mono.jpg .csv 1000 1000 3 3
81	82	81
76	76	76
72	71	69
```

PPM is similar, but uses binary values, and allows RGB as well as greyscale. You'll have to parse the (very simple) header though.

Linear 0-1 is scRGB colourspace, so you could try:

```
$ vips crop k2.jpg .ppm 1000 1000 3 3 | vips colourspace stdin .pfm scrgb 
PF
#vips2ppm - 2023-05-16T22:56:14.277010+01
3 3
-1
�~�>|�`>�b�>�~�>|�`>�b�>�~�>�
]>�r�>�~�>|�`>�b�>�~�>|�`>�b�>�~�>�
]>�r�>�~�>|�`>�b�>�~�>|�`>�b�>�~�>�
]>�r�
```

To get get a binary float array.

**Comment by aradalvand** [comment]
@jcupitt Wow, thanks for the quick response!
Yes that's exactly what I was after, thank you very much!

**Comment by aradalvand** [comment]
@jcupitt One small thing: It seems like each pixel is represented here by one number, I actually need three values (R-G-B) for ever pixel. What am I missing?

**Comment by jcupitt** [comment]
No, CSV is only single-band images.

You can use `bandunfold` to 'unroll' the RGB image into a 3x wider mono image:

```
$ vips crop k2.jpg .ppm 1000 1000 3 3 | vips bandunfold stdin .ppm | vips colourspace stdin .csv scrgb 
0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21586053073406219	0.30946895480155945
0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21586053073406219	0.30946895480155945
0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21952623128890991	0.29177066683769226	0.27049782872200012	0.21586053073406219	0.30946895480155945
```

So each line is 'RGBRGBRGB'.
