### ISSUE TITLE
Pipeline cache invalidation/thrashing occurs for large sharpen then large shrink combination

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3538]
It looks like an area operation with a large radius followed by a large shrink can cause horrible cache trashing. For example:

```python
#!/usr/bin/env python

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1], sequential=True)

# 0.37s
# image = image

# 0.37s
# image = image.resize(0.1)

# 0.45s
# image = image.sharpen(sigma=8)

# 0.44s
# image = image.resize(0.1).sharpen(sigma=8)

# 26s
# image = image.sharpen(sigma=8).resize(0.1)

# 0.4s
image = image.sharpen(sigma=8).copy_memory().resize(0.1)

image.write_to_file(sys.argv[2])
```

That's with a 6k x 4k non-interlaced jpg. sigma 8 is about a 20 pixel diameter (40 pixels across) mask. The pipeline executes with a 16 pixel high window.

See https://github.com/libvips/libvips/discussions/3536 for context, thanks to @CoachRDeveloper for reporting this.

**Comment by CoachRDeveloper** [comment]
We are both using the full res image (and this perform sharpen on it) as well on smaller/low-res images and they need to be identical. That's is our business case.

The involved images are typically shiny objects with large similarly colored surfaces and therefore use quite a large radius for sharpen.

We are also performing tiling on the large image (for loading performance in a browser), so we can't perform sharpening on smaller/individual parts. So while I agree, it's impossible for me to use a smaller radius.

**Comment by jcupitt** [comment]
I think #3603 mostly fixes this. With git master libvips I now see 5.2s (was 26s).

**Comment by jcupitt** [comment]
The remaining difference goes if you remove the `access='sequential'`. With the seq in there I see:

```
$ time ./try342.py ~/pics/nina.jpg
real	0m5.329s
user	0m5.281s
sys	0m0.080s
```

And with it removed I see:

```
$ time ./try342.py ~/pics/nina.jpg
real	0m0.689s
user	0m4.568s
sys	0m0.157s
```

So the CPU used is similar, but there's now some parallelism.

**Comment by CoachRDeveloper** [comment]
Do you have a schedule when to release this fix and for which release?
