### ISSUE TITLE
OpenSlide: JPEG parameter struct mismatch: library thinks size is 600, caller expects 632

### ISSUE THREAD

**Issue by chengdonglin** [libvips/libvips#3539]
when I use the next code to generate tiff file, I use the qupath open it occur the error: OpenSlide: JPEG parameter struct mismatch: library thinks size is 600, caller expects 632，and openslide lib can read the file

import pyvips

tiles_across = 34
tiles_down = 16

tiles = [pyvips.Image.new_from_file(f"D:\\test\\ttt\\{x}_{y}.jpg", access="sequential")
         for y in range(tiles_down) for x in range(tiles_across)]
im = pyvips.Image.arrayjoin(tiles, across=tiles_across)

im.write_to_file("ljh.tiff", compression="jpeg", Q=90, tile=True, pyramid=True)

my system is ubuntu, install libvips by apt-get

**Comment by jcupitt** [comment]
Hi again @chengdonglin,

> I use the qupath open it occur the error: OpenSlide: JPEG parameter struct mismatch: library thinks size is 600, caller expects 632，

That means your qupath has been built against one version of libjpeg, but it is seeing a different version at runtime.

Perhaps you are using Windows and you have set your PATH variable?

**Comment by jcupitt** [comment]
I would not set PATH on Windows, it will probably break other programs. I think qupath has stopped working because of this.

**Comment by chengdonglin** [comment]
> 

yes,  when I cancel the PATH, It work. Grateful！
