### ISSUE TITLE
A problems in determining the file type of imput images

### ISSUE THREAD

**Issue by senbaikang** [libvips/libvips#3544]
## Bug report

**Describe the bug**
I am developing an R package with c++ code processing large image files using libvips. However, I encounter a problem in determining the file type of input images, where function `g_type_from_name()` keeps returning zero. This is the point where the programme exits. If I extract the c++ code out of the R context and feed exactly the same input, `g_type_from_name()` returns some large integers, and the image is successfully loaded.

**To Reproduce**
I cannot really provide a reproducible piece of code as the R context is rather specific.

**Expected behavior**
The file type of the input image should be identified, and the image should be able to be loaded.

**Actual behavior**
Unsuccessful identification of file type.

**Screenshots**
<img width="843" alt="Screenshot 2023-06-21 at 17 35 37" src="https://github.com/libvips/libvips/assets/30857702/6d213625-b98e-4b95-ad3f-8a81aba78198">
<img width="901" alt="Screenshot 2023-06-21 at 17 35 47" src="https://github.com/libvips/libvips/assets/30857702/1dd453f9-e50c-463c-a178-2288de858e99">

**Environment**
(please complete the following information)
 - OS: macos 13.3.1
 - Vips: 8.15.0

**Comment by senbaikang** [comment]
Hi John,

Thank you for the quick reply! I am not calling `VIPS_INIT()` in the R version as it seems to be requiring the name of the application as an argument, and I am only calling functions from libvips. What would you suggest I should give it as an argument?

**Comment by jcupitt** [comment]
Just `""` (empty string) should be fine.

**Comment by senbaikang** [comment]
It works! Thank you very much for your help!
