### ISSUE TITLE
Vips dzsave iiif3 format: How can I change the id when creating info.json?

### ISSUE THREAD

**Issue by jbhanks** [libvips/libvips#3545]
I have been testing the iiif3 format for zoomable images, but to get the images working in my viewer (Openseadragon), I needed to change the "id" property in `info.json`. 

When I first create the tiled image, info.json looks like this:

```
{
  "@context": "http://iiif.io/api/image/3/context.json",
  "id": "https://example.com/iiif/test.jpg.iiif3",
  "type": "ImageService3",
  "profile": "level0",
  "protocol": "http://iiif.io/api/image",
  "tiles": [
    {
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16
      ],
      "width": 512
    }
  ],
  "width": 7852,
  "height": 8936
}
```

However, to make it work with my viewer, I have to change id to the path that my app will need to access, which is `"id": "static/dzi/oniontest.jpg.iiif3"`.  I could just find and replace, but it seems like there ought to be a way to specify what the id will be. And it would be nice if I could avoid the need to use the path as an id so that the file doesn't need to be changed every time the iiif3 folder is moved. Is that possible?

I was looking at [this documentation](https://www.libvips.org/API/current/Making-image-pyramids.html), but I don't see anything that explains how to change the `id` that is created.

This was the command I used to make the iiif3:

```
vips dzsave "/path/to/test.tif" test.jpg.iiif3 --layout iiif3  --tile-size 512 --suffix .jpg
```

**Comment by jbhanks** [comment]
Nevermind, I found the answer here: https://github.com/libvips/libvips/issues/1531

The `--id` option was all I needed.

**Comment by jbhanks** [comment]
The answer is the `--id` tag, which I found out about here:
https://github.com/libvips/libvips/issues/1531

**Comment by jcupitt** [comment]
Hi @jbhanks, the main dzsave docs are here:

https://www.libvips.org/API/current/VipsForeignSave.html#vips-dzsave
