### ISSUE TITLE
Warning: smartcrop: no property named `premultiplied' while Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs

### ISSUE THREAD

**Issue by a-bochilo** [libvips/libvips#3547]
## Bug report

**Describe the bug**
While compile app via gatsby develop command every time (when cache was cleared) next warning appears:

[ ] 0.005 s 0/2 0% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs

** (process:7844): WARNING **: 10:47:10.924: smartcrop: no property named `premultiplied'

Process number different every time.
And sometime error occurs and build become aborted. Next run have a chance to be successful but error could appear several times in a row.

**To Reproduce**
1. clone repository https://github.com/a-bochilo/gatsby-bug
2. install all the packages with 'npm i' command
3. run dev server with 'gatsby develop' command
4. watch the process in the terminal

**Expected behavior**
App compiled without any errors and warnings

**Actual behavior**
WARNING **: 10:47:10.924: smartcrop: no property named `premultiplied' appears

"Unspecified fatal error encountered, aborting." error appears.

**Screenshots**
![image](https://github.com/libvips/libvips/assets/103776395/2be7b433-a0d5-4f1a-93f2-a405c0ec4b06)
![image](https://github.com/libvips/libvips/assets/103776395/576ec051-1834-4b79-9eab-f9687e3a29ae)

**Environment**
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.11.3
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.51)
  npmPackages:
    gatsby: ^5.11.0 => 5.11.0 
    gatsby-plugin-image: ^3.11.0 => 3.11.0 
    gatsby-plugin-sharp: ^5.11.0 => 5.11.0 
    gatsby-source-filesystem: ^5.11.0 => 5.11.0 
    gatsby-source-filesystem-markdown-name: ^1.0.1 => 1.0.1 
    gatsby-transformer-remark: ^6.11.0 => 6.11.0 
    gatsby-transformer-sharp: ^5.11.0 => 5.11.0 
  npmGlobalPackages:
    gatsby-cli: 5.10.0

**Additional context**
The same issue has been opened on Gatsby https://github.com/gatsbyjs/gatsby/issues/38257 . I've been redirected here with it.

**Comment by lovell** [comment]
Hi, this is a warning that can be ignored. I've opened https://github.com/lovell/sharp/issues/3710 as an enhancement to silence it.

**Comment by a-bochilo** [comment]
> Hi, this is a warning that can be ignored. I've opened [lovell/sharp#3710](https://github.com/lovell/sharp/issues/3710) as an enhancement to silence it.

Hello!
Thanks for your reply and solution. But what about fatal error that occurs from time to time?

**Comment by kleisauke** [comment]
I've reported the `handler->pushed_handler == popped_handler` assertion failure here:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3036/diffs#note_1777987

Furthermore, the upcoming Windows builds will disable GLib assertions and checks via the `-Dglib_assert=false -Dglib_checks=false` build options.
