### ISSUE TITLE
dzsave performance

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3552]
Using this test image:

https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/CMU-3.zip

With git master libvips I see:

```
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 516s          
$ vips copy CMU-3.mrxs[autocrop,rgb] x.tif[tile,compression=jpeg] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 40.4s
```

So it can make a one layer TIFF 10x faster than a deepzoom pyramid, which seems strange. I suppose there's some caching or locking issue in dzsave.

**Comment by kleisauke** [comment]
It looks like the old libgsf-based dzsave also suffered from this. On 8.14, I see:
```console
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi --vips-progress --vips-leak
vips temp-2: 90531 x 138396 pixels, 24 threads, 128 x 128 tiles, 512 lines in buffer
vips temp-2: done in 296s          
vips_threadset_free: peak of 54 threads
memory: high-water mark 628.11 MB
$ du -h x.szi 
756M	x.szi
```

For comparison, here's the output of the libarchive-based dzsave:
```console
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi --vips-progress --vips-leak
vips temp-2: 90531 x 138396 pixels, 24 threads, 128 x 128 tiles, 512 lines in buffer
vips temp-2: done in 249s          
vips_threadset_free: peak of 56 threads
memory: high-water mark 629.06 MB
$ du -h x.szi 
783M	x.szi
```

**Comment by jcupitt** [comment]
I think it's not pyramid generation -- writing a single layer of tiles is just as slow:
 
```
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi[depth=one] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 343s
```

It ought to be quicker than TIFF save. That uses a single thread to compress all the output tiles, but dzsave compresses in parallel.

**Comment by jcupitt** [comment]
dzsave is running a pipeline for each tile it saves, and the slowness is the setup and teardown costs. Larger SZI tiles fix it:

```
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi[depth=one] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 347s          
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi[depth=one,tile-size=512] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 77.7s          
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi[depth=one,tile-size=1024] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 29.8s          
$ vips copy CMU-3.mrxs[autocrop,rgb] x.szi[depth=one,tile-size=2048] --vips-progress
vips temp-2: 90531 x 138396 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 23s          
```

I don't think there's a simple fix, unfortunately. I'll try profiling a bit to see if there are any obvious startup/shutdown issues.

**Comment by jcupitt** [comment]
... nothing obvious. 

Maybe dzsave could have a special path for the default save-tile-as-jpeg case (it must be the most common by a factor of 1000s) and call directly into libjpeg?

Other than that, I'm out of ideas heh. I'll close.

**Comment by jcupitt** [comment]
Experimental PR with a direct save mode: https://github.com/libvips/libvips/pull/3557
