### ISSUE TITLE
Monochrome heif with GRAY profile is loaded as RGB and causing `icc_transform` to fail

### ISSUE THREAD

**Issue by tongyuantongyu** [libvips/libvips#3556]
## Bug report

libvips always loads heif/avif as RGB(A). If input image is monochrome and has a profile in GRAY colorspace, this makes image and profile incompatible.

**To Reproduce**
1. Use Image (has png extension, but this is actually an avif file) ![kodim03_grayscale_gamma1.6.avif](https://github.com/libvips/libvips/assets/13075180/8f383528-f675-4bd3-9960-b429836dc35b) 
2. Run `vips icc_transform kodim03_grayscale_gamma1.6.avif output.png srgb`
3. A warning is printed, and output image is not converted to sRGB colorspace (from gamma 1.6).
```
(vips.exe:5680): VIPS-WARNING **: 16:34:45.641: profile incompatible with image
```

**Expected behavior**
No warning and output image is converted to sRGB colorspace.

**Actual behavior**
libvips complains about "profile incompatible with image" and output image is not converted to sRGB.

**Environment**
 - OS: Windows 11 (using MSYS2 distribution)
 - Vips: vips-8.14.2

**Comment by jcupitt** [comment]
Hi @tongyuantongyu,

I'm not sure how to detect mono images with libheif, it's not clear if the API supports this. I'll ask upstream.

**Comment by jcupitt** [comment]
Ah, there's an enhancement for this coming:

https://github.com/strukturag/libheif/issues/879

I'm not sure what the best workaround is in the meantime. If you can somehow detect that this is a mono AVIF you can do:

```
vips colourspace mono.avif x.v b_w
vips icc_import x.v x.png
```

And now the embedded profile will be applied correctly.
