### ISSUE TITLE
BGR565 interpretation

### ISSUE THREAD

**Issue by jstkdng** [libvips/libvips#3561]
Hello, I'm trying to add 16-bit depth support to my application but I wasn't able to find a way to read an image in the BGR565 format. There is the `VIPS_INTERPRETATION_RGB16` interpretation but I couldn't find information about how are the bits distributed. And even if it was RGB565, the way I found to convert from RGB to BGR with libvips doesn't work. This is how I normally do it.

```cpp
        // alpha channel required
        if (!image.has_alpha()) {
            const int alpha_value = 255;
            image = image.bandjoin(alpha_value);
        }
        // convert from RGB to BGR
        auto bands = image.bandsplit();
        auto tmp = bands[0];
        bands[0] = bands[2];
        bands[2] = tmp;
        image = VImage::bandjoin(bands);
```

Is there some other way I can achieve the BGR565 image format?

**Comment by jcupitt** [comment]
Hi @jstkdng,

BGR565 has 16 bits per pixel, with 5 for blue and red, and 6 for green. The reds are the 5 least-significant bits I think.

libvips RGB16 is 16 bits per colour channel, so 48 bits per pixel.

Are you trying to read a BGR image format? You'd need to get it as a 16 bit mono image (GREY16?) then shift and mask.

```python
r = (image & 31) << 3
g = (image >> 5) & 63
b = (image >> 11) & 31
rgb = r.bandjoin([g, b])
```

**Comment by jstkdng** [comment]
>libvips RGB16 is 16 bits per colour channel, so 48 bits per pixel.

oh, haha, that's quite the difference from what I had in mind

>Are you trying to read a BGR image format?

no, no. First, I'm reading an image with the sRGB interpretation.

```cpp
    image = VImage::new_from_file(path.c_str()).colourspace(VIPS_INTERPRETATION_sRGB);
```

after that I need to convert the pixels to the BGR format for displaying inside an X11 window. The method works fine with 8 bits per channels but breaks when trying to convert it to a BGR565 format.

**Comment by jcupitt** [comment]
Ah gotcha. That takes me back, I spent years doing X11 programming back in the 90s. I would write a scrap of C to fill the visual with 24-bit RGB generated by libvips.

Could you use a library to do this step for you? GDK, for example, has quite nice code to render RGB to any X11 visual.

I guess you've seen vipsdisp?

https://github.com/jcupitt/vipsdisp

That uses gtk4, then X11 via the vulkan backend.

**Comment by jstkdng** [comment]
Haha, thanks for the recommendations, but I already have a mature enough codebase that can create and dispay images on x11 windows. It's pretty fast and libvips helps a lot with that.

But then again, the ball is in libvips court even before the X11 code is called. Here's the code I'm using to manage libvips functionality. https://github.com/jstkdng/ueberzugpp/blob/master/src/image/libvips.cpp

It works fine for 8 bits per channel but no luck so far for the BGR565 format.

**Comment by jcupitt** [comment]
(though it'd be faster to do the packing in C, probably)
