### ISSUE TITLE
libvips seems failed to convert some large images to WebP

### ISSUE THREAD

**Issue by n0vad3v** [libvips/libvips#3568]
## Bug report

WebP Server Go is using libvips (https://github.com/davidbyttow/govips) for webp encoding/conversion, we've encountered an error on some specific image when `ReductionEffort` is set to 0, for example: https://inspirehep.net/files/3ce7ad44b03d925850182b268e87487e.png

Setting `ReductionEffort` to 4 can make conversion success.

Issue on our project is at https://github.com/webp-sh/webp_server_go/issues/234

**Describe the bug**

We've tested using Go and C using `ReductionEffort` equal to 0, for golang part, code is as below:
```go
package main

import (
	"fmt"
	"os"

	"github.com/davidbyttow/govips/v2/vips"
)

func main() {
	vips.Startup(nil)
	defer vips.Shutdown()
	// https://inspirehep.net/files/3ce7ad44b03d925850182b268e87487e.png
	image1, _ := vips.NewImageFromFile("3ce7ad44b03d925850182b268e87487e.png")

	ep := vips.WebpExportParams{
		Quality:         95,
		Lossless:        false,
		StripMetadata:   true,
		ReductionEffort: 0,
	}
	bytesData, _, err := image1.ExportWebp(&ep)
	if err != nil {
		fmt.Println(err)
	} else {
		os.WriteFile("1.webp", bytesData, 0644)
	}

}
```

For C part, code is as below by @bennythink.
```c
#include <vips/vips.h>

int main(int argc, char **argv) {
    if (VIPS_INIT(argv[0]))
        vips_error_exit(NULL);

    if (argc != 3) {
        vips_error_exit("usage: %s <input file> <output file>", g_get_prgname());
    }

    VipsImage *in;
    if (!(in = vips_image_new_from_file(argv[1], NULL)))
        vips_error_exit(NULL);

    if (vips_image_write_to_file(in, argv[2], "reduction_effort", 0, NULL))
        vips_error_exit(NULL);

    g_object_unref(in);

    return 0;
}

// gcc -I/usr/include/glib-2.0/ new.c `pkg-config --cflags --libs vips` -o convert_to_webp
```

For the golang part, the error message is: 

```
2023/06/18 06:23:28 [VIPS.info] vips__open_image_write: opening with O_TMPFILE
2023/06/18 06:23:28 [VIPS.info] vips__open_image_write: O_TMPFILE failed!
2023/06/18 06:23:28 [VIPS.info] vips__open_image_write: simple open
WARN[2023-06-18 06:23:34][210:main.webpEncoder()] Can't encode source image: vips2webp: unable to encode

Stack:
goroutine 53 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/davidbyttow/govips/v2/vips.handleVipsError()
	/home/nova/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.13.0/vips/error.go:38 +0x57
github.com/davidbyttow/govips/v2/vips.handleSaveBufferError(0xc000086960?)
	/home/nova/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.13.0/vips/error.go:31 +0x25
github.com/davidbyttow/govips/v2/vips.vipsSaveToBuffer({0x7f6d900061b0, 0x0, 0x2, 0x0, 0x1, 0x50, 0x0, 0x0, 0x1, 0x0, ...})
	/home/nova/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.13.0/vips/foreign.go:465 +0xb7
github.com/davidbyttow/govips/v2/vips.vipsSaveWebPToBuffer(0x7f6d900061b0, {0x1, 0x50, 0x0, 0x0, 0x0, {0x0, 0x0}})
	/home/nova/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.13.0/vips/foreign.go:386 +0x1f8
github.com/davidbyttow/govips/v2/vips.(*ImageRef).ExportWebp(0xc00010e0a0, 0x61?)
	/home/nova/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.13.0/vips/image.go:924 +0xc5
main.webpEncoder({0xc00007c070, 0x61}, {0xc0005c4d80, 0x53}, 0x50, {0x91b8f0?, 0x0?})
	/home/nova/Desktop/webp_server_go/encoder.go:202 +0x29a
main.convertImage({0xc00007c070, 0x61}, {0xc0005c4d80, 0x53}, {0x877eae, 0x4}, {0x0?, 0x0?})
	/home/nova/Desktop/webp_server_go/encoder.go:98 +0x2db
main.convertFilter.func2()
	/home/nova/Desktop/webp_server_go/encoder.go:55 +0x5c
created by main.convertFilter
	/home/nova/Desktop/webp_server_go/encoder.go:54 +0x215
 to WebP 
ERRO[2023-06-18 06:23:34][57:main.convertFilter.func2()] vips2webp: unable to encode
```

For the C part, error message is:

```
VIPS-INFO: 14:20:20.080: found /opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14
VIPS-INFO: 14:20:20.080: using configure-time prefix
VIPS-INFO: 14:20:20.080: VIPSPREFIX = /opt/homebrew/Cellar/vips/8.14.21
VIPS-INFO: 14:20:20.080: VIPSLIBDIR = /opt/homebrew/Cellar/vips/8.14.21/lib
VIPS-INFO: 14:20:20.080: prefix = /opt/homebrew/Cellar/vips/8.14.21
VIPS-INFO: 14:20:20.080: libdir = /opt/homebrew/Cellar/vips/8.14.21/lib
VIPS-INFO: 14:20:20.081: searching "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14"
VIPS-INFO: 14:20:20.081: loading "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14/vips-jxl.so"
VIPS-INFO: 14:20:20.083: loading "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14/vips-poppler.so"
VIPS-INFO: 14:20:20.088: loading "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14/vips-heif.so"
VIPS-INFO: 14:20:20.093: loading "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14/vips-openslide.so"
VIPS-INFO: 14:20:20.096: loading "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-modules-8.14/vips-magick.so"
VIPS-INFO: 14:20:20.098: searching "/opt/homebrew/Cellar/vips/8.14.21/lib/vips-plugins-8.14"
webpsave: unable to encode
webpsave: mux error
```

**But, if `ReductionEffort` is set to 4, the image can be successfully converted**, since we've tried the C version and the `vips` cli, we believe this might be a bug with https://github.com/libvips/libvips but not the Go wrapper https://github.com/davidbyttow/govips.

**To Reproduce**
1. Download image at  https://inspirehep.net/files/3ce7ad44b03d925850182b268e87487e.png
2. Run the golang code above with: `go run .`
3. See error

**Expected behavior**
This image should be converted successfully to WebP whatever the `ReductionEffort`  is.

**Actual behavior**
`webpsave: unable to encode`

**Environment**
This problem can be reproduced on different environments, on my host it's
 - OS: Fedora 36(6.2.15-100.fc36.x86_64) with vips-8.12.2-Tue Jan 25 09:34:32 UTC 2022
The problem can be reproduced when in container:
 - OS: Ubuntu 22.04 with libvips42:amd64             8.14.1-3

**Comment by BennyThink** [comment]
Also this could be reproduce by libvips cli
```bash
vips copy input.png "2.webp[reduction-effort=0]"
```

Even build on master branch (8.15), problem still exists

<img width="1144" alt="iShot_2023-07-18_14 45 21" src="https://github.com/libvips/libvips/assets/14024832/f25a0299-9cd8-4d63-8a42-30e04aba80b2">

**Comment by jcupitt** [comment]
It fails with `cwebp` too:

```
$ cwebp -m 0 renderHalos_TNG50-1-33_n29_gas_stars_withex_sm90.png -o x.webp 
Saving file 'x.webp'
Error! Cannot encode picture as WebP
Error code: 6 (PARTITION0_OVERFLOW: Partition #0 is too big to fit 512k.
To reduce the size of this partition, try using less segments with the -segments option, and eventually reduce the number of header bits using -partition_limit. More details are available in the manual (`man cwebp`))
```

So I think this is a webp error, unfortunately.

**Comment by jo-chemla** [comment]
I've come across the same problem - trying to convert a ~16k jpg file to webp via `vips copy` cli (with vips-8.15.1). 
The input has size 16383x16383 - which according to webp specification should be the maximum manageable resolution, eg [this google faq](https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be). 

I've narrowed down the buggy resolution using bisection and successive `vips-dev-8.15\bin\vips.exe -v resize input_16383.jpeg "test-resize.webp[reduction-effort=0]" 0.81259...` and it seems that on my win64 setup it is 13350x13350. Should we open a dedicated issue in the webp [official tracker](https://bugs.chromium.org/p/webp/issues/list?

**Comment by jcupitt** [comment]
Hi @jo-chemla, I would only open an upstream bug if you can reproduce it with `cwebp`, the official compressor.

**Comment by jo-chemla** [comment]
Thanks for getting back, I was indeed able to reproduce using `cwebp` windows build. Max resolutions handled are approximately the same, around 13k, but it does seem that other factors are also involved - I tried replacing different resolutions of mylarge images with complete noise via gimp or xnconvert, some webp conversion could work at resolution that would not for other. 

I'll submit a bug report to upstream and see if this can be fixed or if it is a limitation of the format itself - in which case the 16383² resolution is not achievable for all image configurations.

**Comment by jcupitt** [comment]
webp is not really suitable for large images. Google were planning (back in erm 2005 maybe?) to add a tiled mode for large image support, but they've mostly abandoned webp now, so it's unlikely to happen.

**Comment by jo-chemla** [comment]
Thanks for that info - I've read somewhere mentions about these initial tiled ambitions for webp - but did not know google had mostly abandonned the format entirely. So AVIF/AV1 is the new kid in town for compressed images for the web right? Thanks again for your time.

**Comment by jcupitt** [comment]
Yes, and JXL, which has a lot of the old webp devs behind it.

**Comment by n0vad3v** [comment]
We at WebP Server Go is planning to support JXL to, in PR: https://github.com/webp-sh/webp_server_go/pull/321 after reading https://cloudinary.com/blog/jpeg-xl-and-the-pareto-front
But both(AVIF/JXL) of them will take significantly longer to convert/encode(than WebP).

@jo-chemla 
> At least while [JPEGXL](https://caniuse.com/jpegxl) has better browser support.

From https://caniuse.com/jpegxl, only Safari can support jxl, you sure about "has better browser support"? 🤔

**Comment by jo-chemla** [comment]
Thanks for the reference post by cloudinary, very interesting read regarding timings, encoding speed and compression efficiency! Did not know about your webp/avif on-the-fly compression server, interesting as well although not for my usecase yet. 

And I meant `until` rather than `while`, will edit.

**Comment by jcupitt** [comment]
> But both(AVIF/JXL) of them will take significantly longer to convert/encode(than WebP).

Is this right? Perhaps I've misunderstood you.

JXL is quite a bit quicker than webp and produces much smaller files. JXL and AVIF produce similar levels of compression, but JXL is much faster.

AV1 is more likely to have hardware support, so if that's available, AVIF will be faster than JXL.

**Comment by n0vad3v** [comment]
@jcupitt I have a test script here:

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/davidbyttow/govips/v2/vips"
)

func main() {
	vips.LoggingSettings(nil, vips.LogLevelError)
	vips.Startup(nil)
	defer vips.Shutdown()

	img, err := vips.NewImageFromFile("1.jpg")
	if err != nil {
		panic(err)
	}

	imgByte, _ := img.ToBytes()
	fmt.Println("Original Image size: ", len(imgByte), "bytes")

	startTime := time.Now()
	imageBytes, _, _ := img.ExportWebp(&vips.WebpExportParams{
		Quality:  80,
		Lossless: false,
	})
	_ = os.WriteFile("input_webp.webp", imageBytes, 0644)

	fmt.Println("WebP took", time.Since(startTime))
	fmt.Println("WebP Image size: ", len(imageBytes), "bytes")
	fmt.Println("WebP compression ratio: ", float64(len(imgByte))/float64(len(imageBytes)))

	imageBytes, _, _ = img.ExportAvif(&vips.AvifExportParams{
		Quality:  80,
		Lossless: false,
	})
	_ = os.WriteFile("input_avif.avif", imageBytes, 0644)

	fmt.Println("AVIF took", time.Since(startTime))
	fmt.Println("AVIF Image size: ", len(imageBytes), "bytes")
	fmt.Println("AVIF compression ratio: ", float64(len(imgByte))/float64(len(imageBytes)))

	imageBytes, _, _ = img.ExportJxl(&vips.JxlExportParams{
		Quality:  80,
		Lossless: false,
		Effort:   3,
	})
	_ = os.WriteFile("input_jxl.jxl", imageBytes, 0644)

	fmt.Println("JXL took", time.Since(startTime))
	fmt.Println("JXL Image size: ", len(imageBytes), "bytes")
	fmt.Println("JXL compression ratio: ", float64(len(imgByte))/float64(len(imageBytes)))
}

```

`1.jpg` is a photo shot by camera(Sony A7M3), the output of this is:

```
Original Image size:  72000000 bytes
WebP took 376.251608ms
WebP Image size:  1437860 bytes
WebP compression ratio:  50.074416146217295
AVIF took 10.321691197s
AVIF Image size:  1617955 bytes
AVIF compression ratio:  44.500619609321646
JXL took 15.456902326s
JXL Image size:  16490855 bytes
JXL compression ratio:  4.366056217218573
```

**Comment by n0vad3v** [comment]
@jcupitt I think I got the reason why `jxl` is so slow in my cases, the parameters used for export is not the same with `cjxl` and `vips`, I've created a PR at https://github.com/davidbyttow/govips/pull/416

However, I found there seems a mismatch that `tier` option is not available in `cjxl`. 

From `libvips`:
```
/**
 * vips_jxlsave: (method)
 * @in: image to save
 * @filename: file to write to
 * @...: %NULL-terminated list of optional named arguments
 *
 * Optional arguments:
 *
 * * @tier: %gint, decode speed tier
 * * @distance: %gdouble, maximum encoding error
 * * @effort: %gint, encoding effort
 * * @lossless: %gboolean, enables lossless compression
 * * @Q: %gint, quality setting
 *
 * Write a VIPS image to a file in JPEG-XL format.
 *
 * The JPEG-XL loader and saver are experimental features and may change
 * in future libvips versions.
 *
 * @tier sets the overall decode speed the encoder will target. Minimum is 0
 * (highest quality), and maximum is 4 (lowest quality). Default is 0.
 *
 * @distance sets the target maximum encoding error. Minimum is 0
 * (highest quality), and maximum is 15 (lowest quality). Default is 1.0
 * (visually lossless).
 *
 * As a convenience, you can also use @Q to set @distance. @Q uses
 * approximately the same scale as regular JPEG.
 *
 * Set @lossless to enable lossless compression.
 *
 * Returns: 0 on success, -1 on error.
 */
```

The only `tier` I can find in `libjxl` are these:

```c
enum class SpeedTier {
  // Try multiple combinations of Glacier flags for modular mode. Otherwise
  // like kGlacier.
  kTectonicPlate = -1,
  // Learn a global tree in Modular mode.
  kGlacier = 0,
  // Turns on FindBestQuantizationHQ loop. Equivalent to "guetzli" mode.
  kTortoise = 1,
  // Turns on FindBestQuantization butteraugli loop.
  kKitten = 2,
  // Turns on dots, patches, and spline detection by default, as well as full
  // context clustering. Default.
  kSquirrel = 3,
  // Turns on error diffusion and full AC strategy heuristics. Equivalent to
  // "fast" mode.
  kWombat = 4,
  // Turns on gaborish by default, non-default cmap, initial quant field.
  kHare = 5,
  // Turns on simple heuristics for AC strategy, quant field, and clustering;
  // also enables coefficient reordering.
  kCheetah = 6,
  // Turns off most encoder features. Does context clustering.
  // Modular: uses fixed tree with Weighted predictor.
  kFalcon = 7,
  // Currently fastest possible setting for VarDCT.
  // Modular: uses fixed tree with Gradient predictor.
  kThunder = 8,
  // VarDCT: same as kThunder.
  // Modular: no tree, Gradient predictor, fast histograms
  kLightning = 9
};
```

There seems no `tier` option from `cjxl --help`:

```
 -e EFFORT, --effort=EFFORT
    Encoder effort setting. Range: 1 .. 9.
     Default: 7. Higher number is more effort (slower).
 -d maxError, --distance=maxError
    Max. butteraugli distance, lower = higher quality.
    0.0 = mathematically lossless. Default for already-lossy input (JPEG/GIF).
    1.0 = visually lossless. Default for other input.
    Recommended range: 0.5 .. 3.0. Allowed range: 0.0 ... 25.0.
    Mutually exclusive with --quality.

 --compress_boxes=0|1
    Disable/enable Brotli compression for metadata boxes (not provided = default, 0 = disable, 1 = enable).
 --brotli_effort=B_EFFORT
    Brotli effort setting. Range: 0 .. 11.
    Default: 9. Higher number is more effort (slower).
 --faster_decoding=0|1|2|3|4
    Favour higher decoding speed. 0 = default, higher values give higher speed at the expense of quality

```

**Comment by jo-chemla** [comment]
Note for people stumbling here, after submitting a bug request in upstream cwebp [here](https://bugs.chromium.org/p/webp/issues/detail?id=634#makechanges) they advised with this command which does indeed work for some 16383² images that were previously failing, but not all. 

```bash
cwebp.exe -m 4 -segments 1 -partition_limit 100 input_16383_noise.jpg -o x.webp
```
