### ISSUE TITLE
ABI version mismatch when compiling version 8.14.3

### ISSUE THREAD

**Issue by brandoncc** [libvips/libvips#3584]
Hello :wave:

I maintain the libvips buildpack for Heroku and I'm having an issue building the latest version. [Here](https://github.com/brandoncc/heroku-buildpack-vips/pull/38) is the PR that I'm working on. I'm experiencing this error when calling `vips --vips-version`:

```
 > [16/16] RUN cd /usr/local/vips   && echo "$ vips --vips-version" > "build/heroku-18.config.log"   && ./bin/vips --vips-version >> "build/heroku-18.config.log"   && echo "" >> "build/heroku-18.config.log"   && echo "$ vips --vips-config" >> "build/heroku-18.config.log"   && ./bin/vips --vips-config >> "build/heroku-18.config.log":
0.360
0.360 (vips:7): VIPS-WARNING **: 04:33:25.840: ABI mismatch
0.360
0.360 (vips:7): VIPS-WARNING **: 04:33:25.840: library has ABI version 0
0.360
0.360 (vips:7): VIPS-WARNING **: 04:33:25.840: application needs ABI version 42
0.360 vips_version: flag not 0, 1, 2
0.360 vips_version: flag not 0, 1, 2
0.360 vips_version: flag not 0, 1, 2
0.360 vips_version: flag not 0, 1, 2
0.360 vips_init: ABI mismatch
```

I switched to installing meson from pip3 as the one from apt is not new enough to meet the requirements to compile libvips. I can't think of any other issue that could be causing it since that is basically all I changed in the Dockerfile. I don't actually understand what an ABI mismatch is though, so it could definitely be something else that needs to be fixed.

Any pointers would be very much appreciated, thank you.

**Comment by lovell** [comment]
The ghost of upgrades past presents to you the vision that is https://github.com/libvips/libvips/issues/1863

**Comment by brandoncc** [comment]
I found that last week and tried to use it to debug the issue. No luck, unfortunately.

**Comment by brandoncc** [comment]
I just had a thought. Heroku added libvips to their build now...I bet I need to add something to the meson build to tell it to use the stuff I'm building and nothing that is built into the Heroku images (which didn't used to exist).

Any tips on how to do that would be greatly appreciated :-)

**Comment by jcupitt** [comment]
Yes, I think you are picking up the system libvips at runtime, not your libvips. You can set `LD_LIBRARY_PATH`, or maybe do something clever with runpath.

**Comment by brandoncc** [comment]
I was able to use your Dockerfile as I mentioned and everything seems to be working now. Thanks, sorry for bothering you!
