### ISSUE TITLE
Massive (200-400x) slowdown when resizing images containing special color profiles

### ISSUE THREAD

**Issue by lorenz** [libvips/libvips#3600]
**Describe the bug**
Massive (200-400x) slowdown when resizing images containing certain color profiles if an affine transformation is in the pipeline.

**To Reproduce**
1. Download [this](https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?cs=srgb&dl=pexels-daniel-xavier-1239291.jpg&fm=jpg) image.
2. Load the image
3. `vips_icc_transform(..., "srgb", "embedded", TRUE, NULL)`,
4. `vips_similarity(..., "angle", 1.4, NULL)`
5. `vips_resize(..., scale)` where scale needs to be more than 4x exactly.

**Expected behavior**
Performance within a reasonable band (0.5-1.5x of the performance for a similar image or the same image and a few pixel different size).

**Actual behavior**
A 200-400x slowdown with a single image taking upwards of 5 minutes. 

**Environment**
 - OS: No OS, special fully static libvips-containing binary on Linux 6.1 x86_64.
 - Vips: v8.14.3

**Additional context**
I think this is due to the fact that the affine transform accesses data pixel-by-pixel which means that the ICC transform has to create the transform context for every pixel, resulting in tens of millions of initializations. A flame graph shows 99.9% of the time spent in cmsDoTransform called by vips_colour_gen. I don't know why the issue occurs specifically 4x and more downscaling.

**Comment by jcupitt** [comment]
Hi @lorenz,

Yes, your guess sounds reasonable. For small transforms (not too much rotation, not too much zooming), affine will fetch pixels from the source in large blocks. For more radical transforms, it switches to single pixel fetches.

I guess the rule it uses to decide on the fetch style isn't right for this case. Perhaps we should revise it.

As a workaround, could you move the transform to the end of the pipeline?

**Comment by jcupitt** [comment]
Hi @lorenz,

I'm not able to reproduce this. I made a test program:

```python
#!/usr/bin/env python

import sys
import pyvips
import time

def benchmark(filename, scale):
    start = time.time()

    image = pyvips.Image.new_from_file(filename)
    image = image.icc_transform("srgb", embedded=True)
    image = image.rotate(1.4)
    image = image.resize(scale)
    image.copy_memory()

    end = time.time()
    print(f"scale {scale} took {end-start:.2f}s")
    
benchmark(sys.argv[1], 3.9)
benchmark(sys.argv[1], 4.1)
```

And ran it like this:

```
$ ./lorenz.py ~/pics/pexels-daniel-xavier-1239291.jpg 
scale 3.9 took 1.19s
scale 4.1 took 1.40s
```

That's with 8.14 HEAD.

**Comment by jcupitt** [comment]
I tried adding a `printf()` to `icc_transform.c`:

```C
/* Process a buffer of data.
 */
static void
vips_icc_transform_line( VipsColour *colour, 
        VipsPel *out, VipsPel **in, int width )
{
        VipsIcc *icc = (VipsIcc *) colour;

        printf("vips_icc_transform_line: width = %d\n", width);

        cmsDoTransform( icc->trans, in[0], out, width );
}       
```

It looks like it typically transforms the image in 40 pixel chunks (for me).

**Comment by jcupitt** [comment]
Ah you said downscaling, so I guess that's 1 / 4? I tried again:

```python
#!/usr/bin/env python

import sys
import pyvips
import time

def benchmark(filename, scale):
    start = time.time()

    image = pyvips.Image.new_from_file(filename)
    image = image.icc_transform("srgb", embedded=True)
    image = image.rotate(1.4)
    image = image.resize(scale)
    image.copy_memory()

    end = time.time()
    print(f"scale {scale} took {end-start:.2f}s")
    
benchmark(sys.argv[1], 1.0 / 3.999)
benchmark(sys.argv[1], 1.0 / 4.001)
```

And I see:

```
$ ./lorenz.py ~/pics/pexels-daniel-xavier-1239291.jpg 
scale 0.25006251562890724 took 0.70s
scale 0.2499375156210947 took 2.38s
```

I agree, that is odd. I'll look into it.

**Comment by lorenz** [comment]
Thanks for looking into this! It was pretty late yesterday and I was already debugging this for like 2 hours, so my reproduction steps maybe weren't the best. I took your script and adjusted it to make it trigger the exact behavior I'm seeing (>100x slowdown):
```
import sys
import pyvips
import time

def benchmark(filename, scale):
    start = time.time()

    image = pyvips.Image.new_from_file(filename)
    image = image.icc_transform("srgb", embedded=True)
    image = image.rotate(6.422569)
    image = image.resize(scale)
    image.copy_memory()

    end = time.time()
    print(f"scale {scale} took {end-start:.2f}s")
    
benchmark(sys.argv[1], 0.26)
benchmark(sys.argv[1], 0.24)
```
Please also run with `VIPS_CONCURRENCY=1`, at least on my system the second benchmark just uses a lot more cores (system is relatively big), making the benchmark very unfair.

**Comment by jcupitt** [comment]
I got a little more info with this:

```C
#!/usr/bin/env python

import sys
import pyvips
import time

image = pyvips.Image.new_from_file(sys.argv[1])
image = image.icc_transform("srgb", embedded=True)
image = image.rotate(1.4)
image = image.resize(float(sys.argv[2]))
image.copy_memory()
```

And uncommenting the `printf()` in `vips_colour_gen()`. I see:

```
$ VIPS_CONCURRENCY=1 ./lorenz.py ~/pics/pexels-daniel-xavier-1239291.jpg 0.26 | wc
    117    1638    9599
$ VIPS_CONCURRENCY=1 ./lorenz.py ~/pics/pexels-daniel-xavier-1239291.jpg 0.24 | wc
 345278 4833892 28085059
```

Haha, so `vips_colour_gen()` is called 3,000x more in the second case.

This looks like cache thrashing. I'll poke a bit more.

**Comment by jcupitt** [comment]
I think I found it, I'll open a PR. Let's continue discussion there.
