### ISSUE TITLE
Gaussblur + Resize => Very slow

### ISSUE THREAD

**Issue by huycn** [libvips/libvips#3616]
## Bug report

**Describe the bug**
It's really slow with certain pipeline configuration.

**To Reproduce**

Here is sample code, tested with v8.14.2:
```
#include <vips/vips8>
#include <fstream>
#include <chrono>
#include <string>

void read_file(const std::string& file_name, std::string& out_buffer) {
    std::ifstream file(file_name, std::ios_base::binary);
    file.seekg(0, std::ios_base::end);
    std::size_t length = file.tellg();
    file.seekg(0, std::ios_base::beg);
    out_buffer.resize(length);
    file.read(out_buffer.data(), length);
}

int main(int argc, char* argv[])
{
    if (vips_init("imageprocessor") != 0) {
        std::cerr << "Failed to initialize libvips" << std::endl;
        return 1;
    }

    std::string buffer;
    read_file("photo.jpg", buffer);

    VImage image = VImage::new_from_buffer(buffer.data(), buffer.size(), "");
    auto t0 = std::chrono::high_resolution_clock::now();
    image.gaussblur(10).resize(0.1).write_to_file("out.jpg");  //<<< pipeline is here
    auto t1 = std::chrono::high_resolution_clock::now();
    std::cout << "Duration: " << std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count() << " ms" << std::endl;

    // Cleanup the libvips library
    vips_shutdown();
}
```

The image `photo.jpg` above can be anything, with [this one](https://picsum.photos/id/12/2500/1667), it 
gives me:
```
Duration: 21126 ms
```
That is a whole 21 seconds!

Interestingly, if I change the line `image.gaussblur(10).resize(0.1).write_to_file("out.jpg");` to
```
image.draw_image(image.gaussblur(10), 0, 0);
image.resize(0.1).write_to_file("out.jpg");
```
it becomes much faster:
```
Duration: 165 ms
```
Even though it takes more processing.

Also, if change the resize ratio to 0.5, i.e. that line becomes `image.gaussblur(10).resize(0.5).write_to_file("out.jpg");`, it will run also fast:
```
Duration: 121 ms
```

**Expected behavior**
It should take that long to run the code above.

Thanks for the awesome library!

**Comment by jcupitt** [comment]
Hi @huycn, 

Yes, I think @lovell is right, this corner case has been fixed in git master libvips. With your photo and libvips 8.15 I see:

```
$ ./a.out 
Duration: 124 ms
```

**Comment by jcupitt** [comment]
(but thank you for the report! we only find horrors like this when people report them)
