### ISSUE TITLE
Memory leak in function im_dif_std

### ISSUE THREAD

**Issue by Hripsime-H** [libvips/libvips#3642]
hi, 
Memory leak in function im_dif_std
The memory leak is reported by a static analyzer tool developed at CAST (https://www.linkedin.com/company/cast-center).

Specifically, dynamic memory is allocated [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L112) and if function returns from [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L133) memory will remain not freed.
This scenario will work if one of `xsize` or  `ysize` is negative, due to cast from int to unsigned will be integer overflow and [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L112) memory will be allocated, but function call [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L132) will return -1 from [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L66) and function will return from [here](https://github.com/libvips/libvips/blob/8ae3e5eb9a8075b4951cb2d928b5a455bfe96fc8/libvips/deprecated/im_dif_std.c#L133) without freeing memory.

**Comment by jcupitt** [comment]
Hi @Hripsime-H,

Thank you for the report. This is a deprecated vips7 function from years ago and is not tested by us, not maintained, not documented, and is not exposed in any API (other than by a direct C call). It's only compiled into libvips if you pass the `-Ddeprecated=true` option to meson.

Having said that, you're correct that there is a leak here and we ought to plug it. Thanks for taking the time to open this issue.
