### ISSUE TITLE
free(): invalid pointer when using pyvips with Torch

### ISSUE THREAD

**Issue by EKami** [libvips/libvips#3655]
## Bug report

**Describe the bug**
If I try to load a Torchscript model but I import Pyvips before doing so, I get an invalid pointer exception.

**To Reproduce**
1. Use Ubuntu 22.04 (macOS seems to be more "fault-tolerant"). My machine has kernel `6.2.0-32-generic`.
2. Create a conda env using this `conda.yaml` file:
```
name: test
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
 - pytorch=2.0.1
 - cpuonly
 - pyvips=2.2.1
 - libvips=8.14.4
```
3. Move to this env `conda activate test` or `micromamba activate test`
4. Use the following script to create a model
```
import torch


class MyDecisionGate(torch.nn.Module):
    def forward(self, x):
        if x.sum() > 0:
            return x
        else:
            return -x

scripted_gate = torch.jit.script(MyDecisionGate())
scripted_gate.save("./mymodel.pt")
```
5. Now use the following script to load that same model:
```
import pyvips
import torch

model = torch.jit.load("./mymodel.pt")
print("I should be displayed if I didn't crash! Otherwise comment out the pyvips import")
```
You should get a:
```
❯ python load_model.py
free(): invalid pointer
[1]    67993 IOT instruction (core dumped)  python load_model.py
```
However, if the pyvips import is removed from the file above, the bad pointer crash does not happen.

**Expected behavior**
I do not expect to have a crash because of an import.

**Actual behavior**
It crashes

**Environment**
The `conda.yaml` is provided above

**Comment by jcupitt** [comment]
Hi @EKami, which libvips binary are you using? You can't use the ubuntu libvips with conda, you must use their libvips.

**Comment by EKami** [comment]
@jcupitt I'm using the one from conda as you can see in the conda.yaml file

**Comment by EKami** [comment]
@jcupitt Indeed, I used the following `Dockerfile`:
```
FROM ubuntu:22.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends --allow-unauthenticated\
    nano \
    wget \
    curl \
    ca-certificates \
    apt-transport-https \
    build-essential \
    pkg-config \
    libglib2.0-dev \
    libexpat1-dev \
    libgirepository1.0-dev \
    python3 \
    python-is-python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    ninja-build \
    python3.10-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install meson
RUN wget -O /tmp/libvips.tar.xz https://github.com/libvips/libvips/releases/download/v8.14.4/vips-8.14.4.tar.xz
RUN cd /tmp && tar xf /tmp/libvips.tar.xz && cd /tmp/vips-8.14.4 \
   && meson setup build-dir \
   && cd build-dir \
   && ninja \
   && ninja install

RUN ldconfig
COPY ./save_model.py /root/
COPY ./load_model.py /root/

RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install pyvips

# Do the same in a conda env
COPY ./conda.yml /root/
COPY ./install_micromamba.sh /root/

# Micromamba installation
RUN chmod +x /root/install_micromamba.sh && /root/install_micromamba.sh
ENV MAMBA_ROOT_PREFIX=/root/micromamba
RUN micromamba create --yes -f /root/conda.yml
```

`install_micromamba.sh`:
```
#!/bin/bash

# This script is intended to be used inside the pw-ai docker image
set -o errexit
set -o pipefail
set -e

MICROMAMBA_URL=https://micro.mamba.pm/api/micromamba/linux-64/latest

echo "Installing mamba..."
curl -Ls $MICROMAMBA_URL | tar -xvj bin/micromamba

ln -s /usr/bin/micromamba /usr/bin/mamba
ln -s /usr/bin/micromamba /usr/bin/conda
mamba config append channels defaults

export MAMBA_ROOT_PREFIX=/root/micromamba

micromamba shell init --shell=bash --prefix=/root/micromamba
source /root/.bashrc
```

`conda.yml`:
```
name: test
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
 - pytorch=2.0.1
 - cpuonly
 - pyvips=2.2.1
 - libvips=8.14.4
```

`load_model.py`:
```
import pyvips
import torch

model = torch.jit.load("./mymodel.pt")
print("I should be displayed if I didn't crash! Otherwise comment out the pyvips import")
```

`save_model.py`:
```
import torch


class MyDecisionGate(torch.nn.Module):
    def forward(self, x):
        if x.sum() > 0:
            return x
        else:
            return -x

scripted_gate = torch.jit.script(MyDecisionGate())
scripted_gate.save("./mymodel.pt")
```

And when I run the script in the system env it works fine but if I use the conda env I get:
```
(test) root@1b7fb756efa6:~# python load_model.py
free(): invalid pointer
Aborted (core dumped)
```

I'm not sure how I can actually report the issue on the conda package.
I still suspect the issue is coming from `libvips` or one of its dependencies, it probably has been compiled with more dependencies than the one I use in the docker image above.
I don't know which one tho, my C/C++ skills are too rusty to remember how to find the source of the issue :( .

**Comment by jcupitt** [comment]
Yes, it's a pain :( conda exists because on windows, without a package manager, getting a set of compatible DLLs is so difficult. Conda has its own private set of libraries and its own build system completely divorced from everyone else.

Because it's not used much (compared to the usual packaging systems), everything in conda is a bit wonky and unreliable. It's full of mysterious bugs and bizarre crashes. On linux, the platform packages (apt and friends) are usually much more stable.

**Comment by jcupitt** [comment]
I found the libvips package for conda on github:

https://github.com/conda-forge/libvips-feedstock

I'd report there.

**Comment by lovell** [comment]
The change in https://github.com/conda-forge/libvips-feedstock/pull/48/files doesn't look right to me, so perhaps get that reverted to start with?

**Comment by jcupitt** [comment]
Oooof yes, we don't guarantee ABI across minor API changes (only micro, and even that's not always possible).

**Comment by EKami** [comment]
I've just reported the issue [here](https://github.com/conda-forge/libvips-feedstock/issues/87), hopefully they'll be able to replicate the issue :)

**Comment by hmaarrfk** [comment]
conda-forge core member here

We may have ABI incompatibility (it hasn't been a problem yet...)

but the underlying issue is that the pytorch channel and the nvidia channel target the anaconda default channel which we are incompatible with.

Sorry for the noise, and thank you for helping troubleshoot.

@EKami in the future, please try to report issues to conda-forge first since the upstream may not always be aware of intricate integration details between conda channels.

**Comment by jcupitt** [comment]
Ah, thanks for the explanation, that makes sense.

Sorry I was rude about conda. We get a frustrating number of bug reports about the conda package and I was feeling grumpy in the heatwave.

**Comment by hmaarrfk** [comment]
i totally understand.

Your awesome package, among others, is what keeps me at conda-forge....

I wish that the larger operations would play nicely a little more. But often people get their minimum viable product going, and don't really worry about the rest.

The fundamental issue, is that pytorch changed its naming again, so now all the downstream packages are playing catchup.....
https://github.com/conda-forge/pytorch-cpu-feedstock/issues/187
