### ISSUE TITLE
ABI compatibility questions

### ISSUE THREAD

**Issue by hmaarrfk** [libvips/libvips#3656]
## Questions, enhancements, tips, etc.

In https://github.com/libvips/libvips/issues/3655#issuecomment-1711662418

you mentionned that you don't consider the library ABI compatible at all? Is that true,

if so I can add more restrictions at conda-forge. Let me know.

Thanks!

**Comment by jcupitt** [comment]
Hi @hmaarrfk,

I looked back though the git history and it seems we've not actually broken ABI back compat in 8.x, so perhaps the libvips feedstock was right to make that change to the pin in conda, from a pragmatic point of view. 

https://github.com/conda-forge/libvips-feedstock/pull/48/files

But we want to keep the ability to break ABI on minor versions if absolutely necessary, so from our point of view, I think the pin in the feedstock is probably now too loose.

This is off topic, but maybe you could you pin on the library ABI version instead? That might be a safer way to do it. Debian name the library as `libvips42.so.x.y`, with the 42 being the major ABI version.

**Comment by hmaarrfk** [comment]
The problem is that the tooling just isn't there at conda-forge to decouple the ABI pinnings from the package version.

Something like
https://github.com/conda-forge/libavif-feedstock/pull/15

can be done, and I should probably do it, but it means we would have to rebuild all downstream packages, for every version of libvips since the version is unrelated to the so version.

thanks for the clarity.

feel free to open an issue if you want to harmonize the so version and library version. 

but I got my answer!

No issue about the conda bug reports. I can see how this library might be particularly susceptible to it.
