### ISSUE TITLE
vips_colourspace error upon calling vips_hough_line

### ISSUE THREAD

**Issue by ewelot** [libvips/libvips#3664]
I'd like to learn about hough transformation and use vips_hough_line() for that. The goal is to use vips functionality to identify (and remove) satellite trails in astrophotography images which gets increasingly annoying due to StarLink and similar missions.
But any call to hough_line() on a grayscale image fails, e.g.:

`vips hough_line satellites.pgm hough_votes.pgm`

throws an error message

`vips_colourspace: no known route from 'matrix' to 'b-w'`

Do I need to prepare the input image in a specific way?
Thanks for help,
Thomas

**Comment by jcupitt** [comment]
Hi @ewelot,

You need to use a format that supports int32 pixels, so perhaps:

```
$ vips hough_line mono.jpg x.v
$ vips hough_line mono.jpg x.pfm
$ vips hough_line mono.jpg x.tif
$ vips hough_line mono.jpg x.csv
$ vips hough_line mono.jpg x.mat
```

nip2 can be handy for exploring the hough transforms:

![image](https://github.com/libvips/libvips/assets/580843/cfdbaf44-d077-46a7-b6d0-f6aeabc59e9b)

**Comment by ewelot** [comment]
Ah, it's some restriction on the output image format! So, maybe you could add a note on that to the documentation ... :)
Thanks for providing the solution so quickly!

**Comment by ewelot** [comment]
I'm having problems to understand the output of vips_hough_line(). While it works fine with my images and produces expected number of peaks clearly in the "votes" image, I am not able to translate the peak coordinates to a function representing the line(s), although the API documentation is quite clear on that matter.

Could you please describe an example on how to translate peak coordinates to a linear function equation (or simply r and alpha) taking into account the size of the parameter space and the size of the input image?

Another strange observation - at least to my current knowledge - comes from another experiment. Lets have an image A containing a straight line resulting in a single peak in the votes image at Xa,Ya. Then I remove some columns on the right side of A producing an image B which now has a somewhat smaller width. It should still contain the line unmodified, which means both the distance to the origin of the image (upper left corner) and the angle between line and x-axis have not changed. Surprisingly the peak in the votes image of B is off in both coordintes (Xb != Xa, Yb != Ya). What am I missing?

**Comment by jcupitt** [comment]
Here's a workspace that demos `hough_line`:

http://www.rollthepotato.net/~john/hough.ws

It looks like this:

![image](https://github.com/libvips/libvips/assets/580843/902cfe80-9cc2-461f-9371-56b55eb55c5e)

So it draws a line, takes the Hough transform, then recovers the line position from the transform. You can adjust the parameters and see all the images change.

**Comment by ewelot** [comment]
Thank you very much, I'll play with it (good opportunity to learn nip2 ...) and see how I can recover the line parameters.

**Comment by ewelot** [comment]
Sorry for re-opening this issue ...
I'am stll having problems to correctly recover line parameters from peak coordinates in the parameter space. Even in your workspace demo there seems to be odd results. Here is what I did:
- modify input image line angle to 60
- verify recovered line parameters being close to the input
- modify image width to 400 (which does not make any change to the line)
- find recovered line parameters to be off by unexpected amount

Are you sure the workspace is using the correct formulae to recover the line parameters?

**Comment by jcupitt** [comment]
You're right, it seems to work for non-square parameter space, but not for a non-square input image. I'll have a look.

**Comment by kleisauke** [comment]
Issue #4494 might be related here.

**Comment by jcupitt** [comment]
I updated the workspace, here's nip4 running it:

![Image](https://github.com/user-attachments/assets/b1bb26d9-1700-4866-b21d-ad33863f0b39)

http://www.rollthepotato.net/~john/hough4.ws

It seems to work fine for non-square images and non-square hough space.

**Comment by kleisauke** [comment]
I think commit 64b145578fb1cb1c67b1187b89e5327ca603901d should fix the original issue.

**Comment by kleisauke** [comment]
Confirmed, everything appears to be fixed now. Tested with:
```console
$ vips black x.jpg 100 100
$ vips hough_line x.jpg x.png
$ vips hough_line x.jpg x.v
$ vips hough_line x.jpg x.pfm
$ vips hough_line x.jpg x.pbm
$ vips hough_line x.jpg x.pgm
$ vips hough_line x.jpg x.pfm
$ vips hough_line x.jpg x.pnm
$ vips hough_line x.jpg x.tif
$ vips hough_line x.jpg x.csv
$ vips hough_line x.jpg x.mat
```

I'll close.
