### ISSUE TITLE
Compiling libvips on Amazon Linux 2 Docker

### ISSUE THREAD

**Issue by stuartrexking** [libvips/libvips#3684]
I need to compile the latest vips on Amazon Linux 2.

Using this [Dockerfile](https://gist.github.com/stuartrexking/1838c2574e0f15e1fe808961a982a8b7) I've managed to get vips compiling, but the tests are failing with

```
1/9 formats          FAIL             0.02s   exit status 1
>>> MALLOC_PERTURB_=242 /libvips-8.14.5/test/test_formats.sh

2/9 stall            SKIP             0.02s   exit status 77
3/9 seq              FAIL             0.04s   exit status 1
>>> MALLOC_PERTURB_=241 /libvips-8.14.5/test/test_seq.sh

4/9 connections      SKIP             0.04s   exit status 77
5/9 cli              SKIP             0.09s   exit status 77
6/9 webpsave_timeout SKIP             0.02s   exit status 77
7/9 descriptors      OK               0.08s
8/9 fuzz             OK               0.76s
9/9 threading        FAIL             1.09s   exit status 1
>>> MALLOC_PERTURB_=244 /libvips-8.14.5/test/test_threading.sh


Ok:                 2   
Expected Fail:      0   
Fail:               3   
Unexpected Pass:    0   
Skipped:            4   
Timeout:            0 
```
I know there is this [Dockerfile](https://github.com/jcupitt/docker-builds/tree/master/libvips-amazonlinux2) from @jcupitt but it's 3 years old and the build system has been replaced since then.

Any ideas on what I'm doing wrong?

**Comment by jcupitt** [comment]
I updated that dockerfile and it seems to work for me now. I found I had to set `LD_LIBRARY_PATH` (amz does not have `/usr/local/lib64` on the sys lib path). You can skip the GOI stuff.

**Comment by stuartrexking** [comment]
Thank you. I really appreciate it.

I've raised the potential to moving off AL2 to something like minideb with the powers that be. These kinds of moves are never simple though. 

If I can get it working on AL2 it will save me a whole lot of pain. Thanks again.

**Comment by jcupitt** [comment]
You'll probably have to build a lot of packages to get HEIC and AVIF working well on a 2019 linux, so there's pain in that direction too.

I'd also make a careful list of the file formats you need to support, get everyone to agree, and only include those loaders.

**Comment by stuartrexking** [comment]
@jcupitt We've moved to the latest debian. Thanks for your help and advice!
