### ISSUE TITLE
How to specify colour in vips_falsecolour?

### ISSUE THREAD

**Issue by prasadbandodkar** [libvips/libvips#3714]
Hi, 

I am looking for help converting a single band image to rgb. I have a bw single band image. I want to make it an rgb image and specify what colour I want it to be. I have been trying to do that with vips_falsecolour, but it chooses its own colour. How to specify the colour? Also, in general, when the documentation says "[NULL]-terminated list of optional named arguments", where do I find those optional arguments?

Thanks!

**Comment by jcupitt** [comment]
Hello @prasadbandodkar,

There are 100s of ways to colour an image. you'll need to be more specific. Do you want to pick a single RGB colour and use that to give your monochrome image a tint?

You can get a list of options at the command-line like this:

```
$ vips embed
embed an image in a larger image
usage:
   embed in out x y width height [--option-name option-value ...]
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
   x            - Left edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   y            - Top edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   width        - Image width in pixels, input gint
			default: 1
			min: 1, max: 1000000000
   height       - Image height in pixels, input gint
			default: 1
			min: 1, max: 1000000000
optional arguments:
   extend       - How to generate the extra pixels, input VipsExtend
			default enum: black
			allowed enums: black, copy, repeat, mirror, white, background
   background   - Color for background pixels, input VipsArrayDouble
```

Or check the docs:

https://www.libvips.org/API/current/libvips-conversion.html#vips-embed

**Comment by prasadbandodkar** [comment]
Hi @jcupitt, you are correct. I have an 5 bw images. They are all single band. I want to give these images a tint so I can see them in color. I was thinking of using the falsecolour function to expand each image into three bands and giving it a color. Is there a better way to do this? Could you point me in some general direction?

**Comment by jcupitt** [comment]
In Python you could write:

```python
#!/usr/bin/env python

import sys
import pyvips

tint = [195, 19, 6]
mono = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
rgb = (mono / 255 * tint).copy(interpretation="srgb")
rgb.write_to_file(sys.argv[2])
```

So scale your 0-255 image down to 0-1, then use that to scale the RGB value. Input pixels which are 255 will become [195, 19, 6] in the output. You have to tag the image as `srgb` with the copy operation or it'll get saved as a mono. This makes:

![x](https://github.com/libvips/libvips/assets/580843/e3408670-26dd-4560-b67a-2ad0b3ac22f9)

It won't be that quick -- you're doing a divide and multiply for each pixel. Instead, you can apply the transform to a linear lut and map the image through that.  You can do something much fancier, like mapping the mono image to a line through CIELAB:

```python
#!/usr/bin/env python

import sys
import pyvips

tint = [195, 19, 6]

# turn to CIELAB
tint = (pyvips.Image.black(1, 1) + tint).colourspace("lab", source_space="srgb")
tint = [x.avg() for x in tint.bandsplit()]

# start with an RGB greyscale, then go to LAB
lab = pyvips.Image.identity(bands=3).colourspace("lab", source_space="srgb")

# scale to 0-1 and make a weighting function
x = lab[0] / 100
weight = 1 - 4.0 * ((x - 0.5) * (x - 0.5))

# we want L to stay the same, we just weight ab 
lab = lab[0].bandjoin((weight * tint)[1:])

# and turn to sRGB
lut = lab.colourspace("srgb", source_space="lab")

image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
image = image.colourspace("b-w").maplut(lut)
image.write_to_file(sys.argv[2])
```

To make:

![x](https://github.com/libvips/libvips/assets/580843/a054861a-936f-4f65-a919-c376582f429c)

**Comment by prasadbandodkar** [comment]
That's beautiful! Thank you for it! Just one more thing - if I want to merge the 5 images into a single image, I should use vips_composite right? Is there a blend more you'd recommend to get the best results so that the images are better distinguishable?

**Comment by jcupitt** [comment]
It depends on the images. I think you'd need to share some samples..

**Comment by prasadbandodkar** [comment]
Hi @jcupitt, 

Apologies for the late response. Here is a sample image I am working with (clicking it with download the image which is about 2 GB in size): https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/sub-resolutions/Fluorescence/LuCa-7color_Scan1.ome.tiff. Libvips reads this image file as having 8 pages. The first 5 pages correspond to 5 channels and the other three are lower resolution images like thumbnails. Each channel is a greyscale 8-bit image. Among other things I am doing to each page(channel) of the image, I want to colorize each image with a predetermined color, and then merge the 5 images creating a single composite image, like the image attached.

Here is how I'm planning it:
- Extract the first 5 page as single multiband image (for any subifd) using` vips_bandjoin`.
- Use` bandsplit` to extract each band as a single image. (How to do this in C? pyvips has bandsplit method, but in C I could only find https://www.libvips.org/API/current/libvips-conversion.html#vips-extract-band which will not do it)
- Colorize each image using `vips_maplut` as you mentioned above
- Combine all the images using `vips_composite` by setting some `VipsBlendMode` 

Do you think this is the best way to do it?
![composite_luca](https://github.com/libvips/libvips/assets/19430510/44bc0e81-5958-478c-acb9-6d1d20aa9421)

**Comment by jcupitt** [comment]
Oh heh, yes I know that image well, it's in my test set.

I'll make you a tiny demo prog in python, hang on.

**Comment by jcupitt** [comment]
Something like:

```python
#!/usr/bin/env python3

import sys
import pyvips

if len(sys.argv) != 3:
    print("usage: ome_to_rgb in-file out-file")
    sys.exit(1)

in_filename = sys.argv[1]
out_filename = sys.argv[2]

# the RGB colours we give each of the image bands ... there can be MANY of
# these, we use the first N 
rgb_set = pyvips.Image.new_from_array([
    [200, 0,   0  ],
    [0,   200, 0  ],
    [0,   0,   200],

    [128, 0,   200],
    [0,   128, 200],
    [200, 0,   128],

    [0,   200, 128],
    [200, 128, 0  ],
    [128, 200, 0  ],

    # etc. add some more
])

# cut into pages
image = pyvips.Image.new_from_file(in_filename)
page_height = image.get("page-height")
pages = [image.crop(0, y, image.width, page_height)
         for y in range(0, image.height, page_height)]

# convert to a many-band image
image = pages[0].bandjoin(pages[1:])

# make a colour conversion matrix ... we take the first N rows of rgb_set,
# transpose and scale
matrix = (rgb_set / 255).crop(0, 0, 3, image.bands).rot90().fliphor()

# to RGB
image = image.recomb(matrix).copy(interpretation="srgb")

image.write_to_file(out_filename)
```

I see:

```
$ ./luca.py ~/pics/ome/LuCa-7color_Scan1.ome.tiff[n=5] x.png
```

To make:

![tn_x](https://github.com/libvips/libvips/assets/580843/2c471180-aaca-4fee-80c0-67d6836028f1)

`recomb` is a linear recombination (dot product):

https://www.libvips.org/API/current/libvips-conversion.html#vips-recomb

So for each of R, G and B, we scale and sum each input band by a column of coefficients, if that makes sense.

**Comment by jcupitt** [comment]
You'll want a better set of RGB colours, of course.

**Comment by prasadbandodkar** [comment]
Thank you @jcupitt! This works quite well!

**Comment by prasadbandodkar** [comment]
Thank you @jcupitt! This works quite well!
