### ISSUE TITLE
Use Mozjpeg on Mac

### ISSUE THREAD

**Issue by alexlsa** [libvips/libvips#3727]
Hello @jcupitt, `libvips` is great thank you

I installed libvips via `brew install vips` but it is not use `mozjpeg`. 
I want to use `mozjpeg` in `tiffsave` operation but `vips` uses `jpeg-turbo` as default. Is it possible to use `mozjpeg` without building from source on macOS 12.7 ? 

System information:

      System Version: macOS 12.7 (21G816)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Model Name: iMac
      Model Identifier: iMac17,1
      Processor Name: Quad-Core Intel Core i5

**Comment by jcupitt** [comment]
Hi @alexlsa,

libvips on macos uses mozjpeg by default. I see:

```
john@cheese ~/pics $ vips jpegsave k2.jpg x.jpg --trellis-quant
john@cheese ~/pics $ which vips
/opt/homebrew/bin/vips
```

ie. I can use mozjpeg features. You can see the formula here:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/v/vips.rb#L46

**Comment by alexlsa** [comment]
Thanks for fast reply @jcupitt 

I tried this command:
`vips tiffsave x.svs x.tif --tile --compression jpeg --trellis-quant` it say: `Unknown option --trellis-quant`

I tried this command:
`vips jpegsave x.png x.jpeg --trellis-quant` this worked and created x.jpeg file

If I run this `vips tiffsave x.svs x.tif --tile --compression jpeg` command in Windows OS,  file size for example 100Mb but in Mac, it's size bigger than 100Mb. According to this [message ](https://github.com/libvips/libvips/issues/1797#issuecomment-683421172) `mozjpeg` has bigger compress ratio. Am i wrong somewhere ?

**Comment by jcupitt** [comment]
> `vips tiffsave x.svs x.tif --tile --compression jpeg --trellis-quant`

libtiff doesn't support mozjpeg, so you can't pass these extra options in, unfortunately.

You could use mozjpeg in deepzoom, if's any help?

**Comment by alexlsa** [comment]
I understand, deepzoom option can be second option.  Why `vips8.14` on windows produce small file size according to mac ?

If I run this `vips tiffsave x.svs x.tif --tile --compression jpeg --vips-progress` command in windows it give this output: 

`(vips:18620): VIPS-WARNING **: 18:04:14.677: mozjpeg library likely detected. Disable emission of Huffman tables in JpegTables tag, and use optimize_coding...` Is it use mozjpeg ?

So can I achieve same compression with better quality on both Mac and Windows without using deepzoom ?

**Comment by jcupitt** [comment]
mozjpeg makes smaller images (up to about 30%) if you enable extra features, like trellis quantisation. libtiff doesn't let you do this, so you can't make smaller jpeg-compressed TIFFs with mozjpeg (I hope I have this right).

Yes, the windows binary uses mozjpeg, I think.

**Comment by jcupitt** [comment]
libtiff doesn't support the extra mozjpeg arguments, like `trellis-quant`. It works fine using mozjpeg as a regular jpeg library.

Mac and windows should be about the same. Do you have an example where you see different results?

**Comment by alexlsa** [comment]
In windows:

```
vips --version:
vips-8.14.5
```

```
vips tiffsave x.svs x.tif --tile --vips-progress --compression jpeg --Q=75
vips temp-4: 101032 x 87649 pixels, 16 threads, 128 x 128 tiles, 384 lines in buffer
vips temp-4: 0% complete
(vips:9104): VIPS-WARNING **: 13:26:33.177: mozjpeg library likely detected. Disable emission of Huffman tables in JpegTables tag, and use optimize_coding to avoid potential issues
vips temp-4: done in 244s
```
```
dir
10/23/2023  13:26       265,068,494 x.tif
03/08/2023  16:34     1,063,742,084 x.svs
```

In Mac:
```
vips --version:
vips-8.14.5
```
```
vips tiffsave x.svs x.tif --tile --vips-progress --compression jpeg --Q=75
vips temp-4: 101032 x 87649 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
vips temp-4: done in 176s
```

```
ls -lh
-rw-r--r--@ 1 ... ....  337M .... 13.36 x.tif
-rwxrwxrwx 1 ... ...    1.0G ....  2023 x.svs
```
As you see it is fast in Mac (I think it is not use mozjpeg because it is faster than my multicore win pc). I can also share original files with you but i have to anonymize it

**Comment by jcupitt** [comment]
I tried here and I agree the TIFFs produced by the windows build are about 20% smaller, I suppose due to differences in the jpeg library version. I don't think it's significant.

You can make it go a bit quicker with the `rgb` flag to SVS load:

```
$ vips copy H2022013912S1-1-22_0e16f82f-9ca3-7b7f-6b6b-d360ad89bf1e_100821.svs[rgb] x.tif[compression=jpeg,tile] --vips-progress
vips temp-2: 149882 x 86028 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-2: done in 48.9s          
$ ls -l x.tif
-rw-r--r-- 1 john john 609718312 Oct 23 13:03 x.tif

```

It might be worth trying that.

8.15 has some improvement to TIFF write and is a bit quicker again:

```
$ vips copy H2022013912S1-1-22_0e16f82f-9ca3-7b7f-6b6b-d360ad89bf1e_100821.svs[rgb] x.tif[compression=jpeg,tile] --vips-progress
vips temp-3: 149882 x 86028 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-3: done in 37.6s          
```

**Comment by alexlsa** [comment]
Thank you for your time @jcupitt I will try `vips8.15`

**Comment by sandstrom** [comment]
Can this be closed? Seems like it's resolved

(also perhaps something that could be moved to the discussions tab?)

**Comment by jcupitt** [comment]
You're right, let's close.
