### ISSUE TITLE
8.15.0 RC2 doesn't compile on i386

### ISSUE THREAD

**Issue by gcsideal** [libvips/libvips#3749]
**Conversion error on i386**
Just do a normal compilation on a i386 machine.

**To Reproduce**
1. Version 8.15.0 RC2 is used
2. Configured generic as I can tell, in a build subdirectory 'meson setup .. --buildtype=plain' was used.
3. For libvips/conversion/composite.cpp I get an error:
In function ‘void vips_composite_base_blend3(VipsCompositeSequence*, VipsBlendMode, v4f&, T*)’:
../libvips/conversion/composite.cpp:867:31: error: conversion of scalar ‘double’ to vector ‘v4f’ {aka ‘__vector(4) float’} involves truncation
  867 |                         f = B <= 0.5
      |                             ~~^~~~~~
../libvips/conversion/composite.cpp:893:31: error: conversion of scalar ‘double’ to vector ‘v4f’ {aka ‘__vector(4) float’} involves truncation
  893 |                         f = A <= 0.5
      |                             ~~^~~~~~

**Expected behavior**
Compile the library normally as on other architectures.

**Actual behavior**
You can see the full build log at: https://buildd.debian.org/status/fetch.php?pkg=vips&arch=i386&ver=8.15.0%7Erc2-1&stamp=1699387234&raw=0

**Environment**
 - OS: Debian GNU/Linux Sid, up-to-date
 - Vips: 8.15.0 RC2

**Additional context**
8.14.5 was recently compiled correctly on i386, so the above bug is a new regression: https://buildd.debian.org/status/fetch.php?pkg=vips&arch=i386&ver=8.14.5-1%2Bb1&stamp=1698013737&raw=0

**Comment by kleisauke** [comment]
Thanks for testing and reporting this! This reminds me of commit https://github.com/google/highway/commit/76e6863ce2fe72c139eaa6fc8654f470b3092cb4, does it work if you compile with `-fexcess-precision=standard`? If not, could you try applying this commit as patch?: https://github.com/kleisauke/libvips/commit/5dd9e169b4cc25287f8a91ded662429d8535668a.

**Comment by kleisauke** [comment]
As an aside, I noticed this in the log file:
```
...
Run-time dependency libarchive found: NO (tried pkgconfig and cmake)
...
image pyramid save with libarchive: NO
````

You might want to replace `libgsf-1-dev` with `libarchive-dev` and `liborc-0.4-dev` with `libhwy-dev` in the control file:
https://sources.debian.org/src/vips/8.15.0~rc2-1/debian/control

See e.g. the (draft) release notes:
https://github.com/libvips/libvips/blob/gh-pages-8.15/_posts/2023-10-10-What's-new-in-8.15.md

Also,  now that libspng is packaged in Debian (https://github.com/randy408/libspng/issues/237) you might want to replace `libpng-dev` with <code>lib**s**png-dev</code>, see:
https://www.libvips.org/2020/06/18/What's-new-in-8.10.html#libspng
https://www.libvips.org/2022/05/28/What's-new-in-8.13.html#libspng-save

**Comment by jcupitt** [comment]
Openslide4 and libdicom1 are out now. It would be great if those packages got added / bumped as well, there are lots of fantastic improvements.

openslide4 release notes here: https://github.com/openslide/openslide/releases/tag/v4.0.0

**Comment by kleisauke** [comment]
I was able to reproduce this, `-fexcess-precision=standard` doesn't make any difference and removing `-std=c++11` makes it compile fine(??). GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107358 might be relevant here.

I just opened PR #3750 for this.

**Comment by kleisauke** [comment]
It appears that the i386 build on `8.15.0~rc2-2` (which contains the above patch) is now successful.
https://buildd.debian.org/status/logs.php?pkg=vips&ver=8.15.0~rc2-2

Plus, the feedback was incorporated as well:
https://tracker.debian.org/media/packages/v/vips/changelog-8.15.0rc2-2

@gcsideal Thank you! FWIW, I had a look at the `Maybe-failed` results, and they all seem to be related to Meson's test timeout settings, except for PowerPC which strangely fails with `TIFFScanlineSize64: Computed scanline size is zero` during `tiffsave`.

> It would be great if those packages got added / bumped as well, there are lots of fantastic improvements.

We could try to open a merge request at https://salsa.debian.org/med-team/openslide, if appropriate.

**Comment by gcsideal** [comment]
> It appears that the i386 build on `8.15.0~rc2-2` (which contains the above patch) is now successful. https://buildd.debian.org/status/logs.php?pkg=vips&ver=8.15.0~rc2-2

 Yes, it is fixed.

> @gcsideal Thank you! FWIW, I had a look at the `Maybe-Failed` results, and they all seem to be related to Meson's test timeout settings, except for PowerPC which strangely fails with `TIFFScanlineSize64: Computed scanline size is zero` during `tiffsave`.

 Doubled the Meson test timeout, as Sparc64 is even slower it still fails. Might triple the timeout if a new Vips release is out.

> We could try to open a merge request at https://salsa.debian.org/med-team/openslide, if appropriate.

Openslide is not (properly) maintained in Debian. You may open a merge request and it might be accepted - but please be prepared that probably you will need to update it periodically.
