### ISSUE TITLE
`sequential` should order by allocation number, not y position

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3754]
At the moment, `sequential` orders request by y position. 

Instead, we should have some thread-private storage containing an *allocation number* -- small integers assigned in order from 0 by the threadpool allocation function (this can go in the base class) and order by that. `sequential` should stall threads which are out of order, and only let them though by strict allocation number.

With this change I think we can get rid of the first-tile-is-single-threaded logic, and we can remove the very expensive extra calls to sequential in the shrinker.

**Comment by jcupitt** [comment]
@kleisauke I know we discussed better fixes for the out of order issues in shrink, do you have any thoughts on this possible solution?

**Comment by kleisauke** [comment]
This sounds interesting, hopefully this would help for https://github.com/libvips/libvips/discussions/2757.

FWIW, here's a work-in-progress branch with the sequential line cache from shrinkv/reduceh removed (+ some other minor improvements): https://github.com/libvips/libvips/compare/master...remove-seq-from-reduce

**Comment by jcupitt** [comment]
I had a quick go: https://github.com/libvips/libvips/tree/thread-ordering-by-allocation-number

I'll test it and see if I can make it misbehave, and if there's any performance benefit.

**Comment by jcupitt** [comment]
I've not been able to provoke an out of order read, but performance is a bit crazy. Here's master:

```
$ time vips shrinkv st-francis.jpg x.jpg 2 --vips-progress
vips temp-7: 30000 x 13160 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-7: done in 10.8s          

real	0m10.889s
user	0m11.687s
sys	0m0.703s
```

And here's that branch:

```
$ time vips shrinkv st-francis.jpg x.jpg 2 --vips-progress
vips temp-5: 30000 x 13160 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-5: done in 8.24s          

real	0m8.339s
user	2m0.697s
sys	0m1.308s
```

So it's faster, but at a huge cost in user time. 

At the moment, threads queue up on `sequential` and wait their turn. Each time sequential moves on, it wakes *all* threads, one of them gets through, and the rest go back to waiting again.

We should probably have a hash of waiting threads and only wake up the right one.

**Comment by jcupitt** [comment]
I got rid of the `cond_broadcast`, so it now keeps a hash of waiting threads and only wakes the correct one. But user time is still terrible:

```
 time vips shrinkv st-francis.jpg x.jpg 2 --vips-progress
vips temp-5: 30000 x 13160 pixels, 32 threads, 128 x 128 tiles, 640 lines in buffer
vips temp-5: done in 8.6s          

real	0m8.739s
user	1m58.884s
sys	0m1.433s
```

Maybe we needed the caching? I'll try putting that back.

**Comment by jcupitt** [comment]
... thinking about this again, it can never work :( Not all output allocations will become input requests, so you can't use that to serialise things. Y position is the best we can do.

I made few other changes which were useful, I'll extract those for master, and see if I can merge with the changes from your commit too.

**Comment by jcupitt** [comment]
.... actually, I'm not sure I understand your changes in that branch. I'll wait for you to finish it!
