### ISSUE TITLE
VipsForeignSave: jfif is not a known file format

### ISSUE THREAD

**Issue by casperbrike** [libvips/libvips#3775]
## Bug report

**Describe the bug**
I'm using `ruby-vips` Ruby gem and trying to save an image in JFIF file format, however, it gives me `VipsForeignSave` error:
```ruby
img = Vips::Image.new_from_file 'img.jfif'
img.write_to_file 'new-img.jfif' # leads to VipsForeignSave: "new-img.jfif" is not a known file format (Vips::Error)
```
I debugged this issue a bit and found out that `write_to_file` calls `vips_foreign_find_save` function from libvips and `vips_foreign_find_save` raises `VipsForeignSave` error for JFIF file format. 

Interestingly that libvips does support JFIF format, for example, we can convert JPG image to JFIF and vice versa:
```bash
vips jpegsave img.jfif converted.jpg
vips jpegsave converted.jpg converted.jfif
``` 

However, if you try to resize a JFIF image then you'll get the same `VipsForeignSave` error:
```
vips resize img.jfif resized.jfif 0.5
```

**To Reproduce**
1. Use Image (GH doesn't allow uploading JFIF files so just remove `.txt` from filename after you download the image): [sun.jfif.txt](https://github.com/libvips/libvips/files/13620724/sun.jfif.txt)
2. Run `vips resize sun.jfif resized.jfif 0.5`
4. See `VipsForeignSave` error

**Environment**
 - OS: MacOS 13.2
 - Vips: 8.15

**Additional details**
I'm not really proficient at C but, probably, a solution would be to add `.jfif` here?
https://github.com/libvips/libvips/blob/fb94a2ff519c1a94f8f1f765207d11613e4f4b41/libvips/foreign/vips2jpeg.c#L907

**Comment by jcupitt** [comment]
Ah I just read the linked issue. I'm amazed that people are still using JFIF!

OK, I'll add `.jfif` as a suffix for jpeg save, although files saved this way might not be JFIFs, which feels bad.

**Comment by jcupitt** [comment]
... this will be in 8.15.1. I credited you in the changelog, I hope that's OK.

**Comment by ramses-lopez** [comment]
In case anyone runs into this issue using [brandoncc's heroku buildpack](https://github.com/brandoncc/heroku-buildpack-vips), I just created a PR to update `libvips` version on  a [fork](https://github.com/ramses-lopez/heroku-buildpack-vips). You can use my fork in case my PR is not merged.

Did some tests on my application and everything looks good
