### ISSUE TITLE
`vips_text` memory leak

### ISSUE THREAD

**Issue by Jacherr** [libvips/libvips#3783]
## Bug report

**Describe the bug**
Valgrind appears to report multiple leaks when using the `vips_text` function in a C program. It's entirely possible that I am missing steps to properly free all of the memory in this program, but as far as I have been able to deduce, there's nothing else that should be required. This does not happen when using a different function that creates a `VipsImage`, such as `vips_black`.

**To Reproduce**
Try using the following code:
```c
#include <vips/vips.h>

int main() {
	int i = VIPS_INIT("vips");
	vips_leak_set(TRUE);
	VipsImage *image;
	vips_text(&image, ".", NULL);
	g_object_unref(image);
	vips_shutdown();
	return i;
}
```
And compile using gcc -g -Wall [source file] -o output \`pkg-config vips --cflags --libs\`

From there run under Valgrind: `VIPS_LEAK=1 valgrind --leak-check=full [object file]`

**Expected behavior**
Valgrind reports no leaks.

**Actual behavior**
Valgrind reports a number of leaks.

**Screenshots**
![image](https://github.com/libvips/libvips/assets/40544507/3d324597-629c-4601-a200-a53c0ed40a23)

**Environment**
(please complete the following information)
 - OS: Ubuntu 20.04 running under Windows Subsystem for Linux (WSL2)
 - Vips: vips-8.14.5

**Comment by jcupitt** [comment]
Hi @Jacherr,

Did you find the libvips suppressions file? 

https://github.com/libvips/libvips/blob/master/suppressions/valgrind.supp

I have a `.valgrindrc` in my home directory containing:

```
$ more ~/.valgrindrc 
--suppressions=/home/john/GIT/libvips/suppressions/valgrind.supp
```

It should help remove false positives, though how many you are left with depends on your platform, libvips version, etc. etc.

**Comment by Jacherr** [comment]
I gave it a shot including the suppressions file in `.valgrindrc` and also just passing it manually, but I didn't seem to observe any difference in the output (still ~60kB in leaks). I always had a suspicion there weren't any real leaks because someone else would have caught on by now!

There's a lot of leaks, but most of them seem to be related to threading and the use of the cache:
![image](https://github.com/libvips/libvips/assets/40544507/c02ad951-9fd4-4374-931d-df181ce2a582)

In addition, libvips itself doesn't report any leaks when using `vips_leak_set`, so I'm inclined to believe it's just Valgrind being cranky.

**Comment by lovell** [comment]
Watch out for fontconfig's `FcInitLoadConfigAndFonts`, which mallocs lots of static/singleton-like structs for font details that are only freed when the process ends; [sharp.supp](https://github.com/lovell/sharp/blob/main/test/leak/sharp.supp) is your friend.

**Comment by jcupitt** [comment]
Yes, it's hard to write suppressions file that will work on most platforms. Simple things like the names of the libraries change.

The gold standard leak check is to put the operation in a loop and see if memuse climbs over 10,000 iterations. Even then, the leak could be in a lib that libvips uses, rather than libvips itself. You sometimes need some careful detective work to pin down the bug.

**Comment by jcupitt** [comment]
I added a couple more suppressions and on ubuntu 23.10 and libvips 8.16 I now see:

```
john@banana ~ $ valgrind --leak-check=full --num-callers=100 vips text x.png "hello world"
==1762124== Memcheck, a memory error detector
==1762124== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1762124== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==1762124== Command: vips text x.png hello\ world
==1762124== 
memory: high-water mark 8.70 KB
==1762124== 
==1762124== HEAP SUMMARY:
==1762124==     in use at exit: 2,241,053 bytes in 36,641 blocks
==1762124==   total heap usage: 78,911 allocs, 42,270 frees, 9,285,771 bytes allocated
==1762124== 
==1762124== LEAK SUMMARY:
==1762124==    definitely lost: 0 bytes in 0 blocks
==1762124==    indirectly lost: 3,346 bytes in 134 blocks
==1762124==      possibly lost: 0 bytes in 0 blocks
==1762124==    still reachable: 627,759 bytes in 3,717 blocks
==1762124==         suppressed: 1,470,668 bytes in 31,786 blocks
==1762124== Reachable blocks (those to which a pointer was found) are not shown.
==1762124== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1762124== 
==1762124== For lists of detected and suppressed errors, rerun with: -s
==1762124== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 38 from 38)
```
