### ISSUE TITLE
RW2 images: `Input file contains unsupported image format`

### ISSUE THREAD

**Issue by mertalev** [libvips/libvips#3794]
## Bug report

**Describe the bug**

RW2 images throw an error when processing with sharp.

**To Reproduce**

1. Use [this](https://github.com/immich-app/immich/files/12828953/P1250419.rw2.zip) image
2. Run the following code:

```
const sharp = require('sharp');
sharp('P1250419.rw2').toFile('test_rw2.jpg');
```

**Expected behavior**

It should process the image successfully, delegating to `magickload` as needed.

**Actual behavior**

It throws the error `Input file contains unsupported image format`.

**Environment**

libvips: 8.15.1 (built with meson setup build --buildtype=release --libdir=lib -Dintrospection=disabled -Dtiff=disabled)
ImageMagick: 7.1.1-13
sharp: 0.33.0
libraw: 0.21.1
OS: Debian Bookworm

**Additional context**

Using ImageMagick directly with `convert P1250419.rw2 test_rw2.jpg` processes the image without error.

The issue seems similar to #3733, but I can confirm that Olympus files are processed successfully as of 8.15.1.

**Comment by lovell** [comment]
```
$ dcraw -i -v P1250419.rw2

Filename: P1250419.rw2
Timestamp: Sat Sep 28 15:42:41 2019
Camera: Panasonic DMC-G80
ISO speed: 200
Shutter: 1/3200.0 sec
Aperture: f/2.5
Focal length: 12.0 mm
Embedded ICC profile: no
Number of raw images: 1
Thumb size:  1920 x 1440
Full size:   4816 x 3464
Image size:  4608 x 3464
Output size: 4608 x 3464
Raw colors: 3
Filter pattern: BG/GR
Daylight multipliers: 2.613800 0.927200 1.226672
Camera multipliers: 667.000000 256.000000 370.000000 0.000000
```
```
$ hexdump -C P1250419.rw2 | head -1
00000000  49 49 55 00 18 00 00 00  88 e7 74 d8 f8 25 1d 4d  |IIU.......t..%.M|
```
I suspect this would require a change to the magick "sniffer" (like https://github.com/libvips/libvips/pull/3460) for the "49 49 55 00" magic bytes.

**Comment by kleisauke** [comment]
Upstream PR https://github.com/ImageMagick/ImageMagick/pull/6967 should fix this.

**Comment by mertalev** [comment]
Wow, that was fast!
