### ISSUE TITLE
php Libvips mapim function

### ISSUE THREAD

**Issue by cmsaccount** [libvips/libvips#3811]
Hello,

I need to convert the Imagick code to Libvips. This is a distort transformation horizontally:

```
$image = new Imagick(...);
$points = [ 
0, 0,
0, 0,

0, 10,
10, 10,

100, 0,
100, 0,

100, 10,
110, 10];

$image->distortImage( Imagick::DISTORTION_PERSPECTIVE, $points, TRUE );
```

I know that i must use a method mapim() but i don't understand what arguments to use :(

Thank you!
![image](https://github.com/libvips/libvips/assets/51406194/6de57ed5-5e86-405a-9717-e40608d1b13f)

**Comment by jcupitt** [comment]
See https://github.com/libvips/libvips/discussions/3812
