### ISSUE TITLE
Attempting to vertically arrayjoin a large amount of images results in a segfault

### ISSUE THREAD

**Issue by TheEssem** [libvips/libvips#3835]
## Questions, enhancements, tips, etc.

Please use libvips discussions for other topics.

https://github.com/libvips/libvips/discussions

## Bug report

**Describe the bug**
It appears that trying to vertically append many images in an array that have been cropped/modified from an original source image with many similar pages results in libvips crashing with a segfault.

**To Reproduce**
Run the following Python script (`./mirror.py input.gif output.gif`) with the following image as input:
![flashtest](https://github.com/libvips/libvips/assets/21112968/75baecd0-80f6-4e40-96a1-188ba5f51fb5)
```py
#!/usr/bin/python3

import sys
import pyvips

original = pyvips.Image.new_from_file(sys.argv[1] + "[n=-1]")
page_height = original.get_page_height()
n_pages = original.get_n_pages()

img = []
for i in range(0, n_pages):
  x = i * page_height
  cropped = original.crop(0, x, original.width, page_height / 2)
  flipped = cropped.flip('vertical')
  img.append(cropped)
  img.append(flipped)

image = pyvips.Image.arrayjoin(img, across=1)
image.set('page-height', page_height - (page_height % 2 if 1 else 0))
image.write_to_file(sys.argv[2])
```

**Expected behavior**
The script should output a GIF with the top half of each frame mirrored onto the bottom half (or, in the case of the provided image, a nearly identical output compared to the input).

**Actual behavior**
The script will exit with a "segmentation fault (core dumped)" error.

**Environment**
(please complete the following information)
 - OS: EndeavourOS Linux (6.6.12-273-tkg-linux-tkg-eevdf-generic_v3)
 - Vips: 8.15.1

**Additional context**
I've provided a Python script for testing, but I've tested this using the C++ library and it occurs there as well.

**Comment by jcupitt** [comment]
I found a workaround:

```
$ VIPS_DISC_THRESHOLD=1g ./mirror.py ~/pics/flash.gif x.gif
$
```

It looks like a bug in the way libvips is flipping between memory and temporary files for intermediates.

**Comment by jcupitt** [comment]
I think found a proper fix, let's move any discussion and testing to the PR.
