### ISSUE TITLE
Add an image format blocklist for imagemagick

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3838]
libvips passes images of unknown format on to imagemagick. But imagemagick in turn has weak support for some common formats, and this can cause unexpected and lengthy delays.

For example:

```
$ /usr/bin/time -f %M:%e vipsheader frank.avi 
frank.avi: 720x576 uchar, 3 bands, srgb, magickload
10691072:16.09
```

Here, IM delegates to `ffmpeg`, and in turn that transcodes the entire AVI file to a supported format before inspection. The result: 10gb of memory and 16s of CPU time.

We have a set of sniffers to spot filetypes which we pass to imagemagick. How about having a set of blocklist sniffers which recognise filetypes which we do NOT pass to imagemagick?

AVI is the obvious one, but I'm sure there are others.

**Comment by kleisauke** [comment]
Specifically for ImageMagick, I believe it's best to utilize a [`policy.xml`](https://imagemagick.org/script/security-policy.php) configuration file. For example, we use this one on [our public service](https://github.com/weserv/images):
```xml
<policymap>
  <policy domain="Undefined" rights="none"/>
  <!--
  Use IM only to read certain image types. Assumes the rest is handled in libvips.
  Note: ICO data can be either a BMP image, or a complete PNG image.
  -->
  <policy domain="delegate" rights="none" pattern="*" />
  <policy domain="filter" rights="none" pattern="*" />
  <policy domain="coder" rights="none" pattern="*" />
  <policy domain="coder" rights="read" pattern="{ICO,BMP,PNG}" />
</policymap>
```

However, according to https://stackoverflow.com/a/50837362, GraphicsMagick does not have a direct counterpart to this functionality, but I'm not sure if that's a issue there.

**Comment by jcupitt** [comment]
I think you're right in a server context.

I was running into this issue with desktop libvips -- an AVI file in a directory is enough to kill vipsdisp :( But desktop users probably don't want to disable all AVI handling in imagemagick, just within libvips (where it's mostly useless).

**Comment by kleisauke** [comment]
Ah, you are right. It would indeed make more sense to block slow formats from the `*_header()` phase. Users who still want to process these files may use `vips_magickload()` directly, for example:
```console
$ vips magickload x.avi x.jpg
```

**Comment by jcupitt** [comment]
I think we're done, I'll close.
