### ISSUE TITLE
vips breaks on PNM files with two or more comments

### ISSUE THREAD

**Issue by louie-github** [libvips/libvips#3842]
## Bug report

**Describe the bug**
When converting PNM files (PBM, PGM, PPM, etc.) containing comments, such as those produced by XSane, libvips errors out as it cannot read the width and height values properly.

**To Reproduce**
1. Use the minimum example `image.pbm`:
```
P1
#
#
1 1
0
```
2. Run `vips pngsave image.pbm image.png`.
3. See error:
```
(vips:2151): GLib-GObject-CRITICAL **: 16:34:01.737: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(vips:2151): GLib-GObject-CRITICAL **: 16:34:01.743: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'
```

Note that if you use the following pbm file (adding 0 to the comments), libvips errors out four times instead of just two:
```
P1
# 0
# 0
1 1
0
```

Error:
```
(vips:2280): GLib-GObject-CRITICAL **: 16:35:49.029: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(vips:2280): GLib-GObject-CRITICAL **: 16:35:49.029: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'

(vips:2280): GLib-GObject-CRITICAL **: 16:35:49.034: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(vips:2280): GLib-GObject-CRITICAL **: 16:35:49.034: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
```

**Environment**
 - OS: Arch Linux on WSL (Windows 11)
 - Vips: vips-8.16.0 (compiled from commit 4265d0026356438f27d25c8cb8675d65254c9d0d)

**Comment by lovell** [comment]
Thanks for reporting, possible fix for this at https://github.com/libvips/libvips/pull/3843

**Comment by jcupitt** [comment]
I think this is done, I'll close.
