### ISSUE TITLE
When vips_heifsave_mime() will be available

### ISSUE THREAD

**Issue by vikasjio** [libvips/libvips#3846]
When we can expect General availability of vips_heifsave_mime(); is there any plan/work for the same?
plz give me pointer if its already there and i missed it. Since apple world is generating heic for some time now its time to have this function as well. Working with vips_heifsave_buffer() + buffer transmission in the meantime i. e 2 steps, which can be done in 1 step and more efficient, saving a buffer copy.

**Comment by jcupitt** [comment]
Hi @vikasjio, 

You have two possibilities:

1. If you use `vips_heifsave_buffer()` + buffer transmission you can set `Content-length`, which is useful for clients.
2. If you use `vips_heifsave_target()`, you can write directly to the pipe and save a copy, but of course you won't be able to set `Content-length`.

**Comment by vikasjio** [comment]
Thanks @jcupitt 

second option seems ok. So, to mimic functionality like vips_heifsave_mime() i.e. save as mime heif/heic on stdout, i'll need below 2 steps:
1. create targe for stdout like this:
VipsTarget *target = vips_target_new_to_file("-", NULL);

2. Save image to target (stdout actually) in heif format, like:
vips_heifsave_target(image, target, NULL);
and then vips_target_free(target);
// sending content-length is optional for me, anyway i can send also that if required

Hope this will work, then we can close this thread.
else kindly point if i still missed any step.

**Comment by jcupitt** [comment]
stdout is file descriptor 1, so you can write:

```C
printf("Content-type: image/heic\r\n");
printf("\r\n");
fflush(stdout);
VipsTarget *target = vips_target_new_to_descriptor(1);
vips_heifsave_target(image, target, NULL);
```

You won't be able to set `Content-length`, since that must be sent *before* the image. If you need to send a length, you'll need to write the HEIC to a memory buffer, send the length, then send the buffer contents.

**Comment by vikasjio** [comment]
thanks a lot sir
