### ISSUE TITLE
PNG compressed larger than original if bitdepth >= 8

### ISSUE THREAD

**Issue by Auxority** [libvips/libvips#3849]
## Bug report

**Describe the bug**
When saving PNGs that are not generated by libvips, the file size increases when the bit depth is greater than (or equal to) 8.

**To Reproduce**
1. Download the PNG image ![penguin](https://github.com/libvips/libvips/assets/35202343/befa31f2-b0da-4446-879b-a64c10d2e8f4) _This is a 24-bit PNG image, but any PNG not generated by libvips should work_
2. Use the command `vips pngsave .\penguin.png --bitdepth 8 output.png`
3. Look at the file size of the `output.png` file compared to the `penguin.png` file.

**Expected behavior**
I would expect the file size to have shrunk, since the bit depth was reduced from 24 to 8.

**Actual behavior**
But for some reason the file size grows. Only when a bit depth below 8 is used, does the file size decrease.

**Screenshots**
![image](https://github.com/libvips/libvips/assets/35202343/78e7ce69-5d9c-4a5b-91a8-0b25c512c5fa)

**Environment**
 - OS: Windows 11 (10.0.22635)
 - Vips: 8.15.1

**Comment by jcupitt** [comment]
Hi @Auxority,

`--bitdepth 8` means 8 bits per band, so 24 bits for an RGB image.

See:

https://www.libvips.org/API/current/VipsForeignSave.html#vips-pngsave

If you want to make a palette (also called indexed) image you need:

```
$ vips pngsave penguin24.png x.png --palette
$ ls -l penguin24.png x.png
-rw-rw-r-- 1 john john 4004114 Feb 12 18:31 penguin24.png
-rw-r--r-- 1 john john 1834187 Feb 12 18:31 x.png
```

To make:

![x](https://github.com/libvips/libvips/assets/580843/5de6d4f2-dd65-4da2-902f-79725001d4d7)
