### ISSUE TITLE
`exif.c` has a 256 character limit for some values

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3857]
### Discussed in https://github.com/libvips/libvips/discussions/3853

<div type='discussions-op-text'>

<sup>Originally posted by **MarcosAndre** February 15, 2024</sup>
Hello,
I'm using the vips_image_get_as_string to extract copyright from the images, but there are some values that are truncated when the they are too long. I think that the [vips_image_get_as_string](https://github.com/libvips/libvips/blob/67647a6968c263d90f508346cb5c9ac7f3ddb13d/libvips/foreign/exif.c#L293) function only gets the first 256 characters. 

Is it possible to get the entire string using vips? Can you increase the string length?

Thank you in advance.
Best regars,
Marcos André 

</div>

**Comment by jcupitt** [comment]
For example, with this PNG suggested by @MarcosAndre:

![img-with-lots-of-metadata](https://github.com/libvips/libvips/assets/580843/18c82936-f4a0-449a-8795-4f56619c5450)

```
$ vipsheader -f exif-ifd0-XPComment img-with-lots-of-metadata.png | wc
     13      34     252
```

We see 252 bytes, but there should be 292.

Swapping all the 256 in `exif.c` for eg. 4096 fixes this, but we should probably do something better.

**Comment by jcupitt** [comment]
I made a PR which adds long exif value support for 8.16, let's move discussion there.

https://github.com/libvips/libvips/pull/3858

**Comment by MarcosAndre** [comment]
Sorry for the late feedback, I've tested the new version and it is working! Thank you so much @jcupitt 🙏🏼
