### ISSUE TITLE
VIPS_MAX_COORD prevents `join`/`insert` operations with obscure messages

### ISSUE THREAD

**Issue by AKlaus** [libvips/libvips#3865]
The library throws obscure exceptions when the image exceeds `VIPS_MAX_COORD` (`10,000,000px`) in height/width.

## Example 1. `join` / `insert` conversions

1. GIVEN 3 images with heights `9,000,000px`, `1,000,000px` and `1,000,000px` (so the joined image would exceed the `VIPS_MAX_COORD` limit in height).
2. WHEN call `vips_join` conversion ([link](https://github.com/libvips/libvips/blob/master/libvips/conversion/join.c#L341) to the code) to join the images.
3. THEN the following exception gets thrown:<br>`unable to call join`<br>`insert: parameter y not set`.

## Example 2. Open a file larger `10,000,000px` in height or width
1. GIVEN an image that exceeds `VIPS_MAX_COORD` (`10,000,000px`) in height or width.
2. WHEN open it (e.g. via `vips_foreign_find_load`)
3. THEN the following exception gets thrown:<br>`tiff2vips: width/height out of range`

## Underlining reason
Under the hood, it all boils down to the validation of the image dimensions being less than `VIPS_MAX_COORD` ([link](https://github.com/libvips/libvips/blob/master/libvips/include/vips/image.h#L64C9-L64C23) to the code), which is defined as "_a maximum value for a coordinate at various points for sanity checking_".

## Expected behaviour
Some time ago, that arbitrary threshold was 10 times smaller – `1,000,000px` and it was increased on request #355.

Due to the nature of my industry, we're dealing with very narrow (`<1,000px` width) and long (`<30,000,000px` height) TIFF images. Hence, can we ask either for another increase of `VIPS_MAX_COORD` or make it a configurable parameter?

**Comment by jcupitt** [comment]
Hi @AKlaus,

Wow I must say I never imagined 10m pixels would be too few. I may have said something similar before, of course ...

I think it's a good idea to have a "beyond this, something has broken" limit, but of course we'd be happy to raise the current bar. Do you have a feeling for what a sensible upper bound might be? I guess the practical limit would be 2bn.

It could also be set via an environment variable I suppose, eg. `VIPS_MAX_COORD`.

**Comment by AKlaus** [comment]
Thank you for understanding.
For our case, we don't expect images beyond `30,000,000px` in height. 
But again, as the famous saying "_640KB of memory ought to be enough for anybody_" goes, there's a chance of hitting the ceiling in 5 years but that's beyond my horizon :).

**Comment by jcupitt** [comment]
Heh OK, let's bump it to 100m and add a config option. I made a quick PR, let's continue any discussion there.

**Comment by AKlaus** [comment]
We appreciate your help.
Is the next version (v8.15.2?) going to be released anytime soon?

**Comment by jcupitt** [comment]
It's an API change, so it'll be in 8.16, out some time this summer I guess.
