### ISSUE TITLE
jpegli support

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3872]
### Discussed in https://github.com/libvips/libvips/discussions/3871

<div type='discussions-op-text'>

<sup>Originally posted by **adityapatadia** March  1, 2024</sup>
I just read that libjxl has a library which backports the advantages of jpeg-xl to good old JPEG. The library is called jpegli. Some information is available in this comment: https://news.ycombinator.com/item?id=38644005

I know it's just a very bird eye view but we should plan to introduce this in VIPS. May be we can generate better JPEGs.</div>

**Comment by kurtextrem** [comment]
Worth noting Jpegli is included in the JXL repo: https://github.com/libjxl/libjxl/blob/main/lib/jpegli/README.md:

> When building the parent libjxl project, two binaries, tools/cjpegli and tools/djpegli will be built, as well as a **lib/jpegli/libjpeg.so.62.3.0 shared library that can be used as a drop-in replacement for the system library with the same name**.

so it might not be too much effort if the "just replace" method is picked (replacing the lib inside libvips), if I understand correctly? It might be valuable to keep mozjpeg around for comparison and upgrade compatibility reasons though (at least temporarily).

**Comment by jcupitt** [comment]
If it's just a question of dropping in a binary-compatible jpeg library, then this is really an enhancement for the various libvips build repos.

@kleisauke, shall I made an enhancement issue for the windows build system?

**Comment by jcupitt** [comment]
[erickguan](https://github.com/erickguan) noted:

A few articles I skimmed through:
- https://cloudinary.com/blog/jpeg-xl-and-the-pareto-front
- https://giannirosato.com/blog/post/jpegli/
The second blog has a few benchmark with commands.

**Comment by kurtextrem** [comment]
It _looks_ like mozjpeg might still be worth keeping: 
>  I also didn't test every chroma subsampling mode that mozjpeg has to offer, and allowed mozjpeg to subsample chroma automatically - this automatic selection gives it a theoretical advantage over each individual jpegli chroma subsampling mode, but wouldn't allow the encoder to display its breadth of competence like jpegli here. In the end, I wouldn't call this a loss for mozjpeg anyhow - it is clearly not obsolete in any case, and the only scenario in which it clearly lost was the first image test. The overall average & three image average results make a compelling case for mozjpeg overall.
(from https://giannirosato.com/blog/post/jpegli/)

jpegli appears to be better than mozjpeg at q80-100.

**Comment by kleisauke** [comment]
> @kleisauke, shall I made an enhancement issue for the windows build system?

Sure, that would be great. I'll see if I could add a `--with-jpegli` build option during the weekend.

**Comment by andrews05** [comment]
Will there need to be a new option to use the XYB colorspace?

**Comment by jcupitt** [comment]
I don't think so (but perhaps I'm wrong).

**Comment by kurtextrem** [comment]
A small question for my understanding: so if jpegli is built and the jpeg libs are replaced at sys level during building of libvips (for linux), or built with --with-jpegli on windows, jpegli would be up and running for anything using libvips?

**Comment by jcupitt** [comment]
Yes, it aims to be a drop-in binary-compatible replacement.

It will only replace regular libjpeg for dynamically linked programs, of course. If you have a statically linked libjpeg in there it'll be harder to swap out.

**Comment by adityapatadia** [comment]
Yeah, I would like to know as well if this is going to be released anytime soon.

**Comment by kurtextrem** [comment]
See above, while libvips itself (apart from the windows build) doesn't have a specific build option, you can replace the jpeg lib and then build libvips. https://github.com/libvips/libvips/issues/3872#issuecomment-1986942622

That's a bit cumbersome, so if you think a better way would be nice, maybe worth opening an issue?
