### ISSUE TITLE
Sampling a random set of pixels.

### ISSUE THREAD

**Issue by atandamen** [libvips/libvips#3875]
Hi!

My task is as follows: to sample a random set of pixels from an image for further analysis. In particular, I need to select 5% of the total number of pixels.

Here are the approaches I've tried:
1. Just select by random coordinates, image[rnd_x][rnd_y]. The speed of this approach is too low (
2. Generate a Gaussian noise mask with such parameters that about 5% of the values of this noise are greater than a certain threshold, and then applying this mask.
```csharp
using Image noise = Image.Gaussnoise(img.Width, img.Height, mean: mean, sigma: sigma);
using Image mask = noise > thresh;

using Image masked = img & mask;
```
But with this approach, I have no idea how to get something like a one-dimensional LUT table with selected pixels.

Can you comment on these approaches and/or suggest your own?

If it matters, I use the NetVips port.

**Comment by jcupitt** [comment]
Hi @atandamen,

For smallish images, probably the simplest thing would be to render to a big array and then just pick pixels randomly.

For large images, I think I would do something like what you suggest -- make a noise image and mask it. You can use `max` to find the top $n points and their values. I think it's only been tuned for small values of n though, so it'd probably perform poorly for large numbers of pixels.

Your final option would probably be to make a new libvips operation that sampled points. That'd need good C/C++ though.

**Comment by jcupitt** [comment]
So eg.:

```
$ vips max k2.jpg --size 10 --x-array --y-array
634 658 659 660 1022 1023 1024 1025 1026 1027 
1280 1280 1280 1280 1280 1280 1280 1280 1280 1280 
255.000000
```

So the three lines are the x and y coordinates of the top 10 points, and the top value (255). The C# interface is the same.

**Comment by atandamen** [comment]
Yes, that seems to be enough.
