### ISSUE TITLE
Loading images with jpegli fails with "No SOS marker found."

### ISSUE THREAD

**Issue by 17dec** [libvips/libvips#3879]
Already reported at the libjxl repo, see [#3378](https://github.com/libjxl/libjxl/issues/3378) for details.

Re-reporting here as well. While not technically a bug in libvips (I think?), if there's enough interest in using jpegli it may be worth implementing a workaround for now.

**Comment by kleisauke** [comment]
Upstream PR: https://github.com/libjxl/libjxl/pull/3394.

**Comment by kleisauke** [comment]
Fixed with commit https://github.com/libjxl/libjxl/commit/5e7560d9e431b40159cf688b9d9be6c0f2e229a1. I'll close.
