### ISSUE TITLE
Conversion to PFM gives incorrect output

### ISSUE THREAD

**Issue by NiHoel** [libvips/libvips#3885]
**Describe the bug**
Converting a floating point linear SRGB image (e.g. EXR or HDR) to PFM results in a file with incorrect orientation (e.g. bottom left corner is top right), clipped highlights and squeezed colors (rougly multiplied by a factor of 2^-20)

**To Reproduce**
1. Use Image https://drive.google.com/file/d/1I9J3iyCnu7LX1K9eXAz_dF6cjq1rJU9t/view?usp=sharing or any other EXR or HDR image file (preferably with intensity values > 1).
2. Run `vips copy sun.hdr sun.pfm`
3. Open sun.pfm in gimp. Everything is just white. By lowering exposure some of the original image becomes recognizable.

The indicated byte order is incorrect: The file is written big-endian but indicates little-endian encoding (-1 in third line). Changing the sign in a hex editor fixes the issue.

**Screenshot**
![grafik](https://github.com/libvips/libvips/assets/28017252/bc05f09d-1769-4652-8741-b762e5d603ac)
left: vips produced file including fix (marked location); right: original pfm file (before conversion to hdr using gimp and to pfm using vips)

**Environment**
 - OS: Win10, i7-9700
 - Vips: 8.15.1

**Comment by jcupitt** [comment]
Hi @NiHoel,

You're right, `ppmsave` treats PFM as regular sRGB, just with float pixels. It should use linear 0-1 (scRGB). I'll make a PR.

Thanks for the report!

**Comment by jcupitt** [comment]
I think this is fixed, I'll close.
