### ISSUE TITLE
JXL Support in Libvips Web Build

### ISSUE THREAD

**Issue by LumiCodex** [libvips/libvips#3891]
Hi,

With the recent improvements in both speed and memory footprint, along with increased support by Apple, Adobe, Samsung, Cloudinary, and many other players,

I think the developer community would benefit from having JXL support in the web build of libvips. This would ease access to this technology for Node.js, .NET, and other developers, save a lot of money on cloud storage, and benefit end users from the quality of this codec.

In my current project, I'm encoding images using .NET 8 AOT on AWS Lambda with the net-vips web NuGet package. While I attempted to rebuild the package with libjxl, the process proved overly complex for a typical .NET developer.

I strongly believe including JXL support in the Libvips web build would significantly benefit developers and streamline workflows.

Thank you for considering this feature request!

**Comment by lovell** [comment]
Does this refer to the prebuilt Windows binaries? If so, please subscribe to https://github.com/libvips/build-win64-mxe/issues/40 for possible updates.

**Comment by LumiCodex** [comment]
In my case it's more about the native binaries in the net-vips package  https://www.nuget.org/packages/NetVips.Native/8.15.1 but I think that the same issue than the one you link.

Should I close this issue and add my comment in the other one?

**Comment by lovell** [comment]
Let's track this at https://github.com/libvips/build-win64-mxe/issues/40 - there's no need to add a comment.
