### ISSUE TITLE
Row sums from vips_project do not necessarily give the same value like summing img(i,j) along i

### ISSUE THREAD

**Issue by rolandlo** [libvips/libvips#3897]
## Bug report

**Describe the bug**
As described in the title. Here is a reproducer using `pyvips`, but it's the same in Lua, so likely not a bug in the binding. Maybe it's some caching issue.

**To Reproduce**
1. Run python3 (and install `pyvips` before).
2. Enter the following commands:
```python
>>> import pyvips
>>> interpolate = pyvips.Interpolate.new("nearest")
>>> im = pyvips.Image.new_from_array([[7.*i+j for j in range(1,8)] for i in range(7)])
>>> rot = im.rotate(45, interpolate=interpolate)
>>> col_sums, row_sums = rot.project()
>>> print([sum([rot(i,j)[0] for i in range(9)]) for j in range(10)])
[1.0, 3.0, 30.0, 74.0, 135.0, 218.0, 215.0, 181.0, 123.0, 49.0]
>>> print([row_sums(0,j)[0] for j in range(10)])
[0.0, 3.0, 30.0, 69.0, 135.0, 225.0, 215.0, 181.0, 123.0, 49.0]
>>> print(rot(5,0))
[1.0]
>>> print(rot)
[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 15.0, 9.0, 3.0, 3.0, 0.0, 0.0], [0.0, 0.0, 0.0, 22.0, 16.0, 17.0, 10.0, 4.0, 0.0, 0.0], [0.0, 0.0, 29.0, 30.0, 24.0, 17.0, 18.0, 12.0, 5.0, 0.0], [0.0, 43.0, 37.0, 31.0, 31.0, 25.0, 19.0, 19.0, 13.0, 7.0], [0.0, 0.0, 45.0, 38.0, 32.0, 33.0, 26.0, 20.0, 21.0, 0.0], [0.0, 0.0, 0.0, 46.0, 40.0, 33.0, 34.0, 28.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 47.0, 41.0, 35.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 49.0, 0.0, 0.0, 0.0, 0.0]]
```

4. Note that the row sums for row 0, 3 and 5 are not same  in `row_sums` like in the row_sums computed from summing `rot(i,j)` over i where j=0, 3 or 5.  Also note that `rot(5,0)` is `1.0` (in a list) which doesn't fit with printing `rot`, where the whole first row consists of zeros.

**Expected behavior**
I would expect that the two computations give the same result (up to maybe small rounding errors).

**Environment**
(please complete the following information)
 - OS: Ubuntu 23.10
 - Vips: 8.14.3

**Additional context**
I stumbled upon this problem when working on adding `vips.Interpolate` to `lua-vips` (https://github.com/libvips/lua-vips/commits/add-interpolate/, based on work of @jcupitt) . Same problem except that printing an image doesn't write out the pixel values. Hopefully I don't miss something obvious.
If I use a `arr = ffi.cast(ffi.typeof("double*"), rot:write_to_memory())` I get the same differences between `rot(5,0)` and `arr[5]` (also between `rot(8, 3)` and `rot[38]` and between `rot(9,4)` and `arr[49]`; the other values are equal).

**Comment by jcupitt** [comment]
Yes, I think this is a bug -- it looks like affine is not calculating the error residual correctly at the start of generate. I'll have a look, and thanks for reporting!

**Comment by jcupitt** [comment]
I did some more digging and affine is fine, it's just a rounding problem.

When affine generates the large image, pixel (0, 5) is computed like this:

```
vips_interpolate_nearest_interpolate: (1, 1) (0, 1): 0 
```

Where the first coordinate is the sample position as a pair of doubles, and the second is after nearest rounding (ie. `floor()`). Obviously the second pair must be (1, 1) as well, so this looks bizarre.

If you pause there in a debugger, you see:

```
344		const VipsPel *restrict p = VIPS_REGION_ADDR(in, xi, yi);
(gdb) p x
$20 = 0.99999999999999989
(gdb) p y
$21 = 1.0000000000000004
(gdb) 
```

x is just under 1.0, so it becomes 0.

I don't think there's anything we can do about this, nearest interpolation will always be noisy.
