### ISSUE TITLE
Looks like 8.15.2 tag is wrong?

### ISSUE THREAD

**Issue by chenrui333** [libvips/libvips#3900]
👋 the tag should be 8.15.2 instead of 8.15.2a? Thanks!

<img width="823" alt="image" src="https://github.com/libvips/libvips/assets/1580956/5ea4bf1a-f0f5-4321-bf63-4e20f2d2fa3b">

cc @jcupitt

**Comment by jcupitt** [comment]
Ooops, sorry. Yes, I put the tag on the wrong branch, then updated it :( I think it's OK now.
