### ISSUE TITLE
HDR AVIF to HEIC (hdr)

### ISSUE THREAD

**Issue by Kinkazma** [libvips/libvips#3903]
No HDR in HEIC/HEIF. Sad

**To Reproduce**
1. Use Image 'HDR (AVIF)'
2. `kinkazma@MacBook-Pro-3 ~ % vips copy /Users/kinkazma/Downloads/Test.AVIF /Users/kinkazma/Downloads/Test.heif`
3. No HDR-Heif (/heic)

**Environment**
(please complete the following information)
 - OS: [MacOS 14.4]

PS : I use : `vips icc_transform /Users/kinkazma/Downloads/Test.AVIF /Users/kinkazma/Downloads/Test.heic /Users/kinkazma/Pictures/VIPS_HDR/BT2020.icc --embedded`
BT2020 → probably HDR. 

[HDR_Map.avif.zip](https://github.com/libvips/libvips/files/14667594/HDR_Map.avif.zip)

**Comment by jcupitt** [comment]
Hi @Kinkazma,

I had a look but I'm not sure what needs fixing. I tried:

```
$ vips copy HDR_Map.avif x.heic
$ vipsheader HDR_Map.avif x.heic 
HDR_Map.avif: 8000x1600 ushort, 3 bands, rgb16, heifload
x.heic: 8000x1600 ushort, 3 bands, rgb16, heifload
```

So range is preserved.

I tried adding a profile to your test image:

```
$ vips copy HDR_Map.avif x.avif[profile=BT20202.icc]
```

And copying that to HEIC preserved the profile. 

I looked through libheif and there's not a lot of information on how to read and write HDR images, so I'm unclear if anything needs fixing there.

Can you give any more information?

**Comment by Kinkazma** [comment]
On my Mac, I used an HDR profile that belongs to the computer. It didn't work any better. I'm not sure what's not working. I don't have coding skills, I do photography so it's not easy either. However, I already have HEIC files that contain HDR information if you're interested. But they come from my iPhone.
[HDR_P3_D65_ST2084.icc.zip](https://github.com/libvips/libvips/files/14716474/HDR_P3_D65_ST2084.icc.zip)

**Comment by jcupitt** [comment]
This discussion has a bit more info:

https://github.com/libvips/libvips/discussions/3153

Your original `HDR_Map.avif` is a 16 bit image and it's correctly read as 16 bits everywhere. It does not have an ICC profile, but perhaps if you attach the correct profile it'll appear as HDR? I'm unclear.

You can also have an HDR image which is a plain SDR, plus an extra gain map image. Yours does not have a gain map, it seems to be a regular 16 bit file.

```
$ heif-convert HDR_Map.avif x.png
File contains 1 image
Written to x.png
```

We'll probably need the help of an expert to make any more progress :(

**Comment by jcupitt** [comment]
You can also write high bit depth HEIC like this:

```
$ vips copy k2.jpg b.heic[Q=65,bitdepth=10]
$ vipsheader -a b.heic
b.heic: 1450x2048 ushort, 3 bands, rgb16, heifload
width: 1450
height: 2048
bands: 3
format: ushort
coding: none
interpretation: rgb16
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: b.heic
vips-loader: heifload
exif-data: 186 bytes of binary data
...
heif-primary: 0
n-pages: 1
heif-compression: hevc
bits-per-sample: 10
```

So libvips is showing as 16 bits, but the `bits-per-sample` metadata field shows the file is really 10 bits internally. Presumably, with the right profile, you could write HDR like this.
