### ISSUE TITLE
Subsample mode not working with jpegli

### ISSUE THREAD

**Issue by Snafuh** [libvips/libvips#3922]
Hello,

I've build windows binaries with the jpegli flag and was trying different setting combinations. 
The subsampling flag does not work correctly when using jpegli and there is no subsampling used when compressing images. File sizes are the same with VIPS_FOREIGN_SUBSAMPLE_ON, VIPS_FOREIGN_SUBSAMPLE_OFF and VIPS_FOREIGN_SUBSAMPLE_AUTO in various quality modes (tested 70, 80, 85,90) and imagemagick repots 444 for all images.

I've tested the prebuild windows binaries (mozjpeg) with the same settings, and OFF and ON are correctly working, and AUTO switches subsampling as expected depending on the Quality.

jpegli itself does not seem to feature and auto mode, but the cli tool shipped with the libjxl binaries supports the a _--chroma_subsampling_ parameter with 444|440|422|420 as valid parameters. These are all working correctly. 

**To Reproduce**
1. Build libvips with jpegli
2. Compress images via 
vips.exe resize test.png out-on.jpg[strip,Q=80,subsample_mode=VIPS_FOREIGN_SUBSAMPLE_ON] 1
vips.exe resize test.png out-auto.jpg[strip,Q=80,subsample_mode=VIPS_FOREIGN_SUBSAMPLE_AUTO] 1
vips.exe resize test.png out-off.jpg[strip,Q=80,subsample_mode=VIPS_FOREIGN_SUBSAMPLE_OFF] 1
4. Compare image size

**Environment**

 - OS: Windows 10
 - Vips: 8.15.2

From what I've understood, there were no adjustments made for jpegli as it is compatible as drop in replacement with mozjpeg/libjpeg-turbo. So I am not entirely sure how such differences would be handled by libvips, or if jpegli should conform to different standards. I'd be happy to open an issue over at libjxl if it's the latter. 

Cheers,
Kim

**Comment by Snafuh** [comment]
From what I can see libvips sets  h_samp_factor and v_samp_factor only ever to 1. 
Mozjpeg uses 4:2:0 (h_samp_factor = 2; v_samp_factor  = 2) as default.
Jpegli might use 4:4:4 as default. Therefore we never set any other values in libvips and subsampling is always off.

So this might require some changes in vips2jpeg.c to implicitly set both values if VIPS_FOREIGN_SUBSAMPLE_ON is set. The question is what values should VIPS_FOREIGN_SUBSAMPLE_ON be mapped to? 420?

**Comment by kleisauke** [comment]
I just opened PR #3924 for this. Any testing would be very helpful.

**Comment by jcupitt** [comment]
OK, I think this is done now. Thanks!
