### ISSUE TITLE
Add target write to `rawsave`

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3941]
### Discussed in https://github.com/libvips/libvips/discussions/3940

<div type='discussions-op-text'>

<sup>Originally posted by **akash-akya** April 18, 2024</sup>
Does it makes sense to create `VipsForeignSaveRawTarget` to support streaming raw pixels in a unified way (`vips_image_write_to_target(in, ".raw", target)`)?
I know there is already `VipsForeignSaveRawFd` which can be used to create similar interface, but in our case we have a unified interface to do streaming writes and this would help us to avoid creating special case to write raw pixels.

If this makes sense then I can try implementing it</div>

**Comment by jcupitt** [comment]
From the discussion: 

You can copy-paste code from something like ppmsave. I would have an abstract base class VipsForeignSaveRaw which writes to a target, then define VipsForeignSaveRawTarget, VipsForeignSaveRawFile etc. as concrete subclasses which define the parameters.

**Comment by akash-akya** [comment]
Thanks for the pointers. I'll try have a PR ready over the weekend.
