### ISSUE TITLE
Thumbnail/Resize removes color on Alpine

### ISSUE THREAD

**Issue by itsyoshio** [libvips/libvips#3945]
## Bug report

Whenever I use ::Vips::Image.thumbnail from `ruby-vips` on **Alpine Linux**, the image is black and white.
(assuming this is identical to upstream since c-binding) 

**To Reproduce**
1. resize any image using thumbnail on Alpine 3.19
2. write to file
3. See error

```ruby
require "ruby-vips"
::Vips::Image.thumbnail("input.jpeg", 536).write_to_file "samesize.jpeg"
::Vips::Image.thumbnail("input.jpeg", 500).write_to_file "resized2.jpeg"
```

**Expected behavior**
The resulting image should only be resized to the specified limits.

**Actual behavior**
The resulting image has the requested dimensions, but color is gone.

**Images**
![input](https://github.com/libvips/libvips/assets/12760988/36ac590e-c9ef-4348-91b9-9ddd0d23337f)
*input.jpeg, 536x354 px*
<details><summary>samesize.jpeg identical to input</summary>
<p>

![samesize](https://github.com/libvips/libvips/assets/12760988/877ade7d-7e35-468c-98e5-2f5546bab4e6)
*samesize.jpeg, 536x354 px*

</p>
</details> 

![resized](https://github.com/libvips/libvips/assets/12760988/3291efe5-8b1f-4285-bc35-2aa2e784c51a)
*input.jpeg, 500x330 px*

**Environment**
(please complete the following information)
 - OS: Alpine Linux v3.19.1
 - Vips: [8.15.0-r0](https://pkgs.alpinelinux.org/package/v3.19/community/x86_64/vips)

**Comment by lovell** [comment]
This was fixed in v8.15.1, please see https://github.com/libvips/libvips/pull/3763
