### ISSUE TITLE
The position of "#include <vips/vips8>" matters.

### ISSUE THREAD

**Issue by huskier** [libvips/libvips#3955]
We're developing applications on Windows 11 OS using Qt5.15.2 + MSVC2019.

In our application, we must to put "#include <vips/vips8>" on top of other including files. Otherwise, we've gotten weird compiling errors related to the lines in the following screenshot.
![image](https://github.com/libvips/libvips/assets/5828575/d4f6ddc4-7409-4a21-abe0-88c72256ff22)

Could we solve this issue?

**Comment by kleisauke** [comment]
I think this was fixed via PR #3946.

**Comment by huskier** [comment]
@kleisauke Thank you very much. This fix has really solved our issue.
