### ISSUE TITLE
vips dzsave crashes when saving tiff to avif

### ISSUE THREAD

**Issue by LumiCodex** [libvips/libvips#3972]
vips.exe dzsave a.tif pyramid --suffix=.avif

some tif files crashes the exe or the .NET libvips wrapper. The crash cannot be handled by .NET exceptions and crashes the whole app.
It works on some tiff, but some other crashes.

**To Reproduce**

1. Use the tiff image in the zip attached [a.zip](https://github.com/libvips/libvips/files/15455800/a.zip)
2. run vips.exe dzsave a.tif pyramid --suffix=.avif
3. See error

**Environment**

 - OS: Windows 10
 - Vips: vips-dev-w64-all-8.15.2

**Comment by jcupitt** [comment]
Hi @LumiCodex,

Your TIFF is 16-bit. It's working fine on ubuntu 24.04, but yes I see a segv on win10 with the official 8.15.2 binary.

I would guess that one of the various avif write libraries needs updating in the thing that builds the win binary:

https://github.com/libvips/build-win64-mxe

**Comment by lovell** [comment]
This was fixed via https://github.com/libvips/build-win64-mxe/pull/61

**Comment by jcupitt** [comment]
Ah OK. Thanks @lovell 

So this bug will be fixed in 8.16, due in a few months.
