### ISSUE TITLE
Crash trying to read/decode large Big TIFF File

### ISSUE THREAD

**Issue by snowzach** [libvips/libvips#3984]
## Bug report

**Describe the bug**
When trying to thumbnail or get the headers for a very large BTF file it give an error and crashes/exits.

**To Reproduce**

Download this huge BTF file (warning, 11-12ish gig)
https://cf.10xgenomics.com/samples/spatial-exp/3.0.0/Visium_HD_Human_Colon_Cancer/Visium_HD_Human_Colon_Cancer_tissue_image.btf

Try to use vipsheader (or vipsthumbnail) on it by piping..
```
cat Visium_HD_Human_Colon_Cancer_tissue_image.btf | vipsheader -a stdin

(vipsheader:28): GLib-ERROR **: 16:00:14.638: adding 4096 to array would overflow
Trace/breakpoint trap (core dumped)
```

**Expected behavior**
Work as expected and print out information or thumbnail.

**Actual behavior**
Traps and coredumps.

**Environment**
Tried in ubuntu 22 with 8.12.1 and Alpine latest with 8.15.0-r0

 - OS: [e.g. Ubuntu 16.04, MacOS 10.13]
 - Vips: [e.g. 8.8, 8.9, etc]

**Additional context**

**Comment by jcupitt** [comment]
Hi @snowzach, wow what a monster. I'll have a look.

**Comment by jcupitt** [comment]
It's working fine in git master libvips:

```
$ vipsheader Visium_HD_Human_Colon_Cancer_tissue_image.btf 
Visium_HD_Human_Colon_Cancer_tissue_image.btf: 75250x48740 uchar, 3 bands, srgb, tiffload
```

I'll try some older versions.

I can view it in the current vipsdisp binary:

![image](https://github.com/libvips/libvips/assets/580843/d87f746d-b764-48be-9c34-3cffde870fa4)

See https://github.com/jcupitt/vipsdisp, you can install the current version with `flatpak install flathub org.libvips.vipsdisp`.

**Comment by snowzach** [comment]
It seems to work okay when pointing it right to the file. I want to try to use thumbnail and header from an AWS Lambda which doesn't have enough disk space to store it. So I am trying to pipe it via stdin. It doesn't seem to like that. That's what's giving the error.

**Comment by jcupitt** [comment]
Ahhhh I see. I'll try again.

**Comment by jcupitt** [comment]
I think it's because you need to be able to seek() to read TIFF --- the format is made of a set of directories and data areas you can read out randomly. This means when you pipe a TIFF into vips, it's forced to buffer the entire file in memory. 

We have an env var called `VIPS_PIPE_READ_LIMIT` which is supposed to limit memory buffering on pipes, but it doesn't seem to be working here, I'll have a look.

However this might not help you -- a lambda with 12gb of spare memory sounds expensive.

**Comment by snowzach** [comment]
Yeah, that's what I was afraid of... There are ways to get it more disk but it's actually capped at 10g of memory. Appreciate you looking.

**Comment by jcupitt** [comment]
I made a PR to improve this (but not fix your problem). I now see:

```
$ cat Visium_HD_Human_Colon_Cancer_tissue_image.btf | vipsheader -a stdin
vipsheader: VipsImage: unable to load source
```

Not a great error message, but much better.

Thanks for reporting this!
