### ISSUE TITLE
vips_vsnprintf own implementation is not thread safe

### ISSUE THREAD

**Issue by Julianiolo** [libvips/libvips#4001]
## Bug report

**Describe the bug**
The implementation of [`vips_vsnprintf`](https://github.com/libvips/libvips/blob/ed700dcd38957d627347a2fe01d9d12bbc0f73d9/libvips/iofuncs/util.c#L456) that is used when vsnprintf is not present is not thread safe, as it uses a [buffer](https://github.com/libvips/libvips/blob/ed700dcd38957d627347a2fe01d9d12bbc0f73d9/libvips/iofuncs/util.c#L467) with static storage duration.
I noticed this while trying to load thumbnails from multiple threads which spontaneously failed due to the `vips_vsnprintf` in [`vips_object_set_from_string`](https://github.com/libvips/libvips/blob/ed700dcd38957d627347a2fe01d9d12bbc0f73d9/libvips/iofuncs/object.c#L2586) sometimes producing garbage data in the buffer (for me this was "t]" instead of the expected "[]").
I guess the buffer has this static storage duration to make overflows less likely to mess up the stack? If that is the case, maybe mallocing or a thread local buffer (if that is even available in c99?) would be better?

The weird part is this happened because meson does not seem to recognise msvc having vsnprintf, which I still have to investigate...

**Environment**
 - OS: Windows 10
 - Compiler: msvc 193
 - Vips: 8.15.2

**Comment by Julianiolo** [comment]
I found out why meson does not find vsnprintf on msvc: #4003

**Comment by jcupitt** [comment]
Fixed with the PR, let's move any discussion there. Thank you!
