### ISSUE TITLE
Meson does not find vsnprintf on msvc

### ISSUE THREAD

**Issue by Julianiolo** [libvips/libvips#4003]
## Bug report

Meson fails to find vsnprintf when compiling on msvc.
```
...
Checking for function "vsnprintf" with dependency -lm: NO 
...
```

I think this can be resolved by adding `prefix: "#include <stdio.h>"` to the [`cc.has_function`](https://github.com/libvips/libvips/blob/ed700dcd38957d627347a2fe01d9d12bbc0f73d9/meson.build#L178) call.

The underlying issue seems to be that msvc only defines the `vsnprintf` function in the stdio.h header (as supposed to having it in a system library and only having the function signature in the header). This makes meson not find the vsnprintf symbol without the prefix parameter, as it then just tries to define the prototype in a  file and see if it links.

**Environment**
 - OS: Windows 10
 - Compiler: msvc 193
 - Vips: 8.15.2

**Comment by jcupitt** [comment]
Hi @Julianiolo, this is a great find, this must have been causing rare problems on windows (I suppose?) since we switched to meson. I'll make a PR for these two issues.

**Comment by lovell** [comment]
Could we switch to the glib-provided [g_vsnprintf](https://docs.gtk.org/glib/func.vsnprintf.html)?

**Comment by jcupitt** [comment]
Yup, our terrible home-made fallback pre-dates libvips being used in heavily threaded applications. The glib one is a great upgrade.

**Comment by kleisauke** [comment]
I just opened PR #4004 for this.

**Comment by jcupitt** [comment]
I made https://github.com/libvips/libvips/pull/4005 for 8.15 -- it's a minimal PR that just changes the fallback and doesn't touch most of the code. Let's move any discussion there.

Let's use Kleis' much more comprehensive one for master.

I credited you in the changelog @Julianiolo, and thanks again for finding this terrible thing!
