### ISSUE TITLE
vips triggering systemlib assert on trying to load corrupt png

### ISSUE THREAD

**Issue by Julianiolo** [libvips/libvips#4015]
## Bug report

When loading this courrupted png test file

**To Reproduce**
1. Use Image ![xcrn0g04](https://github.com/libvips/libvips/assets/50519317/130d7af4-6c87-489a-aadc-25f9441d5d91) (from [pngsuite](http://www.schaik.com/pngsuite))
2. call vips_image_new_from_file or anything similar (vips_thumnail also works)
3. On msvc I get an assert error:
backtrace:

[`isdigit`](https://linux.die.net/man/3/isdigit)
[`vips_strtod`](https://github.com/libvips/libvips/blob/a935ba7a7b197e96db532ceffcea0c8b430cba6b/libvips/iofuncs/util.c#L1963)
[`parse_matrix_header`](https://github.com/libvips/libvips/blob/a935ba7a7b197e96db532ceffcea0c8b430cba6b/libvips/foreign/matrixload.c#L126)
[`vips_foreign_load_matrix_file_is_a`](https://github.com/libvips/libvips/blob/a935ba7a7b197e96db532ceffcea0c8b430cba6b/libvips/foreign/matrixload.c#L345)
[`vips_foreign_find_load_sub`](https://github.com/libvips/libvips/blob/a935ba7a7b197e96db532ceffcea0c8b430cba6b/libvips/foreign/foreign.c#L565)
`...`

the assert reads: `Expression: c>= -1 && c <= 255`
this seems to be caused by feeding the 0x89 at the start of the png magic number to `isdigit`. The [manpage](https://linux.die.net/man/3/isdigit) states:
> These functions check whether c, which must have the value of an unsigned char or EOF, ...

And as the 0x89 gets interpreted as -119 we are causing undefined behaviour, which gets caugth by the assert.
I guess the solution would be to either cast the char to an unsigned char before passing it to `isdigit`, or a extra range check.

As to why this happened with a corrupted png, I think the png was (correctly?) recognized as broken/invalid, so the format detection moved on to the other formats. One of them being these matrix files. 
I have no idea on how this went unnoticed, being that literally any file with a non ascii first byte, which also fails all other format detections, will cause this error. I guess linux might not check for these illegal values passed to `isdigit`?

**Environment**
 - OS: Win10
 - Compiler: msvc 193
 - Vips: 8.15.2

**Comment by kleisauke** [comment]
I assume this issue occurs only when a debug CRT library is used (e.g. when building with the `/MTd` compiler option)?

We should probably replace all occurrences of `isdigit()` with [`g_ascii_isdigit()`](https://docs.gtk.org/glib/func.ascii_isdigit.html) (the GLib equivalent).

**Comment by Julianiolo** [comment]
@kleisauke Yes I was using a debug build, totally forgot that that could be the "cause".

As I said, we could just cast the value to an `unsigned char` before passing it to `isdigit()`. That should be perfectly fine(?). Although yes maybe replacing it with `g_ascii_isdigit()` is a more robust solution.

**Comment by jcupitt** [comment]
I agree, `g_ascii_isdigit()` would probably be the best solution to this.

**Comment by Julianiolo** [comment]
I'll take a look, should similar versions also be replaced? (like `isspace`, ...; the [manpage](https://linux.die.net/man/3/isdigit) has a whole list) Probably, right?

**Comment by kleisauke** [comment]
It looks like libvips only relies on `isalnum()` and `isspace()`, in addition to `isdigit()`. I just opened PR #4045 for this.
