### ISSUE TITLE
vips::VImage::new_from_memory() requires a `void*`, while vips_image_new_from_memory() only wants a `const void*`

### ISSUE THREAD

**Issue by Julianiolo** [libvips/libvips#4026]
## Bug report

**Describe the bug**
See [`vips::VImage::new_from_memory()`](https://github.com/libvips/libvips/blob/79629a6572da95481b65c7a206cbff73c66390a4/cplusplus/include/vips/VImage8.h#L922) vs. [`vips_image_new_from_memory()`](https://github.com/libvips/libvips/blob/79629a6572da95481b65c7a206cbff73c66390a4/libvips/include/vips/image.h#L474)

I guess this is just an oversight and `vips::VImage::new_from_memory()` should also just use a `const void*`.

**Comment by jcupitt** [comment]
You're right, we should add a `const` to the C++ API.

**Comment by jcupitt** [comment]
I made a very quick PR, let's move any discussion there. Thanks for pointing this out!
