### ISSUE TITLE
`vips_image_get_string` returns invalid pointer

### ISSUE THREAD

**Issue by masaedw** [libvips/libvips#4040]
## Bug report

**Describe the bug**

The [vips_image_get_string()](https://github.com/libvips/libvips/blob/088330c112ae15cfe44af1202149b6cf050174d1/libvips/iofuncs/header.c#L1875-L1905) seems to have an issue where it doesn't always work correctly. When the metadata is of type `G_TYPE_STRING`, the function returns a pointer to a string that becomes invalid after `GValue` is unset.

**To Reproduce**
1. Load an image using libvips.
2. Call `vips_image_get_string()` to get a string metadata field (e.g., `"filename"`).
3. The returned string is corrupted or invalid after the function returns.

**Expected behavior**
The function should return a valid string pointer that remains correct after the function returns.

**Actual behavior**
The function returns a pointer to a string that becomes invalid once the GValue is unset, causing corrupted or invalid string data.

**Screenshots**

**Environment**
 - OS: Mac OS 14.5 on Apple M1
 - Vips: 8.15.2

**Additional context**
The value returned by `g_value_get_string()` cannot be used after `g_value_unset()` is called, as it becomes invalid.

**Comment by lovell** [comment]
I think this was fixed in commit https://github.com/libvips/libvips/commit/117c554a7299afcfc647849bb65a7f4cc966ca56

**Comment by jcupitt** [comment]
Yes, 8.16 (due later this summer) should have this fix.
