### ISSUE TITLE
JPEG2000 image fails to load with "unsupported colourspace"

### ISSUE THREAD

**Issue by aksdb** [libvips/libvips#4087]
## Bug report

The attached image fails to load since libvips 8.15.1 on ArchLinux and Alpine (haven't checked other distros).

**To Reproduce**

Try to load the attached image.
[testimage.zip](https://github.com/user-attachments/files/16623710/testimage.zip) (I wrapped it into a ZIP to make sure github doesn't transcode the image in any way.)

**Expected behavior**
The image loads.

**Actual behavior**
It fails with `jp2kload: unsupported colourspace -1`.

**Environment**
(please complete the following information)
 - OS: ArchLinux and Alpine 3.20
 - Vips: 8.15.3 and 8.15.2 respectively

**Additional context**
The same image worked fine before updating (and is part of our test suite).

**Comment by jcupitt** [comment]
Hi @aksdb,

Strange, it seems to work for me:

```
john@banana ~/pics $ vips --version
vips-8.15.3
john@banana ~/pics $ unzip testimage.zip 
Archive:  testimage.zip
  inflating: wheel.jp2               
john@banana ~/pics $ vips copy wheel.jp2 x.jpg
john@banana ~/pics $
```

To make:

![x](https://github.com/user-attachments/assets/314f1bad-fa44-4da5-842a-bb7c50e7a6ec)

Perhaps your openjpeg has changed? I have 2.5.0-2build3 (the one that ships with ubuntu 24.04).

**Comment by aksdb** [comment]
Oh good point, it seems like openjpeg was also updated from 2.5.0 to 2.5.2 in both cases. I'll see if I can downgrade it and if that changes the behavior.

**Comment by aksdb** [comment]
Damn, that's it. Downgrading it on my Arch system back to 2.5.0 fixes the issue.

I don't know how the interaction between vips and openjpeg works, so please excuse if this is a dumb question: but would this behavior hint towards a regression in openjpeg or rather towards missing compatibility with this new version in vips? (In the latter case I assume this bug report is not really a bug then. At least not in vips.)

**Comment by jcupitt** [comment]
I guess openjpeg have changed their API slightly and libvips isn't ready :( We'll probably need to revise the libvips openjpeg connector for the next libvips version.

In the meantime, keeping it pinned to 2.5.0 seems to be a workaround, phew.

**Comment by jcupitt** [comment]
It seems openjpeg have changed the code they return for an unknown colourspace. 2.5.0 returned `OPJ_CLRSPC_UNSPECIFIED` (code 0), but with 2.5.2 they return `OPJ_CLRSPC_UNKNOWN` (code -1). A strange change to make in a minor version number.

Anyway, git master libvips now accepts either.

**Comment by jcupitt** [comment]
And thanks for reporting this!

**Comment by aksdb** [comment]
Wow that was fast! Thank you for that quick analysis and fix! :)
