### ISSUE TITLE
Can't find a link for a Linux binary that I can run on RHEL or Ubuntu

### ISSUE THREAD

**Issue by Toseph** [libvips/libvips#4132]
I see that this program can be source compiled or installed via apt-get on Ubuntu according to this, https://github.com/libvips/libvips/wiki/Build-for-Ubuntu 

But I am seeking a statically compiled binary to use on RHEL, and am having issues with the compilation steps there. 

Is it possible I just missed this somewhere? 

Thank you. 

I would like to drop the binary into an nfs network shared folder which is why I do not want to apt-get install it on a single host.

**Comment by Toseph** [comment]
Feel free to close this out. I was able to install it from source on RHEL.

**Comment by erict-square** [comment]
@Toseph May I ask sharing the steps you've taken to get the statically compiled binary working? I think this knowledge might help others who needs libvips on RHEL as well!
