### ISSUE TITLE
Rotation metadata not found/read for HEIF image

### ISSUE THREAD

**Issue by jrasm91** [libvips/libvips#4143]
## Bug report

**Describe the bug**
Rotation metadata is not found for this HEIF image ([IMG_3925.HEIC.zip](https://github.com/user-attachments/files/16919437/IMG_3925.HEIC.zip))

**To Reproduce**
```
vipsheader -a IMG_3925.HEIC | grep Orientation
```

**Expected behavior**
Returns 3 (rotate 180)

**Actual behavior**
No rotation information is found

**Environment**
 - OS: Ubuntu 22.04
 - Vips: [vips-8.15.2]

FWIW exiftool does report the correct value:

```
exiftool -n IMG_3925.HEIC  -Orientation
Orientation                     : 3
```

**Comment by lovell** [comment]
Did you see https://github.com/libvips/libvips/issues/2551 ?

**Comment by jrasm91** [comment]
No, I did not. This can probably be closed as a duplicate then. Is the TLDR that it is working per the spec and rotation on HEIF is ignored on purpose?

**Comment by lovell** [comment]
Thanks, let's continue to track this at https://github.com/libvips/libvips/issues/2551
