### ISSUE TITLE
Problem in Loading HEIC Image captured after upgrade to iOS18

### ISSUE THREAD

**Issue by vikasjio** [libvips/libvips#4169]
## Bug report

**Describe the bug**
vips_image_new_from_file gives error for images captured on some iPhones with iOS 18.0. Issue confirmed on iPhone 15 after upgrade to iOS 18.0. It used to work ok till iOS17.5.1 at least.
Images captured with iPhone 13 mini are working ok even after upgrade to iOS18.

For iPhone15 with iOS18 (and some other combinations) captured images, issue is same for live image (2-3 seconds duration) and normal images.

Same issue with vips commandline:
vips jpegsave SS_IMG_3587.HEIC SS_IMG_3587.jpeg
SS_IMG_3587.HEIC: bad seek to 4588582
heif: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0)

**To Reproduce**
1. Use attached Image
[SS_iphone15.zip](https://github.com/user-attachments/files/17137258/SS_iphone15.zip)

2. Use Configuration
Vips 8.15.2 or .3 with libheif and dependencies on RHEL 8.8 or 9.3

**Expected behavior**
Heic sud transcode

**Actual behavior**
Heic failed to transcode

**Screenshots**

**Environment**
(please complete the following information)
 - OS:rhel 8.8
 - Vips 8.15

**Additional context**

**Comment by jcupitt** [comment]
Hello @vikasjio ,

I tried with libeheif's command-line tools:

```
$ heif-info SS_IMG_3586.HEIC
MIME type: image/heic
main brand: heic
compatible brands: mif1, MiHB, MiHE, MiPr, miaf, heic, tmap
Could not read HEIF/AVIF file: Invalid input: Unspecified: Metadata not correctly assigned to image
$ heif-info --version
1.17.6
libheif: 1.17.6
plugin path: /usr/lib/x86_64-linux-gnu/libheif/plugins
```

So I guess it's a problem with this version of libheif. I would test with git master libheif, and if that also fails, have a look on their issue tracker.

**Comment by kipcole9** [comment]
I tried this with `libheif` version 1.18.2 without issue, confirmating your observation @jcupitt:
```bash
% heif-info -v
1.18.2
libheif: 1.18.2
plugin path: /usr/local/Cellar/libheif/1.18.2/lib/libheif

% heif-info /Users/kip/Desktop/SS_IMG_3586.HEIC
MIME type: image/heic
main brand: heic
compatible brands: mif1, MiHB, MiHE, MiPr, miaf, heic, tmap

image: 4284x5712 (id=46), primary
  colorspace: YCbCr, 4:2:0
  bit depth: 8
  thumbnail: 312x416
  color profile: prof
  alpha channel: no
  depth channel: no
metadata:
  Exif: 2774 bytes
transformations:
  angle (ccw): 270
region annotations:
  none
properties:
```

**Comment by jcupitt** [comment]
Ah good to know @kipcole9, thanks!
