### ISSUE TITLE
[8.16] removed symbols

### ISSUE THREAD

**Issue by remicollet** [libvips/libvips#4193]
From `abi-compliance-checker`

Lot of symbols have been moved to almostdeprecated.h so are no more available by default (vips_cache...)
Kind of API breakage implying fix to app using libvips

2 symbols are removed from headers
* vips_buf_appendsc
* vips__chomp

But it seems they were previously removed from the shared library, so probably not a real issue.

Can you please clarify ?

**Comment by remicollet** [comment]
Also for the C++ API

```
- VImage::new_from_memory_steal ( void* data, size_t size, int width, int height, int bands, enum VipsBandFormat format ) [static]  1 
- VImage::new_from_memory_steal ( void const* data, size_t size, int width, int height, int bands, enum VipsBandFormat format ) [static]
```

From` abi-compliance-checker`

> The name of the appropriate symbol for this function on binary level has been changed from **_ZN4vips6VImage21new_from_memory_stealEPvmiii14VipsBandFormat** to **_ZN4vips6VImage21new_from_memory_stealEPKvmiii14VipsBandFormat**. This may cause undefined reference linker error in old client applications.

**Comment by remicollet** [comment]
See reports

https://rpms.remirepo.net/compat_reports/libvips/8.15.5-rc1_to_8.16.0-rc1/compat_report.html (with almostdeprecated included)

https://rpms.remirepo.net/compat_reports/libvips-cpp/8.15.5-rc1_to_8.16.0-rc1/compat_report.html (without almostdeprecated)

**Comment by remicollet** [comment]
About deprecation, having to fix vips PHP extension

See https://github.com/libvips/php-vips-ext/pull/55

Notice than including `almostdeprecated.h` generates tons of errors about unknown type, excerpt:

```
/usr/include/vips/almostdeprecated.h:400:9: error: unknown type name 'VipsPlotFn'; did you mean 'VipsStopFn'?
  400 |         VipsPlotFn fn, void *client1, void *client2, void *client3);
      |         ^~~~~~~~~~
      |         VipsStopFn
/usr/include/vips/almostdeprecated.h:403:17: error: unknown type name 'IMAGE'
  403 | int im_plotmask(IMAGE *im, int ix, int iy, PEL *ink, PEL *mask, VipsRect *r);
      |                 ^~~~~
/usr/include/vips/almostdeprecated.h:403:44: error: unknown type name 'PEL'
  403 | int im_plotmask(IMAGE *im, int ix, int iy, PEL *ink, PEL *mask, VipsRect *r);
      |                                            ^~~

```

**Comment by kleisauke** [comment]
Hi @remicollet,

Thanks for reporting this!

> Lot of symbols have been moved to almostdeprecated.h so are no more available by default (vips_cache...)
> [...]
> https://rpms.remirepo.net/compat_reports/libvips/8.15.5-rc1_to_8.16.0-rc1/compat_report.html (with almostdeprecated included)

The ABI report in PR #4187 missed this, likely because it was run over all public headers. Functions like `im_affine` weren't changed in 8.16.0-rc1. Is it possible that the previous `abi-dumper` result didn't include `almostdeprecated.h`, leading to the detection of these symbols as new?

> 2 symbols are removed from headers
> 
> * vips_buf_appendsc
> * vips__chomp

`vips_buf_appendsc()` was removed in commit 2fb5164455d7c8780191560e42d36064022dddc3 since it was a stray declaration.

`vips__chomp()` was a private API (indicated by the double underscore), and the `VIPS_API` macro wasn't applied to this function, so the removal should be fine.

> Also for the C++ API
> [...]
> https://rpms.remirepo.net/compat_reports/libvips-cpp/8.15.5-rc1_to_8.16.0-rc1/compat_report.html (without almostdeprecated)

Commit 75174cd811ee2256b065c6f6dcfd18de4877eff9 did this and `VImage::new_from_memory()`  / `VImage::new_from_memory_copy()` weren't affected. Perhaps we should move the implementation to the header to resolve this? 

Note that in C99, this doesn't qualify as an ABI break, but I'm uncertain about C++, see: https://github.com/libvips/libvips/pull/4189#issue-2573821337.

> Notice than including `almostdeprecated.h` generates tons of errors about unknown type

IIUC, `almostdeprecated.h` cannot be included directly, it needs to be included via `vips7compat.h`, see for example:
https://github.com/libvips/libvips/blob/d42e194ab4cbffddc5fe4205c5ca880116168505/libvips/conversion/cache.c#L51-L55

**Comment by remicollet** [comment]
> Is it possible that the previous abi-dumper result didn't include almostdeprecated.h, leading to the detection of these symbols as new?

Yes, I add it for 8.16

**Comment by remicollet** [comment]
> Note that in C99, this doesn't qualify as an ABI break, but I'm uncertain about C++, see: [#4189 (comment)](https://github.com/libvips/libvips/pull/4189#issue-2573821337).

It is as the function signature change from _ZN4vips6VImage21new_from_memory_stealEPvmiii14VipsBandFormat to _ZN4vips6VImage21new_from_memory_stealEPKvmiii14VipsBandFormat. 

A program using new_from_memory_steal and build with 8.15 will use _ZN4vips6VImage21new_from_memory_stealEPvmiii14VipsBandFormat which is removed in 8.16

**Comment by kleisauke** [comment]
I've just opened PR #4195 to ensure ABI compatibility for the `VImage::new_from_memory_steal()` symbol.

**Comment by remicollet** [comment]
> IIUC, almostdeprecated.h cannot be included directly

If confirmed, see PR #4196, else need to be fixed

**Comment by kleisauke** [comment]
> Lot of symbols have been moved to almostdeprecated.h so are no more available by default (vips_cache...)
> [...]
>About deprecation, having to fix vips PHP extension
> See https://github.com/libvips/php-vips-ext/pull/55

Thinking about this further, perhaps we should make `vips7compat.h` part of `vips.h` unless building with
`-Ddeprecated=false`? I had a quick go with commit https://github.com/kleisauke/libvips/commit/eee7a7e01f5514ab790aae2905aef32c7b1a06a0. @jcupitt WDYT?

**Comment by jcupitt** [comment]
> perhaps we should make vips7compat.h part of vips.h unless building with -Ddeprecated=false?

I agree, this sounds sensible.

**Comment by kleisauke** [comment]
PR #4197 makes `vips7compat.h` part of `vips.h`. Once that lands, this issue can likely be closed.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kleisauke** [comment]
I think we can close. The `abi-compliance-checker` results of v8.16.0-rc2 looks OK now:
https://rpms.remirepo.net/compat_reports/libvips/8.15.5_to_8.16.0-rc2/compat_report.html
https://rpms.remirepo.net/compat_reports/libvips-cpp/8.15.5_to_8.16.0-rc2/compat_report.html
