### ISSUE TITLE
What about a vcpkg package?

### ISSUE THREAD

**Issue by patlecat** [libvips/libvips#4204]
Would be awfully cool if you could create a vcpkg package for libvips. 💯

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/discussions/2102

**Comment by jcupitt** [comment]
Our meson build system can generate VS build files:

https://mesonbuild.com/Using-with-Visual-Studio.html

So that's maybe another route. I've not experimented with this myself, perhaps there are some issues.

**Comment by angelmixu** [comment]
there it is!!!
https://github.com/microsoft/vcpkg/pull/50188
It's a WIP draft PR in the meantime, I'd appreciate your suggestions and improvements :)

**Comment by angelmixu** [comment]
> Our meson build system can generate VS build files:
> 
> https://mesonbuild.com/Using-with-Visual-Studio.html
> 
> So that's maybe another route. I've not experimented with this myself, perhaps there are some issues.

about that, in vcpkg a meson build can be configured to output the libraries needed for developing it, it's what I'm using in the port I created, so we wouldn't need any visual studio solution anymore, unless someone wants to use VS to debug the library by themselves for example.

**Comment by jcupitt** [comment]
Hey @angelmixu, I added a few quick comments. Thanks for working on this!
