### ISSUE TITLE
jpegli: `Message codes are not supported, error message is in msg_parm.s string`

### ISSUE THREAD

**Issue by mertalev** [libvips/libvips#4206]
## Bug report

When an error occurs in jpegli, the error message is not shown and this message appears instead. It seems to come from [this](https://github.com/libjxl/libjxl/blob/main/lib/jpegli/error.cc) file.

**To Reproduce**

1. Build jpegli as in [this](https://github.com/immich-app/base-images/blob/03f086ae735ffeed007f50988be9e81db8596ac2/server/bin/build-libjxl.sh) script (we use 0.11.0, i.e. revision 4df1e9eccdf86b8df4c0c7c08f529263906f9c4f)
  a. Note: you need to apply the patch as in the script before building to reproduce the issue, as it fixes another error encountered before the message code issue described here
3. Ensure jpegli is used by setting `LD_PRELOAD`
4. Attempt to process [this](https://github.com/user-attachments/files/17406541/example.zip) file with vips (this was seen in sharp, but not sure if it makes a difference)
5. See error (or rather, don't see the right error)

**Expected behavior**

It should log a more descriptive error such as this (for the sample image):
```
identify: Premature end of JPEG file `2d3c8299-5a81-4e01-abe1-f2879d76bef2.JPG' @ warning/jpeg.c/JPEGWarningHandler/411.
```

**Actual behavior**

It logs this error instead:
```
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
```

**Environment**
(please complete the following information)
 - OS: Debian Bookworm
 - Vips: 8.15.3
 - jpegli: Built with libjxl 0.11.0

**Additional context**

There's another kind of error that does actually display in the logs as normal: `Error: VipsJpeg: ./lib/jpegli/decode_marker.cc:285: DHT marker: no Huffman table found`. [Here](https://github.com/user-attachments/files/17381057/images.zip) are a few sample images that cause this error.

Edit: updated build instructions since the jpegli patch we apply is needed to reproduce the issue for the image provided in step 3

**Comment by kleisauke** [comment]
I could not reproduce this using:
```console
$ git clone --recurse-submodules https://github.com/google/jpegli.git
$ cmake -S jpegli -B build-jpegli -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/opt/jpegli \
    -DBUILD_TESTING=FALSE \
    -DJPEGXL_ENABLE_{SJPEG,OPENEXR,SKCMS,BENCHMARK}=FALSE \
    -DJPEGXL_INSTALL_JPEGLI_LIBJPEG=TRUE \
    -DJPEGLI_LIBJPEG_LIBRARY_VERSION="62.4.0" \
    -DJPEGXL_FORCE_SYSTEM_{BROTLI,LCMS2,HWY}=TRUE
$ cmake --build build-jpegli
$ cmake --install build-jpegli
$ LD_PRELOAD=/opt/jpegli/lib64/libjpeg.so.62.4.0 vips copy ~/Downloads/2d3c8299-5a81-4e01-abe1-f2879d76bef2.JPG x.jpg
VipsJpeg: ./lib/jpegli/decode_marker.cc:286: DHT marker: no Huffman table found
$ LD_PRELOAD=/opt/jpegli/lib64/libjpeg.so.62.4.0 vips copy ~/Downloads/IMG-20230415-WA0001.jpg x.jpg
VipsJpeg: ./lib/jpegli/decode_marker.cc:286: DHT marker: no Huffman table found
$ LD_PRELOAD=/opt/jpegli/lib64/libjpeg.so.62.4.0 vips copy ~/Downloads/IMG-20230509-WA0001.jpg x.jpg
VipsJpeg: ./lib/jpegli/decode_marker.cc:286: DHT marker: no Huffman table found
$ LD_PRELOAD=/opt/jpegli/lib64/libjpeg.so.62.4.0 vips copy ~/Downloads/IMG-20230509-WA0003.jpg x.jpg
VipsJpeg: ./lib/jpegli/decode_marker.cc:286: DHT marker: no Huffman table found
```

Perhaps the patch added in https://github.com/immich-app/base-images/commit/7fa041313e8ec7516ce9a089ef600080b797567f is the root cause of this?

**Comment by mertalev** [comment]
The images in the additional context section are for the ones that work as expected (do show an error). The link in step 3 has the relevant image for this issue.

**Comment by kleisauke** [comment]
The image from step 3 (`2d3c8299-5a81-4e01-abe1-f2879d76bef2.JPG`) was the one I initially tested with. I had a go to rebase that patch on top of https://github.com/google/jpegli (where the jpegli development continues):
https://gist.github.com/kleisauke/2ca3c63fecf042aa24452c7fd45bfa34

After applying the patch, I was able to reproduce the issue. It seems that jpegli deliberately cannot handle/convert this message code:
https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/jpeg2vips.c#L278

It likely can't handle these either:
<details>
  <summary>Details</summary>

https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/jpeg2vips.c#L248
https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/jpeg2vips.c#L251
https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/jpeg2vips.c#L275
https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/vips2jpeg.c#L814
https://github.com/libvips/libvips/blob/a697fe71dd8c6eb3e07fc52709fa0ff663f49da7/libvips/foreign/vips2jpeg.c#L842
</details>


I'm unsure if we can address this, but you can assume that the error message:
```
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
```
likely indicates an unexpected EOF in the input or an unexpected output write error.

**Comment by mertalev** [comment]
Oh, interesting that you could only reproduce it with the patch. I guess that without the patch, it didn't get far enough to produce the message code error because it ran into the DHT marker issue first.

 Do you know what `msg_parm.s` is referring to? I couldn't find any reference to it, but if it's accessible to libvips then it might be possible to use that.

**Comment by kleisauke** [comment]
I've just opened PR #4208 for this.
