### ISSUE TITLE
Ability to not drop duplicate identical frames when saving with CGIF

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#4220]
### Discussed in https://github.com/libvips/libvips/discussions/4219

<div type='discussions-op-text'>

<sup>Originally posted by **cakedan** October 26, 2024</sup>
Currently, by default, CGIF will drop identical frames from a gif. I just figured this out after using it with libvips for months now 😆. Is it possible to add the ability to disable this option?

The option is `CGIF_GEN_KEEP_IDENT_FRAMES` found here https://github.com/dloebl/cgif/blob/c234bc27d4012548faa13798c203219b59b77b09/inc/cgif.h#L17C9-L17C35 used here https://github.com/dloebl/cgif/blob/c234bc27d4012548faa13798c203219b59b77b09/src/cgif.c#L497

Not sure if it goes in the frame config or cgif config found here https://github.com/libvips/libvips/blob/6c397fb7eea08f2f34af6745d65d9f5bc15dbf4f/libvips/foreign/cgifsave.c#L620

Maybe have it be its own parameter in `gifsave` like "keep_duplicate_frames` which would be by default False?

Would love this option as my discord bot kinda depends on duplicate frames not being dropped for some commands :D</div>

**Comment by dloebl** [comment]
I can take on this work. [cgif v0.4](https://github.com/dloebl/cgif/releases/tag/v0.4.0) (released back in April) started to drop duplicate frames by default
