### ISSUE TITLE
IM_NEW、IM_FREE、IM_PI conflict with ImGui package

### ISSUE THREAD

**Issue by oldercoder** [libvips/libvips#4226]
Hi,

When upgrade to latest libvips 8.16, I found these macro IM_NEW、IM_FREE、IM_PI  conflict with ImGui package, is there any simple way to bypass these?

**Comment by jcupitt** [comment]
Hello @oldercoder,

That's interesting, I didn't realize anyone else used the `im_` prefix.

It's the old vips7 prefix. We keep a compatibility layer in vips8 for older programs. We plan to make it disabled-by-default (finally!) within the next year or so.

You can disable it now by defining `VIPS_DISABLE_COMPAT` before including `vips.h`. 

If you set `deprecated` to false you can stop meson building the compatibility layer and defining the wrappers. 

```
$ meson setup build -Ddeprecated=false --prefix ...
```

You might get link conflicts with symbols like `im_free()` etc. without this.

**Comment by oldercoder** [comment]
Thanks for your suggestion @jcupitt , glad to hear that's only for compatibility, at least I will have no concern about the new feature.
