### ISSUE TITLE
Question about exposure / HDR

### ISSUE THREAD

**Issue by dadsays** [libvips/libvips#4230]
### Discussed in https://github.com/libvips/libvips/discussions/4229

<div type='discussions-op-text'>

<sup>Originally posted by **dadsays** October 31, 2024</sup>
Hi,

I have photos that appear to be overexposed after being processed by libvips. The original photo was processed as SDR in lightroom than exported as jxl. When added to MacOS Photos, Preview etc - it appears correctly exposed. But when added to immich (using libvips) it appears overexposed. 

On the left is the immich processed one and on the right is the original. The colorspace is: Display P3; SMPTE ST 2084 PQ. 
<img width="645" alt="Screenshot 2024-10-29 at 23 48 26" src="https://github.com/user-attachments/assets/ae3c5725-cede-41a9-a8c9-527504d6c1c2">

What might be going on here? (Also, let me know if you want me to send you the original file directly for testing.)

</div>

**Comment by jcupitt** [comment]
Hello @dadsays,

I'd guess this is a profile issue. libvips 8.16 (came out a day or two ago) adds support for ICC profiles in JXL, but immich are (probably?) still using 8.15. 

When they update, this should be resolved (I hope). Please reopen if it isn't.
