### ISSUE TITLE
Saving an lossless AVIF image using `subsample-mode=on` is returning a black image

### ISSUE THREAD

**Issue by shun-recall** [libvips/libvips#4232]
## Bug report

I have been trying different configurations to generate lossless AVIF images using `subsample-mode=on` and I'm getting a wrong black image as a result.

I'm using the following command:

```
vips copy image.jpeg image.avif[subsample-mode=on,lossless=true]
```
It's happening with any JPEG image so I'm not attaching any example file.

This was not happening to me with previous versions of vips.

**Environment**
 - Vips: 8.16.0

**Comment by kleisauke** [comment]
Bisected to commit f0d2b2b4a3346a2c7417fe7f616ad7ab1565334a (which was backported to v8.15.3 with commit 3e95b1b044ca635689931148efea9d7b2950bed1). According to the [AV1 Spec](https://aomediacodec.github.io/av1-spec/#color-config-semantics), `matrix_coefficients=0` (CICP x/y/0) is only valid with `heif_chroma_444`.
> If matrix_coefficients is equal to MC_IDENTITY, it is a requirement of bitstream conformance that subsampling_x is equal to 0 and subsampling_y is equal to 0.

We should probably avoid setting `matrix_coefficients` to `0` when saving with `heif_chroma_420`. libavif uses a similar approach:
https://github.com/AOMediaCodec/libavif/blob/99f7eebb6fa21a3330002f35d66842e648da38f5/apps/avifenc.c#L2166-L2179

**Comment by kleisauke** [comment]
Alternatively, we could force `subsample-mode=off` when the `lossless` parameter is used. That is, remove the `&& !vips_object_argument_isset(object, "subsample_mode")` branch here:
https://github.com/libvips/libvips/blob/d4447090598074876e0e2870adb31fff4587d8bf/libvips/foreign/heifsave.c#L529-L534

**Comment by lovell** [comment]
I feel like requesting "lossless" output is a stronger signal than any attempt to set chroma subsampling (plus in my experience AVIF subsampling often produces worse output quality and worse compression ratios).

**Comment by kleisauke** [comment]
I agree, let's always disable chroma subsampling when saving lossless. I just opened PR #4263 for this.

**Comment by shun-recall** [comment]
Thank you everyone involved in solving this issue. Specially @kleisauke for finding the problem and creating the fix. ❤️
