### ISSUE TITLE
How to Crop with CLI?

### ISSUE THREAD

**Issue by ivanjaros** [libvips/libvips#4254]
I want to crop image while specifying location of the crop. Like center, top, left, top-left and so on. The smartcrop seems to be useless and the crop requires me to know all the dimensions, which i don't. Is there some other cropping method I can use to just do "crop image.jpg into 500x500 with focus on top-right corner"?

Using smartcrop with `--attention-x 100000 --attention-y 100000` for top right corner, for example, is not working and I always get center crop. If i change `interesting` to something else, i always get too many arguments error, so the coordinates and method are not cooperating.

**Comment by jcupitt** [comment]
Smartcrop ought to work. For example, with this image:

![owl](https://github.com/user-attachments/assets/7a263a3f-fc49-4976-9861-c0b35277db0f)

I can run:

```
vips smartcrop owl.jpg x.png 300 300
```

To make:

![x](https://github.com/user-attachments/assets/e9a32739-bf61-4e65-8af0-a8d2c406d223)

And it's kind-of found the owl's head.

It's pretty crude and won't always work, of course.

**Comment by jcupitt** [comment]
> I wanted to avoid having to read the file in order to get the dimensions

`vipsheader` is pretty quick, it only reads the image and the image metadata.

**Comment by jcupitt** [comment]
> --attention-x 100000 --attention-y 100000 

Ah, those arguments are for output. You can get some help with eg.:

```
$ vips smartcrop
extract an area from an image
usage:
   smartcrop input out width height [--option-name option-value ...]
where:
   input        - Input image, input VipsImage
   out          - Output image, output VipsImage
   width        - Width of extract area, input gint
			default: 1
			min: 1, max: 100000000
   height       - Height of extract area, input gint
			default: 1
			min: 1, max: 100000000
optional arguments:
   attention-x  - Horizontal position of attention centre, output gint
			default: 0
			min: 0, max: 100000000
   attention-y  - Vertical position of attention centre, output gint
			default: 0
			min: 0, max: 100000000
   interesting  - How to measure interestingness, input VipsInteresting
			default enum: attention
			allowed enums: none, centre, entropy, attention, low, high, all
   premultiplied - Input image already has premultiplied alpha, input gboolean
			default: false
```

They are both "output gint". You use them like this:

```
$ vips smartcrop owl.jpg x.png 300 300 --attention-x --attention-y
337
111
```

They make the operation output the coordinates of the crop box it selected.
