### ISSUE TITLE
Animation effect lost after converting gif to avif

### ISSUE THREAD

**Issue by BrentHuang** [libvips/libvips#4277]
## Questions, enhancements, tips, etc.

Please use libvips discussions for other topics.

https://github.com/libvips/libvips/discussions

## Bug report

**Describe the bug**
Animation effect lost after converting gif to avif

**To Reproduce**

`vips heifsave 9.gif 9.avif`

**Expected behavior**
9.avif has animation effects

**Actual behavior**
9.avif has no animation effect

**Screenshots**

![9](https://github.com/user-attachments/assets/4fd7e95f-986a-45bb-b7a6-c76036e84f0d)

**Environment**
(please complete the following information)
 - OS: Ubuntu 22.04, WSL2, Windows10
 - Vips: vips-8.12.1-Wed Feb  2 14:43:28 UTC 2022

**Additional context**

**Comment by jcupitt** [comment]
Hello @BrentHuang,

libheif (the library we use to write AVIF containers) has not yet released support for animated AVIF. When they do, we'll add support in libvips and it should become available.

See https://github.com/libvips/libvips/issues/3629

**Comment by 1057744048** [comment]
Hi,
I noticed that libheif now supports animated AVIF.

Since libvips uses libheif for AVIF, are there any plans to expose animated AVIF support in libvips as well (e.g. loading/saving multiple frames when available)?

Thanks for all the great work!

**Comment by jcupitt** [comment]
Hi again, I removed the "blocked upstream" label on the entrancement issue ^^^ Hopefully it'll happen in the 8.19 cycle.
