### ISSUE TITLE
CLI: vips dzsave fails to extract associated image when creating SZI files

### ISSUE THREAD

**Issue by goran-hc** [libvips/libvips#4278]
**Describe the bug**
When trying to produce deep zoom image with SZI container format, `dzsave` CLI command fails with:

```
root@a2794bfcf3c6:/test# vips dzsave CMU-3.ndpi CMU-3.szi --suffix '.jpg' --vips-progress
vips temp-2: 71680 x 50688 pixels, 16 threads, 128 x 128 tiles, 384 lines in buffer
vips temp-2: done in 39.5s
VipsImage: field "openslide.associated.macro.height" is of type VipsRefString, not VipsImage
```

Using `--strip` option doesn't make difference.

**To Reproduce**
1. Use openslide image (from examples list): [CMU-3.ndpi](https://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/CMU-3.ndpi)
2. Run `vips dzsave CMU-3.ndpi CMU-3.szi --suffix '.jpg'`
3. See error

**Expected behavior**
SZI should be successfully created.

**Actual behavior**
The (re)tiling process succeeds but extracting associated image fails.

**Environment**
(please complete the following information)
 - OS: [docker container based on debian:bookworm-slim]
 - Vips: [8.16.0] (built from source)
 - Openslide: [4.0.0] (built from source)

**Additional context**
Used following dependencies when building Openslide and Vips

Openslide dependencies:
```
glib-2.0-dev
libcairo2-dev
libgdk-pixbuf-2.0-dev
libjpeg-dev
libopenjp2-7-dev
zlib1g-dev
libtiff-dev
libxml2-dev
libpng-dev
libsqlite3-dev
```

Vips dependencies:
```
librsvg2-dev
libarchive-dev
libexif-dev
liblcms2-dev
libheif-dev
libhwy-dev
libtiff-dev
libcairo2-dev
libcfitsio-dev
libcgif-dev
libexpat1-dev
libfontconfig1-dev
libheif-dev
libimagequant-dev
libjpeg-dev
libjxl-dev
libmagickcore-6.q16-dev
libopenexr-dev
libopenjp2-7-dev
libpango1.0-dev
libspng-dev
libfftw3-double3
libpangocairo-1.0-0
libpangoft2-1.0-0
```

**Comment by goran-hc** [comment]
My workaround was to use ZIP instead of SZI to avoid extracting the associated image:

https://github.com/libvips/libvips/blob/e38953c5dfa302875c4578ad1222b114ee6eac69/libvips/foreign/dzsave.c#L2289-L2291

The problem lays in `vips_image_get_image` where `meta_get_value` expects VIPS_TYPE_IMAGE instead of VIPS_TYPE_REF_STRING.

https://github.com/libvips/libvips/blob/e38953c5dfa302875c4578ad1222b114ee6eac69/libvips/iofuncs/header.c#L2012-L2023

**Comment by sderaedt** [comment]
The problem stems from the check if the field starts with `openslide.associated` which also matches the `openslide.associated.macro.height` and `openslide.associated.macro.width` fields returned by openslide 4.

https://github.com/libvips/libvips/blob/e38953c5dfa302875c4578ad1222b114ee6eac69/libvips/foreign/dzsave.c#L973

A possible fix is to check if the field is a string as follows:

```c
static void *
write_associated_images(VipsImage *image,
        const char *field, GValue *value, void *a)
{
        VipsForeignSaveDz *dz = (VipsForeignSaveDz *) a;

        char *str;

        // Check if field is a string
        if (vips_image_get_as_string(image, field, &str) == 0) {
                printf("Read field %s: %s\n", field, str);
                return NULL;
        }

....
```

**Comment by jcupitt** [comment]
Hello @goran-hc,

Thanks for reporting this. I agree, this works for openslide 3.4.1, but fails with openslide4 due to the new metadata (as you say). I'll make a PR.

**Comment by jcupitt** [comment]
I made a PR and credited you. Let's move any discussion there.

Thanks again for reporting this!

**Comment by kleisauke** [comment]
FWIW, I noticed that no PR has been created (yet) for the changeset at https://github.com/libvips/libvips/compare/8.16...fix-dzsave-with-openslide4.

Since it's a minor change, feel free to commit it directly to the 8.16 branch :+1: .

**Comment by jcupitt** [comment]
Ooop I forgot to press the PR button, duh :( 

Here it is: https://github.com/libvips/libvips/pull/4286

I'll merge, this will be in 8.16.1.
