### ISSUE TITLE
Regression since version 15.5, "tiff2vips: read error"

### ISSUE THREAD

**Issue by CrispinStichartFNSB** [libvips/libvips#4317]
## Bug report

When using version 15.5 or 16.0 to process the attached image, vips crashes with `tiff2vips: read error`. 

Before the error, there are some warnings (the first one about the missing tag is repeated 8 times):

```
(vips.exe:25624): VIPS-WARNING **: 10:48:07.177: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

(vips.exe:25624): VIPS-WARNING **: 10:48:07.285: Premature EOL at line 7212 of strip 0 (got 0, expected 9600)

(vips.exe:25624): VIPS-WARNING **: 10:48:07.287: error in tile 0 x 7200

(vips.exe:25624): VIPS-WARNING **: 10:48:07.288: error in tile 0 x 2150
```

When using version 15.3, it gives some warnings, but _does_ successfully process the image. It gives the above warning about the "Software" tag, as well as a bunch of:

```
(vips.exe:38280): VIPS-WARNING **: 10:50:42.521: Premature EOF at line 7212 of strip 0 (x 0)

(vips.exe:38280): VIPS-WARNING **: 10:50:42.522: Premature EOL at line 7212 of strip 0 (got 0, expected 9600)
```

I was not able to test with 15.4, as the [link to the windows binaries](https://github.com/libvips/build-win64-mxe/releases/tag/v8.15.4) on the release page 404s.

**To Reproduce**

1. Use [the attached image](https://github.com/user-attachments/files/18116811/error_tiff.zip)
2. Run `vips copy error_tiff.tif output.tif`

**Expected behavior**
It copies the image.

**Actual behavior**
It crashes with `tiff2vips: read error`. 

**Environment**

 - OS: Windows 11
 - Vips: 15.5 (16.0 also crashes with the same error)

**Additional context**

`tiffinfo` for the image:

```
> tiffinfo error_tiff.tif
TIFFFetchNormalTag: Warning, ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
=== TIFF directory 0 ===
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 9600 Image Length: 7400
  Resolution: 400, 400 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Samples/Pixel: 1
  Rows/Strip: 7400
  Planar Configuration: single image plane
  Software: PLP Scanner Interface for XEROX 7356
```

Based on my research it seems that 7400 rows per strip is kinda weird, but I've tested a few images, and it's not a large strip size that causes the crash (or at least, it's not _just_ a large strip size).

**Comment by jcupitt** [comment]
Hi @CrispinStichartFNSB,

8.16 works for me on linux with your image (though there are a lot of warnings, as you say).

I'd guess this is a crash in the libtiff version we use for the windows binary. That build is on libtiff 4.7.0 now, I'll try that on linux.

**Comment by jcupitt** [comment]
Yes, it looks like libtiff 4.7.0 will refuse to read your image. `TIFFReadEncodedStrip()` returns -1, meaning catastrophic failure.

**Comment by jcupitt** [comment]
Ah, looking at the libtiff sources, they use a -1 return there to mean just a warning, which is bizarre. I'll make a libvips PR.

**Comment by jcupitt** [comment]
I made a PR, let's shift any discussion there. Thanks for reporting this!
