### ISSUE TITLE
libvips 8.15 using api thumbnail and jpegsave, some machine saved image occur like attachment

### ISSUE THREAD

**Issue by ovelin** [libvips/libvips#4327]
![微信截图_20241224101619](https://github.com/user-attachments/assets/a441a58d-f0f7-4301-a025-875ae4f9a404)

**Comment by ovelin** [comment]
original image background is black

**Comment by jcupitt** [comment]
Hi @ovelin, you need to give a lot more information before we could reproduce this. What image were you processing, what libvips version, what platform, etc. etc.

**Comment by ovelin** [comment]
@jcupitt think you very much for your quick resposne，8.15.0 has problem, upgrade to 8.15.1 is gone.
