### ISSUE TITLE
vipsthumbnail interpolators

### ISSUE THREAD

**Issue by ferryfax** [libvips/libvips#45]
I'm trying to use different interpolators with the Windows version of vipsthumbnail and I'm having trouble knowing what values to pass with the --interpolator switch. When I try and get a list of available interpolators from vips this is what i get::-

C:\Projects\Common\vips-dev-7.30.3\bin>vips --list classes
possible actions:
      list - list classes|packages|all|package-name|operation-name
      cpph - generate headers for C++ binding
      cppc - generate bodies for C++ binding
     links - generate links for vips/bin
<operation> - execute named vips operation
vips: unknown action "classes"

**Comment by sergeevabc** [comment]
Does `--interpolator` flag still work with `vipsthumbnail`?

``` console
$ vipsthumbnail in.jpg -s 65x65 --smartcrop entropy --linear --interpolator vsqbs -o out.png
```

**Comment by jcupitt** [comment]
Hi @sergeevabc, no, the `interpolator` flag was deprecated a while ago, it doesn't do anything now.

`vipsthumbnail` now picks an interpolator for you automatically depending on the resize operation. If you need more control, you need to call the resize operations yourself.
