### ISSUE TITLE
Vips is not finishing dzsave with one image

### ISSUE THREAD

**Issue by yurykovshov** [libvips/libvips#549]
Hi John,

There is a strange issue with one image.
Briefly: there is a service, which reads a queue and process (tiles) images by calling **dzsave**. Plus some infrastructure actions around.
Recently we've got one image which cannot be tiled successfully.
I have noticed the following:
1) On the local development machine everything is fine. 
2) In the cloud (Azure, Windows Server) - it is not working. Basically VIPS does not creates the result tiles.
2.1) vipsthumbnailing works fine - creates all thumbnails.
2.2) There is a strange logs coming from VIPS when working with this image:

> vips.exe temp-1: 3628 x 16374 pixels, 2 threads, 3628 x 16 tiles, 256 lines in buffer
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 16374 x 3628 pixels, 2 threads, 16374 x 16 tiles, 256 lines in buffer
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 0% complete
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 1% complete
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 2% complete
...
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 91% complete
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 98% complete
vips.exe C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v: 100% complete

2.3) To compare there is standard logs of any successfull image:

> vips.exe temp-1: 2048 x 1365 pixels, 2 threads, 2048 x 16 tiles, 256 lines in buffer
vips.exe temp-1: 1% complete
vips.exe temp-1: 2% complete
vips.exe temp-1: 3% complete
...
vips.exe temp-1: 99% complete
vips.exe temp-1: 100% complete
**vips.exe temp-1: done in 0.407s**          

So **done** is here, but there is no done for the problem image. Looks like VIPS was unable to finish his work. Plus there is some weird Path was added to VIPS "C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v". 
Plus in the beginning VIPS writing 2 times "3628 x 16374 pixels, 2 threads, 3628 x 16 tiles, 256 lines in buffer".
There is no any difference in running VIPS for both images, except the different filenames, width, height.

2.4) Image has some EXIF data. It's a panorama made by iPhone 6s. We found that it has swapped width and height values.

2.5) When I saved this image as PNG - everything is fine.

So I was thinking maybe you could know what's going on, any ideas. And give me some direction to dig.

I've attached this image.
![_problem-image](https://cloud.githubusercontent.com/assets/7525042/19854537/c92c23cc-9f6f-11e6-9ea6-2feed24fe1f7.JPG)

Thanks in advance.

**Comment by jcupitt** [comment]
Hi @yurykovshov,

Sorry, I'm not sure. The extra filename stuff at the start of the temporary filename is strange, that seems to mean that vips is using a real file for the temp, instead of streaming through memory. 

Could you have a look at `C:\Resources\temp\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler\RoleTemp\vips-1-4GZ1PY.v` during processing and check if there is a file there?

It could also be a filename mixup. What happens if you rename the source file as something simple like `fred.jpg` and try?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by jcupitt** [comment]
Thanks for this gardening, @sandstrom
