### ISSUE TITLE
Considering accepting Open Collective donations and sponsors

### ISSUE THREAD

**Issue by h2non** [libvips/libvips#592]
Hi @jcupitt,

Since `libvips` became a strong image processing alternative used by thoundans of individuals and companies, I think you should considering accepting community donations and project sponsors.

Open Collective is a good way of doing this. If sounds good to you, you can try subscribing `libvips` project  here:
https://opencollective.com

Example project using Open Collective:
https://github.com/apex/apex

**Comment by jcupitt** [comment]
Hi @h2non, interesting idea, I'll have a look.

**Comment by lovell** [comment]
https://opencollective.com/libvips now exists and PR #1431 adds a link to it.

**Comment by lovell** [comment]
I just noticed many of the images on the Open Collective site such as avatars, banners etc. are processed via sharp and therefore libvips - see https://github.com/opencollective/opencollective-images

**Comment by jcupitt** [comment]
Oh, how funny.

Well done for sorting this out Lovell! I guess the "sponsor" button takes a while to appear. I'll point people at it next time someone offers funding.
