### ISSUE TITLE
have a go with oss-fuzz

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#695]
See https://github.com/google/oss-fuzz

**Comment by jcupitt** [comment]
Tried so far:

1. It needs libfuzzer, which became part of clang in April 2017. The simplest way to get a working install is to build current clang from source. You can do this via git with: http://llvm.org/docs/GettingStarted.html#for-developers-to-work-with-a-git-monorepo

```
$ mkdir clang
$ cd clang/
$ export TOP_LEVEL_DIR=`pwd`
$ git clone https://github.com/llvm-project/llvm-project-20170507/ llvm-project
$ cd llvm-project
$ git config branch.master.rebase true
$ cd ..
$ mkdir clang-build && cd clang-build
$ cmake -GNinja ../llvm-project/llvm -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi"
$ ninja 
... wait for many, many hours
```

2.

**Comment by jcupitt** [comment]
Update: found and fixed two issues with libvips load-jpeg-from-buffer code, it seems to run well now. I'll leave it fuzzing over the weekend.

**Comment by jcupitt** [comment]
25,000 minutes of CPU time with no issues \o/

tiff and png next.

**Comment by kleisauke** [comment]
Any success so far with OSS-Fuzz integration? I saw that tiff and png load from buffer have been added. Are there any issues found in those specific loaders?

**Comment by jcupitt** [comment]
No issues found, but I should try some more. I became side-tracked with fixing up those language bindings :( 

8.6 has the libjpeg fixes in.

**Comment by kaspergrubbe** [comment]
An integration with oss-fuzz would be really cool, I was just about to add the issue to the project, and then I noticed this issue existed.

**Comment by kaspergrubbe** [comment]
It also seems like Google might pay for the integration based on this blogpost here: https://security.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html

**Comment by jcupitt** [comment]
Oh, interesting, thanks for the link @kaspergrubbe.

I was actually looking at this last week and it seems it's bitrotted in the last two years. It needs to all be done again, following the latest guidelines. Perhaps after 8.8 is out (hopefully RSN).

**Comment by jcupitt** [comment]
This is all done and integrated now, thanks to the efforts of @omira-sch.

It's been fuzzing for a week or two and only found a couple of small things (mostly), so a result!

**Comment by kaspergrubbe** [comment]
Wow thats amazing!
