### ISSUE TITLE
vips_thumbnail: (CIE)LAB TIFF to sRGB

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#730]
It seems that `vips_thumbnail` has some issues with processing a (CIE)LAB TIFF to the sRGB colourspace.

[Input image](https://github.com/lovell/sharp/raw/master/test/fixtures/cielab-dagams.tiff)
[sRGB profile](https://github.com/jcupitt/nip2/blob/master/share/nip2/data/sRGB.icm)

**Input image to sRGB png**
```bash
vipsthumbnail cielab-dagams.tiff \
    --size 200x \
    -o %s_thumbnail_srgb.png \
    --eprofile sRGB.icm
````

Warnings:
```bash
(vipsthumbnail:17830): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored (x8)
(vipsthumbnail:17503): VIPS-WARNING **: icc_transform: intent 1 (relative) not supported by input profile; falling back to default intent
```

Output (wrong):
![cielab-dagams_thumbnail_srgb](https://user-images.githubusercontent.com/12746591/30172888-54d44e92-93f6-11e7-8f32-a16a45f3d938.png)

**Input image to sRGB png with the perceptual intent**
```bash
vipsthumbnail cielab-dagams.tiff \
    --size 200x \
    -o %s_thumbnail_srgb_percep.png \
    --intent perceptual \
    --eprofile sRGB.icm
````

Warning (x8):
```bash
(vipsthumbnail:17830): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
```

Output (wrong):
![cielab-dagams_thumbnail_srgb_percep](https://user-images.githubusercontent.com/12746591/30172875-4745652c-93f6-11e7-829c-bc14cab3c4a9.png)

**Input image to png (without the `--eprofile` flag)**
```bash
vipsthumbnail cielab-dagams.tiff \
    --size 200x \
    -o %s_thumbnail.png
````

Same warnings as the second command.

Output (correct):
![cielab-dagams_thumbnail](https://user-images.githubusercontent.com/12746591/30172867-4479db0c-93f6-11e7-8c8b-0530db26764c.png)

Tested with libvips 8.6.0-alpha2.

**Comment by jcupitt** [comment]
Hi Kleis, I think your image is wrong. CIELAB images should not have profiles attached to them, they are in profile connection space already. This is like an RGB image with a CYMK profile. 

Perhaps `thumbnail` should ignore the input profile for CIELAB images?

**Comment by jcupitt** [comment]
Heh there's a comment about this case in the code:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L360

I'll see if I can disable import for CIELAB images.

**Comment by jcupitt** [comment]
I might have found a smaller test case. This command:

```
vips icc_transform x.jpg y.jpg /usr/share/color/icc/sRGB.icc --embedded
```

With this test image:

![x](https://user-images.githubusercontent.com/580843/30181891-c32b4394-940c-11e7-8ac5-9440b07835f9.jpg)

Seems to fail.

**Comment by jcupitt** [comment]
```
$ vipsheader -f icc-profile-data x.jpg | base64 -di > x.icc
$ iccdump x.icc
icc:
Header:
  size         = 544 bytes
  CMM          = 'lcms'
  Version      = 2.1.0
  Device Class = Abstract
  Color Space  = Lab
  Conn. Space  = Lab
  Date, Time   = 7 Nov 2016, 18:05:20
.. etc.
```

So this is a null profile which just connects LAB to LAB. By the time `vipsthumbnail` applies it, the image is already sRGB, so the profile is no longer correct. I agree, this looks like a `thumbnail` bug.

**Comment by kleisauke** [comment]
Ah OK, I once again have found a strange image. 😅 

Maybe `icc_transform` should ignore null-profiles instead of `vipsthumbnail`?

**Comment by jcupitt** [comment]
It has code for ignoring inappropriate profiles (CMYK profiles on sRGB images, for example), it just doesn't pick up the error in this case. I'll see if there's some way we can tell that the profile is wrong.

**Comment by jcupitt** [comment]
I added some more sanity checking, so it now refuses to import an image with an incompatible profile. I see:

```
$ vips icc_transform lab-profile.jpg y.jpg /usr/share/color/icc/colord/sRGB.icc --embedded
(vips:24840): VIPS-WARNING **: embedded profile colourspace differs from image
icc_transform: no input profile
```
With `vipsthumbnail` you see:

```
$ vipsthumbnail cielab-dagams.tiff --eprofile /usr/share/color/icc/colord/sRGB.icc
(vipsthumbnail:25258): VIPS-WARNING **: embedded profile colourspace differs from image
(vipsthumbnail:25258): VIPS-WARNING **: unable to import with embedded profile: icc_transform: no input profile
```

but it does produce output.

**Comment by jcupitt** [comment]
OK, this is hopefully resolved for 8.6. Thanks!

**Comment by kleisauke** [comment]
Just tested with master and this issue is indeed solved. Sorry for the delayed response.

Can't wait to test 8.6 in production!

**Comment by kleisauke** [comment]
Re-opening as the second test case is regressed.
```bash
$ vipsthumbnail cielab-dagams.tiff \
    -s 200x \
    -o %s_thumbnail_srgb_percep.png \
    -n perceptual \
    -e sRGB
```
![cielab-dagams_thumbnail_srgb_percep](https://user-images.githubusercontent.com/12746591/206873101-42fe40e0-c6fe-4aa3-93c8-971618414f95.png)

git bisected to commit 1297f2c6d790aba928c1f9376674890ad75c6e39, so it looks like we need a similar fix to what was done in commit 3d29daf553adbe24d4375fb7ad487bc60d7b3cf3. Though, I'm not sure how common this case is.

Note that this was detected on sharp's test suite, so another option would be to fix this image fixture. For reference, it was detected on [this test](https://github.com/lovell/sharp/blob/83bb6a45542cbced5d68a258070f256f6ca8cee3/test/unit/resize-contain.js#L119-L135), causing `embed-lab-into-rgba.png` to be generated as:
![embed-lab-into-rgba](https://user-images.githubusercontent.com/12746591/206872701-63a74691-e22d-46ee-9c82-9b6a5897caad.png)
Instead of:
![embed-lab-into-rgba](https://github.com/lovell/sharp/raw/main/test/fixtures/expected/embed-lab-into-rgba.png)

A simple regression test for this would be to simply check that the ICC profile is preserved during conversion. For example:

Before:
```console
$ curl -LO https://github.com/lovell/sharp/raw/main/test/fixtures/cielab-dagams.tiff
$ vips copy cielab-dagams.tiff x.jpg
$ vipsheader -f icc-profile-data x.jpg
vipsheader: vips_image_get: field "icc-profile-data" not found
```

After:
```console
$ curl -LO https://github.com/lovell/sharp/raw/main/test/fixtures/cielab-dagams.tiff
$ vips copy cielab-dagams.tiff x.jpg
$ vipsheader -f icc-profile-data x.jpg
<544 bytes of binary data encoded as base64>
```

**Comment by kleisauke** [comment]
> Note that this was detected on sharp's test suite, so another option would be to fix this image fixture

I just opend PR https://github.com/lovell/sharp/pull/3510 for this.

**Comment by kleisauke** [comment]
I'll close, I think this case is _not_ common enough to introduce another if-statement (similar to what was done in commit 3d29daf553adbe24d4375fb7ad487bc60d7b3cf3).
