### ISSUE TITLE
Error creating pyramid TIF

### ISSUE THREAD

**Issue by haehn** [libvips/libvips#79]
Hi,

I have a 1-channel 32 bit 1024x1024 TIF file which displays nicely.

Then, I want to convert it to a pyramid TIF. ImageMagick just produces a black image so I wanted to try VIPS:

$ vips im_vips2tiff 0.tif "p_0.tif,tile,pyramid"
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order.
vips warning: TIFFReadDirectoryCheckOrder: Invalid TIFF directory; tags are not sorted in ascending order
vips warning: TIFFReadDirectoryCheckOrder: Invalid TIFF directory; tags are not sorted in ascending order
vips warning: tiff2vips: no resolution information for TIFF image "0.tif" -- defaulting to 1 pixel per mm
tiff2vips: unsupported sample format 1 for greyscale image

I think the warnings might be ok but the last error not? Did anybody see something like this yet?

Thank you very much!
Daniel

**Comment by mrgloom** [comment]
How to resolve this problem?
~~~
vips -v
vips-7.26.3-Fri Nov 18 16:39:54 UTC 2011
~~~

~~~
vips tiffsave
possible actions:
      list - list classes|packages|all|package-name|operation-name
      cpph - generate headers for C++ binding
      cppc - generate bodies for C++ binding
     links - generate links for vips/bin
<operation> - execute named vips operation
vips: unknown action "tiffsave"
~~~

vips was installed on Ubuntu 12.04 via `sudo apt-get install libvips-tools`

**Comment by jcupitt** [comment]
Hello @mrgloom, your Ubuntu is very old and does not have vips8 (`tiffsave` is the vips8 syntax).

You can use the vips7 syntax like this:

```
$ vips im_vips2tiff somefile.tif pyramid.tif:jpeg,tile,pyramid
```

**Comment by mrgloom** [comment]
How to resolve this problem?
~~~
vips -v
vips-7.26.3-Fri Nov 18 16:39:54 UTC 2011
~~~

~~~
vips tiffsave
possible actions:
      list - list classes|packages|all|package-name|operation-name
      cpph - generate headers for C++ binding
      cppc - generate bodies for C++ binding
     links - generate links for vips/bin
<operation> - execute named vips operation
vips: unknown action "tiffsave"
~~~

vips was installed on Ubuntu 12.04 via `sudo apt-get install libvips-tools`
