### ISSUE TITLE
fix --enable-deprecated=no 

### ISSUE THREAD

**Issue by rtennill** [libvips/libvips#798]
Building from a fresh git clone on linux (Mint 17.3) fails when specifying --enable-deprecated=no. I initially build with 'make -j' but have also tried a sequential build and got the same errors. Building without this option is successful.

> [truncated]
./.libs/libvips.so: undefined reference to `vips_info_set'
./.libs/libvips.so: undefined reference to `im_scale'
./.libs/libvips.so: undefined reference to `im_powtra'
./.libs/libvips.so: undefined reference to `im_Lab2disp'
./.libs/libvips.so: undefined reference to `im_spcor'
./.libs/libvips.so: undefined reference to `im_free_dmask'
collect2: error: ld returned 1 exit status
make[3]: *** [introspect] Error 1
make[3]: Leaving directory `repos/libvips/libvips'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `repos/libvips/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `repos/libvips'
make: *** [all] Error 2

**Comment by jcupitt** [comment]
Hello, yes, the flag to disable the deprecated stuff doesn't work yet, there are still some chunks that need rewriting. Perhaps in 8.7.

**Comment by jcupitt** [comment]
Work on this problem is now being tracked here: https://github.com/libvips/libvips/issues/1273
