### ISSUE TITLE
vips dzsave tilesize

### ISSUE THREAD

**Issue by PetterRanefall** [libvips/libvips#80]
Is it possible to create larger tiles than 1024x1024 using vips dzsave? When I try vips dzsave using the flag --tile-size with a number greater than 1024 I still get tiles with size 1024.

**Comment by gil-c** [comment]
Hello, with LibVips 8.9, I saved a tiled tiff image with tile size of 2448 / 2048, but then when I open it again it says: tiff2vips: tile size out of range.
