### ISSUE TITLE
Add save to descriptor

### ISSUE THREAD

**Issue by UnitedMarsupials** [libvips/libvips#803]
It makes sense that the target filename is examined to determine the desired file type.

But it should not be the only way to specify the type. Say, for example, my PHP-application needs to output the image to stdout or a network socket... Currently, the only way to do that is by writing the entire image into a buffer, and then deal with the buffer.

The `vips_image_write_to_*` ought to examine the the options list _first_ and only fall back to checking the filename extension, if `format` is not specified in the options...

**Comment by jcupitt** [comment]
Hello, the `write_to_buffer` function is very simple: it looks at the suffix and finds the highest-priority saver that supports that extension.

You can call the savers directly, for example in Python:

```python
data = image.jpegsave_buffer(Q=85)
```

Unfortunately llibvips does not support writing to a socket -- it's just file or memory buffer. If your platform is linux, you can write to a named pipe, or to something like `/dev/stdout`, if that's any help.

**Comment by UnitedMarsupials** [comment]
> You can call the savers directly

Heh, I can call into the relevant format-specific libraries directly too. But, if I'm using VIPS API, I'd like to stay within it...

> Unfortunately llibvips does not support writing to a socket

Why does it matter to the library, where the file-descriptor came from? Maybe, some savers require a _seekable_ object, but I doubt many of them do...

**Comment by jcupitt** [comment]
It's still in the libvips API, just a different function. In PHP:

```php
$image->jpegsave("/dev/stdout");
```

To write a JPG to stdout. 

There's a branch that adds true streaming to and from sockets (if the format supports it), but it's never been merged, for various reasons. 

There was a long discussion here:

https://github.com/lovell/sharp/issues/30

**Comment by jcupitt** [comment]
... but I agree that write to a file descriptor would be a nice, and fairly simple addition. Would that meet your needs?

**Comment by UnitedMarsupials** [comment]
> Would that meet your needs?

How would I specify the filetype? If the same way it is done for when writing to a buffer, then yes :)

**Comment by jcupitt** [comment]
Yes, something like `$image->writeToDescriptor(".jpg", stdout);` I suppose.

**Comment by UnitedMarsupials** [comment]
> Yes, something like $image->writeToDescriptor(".jpg", stdout); I suppose.

Or `vips_image_write_to_filedescriptor()`, right? Yes, that works, thank you!

**Comment by jcupitt** [comment]
Nope :( not yet.

**Comment by ioquatix** [comment]
It would be nice to provide our own function pointer for write, so we can write directly to socket, file descriptor, etc.

**Comment by ioquatix** [comment]
That makes sense.

The main use case for me would be streaming output via a HTTP socket. Keep in mind, with HTTP2, you can't directly output to a socket, because it needs additional framing. So, ideally, we'd have a way to "read" into a fixed size buffer the result of the image computation, write that to the http2 stream, and then once done, read another chunk of data.

**Comment by jcupitt** [comment]
There's a PR now to add true streaming:

https://github.com/libvips/libvips/pull/1443

Any feedback very welcome!
