### ISSUE TITLE
Support for animated webp processing

### ISSUE THREAD

**Issue by tomgallagher** [libvips/libvips#823]
Hi

I'm using Sharp for image processing and I'm getting this error

`Error: webp2vips: unable to read pixels VipsRegion: valid clipped to nothing`

The image is an animated webp - any chance there will be support for processing these at some stage?

Thanks. Relying on libvips a  lot and it's fantastic.

Tom

**Comment by jcupitt** [comment]
OK, let's add this as an enhancement.

**Comment by hbakhtiyor** [comment]
hi @jcupitt, any plans to implement it?

**Comment by jcupitt** [comment]
Hello, I don't have immediate plans to implement this myself, no. I'm very happy to accept a PR, of course.

**Comment by hbakhtiyor** [comment]
here's the [example](https://chromium.googlesource.com/webm/libwebp/+/master/examples/img2webp.c) of creating animated webp from png, jpeg, ... images, it's easy for you to implement it for few hours

**Comment by jcupitt** [comment]
I had a quick look: those functions are still very new and not widely available. For example, current Ubuntu does not include a recent enough version of libwebp for this.

I'd leave it another year or so to settle down.

**Comment by jcupitt** [comment]
Ooop, it's because they mangle function names in their headers. Looks like current Ubuntu does support this. I'll have a quick hack.

**Comment by jcupitt** [comment]
Here's a branch that adds webp write:

https://github.com/libvips/libvips/tree/add-webp-animated

It was more work than you'd think :( but it does seem to write animated webp. It needs count support adding, more testing, and animated webp read. 

```
$ vips copy horse.gif[n=-1] x.webp
```

Makes

http://www.rollthepotato.net/~john/x.webp

Google Chrome only, of course.

**Comment by hbakhtiyor** [comment]
wow, great patches, does it able to create from images too? currently which options available?
would be nice to add options like in the https://developers.google.com/speed/webp/docs/img2webp

**Comment by jcupitt** [comment]
Yes, you can make from any image source. It only supports delay at the moment, we'd need to add extra flags for other options.

**Comment by jcupitt** [comment]
OK, it all seems to work now, I've merged to master, this will be in libvips 8.8. 

Thanks for the suggestion!

**Comment by tomgallagher** [comment]
Thanks to your efforts, can libvips 8.8 now read animated webp as well? I wasn't sure.

**Comment by hbakhtiyor** [comment]
wow, thanks a lot for your efforts, any eta for releasing 8.8? still only delay option supported or did you add more options?

**Comment by jcupitt** [comment]
Save has some new options:

```
 * * @min_size: %gboolean, minimise size
 * * @kmin: %gint, minimum number of frames between keyframes
 * * @kmax: %gint, maximum number of frames between keyframes
```

Though I'm not sure how useful they are.  Load has two new options:

```
 * * @page: %gint, page (frame) to read
 * * @n: %gint, load this many pages
```

So you can select a range of frames to load. 

Some time next year for a formal release, but of course anyone can build 8.8 before then if they wish.

**Comment by hbakhtiyor** [comment]
how about some compression options?

> -mixed
    Mixed compression mode: optimize compression of the image by picking either lossy or lossless compression for each frame heuristically. This global option disables the local option -lossy and -lossless.

per-frame compression options
> -lossless, -lossy
    Compress the next image(s) using lossless or lossy compression mode. The default mode is lossless.
-q float
    Specify the compression factor between 0 and 100. The default is 75.
-m int
    Specify the compression method to use. This parameter controls the trade off between encoding speed and the compressed file size and quality. Possible values range from 0 to 6. Default value is 4.


> -loop int
    Specifies the number of times the animation should loop. Using 0 means 'loop indefinitely'.

per frame option
> -d int
    Specify the image duration in milliseconds.

does it currently support  creating from png, jpeg, ... images?

**Comment by jcupitt** [comment]
Try building it and experimenting with the options. It currently supports:

```
$ vips webpsave
save image to webp file
usage:
   webpsave in filename [--option-name option-value ...]
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   page-height  - Set page height for multipage save, input gint
			default: 0
			min: 0, max: 10000000
   Q            - Q factor, input gint
			default: 75
			min: 0, max: 100
   lossless     - enable lossless compression, input gboolean
			default: false
   preset       - Preset for lossy compression, input VipsForeignWebpPreset
			default: default
			allowed: default, picture, photo, drawing, icon, text
   smart-subsample - Enable high quality chroma subsampling, input gboolean
			default: false
   near-lossless - Enable preprocessing in lossless mode (uses Q), input gboolean
			default: false
   alpha-q      - Change alpha plane fidelity for lossy compression, input gint
			default: 100
			min: 0, max: 100
   strip        - Strip all metadata from image, input gboolean
			default: false
   background   - Background value, input VipsArrayDouble
operation flags: sequential nocache 
```

So most of what you list. `mixed` is not in there, but the others are. Yes, loop and delay are supported, though you can only set a single delay value for the whole animation. Yes, you can create from any source.

**Comment by adityapatadia** [comment]
Does it mean that GIF output support will be there in Nodejs Sharp?

**Comment by jcupitt** [comment]
libvips has had GIF save since 8.7, so September 2018. It should just work, hopefully.

**Comment by MananJethwani** [comment]
does sharp support now conversion of gif to animated webp? I wanted to use it in my project if it is done can anyone tell me how can i do it?

**Comment by jcupitt** [comment]
It should be possible, but ask on the sharp repo.

**Comment by lovell** [comment]
@MananJethwani Please see the "Convert an animated GIF to an animated WebP" example in the sharp documentation at https://sharp.pixelplumbing.com/api-constructor#examples
