### ISSUE TITLE
Things that still need fixing in magicksave

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#839]
git master 8.7 has a new magicksave operation which can write GIF images, among other things. It works, but has a few remaining issues that need fixing up:

- [x] Add configure options to control magick load and save.
- [x] Fix up error handling -- perhaps the `magick.c` wrappers should all add to the vips error log.
- [x] At least some monochrome animated GIFs still come out as red, perplexingly.
- [x] More metadata (properties) need supporting, eg. ICC profiles etc.
- [x] `magicksave` should register as a handler for any supported write formats.
- [x] Add tests to the test suite (in pyvips) and `make check`.
- [x] `magickload` could use the `magick.c` wrappers too.
- [x] Test with graphicsmagick.
- [x] Needs a C API wrapper, and the C++ interface needs regenerating.
- [x] Docs.
- [x] Test with at least short and float images. 
- [x] Test alpha handling.
- [x] `vipsthumbnail` will need to check for `page_height` rather than image height for many-page images.
- [ ] Fix DICOM save
- [ ] We need something like Q or rate for JP2 save
- [x] Rework to use a single call to `vips_sink()` to create the set of output images. At the moment we start a fresh pipeline for every page in the output.

Please add any more tasks you think of.

**Comment by kleisauke** [comment]
`VIPS_FORMAT_FLOAT` (range [-1, +1]) needs to be normalized to range [0, 1] (to make it compatible with `write->storageType = FloatPixel`). Currently this will output a wrong image:
```bash
vips linear lichtenstein.jpg test.v 1 200
vips magicksave test.v test.gif
```

**Comment by kleisauke** [comment]
Maybe we need to set `magick->map = g_strdup( "R" );` ([here](https://github.com/jcupitt/libvips/blob/e12df167e6dd021e11553e265ad6864cb9167511/libvips/foreign/magicksave.c#L259)) to `magick->map = g_strdup( "I" );` when processing an image tagged as `VIPS_INTERPRETATION_B_W`. See:

| *magick map value  | description |
| ------------- | ------------- |
| R  | red |
| G | green |
| B | blue |
| A | alpha (0 is transparent) |
| O | alpha (0 is opaque) |
| C | cyan |
| Y | yellow |
| M | magenta |
| K | black |
| I | intensity (for grayscale) |
| P | pad |

(not tested, but this might solve the monochrome animated GIF issue)

**Comment by kleisauke** [comment]
Also:
- How should `vipsthumbnail` handle animated GIFs (loaded with `[n=-1]`)? For example:
   ```
   vipsthumbnail animated.gif[n=-1] \
       --size "x200" \
       -o tn_%s.gif
   ```
   (should output an animated GIF with a height of 200 pixels)

- `vips copy` needs to fallback to `magicksave` when there is no dedicated saver found. See:
   ```
   vips copy animated.gif test.gif
   VipsForeignSave: "test.gif" is not a known file format
   ```
   (maybe `b = a.write_to_buffer(".gif")` should work too)

**Comment by jcupitt** [comment]
Oh, well done Kleis, yes, that fixes the monochrome problem. I've removed the colorspace set too, since it's no longer needed.

**Comment by jcupitt** [comment]
The TODO item *magicksave could register as a handler for any supported write formats* should fix your point about `vips copy`.

On `class_init`, magicksave should make a list of all supported file formats (no idea how to do this) and set that as a list of suffixes on the class, eg. `jpegsave` does this:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/jpegsave.c#L141

with this:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/vips2jpeg.c#L848

To register `.jpe`, `.jpg`, `.jpeg` as suffixes for jpeg save.

**Comment by jcupitt** [comment]
I added a TODO item for vipsthumbnail, good point.

**Comment by jcupitt** [comment]
... I think I'm out of time for now. I should be able to look at this again towards the end of the month.

**Comment by kleisauke** [comment]
No problem. Happy Christmas!

**Comment by dlemstra** [comment]
@kleisauke I is 'Index channel' not intensity! Setting the image to grayscale and then just setting the red channel solved the issue for me. Did this not fix it for you?

**Comment by jcupitt** [comment]
No, my monochrome GIFs came out red, unfortunately. Setting I and IA seemed to fix it. This works for at least PNG output too.

**Comment by dlemstra** [comment]
@jcupitt Can you share that image, so I can test it? 

> On class_init, magicksave should make a list of all supported file formats (no idea how to do this) 

I can open a new PR for this.

**Comment by jcupitt** [comment]
This seems to suggest I is intensity: https://www.imagemagick.org/api/constitute.php

> **map**
>     This string reflects the expected ordering of the pixel array. It can be any combination or order of R = red, G = green, B = blue, A = alpha (0 is transparent), O = opacity (0 is opaque), C = cyan, Y = yellow, M = magenta, K = black, I = intensity (for grayscale), P = pad. 
>

**Comment by dlemstra** [comment]
@jcupitt Sorry seems you are correct. The code used a value called `IndexQuantum` which made me think it was the index channel. But further down it calls `SetPixelGray` and that is what you would want.

I noticed that you have a todo for magickload also. Maybe we should put this in a separate issue? I think you can throw away a lot of the code and use `ExportImagePixels` instead.

**Comment by jcupitt** [comment]
@dlemstra it seems to write red for any one-band image. For example:

http://www.rollthepotato.net/~john/sarto_ng.v

A vanilla one-band, 8-bit image, with "R" and "RA" and 

```
        if( im->Bands < 3 )
                magick_set_image_colorspace( image, GRAYColorspace,
                        magick->exception );
```

just after `set_properties`, then:

```
$ vips magicksave sarto_ng.v x.png
```

will write a red PNG.

**Comment by jcupitt** [comment]
Re. `magickload`, sure let's fix that up too. 

I suppose the question would be how widely supported `ExportImagePixels` is. Will it work with graphicsmagic and older imagemagick? It needs to be able to build on RHEL5 (erk) with their magick package.

**Comment by jcupitt** [comment]
Sure, a PR for registering the supported suffixes would be great!

I guess one issue might be that it could badly hurt libvips startup time, since it would need to load all of the IM codecs on init, whereas now we just init libMagick on first use of magickload or magicksave. Perhaps just registering a set of useful, basic suffixes would be better. We'd probably need to benchmark.

**Comment by dlemstra** [comment]
@jcupitt You are probably right that you will get a performance penalty because ImageMagick will need to be initialized. It might be wiser to just start with "gif" as a format and then add other formats that are commonly used at a later moment? Your thoughts @kleisauke?

**Comment by kleisauke** [comment]
Commonly used formats that are supported by web browsers are only necessary for me. So it's fine to start with `.gif` as a supported suffix (that was the only format that I missed).

**Comment by coffeebite** [comment]
Does this mean libvips will support animated gifs?

**Comment by jcupitt** [comment]
Hello @coffeebite, yes, it should do.

**Comment by hbakhtiyor** [comment]
@jcupitt and so already release? does it support adding frame to gif and piping?

**Comment by jcupitt** [comment]
@hbakhtiyor no, not released yet. Yes, you can add frames to GIFs.

**Comment by gertcuykens** [comment]
Hi, I am trying to test magicksave but doesn't seem to be available in 8.7.0-rc1?
Maybe something wrong with my docker build?

```
bash-4.4# vips --version
vips-8.7.0-Wed Jul 25 12:06:44 UTC 2018
bash-4.4# vips magicksave original.jpg test.gif
vips: unknown action "magicksave"
bash-4.4#
```
```
FROM golang:alpine as base
ENV LIBVIPS_VERSION=8.7.0

# Here are only the packages for the release image!
RUN apk add --no-cache \
    zlib \
    libxml2 \
    libxslt \
    glib \
    libexif \
    lcms2 \
    fftw \
    ca-certificates \
    giflib \
    libpng \
    libwebp \
    orc \
    tiff \
    poppler-glib \
    librsvg \
    libmagic \
    exiftool

# These packages will be stripped from the release image!
RUN apk add --no-cache --virtual .build-dependencies \
    autoconf \
    automake \
    build-base \
    libtool \
    nasm \
    zlib-dev \
    libxml2-dev \
    libxslt-dev \
    glib-dev \
    libexif-dev \
    lcms2-dev \
    fftw-dev \
    giflib-dev \
    libpng-dev \
    libwebp-dev \
    orc-dev \
    tiff-dev \
    poppler-dev \
    librsvg-dev \
    git

# Install mozjpeg
RUN cd /tmp && \
    git clone git://github.com/mozilla/mozjpeg.git && \
    cd /tmp/mozjpeg && \
    git checkout ${MOZJPEG_VERSION} && \
    autoreconf -fiv && ./configure --prefix=/usr && make install -j$(nproc)

# Install libvips
RUN wget -O- https://github.com/jcupitt/libvips/releases/download/v${LIBVIPS_VERSION}-rc1/vips-${LIBVIPS_VERSION}.tar.gz | tar xzC /tmp && \
    cd /tmp/vips-${LIBVIPS_VERSION} && \
    ./configure --prefix=/usr \
                --without-python \
                --without-gsf \
                --enable-debug=no \
                --disable-dependency-tracking \
                --disable-static \
                --enable-silent-rules && \
    make -s install-strip -j$(nproc)

RUN rm -rf /tmp/vips-${LIBVIPS_VERSION} \
    && rm -rf /tmp/mozjpeg  \
    && rm -rf /var/cache/apk/*
```

**Comment by gertcuykens** [comment]
Doh! Your right confused libmagic with imagemagick sorry, its working now

```
bash-4.4# vips magicksave original.jpg test.gif
bash-4.4# file test.gif
test.gif: GIF image data, version 89a, 64 x 64
bash-4.4#
```

**Comment by ismikhail** [comment]
Hi,

Just wanted to clarify one point -- does the new magicksave support animated gifs? I'm experiencing some issues with it. Here is what I'm doing:

`$ vips magicksave animated.gif out1.gif`
Produces a non-animated gif.

`$ vipsthumbnail animated.gif[n=-1] -o out2.gif` 
Errors out with the following message:

```
vipsthumbnail: unable to thumbnail animated.gif[n=-1]
extract_area: bad extract area
magicksave: libMagick error:
```

Here is my setup
```
$ vips -v
vips-8.7.4-Fri Jan 18 12:51:47 UTC 2019

$convert -version 
Version: ImageMagick 7.0.8-27 Q16 x86_64 2019-02-12 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms ltdl lzma openexr png tiff webp xml zlib
```


Using `convert` on the animated gif works fine
`convert -resize 200 animated.gif out3.gif`

Link to my test image:
https://user-images.githubusercontent.com/2288662/52740679-69499b00-2f88-11e9-8c8c-3bcf14bf0dba.gif

**Comment by jcupitt** [comment]
Hello @ismikhail, yes, `thumbnail` doesn't work on multipage images, there's a checkbox for it on the list at the top of the issue. Hopefully in 8.8 (due real soon now).

**Comment by jcupitt** [comment]
All done and working, hopefully. Let's close.
