### ISSUE TITLE
Smartcrop: cropbox is misplaced

### ISSUE THREAD

**Issue by kleisauke** [libvips/libvips#879]
When using smartcrop, it looks like the cropbox is misplaced when changing the dimensions from 128x128 to 256x256. This is since libvips 8.5.7 (or higher). I couldn't reproduce it with 8.5.6.

Test image: https://t0.nl/skutsje.jpg
<sup>(See [wikipedia](https://en.wikipedia.org/wiki/Sk%C3%BBtsje) for an explanation of 'Skûtsje')</sup>

**libvips 8.5.7+**
```
vipsthumbnail -s 128 --smartcrop attention skutsje.jpg
```
![tn_skutsje](https://user-images.githubusercontent.com/12746591/36073849-530691c6-0f37-11e8-9422-47ea8b999994.jpg)

```
vipsthumbnail -s 256 --smartcrop attention skutsje.jpg
```
![tn_skutsje](https://user-images.githubusercontent.com/12746591/36073854-6255444c-0f37-11e8-86ca-5774c708a514.jpg)

**libvips 8.5.6**
```
vipsthumbnail -s 128 --smartcrop attention skutsje.jpg
```
![tn_skutsje](https://user-images.githubusercontent.com/12746591/36073887-fb1c20f6-0f37-11e8-88a9-1cdc524ce559.jpg)

```
vipsthumbnail -s 256 --smartcrop attention skutsje.jpg
```
![tn_skutsje](https://user-images.githubusercontent.com/12746591/36073891-0c37cc8c-0f38-11e8-9b83-d3443f240bf1.jpg)

This can be reproduced in the nip2 workspace, see:
[128x128](https://user-images.githubusercontent.com/12746591/36073902-3b16d098-0f38-11e8-9962-916db2671977.png) vs [256x256](https://user-images.githubusercontent.com/12746591/36073903-42562098-0f38-11e8-8f1b-1a4176db0b57.png)
<sup>from: https://github.com/jcupitt/libvips/issues/672#issuecomment-307174985</sup>

With the old nip2 workspace I got the expected result:
[128x128](https://user-images.githubusercontent.com/12746591/36073953-08708dea-0f39-11e8-8f43-eddda8ce9359.png) vs [256x256](https://user-images.githubusercontent.com/12746591/36073971-64533f90-0f39-11e8-8801-630583297cc6.png)
<sup>from: https://github.com/jcupitt/libvips/issues/619#issuecomment-287065036</sup>

**Comment by lovell** [comment]
Hi Kleis, it looks like the sunlight on the waves to the right of this image are generating too much noise with the edge detection mask.

Perhaps try reducing the [5x multiplier](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/smartcrop.c#L227) applied (step M9 in the nip2 workspace) to 4x/3x to see if that reduces the impact overall.

**Comment by kleisauke** [comment]
Hi Lovell, the sunlight on the waves does indeed generate too much noise. After applying 2x at step M9 (in the nip2 workspace) it's getting the correct cropbox. Thanks!

Instead of the laplacian edge detection we might use the canny edge detector for smartcrop. John has recently been working on [this](https://github.com/jcupitt/libvips/commits/add-canny).

**Comment by jcupitt** [comment]
Yes, could do, though canny is very slow compared to sobel :(

**Comment by lovell** [comment]
@kleisauke As you've got the nip2 workspace set up, are you able to experiment with adding a median filter (size 5 or 7) to remove some noise before and/or after the laplacian convolution to see if that helps.

**Comment by jcupitt** [comment]
Yes, the problem is the tiny edges in the waves. We want to look for significant edges, not small noise-like edges. 

I experimented with a sigma 2 gaussblur before the Laplacian, and that seemed to fix it too, and would be very quick.

**Comment by ThunderRoid** [comment]
Same problem

![image](https://user-images.githubusercontent.com/3328263/36140328-c24d2a4e-1055-11e8-847f-08d3b61dd353.png)

**Comment by jcupitt** [comment]
Hello @ThunderRoid, do you have a link to the original image? I can test it with the adjusted smartcrop.

**Comment by jcupitt** [comment]
Sorry, found a high-res version. I'll add it to the "test suite".

**Comment by jcupitt** [comment]
I updated the directory here:

http://www.rollthepotato.net/~john/smartcrop/

The nip2 workspace does the sigma 2 blur, and there's a simple script to run it (and vipsthumbnail) for all the images in the directory.

It's better, but it still misses on a couple of the images. `cat` was fine, but nip2 now shoots a bit to the left. With `quagga`, nip2 goes right a bit too far. ThunderRoid's image (`pexels`) centres on the flowers rather than the girl on every version. 

I'll try a sobel filter instead, and adjust the weights a bit.

**Comment by ThunderRoid** [comment]
@jcupitt original image https://static.pexels.com/photos/255349/pexels-photo-255349.jpeg

**Comment by xlotlu** [comment]
Algorithm improvements notwithstanding, I think the real issue here is the potential to get different selections at different resolutions.

@jcupitt  how about first rescaling to a given percentage, or min(percentage, arbitrary-limit), find the interesting area, and then apply the requested cropping to the original? This could even be done in 2 (or more) steps and average the results.

If this makes things seriously slower, it could be a different mode. You could call it "serious-attention". :)

**Comment by jcupitt** [comment]
I agree, there's another smartcrop issue where we're experimenting with resizing everything to 256 x 256 and then doing the search on that. Hopefully an 8.7 feature.

**Comment by uasan** [comment]
Perhaps someone will be interested, there was native support in JS (Chrome 70)
https://www.chromestatus.com/feature/4757990523535360

**Comment by kleisauke** [comment]
As can be seen in PR #1083, shrinking the image at the beginning of the attention-based smartcrop improves the performance and accuracy. I've also tested several images, and it seems that the cropbox remains in the same position, regardless of the given thumbnail size. :tada:

I'll close this issue, this improvement will be in libvips 8.8. For those who still experience issues with the attention-based smartcrop, please feel free to open a new issue.
