### ISSUE TITLE
VIPS for MRuby binding

### ISSUE THREAD

**Issue by proyb6** [libvips/libvips#900]
I've no experience in C programming and MRuby is common for embedded system which make sense to create a VIPS for MRuby. Could you advice the directions?

**Comment by jcupitt** [comment]
Hello @proyb6,

ruby-vips just uses ffi, so perhaps something like this would let ruby-vips run on mruby?

https://github.com/schmurfy/mruby-rubyffi-compat

Though it seems most people say you should use the C interface to mruby rather than ffi.

**Comment by jcupitt** [comment]
The Ruby libvips binding, for reference:

https://github.com/jcupitt/ruby-vips

**Comment by proyb6** [comment]
Thanks @jcupitt I will consider MRuby set of C for performance reason. Let hope there is an interest for someone to contribute.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
