### ISSUE TITLE
Option to set smallest size while resizing

### ISSUE THREAD

**Issue by aried3r** [libvips/libvips#912]
I'm currently studying the extensive libvips API but haven't found anything there or in the issues to achieve the following:

ImageMagick has a [_"geometry option flag '^' which is used to resize the image based on the smallest fitting dimension."_](https://www.imagemagick.org/Usage/resize/#fill), but I haven't found anything to do this with libvips directly, especially the ruby bindings without calculating the width/height myself (not that this would be a problem).  
I haven't found anything in [resample](https://jcupitt.github.io/libvips/API/current/libvips-resample.html), so I figured this might not be implemented.

Is this currently achievable using libvips? And if not, would it be an option to have it in future versions?

Admittedly I think this might be a rather obscure use case since images like panoramas ([example](https://commons.wikimedia.org/wiki/File:Clocktower_Panorama_20080622_20mb.jpg)) would result in very wide thumbnails. However in my case I have full control over the input images and no such thing can happen.

**Comment by aried3r** [comment]
Thanks :)

Is there any chance to have this option built into libvips or would that add too much complexity?

**Comment by jcupitt** [comment]
Let's tag this an an enhancement. It would be a simple addition to `vipsthumbnail.c` at least.
