### ISSUE TITLE
Using vips in Windows with python?

### ISSUE THREAD

**Issue by issawif** [libvips/libvips#92]
How do I install vips in Windows for use in python? I can't find useful instructions on installing it anywhere. Am I supposed to build vips? Or is there a Windows installer somewhere? At a loss...

What I've done: I've downloaded the VIPS package from http://www.vips.ecs.soton.ac.uk/supported/current/win32/, extracted it to my windows machine, added the bin directory to the windows path. I then tried to import the vipsCC package into python using the statement "from vipsCC import *" but I get the error that it cannot find the vipsCC module.

EDIT: I found a vipsCC package for windows online, copied the VIPSCC folder and put it into my PYTHONPATH. I am now able to "import vipsCC" using the python command prompt without issue, but running "from vipsCC import VImage" gives me the following error:

> > > import vipsCC
> > > from vipsCC import VImage
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\Lib\vipsCC\VImage.py", line 25, in <module>
> > >     vimagemodule = swig_import_helper()
> > >   File "C:\Python27\Lib\vipsCC\VImage.py", line 21, in swig_import_helper
> > >     _mod = imp.load_module('vimagemodule', fp, pathname, description)
> > > ImportError: DLL load failed: The specified module could not be found.

The "vimagemodule.pyd" file is located in the same folder as the VImage.py file. Any idea what I should be doing?

Is there another way I should be doing this? Completely lost. Please help!

Thanks.

**Comment by Jondeen** [comment]
What is status on Windows python support (with vips8)?

**Comment by jcupitt** [comment]
It's all done and working. Get the supported dev build for win:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/

Then you need a 64-bit python and a 64-bit gobject-introspection. Copy the vips.dll, vips.typelib and Vips.py into the appropriate directories and off you go.

The simplest way to get the goi bits is to use a gtk3 all-in-one:

https://sourceforge.net/projects/pygobjectwin32/files/

**Comment by jcupitt** [comment]
The official PyGObject page that links to that sourceforge download, if anyone needs some confidence in it:

https://wiki.gnome.org/action/show/Projects/PyGObject
