### ISSUE TITLE
Too many open() calls for same file

### ISSUE THREAD

**Issue by Alexander--** [libvips/libvips#921]
I have been investigating possible alternatives to ImageMagick and discovered your library. Thanks for creating such amazing software!

But it looks your converter program is a little less mature than ImageMagick's `convert`. When I traced it's system calls with strace (in preparation to sandboxing it with seccomp), I noticed, that it's single invocation results in 7 similar open() calls for the same image file:

````
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 3
[pid  4966] close(3)                    = 0
[pid  4966] openat(AT_FDCWD, "./output.jpeg", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
strace: Process 4967 attached
strace: Process 4968 attached
strace: Process 4969 attached
[pid  4969] openat(AT_FDCWD, "/home/user/5366", O_RDONLY) = 4
````

Counting preceding `access` call (why are you doing it btw?) and associated `close` calls, `vips` is using over 14 system calls to open a single image file. Is this expected behavior?

I am running `vips` like this:

````
LANG=C vips --vips-concurrency=1 resize /home/user/5366 ./output.jpeg 1
````

It is a self-build version from Arch Linux AUR. Output of `vips --version`:

````
vips-8.6.1-Wed Jan  3 08:34:04 UTC 2018
````

**Comment by Alexander--** [comment]
Passing `--vips-cache-max-files=2` does not change the observed behavior

**Comment by jcupitt** [comment]
Hello @Alexander--,

It's because of the way the `VipsForeignLoadFile` class `is_a` method works:

https://github.com/jcupitt/libvips/blob/master/libvips/include/vips/foreign.h#L172

libvips determines file type by calling `is_a` on every subclass of `VipsForeignLoadFile` in priority order, so each call has to open the file again. There's talk of reworking this to use an input stream type instead, but it's not happened yet.

I don't think there's a significant performance impact:

```
$ strace vips copy k2.jpg x.jpg |& grep open | wc
    891    9145   91898
$ strace vips convert k2.jpg x.jpg |& grep open | wc
    876    9056   90932
```

**Comment by jcupitt** [comment]
Ooops accidental close, sorry.

**Comment by Alexander--** [comment]
@jcupitt I am not sure about performance impact (post-Meltdown system calls are getting a lot more expensive FYI), but I am interested in implementing analog of ImageMagick's `fd:XX` source, and treating file handles as throwaway aliases to filenames does not bode well with that.

**Comment by jcupitt** [comment]
There was some discussion and a branch here which added true streams to libvips:

https://github.com/lovell/sharp/issues/30

But it was never merged, for various reasons. Something like that, but better, would probably be the way forward.

**Comment by Alexander--** [comment]
@jcupitt I don't care about "true streaming", only ability to read from inherited file descriptor.

**Comment by jcupitt** [comment]
It would be part of the same thing though. Anyway, it's being considered.

**Comment by Alexander--** [comment]
@jcupitt I took a quick  look at the `libvips` code, and things look pretty bad:

1. No consistent `FILE` usage, — there are multiple `openXXX` methods, some of which use `FILE`, while other use raw `int`. No wrappers for `close`.
2. You are doing seek-read/seek-write in several places instead of atomic pread/pwrite

If I my understanding is correct, the later problem is especially bad, because it means, that multiple threads can not safely decode from a file descriptor.

**Comment by jcupitt** [comment]
Suggestions and patches are always very welcome, of course.

1. `FILE` is only used internally, the public API is all `fd`. Perhaps libvips should move away from internal use of stdio as well. 

2. The read/seek/write stuff is always behind a mutex. Almost all image decode libraries (libtiff/libpng/libjpeg/cfitsio/etc.) are single-threaded, so libvips usually puts a `linecache` operator downstream from them to coordinate access. The native vips format does support multiple readers, but it makes a separate `window` object for each thread, so again there's no sharing.

**Comment by Alexander--** [comment]
@jcupitt 

> Perhaps libvips should move away from internal use of stdio as well.

It is probably better to improve internal adoption of `FILE` instead. Then you should be able to replace `fclose` with wrapper, that skips cosing for inherited descriptors.

> The read/seek/write stuff is always behind a mutex.

Yeah, that simplifies things a little. But the library still gets confused because it implicitly assumes, that offsets are reset after each read.

**Comment by jcupitt** [comment]
On 2., could you give an example of a scenario in which the library might get confused? As far as I know there are no races on read and seek, but of course I'm often wrong.

**Comment by Alexander--** [comment]
@jcupitt I have sent some changes, including a simple implementation for reading from (and writing to) an inherited file descriptor.

**Comment by jcupitt** [comment]
libvips 8.9 has an improvement here -- true streaming. It also automatically closes and reopens image descriptors when they are not being used. I'll close.

https://libvips.github.io/libvips/2019/11/29/True-streaming-for-libvips.html
