### ISSUE TITLE
CLI composite2 not blending

### ISSUE THREAD

**Issue by GDmac** [libvips/libvips#928]
Trying to composite2, any mode that i enter ``add`` ``colour-dodge`` results in the output image being the overlay. it is not blending. (MacOS Sierra, brew install vips)

`` vips composite2 input.jpg overlay.png output.jpg VIPS_BLEND_MODE_COLOUR_DODGE``

**Comment by jcupitt** [comment]
It should work. I tried here with the PNG dice image:

https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png

And the cramps image from libtiff:

![cramps](https://user-images.githubusercontent.com/580843/38419100-05035cc2-3997-11e8-9e24-fed51c5c27c1.png)

```
$ vips composite2 cramps.png PNG_transparency_demonstration_1.png x.jpg over
```

To get `x.jpg`:

![x](https://user-images.githubusercontent.com/580843/38419134-1f763f84-3997-11e8-9d2f-7177ab33bb9b.jpg)

`colour-dodge` gives strange results, as you'd expect:

```
$ vips composite2 cramps.png PNG_transparency_demonstration_1.png x.jpg colour-dodge
```

![x](https://user-images.githubusercontent.com/580843/38419165-47bfad0e-3997-11e8-8be6-23c1ce325017.jpg)

**Comment by jcupitt** [comment]
I'll try on my mac at home tonight.

**Comment by GDmac** [comment]
Thanks for the quick response. your example ``cramps dice output multiply`` (with transparent dice overlay) seems to work here.

The other way around does not seem to work. ``dice cramps output multiply`` results in only the cramps picture in output. Or am i missing something?

**Comment by GDmac** [comment]
but multiply should work either way around, shouldn't it. Or else it behaves quite different from multiply (or color-dodge) in photoshop.

**Comment by felixbuenemann** [comment]
@jcupitt I'm running into the same problem. Eg. doing an overlay with a solid blue layer in photoshop gives the underlying image a blueish tint, but with vips I get a solid blue output image instead.

Example:

Source Image: https://assets.imgix.net/examples/bluehat.jpg
Overlay: Solid Blue (0, 0, 255)

Code:

```python
from pyvips import Image
im = Image.new_from_file('bluehat.jpg')
overlay = Image.black(1, 1).add([0, 0, 255]).cast(im.format).embed(0, 0, im.width, im.height, extend='copy')
result = im.composite2(overlay, 'overlay')
result.write_to_file('result.jpg')
```

Expected Result:

https://assets.imgix.net/examples/bluehat.jpg?blend=0000FF&bm=overlay

Actual Result:

A solid blue image.

Tested with vips 8.7.0.

**Comment by jcupitt** [comment]
Yes, I think composite needs revising. It's stopping as soon as it sees a solid layer, but in fact layers below solid layers can have an effect with some operators. There are a couple of speedups we could do as well.

**Comment by felixbuenemann** [comment]
Can you point me at the line were it's skipping solid layers? – I quickly scanned composite.cpp, but didn't find that.

Btw. I noticed that in [libvips/conversion/composite.cpp:315](https://github.com/libvips/libvips/blob/master/libvips/conversion/composite.cpp#L315) `max_bands[0]` is set to 256 for B_W, shouldn't that be 255?

**Comment by jcupitt** [comment]
Two more ideas:

1. The x/y positioning of layers is crude: it simply expands smaller images to match the larger with extra black. We could instead keep track of the positions of subimages, then for each output region find the set of input images that the region touches and only generate those. This would give a very large speedup when compositing many small images (a common case).

2. Compositing is pixel-wise at the moment: for each output pixel, it scans the whole stack of input pixels, using a 4-ary float as the intermediate. This causes a lot of scattered reads for deep image stacks, which hurts cache locality and makes the pipeline bubble. Instead, we should have a whole line of float pels as the intermediate and composite in a series of passes moving up the image stack. This should give a nice speedup.

**Comment by felixbuenemann** [comment]
@jcupitt From a bit of quick testing it seems to work ok for me when I apply this patch:

```diff
diff --git a/libvips/conversion/composite.cpp b/libvips/conversion/composite.cpp
index ee085dd2..a197cc5f 100644
--- a/libvips/conversion/composite.cpp
+++ b/libvips/conversion/composite.cpp
@@ -1086,11 +1086,6 @@ vips_composite_base_build( VipsObject *object )
 				return( -1 );
 			g_object_unref( in[i] );
 			in[i] = x;
-
-			composite->n -= i;
-			in += i;
-
-			break;
 		}
 
 	/* Transform to compositing space. It defaults to sRGB or B_W, usually 
```

This way it adds the solid alpha to all images that are missing one, but doesn't skip compositing any of them.

**Comment by jcupitt** [comment]
Thanks @felixbuenemann ! 

I've made a branch containing your two improvements. I'll try to add mine.

**Comment by jcupitt** [comment]
Test program, adapted from Felix's example above:

```python
#!/usr/bin/python
  
import sys
from pyvips import Image

im = Image.new_from_file(sys.argv[1])
overlay = im.new_from_image([0, 0, 255])
result = im.composite2(overlay, 'overlay')
result.write_to_file(sys.argv[2])
```

**Comment by felixbuenemann** [comment]
Btw. I tested the following blend modes yesterday with just my patch from above, blending the same image as base and overlay and they all seemed fine compared to the same modes in a different tool:

* darken
* multiply
* colour-burn
* lighten
* screen
* colour-dodge
* overlay
* soft-light
* hard-light
* difference
* exclusion

**Comment by felixbuenemann** [comment]
John, do you think it would be much work to also support HSL based blend modes like color, hue, saturation, luminosity?

**Comment by felixbuenemann** [comment]
Yeah, I just used Img-IX, because it's simple to use and has pretty much all the blend modes including a description of what they should do:

https://docs.imgix.com/apis/url/blending/bm

I then just used an url like:

https://assets.imgix.net/examples/bluehat.jpg?blend=/examples/bluehat.jpg&bm=burn

and cycled though all the values for `bm`, comparing the Vips generated image with the web version.

**Comment by jcupitt** [comment]
I added scanline-based compositing. 

Benchmark:

```
$ mkdir sample
$ for i in {1..100}; do cp k2.jpg sample/$i.jpg; done
$ time vips composite "$(echo sample/*)" x.jpg 2
```

method | seconds real time laptop
----------- | ------------------
scanline-based compositing, vector path |  2.2
scanline, no vector | 4.8
pixel-based compositing, vector path | 2.4
pixel, no vector | 4.8

... rather unimpressive! I guess I'll leave it.

I'll try revising the layout next.

**Comment by jcupitt** [comment]
I removed the line-based compositing, it was extra complication for minimal gain.

I've added 1. above: only composite images touched by each request. If you're joining many small images, this gives a huge speedup.

Here's a benchmark: composite a large set of images together with feathered edges.

```python
#!/usr/bin/python3

import sys
import random
import pyvips

# sigma of the feather we add, and approximate radius in pixels
FEATHER_SIGMA = 4
FEATHER_WIDTH = 7

print("loading images ...")
images = [pyvips.Image.new_from_file(filename) for filename in sys.argv[2:]]

def make_white(width, height):
    white = pyvips.Image.black(width, height) + 255
    white = white.cast('uchar')

    return white

# make a one-band uchar image with a feathered edge
def soft_alpha(width, height):
    black = pyvips.Image.black(width, height) 
    white = make_white(width - 2 * FEATHER_WIDTH, 
                       height - 2 * FEATHER_WIDTH)
    mask = black.insert(white, FEATHER_WIDTH, FEATHER_WIDTH)
    alpha = mask.gaussblur(FEATHER_SIGMA, precision='integer')
    white = make_white(width - 4 * FEATHER_WIDTH, 
                       height - 4 * FEATHER_WIDTH) 
    alpha = alpha.insert(white, 2 * FEATHER_WIDTH, 2 * FEATHER_WIDTH)

    return alpha

# add a soft alpha and pad each image out to the final size
print("adding feather ...")
images = [image.bandjoin(soft_alpha(image.width, image.height))
          for image in images]

# composite all the images together at random positions
base = pyvips.Image.black(10000, 10000)
xes = [random.randint(0, base.width) for image in images]
yes = [random.randint(0, base.height) for image in images]
final = base.composite(images, 'over', x=xes, y=yes)

print("starting final write ...")
final.write_to_file(sys.argv[1])
```

Run on 100 images like this:

```
$ mkdir sample
$ for i in {1..100}; do cp ~/pics/k2.jpg sample/$i.jpg; done
$ time ./composeup.py x.jpg sample/*
loading images ...
adding feather ...
starting final write ...

real	0m18.227s
user	2m14.849s
sys	0m0.991s
```

New code:

```
$ time ./composeup.py x.jpg sample/*
loading images ...
adding feather ...
starting final write ...

real	0m3.865s
user	0m15.959s
sys	0m0.993s
```

At least 5x faster, in this case anyway.

All tests pass, and it fixes the original bug report, so I'll merge to master.

Thank you very much everyone, and thank you @GDmac for the original report! I've added all names to the credits.
